### ISSUE TITLE
The "Great Greylocke GasTech" Feature Request

### ISSUE THREAD

**Issue by aidancbrady** [aidancbrady/Mekanism#1037]
*Putting this here for my own reference. All credit goes to Greylocke.*

## Mek Gas Tech, part 1 - Hydrogen batteries

In reality, Hydrogen is an energy carrier -- a means of transporting the energy that was spent in separating it from a water molecule. I suggest a subtle shift in how Mekanism treats H2; not as a fuel, but as the "chemical battery" that it truly is.

This would be accomplished by doing the following:
1. Reduce the per-unit energy output of the Hydrogen Generator to be equal to the amount of energy required to produce hydrogen in the Electrolytic Separator. By burning H2, you’re getting back (almost) what you put into it.
2. Allow hydrogen to be stored in dynamic tanks (liquid H2 from the Rotary Condensentrator?).
3. Create a portable tank for compressed gas, something like a plastic Gas Canister for powering small devices and a metal Gas Cylinder for multi-bucket gas transportation.

Reducing the energy output will make hydrogen a less desirable mid-tier energy system, but should actually increase its overall utility as a kind of very flexible, portable, easily expandable energy storage system. Hydrogen will become a giant battery to be used during consumption spikes or for powering remote or temporary installations. In a Buildcraft- or IC2-based modpack, lava often fills this same role, but lava is so... prehistoric. We've climbed further up the tech tree, haven't we?

## Mekanism Gas Tech, part 2 Heat & Pressure

So what to do when Heat Generators and Windmills no longer keep the machines running? Biofuel! Crush plant matter into lovely gobs of material that can be burned as fuel in a Bio Generator. This will keep things running for a while, but soon even Biofuel cannot keep up. At this point in the Mekanism tech tree, we've likely got tanks of hydrogen and lots of excess Biofuel... I suggest Mekanism  add the potential to boost Bio Generator output to extend their useful life. Introducing… the Pressurized Reaction Chamber (PRC).

Pump hydrogen, Biofuel, and water into the new Pressurized Reaction Chamber, turn on the heat, and watch the internal pressure build. Some of the hydrogen and water is used to heat and pressurize the unit, and some is mixed with the Biofuel. Once the machine has hit critical pressure, the hydrogen, vaporized water and biofuel react to be become gaseous ethylene!

Ethylene is a combustible hydrocarbon with many uses, one of which is a fuel. Burning ethylene in a Bio Generator will produce double the power of biofuel (240J/t) , and burn for 200 seconds, 20 times longer than Biofuel alone! Once converted to a liquid in the Rotary Condensentrator, Ethylene could be able to fuel other mods’ engines, since it is a combustible hydrocarbon very much like Buildcraft’s Fuel or Forestry’s Ethanol. 500mB of liquid ethylene is produced for every 1000mB of gaseous ethylene (2:1 compression)

Pressurized Reaction Chamber (PRC)information:
* 3 inputs, with storage for each: gas, liquid, power
* 2 outputs, a liquid or gas and an item
* A “warmup” time before production can begin
* 100mB of ethylene takes 5 seconds to produce and requires 100mB of hydrogen, 10mB of water, and 2 Biofuel.
* 1 HDPE Pellet (see part 3, below) takes 3 seconds to produce. It requires 50mB of liquid ethylene and 10mB of oxygen.
* Because of its flexibility, it can be very useful for creating all kinds of new resources as the mod continues to grow.

## Mekanism Gas Tech, part 3. Ethylene Revolution

Ethylene makes a great fuel, but what else can you do with it?

* Growth Hormone: In the “real world,” Ethylene is used to ripen citrus, avocados, and other fruits. Use ethylene gas in a sprayer to speed up the growth of your crops! Spray a single plant with a (new) Mekanism Portable Sprayer, or put ethylene in a stationary Powered Sprayer and you’ll affect every plant in a large area around the sprayer.
* Flame Thrower: combine the Portable Sprayer or Powered Sprayer with a Blaze Rod and a flint and steel, and get a tool of flaming destruction!
* HDPE Pellets: Pump liquid ethylene and gaseous oxygen into a Pressurized Reaction Chamber, let it heat up, and you’ve successfully polymerized High Density Polyethylene (HDPE) pellets!
* HDPE Rod: 6 pellets creates a Rod, used as an ingredient in other recipes
* PlaSticks: Combine 2 HDPE Rods to get a PlaStick, a replacement for wooden sticks in recipes.
* PlaStick Torch: Combine 8 PlaSticks with a Blaze Powder to get 8 torches that auto-ignite. Or just hit them with a flint and steel to set them burning.
* HDPE Sheet: 8 pellets in a square creates an HDPE Sheet, and ingredient for other recipes.
* Gas Canister: 3 HDPE sheets creates 3 stackable disposable low-pressure gas cartridges that can be used to power small gas-driven devices. For higher capacity portable storage, something like a metal Gas Cylinder is more appropriate, as it could handle the pressures of a liquefied gas product.
* HDPE Blocks: 8 sheets of HDPE sheets makes 4 HDPE Blocks. HDPE Blocks are a lightweight but fairly durable building material with a slick, plastic, high-tech look.  Once the HDPE Blocks are constructed, they can be dyed by recrafting 4 blocks with one dye item. They have a few variations:
     - Slick Blocks: Run HDPE Blocks quickly through an energized smelter. The surface becomes extra smooth, and slippery like ice. Entities slide across it and spiders cannot climb it.
     - Glow Blocks: Combine 3 HDPE Blocks with 1 glowstone dust and get 3 Glow Blocks that subtly light the area. Glow Blocks have a light level of 10 – just enough to keep the monsters away.
     - Reinforced Blocks: Osmium dust added to 4 HDPE Blocks produces a less shiny but more durable construction material.
* Laminated Glass Panel:  surround 1 HDPE sheet with 8 panes of glass, get 4 panels of extra-durable Laminated Glass, highly resistant to blast damage. Glass Panels are thicker than Panes, thinner than blocks, and can be tinted by re-crafting 4 Panels with one dye.
* Plastic Barrier: 6 PlaSticks form an Plastic Barrier, a higher-tech version of the classic wooden fence.
* Glow Rods: 2 panes of glass, 1 Plastick and a glowstone dust makes 2 glowing tubes. Similar to modern fluorescent tubes, Glow Rods emit the same amount of light as a torch but look so much cooler. Recraft 4 Rods with a dye and add some color to your lighting fixures. They mount on a wall, ceiling or floor. Use a wrench to rotate the tube’s orientation. Rods placed next to each other will join.
* Glow Panels:  4 HDPE Sheets, 2 panes of glass and 2 glowstone dust make 2 brightly glowing panels that can be mounted to a wall or ceiling. Glow Panels produce a light level of 15 and can be colored by combining 4 Panels with a dye.
* High-Speed Logistic Pipe: Add 2HDPE Rods to 2 Steel and 1 Control Circuit, to create a higher-speed version of the basic Logistic Pipe
* Repelletizing: Drop an HDPE-based item or block into a Crusher, and get 75% of the HDPE pellets back. HDPE recycles! Go green!

## Mekanism Gas Tech, part 4. Top Tier Power

So what happens when ethylene-powered Bio Generators aren’t cutting it anymore? Got the resources? Step up to top-tier Mekanism power -- the Vaporized Gas Turbine (VGT). The VGT is actually an assembly of five machines:
* Compressor – starts up and shuts down the entire system. It must be fed power in order to complete a several minute spinup process. Blocks placed close to the front will prevent startup, since the intake airflow is restricted. During operation, a 5x3x5 area in front of the compressor must be kept clear of entities and items or they'll be ingested into the VGT. Sucking in item is a Bad Thing(tm)
* Fuel Vaporizer – is installed behind the Compressor. The Fuel Vaporizer equires inputs of power, water for coolant, and a fuel like ethylene (Mekanism), ethanol (Forestry) or fuel (Buildcraft). Once the VGT is running, if the Fuel Vaporizer runs out of power or water, a hard stop condition will shut down the system, likely damaging the turbine.
* Turbine Shroud - is installed behind the Vaporizer. The shroud is a fairly simple assembly of control circuits, steel chassis, and diamond bearings that houses the actual turbine item, which is placed into the Turbine Shroud GUI. The Turbine Fan is an osmium and steel beast that spins like crazy on precision diamond bearings. The turbine will wear out after approximately one year of minecraft days (about 5 RL days, if running 24/7). An abnormal system shutdown will cause damage to the turbine and may result in a catastrophic failure of the turbine, shroud, and other blocks nearby
* Exhaust Unit– placed directly behind the Turbine Shroud, the Exhaust unit is where the superheated, high-speed air exits the VGT. Like the Compressor up front, the area affected by the Exhaust Unit must be kept clear. Blocks placed close to the rear of the unit will prevent a startup or will cause a hard shutdown. Items or entities close to the Exhaust Unit will be pushed away. Optionally, water fed into the Exhaust Unit will create steam when the VGT is not idling. This steam could be fed to steam powered devices from other mods.
* Generator - converts the Turbine's mechanical force into power to feed your base. It connect to any side of the Compressor except the front or back. It can be connected to multiple VGT Compressors, allowing for very large, very powerful multi-turbine power systems.

VGT Power generation – when running at full power, the VGT consumes 100mB of ethylene every 3.3 seconds and generates 500kJ/s (25,000J/t) at the Generator. The VGT requires one minute (RL) to spin up to its “idle” speed of 10% power.  It has 5 levels of operation: 10%, 25%, 50%, 75%, 100%. This can be set manually, or an “auto” mode will adjust its output every 10 seconds to match the current energy requirements.

Steam Generation – If water is piped into the Exhaust Unit, it will create steam when not running at “idle” speed. The Exhaust Unit creates 10mB of steam per tick.

## Notes

* Volumetric units are based on the assumption that one Minecraft Bucket (1000mB) is similar to a typical European household bucket, which holds 10 liters.
* The design and energy output of the VGT is based on actual turbines used for power generation. Turbines are a very reliable, highly stable and low-maintenance method of converting mechanical force to electricity. Simple gas turbines typically have an efficiency of 33-45%. Using the exhaust heat to fuel steam co-generation often boosts efficiency in the 50% range.
* The fuel consumption of the VGT was based on fuel consumption data of Boeing 747-200 engines while cruising at 50% power, about 45MW across the four engines. It was then scaled down relative to the size of the VGT, a theoretical 750kW turbine with 40% energy conversion efficiency. I then adjusted the fuel rates to allow for the difference of the energy density of ethylene v. aviation jet fuel/kerosene. 
* I have all the conversions and consumptions keyed into an Excel spreadsheet. If you’d like to see the output increased or decreased, it is a simple matter to key in the desired electrical output and compute the new fuel rates.
* According to actual engineers at an ethylene cracking plant (the method most often used for creating polyethylene) it is a common and relatively simple process to get a 2:1 compression ratio when converting gaseous ethylene to liquid form. Liquid is the preferred state for bulk handling.
* The method of creating polyethylene was first discovered in the 1930s. The method involved putting ethylene under high pressure, in the presence of controlled amounts of oxygen. Today, this “high pressure” method is mostly used for low density polyethylene (LDPE), but is still used for some HDPE production. I chose this method because it was better suited for the Mincecraft environment since it uses resources that are already in-game.

**Comment by aidancbrady** [comment]
@Greylocke, can this be closed or is there anything else you hope to be implemented?

**Comment by aidancbrady** [comment]
Merging into #2217.

**Comment by hron84** [comment]
@aidancbrady sprayers will be implemented for using ethylene as a growth hormone? Or it is already implemented but with different name?

**Comment by Gryffen1971** [comment]
I have ran into a problem with the color of the current version of the Electrolytic Separator in Minecraft 1.10.2, The colors are all Orange, when on your Mekanism site it states that Hydrogen is pumped out the Blue side and Oxygen is pumped out the Red side. Since, all the ports are the same color it is a little difficult to determine which side to use. Can the Texture be updated to show the correct colors for the ports, please.
Thank you.

**Comment by Greylocke** [comment]
The  wiki hasn't been updated since the new textures were added.
When standing in front of the machine, hydrogen is on the left and oxygen is in the right, just like the GUI. If you forget... just open the GUI

**Comment by Gryffen1971** [comment]
@Greylocke , After sent in the issue that is what i did and BING! Now, everything is working great.
