### ISSUE TITLE
Factory Tabs render black

### ISSUE THREAD

**Issue by ktole1999** [aidancbrady/Mekanism#1162]
When placing any factory the gui tabs render black. You can still interact with the tabs. screen shot included. Regardless of the texture pack used. Mekanism-6.0.3.21
![image](https://f.cloud.github.com/assets/4421015/2357343/d9f8f816-a5fc-11e3-9575-65b2baa2390f.png)

**Comment by scifibob** [comment]
Why is this some other mods fault? I too have these black tabs, and I'm getting really tired of them.
It's been like that since.. well.. last year.
It's impossible to see any tab if there is no light source in the room.

**Comment by aidancbrady** [comment]
Yeah, honestly I have no clue how exactly this could be occurring.  I'll take another look later today.

**Comment by aidancbrady** [comment]
Should be fixed!
