### ISSUE TITLE
i think Mekanism world gen

### ISSUE THREAD

**Issue by Backdoor32** [aidancbrady/Mekanism#1463]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 06/07/14 20.13
Description: Ticking memory connection

java.lang.NullPointerException
	at net.minecraft.world.chunk.Chunk.func_76592_a(Chunk.java:758)
	at net.minecraft.world.World.func_72832_d(World.java:559)
	at net.minecraft.world.gen.feature.WorldGenMinable.func_76484_a(WorldGenMinable.java:82)
	at mekanism.common.OreHandler.generate(OreHandler.java:28)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:103)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:259)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1253)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:153)
	at net.minecraft.server.management.PlayerInstance.<init>(PlayerInstance.java:43)
	at net.minecraft.server.management.PlayerManager.func_72690_a(SourceFile:208)
	at net.minecraft.server.management.PlayerManager.func_72685_d(SourceFile:337)
	at net.minecraft.server.management.ServerConfigurationManager.func_72358_d(ServerConfigurationManager.java:282)
	at net.minecraft.network.NetServerHandler.func_72498_a(NetServerHandler.java:405)
	at net.minecraft.network.packet.Packet10Flying.func_73279_a(SourceFile:136)
	at net.minecraft.network.MemoryConnection.func_74428_b(MemoryConnection.java:89)
	at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:141)
	at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
	at net.minecraft.server.integrated.IntegratedServerListenThread.func_71747_b(IntegratedServerListenThread.java:109)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:691)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.chunk.Chunk.func_76592_a(Chunk.java:758)
	at net.minecraft.world.World.func_72832_d(World.java:559)
	at net.minecraft.world.gen.feature.WorldGenMinable.func_76484_a(WorldGenMinable.java:82)
	at mekanism.common.OreHandler.generate(OreHandler.java:28)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:103)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:259)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1253)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:153)
	at net.minecraft.server.management.PlayerInstance.<init>(PlayerInstance.java:43)
	at net.minecraft.server.management.PlayerManager.func_72690_a(SourceFile:208)
	at net.minecraft.server.management.PlayerManager.func_72685_d(SourceFile:337)
	at net.minecraft.server.management.ServerConfigurationManager.func_72358_d(ServerConfigurationManager.java:282)
	at net.minecraft.network.NetServerHandler.func_72498_a(NetServerHandler.java:405)
	at net.minecraft.network.packet.Packet10Flying.func_73279_a(SourceFile:136)
	at net.minecraft.network.MemoryConnection.func_74428_b(MemoryConnection.java:89)
	at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:141)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetServerHandler@17d89a64
Stacktrace:
	at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
	at net.minecraft.server.integrated.IntegratedServerListenThread.func_71747_b(IntegratedServerListenThread.java:109)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:691)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)

-- System Details --
Details:
	Minecraft Version: 1.6.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_05, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 432898024 bytes (412 MB) / 1377304576 bytes (1313 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G
	AABB Pool Size: 5341 (299096 bytes; 0 MB) allocated, 4686 (262416 bytes; 0 MB) used
	Suspicious classes: FML and Forge are installed
	IntCache: cache: 0, tcache: 0, allocated: 6, tallocated: 62
	FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 111 mods loaded, 111 mods active
	mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	FML{6.4.49.965} [Forge Mod Loader] (minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Forge{9.11.1.965} [Minecraft Forge] (minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	AppliedEnergistics-Core{rv14.finale3} [AppliedEnergistics Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	CodeChickenCore{0.9.0.9} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	NotEnoughItems{1.6.1.9} [Not Enough Items] (NotEnoughItems 1.6.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	PowerCrystalsCore{1.1.8} [PowerCrystals Core] (PowerCrystalsCore-1.1.8-10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	TConstruct-Preloader{0.0.1} [Tinkers Corestruct] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	OpenModsCore{@VERSION@} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	DamageIndicatorsMod{2.9.2.3} [Damage Indicators] (1.6.4 DamageIndicatorsv2.9.2.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	bspkrsCore{v5.3(1.6.4)} [bspkrsCore] ([1.6.4]bspkrsCorev5.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	mod_ReiMinimap{v3.4_01 [1.6.2]} [mod_ReiMinimap] ([1.6.4]ReiMinimap_v3.4_01.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	TreeCapitator{Forge 1.6.4.r09} [Treecapitator] ([1.6.4]TreeCapitator.Forge.1.6.4.r09.Universal.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BuildCraft|Core{4.2.2} [BuildCraft] (buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BuildCraft|Energy{4.2.2} [BC Energy] (buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	CoFHCore{2.0.0.5} [CoFH Core] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	UniversalElectricity{3.1.0} [Universal Electricity] (Universal-Electricity-3.1.0.114-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ForgeMultipart{1.0.1.268} [Forge Multipart] (ForgeMultipart-universal-1.6.4-1.0.1.268.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ThermalExpansion{3.0.0.7} [Thermal Expansion] (ThermalExpansion-3.0.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	IC2{2.0.397-experimental} [IndustrialCraft 2] (IC2-industrialcraft-2_2.0.397-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Forestry{2.3.1.2-agskies} [Forestry for Minecraft] (forestry-A-2.3.1.2-agskies.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Thaumcraft{4.1.0g} [Thaumcraft] (Thaumcraft4.1.0g.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Waila{1.5.2a} [Waila] (Waila_1.5.2a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	AdvancedThaumaturgy{0.0.28} [Advanced Thaumaturgy] (AdvancedThaumaturgy-1.6.4-0.0.28.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Mekanism{6.0.5} [Mekanism] (Mekanism-6.0.5.46.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	TConstruct{1.6.X_1.5.5.7} [Tinkers' Construct] (TConstruct_mc1.6.4_1.5.5.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	aobd{1.4.0} [Another One Bites The Dust] (AOBD v1.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	AppliedEnergistics{rv14.finale3} [Applied Energistics] (appeng-rv14-finale3-mc16x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Autoutils{1.0.1} [Autoutils] (autoutils-1.6.4-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Backpack{1.28.37} [Backpack] (backpack-1.28.37-1.6.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BuildCraft|Builders{4.2.2} [BC Builders] (buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BuildCraft|Factory{4.2.2} [BC Factory] (buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BuildCraft|Transport{4.2.2} [BC Transport] (buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BuildCraft|Silicon{4.2.2} [BC Silicon] (buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BCTools{1.4-a-17} [Buildcraft Tools] (bcTools-v1.4-a-17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BiblioCraft{1.5.5} [BiblioCraft] (BiblioCraft[v1.5.5].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BigReactors{0.3.3A} [Big Reactors] (BigReactors-0.3.3A.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Additional-Buildcraft-Objects{1.0.7.560} [Additional Buildcraft Objects] (buildcraft-Z-additional-buildcraft-objects-1.0.7.560.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	CarpentersBlocks{2.0.8} [Carpenter's Blocks] (Carpenter's Blocks v2.0.8 - MC 1.6+.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ChickenChunks{1.3.3.4} [ChickenChunks] (ChickenChunks 1.3.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	CoFHLoot{2.0.0.5} [CoFH Loot] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	CoFHMasquerade{2.0.0.5} [CoFH Masquerade] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	CoFHSocial{2.0.0.5} [CoFH Social] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	CoFHWorld{2.0.0.5} [CoFH World] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	CompactSolars{4.4.19.278} [Compact Solar Arrays] (compactsolars-universal-1.6.4-4.4.19.278.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	CompactWindmills{1.0.2.2} [CompactWindmills] (CompactWindmills+MC.1.6.4+v.1.0.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Tombenpotter's ElectricMagicTools{1.0.7} [Electric Magic Tools] (ElectricMagicTools-1.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	mymod{1.0} [ElectroCraft] (electrocraft-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	EnderIO{1.0.0} [Ender IO] (EnderIO-1.0.0.343.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	EnderStorage{1.4.3.6} [EnderStorage] (EnderStorage 1.4.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ExpChest{3.1.40.--} [Exp Chest] (Exp Chest v3.1.40.--.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ExtraUtilities{1.0.3c} [Extra Utilities] (extrautils-1.0.3c.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	FinderCompass{1.6.4} [Finder Compass] (FinderCompass_1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	HopperDuctMod{1.2.2} [Hopper Ducts] (HopperDuctsMod1.2.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	IC2NuclearControl{1.6.2c} [Nuclear Control] (IC2NuclearControl-1.6.2c-ic2-experimental.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ic2stuff{@VERSION@.@BUILD_NUMBER@} [IC2Stuff] (ic2stuff-1.9.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Taigore_InventorySaver{3.5} [Inventory Saver] (InventorySaver_-_3.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	inventorytweaks{1.56} [Inventory Tweaks] (InventoryTweaks-MC1.6.2-1.56-b77.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	IronChest{5.4.1.702} [Iron Chest] (ironchest-universal-1.6.4-5.4.1.702.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	JABBA{1.1.3} [JABBA] (JABBA_1.1.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	LogisticsPipes|Main{0.7.4.dev.217} [Logistics Pipes] (LogisticsPipes-MC1.6.4-0.7.4.dev.217.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Railcraft{8.4.0.0} [Railcraft] (Railcraft_1.6.4-8.4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ThaumicTinkerer{2.3-140} [Thaumic Tinkerer] (ThaumicTinkerer-2.3-140.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	MagicBees{2.1.13} [Magic Bees] (magicbees-2.1.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	MekanismGenerators{6.0.5} [MekanismGenerators] (MekanismGenerators-6.0.5.46.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	MekanismTools{6.0.5} [MekanismTools] (MekanismTools-6.0.5.46.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	MFFS{3.4.0} [Modular Force Field System] (MFFS_v3.4.0.233.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	minechem{5.05.71} [MineChem] (MineChem-5.0.5-RC1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	numina{0.1.2-55} [Numina] (Numina-1.6.2-0.1.2-55.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	powersuits{0.10.0-91} [MachineMuse's Modular Powersuits] (ModularPowersuits-1.6.4-0.10.0-91.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Mystcraft{0.10.13.01} [Mystcraft] (mystcraft-uni-1.6.4-0.10.13.01.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	NEIPlugins{1.1.0.6} [NEI Plugins] (NEI Plugins-1.1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	NEIAddons{1.10.5.70} [NEI Addons] (neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	NEIAddons|AE{1.10.5.70} [NEI Addons: Applied Energistics] (neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	NEIAddons|MiscPeripherals{1.10.5.70} [NEI Addons: Misc Peripherals] (neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	NEIAddons|ExtraBees{1.10.5.70} [NEI Addons: Extra Bees] (neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	NEIAddons|Forestry{1.10.5.70} [NEI Addons: Forestry] (neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	NEIAddons|CraftingTables{1.10.5.70} [NEI Addons: Crafting Tables] (neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	NEIAddons|ExNihilo{1.10.5.70} [NEI Addons: Ex Nihilo] (neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	notenoughkeys{0.0.4} [Not Enough Keys] (NotEnoughKeys-1.6.4-0.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	OpenMods{0.5} [OpenMods] (OpenModsLib-0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	OpenBlocks{1.2.8} [OpenBlocks] (OpenBlocks-1.2.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	fodc{1.4.3} [Ore Dictionary Converter] (Ore-Dictionary-Converter-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	iChunUtil{2.4.0} [iChunUtil] (util^iChunUtil2.4.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	PortalGun{2.0.2} [PortalGun] (PortalGun2.0.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	PowerConverters{1.6.4R2.3.2B1} [Power Converters] (PowerConverters-1.6.4-39.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ProjRed|Core{4.3.5.30} [ProjectRed] (projectRedBase-1.6.4-4.3.5.30.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ProjRed|Transportation{4.3.5.30} [ProjectRed-Transportation] (projectRedMechanical-BETA-1.6.4-4.3.5.30.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ProjRed|Exploration{4.3.5.30} [ProjectRed-Exploration] (projectRedWorld-1.6.4-4.3.5.30.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ProjRed|Compatibility{4.3.5.30} [ProjectRed-Compatibility] (projectRedCompat-1.6.4-4.3.5.30.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ProjRed|Integration{4.3.5.30} [ProjectRed-Integration] (projectRedIntegration-1.6.4-4.3.5.30.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ProjRed|Transmission{4.3.5.30} [ProjectRed-Transmission] (projectRedIntegration-1.6.4-4.3.5.30.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ProjRed|Illumination{4.3.5.30} [ProjectRed-Illumination] (projectRedLighting-1.6.4-4.3.5.30.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ProjRed|Expansion{4.3.5.30} [ProjectRed-Expansion] (projectRedMechanical-BETA-1.6.4-4.3.5.30.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	QuarryPlus{1.0.0} [QuarryPlus] (QuarryPlus-1.6.4-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Redstone Arsenal{1.0.0.0} [Redstone Arsenal] (RedstoneArsenal-1.0.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	remoteIO{@MAJOR@.@MINOR@.@REVIS@.${env.BUILD_NUMBER}} [Remote IO] (RemoteIO-1.8.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	mod_RottenFleshtoLeather{1.2} [mod_RottenFleshtoLeather] (RottenFleshSimplistic.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ThaumicExploration{0.5.1} [Thaumic Exploration] (Thaumic Exploration 0.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	TSteelworks{1.6.4-0.0.4.2-fix2} [Tinkers' Steelworks] (TSteelworks-mc1.6.4_0.0.4.2-fix2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	TiCTooltips{1.1.7} [TiC Tooltips] (TiCTooltips-mc1.6.4-1.1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	AS_UpdateCheck{1.1.1} [AtomicStryker Update Check Mod] (UpdateCheckerMod_1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	weaponmod{1.6.2 v1.13.6} [Balkon's WeaponMod] (WeaponMod.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	WirelessRedstoneCore{1.7.1.4} [Wireless Redstone] (WirelessRedstoneCore-Universal-v1.7.1.4_MC1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	WirelessCamouflager{1.0} [Wireless Redstone - Wireless Camouflager] (Wireless-Redstone-Camouflager-Universal-1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	WR-CBE|Core{1.4.0.7} [WR-CBE Core] (WR-CBE 1.4.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	WR-CBE|Addons{1.4.0.7} [WR-CBE Addons] (WR-CBE 1.4.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	WR-CBE|Logic{1.4.0.7} [WR-CBE Logic] (WR-CBE 1.4.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	YAFM{1.0.0} [Yet Another Food Mod] (yafm-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	McMultipart{1.0.1.268} [Minecraft Multipart Plugin] (ForgeMultipart-universal-1.6.4-1.0.1.268.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ForgeMicroblock{1.0.1.268} [Forge Microblocks] (ForgeMultipart-universal-1.6.4-1.0.1.268.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	TConstruct Environment: Sane and ready for action. Bugs may be reported.
	Ender-Quarry Relfection Code:: No problems here
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 2090 (117040 bytes; 0 MB) allocated, 1014 (56784 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Backdoor32'/1801750, l='Nuovo Mondo', x=-634,43, y=65,00, z=-508,03]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by aidancbrady** [comment]
This shouldn't happen anymore.
