### ISSUE TITLE
Sorter on empty locked JABBA dupe

### ISSUE THREAD

**Issue by BevoLJ** [aidancbrady/Mekanism#1659]
Using a sorter on a locked JABBA barrel it seems it will keep pulling even when empty.  Here is the issue with a lot more talk regarding it.  I'll let Prof know too.  :)

https://github.com/BevoTechPack/BevoTechPack/issues/130#issuecomment-51675874

**Comment by aidancbrady** [comment]
Shouldn't be an issue any longer!
