### ISSUE TITLE
Logistical Transporter/Sorter send entire item stacks to AE2 inscriber

### ISSUE THREAD

**Issue by GauHelldragon** [aidancbrady/Mekanism#1667]
The AE2 inscriber machine will only work when a single item is in any of its slots. A normal hopper will only put in 1 item at a time. The Logistical Transporters/Sorter will force stacks of items into this machine, causing it to no longer function.

**Comment by aidancbrady** [comment]
Huh, this is indeed strange. Looking for a fix...

**Comment by aidancbrady** [comment]
Fixed. I wasn't checking for strict inventory stack limits.
