### ISSUE TITLE
Right click on materials into machinery

### ISSUE THREAD

**Issue by ozzei** [aidancbrady/Mekanism#1678]
While in the enrichment chamber, sometimes if you right-click on your inventory, it won't visually head into the dark blue slot to be processed but it actually is there processing.  This might also happen with the energized smelter.

I'm running 1.7.10 build 1200
NEI latest version
Inventory Tweeks

**Comment by aidancbrady** [comment]
Is this still occurring?  I haven't tested SMP in a while.

**Comment by enterprise12nx** [comment]
ya this happens in SMP

**Comment by DiegoAngelus86** [comment]
Is this fixed in the latest release ?  Seems fixed for me after a quick test.

**Comment by aidancbrady** [comment]
I'm afraid I have no clue how to fix this. There's a good chance this is something on minecraft's end.
