### ISSUE TITLE
Right-click on GUI gauge chemical washer

### ISSUE THREAD

**Issue by robincnp** [aidancbrady/Mekanism#1777]
It happened after a crash that I suspect was caused by an incompatible ore passing through the 5X Ore processing, AKA Dissolution Chamber -> Chemical Washer -> Crystalizer.  After crashing when the ore slurry was processed once by the crystallizer Minecraft crashed.  I broke the Crystalizer, deleted it, then sreated a new one just to be safe.  Then I was checking the inventory on the other two machines to be sure they were empty, I right clicked on the Chemical Washer GUI, the side showing the clean ore slurry quantity, which also caused a crash.  I am going to try repeating the same for the washer, i.e. breaking it then deleting and making a new.

Here are the crash reports, bear with me today is the first time I have used PasteBin :-)

Crystalizer
http://pastebin.com/embed_js.php?i=YtJQaH6G

Chemical Washer
http://pastebin.com/embed_js.php?i=1p4guanZ

Using AOBD 2.2.3 Compatibility -> Aluminum
http://pastebin.com/embed_js.php?i=miARavKJ

On the Aluminum (AKA Aluminium) It looks like it made it past the Crystalizer, I discovered shards in the Purification Chamber after restarting and breaking/replacing the 5X machines.  Looks like the Crystalizer is a buggy bugger ;-).  I know that chain of machines tend to freak out if you try to give it ore before ALL the slurry is processed and gone.  I did have 1 left in the crystalizer but I cleared using the CLR button before passing the Aluminum in.

**Comment by aidancbrady** [comment]
This has been fixed for v8 :)
