### ISSUE TITLE
Suggestion for Robotics

### ISSUE THREAD

**Issue by Ikabodo** [aidancbrady/Mekanism#1788]
I've been thinking a lot about Mekanism lately, and what I really love about the mod is the feeling of actually working with building a FACTORY. Today I use MFR for many of these features, but I would prefer using this with a more mekanik feel. I never really liked having a simple block that just stands there and "magically" does something. It feels cheaty.... some how. 

I know other mods do things like what I am suggesting, but I think that mekanism could do it better. I figured I might just as well share it. :)

What I am suggesting is machines similar to this:
http://www.robots.com/images/DSC_0035%20reduced.jpg

They are in essence a combination of advanced piping and MFR-like machines. Intended to automate things in a factory-like setting. They should be modular, as to create a lot of creativity on how to create machines. 

Robot:
The idea is that the robot is a single-block machine with an automated arm on top of it, that can be switched out and told to do different things. It can be very advanced if you want it to, but you don't have to program it like in some other more advanced mods. You simply give it upgrades, and it will intelligently choose to do what it can. 

Basic robot:
A basic modular robot that you place on a base-block, it can grab items from any inventory next to it or the ground, and move it to another inventory. It is basically just a version of the pipe, but it has some advantages. Firstly, it can grab not only items from inventories, but blocks them the ground. So they can actually move a block from one place to another. Secondly it can be upgraded with speed and energy upgrades, and possibly other interesting upgrades. Such as crafting upgrades, sorting and/or automation. They have a limited range, and can only reach the eight blocks around the center block.

Advanced robot:
A more advanced version of the regular robot. And can be fitted with two different upgrades.

Elite robot:
Can be fitted with three different upgrades and can reach things one block away.

Ultimate robot: 
Can be fitted with four different upgrades and can reach things two block away, and can reach items above or below for even more advance creations.

Suggestion for automation upgrades:
Mechanical upgrade: The robot can use machines. (i.e. left/rightclick blocks) (not sure about this one, can be interpreted as "cheating")
Chainsaw upgrade (axe): The robot can chop down trees (combine it with another robot to pick up the blocks and put them in a chest)
Drill upgrade (pick): The robot is fitted with a drill and can crush ore/blocks and/or drill holes. Cannot effectively be used as a miner, because the robot is stationary, but some creative machines can be created.
Suction upgrade: The robot is fitted with pipes and can suck up liquid from one container and put it another, perhaps not useful for regular pumping, but can be used for advanced liquid/gas mechanics and to minimize use of complicated piping. 
Pressurized suction upgrade: The robot is fitted with tubes and can suck up gases from inventories and put them in others. 
Boltgun upgrade: The robot is fitted with a small boltgun and can attack nearby mobs. (not ranged, but they can be used to kill cows or animals in a pen for example)
Shears upgrade: The robot is fitted with shears, and can cut the the wool from sheep or feathers from chickens. 
Injection upgrade: The robot is fitted with a needle and can inject nearby players/mobs with potions/liquids. (For example the growth hormone idea, and you can automate breeding)
Crafting upgrade: The robot is fitted with claws and tools to craft. (the robot can be "learned" recipes, and then crafts them in crating tables. I.e. one robot puts the items in a crafting-bench, another robot "crafts" the item. Then a third robot picks it out and puts it in a chest (or the items are pulled in/out with pipes if you prefer the simple route.)
Planter upgrade: The robot is fitted with a planting-tool, and can plant seeds in fertile ground. 
Harvester upgrade: The robot is fitted with a harvester-tool, and an harvest crops around it. (Uses an advanced robot and combine it with the planter upgrade for an effective small harvest-field. 

Other possible upgrades:
Speed upgrade: The usual thing, simple speeds up the robot .
Energy upgrade: Same thing, makes it hold more energy.
Strength upgrade: Makes the robot hold more items at once.
Agility upgrade: Makes the robot hold several stacks of different items at once.
Logic upgrade: Makes the robot sense it's surrounding and take logical decisions. 

Final notes:
I know this suggestion might not hit home for all, and might not even fit the vision of the author. But then again, sharing is caring! This mod is amazing as it is, and I am thankful for the time you guys put into it all the time. 

This suggestion would work well with the multiblock-machines i suggested in a forum-thread.

**Comment by aidancbrady** [comment]
I like this - a lot.  Mekanism could really use some kind of auto-crafter, and I love how you made this follow the Mekanism style of "advanced but simple" machinery.  Looking into :)

**Comment by Archtikz** [comment]
On it!

**Comment by Archtikz** [comment]
@aidancbrady I know the kind OP said non-programmable.. but can we discuss that at a later date.

**Comment by Landrash** [comment]
A suggestion to extend this concept.
Accessories to the robots.
Crafting bench - Crafting table with a 3x3 inventory. Items can be placed in by one or more robots and crafted by a third robot. Basicly a simpler version of autocrafting.
Advanced crafting bench - Essentialy a special crafting table that can craft items that only can be made here. Some inspiration from pneumaticraft but extended would be nice. This could be extended to a whole toolchain inspired by realworld examples.

Chargingpad - A pad with the only function is to charge/discharge an item. Could output a redstone signal based on the charge level.

**Comment by aidancbrady** [comment]
I don't think we're gonna see this happening anytime soon, sadly. I need to narrow down the list of feature requests to what I can get finished for the next one or two major releases.
