### ISSUE TITLE
Logistical Transporter pulls items from input side

### ISSUE THREAD

**Issue by jznomoney** [aidancbrady/Mekanism#1836]
I am having issues with logistical transporter pulling items from the input slot of machines that are not mekanism.  Example thermal expansion I set it to pull items but it is pulling from the input slot as well as the output slot.  I have it connected to the right colored side of the machine that is for output.  Using ThermalExpansion-[1.7.10]4.0.0B5-13 and Mekanism-1.7.10-7.1.1.104.

**Comment by aidancbrady** [comment]
Transporters pull from whatever logical side they are attached to.  If that is the input side, it will remove items from the input side.
