### ISSUE TITLE
Energy cube causing massive FPS drops

### ISSUE THREAD

**Issue by Tajmoti** [aidancbrady/Mekanism#1851]
So, When I place a nearly full energy cube and it is only discharging (nothing charging it), my FPS drop from 200 to like 160-170. Ok. But when Some machines take energy out of it and my Gas burning and windmill generators are charging it quicker than it can discharge so It is at 31.99MJ all the time, my FPS drops massively, from 200FPS to 60-80FPS. It makes the game really stutter and it can be a pain for the slower PC users. Please could you look into this

**Comment by aidancbrady** [comment]
Closing this for now - though the energy cube may be slightly strenuous on rendering, it's hard to avoid with the rotating energy core in the center.  I'll consider adding a config to remove these kinds of animations in the future.
