### ISSUE TITLE
Paxel and pickaxe doesn't pickup blocks correctly

### ISSUE THREAD

**Issue by skaviouz** [aidancbrady/Mekanism#1868]
Paxels does not pickup vanilla anvils.
(**ItemMekanismPickaxe** untested bug, assumed to also have same aforementioned bug)
I'm sure there are other blocks that might have similar issues.
Tested this with diamond, iron, obsidian paxels.
1.7.10 - 7.1.0.91

**Comment by aidancbrady** [comment]
Fixed
