### ISSUE TITLE
PRC Needs a Dump button.

### ISSUE THREAD

**Issue by obuw** [aidancbrady/Mekanism#1870]
I have accidentally connected a hydrogen pipe to a PRC that had Liquid Ethylene, so now it has an invalid liquid / gas combination and no way to take them out.

 Would be nice if I could fix that with a dump button instead of having to throw it away and make a new one.

**Comment by aidancbrady** [comment]
No longer necessary in v8 with gauge droppers!

**Comment by ArkavianX** [comment]
Did this issue get resurrected in Skyblock 4?

**Comment by thiakil** [comment]
please explain?

**Comment by macintosh52** [comment]
I don't believe it was. As far as I know, gauge droppers are still fully functional in the latest sf4 update.
