### ISSUE TITLE
Logistical Sorter - sorting by mod-id

### ISSUE THREAD

**Issue by Komoden** [aidancbrady/Mekanism#1872]
This could maybe be 3 different issues, but i decided to just keep it under 1....

Issues:
Not all items get sorted correctly when sorted by mod-id (Logistical Transporter, Crowbars.. the list is long)
Not possible to enter mod-id's longer than 12 chars!!! (MekanismGenerators can't be sorted by your own mod!)
Not possible to enter mod-id's with special characters ( like "|" - this is not the capital i, but the vertical line used like to make the OR condition in some programming languages)

**Comment by aidancbrady** [comment]
Should be fixed!
