### ISSUE TITLE
Rotary Condensentrator far too slow

### ISSUE THREAD

**Issue by kotoroshinoto** [aidancbrady/Mekanism#1877]
it can't possibly keep up with the machines that consume gas if they've been speed-upgraded. (using large fluid storage as the holding tanks for gasses makes more sense than huge arrays of gas tanks. If we could get some dynamic gas-tanks that would be useful, but as of yet that isn't happening. 

it might be improved by massively paralellizing the machines, but thats a bit overkill. Either upgraded versions or slots for upgrades would make sense, probably makes some sense to do this for the gas pipes as well.

**Comment by aidancbrady** [comment]
In the process of adding upgrades for these now.

**Comment by aidancbrady** [comment]
Done!

**Comment by kotoroshinoto** [comment]
is there a beta or release candidate for testing that contains this yet or is it code-only at the moment?

**Comment by unpairedbracket** [comment]
It's only in code at the moment - we're close to finished though now and planning to get v8 out in the next couple of weeks, I think
