### ISSUE TITLE
Digital Miner unloading when changing dimensions

### ISSUE THREAD

**Issue by slawr34** [aidancbrady/Mekanism#1952]
Leaving a digital miner in the Nether or a Mystcraft dimension will result in the miner resetting when exiting that dimension - even with the presence of a chunkloader.

**Comment by aidancbrady** [comment]
This is actually not an issue - the reason why the miner resets is because the chunks it is trying to mine are actually unloaded.   The way to fix this is to introduce a chunkload upgrade for the miner, which I plan to do.
