### ISSUE TITLE
Universal Cable PULL mode, restricts throughput

### ISSUE THREAD

**Issue by aMUSiC** [aidancbrady/Mekanism#1987]
I was trying to pull energy out of an IC2 MFSU using Ultimate Universal Cables. I noticed that the transfer of energy was excruciatingly slow for such high-tier devices and cables, so I measured the cables and the throughput was at 100J/t . Adding more cables to the network did not change the throughput. It stayed at 100J/t.

Initially I thought that it might be the IC2/Mek combination that caused this, but then I tried the same setup using an Ultimate Energy Cube. If the cable attached to the cube is set to PULL mode, the throughput caps at 100J/t for the entire network. If it's in normal mode, then the throughput skyrockets to its normal values, and is additive the more cables you have in the network.

**Comment by aidancbrady** [comment]
This is technically intended - pull mode pulls a specific amount of energy from machinery per tick, but if the machine already emits energy, changing it to normal mode will allow for the complete throughput that the machine is outputting.
