### ISSUE TITLE
Mekanism Osmium tools crash in any and all Crafting tables!

### ISSUE THREAD

**Issue by Lanse505** [aidancbrady/Mekanism#1996]
Explained: 
When the osmium axe is on the crafting grid on the steve's workshop. It crashes and the axe is gone.
Crashed 2 times in a row and I think it is a bug.
Edit; Also, it is confirmed normal crafting table makes the same issue. 
Edit; More confirmed: osmium shovel crashed on crafting table. 

Test Enviroment: RR-3 Mainline Sandbox pack
Pastebin to Crashlog: 

Crashlog was when trying to put in on the workshop crafting grid but it reproduced on vanilla and other crafting grids aswell.

Vanilla Crafting Table Crashlog: http://pastebin.com/y5E2Zp7i
Steve's Workshop Crashlog: http://pastebin.com/Lf6DB9uv

Edit; Trying to get a hold of the crashing player at the current moment so i can get the rest of the crashlogs for you!

**Comment by aidancbrady** [comment]
Vazkii's Botanica issue.
