### ISSUE TITLE
Transporter performance issues.

### ISSUE THREAD

**Issue by ruifung** [aidancbrady/Mekanism#2002]
After a server has been running for a while, it's tick rate drops to ridiculously low rates. It is resolved by restarting the server. However, getting a jvisualvm sampler snapshot shows the following: 
![lowtps](https://cloud.githubusercontent.com/assets/1073945/5233965/997c77f2-77e5-11e4-84e9-83b5bd088983.png)

The full snapshot is here: 
https://dl.dropboxusercontent.com/u/23843338/meklag.nps

Version 7.1.1.127

**Comment by aidancbrady** [comment]
It is possible under certain conditions for transporters to accept items without places to go, most likely there was some form of machine backlog that allowed for them to keep accepting items.
