### ISSUE TITLE
NotEnoughKeys support.

### ISSUE THREAD

**Issue by ruifung** [aidancbrady/Mekanism#2009]
The not enough keys mod allows the use of modifier keys for keybinds, however that requires a mod to  support it.

https://github.com/mod-warriors/NotEnoughKeys/tree/dev/src/main/java/modwarriors/notenoughkeys/api

**Comment by aidancbrady** [comment]
To be honest I'd rather not integrate with yet another low-level API if I don't have to - Mekanism's integration is already extremely cluttered.
