### ISSUE TITLE
Pigmen with armor generating unusually high MS

### ISSUE THREAD

**Issue by PsionicArchon** [aidancbrady/Mekanism#2011]
As the title suggests, I've been noticing spiking MS in the Nether after placing an enderthermic pump. 

Some profiling with Opis revealed that individual pigmen were generating between 2000us and 4000us. I've resorted to placing Magnum Torches around any Nether chunk loaders in an attempt to curb the issue.

Every time I teleported to one of these pigmen they were wearing either glowstone or osmium armor. 

As a temporary fix, will setting the mob armor spawnrate to 0.00 prevent any mobs from spawning with mek armor?

Edit: I'm using a standard forge server running version 10.13.2.1236 of forge and 7.1.1.132 of Mekanism.

**Comment by aidancbrady** [comment]
Most likely this would occur with any armor on mobs - Mekanism just increases the amount.
