### ISSUE TITLE
Constant chunk loading / unloading lag. Might be related to Mekanism.

### ISSUE THREAD

**Issue by ruifung** [aidancbrady/Mekanism#2015]
https://github.com/Vazkii/Botania/issues/408

**Comment by Glassmaker** [comment]
We have the same issue, placed a chunkloader in a base with bunch of meka's machines, it looks like that solved the issue.

nps: http://www.mediafire.com/download/s5t9tloj9uf95fd/spike-12641-3358935556.nps

**Comment by aidancbrady** [comment]
@unpairedbracket is right, we can't really fix this.  I'd recommend using chunkloaders when possible.
