### ISSUE TITLE
Digital Miner Internal Inventory Lag

### ISSUE THREAD

**Issue by mrkirby153** [aidancbrady/Mekanism#2016]
When the internal inventory of the digital miner's inventory is full, it tends to cause the tile entity's update time to skyrocket.

Example:
![image](https://cloud.githubusercontent.com/assets/1572296/5329537/243447f8-7d68-11e4-9480-ef93f307a3db.png)

Opis is reporting that the tile entity is taking 68432.898 microseconds to update. 
![image](https://cloud.githubusercontent.com/assets/1572296/5329543/52a9f0e2-7d68-11e4-9532-142c29331381.png)

Upon clearing the inventory of the digital miner, the update time drops back down to normal.

**Comment by aidancbrady** [comment]
Shouldn't be occurring anymore
