### ISSUE TITLE
Gunpowder Recipe

### ISSUE THREAD

**Issue by whitestarx0312** [aidancbrady/Mekanism#2035]
Mekanism has a recipe that turns flint into gunpowder. One pulverizer can convert cobblestone -> sand -> gravel -> flint -> gunpowder. This is really overpowered when combined with something like Extra Utilities TNT generator or Botanias TNT flower. A config option to disable this recipe would be great! :)

**Comment by aidancbrady** [comment]
I kinda like this recipe.  You can use another mod to remove Mekanism's recipes.
