### ISSUE TITLE
Breaking Universal Cable attatched to Capacitor Bank crashes game/server

### ISSUE THREAD

**Issue by PsionicArchon** [aidancbrady/Mekanism#2037]
Crash report: http://pastebin.com/arwFueEZ

EnderIO: 1.7.10-2.2.4.309
Mekanism: 1.7.10-7.1.1.142

Can be reproduced by breaking a Universal Cable attached to a capacitor bank transmitting power. 

I have no other mods installed for the purpose of testing. 

My bug report on the EnderIO github: https://github.com/CrazyPants/EnderIO/issues/1433

**Comment by HadesDurin** [comment]
it is fixed in the newest version of ender io

**Comment by mrdeadlocked** [comment]
What version? I still have this issue on 317.

**Comment by HadesDurin** [comment]
update it to latest version and all is fine
is use 322
