### ISSUE TITLE
Heat Transmitters / Thermal physics system

### ISSUE THREAD

**Issue by unpairedbracket** [aidancbrady/Mekanism#2038]
Transmitters designed to transfer heat from producers (fusion reactor, maybe some generators) to consumers (steam boiler, stirling generator?). I have an idea for how to design the actual heat flow mechanic of the transmitters, giving each their own temperature and thus deviating slightly from the model we've been using for energy/fluid/gas transmission. We could also use a system of network-wide temperature but that would be less realistic, and potentially more confusing.

**Comment by aidancbrady** [comment]
@unpairedbracket, I'm going to be pushing v8.1.6 this week with a few fixes and v8.2 a bit further down the road with an asset redesign I've had in progress for a while.  Once I get the transmitter issue worked out I'm probably going to create the v9 branch and start work on some of the ideas I have listed in the milestone- I'm going to try to do another major release in the February/March timeframe.  

Are you going to have any time to work on this between then?  I totally understand if you're occupied with your studies, I'd be happy to finish it myself.  If not, though, awesome- I have a feeling you have a better idea of where you want this to go with your background :)

**Comment by unpairedbracket** [comment]
@aidancbrady sounds good - I've got a lab placement starting in a few weeks (working with massive lasers, which is exciting) so that will probably keep me fairly busy - I'll try and get as much as I can done before that starts, and I should have evenings and weekends free to do small amounts of work on Mek. After that I'll be a fair bit busier until around Christmas time but I'll try and help out over that holiday too.

The main things that I think need discussion, re: heat pipes are
* Is the simulation I've written efficient enough for production (needs profiling)? What do we do if it isn't?
* How deeply should it be integrated with the mod's other systems? Solar Evaporation Towers seem like a natural candidate, but how far should we go with using it in Generators? We could convert some of the burning generators to produce heat instead of electricity, but would that be annoying for early-game players? Would it be too similar to what IC2 is apparently doing recently?

I'll resume working on the heat system ASAP, in the meantime if anyone has anything to contribute on those concerns (or any others), do let me know

**Comment by unpairedbracket** [comment]
I've started working on this again, and I've added a block that acts as a fluid radiator, turning pools of lava/water into heat sinks/sources. Still needs work as could be unbalanced.

**Comment by Stekeblad** [comment]
Maybe doing some heat-thing with solar panels and salt?

**Comment by aidancbrady** [comment]
I'm closing this as the conductors are now just about polished.
