### ISSUE TITLE
Better configuration of sides for Energy/Fluid/Gas/Item transport

### ISSUE THREAD

**Issue by unpairedbracket** [aidancbrady/Mekanism#2040]
Enhance the current configuration system to allow setting sides for energy in/out, and assign sides to fluid or gas tanks as we currently can for items.

**Comment by aidancbrady** [comment]
Have some ideas for this.  I'm thinking of a specific interface with 4 different tabs for Items, Fluids, Gases and Energy (in that order), and a button linking to a separate interface that deals with transporter management.  Changing the milestone back to v8 as I have nothing better to do.

**Comment by aidancbrady** [comment]
Making progress on this, just finished the framework. Hopefully the GUI won't be too hard either.

**Comment by aidancbrady** [comment]
Just finished the new GUI - it looks pretty nice.  Everything is done except the actual implementation itself - I'll go ahead and implement this in all currently configurable machines and we can integrate with more later.

**Comment by aidancbrady** [comment]
Energy configuration is done! I'll polish off gas/fluid configuration tomorrow. Once again, we will spread this new system across more machines in either a minor (8.1/8.2) or major release.

**Comment by aidancbrady** [comment]
All done!  Implemented in all machines that currently implement ISideConfiguration.  Once we get dynamic models for the Energy Cube we can implement it there, too; @unpairedbracket, I'll leave the rest up to you.  Keep me up to date in #2042.
