### ISSUE TITLE
Item/Fluid/Gas/Energy teleportation

### ISSUE THREAD

**Issue by unpairedbracket** [aidancbrady/Mekanism#2041]
A block to teleport everything Mekanism can move around.
Currently working in v8:
* Fluid/gas/energy teleportation
* Frequencies

Needs work:
* Needs a model
* Item teleportation
* Frequency abilities based on upgrades.
* Would benefit from #2040

**Comment by aidancbrady** [comment]
Moving this back to v9

**Comment by kotoroshinoto** [comment]
I strongly recommend going similarly to the enderio transceiver UI, where instead of numbered channels you can name channels, and each type of thing that can be transferred has its own set of channels.

**Comment by Aulton** [comment]
Also, please make it secure by default. I hate how TE made theirs not secure by default, making it more effort than it's "worth" to secure the channel.

**Comment by Saizetsu** [comment]
Teleporting objects would be nice, I'm hoping for something that runs similar to EnderIO If you were to choose some basis for it at any rate.

**Comment by Mementh** [comment]
I love this idea.. but does it HAVE to be a block?  why not a upgrade to machines? 
you have a battery and product slots now.. 
just add a "wormhole" upgrade? 


LInk it either like tesseracts and channels or while in machine a new upgrade ( like thermal expansions augments do) to add a new tab

**Comment by mariodk** [comment]
we needing a tesseract but for Mekanism Gasses
right now im using Compact machines mod for that ( but they needing to be chunk loaded inside):
Nether star upgrade+quantum linked and x2 same size compact machine = same inventory for both
so kinda like a enderchest but for everything like mekanism Gasses

**Comment by XFactHD** [comment]
Compact Machines are chunkloading their inside automatically if you didn't change any config settings.

**Comment by aidancbrady** [comment]
This is now on the top of my to-do list.  These "Quantum Entangloporters" are going to use the framework of the teleporters and their frequencies to house their shared inventories, and accordingly will use an interface pretty much identical to that of the teleporter.  For managing input and output sides of different transmission types, I've strongly integrated with my side configuration framework.  I'll post back an update once they're complete!

**Comment by aidancbrady** [comment]
These are now done aside from the model.

**Comment by Mementh** [comment]
can a side input and export on the same side? 

the teleporters framework is a bit small to see things.. i hope its a bit bigger to look through and easier to set names rather then a frequency.
