### ISSUE TITLE
Dynamic models

### ISSUE THREAD

**Issue by unpairedbracket** [aidancbrady/Mekanism#2042]
Models that change based on side configuration. For example a pump that can display piping coming from certain sides, and cabling coming from others. Requires #2040, really.

**Comment by Archtikz** [comment]
That means more work for me!

**Comment by Greylocke** [comment]
What about using FMP mechanics to place the proper "connector" on the proper side? That way you can just make 4 standard connectors (power, fluid, item, gas) instead of doing so much re-modeling.

**Comment by unpairedbracket** [comment]
All of our FMP mechanics are currently using .obj files from models I made in Blender, so doing this would still require remodeling. I take from your recent issue, @Archtikz, that you're planning on remodeling using Blender anyway though. If you do I'll be able to do this almost trivially.

**Comment by aidancbrady** [comment]
This should no longer be necessary, as new block-based models will support nice visual connections.
