### ISSUE TITLE
Nuclear Fusion

### ISSUE THREAD

**Issue by unpairedbracket** [aidancbrady/Mekanism#2043]
An inertial-confinement nuclear fusion reactor. Produces enormous amounts of power, but required large investment to build and run.

Currently working:
* The reactor multiblock
* Reaction simulation
* Rendering the reaction
* Laser ignition and other laser things

Needs work:
* Production of Deuterium, Tritium and Hohlraums for the reaction

**Comment by aMUSiC** [comment]
Atomic Science (now part of Resonant induction) had some neat multiblock power sources. I always drooled over the particle accelerator.

**Comment by Barhandar** [comment]
And when Mystcraft adds Hazard Suit, it needs to be included as an exception which makes you not get dead and gone in a fusion reactor. Since hey, that thing in the original canon managed to keep a human alive for two seconds in a supernova.

**Comment by Stratos396** [comment]
@Barhandar I doubt anything on earth would be invented that is able to survive a supernova for..... a long time.
@unpairedbracket It should vaporize chickens, no drops

**Comment by Stratos396** [comment]
And mirror blocks to combine lasers?

**Comment by aidancbrady** [comment]
@unpairedbracket, we really need to get this thing finished for v8.  I have finished the complete production process of tritium and deuterium, everything is looking great.  A few things I noticed about the reactor itself:

* It looks like you had some content in the works for some kind of neutron flux radiation, are you planning on finishing that or is it just dead code?
* It requires way too much energy to ignite the reactor - with 100 creative energy cells all being amplified into the reactor, there still was not enough energy to ignite after 30 minutes.  Instead of 100 million being the ignition temp, scale it down to something reasonable like one or two million, otherwise there's not much of a reason to go into the struggle of making one
* We need to finalize Hohlraum production.  It seems to be made of lead, should I implement lead ore and come up with some kind of production process?  Also, is the Hohlraum ignition a one-time thing or do you need to continually feed those guys into the reactor to keep it stable?  Excuse my poor knowledge in nuclear mechanics.
* We need disaster mechanics, and I think you'd be best to do this!  Very bad things should happen if these are not maintained precisely.  They should be able to be maintained without any intervention after a while, but it should be hard to get them going smoothy at first.
* I'm not quite sure how energy production works.  Once the reactor ignites, is the production rate constant, or does it depend on certain variables?  If so, what are they?  On the stats panel, I see this:

(http://puu.sh/getZK/8cc4230b1d.png)

* I don't understand exactly what the difference is between "Active" and "Passive."  Also, I don't know about you, but 50 kj/t sounds like a lot less than I would expect from a structure of this size - if the output indeed is constant, I think we could scale it up a little!  1 MJ/t?  2 MJ/t?  This wouldn't even be a 12th of the predicted fusion output of ICF fusion that is 500 MW.

I'll be working on the EIM next, and I'm thinking of including 1 GJ, 8 GJ, 64 GJ and 512 GJ energy storage cells that will make up the structure.  This means that an 16x16x16 EIM will be able to store 1 PJ of energy - quite a lot!  It would take over 3 years for just one of those reactors outputting at 1 MJ/t to fill up a structure of that size.  On a more realistic scale, it would take 18 days for a 5x5x5 EIM to be filled up (considering it contains 512 GJ cells).

Are you planning on working on your heat system at all?  At this point, I think it may be best to hold off from the turbines and boilers until v9, and the heat transfer pipes could probably go with that.  If you have any free time (after finishing the reactor of course), you could work on the item/fluid/energy teleportation, but I think we should focus on getting a release out before April.

Let me know what you think!

**Comment by unpairedbracket** [comment]
The neutron capture stuff is still planned, but we can leave it for now and as it in a future update - it's more for additional interest than actually important for rector operation.

The energy taken to ignite can be varied by adjusting ignition temperature or heat capacities. I'd possibly recommend adjusting the heat capacities to reduce the laser energy needed, as reducing the burn temperature will also have an effect on power production, especially when we move to proper thermal energy systems. (Also, the best way is to use the redstone-triggered laser amplifiers to dump a load of energy in one pulse - constant heating will get you nowhere.)

The hohlraums I've read about are often tiny gold cylinders - that would probably be easier than adding a new metal? In real life inertial fusion goes once, then needs to be restarted and reignited. I've designed our system to be able to run continually once ignited, as long as temperature stays high enough to burn, so it's more user-friendly. If (and only if) it drops below burn temperature, a new hohlraum will be needed to reignite.

The nice thing about nuclear fusion is that it's so difficult to get it to happen at all that it needs to be run at maximum production - if something goes wrong, it won't get out of hand and melt down like fission, it'll just gradually stop. I'm sure I can make it go some damage while it's slowing down, though...

Power production scales with case temperature, which (in equilibrium) scales with plasma temperature. I've written the system so that plasma temperature effectively scales with fuel feed rate, so that would be the important factor in maintaining a reactor.

50kJ/t is 1MW, and our units are significantly bigger than real-life joules and watts (remember when Calclavia suddenly decided to make UE's units kJ? That was to be closer to realistic units). Active and passive behaviour is dependent on whether you're actively cooling the reactor with water or not - active cooling produces much less power but lots of steam for use with other mods like Big Reactors Turbines.

**Comment by aidancbrady** [comment]
Sounds great to me.  I'll work on Hohlraum production then right after I finish my current project.  I suppose I only one favor to ask then - lower the laser energy needed.

Would it be possible for you to add some special effects in the reactor core?  I'm about to add a sound effect for the reactor itself, but it would be pretty cool if we could see some form of indication of a reaction going on inside.

**Comment by unpairedbracket** [comment]
I've just looked and the reactor requires a pulse of 10GJ to ignite - that's 20 lasers charging 4 amplifiers for nearly an hour and a half. Excessive, I agree. There are 2 solutions to that, I reckon:
* Add a higher-powered laser (Our normal ones fire at 5kJ/t) that can charge the amplifiers faster.
* Reduce the heat capacity of plasma by a factor of 10 or so.

I think reducing by a factor of 10 (so it takes about 9 minutes of 5 lasers charging each of 4 amplifiers) should be a reasonable compromise?

**Comment by aidancbrady** [comment]
Sounds great.

I'm trying to find a good example of an effect the reactor can display when it is active, this is the closest I could find:

![Img]
(http://reactor.reed.edu/assets/images/reactor_images/cerenkov_mc2.jpg)

Some kind of glowing sphere that you can see on the inside.  Do you know how to render something like that?  If not, I've already spoken to Calclavia, and he said he'd be willing to write something.

When you have a chance, check out the droppers I just finished yesterday - our GUI element system made them easy and fun to implement.

**Comment by unpairedbracket** [comment]
I've so far been using a 3 modified (but similar) versions of the energy cube core model that pulse in size as well as rotating in a random-looking way.

![2015-02-27_15 26 14](https://cloud.githubusercontent.com/assets/543022/6416966/2110bb08-bea2-11e4-9d6c-ef529b864222.png)
![2015-02-27_15 26 16](https://cloud.githubusercontent.com/assets/543022/6416969/22cb2848-bea2-11e4-99f5-3b8e8052d7ed.png)
![2015-02-27_15 26 17](https://cloud.githubusercontent.com/assets/543022/6416971/248503b6-bea2-11e4-86ca-e3583acbfe4d.png)

They all pulse and rotate at slightly different rates, so it looks nice and random - it was the closest I was able to get to a kind of high-tech ball of burning gas while still looking cool. I'd be happy to replace it with something else though, if anyone else can do any better.

**Comment by aidancbrady** [comment]
Ah, that actually looks really good.  The only thing I would add is some kind of glowy-aura effect.

**Comment by unpairedbracket** [comment]
Hmm, I'll see what I can do... I'll have more time about 2 weeks from now, by the way - I'll be able to help more with finishing v8 then.

**Comment by Greylocke** [comment]
Hey all - I just had an interesting conversation in IRC regarding top-tier power solutions: how much power should they generate, how will it be used, complexity, destructive instability, some examples from other mods, and other stuff. Thought you might be interested. These guys (SeanWCom, Vaygrim, Vexatos, Xaw4) have been around a bit and have some pretty solid opinions.

https://dl.dropboxusercontent.com/u/27787851/TopTierPowerConvo_IRC.pdf

**Comment by aidancbrady** [comment]
Thanks @Greylocke, very helpful.  I may actually scale up the EIM storage a tad after reading that.

What's your input on a good output rate for the reactor?  I like super-large scale production, but I'd like to hear others' input.

**Comment by Greylocke** [comment]
From the IRC convo, I learned that players could easily find uses for 800kRF/t (2000kJ/t), and indeed other mods are currently doing this. So the reactor should be able to at least reach this output. IMO, the output should scale, maybe starting at roughly 20x the output of a gas-burning generator (gas gen is 400 J/t?). Increasing the size of the reactor (and increasing complexity) would increase the power output to as high as 1000kRF/t (2500kJ/t). Maybe there would be tiers of components required to reach the maximum output?

Also, players seem to really enjoy the "efficiency" game with these power systems. It is almost a mini-game, balancing the costs and benefits of the various factors that influence the output. Some common "power system" variables are: component quality (tier I reactor core v tier II core, etc), fuel type, coolant type, heat dynamics, spin-up cost (time and resources), system timing/synchronizing components, and co-generation (usually steam).

**Comment by unpairedbracket** [comment]
The approach I'm taking to the mechanics of this rector is pretty much "Write the equations and let them speak for themselves", which should hopefully give a good feel and level of tunability of different factors. Some things I've thought about adding are neutron capture (for added heat generation/not getting bathed in extreme neutron fluxes) and possibly different fuels with different thermal and fusion characteristics.

**Comment by aidancbrady** [comment]
@unpairedbracket, would it be possible to bump up the fusion reactor output perhaps by a scale of 10, to have a base 500,000 energy per fuel instead of 50,000? I just attempted myself but I'd rather let the actual physicist change the constants.

**Comment by unpairedbracket** [comment]
Yeah, making the Thermocouple more efficient is probably the best way.

I'll have a look at making different fuels with different parameters when I have some time. Another thing I just thought of, by the way - one interesting alternate fuel (as well as possibilities of D-D, D-He3, and P-B11) could be antimatter, and any normal gas. Antimatter would - of course - be extremely expensive to make and highly hazardous to transport and store, but would require no ignition energy and burn as fast as it was fed into the reactor, producing enormous amounts of energy as photons - no neutron flux or anything to worry about.

**Comment by unpairedbracket** [comment]
An interesting few paragraphs to read on the topic of catastrophic failures: http://en.wikipedia.org/wiki/Fusion_power#Accident_potential - the stuff in there about magnetic confinement isn't really relevant to us as we're using the inertial, laser-driven method, but general points about the fact that any equipment failure would cause the reaction to just stop are still valid.

I think the main hazard vector for ICF is probably neutron fluxes (NIF has a record of 300 trillion neutrons produced per second) that would cause the surrounding environment to become slowly radioactive. Not sure how easy it would be to simulate blocks becoming radioactive, but I'm sure that many neutrons would do horrible things to people...

**Comment by aidancbrady** [comment]
I think that neutron radiation would be our best bet - you should need some kind of fancy suit to do maintenance on the reactor.  Perhaps we can implement that when we finish neutron capture stuff.

I'm pretty happy with the current reactor numbers right now.  I'm going to do some more testing, but I feel like they fit well.  Do you have any ideas for hohlraum production?

**Comment by unpairedbracket** [comment]
Yeah - additionally, neutron flux being a safety issue would also be a nice way of adding complexity with different fuel mixes further down the line. We could have (for  example):

* Deuterium-Tritium: best fusion characteristics, but tritium is difficult to synthesize and it produces a lot of neutrons. Also produces He-4. Tritium can be produced from a working reactor by using neutron capture in lithium, or using slower methods that don't require a working reactor.

* Deuterium-Deuterium: fusion characteristics almost as good as D-T, but easier to synthesize as no Tritium is needed. Produces tritium, He-3, hydrogen and neutrons, at half the rate of D-T neutron and He-4 production, so causes less potential damage by neutrons.

* Proton-Boron-11: fusion characteristics comparatively really bad, but protons are just hydrogen gas and boron can be added as worldgen. Also almost entirely aneutronic, which removes the risks of neutron flux and makes it a lot easier to extract useful power from the reaction.

For hohlraum production I think something along the lines of using an enrichment chamber (or some other machine, or just a crafting recipe) on gold dust would yield an empty hohlraum - it would possibly implement IGasItem, so we could then enrich it with fuel (D-T gas, or whatever) to make it usable in the reactor. How does that sound?

**Comment by Greylocke** [comment]
for energy conversion, I've seen thermocouples mentioned, but are steam turbines off the table? It would be nice to have some options (again, back to playing the Efficiency Game). Thermocouples would require less infrastructure but also be less efficient and would output bursts of power; steam turbines would require more infrastructure, be more efficient, and smooth out your generation pulses.

**Comment by unpairedbracket** [comment]
Steam turbines are not at all off the table - in fact, the reactor can currently produce more steam than any mod I know of would know what to do with (tens of BR turbines, for instance) if fed with enough water (again, an enormous amount)

**Comment by aidancbrady** [comment]
Hohlraums are now complete, and therefore marking this issue as closed.  @unpairedbracket, once you're on your break, you can keep working on it - I'm planning on pushing the release once you've had a chance to look over everything.
