### ISSUE TITLE
Need some help with wiki editing

### ISSUE THREAD

**Issue by vixblu** [aidancbrady/Mekanism#2048]
I'd like to contribute by adding/updating wiki pages, but somehow I can't figure it out. I know it should be very easy, but I can't see where I can make changes to existing text. Is there a preference I should enable, or am I looking in the wrong direction?
All I can do is enter a summary, I don't see the existing text in some format > [screenshot](http://i.imgur.com/TOT9wj5.png).
Pleas help me to become less stupid :-)

**Comment by aidancbrady** [comment]
Make an account on the wiki and you should be able to edit pages :)

**Comment by vixblu** [comment]
Sorry for the late reaction, but I was a bit put off by your reply ;-) Of course I made an account before I tried to edit the wiki, see upper right corner of my screenshot ;-)
But never mind, I guess I'm too stupid to get this wiki, I'll continue to be helpful/contribute at the ftb reddit instead :-)
