### ISSUE TITLE
Mechanical pipes multipart bug?

### ISSUE THREAD

**Issue by ddos666TB** [aidancbrady/Mekanism#2053]
running 3 lines of mechanical pipes separated by FMP Cover with different liquids works like a charm until u break one of pipes... there happens a bit mess: liquids in neighbour pipes gets replaced by random from one of those 3

| - cover
M - milk
W - water
L - lava

|M|L|W|
|M|L|W|
|M|L|W|
|M|L|W|

becomes i.e when destroyed/replaced X-marked pipe
|L|L|L|
|L|L|L|
|L|X|L|
|L|L|L|

**Comment by unpairedbracket** [comment]
This should be fixed in 7.1.2 - I gave up waiting on the buildserver
