### ISSUE TITLE
Mechanical pipes redstone sensitivity bug

### ISSUE THREAD

**Issue by ddos666TB** [aidancbrady/Mekanism#2063]
1) Apply redstone signal to pipe
2) Save & reload world
3) Take off signal
4) Pipes wont reconnect
5) Apply again - no change
![2014-12-25_12 26 22](https://cloud.githubusercontent.com/assets/2174953/5561839/209f0b9c-8df7-11e4-840c-414f93c1bcd1.png)

**Comment by unpairedbracket** [comment]
Should be fixed in 7.1.2
https://github.com/aidancbrady/Mekanism/releases
