### ISSUE TITLE
digital mine replacement issue?

### ISSUE THREAD

**Issue by Dommain** [aidancbrady/Mekanism#2066]
When using digital miner to replace a "Inverted red lamp 1410:30" with "inverted blue lamp1410:27" for the Project Red-illumination mod. It places "blue lamp 1410:11" instead. I am using version of mechanism 7.1.0 and Project Red-illumination 4.5.0.50.Would this be fault of mechanism or Project Red-illumination?

**Comment by aidancbrady** [comment]
Most likely Project Red, considering other metadata-specific blocks replace just fine.
