### ISSUE TITLE
Plastic Block microblocks have no texture

### ISSUE THREAD

**Issue by Greylocke** [aidancbrady/Mekanism#2067]
I added the various plastic blocks to FMP's microblocks.cfg. It now makes the microblocks, but they have no texture, just an endless, deep blackness.

My config:
#Mekanism
"tile.GlowPlasticBlock":0-15
"tile.PlasticBlock":0-15
"tile.ReinforcedPlasticBlock":0-15
"tile.SlickPlasticBlock":0-15

Here's a screenshot of what it looks like when you place it. https://dl.dropboxusercontent.com/u/27787851/MekVoidTexturedMicroblocks.png
Note the absence of a texture, not a "missing texture" texture.

Mek .145, FMP .314, Forge 1277

**Comment by laz2727** [comment]
I think that they use some sort of magical rendering that fmp doesn't
support.

**Comment by unpairedbracket** [comment]
I think I added the plastic blocks to FMP in code, so you shouldn't need to in config. I think they worked when I first added them, but something might have broken since then.

**Comment by unpairedbracket** [comment]
Looking at the code, that's only the case in the v8 code. Hopefully it'll be in a releasable state soon.

**Comment by unpairedbracket** [comment]
The issue is that the render colour is based on metadata and the default microblock material doesn't use metadata to find colour, so it just gets black. That's what the black ones should look like, but all the colours look like it currently.
