### ISSUE TITLE
Electric Chest and Cardboard boxes

### ISSUE THREAD

**Issue by ZeekDaGeek** [aidancbrady/Mekanism#2068]
Forge version: 10.13.2.1277
Mod version: 7.1.1.144
Other mods: http://tinyurl.com/wwpack

Cardboard boxes can pick up Electric Chests by default. Seems like they shouldn't be able to while the chest is locked, but it would be nice to be able to move them while they're unlocked.

**Comment by aidancbrady** [comment]
Done!
