### ISSUE TITLE
Bin being destroyed when tool breaks

### ISSUE THREAD

**Issue by Zetharion** [aidancbrady/Mekanism#2070]
I had a bin that had a little over 3000 cobblestone in it.  I placed in on the ground, which happened to be bedrock, and used my osmium pickaxe to try and pick it up.  Well the pick was on its last leg and broke.  When the pick broke, the bin disappeared.  I tested with a wood pickaxe in creative and it did the same thing, so breaking a bin with a pick that has one use left will destroy the bin and its contents.  

Using the Karma modpack for 1.7.10 that has version 7.1.1.133

**Comment by aidancbrady** [comment]
This is indeed a frustrating issue.  Sadly, with the way my machines work, you're simply going to have to live with it - I handle block drops a bit differently, and it seems that tools that are on their last damage value don't call the method I use.
