### ISSUE TITLE
Atomic Disassembler MAJOR glitches

### ISSUE THREAD

**Issue by whitestarx0312** [aidancbrady/Mekanism#2071]
1)When holding the tools, NEI and your inventory can randomly glitch out and appear blank. Just try holding it and mining for 5 minutes.

2) When holding the tool on a multiplayer server, it creates visual images. Certain blocks will appear to be floating or disappear until relogging. (Most notably with Thaumcraft)

*I am using Optifine, however I can replicate these glitches without.

http://i.imgur.com/0CEhi6I.png
Look at the floating objects on the left of the picture.

**Comment by aidancbrady** [comment]
These three issues are linked to another mod's interaction - it is not directly my fault. I experience none of these issues with standalone Mekanism.
