### ISSUE TITLE
Iron and Gold Dust mekanisms IC2

### ISSUE THREAD

**Issue by HadesDurin** [aidancbrady/Mekanism#2074]
Hi my problem is when i make iron or gold dust using my ae2 system i sometimes get the ic2 dusts and sometimes got the mekanism dusts, both from a advanced crusher factory.
The recipe output only changes when i restart minecraft and i want to fix this.

using mekanism 7.1.1.144

Here are some pictures of my setup
![2015-01-06_10 46 55](https://cloud.githubusercontent.com/assets/5231067/5626945/407574b8-9592-11e4-8bdc-71f436fb57b4.png)
![2015-01-06_10 46 59](https://cloud.githubusercontent.com/assets/5231067/5626948/44219236-9592-11e4-816e-e6cd721a7cae.png)

**Comment by PsionicArchon** [comment]
I've been struggling with this issue as well. It's been clogging up my logistics system. 

A simple config option to lock the output of Mekanism machines would be adequate. Thermal Expansion offered a similar option to lock the output of its pulverizers back in 1.6.4.

**Comment by HadesDurin** [comment]
i think the problem is the ore dictionary of gold thingy, which decides what will be outputed and that changes nearly every restart of my game. So to have an fix output of dust will be fine, which means not to make it no longer ore dictionary...

**Comment by PsionicArchon** [comment]
As a temporary fix for this issue I recommend grabbing the Ore Dictionary Converter mod. It has an automatic ore converter block that allows you to set a target and convert anything that's piped into it into the set target. I've used this block to convert all dusts leaving my crushers into Mekanism dusts.

**Comment by HadesDurin** [comment]
thanks for the tip, will grab that mod

**Comment by UndeadZeratul** [comment]
If you have MFR, doesn't it also have a Unifier block?

**Comment by aidancbrady** [comment]
This is something that should be reported on MFR's end.
