### ISSUE TITLE
Elite Factory - Injecting allows water vapor to process Crystals into Shards

### ISSUE THREAD

**Issue by cathode** [aidancbrady/Mekanism#2075]
As the title says, the Chemical Injection Chamber in the Elite Factory form at least allows water vapor to be used to process Crystals into Shards when, as far as I know, only Hydrogen Chloride gas is supposed to be usable.

I had removed a factory block with shards and crystals in it's inventory (and empty of all gas) and placed it later, connected water vapor to it without realizing it had an inventory, then noticed that even though it was filling with water vapor, the crystals were still processing as normal.

EDIT: This happens with Mekanism 7.1.1.145.

**Comment by unpairedbracket** [comment]
I thought I'd fixed this, but maybe it was on the v8 branch and I forgot to apply it here.

**Comment by unpairedbracket** [comment]
Something weird seems to be going on with the buildserver, so there might not be a new build out for a while.
