### ISSUE TITLE
Cardboard Box's are kinda glitchy...

### ISSUE THREAD

**Issue by Shuudoushi** [aidancbrady/Mekanism#2076]
So, you can put a cardboard box on just about anything... Which is kinda great! Till you put one on a code door, then try to remove the box... That makes you crash... I know, I know, "Stack trace or GTFO!", well, here ya go! http://pastebin.com/XH7wZFms It would also seem that anytime you put a cardboard box on a chest with a mystcraft linked book in it, it spits out a copy of the book into the world and makes them dance around... No idea if the books work or not, haven't been brave enough to try to use them...

**Comment by aerialspring** [comment]
Came here to report the Mystcraft linking book dupe issue. Can confirm, they are complete duplicates. This works when placing the box on the book stands and the lecterns alike.

ALSO when placing the box on Extra Utils filing cabinet, when placing it back, sometimes it will turn into and advanced filing cabinet. No effect on the items within - they remain as they were. This is not consistent and no obvious trigger has been found yet.

**Comment by aidancbrady** [comment]
This is why the blacklist exists for server owners.

**Comment by aerialspring** [comment]
So the cardboard box will never be able to pick up the filing cabinet? It's an inventory that should be moveable. Otherwise, I guess we need to add this stuff to the blacklist every single time?

**Comment by aidancbrady** [comment]
The thing about the cardboard box is that it expects a placed block to behave like a normal block in its entirety.  Because some mods work around intended functionality in order to make special things happen, it's impossible to have the box work with every custom block.  I wish there was something I could do!

**Comment by aerialspring** [comment]
no worries! :P cardboard box has made pretty much all other inventory transport tools obsolete - we love it. thanks!

**Comment by Shuudoushi** [comment]
Can you look into the linking book thing a little and see if it's something you can fix?
