### ISSUE TITLE
Client crashing on recipe lookup

### ISSUE THREAD

**Issue by Arkandos** [aidancbrady/Mekanism#2077]
When trying to look up certain Mekanism recipes, the client crashes with the following report: http://pastebin.com/fVaA4Pwy

Using Mekanism 7.1.1.145 and NEI 1.0.4.83

**Comment by srs-bsns** [comment]
I had a similar issue about a week ago, but it was not with Mekanism.

The problem I had was introduced by the latest release of Jabba (v1.2.0, the same you are using) in combination with the latest (or possibly all) build of EnderStorage (v1.4.5.27, the same version you are using). It was causing the same type of crashing issue in NEI when looking up recipes and/or uses of items. The only solution I found was rolling back Jabba to v1.1.4.

You might first want to try rolling back Jabba and see if this is your issue as well.

(Note: NEI version didn't seem to matter)

**Comment by aidancbrady** [comment]
Even though the crash involves Mekanism, it doesn't necessarily mean Mekanism is the issue.  I've tested all NEI recipes with standalone Mekanism and they work fine.
