### ISSUE TITLE
[Request] MineTweaker Support

### ISSUE THREAD

**Issue by UndeadZeratul** [aidancbrady/Mekanism#2078]
I'm aware Modtweaker currently adds support, but @joshiejack has stopped working on it a while ago.  I don't know his policies on giving you the code to integrate it with Mekanism, but I saw Blood Magic now has the classes from ModTweaker, and they're credited to Josh. [Here's](https://github.com/joshiejack/ModTweaker/tree/master/src/main/java/modtweaker/mods/mekanism) the classes you'd need to implement in order to get it working.

**Comment by aidancbrady** [comment]
I'd rather not integrate with any other APIs right now, as I stated in an earlier issue, Mekanism's integration is already a mess.

**Comment by UndeadZeratul** [comment]
That's fair.  It also helps that sometime after I requested mods about MineTweaker support, Jaredlll08 took up the task of continuing modtweaker, over at [the new repo](https://github.com/jaredlll08/ModTweaker2).
