### ISSUE TITLE
Unable to interact with machine

### ISSUE THREAD

**Issue by Winters1299** [aidancbrady/Mekanism#2081]
As the title says, I am unable to interact with any Mek machine. I mean as in cannot interact with inventory and the machines slot(to place stuff) when its gui is open but it's okay when I exit the gui.(Inventory works fine) Ps, If there is any other info needed I'll be glad to provide 'em.

**Comment by Greylocke** [comment]
your description is really too vague to be actionable. Can you be more specific?  Maybe walk through the steps of what you're doing?

**Comment by Winters1299** [comment]
Okay, I interact with a machine(right click), its gui pops up and my invenyory alongside it. Then I am unable to move items from my inventory to the machine or even moving the items at all.

**Comment by Winters1299** [comment]
My Mek version is 7.1.0.88, Forge 10.13.2.1230, Minecraft 1.7.10. 
Alsoo I can't seem to use the latest version of Mek(7.1.1.127). Forge can't detect it but it can detect its addons.(Generators and Tools)

**Comment by unpairedbracket** [comment]
Latest is 7.1.1.145 - Take a look lower down the download page :)

**Comment by Winters1299** [comment]
o.0 thats funny. Anyway I'll try report back what happens. Thanks!
