### ISSUE TITLE
Suggestion for Digital Miner

### ISSUE THREAD

**Issue by Reddawg99** [aidancbrady/Mekanism#2085]
So the main issue we keep having with the Digital Miner is players putting the miner just outside another player's claimed area, setting it to max radius, and using the filter to mine up their machines, among other things. My idea is to have a setting of some sort that would completely disable the Digital Miner's filter settings, defaulting it to ore* only (Basically targetting anything in the oredict listed under the "ore" catagory). This would need to be a server-side setting to prevent these griefers from simply changing their local config to fix this. Would this be possible?

Reddawg99
SysAdmin
PlanetBeast

**Comment by laz2727** [comment]
Why would it mine out things in the first place? You're just asking for it
by allowing it to mine claimed areas.

2015-01-12 20:28 GMT+06:00 Reddawg99 <notifications@github.com>:

**Comment by Reddawg99** [comment]
There is no "allowing it to mine claimed areas". Claims cannot block the digital miner at all, except blocking the placement of it. So to protect everyone's home, they would need to claim a empty 2 chunk border around anything they build.

**Comment by mattymaats** [comment]
I second this as some sort of method to work against this would be great but it would be more useful if it checked for protected areas marked out by plugins, this would be quite a bit of extra work though :(

**Comment by Reddawg99** [comment]
Yeah, I think the easiest solution would just be a config option for server owners to set it to only mine anything with the "ore" tag in OreDict.

**Comment by aidancbrady** [comment]
To be honest, if your server is willing to allow the DM at all, it should allow it in its entirety.  If you'd rather not support the DM, use a recipe remover mod to kill the recipe - problem solved!
