### ISSUE TITLE
mekanism.common.item.ItemElectricBow Crash with other mods??

### ISSUE THREAD

**Issue by louisw22** [aidancbrady/Mekanism#2086]
http://pastebin.com/t6vuwvqJ

**Comment by Reddawg99** [comment]
This has been answered a dozen times already, and could have been easily found with a google search. This crash is a result of one or more mods using an outdated IC2 API. Download the latest IC2 api and install it, or delete the API from the mods that have it.

**Comment by louisw22** [comment]
Thanks so much
