### ISSUE TITLE
Computer Craft Teleporter

### ISSUE THREAD

**Issue by eqdanteon** [aidancbrady/Mekanism#2087]
I am having an issue using Mekanism-1.7.10-7.1.1.144 with ComputerCraft1.65.  I am using CC to set the code of the teleporter and than after a specified amount of time change the code back to a default for that location.  The issue is that when CC changes the code back to default the remote end is not dropping the link and still displays a useable portal that will take you to the original teleporter which no longer has a link.  Any assistance would be greatly appreciated.

Thanks,

**Comment by Reddawg99** [comment]
Have you checked that both ends of the portal are chunkloaded? Might try your program with someone at both ends so they can watch and see if it shuts down while loaded.

**Comment by eqdanteon** [comment]
Unfortunantly I had already moved these 2 teleporters to the spawn chuck and they were about 10 blocks away to eliminate chunk load as a possibility but thanks for the suggestion

**Comment by aidancbrady** [comment]
Already have a "Teleporter Bugs" issue open, if you find any additional issues put them there
