### ISSUE TITLE
Crash on opening

### ISSUE THREAD

**Issue by Cyb3rWarri0r8** [aidancbrady/Mekanism#2091]
Here is the crash log link:
http://paste.ee/p/N3F4L

**Comment by halvors** [comment]
You could try the latest version 7.1.2 (https://github.com/aidancbrady/Mekanism/releases). Also i would remove ResonantInduction as it's pretty alpha and unstable, and i've experienced that it messes up other mods.

**Comment by unpairedbracket** [comment]
Installing the latest ic2 api from http://ic2api.player.to:8080/job/IC2_experimental/ should fix this crash

**Comment by Cyb3rWarri0r8** [comment]
Adding ic2 worked! Thanks!
