### ISSUE TITLE
improvement of electrolytic separator/rotary condensentrator

### ISSUE THREAD

**Issue by HadesDurin** [aidancbrady/Mekanism#2092]
can you make it so that the ES (electrolytic separator) & RC (rotary condensentrator) will be upgrade able, to a tier 2 and tier 3 version?
that way you didn't need those batteries of machines to run a purification chamber or chemical injection chamber in tier 3 ore processing and tier 4

**Comment by aidancbrady** [comment]
Yes, these machines will be able to support upgrades in coming versions :)
