### ISSUE TITLE
Mekanism 7.1.2.155 Crash

### ISSUE THREAD

**Issue by Maxwelljones** [aidancbrady/Mekanism#2094]
SSP crash with the latest version.

Here's the crashlog.
http://pastebin.com/LGV03BWi

Dont know if this helps, but as soon as IC2 is together in the pack, it doesnt crash anymore.

**Comment by halvors** [comment]
That is because the IC2 api needs to be updated. If it works with IC2 simply add this to the mods folder or download the newest IC2 api.
