### ISSUE TITLE
Crashing when selecting Electric Chest

### ISSUE THREAD

**Issue by FagerholmS** [aidancbrady/Mekanism#2096]
Minecraft: 1.7.10 
Mekanism: 7.1.1.127

Game crashes when selecting electric chest on hotbar.
Crashlog here: http://pastebin.com/eY4j3pjv

E: Im using Hermitcraft Modsauce modpack.

**Comment by aidancbrady** [comment]
Not directly linked to Mekanism, most likely due to another mod's render handler.  I can't reproduce on my end.
