### ISSUE TITLE
Exception in server tick loop 7.1.2.157

### ISSUE THREAD

**Issue by mattymaats** [aidancbrady/Mekanism#2097]
Hi guys,

Updated to the latest version available and the server keeps crashing sometimes with the below crash report, any ideas? I'm guessing it has something to do with an API but not sure which one :(

http://pastebin.com/KQyHn4Zr

Using the following tech mods, if you need the full list let me know but it's quite long list xD

Mekanism-1.7.10-7.1.2.157 (all 3)
CoFHCore-[1.7.10]3.0.0B9-40
ThermalExpansion-[1.7.10]4.0.0B8-23
ThermalFoundation-[1.7.10]1.0.0RC1-13
MineFactoryReloaded-[1.7.10]2.8.0RC6-5
industrialcraft-2-2.2.656-experimental
EnderIO-1.7.10-2.2.6.317
buildcraft-6.3.1

Edit -
This is what came up in the console.

http://pastebin.com/1wVeGq7f

**Comment by mattymaats** [comment]
@CrazyPants 

I've checked through the mods and EnderIO-1.7.10-2.2.6.317 has mekanism API within it which is a slimmed down version that has a transmitter section so I've replaced it with the mekanism API, uploaded to the server which seems to have fixed the issue. I've tested by connecting up Mekanism energy cube -> EnderIO machines via uni cables and I've also connected a EnderIO Reservoir to a openblocks tank & EnderIO pressurized tank via Ult Mechanical pipes which all work.

**Comment by aidancbrady** [comment]
Should be fixed
