### ISSUE TITLE
[Feature Request] for Portable Teleporter

### ISSUE THREAD

**Issue by XeenRecoil** [aidancbrady/Mekanism#2100]
Hello;
First I would like to say thanks for a great mod, I can't imagine Minecraft without it.
Please consider upgrading the Portable Teleporter with memory presets.
I find myself wishing every time I use it that I didn't have to change the dial because I am constantly teleporting all over the place and changing the dial all the time is kind of frustrating, it's like having a old dial radio with no presets and every time you want to change the station you have to tune it in..
Having memory presets would greatly increase efficiency and reduce time fiddling with the personal teleporter.
Thank you for your consideration.

**Comment by aidancbrady** [comment]
I'm planning for a teleporter overhaul too, don't worry :)
