### ISSUE TITLE
Logistical Transporter Crashes without buildcraft mod

### ISSUE THREAD

**Issue by Rikonah** [aidancbrady/Mekanism#2102]
I have tested it over and over again, and perhaps it is just my computer, but for some reason when I try to place a Logistical Transporter to move items it crashes my game unless I have buildcraft as well.  The nearest thing I can figure out is the LT is relying on some code in buildcraft in order to work for me.

I didn't see this anywhere else so I made this as a new issue, not a big one, but a new one.  Didn't know if this was by design or a fluke that I happen to be "blessed" with...

**Comment by aidancbrady** [comment]
I'm able to place them just fine - most likely its an issue with your current mod list, perhaps a mod shipping with an outdated version of the API.

**Comment by unpairedbracket** [comment]
It looks like a crash with a pretty old version of Mekanism. Try updating if possible.
