### ISSUE TITLE
Chemical Dissolution Chamber output cap

### ISSUE THREAD

**Issue by Nonsanity** [aidancbrady/Mekanism#2103]
I've been working on a large-scale 5x setup (not because I need more resources, but because this sort of thing is fun to set up by the time that cost is no object) and I've run into a few snags. One may be an oversight: The Chemical Dissolution Chamber (CDC) can be given speed upgrades, but any more than two speed upgrades and it makes the slurry faster than it can export it into a gas-compatible pipe or tank.

I thought it first it might have been the Ender IO gas conduits I was using that was causing the speed cap, but attaching a tank directly to the machine made no difference in the drain speed. (Whereas putting the tank directly on the conduit drained it super fast.) So it looks like the CDC needs to have its drain speed increase along with its processing speed, or else all upgrades after the second fail to have any significant effect.

**Comment by aidancbrady** [comment]
Oh, you're right- the gas output is only 16 units per tick.  Bumped to 256 :)
