### ISSUE TITLE
Consequences of Slurry as a Gas

### ISSUE THREAD

**Issue by Nonsanity** [aidancbrady/Mekanism#2104]
I've been working on a large-scale 5x setup (not because I need more resources, but because this sort of thing is fun to set up by the time that cost is no object) and I've run into a few snags. This one is less of a bug and more of a playability issue.

Through testing, I found that one Chemical Dissolution Chamber (with two speed upgrades) outputs enough dirty slurry to keep 16 (un-upgradable) Washers continuously running. This, in turn, generates enough clean slurry to require more than one Crystallizer. (Two is more than enough.)

As long as only one ore type is put into the system, this arrangement works fine. However the last of the clean slurry to be produced from a given load of ore will likely be split between the two Crystallizers in a random fashion. Neither will have enough to generate a crystal, and so both will no longer function except if given more of the same ore slurry. If a different ore is put into the system, it all jams. It takes a manual dumping of the remainders to clear the jam.

Currently, there is no way to sort gasses, though there are (in a large pack such as Modsauce) many, many methods to sort liquids. If gasses could be sorted, or the slurry (which, with a reality check, would be called anything but a gas) could be handled as a liquid and sorted with existing technology, then the output from the washers could be piped into multiple different ore-dedicated Crystallizers. This would make fixing this issue merely a matter of applying the right modded items—the preferred way to challenge players in modded Minecraft.

Without the ability to sort slurry, the entire slurry segment of the processing chain has to be duplicated for each ore (of which there are around 20 or so in the Modsauce pack), including the CDC, 16 Washers, and 2 Crystallizers for each.

[On a related note, if only one Crystallizer is used, that exact slurry dregs problem goes away. However, new ores still can't be added to the CDC one after the other since this might put the multiple Washers into a race condition, with some Washers sill outputting the last ore and some outputting the new. This also results in the Crystallizer jamming with a little of one slurry type inside and a different slurry in the input pipe from one of the faster Washers. The Crystallizer has to be repeatedly drained before the system completely clears out the old ore. It is possible to automate around this issue with other mods (I did it with a pair of Steve's Factory Managers and some redstone signaling) but it is not for the faint of heart and it hamstrings the whole process with the long delays necessary to clear the pipes.]

Players I know that have been attempting to create a general-purpose 5x system in an automated way have encountered the same issues, and generally end up making massive parallel systems to try and overcome these shortcomings. Now, I love me a nice, complicated system, but these hack-arounds tend to go to server-lagging extremes and leave a bad taste in the mouth.

The only simple solutions I see are to turn slurries into liquids (and let other mods handle the sorting of large or complex systems) or allow a single Washer to match speeds with the CDC and Crystallizer (thereby keeping everything in sync and avoid multiple-machine race conditions).

[[[Not part of the issue, but not itself an issue: Is it intended that Sulfuric Acid can be used in the CDC? I find it a more complicated but FAR more compact option to salination towers, and I recommend it to all my players. I just hope it was intentional and not a bug that may go away in the future.]]]

**Comment by Nonsanity** [comment]
Here's a max-size (15x15x15) Compact Machine with the slurry portion of 5x processing for 8 different ores. (That's 128 washers.) There are two more Compact Machines just like this one. (Total: 384 Washers) Yay, pictures. :)

http://i.imgur.com/nGyt0XA.png

Thankfully, under normal conditions (one source of random incoming ore) only a few sections are active at a time.

**Comment by laz2727** [comment]
EIO has gas pipes iirc.

**Comment by Nonsanity** [comment]
@laz2727  yes. I'm using them in that picture. They don't offer sorting for gasses, however—if that's what you are suggesting.

**Comment by HadesDurin** [comment]
Maybe its possible to color gases in the output color slot and restrict color inputs on the maschines, but under the line you can't avoid to have a seperat maschine for each ore
and you have to not mix up the diffrent ore types
i once tried it to make it tier 5 ore processing, but the hugh batteries of condensers and seperators and other stuff makes it close to needless to have such an enormous amount of maschine to get one more out than in tier 4

**Comment by aidancbrady** [comment]
I will consider making some form of gas sorter block in the future, but aside from that, I like using pressurized tubes for slurry.  Larger-scale construction, like what Nonsanity posted, is exactly what I envisioned when making the 4x, 5x processing systems.
