### ISSUE TITLE
Electrolytic separator energy usage issue

### ISSUE THREAD

**Issue by Ceruleann** [aidancbrady/Mekanism#2105]
Hello,

I am playing this mod (and loving it), version 7.1.1.145, in the modpack "The 1.7.10 modpack":
http://www.technicpack.net/modpack/the-1710-pack.453902
I noticed after playing in a new world that the electrolytic separator has a base usage that is ten times what it should be. It requires 1600 RF/t when it should be 160 RF/t. From the Mekanism wiki page I could see that it should require 400 J/t. It looks like there are some mishaps in the energy values conversions. Since it was working in my previous worlds with this modpack I wonder if something has changed recently.

I tried to play with the configuration file of Mekanism, Mekanism.cfg but had little luck of getting anywhere:

# THIS DETERMINES ELECTROLYTIC SEPARATOR USAGE
D:HydrogenEnergyDensity=2000.0
D:JoulesToEU=10.0
D:JoulesToMJ=25.0
D:JoulesToRF=2.5
B:LogPackets=false
D:MJToJoules=0.04
B:MachineEffects=true
I:ObsidianTNTBlastRadius=12
I:ObsidianTNTDelay=100
I:OsmiumPerChunk=10
D:RFToJoules=0.4

Changing "D:JoulesToRF=2.5" had no effect. Changing "D:RFToJoules=0.4" to D:RFToJoules=4.0" bumped the energy usage to 16000 RF/t (no good), and changing the value to 0.4 reduced it to 160 RF/t (thought I got it). Unfortunately I could not see any difference in the way the machine was pumping the energy from the energy cells. Also I could see that the generators such as the gas burning generator were producing ten times less energy as well. From 800 RF/t to 80 RF/t...

Thanks for looking into this.

Ceruleann.

**Comment by grimallq** [comment]
Wiki is outdated and/or has errors. Electrolitic separator does use 4000 J/t.

Usage is determined by HydrogenEnergyDensity. The same settings determines how much power Gas-Burning generator produces from burning Hydrogen.

The other settings are conversion ratios for other mods power networks.

**Comment by Ceruleann** [comment]
If that is the case then it makes the cost of running the electrolytic separator way too high. I don't see how it is viable to feed 4000J/t or 1600 RF/t just to get from the tier 1 ore processing to the tier 2. I would have to use a Big Reactor or a fair size or a huge amount of other reactors. :(

**Comment by unpairedbracket** [comment]
Change HydrogenEnergyDensity to 200 - that's been the default for quite some time now. It'll reduce ES usage by a factor of 10.

**Comment by grimallq** [comment]
@Ceruleann You hook it up in a closed loop with a Gas-burning generator. It will then run at half speed indefinitely producing oxygen constantly. Granted all the Hydrogen will be burned.

Good enough in the for a start anyway.
