### ISSUE TITLE
"Silently" catching entity tracking error

### ISSUE THREAD

**Issue by jermangarc** [aidancbrady/Mekanism#2106]
Not sure if this is a Mekanism bug or EnderIO or something completely different. But I'm getting server console spam of the log below over and over again, causing server lag spikes every 10-15 sec's. Note: Server and client does NOT crash, but game is very laggy because of the spamming. Any input is appreciated. Thanks. 

https://github.com/CrazyPants/EnderIO/issues/1780

http://pastebin.com/PazfKitU

EnderIO-1.7.10-2.2.7.325
Mekanism-1.7.10-7.1.2.157

**Comment by Fogger** [comment]
I also have this issue in the Nether, and I found that it only occurs when EnderIO and ExU are present.
