### ISSUE TITLE
Mekanism 7.1.2.157 crash with NEI

### ISSUE THREAD

**Issue by ianc1215** [aidancbrady/Mekanism#2107]
I found an odd bug where right clicking on NEI items causes my client to crash.

My troubleshooting goes as such;

Remove problem mods (i.e. Optifine, fastcraft, any other performance mods) = Still crash
Remove other beta mods (I had the lastest AE2 rv2 beta installed) = Still crash
Try older forge = Still crash
Remove Meakanism = No crash

I realize its not much to go on but there is either a bug or conflict is my guess.

Here is the crash log if it helps at all.

http://pastebin.com/kGAfNpkS

**Comment by aidancbrady** [comment]
Doesn't look like a Mekanism issue to me, sorry.
