### ISSUE TITLE
Suggestion: Energy usage configs for each Factory Tier

### ISSUE THREAD

**Issue by ChatFawkes** [aidancbrady/Mekanism#2108]
Currently there is only 1 Factory energy usage for all factory types: ` D:FactoryUsage=`

This means no matter what factory you use the energy usage would be the same. This makes the lower tier factories rather useless mid-to-late-game because if you have enough materials you can just upgrade your factory to the next tier and the energy usage would be the same. It would be nice to have a separate energy usage config for each type of factory if that's possible to do.

**Comment by unpairedbracket** [comment]
Well the energy usage is multiplied by the number of things currently processing, so an Elite Factory at full capacity will use over twice as much power as a basic factory at full capacity. And if you put the materials in to upgrade to a higher-tier factory, it's kind of supposed to be better, isn't it? The way you describe factory progression is kind of how I'd always thought it should work?

**Comment by aidancbrady** [comment]
Yes, I agree, not entirely necessary.
