### ISSUE TITLE
Improvement of Oxygen in Purifier

### ISSUE THREAD

**Issue by HadesDurin** [aidancbrady/Mekanism#2109]
from what i have read so far now every item use a specifiac amount of oxygen to get processed
that way you get with higher tiers and upgrades in machines an exponential rise of needed oxygen per items processed.

i think the last days at work alot about that fact and try to find another way to make it "oxygen efficient" in higher tiers and with upgrades.
my idea bases on a oxygen consumption over time in a machine with higher values for higher tiers of machines and also an improvement for the seperators in diffrent tiers.

but step by step
what if an purification chamber (PC) tier 1 uses every second maybe 100 oxygen,
a tier 2 PC 300 oxygen per second, tier 3 PC 500 oxygen and last tier 4 700 oxygen?
when you upgrade the machines with speed upgrades the oxygen comsumption rate will be the same, which makes it more efficient for the items.

also i am meaning an extra slot for flint and energy upgrade in tier 3 and 4 is nedless and that way you can input in tier 4 an 8's slot for processing ores.
why doing so, well if you advance that far you should have enough recources that you didn't need the slots and if you need them, well than you have yourself overestimated.

another improvement is a introduction of tier 1, 2 and 3 of the seperator
which produce more oxygen per time and use more water to do so.
i come up with some numbers based on the PC values from above.
a tier 1 seperator produce 50 oxygen per second, tier 2 120 oxygen per second and tier 3 250 oxygen per second.
the values for hydrogen are double the values of oxygen, because of the H2O
and water used value is three times the oxygen value.
tier 1 uses 150 mb of water per second and produce 50 oxygen and 100 hydrogen
tier 2 uses 360 mb of water per second and produce 120 oxygen and 240 hydrogen
tier 3 uses 750 mb of water per second and produce 250 oxygen and 500 hydrogen.

all in all to run a tier 4 PC u need without the changes i mention above 3 tier 3 seperators to produce the needed oxygen with and extra 50 oxygen per second, with the changes you need 4 and produce enough oxygen to have 200 oxygen income per second which makes it in some way energy saving under the line.

at the end let me say you are free to comment and discuss and let me say with that changes it will be a way more easier to have tier 3 and higher.
english is not my motherlanguage so any mistakes inside this text are owned by the founder ;-)

**Comment by aidancbrady** [comment]
Thanks for the suggestions!  I like the ideas, but to be honest, it seems like a big hassle all in order to just  have better upgrade support - I don't want to have to deal with different tiers of each Mekanism machine!
