### ISSUE TITLE
[7.1.1.127]Mekanism Conflict with Galacticraft

### ISSUE THREAD

**Issue by beewyka819** [aidancbrady/Mekanism#2113]
I have posted this crash log on the minecraftforums and a user said that it seemed to be a conflict between galacticraft and an armor that my brother was wearing (glowstone chestplate and steel helmet/boots) which would cause a crash about 10-20 minutes after he joined the LAN world. Crash log: 
http://pastebin.com/VdUDd0tg

**Comment by aidancbrady** [comment]
Wouldn't be an issue on my end.
