### ISSUE TITLE
Crash Report: Mekanism dependent on Railcraft?

### ISSUE THREAD

**Issue by mcgraj3** [aidancbrady/Mekanism#2116]
I have a custom pack I have been tailoring to fit my needs. As I have found Railcraft to be pretty much useless to me (especially with duplicate ores with their own unique IDs), I pulled it before starting a new world. The crash report below is the result when starting up Minecraft. When I re-add Railcraft, no error. Any clue what's going on here? Thanks.

http://pastebin.com/zZ1jyBk5

**Comment by mcgraj3** [comment]
After further research, it seems that Mekanism actually requires the Buildcraft API to use pipes. Apparently Railcraft has this API built in, but it seems that is because CovertJaguar has his hands in it and so Mekanism can run fine without BC installed as long as Railcraft is there.

I wanted to depend on this mod (along with Thermal Expansion) as the heart and soul of my factory, but it seems I need to get Buildcraft installed. Not thrilled, but it beats Railcraft's stupid world gen.

**Comment by unpairedbracket** [comment]
Old Mekanism version, please update.

**Comment by grimallq** [comment]
@mcgraj3 You're using a very outdated version of Mekanism. That issue was fixed a long time ago.

**Comment by mcgraj3** [comment]
I just realized that there are newer versions on the download links on the wiki. I downloaded from the "Recommended downloads" buttons, but I neglected to see the newer versions below (my brain must have filtered them out as older versions). Please update those buttons. Thanks guys! :) :+1:
