### ISSUE TITLE
ic2 compatibility

### ISSUE THREAD

**Issue by anar4732** [aidancbrady/Mekanism#2117]
IC2 cables do not connect sometimes.

please...
you better translation into Turkish. (tr_TR)

**Comment by unpairedbracket** [comment]
That is not enough information to find an issue, let alone fix it.

We don't know Turkish, but if you do you're welcome to contribute translations.

**Comment by anar4732** [comment]
then I explain a little more.

Sometimes machines are not connected to the IC2 cable.
The improving my game when switched off.
picture:
- http://i.hizliresim.com/Xyqpzj.png
- http://i.hizliresim.com/QJYGdG.png

cubes. so there is no problem on machines with a complete block of the coating.
but mine are 5 times çıkarmakd penetrating machines problematic.

before starting output problematic machines.
- Chemical wahser
- R. condensentrat is
- Chemical Dissolution of the Chamber

Examples seamless machines.
- Enrichment Chamber
- Osmium Compressor
- Energized Smelter
------------------------------------------------------------------------
If you try to be good Turkish issues.
my favorite "galacitcraft" Turkish. You can get them to help.
---------------------------------------
This text was translated by google translation.
Original language: Turkish
thanks...

**Comment by aidancbrady** [comment]
This should now be fixed.
