### ISSUE TITLE
Suggestion for optional config option to turn off light level changes in machines

### ISSUE THREAD

**Issue by tivec** [aidancbrady/Mekanism#2118]
Whenever factories turn on and off (elite factories do this a lot unless you can feed lots of ore to them), they change light level between 10 and 14 (measured on block next to factory). This causes the lighting to be recalculated, resulting in a quite serious stuttering on some systems.

My suggestion would be a config option to disable the light level changes as this seems to sort out the issues. It goes for all machines and pipes doing the same.

While comparing mods is probably a bad idea since there might be different optimizations in place, EnderIO and ThermalExpansion both have on/off states for animations and particles, but cause nowhere near this kind of stuttering. They also do not change the light levels.

**Comment by Greylocke** [comment]
The ability to configure the ambient brightness of active machines has been a WIP since build 156. Thanks for the suggestion

**Comment by aidancbrady** [comment]
Implemented in v8
