### ISSUE TITLE
[Suggestion] Digital Miner.

### ISSUE THREAD

**Issue by Karmacopper** [aidancbrady/Mekanism#2119]
I am usually of the habit of travelling with my digital miner powering it with an energy cube. On returning to my base I empty it using an AE import bus strategically placed.

I would like to request that an energy cube inside the digital miner would be recharged if the digital miner is being fed power from an external source.

This effectively makes the energy cube an upgrade for the digital miner.

**Comment by aidancbrady** [comment]
This may come in a later version as an upgrade shipped with all machines - something where the machine's extra energy buffer can fill up a battery placed inside.  I'd rather not make this DM-specific.
