### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by chasterfield** [aidancbrady/Mekanism#2120]
hello guys, ,i have this weird problem , when I'm in creative mode i see all mekanism tools or machines everything  ,i can play with those and all that , but when I'm in survival mode i can't see or craft any of those tools , nothing at all no machines nothing , like the mod isn't there at all so ,.. maybe I'm missing something here if u guys have a solution for that  , that would be great, thanks a lot  :)

**Comment by aidancbrady** [comment]
Try using NEI, it can help show you the correct recipes.  Closing as this seems like a user-specific issue.

**Comment by chasterfield** [comment]
yeah NEI works just fine , i was using crafting guide .. thanks a lot :)
