### ISSUE TITLE
Odd Compatibility Issue

### ISSUE THREAD

**Issue by MikeArclight** [aidancbrady/Mekanism#2121]
My issue: Mekanism recipes do not show in CraftGuide - at all.

This issue is by no means game breaking; there's no crash report, game hiccups, or anything of that nature. What it is, is annoying. Of course, my intuition says this isn't the fault of the Mekanism mod team. So, you may ask, why am I bringing it to you? Well, here's the thing: you respond; and I see no indication that the author of CraftGuide has anything like this. I have sent a PM to Uristqwerty on MinecraftForum.net and will see what s/he has to say, if anything. 

To be honest, I'm not sure what can be done other than inform the respective mod teams of this issue; I just thought you should know of this.

**Comment by unpairedbracket** [comment]
It's likely to be because we use a custom recipe handler to allow fancy energy buffer stuff when crafting. I'm not sure that there's anything we can do to solve it.

**Comment by MikeArclight** [comment]
Thank you for the quick response. I am sorry to hear that there is nothing to be done, but glad that it isn't a fault or bug with Mekanism. As of this writing, the author of CraftGuide has not responded (it's been less than a day, so I'm not feeling ignored ... yet); and to be honest, the onus falls on him/her since the collation of recipes is the main goal of their mod. I will keep you informed if any new information should come my way.

**Comment by aidancbrady** [comment]
Thanks!w
