### ISSUE TITLE
A Few Crashes To Report

### ISSUE THREAD

**Issue by enterprise12nx** [aidancbrady/Mekanism#2122]
I have a modpack, on 1.7.10 using Mekanism-1.7.10-7.1.2.157
Im not sure when this errors occur, as my server is running 24/7 

Error #1: 
http://pastebin.com/FYgQv4Ea

Error #2:
http://pastebin.com/QcWTsWe8

I will report further errors i find, hope you can fix these!

**Comment by aidancbrady** [comment]
Already reported, thanks

**Comment by enterprise12nx** [comment]
thanks! hope its out soon, my server crashes every day because of it /=
What is causing it so maybe i can prevent it for now
