### ISSUE TITLE
ambient light config not working?

### ISSUE THREAD

**Issue by Greylocke** [aidancbrady/Mekanism#2124]
I know this feature has been bugging you, so I apologize for asking about it :)

The ambient configs don't seem to do anything. I've been playing with both the level adjustment and the ambient true/false, but neither seems to have any visible effect. Tried .157 and .160

Still WIP or am I just doing it wrong?

**Comment by aidancbrady** [comment]
Should be fixed for v8! The release will hopefully be soon - I'm switching back to Minecraft development and have a lot more freetime on my hands.

**Comment by halvors** [comment]
Will v8 be released for 1.7.10?
