### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by MrHelp** [aidancbrady/Mekanism#2127]
http://pastebin.com/RKd5L3b2
5 crash-reports in a day.

**Comment by unpairedbracket** [comment]
Oh dear, looks like my attempt at synchronizing the maps didn't work. I'll try again.

**Comment by unpairedbracket** [comment]
Was actually a different map crashing, my synchronization holds. Try build 162, I've made the relevant maps concurrent which will hopefully sidestep this issue altogether.

**Comment by unpairedbracket** [comment]
Make that 163 actually

**Comment by aidancbrady** [comment]
Sweet, closing for now
