### ISSUE TITLE
Mekanism will not work with forge versions > 1300

### ISSUE THREAD

**Issue by PaulGWebster** [aidancbrady/Mekanism#2132]
As subject,

**Comment by aidancbrady** [comment]
That's not good.

**Comment by aidancbrady** [comment]
Actually, that makes sense, considering Mekanism hasn't been released yet for 1.8.  Stay tuned for updates!

**Comment by halvors** [comment]
Well, there is a 1300 version for 1.7.10 as well, think it's that @PaulGWebster is refering to.
http://files.minecraftforge.net/minecraftforge/1.7.10

**Comment by aidancbrady** [comment]
In that case, I'll update once it becomes recommended.

**Comment by halvors** [comment]
Yeah i know. But really i think it's a backport for 1.7.10. It's atleast in a own branch. @PaulGWebster ypu should just grab 1291 :-)

**Comment by unpairedbracket** [comment]
It works fine for me on 1307, what's actually not working?
