### ISSUE TITLE
okay, i need help.

### ISSUE THREAD

**Issue by alienfreak101** [aidancbrady/Mekanism#2134]
okay, i never have done any of the config options in Mekanism because i never had to, but with 4x ore processing now, i want to have each machine sitting next to each other (factorys) so, i dont know how the hell the color code thing works and im going to be here for a week trying to figure it out. lol
the wiki didn't help me much, just made me more confused >.<.

**Comment by grimallq** [comment]
Take a good look at the machine's normal GUI. Each slot is colored ...
