### ISSUE TITLE
Rendering Issue with Colored Lights Core

### ISSUE THREAD

**Issue by shadowfacts** [aidancbrady/Mekanism#2136]
When using [Colored Lights Core][clc] there is a rendering issue with Wind Turbines. They become unusually bright.

![2015-02-17_16 10 58](https://cloud.githubusercontent.com/assets/7091588/6237357/3213ab52-b6c0-11e4-9058-2a15046f7168.png)

**Comment by jburrows82** [comment]
Secondary bonus of a free light source, score!

**Comment by aidancbrady** [comment]
Not really my issue, I render my wind turbines the same as any model. I'd consider that an issue with the colored lights.
