### ISSUE TITLE
Placing Logistical Sorter Crashes Game

### ISSUE THREAD

**Issue by mcgraj3** [aidancbrady/Mekanism#2138]
I am having an issue with the Logistical Sorter. Each time I place one, the game crashes. When I come back to the game, it is where I placed it, but the LS has duped itself (one placed, one in inventory). Any idea what's going on here? Thanks. :)

Crash report: http://pastebin.com/DN1bMDAf

(I was using 7.1.2.157 when this happened, updated to .167, still happens.)

**Comment by mcgraj3** [comment]
Update:
I originally had 4 Logistical Sorters, now I have 7 through crash duplication. After placing all of them, only a few made me crash. I went inside the crashing Sorters and removed all filters, thinking that maybe they had bad item IDs/names, but to no avail, those sorters specifically still crashed the game. The other ones are fine, filters or no. I have since burned these bad Sorters in lava, but I still have no clue what happened to them.

Feel free to close this issue. Any theories you can come up with would be helpful, as I may have done something I wasn't aware of.

**Comment by aidancbrady** [comment]
Looks to me like a weird Minecraft corruption issue - if you notice at the top of the crash report its actually an internal issue of ItemStack.  Wish I could help!
