### ISSUE TITLE
URGENT Crash Using V169 Startup Crash

### ISSUE THREAD

**Issue by enterprise12nx** [aidancbrady/Mekanism#2145]
I am getting this crash, i need it fixed urgently as i cannot start up my server because of it now.
http://pastebin.com/HVYK1bqg

Is there someway i can fix this while waiting for the fix?

EDIT:
Also seeing this in server console somtimes:
http://pastebin.com/ABPvG8Mp

**Comment by enterprise12nx** [comment]
or whats causing it?

**Comment by MrGraphic** [comment]
You can "MCedit" this issue. There is enough information in that crash log - exact block location and what is causing issue. Just load world or region with this block and delete erroring one.

**Comment by enterprise12nx** [comment]
ok, has number 2122 been fixed yet?
Is this a confirmed bug? i saw one other person having similer problems.

**Comment by Archtikz** [comment]
It looks like a generic Multipart corruption

**Comment by enterprise12nx** [comment]
i think im down 1 version on forge multipart, do you think that would matter at all?

**Comment by enterprise12nx** [comment]
Also check what i posted again, i updated it

**Comment by aidancbrady** [comment]
No clue how that could happen, but I added a null check.

**Comment by enterprise12nx** [comment]
thanks!
