### ISSUE TITLE
GasGenerator mekanism v177

### ISSUE THREAD

**Issue by vavraCZe** [aidancbrady/Mekanism#2148]
After update server (cauldron latest with forge 1236) from mekanism 157 to 177

http://hastebin.com/zuyavatugi.avrasm

Before update, server are lagging (one of CPU core have 100% usage every 30s). Now server still lagging, but every 10s with this log (one of CPU core have 100% usage).

Mods:
http://prntscr.com/684e3y
http://prntscr.com/684ee3

**Comment by Dannerick** [comment]
I can confirm the exception is generated when a gas generator tile entity with an empty gas tank is loaded during an onChuckLoad call.
