### ISSUE TITLE
Cannot craft heat generator

### ISSUE THREAD

**Issue by metria** [aidancbrady/Mekanism#2149]
When attempting to craft the Heat Generator, I can load the ingredients into the crafting table, but nothing shows in the output. The crafting type listed for the recipe in NEI is "Mekanism Shaped", I don't know if that is normal or not.

**Comment by aidancbrady** [comment]
Not a Mekanism bug, otherwise my issues list would be spammed with your report.

Make sure you have everything lined up correctly - it should indeed say "Mekanism Shaped Crafting." Worst case scenario, another mod is interfering with my recipes.

**Comment by metria** [comment]
It does say mekanism shaped. I'll try to find out where there's a conflict.
Nothing useful in the logs that I can see.  Thanks.

**Comment by rioricorick** [comment]
How would I go about locating the conflict in the recipes? What are the relevant files on the server?
Thanks
