### ISSUE TITLE
Mekanism machines do not receive energy from Team COFH mods

### ISSUE THREAD

**Issue by MacGyversMullet** [aidancbrady/Mekanism#2150]
Mekanism machines cannot receive energy from Thermal Dynamics energy conduits or Thermal Expansion energy cells connected externally. TE energy cells only charge Mek machines if placed inside the energy slot in the machine's UI.

This problem exists in ThermalExpansion-[1.7.10]4.0.0RC1-119 and ThermalDynamics-[1.7.10]1.0.0RC1-69. I'm not sure if the issue is on Mekanism's end or COFH's end, but others have suggested that the problem could be due to Mekanism not being compatible with the current RF API.

**Comment by grimallq** [comment]
And what version of Mekanism that would be? Because 177 certainly does work with Thermal Dynamics without issue.

You're sure you don't have some other outdated mod shipping the old API?

**Comment by unpairedbracket** [comment]
What @grimallq says is almost certainly the issue. I'm pretty sure if we were incompatible with the CoFH version you're using it would be much more obvious, because we would probably be crashing.
