### ISSUE TITLE
All mekanism Tools crashing when put into any type of crafting medium

### ISSUE THREAD

**Issue by Darkmega18** [aidancbrady/Mekanism#2151]
This crash occurs I believe because of botania along with other problems because it makes mention of vazkii. I have had numerous occasions of this blowing up from both the recommended and latest mod versions but not all of them have given a crash report it seems as far as my crash log list goes...

Kaboom when trying to put into crafting bench in applied energistics.
http://pastebin.com/YJUwLjv0 

Kaboom when trying to craft using tinkers bench
http://pastebin.com/QfjFFF1c

I also got kaboomed infinitely when putting one into a translocator crafting box which would constantly crash my world...

it has also kaboomed with normal and tinkers crafting benches.

Found due to trying to craft on enchantments onto the items using artifice upgrades.

**Comment by aidancbrady** [comment]
This has been confirmed to be an issue with Botanica a while ago.

**Comment by Darkmega18** [comment]
Has it been reported to Vazkii or a fix proposed? or will it forever be a problem that I will occasionally forget about and then run into and rage-about because my need for early easy enchantments? :V

**Comment by aidancbrady** [comment]
Vazkii took a look at it before, I'm not sure if he made any progress with it.  Go ahead and make an issue on his tracker, tell him to report back to me if he needs my assistance with something.

**Comment by Darkmega18** [comment]
Roger that. :)

**Comment by Vazkii** [comment]
This is due to Mine&Blade. I think that was established on the last thread already.

**Comment by Vazkii** [comment]
Relevant thread is #1913
