### ISSUE TITLE
Mekanism digital miner

### ISSUE THREAD

**Issue by Flukethoughts** [aidancbrady/Mekanism#2154]
mekanism digital miner on the moon times out the server.
GalacticraftCore-1.7-3.0.8.261
Galacticraft-Planets-1.7-3.0.8.261
Mekanism-1.7.10-7.1.2.177
MekanismGenerators-1.7.10-7.1.2.177
MekanismTools-1.7.10-7.1.2.177

**Comment by aidancbrady** [comment]
Can't do anything without a log.

**Comment by Flukethoughts** [comment]
aidancbrady i would love to provide a log but sadly I can not all I can say is that it's on a live server I host and it seems to always happen in a galatacraft world. It might have to do with the blocks that are not supposed to break or maybe something different I will say how ever I do enjoy your mod and I look forward to donating when the funds are released to me from my bank. I will try to replicate this on the home server and then I will post you the logs then thank you for your time.

**Comment by aidancbrady** [comment]
Okay, thanks a bunch!  If you can give me some logs I'll reopen this and take a look.
