### ISSUE TITLE
Still Crashing 7.1.2.178

### ISSUE THREAD

**Issue by enterprise12nx** [aidancbrady/Mekanism#2158]
I know i reported this issue already, but im on this mekanism build and its still happening, and more frequently.
My server keeps crashing from it, is this currently being fixed at least?
I really need it fixed /= as unexpected crashes are really bad for a 24/7 server and its world(corruption)
http://pastebin.com/eaP0bZ9P

**Comment by aidancbrady** [comment]
Added a proper null check, should be fixed.
