### ISSUE TITLE
8.0.0.385 Crash

### ISSUE THREAD

**Issue by squ1b3r** [aidancbrady/Mekanism#2159]
Just tried using 8.0.0.385 solo and it crashed with: http://pastebin.com/aUULnG7v

With:
```
CoFHCore-[1.7.10]3.0.0RC2-199.jar
CoFHLib-[1.7.10]1.0.0B9-118.jar
ThermalDynamics-[1.7.10]1.0.0RC2-77.jar
ThermalExpansion-[1.7.10]4.0.0RC2-129.jar
ThermalFoundation-[1.7.10]1.0.0RC3-56.jar
```
it crashes with: http://pastebin.com/zpBrmhVG

Also, not sure if this is relevant but after v8+ using mekanism with bunch of other mods gives a mod sorting warning upon loading and won't let me use it.

Here is a log for that as well: http://pastebin.com/1UxZrGX1 (part of the log about sorting). I can provide full log if you need.

Tell me if you need any additional information. Thank you for this awesome mod!

**Comment by aidancbrady** [comment]
The second error is a Topological Sort bug, not on my end.  As for the first, that's not necessarily solo if you have CoFH mods installed - try an installation with literally ONLY Mekanism installed.  I'll reopen if you confirm this is on my end.

**Comment by squ1b3r** [comment]
By solo, I meant solo. Look at the first crash log. There is literally only mekanism installed and ForgeMultipart it downloads on startup

**Comment by aidancbrady** [comment]
Aha! I misread this whole thing.  The more recent beta builds are likely to crash - I'm currently in the process of adding a ton of new content which means unstable builds.  Once I finalize the new content the builds should stop failing.

Apologies for the confusion!

**Comment by squ1b3r** [comment]
Got it. Thanks.
