### ISSUE TITLE
Ender IO Insulated Redstone Conduit to control Mekanism machines?

### ISSUE THREAD

**Issue by filikun** [aidancbrady/Mekanism#2160]
Hi! Im playing Bevos techpack V12 and I have a lot of fun combining Ender IO and Mekanism and they work great togheter in most part. One thing I cant get working is to control the Mekanism machines using a Insulated Redstone Conduit from Ender IO, they dont seem to connect.

Im trying to get the machines to not work when they have a redstone signal from a Insulated Redstone Conduit so that a ender io power monitor can shut down my energy hungry mekanism machines when the power is below say 25%. 

Am i doing something wrong?

Mekanism 7.1.2
Ender IO V 1.7.10-2.2.8.349

**Comment by Dannerick** [comment]
While it is true that ender io redstone conduits do not auto connect to mekanism machines, you can force the conduit to connect manually. Once you do that, it can be controlled just fine using the redstone signal.
