### ISSUE TITLE
Obsidian armor not taking durability damage - Multiplayer

### ISSUE THREAD

**Issue by rob5251** [aidancbrady/Mekanism#2161]
This seems to only occur on multiplayer, tested in single player and the armor takes damage, yet when trying on smp the armor took no durability damage.

The configs for Mekanism are the same server-side and client-side.

This only seems to occur when the full set is worn. (Taking boots off doesn't seem to effect this though)
So as long as you have a full set on (boots excluded) the armor will take no damage.

Server is running Cauldron 1.1236.05.212 which is using Forge Mod Loader version 7.10.85.1236
Might just be Cauldron issue?

**Comment by aidancbrady** [comment]
I play on a private server and never ran into that issue, even when wearing a full set.  I'd submit it to Cauldron.  Thanks for reporting though!

**Comment by rob5251** [comment]
@aidancbrady 
Ah, well if that's the case there's no point in reporting it to them as they're busy working on Sponge now.
