### ISSUE TITLE
SSP Crashing when trying to place Logistical Transporters

### ISSUE THREAD

**Issue by ashkorewd** [aidancbrady/Mekanism#2162]
Singleplayer keeps crashing on me when I try to place Logistical Transporters. I am only running the core of Mekanism in SSP.

Please see crash report below.

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2/25/15 6:56 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: mekanism/common/multipart/PartLogisticalTransporter$TransporterPipeProxy
	at mekanism.common.multipart.PartLogisticalTransporter.<init>(PartLogisticalTransporter.java:65)
	at mekanism.common.multipart.PartSidedPipe.getPartType(PartSidedPipe.java:116)
	at mekanism.common.multipart.ItemPartTransmitter.newPart(ItemPartTransmitter.java:77)
	at codechicken.multipart.TItemMultiPart$class.place$1(ItemMultiPart.scala:32)
	at codechicken.multipart.TItemMultiPart$class.onItemUse(ItemMultiPart.scala:47)
	at codechicken.multipart.JItemMultiPart.func_77648_a(ItemMultiPart.scala:14)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:353)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1435)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1941)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mekanism.common.multipart.PartLogisticalTransporter$TransporterPipeProxy
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more
Caused by: java.lang.NoClassDefFoundError: buildcraft/api/transport/IPipe
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 21 more
Caused by: java.lang.ClassNotFoundException: buildcraft.api.transport.IPipe
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 25 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 27 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mekanism.common.multipart.PartLogisticalTransporter.<init>(PartLogisticalTransporter.java:65)
	at mekanism.common.multipart.PartSidedPipe.getPartType(PartSidedPipe.java:116)
	at mekanism.common.multipart.ItemPartTransmitter.newPart(ItemPartTransmitter.java:77)
	at codechicken.multipart.TItemMultiPart$class.place$1(ItemMultiPart.scala:32)
	at codechicken.multipart.TItemMultiPart$class.onItemUse(ItemMultiPart.scala:47)
	at codechicken.multipart.JItemMultiPart.func_77648_a(ItemMultiPart.scala:14)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:353)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1435)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['AshkoreWD'/350, l='MpServer', x=-226.39, y=72.98, z=265.70]]
	Chunk stats: MultiplayerChunkCache: 576, 576
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-236,64,256), Chunk: (at 4,4,0 in -15,16; contains blocks -240,0,256 to -225,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1775 game time, 1775 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 137 total; [EntitySquid['Squid'/257, l='MpServer', x=-163.44, y=55.28, z=201.84], EntitySquid['Squid'/259, l='MpServer', x=-161.13, y=46.00, z=215.97], EntitySkeleton['Skeleton'/260, l='MpServer', x=-172.30, y=16.44, z=269.69], EntitySkeleton['Skeleton'/261, l='MpServer', x=-170.50, y=20.00, z=262.94], EntitySkeleton['Skeleton'/262, l='MpServer', x=-168.31, y=20.00, z=259.69], EntityBat['Bat'/263, l='MpServer', x=-169.69, y=41.25, z=275.20], EntitySquid['Squid'/264, l='MpServer', x=-167.75, y=48.00, z=282.31], EntitySquid['Squid'/265, l='MpServer', x=-165.25, y=45.34, z=299.25], EntitySquid['Squid'/266, l='MpServer', x=-160.78, y=44.34, z=296.81], EntityZombie['Zombie'/522, l='MpServer', x=-197.50, y=14.00, z=312.50], EntitySquid['Squid'/267, l='MpServer', x=-174.41, y=45.00, z=305.34], EntitySkeleton['Skeleton'/268, l='MpServer', x=-172.94, y=20.00, z=317.50], EntityZombie['Zombie'/269, l='MpServer', x=-174.50, y=21.00, z=316.50], EntitySquid['Squid'/270, l='MpServer', x=-167.06, y=44.38, z=307.09], EntitySquid['Squid'/271, l='MpServer', x=-163.63, y=42.34, z=306.38], EntitySquid['Squid'/272, l='MpServer', x=-168.22, y=38.84, z=309.72], EntitySquid['Squid'/273, l='MpServer', x=-169.72, y=51.34, z=318.50], EntitySquid['Squid'/274, l='MpServer', x=-174.13, y=54.31, z=315.78], EntitySquid['Squid'/275, l='MpServer', x=-174.16, y=53.34, z=306.88], EntitySquid['Squid'/277, l='MpServer', x=-175.94, y=47.16, z=326.22], EntitySquid['Squid'/278, l='MpServer', x=-173.66, y=55.34, z=324.78], EntitySquid['Squid'/289, l='MpServer', x=-159.91, y=48.06, z=201.50], EntitySquid['Squid'/292, l='MpServer', x=-160.75, y=48.19, z=212.53], EntityZombie['Zombie'/293, l='MpServer', x=-155.59, y=22.00, z=236.00], EntityZombie['Zombie'/294, l='MpServer', x=-156.88, y=23.00, z=247.63], EntityZombie['Zombie'/296, l='MpServer', x=-151.59, y=20.00, z=262.91], EntityZombie['Zombie'/298, l='MpServer', x=-148.50, y=21.00, z=272.63], EntitySkeleton['Skeleton'/299, l='MpServer', x=-158.38, y=27.00, z=306.31], EntityZombie['Zombie'/300, l='MpServer', x=-151.91, y=25.00, z=305.63], EntitySquid['Squid'/301, l='MpServer', x=-160.91, y=54.34, z=315.31], EntityZombie['Zombie'/303, l='MpServer', x=-159.03, y=26.00, z=333.41], EntityCreeper['Creeper'/562, l='MpServer', x=-201.50, y=31.00, z=264.50], EntityZombie['Zombie'/566, l='MpServer', x=-188.50, y=25.00, z=305.50], EntitySkeleton['Skeleton'/58, l='MpServer', x=-296.16, y=13.00, z=231.44], EntityCreeper['Creeper'/59, l='MpServer', x=-298.88, y=14.00, z=230.97], EntityEnderman['Enderman'/323, l='MpServer', x=-150.08, y=35.00, z=256.46], EntitySkeleton['Skeleton'/68, l='MpServer', x=-270.84, y=23.00, z=191.50], EntitySkeleton['Skeleton'/73, l='MpServer', x=-271.47, y=23.00, z=195.09], EntityItem['item.tile.flower2.poppy'/74, l='MpServer', x=-272.75, y=63.13, z=328.38], EntityZombie['Zombie'/82, l='MpServer', x=-271.13, y=35.00, z=185.72], EntityBat['Bat'/83, l='MpServer', x=-255.44, y=26.41, z=213.34], EntitySkeleton['Skeleton'/84, l='MpServer', x=-265.50, y=23.00, z=219.09], EntityBat['Bat'/85, l='MpServer', x=-256.75, y=24.10, z=217.25], EntitySheep['Sheep'/86, l='MpServer', x=-256.50, y=79.00, z=234.47], EntitySkeleton['Skeleton'/92, l='MpServer', x=-241.09, y=18.00, z=188.50], EntityZombie['Zombie'/93, l='MpServer', x=-244.00, y=49.00, z=188.44], EntityCreeper['Creeper'/94, l='MpServer', x=-247.09, y=49.00, z=191.34], EntityClientPlayerMP['AshkoreWD'/350, l='MpServer', x=-226.39, y=72.98, z=265.70], EntityZombie['Zombie'/95, l='MpServer', x=-245.41, y=49.00, z=190.91], EntityZombie['Zombie'/96, l='MpServer', x=-243.28, y=49.00, z=189.50], EntityZombie['Zombie'/97, l='MpServer', x=-253.09, y=21.00, z=199.56], EntityCreeper['Creeper'/98, l='MpServer', x=-248.50, y=45.00, z=203.03], EntitySkeleton['Skeleton'/99, l='MpServer', x=-248.97, y=41.00, z=208.50], EntityCreeper['Creeper'/100, l='MpServer', x=-249.50, y=31.00, z=219.50], EntitySpider['Spider'/101, l='MpServer', x=-240.66, y=32.00, z=221.06], EntityBat['Bat'/102, l='MpServer', x=-248.41, y=21.10, z=225.53], EntityCow['Cow'/103, l='MpServer', x=-248.03, y=79.00, z=232.50], EntitySheep['Sheep'/104, l='MpServer', x=-245.08, y=80.00, z=233.53], EntityCow['Cow'/105, l='MpServer', x=-245.93, y=81.00, z=236.91], EntitySheep['Sheep'/106, l='MpServer', x=-251.38, y=81.00, z=228.53], EntityCow['Cow'/107, l='MpServer', x=-248.06, y=80.00, z=230.06], EntitySheep['Sheep'/108, l='MpServer', x=-256.94, y=80.00, z=226.88], EntityCow['Cow'/109, l='MpServer', x=-247.34, y=68.00, z=244.75], EntityZombie['Zombie'/110, l='MpServer', x=-246.66, y=24.00, z=285.34], EntityBat['Bat'/118, l='MpServer', x=-232.65, y=20.01, z=199.86], EntityCow['Cow'/119, l='MpServer', x=-225.53, y=63.00, z=243.25], EntityCow['Cow'/120, l='MpServer', x=-223.72, y=63.00, z=255.72], EntityCow['Cow'/121, l='MpServer', x=-239.47, y=71.00, z=252.50], EntityCow['Cow'/122, l='MpServer', x=-229.63, y=65.00, z=255.47], EntityCow['Cow'/123, l='MpServer', x=-230.47, y=49.00, z=263.31], EntityCreeper['Creeper'/144, l='MpServer', x=-211.47, y=13.00, z=219.03], EntityItem['item.tile.gravel'/145, l='MpServer', x=-214.22, y=34.13, z=237.91], EntitySquid['Squid'/146, l='MpServer', x=-210.73, y=48.02, z=226.92], EntityItem['item.item.seeds'/147, l='MpServer', x=-217.72, y=63.13, z=251.72], EntitySquid['Squid'/148, l='MpServer', x=-198.06, y=53.57, z=246.89], EntityCreeper['Creeper'/150, l='MpServer', x=-210.50, y=26.00, z=257.50], EntityCow['Cow'/151, l='MpServer', x=-224.72, y=58.00, z=265.38], EntityCow['Cow'/152, l='MpServer', x=-225.49, y=68.63, z=266.50], EntityCow['Cow'/153, l='MpServer', x=-218.71, y=69.00, z=274.50], EntitySkeleton['Skeleton'/154, l='MpServer', x=-220.56, y=13.00, z=282.13], EntitySquid['Squid'/155, l='MpServer', x=-220.66, y=48.00, z=318.75], EntitySquid['Squid'/156, l='MpServer', x=-210.53, y=48.34, z=320.91], EntitySquid['Squid'/157, l='MpServer', x=-220.69, y=48.34, z=321.88], EntitySquid['Squid'/158, l='MpServer', x=-216.50, y=48.38, z=319.31], EntitySquid['Squid'/159, l='MpServer', x=-205.75, y=48.00, z=318.66], EntitySquid['Squid'/160, l='MpServer', x=-209.06, y=48.38, z=318.50], EntitySquid['Squid'/161, l='MpServer', x=-216.94, y=48.03, z=327.53], EntitySquid['Squid'/162, l='MpServer', x=-204.75, y=48.63, z=328.09], EntitySquid['Squid'/184, l='MpServer', x=-194.50, y=59.38, z=207.13], EntitySquid['Squid'/186, l='MpServer', x=-206.78, y=44.41, z=230.91], EntitySquid['Squid'/187, l='MpServer', x=-208.94, y=42.00, z=226.78], EntitySquid['Squid'/188, l='MpServer', x=-199.56, y=54.13, z=222.69], EntitySkeleton['Skeleton'/189, l='MpServer', x=-200.50, y=32.00, z=245.50], EntitySquid['Squid'/190, l='MpServer', x=-205.39, y=58.40, z=240.29], EntitySquid['Squid'/191, l='MpServer', x=-194.97, y=47.01, z=238.16], EntityBat['Bat'/192, l='MpServer', x=-205.59, y=27.77, z=274.94], EntityCreeper['Creeper'/193, l='MpServer', x=-201.47, y=32.00, z=261.34], EntitySquid['Squid'/194, l='MpServer', x=-192.01, y=55.32, z=273.97], EntityBat['Bat'/195, l='MpServer', x=-203.71, y=24.15, z=294.44], EntityBat['Bat'/196, l='MpServer', x=-197.99, y=24.82, z=305.15], EntityCreeper['Creeper'/197, l='MpServer', x=-198.31, y=14.00, z=311.59], EntityZombie['Zombie'/198, l='MpServer', x=-197.50, y=14.00, z=315.50], EntityZombie['Zombie'/199, l='MpServer', x=-198.75, y=15.00, z=310.66], EntitySquid['Squid'/200, l='MpServer', x=-188.06, y=55.34, z=315.34], EntitySquid['Squid'/214, l='MpServer', x=-187.75, y=58.31, z=203.81], EntityBat['Bat'/215, l='MpServer', x=-192.94, y=10.69, z=249.51], EntityZombie['Zombie'/216, l='MpServer', x=-183.50, y=25.00, z=232.50], EntityBat['Bat'/217, l='MpServer', x=-183.75, y=17.10, z=238.47], EntityZombie['Zombie'/218, l='MpServer', x=-188.50, y=32.00, z=245.50], EntitySquid['Squid'/219, l='MpServer', x=-185.19, y=52.06, z=262.47], EntitySquid['Squid'/220, l='MpServer', x=-176.63, y=52.34, z=270.50], EntitySquid['Squid'/221, l='MpServer', x=-184.56, y=55.31, z=275.63], EntitySkeleton['Skeleton'/222, l='MpServer', x=-178.28, y=44.00, z=282.50], EntitySkeleton['Skeleton'/223, l='MpServer', x=-177.31, y=42.00, z=278.34], EntitySquid['Squid'/224, l='MpServer', x=-189.50, y=48.38, z=273.63], EntitySquid['Squid'/225, l='MpServer', x=-187.31, y=50.38, z=269.13], EntitySquid['Squid'/226, l='MpServer', x=-189.66, y=50.81, z=270.94], EntitySquid['Squid'/227, l='MpServer', x=-190.50, y=51.38, z=279.50], EntityZombie['Zombie'/228, l='MpServer', x=-183.47, y=14.00, z=301.97], EntityCreeper['Creeper'/229, l='MpServer', x=-179.59, y=34.00, z=295.00], EntityCreeper['Creeper'/230, l='MpServer', x=-185.41, y=35.00, z=293.47], EntityBat['Bat'/231, l='MpServer', x=-185.39, y=37.05, z=290.05], EntityBat['Bat'/232, l='MpServer', x=-184.67, y=36.46, z=292.66], EntityBat['Bat'/233, l='MpServer', x=-179.33, y=38.86, z=296.95], EntityCreeper['Creeper'/234, l='MpServer', x=-182.28, y=18.00, z=318.94], EntityCreeper['Creeper'/235, l='MpServer', x=-181.31, y=17.00, z=318.38], EntitySquid['Squid'/236, l='MpServer', x=-179.69, y=42.38, z=312.44], EntitySquid['Squid'/237, l='MpServer', x=-184.28, y=44.88, z=319.50], EntitySquid['Squid'/238, l='MpServer', x=-192.50, y=46.00, z=321.75], EntitySquid['Squid'/239, l='MpServer', x=-178.16, y=46.34, z=307.81], EntitySquid['Squid'/240, l='MpServer', x=-184.09, y=55.38, z=312.50], EntitySquid['Squid'/241, l='MpServer', x=-187.50, y=42.34, z=325.50], EntitySquid['Squid'/242, l='MpServer', x=-191.50, y=45.00, z=318.50], EntitySquid['Squid'/244, l='MpServer', x=-178.38, y=50.28, z=323.41], EntityWitch['Witch'/506, l='MpServer', x=-183.50, y=21.00, z=233.50], EntityCreeper['Creeper'/507, l='MpServer', x=-162.12, y=47.00, z=254.56], EntitySquid['Squid'/252, l='MpServer', x=-167.50, y=47.38, z=205.84]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 214100584 bytes (204 MB) / 680525824 bytes (649 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 7 mods loaded, 7 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.1.0.314} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mekanism{7.1.1} [Mekanism] (Mekanism-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.1.0.314} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.1.0.314} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: NVS 300/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by aidancbrady** [comment]
This is a mod conflict error - not an issue on my end.  Make sure all your mods you have installed are up-to-date.

**Comment by ashkorewd** [comment]
Well, as I've only added Mekanism core at the current available, and am running Forge at the current available, I'm not sure which mod it is in conflict with.

**Comment by ashkorewd** [comment]
![image](https://cloud.githubusercontent.com/assets/471761/6387284/aedf1990-bd3d-11e4-8fd3-08489476e7ec.png)

**Comment by ashkorewd** [comment]
![image](https://cloud.githubusercontent.com/assets/471761/6387289/c100071a-bd3d-11e4-8b0a-93ba797d652e.png)

**Comment by unpairedbracket** [comment]
Your Mekanism is out of date, updating to 180 should fix it.
