### ISSUE TITLE
Possible issue with blood magic compression sigil

### ISSUE THREAD

**Issue by Sunconure11** [aidancbrady/Mekanism#2164]
http://pastebin.com/Ne0JsEZX

**Comment by aidancbrady** [comment]
Not a Mekanism issue - looks like a problem with Way of Time

**Comment by ChaoticTabris** [comment]
Way of Time says there is no way it's on his side. Some people seen to point it might be related to Botania or M&B.

**Comment by ChaoticTabris** [comment]
M&B author says the problem lies on Mekanism. Look at this issue at their repository: https://github.com/Mine-and-blade-admin/Battlegear2/issues/148
