### ISSUE TITLE
Digital Miner - Mining machines etc, configurable

### ISSUE THREAD

**Issue by enterprise12nx** [aidancbrady/Mekanism#2166]
So on my server, people have found some way to mine peoples machines, etc using the DigiMiner.
I think you should add a config option to only allow ores to be mined by default!

Mark this as a feature please

**Comment by aidancbrady** [comment]
At the moment, there is no real easy way to accomplish this.  I do plan on adding forms of machine privacy to Mekanism v9, however - this will resolve the issue.

**Comment by enterprise12nx** [comment]
sweet
