### ISSUE TITLE
Minechem and Mekanism gases and liquids are incompatible

### ISSUE THREAD

**Issue by Moorleiche2k** [aidancbrady/Mekanism#2169]
Using RR 3.2.3.2 (Mekanism 1.7.10-7.1.1.145 and MineChem 1.7.10-5.0.5.358)

Mekanism and MineChem gases are different although should be the same. E.g. you can place Hydrogen tubes in a rotary condensentrator and it will fill the liquid slot with MineChem hydrogen, but conversion to Mekanism Hydrogen gas doesnt work. Pumping in MineChem liquid hydrogen from a fluid transposer in a condensentrator also doesnt work. Not tested with the other gases.

**Comment by laz2727** [comment]
Iirc they are way too different.

**Comment by aidancbrady** [comment]
MineChem can integrate with the Mekanism API to allow for gas support. Otherwise, nothing I can do.

**Comment by Moorleiche2k** [comment]
Thats sad, but i will try my luck. Thanks anyways
