### ISSUE TITLE
Mekanism Crash Using V180

### ISSUE THREAD

**Issue by enterprise12nx** [aidancbrady/Mekanism#2170]
I didn't see anything about this  being fixed in the next four versions, so here you go.

http://pastebin.com/a5gCXB8U

If or when its fixed, post here please so i can update it!

**Comment by aidancbrady** [comment]
Report to IndustrialCraft, not on my end :)

**Comment by enterprise12nx** [comment]
FYI reporting this problem was fixed in IC2-Experimental Version #689
