### ISSUE TITLE
ENH: substrate recipe for PRC

### ISSUE THREAD

**Issue by Greylocke** [aidancbrady/Mekanism#2174]
Right now the only way to get substrate for HDPE production is as a by-product of ethylene production. But the output of substrate is so low that, if you're actually using much plastic in your construction, you end up running your ethylene production line nonstop, just to produce substrate. This usually results in a large stockpile of ethylene gas.

To resolve the substrate shortage, I suggest a new PRC recipe that focuses on substrate production at the expense of ethylene. This recipe uses substrate to "seed" the creation of more substrate from ethylene gas, heat, pressure, and water.

I've done some tinkering, and the recipe I'm currently using is: 200mB water + 100mB gas:ethene + 1 substrate + 200J + 20 seconds = 8 substrate + 10mB gas:oxygen

**Comment by aidancbrady** [comment]
Done! Exactly as you described.
