### ISSUE TITLE
decrease pellets/sheet

### ISSUE THREAD

**Issue by Greylocke** [aidancbrady/Mekanism#2175]
After working with plastics a fair amount, I think that it takes too many pellets to make sheets of plastic. I suggest decreasing the number of pellets per sheet. In my modpack, I've made the following changes:
- in a crafting grid, 4 pellets = 1 sheet
- in a crusher, 3 pellets = 1 sheet
- in a Railcraft rolling machine, 2 pellets = 1 sheet

**Comment by aidancbrady** [comment]
Added the crafting grid recipe, and created a 3 pellet -> 1 sheet enrichment chamber recipe.  If you don't mind, I'd rather not directly add the rolling machine recipe - too much cluttered integration ^^
