### ISSUE TITLE
Crash(& Duplication) on Placement: Gas-Burning Generator

### ISSUE THREAD

**Issue by Vollykin** [aidancbrady/Mekanism#2177]
http://pastebin.com/X4BKtxeY

(First thing I have ever submitted to Github.)
Strange bug whenever I place the Gas-Burning Generator Minecraft crashes. Stranger yet, when I load the world back up everything is fine and the Gas-Burning Generator is even placed on the ground normally.... however, there is still a Gas-Burning Generator in my inventory. (Duplicating the Gas-Burning Generator).

Labels should be: Bugs , Generators , Machines

**Comment by aidancbrady** [comment]
Ah, yes - this was a bug, and has since been fixed in the latest builds.  Updating will prevent the crash, but there's a chance that you may need to recraft your generator :(
