### ISSUE TITLE
strange very slow world generation

### ISSUE THREAD

**Issue by VasyaOrk** [aidancbrady/Mekanism#2178]
Hello
I play minecraft 1.7.10 with some mods (try to create own "local" modpack ). I use separate client and server, because in future we want to play this modpack with friends.
When add Mekanism into modpack new world generates too long ... if generates.
Near 5-8 min. server start and worldgen without mekanism; 
more than 30 min. with mekanism with no result : save to HDD empty (8 - 300 Kb) world directory)
Then I delete Mekanism OR Gregtech from modpack worldgen completes in 6-10 min.

Java     - 8 update 31
server  -  cauldron-1.7.10-1.1286.06.216
client    -  forge-1.7.10-10.13.2.1291
Hardware  - Core I7, 16 Gb RAM
Java use 1-4 cores (total CPU load 12-40% all time), up to 8 Gb RAM without any result

I try 7.1.1.127, 7.1.2.157 and 7.1.2.184 versions with this result.

Used mods 

appliedenergistics2-rv2-beta-8.jar
BiblioCraft[v1.9.2][MC1.7.10].jar
BiblioWoods[BiomesOPlenty][v1.9].jar
BiblioWoods[Highlands][v1.4].jar
BiblioWoods[Natura][v1.5].jar
BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar
Botania r1.5-168.jar
Carpenter's Blocks v3.3.5 - MC 1.7.10.jar
Chisel2-2.3.7.34.jar
CodeChickenCore-1.7.10-1.0.4.35-universal.jar
CoFHCore-[1.7.10]3.0.0RC4-204.jar
CoFHLib-[1.7.10]1.0.0RC4-121.jar
customrecipes-1.7.10-4.7.jar
DummyCore-1.10.1710.alpha.jar
EnderIO-1.7.10-2.2.8.349.jar
EssentialCraft3-4.4.1710.55betaHF.jar
EssentialThaumaturgy-1.1.1710.11EC(4.4.1710.37)TC(4.2.3.5).jar
ExtraCells-1.7.10-2.2.56b86.jar
gregtech_1.7.10-5.07.07.jar
Highlands-1.7.2-v-2.2.3.jar
industrialcraft-2-2.2.685-experimental.jar
Iron-Chests-Mod-1.7.10.jar
magicalcrops-1.7.10_0.1.jar
Mantle-1.7.10-0.3.2.jar
Mekanism-1.7.10-7.1.2.184.jar
MekanismGenerators-1.7.10-7.1.2.184.jar
MekanismTools-1.7.10-7.1.2.184.jar
Metallurgy-1.7.10-4.0.8.97.jar
MetallurgyCore-1.7.10-4.0.4.18.jar
MineFactoryReloaded-CompatMagicalCrops-1.1.1.jar
MineFactoryReloaded-[1.7.10]2.8.0RC7-71.jar
natura-1.7.10-2.2.0.1.jar
NetherOres-[1.7.10]2.3.0RC4-4.jar
NodalMechanics-1.7-1.0-7.jar
OpenComputers-MC1.7.10-1.5.2.9-universal.jar
OreDictionaryConverter-1.6.1.jar
PlayerAPI-1.7.10-1.2.jar
ProjectRed-1.7.10-4.5.13.65-Base.jar
ProjectRed-1.7.10-4.5.13.65-Compat.jar
ProjectRed-1.7.10-4.5.13.65-Integration.jar
ProjectRed-1.7.10-4.5.13.65-Lighting.jar
ProjectRed-1.7.10-4.5.13.65-Mechanical_beta.jar
ProjectRed-1.7.10-4.5.13.65-World.jar
R-CritterPet 1.7.10 V4a.jar
Railcraft_1.7.10-9.4.0.0.jar
RedstoneArsenal-[1.7.10]1.1.0RC3-50.jar
RO_DragonAPI 1.7.10 V4c.jar
R_ChromatiCraft 1.7.10 V4c.jar
R_ElectriCraft 1.7.10 V4c.jar
R_ExpandedRedstone 1.7.10 V4a.jar
R_GeoStrata 1.7.10 V4a.jar
R_MeteorCraft 1.7.10 V4c.jar
R_ReactorCraft 1.7.10 V4c.jar
R_RotaryCraft 1.7.10 V4c.jar
R_UsefulTNT 1.7.10 V4a.jar
SmartCore-1.7.10-1.0.jar
SolarExpansion-Basic-1.4c.jar
SolarFlux-1.7.10-0.5a.jar
Thaumcraft-1.7.10-4.2.3.5.jar
thaumicenergistics-0.8.9.0b-rv2.jar
ThermalDynamics-[1.7.10]1.0.0RC4-91.jar
ThermalExpansion-[1.7.10]4.0.0RC4-135.jar
ThermalFoundation-[1.7.10]1.0.0RC4-58.jar
ZZZZZ Custom Configs-2.1.0.jar

**Comment by laz2727** [comment]
Both MK and GT are *extremely* heavy.

**Comment by VasyaOrk** [comment]
... internet serfing told : this issue most likely from gregtech.
---
this issue thread was meaningless. need close ... but i do not know how do it.
---
(((
