### ISSUE TITLE
Server timeout and 100% CPU ussage

### ISSUE THREAD

**Issue by Granik24** [aidancbrady/Mekanism#2179]
Hello, 
I have this bug. After rebooting my server, Mekanism has spaming my log with this messages: http://pastebin.com/QhngjLqF and my CPU and RAM ussage is on Maximum. 

My Forge version: 10.13.2.1291
Server running on Debian and Java 7.
Modpack is on FTB launcher, if you want modlist, add to your FTB modpack with code "ModFire".
Thank you for your time.

**Comment by aidancbrady** [comment]
This has been fixed, please update Mekanism to the latest build :)

**Comment by Granik24** [comment]
Oh god.. I forget it! Thank you!
