### ISSUE TITLE
Crash~

### ISSUE THREAD

**Issue by Rafmaninoff** [aidancbrady/Mekanism#2182]
Using latest build. :P 

http://pastebin.com/VKGEYQjr

**Comment by aidancbrady** [comment]
A mod is using an outdated version of the IC2 API.  Either install the most recent version of the IC2 API or find the offending mod and remove its packaged version of the API.

**Comment by Rafmaninoff** [comment]
I don't even have IC2...

**Comment by Rafmaninoff** [comment]
So apparently just dropping IC2 in here fixed the issue, thanks.
