### ISSUE TITLE
Waila factory type tooltip only showing Smelting

### ISSUE THREAD

**Issue by Rodg88** [aidancbrady/Mekanism#2184]
When I look at a factory, waila shows the correct processing type for what seems like 1 tick, then it changes to showing "smelting", no matter what kind of factory it is. And it always shows the factory type tooltip even if I turn off that option in waila settings.
With Waila-1.5.9 and Mekanism-7.1.2.184

**Comment by aidancbrady** [comment]
Not sure about the second bug, but the first bug is due to how I manage factory tiers.  I'll look into it when I have a chance, but its very low priority behind all the other content being developed for v8.  Thanks for reporting!
