### ISSUE TITLE
Tech limits without Mek Generators

### ISSUE THREAD

**Issue by PiggyWhiskey** [aidancbrady/Mekanism#2187]
I'm currently in a modpack that doesn't have Mekanism Generators.
This cuts off 4x and 5x production as there isn't a way to get Brine (No adv solars for the salination plant)

Unless this has come up before and my google-fu is lacking.

Idea: Detect if Mek Generators is installed, if not add receipe for another block to be added to the Salination plant to allow full functionality.

Edit:
3x is also incredibly difficult to sustain without MekGen.
Flint is the only way to get Oxygen without having bulk Hydrogen for no use (Massive power drain for Electrolytic Separator.)
Again, I may have missed something.

**Comment by halvors** [comment]
Why don't you simply add mekanism generators?

**Comment by PiggyWhiskey** [comment]
I believe the Pack author hasn't added it to have a challenge to power gen. (No Big Reactors or any other form of solar power except for Extra Utilities)

If a mod was split into 2 parts like Mek and MekGen it shouldn't handicap players with only the primary mod.

**Comment by aidancbrady** [comment]
Not exactly a bug, considering you can just install MekGen.  Won't be necessary in Mekanism v9, however, with the new heat transfer system.

**Comment by PiggyWhiskey** [comment]
aiden, still playing this modpack with v8 Mek. Still without MekGen.

I can get the Solar Evaporation Tower to form in a desert, but its refusing to generate brine which means the new Induction Matrix and reactor is off limit (Can't get lithium)

**Comment by unpairedbracket** [comment]
The reactor is part of MekGen anyway, but the EIM being impossible is an issue...

**Comment by PiggyWhiskey** [comment]
Bugger. Jumping between a couple different modpacks. Missed that.
