### ISSUE TITLE
Can't reduce sound volume for machines/generators?

### ISSUE THREAD

**Issue by mcgraj3** [aidancbrady/Mekanism#2188]
I have the config file set with:

D:SoundVolume=0.25

This doesn't change machine or generator sound volume at all, staying the same as if it was set to 1. Aside from pulling the annoying sounds (crusher, wind turbine) from the mod's .jar, I am at a loss what to do. Any help here is appreciated. Thanks!

**Comment by aidancbrady** [comment]
You may need to lower the sound volume even more for the changes to go into place - also make sure you restart Minecraft.  Regardless, this is solved in v8 with integration into the Forge sound system.
