### ISSUE TITLE
Mekanism Security

### ISSUE THREAD

**Issue by aidancbrady** [aidancbrady/Mekanism#2189]
This would be a complete security implementation for all machines, as well as teleportation networks, including energy, gas, fluid, item, and player.  I hope to have this partially complete before v8's release, and complete in v9.  The gist, in some bullet points, is as follows:

New machine - the Mekanism Security Terminal.
* A player can have as many of these as he wants.
* All link to a player "security profile" saved in the world file.  In this, a player can add entries for other players that can access machinery, designated by their usernames.
* Require energy to function - CONTINUOUS DRAIN of 100 J/t to function when activated.  When deactivated, takes no charge, but must reactivate to access interface.  Security protocol will still be present when deactivated, however.
* "Universal Behavior" section - allows user to designate specific security mechanisms shared by all machine modes - that means that these options will also affect "Everyone" and "Only Me" behaviors as well.
* "Modify Security" operation section - place a secured block and it will remove security, place a non-secured block and it will add security
* Only accessible by owner - owner can access and break without restriction.  Once broken, non-secured - does not maintain an owner

New TileComponent - TileComponentSecurity.
* Stores data in machines that can be secured.
* Three modes: "Only Me," "Terminal," "Everyone" - "Terminal" designates whether or not the machine should follow security protocol designated by Security Terminal.

Electric Chest changes:
* All previous locking/security settings will be removed and replaced with the new interface.

Will be pretty brutal to implement, primarily the network side of things and serialization when saving/loading.  Hopefully I can get the framework done before v8's release.

**Comment by aidancbrady** [comment]
Closing for now, as it seems many don't see this as a necessary addition. If enough users request otherwise I will implement :)

**Comment by Lord-i7** [comment]
please add this i desperately need this in 1.7.10

**Comment by lumpusman** [comment]
please let me know how we can give access to each other for teleporters, i have tried the security desk, tried changing the settings in escape menu, im not a coder so i don't even know how to open the modpack jar file...just need buddies to be able to change out teleporter freq.

thanks and i love the pack
