### ISSUE TITLE
Mekanism IC2 issue.

### ISSUE THREAD

**Issue by fatyg5** [aidancbrady/Mekanism#2191]
I've seen this issue posted a few times, where IC2 API crashes Mekanism. My question is, where was the update that fixed this? In september a post was made about it being fixed, so has it? Here's the log btw.

Time: 3/9/15 10:19 PM Description: Initializing game

java.lang.NoClassDefFoundError: mekanism/common/item/ItemElectricBow at java.lang.Class.forName0(Native Method) at java.lang.Class.forName(Unknown Source) at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:420) at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) at com.google.common.eventbus.EventBus.post(EventBus.java:275) at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) at com.google.common.eventbus.EventBus.post(EventBus.java:275) at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) at cpw.mods.fml.common.Loader.loadMods(Loader.java:492) at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204) at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) at net.minecraft.client.main.Main.main(SourceFile:148) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: java.lang.ClassNotFoundException: mekanism.common.item.ItemElectricBow at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) at java.lang.ClassLoader.loadClass(Unknown Source) at java.lang.ClassLoader.loadClass(Unknown Source) ... 34 more Caused by: java.lang.NoClassDefFoundError: mekanism/common/item/ItemEnergized at java.lang.ClassLoader.defineClass1(Native Method) at java.lang.ClassLoader.defineClass(Unknown Source) at java.security.SecureClassLoader.defineClass(Unknown Source) at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ... 36 more Caused by: java.lang.ClassNotFoundException: mekanism.common.item.ItemEnergized at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) at java.lang.ClassLoader.loadClass(Unknown Source) at java.lang.ClassLoader.loadClass(Unknown Source) ... 40 more

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head -- Stacktrace: at java.lang.Class.forName0(Native Method) at java.lang.Class.forName(Unknown Source) at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:420) at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) at com.google.common.eventbus.EventBus.post(EventBus.java:275) at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) at com.google.common.eventbus.EventBus.post(EventBus.java:275) at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) at cpw.mods.fml.common.Loader.loadMods(Loader.java:492) at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204) at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization -- Details: Stacktrace: at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) at net.minecraft.client.main.Main.main(SourceFile:148) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details -- Details: Minecraft Version: 1.7.10 Operating System: Windows 7 (amd64) version 6.1 Java Version: 1.7.0_55, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 294553552 bytes (280 MB) / 624951296 bytes (596 MB) up to 1908932608 bytes (1820 MB) JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048m -XX:MaxPermSize=256m AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0 FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 Optifine OptiFine_1.7.10_HD_B5 75 mods loaded, 75 mods active mcp{9.05} Minecraft Coder Pack Unloaded->Constructed FML{7.10.85.1291} Forge Mod Loader Unloaded->Constructed Forge{10.13.2.1291} Minecraft Forge Unloaded->Constructed appliedenergistics2-core{rv1-stable-1} AppliedEnergistics2 Core Unloaded->Constructed Aroma1997Core{1.0.2.13} Aroma1997Core Unloaded->Constructed CodeChickenCore{1.0.4.29} CodeChicken Core Unloaded->Constructed {000} CoFH ASM Data Initialization Unloaded->Constructed NotEnoughItems{1.0.4.90} Not Enough Items Unloaded->Constructed malisiscore{1.7.10-0.9.2} Malisis Core Unloaded->Constructed bspkrsCore{6.15} bspkrsCore Unloaded->Constructed ArmorStatusHUD{1.28} ArmorStatusHUD Unloaded->Constructed CoFHCore{1.7.10R3.0.0RC5} CoFH Core Unloaded->Constructed advancedgenetics{1.5.8} Advanced Genetics Unloaded->Constructed appliedenergistics2{rv1-stable-1} Applied Energistics 2 Unloaded->Constructed Aroma1997CoreHelper{1.0.2.13} Aroma1997Core|Helper Unloaded->Constructed Aroma1997sDimension{1.0} Aroma1997's Dimensional World Unloaded->Constructed Backpack{2.0.1} Backpack Unloaded->Constructed ThermalFoundation{1.7.10R1.0.0RC4} Thermal Foundation Unloaded->Constructed ThermalExpansion{1.7.10R4.0.0RC6} Thermal Expansion Unloaded->Constructed BigReactors{0.4.2A2} Big Reactors Unloaded->Constructed CarpentersBlocks{3.3.5} Carpenter's Blocks Unloaded->Constructed ForgeMultipart{1.1.0.314} Forge Multipart Unloaded->Constructed chisel{2.3.7.34} Chisel 2 Unloaded->Constructed MineFactoryReloaded{1.7.10R2.8.0RC8} MineFactory Reloaded Unloaded->Constructed EnderIO{1.7.10-2.2.8.349} Ender IO Unloaded->Constructed ExtraUtilities{1.2.2} Extra Utilities Unloaded->Constructed FastCraft{1.19} FastCraft Unloaded->Constructed hamsterrific{0.2.0} Hamsterrific Unloaded->Constructed iChunUtil{4.1.0} iChunUtil Unloaded->Constructed inventorytweaks{1.58-147-645ca10} Inventory Tweaks Unloaded->Constructed IronChest{6.0.62.742} Iron Chest Unloaded->Constructed Waila{1.5.8} Waila Unloaded->Constructed JABBA{1.2.0b} JABBA Unloaded->Constructed malisisdoors{1.7.10-1.1.1} Malisis' Doors Unloaded->Constructed Mantle{1.7.10-0.3.2.jenkins184} Mantle Unloaded->Constructed MapWriter{2.1.2} MapWriter Unloaded->Constructed MetallurgyCore{4.0.4} Metallurgy Core Unloaded->Constructed Mekanism{7.1.1} Mekanism Unloaded MekanismGenerators{7.1.1} MekanismGenerators Unloaded MekanismTools{7.1.1} MekanismTools Unloaded TConstruct{1.7.10-1.8.2.build858} Tinkers' Construct Unloaded Metallurgy{4.0.6} Metallurgy 4 Unloaded MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC8} MFR Compat: Applied Energistics Unloaded MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC8} MFR Compat: Atum Unloaded MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC8} MFR Compat: BackTools Unloaded MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC8} MFR Compat: BuildCraft Unloaded MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC8} MFR Compat: Chococraft Unloaded MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC8} MFR Compat: ExtraBiomes Unloaded MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC8} MFR Compat: Forestry Unloaded MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC8} MFR Compat: ForgeMicroblock Unloaded MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC8} MFR Compat: IC2 Unloaded MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC8} MFR Compat: Mystcraft Unloaded ProjRed|Core{4.4.5.44} ProjectRed Unloaded MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC8} MFR Compat ProjectRed Unloaded MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC8} MFR Compat: Railcraft Unloaded MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC8} MFR Compat: RP2 Unloaded MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC8} MFR Compat: Sufficient Biomes Unloaded MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC8} MFR Compat: Thaumcraft Unloaded MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC8} MFR Compat: Thermal Expansion Unloaded MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0RC8} MFR Compat: Tinkers' Construct Unloaded MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC8} MFR Compat: TwilightForest Unloaded MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC8} MFR Compat: Vanilla Unloaded Morph{0.9.1} Morph Unloaded Morpheus{1.7.10-1.5.26} Morpheus Unloaded notenoughkeys{@MOD_VERSION@} NotEnoughKEys Unloaded openmodularturrets{1.3.4} Open Modular Turrets Unloaded PneumaticCraft{1.2.6} PneumaticCraft Unloaded Roguelike{1.3.6} Roguelike Dungeons Unloaded secretroomsmod{4.7.1} The SecretRoomsMod Unloaded SSR{rc3} Soul Shards Reborn Unloaded ThermalDynamics{1.7.10R1.0.0RC5} Thermal Dynamics Unloaded TiCTooltips{1.2.3} TiC Tooltips Unloaded YALSM{2.1.3} Yet Another Leather Smelting Mod Unloaded McMultipart{1.1.0.314} Minecraft Multipart Plugin Unloaded ForgeMicroblock{1.1.0.314} Forge Microblocks Unloaded CoFHCore: -[1.7.10]3.0.0RC5-207 AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187 ThermalFoundation: -[1.7.10]1.0.0RC4-58 ThermalExpansion: -[1.7.10]4.0.0RC6-138 MineFactoryReloaded: -[1.7.10]2.8.0RC8-86 Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine Launched Version: 1.7.10-Forge10.13.2.1291

**Comment by aidancbrady** [comment]
The issue isn't with mekanism, it is with another mod using an outdated version of the ic2 API. You can easily fix it by just installing a new version of the API from ic2api.player.to:8080

**Comment by fatyg5** [comment]
Well, I'll take a stab at that. Thank you good sir!
