### ISSUE TITLE
IC2 Experimental API needed, no reference found about it

### ISSUE THREAD

**Issue by Maxiride** [aidancbrady/Mekanism#2194]
Hi, this is not exactly a bug report since I've seen here (https://github.com/aidancbrady/Mekanism/issues/2083) the same issue as mine and how to solve it.

However that issue was from the 10th of Jan and with the 7.1.1 version of Mekanism. On the website I didn't found any reference about the need of the IC2 Experimental API.. so I found this bug pretty odd since a new version of Mekanis 7.1.2 has been released.

Is just a my problem or is indeed this issue still not solved? In this case I would to suggest to mention it somewhere in the download page, because downloading the Mekanism Core, Tools and Generators is not enough =)

Edit:
Here is my paste of the crash at startup (http://paste.ee/p/HqdMq)

**Comment by unpairedbracket** [comment]
Is this the case with only Mekanism installed? If not it's because another mod is distributing the ic2 api, which they shouldn't be.

**Comment by aidancbrady** [comment]
No, it's definitely a conflict.
