### ISSUE TITLE
Mekanism Walkie Talkie not working

### ISSUE THREAD

**Issue by Poseidon5001** [aidancbrady/Mekanism#2199]
Hi, I have portforwarded the right port and voice server is enabled, yet i can not hear my friends and they can not hear me. and we are using the push to talk

Thanks!

**Comment by Poseidon5001** [comment]
Mekanism version 6.0.5.46

**Comment by Poseidon5001** [comment]
Sometimes I get messages in my console saying Mekanism voice accepted new connection, then saying unable to trace connection, followed by many lines of at java etc starting with java.lang.IllegalArgumentException: Comparis and then it gets cut off. (I use a batch file to start up server, these dont appear at all on the regular server launcher, i cant copy the text on this one and it only goes to like 1/3 of the length of my screen

**Comment by aidancbrady** [comment]
Was fixed for v7, please update!

**Comment by Poseidon5001** [comment]
Is there no dev build for v6 that works? Im using many mods together and some of them arent updated yet...
