### ISSUE TITLE
Power loss issues (Cubes)

### ISSUE THREAD

**Issue by psoftware** [aidancbrady/Mekanism#2200]
Hi,
 I hope this thread will be helpful for debugging purposes.
I'm using the latest Mekanism stable build, and I'm building an electrical power net on a minecraft map. I built a solar power farm with some Advanced Solar Panels and Ultimate Cubes that store producted energy and give that to the net. After some days, I noticed some cube decrease their energy without attached loads.

The cubes are connected to a long universal cable line that I'm building, but he's not connected to nothing: randomly, one of cubes started to decrease his amount of energy. If i break the cube cable, the cube will continue to release energy!

I think I'm doing some mistakes, but try to check this screenshots:
The buggy cubes is the disconnected cube.
![2015-03-12_22 09 11](https://cloud.githubusercontent.com/assets/9152027/6628915/dc19af06-c909-11e4-8513-3af1c80c4146.png)
![2015-03-12_22 09 15](https://cloud.githubusercontent.com/assets/9152027/6628914/dc17f558-c909-11e4-8439-8f85be6b7c5e.png)
![2015-03-12_22 09 23](https://cloud.githubusercontent.com/assets/9152027/6628933/1524ac7e-c90a-11e4-97b7-76ea75eeb7d0.png)

Can be this an issue?
Ask me all informations you need (:

**Comment by psoftware** [comment]
The cable are not green because I disabled the fancy graphic from the mod settings

**Comment by aidancbrady** [comment]
This is normal! The cubes are still connected to single cable units which can store a buffer of power. The fancy graphic would visualize this.
