### ISSUE TITLE
Option to change enrichment chamber ore to ingot output

### ISSUE THREAD

**Issue by simlhawk** [aidancbrady/Mekanism#2201]
Currently, I'm trying to change all of the ore processing machines in my pack to a 1:1 ratio, and it seems that Mek is the only mod so far that doesn't allow me to do that :/

I have a very specific reason why I would like this ( I have a custom ore processing chain), but I wouldn't want this to disable (or do anything to) the 3x, 4x and 5x Mek ore processing machines. Perhaps there could be custom ore to their respective outputs ratios in the configs for each machine?

**Comment by aidancbrady** [comment]
Check out ModTweaker, it can do exactly what you are looking for.
