### ISSUE TITLE
Chemical Washers occasionally have zero of a slurry in the input tank.

### ISSUE THREAD

**Issue by codewarrior0** [aidancbrady/Mekanism#2203]
Using Mekanism 7.1.2.179.

Chemical washer will sometimes have an input tank that reads "Copper Slurry: 0" and will not accept another slurry until the tank is manually cleared. This has happened with many ore slurries, not just copper.

To reproduce, build a dissolution chamber, and connect it to a large number of chemical washers via pressurized pipes. (I use 16 washers as that is enough to handle the dissolution chamber's output rate.) Put stacks of ore into the dissolution chamber. Eventually, one of the washers will get stuck with zero of a slurry in its input tank, instead of just having an empty tank.

![unwashed](https://cloud.githubusercontent.com/assets/307683/6647763/10133e00-c976-11e4-8ef0-cfb5cd207521.png)

I have also seen a similar problem with gas tanks connected to the washer's outputs via pipes, where an empty tank will say "Clean Copper Slurry: 0" instead of having an empty tank. Interestingly, having this zeroed tank output to another, actually empty tank will change that tank to say zero-of-a-gas and then you will have two tanks that say "Clean Copper Slurry: 0" until manually cleared.

This problem may not even be limited to chemical washers.

**Comment by aidancbrady** [comment]
Fixed for v8 :)

**Comment by codewarrior0** [comment]
I'd love to confirm that it's fixed, but #2180 is still in the way. :(
