### ISSUE TITLE
Universal Cables not transferring RF

### ISSUE THREAD

**Issue by RavynousHunter** [aidancbrady/Mekanism#2212]
Using build 185 of Mek, build 94 of Thermal Dynamics, 138 of TE, 58 of Thermal Foundation, 207 of CoFHCore, and 123 of CoFHLib.  Mek cables refuse to transport RF either from generators (with the exception of its own) or to any destination, including its own machines.  KL has said that the version of the RF API Mek's using might be out of date, hence the transference problems.

**Comment by aidancbrady** [comment]
CoFH API updated
