### ISSUE TITLE
oredict entry for osmium?

### ISSUE THREAD

**Issue by kotoroshinoto** [aidancbrady/Mekanism#2213]
I tried to tinker with something using minetweaker and it doesn't seem like osmium is registered with oredict system. Is this intentional?

**Comment by aidancbrady** [comment]
It is definitely registered - if a mod interacts with the Ore Dictionary, however, is not always the case.

**Comment by kotoroshinoto** [comment]
maybe i'm using the wrong name for things. would its name be ore:ingotOsmium for instance?

**Comment by aidancbrady** [comment]
Just ingotOsmium for an osmium ingot.

**Comment by laz2727** [comment]
There's a hidden mode in NEI that shows all oredicted stuff.

**Comment by UndeadZeratul** [comment]
@aidancbrady the "ore:" part is specifically for minetweaker.  when setting up variables or references ore dictionary entries, you'd input a \<ore:ingotOsmium\>

**Comment by kotoroshinoto** [comment]
must've been doing some seriously stupid spelling errors or capitalization derps. Thanks for the prompt response.

**Comment by kotoroshinoto** [comment]
just to show what I was trying to do:

val os_nugget = <AgriCraft:nuggetOsmium>;
val MEK_os_ingot = <Mekanism:Ingot:1>;

val os_nugget = <ore:nuggetOsmium>;
os_nugget.add(os_nugget);

val os_ingot = <ore:ingotOsmium>;
os_ingot.add(MEK_os_ingot);


recipes.addShaped(MEK_os_ingot * 1, [[os_nugget, os_nugget, os_nugget], [os_nugget, os_nugget, os_nugget], [os_nugget, os_nugget, os_nugget]]);

its not happy with this. Though it IS happy if I use the explicit non-ore-dict entries to add the same recipe. It says something about a truncated class file XD.

Perhaps I should seek help from the minetweaker devs.

**Comment by kotoroshinoto** [comment]
maybe if you added your own nuggets and oredicted those it would solve the issue once agricraft adjusts itself to the new version of mek XD

**Comment by unpairedbracket** [comment]
@laz2727 this is relevant to my interests - how would I access this hidden mode?

**Comment by laz2727** [comment]
I don't remember exactly, play around with settings available from
inventory a bit.

**Comment by grimallq** [comment]
@unpairedbracket It's not part of NEI itself. It's added by NEI Addons or NEI Integration. Check their configs.
