### ISSUE TITLE
[v8] Factories from v7 worlds revert to smelteries.

### ISSUE THREAD

**Issue by codewarrior0** [aidancbrady/Mekanism#2214]
As of 749c579bb3e1080be06232dab655fb06eceb4dab, all factories in a world played with Mek v7 will revert to Smelting factories when played in v8. They may in fact be generic "untyped" factories since none of the faces of the factory block show the smeltery face.

**Comment by aidancbrady** [comment]
Ah, yes - some NBT stuff was refactored so you may want to make some initial backups of your world before upgrading.  v8 was initially intended to be released on 1.8, so I was a bit more rough with my changes.

**Comment by codewarrior0** [comment]
Closed, and won't fix? Making a backup doesn't solve the problem that the factories are broken when I upgrade to v8.

I develop MCEdit and I can easily get you NBT data for the machines in question. At a glance, it looks like the `recipeType` field is getting reset to 0 after being played in v8. And also, it looks like all factories in v7 use `AdvancedSmeltingFactory` as the tile entity ID?
