### ISSUE TITLE
Basic I/O non-working issue

### ISSUE THREAD

**Issue by Minion0ne** [aidancbrady/Mekanism#2215]
I have my setup all lined up and cannot seem to get them to Input. my energized smelter will output to a chest placed beside it, but otherwise nothing will accept input from any of the other machines.

are there any suggestions as to what i need to do? all machines are set up the exact same way.

Edit:
Images seem to not be showing up. I have my left (as i'm looking at it) dark red, right is Dark Blue. all else is grey, autoeject is on, strict input is off.

**Comment by aidancbrady** [comment]
Machines will not accept items that they can't process.  Make sure you are feeding into the right machines.  If you are, post screenshots and I'll try and help.

**Comment by Minion0ne** [comment]
i'm using gold ore in the purification factory
![image](https://cloud.githubusercontent.com/assets/11524320/6712209/5c2c81b6-cd59-11e4-80c7-7b3e2edfe907.png)
![image](https://cloud.githubusercontent.com/assets/11524320/6712265/a4b03de2-cd59-11e4-9b7f-688c709b2e83.png)
