### ISSUE TITLE
Cardboard boxes can break "unbreakable" blocks

### ISSUE THREAD

**Issue by thraaawn** [aidancbrady/Mekanism#2219]
A hardness of "-1" is considered unbreakable. Cardboard boxes allows moving those unbreakable blocks, which basically makes them breakable even though they shouldn't be.

See Forge's Block.setBlockUnbreakable()

**Comment by halvors** [comment]
Ok, so this allows you to break bedrock? That's a problem :(

**Comment by aidancbrady** [comment]
Bedrock was hard coded to be unbreakable. However, I actually already implemented the block hardness check for v8, though, so this is no longer an issue :)

**Comment by kotoroshinoto** [comment]
it lets you move things that are supposed to require advancements in tech or magic to move as well, like thaumcraft's nodes.
