### ISSUE TITLE
Missing CodeChickenCore for v8 in dev enviroment.

### ISSUE THREAD

**Issue by halvors** [aidancbrady/Mekanism#2220]
Missing CodeChickenCore for v8 in dev enviroment.

I think there is some missing Gradle dependcies here. Or is it any other build steps that i don't know about?

http://pastebin.com/5G48qcZE

**Comment by kotoroshinoto** [comment]
when I tried to build it, I didn't have to do anything other than run gradle FullBuild.

**Comment by halvors** [comment]
Yeah i know. That works, but i was trying to run it from eclipse.

**Comment by aidancbrady** [comment]
This hasn't changed since v7.  I just reference the CCC library whenever I make a new eclipse workspace.

**Comment by halvors** [comment]
Ok :)
