### ISSUE TITLE
[Dev-branch 8.0.0] Server-side crash from attempting to load tickable sound class

### ISSUE THREAD

**Issue by kotoroshinoto** [aidancbrady/Mekanism#2223]
heres the crash log
http://paste.fedoraproject.org/199562/42669190

**Comment by halvors** [comment]
Have the same crash, here is my crashlog: http://pastebin.com/9eDvf5WR

**Comment by halvors** [comment]
Seems that some recipe stuff somehow is referencing client side stuff.

**Comment by kotoroshinoto** [comment]
looking at the code in WasherRecipe its not immediately apparent to me HOW its referencing client stuff.

**Comment by kotoroshinoto** [comment]
stacktrace references these lines:

public FluidInput waterInput = new FluidInput(new FluidStack(FluidRegistry.WATER, TileEntityChemicalWasher.WATER_USAGE));

this(new GasInput(input), new GasOutput(output));

**Comment by kotoroshinoto** [comment]
Perhaps it interacts with the chemical washer class somehow causing the server to attempt loading the client side sound stuff?

**Comment by aidancbrady** [comment]
New tile sound implementation is a bit rough with its client references, I'm trying a fix but it's acting weird.  I'll push a fix as soon as I figure it out.

**Comment by kotoroshinoto** [comment]
src/main/java/mekanism/common/tile/TileEntityNoisyElectricBlock.java has the import for mekanism.client.sound.IResettableSound; which is likely involved in this.

**Comment by aidancbrady** [comment]
Yes. The import won't necessarily matter though unless it is referenced...

**Comment by kotoroshinoto** [comment]
Yeah, it seems to happen the INSTANT TileEntityChemicalWasher is loaded.

**Comment by kotoroshinoto** [comment]
looks like line 22 might be the culprit.

**Comment by kotoroshinoto** [comment]
In the entityNoisyelectric class i mean

**Comment by kotoroshinoto** [comment]
the sound member variable has type IResettableSound which extends import net.minecraft.client.audio.ITickableSound;

**Comment by aidancbrady** [comment]
Fixed

**Comment by kotoroshinoto** [comment]
is the code in an uncommittable state atm? I notice there is no new commit, so as of yet , can't test for further bugs.

**Comment by aidancbrady** [comment]
There we go, forgot to push ^^

**Comment by kotoroshinoto** [comment]
odd... now i'm getting a buildcraft related crash that I wasn't getting before.

**Comment by kotoroshinoto** [comment]
http://paste.fedoraproject.org/199748/26707473/

**Comment by unpairedbracket** [comment]
Does that happen without Mekanism installed? Also, @aidancbrady, I figured out a solution to the server-side sound issues that works and seems to avoid the issues you were encoutering, and doesn't require the usage of a wrapper class. Shall I revert it before I pull, or go with my solution in a merge?

**Comment by kotoroshinoto** [comment]
yes, without mekanism it launched.

**Comment by aidancbrady** [comment]
@unpairedbracket, just revert and add your change - my fix was definitely messy :P

**Comment by kotoroshinoto** [comment]
buildcraft.api.transport
used in the following files:
src/api/java/buildcraft/api/transport/PipeWire.java:package buildcraft.api.transport;
src/api/java/buildcraft/api/transport/IExtractionHandler.java:package buildcraft.api.transport;
src/api/java/buildcraft/api/transport/IPipeConnection.java:package buildcraft.api.transport;
src/api/java/buildcraft/api/transport/IPipeConnection.java:import buildcraft.api.transport.IPipeTile.PipeType;
src/api/java/buildcraft/api/transport/package-info.java:package buildcraft.api.transport;
src/api/java/buildcraft/api/transport/IPipePluggable.java:package buildcraft.api.transport;
src/api/java/buildcraft/api/transport/IPipe.java:package buildcraft.api.transport;
src/api/java/buildcraft/api/transport/IPipeTile.java:package buildcraft.api.transport;
src/api/java/buildcraft/api/transport/IStripesPipe.java:package buildcraft.api.transport;
src/api/java/buildcraft/api/transport/IStripesHandler.java:package buildcraft.api.transport;
src/api/java/buildcraft/api/transport/PipeManager.java:package buildcraft.api.transport;
src/api/java/buildcraft/api/gates/IGate.java:import buildcraft.api.transport.IPipe;

not sure yet what the error might be.

**Comment by kotoroshinoto** [comment]
I put the crash report and the other message into a new issue, since i'm not certain it has anything at all to do with the sound problem.
