### ISSUE TITLE
[Dev 8.0.0] buildcraft pipes related crash

### ISSUE THREAD

**Issue by kotoroshinoto** [aidancbrady/Mekanism#2224]
http://paste.fedoraproject.org/199748/26707473/

buildcraft.api.transport

used in the following files:
src/api/java/buildcraft/api/transport/PipeWire.java:package buildcraft.api.transport;
src/api/java/buildcraft/api/transport/IExtractionHandler.java:package buildcraft.api.transport;
src/api/java/buildcraft/api/transport/IPipeConnection.java:package buildcraft.api.transport;
src/api/java/buildcraft/api/transport/IPipeConnection.java:import buildcraft.api.transport.IPipeTile.PipeType;
src/api/java/buildcraft/api/transport/package-info.java:package buildcraft.api.transport;
src/api/java/buildcraft/api/transport/IPipePluggable.java:package buildcraft.api.transport;
src/api/java/buildcraft/api/transport/IPipe.java:package buildcraft.api.transport;
src/api/java/buildcraft/api/transport/IPipeTile.java:package buildcraft.api.transport;
src/api/java/buildcraft/api/transport/IStripesPipe.java:package buildcraft.api.transport;
src/api/java/buildcraft/api/transport/IStripesHandler.java:package buildcraft.api.transport;
src/api/java/buildcraft/api/transport/PipeManager.java:package buildcraft.api.transport;
src/api/java/buildcraft/api/gates/IGate.java:import buildcraft.api.transport.IPipe;

not sure yet what the error might be, since grep only found it in the API files. 

are those API files up to date?

**Comment by kotoroshinoto** [comment]
Caused by: java.lang.NoSuchMethodError: buildcraft.api.transport.PipeManager.registerPipePluggable(Ljava/lang/Class;Ljava/lang/String;)V

signature on buildcraft's github file : 
public static void registerPipePluggable(Class<? extends PipePluggable> pluggable, String name)

your copy of the api seems to be missing it...

**Comment by kotoroshinoto** [comment]
is the homebaked jar supposed to have the API classes inside it?

**Comment by kotoroshinoto** [comment]
By which I mean, the buildcraft codechicken  cofh  dan200  ic2  invtweaks   micdoodle8  powercrystals  rebelkeithy directories, not the mekanism ones.

**Comment by unpairedbracket** [comment]
It shouldn't, no. I have encountered the issue that IntelliJ IDEA's build system can put its classes (which necessarily do include the API classes) in the same directory as gradle puts its build classes (which should not) prior to packaging. Try removing ./build/classes and rebuilding?

**Comment by kotoroshinoto** [comment]
seems like that might have been the issue.
