### ISSUE TITLE
[7.1.2.185] Possible cross-mod issue with storage drawers

### ISSUE THREAD

**Issue by Belgabor** [aidancbrady/Mekanism#2225]
I had an odd issue with the Mekanism logistical system and the new storage controller of Storage Drawers.
Full story of the incident:
thephoenixlodge/Regrowth-Stuff#18

I was later able to reproduce it in SSP, although not reliably (includes stacktrace):
jaquadro/StorageDrawers#52

**Comment by aidancbrady** [comment]
No way this can me on my end - there's some form of faulty ISidedInventory implementation going on by the Storage Drawers.  I simply iterate over the list of slots given by getAccessibleSlotsFromSide(), the crash is basically saying that the list returned contains missing element(s).

**Comment by jaquadro** [comment]
Mekanism makes an assumption that all slot numbers are less than the length of the slot array.  While I have not encountered an issue with other transport systems I've tested, I feel like I'm the only mod challenging that assumption, and so I've changed the behavior on my end.
