### ISSUE TITLE
[8.0.0] Client-side code being accessed by server causes crashes

### ISSUE THREAD

**Issue by kotoroshinoto** [aidancbrady/Mekanism#2226]
Previously the sound error: https://github.com/aidancbrady/Mekanism/issues/2223

now this one: http://paste.fedoraproject.org/199790/71315814

**Comment by kotoroshinoto** [comment]
sorry, forgot to copy the URL, fixed it.

**Comment by unpairedbracket** [comment]
^That's the BuildCraft API issue crash, I think you got the wrong link.

**Comment by kotoroshinoto** [comment]
oops

**Comment by kotoroshinoto** [comment]
fixed the original comment

**Comment by unpairedbracket** [comment]
Hmm, that's odd. getRenderType shouldn't be called on the server side, I'm pretty sure, but it's not ```@SideOnly(Side.CLIENT)```ed in the Block source, so I guess that is our issue?

...5 minutes later...

I've just had a look at EU's issue tracker, multiple people have reported this to RWTema, and apparently it's used by the vanilla server. I'll move it to not be client-only in Mekanism code, then.

**Comment by kotoroshinoto** [comment]
Is there an alternate solution or was there code for that that WAS set to client only that was causing a crash?

**Comment by unpairedbracket** [comment]
Our getRenderType() was assuming it was only going to be called on the client side, and was referencing our ClientProxy class (which *is* client side-only), so causing crashes on the server-side when EU called getRenderType() on the server side. I've now moved the fields it was referencing to the common proxy, which is available on the server side.

**Comment by kotoroshinoto** [comment]
Solar panels did it too.
should probably go through all the machines and make sure your fix gets applied
@unpairedbracket

**Comment by kotoroshinoto** [comment]
when i place machines in the world that make noise, it crashes server

**Comment by unpairedbracket** [comment]
Yeah, I'll go through them all and check. Thanks for helping us smooth all this over before release.

**Comment by unpairedbracket** [comment]
Fixed Generators, and an issue with reactor controllers. Let me know if you find any more

**Comment by kotoroshinoto** [comment]
oh i dont mind, I really like mekanism ;D

**Comment by aidancbrady** [comment]
Closing as I don't see where else this could mess up.  If it does, though, please comment here and I'll reopen!
