### ISSUE TITLE
[Dev 8.0.0] Feature inquiry

### ISSUE THREAD

**Issue by kotoroshinoto** [aidancbrady/Mekanism#2227]
Was the choice to have "dump excess" only be available in the canisters and not the separators intentional? (to avoid wasted power by users?) its not like I can't achieve essentially the same effect by adding a canister to the line or anything. I'm just curious.

**Comment by aidancbrady** [comment]
I'll leave this open - it is kind of strange that Gas Tanks can dump excess but separators can't.

**Comment by aidancbrady** [comment]
Done!

**Comment by kotoroshinoto** [comment]
should probably include a check so that if both tanks are nearly full it lets them fill up or get as close as it can to full and THEN stops, (so it doesn't waste power running forever if there is nowhere for EITHER output to go).

**Comment by kotoroshinoto** [comment]
Oh and if you could make the buttons toggle in opposing directions using right/left click, that would be neat. (avoiding the  "dumping" rather than "dump excess" mode would be useful
