### ISSUE TITLE
[8.0.0] External bug related to mekanism -- Ender IO's gas conduits broken

### ISSUE THREAD

**Issue by kotoroshinoto** [aidancbrady/Mekanism#2228]
Likely due to changes in your gas API. Just letting you know. I already created an issue with them to let them know about it.

**Comment by kotoroshinoto** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/2110

linking it here for easy access.

**Comment by aidancbrady** [comment]
Thanks!  Closing, as it is indeed an API compatibility issue.  I'm sure EnderIO will update whenever it can.
