### ISSUE TITLE
[8.0.0] Tooltip onMetallurgic infuser material shows classname and @# instead of value

### ISSUE THREAD

**Issue by kotoroshinoto** [aidancbrady/Mekanism#2231]
PRobably didnt de-reference whatever the int short or byte value was (i dont know how you store it, as i haven't looked)

**Comment by aidancbrady** [comment]
What exactly is the issue?  All tooltips are showing up fine for me.

**Comment by kotoroshinoto** [comment]
I'm not sure why, but when i fill in the material (the colored bar), and mouse over it, i dont see a value and the proper name for what is in it.

**Comment by aidancbrady** [comment]
Ah!  I see now.  Fixed!
