### ISSUE TITLE
[8.0.0] Teleporter packet error.

### ISSUE THREAD

**Issue by halvors** [aidancbrady/Mekanism#2234]
When connecting to a server with a teleporter in the chunk. It throws an error and instant disconnects the player.

Crash log: http://pastebin.com/6khdX1h7

**Comment by halvors** [comment]
@aidancbrady I believe you rewrote this stuff recently, right?

**Comment by halvors** [comment]
Think i narrowed down the issue:

public FrequencyManager getManager(Frequency freq) on line 191 in TileEntityTeleporter returns null if(owner == null || freq == null). This seems to cause the line described in the stacktrace to crash.

**Comment by halvors** [comment]
Hmm. What's strange is that i actually can't reproduce this in an new world. Have to be some NBT data for v7 portals that is messing this up. But could cause potential issues with users upgrading to v8 and crashing because of this.

**Comment by aidancbrady** [comment]
Indeed it is.  Just added a check for v7 teleporters, should be well now :)

**Comment by halvors** [comment]
Excellent :)
