### ISSUE TITLE
[8.0.0] Digital miner is broken when applying upgrades

### ISSUE THREAD

**Issue by halvors** [aidancbrady/Mekanism#2239]
Digital miner is broken. Seems to be related to speed upgrades, but when no speed upgrades is applied it mines a whole stack in seconds.

So think something broke during the new v8's upgrade module handling.

UPDATE:
Done some more debugging now. Seems that it also get messed up and unable to mine blocks when applied upgrades to and when it's breaked and replaced out in world. Maybe some NBT data getting corrupted?
When replaced into world it often mines 1 block then stops mining.

**Comment by aidancbrady** [comment]
Yes, fixed.  I had two goofs in my new filter code.  Expect a commit soon!

**Comment by halvors** [comment]
Nice.
