### ISSUE TITLE
[8.0.0] Worlds played in v7 have broken factories

### ISSUE THREAD

**Issue by codewarrior0** [aidancbrady/Mekanism#2240]
Still not fixed as of 763aef4fd02c9f1e5c01fec72dfbff8d7cf2218e.

All factories from worlds made with Mek 7.1.2.179 turn into unconfigured smelting factories with blank faces when played in v8. 

Factories in v7:
![v7](https://cloud.githubusercontent.com/assets/307683/6741591/ed5e9f10-ce2c-11e4-8571-1ec9090af402.png)

Factories in 763aef4fd02c9f1e5c01fec72dfbff8d7cf2218e:
![v8](https://cloud.githubusercontent.com/assets/307683/6741594/f80121a4-ce2c-11e4-8b57-148013e9e6e4.png)
This was an Injecting factory before.  (And also, it looks like the Metallurgic Infuser lost its rotation setting too.)

**Comment by aidancbrady** [comment]
Yes - there is sadly not much I can do to fix this.  I am putting a statement up warning users about this issue on my website when I release.

**Comment by codewarrior0** [comment]
That's disappointing.

**Comment by aidancbrady** [comment]
You may be able to get around it by keeping the factories in your inventory before updating - the issue should only occur when a factory is loaded as a block in v8.

**Comment by aidancbrady** [comment]
Scratch all that - I managed to find a fix that prevents factories from becoming corrupt on world load.

**Comment by codewarrior0** [comment]
You're on the right track! As of d3df5c5ce7a6b1866f4397b9867d657035133d71 the factories keep their type and have the right block models (and the infusers keep their rotation too), but the side configuration did revert to the defaults, as you might expect.

The last thing to do is migrate the old side configuration and at least apply it to the new configuration for transmitting items.

![sideconf](https://cloud.githubusercontent.com/assets/307683/6742699/f752f90e-ce35-11e4-8480-210294a77fc5.png)

**Comment by codewarrior0** [comment]
Oh, and one more thing. Migrate the upgrades ;)

**Comment by aidancbrady** [comment]
Just pushed a commit that should properly transition custom side item configuration, mind testing?  I'll look into speed/energy upgrades now :)

**Comment by aidancbrady** [comment]
Upgrades should now be migrated too!

**Comment by codewarrior0** [comment]
Ooh, so close.
```
java.lang.IndexOutOfBoundsException: Index: 5, Size: 5                                                      
	at java.util.ArrayList.rangeCheck(Unknown Source)                                                         
	at java.util.ArrayList.get(Unknown Source)                                                                
	at mekanism.common.tile.component.TileComponentConfig.getOutput(TileComponentConfig.java:125)             
	at mekanism.common.tile.TileEntityFactory.func_94128_d(TileEntityFactory.java:906)                        
	at mekanism.common.util.TransporterUtils.isValidAcceptorOnSide(TransporterUtils.java:68)                  
	at mekanism.common.multipart.PartLogisticalTransporter.isValidAcceptor(PartLogisticalTransporter.java:139)
	at mekanism.common.multipart.PartSidedPipe.canConnectToAcceptor(PartSidedPipe.java:719)                   
```

The old values of `config#` don't quite line up with the new ones. My best guess is to find the `SideData` in `sideOutputs` whose `slots` has the old value of `config#`, and store the index into `sideOutputs` as the new value in the bytearray.

**Comment by codewarrior0** [comment]
The old colors are GREY ORANGE DARK_GREEN PURPLE DARK_RED DARK_BLUE

The new colors are GREY DARK_GREEN PURPLE DARK_RED DARK_BLUE

So it looks like you just have to subtract 1 when the old side config is >0. Hang on, I'll give it a try.

**Comment by aidancbrady** [comment]
Just pushed the fix - I'm pretty sure you're right.

**Comment by codewarrior0** [comment]
Yep, that did the trick! Great work! As of b09620213726206008574f5d61b99ebb8eadc38b, all my factories, infusers, and other machines have the same side configuration as before.

Though, if I could ask you for one more thing? <sub>Migrate the auto-eject setting?</sub>

**Comment by aidancbrady** [comment]
Done :)
Let me know if I can do anything else.

**Comment by codewarrior0** [comment]
Wonderful. My entire ore processing chain now survives the v8 transition completely intact!

Except for a minor hangup with the Chemical Crystallizer's output faces getting changed. But the fix for that is kind of hairy. Subtracting 1 from the old side config only works for the generic Factory faces, and since each of the other machine types has its own set of `SideData`s, you'd have to have TileComponentConfig know which type of machine it is migrating side data for... and know all of the old->new mappings for all the different machines. And I'll bet neither of us know all of that. Icky.

But just having all of the Factories survive the transition is going to make a lot of people happy. Thanks for getting this fixed.

**Comment by aidancbrady** [comment]
Of course!  Thanks for your help along the way.
