### ISSUE TITLE
v8 Localization

### ISSUE THREAD

**Issue by aidancbrady** [aidancbrady/Mekanism#2241]
Mekanism v8 needs a new round of localization updates - quite a bit has been added.

**Comment by aidancbrady** [comment]
Russian is done.

@Sakarias-Longhorn, @Mr-tanaka3, @al-myr, @puyo061, @Mrkwtkr, @mymagadsl, mind providing updated translations? :)

**Comment by aidancbrady** [comment]
@Vexatos, we could also use a German translation.

**Comment by aidancbrady** [comment]
@Mr-tanaka3, @Mrkwtkr and everyone else, make sure you do the changes on the development branch.

**Comment by Vexatos** [comment]
I'm on it!
I'm quite busy right now, so it might take a day or two.

**Comment by Adaptivity** [comment]
Also calling @TheVikingWarrior and @DragonsLover it might take more time for your translations but you might be interested in it. I'll also send another PR with Russian update today.

**Comment by halvors** [comment]
Will PR a Norwegian translation soon.

**Comment by Vexatos** [comment]
@Adaptivity It's a German word, just don't translate it, pretend it was a scientific name.

**Comment by aidancbrady** [comment]
Closing, now that the brunt of this is done.
