### ISSUE TITLE
[8.0.0] WorldGenSalt related crash.

### ISSUE THREAD

**Issue by halvors** [aidancbrady/Mekanism#2242]
WorldGenSalt related crash. Not sure when this happends, but i guess when new chunks are generated.

http://pastebin.com/1V2f1HxN

**Comment by aidancbrady** [comment]
No clue how this could happen.  Does it happen regularly, or was it a one time thing?

**Comment by halvors** [comment]
I think one time thing. I was a trip in the nether, then teleporten to spawn with /spawn and was teleported 1000 block offset from spawn. That was when the error occured.

**Comment by aidancbrady** [comment]
I have a feeling this is a transition-related issue.  If it occurs again, let me know.
