### ISSUE TITLE
Salination plant breaks on server load

### ISSUE THREAD

**Issue by PsionicArchon** [aidancbrady/Mekanism#2248]
I am using the latest version of Mekanism.

I've noticed that every time I reboot the server I need to fly up to the salination controller and click the 'salination plant' button. Until I do this the controller reads as incomplete. 

I'm not sure why it's happening but it's gumming up my 5x processing setup.

**Comment by codewarrior0** [comment]
They seem to be fragile. I have to click that button every time I come back from the nether, or even sometimes after taking a long trip away from my base. Would be nice if they would auto-assemble after the first time.

**Comment by PsionicArchon** [comment]
It should only disassemble and reassemble when it detects a block update.

**Comment by codewarrior0** [comment]
Right.

If you need an example of a robust multiblock, look at [BigReactors](https://github.com/erogenousbeef/BigReactors).

**Comment by aidancbrady** [comment]
This can no longer occur in the changes that come with v8.

**Comment by codewarrior0** [comment]
Confirmed! In v8, salin- err, solar evaporation plants will auto-assemble!
