### ISSUE TITLE
[8.0.0] AE2 crafting recipes disabled

### ISSUE THREAD

**Issue by codewarrior0** [aidancbrady/Mekanism#2249]
Using 96a692256873e9db04ae59781b9948b2a5af5c02 with ~~appliedenergistics2-rv2-beta-8~~ appliedenergistics2-rv2-beta-14

Nearly all of the AE2 crafting recipes are disabled. Only happens when Mekanism is loaded. I'm still investigating this, but I'm opening the issue early to see if anyone else is having the same problem.

~~Disabling Mek integration in AE2's cfg does not help.~~

Issue occurs on newly created worlds and is not restricted to the world I was playing.

Issue occurs with only AE2 and Mek installed.

~~Tried using `git bisect` to find out which commit introduced the issue, but the sheer number of commits which either don't build or don't run made it impossible.~~

**Comment by codewarrior0** [comment]
HA HA HA, oh wow. I must have made a mistake at some point, because disabling Mekanism integration in AppliedEnergistics2.cfg actually DOES fix the issue.

Looking at the Mek integration in AE2, I can't imagine what part of it would cause *almost all AE2 crafting recipes* to stop working. I'm pinging @thatsIch to let him know about this.

**Comment by codewarrior0** [comment]
May as well ping @yueh too.

**Comment by codewarrior0** [comment]
Oh, it must be aborting all of the recipe registration after it hits this error:

```
 java.lang.NoClassDefFoundError: mekanism/api/RecipeHelper
 	at appeng.integration.modules.Mekanism.addCrusherRecipe(Mekanism.java:48)
 	at appeng.recipes.handlers.MekCrusher.register(MekCrusher.java:69)
 	at appeng.recipes.RecipeHandler.injectRecipes(RecipeHandler.java:114)
 	at appeng.core.Registration.initialize(Registration.java:591)
 	at appeng.core.AppEng.init(AppEng.java:156)
```

Getting the Mek integration shored up would be good, but making the recipe handler more robust so it can keep going after this kind of error would be even better.

**Comment by aidancbrady** [comment]
What is strange is that RecipeHelper still exists, and is packaged with Mekanism even though if no longer serves much of a purpose.  Unless another mod contains a fragmented Mekanism API (which still shouldn't trigger that), I don't know what changes I made that could have triggered this.

**Comment by aidancbrady** [comment]
Ah, I take that back - the package structure was changed.  An integration update will fix it.  In the meantime, I'll put a notice on my website letting people know of possible API incompatibilities.

**Comment by thatsIch** [comment]
You have an api.jar on a maven by chance? Would make it tons easier, since we do not need to package our own version of your mod to compile against it.

**Comment by thatsIch** [comment]
We had to compile our own API and provide on our own Maven,
no warranty
