### ISSUE TITLE
v8 b509 Crash when clicking w Dropper in Portable Tank GUI

### ISSUE THREAD

**Issue by Greylocke** [aidancbrady/Mekanism#2253]
Forge 1291, only Mek b509 loaded, no other mods.
1. place portable tank on the ground
2. right-click to open the tank GUI
3. with Dropper in hand, r-click on the fluid gauge.
4. Crash.

Error log here: http://pastebin.com/MQq3DWMQ

**Comment by aidancbrady** [comment]
Strange - I thought scala libraries were shipped with forge. I'll see what I can do.

**Comment by unpairedbracket** [comment]
They should be - Forge Multipart is written in Scala, so for it to work it'd need Scala libs

**Comment by unpairedbracket** [comment]
Can we not just use java.util.Arrays though? I suspect it's just a mis-import?

**Comment by aidancbrady** [comment]
We can, that's the fix I'm about to push.
