### ISSUE TITLE
v8 Missing Enrichment Chamber Recipe

### ISSUE THREAD

**Issue by mikestancato** [aidancbrady/Mekanism#2256]
At the moment it is impossible to create an enrichment chamber.

**Comment by aidancbrady** [comment]
Can't reproduce, I was just able able to create an Enrichment Chamber with the provided recipe. Did you disable the Enrichment Chamber in the config file?

**Comment by mikestancato** [comment]
B:EnrichmentChamberEnabled=true

I can see the Enrichment chamber in game. Went to the wiki to try manually producing and the recipe didn't create it. Playing on SkyFactory2 with only mekanism installed (as extra mods).

**Comment by unpairedbracket** [comment]
Do you have NEI and does the recipe given by it correspond to that on the wiki? Does it even give a recipe?

**Comment by mikestancato** [comment]
I am using NEI. When I press "R" on the enrichment chamber, I get nothing.

**Comment by aidancbrady** [comment]
What mods do you have installed?

**Comment by mikestancato** [comment]
I am playing skyfactory2. I removed "redstone arsenal" and added mekanism. Other than that, everything else is default.

**Comment by aidancbrady** [comment]
If you're willing to test, remove all mods but Mekanism and then try again.  May be an integration issue.

**Comment by mikestancato** [comment]
For science. I will. :D Give me a moment.

**Comment by halvors** [comment]
@aidancbrady Do you know why it's behaving like that?

**Comment by aidancbrady** [comment]
I have no clue - like I said, I really need someone to test with only Mekanism installed.

**Comment by aidancbrady** [comment]
Hang on a moment - are you both on SMP?

**Comment by mikestancato** [comment]
I tested with just mekanism installed, works fine. But couldn't weed out why it wouldn't work with a default skyfactory2 installation.

**Comment by aidancbrady** [comment]
I just experienced a server-sided issue of similar nature that I believe I have a fix for.

**Comment by mikestancato** [comment]
That is great new Aidan. Thanks for looking into it!

**Comment by aidancbrady** [comment]
Fixed the issue of machines not being able to be taken out of the crafting table.  As for the issue where they simply show up, it is certainly a compatibility issue.  Thanks for all your help!
