### ISSUE TITLE
v8 Factory upgrades being directly pulled out by export conduit.

### ISSUE THREAD

**Issue by mikestancato** [aidancbrady/Mekanism#2257]
Unsure if this is a bug or a feature, but if you try to add speed/energy upgrades to factories while they are connected to export conduits, the upgrades will get sucked out before getting into the machine.

**Comment by aidancbrady** [comment]
Not sure how this could be happening - the upgrade side configuration was removed in the first place.  Looking into.

**Comment by halvors** [comment]
I did experience the same thing last night. Seems like the occured only when 
machine is processing and inserting upgrades at the same time.

**Comment by aidancbrady** [comment]
Tried to reproduce with Mekanism Logistical Transporters and everything worked as intended.  The only way this could happen is if those export conduits were not checking getAccessibleSlotsFromSide() before attempting to take items from slot 0.
