### ISSUE TITLE
[8.0.0] Impossible to craft Chemical Crystallizer.

### ISSUE THREAD

**Issue by halvors** [aidancbrady/Mekanism#2258]
It's impossible to craft the Chemical Crystallizer. It shows up when trying to craft but i'm unable to pull it out of the crafting bench. Seems like it suddenly doesn't exist anymore.

**Comment by aidancbrady** [comment]
Merging with #2256

**Comment by aidancbrady** [comment]
@halvors, would you test this without any other mods installed?
