### ISSUE TITLE
v8 Compatibility with Thaumic Energisitics

### ISSUE THREAD

**Issue by katur239** [aidancbrady/Mekanism#2259]
After installing Mekanism v8, it causes Thaumic Energitisics 0.8.9.0b-rv2 to error out on post-init.

[B#283]  [16:50:20] [Client thread/ERROR] [FML]: The following problems were captured during this phase
[B#283]  [16:50:20] [Client thread/ERROR] [FML]: Caught exception from thaumicenergistics
[B#283]  java.lang.NullPointerException
[B#283]  	at thaumicenergistics.registries.AEAspectRegister.registerTEItems(AEAspectRegister.java:1001) ~[AEAspectRegister.class:?]
[B#283]  	at thaumicenergistics.registries.AEAspectRegister.registerAEAspects(AEAspectRegister.java:1119) ~[AEAspectRegister.class:?]
[B#283]  	at thaumicenergistics.ThaumicEnergistics.postInit(ThaumicEnergistics.java:124) ~[ThaumicEnergistics.class:?]
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
[B#283]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
[B#283]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
[B#283]  	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) ~[modpack.jar:?]
[B#283]  	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
[B#283]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
[B#283]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
[B#283]  	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
[B#283]  	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
[B#283]  	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
[B#283]  	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
[B#283]  	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
[B#283]  	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[modpack.jar:?]
[B#283]  	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[modpack.jar:?]
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
[B#283]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
[B#283]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
[B#283]  	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
[B#283]  	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
[B#283]  	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
[B#283]  	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
[B#283]  	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
[B#283]  	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
[B#283]  	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694) [Loader.class:?]
[B#283]  	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288) [FMLClientHandler.class:?]
[B#283]  	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541) [bao.class:?]
[B#283]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) [bao.class:?]
[B#283]  	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
[B#283]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
[B#283]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
[B#283]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
[B#283]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]

**Comment by aidancbrady** [comment]
Please report this to the Thaumic Energistics tracker :)
