### ISSUE TITLE
crash on loading converted world

### ISSUE THREAD

**Issue by Greylocke** [aidancbrady/Mekanism#2260]
I made a test world with all the items and blocks from Mek7 Generators and Mek7 (core). I then updated to Mek8 (b509). Upon loading I got a message that "Mekanism:FrictionBoots" was missing.

Once I passed that screen, the world crashed. Log can be found here: http://pastebin.com/bH3NeBvZ

The "boots missing" error can be seen here: https://www.dropbox.com/s/2stth7firbg42sk/Mek8_BootsMissing.png?dl=0

**Comment by aidancbrady** [comment]
Update to the very latest Mekanism - the first log was actually fixed already :)
Ignore the friction boots error.  I just changed the hardcoded ID to "free runners."
