### ISSUE TITLE
world don't load

### ISSUE THREAD

**Issue by Corvorosso** [aidancbrady/Mekanism#2261]
after update to V8 i can't load any world, not even new world.
the client don't crash but remain on main screen.

if i close the program and open the console on launcher i read this.

Client> [23:19:08] [Server thread/ERROR] [MekanismGenerators]: Skipping event FMLServerStoppedEvent and marking errored mod MekanismGenerators since required dependency Mekanism has errored
Client> [23:19:08] [Server thread/ERROR] [MekanismTools]: Skipping event FMLServerStoppedEvent and marking errored mod MekanismTools since required dependency Mekanism has errored

full console log

http://pastebin.com/jVB2baqY

**Comment by aidancbrady** [comment]
Fixed - will be in v8.0.1 :)
