### ISSUE TITLE
v8 trying to craft solar panel in tinker's crafting station crashes client (might not be specific to tinkers crafting table)

### ISSUE THREAD

**Issue by kotoroshinoto** [aidancbrady/Mekanism#2262]
dunno if this happens in ssp, and I don't yet know if its specific to that table or just a recipe error.

**Comment by kotoroshinoto** [comment]
http://paste.fedoraproject.org/200778/42689195/

**Comment by kotoroshinoto** [comment]
it happens when i click to place the last item to make the recipe

**Comment by codewarrior0** [comment]
>Mekanism-1.7.10-8.0.0.homebaked.jar

This problem was fixed recently. Try the release build?

**Comment by kotoroshinoto** [comment]
doing a git pull and a fresh build, will test

**Comment by kotoroshinoto** [comment]
Almost didn't notice the version number increment XD.

But yeah, it works now.
