### ISSUE TITLE
Extra Utilities pipes crash when placed next to Dynamic Tank

### ISSUE THREAD

**Issue by jsaggers** [aidancbrady/Mekanism#2264]
Built a Mekanism tank, wanted to put liquids into the tank via Extra Utilities pipes, as soon as I placed a pipe next to the tank it crashed, was next to the main tank wall, tank seem to get back into the world, just keeps crashing.

Pastebin http://pastebin.com/Tt8cb4Ah

First time I have used github so I hope I posted correctly.

**Comment by aidancbrady** [comment]
Should be fixed in v8 :)
