### ISSUE TITLE
v8 Metallurgic infuser has tooltip inventory: no if that refers to stored infusion material, it doesn't keep it.

### ISSUE THREAD

**Issue by kotoroshinoto** [aidancbrady/Mekanism#2271]
if i wrench the machine it still loses the material, is there a different method i'm supposed to use to pick it up that retains it? IF that isn't what inventory refers to, what am I missing?

When i put the machine down again, it doesn't have the infusion material it had when picked up.

**Comment by codewarrior0** [comment]
I think a Cardboard Box is your only option.

Inventory only refers to the actual inventory slots. It doesn't keep the infuser material or any gases in an Injector or Purifier. But it SHOULD keep all of that when you wrench it!

**Comment by kotoroshinoto** [comment]
oh thats neat XD
didn't know that was a thing
