### ISSUE TITLE
v7>>8 Converted Items are changed, removed, or crash

### ISSUE THREAD

**Issue by Greylocke** [aidancbrady/Mekanism#2273]
Converting from Mek7 to Mek8 will cause some items to change or be removed.
**These items will be changed:**
Copper Dust >> Lead Dust
Diamond Dust >> Tin Dust
Dirty Obsidian Dust >> Dirty Lead Dust
Obsidian Clump >> Lead Clump
Obsidian Shard >> Lead Shard
Obsidian Crystal >> Lead Crystal
Refined Obsidian Dust >> Copper Dust
Steel Dust >> Silver Dust

**These items will be invalid in Mek8 and cause a crash if selected**
Lead Clump
Dirty Lead Dust
Lead Shard
Lead Crystal
Silver Dust
Sulfur Dust
Tin Dust

**This item will be lost after converting to Mek8 but will not cause a crash**
Freerunners

**Comment by Greylocke** [comment]
Here's the world I used for testing the 7>>8 conversion https://www.dropbox.com/s/meszs4b3pk4f20z/Mek7%20AllBlocks.zip?dl=0

**Comment by aidancbrady** [comment]
I won't be able to do anything about the items being lost, but at least I can prevent a crash - what is the log when you mouse over?

**Comment by Greylocke** [comment]
I placed Mek7 Silver Dust in a chest, then updated to Mek8. When I mouseover the silver dust, I get this crash: http://pastebin.com/4xHKKj7S

You can see the same, if you open the attached world with Mek8 and mouseover one of the invalid items in a chest

**Comment by aidancbrady** [comment]
Fixed the crash :)
