### ISSUE TITLE
V8 unable to take precision sawmill off the crafting bench

### ISSUE THREAD

**Issue by kotoroshinoto** [aidancbrady/Mekanism#2275]
when i try to remove it, the item goes right back onto the crafting output.

**Comment by kotoroshinoto** [comment]
after giving myself one with NEI for further testing I note that NEI says the sawdust output from log->wood should be 100%, but I get none.

**Comment by kotoroshinoto** [comment]
ditto for the stick recipe should've been ~25% unless the ratio changed.

**Comment by kotoroshinoto** [comment]
(probably should be a way to feed sticks or wood to the crusher or a grinder or even the sawmill or something to get only sawdust out as an intended product rather than a byproduct.

**Comment by halvors** [comment]
Sane as  #2258. Happeds with almost every machine.

**Comment by aidancbrady** [comment]
Fixed precision sawmill issue. Merging with #2256

**Comment by kotoroshinoto** [comment]
did the no sawdust issue get fixed in the process of fixing this?

also is there a method to explcitly grind wood to obtain sawdust/woodpulp as the intended product rather than a byproduct?
