### ISSUE TITLE
v8 Game Crash with current release of EnderIO Gas Conduit.

### ISSUE THREAD

**Issue by mikestancato** [aidancbrady/Mekanism#2277]
EnderIO + Mekanism are the only mods installed. Tried hooking up an EnderIO gas conduit up to any mekanism devices cause game to crash once the conduit is set to "Extract" "Always Active".

**Comment by kotoroshinoto** [comment]
known problem, gas API changed and enderio hasn't compensated for the change yet

**Comment by mikestancato** [comment]
Alright thanks. Didn't see it on github so figured I would add. Thanks kotorshinoto.

**Comment by kotoroshinoto** [comment]
https://github.com/aidancbrady/Mekanism/issues/2228

its set to closed since its enderio's fault technically
