### ISSUE TITLE
Strange Mekanism v8 issue with NEI and Applied Energistigs2

### ISSUE THREAD

**Issue by accessdenied0** [aidancbrady/Mekanism#2280]
Dear Mekanism team,

I'm here to report this issue to you. I use the latest version of NEI, AE2 and Mekanism... I looked so far but no-one else seem to have had this issue jet... I'm also not sure what it causing it... so far I see it, it seems to be a issue with the Recipe Handler of Mekanism v8. I did not have the issue with v7.1.1.127...
I guess I have to mention that I use ModTweaker (1.5) [and with it MineTweaker (3.0.9C)] as well..

I hope you can help,

access_denied

**Comment by aidancbrady** [comment]
What is the issue?

**Comment by accessdenied0** [comment]
Dear aidancbrady,

I'm such a derp... Now I was so focused to write this issue down that I forgot to link my crash report... http://pastebin.com/xZimU9XS

I'm so sorry and thanks for the help,

access_denied

**Comment by aidancbrady** [comment]
Seems to be an integration issue.  Wait for AE2 to update its integration with Mekanism and it should be solved :)

**Comment by accessdenied0** [comment]
Thank you very much.

**Comment by accessdenied0** [comment]
Dear aidancbrady,

I guess AE isn't the full reason for these crashes... I disabled the Mekanism Integration in the mean time for the fix, but It crashed again... now with a other crash report: http://pastebin.com/wU20PGrN

It seem to be a problem with NEI in general... at least with the newest version: 1.7.10-1.0.4.90-universal... or do I mistaken here? In addition the mod authors from AE2 want something from you... https://github.com/aidancbrady/Mekanism/issues/2249

thank you for your work,

access_denied
