### ISSUE TITLE
Divided textures of factories

### ISSUE THREAD

**Issue by Radviger** [aidancbrady/Mekanism#2281]
Hi, dear mekanism developers!
I'm playing with mekanism a long time and I noticed that different types of factories has a one texture.
Its really hard to make out factory type and will be very nice if different factories has themselves different textures.
Thanks!

**Comment by aidancbrady** [comment]
It would be hard to create all the assets necessary for each factory type, but I will consider adding the recipe type into the factory's title itself - I think that would be a good compromise :)

Thanks for the suggestion!

**Comment by Radviger** [comment]
Maybe some waila cmpat would be a good compromise?
