### ISSUE TITLE
issues between mek and enderIO

### ISSUE THREAD

**Issue by nightstalker6669** [aidancbrady/Mekanism#2282]
http://pastebin.com/CJA2xMQb

http://pastebin.com/84Ey2yDL

getting these crashes when booting up in my test server. seems to be that enderIO gas conduits, with oxygen in them from electrolytic seperators just doesn't play nicely. i'm sure thats probably not the only thing. i don't know if this is an enderIO problem, or a mek problem. but seeing as i just updated to mek 8 on my test server, to play with it, i'm posting it here.
using latest V8 mek, and enderIO

**Comment by aidancbrady** [comment]
EnderIO needs to update its Mekanism integration :)

**Comment by nightstalker6669** [comment]
ok thanks, i'll let them know.

**Comment by unpairedbracket** [comment]
I've made our gas interfaces backwards-compatible. That should fix this issue in 8.0.1.

**Comment by Cracks777** [comment]
when will this be released?

**Comment by Cracks777** [comment]
or do i need to be membership to get access to dev version?

**Comment by unpairedbracket** [comment]
I think 8.0.1 should be out later today, unless we find any pressing issues with it.

**Comment by Cracks777** [comment]
ok thanks so mmuch, just got the reactor setup and its so amazing.
