### ISSUE TITLE
mekanism 8 crash on startup

### ISSUE THREAD

**Issue by oks1998** [aidancbrady/Mekanism#2284]
http://openeye.openmods.info/crashes/1107c0bed965dc09756d845b11178caf
/
http://pastebin.com/JQg9qfDd

after updated to version 8 it crash...

**Comment by Zaflis** [comment]
Thaumic Energistics is not compatible with something? It's not reported on that side yet:
https://github.com/Nividica/ThaumicEnergistics/issues

**Comment by CaptainPepperjack** [comment]
I'm having the same issue with thaumic energistics after updating: http://pastebin.com/sFtRm2mx

**Comment by HeliosDK** [comment]
http://pastebin.com/GWKxbu2E
Have the same problem.

**Comment by HeliosDK** [comment]
http://pastebin.com/vEnR287Y 
And it seems that it isnt cause by mekanism.common.item.ItemDust.func_77667_c ?

Isnt dependent on java version

**Comment by jburrows82** [comment]
Confirmed fixed in latest Mek-dev (#536), so hang tight for release!
