### ISSUE TITLE
Setting reactor temperature to view in Fahrenheit causes display to not update

### ISSUE THREAD

**Issue by Kodos-Atoz** [aidancbrady/Mekanism#2285]
Temperature still rises fine, everything works, but it sticks at -450 F for some reason.  This is across the board, on the heat screen as well as the stats screen.

**Comment by aidancbrady** [comment]
@unpairedbracket, know what may be causing this?

**Comment by aidancbrady** [comment]
Fixed, nevermind! Silly issue.
