### ISSUE TITLE
[8.0.0] Digital Miner block replacement broken

### ISSUE THREAD

**Issue by halvors** [aidancbrady/Mekanism#2286]
The Digital Miner's block replacement mechanism is broken.

The old global block replacement just says "All is well!".

And the new per filter block replacement is broken, i'm unable to set anything at all, it gets lost when saving.

**Comment by aidancbrady** [comment]
Unable to reproduce, I just set up a system with the per-filter block replacement and it worked fine.  What exactly is the issue?

**Comment by halvors** [comment]
The issue is basically that i can't set the "All is well!" to replace stone like on v7. Maybe that is not possible anymore. But i also can't set each filter to replace stone. It simply doesn't store the setting when saved.

**Comment by halvors** [comment]
@aidancbrady Also i'm running Mekanism-1.7.10-8.0.0.188 what build are you on?

**Comment by aidancbrady** [comment]
You can no longer see a global replace. The replace block goes in the right "ghost slot" of a filter GUI. Make sure you hit save after changing it. Does that work?

**Comment by halvors** [comment]
Yes tried that. But when saving the filter "forgets" all about the replace boolean and the actual Block to replace with.

**Comment by halvors** [comment]
Also keeping a global function would be nice since it kinda a hassle to specify in each filter.

**Comment by aidancbrady** [comment]
I'm not experiencing that, strange. I'll check again as soon as I'm in front of a computer.

**Comment by halvors** [comment]
Hmm. And as mentioned you're on version 8.0.0.188?

**Comment by EvulOne** [comment]
I think I might know what he's referring to.  Steps to reproduce:
Place a digiminer.
Add a new filter (Lets use *stone as example)
Place a block in the replace box, and set the "require replace" to yes.
Press save.
Click on your filter again to see its settings, the block you chose as replace is now empty, and the "require replace" is now set to 'no' again.

**Comment by halvors** [comment]
@EvulOne Exactly that is the issue.

**Comment by aidancbrady** [comment]
Fixed - it apparently only happens with OreDict filters.
