### ISSUE TITLE
Reactor set up, lasers going - block tick and crash

### ISSUE THREAD

**Issue by piedpipr314** [aidancbrady/Mekanism#2289]
Ticking block entity, Pastebin included:
http://pastebin.com/XKCaMQ9L
I haven't exactly figured out how to use this reactor yet, so it may be user error.  The reactor controller that I had did have a Hohlraum in it's inventory slot (empty).  Trying to figure out what does what.  I had to manually MCedit the block out to load the world again.

**Comment by aidancbrady** [comment]
Hey!  In order to trigger the reaction, the hohlraum has to be filled with D-T fuel, which can be created via a Chemical Infuser.  The crash is my fault, though - I shouldn't assume that an inserted hohlraum contains some amount of fuel.  Fixed in development, expect the fix later today!
