### ISSUE TITLE
Missing dust, clumps and shards

### ISSUE THREAD

**Issue by grimuars** [aidancbrady/Mekanism#2291]
After update from v.7 to v.8 (8.00.526) ALL shards, dust & clumps made with Mekanism machines (except iron and lead) turned into "unnamed" items (see screenshot).

Is it possible to transform them back? With new shards, dust and clumps all right.

**Comment by grimuars** [comment]
![gpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/6021595/6766621/51c34b48-d01e-11e4-9dff-5ed08e232efe.jpg)

**Comment by Greylocke** [comment]
check this out for more information https://github.com/aidancbrady/Mekanism/issues/2273
TL;DR version: to be safe, clear your in-process ores (dusts, clumps, shards, etc)  before updating.
