### ISSUE TITLE
WAILA tooltip wrong for Induction Cell, Provider

### ISSUE THREAD

**Issue by Greylocke** [aidancbrady/Mekanism#2293]
This may be a WAILA issue, but WAILA shows all the Induction Cells as Basic Induction Cell and all the Induction Providers as Basic Induction Provider

Mek .188, Forge 1291, WAILA 1.5.9

**Comment by aidancbrady** [comment]
Curious - does the same happen with energy cubes?

**Comment by unpairedbracket** [comment]
Does breaking them yield the correct tier?

**Comment by Greylocke** [comment]
All 5 energy cubes are recognized by WAILA correctly.

I broke an Ultimate Induction Cell. In my inventory it shows as an Ultimate Induction Cell. When I place it, WAILA says it is a Basic Induction Cell.

**Comment by aidancbrady** [comment]
Fixed!
