### ISSUE TITLE
Metalurgic Infuser won't craft - Server - 8.0.0.188

### ISSUE THREAD

**Issue by yepidoodles** [aidancbrady/Mekanism#2294]
I've double and triple and even quadruple checked all my configs to make sure nothing but the mod itself is restricting the crafting. We're using the latest version as on the main site.

- Alice/ yepidoodles
- DragonTechMC

**Comment by aidancbrady** [comment]
Fixed in development.

**Comment by yepidoodles** [comment]
What do you mean by that? And the crusher is doing the same
