### ISSUE TITLE
Electric Pump UI: Heavy Water qty out of bounds

### ISSUE THREAD

**Issue by Greylocke** [aidancbrady/Mekanism#2295]
In the Electric Pump UI, the qty of Heavy Water is extending outside the boundary of the field. Looks like the line needs to wrap or the qty field dropped down a line.

screenshot attached https://www.dropbox.com/s/7itwds75tfl3vh2/HeavyWaterOutsideField.png?dl=0

**Comment by aidancbrady** [comment]
Fixed!
