### ISSUE TITLE
Mekanism v8 adding to FTB Infinity

### ISSUE THREAD

**Issue by oXDE4THROWXo** [aidancbrady/Mekanism#2297]
I added mekanism 7 to FTB infinity 1.2.0 ... worked fine. Now when i go to add Mekanism 8 i get an immediate client crash.  It seemed like it was an AOBD problem so i updated that to 2.5.0 and now im getting yet another crash.. here is the 2 crashes i got so far...

Before AOBD update: http://pastebin.com/muF0PWQx
After: http://pastebin.com/e20QWWsc

**Comment by Greylocke** [comment]
That seems to be an issue on the Thaumic Energistics side of things https://github.com/aidancbrady/Mekanism/issues/2259

**Comment by Greylocke** [comment]
I take that back. Looks like Nividica and Aidan worked it out in a dev build https://github.com/Nividica/ThaumicEnergistics/issues/147
