### ISSUE TITLE
Heat Generators

### ISSUE THREAD

**Issue by EvulOne** [aidancbrady/Mekanism#2299]
I've noticed that a single heat generator doesn't seem to put out the indicated J/t (When powered passively at least)

I have one surrounded by 5 lava blocks, and it claims to be producing 25J/t, however my oxidizer with energy upgrades, consuming 15 J/t is running out of power.  It is consuming more than the heat generator is putting out.  Some images:
http://imgur.com/a/Cb7Qh

It could also be an issue with energy upgrades, and/or the gui's display?
I've attempted similar setups with other machines.  An osmium compressor with 5 energy upgrades claims to consume 23.7 J/t, however a single heat generator cannot keep it powered.

Bio generators, conversely, seem to be accurate in their output claims.  A machine consuming just shy of the 350 J/t produced from a bio gen, is able to be sufficiently powered by it.

Is there some way I can further test this, and/or can someone else look into it please?

EDIT: forgot to mention the version I'm using.  This is Mekanism 8.0.0
Also I had initially thought it might be due to the energy upgrades, but further testing with other generators leads me to believe it's the heat generator itself.

**Comment by aidancbrady** [comment]
Ah, yeah - the output display is based on the old generation system. Fixed in development - it now shows exactly how much it is producing.

**Comment by unpairedbracket** [comment]
The reason for this is that I changed the Heat Gen to behave more like a non-ideal [Carnot engine](http://en.wikipedia.org/wiki/Carnot_heat_engine), partially as a test of the thermal energy system that I was designing and implementing, but was pushed back to Mek v9 as I wasn't able to finish it in time for v8's release. I forgot I'd altered the Heat Gen, so didn't change it back.

Long term, I'd like to make a generator (possibly a new one, possibly change the heat generator) that works properly like a Carnot Engine, generating power based on the temperature difference between two sides (i.e. the player will need to keep one side as cold as possible, and the other as hot as possible). I could then possibly have the current heat generator just burn items to produce heat, then transmit it to a Carnot Generator to produce power. @aidancbrady (and anyone else), do you think this is a good idea?

**Comment by laz2727** [comment]
Like RP thermophile?

**Comment by aidancbrady** [comment]
Sounds great!  One suggestion - I would replace the "Generator" term in this new Heat Generator with something else, I think "Generator" should be reserved for blocks that produce heat.  Maybe "Heat Producer"?  Then we could name the actual generator a "Carnot Generator."

**Comment by unpairedbracket** [comment]
I didn't know about that, I've never really used RedPower, but that does look like the kind of thing I was thinking of, yes.

**Comment by unpairedbracket** [comment]
I agree about not calling machines that don't generate power "Generator"s, maybe something like "Thermal Burner"?

**Comment by laz2727** [comment]
Solid Fuel Heater?

**Comment by unpairedbracket** [comment]
We could potentially also turn the Gas-burning generator into a Heater, and make most low-level generation into ways to heat up the Carnot Generator? Not sure about the Bio Generator, we could maybe do the same with that?

**Comment by laz2727** [comment]
Guys, ic2-exp.jar

**Comment by unpairedbracket** [comment]
Good point, maybe best to not accidentally copy ic2.
I've just realised that the solar evaporation plant would possibly work well as a heat-based thing, given it works with temperature. Not sure how much people would want to change though.

**Comment by unpairedbracket** [comment]
And I guess it could possibly be annoying for early-game if many of the generators suddenly need an extra stage to get any power out of them?

**Comment by EvulOne** [comment]
That's pretty much exactly what I was thinking haha.  IC2 exp branch is all of the things thermal related.

I guess it comes down to how far towards realism do you want to go though.  IC2's heat mechanics are literally "Block X heats block Y with direct contact"  It adds a second machine needed for every step.

**Comment by laz2727** [comment]
Make it an upgrade instead of change. Heat pipes, heaters working by
themselves with lower efficiency, rp-like heat'n'cold system.

**Comment by EvulOne** [comment]
Yeah early on especially it becomes tedious to have a secondary block for every generator.

Perhaps an option in the generator's gui, either you can burn fuels in them and generate power as normal, or you can have them accept coolant of sorts and have it output hot coolant?
That way, you could use them as currently, with an "inefficient internal turbine" in theory, or you could run them and pipe their heat into a more efficient turbine that would be its own block?

**Comment by unpairedbracket** [comment]
Kind of like BR's reactors? That could work. 

I have already designed and implemented a heat transmitter that works kind of like universal cables, is pretty physically accurate and looks quite nice (The code is in Mekanism, but is disabled due to not being finished yet), but may or may not be really CPU-intensive compared to other transmitters. The way I simulate heat transfer is based on the [heat equation](http://en.wikipedia.org/wiki/Heat_equation) so should work pretty well in terms of being physically accurate.

**Comment by unpairedbracket** [comment]
The Carnot Engine would be one way of getting power out of heat; other planned uses for heat would be a big multiblock steam boiler (which is again already implemented but has issues so is hidden) with matching turbine, and I guess we could do some kind of directly heat-powered smelter? It's still mostly in the planning stages at the moment, so it's still fluid in terms of what we do with it.

**Comment by laz2727** [comment]
Then you should have a multiblock heater too. And it would be awesome if it
could be something like BR dev doc.

**Comment by unpairedbracket** [comment]
BR dev doc? I assume you mean [the roadmap](https://github.com/erogenousbeef/BigReactors/blob/master/Roadmap.md) but I'm not sure what you're referring to within that?
The Fusion reactor will probably act like a kind of complicated multiblock heater, replacing it's current steam generation functionality, but a big multiblock burner thing could be cool too.

**Comment by laz2727** [comment]
Actually, i'd prefer it with generators being heated and cooled down in the
world, like rp, and pipes transferring just heat by being filled with gold
or something.
...Dont mind me. I just really like pre-frame rp.
