### ISSUE TITLE
Crash when pressing U on an item

### ISSUE THREAD

**Issue by erkro1** [aidancbrady/Mekanism#2304]
When I press U on an item in NEI (Seared Bricks in this case) it crashes my game and points to Mekanism.

Full crash log:
http://pastebin.com/5U9kCkFy

**Comment by aidancbrady** [comment]
This is an integration issue - some mod is attempting to utilize the Mekanism recipe handler in the outdated way.  I assure you that if you tested this with only Mekanism you would not experience this issue.
