### ISSUE TITLE
Mek v8 Enrichment Chamber bug

### ISSUE THREAD

**Issue by Stette** [aidancbrady/Mekanism#2306]
Enrichment Chamber refuses to take any form of input from chests, hoppers etc. I think this is due to some problems mentioned here on Github earlier about integration problems with AE2, bacause when I tried to upgrade my Enrichment Chamber to a factory (to hopefully remove the bug) the game crashed as i pulled the factory out of the crafting table, see crash-log:

http://pastebin.com/nRGvDqTi

**Comment by aidancbrady** [comment]
After doing a bit of code-digging, there is no way that this error could occur in a situation other than a transition issue.  Breaking and placing the block may fix the issue.
