### ISSUE TITLE
Build error on windows gradle related

### ISSUE THREAD

**Issue by kotoroshinoto** [aidancbrady/Mekanism#2307]
for some reason its trying to do an md5sum of a *.lock file that is likely still open with a filehandle at the time.

> Failed to create MD5 hash for file G:\MekanismDev\.gradle\2.3\taskArtifacts\cache.properties.lock.

It happens both in Msys(mingw shell) and CMD.
I dont know if this is a gradle bug, or something in your gradle makefiles/setup, or something purely windows-driven.

**Comment by unpairedbracket** [comment]
I've never seen anything like that, but I dev on Linux (and I believe the buildserver is too) and I think Aidan's on OS X - the Unices tend to be less awkward about more than one process touching a file than Windows is.
If anyone else seeing this compiles with gradle on Windows, does it work for you?

**Comment by kotoroshinoto** [comment]
I had no trouble building on my fedora linux systems, whatever it is seems to be windows related.

**Comment by unpairedbracket** [comment]
This would appear to be a gradle/Windows issue, related to (or the same as) https://issues.gradle.org/browse/GRADLE-2967, I don't think there's anything we can do about it.

**Comment by unpairedbracket** [comment]
Does the build get far enough to find jars in /outputs?

**Comment by kotoroshinoto** [comment]
Looking back at it, it appears there are jars there, so it MIGHT not be a big deal, what should the expected sizes be?

**Comment by unpairedbracket** [comment]
Mekanism should be about 14MB, Generators 200kB and Tools 32kB

**Comment by kotoroshinoto** [comment]
looks about right then.

Still, very odd error
