### ISSUE TITLE
[v8] Crash on server - world previously using Mek v7

### ISSUE THREAD

**Issue by b0bst3r** [aidancbrady/Mekanism#2309]
http://pastebin.com/U6sitF4r

Looks highly related to https://github.com/aidancbrady/Mekanism/issues/2273

**Comment by enterprise12nx** [comment]
Im updating my 24/7 server right now, will report back.

**Comment by enterprise12nx** [comment]
My server started up fine and is working using Mekanism V8

**Comment by aidancbrady** [comment]
Fixed in development
