### ISSUE TITLE
Flamethrower sound vs. water

### ISSUE THREAD

**Issue by katur239** [aidancbrady/Mekanism#2314]
I am not sure if this is intended or not. But when you shoot water with a flamethrower it has a ton of reverb. It sounds like its looping the sound too fast or something.

Also, if you are too close to blocks, the animation for the flamethrower shakes.

**Comment by aidancbrady** [comment]
As for #1, that sound you hear is the "smoke" effect of when the flame hits the water.
For #2, that's simply the "usage" animation that Minecraft displays when right clicking a block with an item. Just ignore it :)
