### ISSUE TITLE
List of Mekanism Crashes

### ISSUE THREAD

**Issue by enterprise12nx** [aidancbrady/Mekanism#2320]
A bunch of crashes mekanism has caused using V8 on 24/7 dedicated server.
http://pastebin.com/fDfgDC1N
http://pastebin.com/sbzAXtKZ
http://pastebin.com/4JxxfPya
http://pastebin.com/mJSW4314

Are all of these fixed in the latest version?

**Comment by aidancbrady** [comment]
Crash #4 has been fixed in v8.0.1 - I'll take a look at the rest tomorrow.

**Comment by enterprise12nx** [comment]
ok thanks :)
i probably shouldnt have update to V8 so hastily xD hope all the major bugs found can be fixed fast so my server is ok!

**Comment by aidancbrady** [comment]
Alright, stayed up a bit later and these all should be fixed for the upcoming 8.0.2 :)
