### ISSUE TITLE
Seismic Reader scans the wrong block column if z-coord is positive

### ISSUE THREAD

**Issue by EzerArch** [aidancbrady/Mekanism#2321]
Mekanism version: 1.7.10-8.0.0.188

Seismic Reader scans the wrong block column if z-coord is positive, probably it's a round-down/up problem.

Example 1:
Stand on a block at Z=248.5 (grass block), reads block at Z=247.5 (plastic road block).

![2015-03-22_19 00 01](https://cloud.githubusercontent.com/assets/6743303/6774187/956f3c8e-d0fb-11e4-84cd-c9c90a9a7f42.png)

Example 2 (no bug):
Stand on a block at Z=-8.5 (grass block), reads correctly.
![2015-03-22_19 21 24](https://cloud.githubusercontent.com/assets/6743303/6774186/956ef328-d0fb-11e4-9a62-b6d38c1b8d77.png)

**Comment by Kodos-Atoz** [comment]
Apologies for the offtopic comment, but I must ask; What resource pack is that?

**Comment by EzerArch** [comment]
> Apologies for the offtopic comment, but I must ask; What resource pack is that?

[Aeon](http://www.planetminecraft.com/texture_pack/aeon-1355543/) (by TheSparko) and [Aeon Extension Patch](http://www.planetminecraft.com/texture_pack/aeon-extention-patch/) (by myself).

**Comment by aidancbrady** [comment]
Fixed
