### ISSUE TITLE
Jetpack causes bspkrs' StatusEffectHUD icons to render incorrectly

### ISSUE THREAD

**Issue by EzerArch** [aidancbrady/Mekanism#2322]
Mekanism version: 1.7.10-8.0.0.188

Mod compatibility issue with bspkrs' StatusEffectHUD. The StatusEffectHUD icons will be rendered upside-down at the upper center part of the screen when the HUD is off (F1 key), if one of the following is true:

1) If you are holding a Jetpack (armored or not).

2) if you put the Jetpack on and you are holding no idem or holding a Flamethrower or Free Runners. 

HUD on (nothing wrong):
![2015-03-23_01 49 16](https://cloud.githubusercontent.com/assets/6743303/6774614/42450ffa-d102-11e4-8666-dc29c016b1e8.png)

HUD off (a wild bug appears):
![2015-03-23_01 49 07](https://cloud.githubusercontent.com/assets/6743303/6774615/42450a32-d102-11e4-8e81-908921037658.png)

If it's not a Mekanism issue, I'll report it to bspkrs.

**Comment by aidancbrady** [comment]
Not sure how this would be affecting bspkrs, but I've made sure to push matrix in the item renderer before performing transformations.

**Comment by EzerArch** [comment]
Anyway, I've reposted this issue in the bspkrs' topic: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1282347-bspkrs-mods-armorstatushud-directionhud?comment=1548

Thank you.
