### ISSUE TITLE
Wind Turbine animation not scaling with power output

### ISSUE THREAD

**Issue by BBoldt** [aidancbrady/Mekanism#2323]
Hi, so I've nerfed wind Turbines a bit in the configs. Problem is, they look terrible ingame because they move so slowly. 

This is a minor issue, but it bugs me.

If you could make it so the windmill is going really fast at whatever the max power is set at, that would be perfect.

**Comment by mst3in** [comment]
That animation was/is hard to deal with, especial with many of them near by.  Lag trap.

I'd like to suggest changing the animation to a transparent disc-like thing and put that in front of it.  Some kind of effect that had the appearance of blades moving fast...without rendering the actual movement.

**Comment by aidancbrady** [comment]
The Wind Turbine animation doesn't rely at all on power output/generation, no matter what the generation level is set at it will still spin faster when at higher Y coordinates.

Though I won't change the animation, maybe I'll add a config to disable the spinning.

**Comment by mSt3in** [comment]
> Though I won't change the animation, maybe I'll add a config to disable the spinning.

This would be much appreciated!  Thank you! :)
