### ISSUE TITLE
Upgrade text unreadable w/ Small MC GUI

### ISSUE THREAD

**Issue by vixblu** [aidancbrady/Mekanism#2327]
* Mek.dev v8.0.2.550
* 1600x900

When opting for a Small GUI (in MC Options) the green text (in the Update GUI tab) regarding how many updates have been put in the machine is unreadable.
Would a mouse-over tooltip be an easy fix?

Doesn't bother too much for now, it's a small annoyance, and I could adjust the GUI when really needed (won't be a lot of times).

**Comment by fcpwiz** [comment]
Wait, where did you get v8.0.2.550?

**Comment by enterprise12nx** [comment]
Mek.dev v8.0.2.550
Donators $10+ get access to dev

**Comment by laz2727** [comment]
On my 1024x1280, it happens a lot and with literally every mod. I don't
really see a way to help this.

**Comment by aidancbrady** [comment]
Not much getting around this, sorry :(

**Comment by vixblu** [comment]
Thanks anyway, problem may be solved on my end eventually (upgrading system specs), and I don't mind the mild annoyances, it's a nice reminder of how well integrated the mod feels and plays in every other aspect!
