### ISSUE TITLE
Suggestion: Separate creative tab for Portable Tank fluids

### ISSUE THREAD

**Issue by AppleConnoiseur** [aidancbrady/Mekanism#2329]
Exactly what it says on the tin. Quality of life improvement if you got mods like Minechem installed that add a bazillion liquids.

Noticed it was quite laggy to scroll over the creative tab because of that.

![All the fluids](https://dl.dropboxusercontent.com/u/547140/pix2/2015-03-22_23.56.29.png)

**Comment by aidancbrady** [comment]
You can disable the tanks by setting the "prefilledPortableTanks" config property to false :)
