### ISSUE TITLE
[8.0.0] Digital Miner loses replacement configuration when breaked and replaced.

### ISSUE THREAD

**Issue by halvors** [aidancbrady/Mekanism#2330]
Digital Miner loses replacement configuration when breaked and replaced.

Referencing this issue #2286, similar problem. But this works now, just that the settings are not stored somehow.

**Comment by aidancbrady** [comment]
8.0.0 or 8.0.1?

**Comment by halvors** [comment]
I'm running version 8.0.1, fixed the problem in pull request #2331.
