### ISSUE TITLE
Just a note regarding Mekanism v8 and AE2 integration/bug

### ISSUE THREAD

**Issue by Stette** [aidancbrady/Mekanism#2332]
I have now tried both Mekanism *8.0.0.188*, *8.0.0.526* and *8.0.1.198*. With *8.0.0.188* AE2 recipes did NOT work, with *8.0.0.526* everything works fine (almost) but with *8.0.1.198* it's broken again.... I deleted all config before every try, still same results.

**Comment by mst3in** [comment]
Knmown issue; @aidancbrady has been closing reports like these as it isn't his bug.
