### ISSUE TITLE
Cannot Open Existent or New Worlds

### ISSUE THREAD

**Issue by TorakWolf** [aidancbrady/Mekanism#2334]
[From my original post on MinecraftForums]

For some reasons IDK, every time I try to open a world or create a new one with Mekanism v8+, I just get returned to the Main Screen, and this appear in the logs: 

http://pastebin.com/PtGmuxs8

I cut that part as I found it important ( it's where it can't load the map anymore ).

**Comment by TorakWolf** [comment]
Seriously, editing made it a dupe error. Sorry, NO SPAM!

**Comment by mst3in** [comment]
Pull out AE2 and see if it works.  That's an older version of AE2 as well...the newer one won't work yet either so don't put in beta-14...

**Comment by aidancbrady** [comment]
Update to Mekanism 8.0.1. This has already been fixed.

**Comment by aidancbrady** [comment]
Fixed

**Comment by TorakWolf** [comment]
Hum, where I can pick the fix ( or is it a hotfix that didn't change the version ) ?

Gonna test anyways!

Just curious, what is it so you guys have special AE2 compatibility ( because AE2 Spatial-Compat Addon works with both AE2 rv1 and rv2 ) ?

**Comment by TorakWolf** [comment]
Ok, I thinks it's a hotfix, because I can't download it now...

Just shows that strange page when skipping adf.ly:

http://pastebin.com/qRRN4uPy
