### ISSUE TITLE
Scuba Tank no longer works underwater

### ISSUE THREAD

**Issue by EzerArch** [aidancbrady/Mekanism#2335]
Mekanism version: 1.7.10-8.0.1.198, Forge 1291. SSP.
Other mods: NEI

Major bug. Gas Mask + Scuba Tank no longer provide the player with oxygen. Player will get hurt and drown as if he had no equipement.

![2015-03-23_23 04 35](https://cloud.githubusercontent.com/assets/6743303/6794484/16a6b2a4-d1b1-11e4-840a-995f87f77208.png)

**Comment by aidancbrady** [comment]
Yes - this is fixed in development :)

**Comment by EzerArch** [comment]
> Yes - this is fixed in development :)

Your efficiency sometimes scares me. :<
