### ISSUE TITLE
Brine does not work as a liquid when in a bucket.

### ISSUE THREAD

**Issue by TacoMage** [aidancbrady/Mekanism#2337]
If you put brine in a bucket, it cannot be manually placed into a solar evaporation unit.  The brine bucket just sits in the top slot.

Pumping with pipes still works.

**Comment by TacoMage** [comment]
Ignore that, I found the issue.

I had turned on redstone sensitivity when setting my pipes up.  Rookie move.

**Comment by aidancbrady** [comment]
Fixed in development
