### ISSUE TITLE
Laser Amplifier Derpiness

### ISSUE THREAD

**Issue by TacoMage** [aidancbrady/Mekanism#2338]
Two issues with laser amplifiers in RF mode:

1) They do not properly show stored RF values above 1.0GRF.  Above that point the readout (but not the fill bar) freezes displaying "Stored: 1.0GRF" until it's filled to 2.0 GRF.

2) Numbers put into the min and max areas are read in as Joules then converted to RF.  For instance, if I enter 50000 as the max, it sets the max to 20KRF.

**Comment by TacoMage** [comment]
Upon further inspection, this appears to be an issue with the induction array as well.  The unit does not display any change in RF level above 1.0 GRF.

**Comment by aidancbrady** [comment]
Should be fixed, thanks
