### ISSUE TITLE
Enough Induction Casing will always form a multiblock structure

### ISSUE THREAD

**Issue by TacoMage** [aidancbrady/Mekanism#2340]
Any solid cuboid structure made entirely out of Induction casing that contains at least 27 blocks will always form a multiblock structure, this includes single-block pillars.

Not sure if this is intended, but seems kinda silly.

**Comment by mSt3in** [comment]
>multiblock structure

try https://github.com/Chicken-Bones/ForgeMultipart

**Comment by laz2727** [comment]
1) I don't see why you should tell FMP

2) Why would you make pillars out of a TE block

3) Seems intended to me.

2015-03-24 13:40 GMT+06:00 mSt3in <notifications@github.com>:

**Comment by halvors** [comment]
I think there at least should be a minimum structure. Like 3x3x3 which will have space for 1 Induction Energy Cell or Induction Provider in it.

**Comment by aidancbrady** [comment]
Fixed in development.
