### ISSUE TITLE
Feature Request: Extract Power From Laser Amplifiers

### ISSUE THREAD

**Issue by TacoMage** [aidancbrady/Mekanism#2341]
It would be really neat to have a block that receives a laser beam and converts it back to power.  Specifically, since the amplifier can already receive laser power, having it interact with power cables would be great.  Would be a cool way to have wireless, and dangerous, power transmission across short distances, like to separate floors in a base, or between buildings in a complex.

Maybe not as practical as tesseracts or the like, but definitely worth some style points.

UPDATE:  Changed the request slightly based on further thinking.  This feature would be best implemented if power could be drawn out of laser amplifiers, since they can already be used to gather power from an active beam.  See my comment below.

**Comment by mSt3in** [comment]
what's a laser bean?

**Comment by halvors** [comment]
@mSt3in I think he meant laser "beam", which is a beam of light from a laser. You know?

**Comment by TacoMage** [comment]
I've been thinking about this request a little more, and I think this feature could easily be implemented if you could draw stored power out of laser amplifiers.

All you'd need to do is set the laser amp to output a max of 0 J, and then connect a cable to it to extract the power that builds up in the unit.  This would also allow you to set up amplifies so that they'd pass partial beams to other amplifies with the retained power building up in the unit for extraction.  You could do some pretty snazzy things with that kind of functionality, such as power multiple floors/buildings off of one high-power beam.

**Comment by aidancbrady** [comment]
Done in development! Thanks for the idea @TacoMage

**Comment by TacoMage** [comment]
Awesome!
