### ISSUE TITLE
Gas Network Crash

### ISSUE THREAD

**Issue by Gatzy** [aidancbrady/Mekanism#2342]
Using FTB Infinity with Mek 8.0.1.196.

http://pastebin.com/BjDf6Fgu <-- crash report

**Comment by laz2727** [comment]
Some mod uses old API, i think.

2015-03-24 14:14 GMT+06:00 Gatzy <notifications@github.com>:

**Comment by Gatzy** [comment]
Is there anything I can to do as a temporary fix?

**Comment by laz2727** [comment]
Use older mekanism version? I dunno.

2015-03-24 15:28 GMT+06:00 Gatzy <notifications@github.com>:

**Comment by aidancbrady** [comment]
Fixed in development

**Comment by Gatzy** [comment]
LOVE YOU AIDAN
