### ISSUE TITLE
[Bug?] [Custom Modpack] Can't craft Enrichment Chamber

### ISSUE THREAD

**Issue by NintendoSMASH** [aidancbrady/Mekanism#2343]
No matter what I do I can't seem to craft an Enrichment Chamber. I've tried looking on the internet for a solution, but no one else seems to have this problem. I'm using a custom modpack, made by me, for me and my friend. I'm not using a modded crafting table, nor any modded materials in the recipe (except for the ones Mekanism adds).

List of mods included: Optifine, Ars Magica 2, Applied Energistics 2, NotEnoughItems, Waila, AnimationAPI (for AM2), Backpacks, Thermal Expansion, Thermal Dynamics, Big Reactors, BuildCraft, Logistics Pipes, Enchanting Plus, EnderStorage, Baubles, ExtraUtilities, FastCraft, Thaumcraft, Thaumic Tinkerer, Forbidden Magic, JABBA, InventoryTweaks, IronChest, Magical Crops, MineFactory: Reloaded, Railcraft, Tinkers' Construct, Tinkers' Mechworks, Mantle (mainly for Tinkers'), The Twilight Forest, Natura, Random Things, Soul Shards: Reborn, Torcherino ("Time Torches that won't kill your server"), VeinMiner, Witchery, Zan's Minimap (VoxelMap), LiteLoader, and Core mods/other required mods. Also, Mekanism and its Subparts.

Any/All help is much appreciated.

![2015-03-24_05 34 16](https://cloud.githubusercontent.com/assets/11627829/6798853/773424fe-d1e7-11e4-8100-551442916e07.png)
![2015-03-24_05 34 27](https://cloud.githubusercontent.com/assets/11627829/6798872/b2210a32-d1e7-11e4-8580-a45450032cd6.png)

-Smash

**Comment by halvors** [comment]
Try updating to 8.0.1.198. It's a known issue ( #2294)
