### ISSUE TITLE
Ender io cables wont connect to mek machines or energy cubes.

### ISSUE THREAD

**Issue by Cracks777** [aidancbrady/Mekanism#2345]
![image](https://cloud.githubusercontent.com/assets/10608111/6802303/429df3ee-d1fd-11e4-9d21-b5ec5d5cff79.png)

**Comment by aidancbrady** [comment]
I'm assuming you don't have CoFHCore installed?

**Comment by Cracks777** [comment]
oh i guess not, sorry was testing some problems, ill try again,

**Comment by aidancbrady** [comment]
Yeah - I'm afraid that's how our energy system works :(

**Comment by Cracks777** [comment]
![image](https://cloud.githubusercontent.com/assets/10608111/6802471/d4eebcdc-d1fe-11e4-90f1-e4742bebf44e.png)

Any idea whats causing this, the gas conduits dont show correctly, but they work correctly. also there not in the creative inventory? more so a problem for them but just wondering.

**Comment by aidancbrady** [comment]
Yes - EnderIO needs to update their integration.

**Comment by Cracks777** [comment]
ok thank you.
