### ISSUE TITLE
Induction Matrix stops outputing power after chunk is unloaded.

### ISSUE THREAD

**Issue by halvors** [aidancbrady/Mekanism#2346]
Induction Matrix stops outputing power after chunk is unloaded. 

To fix the problem i'll have to manually break and replace the cable connected to the Induction Port. I'm using Mekanism's Ultimate Universal Cables.

**Comment by aidancbrady** [comment]
Can't reproduce - after unloading and reloading chunks, it still outputs just fine.  Are you sure the issue doesn't reside somewhere else?

**Comment by aidancbrady** [comment]
If you are in a dimension other than the overworld, this is actually a bug that has been fixed.

**Comment by halvors** [comment]
No it's in overworld. I don't really know if it's the chunk unload/reload but seems to randomly appear and i'm moving around on the server and joining/leaving.

**Comment by halvors** [comment]
It seems to just affect the output thought.

**Comment by aidancbrady** [comment]
Alright. How often does this happen?

**Comment by halvors** [comment]
I really don't know. Maybe a couple of times a day.

**Comment by aidancbrady** [comment]
Just pushed a new release that should (hopefully) solve this issue. Let me know how it works.

**Comment by halvors** [comment]
Will do :-)

**Comment by halvors** [comment]
@aidancbrady I've not experienced this after your fix, it seems to be solved on my side :)
