### ISSUE TITLE
Question regarding observations when using AE2/Mek8/ThaumicEnergistics (not really a bug report)

### ISSUE THREAD

**Issue by SniperHauss89** [aidancbrady/Mekanism#2349]
Hello I have been tinkering with the three mods that have been in question a for a few days now (ie. AE2, Mek8, and ThaumicEnergistics) and I only get the crash report (that has been reported numerous times already) with ThaumicEnergistics in with Mek8. I tried it without Mek8 and with the latest AE2 (r14) and it works but with Mek8 in it decides to crash. The question I have is how exactly is it a AE2 issue when i can load ThaumicEnergistics with the latest build of AE2 and it doesn't crash? is ti just a weird interaction between AE2 and Mek8 that doesn't kick in until you add in ThaumicEnergistics? This behavior seems strange (to me at least). any addition input far as clarification regarding this is appreciated. ;)

**Comment by Towsty** [comment]
This is referenced a few times in reports (ie #2347). 

Basically, AE2 needs to update the mek api. From what I can gather, right now some recipes and things are changed when AE loads the outdated mek api and thaumic energistics is looking for those. I believe there is a patch in the dev builds of mekanism to avoid this but its an ae2 issue at its root.
