### ISSUE TITLE
Suggestion: Oredictionarificator

### ISSUE THREAD

**Issue by Towsty** [aidancbrady/Mekanism#2350]
I would love to see the ability to pump items in and out of this block.

**Comment by aidancbrady** [comment]
This should already be possible.

**Comment by Towsty** [comment]
as of mek 8.0.2.550 it is not using extra utilities transfer nodes. Is it only possible with logistical pipes/sorters? I will update to the latest dev build and try again this evening. Thanks for the fast response!

**Comment by aidancbrady** [comment]
Ah - you're right, it's not working.  Fixing as we speak...

**Comment by Towsty** [comment]
Fantastic! Thanks!! Lovin the updates so far!

**Comment by aidancbrady** [comment]
Fixed :)
