### ISSUE TITLE
Restrictive Transporter priority higher than Bin connected paths?

### ISSUE THREAD

**Issue by mes-mc** [aidancbrady/Mekanism#2351]
Hello. I encountered a trivial phenomenon when using Restrictive Transporter and Bin.

Restrictive Transpoter's description is 
> Only used if no other paths available

But, I seems like to have been preferentially used than other Bin connected paths.

I Tried transport 27 stack items. there are screenshots of that time.

v7.1.2
start
![v7 1 2-start](https://cloud.githubusercontent.com/assets/10321884/6807198/5b0c8308-d290-11e4-96ce-f49600387e40.png)

result
![v7 1 2-finish](https://cloud.githubusercontent.com/assets/10321884/6807212/6ca69e3c-d290-11e4-9ac1-8da4b912a974.png)

v8.0.1
start
![v8 0 1-start](https://cloud.githubusercontent.com/assets/10321884/6807215/783a0b58-d290-11e4-8d92-07a41826244c.png)

result
![v8 0 1-finish](https://cloud.githubusercontent.com/assets/10321884/6807216/7d251040-d290-11e4-8c3d-7315b1de3cfe.png)

This is wrong my usage?

Thank you and sorry very bad english.

**Comment by aidancbrady** [comment]
It appears you have Round Robin mode on.  Because this is the case, the transporters will not put into account the priorities, and simply all the possible destinations instead.

**Comment by mes-mc** [comment]
Thank you fast response!
But, that test is Round Robin mode is off.

v7.1.2 is not different result Rount Robin mode on/off.
v8.0.1 is change result. this is Round Robin mode is on.
![2015-03-25_02 49 57](https://cloud.githubusercontent.com/assets/10321884/6808830/c8d7137c-d299-11e4-920f-a7868b5aba88.png)

sorry if Is wrong understanding of English.

**Comment by aidancbrady** [comment]
Huh, strange.

**Comment by aidancbrady** [comment]
Ah, yes - I actually fixed this for v8. :)

**Comment by unpairedbracket** [comment]
This still appeared to be a problem in v8 (transporter cost was only taken into account in the A* algorithm, so the shortest path was chosen to each destination, but Destinations were sorted by number of transporters, not total cost). I've now fixed that, and the shortest path is now taken as the least-time path for normal transporters.
