### ISSUE TITLE
Inventories are improperly returning null when they should not be.

### ISSUE THREAD

**Issue by KingLemming** [aidancbrady/Mekanism#2353]
We went over this one a long time ago, Aidan. ;) Vanilla doesn't return nulls and you shouldn't either:

https://github.com/CoFH/Feedback/issues/339

**Comment by aidancbrady** [comment]
Uh oh, I thought I changed all those. What machine was the Itemduct connected to?

**Comment by KingLemming** [comment]
Seems to be a logistical sorter:
https://gist.github.com/Brycey92/8796fe3139d2499b7f32

**Comment by KingLemming** [comment]
BTW, a good way to handle this is to just have a static ItemStack[] NO_SLOTS = new ItemStack {}; in your code somewhere and just refer to it whenever you need to.

**Comment by aidancbrady** [comment]
I do exactly that, actually.
Tell them to update Mekanism, they're using v7 :)

**Comment by KingLemming** [comment]
Alright then :) Awesome. I'll shut it down.
