### ISSUE TITLE
v8 Logistical transporter doesn't trigger item placement behavior in some other mods' machines

### ISSUE THREAD

**Issue by kotoroshinoto** [aidancbrady/Mekanism#2354]
Factorization packager doesn't know items are being inserted. I don't know what mechanism is different from player or hopper item placement, but the logistical transporter doesn't trigger the automatic packaging to occur when inserting items.

**Comment by aidancbrady** [comment]
I would call this a Factorization issue, considering the Logistical Transporters work with most all other mods' inventories.

**Comment by kotoroshinoto** [comment]
the problem isn't that it doesn't place the items in, its that whatever method you're using to do it doesn't  make the machine realize there is anything inside it to be checked. I don't know what it expects that enderio and thermal dynamics does differently. hoppers trigger it too.

**Comment by kotoroshinoto** [comment]
what those are supposed to do is when the # of items reaches enough for a 2x2 or 3x3 recipe (provided one exists), its supposed to craft that item and consume the number from its itemstack.

**Comment by kotoroshinoto** [comment]
The mekanism pipes put the items in, but it never checks the stacksize, so something isn't being triggered.

**Comment by kotoroshinoto** [comment]
I dont know if he has a github or not so i'll attempt to report it to them in the IRC

**Comment by kotoroshinoto** [comment]
do the pipes mark inventories as dirty when they inject the items they carry?

**Comment by aidancbrady** [comment]
Fixed!
