### ISSUE TITLE
Oredictionificator UI not intuitive, no in game guidance on how it works.

### ISSUE THREAD

**Issue by kotoroshinoto** [aidancbrady/Mekanism#2356]
I literally have no idea what i'm doing when i look at this thing.
 I click new filter and see a left and right arrow, netiher of which appear to do anything, a box which seems to accept items, but doesn't, and a text box to type in, but no clear idea of what it wants me to type.

**Comment by kotoroshinoto** [comment]
For instance I click new filter and see a left and right arrow, netiher of which appear to do anything, a box which seems to accept items, but doesn't, and a text box to type in, but no clear idea of what it wants me to type.

**Comment by kotoroshinoto** [comment]
I see there is a filter card but it doesn't seem to go inside anywhere, and note that shift right clicking takes data out and right clicking again puts data in, not that I know how to create the data.

**Comment by unpairedbracket** [comment]
The box is used to enter an OreDictionary key. When one is entered, an item matching that key can be chosen with the arrow buttons, and the machine will convert items matching that key into the one selected.

**Comment by unpairedbracket** [comment]
We probably should improve the UI though.

**Comment by kotoroshinoto** [comment]
keys as i know them would be like ore:nuggetIron would I type nuggetIron?

**Comment by kotoroshinoto** [comment]
it doesn't seem to work with some entries XD

**Comment by kotoroshinoto** [comment]
it sees dustIron but not nuggetIron

**Comment by kotoroshinoto** [comment]
or things like blockGold

**Comment by kotoroshinoto** [comment]
I figure you wanted it to be limited to ingots dust and the like, but excluding nuggets seems a bit weird.

**Comment by kotoroshinoto** [comment]
Is there any reason it can't be extended to other types of itemstacks?

**Comment by kotoroshinoto** [comment]
have it just refuse the entry if the dictionary search turns up a null.

**Comment by aidancbrady** [comment]
This is intended, as I don't want people to be able to convert between different colors of glass panes, etc.  I've just added nuggets to the list :)

**Comment by kotoroshinoto** [comment]
did you add blocks as well? might as well put those in ;p

**Comment by kotoroshinoto** [comment]
or would that require explicit checks for metal types

**Comment by kotoroshinoto** [comment]
yeah, probably would
