### ISSUE TITLE
Precision Sawmill won't take upgrades

### ISSUE THREAD

**Issue by vixblu** [aidancbrady/Mekanism#2357]
Not a need per se (for me, right now), but did notice upgrades won't go down in the Precision Sawmill (one or a stack of upgrades just rests in the upper slot). It does say it supports energy and speed upgrades.

Mek.dev 8.0.2.565

**Comment by aidancbrady** [comment]
Can't reproduce. You sure you don't already have the max amount of upgrades installed?

**Comment by vixblu** [comment]
-facepalm- indeed! I had filled it before, and didn't notice that in my updating frenzy ;-)
Thanks! :-)

**Comment by aidancbrady** [comment]
No worries :)
