### ISSUE TITLE
For some reason version 8 of Mekanism is causing ThaumicEnergestics to crash .

### ISSUE THREAD

**Issue by crunkazcanbe** [aidancbrady/Mekanism#2358]
Crash is here http://pastebin.com/YVv0qEqn
Using Mekanism V8.0.2.199
ThaumCraft 4.2.3.5
ThaumicEnergestics 0.8.9.0B
AppliedEnergestics 2 RV2 Beta 15

This crash is only with public version which I consider to be a bit more stable . It stops with any DEV version of Mekanism above 8.0.0.526. The issue is also continued here https://github.com/Nividica/ThaumicEnergistics/issues/147 where a lot of folks are having this issue . TBH its a bit odd the public Release have this issue , but the DEV versions do not . :)

Thank you!

-Crunk

**Comment by aidancbrady** [comment]
AE2 issue :)
