### ISSUE TITLE
Electrolitic Separator Server Crash 8.0.2.199

### ISSUE THREAD

**Issue by yepidoodles** [aidancbrady/Mekanism#2360]
When an electrolitic separator tries to export into a enderIO gas conduit it crashes the server - I am sending this report to the EnderIO dev as well as I don't know which mod is causing the issue

Crash report:
https://drive.google.com/file/d/0ByS9NIAvqyexQnZrUFVNSHBfLUE/view?usp=sharing

EnderIO version: 1.7.10-2.2.8.349
Mekanism Version: 8.0.2.199

**Comment by aidancbrady** [comment]
EnderIO needs to update its Mekanism API.
