### ISSUE TITLE
Digital Miner [Inverted Mode] Causes Server Crash

### ISSUE THREAD

**Issue by spawlak1** [aidancbrady/Mekanism#2364]
It appears that when using inverted mode on the miner, the server just crashes. I only know that It does not matter whether or not the digital miner is in the area of what is to be mined(i.e. above or below the area). Wish I could be of more help :/ .

**Comment by halvors** [comment]
I think this is fixed now. See #2362.

**Comment by aidancbrady** [comment]
Indeed
