### ISSUE TITLE
NEI/Mekanism compatibility issue.

### ISSUE THREAD

**Issue by AnodyneEntity** [aidancbrady/Mekanism#2365]
Not sure which mod is causing it, but my client started crashing after I updated Mekanism to 8.0.2.201

http://pastebin.com/h00Riy9T

**Comment by aidancbrady** [comment]
Not on my end - for some reason a mod is registering an invalid fluid.  You can disable Mekanism's prefilled portable tanks (where the invalid fluid was found) by disabling the property in the config.
