### ISSUE TITLE
Cannot remove upgrades from factories.

### ISSUE THREAD

**Issue by TacoMage** [aidancbrady/Mekanism#2366]
Looks like at least the elite factory has an issue where you cannot remove energy upgrades from it.  I'm betting it affects other factories and upgrades, but do not currently have time for further testing.

The factory in question was an elite enrichment chamber.

**Comment by aidancbrady** [comment]
Firstly, try updating if you're not yet on v8.0.2.

I can't reproduce this on my end.  Make sure you have room in your inventory for the upgrade to be removed.

**Comment by TacoMage** [comment]
It was with dev build 8.0.2.567, only other things loaded in the install are NEI, Waila, and Tinkers'. I'll try updating to 2.571 and see if I can replicate the issue.

I'll also have a video up tomorrow morning where I run into the bug about 15 minutes into the sequence. If it's still an issue in 571, I'll link the time-stamp where it happens so you can see all the steps leading up to it.

**Comment by TacoMage** [comment]
Yup, fixed in 2.571!
