### ISSUE TITLE
Fully upgraded chemical infusers don't output fast enough.

### ISSUE THREAD

**Issue by Glockshna** [aidancbrady/Mekanism#2369]
I can't get gases out of a chemical infuser fast enough to keep up with its output. I tried using Pressurized Tubes, EnderIO Conduits and as a last resort tried connecting the machine directly to a tank and a factory and it will not output its product as fast as it produces it and it's nowhere near producing more than the machines can accept.

All the machines in the chain have every upgrade they accept maxed out.

Screenshots, if they help.

http://puu.sh/gPJ64/ae965f3576.jpg
http://puu.sh/gPJ64/ae965f3576.jpg

Again this happens connected directly to a machine/tank or via tubes.

**Comment by aidancbrady** [comment]
Bumped up in development :)

**Comment by Escain** [comment]
Seems that the max production is with 5 speed upgrades, adding 6, 7, or 8 speed upgrades does not seems to improve (even seems to reduce the production)

**Comment by pupnewfster** [comment]
Your issue probably is that you have no energy upgrades so the energy requirement can't be fully met for the buffer.
