### ISSUE TITLE
NEI CRASH only when Mekanism v8 is installed.

### ISSUE THREAD

**Issue by bfowler1321** [aidancbrady/Mekanism#2370]
Ikeep crashing whenever i use NEI and click a recipe or usage. It
doesn't matter if i use the keyboard shortcuts or if i search and click,
any item-i crash every single time.
Single Player
ATLAUNCHER

just updated mekanism to 8.0.2.201
When Mekanism isn't installed nei works fine

**Comment by aidancbrady** [comment]
Log please

**Comment by aidancbrady** [comment]
Closing, as this most definitely is some form of interaction issue. I'll continue to provide support.

**Comment by bfowler1321** [comment]
I know it's already closed but here's the crash
http://pastebin.com/FgGZzKRQ
