### ISSUE TITLE
Factory installers not keeping settings.

### ISSUE THREAD

**Issue by Aulton** [aidancbrady/Mekanism#2371]
Yo, finally got around to testing my suggestion! Fund out they don't keep the factory's settings when installed (Input/output OR upgrades)

**Comment by Aulton** [comment]
Also, the purification chamber when upgraded it doesn't accept gas upgrades, though it says they're supported.

**Comment by aidancbrady** [comment]
You're right!  Working on it right now.

**Comment by aidancbrady** [comment]
Fixed in development! :)

**Comment by Aulton** [comment]
Thank you!
