### ISSUE TITLE
Cables draining energy/Dynamic Tanks empty when leaving/entering world. 

### ISSUE THREAD

**Issue by imsupercereal4** [aidancbrady/Mekanism#2372]
Whenever I connect cables to my Big Reactor reactor it appears to instantly drain the reactor of all power and does not allow the reactor to build up RF. It continuously drains it so fast that the reactor is unable to ever generate a buffer. I disconnected all machines, leaving only the cables, and it still drained the power out of the reactor. I let the reactor run for ten minutes and the buffer did not fill at all. 

http://imgur.com/a/qgYvg

Additionally Dynamic Tanks appear to have their inventories wiped when you leave the world. 

http://imgur.com/a/Jlb62

Please let me know if I can provide more information to assist. This is by far my favorite mod. 

EDIT: Running FTB Infinity.

**Comment by aidancbrady** [comment]
The first issue you mentioned is simply due to Universal Cables now having a much greater energy buffer than they did before.

As for the second issue, it is currently fixed in development :)

**Comment by imsupercereal4** [comment]
How big of a buffer do they have? 

I've been letting it run for a half hour now and it hasn't started charging the item as seen below. 

http://imgur.com/a/hZVve

**Comment by aidancbrady** [comment]
Huh, something is wrong.  Right click with the cable network with a network reader if you don't mind.

**Comment by imsupercereal4** [comment]
http://imgur.com/H1Bi6l2

Huh, that's a lot of power needed.

**Comment by codewarrior0** [comment]
Happens when taking a portal to the nether and back, or traveling a long ways away and coming back.
