### ISSUE TITLE
Crafting Bug with AE2

### ISSUE THREAD

**Issue by Steelpower900** [aidancbrady/Mekanism#2374]
When Mekanism 8.0.2.201 installed are Applied Energistics rv2 more recipes prepared.

**Comment by Aulton** [comment]
...What? If you're asking why the recipes are screwed with AE2 and Mekanism, you have to disable mod integration in the AE2 configs.

**Comment by halvors** [comment]
To mark that, you have to disable mod integration in for Mekanism in AE2 configs for both client and server ;)

**Comment by Steelpower900** [comment]
I have the setting does not change after the update so I was wondering why it no longer works. Has off work many thanks :)
