### ISSUE TITLE
Pipes and tubes have now too much redstone sensitivity

### ISSUE THREAD

**Issue by EzerArch** [aidancbrady/Mekanism#2375]
Mekanism version: 1.7.10-8.0.2.201

Now levers and redstone dust affect a range of 3 pipes/tubes blocks, instead of just one. Also "redstone sensitivity"=on is the default on placement.

![2015-03-26_01 56 08](https://cloud.githubusercontent.com/assets/6743303/6840698/204e545e-d35c-11e4-9487-7b1a9e78f971.png)
![2015-03-26_01 56 21](https://cloud.githubusercontent.com/assets/6743303/6840697/204e3bf4-d35c-11e4-939a-bd49fc84c09c.png)
----

*Suggestion:* wouldn't it be better if Mekanism had valves instead of levers cutting off pipes? http://en.wikipedia.org/wiki/Valve

**Comment by aidancbrady** [comment]
Fixed.

By the way, I love the idea of valves. Definitely considering!
