### ISSUE TITLE
Mekanism disable the craft of Inscriber from Applied Energestic

### ISSUE THREAD

**Issue by Natchesprout** [aidancbrady/Mekanism#2381]
I don't know why this craft is disable with Mekanism please help

**Comment by aidancbrady** [comment]
This is an AE2 integration issue.

**Comment by Natchesprout** [comment]
thank you is it a bug or it's my fault?

**Comment by Towsty** [comment]
There is a line in the AE2 config that you can disable the integration through. Near the bottom.

**Comment by Natchesprout** [comment]
Thanks =)

**Comment by ruifung** [comment]
i suggest you open a issue on the ae2 github too.
