### ISSUE TITLE
NEI CRASH

### ISSUE THREAD

**Issue by bfowler1321** [aidancbrady/Mekanism#2383]
Still a recipe crash after suggested AE2 rv2 build 18 update
I even disabled AE2 integration with Mekanism
Still no go.
http://pastebin.com/D31HZ4yW

**Comment by aidancbrady** [comment]
I can assure you this is not a Mekanism issue - if you install Mekanism without any other mods, you won't get the crash.  The only thing I can suggest is to find the offending mod by means of removing each one individually, and then report the integration issue to their bug tracker.

**Comment by bfowler1321** [comment]
it was minetweaker 3.09c or modtweaker 2 -0.7.5

thanks for the fast response and help..truly appreciate it! :) 
#wouldn't want you're job

**Comment by aidancbrady** [comment]
No worries! :)
