### ISSUE TITLE
Greif Prevention Recognition/Association

### ISSUE THREAD

**Issue by spawlak1** [aidancbrady/Mekanism#2384]
As of right now, items like the flamethrower and digitalMiner bypass the protection plugin GreifPrevention. It's a pretty common plugin that I have seen around and I was wondering if it would be too much to ask to have mekanism made to not bypass through it for items that break/alter blocks.

**Comment by enterprise12nx** [comment]
spaw pretty sure thats upto the griefprevention team

**Comment by aidancbrady** [comment]
^
