### ISSUE TITLE
Client crash - Crafting - v8.0.2.201

### ISSUE THREAD

**Issue by yepidoodles** [aidancbrady/Mekanism#2385]
Hi there

When crafting an advanced factory using a basic factory which has already been used (therefore containing meta data, it crashes the client. It works fine with a 'fresh' crafted basic factory.

https://www.dropbox.com/s/go4s7eynvyyt13y/crash-2015-03-27_01.23.08-client.txt?dl=0

Thanks for your time :)

- Alice

**Comment by PastorBones** [comment]
I'm having the same problem crafting a basic factory out of a used energized smelter...

http://pastebin.com/3bqwibyF

**Comment by bfowler1321** [comment]
I tried the injector didn't work 
http://pastebin.com/AsAxAKHi

**Comment by aidancbrady** [comment]
This is fixed in development

**Comment by codewarrior0** [comment]
That's a negative. Not fixed in development.

**Comment by aidancbrady** [comment]
Ah - should be *actually* fixed now :)
