### ISSUE TITLE
Minecraft Crash on start-up, (FTB Infinity)

### ISSUE THREAD

**Issue by AJKproductions** [aidancbrady/Mekanism#2387]
I had a problem recently with my minecraft crashing here is the error log (http://tny.cz/fdff9505). I was using the Infinity modpack, which i know has a lot of mods in already but i was looking to use the cables that came with Mekanism.... Hope you can help, tell me if you need more info.
Alex.

**Comment by bfowler1321** [comment]
Update your Applied Energistics.. there was a bug they fixed for that. 
Use most recent beta build- rv2.beta build 18 found here http://ae-mod.info/Downloads/ 
this should help :)

**Comment by AJKproductions** [comment]
Thanks, i installed 'rv2.beta build 18' version of Applied Energistics but it still works fine.
