### ISSUE TITLE
DigitalMiner ore filter server/client crash

### ISSUE THREAD

**Issue by atomic7777** [aidancbrady/Mekanism#2388]
Server crash using Ore filter in Digital Miner
Mekanism 8.0.2.201, no other mods
Server version: Cauldron-Forge1307

Client crash in single player, Forge 1307

Steps to reproduce:
1. Place digitalminer, connect it to power source
2. Open New filter / Stack, place Iron Ore in left slot
3. Choose Inverse mode ON
4. Start digitalminer

Crash report: http://pastebin.com/d6BPJ4Uv

**Comment by aidancbrady** [comment]
Fixed already in development
