### ISSUE TITLE
Problems with barrels, BOP woods and logistical sorters

### ISSUE THREAD

**Issue by MrGreenTea** [aidancbrady/Mekanism#2390]
I built a sorting system that tries to sort wood items in to barrels from the JABBA mod. This works perfectly with vanilla logs and also with BOP (Biomes O' Plenty) when it tries to sort them into chests. But when I try to get the BOP logs in to barrels, the game kind of freezes. I can still move around and place blocks etc, but I can't interact with blocks (by rightlick). The chest stays open too. I added some images to make it more clear what I am trying and what is happening. When I try to close the world it freezes at the "shutting down internal server..." screen. If you are unable to reproduce this bug, I will try to isolate the issue more, so please tell me.
![2015-03-27_16 18 52](https://cloud.githubusercontent.com/assets/9407731/6870630/87f40d32-d49d-11e4-91eb-3d227b0d973f.png)
![2015-03-27_16 18 59](https://cloud.githubusercontent.com/assets/9407731/6870631/87f4b174-d49d-11e4-9c48-b8f724afc568.png)
![2015-03-27_16 21 53](https://cloud.githubusercontent.com/assets/9407731/6870632/87f5a6ba-d49d-11e4-9405-ea35b619e574.png)

**Comment by aidancbrady** [comment]
Would you mind providing your log?

**Comment by MrGreenTea** [comment]
There is nothing interesting in it, I already looked. http://pastebin.com/a0Hvd7Wn
Or are there other log files I/you can take a look at?

**Comment by Xaethon** [comment]
This is also happening on my modpack, here is a warmroast stack taken during when the server was hanging. http://i.imgur.com/u05tNcE.png

The offending setup involved logistical transporters, pipes and JABBA Barrels.

**Comment by aidancbrady** [comment]
What version are you all using?

**Comment by MrGreenTea** [comment]
I am using 8.0.2.201

**Comment by aidancbrady** [comment]
@Xaethon, do me a favor and report this to @ProfMobius and give him that report - after looking through my code I don't know where this could be happening on my end.  Feel free to report back if he confirms it's due to Mekanism.

**Comment by taelnia** [comment]
Please check that you are using the latest version of Jabba.  The most recently released version has a fix that may resolve this.  The log that was linked to earlier was not a complete log and did not include the first part where the mod filenames/versions are included.

**Comment by MrGreenTea** [comment]
You are right, I didn't note there was a new version. Sorry about that and thanks for the help!
