### ISSUE TITLE
Flamethrower creates some ghost flames

### ISSUE THREAD

**Issue by EzerArch** [aidancbrady/Mekanism#2393]
Mekanism version: 1.7.10-8.0.2.201

If you fire the flamethrower across the floor, 1/10 of the flame sprites will not "despawn" when the actual fire object (which hurts you) extinguishes.

Firing a flamethrower trail on the floor:
![2015-03-28_01 15 39](https://cloud.githubusercontent.com/assets/6743303/6879776/15c30f9c-d4e8-11e4-92e1-c0eb446f73ee.png)

After 10 seconds, there are still some fire sprites left behind, they don't burn. They will go away if you reload the game:
![2015-03-28_01 09 44](https://cloud.githubusercontent.com/assets/6743303/6879775/15c0c7dc-d4e8-11e4-8d4b-2a6801c27ff8.png)

**Comment by aidancbrady** [comment]
By flame sprites, do you mean the flame "blocks" that are in the snow?

**Comment by EzerArch** [comment]
> By flame sprites, do you mean the flame "blocks" that are in the snow?

Yes, flame blocks. I wasn't sure those are also blocks.
