### ISSUE TITLE
Mek7>>Mek8 Machines lose side config

### ISSUE THREAD

**Issue by Greylocke** [aidancbrady/Mekanism#2394]
If you have customized the sides of a Mek7 machine, those configurations will be reset when you convert to Mek8. It would sure make the conversion easier if players didn't have to reconfigure their Mek machines.

**Comment by aidancbrady** [comment]
I already worked with @codewarrior0 on this, configurations should transfer over just fine, except for a few. Which machine are you encountering the issue with?

**Comment by aidancbrady** [comment]
Closing as this follows along with the guidelines listed on my site's blog post, but please keep me updated -I'd love to have machine configuration transfer over.

**Comment by Greylocke** [comment]
In my conversion test world, I've got a crusher with input on the bottom side, and ejecting out the right into Logistics Pipe. The pipe feeds the right side of a Smelter, which is set for a right-sided input and an output through the top, directly into the Crusher.

In Mek7, I feed stone into the Crusher, which makes cobble. The cobble goes to the Smelter, which makes stone and passes the stone to the Crusher, etc., etc. When I convert my conversion test world to Mek8, the Logistics Pipe is no longer connected to the Smelter, because the Smelter is no longer configured with an input on the right side.

I'm not at my main PC now, but if you'd like to see it first hand, I can send you my test world later, if it would help.
