### ISSUE TITLE
Feature Request: Teleporter Cooldown

### ISSUE THREAD

**Issue by XBlackLeopardX** [aidancbrady/Mekanism#2395]
When using the teleporter I've noticed that if you dont have a good connection to the server and are able to load everything instantly then by the time you are able to move your already being teleported back to the other portal  so im wondering if it would be possible to add a cooldown or something to where if you go through the portal you cant be teleported back through it until you walk out and then back into the portal so that you arent stuck going back and forth

**Comment by aidancbrady** [comment]
This is currently fixed development :)

**Comment by XBlackLeopardX** [comment]
Okay, Thanks!
