### ISSUE TITLE
A very odd crash

### ISSUE THREAD

**Issue by enterprise12nx** [aidancbrady/Mekanism#2397]
So im using mekanism V8.0.201

My players have suddenly started crashing after they built the Solar Evaporation Plant
they crash right when they join, or freeze and crash.

here is the crash report, it mentions cofh but im not sure where to report bugs to them, if its their problem, where should i report it?

http://pastebin.com/ezCmSckL

**Comment by aidancbrady** [comment]
Report to CoFHLib - not a Mekanism issue

**Comment by enterprise12nx** [comment]
ok will do

**Comment by enterprise12nx** [comment]
i reported it to CoFH but they beleive it may be your problem too?
They said the error report is vary vague..but that is all it produces so im not really sure what todo

https://github.com/CoFH/Feedback/issues/365
