### ISSUE TITLE
Digiminer crash

### ISSUE THREAD

**Issue by enterprise12nx** [aidancbrady/Mekanism#2399]
digiminers are still causing crashes using mekanism 8.0.201

http://pastebin.com/tPcsykMG

**Comment by aidancbrady** [comment]
Yes, this is fixed in development

**Comment by enterprise12nx** [comment]
ah /= no matter how many times i tell my players, they go and put on inverse mode and now the whole servers broken again

**Comment by enterprise12nx** [comment]
is there a way to disable the inverse option server side?

**Comment by aidancbrady** [comment]
v8.0.3 is out now :)
