### ISSUE TITLE
Mode switch not working

### ISSUE THREAD

**Issue by pacthchristensen** [aidancbrady/Mekanism#2400]
The mode switch does not appear to be working with the jet packs or the scuba tanks. Tried both normal and armored jet pack and it is stuck on regular mode.

Tested with mekanism only installed. No matter what hot key I configure I can not change the mode.

running forge version 1291
tested with mekanism 8.0.0.188 and 8.0.2.199

Any ideas?

**Comment by aidancbrady** [comment]
Press F.  Item mode switch has separated from armor mode switch
