### ISSUE TITLE
Universal cable wont connect to buildcraft machines

### ISSUE THREAD

**Issue by ImmortalSpartan** [aidancbrady/Mekanism#2401]
I've been play with the latest version of mekanism and I couldn't get the universal cable to connect to a buildcraft quarry. I tried the upgraded versions of the cable and I even tried to put a energy cube next to the quarry but it wont transfer power, I then went to see if the other buildcraft machines can connect to the cable and energy cubes but non of them could.

**Comment by aidancbrady** [comment]
BuildCraft works fine on my end.  Make sure you both have the most up-to-date version of BuildCraft and your other mods are up to date, as they may be shipping outdated APIs.

**Comment by unpairedbracket** [comment]
Also, you'll need CoFHCore installed at the moment - we're planning to remove this requirement soon.
