### ISSUE TITLE
Unable to view some recipes in NEI with Mekanism installed

### ISSUE THREAD

**Issue by jhjaggars** [aidancbrady/Mekanism#2402]
I noticed that some AE2 recipes do not display when left-clicking them in NEI when I have Mekanism-1.7.10-8.0.3.203 installed.

Given the following installed mods:

* appliedenergistics2-rv2-beta-14.jar
* CodeChickenCore-1.7.10-1.0.4.35-universal.jar
* Mekanism-1.7.10-8.0.3.203.jar
* NotEnoughItems-1.7.10-1.0.4.94-universal.jar

Most of the recipes display, but some AE2 recipes do not. An example is the crystal growth accellerator. If I disable the Mekanism jar then the recipe will display as expected with a left click in NEI.

**Comment by aidancbrady** [comment]
This is actually on AE2's end, they haven't updated their Mekanism integration.
