### ISSUE TITLE
Dumping machine tanks

### ISSUE THREAD

**Issue by EvulOne** [aidancbrady/Mekanism#2404]
It would seem that setting a machine to "dumping excess" on one of its internal tanks, doesn't allow it to continue running when said tank is full.  Is this a bug?  If so, what's the point of the "Dump excess" setting?

To reproduce:
Put down an elecrolytic separator
Give it something to process (infinite water, for example)
Put a tank beside one of the output sides (lets say the left side), and leave the other output with nothing attached (the right side)
Leave the left side (with tank) set to "Idle"
If set to "Idle" on the right side, the internal tank will fill, and the machine will stop working when it gets full.
If set to "Dump" on the right side, the internal tank will never fill and the machine will continue running until the left side is full.
If set to "Dump Excess" on the right side, the internal tank will fill, and the machine will stop working when it gets full.  (same as if set to "idle")

**Comment by aidancbrady** [comment]
Yes - if you want the machine to not halt, you need to have both sides set to dump excess. The reason it is configurable on both sides is for the case you know that a certain buffer will never be filled to the max.

**Comment by EvulOne** [comment]
Thank you, that did indeed work!

**Comment by EvulOne** [comment]
Going by your example, if you know that one of the buffers will never fill completely, why do both sides need to be set to "dump excess" when one of the sides will never have excess.

Here's my thinking:
You have one side set to dump excess, and the other set to idle.  Lets say you're producing oxygen for ore processing out of a couple Separators, and using the hydrogen from them in a gas generator to get some energy return.

If the generator cannot keep up, the internal hydrogen tank will eventually fill, while the oxygen is consumed by your processing.  Eventually, you'll have a full tank of H and your ore processing will slow down due to lack of O.

Now, you could have them both set to dump excess, but since the H is just a bonus output, you want your Separator to stop producing once your ore processing setup is filled and not running.
As it is currently, you can either have it stop producing O once the H tank is filled, starving your processing line, or have it run infinitely, even when you're no longer consuming the oxygen produced.

I guess I don't really understand what you mean though as to why the sides both have to be dump excess.  When you have a minute could you give an example please?

**Comment by aidancbrady** [comment]
Ah, I think you misinterpreted me.  The only reason you would need both sides to be set to dump excess is if you are not outputting to either side (and therefore both buffers are filling).  Most likely you will be outputting gas from one side and dumping the other, which is where dumping excess on one side comes in handy.

**Comment by EvulOne** [comment]
Yes but the dumping excess on only one side does nothing currently.  That buffer will fill to max and then the machine will stop, even if the other side's product is still in demand

If you were dumping one side of a machine, and outputting gas from the other (say, Brine -> sodium and chlorine) You dump all sodium (set it to dump, not dump excess) and leave the Cl side set to idle, which would let the machine stop if the Cl side is full.

**Comment by aidancbrady** [comment]
I am not experiencing this issue, very strange.  Could I have a screenshot?

**Comment by aidancbrady** [comment]
Oh man, just found it.  Apparently was just the left side that is not working.  Fixed, pushing to master in the next few moments.

**Comment by EvulOne** [comment]
Ah okay, was just about to post a screen shot of this happening, and it is indeed on the left side.  Thank you for looking into it!

**Comment by aidancbrady** [comment]
No worries!  Thanks for reporting and your insisting it was an issue to me :)

**Comment by EvulOne** [comment]
Thank you for bearing with me, in case I had been wrong all along haha.
I don't mind being wrong, I just didn't understand why what I was seeing was different from what you were describing.
A lot of people would have simply ignored or shunned someone if they thought they were correct, so thanks =)
