### ISSUE TITLE
Game showing dot notation names instead of display names

### ISSUE THREAD

**Issue by EzerArch** [aidancbrady/Mekanism#2405]
Mekanism version: Mekanism-1.7.10-8.0.3.203

Minor issue, 99% sure it's related to the lang files.

Instead of showing the display names, e.g. Mode Switch and Baby Skeleton, the game or mods show strings like ```key.armorMode```, ```entity.Mekanism.common.BabySkeleton.name``` or simply ```BabySkeleton```.

![2015-03-29_00 52 58](https://cloud.githubusercontent.com/assets/6743303/6884048/49cd11e0-d5ae-11e4-8c2a-f18bfd04fb6c.png)
![2015-03-29_00 55 59](https://cloud.githubusercontent.com/assets/6743303/6884063/265ee1d2-d5b0-11e4-901f-8de343c12dde.png)
![2015-03-29_00 52 32](https://cloud.githubusercontent.com/assets/6743303/6884049/49cd1c76-d5ae-11e4-9cde-aa4d375c7620.png)

**Comment by aidancbrady** [comment]
Fixed, thanks :)
