### ISSUE TITLE
Improve localization

### ISSUE THREAD

**Issue by Adaptivity** [aidancbrady/Mekanism#2406]
In case you didn't saw it. More info here: https://github.com/aidancbrady/Mekanism/commit/2d727b56ca8d8dc9f275a53f7fcd274970fbc468 and here: https://github.com/aidancbrady/Mekanism/pull/2382

**Comment by aidancbrady** [comment]
I have reverted back to the old system of localization for Energy Cubes.  I think that doing so for factories may simply be too much trouble, though - that would be nearly 40 different new localization entries.

**Comment by Adaptivity** [comment]
Well, you can allow us to use individual names for factories but en_US.lang can continue using new localization system. So, if individual name exist in .lang FML uses it, if not it rollback to the new method. But...for what Tier names(https://github.com/aidancbrady/Mekanism/blob/development/src/main/resources/assets/mekanism/lang/en_US.lang#L319) actually used for(for what machines?)? Only for factories? If so, individual names no longer needed. And what about @TheVikingWarrior problem? Basically he want to swap color name with block name. You should just add something like %s tag to the block name in .lang file.

**Comment by Adaptivity** [comment]
any chance of rechecking?
