### ISSUE TITLE
Ender io gas conduit crash w/ Electrolytic Separator

### ISSUE THREAD

**Issue by aldra2012** [aidancbrady/Mekanism#2407]
when connecting a ender io gas conduit to the Electrolytic Separator crashed the server but not the client here is the crash report http://pastebin.com/P6neYebz

**Comment by EvulOne** [comment]
Can confirm.  Placing an enderIO gas conduit on any gas-compatible Mek machine causes a crash, not just Electrolytic Separator.

Looks like an issue on EnderIO's end though; it's their function that's throwing the error.

**Comment by aidancbrady** [comment]
EnderIO's end
