### ISSUE TITLE
Mekanism broken with Appliedenergistics and NEI (quick fix included)

### ISSUE THREAD

**Issue by DJDayta** [aidancbrady/Mekanism#2408]
Since using Mekanism 8 the Recepies of Appliedenergistics stopped showing up in NEI as well as the crafting did not work anymore. 

i used 
Mekanism-1.7.10-8.0.2.201
MekanismTools-1.7.10-8.0.2.201
MekanismGenerators-1.7.10-8.0.2.201
NotEnoughItems-1.7.10-1.0.3.74-universal
NotEnoughItems-1.7.10-1.0.4.83-universal
NotEnoughItems-1.7.10-1.0.4.90-universal
appliedenergistics2-rv1-stable-1

As soon as i deleted Mekanism it worked again 
Downgrade to Mekanism 7 was also working again
Of course thats not a solution even 1.7.10-8.0.3.207 didnt change that yet

**QUICK FIX** 
Open your minecraft folder goto config goto the folder of appliedenergistics2
Open the file AppliedEnergistics2.cfg and scroll down to this and change
modintegration from     S:Mekanism=AUTO ->     S:Mekanism=OFF
thats for your client for single player and on your server for server of course

**BEFOR:**
Since using Mekanism 8 the Recepies of Appliedenergistics stopped showing up in NEI as well as the crafting did not work anymore. 

![Image](http://www.goettlicher-pakt.de/mekanism/1_ingame_auto.jpg)

I used 
Mekanism-1.7.10-8.0.2.201
MekanismTools-1.7.10-8.0.2.201
MekanismGenerators-1.7.10-8.0.2.201
NotEnoughItems-1.7.10-1.0.3.74-universal
NotEnoughItems-1.7.10-1.0.4.83-universal
NotEnoughItems-1.7.10-1.0.4.90-universal
appliedenergistics2-rv1-stable-1

as soon as i deleted Mekanism it worked again 
downgrade to Mekanism 7 was also working again
of course thats not a solution even 1.7.10-8.0.3.207 didnt change that yet

quick fix 
open your minecraft folder goto config goto the folder of appliedenergistics2
open the file AppliedEnergistics2.cfg and scroll down to this and change
modintegration from     S:Mekanism=AUTO ->     S:Mekanism=OFF
thats for your client for single player and on your server for server of course

**BEFOR:**
![Image](http://www.goettlicher-pakt.de/mekanism/1_config_auto.jpg)

**AFTER:**
![Image](http://www.goettlicher-pakt.de/mekanism/2_config_off.jpg)

et voila recipis show up again they are craftable AND they are still interacting

![Image](http://www.goettlicher-pakt.de/mekanism/2_ingame_off.jpg)

i tryed using import export bus on mekanism machines me interfaces tryed sending pattern used mekanism energy as well as energy cubes for powering applied energistics it all worked
so far im a bit confused what this option actually does if i tell it to stop interacting with mekanism but who knows for the moment it works and thats all within my power i can do i hope that information helps someone or maybe even aidan our mekanism hero keep up the good work 

in case logs are intresting to look at i uploaded a fresh start on each cases

appliedenergistics cfg modinteraction S:Mekanism=AUTO recipis dont work
http://www.goettlicher-pakt.de/mekanism/1_logs_auto.rar

appliedenergistics cfg modinteraction S:Mekanism=OFF everything works again
http://www.goettlicher-pakt.de/mekanism/2_logs_off.rar

**Comment by EvulOne** [comment]
Seems more like an AE2 issue rather than a Mek issue... maybe post it there for them to look at?

**Comment by emperor06** [comment]
I think it has been discussed already on AE2's issue page. It may also have been fixed already but be careful with the latest AE2 beta (19 and 20) as they are a bit buggy. Best you checkout AE2's page first.

**Comment by DJDayta** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1061
