### ISSUE TITLE
Solar Neutron Activator can destroy bedrock

### ISSUE THREAD

**Issue by emperor06** [aidancbrady/Mekanism#2409]
When a Solar Neutron Activator is placed in the world, the block directly above it (where the solar panel is) disappears. This can be used to destroy the Nether's top bedrock layer and probably break some other mods like destroying the ceiling of Thaumcraft's Eldritch maze, AE2's spatial storage dimension, or pvp-protected blocks (well, all blocks that are not supposed to be broken).

**Comment by aidancbrady** [comment]
Fixed in development
