### ISSUE TITLE
Chemical Infuser output limit

### ISSUE THREAD

**Issue by emperor06** [aidancbrady/Mekanism#2410]
The chemical infuser can receive 8 speed upgrades, allowing it to create gases at light speed (256x). But that's only for its internal output tank. The machine output is capped at 16.
I don't know if it's intended or not. Maybe it would be nice to either set the output to match the upgrade or to disallow inserting more than 4 speed upgrades (since any speed upgrade above 4 is pretty much useless) to avoid confusing the player.

**Comment by DJDayta** [comment]
i would be happy with lightspeed :) maybe mental power consumption on that level to keep that reserve for endgame

**Comment by emperor06** [comment]
On the other hand, an output limit on the chemical infuser is very nice to enable an easier control of brine consumption. This limit caps the chlorine input so it caps the chlorine production which in turn caps the brine consumption for T4/T5 machines. With a sufficient amount of solar evaporators, that allows a minimum amount of brine to be always available for tritium production so that a reactor won't stop for lack of fuel.
Of course, we can always make a separate network for the reactor but that's trickier.
If we want more hydrogen chloride output, we can still place more chemical infusers.
On the other hand, if the output rate is based on the speed upgrades, we can easily cap the T4/T5 brine consumption by setting a different amount of upgrades in the chemical infuser.

**Comment by aidancbrady** [comment]
Update Mekanism
