### ISSUE TITLE
Reactor Logic Adapter

### ISSUE THREAD

**Issue by aidancbrady** [aidancbrady/Mekanism#2412]
Computer/Redstone port for the Fusion Reactor.  Will have several different redstone output modes:
* Disabled (no power will be emitted)
* Ready for Ignition (core has been heated up to a sufficient level to allow for ignition)
* Heat Capacity Met (the heat capacity of the core has been met)
* Fuel Depleted (either the stored deuterium or tritium is not sufficient to meet the injection rate)

All the modes will also be accessible by a CC computer.

**Comment by Kodos-Atoz** [comment]
Would this be accessible as an OpenComputers component?  I have a few ideas for available methods along what you've listed here.

**Comment by aidancbrady** [comment]
Not immediately, I'm planning on implementing OpenComputers perhaps in v8.2 or later on.

**Comment by Kodos-Atoz** [comment]
Well, what do you think of these;

isEnabled(); returns true if the reactor is running, else returns false
canIgnite(); returns true if the plasma temperature is at or above ignition temperature, else returns false
getPlasmaHeat(); returns the current temperature of the plasma
getMaxPlasmaHeat(); returns the max temperature of the plasma, based on current injection rate
getCaseHeat(); same things here, but for the case
getMaxCaseHeat(); etc
getInjectionRate(); returns the current injection rate
setInjectionRate(integer); sets the injection rate to the given value

It's still early, and these are just ideas for the oc/cc methods.  Just wanted to throw my two cents in.

**Comment by aidancbrady** [comment]
Sure - I'll add all those into CC support.  I'll keep the initial 4 mentioned modes for default redstone support as well.

**Comment by Kodos-Atoz** [comment]
On the disabled redstone one, could you possibly make it emit redstone when the reactor is on, instead of off?  I use a Project Red addon called Project Blue, and you can have levers, buttons, and lamps on a single blockspace for each of 16 colors of the bundled cable, and this would make setting up a reactor status/control panel easier.  Also will the redstone ports just be for monitoring or will you be adding in control as well

**Comment by aidancbrady** [comment]
"Disabled" simply means that no power will be emitted no matter what.  I don't plan on adding redstone-based control but I will definitely add what you suggested to the computer integration.

**Comment by aidancbrady** [comment]
This is now done!

**Comment by buithanh12072001** [comment]
Can I control the reactor by using this Reactor Logic Adapter? I suggest you this logic adapter can interact with bundled cables from Project Red, that would make setting up a reactor status/control panel easier.

**Comment by nosknut** [comment]
Hi. I have a redundant reactor setup on a server. Im producing a lot more fuel of both types then i need. The reactor injection rate is set to 8 and still it keeps shutting down randomely. Why? Can this be a result of the reactor not being in only one chunk or in the same chunk as the fuel generating setup? Also are there any effects of uverheat?
