### ISSUE TITLE
Induction Cell loses stored energy on placement.

### ISSUE THREAD

**Issue by halvors** [aidancbrady/Mekanism#2413]
Induction Cell loses stored energy on placement. This happend when i moved my induction matrix, i've verified that the Induction Cell did have stored energy when it was in inventory.

**Comment by aidancbrady** [comment]
Fixed!

**Comment by halvors** [comment]
Nice :)

**Comment by halvors** [comment]
@aidancbrady I think i found another bug, not sure if this was fixed in your commit, but when i break the mutiblock induction matrix structure to insert another induction cell, it looses all the energy already stored in the existing ones when the structure gets "formed" again.

**Comment by aidancbrady** [comment]
Yes, that was fixed too.

**Comment by halvors** [comment]
Nice :)

**Comment by halvors** [comment]
@aidancbrady Also, this is not big issue for me, just wanna let you know.

I was labbing with the fusion reactor, where my first induction cell is, and i have another induction cell back at my house. These are not connected to each other what so ever. There is no possible connection at all.

But when i broke the induction cell at my lab, it lost it's energy (Full Ultimate Induction Cell). This is ok, and the actual bug reported in this issue. But later i discovered that my induction cell back at my house was completly full (512GJ) and i'm 110% sure that this just had something about 40GJ.

Is this possible that when i broke one of them the energy somehow was inserted into the other one instead? 

I know this sounds really strange. But i simply can't find any other possible reason why it jumps from 40GJ to 512GJ with just a few soler panels in matter of minutes.
