### ISSUE TITLE
Server crashes while wrenching reactor

### ISSUE THREAD

**Issue by xGhost169** [aidancbrady/Mekanism#2414]
Server crashes when you try to wrench any Reactor component. It did work in singleplayer. Since I'm not server owner, I do not have crashlog...

**Comment by aidancbrady** [comment]
If it works on single player it is most likely some kind of conflict on SMP.  If you can find a log, I'll take a look.

**Comment by enterprise12nx** [comment]
Please re-open this issue, i have the crash reports.
Also, asking you to re-open issue #2397 

Regarding issue #2397 this is what KingLemming had to say https://github.com/CoFH/Feedback/issues/365

**Comment by aidancbrady** [comment]
Fixed the first crash :)
I'm confident the second issue is not on my end, however.

**Comment by enterprise12nx** [comment]
well maybe try talking to KingLemming, because your both going back and forth xD and my players cant play because of this crash, they cannot login.

KingLemming says its something about your chunkloading messing with fastcraft and CoFH, but i would reply and talk to him, so maybe you can figure something out, he also mentions that it could be a problem with EnderIO V364 but im not sure, everyone is pointing fingers so maybe all 3 get together?

**Comment by enterprise12nx** [comment]
i have referenced the issue to CrazyPants as well, so all 3 of you have been linked https://github.com/CoFH/Feedback/issues/365

**Comment by aidancbrady** [comment]
Just spoke with him - we both are very sure we are not to blame.  I doubt it is EnderIO as well.

**Comment by enterprise12nx** [comment]
gah, then how can this be fixed?

**Comment by EvulOne** [comment]
I'd suggest making a copy of the world to tinker with, and then forcefully removing the object in question, and see if that solves it.  If it does, try rebuilding the solar evap plant from scratch to see if you can replicate it.  If removing it doesn't fix your problem, then it's something elsewhere (and you just got unlucky that it happened at the same time/place as the solar evap plant)

**Comment by Nick-77ab2** [comment]
or all of the mods could add a debug thing to show if it actually is on their side when the server crashes, pretty much it shows more of what is happening?
would that help?

**Comment by EvulOne** [comment]
The problem is it's often not as simple as "If my mod fucked up, throw this error".  Most mods do already include error handling for their own code.
The issue is caused by an interaction between two or more mods, and is likely not a straight forward error.

**Comment by enterprise12nx** [comment]
they are already working on this issue in another ticket
