### ISSUE TITLE
Reimplement global replace block for Digital Miner.

### ISSUE THREAD

**Issue by halvors** [aidancbrady/Mekanism#2415]
Reimplement global replace block for Digital Miner. I really like the new system, but think that you should have the option to specify replacement globally as well.

The global system whould when kick in where there is no defined replacement block, this whould allow users to actually locally specify for special cases as well.

**Comment by aidancbrady** [comment]
I'm sorry, but I think I'd prefer to maintain the current filter-based replace system for now - the DM code is already very cluttered, and this would just add more to the great amount of calculations performed by that machine.  Maybe I'll consider this later on :)

**Comment by halvors** [comment]
Ok :)
