### ISSUE TITLE
PRC Gas Configuration

### ISSUE THREAD

**Issue by EvulOne** [aidancbrady/Mekanism#2416]
It would seem that the PRC will only output Ethalene to the right hand side, even if the gas tab's config is set to output gas on the left.  Is this intended, seeing as the Ethalene tank in the gui is shown on the right side?
Some images:
http://imgur.com/a/m9wjC

**Comment by EvulOne** [comment]
Also related to the PRC: It has no "dump tank" buttons on its gui.  I currently have one that is stuck full of water and oxygen, and cannot be used for anything as a result.

**Comment by aidancbrady** [comment]
In terms of the dump tank button, I recommend using a gauge dropper :)

Looking into the first issue

**Comment by EvulOne** [comment]
Gauge dropped did the trick, thanks (although it takes quite a bit to drain an entire tank xD)

**Comment by aidancbrady** [comment]
I'll consider it!
