### ISSUE TITLE
Feedback: Hohlraum recipe

### ISSUE THREAD

**Issue by emperor06** [aidancbrady/Mekanism#2417]
Not an issue, just a feedback.
The current recipe for Hohlraum (4 gold dust in Enrichment Chamber) makes enrichment factories unable to craft it when auto-sort is on. Imho, this adds an unnecessary workload for players who use a lot of crafting automation (like AE2). We have to either set auto-sort to off (which kinda breaks the advantage of having a factory) or build another machine with cables, upgrades, channels, and interfaces just for a single item.

**Comment by aidancbrady** [comment]
Made it a Metallurgic Infuser recipe :)
