### ISSUE TITLE
PRC Energy buffer.

### ISSUE THREAD

**Issue by hisorange** [aidancbrady/Mekanism#2418]
Aye, the PRC has a 8k RF energy buffer while it uses 4k RF/tick to create HDPE Pellet, not a big issue just got my attention while was checking where the hell my RF going away :D

version Mekanism-1.7.10-8.0.3.207
(the PRC have the 8 energy upgrade in it)

**Comment by aidancbrady** [comment]
Indeed, with 8 speed and energy upgrades it will use quite a lot of energy ^^
Not really a issue, though, considering there still is enough energy to process.
