### ISSUE TITLE
Factory Upgrade Bug

### ISSUE THREAD

**Issue by iDrewt** [aidancbrady/Mekanism#2419]
Upon adding a factory installer, you have to break the machine before adding Speed/Energy upgrades. Otherwise, you will add them and they will not actually give the bonus, and you can not withdraw them. If you add them, you have to break it and place the machine again .. resulting in the upgrades disappearing. 

TL;DR: You have to break the factory after installer upgrades it (Basic-->Elite-->Ult) before you are able to add speed/energy upgrades.

Edit: I am using version 8.0.2.201

**Comment by TacoMage** [comment]
I experienced this too; however, the bug was fixed in version 2.571, so if you upgrade to the latest 8.3 release, you should be golden.
