### ISSUE TITLE
Crash in Heavily modded Area

### ISSUE THREAD

**Issue by DrDoomaniC** [aidancbrady/Mekanism#2420]
Greetingz!

I know this is a heavily modified version of Minecraft. As soon as i download your newest Mekanism Builds (Main, Generators and Tools) I get quite a wierd crash. It loads up, i see the first frame of the game, and then it gets back to desktop, with this crash report:

http://pastebin.com/FNM3Muu2

I dont know my Java too well im afraid, but its something about fluids i guess... 

I tried for a long time now to resolve this, but it only comes up once mekanism starts to be included, so i guessed it may be something on your side.

If not, im sorry for wasting your time

It it is indeed, please take a look into it.

Thanks in advance anyways whoever has something to say about it

**Comment by aidancbrady** [comment]
Should be fixed for next version :)
