### ISSUE TITLE
Suggestion about config options and some issues.

### ISSUE THREAD

**Issue by anishin** [aidancbrady/Mekanism#2423]
Hello.
Firstly, great thanks for your work. This mod is awesome!

Secondly, I have some suggestion about adding more config options. Now (in version 8.0.3.207) in config file I can change energy production and energy usage. But I can't change:
- capacity of energy cubes,
- voltage (capacity) of energy cables,
- flow rate of liquid cables 
etc.

For example, I want to create modpack with Mekanism, TE4, Thermal Dynamics, Ender IO (etc). And I want all capacitors from different mods have the same capacity (for example, Resonant Energy Cell = Vibrant Capacitor = Ultimate Energy Cube) and all energy conduits have the same voltage (Resonant Fluxduct = Ender Energy Conduit = Ultimate Energy Cable). But now I can't change these values in Mekanism.

Thirdly, I have some issues:
1) I can place some blocks (parts of multi-block constructions, such as Induction Casing) into myself and get x-ray glitch.
2) Some blocks have wrong texture in inventory (such as Solar Neutron Activator).

P. S. Thank you for your work!
P. P. S. Sorry for my English. I'm from Russia.

**Comment by aidancbrady** [comment]
Added all the suggested config properties :)
Also, the bugs you mentioned should be fixed for the next release.
