### ISSUE TITLE
Salination Plants causing client crash (Not Responding)

### ISSUE THREAD

**Issue by mikestancato** [aidancbrady/Mekanism#2426]
For some reason (for the second time) whenever I come into range of my salination plants, my client completely freezes and locks me out of the game. When I restart Minecraft and try to the load the world it immediately locks up and doesn't respond. I fixed it the first time by lowering my loaded chunks and moving into the area slowly. After adding 8 more plants and with my character being right next to them, the issue has happened again and it's now impossible to fix it by lowering my vision range. I have 4GB dedicated to MC and 8GB of ram. I tried turning off machine effects/lighting/sound, still didn't help. Furthermore the game isn't producing a log. I can guarantee it is due to the salination plants because I have them 600+ meters away from my base with no other objects other than a tesseract.

**Comment by aidancbrady** [comment]
This is actually an integration issue.  I guarantee it won't happen without other mods installed.

**Comment by enterprise12nx** [comment]
well we like playing with other mods!
this needs to be fixed somehow /=

**Comment by mikestancato** [comment]
Yeah. I am pretty disappointed at this point. Dismissing an issue as "integration" doesn't make it okay. I am running the most common and needed mods. Ender IO, AE2, MFR, Magical Crops, Tinker's Construct, Big Reactors. I am running 42 mods in total which is already an insanely low amount.

**Comment by enterprise12nx** [comment]
i wouldnt say its his fault, he works hard to get these fixes.

Im just hoping there is someway to fix this, i already made a report on the same problem, i have the same type of mods, but its harder for me to remove them to test it on a 24/7 server where its happening.

Perhaps try removing enderio, ive heard speculation that it could be the culprit, or maybe it really is just something really sneaky in mekanism, who knows.

**Comment by aidancbrady** [comment]
Sorry, I've had a long day - I just get so many of these types of issues.  I'm fairly certain the issue is EnderIO, hopefully they will push an update fairly soon.

**Comment by enterprise12nx** [comment]
@mikestancato try removing enderio if you get the chance and see if the problem stops(make sure to make a backup of your world)

If it is enderio, i'll make sure to report it to them

**Comment by mikestancato** [comment]
I am currently doing so. Stripped down to 28 mods so far. Seems it could be a CoFH issue. Will update.

**Comment by enterprise12nx** [comment]
@mikestancato hmm i reported it to CoFH but they say its possible mekanism, but i guess we'll find out based on your report

**Comment by mikestancato** [comment]
Down to 24 mods (including cores/apis) Latest log output:

java.lang.NullPointerException: Unexpected error
	at net.minecraft.world.World.func_72939_s(World.java:1935)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1994)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


I have no idea where to go from here.

**Comment by enterprise12nx** [comment]
i would re-add the mods till the world works again, and then skip over the mod when it begins working, and just continue removing mods(have you been checking the world every time you remove the mod to see if the problems fixed)

**Comment by mikestancato** [comment]
In the process of doing that now. Will keep you updated.

**Comment by mikestancato** [comment]
It's an issue with CoFH and Mekanism. 

java.lang.NullPointerException: Unexpected error
	at cofh.lib.util.LinkedHashList.delete(LinkedHashList.java:267)
	at cofh.lib.util.LinkedHashList.shift(LinkedHashList.java:168)
	at net.minecraft.world.World.func_72939_s(World.java:50532)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1994)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Trying to figure out where to go from here.

**Comment by enterprise12nx** [comment]
i had the same error, are those the only mods remaining? CoFH mods and mekanism?

**Comment by mikestancato** [comment]
Yes. I am now trying different versions of CoFH to see if I can fix or get different results. Will updates again shortly.

**Comment by enterprise12nx** [comment]
ok, im going to link cofh back to this, so now they know it is their mods

**Comment by enterprise12nx** [comment]
@KingLemming So that crash we all have been trying to figure out, we have narrowed it down.

The only mods remaining that this guy has are Mekanism and CoFH mods.
So it is indeed some type of issue between you two.

**Comment by mikestancato** [comment]
CoFH Core Versions:
RC7-266 : Loads into world then almost immediately crashes ("Shutting Down Server" -> CTD)
                 Log Info:        
                      java.lang.NullPointerException: Unexpected error
	                   at cofh.lib.util.LinkedHashList.delete(LinkedHashList.java:267)

RC7-211 : Loads into world and game freezes completely. (Only way to close is ctrl/alt/del)
                 No log info given.

RC7-207 : Same as 211

**Comment by enterprise12nx** [comment]
It does that even in latest version, sometimes you freeze, sometimes you dont, its random.

**Comment by mikestancato** [comment]
Just to verif:.

Removed
CoFHCore-[1.7.10]3.0.0RC7-211
BigReactors-0.4.2A2
MineFactoryReloaded-[1.7.10]2.8.0RC8-86
NetherOres-[1.7.10]2.3.0RC4-10
ThermalExpansion-[1.7.10]4.0.0RC7-141
ThermalFoundation-[1.7.10]1.0.0RC7-62

re-added ALL other mods including ender io and it is working fine. I can 100% verify that this is an issue between CoFH and Mekanism.

**Comment by KingLemming** [comment]
This is on Mek's side, sorry guys.

Here's why:

java.lang.NullPointerException: Unexpected error
at cofh.lib.util.LinkedHashList.delete(LinkedHashList.java:267)
at cofh.lib.util.LinkedHashList.shift(LinkedHashList.java:168)
at net.minecraft.world.World.func_72939_s(World.java:50532)

We have a list. It responds to things that happen in World, as is clearly shown here. If this were on our end, it would happen 100% every time with every. single. chunk. It doesn't.

There is something unique to Mek's salination plants that screws with World and/or the chunk loading process.

**Comment by aidancbrady** [comment]
Can someone test this without EnderIO and see if the crash still happens? I can't reproduce this with only Mekanism and CoFHCore/TE.

**Comment by Cracks777** [comment]
i have mek 8 cofhcore/te ender io and many others and i have never got this crash, no idea

**Comment by enterprise12nx** [comment]
well the problem for me is, removing enderio from the server causes a crash

**Comment by enterprise12nx** [comment]
Removing EnderIO seems to have fixed it

**Comment by aidancbrady** [comment]
That's what I thought. EnderIO does some fancy reflection stuff with Solar evaporation plants if I'm not mistaken, considering the class name changed since v7, there's a good chance that is the root of the issue. I'll keep providing support, but I assure you this is not on my end.

**Comment by enterprise12nx** [comment]
@tterrag1098 please look into this

**Comment by tterrag1098** [comment]
How could EIO cause this? We don't mess with evaporation plants as far as I know.

**Comment by HenryLoenwind** [comment]
What I'd like to know is: Which mod is ASMing Minecraft here? All those line numbers make no sense at all.

**Comment by enterprise12nx** [comment]
Im not sure, but this only happens when EnderIO and Mekanism are put together

**Comment by unpairedbracket** [comment]
Could it be a 3-way mod conflict? Has this been reproduced with only Mekanism and EnderIO, and nothing else?

**Comment by enterprise12nx** [comment]
well according to @mikestancato he kept removing mods, and he was down to only Mekanism CoFH and EnderIO, after removing EnderIO the problem stopped.

I removed EnderIO and the problem stopped as well.
Maybe its Mekanism doing something with EnderIO or its EnderIO doing something with Mekanism.

hopefully this can be worked out, because a lot of people are starting to get this problem.

**Comment by enterprise12nx** [comment]
if you would like, download my modpack IndustrialAgeTheTurning on technic, and the server is auto downloaded, you can see the problem there, or get enderio and mekanism and build a bunch of solar evaporation plants and see if you can reproduce the crash, im not sure if it happens all the time, or if its just random

**Comment by unpairedbracket** [comment]
Oh wow, yeah. I see what you mean @HenryLoenwind - line 50532 doesn't exist (there are only 4507 lines in World) and updateEntities (aka func_72939_s) runs from L2013 to L2242 in the version I'm looking at. I'll take a look at behaviour with only Mekanism and EnderIO installed, and if I can reproduce in a dev env I'll see if I can work out what's going on. Might be difficult if mods are ASMing Minecraft all over the place, though.

**Comment by enterprise12nx** [comment]
@unpairedbracket if theres any other info you need just let me know, goodluck!

**Comment by enterprise12nx** [comment]
any progress on this at all?

**Comment by speakerrob** [comment]
This isn't just an issue with EnderIO, I'm pretty sure. Here's why:

After I had put up a few solar evaps on a creative world I kept experiencing the crashes when trying to start up the game. However, it only began to occur after I had finally left the region and attempted to reload those chunks upon my return. I haven't used a single EnderIO block/conduit/etc on that save, but I did have some fluiducts running from the solar evaps into a tesseract. After popping into MCEdit and removing them both, I was then able to load perfectly fine. I've since replaced the setup with Mekanism's mechanical pipe and ender tanks, removing both the tesseracts and fluiducts, and have had no issues since.

This leads me to believe it's an interaction between more than just EnderIO and Mekanism; CoFH doesn't play well with the new API either.

**Comment by enterprise12nx** [comment]
fix pleaseeee

**Comment by ryuben** [comment]
i got this issue too - i got several crash logs for it - and apparently Fastcraft doesnt like the way it is  dealth with too, can provide them if needed

**Comment by rubybrowncoat** [comment]
I just wanted to add to this issue, as it is one of the few issues I have found searching on google about this problem, that I don't have neither EnderIO nor Mekanism and I am still getting this crash/freeze. It is random and unpredictable.

Just to reiterate:

```
java.lang.NullPointerException: Unexpected error
	at cofh.lib.util.LinkedHashList.delete(LinkedHashList.java:267)
	at cofh.lib.util.LinkedHashList.shift(LinkedHashList.java:168)
	at net.minecraft.world.World.func_72939_s(World.java:50532)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
