### ISSUE TITLE
Realistic World Gen desert only gives 1x multiplier in SEP 

### ISSUE THREAD

**Issue by AssasinAsha** [aidancbrady/Mekanism#2428]
I am not entirely sure whose side this is on, but I decided to try here.
It's essentially like in the subject. If I build a Solar Evaporation Plant in a rwg_hotDesert biome, I can only get 1x multiplier. I checked the configs but I can't see anything about biomes.
Fortunately, with BoP installed, I can get its biomes and there are a few with 2x, but it's bemusing to find a giant desert made entirely of sand and not be able to run SEP at max efficiency.
Plus, the desert is closer to my base. :P
If this is on the RWG side, I apologise and I will go make an issue there.

Using Mekanism 8.0.3.207 and RWG alpha 1.3.2.

**Comment by aidancbrady** [comment]
This would be on RWG - Mekanism uses the "temperature" values provided by each biome, and this most likely means they didn't modify it.  Thanks for reporting though!
