### ISSUE TITLE
Upgrade Slot Derpiness

### ISSUE THREAD

**Issue by MushroomDynamo** [aidancbrady/Mekanism#2431]
It appears that in some machines (at least, the Metallurgic Infuser if nothing else) treat the slot to insert upgrades and the output slot as the same slot, meaning that if you try to upgrade a machine while it's running shenanagains happen--and vice versa, the machine will shut down if one puts an upgrade in it because the "output" slot is blocked.

Running Mekanism 8.0.3.203.

**Comment by aidancbrady** [comment]
This is fixed in development :)
