### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by xJon** [aidancbrady/Mekanism#2434]
http://paste.ubuntu.com/10716322/

**Comment by aidancbrady** [comment]
Added a null check

**Comment by xJon** [comment]
What release will include this fix, may I ask?

**Comment by aidancbrady** [comment]
v8.1 :)

**Comment by xJon** [comment]
Thanks :)

**Comment by xJon** [comment]
Oh also, is there an expected date for the release of Meka v8.1? :)
