### ISSUE TITLE
Portable tank rendering fluids seems to use a lot of RAM

### ISSUE THREAD

**Issue by Fxzy** [aidancbrady/Mekanism#2438]
Forge 10.13.2.1291
Mekanism V8 (all builds)
NEI 1.7.10-10.4.94

Whenever I look up mekanism in NEI and the portable tanks load, my whole laptop slows down and it looks like all my RAM is used while I only allocated half of my RAM to minecraft. I'm not sure what causes this, because there's nothing in the log and I'm not sure if all tanks do this or just some.
I don't want to ask you to find the actual cause, because that could take a long time, I just want to ask if it is possible to make a config option to disable the tanks with fluids in NEI.

**Comment by aidancbrady** [comment]
There is already an option - "PrefilledPortableTanks" :)

**Comment by Fxzy** [comment]
Oh totally looked over it, sorry for bothering you. Thanks! :smiley:
