### ISSUE TITLE
Chance to force Mekanism not to produce Refined Iron Ingot from IC2

### ISSUE THREAD

**Issue by NitroxydeX** [aidancbrady/Mekanism#2441]
Hey!

Is there a simple way to tell Mekanism to force producing Steel Ingots from Mekanism Steel Dust? Sometimes it produces Steel Ingots and sometimes it produces Refined Iron Ingots.

**Comment by aidancbrady** [comment]
Not really, but you can use the new oredictionificator to standardize ingots :)

**Comment by EvulOne** [comment]
If it makes you feel any better, the server I play on atm has about 6 different types of copper, and depending how my smelting machinery feels at the moment, I've had it spit out at least 5 of the types.  From the same machine.  Without any changes to anything.

An in-game solution:  JABBA Barrels.  They'll unify your ingots =)

**Comment by NitroxydeX** [comment]
Oredictionificator helped! Thanks :)
