### ISSUE TITLE
Mekanism v8 breaks AE2 core recipes

### ISSUE THREAD

**Issue by rowlock** [aidancbrady/Mekanism#2442]
Installing Mekanism v8 (both 8.0.3.207 and 8.0.3.212) causes several of the core AE2 recipes to become uncraftable. They no longer can be clicked in NEI, and laying out the items in a crafting grid causes no product. Encoded AE2 crafting patterns containing these recipes now show up as "Invalid Pattern".

Specifically, so far I have had the problem with both the annihilation and formation cores, and the interface block.

Removing Mekanism restores the AE2 recipes to functionality, including those in existing worlds.

**Comment by aidancbrady** [comment]
This is a well known issue that is solved by updating AE2.
