### ISSUE TITLE
[1.7.10] 8.0.3.207 Elite factory crafting bug

### ISSUE THREAD

**Issue by PatBattle** [aidancbrady/Mekanism#2456]
I apologize in advance if this was already posted, I tried searching but could not find a similar post.

Someone experienced a glitch while playing on my server while attempting to craft an Elite Factory (smelting). Upon placing the advanced factory in his crafting grid, his client would crash. While looking into what was happening, I was able to get it to work for him by removing the stored power (setting to zero with NBTExplorer) from the advanced factory. I just wanted to bring this to your attention in case this is an issue that has not yet been addressed.

**Comment by aidancbrady** [comment]
Thanks - this has been fixed in development
