### ISSUE TITLE
Crash with portable teleporter

### ISSUE THREAD

**Issue by Tergiver** [aidancbrady/Mekanism#2457]
Mekanism-1.7.10-8.0.3.207

I keep crashing when using, or even opening the UI of the portable teleporter. It's not happening every time. I used it once without problem. Used it the second time: teleported, then looked at the UI and crashed. Third time: looked at the UI and crashed. Fourth time: teleported, then looked at the UI and crashed.

A couple of crash dumps, they don't look useful:
http://pastebin.com/4yztu2Dq
http://pastebin.com/KWqHGEsV

**Comment by aidancbrady** [comment]
Fixed in development :)
