### ISSUE TITLE
Factory: when changing machine type, returned machine is broken

### ISSUE THREAD

**Issue by Sakata-MC** [aidancbrady/Mekanism#2458]
Mekanism-1.7.10-8.0.3.212.jar

Place a factory (tested with Elite Smelter), decide to change to purification.
Put purification machine into "I" slot to change the factory mode.

Expected behavior: Returns the smelter, able to place/change another machine, etc.

Observed behavior: Returns a broken item. Is movable in inventory, logged out of server and back in, still in inventory, but when put into chests, LP doesn't recognize it for extraction (not sure if AE will crash if attempted to store), and if attempted to place in world, item is destroyed and no block is placed.

**Comment by aidancbrady** [comment]
Fixed in v8.1 :)
