### ISSUE TITLE
Mekanism NEI issue?

### ISSUE THREAD

**Issue by accessdenied0** [aidancbrady/Mekanism#2459]
Dear Mekanism-team,

I'm sorry in the case this should be a dupe of https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1061, but I'm not sure because the crashlog looks in this case a bit different: http://pastebin.com/8T19rj3t...

Minecraft and the world loads up normally but if I try to "R" or "Left-click" in NEI for looking up a recipe, my game gets this crash... I know because of https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1061 there is/was an issue between AE2 and Mekanism, if this isn't solved yet... I use currently "Mekanism-8.1.0.214" and "AE2 rv2-beta-22"....

thank you for your support,

access_denied

**Comment by aidancbrady** [comment]
This is actually an issue with ModTweaker - they need to update integration.

**Comment by accessdenied0** [comment]
Thank you very much aidancbrandy...

 I'm sorry to bother you... but in this case for example I wasn't sure...

thank you again,

access_denied
