### ISSUE TITLE
Logistical Transporter crashes server

### ISSUE THREAD

**Issue by halvors** [aidancbrady/Mekanism#2460]
The logistical transporter somehow crashes the server, i don't know why caused this. The crash happend totally unexpected.

But seems from the crashlog to be related to ForgeMultipart.

Here is a crash log: http://pastebin.com/WbLT8W5j

This is a hard crash, i need to manually remove the crashing block. Cause restarting the server just causes another crash.

**Comment by aidancbrady** [comment]
Added a check - most likely due to the changed speed added in v8.1.

**Comment by halvors** [comment]
Nice :)
