### ISSUE TITLE
Portable Teleporter crash opening the GUI after teleporting

### ISSUE THREAD

**Issue by lehjr** [aidancbrady/Mekanism#2461]
The portable teleporter crashes when opening the GUI after teleporting:

http://pastebin.com/Pd4kcdTy

The log is from a development environment using commit 63f751c7103faa784ac42f8b100fb449804beda1 but also happens while playing a normal game. Note that while I have Industrialcraft 2 installed, this crash is without the quantum suit or any other armor or even inventory item. The first time the GUI loads fine and displays the destinations. After teleporting, if you open the GUI, it displays briefly but the list is empty and the game crashes.

**Comment by aidancbrady** [comment]
I can't reproduce this on my end.  Is this a one-time occurrence or you or does it happen consistently?

**Comment by halvors** [comment]
So far it just happend once. I've removed the logistical transporters with MCEdit and replaced them. 

Server starts just fine now. Is this some strange multipart issue?

**Comment by lehjr** [comment]
This happens very consistently for me. I'll try and upload a video of what's going on...

**Comment by aidancbrady** [comment]
Don't worry about it, just found and fixed the issue :)

**Comment by lehjr** [comment]
Yup, that fixed it :D
