### ISSUE TITLE
[Api improvement] More customizable jetpacks 

### ISSUE THREAD

**Issue by Radviger** [aidancbrady/Mekanism#2462]
Hi, @aidancbrady.
I've writing addon for mekanism for my server and I encountered a problem:
I've created electrical jetpack, it works on energy, but in main MC gui I see "Hydrogen" string instead of "Energy" or something I want. I think will be better to get the display string from main class of Jetpack and then I can override that method and write my own information.

Thanks!

**Comment by aidancbrady** [comment]
The Electrical Jetpack is part of IC2, not Mekanism.

**Comment by Radviger** [comment]
And what I need to do with jetpack on other gases?on methane, for example? I too see Hydrogen on main screen.

**Comment by Radviger** [comment]
On my add on, methane jetpack is an upgraded version of hydrogen jetpack.

**Comment by Radviger** [comment]
So, if electrical jetpack already exists in other mod I can't create it in my addon for Mekanism? Non-static jetpack info is a good feature I think.
