### ISSUE TITLE
Incompatibility with PrjectE!

### ISSUE THREAD

**Issue by MSandro** [aidancbrady/Mekanism#2463]
Mekanism crashs the game when some thinks form the mod ist lerned in the Transmutation Table/Tablet. I tould the ProjectE team about this bug, but they sayd, this is a bug at Mekanism side.
here is the crash-report:
https://onedrive.live.com/redir?resid=666547eb395d21fd!151931&authkey=!AE5ltHCXlPvhVpg&ithint=file%2ctxt

I play on the newes DNSTechpack with the Mekansim version 7.1.2.184. I have try to update the Mod to the newes version, but the same error comes up.

Sorry for my wrong english, I speak german

**Comment by aidancbrady** [comment]
This is fixed in v8.1 :)
