### ISSUE TITLE
Client & server crash

### ISSUE THREAD

**Issue by furest** [aidancbrady/Mekanism#2465]
Hi!
Since the v8 I can't play on my server...
As soon as I join the server, it crashes because of the electrolytic separator. I know which one it is and where it is. If I break it and re-place it, it connects to the cables it needs to and crashes. (Enderio gas conduits)
So I can't automate my base if I use those pipes (which I want to use)...
Here's the crash report of the server : http://pastebin.com/LNJDAs2U

Thank you for having interest in my problem
Furest

**Comment by aidancbrady** [comment]
EnderIO integration issue
