### ISSUE TITLE
Server Crash with Hydrogen Generator and EnderIO Conduits

### ISSUE THREAD

**Issue by Xaethon** [aidancbrady/Mekanism#2466]
http://pastebin.com/pQwPN8Mw

Mekanism 8.0.1.215

Not sure if this is EnderIOs fault, but it happened upon placing the Gas-Burning Generator next to EnderIO gas conduit line. Fixed it by removing the generator.

**Comment by aidancbrady** [comment]
Yes, looks like lab EnderIO integration issue - they should have a public fix out soon
