### ISSUE TITLE
Missing recipes and has become incompatible with the Applied Energistics 2

### ISSUE THREAD

**Issue by peppe99na** [aidancbrady/Mekanism#2467]
Since the last update made to Mekanism or 8.1.0.215 for minecraft 1.7.10 recipes ae2 I do not work anymore, only if I raise the Mekanism I work so try to fix the bug as soon as possible because this mod is fantastic especially if combined with ae2.
In addition I write from Italy
Thank You

**Comment by aidancbrady** [comment]
AE2 integration issue, they should have a fix soon

**Comment by enterprise12nx** [comment]
rv2.beta17 for mekanism: Fixes #1061 Most recipes are properly registered with new Mekanism. - thatsIch
are you using that or a later version?

**Comment by peppe99na** [comment]
@aidancbrady @enterprise12nx thanks for having responded to both
