### ISSUE TITLE
World freezing since updated to Mekanism v8

### ISSUE THREAD

**Issue by xJon** [aidancbrady/Mekanism#2469]
Here is the log: http://paste.ubuntu.com/10740367/
It happens without Fastcraft too.
Help? Thanks!

**Comment by aidancbrady** [comment]
This log...actually answers a lot of other questions.  Thanks for reporting, looking into.

**Comment by aidancbrady** [comment]
Fixed

**Comment by xJon** [comment]
Okay, thanks @aidancbrady.
I'll wait.

**Comment by xJon** [comment]
Sorry if I'm bothering you, but I wish to know if there's anything new, it's a bit urgent to me, I want to update and fix the broken build of the modpack. Thanks.

**Comment by xJon** [comment]
What build of Mekanism icludes this fix?
