### ISSUE TITLE
Adding Mek 8 to Bevos Teck Pack 11

### ISSUE THREAD

**Issue by moltar512** [aidancbrady/Mekanism#2476]
Hi.. I'm trying to add Mek 8.1.0.215 to BTP 11 on the ATLauncher.

I've updated AOBD [2.5.0], AE2 [rv2-beta-24], and WAILA [1.5.10].
I do not have Thaumic Energistics.  (This is all information from Reddit)

What happens is Minecraft boots up, but when I try to open my world, it just doesn't open and goes back to the start screen.  I don't see a crash-log.  The only log thing that I see is from the ATL console: 

http://pastebin.com/4QXZSFkZ

Looking at this, it seems to be complaining about ModTweaker... I tried updating that too, but it doesn't seem to work.  I am using ModTweaker-1.7.X-0.6-16.jar and I've tried upgrading to the latest ModTweaker 2-0.7.5.jar.  

Help!

**Comment by unpairedbracket** [comment]
What happens with ModTweaker 2-0.7.5? In what way does it not work?

**Comment by laz2727** [comment]
Maybe minetweaker is too old too.

**Comment by moltar512** [comment]
I'm also going to update MineTweaker3-1.7.10-3.0.8B.jar to MineTweaker3-1.7.10-3.0.9C.jar and see if that helps:

....

I updated, and the world started, but I think the world corrupted.
I loaded one chunk, and nothing else would load.
Then i relogged and nothing would load.

**Comment by unpairedbracket** [comment]
That is odd. Anything showing up in the log?

**Comment by laz2727** [comment]
Yep, current id system sometimes makes weird things with worlds. Check your
log.
06.04.2015 0:08 пользователь "moltar512" <notifications@github.com> написал:
>
> I'm also going to update MineTweaker3-1.7.10-3.0.8B.jar to
MineTweaker3-1.7.10-3.0.9C.jar and see if that helps:

**Comment by moltar512** [comment]
I copied back in my backed up save (always back up! lol)

We'll see if it recorrupts the world, and what the log says.

I know it asked if i wanted to remove Mekanism Friction Boots, and I said okay.
When it first loaded the chunk, some of my mekanism machines were in there, but all of the pipes had disappeared.  

Will know more in a few seconds.

**Comment by moltar512** [comment]
I replaced with a working save, and the world booted.

From the chat log in game:
ERROR: Error executing BR.zs: mekanism/api/PressurizedReactants

From the ATL log:
http://pastebin.com/HSb5zuwz

**Comment by aidancbrady** [comment]
Definitely not on our end.  Thanks for reporting though

**Comment by moltar512** [comment]
The world didn't seem to corrupt this time... pipes still gone.

Going to try to relog and see if i can still get in.

**Comment by moltar512** [comment]
nope.. logging in again, world still okay.

hmm...  thanks, maybe everything is fine, except for the pipes!

**Comment by laz2727** [comment]
Everything is fine, except FMP, most likely.
