### ISSUE TITLE
Crash on boot: mekanism/common/tile/TileEntitySalinationController

### ISSUE THREAD

**Issue by pamiller3** [aidancbrady/Mekanism#2479]
I am attempting to update my modpack and would love your v8 but I get this error everytime I try.  Any word what I am missing?

http://paste.ee/p/NqH0B

**Comment by aidancbrady** [comment]
EnderIO integration issue

**Comment by pamiller3** [comment]
Oh alright, thank you for the quick reply!! Is this something on the EIO side that I need to wait for?

**Comment by aidancbrady** [comment]
They should have some kind of dev build out, but in the case they don't, I know for sure that it has already been fixed on their end in development.

**Comment by pamiller3** [comment]
Oh alright thank you for your fantastic mod!

**Comment by aidancbrady** [comment]
Thanks for reporting!
