### ISSUE TITLE
Chemical Injection Chamber uses 10x more gas than v7, even after Gas Upgrades

### ISSUE THREAD

**Issue by infogulch** [aidancbrady/Mekanism#2483]
I performed a test in both v7 and the new v8.

I took an Elite Injecting factory with all upgrades (speed, energy, and gas for v8), filled it with HCl (1400 units), then disconnected all gas pipes. With Auto-Sort *off* (I want the factory's buffer, not its' slots) I placed crystals in the input and timed how long it took to run through the internal buffer of HCl gas.

In version 7, it processed 70 ores in 1:10 (70 seconds), so 20 units of HCl gas per crystal.

In version 8.1.0.216, it processed only **7** ores before it ran out of gas, taking 7 seconds for a full 200 units of gas per ore. Ten times more!

I want to stress that I had all 8 Gas Upgrades installed on the v8 machine.

**Comment by aidancbrady** [comment]
@unpairedbracket, mind taking a look at this?  I'm going to go ahead and push v8.1.1 but if this is trivial I can push out some kind of ninjafix later today.

**Comment by infogulch** [comment]
It looks like the commit just after [Gas Upgrades.][1]: [Recalcuation things.][2] could be the source.

In this commit machines were changed to calculate gas upgrades in `recalculateUpgradables(Upgrade)` overrided from [`TileEntityContainerBlock`][3]. The commit updates [`TileEntityChemicalDissolutionChamber`][4] and [`TileEntityFactory`][5] to use Gas Upgrades, and while there are some edits to the class hierarchy of `TileEntityChemicalInjectionChamber` -- namely, [`TileEntityBasicMachine`][6] and [`TileEntityAdvancedElectricMachine`][7] -- they don't appear to be in the same vein.

Of course, I'm not very familiar with the codebase and could be completely mistaken.

[1]: https://github.com/aidancbrady/Mekanism/commit/2e8edb281c309a7c7f5a3ed8874dc7055053f6be
[2]: https://github.com/aidancbrady/Mekanism/commit/c323969c87a25a4f81d265223d8d5aa2301df7ed
[3]: https://github.com/aidancbrady/Mekanism/blob/c323969c87a25a4f81d265223d8d5aa2301df7ed/src/main/java/mekanism/common/tile/TileEntityContainerBlock.java#L248
[4]: https://github.com/aidancbrady/Mekanism/blob/c323969c87a25a4f81d265223d8d5aa2301df7ed/src/main/java/mekanism/common/tile/TileEntityChemicalDissolutionChamber.java#L470
[5]: https://github.com/aidancbrady/Mekanism/blob/c323969c87a25a4f81d265223d8d5aa2301df7ed/src/main/java/mekanism/common/tile/TileEntityFactory.java#L1037
[6]: https://github.com/aidancbrady/Mekanism/blob/c323969c87a25a4f81d265223d8d5aa2301df7ed/src/main/java/mekanism/common/tile/TileEntityBasicMachine.java#L214
[7]: https://github.com/aidancbrady/Mekanism/blob/c323969c87a25a4f81d265223d8d5aa2301df7ed/src/main/java/mekanism/common/tile/TileEntityAdvancedElectricMachine.java#L413

**Comment by aidancbrady** [comment]
Just to be clear, 10x gas is used when 8 speed upgrades are installed, and adding more gas upgrades does not change that number?

**Comment by infogulch** [comment]
You can't install more than 8, right?

Or are you asking if gas upgrades have any effect at all? I'll test this, just a moment.

**Comment by aidancbrady** [comment]
Yeah, you can't install more than 8.  Installing speed upgrades should increase the gas consumption rate to 10x per tick (if you have 8 installed), but gas upgrades should lower that number back to 1x (again, with 8 installed).

**Comment by infogulch** [comment]
Ah, I wasn't aware those were the mechanics. I'll test them and report back.

**Comment by infogulch** [comment]
I altered my test to simplify it. I'm using just a CIC, not a factory. I fill up the internal buffer, remove the gas source, then put items in the input slot.

In  8.1.0.216:
* No upgrades: one item + a bit
* Gas upgrade only: almost 12 items
* Speed upgrade only: a small fraction of one item
* Gas and Speed upgrades: one item + a bit

**Comment by aidancbrady** [comment]
Yes - that sounds like correct behavior.  Is this different from what you were initially reporting?

**Comment by infogulch** [comment]
Right, compared to the v7 (updated my previous comment), this seems normal... and v8 non-factory compares well with v8 factories. I'll test factories again. Perhaps I'm just going crazy. :laughing:

**Comment by aidancbrady** [comment]
No worries!  Let me know, I'll close the issue if everything works out.

**Comment by infogulch** [comment]
So another, hopefully final, test. Back to elite factories. Same procedure: fill with gas, disconnect gas, put items in. I'm making guessing for processing that stopped while only partially completed.

In 8.1.0.216:
* No upgrades: 7.8 items
* Speed upgrades only: 0.8 items
* Gas upgrades only: 78.2 items
* Both speed and gas upgrades: 7.2 items

In 7.1.2.185:
* No upgrades: 7.8 items
* Speed upgrades: 6.8 items (this difference is strange, but not a big deal)

This is very consistent with the non-factory numbers I just got for both versions, yet very inconsistent with data from my first test! It seems my first data may have come from a significantly outdated version 7.

I suppose my only remaining complaint is game balance (which would be a separate issue), except there's already a config for this by making Brine production faster. Sorry for the trouble!

**Comment by infogulch** [comment]
Actually, it appears the config option has been reverted from the old issue I was looking at (#1847). I'll opening a new issue for Ore Processing Balance Config.
