### ISSUE TITLE
Heat Generators

### ISSUE THREAD

**Issue by ecoay** [aidancbrady/Mekanism#2487]
So I have been reading and saw where the problem with the heat generators power output is a GUI read error. This I feel is incorrect. The problem is the math. It is double calculating the output. IE coming and going.

Default settings put .4 joules to 1rf
D:RFToJoules=0.4

and then there is this 
 D:JoulesToRF=2.5

So when we have 

D:HeatGenerationNether=100.0

we would expect his output to be 40rf

however the output is 15.98 or 16. 

This is  is not just amount on GUI it is the amount test on Power meter multi-meter and capacitor

So instead of just doing 100 * .4=40rf it is doing 100 * .4/2.5=16rf

a temporary fix that doesn't effect the other machines that are operating correctly. is to do the math you want before input like for instance if you want it to be 40 rf  just do 40*2.5/.4=250

D:HeatGenerationNether=250.0  will yield you 40rf

**Comment by aidancbrady** [comment]
Update to the latest Mekanism build, I fixed this in one of the v8 bug fix releases.
