### ISSUE TITLE
Portable tanks load up slowly in NEI

### ISSUE THREAD

**Issue by Zaflis** [aidancbrady/Mekanism#2488]
Well, it seems to be the most likely cause at least. When i search NEI with "mek", i get 5 seconds long lagspike when first page is opened. I open page 2/4 and get another 3 second spike. Half the portable tanks continued to second page. But then pages 3 and 4 open fast. It only happens once, so once loaded they remain loaded until turn off Minecraft, i think.

I have fluids from ThermalExpansion, TinkersConstruct, Bigreactors, MFR, etc.

Tanks from other mods are not showing because INpureCore is hiding them. Mekanism doesn't seem supported.

Mekanism-1.7.10-8.1.0.215

**Comment by unpairedbracket** [comment]
Disable them in the Mekanism Config. Key general.PrefilledPortableTanks
