### ISSUE TITLE
Machine input sometimes gets stuck

### ISSUE THREAD

**Issue by thorjelly** [aidancbrady/Mekanism#2489]
After a chunk unloaded and then reloaded while machines were in use, some machines have gotten "stuck" in a state where they will not accept input from their input side. I believe this is caused by the machine thinking that it is still occupied even when it is empty, because if there is another item that can input to it which is of the same type that it is currently process, it will still be able to pull those items. But once it is unable to pull those items anymore, and the machine finishes and is empty, it will no longer pull any other type of item. If that item it had previously accepted is reintroduced to the transporter network, it will gobble those up again, but not accept any others.

In my example, I have a chest full of dust and a pipe that goes to 4 furnaces. 3 of the 4 furnaces will no longer pull any dust from the chest, even if they are empty. However, if I put a single dust in one of those furances that are not accepting input, then it will pull the rest of the stack of dust from the chest, and continue to do so until there is no more dust left to pull. When it finishes smelting, and is empty, it will stop accepting any input again. If I put dust of the same type it previously had been smelting back, then it will accept that dust, and only that dust, as input.

This state seems to continue even after I destroy and replace the blocks, as well as the item transporters.

Mekanism 7.1.2, with Minecraft 1.7.10, in the ResonantRise modpack.

**Comment by aidancbrady** [comment]
This was a bug that I fixed in v8, best advice I can give is to update :(
