### ISSUE TITLE
No dev downloads after 630?

### ISSUE THREAD

**Issue by vixblu** [aidancbrady/Mekanism#2491]
The changelog reads up till 636 (but downloads till 630), and I'd like to try the newer builds :-)

P.S. I also experienced bug #2474, tried build from #2478, but that didn't load properly, so reversed back to 630, but somehow that did the trick anyway, I don't experience the bug anymore.

**Comment by aidancbrady** [comment]
Ah, there was a bad import causing a compile failure. Should be fixed :)

**Comment by vixblu** [comment]
Fixed! Thanks :-)
