### ISSUE TITLE
NEI/Creativw Tab hang

### ISSUE THREAD

**Issue by CJL48** [aidancbrady/Mekanism#2493]
Minecraft freezes when I try to pull up the mekanism creative or nei tab in the latest version of resonant rise, 3.2.5.1
I belive this is due to the sheer number of items minecraft is attempting to display.

**Comment by aidancbrady** [comment]
Most likely due to the Portable Tanks. Disable "PrefilledPortableTanks" in your config.

**Comment by CJL48** [comment]
Thank you. Sorry to bother you.

**Comment by aidancbrady** [comment]
No problem at all!

**Comment by ShadowDrakken** [comment]
Since this continues to be an issue, even in the current build. Why not actually fix the bug that's causing portable tanks to crash everyone's games?
