### ISSUE TITLE
Laser Config Option Suggestion

### ISSUE THREAD

**Issue by PlanetBeast** [aidancbrady/Mekanism#2495]
Would it be at all possible to create a config option to toggle laser block damage? The biggest issue that I can see with the new lasers is the ability to grief with them on servers. Considering this couldn't be protected against it'd be nice to be able to toggle the block damage so they don't have to be disabled all together and make the fusion reactor useless.

**Comment by PlanetBeast** [comment]
Just tested the flamethrower. Would it be possible to get a toggle for that block damage as well. Not very server friendly :P

**Comment by ErkCurley** [comment]
I agree, this would be enormously useful for server owners

**Comment by aidancbrady** [comment]
You should be able to change the amount of energy required to break a block - would it be an okay compromise to just increase this to a much higher amount?  If not, that's fine, I can add a block damage property.

**Comment by PlanetBeast** [comment]
I mean yeah that could be possible to compromise on. It is always nice to have an option to disable it though, but if not I'm ok with it. I would however like an option for the flamethrower though, from what I remember I don't think there was a way around setting that with the current configs to not damage/change blocks. Thank you :)

**Comment by ErkCurley** [comment]
Yes, thank you. Config options would be best, especially because of the flamethrower damage.

**Comment by aidancbrady** [comment]
"AestheticWorldDamage" is the config property, expect it in v8.1.3.

**Comment by PlanetBeast** [comment]
Awesome thanks so much :)
