### ISSUE TITLE
java.lang.NullPointerException: Ticking block entity in Mekanism-1.7.10-8.1.1.218

### ISSUE THREAD

**Issue by jznomoney** [aidancbrady/Mekanism#2499]
When upgrading to the latest version of mekanism from MekanismGenerators-1.7.10-8.1.0.215 to Mekanism-1.7.10-8.1.1.218 I get this crash http://pastebin.com/NXMnZ06p I only have one set of teleporters on my map.

**Comment by aidancbrady** [comment]
Merging with #2508
