### ISSUE TITLE
Crusher bug with forestry saplings

### ISSUE THREAD

**Issue by DiegoAngelus86** [aidancbrady/Mekanism#2500]
Since a few mekanism versions back my apple oak saplings from forestry refuses to crush into biofuel anymore, any ideas about that ?

EDIT: I also recently updated forestry itself as there was a new version release of that recently, that could possibly have something to do with this.

**Comment by NitroxydeX** [comment]
În Mekanism 223 - respective 224 - it works fine.

**Comment by DiegoAngelus86** [comment]
When i updated my client to mekanism 223 it instantly crashed. So 223 at least was not a solution for me.

**Comment by NitroxydeX** [comment]
You tried 224? 223 only working with a higher forge version than 1291

**Comment by DiegoAngelus86** [comment]
224 was not available when i had time to test it last. I do now however...

And i have forge 1291, do you mean 223 requires a later version than that or that version or later ??

**Comment by NitroxydeX** [comment]
Yes. 223 requires Forge 1365. So try 224 its based on 1291

**Comment by DiegoAngelus86** [comment]
Just tried 224, still doesn't work. Is it tested to work with latest forestry ??

forestry_1.7.10-3.5.3.11 is what i'm using.

**Comment by NitroxydeX** [comment]
Using the same version and I have no problems. Could you try using a crusher factory instead of the normal crusher?

**Comment by DiegoAngelus86** [comment]
i tested it using a basic crushing factory...

Is there any easy way to compile a list of all my mods so you/anyone can see if there is something that could be conflicting ??

**Comment by NitroxydeX** [comment]
Screenshot? :D Easiest way.

**Comment by DiegoAngelus86** [comment]
You wanted a screenie and here you have it:

![ycp2 0 v1 6 mods](https://cloud.githubusercontent.com/assets/11894682/7107141/dec0d0d6-e15a-11e4-82e5-3a1ccc0d0372.jpg)

And then there are assorted mods for Flan but they are in the Flan's folder.

Complete pack for testing in case anyone wants it: http://www.filedropper.com/ycp20v16

**Comment by aidancbrady** [comment]
Not on my end regardless

**Comment by NitroxydeX** [comment]
Mhh. Would say it's growthcraft because I don't know it.

Otherwise here is a screenshot of my Modpack: 

![modpack_list](https://cloud.githubusercontent.com/assets/9305576/7107584/9d1c982c-e169-11e4-861d-fbc9801f2146.PNG)

If it's not growthcraft compare with my modpack list and remove all the Mods that I don't have. And then add one after one to test ist.

**Comment by DiegoAngelus86** [comment]
Tested the latest 225 version and after creating a new world it works again. However it won't work on an old world. Not anything on your end but still managed to fix it eh ??

**Comment by NitroxydeX** [comment]
No Mekanism issue. Just a hash Change in 225 for Multi Block l.
