### ISSUE TITLE
Typo in SynchronizedData.hashCode

### ISSUE THREAD

**Issue by emperor06** [aidancbrady/Mekanism#2501]
I think there are some typos in the assignments in the computation of hashCode().

https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/multiblock/SynchronizedData.java#L41

**Comment by aidancbrady** [comment]
What makes you say that?  Everything looks and compiles in order for me.

**Comment by emperor06** [comment]
I may be wrong but shouldn't it be "code +=" instead of "code ="? It seems that the whole method returns 31 * volume.

**Comment by aidancbrady** [comment]
Ah, you're right.

**Comment by aidancbrady** [comment]
Fixed!
