### ISSUE TITLE
All elite smelting factorys calling for fire in place of atomic core and gold ingots in place of enriched alloy

### ISSUE THREAD

**Issue by jjjworley** [aidancbrady/Mekanism#2503]
I'm not quite sure how to fix this? Versions 8.1.1.216 and 8.1.1.219

**Comment by NitroxydeX** [comment]
Could you provide some additional informations? Are you running it alone or in a modpack?

**Comment by aidancbrady** [comment]
Some mod is messing with ore dictionary registrations. Not on my end.
