### ISSUE TITLE
Crash when loading my world

### ISSUE THREAD

**Issue by abdullamu** [aidancbrady/Mekanism#2505]
my world crash when i load it 
http://pastebin.com/VCpu2EVG

i was in ender io they said its mekanism related 
https://github.com/SleepyTrousers/EnderIO/issues/2281

**Comment by TheJulianJES** [comment]
Removed OptiFine!

**Comment by abdullamu** [comment]
i did remove it and the problem still there http://pastebin.com/RCqNdcL8
 if its not supported that doesnt mean its the problem i have been using optifine since i started my world and without it my frames will be 0.5 fps, anyway the problem happened after i updates some mods

**Comment by abdullamu** [comment]
i found the problem it was after i updated forge to the latest and the cause of the problem is Fluid changes introduced with latest Forge
