### ISSUE TITLE
Server crash with dev build 647

### ISSUE THREAD

**Issue by vixblu** [aidancbrady/Mekanism#2511]
Can't get dev build 647 to work: http://pastebin.com/n9WETbAS

(haven't tried 644 to 646, build 643 is somewhat working (so I'm playing that now), although my water pumps to tank has some issues, haven't been looking close yet to see what it isn't doing right, don't need it that desperately right now).

**Comment by NitroxydeX** [comment]
You tried to update your forge to the latest build?

**Comment by vixblu** [comment]
Thanks, I did now (& should have done before...) :-)
