### ISSUE TITLE
Im getting a NULL Pointer Exception coming from the mekanism api: Crashes Server 

### ISSUE THREAD

**Issue by 1BADragon** [aidancbrady/Mekanism#2513]
Here is the Crash Report http://pastebin.com/raEjeEqS

Also the all the transportation ducts (cables, pipes, etc) lose their inventory spontaneously. For example my gas burning gens will lose there power when a cable is attached even without a machine attached on the other side. Same goes for the mechanical pipes and the pressurized pipes.

If you could take a look that would be great. Thanks

**Comment by aidancbrady** [comment]
This was fixed already, try updating to the latest release.
