### ISSUE TITLE
Solar Evaporator not producing brine (dev 647)

### ISSUE THREAD

**Issue by vixblu** [aidancbrady/Mekanism#2514]
Dev build 647, Forge 1370.
All seems hunky dory except the solar evaporator (in a Myst dimension); it's filled with water, has reached the highest temperature, but it doesn't produce brine.
When I entered the world my endless source of water at the pump station was gone, refilled it and the evaporator refilled and heated perfectly, except for the producing part.
No crashreport, but [here's the FML log](https://dl.dropboxusercontent.com/u/246119/Minecraft/logs/fml-client-latest.log) (too large for pastebin), which also mentions mekanism:water and mekanism:lava, can't remember if that was a thing before or not.

**Comment by NitroxydeX** [comment]
doubles with #2509 - mentioned the Solar plant there.

**Comment by Selgald** [comment]
Forge starting with 13.3.xxxx broke the most mod fluids, they now it, we have to wait for a fix.
Use Forge 13.2.1352 or 1291

**Comment by NitroxydeX** [comment]
Build 223 is build on The New fluid System but its not working

**Comment by vixblu** [comment]
Thanks for the suggestion and clarification, reverting back will not work for other mods in my mix, I'll wait then I guess... Build 647 doesn't work with 1291 anyway, so I've upgraded Forge to 1370, which required updating other mods as well.

**Comment by vixblu** [comment]
Just read the dev builds changelog, and I'm rolling back to Forge 1291 as well, so I'm closing this issue.
