### ISSUE TITLE
NPE in ThreadMinerSearch.java

### ISSUE THREAD

**Issue by solomon56** [aidancbrady/Mekanism#2515]
Exception in thread "Thread-97" 
java.lang.NullPointerException
       at net.minecraft.world.World.func_147438_o(World.java:3129)
       at mekanism.common.content.miner.ThreadMinerSearch.run(ThreadMinerSearch.java:72)

**Comment by aidancbrady** [comment]
Version?

**Comment by solomon56** [comment]
1.7.10-8.1.1.224

**Comment by aidancbrady** [comment]
Did this just happen once or is it consistent?  If it's a one time crash there's not much I can do.

**Comment by solomon56** [comment]
it happens occassionally on my server when player are using their digi miner. the miner will actually freeze and stick on a block and stop completely.  Is there anyway to check which block its colliding with during its search?

**Comment by aidancbrady** [comment]
It's strange - I only see this happening if the world is unloaded at the exact time a block is being checked.  It shouldn't crash the entire server regardless - does it?

**Comment by solomon56** [comment]
nope does not crash the server or cause any lag just makes the miner lock up and players complain

**Comment by jwmims** [comment]
We have this same exact issue. After some testing we have found that it is directly linked to the miner working in unloaded chunks. ACB any chance you have/think of a fix for this? We love this tool but I cant have it filling up the console with error messages galore.

**Comment by aidancbrady** [comment]
Added a try/catch, about the best I can do for now.  DM chunk loading will come soon enough ^^
