### ISSUE TITLE
Suggestion: Jetpacks

### ISSUE THREAD

**Issue by zzApotheosis** [aidancbrady/Mekanism#2516]
While I was getting acquainted with this mod, It seemed odd to me that I was able to walk on the ground faster than I could fly with the jetpack. I vote for an increase in jetpack flight speeds, namely horizontal speeds as vertical speeds are proficient. Perhaps you could implement an argument in the config for jetpack speeds or implement toggle-able modes for flight speeds in-game.

MCP version: v9.05
FML version: v7.10.85.1291
Forge version: 10.13.2.1291
Mekanism build: 8.1.1.224

**Comment by spookydonut** [comment]
Something ala MPS jet flight would be best.

**Comment by aidancbrady** [comment]
A "glide mode" is planned for the near future :)
