### ISSUE TITLE
Transporter Path and Speed Score

### ISSUE THREAD

**Issue by emperor06** [aidancbrady/Mekanism#2518]
I was testing out some new commits before applying them to my world when I found the following:
commits 36f0607d and 4ca9456d seem to suggest the chosen path for logistical transporters would now be the fastest path (rather than the shortest). I made a quick test and it happens that, for me, the shortest path is still chosen.
On the picture below, the chests are linked using ultimate transporters (the upper path) and then short-cut with a straight line of basic transporters. So top path is faster and bottom path is shorter. Items always go to the bottom path. Is that a bug?

![transporters](https://cloud.githubusercontent.com/assets/9116243/7115027/32b2fafa-e1e4-11e4-9b21-a92974b22220.png)

**Comment by aidancbrady** [comment]
It may be, doing some testing now.

**Comment by aidancbrady** [comment]
Fixed!
