### ISSUE TITLE
Where to use the energy

### ISSUE THREAD

**Issue by hisorange** [aidancbrady/Mekanism#2521]
Aye, so just a thing come into my mind, when mek8 come out I built the reactor and the induction cell as fast as my world allowed because they are awesome, it's requires alot of infrastructure, preplaning and resource but worthy on long distance :D Right now the mod got a way to generate a huge amount of energy and also a good way to store it, but where to use it? 

What I like in lasers that they got so many potential, what would happen if say so, someone points 4 laser arrays to a Laser Focus Matrix with some structure around it (multiblock) from 4 side and use the (yet non existing) by product of the fusion reactor to reorder the material's atomic structure :o a "new" material would born... yep my thought is to use the lasers to generate ingots / nuggets other raw materials.

What would make this different than UU-Mater? Not much, but how about if there is no preconfigured gui to choose: "I want goooold" but rather the user plays around the laser beams power and timing, and if things go wrong get a trashy output.

Thanks for reading it, i know it got a bit long, sorry for that :D

**Comment by aidancbrady** [comment]
Large-scale energy use machinery is planned for v9 or v10 :)

**Comment by hisorange** [comment]
Aww sorry, checked the milestones and didn't seen it that why opened the topic, at least gona have time to gather energy :D
