### ISSUE TITLE
Surprising Mechanical Pipe and TE's Portable Tank Integration

### ISSUE THREAD

**Issue by emperor06** [aidancbrady/Mekanism#2522]
I just report it because it seems a bit weird to me, no idea if that's a bug or not.
The setup is a Thermal portable tank and a mechanical pipe. The tank is full of water.
When the tank is in output mode (push fluids) and pipe in normal mode, water flows to the pipe (at the tank's rate).
When the tank is input mode and the pipe is in extraction mode, water flows (at the pipe's rate).
But now, when the tank is in output mode and the pipe in extraction mode, nothing happens.
That's the weird thing, the mechanical pipe can only extract fluids from input mode TE tanks.

**Comment by aidancbrady** [comment]
This is technically correct behavior, as extract mode does not accept any fluids from the connected source but instead attempts to manually pull it out.  Apparently TE's tanks have the exact same functionality, but swapped.
