### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Time6628** [aidancbrady/Mekanism#2523]
What causes this? Is it a incompatibility between Mekanism and Boantia?

http://pastebin.com/fTpGdHaS

**Comment by bjornthv** [comment]
Apparently it isn't incompatibility, because I don't habve Boantia on my server, but I get almost the same error:

http://pastebin.com/0dbyRA75

**Comment by aidancbrady** [comment]
Update to the latest Mekanism build, I believe @unpairedbracket implemented a fix for this.
