### ISSUE TITLE
Upgrade to new Mekanism causing server crash

### ISSUE THREAD

**Issue by Imaginativesoul** [aidancbrady/Mekanism#2524]
Love your mod, unfortunately i went from .224 to .225 and get an error on the linux server I am running.  Am I supposed to delete something after grabbing the new mod .jar files?

**Comment by Imaginativesoul** [comment]
Here is the error FYI: http://pastebin.com/09Grs5X3

**Comment by aidancbrady** [comment]
Fixed in development, hoping to push a fix soon.

**Comment by Imaginativesoul** [comment]
Fantastic, thanks for the response!

**Comment by aidancbrady** [comment]
Sure thing!
