### ISSUE TITLE
Single Player World stopping on opening inventory

### ISSUE THREAD

**Issue by JZELITE** [aidancbrady/Mekanism#2526]
So I recently updated several mods that myself and a friend were using for our SSP/LAN world. I was able to update all the other mods just fine, but when I installed the latest version of Mekanism (8.1.1.225) the world would load (slowly, but my PC is pretty much garbage, but it can usually let me play big packs at 15-25 FPS) and my FPS would be lower than normal and it would freeze and stop responding when I opened my inventory, when I looked at the log, there was nothing that looked like a crash, so here is part of the log: http://pastebin.com/wB0CEG3E

**Comment by RakovKreviech** [comment]
I'm having this same issue, when i type "Mek" for Mekanism mod in NEI it crashes my game and corrupts my save.

**Comment by aidancbrady** [comment]
Your log points to a non-Mekanism issue.  If you're having trouble with NEI, though, try disabling "PrefilledPortableTanks" in the config.

**Comment by RakovKreviech** [comment]
Thanks sir.
