### ISSUE TITLE
Server crash on disconnect

### ISSUE THREAD

**Issue by mrkirby153** [aidancbrady/Mekanism#2527]
When the player disconnects from a server after joining it, the server crashes with this crash:
http://pastebin.com/c6t5FZs9  

Server Log:
http://paste.ubuntu.com/10820073/ (Its really big)

Forge Version: 10.13.2.1352
Mekanism Version: 8.11.225

**Comment by aidancbrady** [comment]
Added a null check, thanks

**Comment by mrkirby153** [comment]
The bug is still present and looking in the Coord4D, I don't see any nullchecks or a commit entailing the fixed issue.
