### ISSUE TITLE
Server crash: Exception in server tick loop (MC1.7.10 + Mekanism 8.1.1.217)

### ISSUE THREAD

**Issue by bjornthv** [aidancbrady/Mekanism#2530]
I updated to the latest mekanism, and since I did, the server crashes intermittantly; Sometimes after 5 minutes, sometimes it lasts well over half an hour.

See the below pastebin for the details:

http://pastebin.com/0dbyRA75

**Comment by aidancbrady** [comment]
As noted in other issue, try updating to the latest Mekanism.
