### ISSUE TITLE
Logical Sorter mod ID Sorting

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [aidancbrady/Mekanism#2532]
I can sort just about anything. But when I try to sort by mod ID. I simply doesn't sort all the items of that mod. I am trying to sort Mekanism items & Thaumcraft items.

Version: 1.7.10-8.1.1.225

**Comment by MathiasDeWeerdt** [comment]
I've looked into the code and I think FML has a deprecated method. 
'findModOwner' Seems to be deprecated. 
http://cmicro.github.io/NeatCraft/forge-javadoc/cpw/mods/fml/common/registry/GameData.html

And it's used right here: http://puu.sh/hdEhR/2bd8ba4427.png

So the reason might be because it simply isn't updated? I would love some help :p

**Comment by aidancbrady** [comment]
Make sure you're using the correct mod ID.  There's really no other way currently to locate a mod ID for a given item, but I'll definitely change the way I do things if there is a new recommended method.

**Comment by MathiasDeWeerdt** [comment]
I added Thaumcraft for example. And I think about 60% of the items worked correctly. But all shards for example did nothing. They didn't do anything.
