### ISSUE TITLE
Under Water alert

### ISSUE THREAD

**Issue by suneetsharmaer** [aidancbrady/Mekanism#2535]
We are working on a project to make a alert system for scuba divers so divers can alert instructor if they are in a panic situation. We are trying to use piezoelectric sensor to transmit the sound waves which are received by receiver at the receiving end which consequently activates the buzzer.

I am struggling to work with piezoelectric transducer, which one to use to transmit signals efficiently. I dismantled the piezoelectric sensor from the home tweeter but it didn't work out.

Any suggestion will be appreciated.

**Comment by aidancbrady** [comment]
I think you've posted this in the wrong location :)
