### ISSUE TITLE
Crash after adding recipe

### ISSUE THREAD

**Issue by fangvo** [aidancbrady/Mekanism#2536]
When i add recipe with modtweaker and try to see it with nei i get crash 
java.lang.ClassCastException: net.minecraft.item.ItemStack cannot be cast to mekanism.common.recipe.machines.BasicMachineRecipe
full [crash log](http://pastebin.com/wCHPnjCg)

**Comment by aidancbrady** [comment]
ModTweaker is outdated, post on their end.
