### ISSUE TITLE
Basic Logistical Transporter and Logical sorter.

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [aidancbrady/Mekanism#2538]
Sometimes when we shutdown the server and reboot it. Some of the items above simply disappear. 

See picture: http://puu.sh/heGrO/3456d687dd.png

Note: This was a full sorting system. I come back to my server and I see this. I am using the latest version of mekanism. The server didn't crash I closed it used the stop command. 
This is the second time that this happend.

**Comment by MathiasDeWeerdt** [comment]
I've done some testing. And it seems that when the server closes when there are items in the transporters the transporter + item included seem to disappear. I've tested this and I can reproduce the issue.

**Comment by aidancbrady** [comment]
This is related to another issue that I've fixed on my end.
