### ISSUE TITLE
Duplicate Glitch with MFR LiquiCrafter

### ISSUE THREAD

**Issue by Radviger** [aidancbrady/Mekanism#2539]
A Dupe hapens when shift right-click on LiquiCrafter with recipe with configurator in Empty mode.
To pervent this I recomment to add this in Empty method in ItemConfigurator.java:

>if(inv instanceof TileEntityFactoryInventory){
>      TileEntityFactoryInventory mfrtile = (TileEntityFactoryInventory)inv;
>      if(!mfrtile.shouldDropSlotWhenBroken(i)){
>            return false;
>      }
>}

**Comment by Radviger** [comment]
May be you can correct the code to work without dependency.

**Comment by aidancbrady** [comment]
Done - now only works on Mekanism blocks
