### ISSUE TITLE
Odd Error 

### ISSUE THREAD

**Issue by enterprise12nx** [aidancbrady/Mekanism#2540]
getting this error, not sure if its ic2 or another mod

http://pastebin.com/QGTbbaxe

**Comment by TeranGR** [comment]
I am getting the same Error,but different entity. I started from version 8.1.0.Tried to update to 8.1.1 and the server shuts down with error:ticking tile entity (bin). I removed lit bins and turned off the rest bins. now i get the same error type with PrecisionSaw. Running Forestry,Buildcraft and NEI wtih Mekanism.

**Comment by enterprise12nx** [comment]
bump?

**Comment by aidancbrady** [comment]
Not sure what I could be doing wrong.  Try reporting to IC2 and see if they have any ideas.

**Comment by enterprise12nx** [comment]
i reported it to them, they said it was something about MFR block breaker but it was saying it was an open blocks block breaker and havent responded since
