### ISSUE TITLE
Forge 1355+ compatibility

### ISSUE THREAD

**Issue by tgstyle** [aidancbrady/Mekanism#2544]
I see there was a commit to revert?
https://github.com/aidancbrady/Mekanism/commit/03e45cc40134d2a6a004d8aa594bc5b3ab1be600

Is there a reason not to go to later Forge versions?

The Electrolytic Separator appears to be broken in anything above 1355.

**Comment by aidancbrady** [comment]
We will update forge in the next week.

**Comment by tgstyle** [comment]
Good news, the sooner the better.

Thanks!
