### ISSUE TITLE
[Suggestion] Liquid and Gas Filler

### ISSUE THREAD

**Issue by emperor06** [aidancbrady/Mekanism#2548]
Many devices in Mekanism can receive container items (energy cubes, buckets, gauge droppers, hohlraums, etc.) but they cannot output them when those items are full/empty.

While it may be a bit of a mess for energy, it would be very nice to have this feature for liquids and gases.
For example, we can pipe in empty buckets in a portable water tank but then we cannot pipe out the filled buckets.
Best candidates for this would be, imo, the portable tank for liquids and the gas tank for gases.
While TE offers an alternative for this on liquids (fluid transposer), there's nothing for gases. Having a possibility to fully automate the creation of filled hohlraums is the only thing we miss so far to fully automate a reactor startup/shutdown.

**Comment by aidancbrady** [comment]
Portable Tanks and Gas Tanks have been revamped to allow for this kind of interaction :)
