### ISSUE TITLE
Basic Logistical Transporter Crash

### ISSUE THREAD

**Issue by Xajar** [aidancbrady/Mekanism#2550]
When using Basic Logistical Transporter pipes and a Logistical Sorter, if both the destination and source inventories become full while items are in-route inside the pipes my server crashes.

![2015-04-16_13 46 25](https://cloud.githubusercontent.com/assets/11982490/7187683/48684aa4-e440-11e4-9099-748d333cd6a5.png)

Tested on both 8.1.1.225 and 8.1.1.226

Crash Log:
http://pastebin.com/JKBZS9cY

**Comment by MFernflower** [comment]
I have noticed a similar issue: http://pastebin.com/P9jguuGL

**Comment by EzerArch** [comment]
> I have noticed a similar issue: http://pastebin.com/P9jguuGL

Yours is more similar to #2537 than this here.

**Comment by jonpw** [comment]
just encountered this in build 229 as well, same crash report, when changing the side configurations of a cyclic assembler being fed through logistical pipes while items are enroute.

**Comment by chaorx** [comment]
Is there a workaround to get the server going, even though the issue persists?

**Comment by jonpw** [comment]
There's an option in forge.cfg to have it automatically remove erroring tile entities but it's a bit dangerous. I used it on my world to have it recover - it seemed to delete the entire pipe that had the fault (not just one block, but the entire connected logistical pipe. Other, unconnected, logistical pipe sections were OK) so it's a worry what else may get tied into it. Luckily it was only short in my case.

Perhaps, after backing the world up, enabling it for one load then disabling it and temporarily avoiding the use of logistical pipes would be the least risk.

**Comment by chaorx** [comment]
Thanks!

It worked like a charm!
I'm a bit hesitant to reconstruct the pipe though :)

**Comment by aidancbrady** [comment]
Fixed! Thanks :)
