### ISSUE TITLE
Balloons attach to the player with a gap

### ISSUE THREAD

**Issue by EzerArch** [aidancbrady/Mekanism#2552]
When balloons attach to the player, they have a gap between them and the player.

![2015-04-09_23 36 32](https://cloud.githubusercontent.com/assets/6743303/7193628/eab05fb6-e479-11e4-9753-445cc270bcef.png)

Probably it's not a Mekanism issue, rather a vanilla bug. It's because the players have their "collision" box 2 blocks positioned at the eye height (1.625).

**Comment by aidancbrady** [comment]
Do you know if this has always happened by any chance, or rather if it is a recent issue?

**Comment by EzerArch** [comment]
Sorry I can't tell. Probably it has always been this way since when dispensers could trap players with balloons (this is how I did to take that screenshot).

**Comment by aidancbrady** [comment]
Fixed!

**Comment by EzerArch** [comment]
Thank you, but I think you fixed it a bit "too much". The balloon was lowered so much that it attaches at the player's eye height, hindering the view.
![2015-06-17_22 41 54](https://cloud.githubusercontent.com/assets/6743303/8222452/15d73e1e-1542-11e5-9f20-b6a6b171c4bd.png)
