### ISSUE TITLE
Weird crafting problem

### ISSUE THREAD

**Issue by Bshof771** [aidancbrady/Mekanism#2553]
Ok, when I look at the crafting recipe on NEI its shows up the item "Fire" for any item that deals with osmium. Im trying to get started on this mod but when i try to craft the machine or object it will not show up as a craftable item! Plz Help

Here is a Screenshot of the fire and the crafting issue.
![2015-04-16_19 33 50](https://cloud.githubusercontent.com/assets/11986488/7194167/184064da-e470-11e4-90f7-1eb24386d95b.png)
![2015-04-16_19 35 41](https://cloud.githubusercontent.com/assets/11986488/7194171/1fd0c99c-e470-11e4-92d6-c53424b96573.png)

**Comment by Bshof771** [comment]
![2015-04-16_19 33 50](https://cloud.githubusercontent.com/assets/11986488/7194139/9ef4ce0e-e46f-11e4-8b3c-551f80542742.png)
Here is a Screenshot of the NEI bug

**Comment by Bshof771** [comment]
![2015-04-16_19 35 41](https://cloud.githubusercontent.com/assets/11986488/7194152/d00ef690-e46f-11e4-8d02-2d4eefda1640.png)
Here is a Screenshot of the crafting issue

**Comment by aidancbrady** [comment]
A mod is messing with OreDict registration, not on my end

**Comment by Bshof771** [comment]
Ohhhh ok thank you for pointing that out! Ill go and fix that
