### ISSUE TITLE
Mekanism limits gamma value ("Brightness" in-game setting)

### ISSUE THREAD

**Issue by Barhandar** [aidancbrady/Mekanism#2555]
Mekanism 7.1.2.157 or total absence of Mekanism - no gamma culling, 8.1.1.225 - gamma is being culled.

I would *really* like to know why does it do that (especially since only thing mentioning said value was the same in 7.X.X), what config setting turns the limiter off, and if it doesn't exist, why.

**Comment by aidancbrady** [comment]
I have no clue how or why this could be occurring, definitely not intended.  If you can pinpoint the issue I can try to fix, otherwise not much I can do.
