### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by Hirsu** [aidancbrady/Mekanism#2556]
Hi,

I'm running a local server with the Resonant Rise 3 modpack (latest version, 3.2.5.3).
It currently has Mekanism 8.1.0.215 running fine, up until now.

I was randomly running around in the world when the server suddenly kicked me out. The client didn't crash, but the server simply restarted. I was enable to reconnect to the server and walk around a minute or two before it happened again. Both times it generated this error in the crash report:

[Pastebin](http://pastebin.com/X4iu3ENG)

I've got no clue on how to figure out crash reports unfortunately, but mekanism seems to be involved in it somehow.

Could anybody point me in the right direction so I can figure out what's wrong?

Thanks!

Also: extra details:
- Java 8 Update 40 (64 bit)
- Windows 7 SP1
- i7 3770K @ 3.50 GHz
- 16 GB RAM (6 server, 4 client, 6 OS)
- Geforce GTX 780
- 2x 240 GB SSD

**Comment by JasperNL** [comment]
Same issue here: http://pastebin.com/JZ5u5FuD

**Comment by aidancbrady** [comment]
Fixed in development.
