### ISSUE TITLE
Request: Extra speed for ore processing

### ISSUE THREAD

**Issue by PiggyWhiskey** [aidancbrady/Mekanism#2557]
I've noticed that my factories have a constant bottleneck in the first step of the ore processing loop (Whether its the Purifier/Enricher etc) when bulk processing ores.

As the first step produces the quantities needed (x2/x3/x4/x5 production) it then gets stuck when the other machines are one for one.

Is it possible to have the production times reduced by a certain factor to prevent this.

i.e. Dirty dust's in the Enricher take a fraction of the time than if you were to put raw ores in (for doubling)

I'm not sure how you'll manage this when the purifier can produce either 1 clump (from Shards) compared to 3 clumps (from raw ore)

Just a suggestion/request.

**Comment by aidancbrady** [comment]
Honestly this is what speed upgrades should be used for - to help balance out your chain.  I don't intend to add any way to work around this in the near future.
