### ISSUE TITLE
[Integration] Universal Cables don't feed Tesseracts anymore

### ISSUE THREAD

**Issue by emperor06** [aidancbrady/Mekanism#2558]
I can't get any universal cable to push power into a TE's tesseract anymore.
Cables happily feed RF-based machines, RF-based cables, and tesseracts happily push power into universal cables.
I'm using a bufferless version of EIO's transceivers and they suffer the same issue now.
I have tried to tie up a universal cable to a TE's resonant fluxduct and it works.
Same thing but using a cryo-stabilized fluxduct instead (so no internal buffer), power won't go through.
It seems (but I may be wrong) that univ cables can't push into RF things that have no buffer.

**Comment by emperor06** [comment]
Yeah it seems that cables now use getEnergyStored() and getMaxEnergyStored() (part of the RF api) to determine the amount of power that can be pushed. This always fails on IEnergyReceivers that have no internal buffer (both methods in this case usually return 0).
I always wondered why the RF api gives access to a tile entity's internal buffer as it is implementation-dependent. I think IEnergyReceiver.receiveEnergy() is a better bet.

**Comment by unpairedbracket** [comment]
You're quite right, this should now be fixed in development and should be in stable builds soon.
