### ISSUE TITLE
AE2 Quartz Wrench does not work on Energy Cube

### ISSUE THREAD

**Issue by Fresh-Mutton** [aidancbrady/Mekanism#2560]
Tried repeatedly to shift+right click and even shift+left click, but the cube would not revert to an item. It could however change its orientation.

... and then I just broke the energy cube with a regular pickaxe and it retained all its energy. Was that... supposed to happen?

Also, for some reason, sometimes the energy core doesn't charge at all, even when the machines are all full. It also empties out entirely once it's connected to the machines.

**Comment by aidancbrady** [comment]
I can't do much about the Quartz wrench, but the functionality you just mentioned all sounds completely normal. Note that machines' buffers will be kept filled by a connected energy cube before its own buffer fills.
