### ISSUE TITLE
Latest Mekanism 8.1.1.225 Conflict with Thermal Expansion Tesseract

### ISSUE THREAD

**Issue by chloeprince** [aidancbrady/Mekanism#2561]
The latest version of Mekanism 8.1.1.225  is causing a conflict with Thermal Expansion - it causes the Tesseract to become disabled, not allowing power to transfer. This really messed up my world as we use them a lot to save on lag from long cables. 

It seems to be on the SEND side of the tesseract. If you hook up a mekanism universal cable to the send, the tesseract won't receive the power into the tersseract even though the cable is glowing green from being powered.

However, if I use a piece of enderIO conduit, the tesseract sends the power fine.
This was never a problem before.... The same world I had before, used to work fine. Now, since upgrading Mekanism, cables are working right with Tesseracts that were connected to them.

Thought I should report it in case others experience the same issue.
I had to roll back to Mekanism version 8.1.0.215, and everything in Thermal Expansion with the Tesseract started working.

This was using:

Forge .1343
ThermalExpansion-[1.7.10]4.0.1-182.jar
CoFHCore-[1.7.10]3.0.2-262.jar
Mekanism 8.1.1.225

Not sure if this is a Mekanism conflict or a Thermal Expansion issue. But the Tessaract is not working, either way.

**Comment by unpairedbracket** [comment]
I think this is the same as #2558, in which case it's fixed in development and should be in a build soon
