### ISSUE TITLE
Digital Miner + TE Cache = Item duplication

### ISSUE THREAD

**Issue by Merilix** [aidancbrady/Mekanism#2562]
How to replicate:

- put one Diamond (or whatever item/block you like) into an TE Cache
- place the Cache on the back of Digital Miner
- turn Auto-Eject on
- insert Gravel (or whatever blocks you dislike) into Miners inventory
--> all your Gravel will be turned into Diamonds :)

used Versions:
Mekanism 8.1.1.219
TE 4.0.0-176

**Comment by bochen415** [comment]
Post your CoFHCore version, remember that CoFHCore-[1.7.10]3.0.2-263 (yes the alpha) changed what can be imported into a cache and what can't be. Try to replicate the issue with that version.

**Comment by Merilix** [comment]
I had that issue with CoFHCore-[1.7.10]3.0.1-254.jar

Now tested with CoFHCore-[1.7.10]3.0.2-269.jar (only 6 hours old) but still the same.
I can duplicate whatever item i want using TE Cache with Digital Miner.

**Comment by aidancbrady** [comment]
What exactly is the TE cache used for?

**Comment by laz2727** [comment]
Barrel.

**Comment by bochen415** [comment]
One item type mass storage like a ^ barrel or MFR deep storage unit.

**Comment by aidancbrady** [comment]
Huh, I'll take a look. I don't think my auto eject implementation could cause that, though...

**Comment by Merilix** [comment]
Just realized, the same happens with other machines also if they are set to eject their output directly into TE Cache. (e.g. for mass smelting cobble into smooth stone)
If i try to smelt something else, the caches item count is still increased regardless if the item type matches.

**Comment by bochen415** [comment]
Maybe @KingLemming could shed some light on the issue.

**Comment by aidancbrady** [comment]
Seems like a TE issue then.  Closing until further notice
