### ISSUE TITLE
Electrolytic Separator not separating in 1.7.10

### ISSUE THREAD

**Issue by Pyroglyph** [aidancbrady/Mekanism#2563]
Hi, I'm not sure how the GitHub issue system works, but I have an issue.
The electrolytic separator doesn't seem to be separating water. I've provided more than enough power  and it's not dumping anything (as seen in picture below).

![image](https://cloud.githubusercontent.com/assets/9498104/7216928/38f241a4-e609-11e4-8597-a0435dd92c62.png)

So why isn't it making any gas?

This is on a server running Forge 10.13.3.1374. There are no errors in the console.

My mods list is here:
  * TreeCapitator
  * Lucky Blocks
  * Battlegear 2
  * Backpack
  * BattleTowers
  * InvTweaks
  * JourneyMap
  * Mekanism (+ Generators + Tools)
  * Minions
  * OpenBlocks
  * OptiFine
  * QuiverBow
  * DamageIndicators
  * DogeMod
  * Infernal Mobs
  * More Swords
  * NEI

**Comment by unpairedbracket** [comment]
This is due to changes made in the Forge fluid system. We will be releasing a build with this fixed shortly.

**Comment by Sslazz** [comment]
"Me too". Shared mods are Journeymap, Quiverbow, Openblocks.

**Comment by Pyroglyph** [comment]
@unpairedbracket When you say 'shortly', how long will that actually be? Out of context, it could be any length of time. I'm not trying to rush anyone, I'm just trying to get a timescale.

**Comment by 2019ygao** [comment]
This way I can know when is the right time to craft my jetpack

**Comment by 2019ygao** [comment]
I have the exact same problem

**Comment by kleineMade** [comment]
Hello,
thank you for this mod. I like this mod so much. 
And i have the same Problem ;-)
I cant programm with java, but if i can help with testing...?

**Comment by tj-miller** [comment]
Has this been patched already?

**Comment by mcgraj3** [comment]
Just to note, I am using Forge 1291 since it still works with the rest of my mods. Mek v8 works without issue.
