### ISSUE TITLE
Energy Network Crash

### ISSUE THREAD

**Issue by compwiz1548** [aidancbrady/Mekanism#2565]
I compiled the development branch for the fixes to the fluid system.  Once I placed down a machine the server began into a crash loop with this crash report: https://gist.github.com/compwiz1548/379ad9e2f6cabf1eecaf  Look to be caused by the energy network changes also in the development branch.

Using Forge 10.13.3.1374

**Comment by RAWRwins254** [comment]
http://pastebin.com/X4dm7LJ3 <--- also experiencing the above crash except it's not looping. Using forge 10.13.3.1373.

**Comment by halvors** [comment]
Same here. https://gist.github.com/halvors/b340f255eb2437183502

**Comment by MastaC729** [comment]
I can confirm the same problem.

**Comment by RAWRwins254** [comment]
Quick request for you all: can you peeps please post a modlist? I'm beginning to suspect a bad interaction with another mod (specifically Thermal Expansion's Tesseracts). If your worlds have tesseracts, please comment and even if they don't, comment. I think i'm seeing where this is going awry but I can't be 100% sure.

**Comment by RAWRwins254** [comment]
Never mind that! Thanks to Zaggy1024, I believe i have fixed the issue. It requires manually editing the source java file located at src/main/java/mekanism/common/base/EnergyAcceptorWrapper.java. On line 21, replace the text there with this to prevent the NPE: if(tileEntity != null && tileEntity.getWorldObj() == null) ... I will submit a pull request shortly.

**Comment by RAWRwins254** [comment]
https://github.com/aidancbrady/Mekanism/pull/2579 is my pull request. Those are you who are impatient can use my repo for the time being until this either gets merged or denied (why would they deny a fix?).

**Comment by RAWRwins254** [comment]
Aidan has merged my pull request. OP: recommend you close this issue.
