### ISSUE TITLE
Download Page Changelog

### ISSUE THREAD

**Issue by karakufire** [aidancbrady/Mekanism#2566]
I want Changelog in Mekanism Download Page.
It helped me to confirm about what changed at latest relese.
Why removed it when Mekanism8 relese?
And Could you set changelog in download page again?

**Comment by karakufire** [comment]
postscript:I can find changelog only in legacy download page.

**Comment by aidancbrady** [comment]
For now, this is necessary - overwhelming Jenkins API queries were crashing the build server.
