### ISSUE TITLE
Logistical Transporter crash on server startup.

### ISSUE THREAD

**Issue by halvors** [aidancbrady/Mekanism#2569]
When i places Logistical Transporters on my server everything works fine at first.

It is when i restarts the server that i'm getting the crash.

Here is the stacktrace: http://pastebin.com/c5W51zWR

**Comment by aidancbrady** [comment]
This is fixed in development. I've been fairly busy over the past week but I hope to get the new release pushed soon.

**Comment by halvors** [comment]
@aidancbrady Are you sure? Still crashing with latest development build...

**Comment by aidancbrady** [comment]
Pretty sure, not sure why you wouldn't have the fix too. I'm without a computer for the next few days though... Hang tight :)
