### ISSUE TITLE
Transporter Path Finder Crash at World Loading

### ISSUE THREAD

**Issue by ZealousZcar** [aidancbrady/Mekanism#2570]
I got this crash in another version of Mekanism, but when I upgraded to 228 it fixed it. Now after a few weeks with 228 I get the same problem again. 

http://pastebin.com/nxY1sHB3

I will need to downgrade to 216 again to play Minecraft.

**Comment by MastaC729** [comment]
I have confirmed that this issue was fixed in developmental, but now the problem is the energy network  intermittently crashes. I think 228 doesn't have the necessary changes to TransporterPathfinder merged yet.

**Comment by ZealousZcar** [comment]
Aidan said that he fixed it in developmental, that was before 228, which actually fixed the problem.

**Comment by ZealousZcar** [comment]
Why did you close this Aidan?

**Comment by aidancbrady** [comment]
It's fixed on my end in development and we're nearing a release. Expect an update in the next 2 days
