### ISSUE TITLE
Small issue with IC2 classic

### ISSUE THREAD

**Issue by Carbon-Ghost** [aidancbrady/Mekanism#2571]
Energy tablet is not accepted in IC2 classic storage units, this is due to the electric manager not working with IC2 classic, from what I understand, to fix this, you will need to look if IC2 classic is loaded or not, the API files should provide you with everything normally, if not, contact Speiger, the mod author, he said he will provide help if you need him ^.^

Have a nice day :)

**Comment by aidancbrady** [comment]
Would rather not add integration for the now-deprecated IC2 classic, sorry.

**Comment by Carbon-Ghost** [comment]
Wait, not that IC2 Classic Aidancbrady, there is 2 versions, the Immibis discontinued one, and Speiger up-to date fully functionnal, with only minor mod interaction issues, like this one :o , please take a look on it ^-^

**Comment by Speiger** [comment]
@aidancbrady that version that carbon-Ghoest is talking about is not Deprecated at all.
Also i checked through the source how the stuff gets handled.
And that part which is used with your batteries in IC2 Classic (SpmodVersion) is 100% identical with the IC2 Exp code. So whatever it is causing that. It is something that you expect to get but not receive...
Check your sourcecode please and look whats causing that.
