### ISSUE TITLE
reactor lag

### ISSUE THREAD

**Issue by Flukethoughts** [aidancbrady/Mekanism#2574]
58.11%	  58.21%	371.41 s	    29.10 ms	 1.0	      12.8k	    Full Server Tick
Learn More

      23.25%	  23.29%	148.62 s	    11.64 ms	 1.0	      12.8k	    world - tileEntityTick
      20.83%	  20.87%	133.15 s	    10.43 ms	4,231	  53,997.3k	    tickTileEntity
      14.05%	  14.07%	 89.78 s	     7.03 ms	 1.0	      12.8k	    world - entityTick
      13.96%	  13.98%	 89.21 s	     6.99 ms	 712	   9,082.2k	    tickEntity
      12.96%	  12.98%	 82.86 s	     6.49 ms	 519	   6,619.3k	    Activated Entities
Learn More

       9.32%	   9.32%	 59.56 s	     4.66 ms	 2.8	      35.8k	    tickTileEntity - TileEntityReactorPort

this is just one reactor built on the server Recator is connected to a TE cryo power tube

**Comment by aidancbrady** [comment]
I'll wait to hear @unpairedbracket's take on this, but it would help a ton if you could do some form of VisualVM profiling so we can have a better idea of what's going wrong.

**Comment by aidancbrady** [comment]
Closing- I've heard no other complaints regarding this, and reactors have been running just fine on my test server.
