### ISSUE TITLE
Electrolyctic Separator not working

### ISSUE THREAD

**Issue by gabrieltm9** [aidancbrady/Mekanism#2575]
Hi!
First of all, i love your mod. Second, when i place down an Electrolyctic Separator, water pumping in through the top and power from the back, it doesnt work. No Hydrogen or Oxygen appears inside the GUI. I know what you are thinking, and no, i do not have it se to Dump the gases and there is no container that they could be going into.

Any ideas?
Thx, Gabe

**Comment by gabrieltm9** [comment]
Ok, i have narrowed down my issue to not being able to change the Dump buttons to Hydrogen and Oxygen. I can only change it to None, Dumping, and Dumping excess... Help?

**Comment by EvulOne** [comment]
The dump buttons each control one side.  The one on the left will dump the left tank's contents, and the one on the right will likewise the right tank.

**Comment by ShneekeyTheLost** [comment]
I'm getting the same problem of the Electrolytic Separator not functioning.. Looks like it is related to the Forge Liquid Handler update in 1351

**Comment by tj-miller** [comment]
Same issue here.  I tried everything that was said above.  What is the status of this bug fix? Amazing mod btw.  I hope it gets fixed.

**Comment by gabrieltm9** [comment]
+EvulOne i know, but it just doesnt make anything to dump. If i set both buttons to None no gases get generated. And i cant set it to Oxygen or Hydrogen

**Comment by gabrieltm9** [comment]
Also, i have tried to downgrade a few versions back and have only been able to get it to work in Mekanism v7, not v8...

**Comment by tj-miller** [comment]
I tested it with Forge 1388 and no luck.

**Comment by gabrieltm9** [comment]
+tj-miller Same. I think its a mekanism bug...

**Comment by tj-miller** [comment]
Sorry to post again so soon, but wanted to report that Forge 1389 did not fix it.  I agree with gabrieltm9, it appears to be a bug in Mekanism.  I'm not totally sure what changed between the Forge versions to make the option for Oxygen and Hydrogen disappear.

**Comment by Tetrajak** [comment]
I'm having the same issue with mek build 8.1.1 andforge build 1355 or later. Electrolytic separators will accept water and energy just fine, but won't create hydrogen or oxygen anymore. I've tried setting both sides to different things (idle, dumping, etc), and no luck, both gauges remain empty. Oxygen tanks pulled from creative work just find, and empty into other machines and the gas gets used up by said machines as normal.

**Comment by ShneekeyTheLost** [comment]
What happened was the Forge Liquid Handler got changed in 1351. You will have to roll back Forge to get this to work again

**Comment by gabrieltm9** [comment]
+ShneekeyTheLost Has anybody tested this? And if so, please post which version of forge this worked with. ANy version before 1351?

**Comment by tj-miller** [comment]
I havent been able to test an earlier version before 1351 because it would require me to downgrade from 1.7.10 to something lower.  And most of ny mods require 1.7.10 so...

**Comment by Tetrajak** [comment]
Just chiming in that versions of forge before 1351 work fine on 1.7.10. I had to downgrade a few other mods that needed later versions of forge to get it all to play nice, but it works now.

**Comment by RAWRwins254** [comment]
Hey guys. I plan on asking @aidancbrady if I can temporarily host a few jars until they can get the development branch published as a new build. If you know How to use forge workspaces, you can manually build the development branch of this repository and plug thus jars in to fix the issue. If you don't know that stuff, I'm going to contact aidan later today.

**Comment by aidancbrady** [comment]
Fixed in development
