### ISSUE TITLE
Cables and Energy Cubes don't connect to EnderIO generators/machines

### ISSUE THREAD

**Issue by MrKunji** [aidancbrady/Mekanism#2576]
![](http://i.imgur.com/YAhQ45p.png)
Any EnderIO generator don't output power to Energy Cubes, even with a EnderIO cable.
Universal Cables don't touch EnderIO machines, and don't transfer power to them.
Tried every possible side configuration.

**Comment by EvulOne** [comment]
I'm not seeing this issue... what version of Mek are you using?  I have (ultimate) energy cables attached to all my EnderIO machines, and just tried it with a EIO Stirling generator, and all connect just fine.

**Comment by MrKunji** [comment]
Thanks, I forgot to mention. Using 228 of Mekanism, and the latest of EnderIO.
I'll install CoFH Core to test, maybe it's something API related.

**Comment by XFactHD** [comment]
Can't be API related, EnderIO is shipping the RF API files it needs to work.

**Comment by MrKunji** [comment]
Confirmed, installing CoFH Core does makes everything behave as it should. Are Mekanism and EnderIO using a different version of the API by chance?

**Comment by aidancbrady** [comment]
Currently "intended" - Mekanism only interacts with RF if CoFHCore is installed.  This may change in the near future.
