### ISSUE TITLE
Suggestion: cardboard box whitelist

### ISSUE THREAD

**Issue by BBoldt** [aidancbrady/Mekanism#2577]
I have mekanism in quite a large pack, and there are tons of things that shouldn't be able to be moved with the cardboard box. 

It would be a lot easier for me to make a list of things that *should be* able to be moved than it would be for me to make a list of things that *should not* be moved.

**Comment by EvulOne** [comment]
I would suggest perhaps removing the use on "any block".  Machines, tanks, chests, etc yes should be able to be boxed up, but random blocks don't really have a need to be "boxable".

**Comment by aidancbrady** [comment]
The intended behavior of the box is to be able to pick up and move any block in a Minecraft world - this could be anything from a block of dirt to a Mekanism energy cube.  The blacklist is the best way to accomplish this.
