### ISSUE TITLE
Upgrading to Mekanism v8 removes upgrades on all machines

### ISSUE THREAD

**Issue by mcgraj3** [aidancbrady/Mekanism#2578]
While I should have expected this, it wasn't a huge deal since I just restarted my world (lost about 30 speed/energy upgrades). If you are upgrading to Mekanism v8, pull your upgrades out of your factories before restarting to update the mod. You can thank me later. :)

As far as fixing this issue? Not sure you can, but it should be reflected in the [Upgrading to Mekanism v8](http://wiki.aidancbrady.com/wiki/Tutorials/Upgrading_to_Mekanism_v8) wiki page. :+1:

**Comment by aidancbrady** [comment]
This is part of the known consequences of updating - as you stated, pulling them out first will allow you to convert without loss.
