### ISSUE TITLE
Mechanical and Pessurized pipes bug

### ISSUE THREAD

**Issue by Master-Jynx** [aidancbrady/Mekanism#2580]
An SMP server I play one is using version 226 and the mechanical and pressurized pipes will stop functioning when their chunk is unloaded then reloaded.

I had left my base to help another player, upon returning, Mechanical pipes that were used to supply water to boilers and steam to a turbine were empty, the turbines were almost dry, the accumulator
couldn't feed water into the pipes and the turbine had shutdown from a lack of steam.

I had to break every single pipe and place them again to get the system back up.
Breaking/Replacing 1 segment doesn't work, the entire netwoork must be replaced
each and every time.

**Comment by smbarbour** [comment]
Same server, different player, with screenshots: http://imgur.com/a/WlSgk  Also affects universal cables, but oddly always the same ones while others in a different chunk nearby have not had a problem.

**Comment by downslope7** [comment]
We're seeing the same thing on Mekanism 225. Has happened every time we've restarted the server in the past 24 hours.

**Comment by aidancbrady** [comment]
Fixed in development.

**Comment by smbarbour** [comment]
This issue is still present in 8.1.2.229.
