### ISSUE TITLE
Pressurized Reaction Chamber Bug

### ISSUE THREAD

**Issue by jznomoney** [aidancbrady/Mekanism#2582]
When upgrading the speed of the pressurized reaction chamber speed to 8 the machine stops working converting substates to hdpe pellets.  I am using the developmental branch at commit 5baf4605e0aab0c1ea6c2d12c14c7f8fcb1bbaf8.

**Comment by jznomoney** [comment]
If I remove the speed upgrades it works again.

**Comment by xGhost169** [comment]
Add energy upgrades to it, it won't have enough power with only speed upgrades.

**Comment by RAWRwins254** [comment]
Also would like to take the opportunity to mention that there's a newer commit for the development branch that fixes the nullpointerexception (npe) caused by a miscode. Otherwise, I support the previous poster's comment.

**Comment by aidancbrady** [comment]
Correct - add energy upgrades :)
