### ISSUE TITLE
Feature Request: Explosives

### ISSUE THREAD

**Issue by Badcholo** [aidancbrady/Mekanism#2583]
ICBM isn't being updated and us voltz fans could use some actually working explosives at 1.7.10
I think Mining explosives or building explosives, or animal explosives are just dumb. Please only allow the antimatter explosive to go past MFFS force fields. I love mekanism and all mods that are like it, but some have been abandoned and aren't getting updated to 1.7.10. We are just so sad to have to keep playing Voltz at 1.5.2. it would be great to be able to play it at 1.7.10 with mekanism.
1). Antimatter: Destroys everything. Not Bedrock,
2). Nuclear: Half as strong as antimatter, but leaves Radiation.
3). Fusion Reactor: Produces a byproduct, Used to create Antimatter.
4). Small Nuclear Explosive: Half as strong as Nuclear, doesn't leave radiation or for a short while.
5). Sonic explosive: as strong as 5xtnt, launches blocks in all directions.
6). dynamite sticks/grenades: half as strong as Explosives.
7). Config to remove explosives.

**Comment by aidancbrady** [comment]
I've already been considering this - @calclavia and I actually spoke a few weeks ago about perhaps me updating ICBM to the latest version.  Closing, but know that it is being considered :)
