### ISSUE TITLE
Mekanism Causing Invaild Server State Along With Forge Multipart

### ISSUE THREAD

**Issue by msgtfox** [aidancbrady/Mekanism#2584]
So Mekanism is crashing due to pathfinding in the logistic pipes, which really really saddens me because I LOVE Mekanism, been using it for over a year now.
But it seems like the issue is also somewhat being caused by forge multipart.
So I wanted to submit this bug report to you.

Here's a link for the crash-log: http://pastebin.com/En865tiC
Using paste bin so I don't flood this box.

**Comment by Flukethoughts** [comment]
hey partner we been using that multipart with no issues so far but i will say we are also using 1307 of cauldron

**Comment by msgtfox** [comment]
Didn't they stop with Cauldron?

**Comment by Flukethoughts** [comment]
Im not saying it stopped with cauldron as I haven't ran strictly forge base in some time

**Comment by msgtfox** [comment]
Oh I know, I'm saying I thought the makers of Cauldron removed all their stuff last year.
So it just surprised me.

**Comment by Flukethoughts** [comment]
I can only legally say cauldron exist out there with the latest forge

**Comment by msgtfox** [comment]
Very curious you are, but we probably shouldn't have casual conversations in the comment box, heh.

**Comment by RaRaRasputin** [comment]
I've been experiencing this same bug. Here's my crash log:
http://pastebin.com/PVay2NA4

**Comment by aidancbrady** [comment]
Fixed in development.
