### ISSUE TITLE
translate 

### ISSUE THREAD

**Issue by Flukethoughts** [aidancbrady/Mekanism#2588]
TRF MRF KRF GRF
Can someone translate this for me?
Because I don't feel like it's the same as the regular numbers
I keep wanting to read it like ever other mod
K=1.000
M=1.000.000
t=1,000,000,000,000
Is there a setting where I can get these number to out put correctly?

**Comment by aidancbrady** [comment]
That is correct by SI unit definition, and that functionality is already present in Mekanism.
