### ISSUE TITLE
Logistical Transport Tubes stop routing properly after reboot

### ISSUE THREAD

**Issue by TacoMage** [aidancbrady/Mekanism#2591]
I've seen a few instances of logistical transporters losing track of color routing information after a reboot.  However, after breaking, replacing, and re-coloring the affected sections, they will begin to function again.

It's really intermittent and I can't seem to find any rhyme or reason behind it.

**Comment by aidancbrady** [comment]
What exactly do you mean by color routing information?  The actual item color is disappearing, or just the path is misbehaving?

**Comment by TacoMage** [comment]
Just the path is misbehaving.  The track is still visibly whatever color it's supposed to be, but colored item won't rout down it.  Rather they'll pass right by, bounce around a bit, and then return to their origin point (or if there's a longer/non-preferred way out of the system, take that rout instead).  Logistical sorters will still apparently try to use the path, because they'll continue to output items, but those items won't rout to the colored path.

In every case, breaking the misbehaving pipe and replacing it will fix the issue while changing the color of the pipe to something else and then back does not work.

**Comment by aidancbrady** [comment]
Hm. I think I may know the source of the issue... Let me try a few things.

**Comment by aidancbrady** [comment]
@TacoMage, do you have dev server access?  If you do, try out the latest dev build - it should mention something about transporters in the changelog.  If not I'll send you a key, you're plenty dedicated enough ^^

**Comment by TacoMage** [comment]
I'll talk to Towsty this evening and see about pushing the latest dev to the server; pretty sure we both have access to dev builds.  Should know whether it's still a problem after a few of the scheduled reboots.

Thanks!

**Comment by aidancbrady** [comment]
I've solved the issue. The fix will be in Mekanism 8.1.2, as soon as I have time for a release.
