### ISSUE TITLE
Game crash when trying to use NEI to see recepies

### ISSUE THREAD

**Issue by drago87** [aidancbrady/Mekanism#2592]
Wehn i hover over a item (dont seem to be a perticular mod) and press "u" or "r" to see what the item can be made with it the game crashes. (This started to happen after i uppdated forge to "forge-1.7.10-10.13.3.1391-1710ls"). if i remove mekanism it works normaly (using V 1.7.10-8.1.1.228 of Mekanism, MekanismGenerator and MekanismTools)

OpenEye: http://openeye.openmods.info/crashes/af6d0d4458ab8e71a8a2235868dd46d9
Crash Report: http://pastebin.com/ShU471DV

**Comment by aidancbrady** [comment]
This is a ModTweaker issue
