### ISSUE TITLE
Crash caused by Digital miner custom dictionary

### ISSUE THREAD

**Issue by Dommain** [aidancbrady/Mekanism#2593]
If you put  " (Asterisk)av(Asterisk) " into custom dictionary in the The-1.7.10-Pack, it will crash.
https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/525
http://pastebin.com/MmCn7UeU

**Comment by aidancbrady** [comment]
Looks like an NEI issue.

**Comment by Dommain** [comment]
Happen to know where I can post for NEI?
