### ISSUE TITLE
Reactor ignoring injection rate.

### ISSUE THREAD

**Issue by hisorange** [aidancbrady/Mekanism#2594]
Aye, not sure if intended that's why opening this issue, but normaly when you infuse the D-T fuel with the reactor the injection rate works as intended but if I infuse and then inject it into the reactor the injection rate will be as much as the gas tube can push in and ignoring the injection rate / internal storage.

Now its still possible to adjust the injection with power upgrades and bottlenecks but I suspect the D-T fuel simply ignores the internal setting.

v8.1.1.228

**Comment by aidancbrady** [comment]
It does. This is for the most part intentional - if you want to bypass the defined injection rate you can just forcefully insert the fuel into the reactor core.

**Comment by BeardedGrue** [comment]
The reactor appears to ignore the internal buffer of fuel when it is not "forcefully" injected.  I will retool and let the reactor mix the fuel to avoid this issue.  Perhaps removing the internal buffer for DT fuel, or disabling the ability to use DT Fuel directly, would be something to consider to avoid complaints of the mod being broken.

**Comment by Radon8472** [comment]
> It does. This is for the most part intentional - if you want to bypass the defined injection rate you can just forcefully insert the fuel into the reactor core.

I was wondering to, why you are able to set an injection rate, and it is fully ignored.
I think for less confusion the reaktor should 

- either respect injection rate for dt fuel
- or, setting of injection rate should be disabled, when using dt fuel

Haveing the option to do configuration that is fully ignored, is massive confusion

**Comment by pupnewfster** [comment]
Injection rate means at what rate the reactor injects deuterium and tritium as (combining it into) D-T Fuel
