### ISSUE TITLE
Forge 1355 Salination bug

### ISSUE THREAD

**Issue by Keridos** [aidancbrady/Mekanism#2595]
For me on forge 1355 forge  (which I need to use because some mod needs it) my salination plant in an eternal day mystcraft age does not produce any brine at 2k Heat and full water.

**Comment by Herekar** [comment]
I have been having a similar problem in forge 1370 in the regular dimension day cycle

**Comment by aidancbrady** [comment]
Issue with latest forge, fixed in development

**Comment by Tomatoh** [comment]
Any news on getting the developmental version?

**Comment by Keridos** [comment]
Official website...
