### ISSUE TITLE
Would you kindly add compatibility code for Mekanism to be run on both Forge 1291 and Forge 1355+?

### ISSUE THREAD

**Issue by Barhandar** [aidancbrady/Mekanism#2598]
Like Extra Utilities and Railcraft do. Would make it not an issue of "upgrade and drop rarely-updating good minor mods or not upgrade major ones".

**Comment by unpairedbracket** [comment]
I wouldn't have thought it was even possible to do so, had they not managed it. Even now, I have no idea how, and as both mods are closed source I have no way of working it out. Maybe @aidancbrady has some idea?

**Comment by Keridos** [comment]
Railcraft is opensource: https://github.com/CovertJaguar/Railcraft
You just might need to check the license

**Comment by unpairedbracket** [comment]
So it is. I must have missed that happening. We'll potentially look at getting that working at some point then, but I've not got any time at the moment.

**Comment by Barhandar** [comment]
Gendustry also allows for both versions of fluid handling and is licensed under MMPL, basically saying "do whatever": https://github.com/bdew/gendustry

**Comment by scootashy** [comment]
yeah hope it is done til all mods have updated past the fluid change so everyone can make use of the updated bug fixed version yet during that time

**Comment by aidancbrady** [comment]
Low priority, mods should update to the new forge fairly soon. In the meantime you can just use an older mekanism release.
