### ISSUE TITLE
[Feature Request] Submarines and/or boats

### ISSUE THREAD

**Issue by gabrieltm9** [aidancbrady/Mekanism#2599]
Hi! Want to start of by saying that i LOVE mekanism. Second, i think it would be an AWESOME idea to add submarines or boats to mekanism with storage systems and on board furnaces or even modular boats and submarines. What do you think?

Thanks for taking the time to read my idea,
Gabe

**Comment by aidancbrady** [comment]
Quite the feature request!  I have secretly always wanted to make some kind of submarine, actually.  I'm closing this for now as it's definitely not going to be implemented soon with all the other projects in the works, but I'll consider it later on down the road :)
