### ISSUE TITLE
Server crash report with newest version

### ISSUE THREAD

**Issue by yepidoodles** [aidancbrady/Mekanism#2600]
https://www.dropbox.com/home?preview=crash-2015-04-28_18.36.28-server.txt

I had to back date the version in order to get my server running again

**Comment by jimmon89** [comment]
your link to your crash report is broken
it tries to take me to my drropbox at "https://www.dropbox.com/home?preview=crash-2015-04-28_18.36.28-server.txt" which links to the person who opens the link's dropbox so it tries to open crash-2015-04-28_18.36.28-server.txt on my box which of course does not exist

**Comment by yepidoodles** [comment]
Sorry, 
https://www.dropbox.com/s/e9srb8srck105rf/crash-2015-04-28_18.36.28-server.txt?dl=0

**Comment by bochen415** [comment]
@yepidoodles  Build 8.1.2.229 is targeted for Forge versions 1355 and above (after the fluid registry changes) so no wonder it crashed with 1307

**Comment by yepidoodles** [comment]
Oh fantastic, see, I updated forge and it broke ender storage, had to back-date it and now I can't update Mekanism >.< Thanks for the help

**Comment by bochen415** [comment]
EnderStorage has a build compatible with latest Forge

**Comment by yepidoodles** [comment]
I didn't see one last time I looked, thanks

**Comment by scootashy** [comment]
I did tests it also works on forge 1370 and 1388 1389 to 1395 have been marked with a bug so you can use 1388 on it and wait for next forge release that aint marked as bugged
