### ISSUE TITLE
Brine requirements immense for 4x processing

### ISSUE THREAD

**Issue by Saereth** [aidancbrady/Mekanism#2601]
I'm not sure if this is a user error, I've used mek 4x processing for along time. Generally I'd run like 3 max heigh salination plants in a desert into a bedrockium drum as a buffer and tesseract to the processing plant. As of this latest version though i'm running 8 brine stations just to barely keep up with a single elite injecting factory. at night it goes into a deep deficit, looking like I'd need 12+ towers to support a single injecting factory. all machines in the chain are max upgraded, running 2 chemical infusers and have max gas upgrades in the injecting factory. Is this a user error or should we (by design) be massively scaling up our brine production vs pre mek-8 numbers?

I can provide any addition info and/or screenshots as requested if this is not intended.

**Comment by EvulOne** [comment]
Is it possible the factories are just inefficient compared to the normal separator+chemical infuser method?  I don't use factories in most of my builds, but I haven't ran into this issue...

**Comment by XFactHD** [comment]
They aren't inefficient, they just work at an enormous speed.
I am also having this problem, but at the moment I am just using 4 solar evaporation plants.

**Comment by hisorange** [comment]
I remember reading this issue, also tested it. Factories seems to use 10x more gas / process in mek8 even with gas upgrades added. If you run 1 injector without speed upgrade that can process 70 ore, with speed + gas upgrade 7 ore (from its internal tank only) maybe fixed in new versions?

**Comment by laz2727** [comment]
That's because Speed upgrade bumps gas usage back to non-upgraded.

2015-04-29 22:33 GMT+06:00 Varga Zsolt <notifications@github.com>:

**Comment by hisorange** [comment]
Yeah but in the end you will use 10 time more gas in mek8 with upgrades compared to mek7. I am not against it, but it's a bit weird cuz all the machines got speed upgrade in x4 / x5 process which eliminated the slowness of x5 but now we need 20 injector at non upgraded state to match mek7 speed.

**Comment by Saereth** [comment]
so by those values I am gonna need closer to 20 max height brine stations to run a single injecting factory full time? eek, better start looking for copper lol

**Comment by hisorange** [comment]
Copper Is The New Black Season 2 >D

**Comment by hisorange** [comment]
You just have to degrade the injectors and split that part into multiple machines.

**Comment by Saereth** [comment]
is the problem with all factories? should I just be using 7 standard injectors then?

**Comment by hisorange** [comment]
Actually 10 speed upgrade gives you 10 time faster process, so replacing 1 maxed injector with 10 non-speed upgraded one will act as 1 full speed injector at mek7, better than building another 20.000 tile entity.

**Comment by Keridos** [comment]
For me this is insane also. I have 4 max height brine stations in an eternal day hell biome (2.0x mult) and 2 in 0.9x and about 30 oxidizers oxidizing salt and I still do not even produce enough brine to power an oreprocessing with 4 speed upgrades in the injector (2 crystallizers/washers/diss chambers).
Gas Upgrades in all machines that accept them.

**Comment by hisorange** [comment]
Yep it's weird a bit factories are a way to reduce your machine requirements in numbers, always better to have 1 factory smelter than 7 but I can understand that the authors wanted to make 5x a bit more tough. But what I see that peeps rise a lot 18x multiblocks all around to keep up which is not making the 5x harder but more laggy to update 6.000 tileentity for one digital miner :/

So maybe have to adjust the brine producing in the config to match the new requirements.

**Comment by aidancbrady** [comment]
Just quadrupled the brine production rate - you're right, it was a bit immense.

**Comment by Zaflis** [comment]
Just curious, does 8x gas upgrades increase the efficiency with brine in machines? It is sort of liquid, but it is used inside "gas using machines" that the upgrades tooltip says.

**Comment by XFactHD** [comment]
You can't insert gas upgrades into electrolytic separators, which means that you can't increase the efficiency of brine directly.

**Comment by Tyrindor** [comment]
You'll need 12+ max sized structures to support a single digital miner at current rates (~8 if you sleep immediately and don't let them cool down). Therefore, brine production should be increased by 8-12x or make gas upgrades better, so it takes less per ore. Another option would be giving them internal power buffer that keeps them running throughout most of the night.

Ideally, I don't feel we should ever need more than 2 max sized plants to keep up with a digital miner.

**Comment by hisorange** [comment]
Don't forget brine now more important than in mek7 I ran 4 for brine and 1 for lithium and it's providing 400k RF / tick so increasing it's production also increase the RF possibility.

Also the brine production is more than enough for 4x since that uses 4 time less than 5x.
