### ISSUE TITLE
Crash: Ender IO gas conduit attached to Solar Neutron Activator

### ISSUE THREAD

**Issue by Tergiver** [aidancbrady/Mekanism#2605]
It was an accident, I didn't mean to place it, but it crashed instantly and now my world crashes on load.

At the time of the original crash I was using:
Forge 1291
Mekanism 8.1.1.225
EnderIO 2.2.8.367

Here is that crash dump:
http://pastebin.com/epyx0D83

Before submitting this report I thought I would upgrade so now:
Forge 1395-1710ls
Mekanism 8.1.2.229
EnderIO 2.2.8.367

Here is that crash dump:
http://pastebin.com/hLunevDf

The Activator was attached to a liquid tritium source (large dynamic tank).

p.s. Any way I can get my world to load without removing either Mekanism or EnderIO from it first? Removing either would suck, hard. And of course I don't have a recent backup :(

**Comment by bochen415** [comment]
Remove the offending conduit with mcedit

**Comment by hisorange** [comment]
or update to EiO 2.3

**Comment by Tergiver** [comment]
I don't see any downloads for EiO 2.3. What I have is the latest.

**Comment by Tergiver** [comment]
Sorry, fumbled the Close and comment button.

**Comment by bochen415** [comment]
Not even clese
http://ci.tterrag.com/job/EnderIO/

**Comment by Tergiver** [comment]
Thank you!
Upgraded to EnderIO 2.3.0.376 and that fixed it.
