### ISSUE TITLE
Flux Ducts cosmetic issue

### ISSUE THREAD

**Issue by tgstyle** [aidancbrady/Mekanism#2607]
TD Flux Ducts show disconnected from Induction Ports and Lasers, usually happens when you reconnect to a server or walk away from an area. They still function properly. It always seems to show connected to a reactor port, just not the others.
![2015-04-29_13 36 27](https://cloud.githubusercontent.com/assets/5832709/7399763/3f1b9e3a-ee75-11e4-8357-b9c08c506d2a.png)

**Comment by XFactHD** [comment]
I have seen the same problem with the lasers.

**Comment by aidancbrady** [comment]
Not sure why that would be, tile updates are sent out whenever an electric block is reconfigured.  As this is not exactly a Mekanism issue I'm going to close, but if anyone has anymore insight I'd be happy to look into it further.

**Comment by tgstyle** [comment]
Maybe @KingLemming could provide some insight?
