### ISSUE TITLE
agriculture and forestry suggestion

### ISSUE THREAD

**Issue by karakufire** [aidancbrady/Mekanism#2615]
Now no uses for sodium, well it should use to produce fertilizer(nitratin, or sodium nitrate).
However, since no meaning as just it, I suggest that relevants.
There are new gus: nitric acid and ammonia, farming machines, another way to make gunpowder and farming/lumber robits.
It's not interesting no way to use sodium.

**Comment by aidancbrady** [comment]
Sodium does need a use, that's for sure. Thanks for the suggestions
