### ISSUE TITLE
Pressurized Tube bug

### ISSUE THREAD

**Issue by Master-Jynx** [aidancbrady/Mekanism#2618]
The upper tier pressurized tubes don't work ......
When connected to a electrolytic separator to process brine,l
It will do so while no tubes are connected, but once a tube is placed , the reservoir
on that side will lose it's contents, instantly, and it will stop proccessing gas on that 
side, while the other side will continue working until a tube is connected.
only the basic tube appears to work

**Comment by aidancbrady** [comment]
Just did some testing.  The upper tiers work exactly as they are intended to, what you are running into are simply the increased buffers.  The separator is processing, the tube network is just filling up with the gas being produced.

**Comment by RobJonesWeb** [comment]
I am experiencing this too when running deuterium through them they eventually stop pulling and need to be broken and replaced
