### ISSUE TITLE
[Suggestion] Dense Ores Vein Mode

### ISSUE THREAD

**Issue by gabrieltm9** [aidancbrady/Mekanism#2620]
Hi! First of all, i LOVE your mod. I was mineing the other day with my Atomic Dissasembler in Vein mode when i came accross some dense ores from the dense ores mod. I was not able to vein mine them even though they were next to there own type. Ex. Iron next to Dense Iron = No vein mine for the dense ore. I was wondering if maybe this could be implemented.

Thx and keep up the awesome work!
Gabe

**Comment by aidancbrady** [comment]
The "vein mode" setting of the Atomic Disassembler works by finding neighboring blocks of the same block type and metadata value, with a set of wildcard exceptions for special cases.  What you mentioned is possible but would require a lot of work for not enough benefit.  Sorry :(
