### ISSUE TITLE
BoxBlacklist doesn't accept *

### ISSUE THREAD

**Issue by Xen1290** [aidancbrady/Mekanism#2622]
If I write for example:
TwilightForest:tile.TFTowerDevice:*
in Box Blacklist this appear in console:
[22:57:59] [Client thread/ERROR] [Mekanism]: BoxBlacklist.txt: Couldn't parse blacklist data on line 4
@aidancbrady could you add the ability to use * ?

**Comment by aidancbrady** [comment]
This would be very hard to accomplish (and hard to implement efficiently, too).  I'm gonna have to say no :(

**Comment by Xen1290** [comment]
Oh, ok, thank you for the answer!
