### ISSUE TITLE
Universal Cables Stop Working; Need Replaced

### ISSUE THREAD

**Issue by justinbellear** [aidancbrady/Mekanism#2623]
Currently using version 8.1.2 

It's not hooked up to anything that isn't part of Mekanism, it is not honeycombed. Its coming out of a Induction Matrix port, was configured properly and ran fine for most of today. This is actually the first time I've had this bug in maybe a month(since before the latest update or so)...

Matrix has 4.6 GJ and is being powered just fine.

Would you like images to see the bug? I've noticed whenever this happens, when I hover over the Universal cable it shows RF power .. right now it says 0/13952000 RF.... However whenever my cables work properly they don't show this. I am using a mod to display what items i am looking at.

**Comment by justinbellear** [comment]
Fixed, accidentally had my port set to output. Sorry.

**Comment by spannerman79** [comment]
Then please close this if it was an issue on your end @justinbellear

**Comment by halvors** [comment]
@justinbellear Can you please close this?
