### ISSUE TITLE
Invalid recipes with B:ControlCircuitOreDict=false

### ISSUE THREAD

**Issue by Xee1** [aidancbrady/Mekanism#2625]
Hi @aidancbrady , with:
Mekanism 8.1.2
If I set B:ControlCircuitOreDict=false
The recipes of Elite factory is very strange, for Basic and Advanced everything is good
![a](https://cloud.githubusercontent.com/assets/8685029/7473373/05890980-f33b-11e4-943a-9fe4deff06d3.png)
**Only for Elite Factory,Induction Port, Elite Factory Installer,Elite Induction Provider, Ultimate Induction Provider , Reactor Port,Reactor Controller,Combiner and Solar Neutron Activator this happen.**
I've also IC2 Installed.
I think that: instead of Fire, Elite Control Circuit is the best thing to add.

**Comment by aidancbrady** [comment]
Fixed, thank you

**Comment by Xee1** [comment]
Thanks!
