### ISSUE TITLE
Custom names for blocks

### ISSUE THREAD

**Issue by Adaptivity** [aidancbrady/Mekanism#2626]
There many mods which allows translators to modify complex names (In most cases: complex name = X (where X is number of adjectives) adjectives plus one noun).
Example: Tinkers Construct .lang file - [adjectives](https://github.com/SlimeKnights/TinkersConstruct/blob/master/resources/assets/tinker/lang/en_US.lang#L866-L902) plus [nouns](https://github.com/SlimeKnights/TinkersConstruct/blob/master/resources/assets/tinker/lang/en_US.lang#L909-L934). This system is good for English language. You don't need to write *Alumite* plus *All tool names* and etc. But for other languages this system just not enough.
In Russian, I can use Alumite adjective for Pickaxe but I can't use same Alumite string for hatchet or for hammer. I need to modify it. It still will the same adjective but with different ending. 
Just look at this: "Алюмитовая" used for pickaxe and "Алюмитовый" can be used for both hatchet and for hammer but not for pickaxe. You don't need to read this. Just look at the ends, they are different.
So, basically you should allow us to use full item/block name instead of complex. I call them custom names because they doesn't replace complex names. So, en_US.lang won't be changed. They will only work if they are exist in .lang file, if they doesn't exist complex names will be used instead.
Examples how to do that:
1) How it was done in AOBD: [first commit](https://github.com/ganymedes01/Another-One-Bites-the-Dust/commit/6f7fae861a5c7db110915cb589481bb95545f323), [second](https://github.com/ganymedes01/Another-One-Bites-the-Dust/commit/3a9289f5d0809c783a9ea4f1b81498110f8de43f)
2) How it was done in Tcon: [first commit](https://github.com/SlimeKnights/TinkersConstruct/commit/7ae5a92a8f30fba3c11dc391ff03b6c38b226444), [second](https://github.com/SlimeKnights/TinkersConstruct/commit/d80bd63e7aa98cf129df921e0edf8c5ec6fc791b)
The things that we should be able to modify:
1) Factory names
2) All Plastic variations
3) Glow Panel names
4) Ballon names
I call @Vexatos here if you still doesn't understand what I mean. He know how to explain better.
Tied with #2445, #2406

**Comment by Vexatos** [comment]
Mhm, I added optional hardcoded names to Forestry once. You could use `StatCollector.canTranslate(key)` and, if that returns `false`, default to the normal name. Your best bet is to look at how other mods do this.

**Comment by aidancbrady** [comment]
Sounds easy enough. Thanks for the explanation (and the suggestion @Vexatos). I'll see what I can do later this week.

**Comment by Adaptivity** [comment]
Also, [and in tooltips](http://i.imgur.com/Okfw8h8.jpg) hardcoded.

**Comment by aidancbrady** [comment]
Fixed the hardcoded "and."  Going to go about what you mentioned now...

**Comment by aidancbrady** [comment]
Hopefully this is what you were looking for @Adaptivity.
