### ISSUE TITLE
Rf displays in krf

### ISSUE THREAD

**Issue by Reignofmagic** [aidancbrady/Mekanism#2627]
I might have done something wrong in the config but ive seen this krf on videos about Mekanism 8 so maybe not. 

In any case when you go into the config and change its display from J to rf in game it displays as krf.

From what i have gotten via testing mainly with ender io as a means of showing the input/output  it seems that krf is .5 rf

While this is not a huge problem it is a little annoying having to divide all displayed numbers by 2. How do you display in rf like in ender io or TE 4, or is this not possible at this time?

**Comment by aidancbrady** [comment]
Krf is kilo-rf, which is 1000 rf. We use SI naming standards for all units.

**Comment by Banderi** [comment]
Just for the record in case it helps anyone;
I'm not sure if it's the same issue OP was describing - but Mekanism machines, at least in 1.12, store the block data in Joules even if they display RF correctly, which means some other mods that display RF data (like RFtools) will show a number 2.5 greater than it actually is, even though they print "RF/t" and such.
