### ISSUE TITLE
Cardboard Box change Nodes from Thaumcraft

### ISSUE THREAD

**Issue by Tymerias** [aidancbrady/Mekanism#2628]
When you put a Node in the Box and unwrap the box the Node have different Aspects and can even change his status to Pale, Normal and so on. I cant find a system behind this, the Aspects change randome every zip and unwrap

**Comment by aidancbrady** [comment]
This would be a good example of a BoxBlacklist addition.

**Comment by Tymerias** [comment]
Sure but your Boxes are such a convenience way to transport the nodes. I dont know any other thing that can do that so easy :)
