### ISSUE TITLE
Feature request: Portable / aimable laser

### ISSUE THREAD

**Issue by Sslazz** [aidancbrady/Mekanism#2629]
I love the new lasers, but they really are only useful for drilling near a base. Digital miner is still the best mekanism mining option. Would it be possible to get a portable version as a mobile mining / fighting solution?

Alternately, could you make an aiming block for the laser, so you can use them as base defenses?

**Comment by cleverca22** [comment]
ive seen another mod that had mob defense lasers, would be interesting to have a turret like the laser amplifier that can store charge, and then release it at any nearby mobs

maybe let the laser pass thru it when its full, so a single beam can charge a whole row of them

**Comment by aidancbrady** [comment]
Something like the IC2 mining laser? That's definitely possible. Obviously it would need a fancy model too :)

**Comment by Sslazz** [comment]
Something very much like the IC2 mining laser. In keeping with the upgradable nature of mekanism, I'd say:

Basic LGMP (laser gun, man portable) - 1 laser, 1 laser amplifier, 1 basic cube, 1 steel frame, 3 lithium, 2 redstone
Upgrades use previous laser, higher level alloys.

Basic LGMP acts like 1 laser, holds as much energy as basic cube. Upgrades hold as much energy as their cubes, act like 2, 4, 8 lasers.

Mekanism mode switches 
-Continuous mode 
-Pulse every .5 seconds
-Pulse every 1 second
-Pulse every 5 seconds
-Charge mode (hold down right mouse button to charge, release to fire)
