### ISSUE TITLE
Unloaded chunk entity property losses

### ISSUE THREAD

**Issue by liamhogan** [aidancbrady/Mekanism#2632]
I seem to be experiencing a bug where liquids/gasses and laser energy are drained when a chunk containing them is unloaded (i.e. when out of range).

I have a large setup of tanks, pipes and lasers (directed into a laser amplifier) that I have noticed this problem with. I have tested by making sure that all gas tanks are full and not draining anywhere, and that the laser amplifiers are configured to be storing the energy - then I leave the area at a great enough distance that that chunk is unloaded. When I return to the chunk, the laser amplifiers have lost all their stored energy and are only starting to fill up again, and the tanks are less full or empty - interestingly, the longer I leave the chunk unloaded before returning, the less full the tanks are. I suspect this to be a glitch with the pipes that the tanks are connected to - perhaps the buffer in the pipes is being emptied/erased but the tanks remain in memory and so continue to empty themselves into this 'infinite empty buffer'? I really have no idea why this is happening though and don't know enough about how Mekanism's code functions in unloaded chunks to be able to figure it out. 

Has anyone else experienced this glitch?

**Comment by liamhogan** [comment]
I can confirm that this only happens on tanks that are connected to pressurised tubes. If there are tanks not connected to anything, they loose nothing. So it does seem to be an issue related to the pipes loosing their buffer contents when unloaded from a chunk. Same with the laser amplifiers.

**Comment by aidancbrady** [comment]
Should be fixed for the next minor release.
