### ISSUE TITLE
Server crash due to gas pipes

### ISSUE THREAD

**Issue by diamondpumpkin** [aidancbrady/Mekanism#2634]
The server seems to crash when ever I get near gas pipes. I have the latest of Mekanism (Mekanism-1.7.10-8.1.1.225) and I'm running it on a custom mod pack. Please fix this!

Server crash report: http://pastebin.com/RPj67byP

**Comment by enterprise12nx** [comment]
are you using enderio gas pipes?
if so use build 377 http://ci.tterrag.com/job/EnderIO/

also maybe update to the latest mekanism and forge
