### ISSUE TITLE
[API Issue] Cannot use config tabs in non-mekanism (addon) machines

### ISSUE THREAD

**Issue by Radviger** [aidancbrady/Mekanism#2636]
Any time when i click that button:
http://prntscr.com/7397dk
I get this:
http://pastebin.com/AUY2B7Ju
And my game/server crashes.
P.S. It's bad to use mod-oriended only methods when you provide a modding API.

**Comment by aidancbrady** [comment]
As of right now this is expected, you're expected to provide your own GUI implementation if you use the Mekanism configuration on an add-on's machines.  I'll consider changing this in the future.
