### ISSUE TITLE
[Question] Mekanism Tools/Generators

### ISSUE THREAD

**Issue by enterprise12nx** [aidancbrady/Mekanism#2637]
Wondering what the two addons for mekanism contain
The Tools/Generators addons: http://cdn.minecraftmodarchive.org/Mekanism/Addons/

what do they add? obviously tools and gens, but specifically?

**Comment by aidancbrady** [comment]
MekanismTools includes basic armor/tool sets.
MekanismGenerators includes all means of energy generation, including the new Fusion Reactor.
