### ISSUE TITLE
Reactor shuts down when right clicking controller

### ISSUE THREAD

**Issue by scifibob** [aidancbrady/Mekanism#2639]
Almost every time I log in and right click the reactor controller, it shuts down.
I tried 10 times in a row, and it happened in 7 of them.

There was no errors in the server/client log files when this happened.
It seemed to reset in a way, because the temperature went down to minimum immediately.
When I cut the fuel, the temperature slowly goes down, but here it was reset to default.

Due to lag, I deleted all my reactor stuff, so I'm not able to test this further right now, but I might try later when things are more stable.

It should also be mentioned in the documentation that the reactor needs to be chunkloaded to survive a player logoff, unless that is a bug.

**Comment by aidancbrady** [comment]
I can't reproduce either of these issues.  Assuming you either were using an out-of-date version or this is an interaction corner case - if this is not the case, let me know and I'll take another look.

**Comment by scifibob** [comment]
I can't try it again, because I completely don't trust your reactor in any way. The lasers created too much lag, so I'm unable to try to reproduce at this time.
All I can say is that I was using the last available versions on the download sites, and it didn't help.
Probably a weird bug surfacing in some special situation. Being a programmer myself, I can certainly see the difficulty in finding such issues.
As I'm using BigReactors right now, and it's not generating any lag, I will probably not try the reactor in a while.
