### ISSUE TITLE
compatibility

### ISSUE THREAD

**Issue by Marcus89uk** [aidancbrady/Mekanism#2644]
Hi there!

I tried your mod out on a cauldron server 1.7.10. but it did not work. is it compatible and if so how do i get it so its working?

**Comment by HanatakeYurii** [comment]
What version of Cauldron are you trying to use? (with the last Mekanism version I guess (8.1.2.229)

**Comment by Marcus89uk** [comment]
hmm I'm I forgot the version I'm using. Could you post me the links to redownload the mods please :)

**Comment by HanatakeYurii** [comment]
For Mekanism: http://aidancbrady.com/mekanism/download/
You probably used a Cauldron version that use a way too old version of Forge, since the last Mekanism version is built against one of the last version (after fluid registry changes made in 1355)
