### ISSUE TITLE
Weird Crash with latest Mekanism

### ISSUE THREAD

**Issue by Carbon-Ghost** [aidancbrady/Mekanism#2645]
I don't know if it's really Mekanism related, but I get this : http://paste.ee/p/G7E8Z with latest Mekanism, it says it caught an exception from Mekanism, but I don't understand exactly what...

PS : Unrelated, I just noticed, but there isn't any way to balance fusion reaction energy output...

Can you add the energy required for firing up a reactor + the max energy output please ? For balance purposes, as this beast can potentially power all machines in my pack ( even MFR using x10 more power than usual and huge x2 ME system, and still produce WAAAAAAAAAAAY to much ). Please ?

**Comment by Belgabor** [comment]
The latest version of Mekanism is no longer compatible with Forge pre-fluid update. You need Forge 10.13.3.X

**Comment by Carbon-Ghost** [comment]
But there are no recommended forge versions past .1291 ... ( So, what do I do now ? ).

**Comment by HanatakeYurii** [comment]
Wait until a new recommended version and use old mod version in the meantime (this can take a while)
or use a newer forge version, I've seen many users playing with 1395
