### ISSUE TITLE
Feature request: Something to use fusion power for

### ISSUE THREAD

**Issue by Sslazz** [aidancbrady/Mekanism#2646]
Mekanism 8 added fusion reactors, which are very nice indeed. However, there's no real way to use all that power other than to store it in an induction setup. Mekanism needs something to use all that power for - be it an IC2 style item replicator (uu matter and whatnot), a super-digital miner, or somesuch. 

Any thoughts?

**Comment by aidancbrady** [comment]
This is planned :)
