### ISSUE TITLE
class not found exception: TileEntity Salination Controller

### ISSUE THREAD

**Issue by sww1235** [aidancbrady/Mekanism#2647]
[Here](https://gist.github.com/sww1235/3e53e22784951be574ab#file-crash-2015-05-10_17-33-29-client-txt) is my crash log. 

Occurs using version 1.7.10-8.1.2.229. I have the appropriate version of generators and tools installed as well. 

Looking at the crash log it appears that the waila plugin is broken.

**Comment by aidancbrady** [comment]
Try updating enderio to the latest dev build. Not on my end regardless

**Comment by sww1235** [comment]
it is the latest build of ender io. They recommended to update mechanism
