### ISSUE TITLE
Small question.

### ISSUE THREAD

**Issue by zHawky** [aidancbrady/Mekanism#2651]
Well i cant scan Mekanism blocks with thaumometer, this is bug or you just dont play with Thaumcraft?

**Comment by HanatakeYurii** [comment]
I think there is simply not aspects set to Mekanism blocks.
I've seen that a week ago. I don't know what side (Mekanism or Thaumcraft) should add them.
Also I know it should be possible with MineTweaker 3 (I found a file that added aspects to Botania), but there would be search to get how it works.

Maybe it would be possible to add support using Thaumcraft API?

**Comment by aidancbrady** [comment]
This is the kind of compatibility I would like to see in a PR- adding block and item-specific aspects is very low priority compared to the other feature requests and issues stacked up right now.

**Comment by zHawky** [comment]
Well, thanks for feedback mate, keep working on mod :+1:
