### ISSUE TITLE
[Suggestion] Heavy Water Bucket

### ISSUE THREAD

**Issue by tgstyle** [aidancbrady/Mekanism#2652]
There are some mods that need a bucket to set fluid filters, could you add a bucket of heavy water?

**Comment by Carbon-Ghost** [comment]
And possibly the fluid that goes in world with it if it's not already done :D

**Comment by aidancbrady** [comment]
Added the bucket :)

I'll consider adding actual fluids later on.

**Comment by Carbon-Ghost** [comment]
Nice :D
