### ISSUE TITLE
[REQUEST] Streamline Generators GUI data representation

### ISSUE THREAD

**Issue by Malkierian** [aidancbrady/Mekanism#2653]
There is way too much redundancy going on in the GUIs for the generators.  For example, the Solar Generator has two places you can see the max output, two places you can see whether it is receiving sunlight, and two places you can see the current buffer charge, or the current power output, depending on if the buffer has charge or not.  I would suggest having only the current power output listed in the main text portion of the GUIs (and not alternate with the buffer charge), then leave the max power output to the Power Information Tab, the buffer charge to the hover context over the buffer charge bar, and the sunlight status to the sun icon, and then doing similar streamlining in the other GUIs.  All the switching and duplication of information is very confusing, especially to someone just starting out.

**Comment by Protheus** [comment]
+20

**Comment by aidancbrady** [comment]
I meant to close this; I simplified the amount of energy shown in generators GUIs for Mekanism v9.  Hopefully that helps :)
