### ISSUE TITLE
Basic universal cable not conducting after being logged out

### ISSUE THREAD

**Issue by hehe3301** [aidancbrady/Mekanism#2654]
Loged out of my server last night and when I logged back in all of my stuff was shut down because basic universal cables were not conducting. replacing the cable fixes it only for the replace cable (power will not flow into cable placed last night). In image the cable on the left was placed now and the right placed last night
![2015-05-12_08 51 54](https://cloud.githubusercontent.com/assets/1365040/7587501/c194448e-f884-11e4-8b18-97d4b7882775.png)

**Comment by hehe3301** [comment]
Forge Version: 10.13.3.1403
Mekanism version: 8.1.2

**Comment by khumps** [comment]
Ive been having this problem too but with 8.1.1 forge 10.13.2.1352

**Comment by RAWRwins254** [comment]
Something tells me that chunks are unloading and THAT CAN result in what you're seeing from both issues you opened. However, I'm not one of the devs so I dunno if it's chunkloading for sure or not.

**Comment by hehe3301** [comment]
Keeping the area loaded (chunk loader or player) has stopped all occurrence of this bug. This indicates that the bug may be due to how the conductive objects are loaded when a chunk is loaded.

**Comment by khumps** [comment]
it also has been happening with the pressurized tubes and mechanical pipes

**Comment by RAWRwins254** [comment]
@khumps make sure the area is chunk loaded. If it is, please make a separate issue on this github.

**Comment by RAWRwins254** [comment]
@hehe3301 can I have you close this issue as it seems to be resolved?
