### ISSUE TITLE
Basic Mechanical Pipe not pulling from Solar Evaporation Valve

### ISSUE THREAD

**Issue by hehe3301** [aidancbrady/Mekanism#2655]
Logged out of my server last night and when I logged back in my mechanical pipes had stopped pulling brine from the solar evaporation valve. last night it functioned fine.
![2015-05-12_08 58 20](https://cloud.githubusercontent.com/assets/1365040/7587607/8b0a50ce-f885-11e4-996c-777042ab8284.png)

EDIT: added picture

**Comment by hehe3301** [comment]
Replacing the mechanical pipe at the valve resulted in similar issue to issue #2654 
![2015-05-12_09 03 31](https://cloud.githubusercontent.com/assets/1365040/7587632/c91bef6c-f885-11e4-920d-34f59281e569.png)

**Comment by XFactHD** [comment]
I also had this issue yesterday on singleplayer after I updated from forge 1291 to forge 1395.

**Comment by hehe3301** [comment]
Forge Version: 10.13.3.1403
Mekanism version: 8.1.2

**Comment by hehe3301** [comment]
@XFactHD there was no mod update I just stopped playing for the evening and came back.

**Comment by drunksob** [comment]
having the same issue

**Comment by hehe3301** [comment]
Keeping the area loaded (chunk loader or player) has stopped all occurrence of this bug. This indicates that the bug may be due to how the conductive objects are loaded when a chunk is loaded.

**Comment by hehe3301** [comment]
@drunksob for now try chunkloading the area

**Comment by aidancbrady** [comment]
This should be fixed for the next minor release - the capacity was not being reset on world load.
