### ISSUE TITLE
Gas Tank causing world crash

### ISSUE THREAD

**Issue by nickcool9999** [aidancbrady/Mekanism#2657]
This issue is caused by the Gas Tank exporting improperly to the Gas Conduits, I think.

There are 2 Mekanism Elite Gas Cables behind the tank, filling it and 2 EIO conduits in front, attempting conversion to their cables.

Forge Version: 10.13.3.1401
EnderIO Version: 1.7.10-2.2.8.367
Mekanism (And Submods) version: 1.7.10-8.1.2.229

If you wish to read what I attempted interpretting, the crash log for the server is here:
http://pastebin.com/NbpbRDJV

If it helps, I am passing though oxygen.

**Comment by nickcool9999** [comment]
Nevermind, requesting takedown of this issue, this issue has been resolved as of beta build #377 of Ender IO and Ender IO has since seemed to have adapted new optional code for gases to prevent crashing.

**Comment by XFactHD** [comment]
You can close it yourself.

**Comment by nickcool9999** [comment]
I don't know how to do that.

**Comment by XFactHD** [comment]
On the left of the comment button is the close button.
