### ISSUE TITLE
Latest version (229) keeps corrupting worlds with Transporters

### ISSUE THREAD

**Issue by MasterTeixi** [aidancbrady/Mekanism#2659]
The changelog say:
"22. Fixed transporters"
"18. Maybe fix bad transporters"

I tested it and it keeps crashing and corrupting worlds

It happens when you unload the chunk and then reload it (for example, going to explore and coming back to the base) and only if the transporter was transporting items when the chunk was unloaded.

The only way to fix it is using MCEdit and deleting the transporter.

I wonder if you could add an option into the config to disable items individually, just like you can with machines, so if you keep not being able to fix it, at least we, the users, could disable those transporters to "unbug" our worlds without having to use MCEdit or directly disabling them for new worlds, so we don't accidentally craft it.

**Comment by aidancbrady** [comment]
The bug is fixed in development. Expect a release very soon
