### ISSUE TITLE
Textures still rotated 90 degrees in build 229.

### ISSUE THREAD

**Issue by ate0ate** [aidancbrady/Mekanism#2662]
This is basically still issue #2617. I know that this issue was marked as fixed a while ago, but it is definitely still occuring in build 229. Are bug fixes only available in dev builds now perhaps?

Its a rather visually horrendous bug at times and has the nasty habit of presenting as a texture bug with other mods. I initially thought that this was an issue with EnderIO's reservoir texture getting flipped in certain chunks before Tterrag pointed me to this issue. Thanks!

**Comment by aidancbrady** [comment]
Release this weekend with fix :)
