### ISSUE TITLE
Any possiblity to remove mekanism recipe from crafting table?

### ISSUE THREAD

**Issue by Radviger** [aidancbrady/Mekanism#2663]
Hi, dear Mekanism developers!
I've encountered a problem with recipe overriding for some mekanism items on my server.
In old MK version that well perfectly works with MekanismUtiles.removeRecipe(), but now it is'nt.
Maybe it's mechanics was changed? I will be very grateful for your help!

**Comment by aidancbrady** [comment]
The mechanics haven't changed. Maybe try using a recipe remover tool?
