### ISSUE TITLE
I keep getting this crash and I think it's caused by mekanism...

### ISSUE THREAD

**Issue by MonzterAssassin** [aidancbrady/Mekanism#2668]
http://pastebin.com/QtLSsVLR

Mekanism V8.1.2

**Comment by RAWRwins254** [comment]
Update forge. 8.1.2 uses a newer forge version than 1291. My server uses 1374 iirc.

**Comment by RAWRwins254** [comment]
1291 has forge handling fluids whereas forge made a change at 1348 if memory serves me to have the mods do fluid management.

**Comment by MonzterAssassin** [comment]
Oh okay thanks

**Comment by HanatakeYurii** [comment]
Just to get it right, it was changed in 1355
