### ISSUE TITLE
[1.7.10-8.1.2.229] Universal Cable Issues With IC2

### ISSUE THREAD

**Issue by Tyaeth** [aidancbrady/Mekanism#2669]
###### Mods Used:
Mod | Version
------------ | -------------
Industrialcraft Experimental | 2-2.2.720-experimental.jar
Mekanism | 1.7.10-8.1.2.229
MekanismGenerators | 1.7.10-8.1.2.229
MekanismTools |1.7.10-8.1.2.229
VoxelCam | 1.3.1
Liteloader | 1.7.10

###### Issue 1:
When transferring power to an IC2 machine using Mekanism universal cable, the cable stops drawing power from the power source and will continue to power the IC2 machine. This continues even if the power source is removed and only the cable remains. This seems to have been referenced in #2606 but the OP closed the issue. 

Basic setup:
http://i.imgur.com/47jxRWK.png

I removed the power source:
http://i.imgur.com/xF0qKkS.png

It continues to fill even though it was only connected to the power source for an instant. 
http://i.imgur.com/xF0qKkS.png

###### Issue 2:
~~Mekanism universal cable doesn't seem to be pulling any energy from IC2 machines.~~ Intended behavior?
http://i.imgur.com/dQ5ZpGu.png

**Comment by Carbon-Ghost** [comment]
Issue 2 is intentionnal from what I understood, as you need to use a configurator now and set cables to extract mode... Although I still will consider this as an issue xD ( as it wasn't like that before ).

**Comment by aidancbrady** [comment]
Issue 1 fixed, was a problem with the new transmitter overhaul.

**Comment by malianx** [comment]
Issue #1 Stil exists, if you hook a universal cable to an IC2 power source, and tell it to extract, then remove the power source (batbox) it will still infinitely power the machines on the uni cable.
