### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by diamondpumpkin** [aidancbrady/Mekanism#2670]
When ever I start up the game it crashes
http://pastebin.com/FJdPeJVN

**Comment by HanatakeYurii** [comment]
Mekanism 8.1.2.229 is intended for Forge 1355+ (if not more recent).
So, no surprise here.

**Comment by diamondpumpkin** [comment]
I can't really update because if I do I can't I mean CAN'T update my server with MCPC+ which adds both mods and plugins. If I do try to update there's no way I can have both. And if I pick just mods the server lags to hell and back.

**Comment by grimallq** [comment]
@diamondpumpkin There are Cauldron builds with Forge 1355+.

**Comment by diamondpumpkin** [comment]
Yeah, but one problem. Cauldron doesn't support both mods and plugins anymore. I tried, like hell to make it work. It doesn't.
