### ISSUE TITLE
Electrolytic separator comsumming RF but produce nothing

### ISSUE THREAD

**Issue by lapin-b** [aidancbrady/Mekanism#2671]
Hello,
Today on a server with a friend, we tried to generate some hydrogen out of water with an eletrolytic separator and some RF. We tried to figure out why the machine wasn't producing any hydrogen at all and it seems that the machine was consumming some RF but producing nothing. It doesn't consumme it's energy buffer.

Hope I'm understandable ^^

**Comment by RAWRwins254** [comment]
Lapin: forge version and mekanism version?

**Comment by RAWRwins254** [comment]
If Mek is at 8.1.2.229 and forge is less than the minimum of .1355, that's why.

**Comment by lapin-b** [comment]
@RAWRwins254 I use Mekanism 8.1.1.228 and Forge 10.13.3.1388 on the DNSTechpack version 7.6.1.0.

**Comment by RAWRwins254** [comment]
I believe 228 didn't support the fluid changes, you'd need to get 229 iirc.
