### ISSUE TITLE
Rf/j/mj/eu displayed

### ISSUE THREAD

**Issue by Saizetsu** [aidancbrady/Mekanism#2674]
In my prior modpack mekanism dominated the displayed power, with its joules while with 1.7.10 the display is showing everything in rf. Is there anyway to change this to joules from mekanism? I dont like doing the conversions of rf to joules and would rather have the cosmetics of mekanism dominating everything else.

**Comment by laz2727** [comment]
There should be a button.

**Comment by unpairedbracket** [comment]
It won't change how other mods display energy, obviously, but there is indeed a button in the general configs

**Comment by Saizetsu** [comment]
Yes but i rely almost entirely on mekanism. The 1:10 j to rf gets me though. The general config with the nei options or with the mods button?

**Comment by aidancbrady** [comment]
With the mods button.
