### ISSUE TITLE
Crash with mek Mekanism-1.7.10-8.1.2.229

### ISSUE THREAD

**Issue by crunkazcanbe** [aidancbrady/Mekanism#2675]
Running latest DEV  build of MEK with latest build of AOBD on curse. Don't know which mod is causing the crash ,but as soon as I click on the creative tab in vanilla minecraft to search for a item I get a freeze for a minute then it crashes . Crash log here http://pastebin.com/tRk6FTXk and I posted this over on the AOBD GitHub as well here  https://github.com/ganymedes01/Another-One-Bites-the-Dust/issues/69

**Comment by ganymedes01** [comment]
It was AOBD's fault and it's been fixed for a couple of versions.
