### ISSUE TITLE
Osmium Compressor Rotates Chunk Block Textures

### ISSUE THREAD

**Issue by MrNoe93** [aidancbrady/Mekanism#2678]
Fastcraft 1.21 is installed. Bug persisted with Fastcraft removed. When placing down an osmium compressor in version 1.7.10-8.1.2.229 of Mekanism, it rotates the textures of all the blocks that are level and above it in that chunk by 180 degrees.

http://imgur.com/sYtfga0

You can visually see the blocks textures rotate as you place and break the block.  I used extra utilities colored bricks to demonstrate but it also happened with vanilla and other modded blocks, I tested stone bricks, snow, and Chisel 2 blocks.

Tested the bug in a minecraft instance containing nothing but Mekanism and forge 10.13.3.1408 and it was also present.

I am playing the karma modpack version 1.5.11 on the AT Launcher if that information is necessary.

**Comment by aidancbrady** [comment]
This is a bug that will be fixed in the next version.
