### ISSUE TITLE
Requesting block break events

### ISSUE THREAD

**Issue by JoeSchmo2840** [aidancbrady/Mekanism#2679]
Hello I am wondering what type of events are being fired when block changing items such as digital miners edit the world or blocks. I am working to make a land protection plugin for the Sponge server. It is currently a forge implementation so if your firing forge events I can listen for them. If they are not, would you be willing to fire them? Or tell me if there is any way to check to see if the block is protected before items in your mod can modify them.

**Comment by smbarbour** [comment]
The digital miner should implement Forge's BlockEventBreak event.  The implementation should go in here: https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/tile/TileEntityDigitalMiner.java#L359-L389.  An example of such an implementation can be found here: https://github.com/BuildCraft/BuildCraft/blob/6.5.x/common/buildcraft/core/lib/utils/BlockMiner.java#L89-L115.

**Comment by JoeSchmo2840** [comment]
Not just the digital miner, anything that modifies or replaces blocks.

**Comment by aidancbrady** [comment]
Done, thanks!

**Comment by JoeSchmo2840** [comment]
No thank you Aidan, this is a great step towards peace of mind on our servers. I will try to get a donation to you soon :)
