### ISSUE TITLE
Chemical Injection Chamber won't accept iron crystals

### ISSUE THREAD

**Issue by FnordMan** [aidancbrady/Mekanism#2681]
Things I tried:
Direct ejection from the Chemical Crystalizer (that works fine, it ejects into a chest fine)
Ender IO item conduits
Vanilla hoppers

None of the above worked and yes I did have the sides configured properly, checked with the configurator and on the machine itself. 

The machine does work, if I manually put crystals in there it'll process things, it just won't accept any shards via automated means. 

Mekanism version: 8.1.2.229
Forge version: 1401

**Comment by RAWRwins254** [comment]
Shards are produced by the chamber last I knew. they shouldn't be an input.

**Comment by RAWRwins254** [comment]
But I might be wrong.

**Comment by XFactHD** [comment]
@RAWRwins254 you are right, the chemical injection chamber doesn't accept shards, it needs crystals or raw ores.
@FnordMan Did the chemical injection chamber have hydrogen chloride in it when the crystallizer should have pushed the crystals into the injection chamber? The injection chamber won't accept any input from shift-click or automation if there is no hydrogen chloride in it.

**Comment by FnordMan** [comment]
Shards, crystals, whatever. Note how I explicitly said it processed normally if I loaded it manually. 
Far as not accepting input without HCl i'll have to check that here in a bit but if that's the case than that's seriously stupid and makes for highly frustrating troubleshooting. Would be nice if that were to change to match what basically everyone else is doing to accept them no matter what and then only process when it has it's stuff.

**Comment by FnordMan** [comment]
Yup.. this is backwards the way it handles things. The machine works once I stuck the HCl tank in there. 
Can we say utterly backwards and completely non-intuitive compared to every single other mod out there? I knew you could...

**Comment by aidancbrady** [comment]
@FnordMan, no need to be harsh.  I'll see what I can do.

**Comment by aidancbrady** [comment]
Fixed.
