### ISSUE TITLE
Bin/Item Duplication Bug

### ISSUE THREAD

**Issue by VT-14** [aidancbrady/Mekanism#2682]
Filling multiple bins in a crafting grid (tested with 2x2 inventory crafting grid) and shift clicking to fill one creates however many bins you have in the stack, with the number of items you were trying to put in 1 bin.

64 bins with 64 diamond ore blocks shift click crafted = 64 bins full of 64 diamond ore blocks (4096 diamond ore blocks)

Shift clicking to unpack these bins additionally duplicates the bins, but I'm not sure how that works.

Mekanism: 8.1.2.229
InventoryTweaks: 1.59-dev-152
(38 additional mods)

**Comment by Deathdroid65** [comment]
Thanks for discovering this, I've decided to temporarily ban them on my server

**Comment by cp3o613** [comment]
I don't see how this is an issue, bins can't be stacked except by spawning them in through NEI.

**Comment by Deathdroid65** [comment]
I have no trouble stacking them without being in creative mode

**Comment by aidancbrady** [comment]
Thanks, Bins can no longer stack.

**Comment by aidancbrady** [comment]
Actually found a better way of doing this.  Bins can still stack while empty but no longer can stack when they have items inside, and the crafting table interaction only works with individual Bins.

**Comment by cp3o613** [comment]
Must have mixed up an outdated version or something, my bad.
