### ISSUE TITLE
How to access language file ?

### ISSUE THREAD

**Issue by Carbon-Ghost** [aidancbrady/Mekanism#2683]
Where can I access the US language file ?

**Comment by HanatakeYurii** [comment]
In the file: src/main/resources/assets/mekanism/lang/en_US.lang

Why do you want access it? Is there a mistake somewhere?

**Comment by Carbon-Ghost** [comment]
Nah, for personnal usage, do I need to decompile it ? And what to use then ?

**Comment by Carbon-Ghost** [comment]
Wait nvm think I got it.

**Comment by Carbon-Ghost** [comment]
Lastly, do I need MDK or I can use normal mekanism ?

**Comment by HanatakeYurii** [comment]
What are you trying to do? (from this will depends what you should use)

**Comment by Carbon-Ghost** [comment]
I want to rename the universal cables, as I changed the recipes for them, and gave them a new "usage" in my modpack, so I also want to rename them ^.^

**Comment by Carbon-Ghost** [comment]
So how do I exactly do it ?

**Comment by HanatakeYurii** [comment]
Open the regular Mekanism .jar (you do NOT need MDK, it's intended for devs only) with an archive program (7zip, WinZip...). 
Open the language file located at src/main/resources/assets/mekanism/lang/en_US.lang in a text editor (Notepad++ is good, bu you can use Notepad that comes with Windows...) and then change what you want.

I'm not sure which of Mekanism.jar or MekanismGenerators.jar is the good one, just try.

**Comment by Carbon-Ghost** [comment]
Kk thx
