### ISSUE TITLE
Electric Chest Duplication Bug

### ISSUE THREAD

**Issue by Deathdroid65** [aidancbrady/Mekanism#2685]
There is a bug with the electric chest, where players can put electric chests in their tool bar (requires at least two) and dupe with them.

1. Put some items in the first chest
2. Close the chest, then right-click in the air to open it again
3. Slightly after the click registers, press a number on your keyboard to switch to the slot of the other chest.

The second chest will open, but have the items from the first chest. You can take the items out and keep them. When you open the first chest again, the original items will still be there.

I have prepared a temporary fix that works for versions 1.6.4 and 1.7.10
This fix is in the form of a plugin, but you should be able to figure it out and make a patch to the mod.
Anyone looking at this is free to use and redistribute it. I just ask that you give me credit if you choose to use it.

This code includes a fix for https://github.com/aidancbrady/Mekanism/issues/957 as well, for those who do not have it. You may have to adjust the checks, but it currently checks for players standing on MFR conveyor belts (I checked the 0.x y value for players, its 0 if they are on the ground, but you can print out the values and modify it if this doesn't work for your server) and riding in vehicles.

You will have to check the plugin configs and set the proper ID value if you choose to use it.

Source Code:
http://pastebin.com/qj9ng97s

Jar:
https://www.dropbox.com/s/ewkk6843r4ewqzj/EChestDupeFix.jar?dl=0

**Comment by aidancbrady** [comment]
This doesn't appear to be an issue in regular Minecraft, both SSP and SMP.  I'm going to assume that this is an issue on Bukkit's end.

**Comment by Eufranio** [comment]
Please fix =/

**Comment by Aurilisdev** [comment]
Did this ever get fixed in some way?

**Comment by thiakil** [comment]
If you can reproduce it in 1.12, please open a new ticket linking to this one
