### ISSUE TITLE
Buildcraft power issue

### ISSUE THREAD

**Issue by flyboy1212** [aidancbrady/Mekanism#2686]
Universal cables will not connect and transmit\receive power from buildcraft generators and machines in buildcraft v6 or v7. As well buildcraft kinesis pipes will not connect to any mekanism machines or generators in any 8.1 version.

**Comment by Carbon-Ghost** [comment]
That's weird... It worked just fine in mek 7, and because BC is know RF powered, it should work normally...

**Comment by grimallq** [comment]
@flyboy1212 CofHCore needs to be installed for Mekanism to handle RF.
