### ISSUE TITLE
Server Crash in Mekanism 230 Build Logistical Pipes

### ISSUE THREAD

**Issue by Reignofmagic** [aidancbrady/Mekanism#2688]
So, I'm having an issue with logistical pipes, Similar to #2649 

The difference is I had this crash while in the 229 build. I saw the #2649 and asumed that thethe 230 build (what I hoped was the "fixed" version) would fix the problem. It did not the problem still persists. while using the 230 build. Please see Crash-log in the pastbin link: http://pastebin.com/95P71MKH

Thanks in advance for the help, and if I am using the wrong version a direct link to the download section with the fixed version, if available, would be greatly appreciated.

**Comment by aidancbrady** [comment]
Yes, 230 was a very minor update. This is still fixed in development.
