### ISSUE TITLE
Invalid tier identifier spam

### ISSUE THREAD

**Issue by Deathdroid65** [aidancbrady/Mekanism#2689]
I have the latest recommended version and I'm seeing this message spammed repeatedly:
[04:07:39 ERROR]: Invalid tier identifier when retrieving with name.

I've managed to get around this for now, using http://dev.bukkit.org/bukkit-plugins/pl3xconsolefilter/
I just setup the config like this (for anyone who happens to have the same issue):

filters:
  ERROR:
    contains:
    - 'Invalid tier identifier when retrieving with name.'

**Comment by aidancbrady** [comment]
Fixed.

**Comment by Deathdroid65** [comment]
When was this fixed?

**Comment by HanatakeYurii** [comment]
At least yesterday when 8.1.3.231 was out
