### ISSUE TITLE
Textures still rotated 90 degrees in build 230.

### ISSUE THREAD

**Issue by ate0ate** [aidancbrady/Mekanism#2691]
Just reopening this as textures remain rotated despite updating to build 230.

**Comment by aidancbrady** [comment]
Hoping to push out a fixed build tonight if I can fix a couple other major issues.

**Comment by ate0ate** [comment]
Oh okay, I apologize. I assumed build 230 was supposed to have fixed the issue. No worries. Thanks Aidan.
