### ISSUE TITLE
Chemical Dissolution Chamber Running Without Sulfuric Acid

### ISSUE THREAD

**Issue by Xandermud** [aidancbrady/Mekanism#2692]
The Chemical Dissolution Chamber is processing ores slowly without providing any sulfuric acid to it. Adding several gas upgrades seems to make it run faster while speed upgrades make it run slower and more sporadically. There is also a visual bug in the GUI that happens when 8 speed upgrades are installed that looks like an out-of-place meter. Tested with Mekanism 8.1.2.229 along with Mekanism Generators of the same version. No other mods. I can post a video of this in action if needed.

**Comment by Xandermud** [comment]
I should note that the machine runs normally when it has sulfuric acid and only misbehaves when the acid runs out.

**Comment by aidancbrady** [comment]
@unpairedbracket, it seems like your statistical gas usage mechanics sometimes return 0 for the amount of required gas.  I've fixed this on the Chemical Dissolution Chamber's end by making sure the required amount is at least 1, but there may be more areas with similar issues.

**Comment by aidancbrady** [comment]
Fixed regardless :)
