### ISSUE TITLE
[Suggestion] Sidedness and a way to "flush the tanks" in Salination plant

### ISSUE THREAD

**Issue by xenoflot** [aidancbrady/Mekanism#2695]
I think some useful adjustments to the salination plant would be to have two different values, one for input and one for output, or a configurable valve such as Big Reactors has.

It would also be nice to have a "flush tank" button for those times when you want to repurpose the plant or correct an error. Breaking the controller breaks the fourth wall in addition to resetting the temperature.

As an aside, would you please add flush/dump buttons to the machines like the PRC? I made some oopsies setting things up last night and had the wrong fluid/gas in the wrong places. Having to move it all out into tanks with a gauge was painful.

**Comment by aidancbrady** [comment]
What would you think about flushing a gas/fluid tank by holding shift while clicking it with a gauge dropper?  I just don't like having dump buttons clutter an interface.

**Comment by TacoMage** [comment]
I can't speak for Xeno, but I like the idea of having the dropper able to void a tank in one shift-click.  As it is now, the gauge dropper is a little clunky when trying to empty something.

**Comment by aidancbrady** [comment]
Done! :)

**Comment by xenoflot** [comment]
Sorry for the late reply, been at work :)

A good GUI finds a balance between aesthetics, functionality and consistency. A combination of these things results in what users consider "intuitive". As much as you might feel that dump buttons clutter a GUI, I think they provide simple and easily-understood functionality and since you use these buttons in other machines, they provide consistency across your mod. Shift-click functionality on the dropper is hidden functionality therefore not "intuitive". As such I think the buttons should be implemented on all machines and tanks.

If I might make some general suggestions on your UI, the lack of contrast and symbols may raise some issues for users with visual impairment and general usability. Also, thanks to the ubiquity of mods like TE, people have been conditioned to work with right-loaded UIs. I'd also upsize the in/out controls a bit.

I'm no artist, but here's a mockup of what I feel would be a positive change to your UI when applied consistently across all machines. http://i.imgur.com/ToyOeXM.jpg  http://i.imgur.com/jXTvpdE.jpg

Cheers, Xeno
