### ISSUE TITLE
Can't mine nether ores?

### ISSUE THREAD

**Issue by Lokiner** [aidancbrady/Mekanism#2697]
So I made a couple Digital Miners and the one on the overworld works just fine but when I drop one in the nether and try to set a filter to mine all of the nether ores, I don't get a picture and it doesn't mine anything, what's the problem here?

**Comment by RAWRwins254** [comment]
What mining keyword are you using? Use ore* if you're not already

**Comment by aidancbrady** [comment]
Works fine for me, make sure your keyword is correct as mentioned before

**Comment by Lokiner** [comment]
I had to go and mine every single ore block from the nether and add them one at a time so my DM has 25 filters now.. So it wasn't the best fix but I guess it's working halfway now, couldn't find every ore.

I was using *ore* as the filter but it doesn't have the nether ores in the ore dictionary, that or the miner isn't pulling the dictionary correctly.

**Comment by RAWRwins254** [comment]
you need ore with an asterisk after it (AKA ore* ) otherwise it shouldn't
work.

**Comment by douglasg14b** [comment]
Shouldn't this still work in inverse mode? Ie. mine everything else except netherrack?

For some reason, in inverse mode it still doesn't collect ores.
