### ISSUE TITLE
[Request] ModTweaker support

### ISSUE THREAD

**Issue by Maxwelljones** [aidancbrady/Mekanism#2699]
Hello!

I'm using Mekanism in my modpack, but it seems that with the last update, minetweaker doesnt support anymore the infuser - means infuser recipes cannot be tweaked anymore. Would that be something that could be sorted on your side?

Thanks in advance for your answer.

-- Here's a link to the report on modtweaker side: https://github.com/jaredlll08/ModTweaker2/issues/111

**Comment by aidancbrady** [comment]
I wish it was, but minetweaker sadly needs to update compatibility on their side.

**Comment by Maxwelljones** [comment]
Thanks for a blitz answer!
By the way Mekanism is awesome! Keep up the good work.

**Comment by aidancbrady** [comment]
Sure thing :)

**Comment by jaredlll08** [comment]
Hey @aidancbrady how does mekanism work now? if it uses IMC then it is not possible for me to update the code.
