### ISSUE TITLE
Clone ores utilizing Enrichment Chamber and Redstone Furnace from TE

### ISSUE THREAD

**Issue by bluewave41** [aidancbrady/Mekanism#2700]
I was using this setup here on a server and noticed some strange results: http://puu.sh/i4qhG/4448c42fa4.jpg

I placed a full stack of sand in the Redstone Furnace and while it was operating, placed iron ore into the Enrichment Chamber.

When the Enrichment Chamber finished, it immediately pushed its iron dust into the ORANGE slot of the Redstone Furnace (which if of course output, nothing should go in there) and when the Redstone Furnace finished its operation, I found myself with 3 iron dust instead of 2.

**Comment by aidancbrady** [comment]
This should be fixed as of a recent change.
