### ISSUE TITLE
Mekanism Pipes

### ISSUE THREAD

**Issue by EmperorMeer** [aidancbrady/Mekanism#2707]
None of the different types pipe, that  have access to aren't working (including Mekanism ones) because they can't pick up the salination plant as a liquid input so I can't set the pipes to pull or push into the plant and the plants status is structured, any suggestions on what to do?

**Comment by aidancbrady** [comment]
Use Mechanical Pipes for fluid transport and a Configurator to define push/pull functionality on the segments connected to the Salination Plant.

**Comment by EmperorMeer** [comment]
i have tried that and I can't because the pipe isn't attaching to the salination plant valve block so I can't define push or pull
