### ISSUE TITLE
Mekanism pipes keep malfunctioning.

### ISSUE THREAD

**Issue by Jynx2700** [aidancbrady/Mekanism#2708]
I have been playing with the new reactor for about a week now and have found a continual problem with all of the pipes (Power/gas/fluid/item) They randomly just stop working and I have to go through and break / replace all of them. I have been digging through forum posts and wiki's but no one else seems to have had this problem before. I cant even get around the problem because the gas state is not supported by other mods. I would just go machine to machine but intake being on the bottom of some machines...It just does not line up.

Mekanism 8.1.2

**Comment by aidancbrady** [comment]
Which version are you using?

**Comment by Jynx2700** [comment]
Mekanism 8.1.2
We are using it in the most recent Resonant Rise pack

**Comment by HanatakeYurii** [comment]
Mekanism 8.1.3.231 is out now
