### ISSUE TITLE
Purification Chamber inputs

### ISSUE THREAD

**Issue by harley9699699** [aidancbrady/Mekanism#2709]
After updating to 8.1.3, had to spend over an hour trying to figure out why my assembly line halted. Could NOT the shards from the Chemical Injection Chamber to the Purification Chamber inputs---any more. Going back to 8.1.2 fixed the problem. Something happened in the update to 813 that nerfed the inputs. Just fyi.

**Comment by Elvarion** [comment]
At least its not just me going crazy, I've almost pulled my hair out trying to see what im doing wrong with the Input to Purification Chamber..

**Comment by hehe3301** [comment]
Thus is explained on the wiki. You have to pump mekanism oxygen gas into the purifier. May I recommend reading the wiki article on ore processing.

**Comment by hehe3301** [comment]
Check it out here.
http://wiki.aidancbrady.com/wiki/Ore_Processing

**Comment by harley9699699** [comment]
May I recommend you reading what I initially wrote. It worked fine---before the update. Since it worked fine before, that means the oxygen was already going to it. Since going back to 8.1.2 fixed the problem, that means there is something amiss in the update.

**Comment by Elvarion** [comment]
@hehe3301 

Oxygen present
http://gyazo.com/adbdb92b56f3f7b6337e284c0f831828
Input Slots
http://gyazo.com/07bdf46494770c6554435d56ad3d1a76
Ender IO Item Conduit
http://gyazo.com/b3abc1bdd478fcef65f7c98ec3fadce3
http://gyazo.com/bb751835a7ae895042f3287cdf7f3cc9
http://gyazo.com/50330cd42a09f56faa481cfea9f83b3a
Chest with items
http://gyazo.com/dc41d63ed6da585764c21105b968ed3c

Also, Mekanism Copper dust has no smelting recipe anymore

**Comment by billm** [comment]
Hopper above worked before update as well.  No method that I have tried (vanilla, Ender IO, Mekanism transporters as well as colored transporters) of automatically putting items in the purifier seem to work.  Performing 2x for now and manually feeding the few ores I need 3x processing for into the purifier.

**Comment by billm** [comment]
Upgrading to a factory did fix the issue.

**Comment by ranma862** [comment]
Getting the same issue here. Purification Chamber does not accept any automatic inputs - I tried vanilla hoppers, Mekanism logistical transporters, and having the machines adjacent to each other. As billm said, switching to a Basic Purification Factory worked, and this is only since the 8-1-3 update. I just finished rolling back to the 8-1-2 on my server and it worked normally, so it's definitely something with 8-1-3

**Comment by ranma862** [comment]
Also getting a similar issue with the Chemical Injection Chamber, it's not accepting automatic inputs either. Switching to a Basic Injecting Factory also still works.

**Comment by magnusjjj** [comment]
Same here. Oxygen fine, energy fine, putting things in manually, all is fine. Just not anything automatic.

**Comment by magnusjjj** [comment]
Can verify the following:
- The latest revision does not fix the issue (compiled it from scratch)
- The factory version still works

**Comment by aidancbrady** [comment]
@Elvarion, I can't reproduce the missing tin and copper smelting recipes with only Mekanism installed, there may be some kind of conflict.  Looking into the purification chamber issue now.

**Comment by aidancbrady** [comment]
Fixed!

**Comment by crashoverride81** [comment]
playing on bevo tech pack reborn latest version on the ATLauncher and the purification chamber does not accept any automatic inputs! Wondering if there is a fix for this yet?

**Comment by thiakil** [comment]
This is a very old bug report. If you're running an v8 series build out of necessity, make sure you're on the latest v8 or you're out of luck.
