### ISSUE TITLE
Entities other than player get constantly teleported.

### ISSUE THREAD

**Issue by Sil3ntStorm** [aidancbrady/Mekanism#2711]
When any entity other than a player (tested chickens and cows), enters an active, linked Teleporter, they will constantly teleport between the two linked teleporters until they leave the portal block.

Using Mekanism 8.1.3.231 on MC 1.7.10

**Comment by TheIcyOne** [comment]
Also applies to items, will drain all power from the teleporter.

**Comment by aidancbrady** [comment]
This has been fixed.
