### ISSUE TITLE
ore processing 

### ISSUE THREAD

**Issue by wandersonbraz** [aidancbrady/Mekanism#2713]
hello friends

recently I rode a ores cleaning process using the Mekanism ended up running into a problem some ores simply not entrao in the process.

Ferrous ore - thermal expansion
shyne ore - thermal expansions
aluminun ore - Tinker`s
yeloriun ore - Big reactor

I am using the process of triple ores with oxygen, have any config or addon Mekanism having to change for these ores are processed?

version of forge 10.13.1.1395

**Comment by RAWRwins254** [comment]
AOBD might allow for that, but if not, those ores are stuck at 2x yield.

**Comment by wandersonbraz** [comment]
the process of 2x I already have with themal expansion

**Comment by RAWRwins254** [comment]
Well see if aobd can do it. If not, Sorry.

**Comment by wandersonbraz** [comment]
I just saw something I'm using hoppers to pull oos items bau soon will use an interface me so that items are not out of the hopper as if the input was not set

**Comment by hehe3301** [comment]
The only way to get those working is to use"Another one bites the dust" mod

**Comment by RAWRwins254** [comment]
The above comment has unabbreviated my last few posts.

**Comment by RAWRwins254** [comment]
Aobd is required to have mek process those ores higher than 2x yield.

**Comment by wandersonbraz** [comment]
I installed aobd now and ores processing station normally but the strange and the hoppers are not sucking the items into the chamber of purification and as if it had an active Redstone signal around but do not have any

**Comment by hehe3301** [comment]
Are your sides configured properly? And do you have auto eject on?

**Comment by wandersonbraz** [comment]
yes all config set
