### ISSUE TITLE
Electrolytic Separator, Insane energy consumption

### ISSUE THREAD

**Issue by Elvarion** [aidancbrady/Mekanism#2715]
ES consumes 40k rf/tick when having 8/8 Speed upgrades and 8/8 Energy upgrades. Removing the Energy upgrades still makes it consume 40k rf/tick. Thus im suspecting the Energy upgrade not working in the Separator

**Comment by aidancbrady** [comment]
This is intentional - energy upgrades do not increase efficiency of the separator, only the max energy buffer.
