### ISSUE TITLE
Electric chest cannot be accessed by OPerators

### ISSUE THREAD

**Issue by themechman** [aidancbrady/Mekanism#2716]
Unfortunately I am unable to monitor these chests when they are passworded. I would like to be able to view these contents to monitor for contraband.

**Comment by themechman** [comment]
And it seems one of the admin's just destroyed the chest in question by accident. <facepalm>

**Comment by aidancbrady** [comment]
Just added an "OpsBypassRestrictions" entry to the config, this allows for operators to access locked chests when enabled.

**Comment by themechman** [comment]
Thank you!
