### ISSUE TITLE
Universal cable issue [x-post]

### ISSUE THREAD

**Issue by aolko** [aidancbrady/Mekanism#2717]
[x-post from EnderIO](https://github.com/SleepyTrousers/EnderIO/issues/2538)
=*=
Why i can't connect enderio conduits/machines with universal cables? (latest enderio/lastest mekanism (8.1.3.231))
=*=
![img1](http://i.imgur.com/UbAvBBr.png)
![img2](http://i.imgur.com/wFzZnis.png)
![img3](http://i.imgur.com/SL5N57y.png)
----
Solved: Check if you got latest cofhcore. Mekanism kinda requires it.

**Comment by aidancbrady** [comment]
In order to interact with RF, yeah, you need CoFHCore.

On another note, I think it's time we start shipping again.  @tterrag1098, would you advise shipping the entire library or just the packages we need?

**Comment by tterrag1098** [comment]
@aidancbrady That's not the problem here, you should be using CoFHAPI|energy in your @Optional annotations, not CoFHCore. So that any mod providing the API will satisfy the annotation. You don't need CoFHCore as that's (definitely) not the only mod that ships the RF API.

**Comment by unpairedbracket** [comment]
The reason I changed the requirement to CoFHCore was because of potential issues with other mods shipping partial cofh energy api. If that isn't going to happen, we can safely change it back

**Comment by tterrag1098** [comment]
@unpairedbracket Of course that's going to happen, but it's not your fault. You can't code around every stupid thing modders try to do. Do it right, and leave it on them to fix their mistakes.
