### ISSUE TITLE
Thermal Expansion Dupe Bug

### ISSUE THREAD

**Issue by palaster** [aidancbrady/Mekanism#2719]
Thermal Expansion - 4.0.1-182
Mekanism - 8.1.3.231
Mod Pack - Resonant Rise 3.2.6.4 RC

If you place any TE Cache on the output face of a digital miner from mekanism, it is possible to dupe the contents of the cache. First, place the desired item (such as diamonds) into the cache, then place any useless item (such as stacks and stacks of cobble) into the inventory of the digital miner. The miner will auto output and increase the number in the cache.

* Also, I made this issue first on the Thermal Expansion issue, but KingLemming said it not his mod.
* https://github.com/CoFH/Feedback/issues/579, KingLemming points out what the issue is.

**Comment by aidancbrady** [comment]
Fixed :)
