### ISSUE TITLE
Exception while updating neighbours

### ISSUE THREAD

**Issue by GodNero** [aidancbrady/Mekanism#2720]
Minecraft - 1.7.10
--------Involved Mods------
Ender IO - 2.2.8.381
Sanguimancy - 1.1.9-29
Mekinism - 8.1.3.231
--------Crash Report-------
Pastebin - http://pastebin.com/menKawd7

I can't tell you what was going on before this crash happened as this is from one of the servers using the Resonant Rise pack. I am still trying to recreate this issue, just thought you might have some insight on this one.

---------------------
Sanguimancy - https://github.com/Tombenpotter/Sanguimancy/issues/61
Ender IO - https://github.com/SleepyTrousers/EnderIO/issues/2543

**Comment by aidancbrady** [comment]
Crash points to Sanguimancy as the culprit.  Let me know what the author says.

**Comment by GodNero** [comment]
Will Do
