### ISSUE TITLE
item input 

### ISSUE THREAD

**Issue by zortag** [aidancbrady/Mekanism#2721]
Mekanism-1.7.10-8.1.3.231

I can't insert items (ores) in mekanism's machines by using pipes. any sort of pipe, from vanilla hopper to te itemducts nor mekanism logistical transporter, nor ender io item conduits, nor me export bus.
I correctly configured faces and tryed to use different sides but items don't go inside the machine (tested on purification chamber and crusher) output works well and machine-to-machine input/output workd

**Comment by aidancbrady** [comment]
This is fixed in development.

**Comment by zortag** [comment]
please can I have the url where get it?

**Comment by grimallq** [comment]
@zortag Dev builds are for donators only.

On that note: A new public release just went out about 30min ago.

**Comment by zortag** [comment]
thanks to explaining me that
