### ISSUE TITLE
Broken energy multiplication on the speed upgrades.

### ISSUE THREAD

**Issue by rrbrussell** [aidancbrady/Mekanism#2722]
Mekanism version 1.7.10-8.1.4.232 and I think 231 as well have a major energy multiplication bug in the speed upgrades.

Base usage on the digital miner is 269.74 J/t
![2015-06-05_17 27 06](https://cloud.githubusercontent.com/assets/5332272/8016372/2cdbc42a-0ba8-11e5-95a3-677272ede105.png)

With 8 of 8 speed upgrades it should be 2697.4 J/t or 2.6974 kJ/t. Instead the miner is reporting and appears to be using 26.97 kJ/t
![2015-06-05_17 28 50](https://cloud.githubusercontent.com/assets/5332272/8016401/697ef960-0ba8-11e5-8ad4-ac849518e0e7.png)

No energy upgrades are involved, Yet.

With 8 of 8 energy upgrades and 8 of 8 speed upgrades installed the digital miner is reporting energy requirements of 2.69 kJ/t.
![2015-06-05_17 31 42](https://cloud.githubusercontent.com/assets/5332272/8016431/c9864494-0ba8-11e5-8c92-29843c0e89c1.png)

With only 8 of 8 energy upgrades installed the digital miner is reporting energy requirements of 26.97 J/t.
![2015-06-05_17 32 50](https://cloud.githubusercontent.com/assets/5332272/8016444/ec970a4a-0ba8-11e5-9d01-40910d25442e.png)

I am pretty sure something is wrong. Especially since when I built the server about 2 Mekanism point versions ago it was working correctly. So sometime after 229 or 230 it broke.

**Comment by aidancbrady** [comment]
I'm not sure why the base usage is 269.74 J/t unless you changed the config, the default is set to 100.

Someone can correct me if I'm wrong, but assuming 269.74 J/t is what you want for the base value, everything looks correct - energy upgrades reduce power draw by a scale of 10, speed upgrades increase power draw by a scale of 100, resulting in a combined increase by a scale of 10 when 8 upgrades of each type are installed.
