### ISSUE TITLE
[Request] Gas storage Multiblock

### ISSUE THREAD

**Issue by Saizetsu** [aidancbrady/Mekanism#2723]
I was trying to fiddle with the dynamic tank for gas storage but that is not something it does. Is there a chance something could be added? Cureently an advanced injection factory requires 8 salination plants at 18 to run a constant stream of 7 ore stacks. And im not seeing a way to optimize it like i can with the power network.

**Comment by aidancbrady** [comment]
As of right now this is just a use of the rotary condensentrator - converting gas to fluid for storage in a dynamic tank. Maybe in the future though :)
