### ISSUE TITLE
A bug, causing server lag.

### ISSUE THREAD

**Issue by ziba1** [aidancbrady/Mekanism#2725]
Hi, I posted this in the 1.7.10 pack repository, and the modpack owner sent me to an already existing thread with the same issue that had been closed.  On my game server Mekanism was... I dunno getting stuck ? repeating the same line of code thousands of times which caused my server to max out on its ram use and cpu use.  The owner of the 1.7.10 pack suggested I post a new issue here and link you to my already existing issue with my server logs, and link the other dudes issue as well, in case you missed the posts already 

https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/611#issuecomment-105611776

https://github.com/aidancbrady/Mekanism/issues/2673  - someone else also posted here with the same issue.

For the time being I ended up rolling the modpack back, but since I am starting a new world with my friend soon I do wanna run the mod pack at its most up to date, so anything you can do to help would be awesome

**Comment by HanatakeYurii** [comment]
What version of Mekanism are you using?

**Comment by ziba1** [comment]
Assuming, I'm reading the technic page correctly, 8.1.2.229 is the version being used by the 1.7.10 pack

**Comment by HanatakeYurii** [comment]
Hum, it's really outdated (now it's 8.1.4.232). Should try with the new version

**Comment by rrbrussell** [comment]
Be aware that speed upgrades are broken in the 8.1.4.232 update per issue #2722.

**Comment by ziba1** [comment]
I havent tried the newest version yet, since when I last updated things, then had to roll back it turned all my glass slabs into osmium slabs haha, don't wanna screw up our world.

However the 1.7.10 pack author has told me that they have now updated to the latest version but the bug is still occurring for people.

**Comment by aidancbrady** [comment]
@unpairedbracket, when you have a chance would you mind taking a peek at this?  It seems like it may have to do with the new orphan system for transmitters you implemented.

**Comment by unpairedbracket** [comment]
I'll take a better look at it in a week or so, after my exams are done, but it looks like there's some chunk stuff going on that may or may not be our fault. We should provide an option to disable the debug output of the transmitter code (or only enable it if Mekanism is in debug mode?), as that is likely causing a significant part of the server load reported

**Comment by aidancbrady** [comment]
Good thinking, done.
