### ISSUE TITLE
[Request] Multi block Hydro electric plant

### ISSUE THREAD

**Issue by Saizetsu** [aidancbrady/Mekanism#2726]
Running on survival it takes alot of thinking on how to use resources and while fusion is great its not to easy to get the laser power to have it dump out power. Though i enjoy the fusion plant considering real life fusion is no capable of powering crap but i was hoping to get more generator if not this very massive hoover dam style hydro electric plant. Or fission power. Gas burners were my goto but the power they generate was dropped to 200 j/t and that just barely powers the seperator it hooks to.

**Comment by rrbrussell** [comment]
Hydrogen was turned into an energy carrier in Mekanism 8. The preferred fuel source for the Gas-Burning generators is now [Ethylene](http://wiki.aidancbrady.com/wiki/Ethylene) follow the link for the wiki page explaining how to make it and about its energy density.

**Comment by Saizetsu** [comment]
No not hydrogen. Hydro electric. Like the hoover dam, pushes huge amounts of water through its turbines and that creates huge loads of power.

**Comment by EzerArch** [comment]
@Saizetsu, I'm interested in it to, but you need to give more details on how it would work so that the developer can get a better figure of your idea. Example: how to build, what is made of, size, shape etc.

**Comment by Saizetsu** [comment]
Its really simple though, its falling water that would spin a turbine and output power based on how much water pressure there was to spin the turbine. An electric pump or several say seven would ram enough water into it to outdo a fusion generator. Real world hydro outputs more than civilian fission plants. But civvys only use 2% of the fission proc they cant do more without military secrets.

The multi block would just be a turbine size can be increased with something like the dynamic tank block it would need a helluva lot of water but the more the better

**Comment by Saizetsu** [comment]
Hm rife with grammatical and spelling errors, the hydro electric plant would require multiple turbines, a water pump and a pressure pump. Higher amounts of pressure and water pushing through a turbine, this would cause the turbine to spin and the rotations would cause electrical discharges which would require something to take that and convert it into proper electricity, the more pressure, and water pushed through would generate more power but it would require a larger size. More turbines and so forth. A very large multiblock structure or just several machines.

**Comment by rdunham3** [comment]
This is worth giving a bump.  Hydroelectric is IRL a great source of power but as noted each unit would be fairly small output - the water equivalent of the existing heat generator.  RL hydro plants use a reservoir behind the dam, so what they're really doing is using water and turbines to convert gravity's pull to energy.  As long as the river upstream doesn't dry up you've got mind-boggling amounts of energy sitting in the reservoir.

Possibly implement like the existing wind generator, but single-block-sized and requiring both a water block above and empty (or flowing water) block below to function?  You could stack these like a vertical checkerboard for a large-scale plant or have a few hiding in a creek for a non-eyesore energy source.

Set up a few dozen of these and you should be able to power a typical base.  Go large and power anything.  A few RL hydroelectric dams power most of Washington state and they export power to other states too.

**Comment by ruifung** [comment]
Problem is, you can't have dried up rivers in minecraft.. since water doesn't flow like that.
Maybe something like RotaryCraft's hydro turbine thingy.

**Comment by Saizetsu** [comment]
I have seen an electric pump drain a lake before. But a storage device could be used in place of having to use water, just set it up like the solar evap plant. Surround a tower multi block that works like a generator with dynamic glass pump an ocean with pumps into the tank and it spins up and makes electricity.

**Comment by ruifung** [comment]
Using electric pump to pump water into a hydro generator? Thats not really a good idea =/

//IRL
For starters, it would violate the law of conservation of energy. Energy is being converted to kinetic energy then converted to potential energy, which is then converted back to kinetic energy then to electrical energy, which would cause quite a bit of energy loss I imagine.

**Comment by Saizetsu** [comment]
Well if we want real life then the fusion generator shouldnt produce enough power beyond being able to sustain itself. And most humans can not punch a tree down either. 

But i digress, a pump was part of an example. I use acqueous accumulator for most if not all water using machines. I assume most people would have a power network before using a hydro plant.

**Comment by ruifung** [comment]
Well IRL its possible for nuclear fusion to generate enough power to sustain itself, we just haven't managed it yet. The sun does use fusion reactions after all.

**Comment by Saizetsu** [comment]
We have managed it. We have a single fusion plant in the states. It powers itself and nothing else, actually i wonder if mekanism would add in cold fusion. Its only workable in theory but hey. Mc has people punch trees down.

The more pressure behind the water the faster the turbine will spin, generates more power so a cyclical system would work to start add in more water or more pressure or both and it would give more power, or set up several turbines. Hence a multi block, it would require thousands of gallons of water.

**Comment by rdunham3** [comment]
For Minecraft/Mekanism purposes we could have the hydroelectric turbine block require that water is above it (mostly for aesthetics) but not actually consume the water.  

If it were to require a continuous supply passing through it, the user would simply put a pump below and a plenisher above anyway, making it all moot.

**Comment by Saizetsu** [comment]
Actually, it could be setup to use more water than a standard plenish/pump can give. It needs massive amounts of water to give out power after all. Although having water fall down to it from a high height could help too. Like 255 near build cap. Water fall height would make such an aesthetic useful as well.

**Comment by Saizetsu** [comment]
Well I hope this is taken into consideration.

**Comment by EzerArch** [comment]
Just to show off, a guy built a hydroelectric dam: https://redd.it/3kic2t

![](http://i.imgur.com/ss6s09Z.jpg)

Although I don't think Mekanism needs to be like that.

**Comment by aidancbrady** [comment]
I'd rather leave this kind of mechanical power generation to mods like Immersive Engineering for now.  This doesn't mean I'm taking it off the table, but for my current release schedule I'd rather streamline the amount of content I'm adding.
