### ISSUE TITLE
Bronze to tinker alloy

### ISSUE THREAD

**Issue by Saizetsu** [aidancbrady/Mekanism#2727]
After hitting reset to defaults on mekanismI am no longer able to make bronze equipment, it all turns into thermal foundations tinkers alloy. Now thermal foundation is turning more virulent and overpowering mekanism on showing rf over joules with waila and now its hijacking equipment is there a way to make this stop aside from obviously removing thermal?

**Comment by aidancbrady** [comment]
Yeah, nothing here is on my end or a result of my changes. Removing TE is the real only way to get rid of all interference, though it's definitely possible to fix the recipes using recipe editors.
