### ISSUE TITLE
[Issue] Freeze in title screen/after quitting world (1.7.10 8.1.4.231-233)

### ISSUE THREAD

**Issue by iExalt** [aidancbrady/Mekanism#2731]
After joining a singleplayer world and quitting to menu, Minecraft freezes. Opening a world for the first time and using the main menu before joining a world works fine. Subsequent "first joins" work fine as well. I have confirmed multiple times that it is indeed the base Mekanism mod that is causing the freeze or an interactition between Mekanism and another mod. When I take Mekanism out of the mod file, the freeze goes away. Adding or removing the generators or tools addons does nothing.  I am running just the base Mekanism, Forge 1424 and Liteloader_04. I've tried Mekanism versions 231-233 to no avail.

[Forge log](http://pastee.co/Jh0kDT)
There is no crashlog - this isn't a crash

**Comment by aidancbrady** [comment]
Working fine with exclusively Mekanism and IC2 in my dev environment.  I'd call this a corner case, do let me know if you find the offending mod though.
