### ISSUE TITLE
Chemical Crystalizer is ignoring side config

### ISSUE THREAD

**Issue by utoc** [aidancbrady/Mekanism#2737]
Good morning,

I am running Mekanism .232 at this time with FML 1448.  I have found a bug with the chemical crystalizer ignoring the side config and only pulling gas from the left.  All side config options are ignored for gas.  See the screenshots below.  Full mod list here: https://www.reddit.com/r/BBQSauce/wiki/modlist

Side config: http://i.imgur.com/wWsZOj2.png

It doesn't accept the gas from that side:

http://i.imgur.com/QPTIqZ0.png

The only workable solution:

http://i.imgur.com/uN9La3C.png

Let me know if there is any way I can assist

**Comment by aidancbrady** [comment]
That's because you're configuring the item panel of the side config.  On the config interface, hit the "warning" label symbolizing gas, and then configure that.  You'll be all set :)

**Comment by utoc** [comment]
I see it now, thanks for point that out.  thank you!
