### ISSUE TITLE
java.lang.NullPointerException when using a dropper in a tank

### ISSUE THREAD

**Issue by utoc** [aidancbrady/Mekanism#2738]
Running Mek 232, FML 1448
Modlist here: https://www.reddit.com/r/BBQSauce/wiki/modlist

Server Pastebin here: http://pastebin.com/XxDznKX5

I was emptying Lithium gas out of a Chemical Crystalizer when this occured.  No errors or crash on the client, just reporting these errors.

**Comment by aidancbrady** [comment]
Fixed! :)
