### ISSUE TITLE
Solar Neutron Activator not using Li from Gas Tubes

### ISSUE THREAD

**Issue by nintendow131** [aidancbrady/Mekanism#2739]
The Solar Neutron Activator does not accept Lithium via Gas tubes from the front side.
Instead it uses the Lithium, but doesnt turn it into Tritium.
(using forge 11.14.3.1446)

**Comment by aidancbrady** [comment]
You need to input lithium through the bottom - tritium will come out the front.

**Comment by FlyTrix** [comment]
My solar neutron activator don't work. I input the lithium to the bottom and I extract the tritium at the front but my lithium don't want to go in the solar neutron activator

**Comment by Solverbolt** [comment]
yeah, bottom no longer works.  Solar Neutron Activator is deleting the lithium on contact, and no other side but the one with the square will accept anything. This used to be a great mod. Apparently its gone into the garbage.

**Comment by Solverbolt** [comment]
![image](https://user-images.githubusercontent.com/38087746/81636657-3f6c6780-93c9-11ea-85d5-59c5c21c2e03.png)

**Comment by Solverbolt** [comment]
every pipe from mekanism acts like that

**Comment by pupnewfster** [comment]
You can't connect mechanical pipes (fluid) to the solar neutron activator... as it only deals with gases (pressurized tubes)
