### ISSUE TITLE
Hydrogen Generator:

### ISSUE THREAD

**Issue by Badcholo** [aidancbrady/Mekanism#2742]
I have installed Mekanism 1.7.10 and have attempted to build a hydrogen generator / separator setup to power my base. I guess the process has changed cause it seems complicated and seems like the Hydrogen generators are useless now. I installed the mod cause i liked the way the Hydrogen generators work. I like Mekanism cause of it's simple setup to get endless X amount of power. It has worked great in the past, specially with the force fields that require constant power. 

The old process is complicated enough for kids to be able to figure it out and use it. It seems that this mod is moving from kid friendly to grown up over complicated. Voltz is a very simple modpack and most people that played it, like myself loved mekanism cause of it's simplicity. I still haven't figured out how the 5x ore processing is done nor do i care. This mod is turning out to be more complicated than it has to be, like AE2. 

With all this rambling, i guess i'm just looking for a config option to turn it back into the way it used to work. I have looked though the config but was unclear of, if any would change the issue. I would just like to state that most players are kids. I create modpacks and have seem a huge change in mods going to overcomplicated ways in 1.7.10. probably why i see so many playing pixelmon.

**Comment by aidancbrady** [comment]
In my opinion, Mekanism still follows a very intuitive and not-too-complicated design that allows for most kids 13-and-up to pick up on things without much instruction.  The Gas Generator can be used in conjunction with ethene to create a good bit of power.

**Comment by Badcholo** [comment]
It's possible you think that cause it's you've played with it for a long time. It's also possible that most kids don't like complicated tasks. What happens after you build all those machines? What do you do after you have all the ores you want? What's next after you can 1 shot kill mobs and swim in lava? What is the point of having all those complicated setups just to get power? Seems to me mods are turning more complicated thinking that it means more fun, but in reality they are just becoming too complicated to be any fun. I really miss voltz. Thanks for the reply, I didn't mean to be a jerk or anything.
