### ISSUE TITLE
ae2 recipe 

### ISSUE THREAD

**Issue by himikokun** [aidancbrady/Mekanism#2744]
hi, I wanted to try this mod but I lost most of my ae2 recipe in nei and my pattern became invalid for most of ae2 items...
don't know if is nei or mekanism bugg please help

**Comment by RAWRwins254** [comment]
Forge and mekanism versions?

**Comment by himikokun** [comment]
forge 10.13.4.1448
mekanism 8.1.5

**Comment by himikokun** [comment]
as far every things work fine again, had to upgrage ic2 and buildcraft

**Comment by aidancbrady** [comment]
Not on Mekanism's side then.
