### ISSUE TITLE
Digital miner doesn't dig blocks on Cauldron server

### ISSUE THREAD

**Issue by HiTECNOLOGYs** [aidancbrady/Mekanism#2745]
After a recent upgrade of something (I'm not exactly sure what since I noticed this accidentally) digital miner stopped digging anything. I've tried removal of all the plugins that affect world modification behavior but without any success. It also works perfectly well in SSP. Any suggestion how I could determine the reason for it not replacing anything? Currently I'm using latest Mekanism (8.1.5.237) and it still doesn't work. Feel free to ask me to provide any additional pieces of information since I'm not exactly sure what else may be needed:
```
Minecraft version: 1.7.10
Mekanism version: 8.1.5.237
Mekanism generators version: 8.1.5.237
Forge version: 10.13.3.1388
```

Thanks!

**Comment by aidancbrady** [comment]
As of pretty recently, Digital Miners follow the Forge BreakEvent standards and will not break any blocks when not allowed.  Most likely there's a mod canceling the event- best advice I have is to try and isolate it in your mods list.

**Comment by HiTECNOLOGYs** [comment]
Hello again. Sorry for bothering again but I did some testing today (involving removing all the mods and plugins then adding them one by one) and at least one source of the problem seems to be the offline-mode authorization plugin that blocks Mekanism. Does the mod have some kind of fake players that might cause the problem? I scouted though the sources but found none. This is the only reasonable explanation I can think of.

**Comment by juniorjunior** [comment]
According to a recent commit:
```java
public static GameProfile gameProfile = new GameProfile(UUID.nameUUIDFromBytes("mekanism.common".getBytes()), "[Mekanism]");
```
It appears as though the fake player is named [Mekanism] or some UUID generated from that. There was also a mention that it it was akin to the BuildCraft implementation. However, BuildCraft outputs its fake player information to the FML log but I see nothing for Mekanism. Until we can figure out what to use, none of the protection plugins are going to let this work.

**Comment by spannerman79** [comment]
@juniorjunior did you manage to track down the fake player info that Mekanism uses?

I also am having this issue on the latest kCauldron and until I can put the fake player into the same group I put [BuildCraft] it won't be able to break blocks
