### ISSUE TITLE
TransmitterNetworkRegistry.java in MDK is referencing "Mekanism" class that is not present in the API.

### ISSUE THREAD

**Issue by halvors** [aidancbrady/Mekanism#2746]
TransmitterNetworkRegistry.java in MDK is referencing "Mekanism" class that is not present in the API.

This must also be a mistake:
`
import mekanism.common.Mekanism;
`

**Comment by aidancbrady** [comment]
Ooh, thank you.  Let me see what I can do.

**Comment by aidancbrady** [comment]
Fixed.

**Comment by halvors** [comment]
Nice :-)
