### ISSUE TITLE
Teleporter only list 4 frequencies

### ISSUE THREAD

**Issue by jaz000** [aidancbrady/Mekanism#2751]
Is it just me or do teleporters only list 4 frequencies?
Have this in a couple of modpacks on 8.1.4 and 8.1.5

Other frequencies work fine if you type them in

We tend to make a number of bases and then use portable teleporters to jump to them. I was expecting the list of frequencies (names) to be able to scroll once there was more than 4 but that's not the case for me. Im not even sure of the pattern to the 4 names that you do see, not always the first 4, last 4 or alphabetical list so it seems

**Comment by aidancbrady** [comment]
I'm able to scroll through them just fine - use the little scroll bar to the right of the entries.

**Comment by jaz000** [comment]
aha - sorry, that scroll bar is very "little" :-)

**Comment by UntouchedWagons** [comment]
The scroll bar doesn't work for me.
