### ISSUE TITLE
Disconnected from server when using Portable Teleporter

### ISSUE THREAD

**Issue by kesppr** [aidancbrady/Mekanism#2752]
Was only able to test on one server, using mekanism 8.1.3
Whenever I right click with the Portable Teleporter I get disconnected from the server  with an "Internal Server Error" message or sometimes a "[...] Disconnected by Peer", but only if the pitch of my head (vertical inclination measured with /getpos, 90° is looking straight down, 0° is looking forward and -90° is looking straight up) is beyond certain values, which differ depending on the y-level I'm standing at. This is what I measured (y-level is feet y-level):
y = 2; pitch < -70°
y = 39; pitch < 21°
y = 72; pitch < 21°
y = 115; pitch < ~48°
Wasn't able to reproduce in singleplayer. Was able to reproduce in different locations on the server, both while near teleporters and far from any of them.

**Comment by aidancbrady** [comment]
I can't do much without a log from the server.

**Comment by kesppr** [comment]
Unfortunately I'm not the server owner but I can ask an admin for a log later. The client logs didn'

**Comment by kesppr** [comment]
...didn't show any errors (I misclicked and closed the issue by error, reopened it)

**Comment by aidancbrady** [comment]
Yeah, it sounds like a server-based issue.  If you could get me a server log I could definitely take a good look.

**Comment by Tom7353** [comment]
I have exactly the same issue, but I can't figure out, what it has to do with the direction I am looking.
Anyway, I and some friend do have a multiplayer server, and I am the admin, so I can post the log (at least, what I can find in the logs):
`[10:35:36] [Server thread/INFO]: ** [/**.**.**.**:2046] logged in with entity id ** at (-4894.309778614357, 69.0, 10094.267112684212)
[10:35:36] [Server thread/INFO]: ** joined the game
[10:36:22] [Server thread/WARN]: Failed to handle packet for /**.**.**.**:2046
java.lang.NullPointerException
[10:36:22] [Server thread/INFO]: ** lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[10:36:22] [Server thread/INFO]: ** left the game`

Hope this helps you!
Mekanism is version 9.0.2 w MekGenerators and MekTools...

**Comment by Hallstead** [comment]
I'm having this same issue now. Can someone give an answer?

**Comment by thiakil** [comment]
nope, no help because there's no indication of where the null pointer exception occurs
