### ISSUE TITLE
How do other mods add recipes?

### ISSUE THREAD

**Issue by jaredlll08** [aidancbrady/Mekanism#2753]
Hey I am the author of modtweaker, currently support is broken, and I am wondering how I am meant to add recipes now, since it changed between 7>>8

**Comment by Landrash** [comment]
Some more details on what you need might get this a bit further?

**Comment by aidancbrady** [comment]
Support should actually work just fine, but yeah, it did change.  Mekanism now uses IMC for recipes, I wrote up a complete guide on how to integrate here: https://github.com/aidancbrady/Mekanism/wiki/IMC-based-recipe-integration

**Comment by jaredlll08** [comment]
:/ Minetweaker does notsupport inc message... Sigh, atleast I have a reason
to implement imc now...
