### ISSUE TITLE
Flamethrower blocking + MineTwekaer flamethrower problem

### ISSUE THREAD

**Issue by DJIronic** [aidancbrady/Mekanism#2754]
I want to block flamethrower at my server, but this option is not in config file and remove recipe by MineTweaker is ignored. (I can add costum crafting but I can´t remove original). 

Can you add this to the next version (or give some tips beacause i need it to run the server in few days.). Yes, I am using latest version on 1.7.10. 

Thanks, Simon.

**Comment by DJIronic** [comment]
OK, I already dealed with it with MineTweaker, but it will be good to block it in configuration of Mekanism :)

**Comment by aidancbrady** [comment]
You can disable aesthetic damage in the config :)
