### ISSUE TITLE
[Suggestion] New chemical injection chamber recipe:Hardened clay softening

### ISSUE THREAD

**Issue by karakufire** [aidancbrady/Mekanism#2757]
Though dirt can be in clay, it's wrong hardend clay can't soften.

**Comment by aidancbrady** [comment]
Done! Chemically injecting water vapor into hardened clay turns it back into clay, and the same turns bricks into clay balls.

**Comment by karakufire** [comment]
Thank you nice jobs!
But, I think not only hardened cray but also stained its, actually only NO STAINED hardened cray...
