### ISSUE TITLE
[Suggestion] Multi-Block battery input graph/reading

### ISSUE THREAD

**Issue by blackice125** [aidancbrady/Mekanism#2759]
I love your new Multi-block battery. Just broke 200T RF storage and I thought of something, 
So I love the output graph, how much trouble would it be to have an input/supply graph also.  I say this b/c on our server we are growing our laser drill array to match our mechanism reactor spare power output. Today I noticed that we were bleeding power and could not track down the new drain.  Just a thought b/c we have a few different power production systems, all feeding into the core battery.  Just thought it would be a nice to have.

**Comment by scifibob** [comment]
I completely agree on this one. It would be nice to have stats on both input an output.

**Comment by RAWRwins254** [comment]
I Also would love to see more stats for the matrix.

**Comment by aidancbrady** [comment]
As of right now the induction matrix only restricts output - I like the idea of also restricting input based on the amount of providers.  I'll see what I can do :)

**Comment by aidancbrady** [comment]
Done!

**Comment by aidancbrady** [comment]
Look how pretty this is:

![](http://puu.sh/iPuN4/e44ffc1e3a.png)

**Comment by hehe3301** [comment]
Beautiful

**Comment by blackice125** [comment]
great!!

B
