### ISSUE TITLE
Reactor fuel rates

### ISSUE THREAD

**Issue by blackice125** [aidancbrady/Mekanism#2760]
the input allows for odd numbers injection rates, but only even numbers effect output(witch makes sense, 1 from each of the fuel gases types)

**Comment by aidancbrady** [comment]
Right - I don't see anything wrong with this functionality.

**Comment by laz2727** [comment]
Does it lose the fuel?

**Comment by blackice125** [comment]
From little testing I did fuel rate of 7 was burying fuel at the same rate
as fuel rate 8 with no gain in RF output.

B

**Comment by laz2727** [comment]
I didn't really play around with the reactors yet. Is there any fuel loss?

**Comment by blackice125** [comment]
Yes. So with a fuel rate of 7 you lose the rate of fuel of the next tier of
fuel. So a fuel rate of 7 burns at fuel rate of 8 so in a sense you lose 2
fuel/tick and gain no rf. My guess is there is a math ceiling calculation
that maybe should be a floor setup.

**Comment by laz2727** [comment]
Sounds like a proper issue then.

**Comment by aidancbrady** [comment]
Hm.

**Comment by aidancbrady** [comment]
Fixed - odd numbers entered in the injection rate field now automatically round down to the nearest even number (e.g. 7 -> 6).  Thanks for pointing this out.
