### ISSUE TITLE
"Ghost" blocks

### ISSUE THREAD

**Issue by NonQueueingMatt** [aidancbrady/Mekanism#2761]
http://imgur.com/GiUjZnP&XUyFvQr
Randomly mekanism blocks/tile entities start doing this and slowly "infecting" other blocks in my world, and they become "ghostly" too. I seriously don't know what's up with this or why it's happening.

**Comment by aidancbrady** [comment]
I really don't think this is Mekanism :)

What is your current list of mods installed?  I may be able to find the culprit.

**Comment by NonQueueingMatt** [comment]
It's the Horizons Daybreaker modpack on FTB, but this has happened on every modpack I've installed mekanism in. Either way, here's the modlist: 
Forge/FML by LexManos, cpw
Advanced Generators by bdew
AMT Generators by Jeanglassmaker
Ancient Trees by ScottKillen
Another One Bites the Dust: Oreberry Bushes by ganymedes01
AOBD 2 by ganymedes01
AppleCore by squeek502
AppleMilkTea2 by defeatedcrow
AsieLib by asie
Aura Cascade by pixlepix
AutoPackager by smbarbour
Baubles by Azanor
Bdlib by bdew
Blood Arsenal by Arcaratus
Blood Magic by WayofTime
Blue Power by quetzi, amadornes, K4Unl, MineMaarten, RavenWhitefang
Carpenter's Blocks by Mineshopper
ChickenChunks by Chickenbones
Chisel by AUTOMATIC_MAIDEN
ChiselTones by TehNut
Clockwork Phase by Lumaceon
CodeChickenCore by Chickenbones
CodeChickenLib by Chickenbones
CoFH Core by CoFH team
Computronics by asie
CustomMainMenu by Lumien
DecoCraft by RazzleberryFox
DenseOres by RWTema
Difficult Life by DarkxElocius
DummyCore by Modbder
Emasher Defense by Emasher
Emasher's Resource by Emasher
Emotes by Vazkii
EnderStorage by Chickenbones
Engineer's Toolbox by Emasher
Enhanced Inventories by ANIMENIAC7
Equivalent Exchange 3 by Pahimar
EssentialCraft III by Modbder
Extra Utilities by RWTema
Farseek by delvr
FastCraft by Player
Flood Light by Keridos
Forge Multipart by Chickenbones
Framez by amadornes
Galacticraft by Micdoodle8
Garden Stuff by jaquadro
GasCraft by Emasher
Geko's Lasers by Gekoreivax
GuideAPI by TehNut
Hardcore Ender Expansion by chylex
Headcrumbs by ganymedes
iBench by Sapient_za
In-Game Wiki Mod by MineMaarten
Inventory Tweaks by Kobata
Iron Backpacks by Iron Backpacks
JourneyMap by techbrew
Kore Sample by ScottKillen
LatBlocks by LatvianModder
LatCoreMC by LatvianModder
LomLib by Lomeli12
Mag Tools by VapourDrive
Malisis Core by Ordinastie
Malisis Doors by Ordinastie
Mantle by mDiyo, progwml6
Matter Overdrive by X_Simeon
Mekanism by aidancbrady
MicdoodleCore by Micdoodle8
MineMenu by dmillerw
MineTweaker by StanH
MmmMmmMmm by boni
Modular Armour by chbachman
NEI Addons by bdew
NEI Integration by Tonius
Not Enough Items by Chickenbones
Not Enough Resources by Way2muchnoise
Obsidiplates by Myrathi
Open Modular Turrets by Poenjabiesous
Open Peripheral Integration by Mikeemoo
OpenBlocks by Mikeemoo
OpenComputers by Sangar
OpenModsLib by Mikeemoo
OpenPeripheral Core by Mikeemoo
Particle Physics by Lunatris
Potion Extension Core by AK
Professor Flaxbeard's Wondrous Steam Power Mod by Flaxbeard
Progressive Automation by Vanhal
QMunitylib by Quetzi
Quantum Flux by jotato
QuiverBow by Domochevsky
Random Things by lumien
Realistic World Gen by ted80
Redstonic by Riazunne
Refined Relocation by Dynious
Resource Loader by Lumien
RF Windmills by Piepenguin
RFTools by McJty
Router Reborn by TomEVoll
Sanguimancy by Tombenpotter
Sanguine Utilities 
Silico
Simple Condensers 
Soul Shards: The Old Ways 
Storage Drawers 
Streams 
Thermal Foundation 
ttCore 
Waila 
Wawla 
XP Teleporters 
Ztones

**Comment by NonQueueingMatt** [comment]
Tested again in a modpack with the 3 mekanism modules and not enough items. Getting the same bug.

**Comment by laz2727** [comment]
This kinda looks like your graphics card cannot render Mekanism properly,
but i might be wrong.
