### ISSUE TITLE
Advanced Universal cables from Mekanism stop transmitting power from Reactor

### ISSUE THREAD

**Issue by adamcogx** [aidancbrady/Mekanism#2762]
I'm not sure if this is a Mekanism issue or not (so I will post it here and at Big Reactors).  I am running a modded-minecraft server (FTB Inifinity with some updates, changes).  The relavent versions are:

Mekanism 8.1.5.238
Big Reactors 0.4.3A

When I disconnect from the server and reconnect, many times the Mekanism cables don't get power from the reactor (they aren't glowing green) and I have to go to the reactor and remove and reconnect the cable to the power tap.  I have 2 reactors in the game, one is connected via basic universal cables and is chunk loaded and doesn't have any issues.  The other is not chunk loaded and uses advanced universal cables (and doesn't work).

**Comment by aidancbrady** [comment]
Yes, this has been reported and is currently a high priority issue, I'm just fairly busy at the moment.  Will be fixed as soon as possible :)
