### ISSUE TITLE
Gas pipes do not show connection state

### ISSUE THREAD

**Issue by scifibob** [aidancbrady/Mekanism#2764]
I haven't tested if the actual flow of gas stops, but when I use the configurator on a gas pipe telling it to disable the connection to another pipe, it don't visually show what's going on.
Most other transport pipes in other plugins have a way of showing whether it's disabled/input/output, etc. but not gas pipes.
It's a pain to use microblocks to separate the pipes, because that's the only thing that helps me to visualize what's going on.

**Comment by aidancbrady** [comment]
Connection states only work on connected acceptors or outputters, not other transmitters (in your case, Pressurized Tubes) - this is the same for cables, pipes and transporters too.

**Comment by scifibob** [comment]
Then in my opinion it's a bug that right clicking with the configurator between pressurized tubes toggles the state. That is, a message about the connection state is logged in the chat.

For a long time I thought it was a bug that the connection state said "NONE", and still, gas was flowing between the pipes.
