### ISSUE TITLE
Server crash with Electro Seperator

### ISSUE THREAD

**Issue by Aphex124** [aidancbrady/Mekanism#2765]
This is from the Horizons Daybreaker pack v1.0.2 but I thought I would post it here also...

Version:
8.1.3

I believe the crash is due to having an Electro Separator with a speed upgrade in it? No idea...

Console Log: http://paste.feed-the-beast.com/view/74494211

Crash Report: http://paste.feed-the-beast.com/view/97a2ad9b

Can it be repeated:
Place speed upgrades in Electro Separator.

Known Fix:
Remove the speed upgrades in an Electro Separator.

**Comment by aidancbrady** [comment]
Fixed in development.
