### ISSUE TITLE
Crash: Redstone Arsenal + NEI + Mekanism

### ISSUE THREAD

**Issue by concertpi** [aidancbrady/Mekanism#2767]
Steps to replicate:

1. Install Redstone Arsenal, NEI, Mekanism core, and their required parent mods.
2. Place down a TE machine (e.g., the Igneous Extruder)
3. Shift-right click on the machine with RA's Flux-Infused OmniWrench (note: using the wrench to rotate the block by right-clicking works fine)
4. The following crash occurs:

java.lang.NoClassDefFoundError: ic2/api/tile/IWrenchable
	at cofh.redstonearsenal.item.tool.ItemWrenchRF.onItemUseFirst(ItemWrenchRF.java:182)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:317)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: ic2.api.tile.IWrenchable
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cofh.redstonearsenal.item.tool.ItemWrenchRF.onItemUseFirst(ItemWrenchRF.java:182)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:317)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['fuserofworlds'/275, l='MpServer', x=217.14, y=65.54, z=274.56]]
	Chunk stats: MultiplayerChunkCache: 622, 622
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (203,64,268), Chunk: (at 11,4,12 in 12,16; contains blocks 192,0,256 to 207,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 43502 game time, 254 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 106 total; [EntityClientPlayerMP['fuserofworlds'/275, l='MpServer', x=217.14, y=65.54, z=274.56], EntityChicken['Chicken'/50, l='MpServer', x=145.41, y=63.00, z=224.41], EntitySkeleton['Skeleton'/52, l='MpServer', x=142.47, y=52.00, z=224.91], EntityEnderman['Enderman'/59, l='MpServer', x=154.31, y=37.00, z=232.50], EntityChicken['Chicken'/60, l='MpServer', x=147.63, y=63.00, z=235.56], EntityCreeper['Creeper'/61, l='MpServer', x=154.06, y=16.00, z=244.38], EntityCow['Cow'/62, l='MpServer', x=149.53, y=64.00, z=261.72], EntityCow['Cow'/66, l='MpServer', x=159.16, y=63.00, z=210.88], EntityCow['Cow'/67, l='MpServer', x=173.16, y=64.00, z=209.94], EntityCow['Cow'/68, l='MpServer', x=163.16, y=64.00, z=221.13], EntityChicken['Chicken'/69, l='MpServer', x=169.53, y=64.00, z=217.53], EntityBat['Bat'/70, l='MpServer', x=165.22, y=56.10, z=234.56], EntityCow['Cow'/71, l='MpServer', x=172.16, y=63.00, z=254.09], EntitySkeleton['Skeleton'/72, l='MpServer', x=162.50, y=52.00, z=240.50], EntitySkeleton['Skeleton'/73, l='MpServer', x=162.50, y=52.00, z=241.50], EntityBat['Bat'/74, l='MpServer', x=188.78, y=53.82, z=247.50], EntityCow['Cow'/75, l='MpServer', x=168.81, y=64.00, z=264.22], EntityCow['Cow'/76, l='MpServer', x=160.03, y=64.00, z=263.09], EntityCow['Cow'/77, l='MpServer', x=169.38, y=64.00, z=261.50], EntitySpider['Spider'/78, l='MpServer', x=173.09, y=17.00, z=298.91], EntityZombie['Zombie'/79, l='MpServer', x=174.69, y=17.00, z=297.31], EntityChicken['Chicken'/80, l='MpServer', x=170.53, y=66.00, z=290.56], EntityChicken['Chicken'/81, l='MpServer', x=167.44, y=66.00, z=297.56], EntitySkeleton['Skeleton'/337, l='MpServer', x=269.50, y=47.00, z=198.50], EntityChicken['Chicken'/87, l='MpServer', x=176.53, y=66.00, z=197.34], EntityChicken['Chicken'/88, l='MpServer', x=176.47, y=65.00, z=200.47], EntityChicken['Chicken'/89, l='MpServer', x=180.25, y=62.49, z=223.16], EntityChicken['Chicken'/90, l='MpServer', x=177.56, y=64.00, z=223.38], EntityCow['Cow'/91, l='MpServer', x=177.84, y=63.00, z=232.94], EntityCreeper['Creeper'/92, l='MpServer', x=183.50, y=23.00, z=251.50], EntityBabySkeleton['Baby Skeleton'/93, l='MpServer', x=191.50, y=53.00, z=246.50], EntityCow['Cow'/94, l='MpServer', x=186.47, y=64.00, z=272.69], EntityCow['Cow'/95, l='MpServer', x=180.47, y=64.00, z=284.16], EntityCow['Cow'/96, l='MpServer', x=181.94, y=68.00, z=288.03], EntityCreeper['Creeper'/97, l='MpServer', x=189.47, y=12.00, z=316.22], EntityZombie['Zombie'/98, l='MpServer', x=183.50, y=12.00, z=307.50], EntitySkeleton['Skeleton'/99, l='MpServer', x=186.50, y=12.00, z=311.50], EntitySkeleton['Skeleton'/100, l='MpServer', x=184.50, y=12.00, z=311.50], EntityItem['item.item.rottenFlesh'/612, l='MpServer', x=195.78, y=61.13, z=224.66], EntitySkeleton['Skeleton'/101, l='MpServer', x=190.09, y=12.00, z=315.38], EntityCow['Cow'/118, l='MpServer', x=192.38, y=64.00, z=228.41], EntityCow['Cow'/119, l='MpServer', x=203.28, y=67.00, z=215.66], EntitySkeleton['Skeleton'/120, l='MpServer', x=193.50, y=58.00, z=235.88], EntityZombie['Zombie'/121, l='MpServer', x=193.06, y=54.00, z=244.50], EntityCow['Cow'/122, l='MpServer', x=198.81, y=63.00, z=249.22], EntityEnderman['Enderman'/123, l='MpServer', x=206.97, y=22.00, z=295.41], EntityChicken['Chicken'/124, l='MpServer', x=202.63, y=70.00, z=304.47], EntityCow['Cow'/125, l='MpServer', x=202.75, y=71.00, z=309.31], EntityCow['Cow'/126, l='MpServer', x=206.09, y=70.00, z=305.03], EntitySquid['Squid'/131, l='MpServer', x=219.03, y=49.38, z=222.19], EntityChicken['Chicken'/132, l='MpServer', x=213.41, y=64.00, z=217.44], EntityCow['Cow'/133, l='MpServer', x=218.97, y=64.00, z=223.13], EntityPig['Pig'/134, l='MpServer', x=219.91, y=66.00, z=211.09], EntityChicken['Chicken'/135, l='MpServer', x=220.47, y=64.00, z=218.47], EntityCow['Cow'/136, l='MpServer', x=217.75, y=64.00, z=224.59], EntityCow['Cow'/137, l='MpServer', x=223.97, y=64.00, z=225.09], EntityCow['Cow'/138, l='MpServer', x=214.75, y=64.00, z=230.31], EntitySkeleton['Skeleton'/139, l='MpServer', x=221.31, y=29.00, z=290.78], EntityCreeper['Creeper'/651, l='MpServer', x=290.50, y=41.00, z=235.50], EntityCow['Cow'/147, l='MpServer', x=229.38, y=65.00, z=203.59], EntityCow['Cow'/148, l='MpServer', x=239.66, y=64.00, z=204.75], EntityPig['Pig'/149, l='MpServer', x=235.06, y=64.00, z=202.94], EntitySkeleton['Skeleton'/150, l='MpServer', x=237.50, y=29.00, z=231.09], EntityZombie['Zombie'/151, l='MpServer', x=229.47, y=32.00, z=287.03], EntityZombie['Zombie'/152, l='MpServer', x=227.47, y=41.00, z=342.94], EntityBat['Bat'/154, l='MpServer', x=228.26, y=42.81, z=352.80], EntityCow['Cow'/166, l='MpServer', x=245.84, y=64.00, z=200.84], EntityPig['Pig'/167, l='MpServer', x=248.53, y=61.00, z=224.75], EntityBat['Bat'/168, l='MpServer', x=252.25, y=13.10, z=229.75], EntityPig['Pig'/169, l='MpServer', x=254.41, y=61.00, z=226.22], EntitySquid['Squid'/170, l='MpServer', x=240.50, y=62.00, z=233.50], EntityCreeper['Creeper'/171, l='MpServer', x=244.00, y=18.00, z=253.41], EntitySkeleton['Skeleton'/172, l='MpServer', x=243.91, y=18.00, z=251.56], EntitySquid['Squid'/173, l='MpServer', x=246.66, y=61.06, z=249.78], EntitySkeleton['Skeleton'/174, l='MpServer', x=243.50, y=51.00, z=243.50], EntityChicken['Chicken'/175, l='MpServer', x=248.44, y=62.35, z=258.56], EntityBat['Bat'/431, l='MpServer', x=223.22, y=19.00, z=274.78], EntitySquid['Squid'/176, l='MpServer', x=249.53, y=62.16, z=261.50], EntityBat['Bat'/432, l='MpServer', x=219.75, y=20.79, z=270.75], EntityBat['Bat'/177, l='MpServer', x=227.58, y=31.19, z=284.50], EntityBat['Bat'/178, l='MpServer', x=226.63, y=34.10, z=288.69], EntityBat['Bat'/434, l='MpServer', x=215.75, y=20.67, z=273.69], EntityBat['Bat'/435, l='MpServer', x=221.47, y=19.95, z=277.59], EntityBat['Bat'/436, l='MpServer', x=224.13, y=20.00, z=275.78], EntityBat['Bat'/190, l='MpServer', x=271.41, y=13.47, z=200.23], EntityBat['Bat'/191, l='MpServer', x=267.25, y=30.10, z=196.13], EntityZombie['Zombie'/195, l='MpServer', x=268.31, y=27.00, z=195.09], EntityCow['Cow'/197, l='MpServer', x=263.94, y=61.00, z=206.03], EntityCow['Cow'/198, l='MpServer', x=261.31, y=61.00, z=215.25], EntityChicken['Chicken'/199, l='MpServer', x=265.47, y=61.00, z=203.63], EntityCow['Cow'/200, l='MpServer', x=279.81, y=64.00, z=229.75], EntityCow['Cow'/201, l='MpServer', x=257.97, y=63.00, z=252.13], EntityCow['Cow'/202, l='MpServer', x=262.03, y=63.00, z=237.06], EntityCow['Cow'/203, l='MpServer', x=265.44, y=68.00, z=254.47], EntityCow['Cow'/204, l='MpServer', x=258.50, y=63.00, z=274.50], EntitySkeleton['Skeleton'/205, l='MpServer', x=269.50, y=34.00, z=339.94], EntitySlime['Slime'/216, l='MpServer', x=281.66, y=30.00, z=200.69], EntityCreeper['Creeper'/217, l='MpServer', x=280.50, y=20.00, z=204.50], EntityCow['Cow'/219, l='MpServer', x=283.78, y=64.00, z=231.19], EntityCow['Cow'/220, l='MpServer', x=285.69, y=64.00, z=226.28], EntitySpider['Spider'/221, l='MpServer', x=284.50, y=15.00, z=255.84], EntityCow['Cow'/222, l='MpServer', x=277.63, y=67.00, z=271.59], EntityZombie['Zombie'/224, l='MpServer', x=296.69, y=21.00, z=196.31], EntityCow['Cow'/226, l='MpServer', x=286.38, y=65.00, z=247.44], EntityCow['Cow'/227, l='MpServer', x=288.47, y=64.00, z=244.84], EntitySkeleton['Skeleton'/228, l='MpServer', x=291.50, y=28.00, z=260.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.9.5
	Java Version: 1.8.0_40, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 256656176 bytes (244 MB) / 773476352 bytes (737 MB) up to 2093809664 bytes (1996 MB)
	JVM Flags: 4 total; -Xmx2G -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -Xmn512M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.130.1395 Minecraft Forge 10.13.3.1395 14 mods loaded, 14 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.130.1395} [Forge Mod Loader] (forge-1.7.10-10.13.3.1395-1710ls.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.3.1395} [Minecraft Forge] (forge-1.7.10-10.13.3.1395-1710ls.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.6.44} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.4.107} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.107-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mekanism{8.1.5} [Mekanism] (Mekanism-1.7.10-8.1.5.246.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	RedstoneArsenal{1.7.10R1.1.0} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0-80.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-8.24.16' Renderer: 'Intel HD Graphics 3000 OpenGL Engine'
	CoFHCore: -[1.7.10]3.0.2-262
	ThermalFoundation: -[1.7.10]1.0.0-81
	ThermalExpansion: -[1.7.10]4.0.1-182
	RedstoneArsenal: -[1.7.10]1.1.0-80
	Launched Version: 1.7.10-Forge10.13.3.1395-1710ls
	LWJGL: 2.9.1
	OpenGL: Intel HD Graphics 3000 OpenGL Engine GL version 2.1 INTEL-8.24.16, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by aidancbrady** [comment]
There seems to be an IC2 API inconsistency somewhere in there.  Try installing the API.
