### ISSUE TITLE
If Ultimate-Universal-Cable is set to pull mode the Throughput is limited to 12,8kRF/t?

### ISSUE THREAD

**Issue by NitroxydeX** [aidancbrady/Mekanism#2769]
Hey Guys,

I don't know if this a issue or if this is what you've really done. When you set UUC to Pull Mode, the Throughput is limited to 12,8kRF/t. When you set it to normal-mode it's like it should act and not limited to 12,8kRF/t.

Hope you can tell me if its really a bug.

**Comment by aidancbrady** [comment]
Not a bug, "pull mode" pulls a designated amount of energy per tick from the source it's connected to (in the ultimate tier's case, 12.8k).
