### ISSUE TITLE
fusion reactor computercraft integration and hohlraum insertion port

### ISSUE THREAD

**Issue by zortag** [aidancbrady/Mekanism#2770]
while automate the hohlraum d-t fuel loading is a piece of cake why not let automate the insertion inside the reactor in a technologic way? add a "hohlraum insertion port" to do it and a robit that take the hohlraum from an electrical chest (both binded to the port with the configurator) and insert it inside the reactor. the binded robit will be recharged directly by the binded chest (you can change the chest graphic aspect in order to be plausible) and the port must be reachable by the robit from the ground. you can add a block to the reactor case to control the robit and bind it to the hohlraum insertion port and the chest.
all the job can be expletated by a computercraft turtle by wrapping the chest and the port and programming its route bethween the 2 blocks. you can add a "hohlraum handler" item equippable by the turtle to turn it in an "hohlraum turtle". this upgrade let the turtle handle the hohlraum, load d-t fuel in it directly from a gas tank and recharge itself from the chest. you have to modify the reactor logic adaptor too to be wrapped to a computer to let program it to automate reactor startup. the port must output if the hohlraum is placed and if fuel is enough to start the reactor. the laser amplifier needs to be wrapped to let the computer to know if it is charged enough to ignite the reactor. obviously, while the turtle can fly, the hohlraum insertion port don't need to be reachable from the ground.

pro:
 -computercraft integration (you can think about opencomputer and pneumaticcraft integration too)
 -full automatable reactor 
 -hi-tech process
 -more things to do
 -robit become more useful
 -computercraft players happyness
bad:
 -hard to do process for the player
 -need of compatibility with another (great) mod

i hope my english was good enough to explain my idea/request
greetings

**Comment by aidancbrady** [comment]
Thanks for the suggestion!  At the moment, you should already be able to automate Hohlraum insertion - Reactor Ports have access to the reactor's inventory.  I do love the idea of using Robits though, maybe I'll save that for another time.
