### ISSUE TITLE
Mekanism fake player identity and functionality unclear

### ISSUE THREAD

**Issue by juniorjunior** [aidancbrady/Mekanism#2771]
The (fairly) recent implementation of a fake/dummy player for the Digital Miner block interactions was explained as being similar to the implementation by BuildCraft. However, BuildCraft reports its fake player information to the FML log during startup like so:
```
BuildCraft's fake player: UUID = 77456a1f-b9f9-3f84-8863-ddef5b8e2209, name = '[BuildCraft]'!
```
It would be quite useful to have this information for the Mekanism fake player.

The commit which implemented this feature shows a fake player name of [Mekanism] with a generated UUID. However, I am unable to find or reference either the name or UUID in the same manner by which the BuildCraft fake player is referenced. Any permissions or tracking plugins I use do not recognize [Mekanism] but do recognize [BuildCraft].

**Comment by spannerman79** [comment]
@aidancbrady Which version of Mekanism was this pushed into?

**Comment by juniorjunior** [comment]
There have been no new Jenkins builds in nearly three weeks.

**Comment by aidancbrady** [comment]
That's because it's currently staged in development.  I'll push out 8.1.6 soon.

**Comment by spannerman79** [comment]
Thanks @aidancbrady greatly appreciated

**Comment by juniorjunior** [comment]
So, the development branch does indeed output the suppsed UUID and fake player name to the config. However, it doesn't act like BuildCraft's fake player. I can't "/op [Mekanism]" as it seems to be unrecognized and is never added to the ops.json file. I'm also unable to see any debug output when checking for block break events using any protection plugins.
