### ISSUE TITLE
Cannot connect pipes/transporters to Purification Chamber

### ISSUE THREAD

**Issue by Halkhan** [aidancbrady/Mekanism#2772]
FTB Horizons Daybreaker 1.0.2
Mekanism-1.7.10-8.1.3.231.jar
MekanismGenerators-1.7.10-8.1.3.231.jar
MekanismTools-1.7.10-8.1.3.231.jar

I have tried on my server instance and in creative:
 - Basic Logistical Transporter
 - Diversion Transporter (with redstone signal)
 - EX Transfer Pipe from a EX Transfer Node (Items)
Oxygen flowing from my Electrolytic Separator flows fine to the Purification Chamber, no matter how "side config" is set up (even with everything set to grey) ;/

 I used a Configurator on any instance using logistical transporters to set transporter from inventory (tried vanilla chest and improved stone chest) as "pull" and transporter touching Purification Chamber as both "push" and "normal" separately.
 I have disabled and enabled Strict Input - using color matching basic logistical transporters (I used black to avoid close color mishaps like the greens so there would be no near color misses)
 With strict input disabled I configured the "Side Config" (Input)to match up with (singularly): Top, bottom, left, right, back, front. Matching Transporter or Transfer Pipe accordingly.
 With strict input disabled I configured all sides simultaneously in the "Side Config" to be "input" and surrounded the Purification chamber in Basic Logistical Transporters.

 Ore and Shards (tried both) will not flow to a Purification Chamber.

 I can successfully feed ore to my Enrichment Chamber with both Basic Logistical Transporters and EX Transfer Node.

 When I use EX Transfer Node I get the message "Searching for Inventories at 0, 0, 0 (point of connection)

**Comment by aidancbrady** [comment]
Update Mekanism, this was a bug :)

**Comment by Halkhan** [comment]
Thanks man and thanks for a great mod pack!
