### ISSUE TITLE
Universal Cable Fails to conect to generators from Extra Utilities

### ISSUE THREAD

**Issue by Angel9001** [aidancbrady/Mekanism#2773]
Universal Cabels is failing to connect to Extra Utilites Generator

Useing the lates version of Both 
Mekanism 8.1.5.246  and Extra Utilites 1.2.6

Tryed to connect other power conduits to the generator and it connected. (Bc kinesis pipes)
but this pipes failed to connect to mekanism machines

I used universial cables to connect this machines befor and it worked

sins other mods seem to be abel to connect to the generator but not mekanism I belive (might be wrong) that the problem lay whit Mekanism

Allso tryed putting a mekanism machine right next to a generator on all sides whitout the generator providing it power...

**Comment by grimallq** [comment]
CofHCore needs to be installed for Mekanism to handle RF
