### ISSUE TITLE
Chemical Injection Chamber Not Auto Ejecting  8.1.3

### ISSUE THREAD

**Issue by defakto** [aidancbrady/Mekanism#2775]
I might be missing something stupid, but I've tried every combination of setting auto-eject to different faces, tubes, etc. 

I cannot get the Chemical Injection Chamber to auto eject shards into mekanism blocks.  I've tried Pull on the logistical tubes. 

I can however get the CIC to output to a chest, but still cannot get a pull of the items out of the chest.

*edit*
I can use the logistical transport to pull items out of a chest, to another chest, but it won't input into a mekanism machine.

**Comment by aidancbrady** [comment]
This is a bug in 8.1.3, update :)

**Comment by defakto** [comment]
Well damn.
