### ISSUE TITLE
Induction Matrix does not output any power

### ISSUE THREAD

**Issue by Curunir** [aidancbrady/Mekanism#2777]
We are using Mekanism 8 in a private modpack that we are currently building and testing. It has been running along quite well, but there is one issue with the new multiblock battery, the Induction Matrix. It will assemble fine and store power, either via Mekanism cabling or using cables from other mods (we mostly use EnderIO). But when we try to get any power back out, it completely refuses to give anything via any port (it does have Induction Providers). It will output power to other batteries that are put into its internal slot, but won't feed the slightest bit into cables or batteries placed next to its ports. We upgraded to version 8.1.5 build 246, but the problem persisted.

I made a few screenshots of a test configuration, available here: http://imgur.com/a/1qDHq

Here is the list of mods included in our pack: http://pastebin.com/0rdXF8d9

If this happens to be just user error, please point out what we are doing wrong. We assumed that the input/output would work mostly like the Dynamic Tank and Solar Evaporation Chamber, which are both working fine in our pack.

**Comment by RAWRwins254** [comment]
Howdy! Question for you: on the induction ports you want to output power, is the light on the port green or red? If it's green you need to shift-right-click on it with a configurator. That will turn on output for that port and turn that small light on the port red.

Veddy

**Comment by RAWRwins254** [comment]
Also, by default the light will be green even if previously red from another matrix deconstruction. If it's the same matrix and you haven't removed the port at all/moved it, iirc it will remain red.

**Comment by Curunir** [comment]
I wasn't even aware of the Configurator. Of course the Port remained green until I used the tool like you described. So user error after all - thanks for pointing it out. I'll close this.

**Comment by vedalken254** [comment]
I'm not one of the developers but no such feature exists in Mekanism as far as I am aware. Your best bet is hooking up a single cube to the port. If it's not being filled, remove the cube and shift-right click on the port with the configurator once if you want it to output from that port. If I remember correctly (you're talking about an issue brought up 3.5 years ago after all), the port is green by default.

**Comment by KickerKerem** [comment]
> Howdy! Question for you: on the induction ports you want to output power, is the light on the port green or red? If it's green you need to shift-right-click on it with a configurator. That will turn on output for that port and turn that small light on the port red.
> 
> Veddy

After I shift-right-click the port doesn't change color. There is still no output

**Comment by vedalken254** [comment]
> > Howdy! Question for you: on the induction ports you want to output power, is the light on the port green or red? If it's green you need to shift-right-click on it with a configurator. That will turn on output for that port and turn that small light on the port red.
> > Veddy
> 
> After I shift-right-click the port doesn't change color. There is still no output

Did you shift-right-click with a configurator in the selected hotbar slot? If not, there's your issue. That being said, I have not kept up with recent changes, this initial issue was opened almost 5 years ago, and changes may have been made. If you are not running Mekanism on 1.7.10 and are experiencing this issue, I recommend opening up a new issue rather than necro'ing a long dead issue. This issue was raised for a version of Mekanism in MC1.7.10.

**Comment by scatter-dev** [comment]
Confirming that shift-right clicking with a Configurator is still the way to fix this in 1.12.2, as described.
