### ISSUE TITLE
Minecart dupe + config request

### ISSUE THREAD

**Issue by yepidoodles** [aidancbrady/Mekanism#2779]
Yesterday, I updated my modpack + server, and I'm finding that every time we place any minecart on a track, the minecart places 2 on the track, and leaves one in your hand. I've tried to recreate it in single player, but have been unable to so far, so I'm not sure exactly what could be causing it, but I noticed that Mekanism added a recipe for tracks, and the player who found the bug, crafted the tracks with that recipe. I understand there's not much you can do with this information as I can not reproduce it, but I felt I must report it nonetheless.

EDIT: We have both Railcraft and Steve's carts in the pack, and none of the minecarts from the mods dupe on the tracks, it's only vanilla carts.

I would also appreciate it if you could add a config option to be able to disable the crafting of the tracks this way, as Railcraft makes crafting tracks much harder, and this just makes Railcraft redundant; but also as it may, somehow, fix my duping issue.

Thank you

Alice

**Comment by Dawnflash** [comment]
You may use MineTweaker to remove the mekanism rail recipes. It's as easy as a little script file serverside.
Also, sometimes items bug out if server-client latency is long enough. Try removing the Mek rails as I suggested. It will balance the modpack and likely fix the issue. This is the common way for tweaking recipe system instead of adding extra config options.

**Comment by aidancbrady** [comment]
Mekanism doesn't actually add any rails, it simply adds a recipe for default Minecraft rail - the issue you're encountering is likely a latency issue as @Dawnflash mentioned.

**Comment by yepidoodles** [comment]
How would I go about removing the recipe? I've tried using Minetweaker, and it doesn't work, it won't even remove the recipe when I try removing all the recipes.

**Comment by Dawnflash** [comment]
It's a vanilla item, literally minecraft:rail.
If you need to get rid of Mek's recipe I recommend something along the lines of
recipes.remove(<minecraft:rail>);
recipes.addShaped(...add your allowed recipes...);
// If you don't like whitelisting recipes anew, you can try
recipes.removeShaped(<minecraft:rail>,[[<Mekanism:Ingot*>,<*>,<*>,<*>][<*>,<*>,<*>][<*>,<*>,<*>,]]);

Play around with MT, you will figure it out.
http://minetweaker3.powerofbytes.com/wiki/Tutorial:Basic_Recipe

**Comment by yepidoodles** [comment]
Using the removeShaped one throws up this error:

https://gyazo.com/c78a728da57eda4f2313e1f00ff17dfa

**Comment by Dawnflash** [comment]
```
recipes.removeShaped(<minecraft:rail>,[[<*>,<*>,<*>],[<*>,<*>,<*>],[<*>,<*>,<*>]]);
```
Here you go, worked for me, should work for you.
