### ISSUE TITLE
Internel Server Error on server connect.

### ISSUE THREAD

**Issue by AnodyneEntity** [aidancbrady/Mekanism#2781]
Hello Aiden, using build 146 of Mekanism seems to cause a Internal Server Error when I try to connect to a private server that me and a few of my friends are playing on. It currently has 176 mods, the log is here;

http://pastebin.com/b7h0hihj

That is the error I get after update Mekanism and a bunch of other mods. Removing Mekanism fixes the issue, and removing about 5-6 mods in place of Mekanism fixes the problem as well. Generally it just depends on how many channels each mod opens up.

**Comment by aidancbrady** [comment]
The log actually states that you have too many packet channels registered - I haven't seen that before, that's funny.  This is not a Melanism-related issue, can be fixed by removing a few network-based mods.

**Comment by NEXUS2345** [comment]
@aidancbrady It looks like it is Spigot as it imposes a hard limit on network channels as seen here: https://hub.spigotmc.org/stash/projects/CHEETAH/repos/spigot/browse/CraftBukkit-Patches/0098-Cap-Channel-Registrations.patch?at=eb638fc322eee8c0f7b38f4497592e1552646fe5

**Comment by aidancbrady** [comment]
Huh, yeah, looks like they cap at half a byte.  With 176 mods that's definitely the reason.
