### ISSUE TITLE
Purification chamber not accepting inputs

### ISSUE THREAD

**Issue by scienceman217** [aidancbrady/Mekanism#2783]
In the screenshots I've attached I have a purification chamber completely surrounded by basic logistical pipes. There is nothing in the inventory, it is full of oxygen, and all sides are set to input mode. I have 62 yellorium shards and 2 iron shards in the chest, and the pipe attached to it is on pull mode. There are no color filters anywhere. I'm not sure what else to do.

**Comment by aidancbrady** [comment]
This is a bug, update to Mekanism 8.1.5.

**Comment by scienceman217** [comment]
wow. quick response. Thanks!
