### ISSUE TITLE
Duplication Bug When Using Version 1.7.10-8.1.3.231 Alongside Router Reborn

### ISSUE THREAD

**Issue by TechnoColt** [aidancbrady/Mekanism#2784]
Hello. I have been playing FTB Horizons: Daybreaker and have encountered a duplication bug when Mekanism interacts with Storage Units from Router Reborn. When any of the Logistical Transport pipes, including the sorter, are used to extract items from a Storage Unit, the items are not extracted, but they *are* added to the destination inventory. One can even loop Logistical Transport pipes into the same Storage Unit to easily duplicate the items infinitely. I tested other transportation methods such as Extra Utilites item transfer nodes, but the glitch only happened with Mekanism pipes. I will also copy this post to the Router Reborn issue tracker, as I do not know which side is causing the bug.

**Comment by aidancbrady** [comment]
Version?

**Comment by ProsperCraft** [comment]
http://youtu.be/49HvxsHBWG4

Came to report it, but already done...here is a video for your viewing pleasure.
