### ISSUE TITLE
Metallurgic infuser automation

### ISSUE THREAD

**Issue by Bulkje** [aidancbrady/Mekanism#2788]

**Comment by Bulkje** [comment]
whoops, didn't mean to post it already, but I have a problem with metallurgic infusers. I have 10 metallurgic infusers in a row behind eachother and have input on the left of the row infusing material on the top and output on the right side. The input and output and infusing material are all connected to chests using Ultimate logistical transporters. The problem is when I input items it only gets to the first 2 metallurgic infusers, not the rest. I think it's weird because the infusing material is being put in the infusers and the products are being output to the chest. Is it a problem with the logistical transporters?
![2015-07-01_15 02 18](https://cloud.githubusercontent.com/assets/13135370/8455075/3d214580-2002-11e5-9505-b8487f3be6bf.png)

**Comment by RAWRwins254** [comment]
Yo. Last I remember, the pipes from a lot of mods use the shortest-path method including Nelson. This means that until the first one fills, none of the others will get anything.

**Comment by RAWRwins254** [comment]
Nelson=Mekanism* didn't notice it til post

**Comment by Bulkje** [comment]
there needs to be a metallurgic infusing factory

**Comment by RAWRwins254** [comment]
I agree.

**Comment by RAWRwins254** [comment]
Hey bulkje:  does your pack have project red in it? If so, you might be able to utilize that to accomplish this task. There is a downside to project red's automation however: each crafting pipe you use can only accommodate one crafting recipe per crafting card inserted into it. You can only use 4 cards Max per pipe.

**Comment by RAWRwins254** [comment]
Last I remember anyways. I'll login to my friend's server shortly and check.

**Comment by RAWRwins254** [comment]
And of course I forgot about the infusing material. That will still need logistical transports

**Comment by Bulkje** [comment]
the infusing material was never the problem, thanks for the suggestion!

**Comment by Bulkje** [comment]
I ended up using a logistical sorter and putting red robin on
