### ISSUE TITLE
Add 3rd/4th tier Solar Panels

### ISSUE THREAD

**Issue by mercsniper** [aidancbrady/Mekanism#2790]
I am working with solar generation and have about 10 advanced generators powering my ender quarry. My problem is trying to bridge the gap between this lower tier power, and getting a reaction chain built for a reactor. Anyway we could add more tiers to the solar panels?

**Comment by aidancbrady** [comment]
I'm looking into some form of power to bridge the gap between low power (wind, solar) and high power (fusion) generation- maybe hydroelectric, maybe small-scale fission.  I'd rather not flesh out tiers for generators, too much work and not very fun

**Comment by mercsniper** [comment]
Thanks for the replay. I appreciate it. If you ever need any assistance, I
wouldn't mind learning Java Programming.

On Mon, Jul 6, 2015 at 2:16 PM, Aidan <notifications@github.com> wrote:

> Closed #2790 <https://github.com/aidancbrady/Mekanism/issues/2790>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aidancbrady/Mekanism/issues/2790#event-348911733>.
>



-- 
Brad
