### ISSUE TITLE
[Suggestion] Mekanic equipments enhancement

### ISSUE THREAD

**Issue by karakufire** [aidancbrady/Mekanism#2794]
Now Mek has some type equipments: Jetpack, Scuba tank and Gas helm, Free runners and more.
They each have each several characteristic features. That's why I favor Mek too.
But I wish their feature get enhance-ablity on the game. In other words I want Mek equipments can modulatable. 
Example, Jetpack allow more boost, gｌiding flight or more speed for horizontal. other example free runners get armor points or sprinting assist.
I thank you for your consideration.

**Comment by RAWRwins254** [comment]
@karakufire to an extent i support what you're looking for. But once that feature goes past just the jetpack, you've lost me. Reika's mods actually give the sort of stuff you're looking for, but at the cost of more expensive mats and stuff. But I agree, the Jetpack should have a glider function that goes faster or slower depending on movement keys (w= faster, s=slower) being pressed. More boost? probably but that runs the risk of destabilizing the balance of the mod itself.

**Comment by aidancbrady** [comment]
I'd rather leave modularization up to a mod like MMPS.  I definitely have plans to add advanced leggings, though, and expect a "gliding" function soon :)
