### ISSUE TITLE
Chemical crystallizer - missing clear button

### ISSUE THREAD

**Issue by ReaLack** [aidancbrady/Mekanism#2795]
At some point, the chemical crystallizer lost the clear button. I don't think this was intended, so here's a bug report, lol. And yeah, I'm stuck... only way to resolve the issue is to build a new one, as it retains the fluid/gas when breaking
![clearbuttonmissing](https://cloud.githubusercontent.com/assets/13164071/8496870/dad96998-2178-11e5-92c7-75df439e5481.jpg)

**Comment by Dawnflash** [comment]
I actually have that button in the latest Mek version...

**Comment by ReaLack** [comment]
Thanks for your comment and help, Dawnflash! Not sure if I'm brave enough to actually try the workaround, lol - I'm op on the server so I'll probably just give me a new crystallizer. :) Hopefully the issue will be fixed on future versions. Really annoying for people without op and/or technical skills.

**Comment by aidancbrady** [comment]
Shift-click the gauge with a gauge dropper, it will clear all its contents :)
