### ISSUE TITLE
[Suggestion] Implement getEnergyStored method for the Laser Amplifier

### ISSUE THREAD

**Issue by ax1m** [aidancbrady/Mekanism#2799]
I'm currently in the process of setting up a fusion reactor, and I'm kinda annoyed that there doesn't seem to be a way to shut off lasers when the amplifier gets fully charged. Would you consider adding a getEnergyStored method to it, so I can get one step closer to a fully CC controlled reactor? Thanks for reading!

**Comment by aidancbrady** [comment]
Added getStored() and getMaxEnergy() methods :)
