### ISSUE TITLE
[Suggestion] Add the ability to remove a recipe in the API

### ISSUE THREAD

**Issue by okyriosy** [aidancbrady/Mekanism#2800]

**Comment by XFactHD** [comment]
I think this is already possible by using IMC messages.

**Comment by okyriosy** [comment]
Unless I'm missreading the IMC handler, there is no way to remove a recipe

**Comment by aidancbrady** [comment]
Done :)

https://github.com/aidancbrady/Mekanism/wiki/IMC-based-recipe-integration
