### ISSUE TITLE
Configurable Mekanism Teleporter Chunkloading

### ISSUE THREAD

**Issue by AuricPolaris** [aidancbrady/Mekanism#2802]
Hello there,

This is more of a request than an issue but the request is to resolve issues with forced chunkloading. Mekanism teleporters currently force chunkload a region and are not configurable (at least to my knowledge). Would it be possible to write a config so that we can disable their forced chunkloading but not disable them completely? This forced chunkloading leads to rather negative chunk churning with other mods such as AE2.

Thank you for your time!

**Comment by aidancbrady** [comment]
The chunk churning you speak of was fixed in a past update. This should hopefully no longer be an issue :)
