### ISSUE TITLE
Brine Production

### ISSUE THREAD

**Issue by SonarSonic** [aidancbrady/Mekanism#2803]
Hey!
I've run into a few problems with brine production.
Often the Solar Evaporation Tower's will get stuck at 300K despite it being day time.
Also brine production is unbalanced in the latest version.

http://i.imgur.com/Z06tpPo.png
I have 30 full size Evaporation towers but I still can't support 5 Elite Factories.

Thanks!
Sonar

**Comment by NitroxydeX** [comment]
Show  a Screen from the Data of the Plants.

**Comment by SonarSonic** [comment]
http://i.imgur.com/lVtFOmN.png

**Comment by mercsniper** [comment]
There is a 0 muliplier. Multiplying production rate by 0 means you get 0 output. The biome your towers are in it bad for producting brine.

**Comment by hehe3301** [comment]
That is something that would be great for the wiki, you should put it up.

**Comment by SonarSonic** [comment]
Nope, the biome is fine. It's in a Normal Minecraft Dessert Biome. I should add this is seen on only some of the towers. I think it seems to be more of a packet problem, as brine is still produced. But considering how many towers I have it still should produce more brine than this. :/

**Comment by mercsniper** [comment]
Multiplier = biomeTemp x (activeSolars / 4) according to the wiki, I would
check the panels and make sure they are powered.

On Tue, Jul 7, 2015 at 1:04 PM, SonarSonic <notifications@github.com> wrote:

> Nope, the biome is fine. It's in a Normal Minecraft Dessert Biome. I
> should add this is seen on only some of the towers. I think it seems to be
> more of a packet problem, as brine is still produced. But considering how
> many towers I have it still should produce more brine than this. :/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aidancbrady/Mekanism/issues/2803#issuecomment-119269566>
> .
>



-- 
Brad

**Comment by NitroxydeX** [comment]
@SonarSonic http://wiki.aidancbrady.com/wiki/Solar_Evaporation_Plant#GUI <- it's in the Wiki...
Maybe try in another Biome?

**Comment by NitroxydeX** [comment]
It's not the Biome... I made a Plant in the Desert. Mult 2.0x... Which Version do you use?

**Comment by mercsniper** [comment]
If the output of the solar generators isnt touching a solar evaporation block, I don't think it is counted in the active solar count. Check and wrench the panels and let me know.

**Comment by NitroxydeX** [comment]
@mercsniper Thats not right. The Solars are not like a energy-source. You just need it. You can output the whole Energy out of the Solars.

**Comment by mercsniper** [comment]
@aidancbrady would this aspect be worthwhile to change?

**Comment by NitroxydeX** [comment]
I thinks the way it works is okay. The Solars heating the Plant up. If Aidan would change this the Plant should also work with alternative energy. So. Let's stay this way.

**Comment by SonarSonic** [comment]
I'll go have a look at the code. It just think it is a sync problem, cause brine is still being produced. I think more should be produced tbh though.

**Comment by mercsniper** [comment]
@SonarSonic , if the multiplier inst being registered, the tower wouldn't be heating up, and then you are losing out on production. See what the code says.

**Comment by SonarSonic** [comment]
Can't spot a problem with the code as such.

**Comment by aidancbrady** [comment]
You can change production rates in the config.  Make sure you're using the latest Mekanism release.
