### ISSUE TITLE
Metalurgic Infuser not accepting input

### ISSUE THREAD

**Issue by mercsniper** [aidancbrady/Mekanism#2812]
Items I have tested with inputing gunpowder:

Export Bus (AE2)
Item Conduit (EnderIO)
Logistical Transport (Mek)

**Comment by grimallq** [comment]
You'll have to show a bit more of your setup. Exact connection points and side configurations for the Infuser.

I've set up an infuser for AE2 autocrafting a few months ago and it's been working without issue through several version updates of both Mek and AE2.

**Comment by aidancbrady** [comment]
I don't think there's a Metallurgic Infuser recipe that uses gunpowder, that may be the issue.
