### ISSUE TITLE
Balloon cord obstructs player view

### ISSUE THREAD

**Issue by EzerArch** [aidancbrady/Mekanism#2814]
From: https://github.com/aidancbrady/Mekanism/issues/2552#issuecomment-113008253

>Thank you, but I think you fixed it a bit "too much". The balloon was lowered so much that it attaches at the player's eyes pos, hindering the view. :)
![2015-06-17_22 41 54](https://cloud.githubusercontent.com/assets/6743303/8222452/15d73e1e-1542-11e5-9f20-b6a6b171c4bd.png)

Semi off-topic: Also, balloons barely lift players from the floor. Intended?

**Comment by aidancbrady** [comment]
Fixed!
