### ISSUE TITLE
Teleportation causes suffocation and poison effect

### ISSUE THREAD

**Issue by itanshi** [aidancbrady/Mekanism#2815]
Now this also happens with op commands. It is on rexxit modpack (I wish I could find a way to report it to them)

I'm not completely sure mekanism is responsible, but using the teleporter caused this here.

Mekanism version 8.1.5.246

**Comment by RAWRwins254** [comment]
@itanshi so the /tp command also gives you suffocation and poison? The suffocation typically indicates a lag problem in my experience, but poison seems like another mod is punishing you for teleporting whether it's via /tp or via Mekanism. I'll take a look ASAP and let you know what I find.

**Comment by RAWRwins254** [comment]
@itanshi based on Rexxit's mod list on technicpack.net, I can't figure out which mod(s) is(are) causing it.

**Comment by RAWRwins254** [comment]
But mekanism doesn't poison you nor do suffocation in any way shape or form, and especially doesn't discriminate against the /tp command as it has no rights to do so. Something else has to be causing it. What that is, however, is unknown to me.

**Comment by itanshi** [comment]
thank you for looking into it

**Comment by aidancbrady** [comment]
Yeah, not on my end.  Strange though!
