### ISSUE TITLE
Splitted factory textures.

### ISSUE THREAD

**Issue by Radviger** [aidancbrady/Mekanism#2819]
Hi, @aidancbrady. Recently I requested you to split MK's factorys textures, but you said that is very hard to do new textures for all factorys. Here is my combined textures for them: https://www.dropbox.com/s/if5xwgnpebg2seg/factorys.zip?dl=1
I really hope that you add them to Mekanism by default. Thanks!

**Comment by aidancbrady** [comment]
Wow, amazing job.  Thank you so much!

**Comment by aidancbrady** [comment]
I have one minor request- would you mind changing the file names to match a "TierTypeFactorySide" structure?  For example, "AdvancedCombiningFactoryFrontOn" instead of "AdvancedFactoryCombiningFrontOn."  Then I'll go ahead and implement your changes :)

**Comment by Radviger** [comment]
Here you go: http://squareland.ru/statuses/upsilon

**Comment by aidancbrady** [comment]
Added!
