### ISSUE TITLE
Mekanism pipes randomly quit working

### ISSUE THREAD

**Issue by MageRoyal** [aidancbrady/Mekanism#2820]
I am running the newest version of Mekanism and all its co-mods. And i am having trouble with all the pipes, pressure/mechanical ect. They jsut randomly quit working and i have to remove them all and place them back down to get them running. They are going to and from mechanism machines. 
My Version Number for Mekanism is 8.1.5.246

**Comment by othermusketeer** [comment]
This is possibly the same as #2806. I am also experiencing this. Network reader shows part of the line of cables/tube as "No Network". Replacing just the junction of Network/No-Network does not fix it. Instead you have to remove the entire No-Network section and replace it. Exists with power, transporter, and gas tubes.

As a temporary solution, and to handle any future problems, it would be nice to have a console command that reinitialize/redefine/rebuild all Mekanism networks. Probaby an OP only command.

**Comment by aidancbrady** [comment]
Yeah, this is the same issue.  Merging with #2806
