### ISSUE TITLE
Error of digital miner on multi-player server

### ISSUE THREAD

**Issue by sjtumc** [aidancbrady/Mekanism#2821]
After updated from Mekanism 8.1.2.229 to 8.1.5.246 on the muti-player server on cauldron-1.7.10-1.1388.1.0, the digital miner no longer dig ore anymore with the same setting, while it still works on individual game of forge 1371.
The digital miner still consume energy and can scan the ores.

**Comment by aidancbrady** [comment]
This should be fixed in development.

**Comment by RAWRwins254** [comment]
@sjtumc a temporary fix until 8.1.6.buildnumber is released is located in #2809. I recommend that if you are unable to wait for 8.1.6, you temporarily download the jars hosted by me at the link posted in the comments. I will repost the link here: http://crius.lksmith.net/mekjars/ <--- NOTE: Those jars will be taken down upon me seeing Aidan has released the true 8.1.6 version which will have additional commits/code changes in it.

**Comment by juniorjunior** [comment]
Something fishy is still up. There seems to be some odd collision or mix-up with fake player UUIDs. My fml-client-latest.log reports the [Mekanism] fake player having a UUID of "46e82cd0-d480-3d48-800a-77431ede078e". If I /op [Mekanism] in the console the ops.json file has "c1fc3ace-e6b2-37ed-a575-03e0d777d7f1" as the UUID for [Mekanism]. If BuildCraft is installed and I /op [BuildCraft] it also puts a UUID of "c1fc3ace-e6b2-37ed-a575-03e0d777d7f1" in the ops.json file for [BuildCraft].

In #2809 someone stated that the dev build of Mek was working for them using Pex/ModifyWorld/etc. I am unable to duplicate that success using RAWRwins254's builds or my own of the current Dev branch.

FML log: http://paste.ubuntu.com/11893959/

**Comment by RAWRwins254** [comment]
@aidancbrady and @unpairedbracket, I'm not that good with java (just starting out), but I think this is a forge issue. Either that or because you guys use the same code for pulling the UUID from a variable, convert to a string, and log it, Forge gets confused. The reason I bring this up is because two completely different /op's for mods are generating the same UUID. I know that the jars are supposed to be kept separate (in terms of code and code functions), but yeah. I think this might be forge. Care to comment?

@juniorjunior what version of forge are you running?

**Comment by juniorjunior** [comment]
This is with Forge 1481.

**Comment by RAWRwins254** [comment]
@juniorjunior i would recommend contacting the kCauldron team. I don't know why but it seems that the UUIDs that are getting recorded in ops.json only include a generic uuid for any mod. I'll continue doing research on this, but that's my recommendation.

**Comment by unpairedbracket** [comment]
(Disclaimer: this is all relating to Forge. I can't find source or anything for KCauldron)

From looking at code, I can't actually work out how it *does* work for BuildCraft. It seems like the FakePlayer is never "registered" or anything similar, so referring to it by name in the Op command can't possibly find the correct GameProfile, as far as I can see. Forge's approach (at least in an offline mode server) is to use the UUID generated from "OfflinePlayer:[Name]". I presume KCauldron does something similar, but with the same name for any unknown player. I've added a command, "/mk op", that ops the correct GameProfile, to our development branch (41492f5d28bd51f3f8a174de3c8224c4f42c984a). Let us know if it works.

**Comment by jcettison** [comment]
Please god explain how I could fix this issue with other mods? I know it's not a Mekanism problem, but this is the only thread I can find that is even discussing the same issue. I have this problem with CoFH, WarpDrive and other mods. 

@unpairedbracket How can I op the correct "gameprofile" manually? I dont care how long it takes, I'll do it. Pleeease take the time to explain to me what's going on here. Is there a .dat I can edit? I've tried adding the UUID to the usercache and usernamecache to no avail.
