### ISSUE TITLE
Elite Injection Factory Bleeding off Gas

### ISSUE THREAD

**Issue by jackelsr** [aidancbrady/Mekanism#2822]
I've added this mod to the latest FTB Infinity version for the server I play on. For some reason the system will bleed out any HCI I have in pipes and gas tanks that are connected to the Elite Injection Factory even if it is not running. If I break the connection the pipes and tanks will fill up. It is doing this with it's own internal storage completely full.

**Comment by jackelsr** [comment]
Toggled Auto eject on and off and it may have fixed the issue, I'll report back if that is the case.

**Comment by aidancbrady** [comment]
Which Mekanism version?

**Comment by jackelsr** [comment]
Latest version, also seems that the issue with sulfuric acid is specific to
the gas tanks output being attached to a pressurized pipe. Attached to a
machine it works as intended.

**Comment by aidancbrady** [comment]
I can't reproduce any of the issues you mentioned, after testing with and without upgrades.  Make sure you don't have "dump" mode enabled on the Gas Tank.
