### ISSUE TITLE
Universal Cable does not connect to Railcraft Steam Engine

### ISSUE THREAD

**Issue by ruifung** [aidancbrady/Mekanism#2825]
Mekanism 8.1.5
Railcraft 9.6.1.0

Although the cables don't connect, and energy doesn't flow into the cable network - all the energy seems to be flowing . Into oblivion.

It does however, work when the engine is directly adjacent to a machine. (And not feeding into a universal cable.)

![2015-07-19_02 01 57](https://cloud.githubusercontent.com/assets/1073945/8762954/7598dd5e-2dba-11e5-9156-1bcef94c3c09.png)

**Comment by unpairedbracket** [comment]
The issue here is due to Railcraft engines only implementing IEnergyConnection, rather than IEnergyProvider. Worked around in dev branch d994f18117c2ac0e44c4b14513a45539a040b5df

**Comment by artturnip** [comment]
Is there any chance of this being merged into the main branch?
