### ISSUE TITLE
Bin Wrenching.

### ISSUE THREAD

**Issue by ruifung** [aidancbrady/Mekanism#2827]
Would it be possible to add a quick deposit function for the bins like JABBA barrels?

Where when you shift + rclick with empty hand it deposits every matching item into the bin.

Also.. are the bin's supposed to be not wrenchable?

**Comment by aidancbrady** [comment]
Right click twice in a row :)

I'll add a check for wrenching.

**Comment by ruifung** [comment]
Oh right lol.

**Comment by aidancbrady** [comment]
Wrenches should now function and not be inserted into bins.

**Comment by ruifung** [comment]
To remove it right? 'Cause the configurator in wrench mode merely rotated it, even when shift wrenching.

**Comment by aidancbrady** [comment]
Right.
