### ISSUE TITLE
[Suggestion] More height floating Balloons with hydrogen gas

### ISSUE THREAD

**Issue by karakufire** [aidancbrady/Mekanism#2828]
balloons enhancement to float heigher: Injecting hydrogen gus, balloon floating height is proportional to amount of hydrogen gas.

**Comment by ruifung** [comment]
And since its hydrogen gas. It should explode! (For science!)

**Comment by EzerArch** [comment]
I'm not sure as to hydrogen, but I'd revamp the balloons completely.

1. There would be possible to attach more than 1 balloon.
2. The more balloons, the higher the entity would float.

Something like this:
![2014-03-14_12 10 59](https://cloud.githubusercontent.com/assets/6743303/8792301/e43c179e-2f3b-11e5-9816-b0af7217fd79.png)
(This is just retextured chickens with leads in low gravity.)

**Comment by karakufire** [comment]
@EzerArch hydrogen is lightest gas(in reality) and Mek can produce. It is why I recommend hydrogen.
(Don't pack hydrogen gas into balloon at real world.)

**Comment by aidancbrady** [comment]
I love the mockup :)

That's actually a really good idea that may not be too far fetched.  Balloons are super fun to develop too.  I feel like it would be possible to do this with a single entity- the hard part would be figuring out how to render a bundle like that.  I'll look into it!

**Comment by aidancbrady** [comment]
For priority reasons I'm going to close this- there's a lot of other things higher on my list than this right now. Once I can get the big features (and porting) out of the way I'll take a look at this again.
