### ISSUE TITLE
Exception in server tick loop from water pump maybe?

### ISSUE THREAD

**Issue by ChrispyBites** [aidancbrady/Mekanism#2830]
This started happening immediately after I added the electric pump.  Like, as soon as I hooked it to power, crash:

http://pastebin.com/xih7Sg9v

- I've tried updating GalactiCraft.
- I've updated Mekanism.

Thanks in advance.

**Comment by aidancbrady** [comment]
Fixed in dev a while ago, expect a release soon :)

**Comment by ChrispyBites** [comment]
You're the man.
