### ISSUE TITLE
Heat Generators doesn't generate the passive amount of energy set in config

### ISSUE THREAD

**Issue by Carbon-Ghost** [aidancbrady/Mekanism#2831]
I set the heatgeneratorpassivegen = 5 ( note that I reconfigured everything so it uses EU and redone conversions and disabled RF ), but in world, the generator generates a certain amount of milliEU/tick but when multiplied by 20, it's far from 5... Using latest Mekanism...

Other generators SOMETIMES also have this behaviour, I was able to do that once with solar panels but I fail to reproduce it for some reasons...

**Comment by aidancbrady** [comment]
This is due to the new Heat Generator heat mechanics- you can bump up heat generation in config.

**Comment by Carbon-Ghost** [comment]
May you explain how it works :o ?
