### ISSUE TITLE
Unsupported HookLoader version error

### ISSUE THREAD

**Issue by cdh0127** [aidancbrady/Mekanism#2833]
Upon trying to load in the MC client once dropping in Mekanism, the client crashes with the error "UnsupportedClassVersionError : mekanism/common/asm/LoadingHook : unsupported major.minor version 51.0"

I have tried multiple versions of Mekanism, including the newest release.

The full client log of the error can be found here: http://pastebin.com/aqsMhN32

**Comment by aidancbrady** [comment]
Update Java.

**Comment by cdh0127** [comment]
I am running Java version 8 update 48…I do believe that is the absolute latest version of Java.

**Comment by aidancbrady** [comment]
You may want to double check that, it seems you have Minecraft running on a Java 6 install.  Check your Minecraft game profile's JVM arguments.

**Comment by cdh0127** [comment]
I’m confused…my system is on Java 8, I have just confirmed. I’m not sure what to put for the JVM arguments.
I’m using the Minecraft vanilla launcher to test a modpack that I am putting together.

**Comment by unpairedbracket** [comment]
I think Apple Java strikes again. Minecraft is for some reason not using the JVM you want it to. Don't know why Apple haven't updated their shipping JVM yet but I'm starting to doubt they ever will.

**Comment by cdh0127** [comment]
Yeah, seems like it.

I’m researching how to manually change the Java version the launcher uses.

**Comment by aidancbrady** [comment]
They never will :(

**Comment by cdh0127** [comment]
I was able to get it working! Thank you!

P.S. sorry about filing a false bug report. I was unaware that regardless I have Java 8 installed, Minecraft was running Java 6.

Keep up the great work on Mekanism! Is there anywhere I can track what you're up to next?

**Comment by aidancbrady** [comment]
Great! No worries, we get that report a lot.

You can keep up with me on Twitter or my website (aidancbrady.com), and I know @unpairedbracket has a (very aesthetically pleasing) site in the works at unpairedbracket.github.io. Glad you like Mekanism :)

**Comment by cdh0127** [comment]
Oh it’s overtaken the spot as my favorite Tech mod for sure!
Can’t wait for the next update!

**Comment by RAWRwins254** [comment]
@aidancbrady and @unpairedbracket just as a heads up that I don't see mentioned here, to get a Mac to properly use Java 8, users NEED the Java 8 JDK, not the JRE. Dunno why exactly this is but that's how it currently works.

**Comment by RAWRwins254** [comment]
Seems to have something to do with minecraft using CLI stuff and the damned apple shipped jre overrides the jre from oracle somehow. You'd think oracle would be suing apple over that.
