### ISSUE TITLE
ERROR: VoiceServer:  Unable to trace connection's IP Address

### ISSUE THREAD

**Issue by FalseTetrabyte** [aidancbrady/Mekanism#2835]
When attempting to join our server with the latest stable release of AE2 installed (rv2-stable-10) the log shows the following error on the server side: 

22.07 10:52:53 [Server] INFO VoiceServer: Accepted new connection.
22.07 10:52:58 [Server] ERROR VoiceServer: Unable to trace connection's IP address.

and then promptly kicks me out with a message in the game that the connection was closed  
I play from work sometimes, and the firewall rules here are restrictive, so there's nothing I can do to change the firewall behavior.  Why is this even a thing?

**Comment by FalseTetrabyte** [comment]
I've looked at the config files as well, and can't locate any way to disable this behavior.

**Comment by aidancbrady** [comment]
Set EnableVoiceServer to false.

**Comment by FalseTetrabyte** [comment]
I apologize... where?  I've looked at both the AE2 cfg as well as server.properties.

**Comment by aidancbrady** [comment]
AE2 is Applied Energistics 2, you want to look in the "mekanism.cfg" file (as this is Mekanism related).

**Comment by FalseTetrabyte** [comment]
Sigh.  I apologize for getting the wires crossed.  Thank you for the help.

**Comment by aidancbrady** [comment]
No worries :)
