### ISSUE TITLE
Updated ru_RU.lang

### ISSUE THREAD

**Issue by Radviger** [aidancbrady/Mekanism#2836]
Hi, @aidancbrady! I found that some Mekanism items are not translated on russian. Here is my translate for them: https://www.dropbox.com/s/esvegg974vpieox/ru_RU.lang?dl=0

**Comment by Radviger** [comment]
Sorry that I don't use git for this things. They are too small I think to pull them as request.

**Comment by aidancbrady** [comment]
Is this pulled from the dev branch or master branch?  We have a few localization changes in the workings.
