### ISSUE TITLE
Mekanism cancels AE2 Recipes

### ISSUE THREAD

**Issue by M4vErw1kiXL** [aidancbrady/Mekanism#2837]
I've done all tests between AE2 and Mekanism-1.7.10-8.1.5.246. I've got a forced downgrade to early versions, because of recipes for AE2

Tests realized with: forge-1.7.10-10.13.4.1448-1.7.10; NotEnoughItems-1.7.10-1.0.3.74; appliedenergistics2-rv2-beta-8; CodeChickenLib-1.7.10-1.1.3.127; ForgeMultipart-1.7.10-1.1.2.331;
CodeChickenCore-1.7.10-1.0.4.29; Mekanism-1.7.10-8.1.5.246; MekanismGenerators-1.7.10-8.1.5.246; MekanismTools-1.7.10-8.1.5.246.

**Comment by ruifung** [comment]
Could you please elaborate? I haven't noticed any such problem.

**Comment by aidancbrady** [comment]
Closing as I'm 99% sure this is not related to me, though I'll still be happy to provide support.

**Comment by XFactHD** [comment]
@M4vErw1kiXL you have to update AE2, this issue has already been fixed a long time ago. The latest version of AE2 is rv2 stable 10.

**Comment by M4vErw1kiXL** [comment]
@XFactHD I did it after i reported.
Just to not happen again, this is here to remember Aidancbrady.
