### ISSUE TITLE
Pressurized Tube and Gas-Burning Generator Bug

### ISSUE THREAD

**Issue by elkendall** [aidancbrady/Mekanism#2842]
If a pressurized tube containing oxygen is connected to a gas-burning generator's input, it will crash the server and corrupt the world save.  I think connecting a pressurized tube containing any gas that the generator does not accept will cause this crash.
Experienced on the FTB Horizons: Daybreaker mod pack version 1.0.2 with Mekanism 8.1.3.231.

**Comment by aidancbrady** [comment]
Update to 8.1.6.
