### ISSUE TITLE
Attuning AE P2P interfaces

### ISSUE THREAD

**Issue by ruifung** [aidancbrady/Mekanism#2843]
I'm not sure if this is a issue on mekanism's side or AE2's side.

Mekanism is registering the itemstack with AE2 via IMC for P2P attunement.
But apparently when I rclick with the transmitter items, it places it down instead.. or adds its multipart part to the block.

**Comment by aidancbrady** [comment]
I have no clue- I've never even messed with attunement before.  Your implementation looked correct, though.

**Comment by ruifung** [comment]
Yeah, I opened a similar issue on the AE2 github to see if they might have any ideas. Either I'm not registering it correctly, or its a multipart thing.

**Comment by ruifung** [comment]
Well damn, FMLInterModComms.sendMessage is returning false, and AE2 doesn't even appear to be receiving the IMC messages. @.@

**Comment by RAWRwins254** [comment]
Rui, y u breaking stuff? :P

**Comment by ruifung** [comment]
I'm breaking stuff?

**Comment by RAWRwins254** [comment]
It was a joke. Sorry.

**Comment by ruifung** [comment]
Huh. I don't get the joke though.. Mind explaining? XD

**Comment by RAWRwins254** [comment]
It had to do with your implementation pr. It didn't work thus my joke came into existence. Typically for me, if you see a ":P" at the end, I'm joking.

**Comment by RAWRwins254** [comment]
Have to make things fun every once in a while... gets too serious otherwise.
