### ISSUE TITLE
ConcurrentModificationException in soundSystem

### ISSUE THREAD

**Issue by ruifung** [aidancbrady/Mekanism#2845]
I was just placing down a bunch of Adv solars when this happened. Its not the first time it happened, and the utter lack of information in the stack trace is leaving me befuddled on where to report this.

And it seems to happen randomly.

http://paste.ee/p/2d9Tm

**Comment by aidancbrady** [comment]
Yeah- it doesn't actually link to Mekanism anywhere.  It may just be one of those corner-case Minecraft issues.  If you somehow trace it directly to me I'll definitely take a closer look.
