### ISSUE TITLE
Request: Sawmill Factories

### ISSUE THREAD

**Issue by MyNameIsKodos** [aidancbrady/Mekanism#2849]
Given the common tree farm's production output, a sawmill factory just  makes sense.  Not to mention after watching a tutorial video on the Logistical Sorter, now more than ever do I want this to be a thing.

**Comment by Utildayael** [comment]
++ to this!

**Comment by sinspawn1024** [comment]
++ Sawmill factory would be very nice, given how much wood is used in crafting all kinds of stuff.

**Comment by MyNameIsKodos** [comment]
If this were to become reality at this point, what is the likelihood of it being a 1.7.10 v9 feature?

**Comment by ThatGamerBlue** [comment]
@MyNameIsKodos 0.01%

**Comment by Utildayael** [comment]
Request was put in literally over a year ago so meh. Was hoping Aidan would toss it in but he made factory versions of a bunch of other stuff instead. Kind of surprised really.

**Comment by MyNameIsKodos** [comment]
Meh alright. I'm just gonna close this. I honestly don't care whether they're added or not if they're not being put into 1.7.10 at least.
