### ISSUE TITLE
[Request] buff Heat Generator

### ISSUE THREAD

**Issue by nintendow131** [aidancbrady/Mekanism#2850]
The Heat Generator is currently useless.
It burns Fuel far too fast for extremly low Energy output (especially compared to other Solid-Fueled Generators).
Also, i never understood why it converts EVERYTHING into Lava?
This is probably a cause of programming (its easier to make one Generator that just burns on Lava by either directly piping or converting other fuel sources).
It is however completly obsolete, as things like the Wind Turbine produce far more Power.
The Heat Generator should produce not only more Power, but also should just burn fuels instead of converting them to Lava.

**Comment by ruifung** [comment]
Well..? It is meant as a very basic generator. Read( the first one you get and move away from as fast as you can )

**Comment by mercsniper** [comment]
Put a stack of would and have it output to an energy cube. The tiers are currently:

Heat -> wind/solar -> advanced solar -> ethylene generator -> fusion



—

**Comment by nintendow131** [comment]
Still other Generators (EIO,TE) are more efficent.
And the Lava conversion still makes no sense in my eyes.

**Comment by ruifung** [comment]
Sure they are more efficient which is probably intended (?)
And the Lava conversion well.. note that a lot of mekanism's machines convert fuel or other solid material into a internal fluidlike system.

**Comment by mercsniper** [comment]
You also can't extract the lava from the generator, so it is just a representation of time remaining on the production of energy. 


—

**Comment by aidancbrady** [comment]
@mercsniper has it right, it represents the internal fuel remaining. You can change the values in the config if you want higher gen rates.
