### ISSUE TITLE
CoFH Core dependency

### ISSUE THREAD

**Issue by Prototik** [aidancbrady/Mekanism#2853]
Mekanism require CoFH core installled for order to use RF, but it's totally wrong. Dependency annotation (like `@Method(modid = "CoFHCore")`) and possible some other parts should migrate to `CoFHCore|energy` api container, so this allow to use RF without CoFHCore installed, for example transport energy from/to Mekanism to/from EnderIO or any other RF mod.

**Comment by aidancbrady** [comment]
This is already reported and planned.
