### ISSUE TITLE
Bug - Teleporter UI is out of order

### ISSUE THREAD

**Issue by Brian-Wuest** [aidancbrady/Mekanism#2854]
![2015-07-25_18 24 20](https://cloud.githubusercontent.com/assets/13502068/8891775/29b61d1a-32fc-11e5-858c-c0051259b69f.png)
When viewing the Teleporter UI, everything seems out of place and I'm not sure why. I made another one and it's still the same issue.

I am running 8.1.6.250. Screen shot attached.

Note: I am running the Horizen's 2 FTB mod pack though I did update it to the latest Mekanism.

**Comment by aidancbrady** [comment]
It seems like you have an out of date resource pack.
