### ISSUE TITLE
Personal protective equipments for Mekanism

### ISSUE THREAD

**Issue by EzerArch** [aidancbrady/Mekanism#2855]
> **Personal protective equipment (PPE)** refers to protective clothing, helmets, goggles, or other garments or equipment designed to protect the wearer's body from injury or infection. The hazards addressed by protective equipment include physical, electrical, heat, chemicals, biohazards, and airborne particulate matter. (https://en.wikipedia.org/wiki/Personal_protective_equipment)

Mekanism has so many radioactive, poisonous and noisy stuff, and there is no working personal safety equipment? Maybe our beloved developers want to slowly kill, poison or drive crazy their devoted players? How so?

Just kidding. There are some ideas to implement PPEs and environmental hazards, pretty much like in those industrial mods:

1. Gas mask would be required within a radius if you dump poisonous gases from gas tanks.

2. Hearing Protection to lower the machinery noise (ref.: [reddit link](https://www.reddit.com/r/feedthebeast/comments/3dc50v/mekanism_aaarrrrggghhhh/))

3. Fire suit for those who are having lots of fun with flamethrowers.

4. Hazmat/radiation shielding suit. Self-explanatory.

And so on.

**Comment by aidancbrady** [comment]
I think I'll add these kinds of features in with the coming MekaSuit, which is currently being discussed in #3108.
