### ISSUE TITLE
Chunks

### ISSUE THREAD

**Issue by lightning02** [aidancbrady/Mekanism#2857]
Matierials and stuff of your mod will generate only in new chunks? Or even in old chunks of my world?
It is valid also for it's addons?

**Comment by ruifung** [comment]
I don't believe Mekanism has retrogen, at least if it did I couldn't find the setting for it.

**Comment by aidancbrady** [comment]
Mekanism does have reteogen- check out "EnableRegeneration" or something like that in the config.
