### ISSUE TITLE
Bin causing crash

### ISSUE THREAD

**Issue by themechman** [aidancbrady/Mekanism#2859]
Rightclicking a bin with an empty hand causes Internal server error and boots client from SMP. Server remains active and client can rejoin.

Latest build - 8.1.6-249

*EDIT*
So long as you have something in your hand, everything is happy.
Leftclick with empty hand also kosher

**Comment by ruifung** [comment]
its already been fixed in dev. You can download a build that i compiled with the fix in #2844 .

**Comment by themechman** [comment]
Awesome. Thanks
