### ISSUE TITLE
Request: Button to dump conten of the Chemical infuser

### ISSUE THREAD

**Issue by krismoellegaard** [aidancbrady/Mekanism#2860]
i was playing araund with teh chemical infuser and got the worong stuffi n 1 of tha tank and i for the love of somthing cuten get it to dump the gass i tryed braking it wit ha pick and wrentch but it still contanind the dam gas so i endet up making a new one os my question is is it posebul to get a dump button for both tanks so if the right is wron you cli kthe right button and it dum the conten

**Comment by Kodos-Atoz** [comment]
You can use a Gauge Dropper to empty the tanks.
