### ISSUE TITLE
Bug - Fluids duplication with dynamic tank and drums from extrautilities

### ISSUE THREAD

**Issue by dydy7210** [aidancbrady/Mekanism#2861]
Hello, I  think I've found a duplication bug in mekanism(8.1.6.249). 
When I put an filled lava drum in a dynamic tank, the dynamic tank is filled with 256 buckets of lava.
If a take two empty drums(from extrautilities) and I put them in the slot of the dynamic tank , the tank will fill both drums, so the tank gives 512 buckets of lava, instead of 256 buckets.
See the attached image
![duplication](https://cloud.githubusercontent.com/assets/13509761/8894960/398792c8-33c9-11e5-8310-c7216b55563a.png)
.

**Comment by spannerman79** [comment]
@dydy7210 Update to 8.1.7.252 and test again

**Comment by dydy7210** [comment]
@spannerman79 , Hello, the bug is always present in Mekanism 8.1.7.252.

**Comment by spannerman79** [comment]
Does this happen with the Multiblock tank from [Pressure Pipes](http://bdew.net/pressure/multiblock-tanks/)? (ExtraUtilities and Pressure Pipes)

If the answer is yes then its an issue with Extra Utilities and the issue should be brought up with that mod dev and this issue closed.

**Comment by dydy7210** [comment]
I will try this afternoon.

**Comment by dydy7210** [comment]
Hello, @aidancbrady , what do you think about this ?

**Comment by ruifung** [comment]
This should be relatively easy to fix by only allowing one single item in the slot.

**Comment by aidancbrady** [comment]
Fixed! Forgot to check for differing NBT data.

**Comment by spannerman79** [comment]
:+1: Thanks @aidancbrady
