### ISSUE TITLE
Render glitch on Energy Cubes

### ISSUE THREAD

**Issue by TechnicianLP** [aidancbrady/Mekanism#2862]
if theres more than one Energy Cube of anyTier rendered on the Screen all but one Cube get really light and seethrough

**Comment by aidancbrady** [comment]
This is likely due to another mod you have that is interfering with default rendering as I can't reproduce the issue.  Let me know if you get it sorted out!

**Comment by TechnicianLP** [comment]
wouldnt it then have to be rendered on screen? apart from the cubes theres only grass
