### ISSUE TITLE
Suggestion: Better Sneaky Pipe Interactivity For Blocks

### ISSUE THREAD

**Issue by RoloEdits** [aidancbrady/Mekanism#2863]
I automate with Steve's factory manager and right now i have to have the inventory cable touching more than one side to get stuff in and out.Could you make it to where I can access blocks from one side?

**Comment by RAWRwins254** [comment]
So with how mekanism is currently coded, this would require a pretty significant rewrite as pipes from Mek were designed to be just in or out, not both. http://wiki.aidancbrady.com/wiki/Logistical_Transporter

**Comment by RoloEdits** [comment]
I meant with the blocks like the energized smelter, not add sneaky pipe functionality for the mek pipes. My goal with this suggestion is to be able to access all slots in the blocks from one side for a more sleeker and more compact automation setup with Steve's Factory Manager.

**Comment by RAWRwins254** [comment]
Oh now I get what you meant. You want machines to allow input and output to be on the same side.

**Comment by RAWRwins254** [comment]
You might want to update the title because as it's written, it looks as though you're talking about mek pipes instead of mek machines.

**Comment by RoloEdits** [comment]
Thanks, after reading it again from your point of view, I can see how someone would misunderstand what I wrote.

**Comment by Utildayael** [comment]
That would be a really nice addition using EnderIO pipes as well. ++

**Comment by RoloEdits** [comment]
yes ender io pipes would also be extremely useful

**Comment by aidancbrady** [comment]
I'm afraid that this would still require a good bit of work, and likely clutter the already-complex block side configuration system. I'll see about doing something like this later on if I have time.
