### ISSUE TITLE
Performance Issues w/ Mekanism Machines

### ISSUE THREAD

**Issue by catzs** [aidancbrady/Mekanism#2867]
According to Opis, Mekanism machines have a pretty high tick rate on the server, perhaps look at TE's code to reduce lag?

**Comment by ruifung** [comment]
What version of mekanism?

**Comment by catzs** [comment]
8.1.3.231

**Comment by catzs** [comment]
Mekanism Lag Test, All Setup, Opis
![mekanism lag test all setup opis](https://cloud.githubusercontent.com/assets/12586946/8946950/43fbd142-3563-11e5-87e7-953012362e38.png)

**Comment by catzs** [comment]
Mekanism Lag Test, All Setup, TPS
![mekanism lag test all setup tps](https://cloud.githubusercontent.com/assets/12586946/8946963/56e80924-3563-11e5-9c61-cc933f22e6ed.png)

**Comment by catzs** [comment]
Mekanism Lag Test, Mekanism Setup, Opis
![mekanism lag test mekanism setup opis](https://cloud.githubusercontent.com/assets/12586946/8946968/72b826d4-3563-11e5-8c6a-a1c658fdfc36.png)

**Comment by catzs** [comment]
Mekanism Lag Test, Mekanism Setup, TPS
![mekanism lag test mekanism setup tps](https://cloud.githubusercontent.com/assets/12586946/8946976/838c2c9e-3563-11e5-8ed1-da99c8a2118b.png)

**Comment by catzs** [comment]
Mekanism Lag Test, XU Setup, Opis
![mekanism lag test xu setup opis](https://cloud.githubusercontent.com/assets/12586946/8946979/8b6f855a-3563-11e5-8e32-c97839f9ddd0.png)

**Comment by catzs** [comment]
Mekanism Lag Test, XU Setup, TPS
![mekanism lag test xu setup tps](https://cloud.githubusercontent.com/assets/12586946/8946981/975ed730-3563-11e5-9eae-69c32cdeb886.png)

**Comment by catzs** [comment]
Mekanism Setup- Means Mekanism machines were placed
XU Setup- Means Extra Utilities pipes/nodes were placed
All Setup- Means Mekanism & XU items were placed
TPS was obtained from /cofh tps
MobiusCore & Opis are version 1.2.5
The reason that the XU nodes seemed to cause a bit more lag is that it was 7-10 transfer nodes with 4 stacks of world interaction upgrades making cobble, and 1 stack of speed upgrades.
The Mekanism machines had no speed upgrades, and were processing gold ore.
This was in a creative test flat world, so performance on a real world would be much more drastic.

**Comment by spannerman79** [comment]
@catzs you do relise [those](https://github.com/aidancbrady/Mekanism/issues/2867#issuecomment-125785528) numbers are actually micro seconds, even smaller then milliseconds - hence the symbol of μs

1 millisecond = 1000 μs

There is 20 ticks to a second so 1 tick = 5 seconds.
5 seconds = **5,000,000μs** - 5 million μs per tick.

**Comment by unpairedbracket** [comment]
@spannerman79 Something's gone wrong with either your maths or your typing there. By that maths 1 second = 20 ticks = 20 * (5 seconds) = 100 seconds :p

A tick is 50ms, which is 50,000μs. Still a lot of μs, but not quite 5 million.

Anyway, I note that the worst Mekanism machine for tick time is an Elite Factory - To be expected, as it's effectively 7 machines working concurrently. Speed upgrades should have no effect on tick time. Looking at that profile, I see no real reason to believe Mekanism is significantly less server-friendly than ExtraUtilities, which I'm pretty happy with as I know server-friendliness is a priority for XU.

**Comment by spannerman79** [comment]
Err re read as I did update my comment @unpairedbracket

**Comment by unpairedbracket** [comment]
Oh sorry, seems I didn't refresh quickly enough.

**Comment by spannerman79** [comment]
its ok @unpairedbracket,  the moment i hit Comment i had a Homer moment - _duh!_ lol

@catzs 23.514μs for a single tile that in essence 7 factories working at once is _very_ good.  Much better then having 7 furnaces with hoppers and chests setup via vanilla method

**Comment by utoc** [comment]
Chiming in on this as well, I have a large server with several in-game users with about 360 elite factories going.. they are VERY tick friendly.

**Comment by RAWRwins254** [comment]
I can also confirm that this is nothing. Try having 8.1.1.228 with one mekanism fanatic consuming across his base area chunks over 200k microseconds... that's 4 ticks in update time. That was an absolute bitch... Especially as it was mainly coming from dynamic tanks that we couldn't afford to get rid of.

**Comment by aidancbrady** [comment]
Those tick times look very okay.  I wouldn't call this an issue.
