### ISSUE TITLE
Logistical Sorter does not sort properly when placed on a Mekanism machine.

### ISSUE THREAD

**Issue by ruifung** [aidancbrady/Mekanism#2870]
For example. if placed on a factory to sort all its output, the Logistical Sorter does not sort at all, unless Auto Output is checked, it does not even output any items. And when auto output is checked - it outputs unsorted items.

**Comment by unpairedbracket** [comment]
Damn. I'll investigate.

**Comment by ruifung** [comment]
That being said, 8.1.6 is a somewhat buggy release.

**Comment by unpairedbracket** [comment]
I was passing the facing side to the searcher, rather than the back side. Fixed in development, I'll push this fix to master as soon as possible.

**Comment by ruifung** [comment]
Which was why it only broke for inventories which check sidedness?

**Comment by unpairedbracket** [comment]
Exactly. And the code block that handles auto-outputting didn't have this issue, so that's why that worked.

**Comment by ruifung** [comment]
well... yeah because the transporters facing direction would have been the opposite.

Anyway 8.1.7 should probably be moved to recommended. Given the bugs in the currently recommended version.

**Comment by unpairedbracket** [comment]
I agree. @aidancbrady will have to handle that though, recommending builds is out of my hands

**Comment by aidancbrady** [comment]
Recommended has been updated.
