### ISSUE TITLE
Feature Request: More Config Options

### ISSUE THREAD

**Issue by Utildayael** [aidancbrady/Mekanism#2871]
I have a [small] enhancement request. While I love that I can disable recipes in the config, I'm finding I can't seem to disable things like the Jetpack?

I keep wanting to use this on a server I'm on but the op requests no flight which means no Mekanism. [ok technically it means no Mekanism Tools mod] :)

Effectively this would be adding to the config much like how you broke out machines to enable/disable.

IE:

machines {
    B:ChargepadEnabled=true

Thanks and keep up the great work! :)

**Comment by Mementh** [comment]
all your admin has to do is disable that one recipie in the options.. minetweaker or such?

**Comment by aidancbrady** [comment]
Yeah, I'd prefer to leave item disabling up to things like MineTweaker.
