### ISSUE TITLE
Request: crafting machine

### ISSUE THREAD

**Issue by rdunham3** [aidancbrady/Mekanism#2872]
Sort of like the auto-crafting capability of the [Steve's Workshop mod](http://www.curse.com/mc-mods/minecraft/223173-steves-workshop) but powered by Mekanism energy, using Mekanism's machine upgrades and with Mekanism's input/output methods.
* Ability to top off internal storage with like items from connected inventory.  (maybe use the internal storage like a filter so only added quantity of stacks of things already on-board or things in the specified recipe are allowed to enter?)
* Ability to take liquid from connected liquid pipe instead of "bucket of water" or "bucket of lava" as called for by recipes.  Would still use the "bucket of _______" item to specify the recipe, but the machine would know to take equivalent liquid from an available pipe rather than empty the bucket.
* Ability to make user-specified number of specified recipe or tell it to make as many as internally stored supplies allow.

I'd suggest each be able to craft a single recipe at once due to the sheer size the UI would have to be for multiple (factory) recipes.  It would be fine to have to chain several of these together to create complicated items like advanced solar generators.

**Comment by aidancbrady** [comment]
Merging with #3081
