### ISSUE TITLE
Crash - Solar evaporation controller

### ISSUE THREAD

**Issue by Dradeliomecus** [aidancbrady/Mekanism#2873]
Hi,

I am playing on Minecraft 1.7.10 with a bunch of mods (106), and I am using Mekanism, MekanismTools and MekanismGenerators v8.1.7.252.

I have a reactor to create a lot of energy, but my solar evaporation tower to create lithium from brine is too small, so I removed the 4 advanced solar generator to make the tower taller, and then when I right click on the solar evaporation controller, my game crashes with an ArithmeticException (division by 0).
I quit mineraft and come back but the bug is still there

Here is the crash report :

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 30/07/15 10:14
Description: Rendering screen

java.lang.ArithmeticException: / by zero
	at mekanism.client.gui.element.GuiFluidGauge.getScaledLevel(GuiFluidGauge.java:85)
	at mekanism.client.gui.element.GuiGauge.renderScale(GuiGauge.java:76)
	at mekanism.client.gui.element.GuiGauge.renderBackground(GuiGauge.java:68)
	at mekanism.client.gui.GuiMekanism.func_146976_a(GuiMekanism.java:161)
	at mekanism.client.gui.GuiSolarEvaporationController.func_146976_a(GuiSolarEvaporationController.java:131)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mekanism.client.gui.element.GuiFluidGauge.getScaledLevel(GuiFluidGauge.java:85)
	at mekanism.client.gui.element.GuiGauge.renderScale(GuiGauge.java:76)
	at mekanism.client.gui.element.GuiGauge.renderBackground(GuiGauge.java:68)
	at mekanism.client.gui.GuiMekanism.func_146976_a(GuiMekanism.java:161)
	at mekanism.client.gui.GuiSolarEvaporationController.func_146976_a(GuiSolarEvaporationController.java:131)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)

-- Screen render details --
Details:
	Screen name: mekanism.client.gui.GuiSolarEvaporationController
	Mouse location: Scaled: (240, 127). Absolute: (960, 508)
	Screen size: Scaled: (480, 255). Absolute: (1920, 1017). Scale factor of 4

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['Dradeliomecus'/286, l='MpServer', x=-1,30, y=75,95, z=323,12]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-230,64,215), Chunk: (at 10,4,7 in -15,13; contains blocks -240,0,208 to -225,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 6601518 game time, 3865 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 82 total; [EntityZombie['Zombie'/260, l='MpServer', x=34,70, y=27,63, z=405,27], EntityBat['Bat'/261, l='MpServer', x=27,98, y=33,76, z=368,80], EntityZombie['Zombie'/263, l='MpServer', x=12,69, y=35,00, z=379,31], EntityCreeper['Creeper'/264, l='MpServer', x=12,50, y=40,00, z=382,50], EntityBat['Bat'/265, l='MpServer', x=8,18, y=34,04, z=369,35], EntityCreeper['Creeper'/266, l='MpServer', x=15,50, y=38,00, z=390,50], EntityCreeper['Creeper'/270, l='MpServer', x=73,56, y=42,00, z=308,06], EntitySheep['Sheep'/271, l='MpServer', x=75,22, y=63,00, z=290,66], EntityZombie['Zombie'/272, l='MpServer', x=67,16, y=48,00, z=295,16], EntityCreeper['Creeper'/273, l='MpServer', x=64,50, y=48,00, z=288,69], EntitySkeleton['Skeleton'/274, l='MpServer', x=25,50, y=41,00, z=388,50], EntityCreeper['Creeper'/275, l='MpServer', x=25,50, y=46,00, z=392,50], EntityBat['Bat'/276, l='MpServer', x=21,75, y=40,81, z=387,79], EntityZombie['Zombie'/277, l='MpServer', x=40,53, y=30,00, z=389,84], EntityCreeper['Creeper'/405, l='MpServer', x=-14,88, y=29,00, z=363,72], EntityZombie['Zombie'/278, l='MpServer', x=-20,30, y=11,00, z=311,70], EntityItem['item.item.feather'/279, l='MpServer', x=-20,66, y=17,13, z=309,13], EntityZombie['Zombie'/280, l='MpServer', x=-16,84, y=44,81, z=320,69], EntityCreeper['Creeper'/281, l='MpServer', x=-23,78, y=46,00, z=317,56], EntitySkeleton['Skeleton'/29, l='MpServer', x=5,50, y=36,00, z=339,50], EntityItem['item.item.bone'/30, l='MpServer', x=-7,66, y=36,13, z=347,31], EntityBat['Bat'/670, l='MpServer', x=-25,56, y=56,10, z=296,47], GCEntityClientPlayerMP['Dradeliomecus'/286, l='MpServer', x=-1,30, y=75,95, z=323,12], EntitySkeleton['Skeleton'/31, l='MpServer', x=-20,96, y=34,00, z=338,63], EntityZombie['Zombie'/288, l='MpServer', x=-15,31, y=32,00, z=338,66], EntityBat['Bat'/32, l='MpServer', x=-5,25, y=35,10, z=335,06], EntitySkeleton['Skeleton'/289, l='MpServer', x=-15,88, y=32,00, z=337,63], EntityZombie['Zombie'/33, l='MpServer', x=-17,16, y=28,00, z=324,69], EntitySkeleton['Skeleton'/290, l='MpServer', x=-20,00, y=35,00, z=332,14], EntityZombie['Zombie'/34, l='MpServer', x=-19,22, y=27,00, z=328,25], EntityZombie['Zombie'/291, l='MpServer', x=-11,41, y=53,00, z=299,00], EntityZombie['Zombie'/35, l='MpServer', x=-12,88, y=28,00, z=336,44], EntityCreeper['Creeper'/292, l='MpServer', x=-11,44, y=54,00, z=298,00], EntityZombie['Zombie'/36, l='MpServer', x=-11,31, y=46,00, z=317,31], EntityZombie['Zombie'/293, l='MpServer', x=-14,03, y=53,00, z=299,53], EntitySpider['Spider'/37, l='MpServer', x=-8,25, y=51,32, z=306,00], EntityBat['Bat'/294, l='MpServer', x=-24,75, y=28,10, z=359,06], EntityZombie['Zombie'/38, l='MpServer', x=-9,38, y=48,00, z=318,36], EntityZombie['Zombie'/295, l='MpServer', x=-26,31, y=56,00, z=293,70], EntityBat['Bat'/39, l='MpServer', x=4,50, y=53,00, z=314,28], EntityBat['Bat'/296, l='MpServer', x=10,59, y=36,31, z=296,89], EntityItem['item.item.string'/40, l='MpServer', x=1,94, y=44,13, z=306,03], EntitySkeleton['Skeleton'/297, l='MpServer', x=10,34, y=31,00, z=300,13], EntityZombie['Zombie'/41, l='MpServer', x=8,10, y=41,00, z=305,38], EntityTier1Rocket['Tier 1 Rocket'/298, l='MpServer', x=20,50, y=84,90, z=301,50], EntitySpider['Spider'/42, l='MpServer', x=2,40, y=48,01, z=314,72], EntityItem['item.item.bone'/299, l='MpServer', x=-27,34, y=40,13, z=371,88], EntityZombie['Zombie'/43, l='MpServer', x=-10,20, y=48,00, z=318,55], EntityZombie['Zombie'/300, l='MpServer', x=-12,94, y=52,00, z=379,47], EntityZombie['Zombie'/44, l='MpServer', x=-12,44, y=45,00, z=318,00], EntityZombie['Zombie'/301, l='MpServer', x=-7,00, y=11,00, z=270,56], EntityXPOrb['Experience Orb'/45, l='MpServer', x=46,00, y=34,60, z=315,44], EntityZombie['Zombie'/302, l='MpServer', x=-3,44, y=24,00, z=395,59], EntityCreeper['Creeper'/46, l='MpServer', x=46,00, y=33,00, z=315,44], EntitySkeleton['Skeleton'/303, l='MpServer', x=-28,53, y=31,00, z=391,06], EntityCreeper['Creeper'/47, l='MpServer', x=49,22, y=32,00, z=311,66], EntitySkeleton['Skeleton'/304, l='MpServer', x=-11,94, y=33,00, z=392,53], EntitySpider['Spider'/48, l='MpServer', x=48,97, y=32,00, z=308,00], EntitySkeleton['Skeleton'/305, l='MpServer', x=-18,63, y=26,00, z=400,63], EntitySpider['Spider'/306, l='MpServer', x=-22,81, y=29,00, z=395,19], EntityZombie['Zombie'/307, l='MpServer', x=-16,84, y=28,00, z=396,41], EntityZombie['Zombie'/308, l='MpServer', x=-20,94, y=29,00, z=395,44], EntityZombie['Zombie'/309, l='MpServer', x=-22,03, y=29,00, z=397,38], EntityZombie['Zombie'/310, l='MpServer', x=-30,78, y=30,00, z=390,00], EntityZombie['Zombie'/311, l='MpServer', x=-29,59, y=30,00, z=389,69], EntityBat['Bat'/312, l='MpServer', x=-29,58, y=57,00, z=395,03], EntityZombie['Zombie'/313, l='MpServer', x=46,53, y=29,20, z=283,64], EntityZombie['Zombie'/314, l='MpServer', x=48,34, y=31,00, z=278,56], EntitySquid['Squid'/315, l='MpServer', x=60,50, y=61,00, z=277,03], EntityItem['item.item.dyePowder.black'/316, l='MpServer', x=58,06, y=61,13, z=272,91], EntityCreeper['Creeper'/320, l='MpServer', x=9,50, y=47,00, z=246,50], EntityZombie['Zombie'/11073, l='MpServer', x=34,50, y=70,00, z=381,50], EntitySquid['Squid'/326, l='MpServer', x=59,34, y=60,31, z=269,09], EntityBat['Bat'/217, l='MpServer', x=-61,88, y=14,59, z=281,55], EntityBat['Bat'/731, l='MpServer', x=20,56, y=40,25, z=384,23], EntityCreeper['Creeper'/220, l='MpServer', x=-49,00, y=15,00, z=277,41], EntitySkeleton['Skeleton'/221, l='MpServer', x=-53,59, y=47,00, z=312,09], EntityBat['Bat'/223, l='MpServer', x=-27,51, y=21,12, z=303,68], EntityZombie['Zombie'/224, l='MpServer', x=-46,56, y=60,00, z=331,00], EntityZombie['Zombie'/225, l='MpServer', x=-39,25, y=26,00, z=367,50], EntityZombie['Zombie'/226, l='MpServer', x=-37,03, y=26,00, z=370,41], EntityBat['Bat'/740, l='MpServer', x=-21,97, y=21,10, z=300,03]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1007272680 bytes (960 MB) / 2207637504 bytes (2105 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 106 mods loaded, 106 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.4.107} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.107-universal.jar) 
	UCHIJAAAA	OpenModsCore{0.7.3} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	cuchaz.ships.core{1.7.10-1.0.3} [Ships Mod Core] (minecraft.jar) 
	UCHIJAAAA	debug{1.0} [debug] (denseores-1.6.2.jar) 
	UCHIJAAAA	IC2{2.2.726-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.726-experimental.jar) 
	UCHIJAAAA	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) 
	UCHIJAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAA	asielib{0.2.7} [asielib] (AsieLib-1.7.10.zip) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	BiblioCraft{1.8.2} [BiblioCraft] (BiblioCraft[v1.8.2][MC1.7.10].jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJAAAA	qmunitylib{1.0} [QmunityLib] (QmunityLib-1.7.10-0.1.69-universal.jar) 
	UCHIJAAAA	bluepower{0.2.835} [Blue Power] (BluePower-1.7.10-0.2.835-universal.jar) 
	UCHIJAAAA	Botania{r1.7-208} [Botania] (Botania r1.7-208.jar) 
	UCHIJAAAA	BuildCraft|Core{6.4.16} [BuildCraft] (buildcraft-6.4.16.jar) 
	UCHIJAAAA	BuildCraft|Builders{6.4.16} [BC Builders] (buildcraft-6.4.16.jar) 
	UCHIJAAAA	BuildCraft|Energy{6.4.16} [BC Energy] (buildcraft-6.4.16.jar) 
	UCHIJAAAA	BuildCraft|Factory{6.4.16} [BC Factory] (buildcraft-6.4.16.jar) 
	UCHIJAAAA	BuildCraft|Transport{6.4.16} [BC Transport] (buildcraft-6.4.16.jar) 
	UCHIJAAAA	BuildCraft|Silicon{6.4.16} [BC Silicon] (buildcraft-6.4.16.jar) 
	UCHIJAAAA	BuildCraft|Compat{6.4.0} [BuildCraft Compat] (buildcraft-compat-6.4.2.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) 
	UCHIJAAAA	Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	chisel{2.4.1.40} [Chisel 2] (Chisel2-2.4.1.40.jar) 
	UCHIJAAAA	ctmlib{1.0.1.5} [CTMLib] (Chisel2-2.4.1.40.jar) 
	UCHIJAAAA	ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) 
	UCHIJAAAA	DraconicEvolution{1.0.1c} [Draconic Evolution] (Draconic-Evolution-1.7.10-1.0.1c.jar) 
	UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.11} [Galacticraft Core] (GalacticraftCore-1.7-3.0.11.333.jar) 
	UCHIJAAAA	Mekanism{8.1.7} [Mekanism] (Mekanism-1.7.10-8.1.7.252.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	extracells{2.2.23} [ExtraCells] (ExtraCells-1.7.10-2.2.23b43.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.9} [Extra Utilities] (extrautilities-1.2.9.jar) 
	UCHIJAAAA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJAAAA	fastleafdecay{1.0} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.0.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.11} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.11.333.jar) 
	UCHIJAAAA	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar) 
	UCHIJAAAA	IC2NuclearControl{2.2.5a-GoingForTheKill} [Nuclear Control 2] (IC2NuclearControl-2.2.5a-GoingForTheKill.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	iridiummod{0.7} [Iridium Mod] (iridiummod-1.7-0.7.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	journeymap{@JMVERSION@} [JourneyMap] (journeymap-1.7.10-5.1.0-unlimited.jar) 
	UCHIJAAAA	MekanismGenerators{8.1.7} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.7.252.jar) 
	UCHIJAAAA	MekanismTools{8.1.7} [MekanismTools] (MekanismTools-1.7.10-8.1.7.252.jar) 
	UCHIJAAAA	Metallurgy{4.0.5} [Metallurgy 4] (Metallurgy-1.7.10-4.0.5.75.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	numina{0.4.0.100} [Numina] (Numina-Mod-1.7.10.jar) 
	UCHIJAAAA	powersuits{0.11.0.178} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.178.jar) 
	UCHIJAAAA	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJAAAA	NEIAddons{1.12.8.30} [NEI Addons] (neiaddons-1.12.8.30-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.8.30} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.8.30-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.8.30} [NEI Addons: Botany] (neiaddons-1.12.8.30-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.8.30} [NEI Addons: Forestry] (neiaddons-1.12.8.30-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.8.30} [NEI Addons: Crafting Tables] (neiaddons-1.12.8.30-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.8.30} [NEI Addons: Ex Nihilo] (neiaddons-1.12.8.30-mc1.7.10.jar) 
	UCHIJAAAA	neiintegration{1.0.9} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.9.jar) 
	UCHIJAAAA	notenoughkeys{@MOD_VERSION@} [NotEnoughKEys] (NotEnoughKeys-1.7.10-1.0.0b29.jar) 
	UCHIJAAAA	neresources{0.1.0.95} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0.95.jar) 
	UCHIJAAAA	ObsidiPlates{3.0.0.18} [ObsidiPlates] (ObsidiPlates-1.7.10-universal-3.0.0.18.jar) 
	UCHIJAAAA	OpenMods{0.7.3} [OpenMods] (OpenModsLib-1.7.10-0.7.3.jar) 
	UCHIJAAAA	OpenBlocks{1.4.3} [OpenBlocks] (OpenBlocks-1.7.10-1.4.3.jar) 
	UCHIJAAAA	sciapi{0.5.2} [SciAPI] (SciAPI v0.5.2.jar) 
	UCHIJAAAA	cuchaz.cuchazinteractive{1.7.10-1.0} [Cuchaz Interactive] (shipsMod-v1.7.10-1.0.3.jar) 
	UCHIJAAAA	cuchaz.ships{1.7.10-1.0.3} [Ships Mod] (shipsMod-v1.7.10-1.0.3.jar) 
	UCHIJAAAA	SSTOW{1.7.10-0.1-RC9-7} [Soul Shards: The Old Ways] (SoulShards-TOW-1.7.10-0.1-RC9-7.jar) 
	UCHIJAAAA	statues{2.1.3} [Statues] (Statues-Mod-1.7.10.zip) 
	UCHIJAAAA	stellarsky{0.1.6} [Stellar Sky] (Stellar Sky v0.1.6 [1.7.10].jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJAAAA	Torcherino{2.2s} [Torcherino] (Torcherino-1.7.10-2.2s.jar) 
	UCHIJAAAA	ttCore{MC1.7.10-0.1.0-67} [ttCore] (ttCore-MC1.7.10-0.1.0-67.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.1} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.1.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 347.88' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.3-303
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.1.0-161
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:OFF, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.5.0 NVIDIA 347.88, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Soartex.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by spannerman79** [comment]
Many of those mods you have hook into forge 1291 - not 1448.
For example, buildcraft, ae2, enderio are just three from quickly scanning over your log file.

Update those plus others to more recent mod versions.

**Comment by Dradeliomecus** [comment]
Well that's the thing, when I updated mekanism (before the bug), I updated it with all of the other mods (ae2, enderio, not buildcraft because it crashes). I might have missed 2 or 3 mods but otherwise, they are all up to date.
Furthermore the exception is a division by zero, so I though the error was most likely that the one who coded the method forgot to check the variable.

**Comment by aidancbrady** [comment]
Fixed!
