### ISSUE TITLE
[Request] Flamethrower output become adjustable

### ISSUE THREAD

**Issue by karakufire** [aidancbrady/Mekanism#2874]
I often use flamethrower to combat too many enemies and feel hard to handle this a little.
Charcoals, metal ingots, or others from flame hit blocks frequently waste my inventry.
Therefore I want that flamethrower launching power be adjustable, notably both of High heat mode(can smelt, high damage and high gas consume) and Low heat mode(cannot smelt, low damage and low gas consume).

**Comment by aidancbrady** [comment]
I actually love this idea- I'll try and get this done for the next minor release.

**Comment by ruifung** [comment]
So... Mode names:

Mildly Warm, Scalding Hot, Burnt to Cinders
XD

**Comment by karakufire** [comment]
Mode names is okay like as high heat and low heat. Simple name is easy to use.

**Comment by Mementh** [comment]
i would say there needs to be a option to do smelt or not smelt.. 
it should only damage mobs on not smelt..  on smelt it damages and does damage to area IE lights trees on fire and smelts

**Comment by aidancbrady** [comment]
I'm thinking "Combat," which only does damage to mobs, "Heat", which deals mob damage and smelts items, and "Inferno", which does deals damage, smelts, and lights fires.

**Comment by phantamanta44** [comment]
What if heat can light fires on flammable materials, but inferno can ignite anything?

**Comment by Mementh** [comment]
your idea of comabt heat and inferno is good! it would make me want to use it as a normal weapon!!!

One question could it be enchanted ? with fortune or beheading?

**Comment by karakufire** [comment]
Happy release 8.1.8! thankyou

**Comment by EzerArch** [comment]
How to change the modes? I tried to use Armor mode switch and Item mode switch, alone and combined with shift-key, but it still stuck in Combat mode.
