### ISSUE TITLE
A few bugs and ideas

### ISSUE THREAD

**Issue by Radviger** [aidancbrady/Mekanism#2876]
1. Jetpack flame renders behind clouds, nether portal, etc: http://prntscr.com/7zi83g
2. Energy upgrades can be inserted into electrolytic separator and you can build an infinity energy source.
3. All basic blocks can be blaced through the player: http://prntscr.com/7zibly
4. Machine sounds still glitch when hearer teleports.

Some improvements:
1. Against ru_RU.lang fix: http://pastebin.com/4svAKs2f
2. Better plastic textures: https://www.dropbox.com/s/zpuppfpty1smby0/plastic.zip?dl=1

Some ideas:
1. Add randomly moving trajectory for baloons.
2. Create multiple creative tabs. For example:
- Mekanism: Basic
- Mekanism: Tools and armor
- Mekanism: Plastic blocks

**Comment by ruifung** [comment]
2- Energy upgrades in the seperator does not decrease energy usage. Only energy capacity.

Which version are you on ?

**Comment by Radviger** [comment]
Also, this is very very terrible: http://prntscr.com/7zlxoh

**Comment by Radviger** [comment]
I know that its hapens on some graphical cards and fixing by manipulating GL_LIGHTING in render.

**Comment by RAWRwins254** [comment]
2- as @ruifung said, Energy Upgrades don't decrease energy usage. They only give it more of a buffer.
3- This is a vanilla issue last I knew. I can't remember if it truly is, but typically I've noticed that even on vanilla servers. This cannot be fixed by a mod.

**Comment by aidancbrady** [comment]
RAWRwins254 and ruifung are right on parts 2 and 3, and I'm not sure there's any easy fix to part 1 - vanilla particle renders face the same issue.  I'll take a look at the sound issue later, I'm pretty sure it's already reported.  I'll implement your fixes when I have a chance :)

**Comment by aidancbrady** [comment]
New plastic textures added, thanks!
