### ISSUE TITLE
Bug - Pumps Destroying Source Blocks

### ISSUE THREAD

**Issue by Utildayael** [aidancbrady/Mekanism#2877]
Multiple electric pumps together seem to "glitch" and destroy the source blocks of the infinite source even tho the source blocks are not under the pump.

Example:

WWWW
PPPP
WWWW

W - Water Source Block
P - Pump

Eventually all water blocks are gone. Seems to only happen when you have pumps next to other pumps as a single WPW setup works fine. 

Thanks

**Comment by RAWRwins254** [comment]
I've noticed the issue in even separated pump setups such as this

PWWPW
WPWWP
PWWPW

**Comment by Utildayael** [comment]
Additional info.. I don't think the pump setup is actually the root cause of the issue. I had the bug happen while I was logged out of my server. I logged in today, noticed my towers were dry. Checked the pumps... no water. Checked around my base and every single electric pump I had in any configuration [even single ones by themselves] had completely obliterated all water blocks around them.

I even had one set as a test such that:

WWPWPWW
WWPWPWW
WWPWPWW
WWPWPWW

It destroyed all those source blocks as well.

My guess at this point is something happens with the server and it causes the pumps to freak out in an area. I did check a few friends places nearby to mine and their pumps were still ok for what that's worth.

**Comment by Utildayael** [comment]
Ok this is odd but related maybe?

I have a set of 4 pumps in a line:

WWWW
PPPP
WWWW

They ran out of water again, ie source blocks gone. I have the pumps going into a separator to make deuterium with a gas tank sitting right on the output to collect the gas and then a gas line running from there straight to my fusion reactor. Tank is set to idle. 

Fixed water initially and saw the tank was low but eh whatever it happens? Got it flowing again. Checked back later gas tank was full. Great! Later the water poofed again. I look in the tank? Empty. It's like it purged the whole tank too and/or the gas line attached to it.

I'm going to try to slap a chunk loader down and see if that helps any.

**Comment by Visstick** [comment]
I noticed the same issue,

http://puu.sh/jyzmC/96b98f51a4.jpg
This is my setup. I filled the entire basin with water and made sure there was no flow in the water.
Then I activated the pump(only the middle one) and within 5 minutes it looked like the screenshot.

I have tried different setups with the basin.
3 wide 1 deep
3 wide 2 deep
3 wide 3 deep
5 wide 2 deep
5 wide 1 deep 
5 wide 3 deep.

All with no effect.

As you can see from the tank on the background they have worked fine for some time. There is like a 1000000 mb of heavy water in that tank.

The area is chunkloaded.

**Comment by hehe3301** [comment]
The problem exists due to chunkloaders. I have tested this with many pool
sizes and shapes, the only thing that made a difference was wether it was a
player leading the area or not.

**Comment by Visstick** [comment]
I use the chickenchunks loader.

**Comment by hehe3301** [comment]
Chickenchunks loader does not act the same as a player, they are part of
the problem.

**Comment by Visstick** [comment]
Had a strange issue between that chunkloader and AE too. Problem ofcourse is that I can not stand next to the pumps too make heavy water all the time :s Lets hope a future update includes a fix for the interaction with chunkloaders or vice versa.

**Comment by Utildayael** [comment]
I had the issue as reported prior to having any chunk loaders in use anywhere on the server. :)

I added in a chunk loader to try to see if that helped but it did not. I've actually witnessed the pumps destroy all the source blocks while I was standing right next to it. It seems like it "forgets" to only take the water block right below it.

**Comment by babyblasphemy** [comment]
I'm having a similar problem, but it's even more annoying, because it seems like the pumps aren't respecting the edge of water at all, and removing all water in the area. 
I had this set up, and all water seen in the picture was completely gone.
![image](https://cloud.githubusercontent.com/assets/12488365/9561055/927e6bfa-4dea-11e5-9e8d-fe37dadaaa28.png)
If you are concerned about the block on the right, they are Transfer Node (Liquids) from Extra Utilities, and they have World Interaction upgrades (they don't use the water source, just check for a valid infinite water setup).
My base was also chunkloaded, but I am not sure if it drained while I was here or not.

**Comment by aidancbrady** [comment]
No longer an issue with v9 changes.

**Comment by Utildayael** [comment]
Woohoo! Thanks Aidan!
