### ISSUE TITLE
Dynamic tank losing contents

### ISSUE THREAD

**Issue by zeroghost** [aidancbrady/Mekanism#2879]
I setup a dynamic tank, that contained about 700 buckets worth of lava, I went to get more lava (was about 80% filled) came back: tank entirely empty. GUI was working just fine, but no more contents(lava) what so ever... nothing hooked up to it, so nothing that could have drained it, it just vanished. I tried to reproduce it in a single player world, but to no success. 

running the latest mekanism (just updated this morning to: 1.7.10-8.1.7.252.jar) the dynamic tank was crafter and setup AFTER I updated, so has nothing to do with the update process, so also no idea if this happened in the previous version. I kinda don't want to use the tanks anymore if it can lose all its contents at random times.. kinda put a big dent in my lava supply. 

Running on a MC Server
Mekanism-1.7.10-8.1.7.252.jar
MekanismGenerators-1.7.10-8.1.7.252.jar
MekanismTools-1.7.10-8.1.7.252.jar

**Comment by aidancbrady** [comment]
There were some multiblock inventory sustaining issues just a few releases back, there's a good chance that was the source of your issue.  You shouldn't run into this anymore with 8.1.7.

**Comment by zeroghost** [comment]
The version I am running, and ran when this error occurred is: Mekanism-1.7.10-8.1.7.252.jar so it doesn't seem like it has been fixed. I made the blocks, and the multiblock AFTER i updated to 8.1.7.252. So it seems this is still an issue?
