### ISSUE TITLE
[Feture Request] Sound Filter(Upgrade)

### ISSUE THREAD

**Issue by karakufire** [aidancbrady/Mekanism#2880]
Each machine's sound are nice in factory, and are loud in home.
However being silent by configure is not moody.
Thank you.

**Comment by Utildayael** [comment]
It would be nice if they worked with the Noise Muffler blocks.

**Comment by karakufire** [comment]
I know so.
Each of machines are individually set silence or not in game. I request it.
No noise of all machiens, that is lonely. This is very important.

**Comment by ruifung** [comment]
So basically a silencing upgrade for the machines.

**Comment by Kodos-Atoz** [comment]
I -love- Witchery Ear Muffs for blocking out sounds, but I don't like having to install a magic mod in a tech pack just for that.  Maybe we can get Safety Ear Covers in Mekanism that block out the sound?

**Comment by ruifung** [comment]
Heck just make the machines work with ExU 's sound mufflers and I'll be happy enough.

**Comment by karakufire** [comment]
I want both of silent machines and noisy machines. I want to adjust machien's sound to some location, separate noisy area and quiet area. Why you recommend way to shut up any machines.
(ExU's sound muffler cannot decrease Mek sound.)

**Comment by ruifung** [comment]
Yes, I know ExU's sound mufflers don't work with mek. Hence please do reread my comment. I said I would be happy enough if the machines are made to work with ExU's sound mufflers.

**Comment by karakufire** [comment]
Uh, huh, It's not. sound muffler work decreasing arround any sounds. not just machines.

**Comment by XFactHD** [comment]
The change log of the first release of Mek 8 actually said that Mek would now be using the Forge sound system which should make the sound muffler work on Mek machines but as others already stated it doesn't work.

**Comment by unpairedbracket** [comment]
Pretty much concurrently with me redoing the sound system, RWTema removed compatibility with tickable sounds, so we unfortunately can't be compatible. I think our sounds need to be Tickable so they don't continue playing after the machine has stopped or been destroyed.

**Comment by karakufire** [comment]
I simply want a upgrade like as Gregtech's muffler upgrade. This indicate what I want.

**Comment by Mementh** [comment]
there is a option in the mod config to change the volume of the machines. its a client side only setting :)

**Comment by karakufire** [comment]
I don't want to be quite all machine. only some placed it(ex.nearby my bed).
My poor English cannot tell my request certainly, also shown in Japanese, my mother tongue.
ワールドに設置してある全ての機械の音は消したくないけども、例えばベッドの近辺などの、自分がよくいる場所の機械の音は消したい。なので、Gregtechのmuffler upgradeみたいなupgradeが欲しい。

**Comment by ruifung** [comment]
No worries, we understood what you meant the first time. And writing in japanese is not likely to make it any more understandable (although I'm trying to learn the language >.<)

**Comment by Stekeblad** [comment]
If possible, how about a own slider in the sounds options for machines?

**Comment by aidancbrady** [comment]
This has been added in v9 :)
