### ISSUE TITLE
Can't craft some items

### ISSUE THREAD

**Issue by zann1** [aidancbrady/Mekanism#2882]
I'm using Too Many Items mod and I have noticed that I can't find some items there i.e scuba tank and universal cable, its small issue becouse I can craft them. On the other hand paxel is not craftable but I can get it from TMI

**Comment by ruifung** [comment]
TMI? I don't notice this issue with NEI? A lot of the recipes are using a custom NEI crafting handler under Mekanism Shaped..

**Comment by aidancbrady** [comment]
Right, Mekanism does not support TMI.
