### ISSUE TITLE
Universal Cable Not Transmitting Power At Certain Point

### ISSUE THREAD

**Issue by RoloEdits** [aidancbrady/Mekanism#2883]
![2015-08-03_19 11 51](https://cloud.githubusercontent.com/assets/12489689/9051746/e23c99ae-3a13-11e5-8097-15eb270a6611.png)

![2015-08-03_19 11 53](https://cloud.githubusercontent.com/assets/12489689/9051747/e6ad9c9a-3a13-11e5-8003-fa8da8c580db.png)

Waila doesn't work on the cable either but it does on the other ones

![2015-08-03_19 11 58](https://cloud.githubusercontent.com/assets/12489689/9051753/ea79d5be-3a13-11e5-8169-8f79046c0138.png)

All are in one chunk space

**Comment by ruifung** [comment]
Yeah I find it does that too if you put it on top of a redstone emitting block (say projectred gates) and then toggle off its redstone sensitivity.

**Comment by aidancbrady** [comment]
Version?

**Comment by RoloEdits** [comment]
Mekanism-1.7.10-8.1.7.252

**Comment by Utildayael** [comment]
I had the same odd problem on 1.7.10-8.1.5.246 I think. If you hit the wire with the network reader does it say "No Network" ??

I just went through this and had to remove the wire and replace it to get it to work again. Sadly it made me replace every single wire in the line. All blocks showed "no network" via network reader prior to be replaced. 

Oh and this affected item, liquid, and gas pipes too. Not all tho oddly. I got tired of fixing them so on a whim I did a server restart and they are all working again. I know that's not exactly a font of info to go from.

**Comment by ruifung** [comment]
8.1.7 yeah.

**Comment by RoloEdits** [comment]
I tried the network reader an the capacity was negative were as the others were like 1.5E9

**Comment by Utildayael** [comment]
Just saw some pipe fixes in the commits... wonder if these are in the new version? Will have to upgrade and test...

**Comment by Utildayael** [comment]
More testing... if I log out and back in that seems to fix them which lead me to think.. chunk loading.

I put down a chunk loader to cover my entire base and the problem has gone away!

**Comment by ruifung** [comment]
@Utildayael If memory serves, the chunk loading issue was due some wierd mod interaction and was fixed in 8.1.6?

**Comment by RoloEdits** [comment]
I tried logging in and out multiple time and it still didn't work, and as i said in my reporting there all in one chunk for me so i think it may be a different problem.

**Comment by RoloEdits** [comment]
All within one chunk 
![2015-08-07_17 22 45](https://cloud.githubusercontent.com/assets/12489689/9148215/662e5064-3d29-11e5-9efd-79b02d8b1ca3.png)

![2015-08-07_17 22 48](https://cloud.githubusercontent.com/assets/12489689/9148217/6b2888dc-3d29-11e5-8f76-5be4bea6b5dd.png)

**Comment by Utildayael** [comment]
Awesome! I'll have to test. :)
