### ISSUE TITLE
Suggestion: Armor Enchant To Protect Against Laser Death

### ISSUE THREAD

**Issue by RoloEdits** [aidancbrady/Mekanism#2885]
Would be cool if there was an enchant to put on armor to prevent death by laser

**Comment by ruifung** [comment]
Please no. I think as a Tech mod, one should not dabble in the mystical arts of enchanting. =P

**Comment by RoloEdits** [comment]
But I hate dyeing accidentally by my own laser :(

**Comment by ruifung** [comment]
Its a occupational hazard of working with high power lasers.

**Comment by laz2727** [comment]
It should at least deal fire damage.

**Comment by aidancbrady** [comment]
In real life there isn't really any armor that can withstand a laser emitting gigawatts of power :)
