### ISSUE TITLE
Suggestion: Blacklist For Laser To Prevent It From Destroying Specified Block

### ISSUE THREAD

**Issue by RoloEdits** [aidancbrady/Mekanism#2886]
If there was a blacklist for blocks like the open blocks grave and what ever block we specified it would be useful for using it to stop the laser if we don't want to have to put bedrock or a laser amplifier across from it,and also if you die the it might destroy the grave and you might loose all your stuff

**Comment by aidancbrady** [comment]
I like the risk involved with using lasers- I think Laser Amplifiers are enough control.
