### ISSUE TITLE
Preserve machine settings when upgrading factory.

### ISSUE THREAD

**Issue by ruifung** [aidancbrady/Mekanism#2887]
It would be nice if machines kept their settings instead of just their upgrades when upgrading from Base machine > factories and when upgrading factory tiers.

**Comment by aidancbrady** [comment]
What do you mean by settings?  Side configuration conversion is tricky from basic machine -> factory

**Comment by Utildayael** [comment]
I think that is what he means. Going from factory to higher tier factory works flawless, you just lose your side settings when moving from basic to factory. I can confirm the behavior. :)

**Comment by ruifung** [comment]
Really? Going from factory to higher tier factory works flawless? I just converted my advanced to elite and it lost all side configurations.

**Comment by Utildayael** [comment]
Yup just upgraded one of mine from advanced to elite and it kept all side configs. I'm on 1.7.10-8.1.5.246 currently.

**Comment by ruifung** [comment]
huh, Oops, my memory was at fault here.

**Comment by aidancbrady** [comment]
As of now, I'm afraid machine upgrades are done about as precisely as possible without getting too messy.

**Comment by Utildayael** [comment]
Thanks for looking into it Aidan!

**Comment by aidancbrady** [comment]
I take that back. I've just done some changes which allow for machine configurations to be preserved between basic machine and factory state. Thanks again for the request :)

**Comment by Utildayael** [comment]
Woo hoo! :)
