### ISSUE TITLE
[Suggestion] More gas tanks.

### ISSUE THREAD

**Issue by hehe3301** [aidancbrady/Mekanism#2888]
Use for all that extra tin you have. A tin gas tank made with 8 tin ingots and one osmium dust, holds less gas then the standard.
Steel gas tank, 8 steel bars with one osmium dust, holds more then the standard tank.

**Comment by ruifung** [comment]
Or... Multiblock Dynamic Gas Tank!

**Comment by mercsniper** [comment]
TE portable tanks have been more cost efficient and store more in my
opinion. Having Dynamic Tanks has thus far seemed not worthwhile IMHO.

On Thu, Aug 6, 2015 at 10:43 AM, ruifung <notifications@github.com> wrote:

> Or... Multiblock Dynamic Gas Tank!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aidancbrady/Mekanism/issues/2888#issuecomment-128399003>
> .
>



-- 
Brad

**Comment by hehe3301** [comment]
My server had a large gas trade so I like item tanks I just wish there were more sizes

**Comment by mercsniper** [comment]
Use rotary condensers to turn the gas into liquid and store into TE Tanks.
Highly dense storage of gas.

On Thu, Aug 6, 2015 at 10:45 AM, Alexander H <notifications@github.com>
wrote:

> My server had a large gas trade so I like item tanks I just wish there
> were more sizes
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aidancbrady/Mekanism/issues/2888#issuecomment-128399654>
> .
>



-- 
Brad

**Comment by Utildayael** [comment]
If you have TE tanks they kind of make all Mek tanks worthless given how much a resonant one can hold. if you're overly ambitious the bedrockium drum from extra utils also holds an insane amount.

The dynamic tank looks cooler tho. :)

**Comment by hehe3301** [comment]
Assuming only mek though. We need more GAS tanks

**Comment by aidancbrady** [comment]
Tiered gas tanks could be a thing, as well as tiered portable tanks for fluids. We'll see!

**Comment by Utildayael** [comment]
Tiered gas tanks would be awesome sir. :)

**Comment by isochronous** [comment]
Totally want this! I'm always frustrated by the lack of gas storage options. I know the RC can be used to work around it, but that's just two more machines (gas -> liquid and liquid -> gas) that have to be added to every setup.

**Comment by aidancbrady** [comment]
I like this, a lot. I think I'm going to rename the Portable Tank to "Fluid Tank" and add tiers for gas tanks and the renamed fluid tanks to add a bit of consistency.

**Comment by aidancbrady** [comment]
This is now done :)
