### ISSUE TITLE
Cables/Pipes/Tubes Breaking

### ISSUE THREAD

**Issue by cdh0127** [aidancbrady/Mekanism#2890]
Something odd has been happening with cables, transporter pipes, tubes..etc and the auto-eject for machines.

I noticed some machines not being powered, and then after investigation, I noticed power wasn't flowing through the cables. The only way to fix it was to break the entire line (from one end to the other) and completely place the cables back down.

Then a similar thing was happening with transport pipes...I have a tier 2 ore processing setup, for example, and the daisy-chain of machines from Purification Chamber to Smelter was not running smoothly. Items were not being auto-ejected (like I have set) and not traveling through the pipes until I broke them all and replaced them, and even right now I have some buggy issues with these transport pipes that I cannot figure out how to fix them. As of right now, I have items being caught in the Crusher machine and not being auto-ejcted to the pipe behind it, except for a single dust after each crush, but not every time...if that makes sense?

Current Mekanism version is 8.1.5

![screen shot 2015-08-07 at 3 07 11 am](https://cloud.githubusercontent.com/assets/5170230/9131494/9930b5ec-3cb1-11e5-837b-386b36505d22.png)
![screen shot 2015-08-07 at 3 07 21 am](https://cloud.githubusercontent.com/assets/5170230/9131497/9af61886-3cb1-11e5-9ecb-593b2620c48c.png)
![screen shot 2015-08-07 at 3 08 02 am](https://cloud.githubusercontent.com/assets/5170230/9131499/9cb0925a-3cb1-11e5-917a-aea69e41f48b.png)

**Comment by Utildayael** [comment]
++ same issue. If you log out and back in that usually fixes it up too. Seems to be tied to chunk loading. I dropped down a chunk loader and set it to cover my entire base and the problem has gone away. Might give that a shot as a workaround.

**Comment by cdh0127** [comment]
I'll drop a chunk loader down I guess. I was going to try updating from 8.1.5 to 8.1.7 to see if that helped. What version are you running?

**Comment by Utildayael** [comment]
8.1.5 as well. I need to get my server owner to update to see if that fixes it. I saw some notes about pipe fixes in the commit log but I'm not sure how to tell if they were put into 8.1.6 or 8.1.7...

**Comment by cdh0127** [comment]
Ah okay. Well, I'm testing 8.1.7 later and I'll let you know if it happens again.

**Comment by Harkole** [comment]
I find that dying causes all power cables to fail, having to break them and replace them to get them working.

**Comment by aidancbrady** [comment]
Update to 8.1.7.

**Comment by cdh0127** [comment]
Re-open this. I am on 8.1.7 and the issue is still occurring...except breaking and replacing the pipes doesn't fix it. I can't get it to pull out or push into any machines. There's no reason for it to be stuck, but it it. Sometimes it will send one item down every 5 seconds or so...not the constant normal flow...and this causes bottle-necks in my processing chain.

**Comment by cdh0127** [comment]
It seems some machines auto-eject into the transport pipes normally, like the enrichment chamber, but others such as the Purification Chamber and Crusher, do not.

**Comment by ruifung** [comment]
Really? I have a few autocrafting builds that will use crushers so I'll test later. (Although i mainly use elite factories)

**Comment by cdh0127** [comment]
Okay let me know how it goes
