### ISSUE TITLE
Purification Chamber can not accept items from any pipes

### ISSUE THREAD

**Issue by Harkole** [aidancbrady/Mekanism#2891]
Mekanism 8.1.3.231 (FTB: Horizions II - DayBreaker)

Purifiaction chamber can will not accept items from Hoppers, Logistical Transport or Transfer Pipes. Pipes show connection to machine and input slots are correct but items will never be delivered. To prove connections were correct I changed the colour input on the side of the machine and saw the Logistical Transport pipe remove the connection.

Tried using strict delivery with colours but still couldn't get items to be sent.

Checked pipe set up by adding a chest in place of the machine and items were delivered.

Tried Enrichment Chamber and system accepted items as expected.

Tried right side and top side but both have same issues. Oxygen can be piped in without issue. Secondary items also fail to deliver when machine input is switched from Dark Red to Purple.

**Comment by aidancbrady** [comment]
This has been fixed.
