### ISSUE TITLE
CTD when hooking up logistical transporters to Refined Relocation buffers

### ISSUE THREAD

**Issue by jesmores** [aidancbrady/Mekanism#2893]
Ran into this while testing for mod interactions. I don't have a callstack, since I only thought to report this after I had removed RR from my pack and purged my test instance, but I'll get one as soon as I finish my custom pack.

#### Repro Steps
1. Chest ---[transporter]---> Regular Buffer ---[relocator + filter module]----> Enrichment Chamber
2. With the Configurator, set the transporter attached to the chest to Export mode

#### Expected
Items go from chest, to regular buffer, to enrichment chamber

#### Actual
CTD, array index out of bounds exception with Mekanism in callstack

#### Notes
I had the RR filter module configured to only keep 2 iron ore inside the enrichment chamber. Not sure if that matters or not.

Refined Relocation is here: https://refinedrelocation.github.io/

**Comment by aidancbrady** [comment]
Could you provide a log?

**Comment by jesmores** [comment]
Sorry for the delay. I uh ... kinda forgot about this! I can get it to repro still using the latest versions of RR and Mek (downloaded from your site). I think it's actually the interaction between the Mek Transporter and the RR buffer only.

![2015-12-19_10 44 34](https://cloud.githubusercontent.com/assets/125214/11914796/307997c0-a63e-11e5-8517-8fe92e2c49db.png)

1. Chest (with items inside!) ---[transporter]---> RR Buffer
2. With the Configurator, set transporter to extract from the chest

Crash doesn't occur if the chest has no items inside it.

fml-client-latest log that has the callstack of the crash
[fml-client-latest.txt](https://github.com/aidancbrady/Mekanism/files/67569/fml-client-latest.txt)

I've long scrapped my custom modpack, so this is just a minimal modlist with Waila, NEI, Mek, and RR installed.

The arrangement from the screenshot doesn't actually do anything, since the RR buffer needs another pipe attached to the other side for it to have something to pipe to (it's meant for connecting piping systems of different mods to each other). This is the minimum configuration I found that causes the crash though.

Let me know if you need more info from me, or want me to try anything else on my test instance.

**Comment by aidancbrady** [comment]
I'm going to call this on RR's end, it seems like the block is returning a different inventory size value than the array of slots it returns on its side.  Thanks for looking into it!
