### ISSUE TITLE
Induction matrix mixup input/output

### ISSUE THREAD

**Issue by Vliro** [aidancbrady/Mekanism#2894]
In the latest version of 1.7.10 pack the induction matrix's output is also reliant on the provider inside the matrix. That is, with a basic version it can only handle an input of 25.6krf/t, not only output. With the ultimate version it could handle 13.1 million RF/t as input. Tested with the fusion reactor. Not sure if intended. Thanks.

**Comment by ruifung** [comment]
http://wiki.aidancbrady.com/wiki/Induction_Providers

Uh, the wiki says the output rate is dependant on the provider?

**Comment by Vliro** [comment]
I mean for whatever reason in the latest update of The 1.7.10 pack the input rate is also dependant on the provider. I used cryogenic flux-ducts from the fusion reactor, and it would only accept 25.6kRf/t with the basic provider, but with the ultimate version it worked.

**Comment by aidancbrady** [comment]
This is intended new behavior as of 8.1.6 - more of a reason to make providers :)
