### ISSUE TITLE
Suggestion: Add config option to disable generation of certain ores

### ISSUE THREAD

**Issue by walkerjonny** [aidancbrady/Mekanism#2895]
Hi
I'm getting this server module crash in SP when I try to create a new world. This is repeatable.
http://pastebin.com/96pFx8aa
Can you check this out, please?

Also a suggestion:
As there are some useful custom ore generation tools like CustomOreGen it would be useful if it might be possible to disable the generation of certain ores within your config file so that this mod can take over the ore generation completely. That speeds up world generation greatly.
Have a look there:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291128-custom-ore-generation-first-revival

**Comment by walkerjonny** [comment]
OK,
That was my fault. I accidently added a custom ore distribution file that was only thought for testing to the CustomOreGen custom module folder.
This caused that issue, as this test file usually messes up the whole world and is not thought for normal playing

So only the suggestion remains then.

**Comment by aidancbrady** [comment]
It is already possible to disable Mekanism ores- I think the property is "XPerChunk" where X is the ore type :)
