### ISSUE TITLE
Laser amplifier outputs current stored charge level to comparator

### ISSUE THREAD

**Issue by ruifung** [aidancbrady/Mekanism#2896]
Is it possible to add this function? So I can cut power to the lasers when the amplifier stores up enough energy.

**Comment by Cbert** [comment]
+1
I have similar request.
It would be great if there would be upgrade for laser amplifier that would make possible to set target storing MRF on reaching what would laser amplifier emit redstone signal or better wireless redstone signal. So it would make much easier running auto fusion reactor setup.

**Comment by aidancbrady** [comment]
Added in development.
