### ISSUE TITLE
Card to copy machine IO settings

### ISSUE THREAD

**Issue by ruifung** [aidancbrady/Mekanism#2897]
So when setting up machine processing clusters where every machine should have the same setting it can be easily duplicated instead of setting it manually.

Something like the Memory Card from AE2 which can copy all the settings?

**Comment by lapin-b** [comment]
+1

**Comment by aidancbrady** [comment]
This is now done!  Filter Cards have been renamed to "Configuration Cards," and can store information from all configurable machines in Mekanism.
