### ISSUE TITLE
Unable to start world, kicked back to main menu

### ISSUE THREAD

**Issue by DeusExNihil** [aidancbrady/Mekanism#2898]
http://pastebin.com/1cyBStqx

This error appears to be caused by a conflict with Flaxbeard's Steam Power, as it worked normally when it was removed.

**Comment by Tsyklop** [comment]
https://github.com/aidancbrady/Mekanism/issues/2933

**Comment by Tsyklop** [comment]
https://github.com/Esteemed-Innovation/Flaxbeards-Steam-Power/issues/298

**Comment by Tsyklop** [comment]
I recreate the configuration file FSP and everything was fine.
