### ISSUE TITLE
Where button "CLR"?

### ISSUE THREAD

**Issue by Azatik** [aidancbrady/Mekanism#2899]
Where button "CLR"? It was before. Now it is not.

![mekanism](https://cloud.githubusercontent.com/assets/10154956/9182817/0ce435ca-3fc5-11e5-8a95-7de1fb1d443f.jpg)

![chemical_crystallizer_gui](https://cloud.githubusercontent.com/assets/10154956/9182829/1829fbf4-3fc5-11e5-919e-4a924fd11406.jpg)

**Comment by mercsniper** [comment]
the dropper was introduced so you can remove leftover substances and place
them in what ever container you would like or release into the air.

On Mon, Aug 10, 2015 at 4:05 PM, Azat <notifications@github.com> wrote:

> Where button "CLR"? It was before. Now it is not.
>
> [image: mekanism]
> <https://cloud.githubusercontent.com/assets/10154956/9182817/0ce435ca-3fc5-11e5-8a95-7de1fb1d443f.jpg>
>
> [image: chemical_crystallizer_gui]
> <https://cloud.githubusercontent.com/assets/10154956/9182829/1829fbf4-3fc5-11e5-919e-4a924fd11406.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aidancbrady/Mekanism/issues/2899>.
>



-- 
Brad

**Comment by Azatik** [comment]
I did not know. Thanks for the quick response.
