### ISSUE TITLE
Suggestion: Blacklist for Digital Miner (TFC compatibility issue)

### ISSUE THREAD

**Issue by Bunsan** [aidancbrady/Mekanism#2900]
In terrafirmacraft the ores are Tile Entities. The way they handle them allows them to have the base texture of surrounding stone, different qualities and different types. They have set it such that when silk touch is used on these ores they still drop their item. As you have implemented a custom silk touch the digital miner in silk touch mode gives the base Ore block and not the item it drops. This is an issue as these blocks can cause issues and the devs state they can corrupt saves. I believe that this is also an issue for Thaumcraft and GregTech as they both have TE ore blocks.

So my request is a Blacklist within config that prevents certain blocks from being silk touched and so would always drop their item. This may be useful for others as well, allowing servers and modpack makers to customize the balance of the digital miner in their server/pack.

**Comment by ruifung** [comment]
it works fine for thaumcraft. i've been using miner to silk touch all them ores to be manually processed later.
