### ISSUE TITLE
[Request] OpenComputers functionality for Reactor Logic Adapter

### ISSUE THREAD

**Issue by MyNameIsKodos** [aidancbrady/Mekanism#2901]
Having used BigReactors for quite a while, and having several programs in OpenComputers that revolve around the mod, I was... disappointed to see that the Mekanism reactor works with ComputerCraft and not OpenComputers.

This is my formal request for OC functionality so I can begin to port my reactor software over.  I love Mekanism reactors since there's much more depth to fuelling and maintaining them than just loluraniumfordays.

**Comment by aidancbrady** [comment]
Done :)

**Comment by dobegor** [comment]
I can't find a commit fixing this.
I am using last release of Mekanism + OpenComputers + ComputerCraft (for using other mods api for CC in OC). But I can't see any component of reactor in my OC setup.

Can you please describe the mod version and the setup required to control mekanism's fusion reactor from OC?
