### ISSUE TITLE
Crash when viewing recipies in NEI after adding Ex Nihilio Dust as a ingredient for ore duplication via modTweaker

### ISSUE THREAD

**Issue by almightyfoon** [aidancbrady/Mekanism#2902]
I'm getting a crash when adding a recipie via modtweaker to the ore duplication chain.The crash occurs when I view the uses of Ore Dust and I get to the page that has the recipie for the outputs (crystals, clumps, dirty dusts) in NEI. It works fine when I'm viewing the recipies from the machines and when I view the recipie for individual outputs and it crafts just fine without crashing. The only machine that works is the enrichment chamber it seems.

Reproduction steps:
1. Load MT script
2. Find non iron ore dust from Ex Nihilo and press u
3. Click next until you get to a page containing a mekanism ore tripling or higher product
4. Collect crash logs

minetweaker script:
http://pastebin.com/9E8qwYhy

crash report:
http://pastebin.com/9Ag21wci

I'm more than happy to also post issues to the other NEI and MineTweaker and Ex Nihilio githubs if you feel its needed. Let me know if you need to re-test anything.

**Comment by Radviger** [comment]
There is askant MK's integration with MineTweaker for now, I just added a few crooks to MK for my server that has additional checks for things like this.

**Comment by almightyfoon** [comment]
Any luck tracking this issue down?

**Comment by aidancbrady** [comment]
This is likely an issue with the version of Minetweaker you were using. Fixes added in 8.1.9 should prevent this kind of error.
