### ISSUE TITLE
Crash opening solar evaporation plant controller

### ISSUE THREAD

**Issue by GrandHunterMan** [aidancbrady/Mekanism#2905]
When I opened the controller's gui, I crashed. http://pastebin.com/9Ha56MHY

I was holding the advanced solar that is part of the multiblock, the multiblock was formed, and there was an ultimate energy cable next to the controller I had accidentally placed.

edit:additional details

edit:the multiblock may not have been complete

**Comment by aidancbrady** [comment]
Already reported
