### ISSUE TITLE
Digital miner/tinkers construct bug

### ISSUE THREAD

**Issue by jtb1313** [aidancbrady/Mekanism#2907]
When I add an ore to the OreDict Flter that also has an ore gravel they 'fight' for the spot and end up not counting as a filter so it just ends up trying to mine all the blocks it can reach, which is a big issue.

Background: I am using the latest version of Mekanism and Tinker's Construct in 1.7.10

EDIT: After further testing (this post was made before I went to bed) it seems as though only the cobalt ore is effected (I went noob mode and had inverse mode on, further testing is needed, and once again bed time)

**Comment by aidancbrady** [comment]
This isn't possible with the current miner algorithm- check your miner's configuration :)
