### ISSUE TITLE
Fusion Reactor water storage

### ISSUE THREAD

**Issue by YinScape** [aidancbrady/Mekanism#2908]
The reactor at 4 injection rate produces 150000 mb/t steam, but only has a buffer for 100000 mb water.

**Comment by vedalken254** [comment]
@YinScape without a slight modification that @aidancbrady or @unpairedbracket would have to make in https://github.com/aidancbrady/Mekanism/blob/development/src/main/java/mekanism/generators/common/tile/reactor/TileEntityReactorController.java#L37 (which I highlighted the line they'd need to change in that particular file, but they would have to also add a configuration option to tie in to that change), this is not something I can fix. My knowledge of Java is very limited so I'd probably do more harm than good trying to add it myself. However, it seems like a simple implementation change to me.

**Comment by aidancbrady** [comment]
Fixed! Reactors now scale steam and water tank size proportionally to injection rate.
