### ISSUE TITLE
Suggestion: Fusion Reactor - Automatic Steam Ejection

### ISSUE THREAD

**Issue by YinScape** [aidancbrady/Mekanism#2910]
As it stands now, using mekanism by itself, there is nearly no way for someone to pull out the amount of steam the reactor generates without config editing.  I propose that the reactor automatically ejects steam to valid connected pipes/tanks.

**Comment by ruifung** [comment]
Uh huh,why not? Using mekanism mechanical pipes should be able to pull that much out, owing to the mechanics of the transmitter system.

**Comment by aidancbrady** [comment]
Setting the pipes to pull mode should do what you want.
