### ISSUE TITLE
Single player VS Server Solar Evaporation discrepency

### ISSUE THREAD

**Issue by Mementh** [aidancbrady/Mekanism#2911]
I have found that on the AIE nomads serverpack on curse that the brine production on the server 1 tower is enough to run 1 normal 5x setup 24/7 ( chunk loader )
but when single player I need 5 brine towers..  ( found this out when figureing out HOW to set it up and was suprised when i did not need 5)

I checked with the admin and he never set anything diffrent... 

Could there be a setting in the mod itself thats set wrong server vs singleplayer or is there a setting we have messed up?

**Comment by aidancbrady** [comment]
The default value has changed between versions, likely the server started with an updated version of the config.
