### ISSUE TITLE
suggestion working better with applied energestics

### ISSUE THREAD

**Issue by Mementh** [aidancbrady/Mekanism#2912]
in 1788 they suggested a factory setting.. I would suggest maybe working better with Applied energestics.. to allow input and output to go into and out of the same side so that its used better there..  
The assembler in that mod can output to a interface.. it does not need a import bus like mekanism does

**Comment by aidancbrady** [comment]
This would take a lot of work and I don't think it's worth it for a little bit of supported integration.
