### ISSUE TITLE
[API] Having issues with the IMC-based recipe removal

### ISSUE THREAD

**Issue by TehNut** [aidancbrady/Mekanism#2914]
Following [this](https://github.com/aidancbrady/Mekanism/wiki/IMC-based-recipe-integration) Wiki page, I produced the following code to allow myself to remove Enrichment Chamber recipes.

```java
removeRecipe("EnrichmentChamber", new ItemStack(Items.diamond), new ItemStack(compressedDiamond));
```

```java
public static void removeRecipe(String recipeType, ItemStack input, ItemStack output) {
    NBTTagCompound recipeTag = new NBTTagCompound();
    recipeTag.setTag("input", input.writeToNBT(new NBTTagCompound()));
    recipeTag.setTag("output", output.writeToNBT(new NBTTagCompound()));
    FMLInterModComms.sendMessage("Mekanism", "Remove" + recipeType + "Recipe", recipeTag);
}
```

Theoretically, this should work. I triple checked everything and see nothing wrong with it. However, when Mekanism handles the it produces the following error:

`[19:15:15] [Client thread/ERROR] [Mekanism]: [Mekanism] recipetweakingcore sent unknown IMC message with key 'RemoveEnrichmentChamberRecipe.'`

When looking through [`IMCHandler.java`](https://github.com/aidancbrady/Mekanism/blob/28165fecdf4fee92b3dbae52827d68aaeb3121ae/src/main/java/mekanism/common/IMCHandler.java) to see if I could pinpoint my error, it appeared to require `Delete` instead of `Remove`, so I tried that as well. Still no dice. I [asked in the IRC channel](http://paste.ubuntu.com/12115374/), but nobody else seemed to know either.

**Comment by ruifung** [comment]
Just to be certain, when you tried using DeleteEnrichmentChamberRecipe, it says unknown IMC message with key 'DeleteEnrichmentChamberRecipe' ?

**Comment by TehNut** [comment]
Correct.

**Comment by ruifung** [comment]
Ok then there's the problem
```
if(msg.key.startsWith("Delete"))
					{
						msg.key.replace("Delete", "");
						delete = true;
					}
```
Isn't running. If it ran the key is supposed to lose the Delete portion.

**Comment by aidancbrady** [comment]
Duh, Strings aren't mutable. Fixed.
