### ISSUE TITLE
Recipe issue when immersive engineering is in the pack 

### ISSUE THREAD

**Issue by occelot666** [aidancbrady/Mekanism#2916]
We have built a large mod pack and we are having an issue with the enriching factory after adding immersive engineering, when you run through nether quartz ore you used to get 6 nether quartz now we are getting immersive engineering quartz dust which is not ore dict any ideas on how to change it back to its old recipe

I hope you can help 

Many Thanks
Occelot666

**Comment by nathan72419** [comment]
U can try to use modtweaker to change it back

**Comment by occelot666** [comment]
looking into the modtweaker way i found this but it does not seem right
//Enrichment Chamber
//InputStack, OutputStack
mods.mekanism.Enrichment.addRecipe(<minecraft:diamond_ore>, <minecraft:diamond> * 8);
//InputStack
mods.mekanism.Enrichment.removeRecipe(<minecraft:diamond>);

obviously changing the diamond_ore to quartz_ore and so on but both say input on the modteaker site
http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Mekanism_Support for reference

any further help would be appreciated as the pack is running live and dont want to mess it up completely :)

many thanks
occelot666

**Comment by nathan72419** [comment]
Remove the recipe first and u will be able to make the recipe
