### ISSUE TITLE
Dupe Bug using Tinker's Construct Smeltery and Mechanical Pipe

### ISSUE THREAD

**Issue by jonhowardlife** [aidancbrady/Mekanism#2917]
Version Details: Using the Space Astronomy pack on the Curse launcher. Pack is running Mekanism-1.7.10-8.1.7.252

Video on YouTube: https://youtu.be/ZTYODYKaGYA

Synopsis: When piping out of a Tinker's Construct Smeltery using a Mechanical Pipe, if you wait for the pipe to fill with an amount of liquid and then apply a redstone signal, it will save the current state of the pipe. You can then drain the liquid out of the pipe, apply a redstone signal again, and the pipe will reset to the saved state full of liquid.

**Comment by ruifung** [comment]
Lol wut?

**Comment by jonhowardlife** [comment]
I can create infinite metal. That probably should not be happening.

**Comment by aidancbrady** [comment]
Yeah, this is pretty serious. Searching for a fix...

**Comment by aidancbrady** [comment]
Fixed!
