### ISSUE TITLE
Liquid replication

### ISSUE THREAD

**Issue by bdbbdb** [aidancbrady/Mekanism#2918]
![2015-08-20_22 50 18](https://cloud.githubusercontent.com/assets/13888196/9385296/9746b030-4790-11e5-8ad6-814f2c5627aa.png)
![2015-08-20_22 50 24](https://cloud.githubusercontent.com/assets/13888196/9385299/9cc913b8-4790-11e5-894f-f94c864fb97d.png)
![2015-08-20_22 50 27](https://cloud.githubusercontent.com/assets/13888196/9385301/9ef1c6e4-4790-11e5-967e-405384daf74c.png)
It is possible on every machine that uses the liquid
If you have overlapping items, and of holding a liquid

**Comment by aidancbrady** [comment]
Already reported
