### ISSUE TITLE
Machines not visually connecting with other mods' pipes

### ISSUE THREAD

**Issue by Rearth** [aidancbrady/Mekanism#2919]
The Mekanism machines dont seem to visually connect with cables near them. This only happened when logging in again on a Server, not when placing them. Found this already at the induction Matrix with a cryo-stabilzed Fluxduct (Thermal Expans
ion) at the induction port and at the Solar Evaporation Valve with a Transfer Pipe (Extra Utilities). The bug is only visually, the induction Matrix still gets power from the cable and the solar Evaporation plant still gets in water.![2015-08-20_19 30 41](https://cloud.githubusercontent.com/assets/10100603/9390733/438dabdc-4773-11e5-85fc-f33054f05ad0.png)
![2015-08-20_19 30 48](https://cloud.githubusercontent.com/assets/10100603/9390734/438f1c74-4773-11e5-98d9-5b7070614108.png)

**Comment by aidancbrady** [comment]
This should be fixed for v9.
