### ISSUE TITLE
Fusion reactor injection rate non-responsive

### ISSUE THREAD

**Issue by XxXYaJrAbXxX** [aidancbrady/Mekanism#2920]
I built a fusion reactor and it was working perfectly fine with the injection rate at 3 and was sustaining heat at around 150MK. I then placed a chunk loader and went offline and when I came back on all my tritium had disappeared from the pipes as a start and it was still in my ME computer and had barely used any. So I wasted over 40 buckets of tritium. I then started the reactor again and this time the heat just built and built well around the 3GK mark and would not stop until it ran out of fuel and it drained the ME computer as if it was set to 99 although in the reactor interface it was set to 3. No matter how much I break the block and replace it, it will not fix it. I am guessing chunkloading caused this error and is there any time this mod will be fully compatible with chunkloading? Using Mekanism 8.1.1 and MekanismGenerators 8.1.1.225

**Comment by gp009** [comment]
[quote] **Using Mekanism 8.1.1 and MekanismGenerators 8.1.1.225** [/quote]


im using versions 8.1.5.246 and not having any issues with reactors being chunkloaded though I dont use ME computers- you might want to try the newer version of Mekanisms and see if your problem goes away

**Comment by ruifung** [comment]
You should be using 8.1.7 instead of 8.1.5 lol, theres some crash fixes in 8.1.7

**Comment by XxXYaJrAbXxX** [comment]
Sorry I thought I was using the latest mekanism as the server I am on uses TPPI2 and it just updated to the latest. Will request mekanism is updated in the latest version of TPPI2 then.

**Comment by ruifung** [comment]
I didn't say that it solved this issue, I just noted that 8.1.5 has some crash bugs in it.

**Comment by XxXYaJrAbXxX** [comment]
It isnt crashing though but apparently chunkloading is working in newer versions so it must be fixed. I cannot test it due to the modpack hasnt updated.

**Comment by ruifung** [comment]
I daresay you haven't used bins or logistical transporters?

**Comment by XxXYaJrAbXxX** [comment]
In the chunks loaded yes

**Comment by ruifung** [comment]
Well.. the server probably should update to 8.1.7 then, because if ANYONE uses logistical sorters with filters and logistical transporters... server will crash.

**Comment by XxXYaJrAbXxX** [comment]
We have no control over that it is when the TPPI2 team decide to do that. All we can do is recommend it to them. As far as I am aware though, the server isnt crashing from that and they are not banned so it either isnt being used or it has been patched on this modpack.

**Comment by XxXYaJrAbXxX** [comment]
Just tested them and they are not crashing the server so guessing they are patched on this modpack.
