### ISSUE TITLE
[Feature Suggestion] Active Fusion Reactor Turbines.  Sorry if this is the wrong format; new to github.

### ISSUE THREAD

**Issue by Lasrer** [aidancbrady/Mekanism#2924]
Title pretty much says it all.  I suggest that turbines should be added that use the steam from an actively-cooled fusion reactor to generate power.  The advantage of using such a turbine is the increased efficiency of doing so instead of directly harnessing the energy via "magic" (AKA thermocouples).  The turbine would be constructed using "Turbine Housing", "Turbine Blades", and "Turbine Shafts".  The design would be similar to that of Big Reactors turbines.  The turbine shell would be a 5x5x8 with the rotor in the center and the blades in the middle.  The steam would be pumped in via a "High Pressure Steam Input" and low pressure steam would be removed via a "Low pressure steam Output".  The turbine housing only extends 6 blocks because induction coils must be places to generate power.  These cover everything over except the rotor where a power emitter would be placed.  strengthened glass view ports could replace housing except for the frame.  I also suggest that steam be made a gas.  The turbine also does not output water.  It outputs "Low-Pressure Steam" which can be run through a second turbine for extracting the most energy.  Turbines running on low pressure steam would output water vapor which could be condensed in the rotary condensentrator for water recovery.  Turbines consume as much steam as can be pumped in and output more energy when more steam is pumped in.  The steam turbine is not without risk; the turbine will explode if you break one of its blocks while it is in operation, Cut off the steam supply without shutting it down, or it is throttled down too quickly.  The turbine can be throttled down by sliding the Power lever until it stops.  If it is done too quickly the turbine will explode.  Once the turbine is in operation it is mostly maintenance free  A special upgrade can be installed to automatically shut down the turbine properly if steam is cut off.  This upgrade will consume an expensive item called the "Turbine Brake".  The upgrade may reduce the chance of explosion, but will not eliminate it.  I also suggest making steam a gas.

:)

**Comment by Kodos-Atoz** [comment]
As far as I know, turbines (And probably other ways to use that much steam) are already planned.

**Comment by Lasrer** [comment]
True.  I just wanted to suggest my idea for how it would be implemented.  My reasoning for making steam a gas is because steam is a gas in real life and it would prevent people from using the turbine with other mods steam.  perhaps steam could heat a evaporator instead of solar panels for faster fuel production.  That way; once the reactor is started it can run itself at a higher rate without using a million solar evaporation towers.  I also suggest Lithium neutron bombardment in the reactor.  Lithium could also be extracted from clay.  Also He3 can be an alternate fusion fuel for aneutronic reactions which should not require shielding over the reactor.  (Something I would like added).  I hope you guys like my ideas :)

**Comment by aidancbrady** [comment]
Turbines are completed for the coming release of v9.
