### ISSUE TITLE
[Feature Suggestion] Wrench

### ISSUE THREAD

**Issue by hehe3301** [aidancbrady/Mekanism#2926]
Simple addition of a wrench with simple features:
Right click to rotate machine.
Shift+Right-click to pick up machine/cable.

**Comment by mercsniper** [comment]
the Configurator does everything you are asking.

On Sun, Aug 23, 2015 at 9:47 PM, Alexander H <notifications@github.com>
wrote:

> Simple addition of a wrench with simple features:
> Right click to rotate machine.
> Shift+Right-click to pick up machine/cable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aidancbrady/Mekanism/issues/2926>.
>



-- 
Brad

**Comment by hehe3301** [comment]
It does not instant pickup or rotate machines like wrenches from other mods

**Comment by Kodos-Atoz** [comment]
You have to set the mode, there are specific modes for 'wrench' and rotate

**Comment by hehe3301** [comment]
How do you change modes, Shift right-click and "Mek item mode switch" do not work

**Comment by Kodos-Atoz** [comment]
I believe it's actually sneak+ meka item mode switch

**Comment by ruifung** [comment]
It is indeed sneak + mek item mode switch.

**Comment by vedalken254** [comment]
not to seem like a jerk here, but isn't shift the sneak key anyways?

**Comment by ruifung** [comment]
It is the default sneak key, but he was trying sneak + rclick and the mek item mode switch alone, not the sneak + mek item mode switch.

**Comment by hehe3301** [comment]
No I tried "sneak+right click" and "mek item mode switch". "Sneak +mek item
mode switch" seamed redundant. It's working now.
