### ISSUE TITLE
[Crash] Pumping oxygen to gas-burning generator crashes game

### ISSUE THREAD

**Issue by timmNygren** [aidancbrady/Mekanism#2927]
Figured you could pump oxygen into the gas-burning generator. I could reproduce by placing a gas burning generator next to the oxygen side of an electrolytic separator or use a gas pipe.

Modpack: FTB Horizons: Daybreaker (v1.0.2)
Crash log says Windows 8.1, but I'm using Windows 10
http://pastebin.com/TNpRfHci

**Comment by ruifung** [comment]
Outdated version of mek, update.

**Comment by vedalken254** [comment]
yarp... outdated mek version... also, the crash log thing seems to be an issue with MS and their upgrade process to 10. I upgraded from 8.1 as well and it stills shows as running on 8.1 even after a reinstall.

**Comment by timmNygren** [comment]
That did it. Thanks guys.
