### ISSUE TITLE
Can't craft with induction casing

### ISSUE THREAD

**Issue by dominsbeard** [aidancbrady/Mekanism#2930]
Putting an induction casing into any crafting table crashes the game. http://pastebin.com/WuZu2Hfd

This seems to be caused by a change in Botania (https://github.com/Vazkii/Botania/commit/b706fcb41da3704276040e1a95906f78f69d3f38#diff-4b138d02fe0f1038cda4ba2569423c63)

But I don't think it's an issue with Botania because other Mekanism items craft fine, except the induction casings.

**Comment by kotoroshinoto** [comment]
probably a duplicate of https://github.com/aidancbrady/Mekanism/issues/2938
