### ISSUE TITLE
Suggestion: GregTech5(u) energy support

### ISSUE THREAD

**Issue by walkerjonny** [aidancbrady/Mekanism#2932]
It would be really nice if you might add support for the GregTech5(u) EU/A energy system. 
It is a bit different to the IC2 EU energy system because it also supports how many packets (A) per Tick of a given Voltage (EU) are required by a machine / can pass through a given cable before it burns and blows up because of an overload.
At least some kind of converter block would be really helpful.

**Comment by aidancbrady** [comment]
I don't see myself adding GregTech support, sorry :(
