### ISSUE TITLE
[Crash] Can not create a new world

### ISSUE THREAD

**Issue by Tsyklop** [aidancbrady/Mekanism#2933]
I can not create a new world.
When creating a new world I return to the main menu. The log file is found:

http://pastebin.com/qFJ3Fya3

**Comment by Tsyklop** [comment]
fix pls....

**Comment by vedalken254** [comment]
Geez. Way to seem entitled... mod developers do have personal lives and other responsibilities too. They aren't at your beck and call. Commenting with fix pls is not cool in my book. Then again, I'm not a developer. But again, they have lives and other responsibilities.

Veddy

**Comment by ruifung** [comment]
Can you test without any tweaking mods, because this doesn't happen to me. And it should also crash when loading any world, given that error.

**Comment by Tsyklop** [comment]
I recreate the configuration file FSP and everything was fine.

**Comment by ruifung** [comment]
FSP? I take it it's not a problem anymore?

**Comment by Tsyklop** [comment]
At present no problem.
