### ISSUE TITLE
[8.1.7.252] Request to disable onConfigSync during world load.

### ISSUE THREAD

**Issue by AnodeCathode** [aidancbrady/Mekanism#2934]
The onConfigSync mechanism in mekanism :0 is very cool, however it is causing us some grief. We build a modpack based upon the TerraFirmaCraft conversion mod. This requires a number of recipe rewrites to fit with the changed mechanics/items/blocks found in the game. 

The onConfigSync deregisters and reregisters a lot of the recipes that we've modified to work with TFC ingredients.

Could we have an option to disable this option? Either the entire config sync or at least the portion that de/re registers recipes?

**Comment by aidancbrady** [comment]
If you need to disable machine recipes, I'd suggest disabling the machines in question with the config- these changes are passed along the onConfigSync() protocol.
