### ISSUE TITLE
Minecart dupe

### ISSUE THREAD

**Issue by yepidoodles** [aidancbrady/Mekanism#2935]
As I discussed in #2779 minecarts keep duping on rails, I've tried to disable the recipe for the mekanism recipe for tracks, but with no luck. I've reset the map, updated the mod, I know for a fact it's not server latency like was originally suggested.

Short of removing Mekanism entirely, I can not find a fix for this.

Alice
DragonTechMC

**Comment by rdunham3** [comment]
How would the Mekanism recipe for tracks (which I wasn't aware existed before now, but seems irrelevant anyway) affect a minecart entity duping on placed rails?  It makes no sense.  A recipe is entirely unrelated to an in-world placement.

Sounds like another mod has modified the code that fires when a cart is placed, and is causing it to fire more than once.

**Comment by yepidoodles** [comment]
Well I have no idea what was causing it and the only thing that changed was that Mek added a recipe for it. I'm not a tech person so I go by process of elimination on my grey areas.

**Comment by aidancbrady** [comment]
This is definitely not Mekanism I'm afraid, all I do (as rdunham3 stated) is add another recipe for rail.
