### ISSUE TITLE
Chemical Oxidizer speed upgrade

### ISSUE THREAD

**Issue by HadesDurin** [aidancbrady/Mekanism#2936]
hi i have the problem, that, when i put in 4 speed upgrades in the Chemical Oxidizer it has only a 3.16 times effect... In other machines like Rotary Condensentrator the same amout of speed upgrades have a 16 times effect.
Is that an issue or is it wanted?
because in the 4 times production chain for ore it slowes the whole process down to more than 20% speed...

**Comment by ringosham** [comment]
There are quite a few of machines that can go up to 256x speed at max and some can only go to 10x at max

**Comment by HadesDurin** [comment]
but i would see and find it nicer if those two maschines would have the same speed limitation

**Comment by aidancbrady** [comment]
Machines that process fluid have a 256x effect, machines that process items have a 10x effect.  I'd rather keep it this way for consistency's sake
