### ISSUE TITLE
Induction Matrix not registering as Computercraft Peripheral 

### ISSUE THREAD

**Issue by hehe3301** [aidancbrady/Mekanism#2937]
No part of my induction matrix is registering as a peripheral, Tried casing and ports in both modes.
Mek -v 8.1.7
CC -v 1.7.4 
OpenPeriphs -v AIO-5

[edit]:
I can connect to power cubes and cables just not Induction Matrices

**Comment by Rearth** [comment]
I have the same Problem

**Comment by aidancbrady** [comment]
Fixed!
