### ISSUE TITLE
Crafting Induction Ports

### ISSUE THREAD

**Issue by magisch** [aidancbrady/Mekanism#2938]
On a server or single player (tested both) with Mekanism-1.7.10-8.1.7.252
trying to craft the Induction Ports crashes the client. Tested with following crafting methods:

- AE Crafting Terminal
- Vanilla Crafting Table
- TiCon Crafting Station
- Gany's Surface Portable Crafting Table
- TE Cyclic Assembler
- Steve's Factory Manager's Machine Inventory Manager
- Buildcraft Automatic Crafting Table
- EnderIO Crafter

Example error log: http://pastebin.com/QudvmWKx

This could be where the problem lies:
https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/item/ItemBlockBasic.java#L205

(credit to Vazkii @ #vazkii)

**Comment by yepidoodles** [comment]
Having the same issue on my server, Botania doesn't look happy with it for some reason.

**Comment by utoc** [comment]
Having the same issue as well with a dedicated server and single player.

Crashlogs hurr:  http://pastebin.com/mfq0LsjQ

Tested with and without Optifile, no change.

**Comment by Frodyn** [comment]
On the plus-side ... I'm not the only one having this problem. I'm running the same version of Mekanism as part of the Core Zero modpack and I'm having the same issue. Originally I would have said that it happens "when I try to craft an induction port" but the reality, for me at least, is that the system crashes as soon as I try to put a block of Induction Casing into a crafting grid.

**Comment by HadesDurin** [comment]
the only way to work around that issue at the moment is to cheat in the item you wanna craft...

**Comment by FHRNet** [comment]
Minecraft crashes as soon as i place Induction Casings into crafting grid. Same crash as @magisch

**Comment by utoc** [comment]
This will hold you guys over in the meantime

```
val p = <Mekanism:BasicBlock2:2>;
val s = <ore:ingotSteel>;
val e = <Mekanism:EnergyTablet:100>;
val c = <Mekanism:ControlCircuit:2>;

recipes.remove(p);
recipes.addShaped(p * 2, [[null, s, c], [s, e, s], [null, s, null]]);
```

**Comment by Frodyn** [comment]
Must admit that I'd basically forgotten about Creative Mode as I only work in Survival. That being said there was no workaround so I did just grab a few Ports from Creative. After that it was smooth sailing. All the other associated blocks craft just fine for me and the structure is up and storing. Thanks for the info (and the reminder).

**Comment by themechman** [comment]
Interesting. I am using Botania 1.6 build 191 and am able to autocraft and use the induction casings as crafting parts.

**Comment by FHRNet** [comment]
We are using Botania r1.7-219 and Mekanism 8.1.7-252.

**Comment by Elvarion** [comment]
Same Issue, Induction in crafting table creates client crash.

Mekanism-1.7.10-8.1.7.252
Botania r1.7-220

**Comment by BBoldt** [comment]
another crashlog if it helps:
https://gist.github.com/09f5ab1fd562d084702d

**Comment by kotoroshinoto** [comment]
i have no idea if Mekanism or applied energistics is ultimately responsible for this.

When I place induction casing into a crafting grid I crash with the following trace. (if you need me to pastebin a specific logfile for more information let me know)

http://pastebin.com/g44v5yb9

Seems to be same issue.

**Comment by phantamanta44** [comment]
https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/item/ItemBlockBasic.java#L205
There should be a null check here, since I would assume induction ports have no stackTagCompound.

**Comment by aidancbrady** [comment]
Fixed in dev.
