### ISSUE TITLE
[BUG?] Logistical Transporter suddenly stops working

### ISSUE THREAD

**Issue by hron84** [aidancbrady/Mekanism#2940]
In my low-tech ore duplication system I use Basic Logistical Transporter to suck ores from a chest into an Enrichment Chamber, that's configured to accept items from directly that side where LT connects. I also configured LT with a Configurer to `PULL` items at the chest side. After some time (I cannot say how much, I playing a few hours ago) LT stops pulling items from the chest, even if literally nothing is changed. This system is processed a _lot_ of ore without any problem, and suddenly stopped. I tried to put vanilla Iron Ore (as I know LT can stop if it detects an unsupported ore) to the chest, and there is no change, Iron is not being sucked until I put 1 ore into the EC. 

Before it's being asked: no Strict Input, no color coding, no adjacent inventories (that can confuse LT) other than the mentioned ones, and LT does not get a redstone signal and also not configued to work only with high redstone signal. And I use only single LT to pull items to the EC, the chest is placed upper-left to the EC, and LT pulls items from the chest to EC. Breaking (wrenching) and re-placing blocks not helps.

Mek versions:

```
Mekanism-1.7.10-8.1.5.246.jar          
MekanismGenerators-1.7.10-8.1.5.246.jar
MekanismTools-1.7.10-8.1.5.246.jar     
```

ModPack: FTB Horizons Daybreaker (FTBHorizonsII) with disabled Redstonic mod.

**Comment by aidancbrady** [comment]
I fixed some transporter bugs since version 8.1.5, try updating.  If you're still encountering issues I'll reopen.
