### ISSUE TITLE
Xp temporarily dissappears when using teleporter

### ISSUE THREAD

**Issue by Kupanfu** [aidancbrady/Mekanism#2943]
When using the teleporter to transfer between dimensions, my xp bar temporarily dissapears. The xp isn't lost but as far as enchanting tables and other items that use xp, I might as well be a fresh lvl 0. Relogging or killing something causes the xp to come back to where it was. At first i thought it was something to do with RFtools dimensions, but it even happened when teleporting to the nether. Pics below show what happens.

--Before using the portal to the nether--
![2015-08-31_12 27 58](https://cloud.githubusercontent.com/assets/6774478/9583966/364560c0-4fdc-11e5-88e5-884b6cd1c943.png)

-- After arriving at the nether, xp is gone--
![2015-08-31_12 28 14](https://cloud.githubusercontent.com/assets/6774478/9584003/8ae6111a-4fdc-11e5-87de-4f4a7ef0a4b3.png)

-- after using a bottle of enchanting my xp is back --
![2015-08-31_12 36 08](https://cloud.githubusercontent.com/assets/6774478/9584055/e2198034-4fdc-11e5-98da-4c209490313d.png)

**Comment by rdunham3** [comment]
Not just a Mekanism issue.  I've seen it with at least two other teleport-type mods.  Now I'm trying to remember if the vanilla nether portal does it too...going to have to satisfy my curiosity tonight.

**Comment by HadesDurin** [comment]
i watched lately some modsauce2 videos from xBCrafted (hermitcrafter) on youtube and he has the same problem using some other portals mod

**Comment by EzerArch** [comment]
This bug used to happen in Galacticraft, but between dimensions: https://github.com/micdoodle8/Galacticraft/issues/1336

**Comment by shadowfacts** [comment]
This is simply a client desync problem, doing anything that causes the server to force the client to update (e.g. using a Bottle 'O Enchanting) causes the GUI to update.
