### ISSUE TITLE
Solar Evaporation Plant temperature not exceeding 300.0K

### ISSUE THREAD

**Issue by asianboi98** [aidancbrady/Mekanism#2944]
I've built the Solar Evaporation Plant about 18 blocks high (The max) and the temperature does not exceed 300.0K which would not allow the production of brine. I currently use Mekanism 8.1.6.250 and was a similar problem to the Recommended Version which forced me to update Mekanism but still face the same problem.
![2015-08-31_17 35 15](https://cloud.githubusercontent.com/assets/8291686/9591070/cbfd28b2-5006-11e5-8baa-44b4dd31eca7.png)
![2015-08-31_17 35 22](https://cloud.githubusercontent.com/assets/8291686/9591073/cc4c802e-5006-11e5-8ae1-63bc546068e8.png)
![2015-08-31_17 35 26](https://cloud.githubusercontent.com/assets/8291686/9591072/cc332a48-5006-11e5-995e-42216682b33d.png)
![2015-08-31_17 35 35](https://cloud.githubusercontent.com/assets/8291686/9591071/cc13afb0-5006-11e5-9304-7cde3fd5a286.png)

**Comment by grimallq** [comment]
You've built that tower somewhere where the multiplication modifier is set to 0.0.

It won't work at all.

**Comment by HadesDurin** [comment]
i think it is the fact, that he uses a super flat world presetting for building it

**Comment by hehe3301** [comment]
Try putting the tower entirely in a desert biome

**Comment by Hyperic88** [comment]
Tried same, in desert and same issue, 300K and nothing...

**Comment by grimallq** [comment]
@Hyperic88 And what's your multiplier there? Should be 2.0.

**Comment by Hyperic88** [comment]
@grimallq figured out somehow mysteriously, run only mek, and it worked, so i add other ones one by one, and it works. Maybe my bad was faultry build, but since i destroyed it, cannot prove that. Good think it works :)

**Comment by Zynoah** [comment]
This is the same problem that I'm having at the moment.. Every place that I've tried to set the solar plant up has had a multiplier of 0.0 .. I have no idea how to fix this .. does anyone have any suggestions please?
