### ISSUE TITLE
Invincible Mobs

### ISSUE THREAD

**Issue by Zsashas** [aidancbrady/Mekanism#2946]
Using the latest version of ModSauce II.

Every so often, I run into mobs in Mekanism armor. And occasionally, these mobs will be completely invulnerable to almost every type of damage. Not even a Tinkers' Construct Crossbow with 64 damage, or a Rapier with 16 armor piercing damage, or LIGHTNING, can hurt them. The only reliable way I have found to kill them is to use a Dagger of Sacrifice on a Blood Altar, because that always one-shots mobs. But that is the ONLY thing that we have found that can hurt them.

**Comment by HadesDurin** [comment]
you should go with that issue to the modsauce 2 development team, because there are more mods inside that pack which take care of mobs

**Comment by Zsashas** [comment]
I thought it might be Mekanism, because it only happens with mobs with full Mekanism armor. Also, only if it's a matching set. And only zombies so far.

**Comment by ruifung** [comment]
It shouldn't be Mekanism. Can you reproduce it with ONLY mekanism?

**Comment by phantamanta44** [comment]
I've seen this happen with all mobs that can spawn with Mek armour before. For some reason, they start taking damage again if I just whack them enough times.

**Comment by HadesDurin** [comment]
like i said earlier, talk to developers and use the forum there to post your issue 

https://forums.atlauncher.com/forum-70.html

**Comment by ktole1999** [comment]
i can confirm this issue with version 8.1.7.252 with only mek installed full armored mobs are invincible. not just mek armor.
