### ISSUE TITLE
Allow 'disabled' machines to show in NEI?

### ISSUE THREAD

**Issue by thephoenixlodge** [aidancbrady/Mekanism#2948]
I'm the developer of the Regrowth modpack, which has included Mekanism as its late game tech for quite a while (packs been out a good 8-9 months) and includes a bunch of recipe changes to incorporate the mod into the pack nicely. However, mek has been the cause of many a headache since updating to mek 8, namely in that it is horribly resistant to having its recipes changed. Initially I couldn't even change the recipes at all with mek 8 (using Minetweaker for changing recipes) as due to the recipes for some reason now loading after the world has loaded, MT is no longer capable of removing crafting table recipes to make mekanism things.
I did however manage to eventually find a way around that with a couple of the mek config options - namely I 'disabled' the machines I was changing the recipes for, and set the config to not remove any disabled machines that exist in the world. This basically worked, but with a major caveat; although the recipe changes now worked (new recipes still added just fine with MT) the machines that I had to do this with seemed to no longer show up in NEI at all, which I presume to be a behaviour related to having a machine be disabled,
This didn't seem like too much of a problem however - I just used MT to then readd them to NEI manually, and it seemed to work. However I was wrong about that too, and it seems to be working VERY inconsistently, and a lot of the time none of the machines I've done this with are showing in NEI at all. This in itself leads me to believe that their being removed from NEI is (like the addition of recipes) happening AFTER minetweaker is applying the scripts, meaning I can do effectively nothing about them showing in NEI.

As such, presuming I'm correct in this, that the lack of their appearance in NEI is related to the 'disabling', would it be possible to get a config to stop them from being hidden in NEI, or have it be tied to the config that removes disabled machines from the world?

**Comment by ringosham** [comment]
This is weird. I have no problems editing Mekanism's recipes without editing any configs using Minetweaker 3.

**Comment by thephoenixlodge** [comment]
What version of mek are you using? I'm only having this issue specifically since updating to mek 8

**Comment by ringosham** [comment]
I am using Mekanism, MekGenerators and MekTools 8.1.7

**Comment by thephoenixlodge** [comment]
@aidancbrady any chance you could wiegh in on this?

**Comment by aidancbrady** [comment]
I've added a bunch of new recipe controls to the IMC handler, info can be found here: https://github.com/aidancbrady/Mekanism/wiki/IMC-based-recipe-integration
