### ISSUE TITLE
[Feature Request] Mass Gas Storage

### ISSUE THREAD

**Issue by andrewrula** [aidancbrady/Mekanism#2949]
One of the things that I (and other users, if a ton of reddit build images are to be trusted) enjoy is the ability to utilize multiblocks to store resources. I propose the addition of a multiblock tank for the purpose of gas-storage, tentatively named the Pressurized Dynamic Tank.

While gas tanks are spectacular for practical storage on the low-end, larger amounts of gas are much more difficult to store in an effective manner. Adding a large multiblock will increase the aestetic value of such builds and provide interesting storage solutions in the mid-late game.

Possible recipes could include Dynamic Tanks as a component, plus additional steel/osmium or pressurized tubes to gas-proof it.

**Comment by MyNameIsKodos** [comment]
Why not use the Rotary Condensentrator to convert the gas to a liquid, and use a dynamic tank or other standard fluid storage from other mods?

**Comment by andrewrula** [comment]
While that is an option, it seems needlessly complex to have to convert it simply for storage sake through a (typically slow) machine, only to have to pipe it back through the same machine to be usable again. Obviously, this could simply be a difference of opinion, but I feel that not having larger scale gas storage is a notable gap in the current Mekanism offerings.

**Comment by ktole1999** [comment]
use what is already there. build your liquid storage and place the condensentrator. you do the same thing for electrolytic seperator. you cant speed it up so you buld more to satisfy the demand. same with  gas/liquid conversion. just my thought

**Comment by Utildayael** [comment]
I agree with andrewula. This becomes a major issues when you get to 5x ore processing and trying to keep enough hydrogen chloride onhand to meet demand. I've taken a rotary to turn it into liquid, store in a bedrockium drum, and then rotary to convert it BACK as needed... even with 8x speed upgrades it isn't fast enough. I suppose I cloud slap a bunch of rotary's on it for the export process...

I think a "dynamic tank" but for gases would be a more elegant solution and the code already exists for a multiblock to store liquids... :)

**Comment by Sandriell** [comment]
Not an "in-house" solution, but the mod Pressure Pipes (https://bdew.net/pressure/) has tanks that are compatible with Mekanism's gases . You can input/ouput directly as a gas or as a liquid.

I have my gas production seperated from my ore processing, so I have it setup to input to large storage tanks as a gas, then export as a liquid to Tesseracts to transport it. Then at the other end I have tiny buffer tanks inputting as a liquid and exporting as a gas for actual use.

**Comment by aidancbrady** [comment]
I'd rather stick with the Rotary Condensentrator/Dynamic Tank method of gas storage for now, maybe I'll add some kind of extension in the future.
