### ISSUE TITLE
No dump/clear button

### ISSUE THREAD

**Issue by polkziggy** [aidancbrady/Mekanism#2951]
The PRC and Chemical Crystallizer do not have a dump/clear button to void their tanks. I am using the latest recommended version (232). If the tanks get a fluid in them, but not enough to do its work, it is useless with no way to remove the fluid.

**Comment by phantamanta44** [comment]
Use a gauge dropper and shift-click on the fluid gauges in the GUI. It destroys the fluids/gases within.

**Comment by polkziggy** [comment]
Boom! That did it
Thanks
