### ISSUE TITLE
Dynamic glass flowing animation with hardly any liquid inside

### ISSUE THREAD

**Issue by killerwife** [aidancbrady/Mekanism#2955]
http://imgur.com/LrWcj9x
As stated, previously in patch 1.6.4 the only liquid inside with any resource pack was the indicator of the amount inside. In patch 1.7.10 with only 1 bucket inside there is a visible flowing animation on the glass sides. Resonant Rise, liquid inside Brine, using fastcraft, without optifine.

**Comment by aidancbrady** [comment]
This is intentional for gasses- I changed the animation algorithm a bit so that you can still see the gas even with a little bit of gas.
