### ISSUE TITLE
Electric pump causing lag

### ISSUE THREAD

**Issue by samara8609** [aidancbrady/Mekanism#2957]
The electric pumps seem to cause server lag due to block updates(guessing the removal of the source waterblock).  This isn't an issue until multiple people on the server want to run mek reactors and there is no other block that can provide the heavy water.

**Comment by brendonlamb** [comment]
I'm having similar issues here, i'm not 100% sure the pump is causing lag but it seems that whenever people are exploring any hiccups w/ the tick count ("Can't Keep up" messages) cause the water source blocks to sometimes disappear entirely.

Is there a way we could pump water into a filtered electric pump directly? Maybe using a Extra Utilities transfer node?

**Comment by aidancbrady** [comment]
This should no longer occur with the recent Electric Pump changes.

**Comment by brendonlamb** [comment]
Awesome work man thanks for the update and excellent mod :D
