### ISSUE TITLE
Wind turbine not producing energy

### ISSUE THREAD

**Issue by The-Silver-Kid** [aidancbrady/Mekanism#2958]
running mekanism 8.1.7; the wind turbine has a clear view of the sky but still wont produce power

**Comment by HadesDurin** [comment]
can you give more details of which mekanism versions you use...
there are 3 mekanism files in your mods folder

**Comment by The-Silver-Kid** [comment]
mekanism 8.1.7.252
mekanismGenerators 8.1.7.252
mekanismTools 8.1.7.252
Minecraft 1.7.10 Forge 10.13.4.1448 for 1.7.10
the sky detection box is red but there is nothing above it

**Comment by HadesDurin** [comment]
hmm, can you provide a picture of your setup, because, my wind turbine works fine
![2015-09-13_11 57 18](https://cloud.githubusercontent.com/assets/5231067/9836146/9f3b6d22-5a0e-11e5-92fc-11e0785ce1f9.png)

**Comment by Alaberti** [comment]
What height is the turbine at, and what cables do you have it connected to (if applicable)?

**Comment by HadesDurin** [comment]
i use universal basic cable from mekanism like you see in the picture
and the high is at y 65

**Comment by The-Silver-Kid** [comment]
Github isnt letting me post pictures but anyway the Y of the generator is 71 and it is attatched to an advanced universal cable... and there is nothing above it
![2015-09-13_16 25 47](https://cloud.githubusercontent.com/assets/7415468/9839479/ed302480-5a38-11e5-91bb-deb6b5d2fcc8.png)
![2015-09-13_16 26 36](https://cloud.githubusercontent.com/assets/7415468/9839480/ed50dfc2-5a38-11e5-91af-3c513e907b50.png)
![2015-09-13_16 27 15](https://cloud.githubusercontent.com/assets/7415468/9839481/ed51d59e-5a38-11e5-848e-8b578a6927c0.png)

**Comment by The-Silver-Kid** [comment]
Not sure what the whole YJ is but that is my setup just ignore my resourcepack

**Comment by phantamanta44** [comment]
Are you sure it's not just producing energy, then immediately hosing it out to the universal cable?

**Comment by HadesDurin** [comment]
rewiev your mekanism config file and switch to RF as energy type, that maybe fix your problem

**Comment by phantamanta44** [comment]
RF is automatically used with CoFHAPI installed. It doesn't actually work without it.

**Comment by HadesDurin** [comment]
i use thermal expansion and i have to set it manually in the config to use RF instead of J
and looking at the pictures from The-Silver-Kid
he didn't use RF for his mekanism

**Comment by The-Silver-Kid** [comment]
No even when its not plugged into a cable it doesn't accumulate energy
I set it to RF and the only thing that changed was it now says RF instead of J and some of the numbers are different

**Comment by The-Silver-Kid** [comment]
could it possibly be my forge version?

**Comment by HadesDurin** [comment]
maybe
i am on forge 10.13.4.1492

**Comment by The-Silver-Kid** [comment]
ill check that version

**Comment by The-Silver-Kid** [comment]
still nothing

**Comment by The-Silver-Kid** [comment]
So i generated a new world and the wind turbines worked fine i went back to the other one made two new ones (with cheated items) and they worked so i'm not sure what happened so they work now
