### ISSUE TITLE
Server crash connecting fluid pipe to Reactorcraft neutron absorber

### ISSUE THREAD

**Issue by Saereth** [aidancbrady/Mekanism#2959]
accidentally connected an ultimate mechanical pipe to a neutron absorber from reactor craft and the server crashed. Not sure if it's a Reika issue or Mek. Crashlog
http://pastebin.com/mCJZpNzG

reference report for reactorcraft:
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/245

edit: Reika says its on Mek's end

**Comment by aidancbrady** [comment]
This was fixed in an earlier version.
