### ISSUE TITLE
Unclear Syntax on BoxBlacklist.txt

### ISSUE THREAD

**Issue by Zero-Angel** [aidancbrady/Mekanism#2960]
I'm trying to blacklist decocraft items on the box blacklist due to it crashing the client (due to many structures taking up more than one block). This particular mod uses the same itemID, but different damage values to differentiate between the 500+ items in its repertoire.

BoxBlacklist.txt has this comment:
# Use this file to tell Mekanism which blocks should not be picked up by a cardboard box.
# Proper syntax is "NAME:META". Example (for stone):
# stone:0

Yet, the CSV file generated by NEI's item panel dump generates this type of info:
Item Name,Item ID,Item meta,Has NBT,Display Name
props:blockProps,963,0,false,"Unnamed Block, report to mod author."
props:blockFake,964,0,false,"Unnamed Block, report to mod author."
props:props,4553,0,false,Stuffed Creeper
props:props,4553,1,false,Wine Bottle
props:props,4553,2,false,Grandfather Clock
props:props,4553,3,false,Wood Blocks
...etc

Nothing I input works, so what is the proper syntax for blacklisting the items and can it be written into the comment of BoxBlacklist.txt?

**Comment by xenoswift** [comment]
Seems pretty straightforward. itemName:metaValue.
So if you wanted to blacklist Stuffed Creeper you would use:
props:0
And for Grandfather Clock
props:2
What have you been trying?

**Comment by aidancbrady** [comment]
Updated to be a bit more clear. Correct syntax is now "NAME META" instead of "NAME:META" to avoid domain confusion- for example, an entry for stone would be "minecraft:stone 0".
