### ISSUE TITLE
Induction matrix not outputing power

### ISSUE THREAD

**Issue by themechman** [aidancbrady/Mekanism#2962]
Not sure if I'm doing it wrong or what, but latest version will accept power from TE's Cryoducts, but not output to them.

![2015-09-13_10 56 58](https://cloud.githubusercontent.com/assets/2990361/9837227/4f15d31c-5a06-11e5-9447-ded3cbae0ab4.png)

This is not working either

![2015-09-13_11 01 00](https://cloud.githubusercontent.com/assets/2990361/9837241/c155362a-5a06-11e5-9afe-07b52f76ba6b.png)

**Comment by phantamanta44** [comment]
You need to shift+rclick the port with a configurator to toggle in/output.

**Comment by themechman** [comment]
Noted, Thanks!
