### ISSUE TITLE
Logistical sorter on double-wide chest behaves differently depending on which half item is in

### ISSUE THREAD

**Issue by Ricket** [aidancbrady/Mekanism#2964]
![mekanismlogisticalsorterbug](https://cloud.githubusercontent.com/assets/196978/9897032/ba5fea56-5c11-11e5-9ad6-2b41f3086cfc.png)

![mekanismlogisticalsorterbug2](https://cloud.githubusercontent.com/assets/196978/9897038/dea9fec4-5c11-11e5-87f4-e17dfcb592bb.png)

Setup like the above. Item doesn't matter.

If you drop the item in the bottom half of the chest, it never leaves the chest. If you drop it in the top half of the chest, it exits with the color.

If you enable auto-eject, then when you drop it in the bottom of the chest, it exits with no color; top half of chest exits with color.

This bug exists in 8.1.7.252, and not in 8.1.5.246 (the version that ships in FTB Horizons Daybreaker, which is what I am playing in).

**Comment by phantamanta44** [comment]
The two halves of the chest are different tile entities. I suggest you use IronChests (for the time being).

**Comment by Ricket** [comment]
Sure, we're evaluating other chest mods, but for now we just backed down to version 8.1.5.246 so that our chest organization system will work again. Since this is a regression, the fact that the chest is separate tile entities might be a reason it was overlooked.

**Comment by Ricket** [comment]
I wonder if it was introduced in 51f1c68f05880b4d60cc8824e4302b2c1e2fa2a3 -- the description message is suspiciously similar to this bug title...

@unpairedbracket ?

**Comment by phantamanta44** [comment]
Doesn't look like it. 51f1c68 looks more like a fix for logistical sorters looking in the wrong direction...?

**Comment by aidancbrady** [comment]
Thanks- I guess I forgot to pass my double-chest check into the sorter eject algorithm.  Should be fixed :)
