### ISSUE TITLE
Induction matrix disconnecting on logout

### ISSUE THREAD

**Issue by themechman** [aidancbrady/Mekanism#2965]
My simple induction matrix is in a chunk loaded area. Unfortunately once the last user logs out of the server, it dismantles the multiblock structure causing all the cables attached to disconnect.

Upon login, the matrix re-assembles showing the red particle effect, but all the energy that was being pumped into it was wasted.

**Comment by kotoroshinoto** [comment]
I can confirm that I see the red particle effect on login, but I have not confirmed whether it is actually disassembled or if that is simply the client reacting wrongly.

**Comment by themechman** [comment]
After spending quite some time trying this out in several environments, it appears that in chunkloaded areas, the disconnect is a graphics glitch. I'd probably put this as a very low priority.
