### ISSUE TITLE
MekanismGenerators not launching on servers

### ISSUE THREAD

**Issue by diamondpumpkin** [aidancbrady/Mekanism#2966]
When I start my server I get this error: http://pastebin.com/wVfe5pLY and MekanismGenerators does not work when I go onto the server. This works fine in single player.

Version MC: 1.7.10
Mekanism: All at 8.1.7
Forge: 10.13.4.1492

**Comment by Ricket** [comment]
Looks like your jar file is simply corrupt (jar is in zip format, the Java standard zip loader is choking on it). Try re-downloading it.

**Comment by diamondpumpkin** [comment]
Ahh thanks!
