### ISSUE TITLE
Logistical Sorter Mod ID filter is not filtering

### ISSUE THREAD

**Issue by Ricket** [aidancbrady/Mekanism#2967]
I use NEI to export items in order to view their mod ID. For example, mekanism is "mekanism" and Essential Craft 3 is "essentialcraft". I create a logistical sorter and choose Mod ID, and type the ID exactly into the box and click the checkmark. Usually it doesn't show any matching items; sometimes it shows a couple but not nearly the complete set of items from the mod.

For example I type `mekanism` and no results. `Mekanism` and no results. `*ekanis*` and the items shown are a few blocks, it cycles through 12 blocks, but this isn't nearly all the Mekanism items. I type `essentialcraft` and nothing, `*ssent*` and it only matches one block, which I visually identified as the "Compressed Drops" item from Essential Craft 3. It doesn't show or match any more (I tested if it matches anyway, and it doesn't).

I am running Mekanism 8.1.5.246 because I'm waiting for a fix to #2964 before I upgrade. Minecraft 1.7.10; a modified version of FTB Horizons Daybreaker.

**Comment by aidancbrady** [comment]
The reason you don't see many blocks cycled is due to the way the animation algorithm works- it only pulls from mod items and blocks that are registered with the Ore Dictionary. It should still filter the items as you intend.
