### ISSUE TITLE
cardboard box change extra utilities filing cabinet to advenced?

### ISSUE THREAD

**Issue by akasia** [aidancbrady/Mekanism#2969]
i just find out that cardboard box change extra utilities filing cabinet to advenced?
i just test it on 2 modpack olso so got same issues

**Comment by akasia** [comment]
ver Mekanism-1.7.10-8.1.7.252 this ver?

**Comment by aidancbrady** [comment]
This is an example of an interaction issue I can't do much about; I'd suggest placing the block on the blacklist.
