### ISSUE TITLE
[Bug/Mod conflict] Induction matrix does not show RF correctly when it has a capacity over 2000000000 RF

### ISSUE THREAD

**Issue by ringosham** [aidancbrady/Mekanism#2971]
I got a 5x5x5 induction matrix full of ultimate induction cells and one ultimate induction provider. From the matrix GUI, the energy count is fine, but I pointed myself over the induction port. Waila shows that I have something like "56567126/-9778687612 RF". At first I thought this is probably just a glitch of Waila, but I plugged the matrix to a computer from Opencomptuers. It returned my energy count wrongly and it sometimes even returned negatives! I am not sure if this is a mod conflict because I have seen others have no problems.

Here is a list of mods I installed to trigger this bug.
Forge 10.13.4.1492-1.7.10
ForgeMultipart 1.1.2.331 universal
CodeChickenCore 1.0.7.46 universal
CodeChickenLib 1.1.3.138 universal
CoFHCore 3.0.3-303 <-- Needed in order to show number of RF in machines in Waila
Mekanism 8.1.7.252
MekanismTools 8.1.7.252
MekanismGenerators 8.1.7.252
neiaddons 1.12.5.17
NEIIntergration 1.0.12
NotEnoughItems 1.0.5.118 universal
Opencomputers 1.5.18.36 universal
RFTools 3.35
Waila 1.5.9
Waila Harvestability 1.1.2
WailaNBT 1.4
Wawla 1.3.1

EDIT: Note that the GUI in the induction matrix works just fine.

**Comment by phantamanta44** [comment]
We should store the RF amounts as longs.

**Comment by ringosham** [comment]
I am pretty sure this is a bug in Mekanism since I have seen others let's play and they have no problems. Probably they are using a older version of Mekanism.

**Comment by XFactHD** [comment]
This is not really a bug, it's just the fact that multiblock batteries like the induction matrix are capable of storing more power than you can store as a number in an Integer. I don't know if the induction matrix has special waila compatibility. If it doesn't, then the problem simply is that waila sees the induction matrix as an RF handler and assumes that it can display the values as an integer because it knows that the RF API can only handle energy values up to Integer.MAX_VALUE (this is not a waila bug, don't report it to them!).

**Comment by ringosham** [comment]
I also tested with OpenComputers and RFTools' RF network monitor. It also gives me the incorrect RF.

**Comment by aidancbrady** [comment]
That is indeed the issue- it is not necessarily a Mekanism bug. I'll leave this open to remind myself to add a specific WAILA handler.

**Comment by aidancbrady** [comment]
There's actually not much that I can do to avoid this- the mod that adds the energy tooltips to WAILA would need to do a check for my double-based energy storage.

**Comment by ringosham** [comment]
Well..... I contacted CoFH about the issue and they refused to change their API(It uses integer) for compatability for the induction matrix. So.... there's that.

**Comment by XFactHD** [comment]
@ringosham they have their reasons in not changing their API. It was never intended to be used for such giant storage and if someone does it anyway, he has to do the compatibility too.

**Comment by ringosham** [comment]
@XFactHD Yeah I understand that. That sucked. :/
