### ISSUE TITLE
[crash] mekanism/enderio

### ISSUE THREAD

**Issue by karalys** [aidancbrady/Mekanism#2975]
bonjours a tous 
Sur ma partie solo en 1.7.10, lorsque je place un cable de gaz d'enderio sur l'electrolytic serparator minecraft crash et plus moyen de relancé ma save ! 
version de mekanism : 8.1.7.252 
version enderio 2.0.5.214
version forge 10.13.4.1448

quelqu'un peut il m'aidé ?? si vous voulez d'autre info demander moi

**Comment by Sandriell** [comment]
Your version of EnderIO is over a year old. You need to update.

**Comment by karalys** [comment]
ah d'accord bah je comprend mieux ^^ merci :)
