### ISSUE TITLE
request for coloring of mechanical (fluid) and pressurized (gas) tubes

### ISSUE THREAD

**Issue by The-Silver-Kid** [aidancbrady/Mekanism#2976]
Like the Logistical transport pipes (item) but for the fluid and gas tubes

**Comment by Ricket** [comment]
What? They already do, they're even color coded. Here's a screenshot of our reactor. You can see the water mechanical pipe running across the middle, and the darker blue heavy water pipe in the top right. If I had an empty mechanical pipe, it would be clear. The pressurized tubes lit up red have deuterium (it shows red in the reactor UI as well) and the blue ones contain tritium. The darkened ones in the bottom left are empty.

![2015-09-28 21_43_00-minecraft 1 7 10](https://cloud.githubusercontent.com/assets/196978/10153401/fa747cb6-6629-11e5-8381-4e787c653951.png)

**Comment by vedalken254** [comment]
@ricket I think he's trying to come up with fluid routing options like the logistical sorter does with items.

**Comment by Ricket** [comment]
@vedalken254 Oh I see.. Not that the tubes are colored, but that you would mix liquids/gases except they'd be assigned a color and separated later. I guess that's the request.

**Comment by vedalken254** [comment]
@ricket yeah. I can only guess that's what he's after.

**Comment by xenoswift** [comment]
You can put FMP covers between pipes to separate them.

**Comment by The-Silver-Kid** [comment]
@vedalken254 That is what it is

@xenoswift what is a FMP cover? i am not familiar with them

**Comment by vedalken254** [comment]
@The-Silver-Kid FMP is Forge MultiPart. Microblocks stuff basically... not what you're looking for unless you want to truly separate the pipes and keep them from connecting to each other.

**Comment by The-Silver-Kid** [comment]
@vedalken254 alright thanks ill use those for now

**Comment by Utildayael** [comment]
Ya Xenoswift's solution is the easiest I've found when you want to run gas/liquid pipes next to eachother. I'm sad I can't color them like the logistic [item] pipes to keep them from connecting.

**Comment by aidancbrady** [comment]
I don't see myself adding color support to other types of transmitters anytime soon, sorry.
