### ISSUE TITLE
Feature Request.

### ISSUE THREAD

**Issue by TheRealKANi** [aidancbrady/Mekanism#2979]
Hi aidancbrady..

Would it be possible to implement the ability to get the energy output of the fusion reactor.
I can see in the energy API there is no options to get energyOutput in OpenComputers - Computronics - Mekanism co-operation.

And one more thing, energyOutput and energyInput from Induction Matrixes would be super..
Currently there is no way of knowing how much goes in or out via OpenComputers..

Thanks in advance...

Kenneth

**Comment by aidancbrady** [comment]
Added "getProducing()" for Fusion Reactor.  Induction Matrixes actually already had that functionality, but it wasn't very obvious (named "getLastInput" and getLastOutput").  Renamed to getInput() and getOutput().
