### ISSUE TITLE
universal cables do not connect to with turret bases from the open modular turrets mod.

### ISSUE THREAD

**Issue by ctNOAH** [aidancbrady/Mekanism#2980]
The problem is that the universal cables do not connect with the turret bases from the open modular turrets mod. the only way to power the bases is to place an energy cube directly next to it.  
This issue is only in v8.1.7 of Mekanism. I've tested it with the previous version and i worked fine.

**Comment by jburrows82** [comment]
All the universal cables connect to the bases fine in *.183, and each appropriate tier works for me. Post a screenshot proving they won't connect, because *.183/8.1.7 is pictured in my screenshot.

http://pasteboard.co/16NGeQFn.png
