### ISSUE TITLE
oredictionificator won't accept galacticraft aluminum ore

### ISSUE THREAD

**Issue by kotoroshinoto** [aidancbrady/Mekanism#2982]
might have something to do with the fact that it is in 3 oredict entries. (aluminum aluminium and naturalaluminum)

**Comment by kotoroshinoto** [comment]
when I make it so it only exists in 1 entry with minetweaker, this behavior does get fixed, so it looks like a complication of the logic for the oredictionificator

**Comment by aidancbrady** [comment]
Not my fault, the oredictionificator maps to OreDict keys of corresponding names. Sorry :(

**Comment by kotoroshinoto** [comment]
The point is that if the mapping isn't 1:1 (if something is in more than 1 oredict) it seems to break

**Comment by kotoroshinoto** [comment]
similar problems with yellorium/uranium.

**Comment by aidancbrady** [comment]
In that case I'll take a look. It should be routing to the first entry on the list, though...

**Comment by aidancbrady** [comment]
Did some testing, everything is working nicely for me.  Make sure you're spelling the ore names correctly, use the Dictionary to double check- I know that Yellorium is spelled something else (yellorite I think) in the oredict registrations.

**Comment by kotoroshinoto** [comment]
What I was aiming to do is convert the uranium ores to yellorium for stacking purposes.

When I process it, it ends up as yellorium anyway, so its not a big deal if it doesn't work. its possible I need to update mechanism. I may be out of date.

I'll give it another go and see what I can get working.
