### ISSUE TITLE
Problems with machines not making the right gases. Pumps separator and so on

### ISSUE THREAD

**Issue by iceman11a** [aidancbrady/Mekanism#2985]
This is the video for the tutorial that I been watching to make a 5x ore processing.
https://www.youtube.com/watch?v=Nv0Iq1Ii2KY
I did make this earlier this year and it worked fine. How ever, now I can get some of the machines to make what I need in order for the processing to take place. 

The separator I should add brine to it and I should get Hydrogen, How ever I get Sodiam. When placing a machine like the separator down it has the same contents in the gui as the last machine that i placed down. I use the upgrades for the pumps to give me heavy water. That doesn't work. Just sends water. I been having other problems all so. I use the newest version 8.1.7.252 

I all so tries one of these on my test server with the separator and I got the same results, So I can't do any thing to make the gases I need to do a 5x ore processing. 

Last is there a videos that shows a newer version that the video that I have. The video I have is 1 year old. Is there some thing that not even a month or 2 old. 

Thanks
Ice

**Comment by phantamanta44** [comment]
Honestly, sodium makes more sense since Brine is essentially water and sodium chloride.

**Comment by iceman11a** [comment]
Is there an updated mod spotlight on this mod. There has to be some thing newer on this mod with all the gases that have been changed and added.

**Comment by aidancbrady** [comment]
If you search for "Mekanism v8 spotlight" there are plenty of videos that go over the new features.  I just ran a quick test and everything is working properly.
