### ISSUE TITLE
Cannot extract energy via cables from the laser amplifier

### ISSUE THREAD

**Issue by cornytrace** [aidancbrady/Mekanism#2987]
According to the issue and commit message of some time ago, you can extract rf/joule power from laser amplifiers, forming a wireless energy transport network.
However, while you can connect universal cables to the amplifier, it does not actually output any power.
I'm on the latest release via The 1.7.10 Pack.

**Comment by aidancbrady** [comment]
It does not output power unless you change the connected segment of cable to "pull" mode with a configurator.
