### ISSUE TITLE
Items not flowing properly when differently coloured pipes placed adjacently

### ISSUE THREAD

**Issue by teeg82** [aidancbrady/Mekanism#2990]
**Summary**
I have a set of basic logistical pipes that end up crossing adjacent to a set of advanced logistics pipes. They aren't connected as they're coloured differently. In the second screen shot below, when I place the basic yellow pipe that is directly adjacent to the advanced green pipe, the flow of items from the black and yellow basic pipes cease, and the items bob up and down at the bottom of the pipe, and go no where.

First screen shot, black and yellow basic logistical pipes connecting to JABBA barrels:
![2015-10-13_15 58 39](https://cloud.githubusercontent.com/assets/5384181/10466826/49d9eeb2-71c4-11e5-97db-a398c1d19573.png)

Its hard to see without an animation, but you can see the gravel at the bottom of the pipe, and it merely bobs up and down, going no where.

Second screen shot, yellow pipe is next to a green pipe.
![2015-10-13_15 59 34](https://cloud.githubusercontent.com/assets/5384181/10466912/ee3d2438-71c4-11e5-9079-fd5a3c357a87.png)

The instant that yellow pipe is placed, the flow of items from both the black and yellow pipes cease (items bob up and down at the beginning of the pipe.

**Important to note** The advanced pipe with the green is part of the system that transports items INTO the barrels that the yellow and black pipes are attempting to draw from, however they are (or at least should be) two completely separate systems.

My expectation was that the pipe systems wouldn't interfere with eachother if they're not connected through common / no colours, however there seems to be some kind of interference going on. Let me know if this is an actual bug, or whether I'm simply doing something wrong.

**Comment by vixblu** [comment]
What happens if you reduce the black coloring on those pipes? Start coloring black like you did with the yellow line, so no black at the section (first screenshot).

**Comment by teeg82** [comment]
So you mean something like this?
![2015-10-24_20 00 30](https://cloud.githubusercontent.com/assets/5384181/10713374/34411ade-7a8a-11e5-83a7-228b29b96c95.png)

If so yes, that was one of the things I tried. My solution after posting this was ultimately to fix the pipes in the second screen shot so that they weren't adjacent.

The stream of sand you're seeing is coming from a machine further up which is connected to a PULL which normally goes further up the pipe to the only PUSH connection in that network. The sand barrel is, as you can see, also set to PULL mode too, so there's no reason the sand should have come DOWN from the machine, yet when I rearranged the pipes back to their problematic configuration to try your suggestion, the sand all went down the pipe and bounced up and down, along with the gravel.

The length of the colour doesn't seem to make a difference

**Comment by vixblu** [comment]
Maybe the bouncing sand had no way (yet) to go somewhere? In one of my builds I've just upgraded the transporter cables (from basic to advanced, so I can pull stacks at a faster rate), and threw in restrictive tubes at some spots, that seemed to help with the wandering items going everywhere/bouncing. You also may want to put an diversion transporter at that push connection, to give it an higher priority.

**Comment by teeg82** [comment]
Cool I'll consider a diversion transporter next time. I actually eventually replaced them with ender io item conduits once I got enough ender pearls, so its partially moot for me now, but I'd still like to try and find a solution if possible, as it may affect and confuse other people too.

The bouncing is not quite the bouncing you may be thinking of where it flows back and forth through the length of the tube. You see the gravel on the right side in the latest screen shot? If the pipes are set up as I've described, that right there is about as far up the pipe as they go; the items "poke their heads" up, and just bob up and down. I'll try and post a gifycat animation later if possible.

If it helps, here's a simplified drawing of the scenario:
<img width="240" alt="screen shot 2015-10-26 at 4 16 23 pm" src="https://cloud.githubusercontent.com/assets/5384181/10741211/f892df3a-7bfc-11e5-8de3-5c69aa5c3c3f.png">

When the green and black touch like that, that's where the problem occurs. It should technically be two different networks, and even though they do not connect due to the difference in colour, the system almost behaves as though they are. Its like the algorithm falsely recognizes that a path exists, calculates the shortest path to be the exit point, somehow ignoring that the point is strictly a PUSH, and then re-ingests the item it spat out, ad infinitum.

**Comment by vixblu** [comment]
Ah yes, I recognize the behaviour, it's quite prioritizing inventories despite the configuration of pipes. Spacing out is what I usually end up with...

**Comment by aidancbrady** [comment]
I just did some testing with the scenario described and wasn't able to reproduce this issue.  I was having some pathfinding issues in an earlier version- are you using 8.1.7?  Gonna close this until further notice.

**Comment by teeg82** [comment]
Yes, is the 8.1.7.252 build. I will attempt reproduce this in a different setting and see if I can provide more information if possible.
