### ISSUE TITLE
[REQUEST] Fusion Reactor using Liquid Lithium instead of Tritium

### ISSUE THREAD

**Issue by nintendow131** [aidancbrady/Mekanism#2992]
At the moment, the FR uses Deuterium and Tritium. I have the suggestion, that you can use Deuterium and Liquid Lithium. The Lithium gets converted into Tritium by neutrons produced by D-D/D-He³/D-T Fusion (D-D creates He³ and T, wich react further with D). You would need a lot more Energy to ignite the Reactor however. Maybe you could also be able to just use D-D.

**Comment by aidancbrady** [comment]
I'd rather just stick with D-T for now, it's simple enough and I like the complexity of making the products.  Maybe I could extend the fuel range in the future.
