### ISSUE TITLE
[REQUEST] Steam Cracker (alternative production of Ethylene)

### ISSUE THREAD

**Issue by nintendow131** [aidancbrady/Mekanism#2993]
An extra machine, that uses Water Vapor to crack Buildcraft Oil into Ethylene and Methane. You get one bucket of Methane and Ethylene, however Methane only produces half as much as Ethylene and the Cracker needs energy to work. The Cracker can be build as a multiblock. When its a multiblock, it has higher speed, a bit higher efficenciey, but higher energy usage.

**Comment by TheProdigy22** [comment]
This wouldn't need to be a multi block structure, as speed upgrades does exactly that. The energy requirements would have to be high and crafting recipe would need to be expensive (reinforced alloys?) And maybe Mekanism could have it's own type of oil that spawns in pools like lava does. This is a good idea, but I don't think there needs to be two ways to get ethylene.

**Comment by aidancbrady** [comment]
I'd rather not add new content purely to integrate with BuildCraft, and I don't have plans to add my own form of oil anytime soon. Still, I truly appreciate the suggestion; it's not off the table, just not something I see for v9 :)
