### ISSUE TITLE
Ender io and mekanism in minecraft 1.7.10

### ISSUE THREAD

**Issue by Idento** [aidancbrady/Mekanism#2994]
Hello,

I have a problem with mekanism, mekanism it's not compatible with ender io, i can't connect cable and other generator. 

EnderIO-1.7.10-2.2.8.381; Mekanism 1.7.10-8.1.7.252; Forge10.13.4.1448-1.7.10

http://image.noelshack.com/fichiers/2015/42/1445078899-2015-10-17-12-45-22.png
http://image.noelshack.com/fichiers/2015/42/1445078900-2015-10-17-12-47-02.png

if anyone can help me please.

**Comment by vedalken254** [comment]
Last I remember, you'll need CoFHCore added. It's required by the mekanism devs because it makes their code for dependencies less complex iirc. You won't need anything except CoFHCore.

**Comment by Idento** [comment]
Oh yes, thanks you! I did not know, big thanks!

**Comment by vedalken254** [comment]
No problem! I assume you've already tested my solution? If so and it fixed it, close out this github issue.
