### ISSUE TITLE
Energy Efficeny Upgrade Bug

### ISSUE THREAD

**Issue by Speiger** [aidancbrady/Mekanism#2995]
The Energy Efficency Upgrade does not work in a Electronic Seperator.
The Capacity of the Energy Storage is going up but the Powercost does not go down.
Problem is. I am making a custom Challange. Run my base with only 120RF/t Production.
And these Electronic Seperators (i know the name is wrong but you know what i mean) drain a huge power.
I am playing on a Server with Mekanism 8.1.7.252. (ModSauce2)
Could you fix that please so i can run my 4x Ore Processing without draining like 300 Rf per tick?

**Comment by mercsniper** [comment]
It is like this so that the Hydrogen Power generation does not produce more
power than it requires. This will not be fixed as it is working as
intended.

On Tue, Oct 20, 2015 at 2:13 PM, Speiger <notifications@github.com> wrote:

> The Energy Efficency Upgrade does not work in a Electronic Seperator.
> The Capacity of the Energy Storage is going up but the Powercost does not
> go down.
> Problem is. I am making a custom Challange. Run my base with only 120RF/t
> Production.
> And these Electronic Seperators (i know the name is wrong but you know
> what i mean) drain a huge power.
> I am playing on a Server with Mekanism 8.1.7.252. (ModSauce2)
> Could you fix that please so i can run my 4x Ore Processing without
> draining like 300 Rf per tick?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aidancbrady/Mekanism/issues/2995>.
>



-- 
Brad

**Comment by Speiger** [comment]
:( thats sad....

**Comment by mercsniper** [comment]
Running a hydrogen generator off of the water splitting electrolytic
separator will be cost neutral to your Challenge, since the hydrogen can be
used to power the electrolytic separator, and still be separate from your
production chain. Your later separators will not have that luxury though.

On Tue, Oct 20, 2015 at 2:27 PM, Speiger <notifications@github.com> wrote:

> :( thats sad....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aidancbrady/Mekanism/issues/2995#issuecomment-149656886>
> .
>



-- 
Brad

**Comment by Speiger** [comment]
Well problem is i want to make 4x ore Processing with only 120 RF per tick. It would be possible if not the Hydrogen and the Cloride processing would eat up 200 RF per tick... Could you make maybe a Combined machine which produces the Hydrogen Cloride and the Oxigen only^^" At the powercost of all 3 machines together but it is efficency upgradeable?

**Comment by mercsniper** [comment]
I am not the Dev, but I don't think Aidan has a plan to include such a
machine, but I will let him comment when he has the time.

On Tue, Oct 20, 2015 at 2:43 PM, Speiger <notifications@github.com> wrote:

> Well problem is i want to make 4x ore Processing with only 120 RF per
> tick. It would be possible if not the Hydrogen and the Cloride processing
> would eat up 200 RF per tick... Could you make maybe a Combined machine
> which produces the Hydrogen Cloride and the Oxigen only^^" At the powercost
> of all 3 machines together but it is efficency upgradeable?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aidancbrady/Mekanism/issues/2995#issuecomment-149661771>
> .
>



-- 
Brad

**Comment by Speiger** [comment]
Would be great. That is the only thing which allows not Efficent build and i can say that my Build is pretty efficent (time wise maybe not but its running smooth) if we count only machines that process resources (not the gas production) i am at about 20-40 RF per tick xD constantly without problems. xD

**Comment by phantamanta44** [comment]
I feel like such a machine would undermine the theme of this mod, being extraneous and fairly unrealistic; the hydrogen in water has to go somewhere, right?
