### ISSUE TITLE
Waila tooltip showing Bounding Block for multiblock structures

### ISSUE THREAD

**Issue by mrogaski** [aidancbrady/Mekanism#2996]
The Waila tooltip for multiblock structures is showing "Bounding Block" instead of the structure name.

Mekanism 8.1.7.252
Forge 1.7.10-10.13.4.1448
Waila 1.5.10

![2015-10-20_21 22 58](https://cloud.githubusercontent.com/assets/1449231/10625500/d4a519ce-7771-11e5-979d-0ce8b7455f20.png)

**Comment by aidancbrady** [comment]
Fixed!

**Comment by Mementh** [comment]
woot :) thanks

**Comment by mrogaski** [comment]
This bug is still present in 8.1.8.258 and 8.1.9.265.
