### ISSUE TITLE
Using a cardboard box on a ChromatiCraft crystal pylon will cause a server to CTD

### ISSUE THREAD

**Issue by Hypocrisy** [aidancbrady/Mekanism#2997]
I know this doesn't pertain to you since you don't develop ChromatiCraft and can't do anything to stop this interaction but I just thought I would let people know to prevent crashes.

**Comment by aidancbrady** [comment]
I probably can't do anything, but would you mind providing a log?

**Comment by Hypocrisy** [comment]
Sorry, I was on a public server when I caused the crash so I do not have access to the log. I spoke to Reika, however, and they stated that the crash was probably one they deliberately set up to prevent world corruption for moving those entities (I can't see how it would but I'm not a developer). 

They asked for a blacklist on the box.
