### ISSUE TITLE
Possible Mod Conflict - Able to walk through Crusher

### ISSUE THREAD

**Issue by Harkole** [aidancbrady/Mekanism#2998]
Have the Matter Overdrive mod installed and now that I've become an Android I'm able to walk through (and not stand on to) the crusher machine. I'm still able to right click interact with the machine and the machine still works normally.

Cross posted on Mater Overdrive as #278

**Comment by Mementh** [comment]
i have noticed this int he nomads pack.. sometimes i fall through it and can't stand on it

**Comment by aidancbrady** [comment]
Definitely not a Mekanism issue.
