### ISSUE TITLE
Unable to place tank in Chemical Crystallizer using automation

### ISSUE THREAD

**Issue by dieselfuelonly** [aidancbrady/Mekanism#2999]
The Chemical Crystallizer is unable to accept a tank of clean ore slurry through any means of automation, even though it has a purple item slot that should accept it.  Placing the tank in by hand works fine.

On another note, it would also be extremely useful to be able to condensate clean ore slurries into liquid form.

**Comment by vixblu** [comment]
I think the gas tanks are literally handy :-)

I guess you've separated processes, have a large distance between machinery/contraptions? That's why you choose to use gas tanks instead of direct input/piping?

(I have my chemical machinery lined up next to each other, feeding the next one directly)

**Comment by dieselfuelonly** [comment]
Actually, kind of the opposite.  With 5x ore processing is the way that mekanism gas tubes distribute clean slurry to the crystallizers leads to a small amount getting left over in the crystallizer,  jamming the whole system up if a different type of clean slurry comes through.  

My plan was to have a bunch of empty tanks basically work in a loop - the tanks fill up with clean slurry, get picked up when full (was gonna use a SFM block gate, but it can't break the tanks apparently), then deposit the tank into a crystallizer.  Since a full tank has an even amount of slurry in it, the crystallizer completely processes all the slurry and is empty.  Once the tank was empty, it would get sucked out and get back into the loop to be refilled with more slurry. 

The thing I am trying to avoid is having a different set of crystallizers for each type of ore slurry.  It would be incredibly messy and a huge waste of both in-game and server resources.

**Comment by vixblu** [comment]
Aha, that would be nice indeed if would work like that for that kind of situation.

I think I'm used to set up more Mek machinery for convenience (each ore has it's own line of chemical machines) and/or put up with manually configuring/finetuning at the start or during the process. Also: I'm on single-player w/small modpack. But I'm feeling your need :-)

**Comment by Mementh** [comment]
honestly if your at 5x process time the ammount of "waste" is minimal physically.. now size wise it is.. but honestly there is no way to prevent this unless it can process only one ore at a time .. 
my advice is to store the slurry and run it though when you know you have full runs without leftovers ..

**Comment by aidancbrady** [comment]
Thanks for the pointer, this was definitely not intentional.  Crystalizers can now accept gas tanks.
