### ISSUE TITLE
Universal Cables not working with Railcraft Steam Turbines

### ISSUE THREAD

**Issue by artturnip** [aidancbrady/Mekanism#3000]
I guess the title says it all...

Is this intentional and, if so, would it be possible to get the Universal cables to carry Railcraft charge as well as IC2 EU?

Mekanism version: 8.1.7
Railcraft version: 9.7.0.0

**Comment by aidancbrady** [comment]
Merging with #2989

**Comment by artturnip** [comment]
Was this issue closed because it's not an issue with Mekanism?
