### ISSUE TITLE
Wrench cannot pick up energy cubes

### ISSUE THREAD

**Issue by mcgraj3** [aidancbrady/Mekanism#3001]
I haven't played for about a month and just got back to the game. I started a new world, built some machines, then whipped up a Yeta Wrench to rearrange the temporary machine setup.

The Yeta Wrench works on everything EXCEPT Energy Cubes. I can switch the orientation of the output, but it will not allow me to pick up the block. I tried a few other mod wrenches to no avail. I tried to break it manually, which just ended up destroying it. So basically, in survival, once I place this block it is stuck there.

Everything was working before I came back to the game. The only thing that might have changed was the Java version (currently Version 8 Update 65, build 1.8.0-65-b17).

I did had an older version of Mekanism (Mekanism-1.7.10-8.1.5.246) so I updated that. No change.

Currently running: **Mekanism-1.7.10-8.1.7.252** on **1.7.10-Forge10.13.4.1448-1.7.10**

Any clue as to why this issue is occuring? Anything else I could try? I didn't see any other conflicts. Thanks.

*edit* - I did try picking up this block with a pickaxe which is a workaround, but as far as I remember, I never needed it as wrenches (Yeta Wrench in my case) did the job. The wiki confirms that the wrench will pick up the block when shift-right clicking.

**Comment by aidancbrady** [comment]
Can't reproduce this- I'm able to pick up energy cubes just fine.
