### ISSUE TITLE
Crash when opening AE2 crafting terminal (Induction matrix related?)

### ISSUE THREAD

**Issue by Zaflis** [aidancbrady/Mekanism#3003]
This started after i made 4 Induction Casings and put it in the ME drive. Server stays up but i crash everytime i restart Minecraft and right click terminal. I've not had crashes ever before this, and we are far in almost endgame base. I have built other Mekanism stuff with AE2 up to elite factories etc. Was going to add Induction Matrix autocrafting recipes to AE2, but now i can't play at all.

http://pastebin.com/UzUwG6T8

Mekanism-1.7.10-8.1.6.250
appliedenergistics2-rv3-alpha-9
Botania r1.7-226

**Comment by XFactHD** [comment]
This seems to be an odd interaction between Botania and Mekanism.

**Comment by Zaflis** [comment]
I figured out something new today. I realized that i can use wireless terminal, and that there were no Induction casings in system. They were in fact on the crafting terminal itself. So i wrenched it and items flew out. ME system is no longer crashing.

But then i put 1 induction casing on ordinary wooden crafting table and i crash immediately.

**Comment by aidancbrady** [comment]
Fixed :)
