### ISSUE TITLE
Bins are still able to duplicate items.

### ISSUE THREAD

**Issue by Hypocrisy** [aidancbrady/Mekanism#3004]
As you have implemented, Bins are no longer able to stack. However, there is a work around that still allows for duplication but not in the same way as the previous issue #2682.

Putting a bin and a stack of diamonds in a crafting grid will create a diamond bin but before you create the item you can place as many empty bins on top of the original bin and add to the stack which will create a bin filled with a stack of diamonds but will only actually deplete one from your stack in the crafting grid (leaving you with 63 diamonds in your grid for a new total of 127 diamonds).

Mekanism version 8.1.7.252

ETA: Should note that there are even more funky things going on here. If you shift + click, it will duplicate the bins with the stacks in it as well and also will most of the time cause your game to crash.

**Comment by VT-14** [comment]
May I suggest changing bins to have a GUI accessible from the hot bar (like various bags, backpacks, satchels, etc)?

**Comment by aidancbrady** [comment]
Added a check- bin crafting recipe no longer works when the stack size is greater than one.  I think the crafting interaction is much more efficient than an interface.
