### ISSUE TITLE
Wind turbines should not work to close togther

### ISSUE THREAD

**Issue by Dijkstra1** [aidancbrady/Mekanism#3005]
![2015-10-30_00 46 56](https://cloud.githubusercontent.com/assets/11648771/10844243/0949b122-7ef6-11e5-8142-11b4d313d575.png)

It easy to see from the picture what I am getting on about wind turbines should not work if there blades overlap

**Comment by mercsniper** [comment]
I believe the mod author was going for the realism of space when designing
the Turbines. I doubt he will change their behavior in this regard.

On Fri, Oct 30, 2015 at 7:07 AM, Dijkstra1 <notifications@github.com> wrote:

> [image: 2015-10-30_00 46 56]
> <https://cloud.githubusercontent.com/assets/11648771/10844243/0949b122-7ef6-11e5-8142-11b4d313d575.png>
>
> It easy to see from the picture what I am getting on about wind turbines
> work just even if the blades over lap
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aidancbrady/Mekanism/issues/3005>.
>



-- 
Brad

**Comment by mcgraj3** [comment]
@mercsniper I think you misunderstood. The wind turbines at present work close together. The picture that Dijkstra1 posted shows them working like that. They should be a little more realistic and not work if directly adjacent to another wind turbine.

I am thinking that a 5 block radius around the wind turbines would be a little more realistic. It could probably be implemented with a simple check when placing the wind turbine.

**Comment by EzerArch** [comment]
The title should be changed to *"Wind turbines should __not__ work to close together"*.

**Comment by Dijkstra1** [comment]
Yes I will change the title I must missed a word out.

**Comment by aidancbrady** [comment]
I had a check for this earlier, but there's really no way to avoid this without doing environment checks which are pretty CPU intensive.  I'm happy with the current functionality.
