### ISSUE TITLE
[Request] Bin input/output port on back

### ISSUE THREAD

**Issue by mcgraj3** [aidancbrady/Mekanism#3006]
I really like the idea of Bins and have used similar blocks in other mods (Barrels from Factorization). However, I have tightened up my mod pack that removes a few of these (my modpack revolves around Mekanism v8 being the core of the modpack, where other mods are added to fill gaps, not add unnecessary redundancy). I find Bins very useful, but that usefulness is lost once I move forward into Applied Energistics computer systems. I enjoy the the way they look (stacked vertically into a wall), so I would like them to continue having a place in my system.

I would like to see Bins adjusted so that it is possible to input and output items from the back of bins. The reasoning behind this is that a wall of bins cannot be automated without wasting a lot of space. I like to see my inventory for certain blocks and prefer Bins over AE2's interface panels.

Please consider adding this functionality. Thank you for your time and effort.

**Comment by TheProdigy22** [comment]
Maybe a way for the Configurator to set which side for the bin's in/out?

**Comment by aidancbrady** [comment]
I'd rather stick with the current bin functionality for now. Perhaps I'll implement this later with some kind of sneaky inventory access device.
