### ISSUE TITLE
Crash when automating seed analyzer

### ISSUE THREAD

**Issue by drz2k** [aidancbrady/Mekanism#3008]
As a tester of my pack reported here : MyM-ModpackTeam/hypovolemia#88

We are on 1.4.2 but I didnt see any fix related to this.

Singleplayer crash report - http://paste.ee/p/DGsao

The setup - http://imgur.com/MMsfB85

"

I'm trying to automate my seed analyzer. These are the crashes I've encountered. Building the system doesn't cause the crash, but when the system tries to move any seed, the crash happens.

chest->mekanism logistical transporter->seed analyzer => server crash
seed analyzer->translocator->seed storage => client crash
"

Reported to agricraft, but XU nodes work well : https://github.com/InfinityRaider/AgriCraft/issues/441

**Comment by aidancbrady** [comment]
Try updating Mekanism.

**Comment by drz2k** [comment]
Mekanism-1.7.10-8.1.7.252

Dont think some localization fixes or xp stuff will magically fix this.
