### ISSUE TITLE
[Feature request] Crafting Machine

### ISSUE THREAD

**Issue by vixblu** [aidancbrady/Mekanism#3010]
I'd like to have a way to autocraft with Mekanism, and I wouldn't mind if it's costly to craft or energy draining, or that I'll have to build multiple machines for those nesting recipes. For now I'm crafting manually, or use another mod like Easy Crafting, the latter is breaking the immersion a bit and the first one can become quite boring and even painful (RSI) sometimes.

I did some thought and have come up with this:
* I'd like it to be a multi-block structure/machine of 3x1x1 (built horizontally or vertically).
* It would contain a sorter with filters for nine numbered slots (to correspond with a 3x3 crafting grid).
* The sides should be configured to allocate input (min 1/max 9), output min 1/max 2) and energy (min 1/max 12) slots.
* Instead of using the sorter filters one could also appoint 9 input slots in the GUI for direct input from sides.

The recipe for a simple machine could contain a combiner, a sorter and a crafting bench, and preferably be upgradeable into factories as well.

(edit: numbers)

**Comment by aidancbrady** [comment]
Merging with #2872
