### ISSUE TITLE
Feature: culling gas tanks similar to not-generating prefilled liquid tanks NEI/creative

### ISSUE THREAD

**Issue by usafphoenix** [aidancbrady/Mekanism#3013]
is it possible to add a config option or feature to reduce lag in NEI/creative to not generate /prefilled gas tanks similar to the way the liquid portable tanks were done? I always run mekanism with the portable tanks prefilled setting as "false", but am looking for more ways to improve search-lag in NEI/creative

**Comment by aidancbrady** [comment]
Prefilled gas tanks should be causing little to no lag at all; I definitely don't think they would be the cause of a problem.
