### ISSUE TITLE
[Request] Farming Machine + Digital Miner Auto-Restart

### ISSUE THREAD

**Issue by VT-14** [aidancbrady/Mekanism#3015]
After playing around with Biofuel and seeing its potential, I noticed that Mekanism doesn't have any automated farming (as far as I could find).  I feel that an auto-farming system would be a good addition to a mod that has a biofuel option.  

I think this could be added to the Digital Miner by adding a plant filter that will harvest fully grown plants, and give the Miner an auto-restart option to continually scan an area (a feature that would also prove useful for a cobblestone generator).  Depending on how the auto-replace works with plants, it could supply replanting.

I believe such a solution would accommodate both tree and crop farms, and satisfy #1630

**Comment by Gazmer** [comment]
Bit uninspired don't you think? I mean we do have a robot running around doing nothing but follow us.

**Comment by VT-14** [comment]
The Digital Miner is the lazy, somewhat small change that I picked as I assume it would take relatively little coding time compared to an entirely new machine or another new mechanic.  I purposefully picked it because of that due to this mod being pushed to the back burner as the owner is busy with school.

That said, my request is with the title.  I want an automated farming mechanic (I don't care how it is done), and I want an auto-restart function on the Digital Miner (Still useful for gathering cobblestone, Obsidian, and gravity falling blocks as the DM mines from the bottom up [last time I checked]).

Another idea I have is to make a machine to do it, either out in the world or completely internal.  Perhaps a Hydroponics Bay could be an internal machine for crops; though another machine would need to be used for a tree farm (and that would probably need to be external anyway).

Repurposing a Robit could also work, though it seems rather arbitrary to me.  A Robit is currently a 3x3 Crafting Grid, Chest, Furnace, and Anvil that follows you around and will pick stuff up for you.  Repurposing it into a farming device seems somewhat random and limited.  It could be turned into (or upgraded) into a utility robot, and could add abilities similar to Thaumcraft's golems.  I think that would be a cool addition, but would be a large one that we almost certainly wouldn't see until Mekanism v9 at the earliest.

**Comment by Gazmer** [comment]
Point taken and considered. Now I'm off to look up what a hydroponic bay is.

**Comment by Gazmer** [comment]
And a hydroponic bay is a great idea for the farms in Mekanism in my eyes. But my eyes are not the ones that have any power.

**Comment by aidancbrady** [comment]
I'm already considering adding some form of farming machine in the near future so I think this would be a bit redundant. Thanks for the feature request, though!
