### ISSUE TITLE
use logistical transporter on special inventory

### ISSUE THREAD

**Issue by ken2812221** [aidancbrady/Mekanism#3018]
I try to use logistical transporter to transfer item to tinker smeltery, but I put 1 stack in chest, it only has one item in smelter inventory
![2015-11-17_04 10 17](https://cloud.githubusercontent.com/assets/11154118/11193401/778c8d1e-8ce1-11e5-900c-b867f803724a.png)
![2015-11-17_04 10 55](https://cloud.githubusercontent.com/assets/11154118/11193404/7a5a0a3a-8ce1-11e5-9551-bfdee6d11851.png)
![2015-11-17_04 11 06](https://cloud.githubusercontent.com/assets/11154118/11193408/7bfe76d2-8ce1-11e5-9908-90a704df4c4e.png)

**Comment by Chupp4-Jo3** [comment]
Just wondering does it delete the other items or just move them one at a time?

**Comment by ariscop** [comment]
@Chupp4-Jo3 Deletes them outright. When using an advanced pipe for example, it'll take an 8 stack, which after insertion turns into a 1 stack, effectively deleting 7 of that item

Happens with the tinkers smeltery and thaumcraft pedestals, which means you can't really automate either with mekanism :(

**Comment by aidancbrady** [comment]
This is fixed for v9, thanks!  I was forgetting to take into account the inventory's item stack limit when actually placing the blocks into the inventory.
