### ISSUE TITLE
Shift clicking bin's dupe

### ISSUE THREAD

**Issue by Detroitiron** [aidancbrady/Mekanism#3019]
When shift clicking a bin from a crafting grid where you are filling it with material I discovered that it will put several different bins in your inventory with varying inventory sizes of the item you where using. 

I discovered this when putting a stack of cobblestone in my bin in my players crafting grid. I shift clicked it out of my players crafting grid and suddenly my inventory filled with around 10 bins with varying amounts of cobblestone that added up to well over the combined storage size of the original bin. I was able to duplicate this several times with varying levels of cobblestone. I am not sure if it works on other storage items besides cobblestone since I was sick of filling my inventory with bins.

**Comment by aidancbrady** [comment]
Should be fixed
