### ISSUE TITLE
Mod compatibility: minechem

### ISSUE THREAD

**Issue by NightOps007** [aidancbrady/Mekanism#3020]
So, minechem allows for all of its elements and compounds to be capable of being stored in tanks as liquids. I've been trying to find a way using minetweaker to make the oxygen and hydrogen from minechem interchangeable with their equivalent gases in liquid form from mekanism. There are other compounds I'd like to try to script compatibility with such as ethylene, etc... I'm having trouble identifying the gases in their liquid forms in the script. I imagine it is identified by something like: mekanism:gasLiquidOxygen or mekanism:liquidOxygen or some sort. Could you tell me how I might achieve my goal?

**Comment by spannerman79** [comment]
Its been awhile since I had Minetweaker installed but can't you hold the source block (obtained via NEI) in hand and run `/mt hand` to give you the correct info?

**Comment by aidancbrady** [comment]
For liquid versions of Mekanism gasses, I register them using only their lowercase names- for example, "oxygen" or "hydrogen."  Ethylene is registered as "ethene."
