### ISSUE TITLE
IC2 Chem Reactor conflict

### ISSUE THREAD

**Issue by Yahwehdo** [aidancbrady/Mekanism#3021]
I found myself unable to place Chlorine into an IC2 chemical reactor to make titanium tetrachloride (probably erroneous info on the recipe).  I found the chem reactor would not accept it, and I had to remove mods one-by-one until I got it to work again.  Turns out, removing mekanism fixed the problem.  Mekanism also prevented me from inserting oxygen into my gregtech electric blast furnace.  I don't know why, but I've had to remove mekanism till a fix is found!  Letting you know.  Thanks!

**Comment by aidancbrady** [comment]
This is not a Mekanism issue- it is likely IC2 or GregTech are improperly interfacing with FluidRegistry.
