### ISSUE TITLE
[Crash-report] Mekanism 8.1.7.252: Crashes then placing Induction Casings in crafting tables

### ISSUE THREAD

**Issue by Stekeblad** [aidancbrady/Mekanism#3023]
The game crashes then trying to place Induction Casings in a crafting table (tested in vanilla crafting table, Tinkers' Construct crafting station and ME Crafting Terminal). It seems to crash then placing the items by holding down a mouse button and draging the cursor. I have also tried to place the casings in a crafting table normaly but that does not seems to work. It's possible to place the Casings in a crafting without crashing, but its very difficult, managed to do it once or twice. (Can't reproduce it)

Does not help to try placing the casings one and one. - crash
shift-clicking in the items using AE and NEI does not work - crash
    -After restarting the game, open the crafting terminal crashes the game, need to wrench it down.
Click-and-draging out the items in your inventory (both then a crafting table is open and just in your normal inventory) does not make it crash.

A quick look at the crash report says that Botania may be involved (I have Botania version r1.7-228)

A crash report from one of all my tests on this are attached here.

[crash-2015-11-30_18.43.59-client.txt](https://github.com/aidancbrady/Mekanism/files/47592/crash-2015-11-30_18.43.59-client.txt)

Information about the modpack I'm using (if it may be usefull)
Hermitcraft Modsauce 2 (2.2.4.0) (AT-Launcher) but with open peripherals core/addons/integration added.
Fastcraft is not in the pack (it's often said to say if this is present or not)

**Comment by aidancbrady** [comment]
Fixed!
