### ISSUE TITLE
[Question] Top Tier Generators?

### ISSUE THREAD

**Issue by TheProdigy22** [aidancbrady/Mekanism#3024]
I loved the Hydrogen generators that were the huge producers for energy, but now there is no top tier generator to run large bases on. I would like to know what the plan is for high tier power generation

**Comment by TheProdigy22** [comment]
BTW, I love the Hydrogen batteries idea, it is a really cheap and effective energy storage system. I just don't know what to do for huge amounts of energy demand.

**Comment by cloakable** [comment]
The fusion reactor produces 100KRF/t per injection level, minimum 2, even numbers only. So it starts at 200kRF/t and scales to 9800KRF/t, though you'll need an extensive tritium/deuterium production setup to produce the 48mb/t needed of each.

**Comment by mercsniper** [comment]
I would agree a way to upgrade gas generators as a median to fusion reactor would be an idea. That way you aren't running 2^X ethylene generators



—

**Comment by TheProdigy22** [comment]
I feel like gas burning generators should have another way to make a positive feedback loop, of course more costly but a second option to the fusion reactor.

**Comment by VT-14** [comment]
Bio-fuel -> Ethylene is good step before Fusion Reactor if you can set up a fast auto farm.  Each Gas-Burning Generator nets something like 200 RF/t and a single upgraded setup can supply hundreds of generators (lag possible).  The setup also generates excess Oxygen for 3x ore processing.

Only real issue is you need a (near) constant supply of Bio Fuel, which I have been unable to easily get a constant supply of with Mekanism alone.

A Fusion Reactor is the end power generator, but very expensive and large (and can cause some lag due to the fuel production).

**Comment by mercsniper** [comment]
We know where the issues lie, its just a matter of finding solutions that
Aiden agrees with and has time to code with when not dealing with school.
Upgrading generators seems like a possible solution, requiring more fuel
for an equal production of more electricity seems like the best route. This
would also assist with the hydrogen side with a fully upgraded electrolytic
separator.

On Tue, Dec 1, 2015 at 3:08 PM, VT-14 <notifications@github.com> wrote:

> Bio-fuel -> Ethylene is good step before Fusion Reactor if you can set up
> a fast auto farm. Each Gas-Burning Generator nets something like 200 RF/t
> and a single upgraded setup can supply hundreds of generators (lag
> possible). The setup also generates excess Oxygen for 3x ore processing.
>
> Only real issue is you need a (near) constant supply of Bio Fuel, which I
> have been unable to easily get a constant supply of with Mekanism alone.
>
> A Fusion Reactor is the end power generator, but very expensive and large
> (and can cause some lag due to the fuel production).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aidancbrady/Mekanism/issues/3024#issuecomment-161081181>
> .
>



-- 
Brad

**Comment by TheProdigy22** [comment]
Okay so if I can get an auto farm set up (probably with mine factory reloaded) then I would get a good supply of ethylene. That does sound interesting to try and automate, and if ethylene is really that good, then I think that would be a great setup. I'm pretty satisfied with how this mod works and i think Aidan is doing awesome. Actually, Mekanism is probably my favourite mod. I just love how it looks and how all of the machines extend a minecraft world's life time by giving you a goal. And now that I know what to do about energy, I think this issue is good now.
