### ISSUE TITLE
Crash upon usage of Electric Pump

### ISSUE THREAD

**Issue by GodofVelcro** [aidancbrady/Mekanism#3025]
When the Mekanism Electric Pump is both connected to a power source and a water source, either the client, or server breaks. I tested with two people, my friend put the pump down, and it kicked me from the server. Both he and the server were fine. I then rejoined, put the pump into place myself, and it kicked us both out and crashed the server. This is the server crash report if anyone can make any sense of it. I love this mod, and so far the only problems I have with it is this annoying random bug, so if I could get any sort of feedback it would be appreciated.

[crash-2015-05-02_15.26.45-server.txt](https://github.com/aidancbrady/Mekanism/files/49416/crash-2015-05-02_15.26.45-server.txt)

**Comment by Greylocke** [comment]
You need to update your Forge to 1355+ so that you get the new fluid systems.
