### ISSUE TITLE
Reactor Logic Adapter says 'Unformed' in LUA API while the reactor is formed.

### ISSUE THREAD

**Issue by dobegor** [aidancbrady/Mekanism#3027]
Reactor is formed (it's controller block says so and there is some fuel in it), but it returns 'Unformed' in every API call made from OpenComputers.
Latest development build from last commit, latest stable OpenComputers & ComputerCraft.

**Comment by dobegor** [comment]
It seems that getReactor() returns null, while Reactor Logic is standing on reactor.
https://github.com/aidancbrady/Mekanism/blob/development/src/main/java/mekanism/generators/common/tile/reactor/TileEntityReactorLogicAdapter.java#L58

**Comment by aidancbrady** [comment]
Just did some testing, this is not occurring with a formed reactor.  Make sure you have the logic adapter placed on a formed reactor's structure.
