### ISSUE TITLE
Digital Miner not working on multiplayer

### ISSUE THREAD

**Issue by xxmynamesucksxx** [aidancbrady/Mekanism#3029]
I have recently created a private modpack and server for me and 3 friends but whenever I try to use the Digital Miner on the server, everything works properly with it, but it will not start mining. It works fine in single player.
Not sure if its a plugin I have installed doing this or the Mekanism config, but I could not find a single thing in any of the configs that would affect this working.

Not sure if you can help since it is serverside, but google didn't have anything specifically so didn't know where else to ask.

Thanks.

**Comment by VT-14** [comment]
Double check all the Digital Miner settings (area, filters {including auto-replace settings}, power, etc.).  Also turn off you texture pack if you are using one, as the GUI has changed slightly over time, and the pack may be behind [the one I use doesn't show the moved auto-replace settings].

Make sure Mekanism is the most recent version (you should always include versions of mods when reporting bugs).  Also make sure Forge is up to date as well (usually worth including its version as well).

If neither of those fix it, then it's likely a config somewhere.  You can reset your configs by removing that folder from the server files (it will generate new, default configs on the next startup) [keep a copy of the originals].  Alternatively, you could replace the server config with your working single player config.


The last option I can think of is mod compatibility.  Start off by making a server with only Mekanism in it and make sure the digital miner works.  Then turn on half your mods and check again. Repeat activating half your mods until it fails.  When it fails, remove all the "working" mods (only use mods recently added + Mekanism) and deactivate half of them.  Use this or a similar procedure to figure out which mod(s) is causing the problem.

Alternatively, post your mod list (with versions of everything), and wait for someone to do something with the information.  If I have time (maybe in a few days), I might try making the pack and a private server on my computer and see if I can replicate the problem.

**Comment by XFactHD** [comment]
@xxmynamesucksxx do you have a permission plugin on your server? If you have, try removing it our, if possible, whitelist the mekanism fake player (I think it is just called "Mekanism").

**Comment by themechman** [comment]
Also, a very huge word of caution. The digital miner has, in the past, caused major heartbreak for server operators due to world corruption. It is still blacklisted on several servers I play on and do not know if the issue has been fixed. Please use responsibly.

**Comment by Sosjojuror** [comment]
I'm also having a problem like this on the server I play on. Using "Mekanism-1.7.10-8.1.7.252" by the way.

It always wants a few more RF/tick than it's currently getting, no matter how much you give it.

**Comment by Zaflis** [comment]
We have Mekanism-1.7.10-8.1.7.255, and there's not been issues with digital miner so far. I just had to make 24 item filters for each ore, so that was a bit of chore. But having tesseract at the back and it's autosending stuff home like other quarries. About 2 ores per second for 5.2k RF/t makes it many times more efficient than laser drill.

**Comment by VT-14** [comment]
@Zaflis Setting an Oredict filter as ore* will mine everything that is set as an ore in the ore dictionary.  You only need to set multiple filters when a mod doesn't use the ore dictionary for its ores, or if you want to exclude something excessively common like Coal.

* allows for any string (letters) to be used.  For example, oreCo* would mine Copper, Coal, and Cobalt (and anything other ores that start with Co).  *Iron would mine Iron Ore (oreIron) and Blocks of Iron (blockIron), and likely more.

**Comment by HideAwayDk** [comment]
Well it have nothing to do with the filters i have Mekanism 8.1.7.252 and it work in offline mode but not online mode with KCauldron-1.7.10-1614 & PermissionsEx-1.22.9

**Comment by ktole1999** [comment]
i have v252 everything has been working fine up until yesterday. Now the miner will just go dead. still powered, still using power but will not mine. tried conduit power and tesseract. wrench and replace both, break and replace both. nothing. if i move it out of that 3x3 it works for a bit and then stops again.  Any thoughts or suggestions?

**Comment by HideAwayDk** [comment]
Hey ktole1999, 

For me it worked when i removed the PermissionsEx plugin, so if you have any permissons plugin try remove it and try again.
For now iam trying to use Forge ServerTools insted, and it workes

**Comment by ktole1999** [comment]
Yes I use pex and essentials and have never had issues before. If it was a perm thing I would think it wouldn't work at all but for me it works and then stops. I will try adding perm node to see if it resolves. Thanks for feedback. I am also looking at forge tools as an overall alternative.

Sent from Outlook Mobile




On Fri, Jan 8, 2016 at 8:16 AM -0800, "HideAwayDk" <notifications@github.com> wrote:





Hey ktole1999,

For me it worked when i removed the PermissionsEx plugin, so if you have any permissons plugin try remove it and try again.
For now iam trying to use Forge ServerTools insted, and it workes

---

**Comment by HideAwayDk** [comment]
Well let me know if you make it work ktole1999, and what perm's you are using in PermissionsEx corse atm i can't get groups to work in Forge Server Tools

**Comment by ktole1999** [comment]
i was able to get it working by running miner outside of my claimed area. i use grief protection. also using mytown it works fine in MT claimed area. so something in GP is funky with the miner. So its not pex or essentials causing as both are still active on my server.

**Comment by aidancbrady** [comment]
I believe I know the issue. The Digital Miner passes a fake player with the username of "[Mekanism]" into all initial checks before breaking a block, and likely the protection is recognizing that as an invalid player. This is intentional behavior.
