### ISSUE TITLE
Atomic Disassembler - Enderzoo khndrel keght - Compatibility Issue

### ISSUE THREAD

**Issue by tgstyle** [aidancbrady/Mekanism#3030]
See the following response from @HenryLoenwind

https://github.com/SleepyTrousers/EnderZoo/issues/113

Anything that can be done to fix this?

**Comment by isochronous** [comment]
From that issue thread:

> A khndrel keght is spawned when a dirt or grass block is broken by a player using a tool that is not effective on dirt. To determine if it is effective, we ask the tool. Only if the tool answers that it is not effective, will we potentially spawn one.

So if there's a way for the AD to register itself as effective on dirt (which it certainly is) that would fix the problem.

**Comment by HenryLoenwind** [comment]
We ask https://github.com/MinecraftForge/MinecraftForge/blob/1.7.10/src/main/java/net/minecraftforge/common/ForgeHooks.java#L142 (1.7) or https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/common/ForgeHooks.java#L175 (1.8) about the tool's effectiveness. Sadly it isn't involving the tool as much as would be nice, but for a tool to say can shovel, even if it only shovels some blocks, is better than the other way around.

**Comment by aidancbrady** [comment]
This functionality will likely be innately fixed with the internal changes in 1.8 I've had to complete.
