### ISSUE TITLE
Logistical Transporters not inserting into machines

### ISSUE THREAD

**Issue by cinnamennen** [aidancbrady/Mekanism#3033]
So it's easiest to use the attached picture below to understand the issue, but basically, LT's won't insert into the Bio-Generators I have setup. While I am inclined to think it is an issue with the Bio-Generators, there is also a possibility that it is something to do with the LT's, as I was setting up something with Applied Energistic Inscribers using the LT's to move items around, and the tubes stopped working.

Some questions you might have, and their answers:
- Is the Crushing Factory (pushing the Bio Fuel) properly configured?
  - Yes, further confirmed by the fact that *other* Bio-Generators are getting Bio Fuel pushed to them
- Have you tried breaking and re-placing the Bio-Generators?
  - Yes
- Have you tried disconnecting the other machines?
  - Yes, I tried running the tube to only the front of the machine, and then to the top of the machine, bypassing the others. The only thing I noticed was that when I ran the line to the top of the machine, it didn't solve the issue, but the Bio-Generator above the LT line did still accept/get sent Bio Fuel

![2015-12-08_15 58 51](https://cloud.githubusercontent.com/assets/2693113/11668695/94ae112e-9dc6-11e5-90e7-799b2e286541.png)

Version: Mekanism 1.7.10 8.1.7.252

Not sure how to reproduce, but it appears that restarting the server "resets" it to make it work again.

**Comment by aidancbrady** [comment]
This should be fixed v8.1.9, which should be coming soon.
