### ISSUE TITLE
Machines continue to play sound even when there's no work

### ISSUE THREAD

**Issue by PsionicArchon** [aidancbrady/Mekanism#3034]
As the title states, at random, I will hear my Mekanism machines producing sound as if they are processing when they are not. This can become quite frustrating when tinkering around in my workshop.

Logging in and out of the server causes the sound loop to stop.

Using latest version of Mekanism on version .1448 of Forge.

**Comment by rdunham3** [comment]
I had this happen a couple days ago while I was tearing up a base to rearrange everything more efficiently.  (saved 20+ blocks of pressurized tube!)

The crusher sound continued to play even after the crusher and every nearby Mekanism block was removed.  It didn't stop until I broke the vanilla chest that the Mekanism stack was ejecting to.

Current Mekanism and I believe I'm still on 1448 of Forge but I'll have to double-check that.  About 70 other mods also installed but none of their blocks in the immediate area and none that would interact with the Mekanism parts or chest.

**Comment by PsionicArchon** [comment]
I did some poking about in my configs, hadn't noticed this before for some reason.

B:ReplaceSoundsWhenResuming

I'm going to set that to false as I have a lingering suspicion it might have something to do with this issue.

**Comment by Meller127** [comment]
Have the same problem, disconnect and rejoin the server fixes the sound duplication.

Have tested some scenarios and this will happen 100% of the tests i have done.

Fill a mekanism machine lets say the crusher, teleport some chunks away, then return when the machine is done. You now have crusher sound always.

Repeat the steps and the sound bug stacks, with say 10 mekanism machines running and its duplicate the sound = chaos in my factory ;)

If more info is needed let me know.

MCP 9.05
FML 7.10.99.99
Mekanism 8.1.8.261

**Comment by aidancbrady** [comment]
Merging with #2741
