### ISSUE TITLE
Solar Evaporators producing Orphaned TEs

### ISSUE THREAD

**Issue by tgstyle** [aidancbrady/Mekanism#3035]
See screenshot below, using 8.1.7.255
![2015-12-09](https://cloud.githubusercontent.com/assets/5832709/11699064/80bb0ad2-9e7f-11e5-98d4-7844d7b94491.png)

**Comment by aidancbrady** [comment]
Ah, I think I actually know the issue here- I'm holding onto references of all tank blocks with my current algorithm. This is luckily a very easy fix, I'll just change the references to use my hashable coordinate wrappers.

**Comment by aidancbrady** [comment]
Fixed!

**Comment by tgstyle** [comment]
I built the dev version from the source and tried it with your fixed commits, I still saw the orphaned TEs in Opis.
