### ISSUE TITLE
[Request/Enhancement] Adding/removing Mekanism Shaped recipes

### ISSUE THREAD

**Issue by TheTrueForce** [aidancbrady/Mekanism#3038]
Hi,
I've been tweaking my (personal) modpack using MineTweaker and ModTweaker, which is working well, for the most part.
The problem comes when I want to replace a recipe that NEI reports as being Mekanism Shaped Crafting. I've tried to remove such recipes using MineTweaker, and it doesn't work(I expected as much). I am willing and able to write a small mod to do this, but looking at the code, it doesn't look like it's possible to add or remove recipes that use this handler by IMC.
Could you add that ability, please?

EDIT: I've also looked at the wiki (before I posted this in the first place), and it doesn't talk about recipes that use the vanilla crafting table, which is what I want to remove/alter. Also, I'm using Mekanism 8.1.7.252, if that's any help.

**Comment by aidancbrady** [comment]
I've just completed this and pushed my work to the development branch.  I've also updated the [wiki](https://github.com/aidancbrady/Mekanism/wiki/IMC-based-recipe-integration) with information on how to use the new IMC crafting integration once it's released.  Let me know if this is what you're looking for!

**Comment by TheTrueForce** [comment]
Thank you, sir! What's described in the wiki is exactly what I'm looking for.
I have pulled together a rather more direct method of recipe removal, but doing it this way won't short-circuit anyone.
That info about `ItemRetriever` is also good to know. I probably shouldn't have been using `MekanismItems` directly.

**Comment by Nohicom** [comment]
I'm new to coding and minetweaker scripts, how exactly does this work? How would I be able to use this in my pack?

**Comment by bookerthegeek** [comment]
Thank you. :)

**Comment by TheTrueForce** [comment]
@Nohicom This works by having a purpose-built mod that does the tweaking. It isn't relevant to MineTweaker, unless you intend to write a plugin/addon for it to support Mekanism.
I have to say that I haven't touched my tweaks mod since I used this. I went into it because Quadrum was a pain to use, and I couldn't use JSONables, because it had no documentation that I could find.
