### ISSUE TITLE
Request: Option to disable world lighting via machines

### ISSUE THREAD

**Issue by themechman** [aidancbrady/Mekanism#3039]
Having a slight problem where rooms with large numbers of MEK machines that are starved for resources keep flickering on and off at high speeds. In a room where 10 machines exist, its bothersome. In a processing facility with 40+ machines, this is a massive tick killer.

Would it be possible to disable light outputs from these machines when they are functioning? An option... anything? Its impossible to walk into the building using any client pc's due to the lighting recalculations being done every tick (times the number of machines malfunctioning).

**Comment by aidancbrady** [comment]
Turn machine-effects off in the config.

**Comment by themechman** [comment]
Is this the string under general?
B:EnableAmbientLighting=true

**Comment by themechman** [comment]
Unfortunately Aidan, this only turned off the machine particle effects. Not the lighting.
