### ISSUE TITLE
Hohlraum insertion via reactor port problem

### ISSUE THREAD

**Issue by cornytrace** [aidancbrady/Mekanism#3044]
Hi again,

Thanks for your amazing mod and your help so far, but I found another issue.
According to your comment at issue #2770, it should be possible to connect item pipes to the reactor port to insert and remove hohlraum, and according to the java code of the reactor port, this again should be possible.
However, I cannot get any item pipes, mekanism or not, to connect with the reactor port.
The reactor is formed. My mekanism version is 8.1.7

**Comment by aidancbrady** [comment]
Fixed!

**Comment by Conversage** [comment]
solution ?
