### ISSUE TITLE
Network Upgrade Tool

### ISSUE THREAD

**Issue by cinnamennen** [aidancbrady/Mekanism#3047]
This is a suggestion for a new item. What it would allow you to do is upgrade your network a la the wand of equal trade, for example, you could use it to turn your basic universal cables to elite universal cables, using the tool, not having to  manually break and place each one.

**Comment by tylerjcw** [comment]
I would second this. Maybe make an item like the existing factory upgrade kits that you could apply directly to a cable.

**Comment by aidancbrady** [comment]
This is now done for v9- you just right-click a cable network with a respective alloy and it will upgrade the tier of 8 cables accordingly.
