### ISSUE TITLE
Salination Generator

### ISSUE THREAD

**Issue by candyninja22** [aidancbrady/Mekanism#3048]
Ive created a custom modpack. Absolutely love Mekanism. I did a full mudpack update, ran into some issues. Everytime I add newer versions of Mekanism, It give me the crash report-
Time: 12/26/15 12:45 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: mekanism/common/tile/TileEntitySalinationController

Any ideas how to fix? 
Thank you

**Comment by aidancbrady** [comment]
This is due to outdated mod interaction- make sure your entire mod list is up to date.

**Comment by candyninja22** [comment]
alright, thank you very much for the help. have a great new year, and
amazing job with this mod as well.
