### ISSUE TITLE
[Suggestion] Laser Power

### ISSUE THREAD

**Issue by tylerjcw** [aidancbrady/Mekanism#3051]
I really enjoy using the Lasers in this mod to transport power around my base; It looks cool, and does an effective job (and I love the hum). I just have one suggestion as to HOW to transport power with lasers.

I do of course know that I can direct all lasers in to a single laser amplifier and pull power from it, but I think the end amplifier that I actually extract the power from should be a separate block from the amplifier. The way I see it is this: The Laser Amplifier has one job, to collect the energy from multiple lasers and focus it in to one, single, stronger beam. In order to convert this laser back in to usable RF power there should be a block separate from the amplifier that does not emit a focused beam (thereby not destroying any pre-set wire you may have if you forgot to set the min and max in the amplifier). Thus allowing up to 5 (instead of 4) connections extracting power from this block. Maybe add some OpenComputers / ComputerCraft compatability and a (very) small RF storage. Perhaps it could be called the "Laser Dispersion Matrix" or "Laser Conversion Matrix". Maybe even add the ability to place a Laser Focus Matrix directly within the multiblock structure of the Energized Induction Matrix, allowing direct laser input from a fusion reactor to your matrix.

Edit: changing the color of the laser beam would also be cool

**Comment by vixblu** [comment]
Would this work? Amplifier > Universal Cable > Energy Cube
See also: https://www.youtube.com/watch?v=1kE1FCqSN_w&t=3m

**Comment by tylerjcw** [comment]
I have done this plenty of times. It is how I transport power to certain parts of my base. What I mean is a new block specifically for controlling the RF Output of the laser. One that maybe has redstone control, or can emit a signal when it's (small) power buffer falls below a user-specified threshold. Plus, it would allow for 5 sides of the block to be pulled from with cables, instead of just four. And, as I stated it won't destroy any pre-built blocks if you fire a laser in to it, because It does not fire a amplified laser out of it. (unlike the amplifier that has a default minimum of 0, and I forget to set this all the time, resulting in the destruction of some of my work.)

**Comment by aidancbrady** [comment]
Merging with #2422
