### ISSUE TITLE
Logistical Transporter - disconnect at chunk boundary 

### ISSUE THREAD

**Issue by elexx** [aidancbrady/Mekanism#3052]
When loading a save file some Logistical Transporters are disconnected. The problem seems to be connected to chunk boundaries. I successfully reproduced it - see screenshots. If the connected inventory is in the **east** or **south** chunk next to a transporter in another chunk it will not reconnect when the world is loaded

![2015-12-28_21 02 01](https://cloud.githubusercontent.com/assets/221837/12024751/c6684950-ada7-11e5-9d20-437ca1126811.png)
![2015-12-28_21 03 39](https://cloud.githubusercontent.com/assets/221837/12024750/c6680ab2-ada7-11e5-8a04-b0100383b21d.png)

Version: 8.1.7.255
Minecraft: 1.7.10

**Comment by callous4567** [comment]
I can't reproduce it on my server; single player only issue? Perhaps try chunkloading the pipes, that might help.

**Comment by aidancbrady** [comment]
Perhaps try updating to the latest Mekanism version; I can't reproduce this either.

**Comment by aidancbrady** [comment]
I take that back- I was just able to reproduce. What's strange is that it only occurs for vanilla inventories, not mine; the disconnection issue does not occur when transporters are connected to energy cubes. It's most likely some kind of block update issue

**Comment by aidancbrady** [comment]
()[http://imgur.com/87kjKhy]
Here's an image showing the oddity.

**Comment by elexx** [comment]
Not only vanilla inventories. Originally I encountered the bug with AE2 Inscribers. But it's possible that they are only some sort of extended vanilla inventories, I haven't checked the code.

**Comment by aidancbrady** [comment]
Fixed :)
