### ISSUE TITLE
Crash when creating a solar evaporation plant

### ISSUE THREAD

**Issue by solidDoWant** [aidancbrady/Mekanism#3053]
Pastebin to log: http://pastebin.com/1ncSb9a1

This seems to happen after changing to another dimension and placing a block in the middle of the base, rather than on the sides. Looks something like this:

Layer 1:

SSSS
SSSS
SSSS
SSSS

Layer 2:
 AAAA
AASA
AAAA
AAAA

Where A is air, and S is solar evaporation block.

**Comment by aidancbrady** [comment]
Should no longer be an issue.
