### ISSUE TITLE
Teleporters Computercraft Returning error.

### ISSUE THREAD

**Issue by lghenk** [aidancbrady/Mekanism#3054]
Hello,

I am not sure if i am supposed to put it here or with computercraft forgive me if i post it wrongly.
But when i try to execute the set command or any other it simply returns error. and nothing else.

http://prntscr.com/9jwx57
^^ This is what i have tried with computercraft (the portal is directly attached to the back of the computer)

Thanks in advance

**Comment by aidancbrady** [comment]
This is fixed in development.
