### ISSUE TITLE
Crash when opening a recipe in NEI

### ISSUE THREAD

**Issue by notchriss** [aidancbrady/Mekanism#3057]
After updating to Mekanism 8, every time I click on any item's icon in NEI, client crashes. Doesn't matter what kind of item, I tested a few - vanilla iron pickaxe, reactorcraft's uranium fuel pellet and others.

Everything was fine with Mekanism 7

http://pastebin.com/3VGExtj2

Thanks in advance for your help

**Comment by aidancbrady** [comment]
This looks like outdated minetweaker.
