### ISSUE TITLE
[Mek 252] / by zero on right-clicking Solar Evaporation Controller

### ISSUE THREAD

**Issue by TheTrueForce** [aidancbrady/Mekanism#3058]
Sometimes when I right-click on the Solar Evaporation Controller, I crash with a / by zero. It doesn't always happen, and last time it did, I was trying to put it in a cardboard box.
Also, I couldn't get hold of the full forge log where this happened, so I've had to link the Minecraft-generated one.
Crash log:[Pastebin] (http://pastebin.com/2WA23TTF)

**Comment by aidancbrady** [comment]
Thai is fixed in development
