### ISSUE TITLE
[Suggestion] Add a volume slider for Mekanism

### ISSUE THREAD

**Issue by TheAnimatronicFox** [aidancbrady/Mekanism#3061]
If you havent implemented it yet id suggest you add a volume slider for Mekanism machine sounds to minecraft volume settings  and overhaul the slider menu and make a api for other mods to make use of so all volume sliders arent cluttering each others slider spots with mods that already have similiar sliders

**Comment by aidancbrady** [comment]
I'd rather not add some kind of slider API into Mekanism. I'm happy with the current functionality- if you want to turn down machine volume, just turn down block volume
