### ISSUE TITLE
Crash on server startup 8.1.8

### ISSUE THREAD

**Issue by adamcirillo** [aidancbrady/Mekanism#3062]
Get this crash on my server start up since upgrading to 8.1.8 the only reference I found was in the Crash Log couldn't see the error message in the full log but I've attached it as well.

[fml-server-1.txt](https://github.com/aidancbrady/Mekanism/files/83987/fml-server-1.txt)
[crash-2016-01-10_16.39.02-server.txt](https://github.com/aidancbrady/Mekanism/files/83989/crash-2016-01-10_16.39.02-server.txt)

**Comment by aidancbrady** [comment]
Update to build 258, it has a fix.
