### ISSUE TITLE
crash with 8.1.8.257

### ISSUE THREAD

**Issue by blarghhh** [aidancbrady/Mekanism#3063]
Here is the pastebin to the crash log.

http://pastebin.com/3G2Yaq5t

i am using ftb infinity evolved 2.2.2 on curse and this only occurred when i manually updated to 8.1.8.257. using 8.1.8.252 does not have any problem.

**Comment by aidancbrady** [comment]
This is not on my end, something funky is going on. I'll have a new minor release out soon.
