### ISSUE TITLE
Logistical Sorter wont use Default filter

### ISSUE THREAD

**Issue by WildBill918** [aidancbrady/Mekanism#3068]
Hello all! 
Minecraft - 1.6.4
Mekanism/Generators/Tools - 6.0.5.46

I seem to have ran into an issue with the Logistical Sorter where I'll trying to set a sorting system up with multiple sorters but the Default color filter wont work. 

Auto-Eject is on and Default color is set to Dark Green. I set the items in the filters that I want sorted to a certain chest set to Dark Blue. I color the Logistical Transporters accordingly but the sorter only pulls items on the filters I set for certain chests, nothing else, even though Auto-Eject is on and a Default filter is set. If I take the Dark Green color off of the Transporters, it pulls the items just fine, however then some items with a filter to a chest will reroute for some reason and just keep going through the system. I don't know if there's a fix for this out or not but if so let me know please and thank you!

**Comment by aidancbrady** [comment]
You're using an unsupported version of Mekanism, I'd advise updating :)
