### ISSUE TITLE
Issue with Metalurgic Infuser

### ISSUE THREAD

**Issue by Adam4CZ** [aidancbrady/Mekanism#3069]
I found some issue (maybe bug?) with Metalurgic Infuser. It's about automatic putting items into GUI with Shift key - it's all shifted to the right (see in pictures).

**e.g. By clicking on _Compressed Redstone_ with Shift:**
![2016-01-16_12 23 01](https://cloud.githubusercontent.com/assets/15090021/12372123/b7b0c028-bc4c-11e5-9238-203b02db3203.png)

**e.g. By clicking on _Iron ingot_ with Shift:**
![2016-01-16_12 23 18](https://cloud.githubusercontent.com/assets/15090021/12372126/be628d52-bc4c-11e5-86c9-9a5f55a3fdab.png)

*Mekanism version: 1.7.10-8.1.8.258 (newest)*

**Comment by aidancbrady** [comment]
Fixed, thanks!

**Comment by Adam4CZ** [comment]
@aidancbrady :+1:
