### ISSUE TITLE
Ingame Guide like in other mods?

### ISSUE THREAD

**Issue by chaos234** [aidancbrady/Mekanism#3070]
Searched for it but didn't found a ticket for this question:

Is it possible to include a Book like in Tinker's Construct or Witchery which helps you hup with your mod? It can also be like RFTools. Another way can be like the Informationtablet from Draconic Evolutin (I realy like it, better as the old book style).

What should it contain?

Overviewing page as Index to go to the prefered page (e. g. machines).
Overview page for each liquid/gases supported by this mod and how it can be obtained/crafted.
Overview page for each module which can inserted in machines or upgrade them.
Page which contains the images like http://i.imgur.com/lzE9OPY.png but in a simpler way that it not exceeds this information book/tablet (possible using symbols for the different machines with collored arrows to which machin the specified liquid/gas can go and what comes out and if it's possible to store it in a (dynamic) tank or smth. similar.

Sounds like a lot todo I know but if it's mostly finished it will help the player and should improve the gameplay :).

**Comment by EzerArch** [comment]
Like this? #2939 :)

**Comment by chaos234** [comment]
Yes, smth. like this will be awsome. Also I accept that implementation in IGW must not be but as seperate book and/or information tablet or smth similar will be fine ;).

**Comment by aidancbrady** [comment]
Definitely on my agenda :)

**Comment by chaos234** [comment]
Thanks @aidancbrady :)

**Comment by Dr-DaNk** [comment]
it's been 5 years... Still on your agenda?

**Comment by thiakil** [comment]
It is, see https://github.com/mekanism/Mekanism/pull/6651

Like most developers I hate writing documentation, so progress is slow going and help is welcomed by PRing to my fork (and maybe pinging me as github doesn't notify me by email)

**Comment by thiakil** [comment]
We only develop for the latest minecraft version

**Comment by Chaoschaot232** [comment]
ok
