### ISSUE TITLE
Value of Compressed Materials

### ISSUE THREAD

**Issue by Mohron** [aidancbrady/Mekanism#3071]
Compressed materials like carbon, redstone, diamond and obsidian are a great way to get even more value out of precious materials. Unfortunately there is one issue with them that has always bugged me and I wanted to see what your thoughts are on it. 

Compressed materials are worth 10 of the uncompressed material vs 8 which would allow you to make an even stack of materials without anything left over. Where almost everything in Minecraft and even Mekanism involves amounts in powers of 2 I can't say I understand the logic of the 10 over 8 use. Changing this behavior would be a nerf I understand but it would make using compressed materials a lot more natural for both manual and automated crafting.

**Comment by sinspawn1024** [comment]
I would say I tend to agree. I mean, getting an extra 2 free is nice, but my OCD would prefer if everything was powers of two.

**Comment by Landrash** [comment]
The value of the compressed items can be found in Mekanism/src/main/java/mekanism/common/Mekanism.java at about line 835 and forward.

A commit always speaks more than a suggestion and it would make a great first commit ;)

**Comment by aidancbrady** [comment]
done!
