### ISSUE TITLE
[Idea] Make the Portals abit like Enhanced Portal 3 mods but with extra stuff+fit for this mod

### ISSUE THREAD

**Issue by mariodk** [aidancbrady/Mekanism#3072]
since Enhanced Portal 3 mod is kinda Dead
and Mekanism´s portal is the next best thing

i was wondering if you will take some of the ideas from enhanced portal 3 and make it to mekanism´s portals 
like: dialing with a Competercraft/opencomputer computer or a Special Cable & monitor(touch screen) made just for Portal to show what Dials/Name of dials there is, Redstone controll, alot of ways to customize the portals like make the frames be whatever block you wanted & portal colour too + all those other modules/upgrades that mod has (you should check it out)

and here is also a new idea for it(was mainly meant for enhanced portal 3 mod but i give you the idea for it anyway+its a copy/paste from a thread/PM to EP3 mod´s maker but he never answered also maybe inc. a player/entity sensor to it):

here is a idea that might be very usefull for this mod to make portals in a other way instead of frames around the portal but still same mod:

Black wool = the portal blocks so instead of a frame you build you can build some of the portal blocks under or over like this
and have some extra blocks like this: looks just call them portal blocks where the player can stand in/touches these portal block the player will get teleported if portal actived also these portal blocks can be turned into look other blocks(and not look the same as the portal frames blocks)
http://i.imgur.com/ZlbNscf.png
and here is what i will use it for:
http://i.imgur.com/Yjt5GNY.png
and will be even more perfect if looking glass support(so we can see whats on the other side of the portal) so if this idea happens i can build a tardis in most modpacks with build the inside of the tardis in like a void dimension :D and if CC dialing program inside the tardis to TP to other tardises built like this so it is 100% working like one without any DR who mods but just normal mods we normaly see in modpacks like FTB/tekkit/resonart rise/most tech packs

 

im not sure what others can use it for but thats idea makes portals/teleporting alot more customize options

 

also the redstone module needs to have a redstone output so if the player touches the portal frames(even if portal is not active) or is near the portal it will emit redstone since modded MC like redstone like mods and so on dont really have player sensors not many mods do unless you go deep in thaumcraft+having a addon for it or knows to computercraft or super expansive materials for make one: the one from draconic evolution so basically alot of time to get something as simple as like a redstone repeater

**Comment by cleverca22** [comment]
i've found that the rf tools teleporters are far better then both EP3 and mek, because you cant get a busy signal

you can have 2 senders dialed to the same destination at once, so if another person on the server forgets to DC, he doesnt lock the door for days

**Comment by mariodk** [comment]
but what if i wanted a Portal method to transport myself?
like if i wanted to build a Stargate themed portal network
or something like my tardis(inside in a void dim.) that needs computercraft for touch screen to controll what portal(one of the Tardis builds in overworld) to Connect to

i think mekanism´s portals needs a big update like my idea 
so it can be both portals(really customizable friendly) & telepads with support for this:
http://www.curse.com/mc-mods/minecraft/230541-lookingglass
so we can see whats on the other side of the portal

**Comment by mariodk** [comment]
maybe my idea with having a touch Special Screen & "network cable?" for portal 
the screen shows all the Dials from that portal and if right click on one of the dials on
the screen that is connected to the poral it will dials to that portal (like advance CC monitors can do with buttons API & Enhanced portal 3 mod): Not all knows to CC/opencomputer & LUA so will be awesome if the portal has a screen & Cables for that (cables to be able to place the screen anywhere and not only next to the portal)

that Screen & "network cable?"  idea can maybe be used on other parts then portal part on mekanism too
maybe Fusion reactor for a easier method of controll lasers,Laser Amplifier (the one that you charging up for start fusion) & the reactor

**Comment by VT-14** [comment]
Screens are also in RFTools.  I haven't messed with it enough to know how to do it off hand, but you can make a touch screen dial various transporters.  I think it's almost exactly what you are looking for.

**Comment by mariodk** [comment]
yeah if i wanted Telepads
but i wanted Stargate(s) (wormholes/portals)

**Comment by aidancbrady** [comment]
I'd rather leave this kind of stuff up to a different mod. I'm happy with teleporters currently
