### ISSUE TITLE
Dynamic Tanks bug again

### ISSUE THREAD

**Issue by Adam4CZ** [aidancbrady/Mekanism#3074]
I already wrote this bug here:
https://github.com/aidancbrady/Mekanism/issues/3067
This bug persist, tanks is still "shared" after update Mekanism.

*Mekanism version: 8.1.8.258*

**Comment by aidancbrady** [comment]
I've changed the tank algorithms to use unique identifiers instead of incremented integers- this should fix the issue. It's in the v9 branch.
