### ISSUE TITLE
Sounds play at incorrect location

### ISSUE THREAD

**Issue by ajthemacboy** [aidancbrady/Mekanism#3076]
To describe this issue, picture the following:

`A machine is to my south. When I face west, so that the machine is to my left, the sound is loud and plays in my left ear and is quiet in my right ear.

When I facesouth, towards the machine, the sound is loud in my right ear and quiet in my left ear.`

All Mekanism machines behave this way. Any sound played by a Mekanism machine comes from the wrong side.

On a similar note, machines are very loud when you are near them, but become very quiet just a few blocks further away. I'm not really complaining about this though, because with a room full of running machines, sound can get annoying. But it may be also be a bug, or it may be related.

**Comment by aidancbrady** [comment]
There doesn't seem to be a way to easily fix this, I'm sorry.

The rapid quietness of machines when moving is intentional, for the reason you noted.

**Comment by ajthemacboy** [comment]
Every other machine in the pack plays sounds perfectly, why can't you code your sounds like them..?
