### ISSUE TITLE
Cryo-stabilized fluxduct (Thermal Dynamics) losing energy when connected to Elite or Universal cables

### ISSUE THREAD

**Issue by TheSprtCz** [aidancbrady/Mekanism#3077]
I tried to report this to COFH team [here](https://github.com/CoFH/Feedback/issues/1006), but they turn me down, so I am trying it here.
When connecting Cryo-stabilized flux duct to Elite Universal Cable or Ultimate Universal cable energy gets lost. I tested it with [these mods](http://pastebin.com/wChPHnd3) by simply creating loop from one energy storage to another, in this case Ultimate Energy Cube. Here is picture of my testing loop.
![How I tested it](https://cloud.githubusercontent.com/assets/5594403/12521876/8ff89dac-c14d-11e5-9c47-50e67812701e.png)

**Comment by iKaneki-Ken** [comment]
This isn't a bug, you can easily set the conversion rates within the Mekanism configuration file yourself.

**Comment by TheSprtCz** [comment]
Only Cryo-stabilized fluxduct does that and energy keeps losing. If it was just conversion, energy would be same just in different units.

**Comment by iKaneki-Ken** [comment]
Or it's just the default conversion rates inside Mekanisms configuration file is a little off.

**Comment by Adam4CZ** [comment]
IMHO, it's not about energy conversion.

![1](https://cloud.githubusercontent.com/assets/15090021/12555627/5b05d3d0-c382-11e5-9bd8-99d337cd8c51.png)
![2](https://cloud.githubusercontent.com/assets/15090021/12555633/5b595b9a-c382-11e5-953d-0d2e24351257.png)
![3](https://cloud.githubusercontent.com/assets/15090021/12555743/e2b96e18-c382-11e5-8ac4-653bdc9b9cef.png)


**When I connect Elite/Ultimate Univesal Cable (Mekanism) to Cryo-stabilized Fluxduct:**
![4](https://cloud.githubusercontent.com/assets/15090021/12555629/5b11aa7a-c382-11e5-94ac-01fb9f3ab468.png)
![5](https://cloud.githubusercontent.com/assets/15090021/12555631/5b2148ea-c382-11e5-8d2b-5fb958827390.png)
![6](https://cloud.githubusercontent.com/assets/15090021/12555630/5b14cc6e-c382-11e5-8da6-c20bfcb3fc66.png)
And energy gets lost, although has nowhere to go.

**Comment by cleverca22** [comment]
the mekanism cables have storage within the cable, which the cryo-stabalized ones lack

**Comment by Adam4CZ** [comment]
But it's only for Elite or Ultimate cables, Basic and Advanced works fine.

**Comment by cleverca22** [comment]
the size of that storage also scales with its rank, and the basic may be small enough that your not noticing it

**Comment by aidancbrady** [comment]
This has been fixed, thanks!
