### ISSUE TITLE
Buildcraft Incompatibility

### ISSUE THREAD

**Issue by Nosnamreh** [aidancbrady/Mekanism#3078]
Hello!

The Miner robots from Buildcraft are not recognizing Osmium ore, though they will happily mine Copper and Tin. I was advised to post this here, as the BC team may not be able to fix everything on their end.

https://github.com/BuildCraft/BuildCraft/issues/3189

Thank you very much for your time and energy.

**Comment by aidancbrady** [comment]
I'm sorry, but I'm fairly certain this is not on my end- Mekanism's osmium ore is registered with the "ore" prefix, otherwise my Digital Miner wouldn't be able to mine it.  Let me know if I can help in any other way.
