### ISSUE TITLE
[Request] Minetweaker or modtweaker support. 

### ISSUE THREAD

**Issue by vagaprime** [aidancbrady/Mekanism#3079]
I am a pack builder, and am currently working on a modpack. I am attempting to integrate the tech mods in my pack into each other. To do so I am using the mekanism steel casing in the recipe for the Machine chassis and machine frame which is done easy enough. The problem I am running into is changing the recipes for the Steel Casing, basic cable, basic tube, basic pipe, routing, and basic transporters to use steel plates, and in the case of the steel case to use a gear as well.

But due to the way that Mekanism registers its recipes mine and mod tweaker are unable to remove the old recipes. I was wondering if there was anyway to add native mine or mod tweaker supprt to the mod or add an option in the configs to disable the casing and all of the pipe's and cables.

**Comment by aidancbrady** [comment]
I've added better IMC support in Mekanism v8.1.9- this should no longer be an issue.
