### ISSUE TITLE
Metalurgic Infusers

### ISSUE THREAD

**Issue by Adam4CZ** [aidancbrady/Mekanism#3080]
I tested issue #3069 with version _1.7.10-8.1.8.261_  and in this version Shift+Click on item not working.
When I click on the item (e.g. Iron ingot), nothing happens.

**Comment by Adam4CZ** [comment]
**Edit:** I tested it again and I found out this:
Items for Infusing (_coal, redstone,..., compressed items_) is still going to wrong slot (for input items) and infusing items (_iron, alloys,..._) absolutely not working.

**Comment by adamcirillo** [comment]
I have the same issue expect iron ingots go to the output slot and then get pulled back into my system

**Comment by Adam4CZ** [comment]
If you have this problem, imho you have older version. This problem I had in version _1.7.10-8.1.8.258_, but in _1.7.10-8.1.8.261_ I only have this problem with items for Infusing (coal, redstone, etc.).

**Comment by aidancbrady** [comment]
Fixed in dev
