### ISSUE TITLE
[Enhancement] Crafting machine and high tech inventories

### ISSUE THREAD

**Issue by sinspawn1024** [aidancbrady/Mekanism#3081]
Mekanism adds really amazing machines for gathering and processing resources, but two things I think could really add to the mod are (1) a crafting machine, and (2) some high tech inventories. Here are my ideas:

The crafting machine would have a 9 slot internal inventory plus a slot for accepting a blueprint/recipe. Like other Mekanism machines, its speed and efficiency could be upgraded, and it could be converted into a factory. Each tier of factory would add 9 additional inventory slots and 2 additional blueprint slots. The player could decide to use different recipes or copies of the same recipe. The output could be configured to either eject the resulting craft or put it back into the internal inventory to be used in a different recipe. There might also be an upgrade that allows the player to format the internal inventory with ghost images of items so that only instances of specific items could occupy a particular slot (to prevent the machine locking up when cycling through multiple recipes). The recipe for the machine might be a steel casing surrounded by four redstone, two control circuits, a crafting table, and a chest. Possible names include the Hyperfabricator or the Replicrafter. 

The high tech inventories would be full blocks, accessible regardless of whether a block was placed above them, and would keep their contents when broken. The basic inventory would have 54 slots, and could be upgraded to advanced (72 slots), elite (81 slots), and ultimate (108 slots) versions. What makes them advanced is that the faces could be configurable to either push or pull items from neighboring inventories/machines (potentially using RF to do so). There could also potentially be 6 slots in the configuration tab for filters to be added to any side pushing or pulling items. By default, the inventory would transfer the items one at a time, but speed upgrades could be added to increase transfer speed. Finally, a teleportation core could be added that would link two inventories like an ender chest. Optionally, they could be open-able when in the hot bar and effectively be bags. The recipe might be a steel casing surrounded by four redstone, two control circuits, and two chests. Possible names include the Intelligent Inventory or the Itemizer.

**Comment by aidancbrady** [comment]
I'm now working on the crafting machines. Will keep you posted :)

**Comment by aidancbrady** [comment]
Crafting Machines are now complete. I named them "Formulaic Assemblicators" - they were quite a project!  I really like the idea of a high-tech inventory as you stated, but as I already have the electric chest, I'm going to hold off for now. Perhaps sometime in the near future :)
