### ISSUE TITLE
Crash on World Load

### ISSUE THREAD

**Issue by fabbe50** [aidancbrady/Mekanism#3083]
Game is crashing right after spawnchunks are generated according to console.
I've tried removing mods that people said would cause this, but with no luck.

Anyways, here's the crash event: http://pastebin.com/2LvxfhhZ

**Comment by fabbe50** [comment]
Found the issue.
It's because of Voltz engine with it's ores removed, that apparently causes Mekanism to crash.

**Comment by fabbe50** [comment]
accidental close, sorry

**Comment by aidancbrady** [comment]
It seems that VoltzEngine is somehow interacting with Mekanism recipes in a way that makes the Item itself invalid. This isn't on me.
