### ISSUE TITLE
Bug or not? Osmium Compresser not working corecctly

### ISSUE THREAD

**Issue by chaos234** [aidancbrady/Mekanism#3084]
Hey,

I found a bug (or not) with the Osmium Compresser to get Glowstone Ingot and Refined Obsidian Ingot.
The Problem is that, if I am putting in 1 glowstone dust and one osmium ingot all went fine, but if it's two or more of them (same goes to with the refined obsidian ingot) then it won't create two outputs.

So my question: Is this normal or is this a bug? Because the recipe in NEI tells me to use one RFI/GI with one Osmium Ingot but this seems not be true at all.

Also I don't tested it with a higher tier of that machine.

**Comment by aidancbrady** [comment]
There is some slight loss osmium as a result of the operation, so in reality a small fraction more of osmium is required than just one ingot.
