### ISSUE TITLE
[Request] Opaque option/upgrade

### ISSUE THREAD

**Issue by chaos234** [aidancbrady/Mekanism#3089]
On the server where I am playing it is realy hard to build a good flow for e. g. x5 ore production because fluid pipes are not opaque able (must change to Thermal Dynamics because Ender IO are to slow for Mekanism).

The next part are the pressurized pipes, which also causing FPS lags.

The main problem for all those pipes (icl. electical ones) are that they counted to cofh so they are always on the top in Opis with over 1000's ms.

Actually, if I am using /cofh tps I'll get only for the overworld 20.00 TPS/35.82 MS (100%) but normaly our Overworld has arround 20.00 TPS/MS. Overall is arround 44.00 MS.

I think that the way which Mekanism uses to render things is specially for the server and for the client not good, if there are no possible option to use an opaque upgrade or smth. else.

Result: With my current setup I have only 11-16 FPS as normaly +45 FPS and this with a NVIDIA GeForce GTX 970 (default ressource pack, optifine HD U1 C7, no shaders mod).

I hope that you can include a opaque option/module (like in Build Craft?) to reduce those FPS lags.

**Comment by MyNameIsKodos** [comment]
I'm just curious, does your FPS worsen or get better when you remove Optifine? Optifine is notorious for more often than not doing more harm than good.

**Comment by chaos234** [comment]
Wait a bit, I'll take Screens and add them to THIS comment her :)

**Comment by XFactHD** [comment]
I don't know what you are doing to your graphics card but I am getting the same results with the GTX 760 which is 3 years older than the GTX 970. Could you post the complete specifications of your computer (RAM, CPU), please?

**Comment by chaos234** [comment]
Why should I this? Sorry, but I don't do it.

What I can say is that other player on the same server have the same problem (hardware doesn't matter) and if you have clicked the link above to my pull request which includes an opaque version which do what it should do then you have your answere.

I am not here to analyze my nor another pc system because I know how to handle hardware issues and there is no issue with my hardware.

Well, then I'll wait ;).

**Comment by XFactHD** [comment]
The hardware does matter. If you have a bad CPU, a good graphics card won't make things any better and Minecraft won't run better than when you are using an older graphics card (other games might, but not Minecraft). The reason is that Minecraft does too much work on the CPU (also pre-render calculations). This was, IIRC, changed drastically in 1.9.

**Comment by chaos234** [comment]
Nice to hear that this is solved in 1.9 which isn't supported by any kind of mod ... oh I forgott that only a few mods supporting 1.8 at this moment so we must life with this problem.

Well, my OS is Win10 x64 based on DDR 4 and MC "eats" up to max. 6-10GB based on the played modpack but not more than 16GB ;).

Means that I currently have the lates hardware but not the best one (money does not grow on trees ;) ).


Am 07.02.2016 00:27:08 schrieb XFactHD <notifications@github.com>:
The hardware does matter. If you have a bad CPU, a good graphics card won't make things any better and Minecraft won't run better than when you are using an older graphics card (other games might, but not Minecraft). The reason is that Minecraft does too much work on the CPU (also pre-render calculations). This was, IIRC, changed drastically in 1.9.

**Comment by XFactHD** [comment]
I am using Win7 x64 and I am allocating 10GB to MC and the result is the same. I will have to try a big setup with hundreds of pipes and I'll report back if I was right or just trying to be intelligent 😏.

**Comment by chaos234** [comment]
Hey XFactHD,

have you any new informations or done your test?

**Comment by XFactHD** [comment]
No, sorry, couldn't do it over the last days because I had too much to do for school but I didn't forget about this.

**Comment by SunDwarf** [comment]
EnderIO conduits are definitely not too slow for Mek - I use them in all my builds. Just add speed upgrades to the extractor conduits.

**Comment by chaos234** [comment]
@SunDwarf - Tell that all other server admins wich are not using EnderIO.

This means that pipes or cables from other mods are not an argument to prevent lags if you don't
have any of these mods installed. So each mod should then provide an option to be opaque like the BC  Pipes (e. g. Fluiducts).

Also it's not an argument if you have them installed because why should I use EnderIO if the mod gives me better options? So I reject the usement of these. Oh and don't forgett that only Meka has pipes for there gases ;).

**Comment by XFactHD** [comment]
I went over to using Mek pipes and TD fluiducts because EnderIO pipes did lag the hell out of my game. Also, the fluiducts have an opaque version (if you didn't mean to say that).

**Comment by chaos234** [comment]
@XFactHD - That's true. fluiducts have an opaque version but my problem with those are the pumpin rate. It's not written how many mb/t flows nor either it's written when such a fluiduct transferes unlimited if it's pressurized. Searching the web doesn't solved this question nor is there any video for that.

Any idea how to pressurize this fluiduct? Otherwise I must fall back to meka UMPs ones and this can be and in cutting my head due to server lag because all those pipes are cofh multipart tiles (duno why it is so but at this moment it is so ^^). Also I can't differ in Opis which pipes does the highest lag because they are countet all together :( ...

Same goes to each SEP Block which count's as tileentity and consumes a lot of server ressources. If I compare this to the Draconic Evolution Energy Multiblock then I see that those blocks are not tileentities, they are blocks like dirt, stone, ...

It should be possible to optimze this so that this mod will be one of the most used tech mods with all his functionality but without those server performance issues ;).

Should be possible to do this and I think using multiblock ore pipe classes from other mod's (after asking there for usement) should be the best way. I think I can take a look at some classes, how they are working and if meka has the ability to use them. Can be take a wihle but if I have the answere I'll response here :).

**Comment by XFactHD** [comment]
ThermalExpansion had the same problem in 1.6.4. The blocks were always ForgeMultipart blocks and that kind of multiblock you are suggesting. They were lagging, sometimes didn't save their contents or settings and many other problems. To be honest I don't think the reason why the pipes lag is not them not bein a multiblock but rather the multipart functionality.

**Comment by Nova001Sol** [comment]
@chaos234 Regarding the pressurizing of TD super-laminar fluiducts; the fluiducts get pressurized automatically. Basically if there's enough fluid in them to completely fill them up they become pressurized. Just place them where you need them, add servos and retrievers as needed and you're good.

**Comment by aidancbrady** [comment]
How about a client-based config option, "RenderTransmitterContents"? I think something like this would be easier.
