### ISSUE TITLE
Chemical Injection Chamber won't automatically accept crystals

### ISSUE THREAD

**Issue by martinegui** [aidancbrady/Mekanism#3091]
So I'm trying to do the x5 ore processing, but when I get to the end of the tier 4 processing and have my crystals. However, when telling the crystalizer to eject the crystals, the CIC won't accept them. I've tried 3 other ways to move them out.

1) Using Ender IO conduits.

2) Using Extra Utilities NODES.

3) Using Steve's factory

In each scenario I made sure that the slots were the correct color for input/output. In the end I have to manually move them by hand. ( Shift doens't work as well )

I can Transfer to Chest or inventories like AE 2, but the CIC dont accept.

Im playing at Mekanism 8.1.8 at 1.7.10 modpack.
I read at mekanism github that old version from meknaism had this problem and have been fixed, maybe the mekanism from this modpack is out to date? Or maybe a miss config?

EDIT : The Metallurgic Infuser are not acceptin shift click to any items.

**Comment by aidancbrady** [comment]
Fixed in dev
