### ISSUE TITLE
Atomic disassembler makes inventory contents & NEI invisible

### ISSUE THREAD

**Issue by isochronous** [aidancbrady/Mekanism#3092]
I'll update this ticket later today with the version numbers, I just wanted to go ahead and enter it before I forgot.

I have no optifine, FastCraft, shaders, or CoFHTweaks installed.

In two consecutive worlds now, having the AD in my hotbar but not selected causes all of my inventory contents and all NEI GUI elements to vanish. The items are still there - I can mouse over them and get the tool tips - but nothing is visible. If I have the AD in my hand, then everything shows up just fine. If I throw away the AD by pressing Q, then everything vanishes and stays invisible until I log out and back in again. If I have the AD in hand, open the inventory, then click on the AD, everything immediately disappears.

If I have an item with its own inventory (backpack, golden bag of holding, alchemical bag, etc), opening its inventory via right-click makes everything show up normally. It's only when using E to open the standard inventory that this occurs.

This has happened on two different versions of forge and two different versions of Mekanism. It makes me sad because I love Mekanism and the AD, but it's extremely frustrating to have to select the AD every time I want to open my inventory or use NEI.

**Comment by isochronous** [comment]
Currently using:

* Mekanism 8.1.8.258 (Core, Generators, Tools)
* Forge 10.13.4.1614-1.7.10

Previously happened with

* Mekanism 8.1.7.252
* Forge ah crap I don't have that info, but I think it was 1556

**Comment by aidancbrady** [comment]
This is interaction of another mod- I promise this is not on my end.
