### ISSUE TITLE
Auto-eject from machines not working with Thermal Dynamics

### ISSUE THREAD

**Issue by Zaflis** [aidancbrady/Mekanism#3100]
I have elite enriching factory chewing coal ores. Output side (blue) is set to back where is a Warp itemduct. That in turn connected to ME interface from AE2 with a filter with "Allow over-sending". So basically it's trying to put item into pipe with infinite and instant transfer capacity. But it's not sending anything. If i add resonant servo to pull instead it will work, but it only keeps up with 2 of the output slots, leaving 5 processing lines go idle.

I tested outputting to right side into chest and it works. Also this bug i've seen at random times in many different versions of Mekanism, that machines are not out auto-ejecting.

Mekanism-1.7.10-8.1.8.258

**Comment by laz2727** [comment]
I can't even begin to tell how bad that setup sounds.

**Comment by Zaflis** [comment]
All other mods machines are fine with outputting into those ducts though, including TE and EnderIO. So how can you tell which mod is using API's or something wrong, TD or Mek? Would you think TD contains any EnderIO specific code?

Not sure what you mean by bad setup, it's made for endgame carrying capacity. ME interface can handle way more items than almost any sum of machines can output.

**Comment by laz2727** [comment]
While ME can handle any load, TD can't. It's severely limited by the
servos. ExU pipes are much better for close ranges.
It's pretty likely that EIO has some related code.
I can't see the code right now, but it looks like there's simply no
autoimport slot in the pipes.

**Comment by laz2727** [comment]
Checked EIO code. It seems to actually do the insertion through cofh apis.

**Comment by isochronous** [comment]
I ran into a similar issue yesterday, only with logistics pipes (from the LP mod, not Mek's version). I had four enrichment chambers in a row, each one block apart from the others. Itemducts inputting into the top, power into the bottom, with basic logistics pipes handling output at the back... Only the enrichment chambers would not eject into the logistics pipes. The enrichment chambers were configured to auto-eject with their output set to the back, but nothing. I've got a room full of TE, EIO, and Mek machines, and they all output into the logistics pipes just fine except for the Mekanism ones. Eventually I just replaced those logistics pipes with itemducts, with signalum servos pulling out the back, ran the item ducts to feed into my logistics pipes network, and that worked. Not a big deal, but a little weird.

**Comment by aidancbrady** [comment]
I don't think this is an issue on my end, assuming you're using the latest release of Mekanism.  I'd be happy to reconsider if this is isolated to be on my side.

**Comment by KingLemming** [comment]
This is simply Mekanism not implementing the CoFH API. Nothing more.

**Comment by Zaflis** [comment]
And yeah i tested on the very latest (1.7.10-8.1.8.261) version of Mekanism. Those 2 other machines are outputting into pipe fine:

http://imgur.com/a/TqLn8
