### ISSUE TITLE
[Suggestion] Bubble trail if using the scuba tank underwater

### ISSUE THREAD

**Issue by EzerArch** [aidancbrady/Mekanism#3101]
Totally aesthetics. Low priority.

If you are underwater using the gas mask with the scuba tank, the player would emit a stream of bubbles upward, continuously or every ~3 seconds, while you don't run out of oxygen. In case you miss the air meter...

**Comment by Nova001Sol** [comment]
Every few seconds would certainly be more realistic. One doesn't release a constant stream of air either, after all.

**Comment by aidancbrady** [comment]
Done :)
