### ISSUE TITLE
Digital miner stops working after some time

### ISSUE THREAD

**Issue by xGhost169** [aidancbrady/Mekanism#3102]
Digital miner doesn't work sometimes, it just shows ores to mine, but doesn't mine them(on a modpack server)

http://i.imgur.com/dPARO0J.png
http://i.imgur.com/tFM1ITX.png
http://i.imgur.com/uxsReK1.png

**Comment by aidancbrady** [comment]
There's a good chance those ores are somehow protected by the server- this would be intended functionality.

**Comment by xGhost169** [comment]
Well, the server owner said that there are no ores protected by the server.

**Comment by VT-14** [comment]
Are you near spawn?

**Comment by xGhost169** [comment]
Nah, it works for some time, then randomly stops working, it does drain the power however. You have to replace it to get it working again
