### ISSUE TITLE
[Digital Miner] Please, by default, make it so the digital miner...

### ISSUE THREAD

**Issue by AzazelTheDark1** [aidancbrady/Mekanism#3104]
Please make the digital miner from your amazing mekanism mod, not mine lava or water (still and source) blocks. Thanks.

**Comment by Landrash** [comment]
By default the miner wont mine anything.

**Comment by AzazelTheDark1** [comment]
On inverse mode, sorry. 

    On Wednesday, February 17, 2016 5:26 AM, Landrash <notifications@github.com> wrote:
 

 By default the miner wont mine anything.—

**Comment by aidancbrady** [comment]
Done :)
