### ISSUE TITLE
Mekanism Jetpack breakable by RotaryCraft Bedrock Sword

### ISSUE THREAD

**Issue by BlueAgent** [aidancbrady/Mekanism#3105]
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/627
Relevant files:
https://github.com/ReikaKalseki/RotaryCraft/blob/f7e9b3f91553aae85449dd5b5ce419456a74c32c/Items/Tools/Bedrock/ItemBedrockSword.java
https://github.com/aidancbrady/Mekanism/blob/bfd32a1c3e5cc97b90040e43270c6e87d5180189/src/main/java/mekanism/common/item/ItemJetpack.java

Mekanism overrides damageArmor from ItemArmor to do nothing.
damageArmor is used when the entity wearing the armor is taking damage.

The bedrock sword in addition to dealing damage, does durability damage directly to the item. https://github.com/ReikaKalseki/RotaryCraft/blob/f7e9b3f91553aae85449dd5b5ce419456a74c32c/Items/Tools/Bedrock/ItemBedrockSword.java#L130

Mekanism sets the maxDamage of the item. https://github.com/aidancbrady/Mekanism/blob/bfd32a1c3e5cc97b90040e43270c6e87d5180189/src/main/java/mekanism/common/item/ItemJetpack.java#L40
This causes the jetpack to become damageable.

Mekanism uses the durability value of the item to display the fuel level. If the item is not damageable, the damage bar does not render.

Potential solution:
Set maxDamage to 0 to make the item unbreakable.
Override Item.showDurabilityBar to return true. (By default it returns true if the item is damageable).
Override Item.getDurabilityForDisplay to return the fuel level. (By default it returns the ratio damage/maxDamage)

Off topic: I love both mods and want to make a mod too some day.
Edit: Changed links to files to permalinks

**Comment by BlueAgent** [comment]
Is also destroyed by Ars Magic 2's fire guardian melt armor spell when fuel level is less than 25%.
https://github.com/Mithion/ArsMagica2/blob/5bc4c93979b6170d52cc9c7110f490b308ed058b/src/main/java/am2/spell/components/MeltArmor.java#L55

**Comment by aidancbrady** [comment]
Fixed, thanks a bunch for the excellent report!

**Comment by BlueAgent** [comment]
No problem, it was fun to look into the interaction :)

**Comment by flier268** [comment]
Jetpack will be broken by any damage,when i have install minefantasy2
I don't know why,but I guess,it is because Jetpack does not have durability.
I don't know how to fix it.
please help!
