### ISSUE TITLE
[ 8.1.8 ][ Mass Item Deletion ] Piping Stacks into inventories that only accept single items deletes all but 1 of item

### ISSUE THREAD

**Issue by Aedda** [aidancbrady/Mekanism#3110]
Piping Stacks into inventories that only accept single items deletes all but one of item per stack.

Steps to reproduce:
Chest or other inventory, connected to an inventory (that only accepts single items per slot) via an Advanced Transport Pipe.

Pipe will pull stacks from the first inventory and insert the first item correctly but then discards remainder of stack.

Tested with Tinkers Construct Smeltery Controllers and Thaumcraft Pedestals.

**Comment by aidancbrady** [comment]
This has already been reported.

**Comment by ariscop** [comment]
Can you link where it was reported? i can't see an open issue for this bug

**Comment by aidancbrady** [comment]
https://github.com/aidancbrady/Mekanism/issues/3018
