### ISSUE TITLE
[idea if possible]: Steam will be converted into a Gas instead of Fluid if mekanism is installed

### ISSUE THREAD

**Issue by mariodk** [aidancbrady/Mekanism#3112]
Steam is a Gas form of Water basically not a fluid
but becuase most mods is mainly Items/energy/Fluid but no gasses
Steam in those mods is a Fluid but since mekanism has Gasses 
but this idea can make Steam be converted into a Gas if mekanism is installed
but this also needs alot of mod compatibility: railcraft,big reactor,thermal expansion & etc.(stuff that uses the fluid: Steam)

so machines that uses "steam" needs to be connected to gas pipes instead of fluid pipes if mekanism is installed
as i said: if this idea is possible 

but we Needing a Tesseract like item/block to send Gasses wireless
since the only mod that can do that is: 2x Compact machines with nether star upgrade and both quantum linked to each other so they got the same inside(like 2 linked enderchest)
but for each compact machine you use for send wireless Gasses you needing 1x chunk more to be loaded

**Comment by XFactHD** [comment]
This is not easy to do because every mod author would have to add compatibility by himself.

**Comment by VT-14** [comment]
Steam is in the Ore Dictionary.

Messing with the Ore Dictionary in the way you are suggesting is a great way to get shunned by the modding community.


Making steam a gas makes sense.  However, Mekanism doesn't use steam (it uses Water Vapor), so the only thing this would accomplish would be to break other mods and force them to use Mekanism gas pipes.  That's like selling a window repair service by throwing a brick with your company's contact information through someone's window.

**Comment by mariodk** [comment]
i was also thinking this would be near impossible to do sadly
so kinda hope mod dev. who is working with something about the steam
will think about mekanism soon since Steam is a Gas 
mekanism has existed for some years now so kinda hoping we can do something about making steam offcial a Gas in minecraft now instead of a fluid 

but as XfactHD said: every mod author would have to add compatibility by them self
but would be nice still

**Comment by unpairedbracket** [comment]
Fun Fact: Gases are fluids, just like liquids are. A fluid is any substance that deforms continuously under applied shear stress. I think it's more helpful in many cases to think of Mekanism's "gases" more as chemicals that require special methods of transport and storage, especially given some of them would actually be liquids under standard conditions. I might propose to Aidan that we rewrite things that refer to gases to refer to them as chemicals, actually.

**Comment by aidancbrady** [comment]
I agree completely with @unpairedbracket on this one- right now we treat gases more as chemicals than as generic gaseous substances. Perhaps this change could be made in the 1.8.9/1.9 port to avoid API conflicts.
