### ISSUE TITLE
Suggestion:  Gas tank fill gauge

### ISSUE THREAD

**Issue by UnixRonin** [aidancbrady/Mekanism#3113]
I have a small, simple [I hope] request regarding gas tanks.

The gas tank already has a "dot" on one side which shows where its default output side is. And that "dot" is actually more of a kind of a vertical bar than a "dot". And pressurized tubes don't connect right up to the tank, they leave a gap in which the "dot" remains visible.

So ... how much work would it take to make the "output side dot" do double duty as a fill-level gauge?

Looks to me like the "dot" is six pixels high. Conveniently, a tank holds 96000 millibuckets, divisible exactly by six. Which means each pair of pixels in the gauge could represent 16000mb. The way I'd do it is probably to offset it by half of that, so 0-8000mb is solid red; 8001-24000mb, the lowest two pixels turn green (or blue, or white, or whatever); 24001-40000mb, the next pair "light up"; until at 88001mb or higher, the entire gauge is "lit". (Or, you could light individual pixels and have each pixel represent 8000mb instead of each row representing 16000.)

If you wanted to get really fancy, you could have the "dot"/gauge pixels light up in the same color scheme that pressurized tubes use to show their contents, so that the gauge would show not only roughly how much gas is in the tank, but what gas is in it.

**Comment by Greylocke** [comment]
I'm not sure that giving that "dot" double-duty is the best solution, but **having **a gauge is a great idea -- especially a gauge that shows the color of the stored gas.

**Comment by aidancbrady** [comment]
As Gas Tanks have just been remodeled, I'm going to need to put this one off for a while. It's not off the queue, but I need to focus on bug fixes and some higher-priority content first.
