### ISSUE TITLE
Induction Matrix stopped working

### ISSUE THREAD

**Issue by Mattallum** [aidancbrady/Mekanism#3114]
Hi,

Before I updated to 8.1.9 my induction matrix was running fine, using Thermal Dynamics cryo-stabilised fluxducts between the fusion reactor and the matrix. I updated and now the induction ports are refusing input from the Thermal Dynamics fluxducts, both cryo-stabilised and resonant. I've also tried it with basic universal cable and Ender IO Ender Energy Conduits. The cables/conduits/ducts all show as being powered, but the Induction Matrix doesn't show any input, and the charge which was held in there is now gone.

Any ideas? What can I do to help with tracing this - logs etc.?

**Comment by jaap81** [comment]
I can confirm this. Induction Matrix seems to retain it's information. When breaking a block and then replacing it makes it work again until the server reboots.

**Comment by aidancbrady** [comment]
Strange, nothing was changed between the two versions that could cause this.  I'll do a bit more digging.

**Comment by aidancbrady** [comment]
Ah, I think I found the issue- it has to do with a change in the multiblock algorithm I implemented.  I'll push out a quick fix and bump it to recommended :)

**Comment by aidancbrady** [comment]
Build 265 has the fix.

**Comment by jaap81** [comment]
That was quick! Updating asap. Thanks
