### ISSUE TITLE
Requirement for x5 Processing?

### ISSUE THREAD

**Issue by chaos234** [aidancbrady/Mekanism#3115]
Hey,

I've a question how to setup a not laggy x5 production. I also read https://github.com/aidancbrady/Mekanism/issues/2601 before but I can't figur out what is actually needed.

My setup actually (not compleatly connected) are 80 full sized towers (yes 80). Watter support comes from "Infinite Water Source" from Gany's End and all those 80 towers are standing in a 2.0 RFTools-Biom where no night is present.

Next part is the first step - washing the ore (sulfur is not the problem). For this 3 machines I seted it up 10 times (means 10 washer, 10 crystalizer and 10 dissolutions - goal are 20). This produces with max upgrades a fast production in the first x5 step. Now it has to go the Elite Injection Factory - actually I seted up 6 of them with full upgrades and here are the problem which I can't handle ... the Hydrogen Chloride Production.

Can it be that we are using to much of all those machines? What is the ground setup for a working x5 production? @aidancbrady announced in his comment (look at the linked ticket) to quadrouble the brine production but what does this means directly?

What I know is that the speed upgrade can either give x10 or x256 speed and gas only x10. But because I don't know how many mb/t Brine is produced with one 18 height 2.0 mult tower I can't do maths on it so I hope that you can help me with it or better with the following:

1. How many brine can one full x2 tower produce and is this equal to lithium?
2. One UMP can hold 64kmB/t Fluid and transfers 6.4kmB/t Fluid. Are the capacity added with each additional UMP in this network and also the Pump Rate?

3. How many towers are needed for at last constant x5 Production (1 of those 3 machines, the injection and so on)?

It will be glad to read good news :).

**Comment by aidancbrady** [comment]
While I don't know the exact numbers off the top of my head, you'll be happy to know that the amount of towers required for processing has been nerfed a good bit for v9- I figured that five towers is way too much for a single line of 5x ore processing.

**Comment by chaos234** [comment]
The problem is that the server owner don't do any update. Not mekanism, not AE2, not another one.
This means that this sounds good for v9 but we won't get it :(.

This means - @aidancbrady - that I must use this, what's given in 1.8.7 which means that my question is still open :( ...

**Comment by aidancbrady** [comment]
Well in that case there's not much I can say- I don't know the exact numbers for the old evaporation plant requirements.  Mekanism v9 is coming out sometime before summer so perhaps the server owner can be convince to update in that period.

**Comment by chaos234** [comment]
Short notice ... I have to use 48 SEPs for only one Elite Injection Machine with full upgrades. Not less because all Blocks are TileEntities ^^.
