### ISSUE TITLE
[Suggestion] More LUA support

### ISSUE THREAD

**Issue by MJRLegends** [aidancbrady/Mekanism#3116]
Please could you add methods such as

"getEnergyStored()"
"getEnergyPerTick"
"getWaterTank()"
"getSteamTank()"
"getDeuteriumTank()"
"getTritiumTank()"
"getFuelTank()"
"getBufferedEnergy()"
"getMaxPlasmaTemperature(boolean active)"
"getMaxCasingTemperature(boolean active)"
"getIgnitionTemperature(boolean active)"

because i would really like to make some advanced programs for the reactor but the LUA support is quite limited atm

**Comment by Sil3ntStorm** [comment]
getEnergyStored and getBufferedEnergy would be the same thing wouldn't it?

**Comment by MJRLegends** [comment]
Yeah I suppose it would be

**Comment by Theagle43** [comment]
I just used getEnergyStored() in a single player world running Mekanism 8.1.9. That definitely exists.

**Comment by aidancbrady** [comment]
I have added the following methods:
- getIgnitionTemp()
- getEnergy()
- getMaxEnergy()
- getWater()
- getSteam()
- getFuel()

I hope this is helpful!

**Comment by MJRLegends** [comment]
@aidancbrady Thanks for adding them, when do you think the next release/build will be out containing them.

**Comment by MJRLegends** [comment]
@aidancbrady The getFuel() one isn't very helpful since it doesnt actually have a buffer of fuel stored in the reactor so just returns a value of 0, could you consider adding "getDeuteriumTank()" and "getTritiumTank()" please
