### ISSUE TITLE
Fusion Reactor Loading/Unloading Issue

### ISSUE THREAD

**Issue by MJRLegends** [aidancbrady/Mekanism#3119]
Right i've got a fusion reactor setup with fuel being cabled in to the reactor through pipes.

![2016-03-03_15 45 31](https://cloud.githubusercontent.com/assets/8526321/13499614/08b3291e-e157-11e5-91d9-c0655f5b7b00.png)

Im using:
Mekanism-1.7.10-8.1.8.261
MekanismGenerators-1.7.10-8.1.8.261
MekanismTools-1.7.10-8.1.8.261

Playing on a server using kcauldron!

The reactor has a reaction that is taking place like the image shows above, when logging out near the reactor then logging back in to the world(with no chunk loaders keeping it loaded while no one is near it) the reaction have stopped when logging back in, 

But then when I chunk load it so it keeps it loaded while no one there i can log out and back in and the reaction is still taking place. It seems to be a chunk loading/unloading issue...

Edit: I know im using a older version of Mekanism but i have checked the github commits and nothing seems to show that anything has changed with the fusion reactor code that would affect this issue, so i dont think updating to the newest version will help.

**Comment by MJRLegends** [comment]
Also even if i chunk load the reactor, the reaction still stops when the server restarts anyways.

**Comment by MythixDino** [comment]
> Also even if i chunk load the reactor, the reaction still stops when the server restarts anyways.

I don't h

**Comment by MJRLegends** [comment]
@MythixDino yeah that might just be my reactor is running out of fuel, but the chunk unloading is 100% a bug

**Comment by aidancbrady** [comment]
I'm pretty sure that this was fixed recently, I remember going through the reactor initiation code. Update to the latest Mekanism and if this is still an issue I'll reopen.

**Comment by MJRLegends** [comment]
Ok I will give it a test and get back to you

**Comment by MJRLegends** [comment]
@aidancbrady nope still isnt fixed when using the latest version

**Comment by MythixDino** [comment]
I can confirm they will still turn off when they get unloaded.

**Comment by MJRLegends** [comment]
Any news on this issue @aidancbrady

**Comment by aidancbrady** [comment]
Fixed, thanks!

**Comment by MJRLegends** [comment]
When will the update be out containing the fix?

**Comment by aidancbrady** [comment]
Sometime next month. All development has been shifted to the release of v9.

**Comment by MJRLegends** [comment]
Really, geez. That's a long wait for this fix for this annoying bug :(
