### ISSUE TITLE
Glitch with IC2 Glassfibre & MFSUs and adv cables

### ISSUE THREAD

**Issue by BlazingGamer** [aidancbrady/Mekanism#3120]
![2016-03-06_22 00 08](https://cloud.githubusercontent.com/assets/13196222/13556326/dac90d96-e3e7-11e5-8273-a95d36fbeeaa.png)
![2016-03-06_22 05 22](https://cloud.githubusercontent.com/assets/13196222/13556325/dac82e26-e3e7-11e5-8e2d-c198367d7324.png)

**Comment by aidancbrady** [comment]
These interaction issues have already been reported.
