### ISSUE TITLE
[REQUEST] Swap 'dump' and 'dump excess' on the electrolyser

### ISSUE THREAD

**Issue by Nova001Sol** [aidancbrady/Mekanism#3122]
It may just be me of course, but it's always bothered me that we go from keeping everything to dumping everything to dumping what we can't store. It's not a big thing, and I'll still enjoy the mod if you decide to keep the current order.

Anyway, thanks for reading.

**Comment by Sil3ntStorm** [comment]
Another way might be to add right click to the button to go backwards through the cycle.

**Comment by aidancbrady** [comment]
Fixed in dev :)
