### ISSUE TITLE
Use for Na (sodium)

### ISSUE THREAD

**Issue by The-Silver-Kid** [aidancbrady/Mekanism#3123]
Please make some use for sodium like make Sodium Nitrate NaNO3 for soda or something

**Comment by The-Silver-Kid** [comment]
Yes well i just want a use for it other then just sitting in a tank not doing anything

**Comment by Nova001Sol** [comment]
Fair enough. I just use it to keep track of how much chlorine I use. A little over three bedrockium drums now. Then again I _am_ a chronic hoarder. Unless you are too, just fill up a reasonably compact tank and dump the excess.

**Comment by The-Silver-Kid** [comment]
that is what i am doing now but i would still like a use for it

**Comment by Cracks777** [comment]
Use Minetweaker and create a use for it.

**Comment by The-Silver-Kid** [comment]
Minetweaker can do that? cool but i would still like some sort of official use for it

**Comment by Cracks777** [comment]
Minetweaker and Modtweaker

**Comment by aidancbrady** [comment]
This has already been brought to my attention; though I can't promise anything for v9, there are differently uses planned for the future.

**Comment by The-Silver-Kid** [comment]
thanks

**Comment by Herowl-s** [comment]
Actually, if it is producing sodium, it should be using molten salt and not brine. In reality, brine gives chlorine, hydrogen, and sodium hydroxide solution. After all chlorine is out, it starts hydrolysing water in the solution, giving hydrogen and oxygen... but never sodium, at least not until it uses up all the water, effectively drying the solution... and then you would have to melt the sodium hydroxide anyways to give hydrogen, oxygen and sodium.
As much as I know that the mod is not realistic... I still think realism is affordable in such cases. When you will be adding some uses for sodium, please either make it more complex and realistic by making it give hydrogen and chlorine + the solution remaining to be handled, or simply exchange brine for molten salt. Aside of some recipe changes, it shouldn't be that hard, would it?
