### ISSUE TITLE
Add Mekanism (and Co.) to Curse

### ISSUE THREAD

**Issue by callmebackdraft** [aidancbrady/Mekanism#3125]
Hi there,

It would be nice to add Mekanism to Curse so it can be used in the Curse Voice minecraft launcher.

**Comment by HanatakeYurii** [comment]
Nice to ask. Thought I'm not sure Aidan will agree as he never intended to put it on Curse and remove the last version uploaded on it (but the guy didn't asked and published it as a (fake) fork).

Don't hope too much

**Comment by callmebackdraft** [comment]
Asking is all we can do, installing isnt to hard but it would be a nice addition that could increase userbase ;). and of course Uploading a File/Mod/program which is not yours should not be condoned.

let's see what aidan says :D;)

**Comment by VT-14** [comment]
In #2380  he said he was thinking about it.  That was sometime last year.

I'm quite curious what Aidan's thoughts on Curse are at the moment.

**Comment by Nova001Sol** [comment]
I'd rather he put it on CurseForge actually. Curse lags the Nether out of my browser and I don't know why.

**Comment by Nova001Sol** [comment]
Ah. Sorry, I assumed they meant Curse. Why do they even _have_ mods on both Curse and CurseForge anyway?

**Comment by aidancbrady** [comment]
This is being considered, I promise :)

**Comment by usafphoenix** [comment]
unable to safely/securely transit through completion of downloading mekanism since last two releases. AdFly pages get hijacked WAY too easily. please take this into consideration for hosting project on curse.com aka cursefoge

**Comment by ShadowDrakken** [comment]
Yeah, AdFly is broke as all heck lately... comes up blank, then when you wait out the timer and click the link it brings you to multiple very spammy and hacky looking and just totally untrustworthy sites with no actual downloading of Mekanism possible. I finally gave up and searched out an unauthorized mirror because it was impossible to get through AdFly's spam wall.

**Comment by usafphoenix** [comment]
i eventually found it by downloading some random modpack (Random meaning i
forgot which one lol)
