### ISSUE TITLE
Wireless Power/Item/Liquid/Gas transport

### ISSUE THREAD

**Issue by The-Silver-Kid** [aidancbrady/Mekanism#3126]
Like the Thermal expansion Tesseract but more mekanismy

**Comment by Nova001Sol** [comment]
We have teleporters and fusion reactors only slightly taller than my bedroom, so it should be well within the scope of technology available to the modern Steve sapiens sapiens. I like this idea. Shame that my opinions are insignificant where Mek development is concerned.

**Comment by aidancbrady** [comment]
Already under development :)

**Comment by Majora320** [comment]
@aidancbrady any status on this?

**Comment by thiakil** [comment]
Holy necropost batman, you want the Entangoloporter

**Comment by Nova001Sol** [comment]
@Majora320 How did you even _find_ this? It's literally been almost two years since this issue was opened and closed.

**Comment by Majora320** [comment]
Sorry! Googling"mekanism wireless power" and similar doesn't return any results, so I didn't know you needed to use that. Thanks!
