### ISSUE TITLE
Factory Energy Usage

### ISSUE THREAD

**Issue by Sil3ntStorm** [aidancbrady/Mekanism#3128]
I'd suggest the RF/t reading to be the total energy required for the entire block/machine, not just a single part/slot of the machine. It would make it easier to calculate power needs / see if one can afford the power.

**Comment by VT-14** [comment]
You don't necessarily have all lines in a factory going at one time, so being able to see the power requirements of 1 line and multiplying as needed is better than having to divide by 3, 5, or 7 and then multiply as needed; at least in my opinion.

When using a Elite factory, (7 lines) and are using 4 lines at the same time, It's easier to take 20 rf/t per line and multiply by 4 (to get 80 RF/t) than to take the possible 140 RF/t total and multiply by 4/7.

That said, I agree that adding an "at max capacity" statistic would be somewhat convenient.  I just ask that you don't remove the per line stat.

**Comment by aidancbrady** [comment]
This is now complete, factories display actual current energy usage.
