### ISSUE TITLE
Chargepad + Teleporter block glitch

### ISSUE THREAD

**Issue by IcieFlake** [aidancbrady/Mekanism#3129]
Is it just me that fall throught the portal (without frame) when there is a chargepad nearby?
Don't know if there is a mod compatibility issue with these 2 objects/blocks Or if its some other mod messing something up for Mekanism. 
(still using these 2 in a fresh single player world i get issues) 

Also, I would be very thankful if someone could give me a link to what possible commands there are with ComputerCraft and Mekanism, been googling and searching various places for 2 hours now and cannot find any info on even how to connect a fusion reactor to a CC computer (at this moment im going with bundle cable but there is a need for making it more "high tech" now) 
But more importend what API commands/etc that are available with CC and mekanism blocks and machines..+ rest..xP

BestRegards 
Icie

**Comment by IcieFlake** [comment]
Also i just remmberd a suggestion (not sure if its been up here before) 
But since Massive RF and J have been intreduced, isn't it possible to make a lightning rod (Ofcourse insanely expensive mats to handle that "1.21 Gigawatt" xP )
But a Lightning rod, (higher better chanse of getting a strike) and it would shock charge your induction matrix =3 
(more energy providers = less chanse of a boom) and boom crater is increased by Matrix block ammount/ size

**Comment by aidancbrady** [comment]
The chargepad is not a solid block, but the teleporter is- I'm not sure why you'd be falling through the block.  I'll consider a lightning rod in the future :)
