### ISSUE TITLE
[SUGGESTION] Port to MCPE

### ISSUE THREAD

**Issue by MochifishCoder** [aidancbrady/Mekanism#3131]
I love the mod, but I am bad at MCPC. I am good at MCPE, and I think it would be fun if Mekanism was in MCPE. Just a suggestion.

**Comment by aidancbrady** [comment]
This is something that I'm not going to be able to get around to. If someone else is familiar with the MCPE framework they're welcome to make a port.

**Comment by MochifishCoder** [comment]
Ok. Thanks for your input, and I will try to find someone who can port soon. By the way, keep it up with the good work!
