### ISSUE TITLE
Unviersal Cables are transfering too much power!

### ISSUE THREAD

**Issue by Scoredlizard** [aidancbrady/Mekanism#3132]
On a single player world I have been doing a number of tests regarding universal cable. When doing this I came across a bug. When there are more universal cables hooked up in a circuit it increases the amount of J/t that the wire can transfer. (Example) say if I had power transferring from one energy cell to another, if the two energy cells are one block away from each other I would need only one basic universal cable to connect them, lets say this cable is able to transfer power at 3200 J/t, if i were to add two more cables anywhere on this circuit, the first wire would then be able to transfer 9600 J/t. Eventually by adding enough cables you can  make a basic universal cable be able to transfer more power than an ultimate universal cable!

**Comment by aidancbrady** [comment]
This is intentional behavior :)
