### ISSUE TITLE
BUG - Energy Upgrade Not Working on Electro Separators

### ISSUE THREAD

**Issue by Utildayael** [aidancbrady/Mekanism#3133]
Hi Aidan!

Minor bug. The energy upgrades when used on an electrolyte separator does increase max energy storage but does not increase efficiency as it does on all other machines and per the tooltip. I'm not sure if this is "as designed" but a base electro stays at 160 RF/t with no upgrades and with 8 energy upgrades. 

Thanks :)

**Comment by aidancbrady** [comment]
This is sadly needed to prevent energy duplication with a gas generator.  Check out the issues list, though- we're trying to find a better option.

**Comment by Utildayael** [comment]
Ahh makes sense now! Thanks :)
