### ISSUE TITLE
.getEnergyStored() still returns a value in J

### ISSUE THREAD

**Issue by Theagle43** [aidancbrady/Mekanism#3134]
I'm not sure if this is something that you have control over or if it's on the ComputerCraft/OpenPeripherals side of things, but I just wanted to let you know that even though the GUI of every power storage block in Mekanism displays in RF, the .getEnergyStored() command still displays those values in J, and must be multiplied by 4 to get the RF value. Is this intentional?

**Comment by aidancbrady** [comment]
This is intentional, yes- getEnergyStored() returns all values in base Mekanism units (J).
