### ISSUE TITLE
Suggestion: Remove the heavy water filter from the pump and move it to another processing machine

### ISSUE THREAD

**Issue by bshelden** [aidancbrady/Mekanism#3135]
It would be nice if we could process water into heavy water inline rather than only being able to do it at the original water intake.

This will avoid strange issues like the pump once in awhile getting ahead of Minecraft's replenishment code causing stoppages to the heavy water processing line (assuming water is sourced another way).

**Comment by aidancbrady** [comment]
The issue you described is fixed in v9.
