### ISSUE TITLE
Cardboard boxes delete Magneticraft Shelving Units

### ISSUE THREAD

**Issue by bloxgate** [aidancbrady/Mekanism#3137]
Just encountered this nasty bug. I tried to pack a shelving unit using a cardboard box. The shelving unit's GUI opened for a second instead of packing, then both it and the box disappeared. Everyone nearby checked their inventories but could not find it. We tested it on another shelving unit and got the exact same results. We checked the server console and didn't see any errors.

Mekanism Version: 1.7.10-8.1.8.258
Magneticraft Version: 0.6.1-final

**Comment by aidancbrady** [comment]
This is an example of an interaction that would call for a blacklist entry. There are simply too many special cases for me to account for.

**Comment by Alexismachina** [comment]
@bloxgate Do you have your forge config to remove erroring tile entities ?

**Comment by bloxgate** [comment]
@Alexismachina No I don't. Both settings for removing entities are set to false.

**Comment by Alexismachina** [comment]
Hum...yeah i guest just add it to the blacklist like aidan said would be the best thing :/
