### ISSUE TITLE
Remaining water/brine in solar evaporation plant

### ISSUE THREAD

**Issue by compughatt** [aidancbrady/Mekanism#3138]
Using Mekanism 8.1.7, the solar evaporation plant internal tanks do not completely empty out after the water/brine supply is turned off or exhausted. Most often, there is some tiny amount of fluid left in the tanks that is too small to convert to brine/lithium, so it just remains there. There is no option to dump it or remove it either.

I got out of this problem of water in the tank once by having exactly 0mB left and then it was really empty. However, now I encounter the same issue with the brine. There is 2mB of brine left. I can't drain it out, and I can't make more brine because water cannot get into the tank with the remaining brine there.

**Comment by VT-14** [comment]
If I recall correctly, a Gauge Dropper lets you remove small amounts of liquids and gases from the machine GUI.  pick up and click the dropper on the tank you want to empty, then hold it and (shift?) right click it on the ground [voids fluid] or another tank to empty it.

**Comment by aidancbrady** [comment]
Right, that's part of the reason why I developed the gauge dropper.

**Comment by compughatt** [comment]
Thanks that worked great. Thanks!
