### ISSUE TITLE
Questions: Tweaking Solar Neutron Activator, config explanation

### ISSUE THREAD

**Issue by Pordy** [aidancbrady/Mekanism#3139]
Hello!
I want save my server rescources, and i would like to change the production rates of the SNA's, since i dont find options in the config to do that, i have to edit the mod .jar or zip files.
I am very newbie at java programming. 
May you help me find the attributes that i need to modify, and suggest me any value?
Maybe you can add a config option to do that?

Can you explain me this two line?
    B:AestheticWorldDamage=true
    B:AllowSpawnerBoxPickup=true - if i use ender I/O i got a broken spawner, and i am able to move the spawners with jabba dollys, but if this is true, and i use only the makanism i need a special too for that? 

Thx.

**Comment by XFactHD** [comment]
You can't unpack a jar and just edit it. You need to either use a byte code editor (which I absolutely don't recommend!) or take the source from the github, change the values and compile it yourself. If you don't know how to do that, don't try it. Also, there might be big changes in performance, etc. in the upcoming v9.

**Comment by aidancbrady** [comment]
AestheticWorldDamage allows things like the flamethrower to cause damage to the world.
AllowSpawnerBoxPickup allows the Cardboard Box to pick up vanilla spawners. It's basically a box blacklist entry.
