### ISSUE TITLE
[REQUEST] Water output for gas generator

### ISSUE THREAD

**Issue by Nova001Sol** [aidancbrady/Mekanism#3141]
I would like to request a new(-ish) feature. The gas-burning generators can run on hydrogen (H2) and ethylene (C2H4), yes? Burning either produces water because both involve the oxidizing of hydrogen. This is why I would like the generator to output water.

One advantage to the gas-burning generators outputting water is to allow for a fully self-sustaining oxygen-producing loop using only Mekanism. This is possible because looping the water eliminates the power cost of the pump.

Another would be slightly cheaper ethylene production, once again because the need for a pump is eliminated.

Either way, thank you for reading.

**Comment by aidancbrady** [comment]
Mekanism v9 makes water much easier to pump through upgrades and the new option of not sucking the water source.  I'll keep your suggestion in consideration, but I'm gonna mark this closed for now.  Thanks!
