### ISSUE TITLE
Portable Teleporter not saving settings

### ISSUE THREAD

**Issue by Sil3ntStorm** [aidancbrady/Mekanism#3145]
The portable teleporter always opens on the public tab, instead of the one used last. Would be nice if it could store the last used tab, maybe even the last used Frequency so that if you want to transport back  there again you would only have to hit the teleport button. But even only saving the tab that was last used would be a huge benefit.

**Comment by The-Silver-Kid** [comment]
Being someone who uses the portable teleporter a lot this would be useful especially when i'm digging on the moon and run out of oxygen i could quickly teleport back to earth and not lose all my health trying to go through my teleporter list trying to find one of the teleporter frequencies i have on earth

**Comment by aidancbrady** [comment]
Done! Portable Teleporters now bind to their owner and save the last used frequency.
