### ISSUE TITLE
Electrolytic Separator speed upgrade bug

### ISSUE THREAD

**Issue by diamondpumpkin** [aidancbrady/Mekanism#3146]
When I upgrade an Electrolytic Separator with 8 speed upgrades the speed effect is 256... But my config is set to 11, other machines do not do the same thing.

**Comment by aidancbrady** [comment]
Fluid-based machines function differently with speed upgrades, the modification is hard-coded in for balance and simplicity reasons.

**Comment by diamondpumpkin** [comment]
I can't even use the machine...
