### ISSUE TITLE
Server Crash upon doing /spawn

### ISSUE THREAD

**Issue by Yanniclord** [aidancbrady/Mekanism#3147]
So, it happened somewhat random. It didn't happen ever before, but when i did /spawn from someones base, the server crashed with this log:

http://pastebin.com/fkezcZfx

**Comment by aidancbrady** [comment]
Already reported

**Comment by Yanniclord** [comment]
@aidancbrady So why is it still happening in the latest version of Mekanism if it was already reported?

**Comment by Yanniclord** [comment]
New log: http://pastebin.com/K7GuE2Nv

**Comment by HanatakeYurii** [comment]
it's probably in the dev version, thus not out yet
