### ISSUE TITLE
Fusion Reactor does not run on D-T Fuel

### ISSUE THREAD

**Issue by Sil3ntStorm** [aidancbrady/Mekanism#3149]
When pumping in D-T Fuel directly as opposed to having the reactor create it itself, the reactor does not run. It'll start shortly if providing an initial power burst with lasers but will not really consume any fuel and will just instantly begin the cooldown phase.
The wiki mentions it can be run on D-T Fuel, plus it would save having to craft another set of 2 Ports.

It will only work if you pump in Tritium and Deuterium separately.

**Comment by aidancbrady** [comment]
I get the feeling something is off in your setup.  You can directly pump D-T fuel in directly assuming it is in its gaseous form- it will not insert the liquid form.  I have tested this multiple times.

**Comment by Sil3ntStorm** [comment]
fair enough, I'll delete everything and try again next week.
