### ISSUE TITLE
Dynamic Tank issues

### ISSUE THREAD

**Issue by Sil3ntStorm** [aidancbrady/Mekanism#3150]
The Wiki mentions a maximum Size of 18x18x18, however the multiblock will still form when the size is for example 3x3x20 (outer bounds).

When building a maximum sized 18x18x18 cube (outer bounds, higher doesn't form) the fill gauge in the UI doesn't seem to work properly. It will show about 20% full when the tank is entirely filled and not accepting any more fluid. (was filled using multiple ultimate mechanical pipes each with its own bedrockium drum)
![2016-03-25_21 00 26](https://cloud.githubusercontent.com/assets/12677273/14052738/b18883aa-f2cc-11e5-8dc0-f2abf8b41e2e.png)

Also it seems that it becomes less efficient with higher tank capacity? A single block in the center (3x3x3 tank) can store 432 buckets worth of liquid and has a volume of 27 according to the UI. The max size tank in above image has 16x16x16 = 4096 blocks in the center with a volume of 5832. As such it should store 432 * 4096 = 1769472 buckets worth of liquid, the tank above only stores 93312 and is visually full and not accepting additional Lava.
The volume is only 216 times as much, even though there are 4096 blocks inside it instead of just 1. It just doesn't seem right.

**Comment by aidancbrady** [comment]
Fixed, thanks :)
