### ISSUE TITLE
Rotary condensentrator oxygen

### ISSUE THREAD

**Issue by zane49er2** [aidancbrady/Mekanism#3153]
I realize this is not strictly a mekanism issue, but I don't know where else to go:
When I pump oxygen into a rotary condensentrator, instead of liquid oxygen, I get 1mb of "oxygen gas" and the machine stops working. I cannot de-condensentrate it, and trying to pump it out with mechanical pipe crashes the game. I have no idea what mod the oxygen gas comes from, either.
EDIT: I have figured out the crash is probably related to chickenchunks.

**Comment by aidancbrady** [comment]
Use a gauge dropper to get rid of the "oxygen gas." Likely due to an already-existent oxygen registration

**Comment by zane49er2** [comment]
Thank you for trying to help, but I think you may have misunderstood my issue. If I want to get rid of the oxygen gas, I can just throw away the condensentrator. the issue is that I want to stop it from ever being made. I was wondering if I could change a config, the registry, or just delete the mod. If anyone knows what mod the gas is coming from please let me know.
