### ISSUE TITLE
v9 Localization

### ISSUE THREAD

**Issue by aidancbrady** [aidancbrady/Mekanism#3154]
@Vexatos, @Adaptivity, @EzerArch, @LFalch, @Mazdallier, @TheVikingWarrior, @mymagadsl, @Mr-tanaka3, @halvors, @Mrkwtkr, @al-myr, and anyone else interested

**Translations complete:**
- French
- Danish
- German
- Chinese (Simplified)
- Russian

Calling all willing translators!  Mekanism v9 is nearing its release date, and it'd be awesome to have updated localizations alongside it.  Thanks!

EDIT:
Please note that the updated files are located in the **development branch.**

**Comment by EzerArch** [comment]
I tried to translate these strings:

![2016-03-27_22 52 47](https://cloud.githubusercontent.com/assets/6743303/14070127/f0cd67d0-f478-11e5-9290-7a5163192264.png)

I couldn't find them in both master and dev branches.

**Comment by HanatakeYurii** [comment]
Hi, pulled updated FR localization.
Anyway thanks for you work

**Comment by LFalch** [comment]
I'll have a look and see if I can manage to get something done.

**Comment by IcieFlake** [comment]
Like i stated in the pull topic
I can do the Swedish and Polish translation if there would be any need for that.

**Comment by aidancbrady** [comment]
Swedish and Polish would be fantastic, @IcieFlake!

**Comment by Vexatos** [comment]
I am rather busy with university right now. I may be able to sneak in a translation some day if I get the chance to.

**Comment by LFalch** [comment]
I've submitted a PR for the Danish translation now. (See #3157)

**Comment by aidancbrady** [comment]
Thanks @Vexatos, anytime within the next month would be perfect.

**Comment by MineWitherMC** [comment]
I've submitted a russian localization PR.

**Comment by 3TUSK** [comment]
Question, seems like there is something untranslatable:
![21cfc672-4533-4983-8de0-f6110764067c](https://cloud.githubusercontent.com/assets/9113033/15269054/1ecab968-19c1-11e6-8650-402584102326.png)
Picture is provided by @sfmiyuki

**Comment by 3TUSK** [comment]
Make a reference to #3216 which updates Simplified Chinese localization to v9.

**Comment by karakufire** [comment]
I'm trying localization to Japanese. I tried to see Industrial Tubine GUI, but I've not know how to constuct it. Would you teach me to construct industrial turbine?

**Comment by 3TUSK** [comment]
@karakufire Check out [this teaser](https://www.youtube.com/watch?v=R69_SkPoYcQ) and also [this teaser](https://www.youtube.com/watch?v=4W-9alhZGng).

**Comment by karakufire** [comment]
@3TUSK I already checked both of them teaser. but I can't understand how these constructed, especially Industrial Turbine. and these movies do not mentioned how to construct multi-block machinery. what I should do?

**Comment by 3TUSK** [comment]
Hmm... Call @sfmiyuki. I bet he knows more details than me, and I currently don't have enough time to make a detailed spoiler.

**Comment by aidancbrady** [comment]
@karakufire, if you shoot me an email I can send you my internal documentation on the multiblock structures.

**Comment by karakufire** [comment]
@aidancbrady I see.

**Comment by IcieFlake** [comment]
Sorry, I've been very busy irl lately.
Back to continue translating it all to Swedish.
The polish one won't be as hard to translate since there is an old translate.
And the hardest task I've had so far is to make up names as accurate as possible while some english words/names do not exist in Swedish or Polish.

**Comment by LFalch** [comment]
@IcieFlake Making up names was also hard for the Danish. Sometimes I also just resorted to writing the English word, since we've often do that in Danish when there's no Danish word.

**Comment by IcieFlake** [comment]
Yeah I know, Same in Sweden. But the Swedish translation in Minecraft is so well done that I just had to do the same xP.

**Comment by EzerArch** [comment]
Just a question: are the most updated files still located in the development branch? Can I get those in Master?

**Comment by aidancbrady** [comment]
They are. 1.9.4 builds are in the 1.9.4 branch.
