### ISSUE TITLE
salt generation problem

### ISSUE THREAD

**Issue by SvEgiiVEteR** [aidancbrady/Mekanism#3158]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294659-climate-control-change-climate-zones-sizes-ocean?page=55#c1111
please see. salt with generation problem when large oceans.
in combination with these mods and seed world.

**Comment by aidancbrady** [comment]
I wouldn't call that an issue with my mod. Salt's generation code is almost identical to that of clay.

**Comment by SvEgiiVEteR** [comment]
yes there together mode, those that I have listed. removing one of them, the problem is solved. But I was able to solve the problem by turning off the salt. without shutting down any of the mods.
