### ISSUE TITLE
Interaction issues with universal cables.

### ISSUE THREAD

**Issue by MineWitherMC** [aidancbrady/Mekanism#3160]
1) Issue with ThermalDynamics' CryoStabilized Fluxduct. Basic, Advanced and Elite cables work fine, but Ultimate...
1a) Resonant Energy Cell, TE (it was full before I connected cryo-duct):
![2016-04-02_08 03 57](https://cloud.githubusercontent.com/assets/18210824/14224643/51f06cce-f8ac-11e5-811f-522b52184a2b.png)
![2016-04-02_08 03 59](https://cloud.githubusercontent.com/assets/18210824/14224644/51f1f4a4-f8ac-11e5-95f9-f8bd4ad3386a.png)
1b) Vibrant Energy Cell, EIO:
![2016-04-02_08 04 32](https://cloud.githubusercontent.com/assets/18210824/14224655/dc32614e-f8ac-11e5-8ee2-a8bb1e814a53.png)
![2016-04-02_08 04 42](https://cloud.githubusercontent.com/assets/18210824/14224656/dc32c972-f8ac-11e5-94b4-0cc3de1075aa.png)
![2016-04-02_08 05 34](https://cloud.githubusercontent.com/assets/18210824/14224657/dc34a878-f8ac-11e5-8e3a-48d29890c9a8.png)
1c) Energy Cubes, Mekanism (I'll show 1 only, but its for all 4):
![2016-04-02_08 27 23](https://cloud.githubusercontent.com/assets/18210824/14224665/04e915c4-f8ad-11e5-81ab-df410beb6588.png)
![2016-04-02_08 27 27](https://cloud.githubusercontent.com/assets/18210824/14224664/04e8d726-f8ad-11e5-8105-df4d65c07966.png)
2) Issues with IC2:
2a) U.Cables don't connect to wires:
![2016-04-02_08 11 27](https://cloud.githubusercontent.com/assets/18210824/14224670/2859ea56-f8ad-11e5-81b7-f7a39432b27f.png)
2b) Can't output energy (for example from MFSU):
![2016-04-02_08 13 37](https://cloud.githubusercontent.com/assets/18210824/14224672/45fe048e-f8ad-11e5-98a4-12448b4eda70.png)
![2016-04-02_08 13 43](https://cloud.githubusercontent.com/assets/18210824/14224673/4604ae88-f8ad-11e5-8cae-4c476e518c9e.png)
Mekanism 8.1.9 build 265.

**Comment by Adam4CZ** [comment]
to 1) :
https://github.com/aidancbrady/Mekanism/issues/3077 (Mekanism-1.7.10-8.1.8.258)

**Comment by laz2727** [comment]
Fluxducts are very weird. Your RF is probably in them.

**Comment by MineWitherMC** [comment]
Nope, they dont store RF as they are cryostab. and transfer infinite.

**Comment by MineWitherMC** [comment]
@Adam4CZ yup but not for elite cables.

**Comment by Adam4CZ** [comment]
@MineWitherMC At an earlier version I've tested all cables and this problem was only with elite/ultimate cables.

**Comment by MineWitherMC** [comment]
@Adam4CZ this means @aidancbrady has a bug in ultimate cable code, I'll look in commit that fixed #3077 and maybe will find something.

**Comment by Adam4CZ** [comment]
@laz2727 No, see in TheSprtCz's issue (https://github.com/aidancbrady/Mekanism/issues/3077).
I've tested only cryo-stab. fluxdust and nothing happened, only when I connect Elite or Ultimate cable to cryo-stab. fluxdust, energy gets lost.

**Comment by aidancbrady** [comment]
The issues you mentioned have been fixed.

**Comment by MineWitherMC** [comment]
Nope, they weren't. I tested them today (latest recommended build 265) and they happened. Then I looked into the commits that fix #3077 and didn't find any of them.

**Comment by aidancbrady** [comment]
The fixes are in the development branch.

**Comment by MineWitherMC** [comment]
OK, will test and tell results. :)
