### ISSUE TITLE
Interaction with Nuclearcraft

### ISSUE THREAD

**Issue by th4umiel** [aidancbrady/Mekanism#3161]
I know that you are already working on V9, but I only wanted to point out a strange interaction with the Nuclearcraft mod. When both mods are installed, I can't find a single Mekanism ore in the world. I was searching for osmium, but I am quite sure that the problem persists even with tin and copper. 
Maybe it's too late to let you know this, as I am still using 1.7.10, but... Better to say it, don't you think? :)

P.S: I've already pointed out the issue in the Nuclearcraft github page, but I think that a cross-post is the best solution.

**Comment by aidancbrady** [comment]
I'm not sure if this is on Nuclearcraft's end but it's definitely not on mine, all my ore registrations are done in accordance with Forge guidelines.  Thanks for reporting though, good luck :)
