### ISSUE TITLE
java.lang.StackOverflowError: Ticking block entity at net.minecraft.world.World.func_147438_o(World.java:2540)

### ISSUE THREAD

**Issue by jaap81** [aidancbrady/Mekanism#3162]
[crash-2016-04-02_11.46.29-server.txt](https://github.com/aidancbrady/Mekanism/files/202116/crash-2016-04-02_11.46.29-server.txt)

Not sure what is happening here. This is on a private server with a custom modpack. Seems to have something to do with multiblock liquid tanks?

**Comment by aidancbrady** [comment]
It's been fixed for v9, thanks :)
