### ISSUE TITLE
Fusion Reactor

### ISSUE THREAD

**Issue by landunter** [aidancbrady/Mekanism#3163]
the mekanism reactor generates allways max heat and energy when i set input rate to 22. EVEN when there is no fuel in the reactor and its switched off!!

I dont know if this description is enough or i made a noobish mistake...  if u have any more questions feel free to ask.

**Comment by aidancbrady** [comment]
The "max heat and energy" you describe scales up with the input rate, so technically you're generating the max values at every input rate, as long as you're supplying enough fuel.

**Comment by landunter** [comment]
i play your mod in dnstechpack... and i do not need any fuel. i just build the reactor set input to 22 and without starting process i get sick high temperatures...
