### ISSUE TITLE
[BUG] Memory leak with Solar EvapTower

### ISSUE THREAD

**Issue by spannerman79** [aidancbrady/Mekanism#3164]
Forge 1614
Mekanism-1.7.10-8.1.9.267.jar
MekanismGenerators-1.7.10-8.1.9.267.jar
MekanismTools-1.7.10-8.1.9.267.jar
SMP
Linux
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)

Steps to reproduce:
Create a solar evap tower 15 - 18 blocks high (biome doesn't matter)
Place controller down near the bottom of the tower (+2 blocks up from base)
Forces a 8GB instance of just Mek alone to push past 8GB and start to use swap (memory leak)

![2016-04-08_01 04 52](https://cloud.githubusercontent.com/assets/7542384/14356264/835b178a-fd27-11e5-9575-ab25942183d7.png)

**Comment by aidancbrady** [comment]
This has been fixed for v9, thanks.
