### ISSUE TITLE
Crash on Joining Server [BUG] 

### ISSUE THREAD

**Issue by AdamMOD** [aidancbrady/Mekanism#3166]
Greeeetings
I'm playing on a custom pack with my friend, here are the mods (in the form of screenshots of my mods folder):
 https://gyazo.com/068c5f936e7314a50369349b710d7662
https://gyazo.com/f7aa1d12872660967c6e5052f2148b5d
It started crashing this morning, I was playing on the server without a problem last night.
Here's the log: 
http://pastebin.com/Pd5EjgT7

I can't find a thing on this. Anyone got any ideas?

**Comment by CristinoValdigem** [comment]
i've found 2 Optifines. leave only 1.... You Shutdown the mod in night and when u open in morning it's crash ??

**Comment by AdamMOD** [comment]
Issue resolved, apparently someone spawned in a couple hundred villagers too many and the server had to restart. Thanks for pointing out the optifine issue though!
