### ISSUE TITLE
Logistical sorter miscoloring items

### ISSUE THREAD

**Issue by khumps** [aidancbrady/Mekanism#3168]
When items are put in a chest connected to a logistical sorter items are pumped out the correct color. however as soon as the machines recieving said color are full the logistical sorter pumps the items out in the default color. The Supply crates should always come out purple. however as soon as the machines they are meant to go to are full they pump out yellow. this happens for everything else too
[http://prntscr.com/aq9fif](url)
[http://prntscr.com/aq9frt](url)

Edit: Version 8.1.7

**Comment by aidancbrady** [comment]
This is intended.  Auto-eject is on, so when there is no room left for a block to enter an inventory with its filter color, it will try to find a location with the default color.
