### ISSUE TITLE
[Request] Compatibility with CoFH friends system for teleporters

### ISSUE THREAD

**Issue by Mrrraou** [aidancbrady/Mekanism#3170]
It would be awesome to be able to make private frequencies shared with your friends, so you can use the same teleporter for your entire team/friends, without making it accessible to other people. It can be done for the Thermal Expansion Tesseracts, where you can set the Restricted mode to only make it accessible for your team.

**Comment by aidancbrady** [comment]
I have integrated my own system of trusted players for v9 :)
