### ISSUE TITLE
Reactor Fuel Bug

### ISSUE THREAD

**Issue by landunter** [aidancbrady/Mekanism#3171]
So i already opend a topic.. but u closed it. i made a video:
https://youtu.be/VslWlfVlawE 

i tested DNS Techpack 7 8 4 1 with updated mekanism *267 and the 265 Version.
And on DNS Techpack 7 8 5 0. allways the same...

i did not touch the mekanism configs I only updated the mod.

**Comment by aidancbrady** [comment]
Ah. You're right, the max steam value for injection rates above 21 was exceeding the max integer value. Fixed :)
