### ISSUE TITLE
Oredictifionificator 3 filters only [old issue]

### ISSUE THREAD

**Issue by condensedapple** [aidancbrady/Mekanism#3174]
In the newest version of Mekanism, you can add only three filters, trying to add a new one results in modifying the third filter. This seems to be related to #2676 and #3124 
It would be awesome if you could fix this bug so you dont have to use the NBT-method described in issue 2676.
Keep up the good work and im looking forward to playing v9!

**Comment by aidancbrady** [comment]
Fixed!

**Comment by condensedapple** [comment]
Nice!
