### ISSUE TITLE
In-Game Config Editor Description Tags Broken

### ISSUE THREAD

**Issue by The-Silver-Kid** [aidancbrady/Mekanism#3175]
I am 100% sure its not supposed to do this.

![screenshot 2016-04-17 16 37 27](https://cloud.githubusercontent.com/assets/7415468/14590585/c15a23dc-04bb-11e6-8188-62c08f1bbe1d.png)

**Comment by aidancbrady** [comment]
I can't reproduce. Make sure your MCForge is up to date.
