### ISSUE TITLE
not sure where to best ask so i am asking here. RE *HOW* to add to curse modpacks

### ISSUE THREAD

**Issue by Mementh** [aidancbrady/Mekanism#3176]
I have a friend that wants to add mekanism to the modpack.. and its not showing up on curse for use which would make it easier. 

I see the option to donate to access the ones on mr bradys server but i was thinking its ok to host it for download on my friends server? but my friend was thinking it was not? 

I don't know legal well enough but i was curious since it seems the MIT license allows it? or is the only way to add to a modpack to use the download options you have to donate for?

**Comment by aidancbrady** [comment]
Yeah, my license honestly should be updated. There's a few things I need to change...

Your friend is welcome to host mekanism if it is for a private community, or within a mod pack :)

**Comment by VT-14** [comment]
You can download it for free from here (this link is on the wiki and I'm fairly certain it's Aidan's website).
http://aidancbrady.com/mekanism/download/

That will take you to an AddFly download page.  There will be a skip add link in the top right after about 5 seconds.  From there, you can download the mod.  Repeat for each sub-mod.  I don't think you need the MDK.

To install, place those .jar files into the Mods folder for that instance on both the server and clients.  Curse has a convenient 'open folder' option under the "..." button in the top right (I think, not too familiar with the new layout yet).

As for future hosting on Curse: #3125.

**Comment by Mementh** [comment]
@VT-14 using for a modpack wont work with adfly sadly :/
