### ISSUE TITLE
Crash while creating world

### ISSUE THREAD

**Issue by programgames** [aidancbrady/Mekanism#3178]
Hi, i got the same issue than "jeviuss " : https://github.com/aidancbrady/Mekanism/issues/3152

And u answered : "Fixed in dev :)" so, i downloaded 8.1.9.267 for 1.7.10 version.
And i got again the issue.What i need to do then ?
Sorry for my bad english.

**Comment by aidancbrady** [comment]
The development branch has not yet been pushed to master.  The issue has been fixed, don't worry- expect a release soon.

**Comment by programgames** [comment]
Ok, thank you very much.Waiting the release for my server :)
