### ISSUE TITLE
When using Factory Installers, Security is reset

### ISSUE THREAD

**Issue by MyNameIsKodos** [aidancbrady/Mekanism#3181]
Reproduction is simple:

Place Factory-Upgradeable machine
Set Security (or have it already set via the Desk)
Upgrade with Factory Installers
And at least in the GUI, the security is reset and owner as well.

**Comment by aidancbrady** [comment]
Ooh, thank you. This is something I need to update in the recipe as well.

**Comment by aidancbrady** [comment]
Fixed :)
