### ISSUE TITLE
TPS / Java Cleanup Bug

### ISSUE THREAD

**Issue by legracen** [aidancbrady/Mekanism#3188]
With Version 8.1.9.265 I noticed alot of lag on my server pack. After checking in Java VM i caught the cpu usage spiking like crazy. When i removed Mekanism it went away. So i rolled back and tried the previous version of the pack.

version 8.1.8.258
![image](https://cloud.githubusercontent.com/assets/4247799/14853182/bb9c1c0a-0c47-11e6-81b0-5399be76ac5c.png)

Version 8.1.9.265:
![image](https://cloud.githubusercontent.com/assets/4247799/14853198/c698691a-0c47-11e6-8304-77febfccd4b2.png)

Not sure what update to the code would cause cleanups to suddenly jump this high. Even idle with noone on the server it causes tps to drop as low as 6.5

**Comment by aidancbrady** [comment]
Likely due to the memory leaks I encountered- should be fixed v9.

**Comment by NoOneNo** [comment]
when can we expect v9?
