### ISSUE TITLE
MekaTools-(weapon)-(utility)-(other) discussion

### ISSUE THREAD

**Issue by Alexismachina** [aidancbrady/Mekanism#3189]
This is a bit like the mekasuit discussion , yesterday i briefly talked to aidan on irc about weaponry, i suggested a sword that powers on gas to create a plasma or Flame-sword. I wonder what you guys can come up with like in the MekaSuit-Discussion.

**Comment by aidancbrady** [comment]
Gonna close this for now, if you want to discuss the tools then just use the current MekaSuit discussion thread.

**Comment by Alexismachina** [comment]
alrigth
