### ISSUE TITLE
Gas-Burning Generators not updating properly with new universal cable

### ISSUE THREAD

**Issue by TacoMage** [aidancbrady/Mekanism#3191]
If you break a universal cable attached to a gas-burning generator and replace it, the generator's burn rate drops to 0, but it still continues to "run" (noise persists, but it produces no energy nor does it burn fuel).  

If you cycle through all the redstone settings in the generator twice, the generator will start working again (cycling only once seem to have no effect).  You can also save and quit then reload and it'll also recover and start working properly.

This was observed in an SSP world with release 921.

**Comment by aidancbrady** [comment]
Fixed!
