### ISSUE TITLE
Display issues in thermal information

### ISSUE THREAD

**Issue by TacoMage** [aidancbrady/Mekanism#3193]
There are two display issues:

The thermal popup overlay always displays Transferred and Dissipated information in Kelvin, despite selecting other units.

"Transferred" number is always 0.00 K/t no matter what the transfer rate actually is.

An example of this is below.

![thermal_bug](https://cloud.githubusercontent.com/assets/11623906/14877515/44a13bfc-0ce3-11e6-8f81-ac7d97569cea.png)

**Comment by aidancbrady** [comment]
Fixed.  I've removed the "Transferred" display, it is unnecessary overall.
