### ISSUE TITLE
FakePlayer Location is reported incorrectly

### ISSUE THREAD

**Issue by DraksterAU** [aidancbrady/Mekanism#3199]
Hi There,

I'm currently trying to make the Mekanism Digital Miner and BuildCraft quarries support some level of grief prevention (especially on servers running Factions/Towny/WorldGuard/Grief Prevention etc).

See here for the BC Post: https://github.com/BuildCraft/BuildCraft/issues/3323

Any chance you could do the same for Mekanism in a later build?

The Location of your digital miner fakeplayer is reported as t he block that was broken, not the miner itself.

**Comment by aidancbrady** [comment]
I'm fairly certain that the way I have the fake player implemented is the same way all similar mods manage the interaction as well.  If the BuildCraft team decides to adjust to fit your suggestion, I'll do the same- just let me know.

**Comment by DraksterAU** [comment]
@aidancbrady Thanks for the fast response Aidan.

Turns out that to support this you'd have to implement multiple Fake players (to report different concurrent locations) and forge require a 0,0,0 position anyway.... so this is a no go :(

**Comment by DraksterAU** [comment]
@aidancbrady

Build craft after going to adapt, they can see the merit in it :)

Please do when you get a chance.

Regards
DraksterAU

**Comment by DraksterAU** [comment]
@aidancbrady 

Are you still up to doing this one mate?
Build craft have completed their changes :)
I'll finish off the plugin today or tomorrow!

Regards
DraksterAU
