### ISSUE TITLE
Atomic Disassembler interaction with EnderZoo

### ISSUE THREAD

**Issue by Karmacopper** [aidancbrady/Mekanism#3201]
One of the newer mobs in EnderZoo is triggered to spawn when dirt isn't broken with a "shovel". Dirt broken with the Atomic Disassembler is triggering this spawn, making the AD all but useless as a shovel where both mods are installed. (Current workaround is to deactivate the EZ mod.)

MC 1.7.10
Mek 8.1.9
EZ 1.0.15.32

**Comment by aidancbrady** [comment]
Already reported. Definitely a strange interaction
