### ISSUE TITLE
Advanced Solar Generator won't show up in NEI and can't be crafted

### ISSUE THREAD

**Issue by Afra2015** [aidancbrady/Mekanism#3204]
I'm playing the Direwolf20 1.7.10 pack, latest version of the pack. 
I added Mekanism to the pack, it's not originally in it.
I wanted to make the solar evaporation plant but when I went to make the advanced solar generators, they wouldn't show up in NEI. When I tried to create the generator manually in a crafting table, the output was empty.

I can't make the solar generator, the advanced solar generator and the solar panels.
I also checked all mekanism items to see if it has a different name, but that doesn't seem to be the case.

I'm using Mekanism version 8.1.9. I have several other mods that weren't part of the Direwolf20 pack:
Ars Magica 2, Decocraft and their required mods. I'm not sure if it's relevant though.

**Comment by aidancbrady** [comment]
Make sure you've installed MekanismGenerators :)
