### ISSUE TITLE
[Suggestion] Add a delay for the portable teleporter

### ISSUE THREAD

**Issue by EzerArch** [aidancbrady/Mekanism#3206]
I was messing around with portable teleporters. I noticed I could teleport from anywhere I was, in any situation (as long as the device is charged), to another place at a heartbeat.

What if there were a 5 second delay between when you press "Teleport" and the event, and perhaps with a cool animation?

This is a sort of a "balancing" issue: while the normal teleporters require you build 2 of them and you go/walk to them to teleport, the portable teleporters are always at hand, they can work immediately, and you can get away with almost anything, such as a hostile mob siege, falling in lava, multiplayer combat etc.

**Comment by mimikal** [comment]
100% agree on that! And also that it takes more energy, so the portable teleporter becomes more of a couple-use emergency thing rather than a quite OP gadget.

**Comment by CJL48** [comment]
Definitely a good idea. I might add that it makes sense for the portable teleporter to take more energy than the one that has a frame to form the field in- it has to use more energy to define the area of effect/push the area of effect outside of itself.

**Comment by mimikal** [comment]
Yes.

**Comment by Mementh** [comment]
i would suggest the inreased power usage.. but also a "advanced" teleporter remote that offers a quicker teleport or a "shield" while teleporting?

**Comment by themechman** [comment]
This makes more sense for single player, but SMP servers are usually laden with instant alternatives such as /home /spawn or /back.

**Comment by EzerArch** [comment]
> but SMP servers are usually laden with instant alternatives such as /home /spawn or /back.

Yes, but this is a decision of the server staff on _their_ own server: some may want Civ and PvE: staff can give players ores or valuable drops, which would render the digital miner useless; others may want PvP: usually [PvP logging](http://gaming.stackexchange.com/questions/112484/what-does-pvp-logging-mean-in-minecraft) is strongly discouraged, so would be instant teleportation.

But still,

**Comment by aidancbrady** [comment]
Added a config option, "PortableTeleporterDelay", that defines the time in ticks it takes to teleport after pressing the teleport button.
