### ISSUE TITLE
[Question] About 1.8.9 branch

### ISSUE THREAD

**Issue by miuirussia** [aidancbrady/Mekanism#3207]
How to compile Mekanism for 1.8.9? Maybe I can test this version and write bug reports and PR fixes

**Comment by aidancbrady** [comment]
The 1.8.9 branch is currently far too bug-ridden to be tested- I'm considering jumping to 1.9 just to escape the horror that is Tile Entity management in 1.8.  I'll definitely consider giving testers access to 1.8.9 once it's ready.
