### ISSUE TITLE
Dupe Bug with Robit and MFR Spawner

### ISSUE THREAD

**Issue by Eufranio** [aidancbrady/Mekanism#3208]
1- Put down an Robit and put something into your inventory.
2- Go away to Robit walk to you
3- Catch the Robit with a Safari Net from MFR
4- Put the Safari Net in the spawner and select "spawn exact copy"
4- Profit. A lot of robits with dupped inventories.

**Comment by laz2727** [comment]
1- Put down a zombie and put something into its hands.
2- Catch the zombie with a Safari Net from MFR
3- Put the Safari Net in the spawner and select "spawn exact copy"
4- Profit. A lot of zombie with duped items.

2016-05-10 21:19 GMT+05:00 Eufranio <notifications@github.com>:

**Comment by Eufranio** [comment]
Maybe block Robit of be catched by other mods... ? Is it possible?

**Comment by laz2727** [comment]
There's a SafariNetBlacklist.

**Comment by Eufranio** [comment]
But other spawners may still spawning it...

**Comment by laz2727** [comment]
There are three spawners i know of, EIO spawner has no such bugs and
Draconic cannot even capture anything.

**Comment by ktole1999** [comment]
If u have ability to place zombie then why are u worried about dupe items. Normal user can't place mobs unless cheated in or creative.

Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone<div>
</div><div>
</div><div>-------- Original message --------</div><div>From: laz2727 <notifications@github.com> </div><div>Date: 5/10/2016  11:37 AM  (GMT-06:00) </div><div>To: aidancbrady/Mekanism <Mekanism@noreply.github.com> </div><div>Subject: Re: [aidancbrady/Mekanism] Dupe Bug with Robit and MFR Spawner (#3208) </div><div>
</div>
1- Put down a zombie and put something into its hands.
2- Catch the zombie with a Safari Net from MFR
3- Put the Safari Net in the spawner and select "spawn exact copy"
4- Profit. A lot of zombie with duped items.

2016-05-10 21:19 GMT+05:00 Eufranio <notifications@github.com>:

> 1- Put down an Robit and put something into your inventory.
> 2- Go away to Robit walk to you
> 3- Catch the Robit with a Safari Net from MFR
> 4- Put the Safari Net in the spawner and select "spawn exact copy"
> 4- Profit. A lot of robits with dupped inventories.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/aidancbrady/Mekanism/issues/3208>
>


---

**Comment by laz2727** [comment]
Ugh. You don't need to pull something that spawns every night from creative.
