### ISSUE TITLE
Idea: Atomic Disassembler sounds

### ISSUE THREAD

**Issue by SupernovaCo** [aidancbrady/Mekanism#3210]
Would it be possible to add sounds to the atomic dissasembler (kinda like the ones in [this video](https://www.youtube.com/watch?v=4J5dUtIvx0Y))?

**Comment by aidancbrady** [comment]
It technically would be possible, but I think the default breaking sound is sufficient for the disassembler.

**Comment by SupernovaCo** [comment]
I meant the ambient hum while the atomic dissembler is equipped, not the
break sound.

*--Marvin_Megavolt*
