### ISSUE TITLE
Solar Evaporator without Generators?

### ISSUE THREAD

**Issue by MineWitherMC** [aidancbrady/Mekanism#3212]
I play without MekGenerators and thus can't build solar evaporator as if I put S.E. blocks in corners (the ones for Adv Solar Panels) the structure completes but it never gives me non-zero multiplier...

**Comment by aidancbrady** [comment]
Won't be an issue in v9 :)

**Comment by MineWitherMC** [comment]
Will you fix this for 1.7?

**Comment by ktole1999** [comment]
Aiden are you removing solar from multi block and allowing get tower to be externally.powered?
