### ISSUE TITLE
Mekanism v9 crash on construction

### ISSUE THREAD

**Issue by MineWitherMC** [aidancbrady/Mekanism#3214]
After compiling Mekanism myself I'm getting this bug...
http://codepad.org/gfx6m4xu

**Comment by aidancbrady** [comment]
Is this in a development environment? Client or server?

**Comment by MineWitherMC** [comment]
Client, not dev env. I'm guessing if I'm using correct file (it was called toObf[LongNumberCode].jar)...

**Comment by aidancbrady** [comment]
Likely an issue with your obfuscation then when compiling.  I'm testing a build of v9 in a vanilla MC environment and everything works fine.

**Comment by MineWitherMC** [comment]
Yes this is because the same crash happens in vanilla. Also a strange crash appears when LiteLoader is used...
http://codepad.org/ZOXjWpju
