### ISSUE TITLE
Portable Teleporter issue

### ISSUE THREAD

**Issue by Cbert** [aidancbrady/Mekanism#3218]
Portable Teleporter don’t have scroll, (1) but it has some bar that looks like scroll.
It don’t show more than 4 addresses to teleport, however, if you type address manually, you could teleport to that location.
I think it would be better to scroll and have ability to choose from more than 4 addresses.
![portable teleporter issue](https://cloud.githubusercontent.com/assets/9320867/15275404/69a274e0-1ad3-11e6-91f6-57b7ea33a7ee.png)

**Comment by aidancbrady** [comment]
Click and drag the scroll thing :)

**Comment by Cbert** [comment]
Can you make it scroll with mouse wheel?

**Comment by Cbert** [comment]
Ok :(
