### ISSUE TITLE
Unknown block ID crash 

### ISSUE THREAD

**Issue by GmanAtheist** [aidancbrady/Mekanism#3219]
[crash-2016-05-16_03.08.46-client.txt](https://github.com/aidancbrady/Mekanism/files/265435/crash-2016-05-16_03.08.46-client.txt)

Any chance that could be fixed?. Thanks.

**Comment by MineWitherMC** [comment]
@GmanAtheist This crash is caused with UnwrittenFun utils aka CommonFun/WorldTeleporters and has nothing related to mekanism. Try removing them.

**Comment by GmanAtheist** [comment]
Thanks. I think there is a conflict between the Teleporters in Mekanism and [1.7.10] SecurityCraft v1.8.1. Because when I try and link a Camera to the hand-held monitor I get this crash report.  I won't use the cameras in SecurityCraft, a shame because they used to work fine before I installed Mekanism . I am not a fundy at this . Just a gamer. looking for some help. :-)

**Comment by MineWitherMC** [comment]
@GmanAtheist interesting...  I can't help you with this issue as 
> I am not a fundy at this . Just a gamer.
Sorry.

**Comment by aidancbrady** [comment]
I am fairly confident that this is not on my end. I've never actually seen a crash like this before.

**Comment by GmanAtheist** [comment]
Thanks for the replies. I can live without the cameras. :-)
