### ISSUE TITLE
[Bug?] Thermoelectric Boiler putting at ~305M degC

### ISSUE THREAD

**Issue by taronz** [aidancbrady/Mekanism#3221]
Not particularly sure if this is a bug because I'm not sure what the mechanics of the Superheating Elements are, build has a 3x3 interior footprint with 9 high of superheaters in a solid block.

Showing the stat screen for relevance, also wondering if we could get the formula for the Superheating elements or the mechanics?

Edit: Build is Dev v 9 0.956

![may have overengineered](https://cloud.githubusercontent.com/assets/8342484/15391490/bf0bc9ac-1e04-11e6-9135-bcd278237b51.jpg)

**Comment by aidancbrady** [comment]
Looks like the steam buffer is full so all heat energy is being directed into the casing of the multiblock instead of the water. Usually formulas get discovered by the player base pretty quickly :)

**Comment by laz2727** [comment]
Mekanism is visible source ffs
