### ISSUE TITLE
Just a collection of different issues encountered with mekanism v.8.1.9.265

### ISSUE THREAD

**Issue by lightning02** [aidancbrady/Mekanism#3223]
Hello aidan,
I'm gonna to write down here a list of issues that i encountered with mekanism before you release mekanism v.9.
(Most of them related with rftools too)
Some of these may you already know, others maybe you don't.
The first one is what happened in a all-day-dimension from rftools. When i've used the lasers to start a fusion reaction in the reactor all my solar panels became non-functional and even the new ones i was placing down after was non-funcional too
![4](https://cloud.githubusercontent.com/assets/11884147/15401453/ef0d4532-1def-11e6-8c61-7f21d4affe28.png)

Another issue was a visual issue, the reaction inside the reactor was no more visible if the controller got removed and re-placed.
This one you see in the image instead: 
![1](https://cloud.githubusercontent.com/assets/11884147/15401460/f83b85ba-1def-11e6-96d4-e84ccc7c0259.png)

Is still visual but i'm not sure because i don't remember exactly if it was also practical, because for example this one was practical: 
![2](https://cloud.githubusercontent.com/assets/11884147/15401466/fe3bf710-1def-11e6-9d92-e8cf82b59b87.png)

As you can see in the screenshot when the chunk or the entire dimension was unloaded most of chunks was getting glitching. 
Fluidic plenishers that you see in this screenshot had to be removed and re-placed down in order to operate again and fill again the basin that was needed for electric pumps because all the water gone every time the chunk was unloaded.
The last thing is about the reactor and i'm sure you already know that when you set the reactor on fuel usage of 22% it glitches and no longer need fuel to operate and start on it's max and if you set the fuel usage on an higer level than 22% the reactor begin to burn out.
I managed to resolve most of this problems putting down chunk loaders from chikken chunks in the area when this mekanism complex was built but some day later i encountered some massive lag problems.  https://github.com/CyberdyneCC/Thermos/issues/356
Probably related to solar evaporation towers.
This is kinda the summary, i hope this could be helpfull.

**Comment by aidancbrady** [comment]
I'm pretty sure that the majority of these issues have been fixed as a result of the internal overhauls of all those depicted machinery.  If you still encounter them in v9 upon its release then I'll see about fixing them :)
