### ISSUE TITLE
v9 not working with a couple mods

### ISSUE THREAD

**Issue by bfree380a** [aidancbrady/Mekanism#3224]
V9.0.0.956 doesn't seem to work with Practical Logistics and SonarCore.

Here is the server crash log:
[crash-2016-05-19_16.55.38-server.txt](https://github.com/aidancbrady/Mekanism/files/273520/crash-2016-05-19_16.55.38-server.txt).

We ended up just removing those two.  Thanks!

**Comment by aidancbrady** [comment]
Thanks for the report!  It looks like one of those mods is using the Thermal Evaporation Plant API which was changed a bit in v9 to reflect the changes to their framework.  They'll need to update their support in order to support builds of Mekanism v9.

**Comment by bfree380a** [comment]
Thanks for letting us know :)  We'll keep an eye out for an update from them, and I'll let them know about the changes!
