### ISSUE TITLE
[Suggestion] Have the wind turbine sound categorized as "Weather"

### ISSUE THREAD

**Issue by 61352151511** [aidancbrady/Mekanism#3225]
https://github.com/aidancbrady/Mekanism/blob/master/src/main/resources/assets/mekanism/sounds.json
Instead of having the wind noise that the wind turbines make categorized as a "Blocks" noise, change it to weather, it makes sense.
I don't mind turning my weather volume down to not hear the wind turbine factory when I'm close by, but having to turn the blocks sound down means that I don't hear the placing/digging noises as well.

**Comment by Mementh** [comment]
good idea.. or let it have a sound muffler upgrade?

**Comment by aidancbrady** [comment]
Fixed!
