### ISSUE TITLE
Automating Infusing Factory is not working with SFM v9

### ISSUE THREAD

**Issue by tgstyle** [aidancbrady/Mekanism#3228]
It keeps putting items in the Extra slot, it does not accept them in the input slot. It will not put redstone, etc. in to the extra slot at all. I have it configured to put the relavant items on the UP and North side in this case.
![2016-05-20_15 20 17](https://cloud.githubusercontent.com/assets/5832709/15442450/8601c1f8-1e9e-11e6-8bb2-02da8745bb35.png)
![2016-05-20_15 20 34](https://cloud.githubusercontent.com/assets/5832709/15442453/892607b8-1e9e-11e6-8627-e0e8b3a9e46f.png)

**Comment by tgstyle** [comment]
Note: A Metallurgic Infuser works just fine in it's place.

**Comment by CristinoValdigem** [comment]
With me happened the same i upgraded one of my metallurgic infuser and when i put in the place the "infuse slot" changed the name to "extra" and stop enter compressed coal automatic

**Comment by slebreton79** [comment]
Mine is the opposite but with Ae2 unable to input into Purple Extra Slot.  Items have to be manually inputted.  But regular Metallurgic Infuser in its spot is fine.

**Comment by dsbookbug** [comment]
To elaborate, I'm also getting the same issue with Ender IO item conduits, item transfer nodes from OpenBlocks, and even the Logistical Transporters from this mod

**Comment by aidancbrady** [comment]
I believe I've fixed this, I was not using the same algorithms for item checking as I was in the metallurgic infuser.  v9.0.1 will have the change.

**Comment by CristinoValdigem** [comment]
Now after launch version 9.0.1 the infuser are accepting itens
