### ISSUE TITLE
Weird textures on two new machines Mekanism V9

### ISSUE THREAD

**Issue by Xireka** [aidancbrady/Mekanism#3229]
SO I fired up the new mekanism and noticed two textures looking weird sadly.

No idea if it's on my end or if there was an error somewhere but it's sad to see these blocks like these

If I remember correctly it's the metallurgic infuser and thermoelectric separator:

http://imgur.com/iDQwvpA

Thanks in advance for the help :)

**Comment by slidingmike** [comment]
Believe this is going to be on your end. I've had a few installs for an ATL pack I managed with no issues like this. We get the new textures.

**Comment by aidancbrady** [comment]
Same thing on my end, I'm not experiencing any issues.  Likely some kind of mod-interaction.

**Comment by b0bst3r** [comment]
Likely the resourcepack he's using.

**Comment by Xireka** [comment]
Yes, really sorry :(

My resource pack actually had a few textures I forgot about but they were for Mekanism V8 so those two machines apparently broke, I deleted the folder and now it all looks great :D

Again sorry  :(
