### ISSUE TITLE
fuelwood heater and reactor heat glitch

### ISSUE THREAD

**Issue by hollowhalls** [aidancbrady/Mekanism#3230]
hello, i was testing out the new mek9 and while testing if the heaters could interface with a reactor i found a weird glitch. i took some ultimate thermodynamic conductor in a 4x4x4 hollow box with 8 fuelwood heaters inside (2x2x2 block) after sicking a stack of blaze rods in each heater they started going haywire, shelling out temps of 2.147483647e7y degrees F. i plug the thermodynamic conductor line into my reactor thinking nothing of the temp and the animated core texture starts to violently flash. i check the temp and it is through the meter so i break all the thermo conductors and replace them. after checking the reactor again i found that the whole temp was gone, everything was set back at 0 and it seems i can start it back up again. i can attach photos if you'd like.

**Comment by aidancbrady** [comment]
Very strange, I'm looking into this now.

**Comment by Redblade21** [comment]
sorry crated my own issue that has similar effects. but I think it is linked with the Fuelwood heaters them selves.

**Comment by aidancbrady** [comment]
Fixed for v9.0.1, thanks!
