### ISSUE TITLE
Mekanism v9 and IC2 .807 IC2 Machines consume all power

### ISSUE THREAD

**Issue by YinScape** [aidancbrady/Mekanism#3231]
Attaching an IC2 machine to a Mekanism Universal cable network consumes all energy provided to network.  This did not occur in the latest v8 version.

**Comment by slidingmike** [comment]
Been testing this but unable to replicate or understand if I've got the same thing happening. Is your setup ic2 on all universal cables, or is it mix in match? I.e. I run ender io energy conduits,with Universal cables in between where I have an ic2 machine.

**Comment by YinScape** [comment]
Here is my test setup. New world, no config edits. Local Server.
Induction Matrix used for maximum output, connected by Universal Cables into a RUNNING Electric Furnace.
![2016-05-25_18 06 02](https://cloud.githubusercontent.com/assets/2998689/15557863/be6eebd4-22a3-11e6-975c-ae6d80be9d2e.png)

Power Usage shown from Induction Matrix.
![2016-05-25_18 06 10](https://cloud.githubusercontent.com/assets/2998689/15557879/d32a356a-22a3-11e6-896e-3c44e800cf8d.png)

Running Furnace.
![2016-05-25_18 06 13](https://cloud.githubusercontent.com/assets/2998689/15557886/da26bd70-22a3-11e6-95c2-507dd672735e.png)

Power Draw shown by Network Tool, note the power draw is the capacity is the throughput.
![2016-05-25_18 06 18](https://cloud.githubusercontent.com/assets/2998689/15557898/e4718abc-22a3-11e6-98b5-3af62efb4e57.png)

Add more cables to expand capacity, get more power draw.
![2016-05-25_18 06 49](https://cloud.githubusercontent.com/assets/2998689/15557909/fd21a4f2-22a3-11e6-801d-0417d93f4b33.png)
![2016-05-25_18 06 52](https://cloud.githubusercontent.com/assets/2998689/15557911/0218a8fc-22a4-11e6-9cc8-108902626582.png)

**Comment by YinScape** [comment]
Modlist
![2016-05-25_18-13-30](https://cloud.githubusercontent.com/assets/2998689/15557957/6fd17766-22a4-11e6-8651-d09a173c6a3c.png)

**Comment by VersedXth** [comment]
I have the same Problem here. If I run any IC2 machine with Mekanism cable directly my Ultimate Energy Cube drains pretty fast. Even with the Recycler without any Overclockers no chance.

**Comment by HadesDurin** [comment]
you should try it out with the latest 271 version of mekanism to see if it still happens

**Comment by VersedXth** [comment]
I'm using 2.2.804 it's higher than 271 or isn't it ?
The latest verion is 2.2.822 
I'll try it with that version

**Comment by VersedXth** [comment]
![2016-05-30_14 41 21](https://cloud.githubusercontent.com/assets/16269139/15649850/f0a1866e-2674-11e6-9541-25b07a99a180.png)
nope doesn't work

**Comment by HadesDurin** [comment]
i mean mekanism v9.0.2.271 and you are right ic2 latest is 2.2.822

**Comment by VersedXth** [comment]
I'm using mekansim v9.0.2.271

**Comment by YinScape** [comment]
51.2kj/t is just the max output of that energy cube.  I've found that the ic2 machine will consume as much as is possible.

**Comment by VersedXth** [comment]
oh I understand. Forget to check the max value of the Energy Cube. I'm now using immersive engeniering cabel for a work around , but this is hopfully soon fixed

**Comment by HadesDurin** [comment]
after some thinking about the issue, i guess its an industrial craft issue, since the maschine uses all power it gets. in my eyes its an IC issue. it could also be a cable problem, that way its an mekanism issue.
have you tried diffrent tiered cables?

**Comment by YinScape** [comment]
Yes, but this was not a problem in v8 Mek.  I discovered the bug after upgrading to v9 and the Induction Matrix in my base read empty.

**Comment by Just-some-cannibal** [comment]
I have this problem too

**Comment by YinScape** [comment]
ITh mass fabricators i had in my network did not  use steady draw of power, they consumed large spikes. I believe the behavior in v8 was that ic2 machines consumed large bursts of power from the cable,  but those bursts were stored in the machine and waited until that power was depleted before consuming another burst.

**Comment by HadesDurin** [comment]
related to some problems i have in mekanism v9, i just tought about the fakt. 

that this issue makes sence under one condition:
the mek v9 cables check the connected maschines if they have need of energy. the result is true, so maybe ic2 doens*t have the required check command to give a false output to the cable and 
additionally the input of the energy that was send is diffrent from the input when you use pure ic2 cables, energy and such.
only that explains why you can send ~51kJ/t into a macerator, which normaly only accepts 16(?) or 32 (?) EU/t.

**Comment by YinScape** [comment]
The machine does not consume power if it is not processing though.

**Comment by th4umiel** [comment]
Been able to replicate: wind generator, with a basic universal cable and metal former, macerator and furnace connected. They use all the power the cable is able to transmit, but only when processing.

**Comment by aidancbrady** [comment]
Fixed in development.
