### ISSUE TITLE
Shift clicking to insert to machine doesn't work properly

### ISSUE THREAD

**Issue by Lazarix** [aidancbrady/Mekanism#3233]
If you shift click something to go into a machine (example, food or cobble or whatever into a basic smelting factory), it goes back into your inventory like regular minecraft would.
Example, shift click from the bar, goes into your inventory. Shift click from inventory goes to the bar.
After this occurs though, the machine is processing whatever you shift clicked, so if you go to move the item in your inventory, the system seems to "catch up" and shows the item in the machine and not in your inventory.

**Comment by aidancbrady** [comment]
This was reported a long time ago and I still have been unable to find the culprit.  I'll do some searching once I've finished the majority of the issues I'm looking at, but note that it's low priority.
