### ISSUE TITLE
Electrolytic Separator power usage in v9

### ISSUE THREAD

**Issue by Mementh** [aidancbrady/Mekanism#3235]
turning water to o2 and h2

dumping BOTH 40.96k rf/tick 

dumping excess h2  excess o2 20.48k rf/tick 
same energy when running normally.

i don't believe this is normal power usage

**Comment by aidancbrady** [comment]
This is intentional, assuming you have upgrades installed.  The Electrolytic Separator is pretty power-hungry :)

**Comment by Mementh** [comment]
they are.. but the two power usages 1 with dumping all and 1 with working normal i feel is not normal.. it did not make logical sense

**Comment by aidancbrady** [comment]
The Electrolytic Separator will scale usage with the amount of available room in the internal gas tanks; if dumping is off, it is likely capping to tank capacity.
