### ISSUE TITLE
NEI not showing recipie for gas tank or other tanks in NEI Inpure glitch (info post only)

### ISSUE THREAD

**Issue by Mementh** [aidancbrady/Mekanism#3236]
looking at NEI it only shows the "gas tank" which its unable to give the recipie for.

removing inpure showed the tanks and recipie..

setting inpure to 

S:Mekanism_enabled=false did nothing.. 

removing from Mekanism.js
NEI.override("Mekanism:GasTank", [100]); 

seems to have worked.. though it is showing all teh plastic/glowpanels .. thats not a big deal :)

thought you guys should know so its documented/shown just in case someone complains

**Comment by aidancbrady** [comment]
Thanks- they likely just need to update their integration.

**Comment by Mementh** [comment]
huggles :) figured it would help having it since it would be annoying/a issue to come back to
