### ISSUE TITLE
Creative Energy Cube does not output RF to non Mekanism Cables

### ISSUE THREAD

**Issue by MRuth** [aidancbrady/Mekanism#3237]
It seems that the Creative Energy Cube does not output RF to any other mod based RF delivery system (ducts, conduits, etc.) or device such as a Thermal Expansion Pulverizer.  This only seems to happen with the creative cell, every other cell works.  Here are some attached photos for details.

![2016-05-21_09 52 41](https://cloud.githubusercontent.com/assets/3927478/15449126/715b5ab0-1f3a-11e6-89f2-44ac8d6f3aff.png)
![2016-05-21_09 52 37](https://cloud.githubusercontent.com/assets/3927478/15449128/715c5e38-1f3a-11e6-9c97-f4a27be7bf32.png)
![2016-05-21_09 52 34](https://cloud.githubusercontent.com/assets/3927478/15449129/715d1ee0-1f3a-11e6-85f6-9fd5e52e8796.png)
![2016-05-21_09 52 43](https://cloud.githubusercontent.com/assets/3927478/15449127/715bb9c4-1f3a-11e6-9781-d450fcaaf7ce.png)

**Comment by HadesDurin** [comment]
i have a simmilar issue but the other way around, that mekanism cable not transfer power from thermal expansion energy cell to mashienes

**Comment by aidancbrady** [comment]
Should be fixed, thanks- scaled down power output to Integer.MAX_VALUE

**Comment by MRuth** [comment]
@aidancbrady thanks for your awesomeness!
