### ISSUE TITLE
Problem with Turbine Casing Recipe

### ISSUE THREAD

**Issue by CristinoValdigem** [aidancbrady/Mekanism#3238]
In Nei, appear 4x Steel + 1 Osmium = Turbine Casing.. When i try to make this recipe using the same the result is Steel Casing... Following image below
![2016-05-21_12 30 23](https://cloud.githubusercontent.com/assets/16420781/15449297/14a7223e-1f50-11e6-99d8-6c76b50cfcb6.png)

![2016-05-21_12 30 36](https://cloud.githubusercontent.com/assets/16420781/15449298/17b20e4e-1f50-11e6-895c-23a041b0732b.png)

**Comment by laz2727** [comment]
Modpack bug.

**Comment by aidancbrady** [comment]
Fixed for 9.0.1, thanks!
