### ISSUE TITLE
crash with steam turbines.

### ISSUE THREAD

**Issue by achman741** [aidancbrady/Mekanism#3239]
Crashed when testing steam turbines in test world, don't know what i did to cause the crash, also cannot start world without crashing.

crash report:
[crash-2016-05-21_12.53.57-client.txt](https://github.com/aidancbrady/Mekanism/files/275951/crash-2016-05-21_12.53.57-client.txt)
log file:
[latest log.zip](https://github.com/aidancbrady/Mekanism/files/275952/latest.log.zip)

**Comment by aidancbrady** [comment]
Added a null check, thanks!
