### ISSUE TITLE
Feulwood Heater Glitch

### ISSUE THREAD

**Issue by Redblade21** [aidancbrady/Mekanism#3240]
5 or more heaters stacked(touching) when some or all are burning fuel. The temp Becomes erratic and incorrect ( and Very Buggy). I have tested attaching heat cables as well as other heat accepting Blocks( Heat Gen, Boiler, Ect) and the erratic temp transfers and shows the incorrect temp on the accepting blocks. 
![2016-05-21_12 09 56](https://cloud.githubusercontent.com/assets/19507592/15449880/e1b9149a-1f4f-11e6-81a4-bb5d48193d08.png)
![2016-05-21_12 19 03](https://cloud.githubusercontent.com/assets/19507592/15449881/e36c857e-1f4f-11e6-9306-0beca51d5b75.png)

**Comment by aidancbrady** [comment]
Fixed for v9.0.1!

**Comment by Redblade21** [comment]
Lol... Your the Best!  Fantastic update for my favorite mod!
