### ISSUE TITLE
Seems to crash when I click the "Mekanism" creative tab.

### ISSUE THREAD

**Issue by Acdrybones** [aidancbrady/Mekanism#3242]
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 5/21/16 3:37 PM
Description: Updating screen events

java.lang.NoSuchMethodError: net.minecraftforge.fluids.FluidStack.getFluidID()I
	at mekanism.common.item.ItemBlockMachine.setFluidStack(ItemBlockMachine.java:632)
	at mekanism.common.block.BlockMachine.func_149666_a(BlockMachine.java:546)
	at net.minecraft.item.ItemBlock.func_150895_a(ItemBlock.java:181)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147053_i(GuiContainerCreative.java:347)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:550)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:456)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:566)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1628)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mekanism.common.item.ItemBlockMachine.setFluidStack(ItemBlockMachine.java:632)
	at mekanism.common.block.BlockMachine.func_149666_a(BlockMachine.java:546)
	at net.minecraft.item.ItemBlock.func_150895_a(ItemBlock.java:181)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147053_i(GuiContainerCreative.java:347)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:550)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:456)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:566)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Acdrybones'/337, l='MpServer', x=-252.75, y=72.66, z=18.56]]
	Chunk stats: MultiplayerChunkCache: 495, 495
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-268,64,31), Chunk: (at 4,4,15 in -17,1; contains blocks -272,0,16 to -257,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 344 game time, 344 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 117 total; [EntitySkeleton['Skeletman'/270, l='MpServer', x=-222.88, y=15.00, z=-48.56], EntityBat['Bat'/271, l='MpServer', x=-219.45, y=23.78, z=-42.70], EntityZombie['Zombie'/272, l='MpServer', x=-215.50, y=27.00, z=-23.69], EntityZombie['Zombie'/273, l='MpServer', x=-216.50, y=27.00, z=-27.06], EntityZombie['Zombie'/274, l='MpServer', x=-215.50, y=27.00, z=-24.59], EntityZombie['Zombie'/275, l='MpServer', x=-214.50, y=28.00, z=-17.50], EntityZombie['Zombie'/276, l='MpServer', x=-214.50, y=28.00, z=-18.50], EntitySpider['Spider'/277, l='MpServer', x=-217.97, y=31.00, z=-6.59], EntityBat['Bat'/278, l='MpServer', x=-210.10, y=31.47, z=-12.51], EntityZombie['Zombie'/279, l='MpServer', x=-210.50, y=12.00, z=37.50], EntityZombie['Zombie'/280, l='MpServer', x=-208.50, y=12.00, z=35.50], EntitySkeleton['Skeletman'/281, l='MpServer', x=-217.69, y=14.00, z=32.44], EntitySkeleton['Skeletman'/282, l='MpServer', x=-216.50, y=24.00, z=39.50], EntityCreeper['Creeper'/283, l='MpServer', x=-208.53, y=38.00, z=64.97], EntityCreeper['Creeper'/284, l='MpServer', x=-210.50, y=38.00, z=67.50], EntityBat['Bat'/285, l='MpServer', x=-224.80, y=13.76, z=90.25], EntityCreeper['Creeper'/289, l='MpServer', x=-208.53, y=20.00, z=-21.11], EntityCreeper['Creeper'/290, l='MpServer', x=-204.44, y=20.00, z=-27.00], EntitySkeleton['Skeletman'/291, l='MpServer', x=-201.40, y=19.16, z=-28.49], EntityZombie['Zombie'/292, l='MpServer', x=-207.50, y=12.00, z=35.50], EntitySpider['Spider'/293, l='MpServer', x=-198.58, y=15.99, z=46.80], EntitySkeleton['Skeletman'/294, l='MpServer', x=-205.91, y=50.00, z=56.50], EntitySkeleton['Skeletman'/295, l='MpServer', x=-203.50, y=49.00, z=48.50], EntityBat['Bat'/296, l='MpServer', x=-193.52, y=32.30, z=60.45], EntitySkeleton['Skeletman'/297, l='MpServer', x=-199.13, y=39.00, z=72.50], EntityBat['Bat'/298, l='MpServer', x=-203.36, y=34.52, z=81.35], EntityZombie['Zombie'/305, l='MpServer', x=-188.50, y=47.00, z=-50.91], EntitySkeleton['Skeletman'/306, l='MpServer', x=-189.50, y=53.00, z=-61.50], EntitySkeleton['Skeletman'/307, l='MpServer', x=-187.72, y=53.00, z=-59.53], EntitySkeleton['Skeletman'/310, l='MpServer', x=-189.50, y=29.00, z=45.50], EntitySkeleton['Skeletman'/311, l='MpServer', x=-188.50, y=29.00, z=46.50], EntitySkeleton['Skeletman'/312, l='MpServer', x=-191.47, y=31.00, z=49.94], EntitySkeleton['Skeletman'/313, l='MpServer', x=-180.50, y=23.00, z=67.50], EntitySkeleton['Skeletman'/314, l='MpServer', x=-179.50, y=23.00, z=68.50], EntityCreeper['Creeper'/315, l='MpServer', x=-190.78, y=41.00, z=70.88], EntityCreeper['Creeper'/318, l='MpServer', x=-173.50, y=25.00, z=21.50], EntityClientPlayerMP['Acdrybones'/337, l='MpServer', x=-252.75, y=72.66, z=18.56], EntityPig['Swine'/98, l='MpServer', x=-328.28, y=66.00, z=-59.50], EntityPig['Swine'/99, l='MpServer', x=-326.69, y=67.00, z=-59.66], EntityPig['Swine'/100, l='MpServer', x=-324.66, y=67.00, z=-55.16], EntityChicken['Duck'/101, l='MpServer', x=-329.75, y=66.00, z=35.25], EntityChicken['Duck'/103, l='MpServer', x=-322.59, y=66.00, z=47.69], EntityChicken['Duck'/104, l='MpServer', x=-327.50, y=64.00, z=49.50], EntitySheep['Lamb'/105, l='MpServer', x=-320.50, y=67.00, z=48.66], EntitySheep['Lamb'/106, l='MpServer', x=-324.50, y=72.00, z=77.50], EntitySheep['Lamb'/107, l='MpServer', x=-321.50, y=71.00, z=73.50], EntityPig['Swine'/119, l='MpServer', x=-316.53, y=72.00, z=-48.47], EntityPig['Swine'/120, l='MpServer', x=-315.47, y=72.00, z=-49.53], EntityPig['Swine'/121, l='MpServer', x=-312.50, y=67.00, z=-51.50], EntityPig['Swine'/122, l='MpServer', x=-316.50, y=65.00, z=-47.50], EntityPig['Swine'/123, l='MpServer', x=-305.50, y=64.00, z=-20.50], EntitySheep['Lamb'/124, l='MpServer', x=-306.63, y=64.00, z=-12.91], EntitySkeleton['Skeletman'/125, l='MpServer', x=-317.50, y=19.00, z=11.50], EntityZombie['Zombie'/126, l='MpServer', x=-302.88, y=28.00, z=21.78], EntitySheep['Lamb'/127, l='MpServer', x=-319.50, y=67.00, z=41.50], EntitySheep['Lamb'/128, l='MpServer', x=-312.16, y=67.00, z=41.88], EntitySheep['Lamb'/129, l='MpServer', x=-316.38, y=67.00, z=32.16], EntitySheep['Lamb'/130, l='MpServer', x=-315.06, y=68.00, z=72.75], EntitySheep['Lamb'/131, l='MpServer', x=-314.98, y=71.00, z=78.45], EntityPig['Swine'/146, l='MpServer', x=-286.42, y=64.00, z=-62.50], EntityPig['Swine'/147, l='MpServer', x=-293.78, y=64.00, z=-57.72], EntityPig['Swine'/148, l='MpServer', x=-291.59, y=74.00, z=-28.20], EntityPig['Swine'/149, l='MpServer', x=-300.47, y=73.00, z=-16.50], EntityPig['Swine'/150, l='MpServer', x=-300.50, y=65.00, z=-13.50], EntitySheep['Lamb'/151, l='MpServer', x=-301.50, y=73.00, z=-9.47], EntitySheep['Lamb'/152, l='MpServer', x=-302.91, y=65.00, z=-12.09], EntitySheep['Lamb'/153, l='MpServer', x=-301.50, y=73.00, z=-10.53], EntityZombie['Zombie'/154, l='MpServer', x=-302.28, y=28.00, z=17.75], EntitySquid['Squid'/155, l='MpServer', x=-295.99, y=58.03, z=65.96], EntitySquid['Squid'/156, l='MpServer', x=-293.58, y=56.35, z=72.33], EntitySquid['Squid'/157, l='MpServer', x=-293.53, y=57.24, z=71.24], EntitySquid['Squid'/158, l='MpServer', x=-291.55, y=56.91, z=75.91], EntitySquid['Squid'/159, l='MpServer', x=-294.16, y=56.71, z=76.79], EntitySquid['Squid'/160, l='MpServer', x=-290.57, y=53.00, z=69.14], EntitySquid['Squid'/161, l='MpServer', x=-294.12, y=59.22, z=70.47], EntitySquid['Squid'/164, l='MpServer', x=-300.38, y=57.37, z=80.14], EntityPig['Swine'/178, l='MpServer', x=-279.50, y=64.00, z=-58.72], EntityPig['Swine'/179, l='MpServer', x=-285.13, y=64.00, z=-55.72], EntityBat['Bat'/180, l='MpServer', x=-281.36, y=18.93, z=51.51], EntityZombie['Zombie'/181, l='MpServer', x=-286.50, y=46.00, z=44.50], EntityZombie['Zombie'/182, l='MpServer', x=-283.91, y=46.00, z=44.63], EntityZombie['Zombie'/183, l='MpServer', x=-281.50, y=46.00, z=43.50], EntityBat['Bat'/184, l='MpServer', x=-276.90, y=46.94, z=43.31], EntitySquid['Squid'/185, l='MpServer', x=-287.57, y=57.07, z=74.92], EntitySkeleton['Skeletman'/197, l='MpServer', x=-262.34, y=24.00, z=47.50], EntityBat['Bat'/198, l='MpServer', x=-260.53, y=26.41, z=52.72], EntityCreeper['Creeper'/199, l='MpServer', x=-268.69, y=40.00, z=43.31], EntityCreeper['Creeper'/200, l='MpServer', x=-270.50, y=40.00, z=44.50], EntityCreeper['Creeper'/201, l='MpServer', x=-267.25, y=40.00, z=48.03], EntityItem['item.item.sulphur'/457, l='MpServer', x=-190.75, y=41.16, z=70.80], EntitySkeleton['Skeletman'/202, l='MpServer', x=-268.50, y=40.00, z=42.44], EntityItem['item.item.sulphur'/458, l='MpServer', x=-190.86, y=41.26, z=70.83], EntityPig['Swine'/203, l='MpServer', x=-266.93, y=64.00, z=41.50], EntityPig['Swine'/204, l='MpServer', x=-265.09, y=64.00, z=41.50], EntityPig['Swine'/205, l='MpServer', x=-266.50, y=73.00, z=44.50], EntityPig['Swine'/206, l='MpServer', x=-270.28, y=69.00, z=47.56], EntitySkeleton['Skeletman'/207, l='MpServer', x=-265.50, y=24.00, z=49.50], EntitySkeleton['Skeletman'/208, l='MpServer', x=-257.31, y=24.00, z=51.47], EntitySkeleton['Skeletman'/209, l='MpServer', x=-259.88, y=24.00, z=52.00], EntitySkeleton['Skeletman'/210, l='MpServer', x=-263.75, y=24.00, z=48.50], EntityZombie['Zombie'/218, l='MpServer', x=-248.46, y=20.00, z=-33.34], EntityCreeper['Creeper'/219, l='MpServer', x=-241.50, y=48.00, z=45.50], EntitySkeleton['Skeletman'/220, l='MpServer', x=-243.44, y=48.00, z=45.06], EntityBat['Bat'/221, l='MpServer', x=-234.50, y=34.29, z=64.50], EntitySkeleton['Skeletman'/222, l='MpServer', x=-240.50, y=32.00, z=63.50], EntityBat['Bat'/224, l='MpServer', x=-242.14, y=14.51, z=95.03], EntityBat['Bat'/229, l='MpServer', x=-220.24, y=20.42, z=-55.00], EntityBat['Bat'/230, l='MpServer', x=-226.24, y=38.29, z=-12.13], EntitySkeleton['Skeletman'/231, l='MpServer', x=-227.50, y=25.00, z=30.50], EntitySkeleton['Skeletman'/232, l='MpServer', x=-228.50, y=24.00, z=37.50], EntitySkeleton['Skeletman'/233, l='MpServer', x=-225.47, y=25.00, z=38.00], EntitySkeleton['Skeletman'/234, l='MpServer', x=-226.50, y=28.00, z=46.50], EntityZombie['Zombie'/235, l='MpServer', x=-227.66, y=44.00, z=45.94], EntitySkeleton['Skeletman'/236, l='MpServer', x=-226.91, y=49.00, z=38.50], EntitySkeleton['Skeletman'/237, l='MpServer', x=-237.69, y=28.00, z=55.47], EntityZombie['Zombie'/238, l='MpServer', x=-227.50, y=41.00, z=51.50], EntityCreeper['Creeper'/239, l='MpServer', x=-223.48, y=37.13, z=51.51]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 608117256 bytes (579 MB) / 1254866944 bytes (1196 MB) up to 2040135680 bytes (1945 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.85.1286 Minecraft Forge 10.13.2.1286 10 mods loaded, 10 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1286} [Forge Mod Loader] (forge-1.7.10-10.13.2.1286.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1286} [Minecraft Forge] (forge-1.7.10-10.13.2.1286.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CustomMainMenu{1.9.2} [Custom Main Menu] (CustomMainMenu-MC1.7.10-1.9.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mekanism{9.0.1} [Mekanism] (Mekanism-1.7.10-9.0.1.270.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MekanismGenerators{9.0.1} [MekanismGenerators] (MekanismGenerators-1.7.10-9.0.1.270.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MekanismTools{9.0.1} [MekanismTools] (MekanismTools-1.7.10-9.0.1.270 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Launched Version: 1.7.10-Forge10.13.2.1286
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4276, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Official Pack]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by unpairedbracket** [comment]
Looks to me like you're going to need to update Forge (your current build is 272 builds behind the recommended 1.7.10 one) due to fluid changes
