### ISSUE TITLE
Upgrade v8 to v9 side config issue

### ISSUE THREAD

**Issue by jznomoney** [aidancbrady/Mekanism#3244]
When upgrading from v8 to v9 all my side config states are messed up and I have to reconfigure all of my machines.  Is there a way to retain this information?  I did a backup of my world so I can revert back to v8 but I have a lot of mekanism machines and it would be easier if there was a fix to keep the side config information retained during the upgrade.

**Comment by aidancbrady** [comment]
Yeah, this is sadly one of the necessary changes required to make the factory transition work better. I promise you I won't change the configuration data again :)
