### ISSUE TITLE
[Cross-mod] MPS omniwrench is crashing after Mek9 update

### ISSUE THREAD

**Issue by EzerArch** [aidancbrady/Mekanism#3246]
That's a weird issue. I don't know on which end the problem lays.

Since I updated to Mek9, MachineMuse's Modular PowerSuits omniwrench started to crash with Unexpected error/NoClassDefFoundError: cofh/lib/util/helpers/ServerHelper.

This is me using MPS omniwrench with Mek8 r267, prior to update:
![mps](https://cloud.githubusercontent.com/assets/6743303/15451107/e5c0cce2-1f89-11e6-8059-80ddeaaf335a.gif)

Once updating to Mek9:

![mpscrash](https://cloud.githubusercontent.com/assets/6743303/15451172/79af11c4-1f8b-11e6-8382-2b0d2d70246b.gif)

Tested both cases, in  Mek8 and Mek9, twice, to be sure.

Probably it's not Mekanism's fault, once the error log says nothing about it. The Mek9 update might have exposed a left-over dependency in the MPS mod, which wasn't supposed to be there.

Already reported, with error log: https://github.com/MachineMuse/MachineMusePowersuits/issues/720

**Comment by aidancbrady** [comment]
Yeah, this is not on my end- all I can think is that Mekanism v9 now ships with the latest RF API. Let me know if I can help with anything else!
