### ISSUE TITLE
Mek8 dynamic tanks user interaction crash and rendering

### ISSUE THREAD

**Issue by EzerArch** [aidancbrady/Mekanism#3248]
This is rather a warning than a bug report.

Using my Galacticraft Rocket Fuel dynamic tank as example.

![2016-05-22_00 03 18](https://cloud.githubusercontent.com/assets/6743303/15451906/e35f87d2-1fb0-11e6-91c3-0bf4be210a78.png)

**1. Structural Glass crash.** If I right-click the frame, that is, the dynamic tank blocks, it will show up the Dynamic Tank user interface on screen. OK. But if I right-click the structural Glass in the middle, my world is shut down with "Connection Lost". This also happens with vanilla fluids, such as water. It doesn't crash if the dynamic tank is empty.

Log: https://gist.github.com/EzerArch/93f628c3d9bbba21c4da8a37dc26c77a

**2. Structural Glass does not always render custom fluids.** If you compare my rocket fuel tank in this video (https://youtu.be/7p2fuMK4QGo?t=2m20s) with the one in the image, you notice it is not rendering the "yellow" fluid in it.

So, it's advisable to tear down old dynamic tanks and rebuild them. I had both problems about; rebuilding fixed it all good. :)

**Comment by aidancbrady** [comment]
Huh, interesting.  The issue does not occur at all after you rebuild the structure?

**Comment by EzerArch** [comment]
> The issue does not occur at all after you rebuild the structure?

No.
