### ISSUE TITLE
Mekanism v9 Induction Matrix Bug

### ISSUE THREAD

**Issue by MineWitherMC** [aidancbrady/Mekanism#3250]
![2016-05-22_12 49 31](https://cloud.githubusercontent.com/assets/18210824/15453361/825c3866-201b-11e6-85fe-eaeeb66bcc50.png)

**Comment by aidancbrady** [comment]
Assuming the issue in question is the waila display, this has already been reported and is sadly unavoidable as a result of the way I handle large scale energy.
