### ISSUE TITLE
[Thermal Expansion 4.1.2-240 & Mekanism-1.7.10-9.0.1.270] Tesseract connection issue

### ISSUE THREAD

**Issue by HadesDurin** [aidancbrady/Mekanism#3252]
When i use an universal elite cable to pump rf into a tesseract, no energy gets delivered to the destination tesseract.
If i change the last cable with an Thermal Expansion Energyduct all works fine as expected.
here is a picture:
http://imgur.com/NrDFxyU

**Comment by aidancbrady** [comment]
A TE interaction issue has already been posted, rest assured that I'll take a look as soon as I can :)
