### ISSUE TITLE
crash after updating to Mekanism-1.7.10-9.0.1.270

### ISSUE THREAD

**Issue by jaap81** [aidancbrady/Mekanism#3253]
Same issue as in #3162. Doesn't seem to be solved in v9 :(

[crash-2016-05-22_15.32.03-server.txt](https://github.com/aidancbrady/Mekanism/files/276333/crash-2016-05-22_15.32.03-server.txt)

**Comment by aidancbrady** [comment]
Already reported. I'll take a look later today
