### ISSUE TITLE
[Suggestion]--Silos

### ISSUE THREAD

**Issue by gp009** [aidancbrady/Mekanism#3254]
I think Silos would be a good multi-block structure to add for Mass storage of a single item OR perhaps even Mass storage of multiple items.

Even though we already got tiered Bins now that can hold alot already, the Silo would take it a step further.

Just an idea i'd thought i'd pass along.

**Comment by aidancbrady** [comment]
Thanks for the suggestion! I'm happy with tiered bins for now, but massive scale storage is something I want to do in the future- I'll keep this in mind :)
