### ISSUE TITLE
Crash w/ IC2 classic 

### ISSUE THREAD

**Issue by FnordMan** [aidancbrady/Mekanism#3255]
(not the immibis IC2 classic)
How to reproduce the problem: Set up a laser array for a fusion reactor w/ laser amplifiers and ultimate cable. Add creative energy cube to cause crash. 
edit: doesn't crash with Thermal expansion's creative energy cell or with an ultimate energy cube in the same place. 

Crash report:
[crash-2016-05-22_11.05.24-server.txt](https://github.com/aidancbrady/Mekanism/files/276410/crash-2016-05-22_11.05.24-server.txt)

**Comment by aidancbrady** [comment]
Should be fixed, I was apparently emitting a value too high to be supported by other energy networks.
