### ISSUE TITLE
SFM Crash with PRC 9.0.1.270

### ISSUE THREAD

**Issue by tgstyle** [aidancbrady/Mekanism#3257]
Trying to create an input in SFM (w StevesAddons), this happens when trying to clear the search field from .all. I cannot for the life of me get it to duplicate on another server. It only happens on one server that has an extensive SFM setup.

https://gist.github.com/tgstyle/9594d4354d53afbd995eb3a6ce43f8fb

**Comment by aidancbrady** [comment]
This may be related to a v8 -> v9 transition error; some side configurations of machines changed, and that could result in the ArrayIndexOutOfBoundsException displayed.  Try breaking and replacing the PRCs in your world.
