### ISSUE TITLE
Advanced and Elite Factories do not accept Muffling Upgrades

### ISSUE THREAD

**Issue by MRuth** [aidancbrady/Mekanism#3259]
It seems that the Advanced and Elite variants of factories do not accept Muffling Upgrades as of Mekanism v9.0.1.270.  Here are some attached photos.

![2016-05-23_10 23 19](https://cloud.githubusercontent.com/assets/3927478/15475638/ac2312d6-20d0-11e6-97cd-65558d23bfb3.png)
![2016-05-23_10 23 14](https://cloud.githubusercontent.com/assets/3927478/15475637/ac1c131e-20d0-11e6-876e-93b72ea6cf94.png)
![2016-05-23_10 23 07](https://cloud.githubusercontent.com/assets/3927478/15475639/ac3c1cd6-20d0-11e6-8ae5-a1b3b7a74ad5.png)

**Comment by aidancbrady** [comment]
Fixed in development, thanks!
