### ISSUE TITLE
Having more than 163(~2.13GRF) Ultimate Inductive Providers, TE Cryo-Stabilised Ducts fail completely

### ISSUE THREAD

**Issue by SteelShot** [aidancbrady/Mekanism#3260]
I think this relates to the EnergyCell bug, too much energy is being pushed in(more than 2.147B)
It should just output the MAX value that conduit can take and just ingore the actual MAX output.

Maybe in the future we will see a Mekanism Super Conductor that maybe would have a larger flow rate or is that tied down to minecraft to use integers rather than longs?

![2016-05-23_18 25 46](https://cloud.githubusercontent.com/assets/5291010/15478733/f5030d10-2113-11e6-8a3f-1106f0ee3218.png)
![2016-05-23_18 26 10](https://cloud.githubusercontent.com/assets/5291010/15478735/f6f37498-2113-11e6-82bf-8087cf1d1b3e.png)

**Comment by aidancbrady** [comment]
Fixed in development; energy transfer to other networks now caps out at Integer.MAX_VALUE to prevent bad interaction.  I'll consider superconductors for the future :)
