### ISSUE TITLE
Quantum Entangleporters loose frequency connection on game exit/restart

### ISSUE THREAD

**Issue by MRuth** [aidancbrady/Mekanism#3261]
It seems that the Quantum Entangleporters will loose the bound frequency when the game exits and restarts.  I have two entangleporters set up on the same frequency (Oxygen) for transmitting oxygen from the electrolytic separators to 3 elite purifying factories.  Each time the game is restarted, the a new frequency has to be made and both entangleporters must be set to the new channel.

![2016-05-23_13 14 16](https://cloud.githubusercontent.com/assets/3927478/15480139/7e8cc678-20e9-11e6-80c7-322e6295af52.png)
![2016-05-23_13 14 26](https://cloud.githubusercontent.com/assets/3927478/15480138/7e8c736c-20e9-11e6-82bb-0d635fa9677d.png)
![2016-05-23_13 14 46](https://cloud.githubusercontent.com/assets/3927478/15480136/7e8b068a-20e9-11e6-9509-ac8209e79b3d.png)
![2016-05-23_13 14 50](https://cloud.githubusercontent.com/assets/3927478/15480140/7e8d9760-20e9-11e6-88f3-cbf740ecc8a6.png)
![2016-05-23_13 22 31](https://cloud.githubusercontent.com/assets/3927478/15480137/7e8c5a76-20e9-11e6-8cca-92f025841953.png)

**Comment by aidancbrady** [comment]
I'm unable to reproduce this; Quantum Entangloporters are remembering their frequencies on world reload and chunk reload.  There may be some kind of erroring block in the chunk of the Entangloporters that is preventing them from saving their state; I assure you that if you test a new world, however, this will not happen.

**Comment by MRuth** [comment]
This seems to happen when the entangleporters are used in separate dimensions.  I used the Overworld and the Nether for testing on a brand new world.  The areas containing the setup in each dimension was chunk loaded and worked both directions while in game and teleporting across dimensions, however on world exit and reload, they loose connection.

**Comment by aidancbrady** [comment]
Hmm.I'll look into it tomorrow

**Comment by aidancbrady** [comment]
Merging with latest report.
