### ISSUE TITLE
Fail to create a new world: state engine was in incorrect state ERRORED and forced into state AVAILABLE

### ISSUE THREAD

**Issue by SmokeyTheBandicoot** [aidancbrady/Mekanism#3262]
Any time I try to create a new world I got redirected to the main menu (no crash). This is the log: http://pastebin.com/wPsKWrmy

MC 1.7.10, Forge .1614, Mek v9 (core+gen+tools) v9.0.1.270

Full forge log attached.

[fml-client-latest.txt](https://github.com/aidancbrady/Mekanism/files/278044/fml-client-latest.txt)

**Comment by aidancbrady** [comment]
This is due to a mod providing an invalid recipe to the Mekanism recipe list, I'm afraid there's not much I can do :/

**Comment by SmokeyTheBandicoot** [comment]
Sorry to bother you, but could it be a Minetweaked recipe? Why would it prevent world from loading?

**Comment by HadesDurin** [comment]
my guess is that you get a recipe for an item that is no longer aviable
but you have to search and detect that on your own or with help from the minetweaker programmer

**Comment by SmokeyTheBandicoot** [comment]
I am the Minetweaker programmer, and I was sure I disabled all Mek-related recipes, because I removed Mek from my modpack and MT didn't throw any error. Now I added both Mek v9 and v8, and it failed loading. Thank you for your help, I'll double-check my scripts.
