### ISSUE TITLE
V9 -- Valve does not output steam

### ISSUE THREAD

**Issue by addrever** [aidancbrady/Mekanism#3263]
When I put a boiler valve at the same level as a pressure disperser the steam does not come out.  If it's one block above it does.  I am under the impression that it should be able to be at the same level as the valve for the water works the same way.

I attached two screenshots to show you it working and not working.
![2016-05-23_15 10 55](https://cloud.githubusercontent.com/assets/190461/15481492/b5572360-20f8-11e6-8867-ce3d0ef3c79b.png)
![2016-05-23_15 11 18](https://cloud.githubusercontent.com/assets/190461/15481493/b564dcd0-20f8-11e6-9b5b-69b9e7d2965e.png)

**Comment by aidancbrady** [comment]
Fixed- water now must be accessed below the pressure dispersers, and gas can be accessed at the level of the dispersers or above
