### ISSUE TITLE
Mekanism v9 reactor

### ISSUE THREAD

**Issue by jznomoney** [aidancbrady/Mekanism#3264]
When restarting my server all my reactors shut off and I have to restart them all.

**Comment by SteelShot** [comment]
Never had that issue iam running V9 fine, more info? Mods, logs?

**Comment by aidancbrady** [comment]
I'm not reproducing this either; server restart and chunk reload is working fine.  It may be some kind of transition issue, I'd suggest breaking and replacing the reactor structure.
