### ISSUE TITLE
Problem with steam

### ISSUE THREAD

**Issue by RedGuy54** [aidancbrady/Mekanism#3265]
I don't know if this is a problem with other liquids, but I have a dynamic tank filled completely with steam, and an ultimate mechanical pipe taking it to a turbine. For some reason, the steam doesn't pour out like it should, if I look inside the turbine and I mouse over the input rate, it flashes between 6400 and 0. Also, if I look at the pipe, it flashes with the steam texture too. Also, it still does this if I hook it up directly to a reactor or boiler.

**Comment by MineWitherMC** [comment]
Is UMP set to pull mode?

**Comment by RedGuy54** [comment]
I have it pulling from the tank and pushing in the turbine.

**Comment by RedGuy54** [comment]
Ok well overall I'm having problems with Steam. Now like the turbine just fills up, but the input bar is at 0 the entire time.

**Comment by aidancbrady** [comment]
I can't reproduce, it's likely just a client sync issue. If it keeps occurring I'll take another look.

**Comment by RedGuy54** [comment]
Ok I think I figured it out, I'm using KCauldron on my server and it worked fine after I disabled it. I guess I'll have to get rid of it :(
