### ISSUE TITLE
[Suggestion] Heat from gas and liquid fuels

### ISSUE THREAD

**Issue by TheGuyFromTheInternet** [aidancbrady/Mekanism#3266]
Generating steam from charcoal is nice and all but I would like to be able to use ethylene and/or lava to produce steam as a mid-game power source. It would be nice if it could also use gas and liquid fuels from other mods.

**Comment by aidancbrady** [comment]
This is planned, actually :)

**Comment by TheGuyFromTheInternet** [comment]
Yey! :D
