### ISSUE TITLE
[Feature Suggestion] Upgradeable Ordictionificator

### ISSUE THREAD

**Issue by condensedapple** [aidancbrady/Mekanism#3268]
It would be awesome if you could provide an upgrade the Ordictionificator so it is faster. Possible solutions:

- entire stacks per tick
- multiple operations per tick,
- "factory upgrades" for the Ordictionificator so it can process up to 7 stacks at once).

Background: The Ordictionficator is currentely the bottleneck in my ore-processing factory, and even applying a tick-speedup-machine (imaginary time unit from QuantumFlux) did not help.

**Comment by SteelShot** [comment]
http://minecraft.curseforge.com/projects/oredictionaryconverter try this mod
Also a great idea.

**Comment by condensedapple** [comment]
Thanks a lot, I will check this out.

**Comment by aidancbrady** [comment]
I'll leave this kind of sped-up functionality up to the other mod. Oredictionificators process 20 items per second, which I believe is an adequate speed; if you need more, you can always place more.

**Comment by condensedapple** [comment]
Ok, I understand this, as my request has only very few applications.
