### ISSUE TITLE
Power Connection Issues Version 9

### ISSUE THREAD

**Issue by sphynx1492** [aidancbrady/Mekanism#3269]
There were no entries in the log, but we loaded v9 up on our server and logged into the world to find that most of our power connections were offline.  We use an extensive amount of tesseracts and p2p tunnels for power.  The cable would connect, even if we disconnected it and reconnected, but power will not traverse the connection.  We can see power going into both the tesseract and the p2p tunnel, but no power out the other side.  I had to revert back to v8.

**Comment by SteelShot** [comment]
To my knowledge this is fixed Development branch, You can download the repository and build it yourself until aidan drops a release :)
