### ISSUE TITLE
[Machine Suggestion]Drainage Pump

### ISSUE THREAD

**Issue by CJL48** [aidancbrady/Mekanism#3272]
The electric pump is great for getting water, but sometimes you want to get rid of a fluid...or at least get it out of the way of your building plans. I suggest a variant on the electric pump, designed specifically for draining pools of fluid.
This pump would:

- Work with all fluids capable of being piped (I don't know if the electric pump does this already, but it does seem to mostly be about acting as a water source).
- Extend a pipe downwards to collect fluids not immediately below it (I'm pretty sure that the electric pump does not do this already).
- Block fluids such as water from forming new source blocks temporarily (this is the big one, along with the point above, that separates this pump from the one already implemented- this pump is specifically for removing fluids from the world).

This could be implemented as an upgrade to the existing pump, but I feel that it would work best as it's own machine. Where the existing pump mostly collects water for use, this pump would be more like the digital miner(1): it's purpose is as much to remove fluids as to collect them (though it can be used to collect fluids such as oil and lava).
(1)Though much simpler- it would only remove fluids from the world. Filtering and height specification optional, though it should not teleport fluids.

**Comment by TheGuyFromTheInternet** [comment]
Just tried using the pump fully upgraded, it doesn't work. Water regenerates faster than the pump could pump out. I guess this may have some use.

**Comment by CJL48** [comment]
Keep in mind that the current pump no longer removes the source block in v9.

**Comment by XFactHD** [comment]
This new pump would only be needed for water. If you place one or more pumps on a nether lava pool, you can empty it out pretty quickly (much quicker than with a BC pump).

**Comment by TheGuyFromTheInternet** [comment]
CJL48,
it is configurable if the pump removes the water source block or not. I configured it to remove the water block but no dice.

**Comment by CJL48** [comment]
Okay, so the currently implemented pumps can pick up fluids other than water, and reach down to pick up fluids? I didn't realize that, makes this unnecessary.
