### ISSUE TITLE
[Bug] Transporting Deep Resonance Liquid Crystal with Mechanical Pipes.

### ISSUE THREAD

**Issue by sm31415** [aidancbrady/Mekanism#3274]
When Deep resonance liquid crystal is created, it has various percentage attributes, that start out at 100, 10 ,10 and 10.

After a trip through some mechanical pipes from one deep resonance tank to another, all the attributes are zeroed out and the liquid is thus broken and useless.

I presume something about the pipes are dropping the extra attributes.

I am on a custom pack, with 

Mekanism-1.7.10-9.0.1.270 download
and
deepresonance-1.1.4

**Comment by Deathlymad** [comment]
did you try any other transfer methods?

**Comment by sm31415** [comment]
I successfully moved the fluid with enderio conduits.

It didn't occur to me to try other fluid transfer systems.

**Comment by Deathlymad** [comment]
were all mechnical pipes loaded while the fluid was transversing through it?
Are you playing multiplayer or singleplayer?

**Comment by laz2727** [comment]
I don't think it's supposed to be possible to move them with most pipes.
Forge doesn't support fluids with data attached.

**Comment by Deathlymad** [comment]
appearently it does i checked the deepResonance and Forge Code and FluidStacks have NBT attached to them.

**Comment by laz2727** [comment]
Oh, okay. It didn't in 1.6.4.

**Comment by Deathlymad** [comment]
I scanned the Mekanism Code and as it turns out there are many calls like that:
**new FluidStack( fluid.getFluid(), amt)**
**amt** is an Integer and **fluid** the previous fluidStack.
that copy construction is deleting the Tag.
fix for that is simple just remove the "_.getFluid()_" to call the proper copy constructor Fluid Stacks :)

**Comment by aidancbrady** [comment]
Fixed, thanks!
