### ISSUE TITLE
Crash on small logistical transporter network

### ISSUE THREAD

**Issue by Alleluid** [aidancbrady/Mekanism#3275]
Using v9 I have a small network of several coal heaters, a logi transporter facing a TE Creative Strongbox with charcoal in it, no filters, and another empty one facing the network, behind it is a personal chest, and it is filtered with an oreDict entry of "ore*"

http://pastebin.com/pCk8hH1A

**Comment by Alleluid** [comment]
Oh, and it's stock FTB Infinity Evolved with Mek added.

**Comment by aidancbrady** [comment]
Already reported. I'll try and get to this tomorrow if I have time
