### ISSUE TITLE
Gas Mask stops emitting sound if it rains

### ISSUE THREAD

**Issue by EzerArch** [aidancbrady/Mekanism#3276]
MC sound engine to blame?

I noticed that the Gas Mask stops emitting sound, namely [GasMask.ogg](https://github.com/aidancbrady/Mekanism/blob/master/src/main/resources/assets/mekanism/sounds/GasMask.ogg), if it starts raining.

It seems the game fails to loop the GasMask.ogg playback once the rain sound takes place in the ambient. Once the rain is gone or out of reach (that is if I'm in a cave or very bottom of the ocean), all I have to do is reload the world. GasMask sound is back playing safe and sound... eh?

I removed all resource packs. The bug still sticks.

**Comment by aidancbrady** [comment]
Likely the stupid MC sound system with all its problems. I'm getting more and more tempted to restore my old sound system that I had back in 1.6.4, I had it working with absolutely no problems and everyone loved it. Maybe for 1.9...

**Comment by R1ZL4** [comment]
This also applies to machines for me, specifically the factories. I've also noticed it on the jetpack.

**Comment by aidancbrady** [comment]
Merging with #2741 for now
