### ISSUE TITLE
[Suggestion] Potential heat-system imbalance and fuelwood heater buff

### ISSUE THREAD

**Issue by TacoMage** [aidancbrady/Mekanism#3277]
Currently a heat generator with lava on 5 sides produces ~40% more heat than a single fuelwood heater.  I'm not sure if this is intended, but it seemed somewhat odd given the comparative difficulty of keeping a fuelwood heater fed vs dumping lava on a heat generator. 

That actually leads to my suggestion: In general the fuelwood heaters feel underpowered compared to similar fuel-burning options in other mods, especially given the great difference in total setup costs when using fuelwood heaters to produce power via steam boilers and turbines.

For comparison:  A single piece of coal burned in a fuelwood heater attached to a boiler produces 10mb/t of steam for 1/2 the fuel burn-time.  This steam pumped into a turbine produces roughly 125Rf/t, for a total coal energy production of around 100,000 RF/coal. (This was the best setup I could manage, maybe I'm doing something wrong?)

While this is about 25% more efficient than a survivalist generator, this comes in at 20% less efficient than a fully-upgraded EnderIO furnace generator, and is 60% less efficient than an optimally tuned MFR steam boiler.   Yet the Mekanism boiler comes at a far higher startup cost due to having to build both a boiler and a turbine in order to realize the energy production.  And, within Mekanism, the lower associated startup costs and ease of implementation of wind turbines will have most people skipping over fuelwood heaters entirely.

My suggestion is to consider beefing up the steam production from the fuelwood heaters to bring their energy production more in-line with the associated startup cost of building both a boiler and turbine.  I would also suggest considering the removal of the lava bucket as a fuel source. I've historically been able to abuse lava rather outrageously in other mods to create very gainful perpetual motion.

**Comment by aidancbrady** [comment]
Just a heads-up, there's a config value labeled "HeatPerFuelTick" which allows you to define how much that is generated per "tick" of fuel burned in a Fuelwood Generator.  Its default value is 1, but I've bumped to 4 in order to make the Fuelwood/Boiler system a bit more appealing.  Thanks for pointing this out :)

**Comment by mimikal** [comment]
Yep, what I always did was set heat generator passive generation to 0, but
now it's a different problem.
