### ISSUE TITLE
[Bug] Electric Pump consumes water source blocks when the Filter Upgrade is installed

### ISSUE THREAD

**Issue by CaptainKorhonen** [aidancbrady/Mekanism#3279]
Using Mekanism 9.0.1.270. When the Filter Upgrade is installed and the Electric Pump produces Heavy Water, it consumes water source blocks even though it shouldn't.  It works fine without the upgrade.

Just to be sure, I checked the Mekanism.cfg file and the "B: PumpWaterSources" variable is set to "false" so it should work but doesn't.

**Comment by FnordMan** [comment]
Already been mentioned, fixed and closed, see #3243

**Comment by CaptainKorhonen** [comment]
I don't get it. If it's been fixed why is it still happening? Or is it supposed to do that? The issue you linked didn't answer my question.

**Comment by FnordMan** [comment]
Yes it did.. it's fixed, that doesn't mean an immediate release. Note the date on the issue, note how the last version was made on the 21st...

**Comment by CaptainKorhonen** [comment]
Ah, now I understand. Thanks. Will wait for the next update then.
