### ISSUE TITLE
Crash when rendering an industrial turbine

### ISSUE THREAD

**Issue by jznomoney** [aidancbrady/Mekanism#3280]
I have the log here http://pastebin.com/5J8rjuAY
I started my server today and I cannot seem to get to the one turbine I built.  I was the largest sized turbine I could build and it was full to the max with steam and stored power.  When I move towards it now I get that crash and can no longer join my game.  The server doesn't crash just the client.

**Comment by jznomoney** [comment]
I tried removing fastcraft and optifine and it still crashes.

**Comment by aidancbrady** [comment]
Added a null check, thanks!
