### ISSUE TITLE
ComputerCraft/OpenComputers-Integration for Thermal Evaporation Towers does not work

### ISSUE THREAD

**Issue by condensedapple** [aidancbrady/Mekanism#3281]
All methods return "Unformed.", even though they are clearly formed. The integration works with the Fusion Reactor.

**Comment by aidancbrady** [comment]
You're sure that both OpenComputers and ComputerCraft integration don't work, or just one of the two?

**Comment by condensedapple** [comment]
Yes, both do not work. (I am using the 1.6 beta of OpenComputers, dont know whether this has an impact)

**Comment by aidancbrady** [comment]
Is the Thermal Evaporation Plant formed, or is it unformed?  Support technically will only work with a structured plant.

**Comment by condensedapple** [comment]
The plant is formed, of course ;)

**Comment by condensedapple** [comment]
CC recognizes the TEController as a peripheral, and OC lists it as a compontent (using an adapter block)

**Comment by condensedapple** [comment]
Digging in your code, the implementation of `IComputerIntegration` in `TileEntityEvaporationBlock` is almost identical compared to the fusion reactor. Therefore, as the computers return "Umformed.", the `getController()`-method may be the issue. What happens if you implement `IComputerIntegration` only in `TileEntityEvaporationController`, as in this case, you don't have to call `getController()`?

**Comment by condensedapple** [comment]
Funny update: The integration works fine with every block **EXCEPT** the Thermal Evaporation Controller, which is quite funny.

**Comment by condensedapple** [comment]
possible workaround for [TileEntityThermalEvaporationBlock](https://github.com/aidancbrady/Mekanism/blob/development/src/main/java/mekanism/common/tile/TileEntityThermalEvaporationBlock.java#L168), which also might be a tiny bit more performant xD
```
public Object[] invoke(int method, Object[] args) throws Exception 
{
	//add check
	TileEntityThermalEvaporationController controller = this instanceof TileEntityThermalEvaporationController ? this : getController();
	
	if(controller == null)
	{
		return new Object[] {"Unformed."};
	}
	
	switch(method)
	{
		case 0:
			return new Object[] {controller.temperature};
		case 1:
			return new Object[] {controller.height};
		case 2:
			return new Object[] {controller.structured};
		case 3:
			return new Object[] {controller.inputTank.getFluidAmount()};
		case 4:
			return new Object[] {controller.outputTank.getFluidAmount()};
		default:
			throw new NoSuchMethodException();
	}
}
```

**Comment by condensedapple** [comment]
anything new?

**Comment by MJRLegends** [comment]
Yeah i can confirm it works on normal blocks but haven't tried on the controller

**Comment by aidancbrady** [comment]
Fixed!

**Comment by condensedapple** [comment]
Nice! If it is not too hard to explain, what was the issue?

**Comment by condensedapple** [comment]
Nvm, just saw it in the commits of the development branch.
