### ISSUE TITLE
Crash With Logistical Sorters and Personal Chests

### ISSUE THREAD

**Issue by Kaltazar** [aidancbrady/Mekanism#3282]
In Mekanism 9.0.1, if you attach a Logistical Sorter to a Personal Chest, and also have a Logistical Transporter attached to the sorter, the game will crash as soon as you apply a filter.  It does not seem to happen if the sorter is attached to the bottom of the chest however.  Attaching an example crash log.

https://gist.github.com/Kaltazar/6225843136773f507e00d3b2ea6109b6

**Comment by jznomoney** [comment]
I believe this was fixed on the dev branch. you either have to wait for the release branch or build the dev branch yourself.

**Comment by aidancbrady** [comment]
Yeah, fixed :)
