### ISSUE TITLE
[Suggestion] Regulaters

### ISSUE THREAD

**Issue by RedGuy54** [aidancbrady/Mekanism#3283]
There should be a block that takes in gases, liquids, and power, then regulates how much goes out.  This would be useful to control how much power is going where or how much water is going where etc. It would be like the power relay in RF Tools, but it can work with more than just power.

**Comment by CristinoValdigem** [comment]
Complementing... Another good modification on game is about thermoeletric boiler... with 5 superheating he is producting only 10mb of Steam..

![2016-05-28](https://cloud.githubusercontent.com/assets/16420781/15629508/88036166-24f0-11e6-929c-601ffbb28ed8.png)

**Comment by EzerArch** [comment]
So this would be advanced version of my suggestion #3256 [Suggestion] Valves and switches - except for the "Has only two states: on/open (green light) and off/closed (red light)" aspect.

**Comment by RedGuy54** [comment]
Basically, yes. There could actualy be two versions. A basic version could limit one pipe, it would look like what you suggested. Then an advanced version could be a complete block, and it could limit more than 1 pipe.

**Comment by aidancbrady** [comment]
I'm going to go ahead and merge this with #3256.  There's a few things that I'm planning on for the future:
- Removing redstone sensitivity in transmitters, adding in some kind of "transmitter switch" to function as @EzerArch suggested
- Colored transmitters in all types, not just item transport
- "Transmission Mediator" block to configure input and output values for all transmission types on a side-by-side basis, as this issue suggested
