### ISSUE TITLE
V9 -- Osmium not rendering properly in Storage Drawer

### ISSUE THREAD

**Issue by addrever** [aidancbrady/Mekanism#3286]
When I place osmium blocks into a compacting drawer the ingot and nugget do not show up.  If I place the ingot in all three do.

![2016-05-28_21 12 58](https://cloud.githubusercontent.com/assets/190461/15630831/4d65557c-2519-11e6-9796-5d3d983e647c.png)
![2016-05-28_21 13 29](https://cloud.githubusercontent.com/assets/190461/15630832/4d6e438a-2519-11e6-967b-5e57aa4b62d6.png)

Not sure if this is an issue with the new texture so I thought I would post anyways.

**Comment by addrever** [comment]
I should also mention that when you try and take an ingot or a nugget out it doesn't allow you to.

**Comment by aidancbrady** [comment]
Not really sure why that would be the case.  I really doubt this is on my end, though; everything is properly registered on my end with OreDictionary.  Ask the Storage Drawers team if they have any ideas, if they link it back to me, I'll take another look.

**Comment by addrever** [comment]
I noticed oredict was the same so I'm not sure either.  I've opened an issue on the SD github as well.

For reference: https://github.com/jaquadro/StorageDrawers/issues/290
