### ISSUE TITLE
[Feature Suggestion] Option to require machine maintenance?

### ISSUE THREAD

**Issue by Twilix01** [aidancbrady/Mekanism#3287]
I think it would be cool for a more hardcore difficulty to have the option in configs to enable a maintenance system, occasionally having to install replacement parts or otherwise repair machines after a while of using them. Obviously this would be off by default, but if it wouldn't be too much of a headache to work on I think it might be an interesting option to have.

**Comment by HadesDurin** [comment]
Nice idea, but to get this to work you need a maintance tab, where parts get used up (like the Railcraft Turbinerotor). My guess is, that it is way to much coding nessesary to implement it.

**Comment by RedGuy54** [comment]
Maybe just have it where machines get slower and slower over time, then you can just shift right click something on it to speed it up again.

**Comment by mimikal** [comment]
Or, how about you need to smear the machine with some sort of tar / oil
once every so often? Otherwise the machine gets slower and slower until it
stops working (like RedGuy said)?

**Comment by aidancbrady** [comment]
Maybe. Emphasis on maybe. I like complete self-sustainability, if I could find some way to manage this without breaking machine setups I'll do so. Closing for now, though- priority is in other areas right now.
