### ISSUE TITLE
[Feature Suggestion] Dump button to discard input gas in machines

### ISSUE THREAD

**Issue by trolleytrev** [aidancbrady/Mekanism#3288]
Hi there

One of the problems I'm having with my machine setup is if I have multiple chemical crystallizers is that there doesn't always end up being an even distribution between them. eg, you might have 192mb in one and 8mb in the other. Neither can produce a crystal and I can't run any new ores through the system without making a new chemical crystallizer. If a dump button akin to what the metallurgical infuser has could be added to any machine that takes gas as an input to dump an odd amount would be amaze balls!

Cheers!

**Comment by HadesDurin** [comment]
you have the gauge dropper to switch fluids/gasses around
http://wiki.aidancbrady.com/wiki/Gauge_Dropper

**Comment by aidancbrady** [comment]
Indeed, the Gauge Dropper already does everything you mentioned :)
