### ISSUE TITLE
[idea for 1.9.4 mek only]: elytra + jetpack(armored too) in 1 

### ISSUE THREAD

**Issue by mariodk** [aidancbrady/Mekanism#3289]
ofc needs to be more expensive than just combin jetpack or armored jetpack +elytra

but flying with the elytra and having a jetpack will be a awesome combo to have 

so while gliding with the elytra you can hold space to get more speed with the jetpack
but while in the air and not in Elytra gliding you can use the jetpack as normaly

and will be able to turn off elytra mode so you can fly like normal jetpack without worry about press double Space(jump) and go into Elytra gliding

and while gliding since RF/T is basically durability it needs to use RF/T while gliding
(maybe a RF/T Elytra can be a thing and combin that with a jetpack/armored jetpack)

**Comment by aidancbrady** [comment]
Discuss this in #3108 :)
