### ISSUE TITLE
[Feature Suggestion] Atomic Displacer

### ISSUE THREAD

**Issue by rihlsul** [aidancbrady/Mekanism#3290]
One tool that I keep wanting to find in a tech mod is some tool that allows you to replace blocks in place as a single operation.

Mekanism makes sense for that, given the teleporters and Atomic Disassembler.  What I'm thinking - a new tool, the Atomic Displacer, that uses the AD as a central component, plus teleportation cores.  Same normal/fast/slow/vein speeds as the AD, it allows you to right click on blocks and they are replaced with another block.  Example:  You're mining, you find a diamond ore block, but it's holding back lava.  If you use the Atomic Displacer, you can exchange-in-place the diamond ore with cobble.

How the tool gets the source blocks?  A new machine block called the Matter Dispatcher (also using Teleport Cores) that serves as the main system to receive and send blocks.  It would use the same import/output UI as other blocks, so you can easily pipe in and out the replacement blocks and the replaced blocks.  Each operation of the replacement uses the energy storage of the tool and a corresponding amount in the Matter Dispatcher.

This has a lot of use for when you're doing base building, as well as mining.  You might carve out a room, build a lot of things within it, then later, when you have more materials for fancier blocks, you can in-place change the stone blocks of the wall to White Plastic Blocks (etc).  

I think thematically it would match well, since it would combine the Atomic Disassembler logic with the Digger's replacement, and also add more teleportation functionality.  I *think* it would be relatively copy/paste code from a variety of existing parts, so hopefully not too hard to implement.

**Comment by HadesDurin** [comment]
thats a neat idea and i appreciate such a device in mekansim

**Comment by condensedapple** [comment]
this idea seams pretty similiar to EnderTech's [Exchanger](https://github.com/CarrotCodes/EnderTech/wiki/Exchanger) with range 1

**Comment by rihlsul** [comment]
Apparently.  A buddy of mine, more familiar with EnderTech let me know about that as well.  I've not used it, so news to me.  Still, would be a great feature within this mod, but if existence in others deprioritizes the notion, that would be understandable.

**Comment by AlphaKintari** [comment]
Granted EnderTech is still back on 1.7.10 and it's last commit was back in Oct 2015.  Cant seem to see any plans for updating to 1.9+

**Comment by bbgott** [comment]
An interesting idea indeed, but maybe a slight change. Instead of making a new machine to feed, maybe tie it into the new quantum entangleporter. Use the quantum entangleporter to feed the items to the atomic displacer.

**Comment by aidancbrady** [comment]
Going to merge this with the MekaSuit/MekaTools thread, where other ideas like this are being discussed.

**Comment by rihlsul** [comment]
Directly referencing the #3108 issue so it shows up there.
