### ISSUE TITLE
[1.7.10][9.0.1.270] Can't pipe Lithium into Solar Neutron Activator

### ISSUE THREAD

**Issue by Xiaminou** [aidancbrady/Mekanism#3292]
It's impossible to pipe Lithium into Solar Neutron Activators, I have tried many different gas pipes (conduits, pressurized, Extracell's gas buses, Gas Tank).
Putting a Gas Tank directly in the Solar Neutron Activator works.
![2016-05-29_16 26 07](https://cloud.githubusercontent.com/assets/8670392/15634029/b4e50fd4-25ba-11e6-83fa-7a6f308882f8.png)
![2016-05-29_16 26 08](https://cloud.githubusercontent.com/assets/8670392/15634030/b4e5fdf4-25ba-11e6-802c-0d5d386135bc.png)

**Comment by HadesDurin** [comment]
the label of the gastank is the output of it, so it has to face the destination of the gas

**Comment by Just-some-cannibal** [comment]
The input of the solar neutron activator is on the bottom

**Comment by Xiaminou** [comment]
really? Didn't look like it, oh well.
