### ISSUE TITLE
[Source build Question]

### ISSUE THREAD

**Issue by Lazarix** [aidancbrady/Mekanism#3293]
How do you get the source to build three seperate .jar files with gradle?
I only seem to be able to build MekanismAll-ver.homebaked.jar

**Comment by Lazarix** [comment]
When I try to do a gradlew fullBuild, I get the following error:

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':coreJar'.
> Could not add file 'D:\Storage\Create\Minecraft\1.9\Mekanism-1.9\etc\core\dependancies.info' to ZIP 'D:\Storage\Create\Minecraft\1.9\Mekanism-1.9\output\Mekanism-1.9.4-9.0.2.homebaked.jar'.`

`Caused by: org.gradle.api.GradleException: Could not add file 'D:\Storage\Create\Minecraft\1.9\Mekanism-1.9\etc\core\dependancies.info' to ZIP 'D:\Storage\Create\Minecraft\1.9\Mekanism-1.9\output\Mekanism-1.9.4-9.0.2.homebaked.jar'.`

```
Caused by: groovy.lang.MissingPropertyException: No such property: mcmp_version for class: SimpleTemplateScript1
        at SimpleTemplateScript1.run(SimpleTemplateScript1.groovy:1)
```

**Comment by Bunsan** [comment]
gradlew release. It will create the 4 jars (includes the Mekanism-all) in the output folder found in root folder.

**Comment by Lazarix** [comment]
Thanks!
