### ISSUE TITLE
Crash when opening GUI on Updated Dynamic Tanks

### ISSUE THREAD

**Issue by b0bst3r** [aidancbrady/Mekanism#3294]
This only happens when you click on structural glass which was upgraded from Mek8 dynamic glass, only seems to occur when you click the glass (doesn't happen if you click the frame or valves).

A crash log is not generated but the following is recorded in the Forge log - http://pastebin.com/YL6EMM9w

Mekanism-1.7.10-9.0.2.271 (was initially logged with me using 1.270)
Forge 1566

https://github.com/BevoTechPack/BevoTechPack/issues/991

Also could this be why the tank appears bugged during the update from mek8 to mek9?

**Comment by aidancbrady** [comment]
Yeah, this has been reported in the past. Breaking and replacing the structural glass should fix the issue.
