### ISSUE TITLE
Mek 8 gas tanks can't be used to make certain Mek9 machines

### ISSUE THREAD

**Issue by b0bst3r** [aidancbrady/Mekanism#3295]
Seems Mek8 gas tanks don't work in the recipes for Rotary Condensentrator, Chemical Dissolution Chamber, Chemical Washer and Chemical Crystallizer.  

Making new gas tanks in Mek9 solves the issue.

No crash log or crash occurs it simply doesn't complete/make the recipe.

https://github.com/BevoTechPack/BevoTechPack/issues/992

Mek 9.0.1.270
Forge 1566

**Comment by aidancbrady** [comment]
Emptying the gas tank before recipe use should fix this issue. It's likely a result of the removal of item damage-based gas displays in item form.
