### ISSUE TITLE
Gas Generator Config Option

### ISSUE THREAD

**Issue by RedGuy54** [aidancbrady/Mekanism#3296]
There is a config option for every generator except a gas-generator. I think the gas-generator should make way more power but I can't tweak it!

**Comment by aidancbrady** [comment]
The gas generator relies on other config values. Check out the hydrogen/ethelyne energy values, both are configurable :)

**Comment by RedGuy54** [comment]
@aidancbrady Wait I see the Ethelyne one but what is the Hydrogen one called? There's a HydrogenEnergyDensity one but it says above it controls Electrolytic separator usage.

**Comment by aidancbrady** [comment]
It does both.

**Comment by RedGuy54** [comment]
Ok I'll try it
