### ISSUE TITLE
Quantum Entangloporter Permission Denied

### ISSUE THREAD

**Issue by DarkenTheSun** [aidancbrady/Mekanism#3297]
Hello,

I've tried hard to find as much information as I can about the Quantum Entangloporters, but so far I have had no luck explaining this permission denied message we are getting.

Basically whoever sets the block down is the only one who is able to access the settings on the block, even when setting it to a public frequency.  I don't know if this was the intention, but it is very frustrating and I hope I'm just missing something very simple here.

Thanks for any help you can provide!

**Comment by aidancbrady** [comment]
That is correct, whoever places the entangloporter is defined as its owner, with absolute (and exclusive) access rights. Public frequencies allow for other players to access your frequency from their owned entangloporters.
