### ISSUE TITLE
[Feature Suggestion] Upgrade Bins in place

### ISSUE THREAD

**Issue by addrever** [aidancbrady/Mekanism#3299]
It might be a cool feature to be able to upgrade bins in place like factories and various transportation items.

**Comment by HadesDurin** [comment]
i am supporting that idea and it makes storing items and upgrading bins a lot easier

**Comment by addrever** [comment]
how about energy cubes too?:)

**Comment by aidancbrady** [comment]
I've renamed Factory Installers to Tier Installers, added an Ultimate Tier Installer, and added support for Energy Cubes, Gas Tanks, Fluid Tanks and Bins as well.  Transmitters can already be upgraded using respective alloys.  Expect changes in v9.1, enjoy :)
