### ISSUE TITLE
Mekanism Cable and TE Tesseracts

### ISSUE THREAD

**Issue by VersedXth** [aidancbrady/Mekanism#3303]
I'm using a bunch of Bio-Generator attached to Ultimate Energy Cables. These  are attached to an Tesseract from Thermal expansion. They connect right to it but no energy comes out the target Tesseract. I'd checked all configuration twice. Doesn't work :/
before I'd updated Mekanism to v9 all worked

**Comment by HadesDurin** [comment]
@VersedXth the issue is known and @aidancbrady will look as soon as he can
i have problems with tesseracts and mekanism to mentioned here: https://github.com/aidancbrady/Mekanism/issues/3252
