### ISSUE TITLE
Quantum Entangleporter: broken channel

### ISSUE THREAD

**Issue by VersedXth** [aidancbrady/Mekanism#3304]
Sometimes (very often) I'd restarted my Server all my Ultimate Energy Cables and pipes disconntects from the Quantum Entangleporter. Then the only way to fix them is to use a new Channel. I'd tried to place the cabel new, switch the inputs,replace the Porter itself nothing worked.

**Comment by TheGuyFromTheInternet** [comment]
had the same problem. I think they're working on it. Are you using the private channel and all the quantum entanglopers are in the overworld?

**Comment by VersedXth** [comment]
I'm using only public Channel and yes also on different dimensions.

**Comment by TheGuyFromTheInternet** [comment]
That's what's causing the disconnect for me sadly.

**Comment by MRuth** [comment]
Just as a heads up, if you are using any mods that adds Mekanism integration (especially with gas transport) make sure that they are all updated.  There are a few mods specifically that I have found needs to be updated and/or have their integration disabled.  See [this post](https://github.com/aidancbrady/Mekanism/issues/3273#issuecomment-222337658) for more information...

**Comment by aidancbrady** [comment]
Indeed. Integration is likely the issue.
