### ISSUE TITLE
[Suggestion] Auto eject on reactors

### ISSUE THREAD

**Issue by Just-some-cannibal** [aidancbrady/Mekanism#3305]
When I set up a fusion reactor and a turbine, I had to set up 14 ports on the reactor (10 dedicated to steam) to keep up with ultimate mechanical pipes pumping 64000 mb/t. Can you make an auto eject option for the fusion reactors?

**Comment by TheGuyFromTheInternet** [comment]
I used Pressure Pipes mod to get around this.

**Comment by laserjet25** [comment]
I agree, there needs to be a point to using water with the reactor.

**Comment by themechman** [comment]
+1 to this request

**Comment by aidancbrady** [comment]
Done :)

**Comment by themechman** [comment]
We love you! Er... in a bro way bro. Thank you

**Comment by themechman** [comment]
Which build was it corrected in?
