### ISSUE TITLE
[Suggestion] Add config option for in-world pipe/cable upgrade

### ISSUE THREAD

**Issue by ax1m** [aidancbrady/Mekanism#3307]
In my private modpack I'm developing, I have used MineTweaker to nerf all the things, one of which are Mekanism pipes and cables. What I did was change the recipes to only upgrade 2 pipes per each alloy instead of 8. As I'm currently in the process of updating all the mods in my pack, I have noticed that Mekanism 9 allows one to circumvent that tweak by using the new in-world upgrade mechanic, which will of course happily ignore my recipe changes and upgrade the default 8 cables per alloy.

I obviously don't want to ignore a major mod update like this, but I also can't have my tweaks be circumvented like this, especially since I'm using upgraded Mekanism pipes and cables as ingredients in other tweaked recipes, and this would majorly impact the balancing of my pack.

Because of this I would like to request that you add a config option for how many pipes/cables each alloy can upgrade. My other option would be to add functionality to my own mod to override this behavior, which I could probably probably pull off, but I can imagine that causing major problems in some way I am not able to foresee, so obviously I would like to avoid taking this route if at all possible.

**Comment by mariodk** [comment]
i want this too
since i make a modpack too
where there is cable tiers inbetween Mek´s cable tiers so i have to balance that in the repices but will be OP to skip so many tiers just by right click with a alloy on cable

**Comment by RedGuy54** [comment]
Yeah in general, I think there should be more config options for Mekanism.

**Comment by aidancbrady** [comment]
Done!
