### ISSUE TITLE
Infusing Factory doesn't have a dump button

### ISSUE THREAD

**Issue by KazroFox** [aidancbrady/Mekanism#3308]
The basic Metallurgic Infusers have a button to dump the infusion "buffer". Once you upgrade to the factory version, there is no way to clear this buffer. Although it is definitely possible that I missed something.

**Comment by aidancbrady** [comment]
The gauge dropper, if I'm not mistaken, is capable of removing the contents of an infusing factory's infuse storage. Report back and let me know, if not I'll add that functionality :)

**Comment by KazroFox** [comment]
Sure enough, that works! I thought it was only for gasses.

**Comment by aidancbrady** [comment]
You're right, it was. I figured it was needed though with the v9 changes. You can also use it on the metallurgic Infuser instead of the dump button.

**Comment by Timeslice42** [comment]
Can we get this put on the tool tip for the gauge dropper? Also, why doesn't the "Empty" mode of the configurator also do this?
