### ISSUE TITLE
1.8.9 branch

### ISSUE THREAD

**Issue by jeromecoder** [aidancbrady/Mekanism#3310]
Hello,
I've tried to compile 1.8.9 branch with gradle but I have already the same error.
![sans titre](https://cloud.githubusercontent.com/assets/9369532/15687818/0a075c7a-2777-11e6-8231-c144b272b6a5.png)
See the image.
Please I beg you help me to compile it. Because I'm building a modpack 1.8.9.
I don't want 1.9
Thanks !

**Comment by aidancbrady** [comment]
You're not compiling with cofh RF API. Note that I can't support 1 8.9-related issue reports if you encounter any problems.

**Comment by jeromecoder** [comment]
OK thank you for your answer.
I try it tonight. 
I'll tell you when it's done.
Thanks. :)
