### ISSUE TITLE
Universal cable problem with tesseract

### ISSUE THREAD

**Issue by elsc** [aidancbrady/Mekanism#3314]
Version: 1.7.10-9.0.2.271

Universal cable not send power if attached to tesseract directly, but it can receive power.

![image](https://cloud.githubusercontent.com/assets/3804338/15736432/4678914a-28d2-11e6-9f19-795c7cd3c166.png)

**Comment by HadesDurin** [comment]
@aidancbrady knows about this issue and maybe there will be a fix soon for it

**Comment by elsc** [comment]
Okay, thank you.

**Comment by aidancbrady** [comment]
Fixed in development!
