### ISSUE TITLE
Cannot form industrial turbines

### ISSUE THREAD

**Issue by TheGeekdu74** [aidancbrady/Mekanism#3317]
Hi, I have a huge problem with Mekanism V9. I tried all v9 versions just in case. I just can't form the turbine, I can't access to the interface, I reproduce the same turbine than in the video, I'm on a Superflat world, but it doesn't work. It's the only mod that I have, and I don't know why it doesn't work. Any solutions ?

EDIT : my configurator doesn't works too, and I can't change the mode of the Atomic Dissaembler

**Comment by HadesDurin** [comment]
can you provide some pictures of the turbine?
i am not that far into mekanism to have a turbine at the moment or in the next few weeks, but maybe you missed some kind of blocks, which are needed for the turbine

**Comment by TheGeekdu74** [comment]
Sure, there you go : 
![2016-06-02_18 06 34](https://cloud.githubusercontent.com/assets/9696697/15752099/d70f5c6a-28ec-11e6-9014-3279ff92d63b.png)
![2016-06-02_18 06 46](https://cloud.githubusercontent.com/assets/9696697/15752097/d709712e-28ec-11e6-8e50-837e838f9a97.png)
![2016-06-02_18 06 54](https://cloud.githubusercontent.com/assets/9696697/15752098/d70e3394-28ec-11e6-876a-62474eb32746.png)
![2016-06-02_18 06 26](https://cloud.githubusercontent.com/assets/9696697/15752100/d71b1d2a-28ec-11e6-9f9f-7c53b8074455.png)

**Comment by aidancbrady** [comment]
You don't have any glass above the pressure dispersers- a full cuboid still needs to be formed with glass and tank blocks.

**Comment by TheGeekdu74** [comment]
I didn't understand, the last photo looks like your video... I'm sorry, I'm french I don't understand everything...

**Comment by aidancbrady** [comment]
In the first image, it seems like you don't have glass covering the outside of your pressure dispensers and coils. It has to enclose the entire structure.

**Comment by TheGeekdu74** [comment]
Sure, but this photo was just to show the inside of the structure. Look a the 4th photo, everythign is perfect, but it doesn't form..

**Comment by aidancbrady** [comment]
In that case, which version of Mekanism are you using? I fixed an issue related to turbines not forming in other dimensions, perhaps this is related.

**Comment by TheGeekdu74** [comment]
I use thé last version of Mekanism (9.0.2). But btw, I can't switch mode with the atomic disassembler and the configurator doesn't works too.

**Comment by aidancbrady** [comment]
That's very strange, unless there's a keybind conflict there's something weird going on. Try playing on an instance with only Mekanism.

**Comment by TheGeekdu74** [comment]
But I found that the turbines are only with Mekanism Generators. I already tried to play only with Mekanism. But it doesn't works .... Maybe my problem is linked with the configurator or the atomic du disassembler ... i don't know ...

**Comment by TheGeekdu74** [comment]
Specs : TechnicLauncher, superflat world, Minecraft 1.7.10, Forge 10.13.4.1566, Java 1.8

**Comment by TheGeekdu74** [comment]
Holy mother... I'm a universal idiot, I used Turbine vent and not Pressure Dispersers around the Complex. My bad, sorry...
