### ISSUE TITLE
Quantum Entangloporters are broken in base Mekanism

### ISSUE THREAD

**Issue by KazroFox** [aidancbrady/Mekanism#3319]
I looked through the other bug reports, and I found a few references to it being related to integration, but I've loaded MInecraft with only Forge + Mekanism (base, tools and generators v9.0.2) and can reliably reproduce the bug.

Steps to reproduce:
1. Create new world with Mekanism v9.0.2
2. Place two entangloporters, set them up on a private frequency.
3. Configure left entangloporter to send items, right to receive
4. Setup a chest on the left with items to send and use logistical transporter to send them into the entangloporter. On the right, setup a logistical transporter to move the items into another inventory
5. While items are being sent through the entangloporter, restart the server or leave single player
6. Restart/rejoin. Logistical transporters will be disconnected from entangloporters and cannot be reconnected. Frequency also disappears for me in singleplayer.
7. It doesn't seem to always happen the first attempt. Let about a stack of items move through the entangloporters before restarting/disconnecting. Repeat disconnect/restart until bug occurs.

Also including some images of the setup:
![2016-06-02_15 23 26](https://cloud.githubusercontent.com/assets/6764762/15758125/227f777c-28d7-11e6-8938-6401af2ddebb.png)

![2016-06-02_15 24 12](https://cloud.githubusercontent.com/assets/6764762/15758133/2ca43404-28d7-11e6-9cfd-0bee15372490.png)

After reconnecting:
![2016-06-02_15 24 31](https://cloud.githubusercontent.com/assets/6764762/15758135/2f8e37f0-28d7-11e6-978d-9d27197bd882.png)

![2016-06-02_15 24 37](https://cloud.githubusercontent.com/assets/6764762/15758138/31f7a238-28d7-11e6-8c4e-9bfd2f55481c.png)

Mods Enabled:

```
Mods:
  Mekanism-1.7.10-9.0.2.271
  MekanismGenerators-1.7.10-9.0.2.271
  MekanismTools-1.7.10-9.0.2.271
```

**Comment by aidancbrady** [comment]
Do me a favor and check your server logs, this may be an NBT load fail

**Comment by aidancbrady** [comment]
Yup- after checking the source, this is indeed a flaw on my end. I can't fix it until I get home, but I'll release a fix as soon as I can.

**Comment by KazroFox** [comment]
Well I'm glad I'm not crazy at least!

**Comment by MRuth** [comment]
@aidancbrady Could this be related to the other Quantum Entangleporters problems with world reloading?

**Comment by aidancbrady** [comment]
It could, only if you were using the frequency to transmit items. Otherwise likely not :/

**Comment by MRuth** [comment]
So the NBT info stored is specific to the type of transfer?  This seems to have the exact issues as the few that were open before, including the ticked that I opened.  I have tried to test and see if I could narrow down the offending mod or mods possibly responsible for the breakage on world reload, and even went so far as to disable all mods except Mekanism to test and found that it worked, and then re-enabled mods in batches and retested each time until all mods have been enabled, and then on subsequent loads, the entangleporters worked normally, even with all mods loaded and active.

**Comment by aidancbrady** [comment]
Each frequency has an NBT tag that stores item, gas and fluid (and other) data on world load. The item loading functionality is broken, however, to the point where if any item is stored in the frequency data on world load it will result in the entire frequency corrupting. In other words, if your entangloporters were transferring items on world exit/reload, this could be the issue. Otherwise, it's likely related to interaction as your testing discovered.

**Comment by aidancbrady** [comment]
Fixed!

**Comment by jznomoney** [comment]
is there a way to delete old quantum frequencies from the server folder in the world folder itself?  I have 1 frequency that is broken and I can't delete it within minecraft itself.

**Comment by Wyattsb** [comment]
Is this fix currently present in any master or development builds that can be downloaded or have the changes not been pushed yet? Thanks.
