### ISSUE TITLE
Electrolytic separator not working with energy upgrades.

### ISSUE THREAD

**Issue by sm31415** [aidancbrady/Mekanism#3321]
Electrolytic separators, despite saying they are compatible with energy upgrades, don't gain full functionality from them.

You can add the normal eight and the amount of power it stores goes up, but the energy usage does not go down at all.

Using 

Mekanism-1.7.10-9.0.2.271
MekanismGenerators-1.7.10-9.0.2.271
MekanismTools-1.7.10-9.0.2.271

**Comment by HadesDurin** [comment]
it is intended that energy upgrades not work on it, to not abuse hydrogen generated power

**Comment by sm31415** [comment]
Ahhh, ok then.

I was just lamenting that it meant ore multiplication required now ridiculous sums of energy to manage with the volume of oxygen required.

Thank you.

**Comment by sm31415** [comment]
Tho, thinking about it, if people wanted to make oxygen energy efficiently, for ore purification, 

It could be made that an electrolytic separator, with energy upgrades, has the energy reduction bonus, but either makes half the default per energy upgrade of hydrogen, or no hydrogen at all?

**Comment by XFactHD** [comment]
This would not be realistic anymore because the results are not equal anymore to the H2O molecule.

**Comment by Limeicus** [comment]
Well then perhaps in increasing the energy efficiency of oxygen production means the hydrogen can no longer be efficiently captured and collected?

**Comment by Sandriell** [comment]
Could simply say that it is more energy effecient because it is using more and more of the hydrogen it produces to power itself.

**Comment by HadesDurin** [comment]
get a new block which only gewnerates oxygen capturing from the air directly. like the one from galacticraft. that way you can raise oxygen production to its limits without abusing hydrogen

**Comment by sm31415** [comment]
That would be great, or possible even something you have to pipe organic matter in, in order to generate oxygen in large quantities.
