### ISSUE TITLE
[Feature Suggestion] Shift-Clicking applying upgrades to machines

### ISSUE THREAD

**Issue by jznomoney** [aidancbrady/Mekanism#3322]
Is is possible to add shift-clicking upgrades to the machines?  I am building a massive pump station and I figured it would be easier if you were able to shift-click the upgrade modules into the machines then clicking the machine, hitting upgrade and then  dragging the upgrade into the slot.

**Comment by RedGuy54** [comment]
I agree with this, I think the current upgrade GUI/System is kind of overdone.

**Comment by aidancbrady** [comment]
Added in development
