### ISSUE TITLE
Universal Cable Issue with ProjectRed?

### ISSUE THREAD

**Issue by SteelShot** [aidancbrady/Mekanism#3326]
So i was building myself a "Smart House" using tons of redstone cables, and i've noticed that the Universal Cable straingly reacts to the ProjectRed cables. Examples:

Is this supposed to happen, because the Insucalted cables are well supposedly should not affect the U cable?

Also could there be maybe a setting, to enable/disable Universal Cable Redstone interaction, so when disabled, cables wound not disconect when powered with redstone?

![2016-06-03_21 32 32](https://cloud.githubusercontent.com/assets/5291010/15792038/bbd4f1c6-29d2-11e6-80f9-14e48f758ec5.png)

![2016-06-03_21 33 08](https://cloud.githubusercontent.com/assets/5291010/15792050/c562a562-29d2-11e6-9480-7a1e95eaeaee.png)

**Comment by aidancbrady** [comment]
Transmitters are redstone sensitive :)

**Comment by aidancbrady** [comment]
Right click a cable with a configurator to turn off sensitivity.
