### ISSUE TITLE
Texture Pack Issues

### ISSUE THREAD

**Issue by Cyclone62** [aidancbrady/Mekanism#3327]
Sorry if this isnt the right place for this, but I thought this might be the best place to get an reliable response. Im trying to run Sphax x64 on RR3 and it works with the majority of the other mods, but it dosent seem to be affecting certain machines and blocks from mekanism. Attached are pictures of what the machines look like, and a couple of shots of the texture pack folder itself

![2016-06-04_19 58 35](https://cloud.githubusercontent.com/assets/19751986/15801516/9f4692e0-2a8f-11e6-8114-8eb9173080c2.png)
![2016-06-04_19 58 30](https://cloud.githubusercontent.com/assets/19751986/15801517/9f4fc05e-2a8f-11e6-80b0-ad110b259b29.png)

https://gyazo.com/c2f68c142fbb82fe2693d8ed51d3cad5
This is the texture that should be displaying for the enrichment chamber
https://gyazo.com/feacd55ce8eb44e1ffcdd5f2ed075f9d

Many Thanks for any help

**Comment by aidancbrady** [comment]
Texture pack issues are not my fault and should be reported to the pack's owner.

**Comment by Yulife** [comment]
They just haven't updated the UV maps / models to Mek 9. It needs to be updated, probably.
