### ISSUE TITLE
[Suggestion] Excess Steam Handling

### ISSUE THREAD

**Issue by WhiteFire-Sondergaard** [aidancbrady/Mekanism#3331]
Currently when the Industrial Turbine can no longer output power for whatever reason it fills up it's energy buffer, and then fills up it's steam buffer. At this point, it stops accepting steam.

This interacts poorly with Big Reactors who, if they can't output their steam, start to overheat until flow is restored or you shut the reactor down.

I suspect this may be a common configuration before people get their Mekanism generator setup since the only other way to deal with the steam that a Big Reactor outputs is the Big Reactor turbine which tops out at 2k/mb, requiring you to build many of them if you want more power. While the Mekanism one's steam to power conversion isn't as good, the fact one turbine can handle anything that a Big Reactor can output makes it a very appealing option.

So: It would be nice if you could tell the turbine to vent excess steam when it's full so it continues to accept it.

**Comment by WhiteFire-Sondergaard** [comment]
As an alternative you could just do what the Big Reactor turbines do: discard excess power and let the turbine continue to eat steam. Maybe make it an option in the GUI for people that use Big Reactor setups.

Or a redstone "I'm full" output so we could shut down the reactor auto-magically perhaps.

**Comment by aidancbrady** [comment]
I like the idea of a "dump" button similar to what I have on the gas tank and electrolytic separator. Definitely a priority when I get home.

**Comment by WhiteFire-Sondergaard** [comment]
Wonderful! thank you. :)

**Comment by WhiteFire-Sondergaard** [comment]
If anyone needs a work around until then pressure pipe's router can be configured with high priority to your turbine, and low priority to something like an extra utilities liquid trash can. Poor man's pressure relief valve.

**Comment by SuperBrainAK** [comment]
can't you just put a Mekanism Gas Tank in line so that 1 you have a steam buffer and 2 you can set it to dump excess so that the reactor doesnt go critical? I do not know the flow rates of the tanks themselves but the elite tube can do 4096mB/t

**Comment by WhiteFire-Sondergaard** [comment]
Insufficient flow rate. My reactor puts out 7k mB/t and it's a small one. Well was, I finally got my my fuel chain worked out so I've converted to the mekanism reactor.

**Comment by CristinoValdigem** [comment]
![2016-06-27_16 44 11](https://cloud.githubusercontent.com/assets/16420781/16393317/a99136fc-3c86-11e6-8824-d4b1856adebe.png)
![2016-06-27_16 44 25](https://cloud.githubusercontent.com/assets/16420781/16393321/ac4f12f6-3c86-11e6-9c10-50308ce3fc05.png)

The Energy bar fill's up because the output of valve doesn't support 102k/J and when i gona check after a long time with the turbine Working. The Steam have Fill's up inside and turn her unusable

**Comment by aidancbrady** [comment]
Done in development!
