### ISSUE TITLE
Problem with forge version or with the hole modpack?

### ISSUE THREAD

**Issue by chaos234** [aidancbrady/Mekanism#3332]
Hi @aidancbrady ,

long time not seen ^^.

EDIT: After some magic it seems now to be working (updated a few mods, reassigned some IDs). I'll edit it again, if error are still left otherwise I'll close this error self :)

Ok, that's all for now :).

Oh, last thing: Great work for v9 - looked the video and it's awsome <3

**Comment by XFactHD** [comment]
This had nothing to do with your forge version, the problem was that the version of minetweaker you were using wasn't up to date with the new Mekanism API.

**Comment by chaos234** [comment]
Ok, then this is fixed now because I changed the mod-packs version to the correct one :) (will close it then).

Will be funny to setup the ore-processing again with the new images. Are there any changes made since v7/v8?
