### ISSUE TITLE
Mekansim in Regrowth

### ISSUE THREAD

**Issue by mfg495** [aidancbrady/Mekanism#3333]
I'm having issues crafting items in the crafting stations in Regrowth. I have all the right ingredients but when I tried to craft no new items are made just a blank square instead of, lets say, a basic control circuit should be.

Any help would be grateful, a frustrated Minecrafter

**Comment by HadesDurin** [comment]
if i mind it correctly regrowth tweaks some recipes and that way the default recipes where disabled.

**Comment by mfg495** [comment]
Thank you for your reply. I am aware that there is sometimes different crafting recipes I would just have to do some research and see if I can find new ones

**Comment by aidancbrady** [comment]
Yeah, this is definitely not on my end. Make sure no recipes are enabled.

**Comment by mfg495** [comment]
All sorted guys, for some reason my system is not showing the graphic for the osmium plates! some one issue sorted now to try and sort out another. Thanks for your input.
