### ISSUE TITLE
Comparator support for all storage devices? (especially Portable Tanks and the broken Gas Tanks)

### ISSUE THREAD

**Issue by SuperBrainAK** [aidancbrady/Mekanism#3334]
So I am loving the new V9 especially being able to power the Thermal Evaporation Plants with other means, I am trying to properly implement using a Resistive Heater to heat it up with joules which works fine however I am concerned about letting my system idle with 1.12kJ/t, I have an infinite power source (melon farm needing not to say more) but it would be good for other setups that are not as automated or efficient. so I was thinking about using a redstone signal from the Comparator to turn on the Resistive Heater so when I need Brine it will heat up the Thermal Evaporator. Only problem it does not seem like the Comparator is working for the Portable Tank, and also it looks like the Gas Tank is broken, only Block Updates will cause its output to change based on the capacity.

So I shall submit this issue hoping to see fixed and added support to Gas Tanks and Portable Tanks and hopefully keep a single thread for the other storage devices that I am sure other people would like to see supported by the comparator. Cheers!

**Comment by Deathlymad** [comment]
Just to add onto that suggestion it would be awesome if resistive heater and similar blocks would scale their power consumption to a maximum base3d on the redstone signal.

In other words 0 is off
5  = 5/15 of max power is used
15 = maximum limit is used 

That could make regulation of these Setups a lot more adaptive.

**Comment by aidancbrady** [comment]
@Deathlymad, I love the idea but I'm going to leave it up to the Valves and Switches implementation suggested by @EzerArch.

I've added comparator support for the Fluid Tank and fixed the Gas Tank support in development.  Enjoy :)
