### ISSUE TITLE
Searching "Mekanism" in NEI causes crash

### ISSUE THREAD

**Issue by claws-of-fury** [aidancbrady/Mekanism#3338]
I have used and enjoyed Mekansim for a very long time. Recently my Minecraft stops responding every time I look up "Mekanism" in NEI, so there is no crash log unfortunately due to it making my program not respond. I updated to 9.0.2 and it did not help sadly.

**Comment by Eufranio** [comment]
Change B:PrefilledFluidTanks=true to false in Mekanism.cfg.

**Comment by Eufranio** [comment]
@aidancbrady you should make "false" by default in the config :(

**Comment by taze57050** [comment]
Please @aidancbrady add this config

**Comment by XFactHD** [comment]
You just need to use it/change the value!
