### ISSUE TITLE
Long standing issue with Osmium Compressor

### ISSUE THREAD

**Issue by MineWitherMC** [aidancbrady/Mekanism#3339]
Normally, when you place 1 ingot of osmium and 1 ref.obs/glowstone dust into osmium compressor it uses exactly 1 ingot per dust. You can then continue place ingots and dust 1 by 1 and all will be OK. But if more than 1 ingot and 1 dust is placed each dust uses 201 liquid osmium not 200 thus losing 1 ingot worth of osmium. This issue is present in versions from 7.1.2 to 9.0.2 and maybe some others.

**Comment by aidancbrady** [comment]
This loss of osmium efficiency has been intended as far as I'm concerned.

**Comment by 4rz0** [comment]
But then why is there a loss when putting in more than one, but not when putting in single ones?
Makes not a lot of sense imo.

**Comment by Keekuli** [comment]
This is just a thing in the long list of stupid stuff with Mekanism.
