### ISSUE TITLE
Digital Miner ate my Tesseract

### ISSUE THREAD

**Issue by otakucode** [aidancbrady/Mekanism#3341]
So I needed some Sky Stone.  Flew to a meteor.  Put my Digital Miner down on top of it.  It sat such that on the right-hand side of the miner, there was an empty air block underneath where I intended to put my Tesseract.  So, being unable to place it on the ground, I shift-right-clicked on the port on the miner.  To my surprise, the Tesseract was placed INSIDE that block space.  Both the Tesseract and the port of the miner appeared to be there in the same block.  But the miner powered up and worked fine.  After it'd mined out the meteor, I shift-right-clicked on the front of the Digital Miner with my wrench (Applied Energistics Crescent Hammer specifically) to pick it up.  The miner turned to block form and my magnet pulled it to me.  But the Tesseract was gone.

I searched the issue tracker here, but didn't see any mention of this, so figured I should report it.  Haven't had a chance to more thoroughly test, it just happened.  If there are any experiments you'd like me to run or logs that might be helpful, just let me know.  I'm playing on Bevo's Tech Pack Reborn Beta T via ATLauncher.

**Comment by Deathlymad** [comment]
When Mekanism blocks are broken with a wrench their Inventory is retained (it should say so on the Details tooltip) (does it say Inventory: true when all other slots are empty )

if you place the miner again does he work like previously without having to place a tesseract again (if not will the same thing repeat with a tesseract disappearing?).
Does that happen with the Entangloporter too?

Side note:
AppEng Crescent Hammer O.o i thought the crescent Hammer was from (the former) Thermal Expansion and AppEng has a Wrench too :) (its fine I am just irritated)

**Comment by otakucode** [comment]
Yes, sorry, it was the crescent hammer from Thermal Expansion.  The tooltip
says Inventory: no.  Placing the miner again resulted in it requiring
external power as usual.  I have not been able to reproduce the occurrence
despite much trying.  I even flew back to the exact same meteor and
replaced the miner in the same spot I had placed it before (but the meteor
is gone now unfortunately so it's not exactly the same as before).  I
hadn't created an entangloporter before, but just did a few minutes ago to
test and I could not reproduce it using one of them either.  If anything I
wrote caused your irritation, I apologize.  I love the hell out of your mod
and greatly appreciate your work.  The last thing I want is to be a pain in
the ass.

**Comment by Deathlymad** [comment]
hmmm....
did you do that on a server or a client and di you check the log for any weird warnings and stuff?

**Comment by aidancbrady** [comment]
I get the feeling this is a one-time issue from the way you described it, I've never seen a block placed inside the Digital Miner bounding block space.  Let me know if you eventually find a way to reproduce this.
