### ISSUE TITLE
Quantum Entangloporter breaks after server restart.

### ISSUE THREAD

**Issue by RedGuy54** [aidancbrady/Mekanism#3342]
I set up a Quantum Entangloporter that was working, but when I restart my server, the cables are no longer connected and I have to create a whole new channel for it to work again.

**Comment by th4umiel** [comment]
Can confirm that this happened to me in single player.

**Comment by aidancbrady** [comment]
Has been reported, due to either an item-related bug which has been fixed or an interaction issue.
