### ISSUE TITLE
Gas Generators

### ISSUE THREAD

**Issue by RedGuy54** [aidancbrady/Mekanism#3344]
I've been trying to make the hydrogen way of making energy work. It's really complicated because unlike all the other generators there is not a config option, it relies on other ones. I tried increasing the ethylene burn rate, it didn't seem to affect anything. Also, no matter what the HydrogenEnergyDensity is, it always balances out. Is there anyway to make the hydrogen system actually create energy?

**Comment by SuperBrainAK** [comment]
hydrogen is not a source of energy as you have to make the hydrogen the same way as you are "burning it" Sine V8 the same variables that make them (electrolytic separator consumption) is the same as what they produce (GBG output) it is only possible to store energy as hydrogen, it just makes no sense as a source of power. in physics water comprised as H2O (2 Hydrogens and 1 Oxygen) uses energy to break it into H2 and O (electrolytic separator) then the H2 is put into a hydrogen fuel cell (Gas Burning Generator) that combines the H2 with O (that comes from the air where you put the O that came from the water originally) which makes H2O and a little bit of energy which is back where you started so where would the power come from?

**Comment by RedGuy54** [comment]
@SuperBrainAK I don't care about the science behind it. I'm making a modpack and I wanted to create another way to make energy.

**Comment by VT-14** [comment]
If Hydrogen produced more power than it took to make, you would make an infinite power loop.  It was possible to do this before, and was fairly quickly patched out.

You just tried to break the laws of Thermodynamics.  I know this is just a game, but Mekanism is fairly scientifically accurate.

In Mekanism, Hydrogen is used for Energy Storage, as it is 100% efficient (you get all the energy out that you put in [not possible in real life, so be happy about that being in the mod]).  If you want to generate power with a Gas-Burning Generator, then make Ethylene.

**Comment by RedGuy54** [comment]
Well yesterday I messed around with Ethylene using Minetweaker, and It was a disaster. I'm just going to use minetweaker to make it generator more power.
