### ISSUE TITLE
Mekanism textures 

### ISSUE THREAD

**Issue by GrandNickyNick** [aidancbrady/Mekanism#3345]
Hello, so I am making a resource patch pack for an upcoming modpack no released yet. I'm aware mekanisms just updated however on other packs I can cover the items/machines that I have textures for and the remaining are just the vanilla textures. In this specific instance I have tools and items covered with textures however the machines/cable textures do not lose despite having a patch that covers them.

**Comment by aidancbrady** [comment]
I'm not sure why this would be occurring- make sure another resource pack is not interfering with my textures.
