### ISSUE TITLE
Digital Miner incorrectly mining "Lava Rock" from GeoStrata with Silk Touch

### ISSUE THREAD

**Issue by starg09** [aidancbrady/Mekanism#3346]
Hi, just wanted to report what happened when I put these two mods together in my pack. I ran a digital miner to see the amount of ore in a certain area, and to my surprise [this appeared](https://gfycat.com/DenseRemoteBighorn)

Now, I've talked to Reika before posting here, and from his reply I get that he cannot do much on this, so I thought maybe you could fix this :)

There's not an issue with the collection of the block itself, but it should always be obtained with a metadata value of 0 (the block that looks like lava with a little bit of stone in it). All other variants should be transformed to that. This can be replicated by using picks both with and without a Silk Touch enchantment.

**Comment by starg09** [comment]
Oh, I just noticed that gfycat cropped the recording at 15 seconds. There's a part missing where I mine all 4 blocks in the chest with a pickaxe enchanted with Silk Touch, then with a regular one. In every case the block is returned as the more red one, with a metadata value of 0.

**Comment by aidancbrady** [comment]
That's strange. I'm afraid there's not much I can do about this- I pass all the necessary information to blocks before they are destroyed. If I find a way to solve this later I'll definitely take another look :)

**Comment by starg09** [comment]
So, with that you mean there's a way a mod can say "hey, this block shouldn't be mined" or "hey, mining this block should always give this"?

**Comment by XFactHD** [comment]
When a block is defined, the modder can specify the block's drops. Making a block unbreakable is also possible.

**Comment by starg09** [comment]
Hmm, how odd that actual silk touch pickaxes do drop the correct block... Maybe I should try the Digital Miner without Silk and see if the same happens...
