### ISSUE TITLE
Thermal Evaporation structure's contents visible

### ISSUE THREAD

**Issue by themechman** [aidancbrady/Mekanism#3350]
Well, don't know what to say caused this. Just spotted it in my reactor building. It looks like the interior is misaligned with the structure's. Before I put them here, they were outside and solar powered.

![2016-06-12_02 16 46](https://cloud.githubusercontent.com/assets/2990361/15989454/c82d239e-3044-11e6-82fb-3faf857f7718.png)

**Comment by MrGraphic** [comment]
Noticed this to. Looks more like flipped direction of fluid placement.

**Comment by adamcirillo** [comment]
I've seens this as well in my skyblock spawning below the tower using build 274

**Comment by aidancbrady** [comment]
I forgot to account for the new variable controller placement in the render code. Should be fixed!
