### ISSUE TITLE
Mekanism Crashing with NEI (FIX)

### ISSUE THREAD

**Issue by LilShrimp01** [aidancbrady/Mekanism#3352]
-----------------------------------------------------------EDIT (FIX)------------------------------------------------------
Problem: NEI keeps crashing when you type in the search bar "@mek" or "@mekanism"
Fix: Load up Minecraft. Click on "Mods." Scroll down to "Mekanism" and click on it. Then click "Config." Click on "Mekanism General Settings." Scroll down to these three options: "PrefilledFluidTanks," PrefilledGasTanks," and "PrefilledPortableTanks." Make all of those switch to "false." After that, click "Done" and you should be good to go! ^-^
-----------------------------------------------------------EDIT (FIX)------------------------------------------------------

------------------------------------------------------Original Problem---------------------------------------------------
First things first, I can't show a crash log of this problem because every time it happens my Minecraft window goes to "Not Responding," and then a few seconds later my laptop's disk goes to 100%, stays like that for about five minutes until the Minecraft window is terminated altogether-which leaves me with no crash log for some reason. Regardless, here is the story: my Minecraft is doing just fine until I go to the NEI search bar and put "@mek" in order to look up the Mekanism mod and its recipes. That is where all hell breaks loose. Notice how I only got as far as "@mek"-as soon as I put that in my Minecraft stops responding and what you heard above with my disk going to shit happens. So I was wondering if there was some sort of fix for this, or a 1.7.10 version of Mekanism that won't do this. By the way, I am using the latest version of 1.7.10 for both Mekanism and NEI. Also, if this helps, I am using the "amazon" download of Minecraft because for some reason the installer for MInecraft stops at "Runtime Enviroment won't set up" or something like that (be cool if someone could help me with that too :P). Anyway, I'd be nice if someone could please help me ;-;
------------------------------------------------------Original Problem---------------------------------------------------

**Comment by noobyaran9** [comment]
Try go to your mekanism config option and turn of this 2 option.
B:PrefilledFluidTanks=false
B:PrefilledGasTanks=false

**Comment by LilShrimp01** [comment]
How do I get to the config for Mekanism? XD

**Comment by HadesDurin** [comment]
it is normals located in C:\Users\USERNAME\AppData\Roaming\.minecraft\config
ther you find the mekanism.cfg for the config options
you can open and edit it with any text editor

**Comment by LilShrimp01** [comment]
Ah, thanks. Also, I loaded up Minecraft and found the option. I am going to try it and see if it works. If it does, thanks! :D

**Comment by LilShrimp01** [comment]
Should I do the same for "Prefilled Portable Tanks?"

**Comment by HadesDurin** [comment]
its totally up to you, i have it set to false

**Comment by LilShrimp01** [comment]
K, thanks, now I am gonna try it. Fingers crossed! ^-^

**Comment by LilShrimp01** [comment]
YAS, thank you guys! It worked!

**Comment by Mekanism** [comment]
I only play Starcraft :(


________________________________

**Comment by LilShrimp01** [comment]
But Mekanism, what do you mean? xD

**Comment by Mekanism** [comment]
I have no idea why I'm getting these emails. xD


________________________________

**Comment by LilShrimp01** [comment]
Lol

**Comment by LilShrimp01** [comment]
Aidan, what does it mean when it says you "closed" this thread? xD
