### ISSUE TITLE
BUGGED ultimate fluid tank

### ISSUE THREAD

**Issue by gp009** [aidancbrady/Mekanism#3353]
this Ultimate fluid tank of only holding basic tank worth of liquids  which of 14000mb  instead of 112000mb

I dont know of this bug is persisting in latter mekanism versions, im currently using 9.0.1. 

 I **want** to download the latest version, but adfly  scares me **not** to do so ( please use a different download site )

![bugged-tank](https://cloud.githubusercontent.com/assets/12178372/16033661/38ed856e-31db-11e6-9734-07c5c00951a3.png)

**EDIT**

there is a work around this bug by breaking the tanks and replacing them,  then they hold the amounts they should

**Comment by aidancbrady** [comment]
This should be fixed in development, expect a release soon.
