### ISSUE TITLE
Gas Tank Recipe in NEI

### ISSUE THREAD

**Issue by Cazadorsniper** [aidancbrady/Mekanism#3354]
Hello, while creating Project Ozone 2, the Basic Gas Tank won't display its recipe in NEI. I have to craft it first before I can see the recipe by pressing "R" in NEI, but it won't display the recipe directly. The Advanced, Elite, and Ultimate Gas Tanks don't show up in NEI at all. Using Version: 9.0.2.271 the recommended version. Should I update to the latest?

**Comment by aidancbrady** [comment]
This is due to a mod interaction, I can't put my finger on the name right now. Make sure your mods list is totally up to date.

**Comment by Cazadorsniper** [comment]
all mods are as updated as curse will let me.
