### ISSUE TITLE
[Suggestion] Dynamic Tanks

### ISSUE THREAD

**Issue by R1ZL4** [aidancbrady/Mekanism#3355]
It would be really useful if the dynamic tanks had a rednet port with support for the full 16 channel rednet cables, combined with some basic logic that would allow the following:

Closing / Opening of individual valves (external redstone triggers or internal fill levels)
Reading the fill level (0-15 redstone level)
Complete shutdown of the tank (nothing in or out) (external redstone triggers or internal fill levels)
Ability to convert a valve to an input or an output or both based on fill levels or external redstone trigger
Select the input/output speed per valve based on fill levels or external redstone trigger

Another useful feature would be the ability to dye the dynamic tank blocks to break up the blandness of 10 tanks looking exactly the same.

**Comment by aidancbrady** [comment]
Such a trigger device is planned in the future, and I'm pretty sure it's going to be separate from the tank itself.  Appreciate the feature request :)
