### ISSUE TITLE
[BUG] Sorting by ModID only sorts blocks

### ISSUE THREAD

**Issue by Arkandos** [aidancbrady/Mekanism#3356]
Using version 9.0.0.269

When I use a Logistical sorter to sort by ModID, it only sorts blocks, not items. 
It also does not sort non-solid things like pipes.

**Comment by HadesDurin** [comment]
as you notice, mekanism is based on 3 parts, mek tools, mek gen and mek in general
if you set it right, then you will have no problems

**Comment by Arkandos** [comment]
Thats not the issue.
For example, if I set the filter to "Mekanism", it does not filter Logistical sorters or Enriched alloys.

**Comment by aidancbrady** [comment]
I'm afraid that the real fix for this is not going to come until the 1.9.4 release, there are some strange issues with the way mod ID filters are handled.
