### ISSUE TITLE
[Question] Bin Storage

### ISSUE THREAD

**Issue by HadesDurin** [aidancbrady/Mekanism#3358]
i lately try out some of the bins and find the settings for the stored max items per tier in the config file.
my questin is, what is the highest possible max item number to set?

**Comment by aidancbrady** [comment]
The max integer value, which I don't know off hand. But it's likely larger than any value you would care to set :)

**Comment by mimikal** [comment]
It's 2147483647. :)

**Comment by HadesDurin** [comment]
many thanks for the answer
