### ISSUE TITLE
[1.9.4] Compatibility issue with Industrialcraft

### ISSUE THREAD

**Issue by Xiaminou** [aidancbrady/Mekanism#3359]
1.9.4 build crash on startup because of a compatibility issue with Industrialcraft, is there any way to disable Industrialcraft compatibility? (it should be a config option)

Crash Report: http://pastebin.com/mbAcYyad

**Comment by Xiaminou** [comment]
any words on this? I'd like to include mekanism in my pack for further testing but I can't remove Industrialcraft.

**Comment by Marfjeh** [comment]
Yup. Have the same crash log as you when i load ic2

**Comment by aidancbrady** [comment]
Fixed, thanks!
