### ISSUE TITLE
[1.9.4] All parts of the armors want to go on your head

### ISSUE THREAD

**Issue by Xiaminou** [aidancbrady/Mekanism#3360]
Chestplate, leggings and boots are treated as helmets.

![2016-06-16_12 28 48](https://cloud.githubusercontent.com/assets/8670392/16113770/16700ed2-33be-11e6-9f19-2d49e6d582cf.png)
![2016-06-16_12 29 27](https://cloud.githubusercontent.com/assets/8670392/16113769/166f78c8-33be-11e6-9630-d55fbbf84d48.png)

**Comment by XileForce** [comment]
I can second this in a build compiled from latest sources.

**Comment by aidancbrady** [comment]
Fixed!
