### ISSUE TITLE
Inconsistent heat generator heating

### ISSUE THREAD

**Issue by TacoMage** [aidancbrady/Mekanism#3370]
If you hook up a heat generator to ultimate thermodynamic cabling and then hook that into a heat boiler, it produces 20 mb/t of steam.

If you instead build the heat generator directly on top of the boiler, it produces 125 mb/t of steam.

Meanwhile the fuelwood and resistive heaters produce the same steam regardless of if they're directly touching the boiler or connected with cabling.

The big difference I noticed in the above configurations is that the head generator "transfer" numbers are much different between the two cases.

**Comment by aidancbrady** [comment]
Yeah, this is due to the transfer coefficient of the heat generator. Technically this falls under intended behavior but I'm gonna do some tweaking in the coming versions. Thanks for the heads up :)
