### ISSUE TITLE
Nei glitch with gas tank

### ISSUE THREAD

**Issue by budder221** [aidancbrady/Mekanism#3371]
i truly don't know if this is nei's fault or mekanism's but when i try to find the gas tanks i only see the basic and i can get the recipe though if i have a gas tank of any kind in my inventory i can press "R" for the recipe and i can see it. again don't know who's bug it is other both but reporting on both

**Comment by aidancbrady** [comment]
This is due to a mod interaction, some kind of NEI clutter fix thing. They just need to update Mekanism integration
