### ISSUE TITLE
Mekanism creating a ton of lag!

### ISSUE THREAD

**Issue by RedGuy54** [aidancbrady/Mekanism#3372]
I've been playing a modpack with my friends and recently, I would join the server and I would be falling though the world. I tried investigating with opis, but the only thing I could see was the ping would get crazy high anytime I went near our city. I removed mods one by one and noticed it all stopped when I removed Mekanism. It might be because we use the mekanism cables everywhere... i'm not sure.

**Comment by aidancbrady** [comment]
Disable fancy cable rendering in the config, it's likely the update packets causing the issue.

**Comment by RedGuy54** [comment]
@aidancbrady  I tried that, it reduced the ping, but not enough. The only way I can fix it, is I use a backup. It seems like anytime the world saves with no one on it, this happens.

**Comment by RedGuy54** [comment]
@aidancbrady Also, on opis. When I go into outbound the "S35PacketCustomPayload" gets really high, I think this is what is making the ping get really high. I just don't know what to do to get it lower.
