### ISSUE TITLE
[1.9.4] Strange bug with server loading (RecipeSorter)

### ISSUE THREAD

**Issue by miuirussia** [aidancbrady/Mekanism#3375]
I figured that this happens because of Mekanism (server not starting if Mekanism presents):
https://github.com/MinecraftForge/MinecraftForge/issues/2995
Mekanism build: https://github.com/aidancbrady/Mekanism/commit/466c27b52cbb98af92def830e65dddeedc36a221

**Comment by aidancbrady** [comment]
While it may only occur when Mekanism is installed, I would not link it to me as I don't experience this with my own list of mods installed.
