### ISSUE TITLE
Creative Energy Cube doesn't output to fluxducts of any kind

### ISSUE THREAD

**Issue by mattfreyer** [aidancbrady/Mekanism#3376]
It seems when the Creative Energy Cube tries to output to any kind of fluxduct it shows a negative amount of energy in the fluxduct. Reported it to COFH Github and KingLemming said it was on your end.
Cofh 3.1.2
Thermal Dynamics 1.2.0
Mekanism 9.0.0

[https://github.com/CoFH/Feedback/issues/1184#event-696742457](url)

**Comment by HadesDurin** [comment]
the way how mekansim handels rf is completly diffrent then ender io and thermal expansion handles it.
so to make it right you have to use an thermal expansion creativ energy cell

**Comment by mattfreyer** [comment]
The Creative Energy Cube is just plain better than the Creative Energy Cell, It seems to match the input's RF/tick to its output which might be the problem here.

**Comment by HadesDurin** [comment]
the only safe way of combining thermal expansion and mekanism is that you have befor/after a maschine of the mod a matching cable and then cable from the other mods

**Comment by aidancbrady** [comment]
Update to 9.0.2
