### ISSUE TITLE
[1.9.4] java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by Lazarix** [aidancbrady/Mekanism#3378]
Server side crash when someone logs on

https://gist.github.com/Lazarix/9e5735e41faaa6f0d612a7ba735ab729

**Comment by Lazarix** [comment]
This appears to happen because of mekanism power cables.

**Comment by aidancbrady** [comment]
This should be fixed with the latest server changes.

**Comment by Lazarix** [comment]
Unfortunately not :(
I built the build yesterday and it's occurring. Last code check-in was two days ago

**Comment by aidancbrady** [comment]
Sad :(

**Comment by Lazarix** [comment]
Everything apart from cables is working well though :) :+1:

**Comment by aidancbrady** [comment]
Added a fix.
