### ISSUE TITLE
Infinite Gas in Preplaced Preupdate Hydrogen Tank.

### ISSUE THREAD

**Issue by Triaxx2** [aidancbrady/Mekanism#3380]
So, I have three Portable Gas Tanks, which had been placed in the world before updating from Mekanism v8 to v9.0.1. Now they seem to be infinite. I've tried draining them with newly created tanks, so they'd be below the point where any pre-upgrade Hydrogen would have been 'in storage' in the ether, and they didn't move at all from 64,000 mb of Hydrogen. Picking up and replacing them doesn't seem to have any effect.

**Comment by aidancbrady** [comment]
It's likely that the capacity got screwed up. Breaking and replacing should theoretically fix, but I have no plans on adding new transition features.
