### ISSUE TITLE
Universal cables and EnderIO power buffer.

### ISSUE THREAD

**Issue by RedGuy54** [aidancbrady/Mekanism#3381]
When I disconnect a Mekanism Universal cable from a enderio power buffer, my server crashes.

EnderIO: 2.2.8.381
Minecraft: 1.7.10
Forge: 10.13.4.1558
Mekanism 9.0.2.271

Crash Report:

http://pastebin.com/JvxUHqAf

**Comment by Gepett0** [comment]
Seems like a problem from ender io.
Try to update to latest beta (427) and see if problem persists.

**Comment by aidancbrady** [comment]
Yeah, does not appear to be on my end.
