### ISSUE TITLE
Basic universal cable throughput scales with length.

### ISSUE THREAD

**Issue by tolomea** [aidancbrady/Mekanism#3382]
This is on Mekanism-1.7.10-9.0.2.271
I've been conducting experiments to find out the throughput of the basic cable.
My test setup is two ultimate energy cubes with a length of basic cable between them.
On this setup I've been timing how long it takes to move power between the cubes and what I've found is it's proportional to the length of the cable.
So one block of cable moves power at 3.2kJ/t
Two blocks at 6.4kJ/t etc
Up to 16 blocks where it maxes out the drain on the energy cube.
Also the cable distance between the cubes doesn't have to be 16, only the total cable. 
So for example a 3 section cable between the cubes with a 13 section run off to the side going no where will also serve.
Or you could bundle those 13 blocks up into a cube, that doesn't change anything either.
The wiki doesn't talk about cable throughput under different network topologies but it seems unlikely that this is correct behavior, hence posting it here.

This came up while trying to understand the behavior of basic cables, more info on that here:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1284681-mekanism-v9-0-2-industrial-turbines-thermoelectric?comment=2226

**Comment by aidancbrady** [comment]
Intended behavior, believe it or not!

**Comment by tolomea** [comment]
Doesn't that remove most of the value of the higher tier cables?

**Comment by ktole1999** [comment]
no because you can transfer that same amount using less cables.
