### ISSUE TITLE
crash when placing a power using block

### ISSUE THREAD

**Issue by clarence112** [aidancbrady/Mekanism#3383]
[crash-2016-06-20_23.54.36-server.txt](https://github.com/aidancbrady/Mekanism/files/324779/crash-2016-06-20_23.54.36-server.txt)
[crash-2016-06-20_23.50.07-server.txt](https://github.com/aidancbrady/Mekanism/files/324780/crash-2016-06-20_23.50.07-server.txt)

**Comment by aidancbrady** [comment]
Hopefully fixed with latest changes.
