### ISSUE TITLE
[Suggestion] Oredictionifier upgrade

### ISSUE THREAD

**Issue by XredstonemodsX** [aidancbrady/Mekanism#3384]
I'd like to see an upgrade for digital miners that allows you to convert all items into one specific type as it mines, rather than having to let it clutter the inventory of the device and change it later, it could fit a maximum of 8-16, each adding 1 more oredictionary filter

**Comment by aidancbrady** [comment]
This is why the Oredictionificator block is a part of Mekanism. I'd rather leave the functionality the way it is now.
