### ISSUE TITLE
[Suggestion] more Bin Tiers/switchable to only one aviable max int Bin

### ISSUE THREAD

**Issue by HadesDurin** [aidancbrady/Mekanism#3385]
after some testing and using of the bins, i ran into the problem that making equal steps from 0 to 2.147.483.647 in 4 tiers is do able:
Tier 1 8.192
Tier 2 524.288
Tier 3 33.554.432
Tier 4 2.147.483.647

(How did i do it:i add 1 to the max int and divide the result by 64 each step)
as you see the steps are enourmous, which is in my eyes a problem.

so i thought about that it will be better to have more tiers to have closer steps
and a diffrent tought was to have only one tier of storage with max int value.

**Comment by aidancbrady** [comment]
This is why the configuration exists, so that you can change the values to your liking. Current values are scaled to the way I intended.
