### ISSUE TITLE
[1.9.4] Leggings and Chestplates do not render the right parts on the player

### ISSUE THREAD

**Issue by Xiaminou** [aidancbrady/Mekanism#3386]
![2016-06-21_15 24 24](https://cloud.githubusercontent.com/assets/8670392/16231033/93d63748-37c4-11e6-92d3-23343c980497.png)
![2016-06-21_15 24 30](https://cloud.githubusercontent.com/assets/8670392/16231034/93d641a2-37c4-11e6-9ce3-dd69137db8f3.png)

Screenshots should speak for themselves.

**Comment by aidancbrady** [comment]
Fixed!
