### ISSUE TITLE
[1.9.4] WAILA Integration reports the wrong machines

### ISSUE THREAD

**Issue by Xiaminou** [aidancbrady/Mekanism#3387]
You're probably aware of this but I'm going to report it anyway, WAILA reports the wrong machines:

![2016-06-21_15 26 56](https://cloud.githubusercontent.com/assets/8670392/16231081/caa3e036-37c4-11e6-9d59-209994fd078c.png)

**Comment by InsomniaKitten** [comment]
I think this is an issue with WAILA. It seems to only be able to display information based on the block ID and ignores any metadata.

**Comment by Xiaminou** [comment]
Good point, it doesn't work for Iron Chests either.

**Comment by aidancbrady** [comment]
Yeah, not on my end. I'll wait to see if WAILA fixes the issue.

**Comment by Xiaminou** [comment]
has it been reported to WAILA? or should I report it?
