### ISSUE TITLE
[1.9.4] Mekanism causes FPS lag

### ISSUE THREAD

**Issue by Xiaminou** [aidancbrady/Mekanism#3388]
When placing or breaking any blocks near Mekanism's stuff (must be within your render distance) the game will lag or freeze for a millisecond. This also happens when a machine turns on and off a lot.
For example PRC being faster than crusher will turn on/off a lot. This dropped my FPS to 7 from 100. Note that this only happens when the machines turn on or off, not when they're running.

![2016-06-21_15 25 12](https://cloud.githubusercontent.com/assets/8670392/16231193/6e2a7b66-37c5-11e6-8232-2c0b9f2126d3.png)
![2016-06-21_15 26 56](https://cloud.githubusercontent.com/assets/8670392/16231192/6e266bc0-37c5-11e6-97b3-a4b4173aa76f.png)

**Comment by Lysdex** [comment]
Did your PRC actually output ethylene, No matter what i did to the config mine would now output the Gas, i am aware the gas output is on the right hand side

**Comment by Xiaminou** [comment]
I don't remember if they used to output gas in 1.7.10 but in 1.9.4 you have to set the pipe to pull the gas out of the machine.

**Comment by Lysdex** [comment]
So the actual pipe needs configuring. Maybe this is where i am going wrong XD

**Comment by Xiaminou** [comment]
Yes indeed, you have to use the Configurator

**Comment by aidancbrady** [comment]
90% sure this has to do with the way CTM stuff is rendered- CTM connections are recalculated and rerendered every time the world renderer updates which likely leads to some overhead when you have a lot of multiblock contraptions nearby. I'm too busy to do anything about this now but I'll look into some caching in the near future.
