### ISSUE TITLE
[1.9.4] Mekanism ships with an incompatible RF API

### ISSUE THREAD

**Issue by HenryLoenwind** [aidancbrady/Mekanism#3389]
The RF API that's included is the BuildCraft port which is incompatible with the official port, leading to "method not found" crashes (e.g.https://github.com/SleepyTrousers/EnderIO/issues/3428 ). Would be nice to use the official 1.8 port instead, it only needs one tiny change to work on 1.9.

**Comment by McJty** [comment]
Yes, this problem also causes a conflict with RFTools

**Comment by aidancbrady** [comment]
Fixed!
