### ISSUE TITLE
[1.9.4] Universal Power Cable crash

### ISSUE THREAD

**Issue by ruyanve** [aidancbrady/Mekanism#3392]
Placing a power cable gives me this: https://gist.github.com/ruyanve/0c4c11ffdc5e9ea0937b5323ddd79977

**Comment by aidancbrady** [comment]
Not sure how this could happen unless you have a mod shipping an outdated IC2 API.  I'm running without IC2 just fine.

**Comment by ruyanve** [comment]
Aye, my bad! Sorry!
