### ISSUE TITLE
[1.9.4] Server crash while in the mining world

### ISSUE THREAD

**Issue by Xiaminou** [aidancbrady/Mekanism#3396]
I recently integrated Mekanism in my modpack and soon found out that my mining world somehow dropped my FPS down to 1.
Now that was only client side until today, I stayed a bit longer than usual (as I have decided to build a new one and hopefully get more FPS) in my mining world and the server ended up crashing.

Crash Report: http://pastebin.com/h3qxVYUV

**Comment by aidancbrady** [comment]
Strange. I'm pretty sure that's not on my end, though- Mekanism isn't mentioned anywhere.  Let me know if you somehow trace it back to me.
