### ISSUE TITLE
[1.9.4] Right clicking mechanical pipe with configurator crashes client

### ISSUE THREAD

**Issue by RealGrep** [aidancbrady/Mekanism#3397]
Shift-right clicking works ok, but plain right clicking a mechanical pipe end with the configurator crashes the client and gives this output:

http://pastebin.com/aFmVzCXK

This is using MekanismAll-1.9.4-9.0.3.homebaked.jar built from 1.9.4 Github branch, and Forge 1968 on MC 1.9.4.

Let me know if there's anything else you need. Thanks! :)

EDIT: I should mention this is SMP and a server is involved, in case that matters at all.

**Comment by aidancbrady** [comment]
A mod is shipping an old version of the CoFH API. Once they update this will be fixed :)

**Comment by RealGrep** [comment]
Ok, thanks :)
