### ISSUE TITLE
[1.9.4] - Rendering block entity crash

### ISSUE THREAD

**Issue by Lazarix** [aidancbrady/Mekanism#3399]
The portable tank causes a crash when put into a tinker's construct crafting station.
We believe the issue is a rendering issue due to the fact that the crafting station renders items on top of the table.

https://gist.github.com/Lazarix/006ac9201aeffdd2cb1c31458b634734

**Comment by aidancbrady** [comment]
What Mekanism release are you using?

**Comment by Lazarix** [comment]
latest code from today, 1.9.4

**Comment by Xiaminou** [comment]
TiCon's crafting stations are known to crash with mod items, you should probably disable the render.

**Comment by aidancbrady** [comment]
Fixed, thanks
