### ISSUE TITLE
1.9.4-9.0.3.33 Digital miner not working.

### ISSUE THREAD

**Issue by joshricker** [aidancbrady/Mekanism#3401]
The digital mine seem to not be scanning blocks at all in this version and thus shows no blocks to mine. Link to video here to make sure it isn't just me not doing it right https://www.youtube.com/watch?v=qa9JGNiS6V4 . Tested with only Mekanism	9.0.3.33, MCMultiPart experimental 1.2.0_73 and forge 12.17.0.1987 on a fresh install.

**Comment by aidancbrady** [comment]
Fixed!

**Comment by pchard** [comment]
@aidancbrady How was it fixed?
