### ISSUE TITLE
[1.9.4] ThermoElectric Boiler and Steam Turbine not showing informations

### ISSUE THREAD

**Issue by Xiaminou** [aidancbrady/Mekanism#3402]
The ThermoElectric Boiler is not longer showing the Boil Rate and Max Boil, they're showing 0 when it should be 390.
![2016-06-24_15 07 37](https://cloud.githubusercontent.com/assets/8670392/16338497/673377c2-3a1d-11e6-80fb-ece0508ef353.png)

The Steam Turbine doesn't show the right informations either, it's showing 45mb/t and 642 RF/t instead of 5k RF/t. It also looks like it's full of steam, when it's not.
![2016-06-24_15 01 50](https://cloud.githubusercontent.com/assets/8670392/16338509/855c41ac-3a1d-11e6-9e80-d8842a9775e9.png)
![2016-06-24_15 01 55](https://cloud.githubusercontent.com/assets/8670392/16338512/856024e8-3a1d-11e6-81cb-88972145b49a.png)
![2016-06-24_15 02 03](https://cloud.githubusercontent.com/assets/8670392/16338510/855df47a-3a1d-11e6-9880-b35c0f9fef2f.png)

It's producing power just fine but I don't know what caused it, and have no idea how to reproduce it, or make it behave normally again for that matter.

**Comment by Xiaminou** [comment]
Broke a replaced a block, now the Boiler is fine but the turbine shows half the production.

**Comment by Xiaminou** [comment]
I do have a theory about this, I think it's the same kind of bug as [this one](http://bt.industrial-craft.net/view.php?id=1857).
I added a tree farm nearby, and every time a tree grows or gets chopped down I see the particle effects as if the multiblock was re-forming.

**Comment by aidancbrady** [comment]
I'm fairly certain this is an interaction issue, after a bunch of testing with the boiler and turbine I can't get this to happen.  Let me know if you can prove otherwise.
