### ISSUE TITLE
Heat generator GUI

### ISSUE THREAD

**Issue by Darktotaled** [aidancbrady/Mekanism#3403]
Hey aidan o/
i'm using the latest version of mekanism(base, generators and tools) and my heat generator doesn't change the the heat unit when i click the heat tab on it. It appears the unit that's selected but the heat produced/dissipated keeps showing kelvin even though i change it to Celsius or any other. Could you have a look at it?

**Comment by aidancbrady** [comment]
Fixed in development, thanks! Don't know how I missed this.
