### ISSUE TITLE
8V to 9V energy cubes in recipies

### ISSUE THREAD

**Issue by Dommain** [aidancbrady/Mekanism#3405]
I cannot seem to use energy cubes made in version 8 in version 9 recipes so I have allot of energy cubes sitting in my ME system that cannot be used. Is there a fix for this?

**Comment by aidancbrady** [comment]
Drain the energy cube first, or place it and then break it. This is just one of those weird transition issues.

**Comment by Dommain** [comment]
Thanks, still cannot figure out how to fix the 75k tablets. Ill just drop them into lava.
