### ISSUE TITLE
[1.9.4] Cable's can't extract RF

### ISSUE THREAD

**Issue by Master0r0** [aidancbrady/Mekanism#3408]
When connected to RF generators or power storage blocks from other mods the cables are unable to pull the energy from them and the blocks cannot push energy out into the cables even after changing the connection types on the cables themselves to push and pull.
However Mekanism Generators can push energy into cables and the blocks of other mods and the mekanism machines will accept power from other mods cables.

**Comment by aidancbrady** [comment]
This is due to the way transmitters handle their contents now- everything is done with capabilities. Mekanism will be supporting the Tesla API which will allow this kind of power transfer to work again.
