### ISSUE TITLE
Energy not transferred through AE2 P2P channels

### ISSUE THREAD

**Issue by AterIgnis** [aidancbrady/Mekanism#3410]
Connecting universal cable to AppliedEnergistics2 P2P channel on both ends does not allow for energy transfer.
Seems the cause is EnergyAcceptorWrapper.RFAcceptor::transferEnergyToAcceptor()
'int needed' is calculated from enegy capacity on other side (getEnergy, getMaxEnergy), which returns 0-0=0 in this case. Removing 'needed' and using "int transferred = acceptor.receiveEnergy(side, toRF(amount), false);" fixed the issue for me.

**Comment by aidancbrady** [comment]
Fixed, thanks.
