### ISSUE TITLE
[1.9.4] Crash caused placing generators

### ISSUE THREAD

**Issue by karakufire** [aidancbrady/Mekanism#3411]
[Here's crash report](http://pastebin.com/Z6ehUMrK).
I guess this crash caused at IC2 API loading.

**Comment by aidancbrady** [comment]
Make sure your version of IC2 is totally up to date. There's also a chance a mod is shipping with an old version of the API.

**Comment by karakufire** [comment]
Thank you for answering, but this crash caused in game launched by "gradle runClient".
