### ISSUE TITLE
Universal cables do not accept EU power

### ISSUE THREAD

**Issue by DraksterAU** [aidancbrady/Mekanism#3413]
Hi Aidan,

I'm using IC2 build 807 and am still unable to get IC2 to output over the universal cables, effectively leaving them as RF cables ;) 

Is there any chance this has been missed in v9 - or I am using too old a build of IC2 - I read through the issue history and saw it was resolved.
Using Mek v9.0.2.274
Regards,
DraksterAU

**Comment by DraksterAU** [comment]
Update: Tried b822 of IC2. No change.

**Comment by DraksterAU** [comment]
I believe youll need to implement the IEnergySink interface for this to work correctly.

I'll do a pull request when it is not 1AM if you dont beat me to it :P

http://ic2api.player.to/ic2api/html/interfaceic2_1_1api_1_1energy_1_1tile_1_1_i_energy_sink.html

**Comment by aidancbrady** [comment]
Already reported. Fixed IC2 support will come when I have some time :)
