### ISSUE TITLE
Gregtech argon gas

### ISSUE THREAD

**Issue by Dekker254** [aidancbrady/Mekanism#3417]
If I traing move gregtech argon gas throught mechanical pipe game crash and world is corrupted. 
Using Mek v9 and gregtech 6.03.03. 

[crash-2016-06-28_17.22.41-client.txt](https://github.com/aidancbrady/Mekanism/files/337515/crash-2016-06-28_17.22.41-client.txt)

**Comment by aidancbrady** [comment]
Fixed in development.
