### ISSUE TITLE
[1.9.4] Crash without Industrialcraft

### ISSUE THREAD

**Issue by Xiaminou** [aidancbrady/Mekanism#3418]
I was testing some stuff with Mekanism alone and it crashes when I built a steam turbine, looks like it won't run without IC².

Crash Report: http://pastebin.com/S0JaENwY

**Comment by Lazarix** [comment]
If you're building from source, you can get around this by copying the IC2 directory from src\api\java to src\main\java

**Comment by Xiaminou** [comment]
Well I just included IC² in my testing pack, it's easier.

**Comment by Lazarix** [comment]
up to you, but you only need that api.

**Comment by aidancbrady** [comment]
Fixed.
