### ISSUE TITLE
[1.9.4] - java.lang.IllegalStateException: Not building!

### ISSUE THREAD

**Issue by Lazarix** [aidancbrady/Mekanism#3420]
When trying to configure a fluid pipe with the Mekanism configurator, a render crash occurred:

https://gist.github.com/Lazarix/19f634e11fc638f4d42603d244700e17

This is with build from June 22nd

**Comment by Lazarix** [comment]
related to #3422 i believe. Will test with new build

**Comment by aidancbrady** [comment]
Yes, this should be fixed, I'm not reproducing on the client.
