### ISSUE TITLE
[1.9.4] - build failing

### ISSUE THREAD

**Issue by Lazarix** [aidancbrady/Mekanism#3421]
Just checked out the latest version of the 1.9.4 branch and got quite a large build failure. It seems to be because the forge fluid source code is being used, but it's not contained within the src directory anywhere:

error: package net.minecraftforge.fluids.capability does not exist
import net.minecraftforge.fluids.capability.IFluidHandler;

https://gist.github.com/Lazarix/17acb7d185b6e4b7f2da0bbef7e0c089

**Comment by unpairedbracket** [comment]
Somehow the forge version specified in build.properties is out of date - change it to something beyond 1946 (1976 is the latest recommended build) and it should work fine. I'll push a version with updated build props soon as well
