### ISSUE TITLE
[1.9.4] Cannot change Induction Port to Output

### ISSUE THREAD

**Issue by Xiaminou** [aidancbrady/Mekanism#3423]
Sneak-right-clicking the Induction Port with a configurator set for Energy does not change the Induction Port from Input to Output.

![2016-06-29_16 15 06](https://cloud.githubusercontent.com/assets/8670392/16455491/cb7e800a-3e14-11e6-9117-6398e00e9889.png)

**Comment by aidancbrady** [comment]
Fixed, thanks!
