### ISSUE TITLE
[1.9.4] Mekanism Pipes do not connect with other mekanism blocks!

### ISSUE THREAD

**Issue by x1nitrc** [aidancbrady/Mekanism#3424]
The working version of the mod is the latest at the moment (June 29). In the description it says that they transfer only MinecraftForge Fluids, whereas Tubes, for example, say Mekanism Gasses.

**Comment by aidancbrady** [comment]
That's because I'm in the process of updating the fluid system. 1.9.4 builds are subject to have some pretty broken features at times due to the big internal overhaul.
