### ISSUE TITLE
[1.9.4] Quantum Entangloporter not connecting to Pipes

### ISSUE THREAD

**Issue by Xiaminou** [aidancbrady/Mekanism#3426]
![2016-06-30_14 36 32](https://cloud.githubusercontent.com/assets/8670392/16488810/a8b67bcc-3ed2-11e6-887c-4ec4f3935da3.png)

The Quantum Entangloporter will only connect to pressurized pipes and even then I haven't been able to get it to transmit anything.

**Comment by aidancbrady** [comment]
Can't reproduce with the very latest source. Make sure you're configuring the sides properly and that the entangloporter is set to a frequency.

**Comment by Xiaminou** [comment]
Have you tried it on a server? It works fine in Singleplayer but on servers it doesn't.

**Comment by Xiaminou** [comment]
Okay, I don't know why, maybe it just needed a server restart, but now it works. That's strange.
