### ISSUE TITLE
[SUGGESTION] item recycler

### ISSUE THREAD

**Issue by gp009** [aidancbrady/Mekanism#3427]
so now that you got that fusion reactor built and running, but wandering what to do with dozens of windturbines/gas-burners/ect.?

since mekanism seems to be about high technology and resource effieciency, ect.  it would be logical to suggest some way to break down and reclaim a fraction of resources it took to create them but should not be 100% but  instead should reclaim 50-75% of the resources that made the item to be recycled.

what do you think?

**Comment by aidancbrady** [comment]
I considered adding something like this a while ago but I don't think I'm going to do so anytime soon.  Perhaps I will add something similar to IC2's scrap boost system when I have some time.
