### ISSUE TITLE
java.lang.NullPointerException with QuantumEntangloporter

### ISSUE THREAD

**Issue by Steelpower900** [aidancbrady/Mekanism#3429]
DNS Techpack 7.8.9.0
Mekanism-1.7.10-9.0.2.271

Error,-
http://pastebin.com/ApkhMynY

Complete fml log from Server,-
http://www.mediafire.com/download/5826kxa49ahgsl6/fml-server-latest.log

**Comment by aidancbrady** [comment]
Thanks, this has already been fixed in development :)

**Comment by Steelpower900** [comment]
good work :)
