### ISSUE TITLE
Robbit stops following you once it picks up a drop

### ISSUE THREAD

**Issue by EzerArch** [aidancbrady/Mekanism#3430]
How to reproduce it:

1. Get yourself a robbit and set following true and pickup true.
![2016-07-02_18 58 35](https://cloud.githubusercontent.com/assets/6743303/16542651/51b5c240-4087-11e6-8069-d56a0e8b7eed.png)

2. Walk away bit, it will follow you. Now drop an item (e.g. pickaxe)
![2016-07-02_18 59 22](https://cloud.githubusercontent.com/assets/6743303/16542653/61218f66-4087-11e6-8456-1d4977cd9cb0.png)

3. The robbit will move to pick it up (pickaxe is in there). 
![2016-07-02_18 59 30](https://cloud.githubusercontent.com/assets/6743303/16542654/6b2ae6ec-4087-11e6-8c1b-475aa3bdb224.png)

4. Walk away. Robbit will not follow you even though the following is true. (If you drop another item **nearby**, it will move slowly towards the item and pick it up).
![2016-07-02_19 04 55](https://cloud.githubusercontent.com/assets/6743303/16542665/e2472344-4087-11e6-98e3-df5ae71fd093.png)

5. I went back and disabled pickup. It follows me.
![2016-07-02_19 06 49](https://cloud.githubusercontent.com/assets/6743303/16542669/3943fee2-4088-11e6-88d7-5ead1012f979.png)

6. I re-enabled pickup. It moves/teleports back to where it had picked up the drop.
![2016-07-02_19 09 01](https://cloud.githubusercontent.com/assets/6743303/16542691/35c55878-4089-11e6-8006-66d4a5623450.png)

So, I have these issues:
* The following+pickup mode only woks if the robbit hasn't picked up any drop. Once it picks up an item I have to disable the pickup if I want it to follow me.
* _**The main problem**_: the pickup mode is available only where the robbit has **last** picked up a drop. If I want to use the pickup mode elsewhere, I have to break the robbit's charge pad to clear out the latest pickup point in its memory, otherwise it will attempt to teleport away back to the latest pickup point (except between dimensions).
* It seems the issue is per-dimension. Changing dimensions clears the latest pickup point and the  following+pickup mode will work again until the robbit picks up an item, and the issue described above repeats.

**Comment by aidancbrady** [comment]
Oops! I had set the mutex bits so that the follow and drop pickup AI tasks couldn't run concurrently.  Aside from that, I wasn't discontinuing the pickup task once the Robit actually consumed the item. Thanks for pointing this out, should be fixed!
