### ISSUE TITLE
Duplicating items

### ISSUE THREAD

**Issue by LemonNick** [aidancbrady/Mekanism#3432]
Duplicating items related to the subject Robbit:
1) The first player enters the Robbit and opens his inventory . He puts in his inventory of any items.
2) The second player breaks the charging plate . ( The first player still holds open Robbit inventory)
3) The first player takes all his subjects from Inventor Robbit
4) Again we put Robbit. We look at his inventory. Objects are not lost . They became x2
5) Dupe
I used a translator , if something is not clear then do not judge = )

**Comment by aidancbrady** [comment]
Fixed, appreciate it!
