### ISSUE TITLE
Bug - Industrial Turbine Will Not Form

### ISSUE THREAD

**Issue by Utildayael** [aidancbrady/Mekanism#3435]
Mekanism 9.0.3.276
Minecraft 1.7.10

Built the industrial turbine multiblock per instructional video Aiden has on his YT channel. 5x5x8

I'd describe the blocks but it is literally the exact setup block by block.

https://www.youtube.com/watch?v=kHJSEUjCsyA

Turbine multi never forms. No sparkles. Tried a 5x5x5 as well and no luck.

**Comment by Utildayael** [comment]
Oops. My bad. Vents and dispersers look so much alike! Sorry about that.

**Comment by akilliess** [comment]
Mine won't form at all for some reason my coils won't link up to one another any one else having this issue?

**Comment by DepthSpider** [comment]
Hey. Im also having issues with the turbine. Take a look at these photos. Especially the coils.
![2018-07-19_21 36 46](https://user-images.githubusercontent.com/41458629/42980450-fa0dd308-8b9c-11e8-9bf9-b7b89e3dae07.png)

next is the boiler. it works somhow but look.
![2018-07-19_21 43 10](https://user-images.githubusercontent.com/41458629/42980473-1341aca0-8b9d-11e8-8cbc-f0e069d08437.png)

Also look at the structural glass. its not connecting.
![2018-07-19_21 36 53](https://user-images.githubusercontent.com/41458629/42980482-23b40844-8b9d-11e8-8427-713bd70d9547.png)

**Comment by thiakil** [comment]
You need the CTM mod for connected textures

**Comment by DepthSpider** [comment]
thank you!
