### ISSUE TITLE
Integeroverflow at Induxtion Matrix when using RF-API

### ISSUE THREAD

**Issue by Iarinu** [aidancbrady/Mekanism#3439]
When using an Induction Matrix, containing enough Induction Providers and connecting it via Cryoteum Fluxduct or anything else transferring unlimited RF/Tick you seem to run into an integer overflow.
If you check the transfer rate with an external tool like WAILA or a PowerMonitor you see that the RF/t transfered constantly jumping from negative to positive and back. (see screen shots attached)
The only impact I discovered so far is, that block with an charge-speed limit charges immediately the second the value gets negative. But since the RF-API isn't supposed to handle negative transfer values I bet there are many more strange side effects which could happen.
An easy way to fix this would be to limit the maximal I/O to the maximum possible with the RF/API, when any kind of RF transferring pipe is connected.

Tested with latest version 9.0.3.277 at MC 1.7.10 with forge 10.13.4.1614-1.7.10

Additional informations can/will be provided if requested

All those screenshots are taken in around 5 seconds.
![2016-07-04_12 41 09](https://cloud.githubusercontent.com/assets/8089791/16560174/04d1c96c-41f2-11e6-9f76-85df346a024c.png)
![2016-07-04_12 41 10](https://cloud.githubusercontent.com/assets/8089791/16560175/04d361f0-41f2-11e6-91ec-3ba8af06cd96.png)
![2016-07-04_12 41 10_2](https://cloud.githubusercontent.com/assets/8089791/16560177/04d7a878-41f2-11e6-968a-126b6e8033c0.png)
![2016-07-04_12 41 11](https://cloud.githubusercontent.com/assets/8089791/16560178/04da19c8-41f2-11e6-9f01-a357f79046e0.png)
![2016-07-04_12 41 11_2](https://cloud.githubusercontent.com/assets/8089791/16560176/04d69104-41f2-11e6-8af2-356a0e088fef.png)

**Comment by aidancbrady** [comment]
Yes, it's true that the Induction Matrix shows some wonky numbers, but I assure you everything is working fine within mod integration.  I cap out at Integer.MAX_VALUE when outputting just as you suggest.
