### ISSUE TITLE
[1.9.4] Server crash when Mekanism Retrogen attempted

### ISSUE THREAD

**Issue by drewbit** [aidancbrady/Mekanism#3440]
Compiled today (04/07/2014)
Forge Version: 1.9.4-12.17.0.1976

Server crashes when retrogen is attempted. Here's the log:

http://pastebin.com/DJGE3UPa

In case it is needed, here is my Mekanism.cfg:
http://pastebin.com/x6D6nGL0

**Comment by aidancbrady** [comment]
Fixed, thanks- no way I would have caught that.
