### ISSUE TITLE
[1.9.4] - Build 9.0.3.58 - Crash when left clicking machines

### ISSUE THREAD

**Issue by addrever** [aidancbrady/Mekanism#3441]
I tried with tinker's pick and empty hand.

Here is a paste.ee of the log left clicking a Metallurgic Infuser:

http://paste.ee/p/BUznv

Here is a paste.ee of the log left clicking a creative energy cube:

http://paste.ee/p/fC4EZ

I should also mention this happens in both single player and multiplayer and with multiple blocks

**Comment by addrever** [comment]
I see this is possibly resolved in 1.7.10.

**Comment by aidancbrady** [comment]
Fixed!

**Comment by addrever** [comment]
oh aidan....you are the man!!!!!  Is there a build ready for 1.9.4?  I'm
ready for 1.10 when you are:D

On Mon, Jul 4, 2016 at 6:49 PM, Aidan <notifications@github.com> wrote:

> Fixed!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/aidancbrady/Mekanism/issues/3441#issuecomment-230361302>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AALn_bHLYFHgcTeEsf5BJyO2k2mTFNcNks5qSY3ygaJpZM4JEnt5>
> .
>



-- 
Aaron Drever
