### ISSUE TITLE
Quantum Entangloporter broken after server restart

### ISSUE THREAD

**Issue by Lennart247** [aidancbrady/Mekanism#3442]
I found out that there seems to be a problem with the Quantum Entangloporters when Galacticraft is installed. It's exactly the same like in other Topics described. After a server restart every type of pipes (Universal Cable, Logistical Transporters, pipes from Buildcraft etc.) disconnects from the entangloporter and it's not possible to reconnect them without creating a new channel. However I think it doesn't happen in singleplayer.  If thats important i tried it with these versions:
-GalacticraftCore-1.7.3.0.12.375
-Galacticraft-Planets-1.7.3.12.375
-Mekanism-1.7.0-9.0.3.276
-MekanismGenerators-1.7.10-9.0.3.276
-MekanismTools-1.7.10-9.0.3.276
-MicdoodleCore-1.7.3.0.12.375
and Forge 1558 for 1.7.10
edit: Okay also happens with forge 1614 and Mekanism-...-278 and without Galacticraft.
strangely pressurized tubes do not disconnect
![2016-07-05_13 28 40](https://cloud.githubusercontent.com/assets/20297308/16583254/a9d665b8-42b4-11e6-984f-464dab13d0f4.png)

**Comment by aidancbrady** [comment]
Mod interaction issue, I assure you.  Been reported several times in the past.

**Comment by Lennart247** [comment]
Yes I read that in other threads. but interaction with what? I do not have another mod installed besides Mekanism.

**Comment by aidancbrady** [comment]
Ah, I didn't see your edit. Does this constantly happen on multiplayer or is it on and off? Are you sure you can't reproduce in single player?

**Comment by aidancbrady** [comment]
I'm doing some testing on a server and I'm unable to reproduce this as you've stated.  I'm using the exact version of Forge mentioned.

**Comment by Lennart247** [comment]
At least for the 5 times i tried it now it happens constantly. And yes I can't reproduce it in single player (leaving the world, and loading it should be enough right?), ah okay found out that if i open the world to lan in singleplayer it also happens in singleplayer.

**Comment by aidancbrady** [comment]
Fixed, once and for all.  Thanks.
