### ISSUE TITLE
[1.9.4 - Build 61] - Waila Incompatibility

### ISSUE THREAD

**Issue by addrever** [aidancbrady/Mekanism#3444]
Waila shows enrichment chamber for all machines.
![2016-07-05_22 24 11](https://cloud.githubusercontent.com/assets/190461/16606274/a81de502-4304-11e6-8dc5-2786d8395eac.png)
Raised issue with waila
https://bitbucket.org/ProfMobius/waila/issues/273/194-showing-incorrect-block-type-mekanism

**Comment by aidancbrady** [comment]
On Waila's end, not mine.
