### ISSUE TITLE
[Feature Suggestion] Laser Amplifier with Redstone Comparator support?

### ISSUE THREAD

**Issue by mariodk** [aidancbrady/Mekanism#3446]
![laser](https://cloud.githubusercontent.com/assets/10171517/16621898/30ab2fcc-4398-11e6-8310-4934365f3399.png)

im sure im not the only one who needs some form of redstone output when the front laser amplifier is Full so i can shut down power for lasers via redstone signel automatic

**Comment by aidancbrady** [comment]
Already been suggested :)
