### ISSUE TITLE
[1.9.4] Broken recipe

### ISSUE THREAD

**Issue by FiveEYZ** [aidancbrady/Mekanism#3448]
Compiled on 2016-07-07
forge-1.9.4-12.17.0.1976:

unable to craft a Crusher,

Can see the recipe inside jei and use the [+] to get the items in to the crafting table, but the crusher wont get crafted.

**Comment by natandestroyer** [comment]
Same on 1.10 version

**Comment by Xiaminou** [comment]
![2016-07-08_00 21 22](https://cloud.githubusercontent.com/assets/8670392/16671827/17328738-44a2-11e6-8ac5-b87d605d2d2a.png)

**Comment by DnTheMn** [comment]
you are aware that 1.9 and 1.10 are dev build's just saying

**Comment by FiveEYZ** [comment]
so you say i shouldn't have made an issue? @DnTheMn

**Comment by Carrots4U** [comment]
@DnTheMn We know they are dev builds, and they have bugs that the developer might not know of, so it's best to report them just in case.

**Comment by aidancbrady** [comment]
Fixed! Appreciate it
