### ISSUE TITLE
[1.7.10] Industrial turbine issue

### ISSUE THREAD

**Issue by jznomoney** [aidancbrady/Mekanism#3450]
When restarting my server my industrial turbine looks like this.

![2016-07-07_08 39 47](https://cloud.githubusercontent.com/assets/381979/16653604/a00c8f32-441f-11e6-9f13-3f7179e73b89.png)

When I break the turbine are replace it, it looks like this

![2016-07-07_08 39 59](https://cloud.githubusercontent.com/assets/381979/16653630/c1e0ba5c-441f-11e6-8b18-9be7983391bc.png)

The turbine is full upon restart if that helps at all.

Thanks for your continued support.

**Comment by aidancbrady** [comment]
Thanks yeah, this has been reported. Still trying to figure out what the issue is.
