### ISSUE TITLE
Ethlyene in Gas Burning Generators

### ISSUE THREAD

**Issue by Oaurn** [aidancbrady/Mekanism#3453]
I'm not sure if this is intended or not, but Ethylene is producing Huge amounts of power in gas burning generators.   The last time I used Ethylene as power in a Gas Burning Generator, it produced around the same amount as Hydrogen (300 RF/t) but just lasted much longer.

Now it seems to be able to produce at the base fuel usage of 1 at about ~800 RF/t and at full usage of 28 at 7.8K RF/t.  Is this correct?   It might just be me, but this seems like a huge huge jump in power for how easy it is to make the Generator, and how easy it is to make the Ethylene.   

Thanks for reading.

**Comment by aidancbrady** [comment]
Intentional, ethene is supposed to be a very efficient source of energy. You can always change the configs :)

**Comment by Alleluid** [comment]
This might be a stupid question, but where is the setting for how much energy/tick ethylene produces in a gas gen? I see burntime for ethylene in there, but nowhere for how much actual energy it generates per tick.
