### ISSUE TITLE
Steel OreDict inconsistency

### ISSUE THREAD

**Issue by Deathlymad** [aidancbrady/Mekanism#3455]
I noticed that after a server restart the Steel i get from smelting steel dust changes from time to time. Sometimes the result is mekanism steel sometimes the result is TCon steel. normally that is not a problems but it leads to problems while auutocrafting since only one kind of steel is expected.

I am using the modpack Resonant rise 3.4.0.2 it is currently running 9.0.1 (1.7.10) but since the bug persisted from mekanism 8 onwards i will report it anyway. (and because i did not see anything in the changelog concerning this issue.)
There are no errors in the Log.
The steel has been smelted using the Smelting factory.

**Comment by aidancbrady** [comment]
This isn't mine or TC's fault.  Use Mekanism's Oredictionificator to sort out issues like this.

**Comment by Deathlymad** [comment]
Okay thanks. also if the steel turned into railcraft steel today? (maybe my server just feels fancy ^^)
