### ISSUE TITLE
Displaying RF changes back to MJ after re-log/server restart

### ISSUE THREAD

**Issue by Hazmatik** [aidancbrady/Mekanism#3456]
I change the machines to display their energy in RF by clicking in the GUI, after I re-log or the server restarts they are back to displaying it in MJ. Is there still a config option to have them default to RF or another way to have them keep displaying in the selected energy type after a re-log/restart?

**Comment by aidancbrady** [comment]
This is technically intentional and therefore doesn't classify as an issue, but I may change this in the future. If you want to hard-set an energy type, use the config GUI.
