### ISSUE TITLE
[CRASH] Unboxing a Cardboard Boxed OpenComputers computer that was powered crashes server!

### ISSUE THREAD

**Issue by Techokami** [aidancbrady/Mekanism#3457]
Steps to reproduce:
0) Make sure you got Mekanism and OpenComputers installed. (Tested on 1.7.10)
1) Place and put together a working computer setup. At minimum you need a case (containing a CPU, some RAM, a hard drive, a graphics card, and a Lua BIOS EEPROM), a screen, and a keyboard. You also need an OS from an OS install floppy disk, which depending on the tier of case, will either require a disk drive block (Tier 1 and 2), or the disk can be placed inside the computer case GUI (Tier 3). Turn the computer on from the case GUI, use the screen with attached keyboard to use the computer; type 'install' at the prompt and press enter, then follow on-screen instructions to install the OS to the hard drive. After installation, make sure to reboot and remove the install media! But leave the computer on.
2) Use a Cardboard Box on the running computer case.
3) Collect Cardboard Box.
4) Place box back where it was.
5) Open the box.
6) ???
7) Client code on server!

CRASH LOG: http://pastebin.com/E0Vv9vnp

Crosspost on OpenComputers issue tracker: MightyPirates/OpenComputers#1941

**Comment by aidancbrady** [comment]
Does not appear to be on my end, let me know if it's found otherwise.
