### ISSUE TITLE
[1.7.10] Crash when updating to lastest Mekanism (EnderIO Fluid conduit against a Mek turbine)

### ISSUE THREAD

**Issue by b0bst3r** [aidancbrady/Mekanism#3458]
Updating to Mekanism-1.7.10-9.0.3.278

Ender IO fluid pipe inputting steam into the turbine.

http://pastebin.com/piG2hhJX

Fixed by:
Taking out the turbine valve before updating then replacing after the update.

Did the problem appear in single player or on a server? - Server

https://github.com/BevoTechPack/BevoTechPack/issues/1020

**Comment by aidancbrady** [comment]
Fixed in dev.

**Comment by b0bst3r** [comment]
Hi Aidan, any chance of a release for this as it's not just down to the udpate but this happens everytime the server is restarted.
