### ISSUE TITLE
[1.10] can't break the digital miner?

### ISSUE THREAD

**Issue by natandestroyer** [aidancbrady/Mekanism#3459]
Using the 9.1.0 version. 
Acording to WAILA it is composed of "bounding blocks" which simply replace themselves once broken.
Sorry if this was fixed already but I didn't see anything about this

**Comment by Alleluid** [comment]
Yup, same issue, it also happens with the other multi block machines. You can pick it up with a configurator set to wrench mode for now.

**Comment by aidancbrady** [comment]
Fixed!
