### ISSUE TITLE
Logistical Transporters connecting and routing items through Chisels and Bits.

### ISSUE THREAD

**Issue by Alleluid** [aidancbrady/Mekanism#3461]
http://i.imgur.com/D96wKsl.png

**Comment by Ramireztime** [comment]
The way it works, it doesn't actually "cover" cables or pipes, instead it renders the "pixels" over the them. I'm not sure if it's something with MCMultipart or Mekanism, but I just thought I'd also point out that it happens to other pipes/cables.

**Comment by aidancbrady** [comment]
Mekanism does not currently support Chisel & Bits. Perhaps I'll add support in the future.
