### ISSUE TITLE
Add config option to disable the security features

### ISSUE THREAD

**Issue by Ricket** [aidancbrady/Mekanism#3462]
I would like the ability to disable the ownership/security features via the config file. Our server is myself and a couple friends, and we share everything, there's no concept or need for ownership.

**Comment by aidancbrady** [comment]
By default all machines are all set to public, meaning all other players can break, access, and utilize the machinery.  Assuming both of you are operators, there's a config option to allow ops to bypass security.  I'm afraid it'd be too much work to totally disable security.

**Comment by gitgud-software** [comment]
This is a perfectly valid feature request, especially for servers that subscribe to near or total anarchy in regards to gameplay rules. The feature should have been considered opt-in in the first place, instead of mandatory. At least pin it as a Milestone? I'm sure somebody will take a stab at it.

**Comment by Ricket** [comment]
I think this is added by commit fadbb16a8613caa4e9189021ac87e485102b455f.
