### ISSUE TITLE
Translation: The risk of using compounding strings

### ISSUE THREAD

**Issue by EzerArch** [aidancbrady/Mekanism#3464]
What if, in your language, you right-click a machine and the dialog title says "Factory Injecting Basic"? Weird, isn't it? This is equivalent of what I get when I open the Basic Injecting Factory in Portuguese.

If you translate that name, word by word **in the same order**, I get something saying like "Basic (that is) injecting (a) factory", because Romanic languages (PT, ES, FR, IT etc) prefer to put adjectives (qualifiers) after the noun, the opposite of English-like languages.

The plastic blocks and glow panels are the other examples. I read them as "Plastic Blocks Yellow" and "Glow Panel Red". In this case let us translate strings with % format, e.g. "%s Plastic Block" -> "Bloco de Plástico %s", so we can put the %s where it best fits.

**Comment by aidancbrady** [comment]
This support is actually half-implemented by dynamic localization, I just finished it in full for factories.  You can add specific localizations by defining them using the syntax "tile.BasicSmeltingFactory", for example.  The support is added for other compounded block names as well.

**Comment by EzerArch** [comment]
That's good. :)
