### ISSUE TITLE
[Feature Suggestion] Satellite

### ISSUE THREAD

**Issue by citylion** [aidancbrady/Mekanism#3465]
**Local Mod Suggestions**
-Satellites Added To Mekanism
-Satellites Hover At About 250 Blocks High and are entitys
-Satellites can have many uses as; Collecting Power, Housing Storage, (See inter mod compatibily)
-Satellites can be remotely Docked so you can edit blocks
-You can view/control your satellites actions with a satellite control station
-Satellites have frequencys you use to connect to them
  -You can add a module to your satellite that makes them password protected.
  -Satellites without a password protection module can be hacked into.
**Intermod compatibality**
  -Such as satellites can transmit Computercraft Lua when CC is detected
  -Satellites can shoot down missles when Defense Tech Is detected.
  -Satellites can show you a bigger radius of radar when Defense Tech/Mc heli is Detected.
    (Shows Mcheli planes ect)
  -Satellites can drill into the earth when Defense Tech Is Detected

**Comment by citylion** [comment]
**Local Mod Suggestions**
   -Satellites Added To Mekanism
     -Satellites Hover At About 250 Blocks High and are entitys
     -Satellites can have many uses as; Collecting Power, Housing Storage, (See inter mod compatibily)

     -Satellites can be remotely Docked so you can edit blocks
     -You can view/control your satellites actions with a satellite control station
     -Satellites have frequencys you use to connect to them
         -You can add a module to your satellite that makes them password protected.
         -Satellites without a password protection module can be hacked into.
       
      -Satellites have **intermod compatibality**   
             -Such as satellites can transmit Computercraft Lua when CC is detected
             -Satellites can shoot down missles when Defense Tech Is detected.
             -Satellites can show you a bigger radius of radar when Defense Tech/Mc heli is Detected.
                    (Shows Mcheli planes ect)
             -Satellites can drill into the earth when Defense Tech Is Detected

**Comment by aidancbrady** [comment]
If I added something like this it would be implemented in DefenseTech.  Would you mind posting this there?
