### ISSUE TITLE
no way for digital miner to pull items?

### ISSUE THREAD

**Issue by SniperHauss89** [aidancbrady/Mekanism#3466]
Hello, I was just curious if I'm missing something with Mekanism v9 regarding the digital miners (btw they look great! ;)). So it seems like there is no way currently to pull in items to fill up the holes created by it when mining. Yes there is the pull option toggle in the GUI for the digital miner but as far as I can tell there is no way to have it pull in items since there is only one item port which is for ejecting mined ores and such. the other three ports are for power and the top is solid although in the previous versions that is where the pull port was located. 

Mekanism 9.0.3.278

**Comment by aidancbrady** [comment]
This is actually more of a texture issue than a bug- the port is still in the same place as before. I'll see about adding a visual port on top.

**Comment by SniperHauss89** [comment]
Oh ok thanks for the input ;) although I did set a vanilla chest on top and turn pull on to try to replicate that function as if there was a visual port and it didn't want to pull... I then tried an ultimate logistical transporter and even set it to pull with the configurator and still nothing...

**Comment by aidancbrady** [comment]
Fixed!

As for your sound issue, that's been in my tracker for a while. There's not much I can do on my end I'm afraid.
