### ISSUE TITLE
[Suggestion] Chemical Dissolution Chamber Factory

### ISSUE THREAD

**Issue by phill3** [aidancbrady/Mekanism#3469]
Chemical Dissolution Chambers are required for 5x ore processing, which means 5x is always going to be a lot slower than 4x, since there are no factories for the 5x required machines. Factories for the chemical dissolution chamber would be nice, allowing 5x ore processing to keep up with 4x in speed. Since the chamber can only do 1 ore at a time, 5x ore processing isn't practical at all. A factory for this machine would make 5x more viable and more worth it.

**Comment by aidancbrady** [comment]
I currently do not have plans to add "factory" versions of 5x processing, at least for now.  This may change in the near future, but 5x is meant to be a bit slower as to be squeezing every last bit of resource out of ores.
