### ISSUE TITLE
Add compatibilty for TechReborn's implementation of EU

### ISSUE THREAD

**Issue by utoc** [aidancbrady/Mekanism#3471]
Hello!

I understand that universal cables are compatible with IC2's EU but they don't seem to work with TechReborn's EU. I'm testing this with Mek 1.10-9.1.0

Screenshot can be seen here: http://i.imgur.com/feLfCr1.png

Their curseforge: http://minecraft.curseforge.com/projects/techreborn

Their repo: https://github.com/TechReborn/TechReborn/tree/1.10

Please let me know if I've neglected any important information

**Comment by aidancbrady** [comment]
I'm going to stick with IC2's still-maintained API for now.  Perhaps I'll add support for TechReborn later if necessary.
