### ISSUE TITLE
[1.10.2] Cardboard Box deletes inventory of Quark Chests

### ISSUE THREAD

**Issue by Carrots4U** [aidancbrady/Mekanism#3472]
Using a Mekanism Cardboard Box to pickup Quark chests deletes the entire inventory of the chest and turns the texture of the chest into this when placed, https://i.gyazo.com/a3cbc105aa0967736247c29d74bfed48.png

**Comment by aidancbrady** [comment]
This is an example of something you should use the Box Blacklist for.  I'm afraid I don't have enough time to add compatibility for all unique mod blocks.
