### ISSUE TITLE
Crashing due to tank things

### ISSUE THREAD

**Issue by Rukia1727** [aidancbrady/Mekanism#3473]
Idk know the name of these thigns but they are like ultimate liquid tanks but they crash my game when I'm just in the Mekanism tab scrolling through. I am very irate as the current version makes the Project Ozone modpack pretty damn easy but I cannot do anything if I search for "Mekanism" in the NEI tab and it just crashes because of the tank thingies rendering. PLEASE someone tell me why the fuck this is happening because it has happened before and I will have to go to an earlier version before these stupid things were added so if anyone knows what is going on please tell me (I've had this happen to me before, like just using this and a few other tech mods and the ultimate tank thingies do seem to be the cause of the problem, and it is seeing it in the creative or NEI menu which crashes the game, causing it to go slow. My PC is a fairly decent non-clunky potatoe pc so I do not know why this would crash the game).

**Comment by aidancbrady** [comment]
Set PrefilledPortableTanks to false
