### ISSUE TITLE
Game crashes on fresh install

### ISSUE THREAD

**Issue by Munky33** [aidancbrady/Mekanism#3477]
I can't seem to play on 1.9 or 1.9.4 with the Mekanism mods from the official download page and forge. The game loads vanilla and with forge installed, but as soon as I add the Mekanism files to the /mods folder the launcher is as far as I can get, I do not even get as far as the Mojang splash screen.

**Comment by aidancbrady** [comment]
Mekanism does not currently have a supported release available for 1.9.4.  However, I'm getting close to the final stages of development; I promise you can expect a release soon :)

**Comment by Munky33** [comment]
It does work with 1.9 though, right? I can't get that to work, either.
