### ISSUE TITLE
(Suggestion) Gas-Burning Generator Light Updates

### ISSUE THREAD

**Issue by mattfreyer** [aidancbrady/Mekanism#3478]
I noticed that in the Mekanism 9.X.X for 1.7.10 the Gas-Burning Generator creates a ton of light updates if you let it continually run out and fill it slightly. It does create a bit of fps lag constantly doing light updates every two seconds. I was wondering if there could be a config option to disable it from creating light. Just my two cents.
        

Sincerely Matt

**Comment by aidancbrady** [comment]
MachineEffects can be tweaked, as well as UpdateDelay in the config to prevent continuous updates.
