### ISSUE TITLE
Hydrogen Generator Lag

### ISSUE THREAD

**Issue by etpof** [aidancbrady/Mekanism#3479]
This issue was probably solved a while ago, but I was wondering where the MachineEffects property in the Mekanism config was. I need to turn it off because I read that it decreases lighting lag caused by generators (specifically Hydrogen Generators in this case). I believe I'm running a much older version (questions about older versions are allowed here, right?) because I'm playing through the Voltz modpack from the Technic Launcher. What would be the best way to decrease the generator's lag, assuming MachineEffects wasn't an setting in this version's config file? Thanks!

**Comment by aidancbrady** [comment]
Increasing the value of UpdateDelay will prevent multiple updates from happening too quickly :)

**Comment by etpof** [comment]
Thanks! That was another solution I saw. But I couldn't find UpdateDelay either. Is it in the config?
