### ISSUE TITLE
Can't make water vapor... rotary condensentrator can't be crafted and/or does not exist but 5x ore processing exists?

### ISSUE THREAD

**Issue by SwagMelon7** [aidancbrady/Mekanism#3480]
I really want to start 5x ore processing in my Survival world, but apparently you cannot make a rotary condensentrator to make water vapor required for sulfuric acid, a vital substance in the process. It says in NEI that you can make water vapor Please either update Mekanism to include the rotary condensentrator again, or help find another way to make water vapor.

**Comment by aidancbrady** [comment]
Somethings up with your mod installation, make sure nothing is interfering with the recipe.
