### ISSUE TITLE
Two Questions

### ISSUE THREAD

**Issue by chaos234** [aidancbrady/Mekanism#3484]
Refering to issue #2988 the last post von @aidancbrady was if someone can create it as an own mod.

My question now is, if the changes which I have made are actually usable or are they no longer useable?
I looked the new guide for Meka 9 but it was not a fully detailed guide so I dunno if this works because I have seen that the SEP was/seem to be removed.

It will be glad to if someone can introduce me a bit.

Secound one is the problem with the FPS if pipes are not opaque. Was this included or is there actually no opaque option included? Punch me if I have overseen it in the config.

**Comment by aidancbrady** [comment]
Yes, the changes you made are still totally usable!  As mentioned before, I'm in full support of you releasing this as your own independent mod.

And no, I never added opaque pipes; not enough time on my end.  Perhaps I will in the future.

**Comment by chaos234** [comment]
Thanks for your response. But can you then please let this open and lable it with smth. like "external Plugin/Mod/Addon" ?

Well, then I'll first help with the opaque option and then I'll do the other plugin :).
