### ISSUE TITLE
[Suggestion] Upgradable Solar Neutron Activator

### ISSUE THREAD

**Issue by condensedapple** [aidancbrady/Mekanism#3487]
So, for large reactors, you need A LOT of solar neutron activators (in need 160 SNAs for my fusion reactor with 50 injection rate). This seems rather tedious and unnecessary (huge amount of tileentities), what about upgrades for solar neutron activators or even a new more powerful multiblock structure for this purpose?

**Comment by gp009** [comment]
i would vote for the multi-block version.

**Comment by mimikal** [comment]
Me too, but as long as it is expensive.

**Comment by aidancbrady** [comment]
Solar Neutron Activators can now be upgraded in the same way as other machines.

I do like the idea of a multiblock version, though. You can expect something like that soon!

**Comment by condensedapple** [comment]
Wow, thanks for this quick implementation!

**Comment by ben569** [comment]
I'm glad too. I had ~200 SNAs with watches of passing time in range of each ^^.
