### ISSUE TITLE
Bug: Quantum entagloporter forgetting connection

### ISSUE THREAD

**Issue by EurypteriD192** [aidancbrady/Mekanism#3490]
Every time i reload my game the quantum entagloporters will not connect to mechanical pipes and power cables.
To restore the operation you got to create a new channel on both and then it works.

Im running 1.7.10-9.0.3.278

**Comment by aidancbrady** [comment]
Fixed in dev

**Comment by EurypteriD192** [comment]
Awesome. keep up the good work :)
