### ISSUE TITLE
Mekanism Wind Generators causing severe server lag (even overloads) when a player is near them

### ISSUE THREAD

**Issue by Campiotti** [aidancbrady/Mekanism#3494]
Whenever I get really close to my Mekanism Windgenerators the server CPU and RAM increase exponentially... especially the CPU. 
I host my server on a site wich hosts deticated servers, my server has 8gb RAM but idk about the cpu, though it never was any issue at any other given times.

(There are about 100 +/- wind generators)

So my Windmills are at y 253 or 252 so the top block is max height (256)... Whenever I got near them (under them at like 100 is my base) wich means flying up to them, the server as said almost crashes and in some cases give my a java.io exeption error and kicks me with it (overload of cpu).

One very important thing to add though... I doubled the energy production, output & input with pretty much all mekanism generators, haven't changed much else though. 
The wind generators are really fast and I think that might also contribute to that issue

Server config file to the attachments.     (file changed to .txt to support upload)

[Mekanism.txt](https://github.com/aidancbrady/Mekanism/files/367481/Mekanism.txt)

Hope you can help me out Thanks!

**Comment by aidancbrady** [comment]
Thanks. I haven't looked at the Wind Generator code in a long time, it turns out I was performing an upwards ray trace every render tick- very bad.  Should be taken care of now :)

**Comment by Campiotti** [comment]
So is this fixed in the Mekanism-1.7.10-9.1.0.280.jar version? Please reply as soon as you see this, thanks!
#DigitalMiner2016

**Comment by aidancbrady** [comment]
Indeed :)

**Comment by Campiotti** [comment]
omg... that's hell of a fast reply :clap: :tophat: 
Thanks! gonna update my server & client to those right now!

**Comment by Campiotti** [comment]
One last question... Configs aren't changed / reset (or don't have to be) right?

**Comment by aidancbrady** [comment]
Nope. Let me know how things work out.

**Comment by Campiotti** [comment]
Oh though finally... the hopefully actual last question... Do i put the MDK.zip folder in my mods folder or export the mekanism folder with api in it?

**Comment by Campiotti** [comment]
oh
I just realized that that's what i was reading on the download site before... my bad xI
