### ISSUE TITLE
Electrolytic Separator speed upgrade bug

### ISSUE THREAD

**Issue by Rayder44** [aidancbrady/Mekanism#3498]
I believe there is a bug with the electrolytic separator's processing rate with speed upgrades.

The machine seems to operate as expected with all speed upgrades, with one exception. Upgrades one through seven (being x2 to x128) operate as expected. The bug seems to be that upgrade #8 (x256) has no effect. The output rate does not appear to change by adding an 8th speed upgrade.

Testing fluid is Heavy Water, being pumped in from a creative tank from Thermal Expansion. I don't believe there is a throughput limitation for the tank.

Transfer pipe is an Ultimate Mechanical Pipe, which according to the game can pump at 6,400 mB/t. It is my understanding that this is more than fast enough to feed the machine. I've also tried using a pump from 'Pressure Pipes' and a Super-Laminar Fluiduct from Thermal Dynamics. This setup is theoretically unlimited so I don't believe there is a throughput issue here.

Measurement was taken using an ultimate pressurised tube into an ultimate gas tank to measure the output gas. The tube has a pump rate of 4,096 mB/t so I do not believe there is a throughput limit here.

I've set the gas tank to dump, to keep the level at zero. I've then started measurement by setting the tank to idle, thus starting to fill the tank. Using 7 speed upgrades, I've measured the gas tank at 307,200 Deuterium after 1 minute. Reset by dumping the tank. After adding an 8th upgrade, the tank again reads 307,200 Deuterium after one minute.

Power is provided using a Creative Energy Cell from Thermal Expansion. I do not believe there is a power delivery issue.

I'm unsure if this issue carries over to other machines (Untested).

**Comment by aidancbrady** [comment]
Fixed, thanks!
