### ISSUE TITLE
Digital miner's silk touch in nether not working?

### ISSUE THREAD

**Issue by RalphFox** [aidancbrady/Mekanism#3499]
Hello, i'm using a filter of *ore* in digital miner in the nether; If silk tough is disabled, i can successfully use it, but if i enable the silk touch it simply hangs up:

Gui "*ore*"
![gui *ore*](http://i.imgur.com/AjbwB6f.png)

Gui showing ores to mine but there is no "hello world" in the miner's screen
![gui showing ores to mine but there is no "hello world"](http://i.imgur.com/ihHeOWt.jpg)

It does show the nether ores, and is able to collect all the ores in *ore* without having silk touch enabled, but if i enable the silk touch, the digital miner does not work;

Context: i'm trying to harvest draconium and ammonium chloride , these two are the only ones that when mined does not drop their ores; instead they drop their resources; all the rest drops as ore.

Waila shows the oredict for draconium(draconic evolution)(oreDraconium) and for ammonium chloride(rotarycraft)(oreAmmonium), i tried the names as well to no avail;

Mekanism 9.0.3

here's more info, a gif is worth more than 1kk words:

http://g.recordit.co/mbYNBayWjO.gif

http://g.recordit.co/pYj7C8h5rk.gif

**Comment by RalphFox** [comment]
here more info, an gif is worth more than 1000k words:

![gif](http://g.recordit.co/mbYNBayWjO.gif)

**Comment by aidancbrady** [comment]
Just did some testing. Using Mekanism v9.0.3 and a pretty big list of mods, silk touch behavior was working just fine in the nether. I wasn't testing with Draconic Evolution, but I'm confident this isn't on my end.

**Comment by RalphFox** [comment]
I've found the problem. It was the speed upgrades, i had to add a energy upgrade as well; at 5 speed upgrades without energy upgrade and it stops mining; I suggest to add a information where it displays "all is well" in the gui with a green tick and change it to "missing power/power upgrades" and a red cross;
