### ISSUE TITLE
1.10: Attempting to use the Configurator on Pressurized Tubes causes a repeatable crash.

### ISSUE THREAD

**Issue by AnonymousPepper** [aidancbrady/Mekanism#3500]
Crash report, for reference in case it helps pin down the bug. The crash report was substantially the same every time every time I repeated it.

http://pastebin.com/u3pDpE3B

In short, using a charged Configurator to attempt to access and configure Pressurized Tubes of any variety causes an immediate crash to desktop. The Configurator can still be used in wrench mode to remove the tubes, but any attempt to actually access them causes bad juju.

Experienced while using the All the Mods pack v1.4 on the Curse launcher, though it's likely universal (although I haven't checked for certain). It can be replicated on other clients besides my own, that I did verify with a friend.

Was attempting to pull hydrogen gas from an Electrolytic Separator, couldn't in any way get the tubes to hook up to the Separator nor find the configuration for the Separator itself, so, went for my Configurator, and the game crashed out on me.

**Comment by aidancbrady** [comment]
This is due to a mod shipping with an outdated CoFH API. I assure you it's not on my end :)

**Comment by FiveEYZ** [comment]
its the same as this issue https://github.com/aidancbrady/Mekanism/issues/3474
