### ISSUE TITLE
Configuration card works on private machines that is owned by another player

### ISSUE THREAD

**Issue by Stekeblad** [aidancbrady/Mekanism#3501]
After finding a item called configuration card I decided to try it out, after some testing I found that I can "paste" a configuration to a machine that is set to private and is owned by another player, that sounds wrong. If I try to open a machine it tells me I don't have access.

I tried this on a server with Mekanism 9.0.2 and I am op on the server.

**Comment by aidancbrady** [comment]
Fixed, thanks. Definitely not intentional :)
