### ISSUE TITLE
Urgent, hard crash on server and I had to reload from backup.

### ISSUE THREAD

**Issue by Harrison1249** [aidancbrady/Mekanism#3505]
I connected a basic fluid pipe onto the side of an ender tank from EnderTanks-1.10.0-1.4.1; I am using Mekanism version MekanismAll-1.10.2-9.1.0homebaked-01 from all the mods. I assume this is just a compiling of all the mekanism things. I am playing on the All The Mods pack v1.4. The crash log is here

http://pastebin.com/LQ0FPHSd

**Comment by aidancbrady** [comment]
Added a null check, will be pushing a fix soon.
