### ISSUE TITLE
Teleporter missing texture

### ISSUE THREAD

**Issue by TehStoneMan** [aidancbrady/Mekanism#3507]
Version 1.10.2-9.1.0.287
Teleporter base block appears to have a missing texture.

**Comment by aidancbrady** [comment]
Strange, it appears fine for me, both in testing and in release builds. Make sure there's no resource pack conflicts.

**Comment by TehStoneMan** [comment]
![2016-07-21_09 24 27](https://cloud.githubusercontent.com/assets/5953163/17006631/7e57e858-4f25-11e6-8a89-d50edb554d86.png)

After a bit of experimenting, I found by renaming the texture files "Teleporter-ctm.png" and "Teleporter.png" within the jar itself to "teleporter-ctm.png" and "teleporter.png" (note capitalisation), it works as intended.

**Comment by aidancbrady** [comment]
Huh, thanks. I'll reopen to remind myself to change that.

**Comment by aidancbrady** [comment]
Fixed!
