### ISSUE TITLE
Feature Request:Fortune Upgrade.

### ISSUE THREAD

**Issue by blockbreaker1361** [aidancbrady/Mekanism#3508]
How about adding a fortune upgrade for the Digital Miner. It would only accept 3 (Fortune 3). While they are installed, of course, you cannot use silk touch mode. It would be useful when mining for redstone, lapis, diamonds, emeralds or any other gems from other mods. They would also require more power to run with them installed.

**Comment by laz2727** [comment]
Why?

**Comment by blockbreaker1361** [comment]
Isn't it obvious? FORTUNE 3. FailFish

**Comment by Rayder44** [comment]
I think the advantage of retrieving the ore so conveniently far outweighs the need for fortune. Consider it as a balancing mechanism.

Need more ores? Relocate the miner.

**Comment by laz2727** [comment]
You don't need to fortune anything. Only Draconium gives more resources per
block when fortuned.

**Comment by blockbreaker1361** [comment]
Fortune affects everything that I listed above. I've been playing Minecraft since Alpha days and it has always been the same.

**Comment by laz2727** [comment]
Yes, but you can use any crusher and it'll literally give more.

**Comment by blockbreaker1361** [comment]
OK. I'm not going to get into a heated discussion over it.
