### ISSUE TITLE
Logistical sorter places down but also has a phantom copy.

### ISSUE THREAD

**Issue by RyanP1991** [aidancbrady/Mekanism#3509]
Forge Version - 

12.18.1.2014

Mod Version: - 

Mekanism - 9.1.0.287
Mekanism Generators - 9.1.0.287
Mekanism Tools - 9.1.0.287

When placing the logistical sorter down it will place down correctly but also renders a copy next to it but isnt technically there as in you can interact with it / you can still walk through it and build on that block but it looks like another logistical sorter is placed down. When breaking the original both blocks disappear only giving the original version back.

**Comment by aidancbrady** [comment]
Fixed in development, thanks!
