### ISSUE TITLE
Server CPU & RAM overload (=timed out) when going near wind generators

### ISSUE THREAD

**Issue by Campiotti** [aidancbrady/Mekanism#3510]
Yesterday in the new version .280 version supposedly fixed... seemingly still causing lots of lag.
So I updated the Mek. version to the newest scince you said the wind generator code was outdated and had a bad code line in it causing it to do something every tick... Now it happened again...

The server heald a little longer before completle overloading the 6gb Ram and using the Cpu at 94%
It caused me a timed out message when going up to my windmills (y=max lvl),
Please take a closer look at the wind generator code, it caused my server to overload even on the newest version (280 right?) ^^ thanks!

**Comment by Campiotti** [comment]
Actually something else to add... ( I DON'T KNOW IF THIS WAS SERVER-SIDED SOFTWARE ISSUE OR MEKANISM'S FAULT)
The RAM ussage didn't go down (was on 100%) after I went to the wind generators, even When I had a decent distance from them (100+Blocks) (not rendering the animation anymore) the RAM still didn't go down, I had to restart the server to make it normal again, the CPU ussage was behaving abnormally a bit but generally also staying higher than normal and not going down really untill I restarted the server.

**Comment by b0bst3r** [comment]
Try .282 since they were changed I think after.

**Comment by Campiotti** [comment]
ok thanks I'll try that!

**Comment by b0bst3r** [comment]
As a matter of interest how many windmills do you have up there?

**Comment by aidancbrady** [comment]
I've done about all I can do to eliminate this issue, at this point it's just a matter of how many Wind Generators you have.  With 100 of any type of Tile Entity you'll run into similar problems.
