### ISSUE TITLE
[1.10] World regen not genning osmium

### ISSUE THREAD

**Issue by elkillo** [aidancbrady/Mekanism#3513]
so i was super excited to see meka finally on 1.10 so i added it to my existing world only to find out that osmium wont spawn in existing chucks. so i looked in the config and sure enough a world regen option was available so i set it to true but nothing happened. no osmium spawned in any of my existing caves/tunnels. am i missing something? if not then the retro gen may be a tad broken

**Comment by b0bst3r** [comment]
Pretty sure that world regen is not retrogen, you'd have to gen new chunks to get Osmium.

**Comment by elkillo** [comment]
If i remember correctly there was a post that stating the opposite and that world regen was like retrogen. If if hat isnt what it does then i would like to know what it does.

**Comment by Rayder44** [comment]
B:EnableWorldRegeneration=false

It's disabled by default. You'll have to set it to true for it to work.

**Comment by elkillo** [comment]
So it turns out you need to find the World regen type option and set it from 0 to 1 as well as set world regen to true for it to work
