### ISSUE TITLE
[1.10.2] Crusher does nothing with Ore

### ISSUE THREAD

**Issue by kwpugh** [aidancbrady/Mekanism#3516]
Tried gold, iron, copper, lead, osmium, etc in ore form, the crusher machine does nothing.

place ingots crushes them into dust, that can be smelted.

Forge 2014
Mods: Mekanism-1.10.2-9.1.0.288.jar
MekanismGenerators-1.10.2-9.1.0.288.jar
MekanismTools-1.10.2-9.1.0.288.jar

**Comment by laz2727** [comment]
That's because there's another machine ores go into.

**Comment by nikkimas** [comment]
You have to put ores in the Enrichment Chamber. The crusher is there to crush ingots etc. not ores

**Comment by kwpugh** [comment]
Derp!  I guess I have been away from 1.7.10 and Mek too long.   Sorry.
