### ISSUE TITLE
Digital Miner not working in ftbutils chunks

### ISSUE THREAD

**Issue by nikkimas** [aidancbrady/Mekanism#3517]
I got my digital miner set up and it didnt work. I tried different positions and found out it can't mine in the protected chunks from ftbutils. Is this intentional, or an error. And if it's an error, is it on your or on ftbutils side?

**Comment by laz2727** [comment]
That's because Mekanism fake player can't mine in these chunks.

**Comment by nikkimas** [comment]
is there a way to allow that?

**Comment by laz2727** [comment]
You can try adding [Mekanism] as a friend, or unprotecting the chunks.

**Comment by nikkimas** [comment]
okay, thank you! Now I just need to figure out that friends system. :)
