### ISSUE TITLE
[1.10.2] Crash on Client startup while Natural Pledge is installed

### ISSUE THREAD

**Issue by ParaMotor** [aidancbrady/Mekanism#3518]
I'm using Minecraft 1.10.2, Forge 12.18.1.2016, Mekanism 9.1.0.288, Botania Unofficial r1.8-313, Natural Pledge r1.1. Client crashes on startup. 

http://pastebin.com/h3L1REbj

**Comment by laz2727** [comment]
Probably Natural Pledge bug.

**Comment by Drock1994** [comment]
i had the same crash but just removed Natural Pledge for now

**Comment by aidancbrady** [comment]
Not on my end.
