### ISSUE TITLE
Digital miner can't accept power from mekanism energy storage items.

### ISSUE THREAD

**Issue by 63502** [aidancbrady/Mekanism#3521]
Crash when placing any power containing object anywhere in digital miner's inventory.

I also can't seem to get it to take in power via external cables of any kind either.

Gist Crash Log:
[https://gist.github.com/63502/704f30457bd7fbefc210a58481776bba](https://gist.github.com/63502/704f30457bd7fbefc210a58481776bba)

**Comment by Rayder44** [comment]
Can you elaborate on your definition of a 'power containing object'? I've tried placing several types of energy cubes into the digital miner and it appears to function as expected (no crash).

What items are you crashing with?

**Comment by 63502** [comment]
I've tried with all energy cubes, an energy tablet, EnderIO capacitor banks, and at one point for some reason, a personal chest(i cant remember if its powered or not, but go with me here). All result in the game crashing. Also, it appears I made a mistake with where the items must be placed for the miner to crash. Only the power input slot in the top right of the interface is affected.

**Comment by 63502** [comment]
I just got a Creative capacitor bank from enderio to input power from the input slot, so it may be that only mekanism power containers cause this crash

**Comment by Rayder44** [comment]
Hmmm... I've tried using multiple energy sources into the digital miner and I just can't seem to replicate your crash.

What mods do you have installed? Are you able to test with just Mekanism installed?

**Comment by 63502** [comment]
All of my minecraft version/mod info is in the crash report in the gist link above, and I may be able to test with just mekanism, but it will take a little bit to set up.

**Comment by aidancbrady** [comment]
Not on my end, another mod is likely shipping with a conflicting API.
