### ISSUE TITLE
Weird UI Bug / Glitches with Latest version.

### ISSUE THREAD

**Issue by Zoidey** [aidancbrady/Mekanism#3523]
Since updating to the latest version I've noticed the UI for the turbine to be bugged. It's no longer outputting / showing how much power is being generated or the flow rate, it just says 0. It's producing power as all my machine etc are still chugging away nicely, AE system still powered up and the internal; buffer refills if I drain it (via recharging a induction energy storage for an example).

Also noticed that my boiler is reaching like over 900k c (not sure if that's normal). The boil rate is like 84mb and it spikes to 111mb for a split second. Not sure if this is normal as I've only just started playing around with the latest version in the past week or so.

I should also mention I'm using the latest version for 1.7.10 (not sure if they'll help much)

**Comment by aidancbrady** [comment]
Reported. Thanks
