### ISSUE TITLE
[1.7.10] Bug on Gui in the Turbine

### ISSUE THREAD

**Issue by CristinoValdigem** [aidancbrady/Mekanism#3524]
I Think i don't type much about the problem i've found... The pictures below explain better

![2016-07-22 1](https://cloud.githubusercontent.com/assets/16420781/17047900/0a52813c-4fb8-11e6-817b-fa96dbd0e596.png)

![2016-07-22 2](https://cloud.githubusercontent.com/assets/16420781/17047905/102d954c-4fb8-11e6-9533-d29b0239c421.png)

**Comment by CristinoValdigem** [comment]
on Mekanism 9.1.0.281 the power generation by turbine and flow rate, don't appear

**Comment by aidancbrady** [comment]
Already reported.
