### ISSUE TITLE
[1.7.10] Shift-click upgrade on solar neutron activator

### ISSUE THREAD

**Issue by jznomoney** [aidancbrady/Mekanism#3525]
I am not sure if this is a bug or not,  I can only shift-click upgrade the solar neutron activator from the base not the top part with the solar panel.

**Comment by Rayder44** [comment]
This could just be an issue with the way the game handles objects that are a single entity, but sit within more than one block space. Similar to how the Digital Miner works.

By the way, I'm at a loss to find any information on this "upgrade" for the SNA. I've seen it listed somewhere else as well. Could you elaborate? Is it in a beta update?

**Comment by condensedapple** [comment]
see #3487
