### ISSUE TITLE
Vanishing brine in evaporation towers

### ISSUE THREAD

**Issue by kythorn** [aidancbrady/Mekanism#3527]
This is for Mekanism 9.0.3.277 / MC 1.7.10.

I have two max height evaporation towers for my reactor setup that I'm trying to scale up. The brine one is producing 300mb/tick and the lithium one is producing 30mb/tick as expected feeding into a typical 1x decondenstrator / 7x SNA (un-upgraded) / Reactor setup.

By my understanding I should be dramatically overproducing both brine and lithium for my current rate 2 reactor, but I'm not building up a backlog of brine at all. I'm making 300mb/tick, 300mb/tick is going into the lithium producing tower, and 30 mb/tick of lithium is flowing out consistently.

The SNAs, decondenstrator, and all pipes "downstream" of the lithium tower are 100% full. However the brine tower is perpetually empty (as is the pipe connecting the two towers). I'm not aware of any other possible destinations for the lithium/brine on this network. I have eliminated the use of all other mods in this setup trying to troubleshoot, only Mekanism pipes are being used, etc.

**Comment by Rayder44** [comment]
I'm not sure I entirely understand your question...

The Lithium tower converts Brine into Lithium at a rate of 10:1, so it takes in 300mb of Brine and converts it into 30mb of Lithium.

Knowing this, you will require 10 full-size Brine towers (3,000mb) to match the Lithium tower, in order to produce 300mb of Lithium.

The other thing could be the Lithium might be stored in the pipes themselves, as they have their own storage capacity.

**Comment by aidancbrady** [comment]
Not an issue. There's a 1/10 ratio from brine to lithium.

**Comment by kythorn** [comment]
Hello Aidan,

I am sorry if I explained it poorly, but I think you misunderstood the situation I am experiencing. 

The lithium tower and everything "past" it is completely full. The buffers on the pipes are full, the machines are full, and the tower is full. There is nowhere on my network for 30 mb/tick to go (I was trying to ramp up).

The issue is that the full 300 mb/tick of brine keeps getting consumed. I suspect what is happening is that the lithium tower is converting all of the bring to lithium per tick, and the excess is being lost/discarded somewhere. Is that intentional? My expectation is that both towers would have built up a backlog of brine.

**Comment by aidancbrady** [comment]
I've looked into the issue again and it turns out I had forgotten to scale the production to the amount needed. Should be fixed now :)
