### ISSUE TITLE
Turbine issue

### ISSUE THREAD

**Issue by blackice125** [aidancbrady/Mekanism#3528]
the turbine on our server filled up our battery over night, and then the reactor and turbine internal energy storage both maxed out.

when u highlight over the turbine value you see values for the steam but rf is some negative number

our battery now is draining, reactor is outputting power but the steam turbine looks stuck/bugged and wont come back to life won't drain power etc.

Our battery has room to accept power  

![turbine_shot1](https://cloud.githubusercontent.com/assets/13007943/17079116/7df6b73a-50d4-11e6-9f14-ba01ad6111ac.png)
![turbine_shot2](https://cloud.githubusercontent.com/assets/13007943/17079117/8169c740-50d4-11e6-9b8f-622cf4ef5c66.png)
![reactor_shot1](https://cloud.githubusercontent.com/assets/13007943/17079118/8380a800-50d4-11e6-8419-ac3fbb9e6867.png)
![bat_shot1](https://cloud.githubusercontent.com/assets/13007943/17079206/fa8b64a6-50d6-11e6-8c52-feb5e18f3fe8.png)

I was able to get it to come back to life,  but I had to op and use a creative empty cell to drain the internal turbine bat and all stored steam.

rf info still negative on display, but working

**Comment by aidancbrady** [comment]
This issue is due to the massive amounts of energy capable of being stored in the turbine, as well as another issue I still have not been able to solve. The latter is being worked on :)

**Comment by blackice125** [comment]
ok, 

thanks for the update.
