### ISSUE TITLE
Mekanism

### ISSUE THREAD

**Issue by StarfireSky** [aidancbrady/Mekanism#3533]
I try to use your mod Mekanism with my mod pack and when I put it in with the forge Multipart mod in my game will not load the map it just sits there and just say loading world but when I take out Mekanism and the forge multipart mods the map loads just fine. It does not crash so I don't get a crash report all it does is sits at loading world and then goes back to the main menu where it shows singleplayer and multiplayer and that is where it sits and does not go any further. What do I do.

**Comment by CristinoValdigem** [comment]
U can try delete your folder config and make a copy of your world and try to enter on a map copy

**Comment by aidancbrady** [comment]
Yeah, not much I can do about issues like this
