### ISSUE TITLE
purification chamber induces lag spike when turning on/off

### ISSUE THREAD

**Issue by adelayde** [aidancbrady/Mekanism#3535]
If the purification chamber isn't being fed as fast as it processes, it flips on and off as input comes in.  This transition always induces a lag spike.  In my survival world, this is on the order of hundreds of milliseconds during which the game freezes.

In a new creative flatworld with nothing but a simple tier 2 chain and a timer set up to turn the chamber on and off via redstone every second, I still see this spike, although much less severe.  The game visually stutters whenever the machine changes state, and the F3 graph shows a clear lag spike.

I haven't tested whether other machines have this problem.

This seems to occur with the default config, and also after disabling these:

`B:CTMRenderer=false`
`B:EnableAmbientLighting=false`
`B:EnableMachineSounds=false`
`B:EnablePlayerSounds=false`
`B:MachineEffects=false`
`B:OpaqueTransmitterRender=false`

**Comment by adelayde** [comment]
Interestingly, at a distance of about 30-35 blocks, the stutter disappears.

**Comment by aidancbrady** [comment]
Try and increase the value of UpdateDelay. It will determine how quickly a machine can transition from its on to off state and vice versa.
