### ISSUE TITLE
lag when building multi-block structures

### ISSUE THREAD

**Issue by adelayde** [aidancbrady/Mekanism#3537]
When building the thermal evap tower or boiler, for instance, the game experiences lag proportional to the size of the structure when placing/destroying blocks nearby, reaching hundreds of millis per update for full-sized structures.

This makes building anywhere near the structure very painful.

I've noticed the area experiencing update lag extends out to a certain range into the world, beyond which blocks can be placed lag free.  A 5x5 test boiler in a new flatworld requires me to stay 12 blocks away in order to avoid block placement lag.  Maybe that depends on chunk boundaries or other particulars... not sure.

I assume it's the multi-block is doing validity testing?  I wonder if it could employ an incremental test that spans ticks to avoid single-tick lag?  Obviously speaking from ignorance here...

**Comment by adelayde** [comment]
Hmmm... it DOES seem to align to chunks.

**Comment by adelayde** [comment]
F3 shows gameRenderer.level.terrain_setup.rebuildNear spiking rapidly when I start spamming blocks in the same chunk as a multiblock.

Ditto for any other chunk, but to nowhere near the same degree.

**Comment by adelayde** [comment]
Mapped out the laggy region... it's 18x18.  So not chunks, but not-so-coincidentally the max multiblock size.

**Comment by adelayde** [comment]
It *appears* to be in the CTM engine.  There's a CTMRenderer config flag, but it seems it no longer has any effect?  Looks like non-CTM code was ripped out in May.

**Comment by Utildayael** [comment]
FWIW I have the exact same issue. Glad it isn't just me. If I move away from my Mekanism stuff, block placement returns to normal speed.

**Comment by aidancbrady** [comment]
Fixed in development!

**Comment by Utildayael** [comment]
Woo hoo!!
