### ISSUE TITLE
NullPointerException: Rendering Block Entity

### ISSUE THREAD

**Issue by jokish63** [aidancbrady/Mekanism#3539]
the game crasht if I try to use the mekanism Basic Tank.
I have crafted a Basic tank and moved It in my Inventory. when I tried to pull it from the inventory into the Hotbar the game crashed immediatly and in the log appears Device not closed.
If I try try to restart, the game crashes in between the worldloading with the same log message
I figured out that Immersive Craft is involved. So I tryed to start alternatly without Mekanism and alternatly then without Immersive Craft. In both cases the world do load properly.
MC 1.10.2 the forge version is 2026
crash log:http://paste.ee/p/3tN3d
regards jokish

**Comment by aidancbrady** [comment]
Added a check, thanks!

**Comment by jokish63** [comment]
To Eufranio it's not always Optifine. I'm on research right now and I've checked optifine first and the problem is still there. I think MCMultipart is part of the problem but it is integrated in other mods and its difficult to turn it off if it is not wanted.

To Aidan thank you for the responding.
