### ISSUE TITLE
[Suggestion] Make it possible to set the Reactor Port to automatically output steam

### ISSUE THREAD

**Issue by SergeySave** [aidancbrady/Mekanism#3540]
The reactor can produce insane amounts of steam by itself, but in Mekanism there is no way of transferring all of that steam to a turbine or a storage tank. If the port could be set to auto-output the steam, you would be able to directly connect it to a turbine, storage tank, or entangloporter and be able to take advantage of all of the Steam/tick that the reactor is generating. As of now the maximum output you can get with just mekanism is 44,800 mB of Steam/tick (Assuming that you have 1 laser focus matrix, 2 ports for Deuterium and Tritium input, 1 port for water input, and 1 port for direct energy output). This is less than the minimum steam/tick that the reactor produces.

**Comment by cobra** [comment]
already done, #3305 - use the configurator on a reactor port to change it to output mode. IMHO, this could be a bit more obvious, but I don't have an idea for that.

**Comment by SergeySave** [comment]
Oh I tried using a configurator and it didn't do anything. Maybe it was in the wrong mode.
