### ISSUE TITLE
[Suggestion] Energy ratios

### ISSUE THREAD

**Issue by cindylo** [aidancbrady/Mekanism#3541]
Is there any way Mekanism could support values lower than 0.1? For example 0.08 or 0.001 to make it possible to bring it in line with other tech mods easily like IC2. For example as it is right now with 0.1 the standard solar panel in Mekanism is over twice as fast as the IC2 one.

**Comment by aidancbrady** [comment]
Mekanism can support energy values much smaller than 0.1. Everything can be modified in the config.
