### ISSUE TITLE
Configuration of Creative Energy Cube

### ISSUE THREAD

**Issue by Stekeblad** [aidancbrady/Mekanism#3542]
While playing in creative I noticed that the creative energy cube by default only output on one side as all the other energy cubes do I asked myself
"Can I input energy into a creative energy cube and void it?"
I tried with a full one but it did not accept it, tried the empty one and it worked.

My suggestion is to make all sides on the full creative cube output sides and all input for the empty one telling this difference in a tool tip. 
Then you place a creative energy block of some time you in most cases want to extract power, place it down together with some cables. Not think about the angle you are looking in and side configuration.

As one extra thing, the configurator does not work on a creative energy cube (Single player+creative mode) so the sides can not quickly be changed for many cubes.

**Comment by aidancbrady** [comment]
Done!
