### ISSUE TITLE
Fusion reactor consumes D-T fuel at 1000 units per tick

### ISSUE THREAD

**Issue by Stekeblad** [aidancbrady/Mekanism#3543]
Minecraft: 1.10.2
Mekanism +MekansimGenerators: 9.1.0.288

I made a fusion reactor in a creative single player world and then I started it the D-T stored in it vanished instantly and it quickly empties tanks piping into it. An ultimate gas tank feeding the reactor empties in about 25 seconds --> about 1000 units/tick. That is how much the reactor internally can store.

Changing the injection rate in the reactor does not make any noticeable changes in D-T fuel consumption nor in how fast the energy production rate is increasing.

After running the reactor for  a few minutes it is now stabilizing at about 250MJ/t and 75GK

**Comment by cloakable** [comment]
Injection rate determines how fast the reactor internally mixes deuterium and tritium to make d-t fuel. If you pipe in d-t fuel directly it will burn pretty much as fast as you can pipe it in. Don't do that.

**Comment by Stekeblad** [comment]
oh, ok.

I thought I should pump in D-T because I could make it outside the reactor (chemical infuser)
Have I any use of a tank with D-T for more then giving a reactor a little extra boost?

**Comment by cloakable** [comment]
Nope! You can use it to fill Hohlraums though. So you're probably set for any time you need to restart the reactor. xD
