### ISSUE TITLE
suggestion: Creative gas tank

### ISSUE THREAD

**Issue by Stekeblad** [aidancbrady/Mekanism#3544]
Suggesting a creative gas tank, for everything gases you need to do in creative.
It could have helped me testing #3543 instead of placing a long line of tanks outputing to each other.

To avoid filling up NEI /JEI with creative tanks, maybe have a little more clever solution like only having one creative gas tank and have its output desided by a normal tank in its inventory.

**Comment by ThatGamerBlue** [comment]
support

**Comment by MrPatience** [comment]
Why not but please no more "place every tank in nei/jei" <3

**Comment by Utildayael** [comment]
Good idea. Personally I'd like to see it like how Thermal Expansion does where you can place an empty creative tank and then apply the liquid you want to it to make it infinite. Could do same sort of thing in Mekanism to support gas or liquid.

While we're at it, creative bin as well. Same deal, place creative bin, place item in it, becomes infinite bin of that item.

**Comment by aidancbrady** [comment]
Creative Gas Tanks and Creative Fluid Tanks are finished in development :)
