### ISSUE TITLE
[1.10][bug] mining energy pipe causes CTD

### ISSUE THREAD

**Issue by elkillo** [aidancbrady/Mekanism#3545]
i have version 9.1.0.287 for 1.10.2 of mekanism and like the title says when i mine the energy pipes with a diamond pickax it causes a CTD i didn't have time to get the log as i am at work. ill get it as soon as i get home. also non-vanilla picks from silent gems mod mine it really slowly but don't cause a crash.

**Comment by elkillo** [comment]
http://pastebin.com/Tq9pbZSN link to the crashlog

**Comment by aidancbrady** [comment]
McMultipart bug.

**Comment by Ushupiuck** [comment]
Aidan... Just reported to MC Multipart. By what they said it's your fault... For short, you're using an old version. Check the original post over here: https://minecraft.curseforge.com/projects/mcmultipart
