### ISSUE TITLE
Crash after placing Personal Chest on a Tinker's Workbench

### ISSUE THREAD

**Issue by kraft2004** [aidancbrady/Mekanism#3546]
I'm getting a crash after placing a Personal Chest on a Tinker's Crafting Table, here's the crash log:
http://pastebin.com/XWFtpywW

It's only happening on the Tinker's Crafting Table. I don't know how to discover the cause of a crash decently, but i suspect it's a issue with the new feature of 3D blocks on the top of the table. When you place a item in the crafting grid, it appears as a model in the top of the Workbench.
After placing it, it will stay there as it is a table from Tinker's, so i'll have to remove the block trough external means.

~ Sorry for my bad english, it's not my native language.

**Comment by Eufranio** [comment]
Try without Optifine.

**Comment by aidancbrady** [comment]
Fixed in development, thanks.
