### ISSUE TITLE
Curse/Curseforge?

### ISSUE THREAD

**Issue by MakeLord** [aidancbrady/Mekanism#3547]
Any news on uploading Mekanism to Curse/Curseforge?

**Comment by aidancbrady** [comment]
I'm hoping to get a few more bug fix releases out first.  It'll be out soon :)

**Comment by MakeLord** [comment]
Oh nice... Thanks :D

**Comment by VT-14** [comment]
...It's been a month.  Any update on this?

**Comment by MakeLord95** [comment]
Yea... Still waiting for Mekanism. :/
