### ISSUE TITLE
Can't export gases/fluids from Mek machines

### ISSUE THREAD

**Issue by loveliss** [aidancbrady/Mekanism#3549]
Currently we are using 9.1.0 
As an example. I have an Electrolytic Sep across from a Gas Burning Gen. No matter what side I put the Basic Pressurized Tube on either machine gases do not flow. Tried EnderIO fluid conduit and I can get water into the Electro Sep. pressurized EnderIO conduit will attach to the Electro Sep but not the Gas Burning Gen.

Also for some reason most of the machines when placed down show a different name.. even the multiblock Dynamic tank.. (((you can't click on it to get into the gui.)))edit((((I can get into the tank gui now)))

**Comment by ktole1999** [comment]
gas gen has specific side to accept it if i remember. try rotating the gen.

**Comment by loveliss** [comment]
I tried from every possible side on both machines. I used to use this setup a couple years ago to power a mini base.

**Comment by aidancbrady** [comment]
The crash is due to another mod interfering, which I've added a check for in development.  Your other issues sound interaction-related as well.  Check in soon for a new release :)

**Comment by loveliss** [comment]
Thanks Aidancbrady :)
