### ISSUE TITLE
1.10.2 Pipe Problems

### ISSUE THREAD

**Issue by HickGamer** [aidancbrady/Mekanism#3553]
Alright so when i place at least your universal cable and try to break it with my pickaxe it crashes everytime. No its not cause of another mod. i have tryed mekanism by itself completely and done the same thing and it still crashes

**Comment by elkillo** [comment]
same as #3545 can confim it happens with every pick at but the paxel.

**Comment by aidancbrady** [comment]
McMultipart issue. @amadornes, any luck with the crash in #3545?

**Comment by elkillo** [comment]
can confirm installing McMultiparts fixed issue, i forgot to install in #3545. mek also doesn't tell me that it was missing despite it being a prerequisite.

**Comment by aidancbrady** [comment]
Strange. It's automatically installed on runtime, Minecraft wouldn't launch without McMultipart installed, I'm surprised there was no mod conflict upon your installation.

**Comment by elkillo** [comment]
One thing i did notice is that it creates a 1.10 folder that has mc mp in it. It was an experimental version. i Deleted it and redownloaded a version on curse using the minecraft client. The crash then stopped. Maybe the version that is downloaded with the runtime contains the bug. The conflict happened the first time i downloaded mcmp and it said i had 2 versions.
