### ISSUE TITLE
[1.10.2] RF not transferring through universal pipes

### ISSUE THREAD

**Issue by elkillo** [aidancbrady/Mekanism#3554]
i have an ender io capacitor attached to a uni pipe from mek to a sag mill and the rf is not transferring. the capacitor is set to out put to the appropriate side. Do they still transfer RF? the tool tip says they can i assume yes.

**Comment by aidancbrady** [comment]
This is due to a lack of Tesla integration by EnderIO.  Hopefully they'll update soon!
