### ISSUE TITLE
Cables and pipes not interacting with IC2 or Forestry correctly

### ISSUE THREAD

**Issue by Equanic** [aidancbrady/Mekanism#3558]
Using a clean build with industrialcraft-2-2.6.16-ex110, Mekanism-1.10.2-9.1.0.2.88, MekanismGenerators-1.10.2-9.1.0.2.88, MekanismTools-1.10.2-9.1.0.2.88 and forge 1.10.2-forge1.10.2-12.18.1.2027 on a flat world with defaults, I was unable to connect any form of universal cable to ic2 machines. Wires from ic2 connect and transfer energy fine between Mekanism machines and ic2 machines. Mekanism pipes also failed to connect to ic2 machines. When testing using the same set up but with forestry_1.10.2-5.2.3.213 instead of ic2, the cables would connect, but could not transfer power from forestry generators to other machines while forestry machines could receive power from Mekanism power sources using the same cable. I did not check pipe compatibility with Forestry. As I understand it, previous issues similar to this had to do with a dependency on a 3rd party mod, is this related to that, or am I doing something wrong?

**Comment by aidancbrady** [comment]
This is due to the way cables currently work- I'm awaiting the mods to support new power systems that utilize capabilities.

**Comment by Equanic** [comment]
Thank you for taking the time to look at this.

**Comment by JFMillerUSA** [comment]
It's 2017 and this is still an issue.

Mekanism-1.10.2-9.2.2.301
industrialcraft-2-2.6.142-ex110

**Comment by kraft2004** [comment]
It's 2018 and this is still an issue.

Mekanism-1.12.2-9.4.10.345
industrialcraft-2-2.8.76-ex112

**Comment by thiakil** [comment]
Don't necropost.
