### ISSUE TITLE
[Suggestion] Allow Muffling upgrades to be used in Bio-Generator

### ISSUE THREAD

**Issue by Hazmatik** [aidancbrady/Mekanism#3560]
Just as the title says, the bio-generators are really loud would be nice if they could accept the muffling upgrades.

**Comment by aidancbrady** [comment]
I've been considering adding upgrade support to generators for a while, but I'd rather wait until I have support for upgrades other than just the muffler.

**Comment by winsrp** [comment]
can we revive this for the gas-burning generator... OMG that thing is loud
