### ISSUE TITLE
Crash when rendering Mechanical Pipe with multiple sides set to PULL

### ISSUE THREAD

**Issue by static7s** [aidancbrady/Mekanism#3562]
I placed a mechanical pipe and set two sides to PULL mode, promptly followed by a crash. 
http://paste.ee/p/iIcvL

**Comment by murapix** [comment]
Exact same issue here, but with one side set to Pull, the other to Push. No problem until my pump-boiler-turbine system started up, then instant crash. Stack trace is exactly the same as OP's.

**Comment by aidancbrady** [comment]
Fixed in development.
