### ISSUE TITLE
support for Pam's Harvestcraft and SaltyMod salt

### ISSUE THREAD

**Issue by Hypsellis** [aidancbrady/Mekanism#3564]
There is no any support between the salt of these mods, so it's not possible to switch between the difference recipes of the 3 mods and use them in the mekanism machines.

**Comment by Utildayael** [comment]
I just tested and the salt from Pam's seems to work just fine in the Chemical Oxidizer to make gaseous brine. Can't speak for SaltyMod as I don't have that in my pack.

**Comment by aidancbrady** [comment]
Salt uses the ore dictionary, it's up to other mods to add their own support.
