### ISSUE TITLE
[Crash] Quantum Entangloporter

### ISSUE THREAD

**Issue by Utildayael** [aidancbrady/Mekanism#3565]
Placed the quantum entangloporter and opened interface. Clicked the side config button. Crash to desktop.

Opened MC again, tried to load same world and immediate crash to desktop. :(

QE was attached to fluxed redstone wire connected to an Environmental Tech solar multiblock.

Made new world, placed QE, seems fine now. Not sure if issue with Mek and fluxed redstone mod or what the deal is. 

Pastebin of the crash log. Same error both times.

http://pastebin.com/WE0MdW5i

Mekanism-1.10.2-9.1.0.288

**Comment by aidancbrady** [comment]
Not a Mekanism crash.

**Comment by Utildayael** [comment]
Thanks Aidan. Any idea where to look at with this? Just want to pass issue over accordingly. 

Thanks!
