### ISSUE TITLE
[Bug] Not all Dirty Dusts Process in Enrichment Chamber

### ISSUE THREAD

**Issue by Utildayael** [aidancbrady/Mekanism#3566]
Bit of an odd one.

Loaded up Mek v9 and set up my usual ore processing chain. Just a basic one.

Purification -> Crusher -> Enrichment -> Smelter

All machines set to input left, output right and in the same order shown above.

Input fine. Purification fine. Crusher fine. STOP!

The dirty dusts will not go into the enrichment chamber and if I manually toss one in, it does nothing.

Tested Working: Copper works. Tin works. Osmium works. Gold works. 

**Tested NOT Working: Iron**

I looked in the recipes for the enrichment chamber and it seems that quite a few things have dirty dust recipes... but Iron does not. Just plain ol vanilla Minecraft iron. 

Didn't see any config options around this so assuming a bug?

Cheers!

Mekanism-1.10.2-9.1.0.288

**Comment by aidancbrady** [comment]
Just ran some tests, all dirty dusts are working fine.  Likely an interaction issue.

**Comment by Utildayael** [comment]
Hi Aidan,

Thanks for looking. Can you please elaborate? I literally can't put Mekanism dirty iron dust into an Enrichment Chamber. I'm not sure where to look if it is some form of mod interaction issue. Any leads?

The dust shows as a Mekanism item and it was generated by a Mekanism T4 ore processing setup. 

Appreciate any direction you can give to help us find the cause.

Thanks

**Comment by AlphaKintari** [comment]
@Utildayael Also having the same issue, Want to compare modlists and see if we can track it down?

`1.10.2
\MCMultiPart-1.2.1-universal.jar
\CodeChickenLib-1.10.2-2.2.3.58-universal.jar
ic2
\EJML-core-0.26.jar
AbyssalCraft-1.10.2-1.9.2.9.jar
ActuallyAdditions-1.10.2-r60.jar
Aroma1997Core-1.9.4-1.1.0.3.jar
Aroma1997s-Dimensional-World-1.9.4-1.2.0.1.jar
Bagginses-1.10-3.0.3.jar
bdlib-1.12.2.8-mc1.10.2.jar
BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar
BetterFps-1.3.2.jar
BlockDrops-1.10.2-1.0.10.jar
BloodMagic-1.9.4-2.0.3-54.jar
Bloodmoon-MC1.9.4-1.4.1.jar
BrandonsCore-1.10.2-2.1.0.36-universal.jar
Chameleon-1.10-2.1.7.jar
ChickenChunks-1.10.2-2.1.3.36-universal.jar
Chisel-MC1.9.4-0.0.6.33.jar
chiselsandbits-11.10.jar
CodeChickenCore-1.10.2-2.1.8.79-universal.jar
CompactSolars-1.10.2-5.0.4.328-universal.jar
CookingForBlockheads_1.10.2-4.1.12.jar
deepresonance-1.10-1.2.1beta37.jar
Draconic-Evolution-1.10.2-2.0.0.82-universal.jar
ElecCore-1.9.4-1.5.303.jar
EnderBags-1.9.4-2.0.0.jar
EnderCore-1.10.2-0.4.1.48-beta.jar
EnderIO-1.10.2-3.0.1.92_beta.jar
EnderStorage-1.10.2-2.1.3.72-universal.jar
EnderZoo-1.10-1.2.3.43.jar
extrautils2-1.10.2-alpha-1.0.1.jar
FastLeafDecay-v11.jar
forestry_1.10.2-5.2.8.235.jar
FTBLib-1.9.4-2.1.0-pre2.jar.disabled
FTBUtilities-1.9.4-2.1.0-pre2.jar.disabled
gendustry-1.6.4.17-mc1.10.2.jar
generators-0.9.20.10-mc1.10.2.jar
GraveStone Mod 1.5.5.jar
industrialcraft-2-2.6.37-ex110.jar
InventoryTweaks-1.61-58.jar
ironchest-1.10.2-7.0.9.796.jar
jei_1.10.2-3.9.0.244.jar
jeibees-0.9.0.1-mc1.10.2.jar
journeymap-1.10.2-5.2.4-unlimited.jar
justenoughbuttons-1.10.2-1.2.jar
JustEnoughResources-1.10.2-0.4.9.50.jar
Mantle-1.10.2-0.10.4.jar
mcjtylib-1.10-1.9.9.jar
Mekanism-1.10.2-9.1.1.290.jar
MekanismGenerators-1.10.2-9.1.1.290.jar
MekanismTools-1.10.2-9.1.1.290.jar
MmmMmmMmmMmm-1.11.jar
Morpheus-1.10.2-3.1.7.jar
notenoughwands-1.9.4-1.3.5.jar
OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
Pam's HarvestCraft 1.9.4-1.10.2c.jar
ProgressiveAutomation-1.10.2-1.6.49.jar
Psi-r1.0-37.jar
Quark-r1.0-51.jar
RandomThings-MC1.10.2-3.7.5.jar
refinedstorage-0.8.15.jar
Reliquary-1.10.2-1.3.3.467.jar
rftools-1.10-5.15.jar
rftoolsdim-1.10-4.30beta47.jar
roots-1.10.2-0.111.0.jar
Ruins-1.10.2.jar
Ruins-1.10.2.zip
Ruins-1.10.2-sources.jar
StorageDrawers-1.10.2-3.2.4.jar
TConstruct-1.10.2-2.4.0.jenkins312.jar
Tinkers' Addons-1.10.x-1.0.3.jar
UniDict-1.10.2-1.5.jar
VeinMiner-0.34.1-1.9r571+73be663.jar
Waila-1.7.0-B3_1.9.4.jar
WailaHarvestability-mc1.10-1.1.7.jar
Wawla-1.10.2-2.3.0.201.jar
woot-1.10.2-0.2.5-alpha.jar`

**Comment by Utildayael** [comment]
Gonna be difficult. Thought it was modern metals but we made new server without it and still broke. :(

Not sure what "mod interaction" I would be looking for exactly as it's just vanilla iron ore and processes in Mek machines to normal Mekanism dirty iron dust. Oddly it works fine until it hits enrichment chamber be it a t3 or t4 processing chain.

**Comment by AlphaKintari** [comment]
yeah, I'm seeing the same. I'll build a new Minecraft version. and start adding Mods till it breaks. :)
Let you know.

**Comment by Utildayael** [comment]
Sorry for late reply. Yes we have unidict as well. Need @aidancbrady  to look at the unidict bug issue you listed as well if he would be so kind. Not sure who the "fix" needs to go to. I'm guessing unidict but never know.
