### ISSUE TITLE
Mekanism

### ISSUE THREAD

**Issue by StarfireSky** [aidancbrady/Mekanism#3570]
I have the Mekanism version 1.7.10-9.1.0.-281 and when I update the forge multipart to 1.7.10-1.2.0.336 it will crash because I did a test and that is how I found out. Here is how I did it I took forge multipart version 1.7.10-1.1.2.331 out of my mods folder just put in forge multipart version 1.7.10-1.2.0.336 after I deleted the configs from version 1.7.10-1.1.2.331 and then loaded my game and as soon as it started to load the game crashed is there a version of Mekanism 1.7.10 that will work with forge multipart version 1.7.10-1.2.0.336. Please let me know.

**Comment by aidancbrady** [comment]
Use the FMP version that is auto-downloaded.
