### ISSUE TITLE
[request] more options for flamethrower

### ISSUE THREAD

**Issue by gp009** [aidancbrady/Mekanism#3571]
sometimes another would cause flamethrower to have some issues  for example:

blue power would cause the flamethrower to smelt stone blocks into blue powers stone tiles, making it possible to smelt cobblestone into stone via flamethrower.

it would be nice to add an option to disable flamethrower from smelting stuff into other mods items

**Comment by MrPatience** [comment]
Even further from this idea , it would allow servers owners to enable this item , which honestly can't be allowed on a public server at this moment.

**Comment by aidancbrady** [comment]
There's a config option that allows users to disable world damage.  You can use combat mode to prevent things from being smelted.
