### ISSUE TITLE
[Performance] Particles and Factories

### ISSUE THREAD

**Issue by Utildayael** [aidancbrady/Mekanism#3572]
I think I finally tracked down my source of poor performance fps drop and stuttering within Mekanism. It seems the factories put out a LOT of particles even though it doesn't look like it. 

Normal MC: 120+ fps
Looking at Mek Factories with full particles; 20 fps

If I turn particles down to "decreased" it goes to 40 fps.. minimal goes to 60 fps. 

Not using Optifine or any of that mess.

i4670k, 16gb RAM, Geforce 770GTX 4GB
MC 1.10.2
Forge 12.18.1.2039
Mekanism-1.10.2-9.1.0.288

Not a lot to go on but seems to be specifically the particles the factories put out. I don't notice the same stuttering and fps drop around other Mek machines that I've noticed. [separator, oxidizer, etc]

Cheers!

**Comment by Utildayael** [comment]
Additional testing: Found out that by turning off the Mekanism sounds in client config it helps as well ... had been fine.. started getting like 2 fps when factory ran... friend suggested turning off sounds in config and as odd as it sounds, it worked. Went up to 20-30 fps which was much better than 2... still stutters like mad. If factories aren't running.. pull the usual 120 fps.

**Comment by Utildayael** [comment]
Even more testing. Made new world. Flat world. No structures. Redstone ready. 120fps pegged base with nothing built.

Built out same setup I have on my world I reported this on except this time I kept it 100% Mekanism other than a few Pressure Pipes infinite water sources to feed the separators. I could have just used pre-filled ultimate gas tanks but wanted an "identical" test using all the Mek machines as much as possible.

Contents:

Full tier 4 processing set up using all the stock items including a full height solar evap tower w/ heater + solar panels. All factories were "Advanced" factories with max upgrades to match what was in my other world. [8x speed, 8x energy, 8x gas as applicable]  

Here's the full setup:
http://imgur.com/a/okKnv


**Baseline:** 120 fps with machines NOT running

**Power up all machines:**  20 fps! Important note, this was NOT processing any ores, just the separators making the gases and whatnot so my earlier thought it was only factories is incorrect. This is with default Mekanism client settings.

http://imgur.com/a/XmjYO


**Processing Ore:** Stayed around 20 fps

**Processing Ore Pt 2:** Turned off player sounds, machine effects, and really everything in the Mek client settings. Only items enabled were ambientlightinglevel [default 15], CTMrenderer [true], and EnableAmbientLighting [true] -- fps went up 60 and fluctuated 40-70 fps but had stuttering

**All Finished:** Machines all idle, fps back to 120fps

Any time during the tests if I look away from the Mekanism setup, my FPS immediately went back to 120 fps [vid settings had it capped at 120]


If there is anything else I can provide to help with this please let me know.

Cheers

**Comment by aidancbrady** [comment]
I'm assuming you're using Mekanism for Minecraft 1.7.10- the performance issues you've mentioned have actually been addressed with the changes in 1.9.4/1.10.2.  I understand you might not be ready to transition, but I just want to assure you that I've experienced and fixed the problem :)

**Comment by Utildayael** [comment]
Aidan... I'm using 1.10.2 as in my post and the issues are most definitely there sadly. Please reopen.

MC 1.10.2
Forge 12.18.1.2039
Mekanism-1.10.2-9.1.0.288

**Comment by aidancbrady** [comment]
Ah, sorry, was doing a quick sweep through the issue. I'll take a look

**Comment by Utildayael** [comment]
No worries. Let me know if there is anything else I can provide to help. :)

**Comment by aidancbrady** [comment]
Might I ask what version of Mekanism you're using? I just did some testing using v9.1.1 and I'm getting a fairly consistent 60 FPS when the factory is running and idle. I recently completed some rendering performance changes which may be resulting in the fix.

**Comment by Utildayael** [comment]
9.1.0

Saw you out out an update. Will poke my server admin to update. I'll give that a test tonight if he gets it updated and let you know!

Thanks

**Comment by Utildayael** [comment]
Seems to be fixed with 9.1.1. Thanks! :)
