### ISSUE TITLE
[Bug?] Transfer Rate on Ultimate Universal Cable Inconsistent

### ISSUE THREAD

**Issue by Utildayael** [aidancbrady/Mekanism#3573]
I apologize in advance if this is not a Mek bug persay but I tested as best I could to try to eliminate.

Using Environmental Tech mod it has a solar panel tier 4 that pushes 85kRF/t. Ok cool, I'll use Mekanism Ultimate Universal Cables into an induction matrix! Cable rating says 128kRF/t. Hook up the cable feeding into an induction matrix that is full of ultimate induction cells and an ultimate induction provider. 

Hook universal cable to induction port and power starts flowing but it seems capped at 12.8kRF/t.

Thinking maybe its an issue with Env Tech I remove the Univ Cable and toss on an EnderIO conduit that is rated at 20kRF/t. Connection from solar to induction gets the expected 20kRF/t.

So I hook up two Mek univ cables to the matrix and I can get 25.6kRT/t [12.8kRT/t * 2 connections]. So it doesn't seem to be a limit on the induction matrix but the universal cables themselves seem to not be wanting to transfer at the tooltip speed.

I hooked up a creative energy cell and fed a vibrant capacitator bank [ender io] and was able to push 250kRF/t with one cable! That's double the rated capacity of the universal cable and is actually more than what a single vibrant Capac in enderio is supposed to take [capped at 25k!].

So I'm seeing inconsistent behavior with the universal power cables. Hoping it is something you can fix as I was super stoked to see you upped the power transfer rates on the cables with v9. :)

Cheers

**Comment by qinsignificance** [comment]
Same issue here

**Comment by aidancbrady** [comment]
Not a bug, it's the way the cables work :)

**Comment by Utildayael** [comment]
I'm confused. Can you explain further? Tooltip vs actual differs so curious what is going on. Should they actually get 128 kRF/t? Since they get 12.8 instead was thinking you moved the decimal one spot. :)

Thanks!
