### ISSUE TITLE
[1.10.2] Digital Miner model bug

### ISSUE THREAD

**Issue by CivilNikolas** [aidancbrady/Mekanism#3576]
There seems to be a bug with the digital miner rendering. 

 [Screenshots](http://imgur.com/a/4JDOY)

I'm using  All the mods modpack with nothing extra.

**Comment by aidancbrady** [comment]
You have an outdated texture pack.

**Comment by CivilNikolas** [comment]
I don't think this is the problem. The same thing happens without a resource pack. It may be something else causing this but have not managed to pinpoint it. Anyways. I'll keep looking.

**Comment by yutang13** [comment]
Can confirm this weirdness using my own custom pack and no texture pack on 1.10.2
