### ISSUE TITLE
Suggestion: Crossover pipe block

### ISSUE THREAD

**Issue by yutang13** [aidancbrady/Mekanism#3577]
Just a thought I had. Would be nice if there was a block that allows you to pass  pipes/cables through each other instead of having to bend one around the other.

How it'd work:
Place the block down and connect the  pipes you want to use and then use the blocks GUI to configure the sides (like the entangloporter).

Recipe:
A teleportation core
One of each type of (ultimate?) pipe/cable (energy, liquid, gas and heat)
4 glowstone ingots or bronze ingots.
Due to not having a item pipe in the recipe maybe item transportation shouldn't be allowed?

**Comment by laz2727** [comment]
Or maybe a pipe plug-like thing?

**Comment by aidancbrady** [comment]
Merging with #3256.
