### ISSUE TITLE
Crash on Server

### ISSUE THREAD

**Issue by DoughnutDev** [aidancbrady/Mekanism#3580]
Not sure which mod dev it is because it looks like IC2 (is not even in the pack), EnderIO and Mekanism is part of the issue. Here is the log http://hastebin.com/wuxeqivegu.coffee

EnderIO: 3.0.1.77
Mekanism: 9.1.0.288

**Comment by DoughnutDev** [comment]
Another issue that is happening after adding Mekanism I started to get a crash with my IC2 setup which caused me to remove the mod itself here is log for the crash http://hastebin.com/ehirotumij.coffee

**Comment by cindylo** [comment]
I have the same crash with IC2 and Mekanism on my server. Whenever I remove mekanism it boots the server without crashing though.

**Comment by DoughnutDev** [comment]
I am glad I am not the only one. I looked on the IC2 tracker and I found other people that had the issue and they all have Mekanism and IC2

**Comment by Terpo** [comment]
Just for the moment, can you try this config option? B:BlacklistIC2Power=true
I am struggeling with the same problem and for me it helped.

**Comment by DoughnutDev** [comment]
I am a pack developer on ATLauncher so I had to remove the mod because it was breaking all the things lol.

**Comment by DoughnutDev** [comment]
Were you having the issue then you set that to true and it was gone?

**Comment by Terpo** [comment]
Yeah, but I only did some tests in SP.

**Comment by cindylo** [comment]
That does indeed fix it Terpo, it seems that the IC2 API implementation for the energy conversion is broken.

**Comment by Redlotus99** [comment]
I too am having this same issue. I'm guessing BlacklistIC2Power=false is a workaround until this gets corrected by IC2?

**Comment by Utildayael** [comment]
BlacklistIC2Power=true would be workaround, false is default ... :)

**Comment by Utildayael** [comment]
@aidancbrady here's the IC2 bug link if that helps in your troubleshooting; there's some details on what they think the issue might be with how Mekanism is calling something in IC2

http://bt.industrial-craft.net/view.php?id=1948

**Comment by aidancbrady** [comment]
Should be fixed, appreciate it!

**Comment by Utildayael** [comment]
You're on a roll today. :)

Thanks!
