### ISSUE TITLE
Ultimate Fluid Tank's aren't hidden in NEI

### ISSUE THREAD

**Issue by Zaflis** [aidancbrady/Mekanism#3581]
I'm using a config change in Mekanism.cfg:

    B:PrefilledPortableTanks=false

It hides most of the tanks but Ultimate Fluid tanks still show up, and cause few seconds loading spike in NEI.

Mekanism-1.7.10-9.1.0.281.jar

**Comment by aidancbrady** [comment]
I'm pretty sure the config option is now "PrefilledFluidTanks."
