### ISSUE TITLE
Two Crazy Ideas

### ISSUE THREAD

**Issue by Zoidey** [aidancbrady/Mekanism#3582]
I've had some ideas come to me over the past week or so that I reckon would be pretty cool to implement if it's possible and not overly complicated to do.

Idea number one is with regards to the digital miner, the idea I had with this is adding a new upgrade for it along the lines of the speed and energy upgrade but have it as a chunk loader upgrade that either keeps the digital minger  and/ or the mining area chunkloaded. This would be handy if you don't use a mod that has chunkloaders or you just hate having to carry around a chunkloader to deploy and then pick up each time you change locations to mine.

Idea number two might be a tad complicated but cool nonetheless , Have you ever found the perfect place to build your house or other building on and go to make the basement by digging down several layers down only to find there is a huge hole or canyon underneath your soon to be home that you almost fall to your death? I had an idea on a way that you could fill it, You could use the Fluidic Plenisher and fill the area with water, but that's no good unless you want your very own indoor swimming pool. The idea is some sort of machine like the Fluidic Plenisher but instead of filling the underground holes etc with water it fills it with liquid dirt or mud in the same way as the Fluidic Plenisher would, The difference would be that the liquid dirt / mud would turn into dirt after a set period of time. Maybe have another machine or an existing one that allows you to grind down dirt and then mix it with water to make it into a slurry that you can then fill the holes it and let it harden turning into dirt.
Would be easier than filling it in by hand or using the filler from buildcraft (that thing can be a fussy pain in the royal backside when laying out the landmarks etc).

Mekanism is probably one of my most favourite if not the most favorite tech mod and I'm loving all the new addons, updates extras etc. Anyway I'll leave you to decide if my crazy idea is plausible or insane.

**Comment by aidancbrady** [comment]
I've had plans to add some form of chunk loader upgrade for a while, I'll see!

Your idea for a "filler" is very clever.  I want to add new forms of building devices to Mekanism in the near future, I'll keep something like that in mind :)
