### ISSUE TITLE
java.lang.NullPointerException: Updating screen events

### ISSUE THREAD

**Issue by ohunter** [aidancbrady/Mekanism#3583]
When running Minecraft with the mod Armory, this is the error that gets reported

> java.lang.NullPointerException: Updating screen events
> 	at com.smithsmodding.armory.common.fluid.FluidMoltenMetal.getLocalizedName(FluidMoltenMetal.java:41)
> 	at mekanism.common.util.LangUtils.localizeFluidStack(LangUtils.java:26)
> 	at mekanism.common.item.ItemBlockMachine.func_77624_a(ItemBlockMachine.java:199)
> 	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:610)
> 	at net.minecraft.client.gui.inventory.GuiContainerCreative.updateFilteredItems(GuiContainerCreative.java:367)
> 	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147053_i(GuiContainerCreative.java:345)
> 	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:523)
> 	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:427)
> 	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:556)
> 	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:539)
> 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:515)
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
> 	at net.minecraft.client.main.Main.main(SourceFile:124)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:483)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Full crash report: http://pastebin.com/ywf27bnC

**Comment by aidancbrady** [comment]
Report this to the Armory mod.
