### ISSUE TITLE
[1.10.2] [9.1.0.288] Atomic Disassember not respecting attack speed.

### ISSUE THREAD

**Issue by Kazzamkablam** [aidancbrady/Mekanism#3584]
Atomic disassembler on 1.10.2 has no attack speed, making it spammable and insanely overpowered compared to other items/weapons.

**Comment by aidancbrady** [comment]
Fixed!

**Comment by Kazzamkablam** [comment]
Now it has attack speed but no matter what you do you always hit for same damage, so you can still spam it. Also for whatever reason it's missing attack damage on tooltip.
