### ISSUE TITLE
Mekanism weapon and tool rendering

### ISSUE THREAD

**Issue by Arcanatias** [aidancbrady/Mekanism#3586]
It seems the weapons and tools (except the flamethrower and atomic disassembler) do not render correctly on the user, other players and mobs in 3rd person. They render correctly on the user in 1st person. Tested in a creative world with all the tools and weapons. I am using the 1.10.2-9.1.0.288 version of mekanism.
![2016-08-03_02 07 39](https://cloud.githubusercontent.com/assets/20810007/17357040/5a78c420-5920-11e6-820c-f9ad6f88300b.png)
![2016-08-03_02 07 47](https://cloud.githubusercontent.com/assets/20810007/17357044/5dca8492-5920-11e6-9079-1288f061db07.png)

**Comment by aidancbrady** [comment]
Fixed, thanks!
