### ISSUE TITLE
Suggestion: Allow Thermodynamic Conductors to pass IC2 heat units

### ISSUE THREAD

**Issue by TheGuyRunningSouth** [aidancbrady/Mekanism#3588]
If at all possible, I would love to see the Thermodynamic Conductors be able to work with IC2's heat system in a manner similar to the Universal Cable's energy conversion.

**Comment by aidancbrady** [comment]
I considered this several weeks ago, but I'm afraid that the conversion technicalities and differences in our systems would make this rather difficult.  Perhaps in the future!
