### ISSUE TITLE
Crash between Mekanism and ActuallyAdditions; Possibly from outdated Tesla API

### ISSUE THREAD

**Issue by utoc** [aidancbrady/Mekanism#3590]
When attaching any Mekanism power conducting cable (conduit) to an AA Energy Relay, there is an immediate crash with the following: http://pastebin.com/sz68A2JQ

I am running:
    FML 2045
    Mekanism 288
    AA r57
    Tesla 1.10.2-1.2.1.42.  Reverting to AA r56 alleviates the issue.  Please let me know if I have neglected anything.

@ellpeck stated [here](https://github.com/Ellpeck/ActuallyAdditions/issues/187) that the cause was due to the Mek implementation of Tesla being outdated as the mod author has lowercased the mod name.  You have likely updated already in development but here is a report anyway.

**Comment by aidancbrady** [comment]
Updated Tesla API, hopefully that works!
