### ISSUE TITLE
Split config options between Bio Generator and Gas Burning Generator

### ISSUE THREAD

**Issue by utoc** [aidancbrady/Mekanism#3591]
I have a request: Would you consider splitting the shared config option between the Bio Generator and the Gas Burning Generator into their own options, apart from each other

Like so:

     D:BioGeneration=24.0
     D:GasGeneration=256.0

Thanks so much!

**Comment by aidancbrady** [comment]
The config options are not shared. The Gas Generator uses the energy values based on the type of gas being burned, which are also defined in the config.

**Comment by utoc** [comment]
I didn't realize that.  I was tweaking my config yesterday and saw that Ethleyne was burning at 8krf/t and the only way to get it down was to set BioGeneration from 64.0 to 5.0... this brought Ethleyne burning to aprx 500rf/t.
