### ISSUE TITLE
Lagg on server 1.7.10

### ISSUE THREAD

**Issue by LemonNick** [aidancbrady/Mekanism#3592]
http://f3.s.qip.ru/bmdN29pJ.png

When a lot of players the server starts to lag due to the security system. You can add in the config function otklyucheniya.
Or optimize security system

**Comment by aidancbrady** [comment]
This is in no way related to the security system, rather the Logistical Transporter pathfinding calculations.  These have been optimized for 1.10.2, but I'm afraid this kind of support is no longer provided for 1.7.10.
