### ISSUE TITLE
Universal cable will not extract power from other mods' generators

### ISSUE THREAD

**Issue by ManMan36** [aidancbrady/Mekanism#3593]
On version 9.1.0.288 for 1.10.2, I attempted to use the basic universal cable to extract power out of an Ender IO sterling engine. I could not get the power to extract, even setting the cable to extract and telling the machine itself to provide. Thinking it was an Ender IO issue, I had tried the same thing with a power cube from Calculator and could not get it to work either. I was able to get it to extract energy from various Mekanism machines.

**Comment by elkillo** [comment]
i had the same issue with the Coal generators from RF tools and i was told that is because that those mods (enderio and rf tools) do not have proper tesla API integration. Once the integration is added it should work. #3554 here i my issue report.

**Comment by aidancbrady** [comment]
@elkillo is right :)

**Comment by Anarcraft** [comment]
FYI a good workaround for this is to input your other mods' energy into a Mek energy cube first, then run universal cables off the energy cube.
