### ISSUE TITLE
[Suggestion] Radial menu for choosing Configurator modes

### ISSUE THREAD

**Issue by Raakuu** [aidancbrady/Mekanism#3595]
I have an idea for a radial menu for Configurator. It would be easier and faster to choose a certain mode. 
Something similar to radial menus from Psi and Chisels & Bits

Here's a design that I came up with to help visualize the idea: http://imgur.com/a/rdzGK

**Comment by yutang13** [comment]
100% Support this. Changing modes on the configurator currently is a pain.

Ps: Nice artwork

**Comment by Ambaire** [comment]
This is a great idea; I often want to swap between wrench and configurate fluid conduit input/output modes.

**Comment by aidancbrady** [comment]
Added a feature that allows for configurator mode change by sneaking+scrolling, along with a handy visual indicator. Hopefully this helps!
