### ISSUE TITLE
[Balances] HCl usage on Sulfuric Acid production

### ISSUE THREAD

**Issue by donqixot** [aidancbrady/Mekanism#3597]
Hi, thanks a lot for this mod, truly awesome!
I just wanted to check balancing on some materials usage. To produce Sulfuric Acid, I need to process gunpowder to sulfur with the help of Hydrogen Chloride (HCl) in Chemical Injection Chamber. It takes about 2000 mb of HCl for one gunpowder, which produces 100 mb of sulfuric acid, so I need about 20000 mb (20 buckets) of HCl to produce one bucket of sulfuric acid to be used for **one** ore to be processed in Chemical Dissolution Chamber. One ore for 20 buckets of HCl? That chloride comes from Thermal Evaporation Tower and is not exactly cheap. Is this on purpose? With such high cost on HCl it doesn't make any sense to try quintuple ore processing because quadruple is so much less expensive. One extra ingot of metal for 20 buckets of HCl? Or did I miss something? Of course you could use other mods to produce sulfur from blaze rods etc, but in a standalone Mekanism, this seems prohibitively expensive. Just wanted to hear directly from developer what do you think on this?

I tested all this in 1.7.10-9.1.0.281 with forge 10.13.4.1614-1.7.10.

**Comment by aidancbrady** [comment]
You can use Gas Upgrades in the Chemical Injection Chamber to lessen the amount of HCl required to produce gunpowder.  Yes, those values are intentional :)

**Comment by donqixot** [comment]
Of course Gas Upgrades! This changes the whole thing! Thanks a lot for a quick response! Best mod ever!!! I don't see a button to close this ticket, may be you can, thanks!
