### ISSUE TITLE
JEI tooltip for Metallurgic Infuser says Enrichment Chamber (unimplemented)

### ISSUE THREAD

**Issue by GPAShipwreck** [aidancbrady/Mekanism#3598]
As in subject line, the tooltip when mousing over the Infuser says Enrichment Chamber (unimplemented). I don't know if this is a JEI or Mek issue, or an interaction with other mods/code. I am running 9.1.0 in the Avant3 modpack on a community server.

As an aside, when I place the machine next to a coal generator it reorients itself to be back to back with it instead of side to side after a second or two as well.

I don't have the technical expertise to begin to diagnose either of these issues, just thought I would mention them in case they require attention.

**Comment by aidancbrady** [comment]
Pretty sure this is actually WAILA-related, and I'm confident this is on their end.
