### ISSUE TITLE
[Suggestion] Elytra Jetpack!

### ISSUE THREAD

**Issue by yutang13** [aidancbrady/Mekanism#3601]
There should be a way to get an elytra mode on the jetpack.

How to get the upgrade:
 You'd have to get an elytra and then use it to craft the "Elytra Upgrade" and then take that and your jetpack and use the "Upgrade table" to install the upgrade.

How it would work:
 Pretty simple; "Elyta mode" works the same as a normal elytra except you can use the jetpack to give you a speed boost for the cost of fuel.

The Upgrade table:
 Allows you to install upgrades onto your tools/armour. Would later be used to apply and remove upgrades for the MekaSuit.

**Comment by aidancbrady** [comment]
Expand on this in the MekaSuit Discussion thread :)
