### ISSUE TITLE
[Sound bug] Excessively loud windmills. 

### ISSUE THREAD

**Issue by yutang13** [aidancbrady/Mekanism#3602]
I updated to the latest version of mekanism today and was moving my windmills up to max height when i discovered that the windmills were being **extremely loud!**

How loud? Loud enough for the sound to be capping and distorting horribly. I only have about a dozen up there. Luckily I never have to go up there but windmills are so very loud.

**Comment by aidancbrady** [comment]
Wind Generators now fall under the Weather sound category.
