### ISSUE TITLE
Chat Massage

### ISSUE THREAD

**Issue by Lostordem** [aidancbrady/Mekanism#3606]
I play a Modpack in the 1.7, with Mekanism 9.1.0. So I start my World and in the chat is an alert, that I have an outdated version of Mekanism, but I don't have found a newer version for 1.7... it is no big deal to ignore that but it is a little bit annoying for me ^^

**Comment by aidancbrady** [comment]
You can disable update notifications in the config :)

**Comment by Lostordem** [comment]
where? ^^
