### ISSUE TITLE
[1.10]Block Lag/Texture Error

### ISSUE THREAD

**Issue by TheXWolf** [aidancbrady/Mekanism#3607]
It seems when the factories are running full tilt there's a great deal of lag.
At first I thought it was the sheer amount of machines running (I have a tier 3/x4 factory running)
but it was running smoothly, all of a sudden the production stopped and I had to vent the excess sodium I had. When I started doing it I got a massive FPS drop (down to the teens from over 100) and tried breaking every one of them. It wasn't until I had mined away every machine including the Evap. plant controller did it actually stop. (Let me know what/if any logs can help. I had around 10g of memory allocated, was only at about 30%.)

Also I noticed some startup errors with textures, might have something to do with an issue I noticed where when I used a configurator on a pipe the pipe actually looked like it was porting in from the wrong direction and left the gas texture exposed.
http://pastebin.com/2fEvnU0V

**Comment by aidancbrady** [comment]
Merging with #3572.
