### ISSUE TITLE
Flickering Machines

### ISSUE THREAD

**Issue by Oaurn** [aidancbrady/Mekanism#3608]
Mekanism 1.10.2-9.1.0.288

I notice that every few seconds my mekanism machines will flicker for a second where they change their texture, but never for longer than a second before returning to normal.

https://www.youtube.com/watch?v=VVjssdlHt9M

This is a quick video of the issue I took on the server I play on.   It only affects Mekanism machines and nothing else.  I've tried removing various non essential client mods but the issues still persists.

It has no real impact on gameplay as all the machines work as intended, but is very annoying to look at.

Thanks.

**Comment by BeyJohn** [comment]
I am also having this issue with Mekansim 1.10.2-9.1.1.289
It looks the same as the flickering in the video above, and it gets a lot worse when I use a farming machine with a torcherino. I _think_ it _may_ be happening when the chunks are redrawn.
