### ISSUE TITLE
Tank Dupe

### ISSUE THREAD

**Issue by bookerthegeek** [aidancbrady/Mekanism#3609]
While looking inside any portable fluid tank from Mekanism, fill every slot in your inventory (Not your hotbar) with single stacks size items that actually stack (for example 27 diamonds).

Once your inventory is completely full, shift right click on the the items one by one. Profit. Works both Single Player and Server.

**Comment by spannerman79** [comment]
I assume that your not running Inventory Tweaks server side?

**Comment by aidancbrady** [comment]
Fixed in development.

**Comment by bookerthegeek** [comment]
@spannerman79 tested both with and without, no effect on the dupe but it seemed to be easier with it installed.

**Comment by spannerman79** [comment]
As @aidancbrady stated its fixed in dev so "soonish" there will be an update release.

@bookerthegeek Inventory Tweaks doesn't need to run server side.  The ability to dupe with Inventory Tweaks is *much* easier if running on the serve.r  Suggest that you take it off the server. Reference for this is already done via https://github.com/CyberdyneCC/Thermos/issues/345

**Comment by bookerthegeek** [comment]
@spannerman79 I realized that, I was responding to you with that comment. We actually don't run that mod normally on the server, but I tested for the off chance it would solve it. ;)

And of course tested on forge versions also.

**Comment by Sir-Will** [comment]
In which version will this be fixed?

**Comment by bookerthegeek** [comment]
@aidancbrady no rush, any idea when this will be included into a release for 1.7.10?

Only asking so we can inform our players if/when we will be able to unban those items.

Love you mod and looking forward to what comes next.

**Comment by evernife** [comment]
Same question o.0

**Comment by bookerthegeek** [comment]
@aidancbrady 

Would it be possible to get this implemented into the 1.7 branch for a final bug fix version?

**Comment by evernife** [comment]
`Same question o.0`²
