### ISSUE TITLE
[1.10.2] [Mod Incompatibility] Cardboard boxes breaking items

### ISSUE THREAD

**Issue by Dijkstra1** [aidancbrady/Mekanism#3611]
I am glade to see Mekanism on 1.10.2, be using the cardboard boxes, a lot and found that I should not use them Industrialcraft machines as when I remove the box i get an invalided block with no texture, that drops nothing when broken/wrenched. Also the Extra utils furnace when moved, becomes base machine frame for Extra utils. I want say this probably down machines are the same ID, and either different mate values or NBT, although i thought cardboard boxes saved them. It hard to look at there code to see what they are doing both being closed sourced mods.    

Edit:
When removing an cardboard from an non Meakanism item it will open the block GUI as well

**Comment by aidancbrady** [comment]
Reported in a later issue, definitely being looked at.
