### ISSUE TITLE
[1.10.2] Cardboard box deletes Advanced Solar Generator when boxing the base of it.

### ISSUE THREAD

**Issue by Hypocrisy** [aidancbrady/Mekanism#3613]
The box and the Advanced Solar Generator just straight up disappear, never to be seen again.

**Comment by Frontrider** [comment]
Slightly random note: in 1.7 a similar behaviour also exists with the nasa workbench, never to be seen again.

random idea for it: create a separate liblary for tiles like this, so when you fix the behaviour it can be fixed everywhere. A "bounding block api" or something.
