### ISSUE TITLE
[1.7.10] java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by deframet** [aidancbrady/Mekanism#3614]
Windows 10 (Version 1607)
Java 8u25

If I delete Mekanism the pack works just fine....
* [Modlist](http://pastebin.com/YiYG04pE)
* [Log](http://pastebin.com/jLKMDiet)

**Comment by aidancbrady** [comment]
Make sure the version of Mekanism you have installed is for 1.7.10.

**Comment by deframet** [comment]
Oh....Thanks
I should learn not to make modpacks at night
