### ISSUE TITLE
Compatibility with Carpenter's Blocks

### ISSUE THREAD

**Issue by karakufire** [aidancbrady/Mekanism#3617]
When I use Carpenter's blocks with Mekanism blocks, I noticed Mekanism blocks are unique rendering and cannot use with it.
I like every awesome Mekanism textures, because the fact Mekanism blocks cannot apply in carpenter's blocks makes me sad.

**Comment by aidancbrady** [comment]
This is likely due to the way certain blocks utilize the CTM renderer.  I'm afraid there's not much I can do :/
