### ISSUE TITLE
Unknown crash. 9.1.0.281

### ISSUE THREAD

**Issue by vagaprime** [aidancbrady/Mekanism#3618]
On a server that is hosting my pack someone decided to use a cardboard box on a rotarycraft gearbox. Now when ever someone gets near that person's base they crash to desktop. No crash log is being created, and there are not even any errors showing up in the FML log before Minecraft shuts down.

here is a link to my FML log from the crashed instance.
http://paste.ee/p/fnStc

one of the server Admin's Logs
https://ghostbin.com/paste/2o7sd

and the player who the base belongs to who but the cardboard box on the rotarycraft gear box
http://pastebin.com/5Z8vE8Rz

**Comment by aidancbrady** [comment]
Perfect example of a time to use the BoxBlacklist in the mekanism config.

**Comment by vagaprime** [comment]
Ok. then would it be possible to have the black list have a config option allowing it to be treated as a white list, allowing for server admins and pack dev to have a much smaller list allowed items?
