### ISSUE TITLE
[crazy idea] Reverse of Digital Miner

### ISSUE THREAD

**Issue by rdunham3** [aidancbrady/Mekanism#3621]
Just floating this out there to see if anyone else has had this situation...

Every once in a while I wish I had an easy way to fill in a large area of air blocks.  It would be nice to be able to load a few stacks of something (dirt, cobble, whatever) into a machine, give it two coordinates (opposite points of a cube shape) and it fills everything between those points with the supplied blocks.  Think of this as the solids equivalent of a fluidic plenisher, if you like.

As far as I'm aware the Digital Miner can't be coerced into doing that, without mining out blocks in the process.  Or can it?

If such a machine had a toggle for filling just air blocks, or both air and fluid, even better.

**Comment by spannerman79** [comment]
I am not sure if this is a good idea.

Reason being is that you *could* do the same via BuildCraft Builder.  But you and I both know the reason why that myself (and perhaps even yourself @rdunham3) is that BuildCraft isn't as server friendly as what Mekanism is - even more so the Digital Miner.

There are other ways in filling in areas (Better Builders Wands etc) or even WorldEdit which is perfectly suited for this if not looking at using BuildCraft.

I can also see this suggestion being used to grief players as well.  Currently the Digital Miner only replaces ore/blocks when instructed to - in essence replacing what it mines with another block (be it cobblestone, etc) when setup to do so.  Allowing it to replace minecraft:air you can in effect surround another players area (bed, house etc) and replace with a block.  That player connects and dies from being suffocated.

**Comment by aidancbrady** [comment]
A "Digital Builder" is something I've considered for a while, but it likely won't be added anytime soon.  I'll keep it in mind!

**Comment by VT-14** [comment]
Can you 'mine' air blocks?  Setting radius and depth while mining 'air' would produce no drops, and let you use the existing auto-replace feature.

A separate machine would be more appropriate; but this could be a temporary solution.
