### ISSUE TITLE
[JEI Support] ISubtypeRegistry

### ISSUE THREAD

**Issue by Dijkstra1** [aidancbrady/Mekanism#3622]
Are you aware of ```ISubtypeRegistry``` in JEI, it lets you tell JEI about NTB tags that define an item as being being different though they have same ID, thus fixing the issue of showing recipes for each tier item one click on just the one.

**Comment by aidancbrady** [comment]
Done! Appreciate it, I was using NbtIgnoreList and it seems as though that is now deprecated.
