### ISSUE TITLE
[CONFIG] Add option to disable Wind / Wind Turbines in dimensions

### ISSUE THREAD

**Issue by LokeYourLord** [aidancbrady/Mekanism#3623]
As the title suggests, i would really like having that option, as i do not like my players using them when far out in space where there is no wind, like in an Asteroid Field (Solar is no problem as sun almost always reaches those places).

I would like this to be added to the 1.7.10 version and upwards.

**Comment by aidancbrady** [comment]
Wind Generators and other generators can now be disabled.

**Comment by Bysokar** [comment]
Damn haha, I'm on 1.7.10 and would love this. Great you have done it for 1.10+ though thanks Aid!
