### ISSUE TITLE
DigitalMiner is missing a blacklist

### ISSUE THREAD

**Issue by LemADEC** [aidancbrady/Mekanism#3625]
To my understanding, a digital miner can mine any kind of blocks even if:
- block has high hardness like an Reinforced stone or equivalent,
- block is a tile entity like a machine or sort,
- block is part of a force field,
- block is non-accessible (behind a wall of unbreakable blocks like bedrock or one of the previous).

Could we have at least an hardness cap or a blacklist to address this?

**Comment by aidancbrady** [comment]
In 99% of cases, people in need of serious restriction of the DM would be better off using a miner from another mod- it's fairly easy to disable Mekanism machinery.  Regardless, for in-game limitation of the miner, check out the currently-open DM overhaul thread.
