### ISSUE TITLE
Machines and Tanks Losing Facing

### ISSUE THREAD

**Issue by Utildayael** [aidancbrady/Mekanism#3627]
Odd one tho I remember seeing this a looooooong time ago and you fixed it but it seems back in the current version.

Machines and gas tanks are losing their facing, that is to say, the way they are facing.

For example, I'll have a row of Mek ore processing machines all facing North. I'll log in to server and they are jumbled where they all face in different directions!

Gas tanks have this problem as well and exhibit the *really* weird behavior of pointing DOWN. The output point actually faces down and the tank is horizontal! While I've wished I could place them like that forever for specific configs, this isn't quite what I was looking for. :)

This seems to happen when I log back on to server after having crashed to desktop on the mechanical pipe rendering bug #3626 fwiw.

**Comment by aidancbrady** [comment]
This issue may be linked to the Mechanical Pipe rendering issue- I'm not able to reproduce in my development environment.  Let me know if the issue persists once v9.2 is out!

**Comment by Utildayael** [comment]
Will do. Thanks!
