### ISSUE TITLE
[1.10.2] Large Dynamic Tanks initial rendering lag

### ISSUE THREAD

**Issue by donqixot** [aidancbrady/Mekanism#3629]
Hi, thanks for this awesome mod again! I started testing 1.10.2 version, I know it is work in progress. Just wanted to let you know about this case. When I create very large dynamic tank and try to put a bucket of water in it, it takes significant hit on computer resources (disk at 100%) and causes significant delay (5 minutes). Once the water being rendered once, then taking bucket in and out is ok, although still laggy compared to before tank. I use default video settings except "Use VBOs = off". I see in the log something like this: [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 270358ms behind, skipping 5407 tick(s).

Smaller tanks (9x9x18) are much better, bigger tanks (18x9x18) and (18x18x18) are exponentially worse.

I use latest version of Mekanism 1.10.2-9.1.1.290 and forge 1.10.2-12.18.1.2050.
Thanks!

**Comment by aidancbrady** [comment]
Fixed in dev, thanks!
