### ISSUE TITLE
Advanced Fluid Tank Crash

### ISSUE THREAD

**Issue by krzosik** [aidancbrady/Mekanism#3630]
Hi, I have problem with Advanced Fluid Tank crafting. I made basic fluid tank, but when i put all things in crafting table for advanced tank my game crashes. Unfortunately, when I restart game, my save can't load. I tried many times, but still without success. I hope that this bug will be fixed, because I dont want to lose my save. I used last version of Mekanism for MC 1.10.2.

I discovered, that the problem is caused by crafting fluid tank in crafting station from Tinkers Construct. When I use crafting table, eveything is ok.

**Comment by aidancbrady** [comment]
Already been reported.  I'm afraid there's not much I can do here, I've added as much render support as I can.

**Comment by krzosik** [comment]
One thing I should add: only solution which i found for this problem was to move player far away from chunk with crafting station and change this block by command /setblock into air. Then i can came back to my home.
