### ISSUE TITLE
All Induction Cells turn into Basic Induction Cells

### ISSUE THREAD

**Issue by feldim2425** [aidancbrady/Mekanism#3631]
Mekanism: 9.1.1.290

Ultima induction cells turn into a basic cells. If it dosn't turn into a basic cell it does it after a world reload. The Induction Provider doesn't has that problem.
![2016-08-12_02 02 48](https://cloud.githubusercontent.com/assets/6705744/17609056/9a7d5d48-6031-11e6-9058-6cc3dea5183c.png)

EDIT: Same problem with other tiers

**Comment by aidancbrady** [comment]
Fixed in dev, thanks :)
