### ISSUE TITLE
Setting Energy cable to pull patally crashes server

### ISSUE THREAD

**Issue by Gunner76th** [aidancbrady/Mekanism#3632]
First let me define how I am using "Fatally crashes: for this bug report. Fatally crashes within the scope of this bug report refers to the fact that unless the world is opened with MCEdit, and the cable is removed, the world is no longer playable. 

I have a player that was connecting the ultimate level energy cable to a mekanism machine. While he was configuring the cable, it set one of the settings to PULL. Upon doing that, the server crashed with the following crash report: http://pastebin.com/y8UpJwpf

I attempted to restart the server, and the server again crashed with this crash report: http://pastebin.com/dWUAQ1c1

If you need any information that is not included within the crash report itself, please let me know.

**Comment by static7s** [comment]
Same thing happens with the fluid and item pipes. Have not yet tried with the gas and heat pipes, but I expect that similar results would occur.

**Comment by aidancbrady** [comment]
Fixed in dev, thanks.
