### ISSUE TITLE
[1.7.10, 1.10.2] Digital miner inconsistent behavior when mining clay

### ISSUE THREAD

**Issue by Ambaire** [aidancbrady/Mekanism#3633]
If you set a digital miner to mine clay blocks, no silk touch, at the start of a new mining session it will always give 7 clay balls for the first clay block mined. This lets you dupe clay. I have not managed to reproduce this with any other blocks. I first noticed this strange behavior in 1.10.2 and I reproduced it in 1.7.10 as well.

Steps to reproduce: 
Create a digital miner and place it in the world
Give yourself a stack of clay
Set the digiminer to mine item stack and prime it with the clay.
Place a clay block in the world
Start the digital miner
Notice that you now have 7 clay balls in the inventory

If you place two+ clay blocks and mine without stopping, you will get 7 for the first and then 4 for any others.

If you place two+ clay blocks, mine, stop, reset, mine again, you will get 7 for each.

**Comment by aidancbrady** [comment]
Fixed, appreciate it
