### ISSUE TITLE
add ore dictionary

### ISSUE THREAD

**Issue by TheRealM18** [aidancbrady/Mekanism#3634]
i am having a problem with your ore dictionary of the copper ingots at least. could you fix that so that it can be solved.  I know it take not a lot of time though there is a lot of lines to right, so having it in as a ore dictionary will help quite a lot.

**Comment by TheRealM18** [comment]
might have been fixed in 1.10.2 latest though the one in 1.7.10 is massively broken

**Comment by aidancbrady** [comment]
Copper is in the ore dictionary, interaction issues are not on my end.
