### ISSUE TITLE
Seems that WailaPLUGIN still have some problem with mekanism occasionally

### ISSUE THREAD

**Issue by lightning02** [aidancbrady/Mekanism#3635]
http://pastebin.com/pDCCP7mL
Is there something that can be done on your side? or I have to report them only?
btw this is the first time it happens on client initializing using latest Mekanism version for 1.7.10

**Comment by Utildayael** [comment]
WAILA has a bunch of issues with Mek it seems. Most of the time it reports the Mek block as something other than what it is... else I apparently am processing ore using only rotary condensers. :)

**Comment by aidancbrady** [comment]
The issue you're reporting is due to a mod trying to access a class in Mekanism that no longer exists. They just need to update their integration.
