### ISSUE TITLE
Induction Casing bug

### ISSUE THREAD

**Issue by TheRealM18** [aidancbrady/Mekanism#3637]
To replicate you will need to make a 4 x 4 x 4 induction battery and put a ultimate induction cell on the casing, that will give you a basic induction cell and if you click with in on the ultimate induction provider it will give you the correct cell. I found this out in creative though i though it might be a creative only bug but it is both.

to replicate it use the builds 9.1.1.290 on all of them.

**Comment by aidancbrady** [comment]
Fixed in dev, thanks!
