### ISSUE TITLE
[1.10.2-9.1.1.] Logistical sorter sound bug

### ISSUE THREAD

**Issue by tipilu** [aidancbrady/Mekanism#3638]
No idea why, no matter whether Mekanism sounds enabled/disabled, when Logical Sorter is working, it is not emitting 'Click' sound. Instead, it emits 'Eerie noise'.

**Comment by aidancbrady** [comment]
Likely a resource pack issue, I can't reproduce this.

**Comment by thiakil** [comment]
I'm getting this on FTB Beyond

**Comment by thiakil** [comment]
@aidancbrady I've managed to reproduce this in a dev environment - it only happens when using a separate server and client (dedicated server?)

Basic setup, one filter
![2017-05-06_10 53 20](https://cloud.githubusercontent.com/assets/1788847/25769388/f56c86de-324a-11e7-9c75-29874d5f8a93.png)
