### ISSUE TITLE
Pipe Connections - Weird Visual Bug Mek 9.1.1

### ISSUE THREAD

**Issue by Utildayael** [aidancbrady/Mekanism#3639]
Got a weird one for you, so weird it required screenshots!

Seems pipe connections in 9.1.1 are doing weird things. They still work fine, they just visually look really weird. I had same issue connecting mechanical pipe to an extra utils drum as I did a pressurized pipe coming out of a Mek gas tank.

http://imgur.com/a/Shu4q

Note in the screenshot the "ghost" connector and the weird random connector that goes off in some other direction. The one that has the gas in it is the proper direction. 

Reproduce? Easy. Place drum/gas tank/whatever. Place pipe. Use configurator to set pipe to extra.

Again, pipes function fine but the connection graphics get weird like that. Not sure if due to the fix for the mechanical pipe render bug from 9.1.0 or not.

Bug is in Mekanism 9.1.1

Cheers

**Comment by Utildayael** [comment]
Did some more testing, it seems to be mainly pressure and mechanical pipes that do this.

**Comment by Utildayael** [comment]
Another screenshot showing mechanical pipe from Evap Tower with lithium going to Rotary Condenser

http://imgur.com/a/a01hQ4

**Comment by Utildayael** [comment]
Edit: I typo'd and for some reason Git isn't letting me edit.

It's ALL pipes. Just connected a logistics pipe to a crystalizer and it connected itself to the ground once I set pipe to pull. I think the issue specifically is when you set the pipes to "extract"  ... still works, just visually doesn't look like it connects or does the weird ghost fluid/gas bug as in the screenshots. :)

**Comment by aidancbrady** [comment]
Should be fixed in dev.
