### ISSUE TITLE
Cables ignore other multiparts

### ISSUE THREAD

**Issue by feldim2425** [aidancbrady/Mekanism#3640]
The Cables and Pipes in Mekanism don't make a Occlusion Test so they ignore if there is a multipart that blocks the connection. 
![2016-08-13_18 06 29](https://cloud.githubusercontent.com/assets/6705744/17644196/adf5565a-6180-11e6-8af6-2429b2f35e30.png)
EDIT: In this case the stone cover is made with Chisels & Bits

**Comment by aidancbrady** [comment]
Mekanism does not currently have Chisel & Bits compatibility.

**Comment by feldim2425** [comment]
Thats a thing thats build into MCMultiparts. There is a class called OcclusionHelper and this class has a method called occlusionTest or slotOcclusionTest. This Methods check if the cable collides with any other multiparts.
