### ISSUE TITLE
java.lang.NoClassDefFoundError: mcmultipart/block/BlockMultipartContainer

### ISSUE THREAD

**Issue by Lammi2000** [aidancbrady/Mekanism#3642]
hi, i installed the correct versions of forge and mekanism, but still MC crashes. I've treid 1.7.10 first, that seemed to work at first, but crashed later. 1.9.4 crashes already when I attempt to launch.
I've attached the crash report.

[crash-2016-08-13_20.41.32-client.txt](https://github.com/aidancbrady/Mekanism/files/416723/crash-2016-08-13_20.41.32-client.txt)

**Comment by aidancbrady** [comment]
Install McMultipart.
