### ISSUE TITLE
MDK is not usable as it references classes outside the API

### ISSUE THREAD

**Issue by bdew** [aidancbrady/Mekanism#3645]
Some classes in the MDK/API reference mekanism.client.render and mekanism.common.capabilities packages, so it can't be used directly without the rest of the sources, kinda defeating the purpose.

Also is there an official gradle/maven repository to use in dependencies?

**Comment by LemADEC** [comment]
Any update on this?

**Comment by aidancbrady** [comment]
I'll fix this over the weekend, thanks for the reminder!
