### ISSUE TITLE
Block highlight broken with a running turbine

### ISSUE THREAD

**Issue by feldim2425** [aidancbrady/Mekanism#3650]
With Turbine:
![2016-08-14_23 52 27](https://cloud.githubusercontent.com/assets/6705744/17652354/6671a52c-627a-11e6-9f07-08421390171a.png)
Turbine multiblock broken:
![2016-08-14_23 52 50](https://cloud.githubusercontent.com/assets/6705744/17652355/690683d4-627a-11e6-8ceb-e1d74f27a15d.png)

I tested it some more and it seems like the turbine needs steam in it and there has to be a Machanical Pipe that gets rendered (seems like it doesn't matter if there is a Fluid in the Pipe) to break the block highlight

Edit:
Forge 1.10.2 - 12.18.1.2064
Mekansim 9.1.1.290

**Comment by aidancbrady** [comment]
Fixed in dev, thanks!
