### ISSUE TITLE
Crash upon overworld load after dying in nether

### ISSUE THREAD

**Issue by TheGuyRunningSouth** [aidancbrady/Mekanism#3651]
Using FTB Unstable 1.9 with Mekanism added.
Log File: https://gist.github.com/TheGuyRunningSouth/1371e796f43169918044361dd94fd004
Crash Report: https://gist.github.com/TheGuyRunningSouth/2386d2d36128c621be57f5ee1663454e

**Comment by feldim2425** [comment]
Issue #3641 is the same.

**Comment by TheGuyRunningSouth** [comment]
Alright. Missed that somehow. Thanks.
