### ISSUE TITLE
[1.10.2] [Bug] Something to do with OpenGL

### ISSUE THREAD

**Issue by Dijkstra1** [aidancbrady/Mekanism#3653]
When crafting the second tier of tank, my client crashes [crash report](https://github.com/aidancbrady/Mekanism/files/417759/Bug.mek.or.tinkers.txt) and will crash ever time i join the server I know enough about OpenGL to tell that bug has something to do with OpenGL but that is it. It us my understand that the LWJGL uses on thread for rendering, and differnt one for updating and some crafting the second tier tank is trying to render it on the update thread, which OpenGL has not been setup. At first I thought the @slimeknights might be to blame rendering items on the [Tinkers Construct](https://github.com/SlimeKnights/TinkersConstruct) crafting table but after disable that feature in config my client still crashes when I join the server.

Disclaimer - Do not trust anything I say about OpenGL or the LWJGL as it most likely wrong.

**Comment by tipilu** [comment]
Putting Adv Solars/Fluid tank into crafting station crashes client each time chunk with the table is loaded, no matter if Table Contents Rendering is enabled or not.
