### ISSUE TITLE
Unnecessary instantiation of Thread objects

### ISSUE THREAD

**Issue by blay09** [aidancbrady/Mekanism#3654]
All of the packet handlers are instantiating new `Thread`s, when all that is really needed here are `Runnable`s.

See [PacketConfigurationUpdate.java#L36](https://github.com/aidancbrady/Mekanism/blob/26b20504cd7bb50088322b98c227652b43f368f1/src/main/java/mekanism/common/network/PacketConfigurationUpdate.java#L36) for example.

They are [then just casted up to](https://github.com/aidancbrady/Mekanism/blob/26b20504cd7bb50088322b98c227652b43f368f1/src/main/java/mekanism/common/PacketHandler.java#L270) `Runnable`s [further down the line](https://github.com/aidancbrady/Mekanism/blob/26b20504cd7bb50088322b98c227652b43f368f1/src/main/java/mekanism/common/CommonProxy.java#L661), so them being `Thread`s in the first place is a waste in terms of memory allocation and performance (see Thread.java for the overhead that's happening for every packet at the moment).

**Comment by TitaniumSapphire** [comment]
Submit a PR.

**Comment by aidancbrady** [comment]
Done!
