### ISSUE TITLE
[performance] assemblicator with formula does useless recipe search each tick

### ISSUE THREAD

**Issue by cobra** [aidancbrady/Mekanism#3655]
Formulaic Assemblicators are doing a full recipe search in the doSingleCraft() method, which is being called each tick by onUpdate(), even when they can't do anything AND have a crafting formula set. This is creating a considerable load on the server. In my world with 5 assemblicators (all have formulas set) it's the biggest load before mobs, with a whopping 13.6% of the total server thread run time spent on TileEntityFormulaicAssemblicator.onUpdate(). I don't want to imagine what happens with a large number of assemblicators in a larger modpack (compressed cobblestone farm, anyone?).

I think the recipe search should be skipped altogether when a crafting formula is present and the result should really be cached otherwise.

**Comment by aidancbrady** [comment]
Fixed in dev.
