### ISSUE TITLE
[1.10.2-9.1.1.290]Breaking a Pressurized Tube with a Pick Crashes client

### ISSUE THREAD

**Issue by AlphaKintari** [aidancbrady/Mekanism#3656]
See title, but tried with a wrench, no issue.  Doing additional testing, Seems to be any type of pick, Tried standard Minecraft picks and Tinkers' Construct ones. 
I'll update as I get more info.

Log:
http://paste.ee/p/O7Axa

**Comment by aidancbrady** [comment]
Update MCMP :)

**Comment by AlphaKintari** [comment]
Thank you!  That indeed fixed the issue.
