### ISSUE TITLE
[1.10.2] Server spits out "Error executing task"

### ISSUE THREAD

**Issue by TheDarknessEmperor** [aidancbrady/Mekanism#3657]
So i have built a Dynamic Tank that is 5x5 with glass on every side including top and bottom with 2 valves on the center of the top and bottom. When i right click it, nothing happens other than this error being spit out in the server console. It doesn't crash anything but gets really annoying as i can't access the menu. I haven't tested this but i think it might be because of other machines beside it.
Error: http://pastebin.com/FimZvHeq
Modlist: http://pastebin.com/rL9g4eca

**Comment by aidancbrady** [comment]
Fixed in dev, thanks!
