### ISSUE TITLE
[Suggestion] Induction Matrix Changes

### ISSUE THREAD

**Issue by Utildayael** [aidancbrady/Mekanism#3659]
Some thoughts on the Induction Matrix and some changes that would be nice...

1. It's kind of boring. Honestly. Compared to turbine and other multis it's pretty plain. However! I have an idea to make it a little nicer. Allow structural glass [or some new glass] to be used in the side/top/bottom panels. Basically make it follow the dynamic tanks build rules in that the outside frame has to be the normal induction blocks but the rest can be some form of glass. Why? You spent the time to make nice looking textures for the various bits inside the induction matrix so let us show them off!

2. It needs more parts. Ports are fine but... it needs more. I would suggest a "control panel" much like the evap tower. This would be the point to interact with the GUI of the multiblock. 

3. I would also suggest a "redstone port" that can be configured to output a redstone signal based on various conditions such as matrix fill level. Computercraft/OpenComputers port, same deal but you can guess what that would be used for.

Love the multiblock but it's just feeling a little sad after all the great updates in v9.

Cheers

**Comment by aidancbrady** [comment]
#1 is already possible :)
#2, while a good idea, goes against my system of controller-less multi blocks that I utilize.
#3 is an awesome idea, I'll look into it!

**Comment by Utildayael** [comment]
What I can use structural glass now?? Could have sworn I tried. Will do again! Sweet!!

Mostly the controller idea was for the aesthetics of having a control panel. Looks neat. :)

Thanks much sir!
