### ISSUE TITLE
Crash and no power from ender io

### ISSUE THREAD

**Issue by BlackMist1035** [aidancbrady/Mekanism#3660]
when items over lapp on tinker table
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.61-dev-51.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.41-beta.jar)
  LoadingHook (Mekanism-1.10.2-9.1.1.290.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 8/16/16 12:32 AM
Description: Rendering item

java.lang.IllegalStateException: Not building!
	at net.minecraft.client.renderer.VertexBuffer.func_178977_d(VertexBuffer.java:713)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
	at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:164)
	at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:135)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:198)
	at net.minecraft.client.renderer.RenderItem.func_184390_a(RenderItem.java:439)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:478)
	at net.minecraft.client.gui.GuiIngame.func_184044_a(GuiIngame.java:1192)
	at net.minecraft.client.gui.GuiIngame.func_180479_a(GuiIngame.java:566)
	at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:329)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:140)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1369)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.VertexBuffer.func_178977_d(VertexBuffer.java:713)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
	at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:164)
	at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:135)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:198)
	at net.minecraft.client.renderer.RenderItem.func_184390_a(RenderItem.java:439)

-- Item being rendered --
Details:
	Item Type: slimeknights.tconstruct.tools.item.Hammer@79e8911a
	Item Aux: 416
	Item NBT: {StatsOriginal:{AttackSpeedMultiplier:1.0f,MiningSpeed:5.4750004f,FreeModifiers:3,Durability:620,HarvestLevel:1,Attack:3.25f},Stats:{AttackSpeedMultiplier:1.2f,MiningSpeed:11.698643f,FreeModifiers:1,Durability:1120,HarvestLevel:4,Attack:4.25f},Special:{Categories:[0:"weapon",1:"tool",2:"harvest"],RepairCount:15},TinkerData:{UsedModifiers:2,Materials:[0:"copper",1:"copper",2:"iron",3:"copper"],Modifiers:[0:"fortifyobsidian",1:"haste",2:"diamond"]},Modifiers:[0:{identifier:"established",color:-1204473,level:1},1:{identifier:"magnetic",color:-3487030,level:2,magnetic2:1b},2:{identifier:"fortifyobsidian",color:-10478396},3:{identifier:"haste",current:50,color:9502720,level:1,max:50,extraInfo:"49 / 50"},4:{identifier:"diamond",color:9237730}],Traits:[0:"established",1:"magnetic2"]}
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:478)
	at net.minecraft.client.gui.GuiIngame.func_184044_a(GuiIngame.java:1192)
	at net.minecraft.client.gui.GuiIngame.func_180479_a(GuiIngame.java:566)
	at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:329)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:140)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Dvd1035'/411, l='MpServer', x=210.98, y=68.00, z=253.81]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (236,64,256), Chunk: (at 12,4,0 in 14,16; contains blocks 224,0,256 to 239,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 874981 game time, 883229 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 32 total; [EntitySheep['Sheep'/208, l='MpServer', x=248.51, y=79.00, z=211.72], EntityPig['Pig'/209, l='MpServer', x=249.25, y=94.00, z=221.51], EntitySheep['Sheep'/210, l='MpServer', x=248.94, y=66.00, z=319.47], EntitySheep['Sheep'/211, l='MpServer', x=249.95, y=66.00, z=319.55], EntitySheep['Sheep'/212, l='MpServer', x=249.50, y=65.00, z=311.21], EntitySkeleton['Skeleton'/280, l='MpServer', x=274.50, y=34.00, z=264.50], EntityMinecartChest['Minecart with Chest'/281, l='MpServer', x=282.50, y=20.06, z=331.50], EntitySheep['Sheep'/282, l='MpServer', x=282.18, y=62.29, z=328.74], EntitySheep['Sheep'/154, l='MpServer', x=222.49, y=71.00, z=176.19], EntitySheep['Sheep'/155, l='MpServer', x=225.48, y=70.00, z=171.67], EntityPlayerSP['Dvd1035'/411, l='MpServer', x=210.98, y=68.00, z=253.81], EntityCreeper['Creeper'/158, l='MpServer', x=221.50, y=45.00, z=259.50], EntityPigZombie['Zombie'/159, l='MpServer', x=218.75, y=75.00, z=256.49], EntityCow['Cow'/97, l='MpServer', x=153.73, y=64.00, z=183.50], EntityCow['Cow'/98, l='MpServer', x=151.58, y=65.00, z=194.20], EntityCow['Cow'/99, l='MpServer', x=159.26, y=66.00, z=190.14], EntityCow['Cow'/100, l='MpServer', x=158.08, y=67.00, z=199.10], EntitySkeleton['Skeleton'/101, l='MpServer', x=141.69, y=15.00, z=288.51], EntityCow['Cow'/109, l='MpServer', x=171.53, y=72.00, z=299.15], EntitySheep['Sheep'/241, l='MpServer', x=265.90, y=97.00, z=216.48], EntitySheep['Sheep'/242, l='MpServer', x=259.75, y=98.00, z=215.61], EntityPig['Pig'/243, l='MpServer', x=257.51, y=93.00, z=231.97], EntityPig['Pig'/244, l='MpServer', x=263.59, y=95.00, z=228.27], EntitySheep['Sheep'/245, l='MpServer', x=258.21, y=97.00, z=225.20], EntitySheep['Sheep'/181, l='MpServer', x=231.70, y=67.00, z=175.70], EntityCreeper['Creeper'/182, l='MpServer', x=229.83, y=85.00, z=218.20], EntityPig['Pig'/246, l='MpServer', x=259.32, y=96.00, z=227.48], EntityCreeper['Creeper'/183, l='MpServer', x=232.50, y=36.00, z=311.50], EntityMinecartChest['Minecart with Chest'/247, l='MpServer', x=264.50, y=16.06, z=331.50], EntityCow['Cow'/124, l='MpServer', x=186.77, y=72.00, z=223.58], EntityEnderman['Enderman'/444, l='MpServer', x=163.50, y=69.00, z=208.50], EntityEnderman['Enderman'/446, l='MpServer', x=183.50, y=68.00, z=185.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:496)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1132880240 bytes (1080 MB) / 2355589120 bytes (2246 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.32 Powered by Forge 12.18.1.2016 Optifine OptiFine_1.10.2_HD_U_C2 32 mods loaded, 32 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2016-failtests.jar) 
	UCHIJAAAA	Forge{12.18.1.2016} [Minecraft Forge] (forge-1.10.2-12.18.1.2016-failtests.jar) 
	UCHIJAAAA	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCHIJAAAA	BiomesOPlenty{4.1.0.2052} [Biomes O' Plenty] (BiomesOPlenty-1.9.4-4.1.0.2052-universal.jar) 
	UCHIJAAAA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.9.4-2.0.0-40.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.0.1.jar) 
	UCHIJAAAA	JEI{3.7.8.234} [Just Enough Items] (jei_1.10.2-3.7.8.234.jar) 
	UCHIJAAAA	BloodMagic{1.9.4-2.0.3-52} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.3-52.jar) 
	UCHIJAAAA	Chameleon{1.9.4-2.1.6} [Chameleon] (Chameleon-1.9.4-2.1.6.jar) 
	UCHIJAAAA	mcmultipart{1.2.0_72} [MCMultiPart] (MCMultiPart-experimental-1.2.0_72-universal.jar) 
	UCHIJAAAA	chiselsandbits{10.2} [Chisels & Bits] (chiselsandbits-10.2.jar) 
	UCHIJAAAA	ElecCore{1.5.292} [ElecCore] (ElecCore-1.9.4-1.5.292.jar) 
	UCHIJAAAA	deepresonance{1.2.0beta35} [DeepResonance] (deepresonance-1.9.4-1.2.0beta35.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.41-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.41-beta.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-Mod-1.9.4.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.0.1.73_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.73_beta.jar) 
	UCHIJAAAA	inventorytweaks{1.61-dev-51-698bcef} [Inventory Tweaks] (InventoryTweaks-1.61-dev-51.jar) 
	UCHIJAAAA	IronChest{7.0.7.795} [Iron Chest] (ironchest-1.10.2-7.0.7.795.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
	UCHIJAAAA	llor{1.1.0-mc[1.9-1.10.2]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.0-mc[1.9-1.10.2].jar) 
	UCHIJAAAA	mantle{1.10-0.10.3.jenkins156} [Mantle] (Mantle-1.10-0.10.3.jar) 
	UCHIJAAAA	Mekanism{9.1.1} [Mekanism] (Mekanism-1.10.2-9.1.1.290.jar) 
	UCHIJAAAA	MekanismGenerators{9.1.1} [MekanismGenerators] (MekanismGenerators-1.10.2-9.1.1.290.jar) 
	UCHIJAAAA	MekanismTools{9.1.1} [MekanismTools] (MekanismTools-1.10.2-9.1.1.290.jar) 
	UCHIJAAAA	progressiveautomation{1.6.48} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.48.jar) 
	UCHIJAAAA	Psi{r1.0-37} [Psi] (Psi-r1.0-37.jar) 
	UCHIJAAAA	rftools{5.06} [RFTools] (rftools-1.10-5.06.jar) 
	UCHIJAAAA	rftoolsdim{4.30beta46} [RFTools Dimensions] (rftoolsdim-1.10-4.30beta46.jar) 
	UCHIJAAAA	roots{0.109} [Roots] (roots-1.10.2-0.109.0.jar) 
	UCHIJAAAA	StorageDrawers{1.9.4-3.2.1} [Storage Drawers] (StorageDrawers-1.9.4-3.2.1.jar) 
	UCHIJAAAA	tconstruct{1.10-2.3.3a.jenkins271} [Tinkers' Construct] (TConstruct-1.10-2.3.3a.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.61-dev-51.jar)
  invtweaks.forge.asm.ContainerTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.41-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
LoadingHook (Mekanism-1.10.2-9.1.1.290.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13447 Compatibility Profile Context 20.19.0.32832' Renderer: 'AMD Radeon(TM) R7 Graphics'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/The%207700/AppData/Roaming/.minecraft/mods/Mekanism-1.10.2-9.1.1.290.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/The%207700/AppData/Roaming/.minecraft/mods/Mekanism-1.10.2-9.1.1.290.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/The%207700/AppData/Roaming/.minecraft/mods/Mekanism-1.10.2-9.1.1.290.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/The%207700/AppData/Roaming/.minecraft/mods/Mekanism-1.10.2-9.1.1.290.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/The%207700/AppData/Roaming/.minecraft/mods/Mekanism-1.10.2-9.1.1.290.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/The%207700/AppData/Roaming/.minecraft/mods/Mekanism-1.10.2-9.1.1.290.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/The%207700/AppData/Roaming/.minecraft/mods/Mekanism-1.10.2-9.1.1.290.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/The%207700/AppData/Roaming/.minecraft/mods/Mekanism-1.10.2-9.1.1.290.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/The%207700/AppData/Roaming/.minecraft/mods/Mekanism-1.10.2-9.1.1.290.jar!/cofh/api/energy/TileEnergyHandler.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/The%207700/AppData/Roaming/.minecraft/mods/Mekanism-1.10.2-9.1.1.290.jar!/cofh/api/energy/TileEnergyHandler.class

	Launched Version: 1.10.2-forge1.10.2-12.18.1.2016-failtests
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) R7 Graphics GL version 4.5.13447 Compatibility Profile Context 20.19.0.32832, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A10-7700K Radeon R7, 10 Compute Cores 4C+6G
	OptiFine Version: OptiFine_1.10.2_HD_U_C2
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13447 Compatibility Profile Context 20.19.0.32832
	OpenGlRenderer: AMD Radeon(TM) R7 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by tipilu** [comment]
Actually Tinker Table is bugged, and will insta crash when some items from other mods inserted

**Comment by BlackMist1035** [comment]
Thanks for letting me know

**Comment by tipilu** [comment]
For sure it crashes when You insert Advanced Solars or Fluid Tank. Every player which will load chunk containing this table with bugged items, client will crash.

**Comment by aidancbrady** [comment]
Yeah, I've done about all my can to fix this silly TC issue.
