### ISSUE TITLE
[1.10.2-9.1.1] Unable to craft Crafting Formula

### ISSUE THREAD

**Issue by tipilu** [aidancbrady/Mekanism#3661]
The Crafting Formula cannot be crafted using given recipe:

![2016-08-16_16 56 03](https://cloud.githubusercontent.com/assets/21001212/17704097/32899804-63d4-11e6-9312-00077bb21427.png)

While in crafting table it doesn't produce anything:

![2016-08-16_16 56 29](https://cloud.githubusercontent.com/assets/21001212/17704105/40b1d720-63d4-11e6-96f0-344f03d4fe96.png)

**Comment by aidancbrady** [comment]
Fixed in dev, thanks!
