### ISSUE TITLE
Mekanism Digital Miner Dissapearing

### ISSUE THREAD

**Issue by ZiggyAdventures** [aidancbrady/Mekanism#3662]
The mekanism Digital Miner has been disappearing for many players over a couple of weeks now. All the cases I know have been on servers. Unfortunately no logs. https://github.com/whatthedrunk/allthemods/issues/90
Hopefully this little information can help.

**Comment by aidancbrady** [comment]
I'm unable to reproduce this. Make sure the server admin has not disabled Digital Miners in the config.

**Comment by akitainuowner** [comment]
This just happened to me too was after I went to nether came back no miner, and it wasnt stolen as I am doing single player
