### ISSUE TITLE
[Feature Request] Cables

### ISSUE THREAD

**Issue by Stuart74** [aidancbrady/Mekanism#3664]
Currently the method to break mekanism cables is long and tiring and unless I am missing something there is no easy way of breaking and removing the cables except mining them which if you have a lot of cables to remove takes way too long. 

I do believe back in 1.7.10 you could use the thermal expansion crescent hammer to easily remove cables but in 1.10.2 there is currently no wrench that does this. Maybe include your own or maybe allow the use of EnderIO's Yeta Wrench to be able to remove cables this would make it a lot easier.

**Comment by Utildayael** [comment]
You have to use the configurator and switch its mode to "wrench"

That said, I do wish Mek cables were compatible with other wrenches. I really, really hate the mode selector to flip through all the modes of configurator just to get to wrench mode to break some cables.

I have a love/hate with the fact that using a pickaxe on them requires WAAAAY too much effort. On the love side, I don't accidently break my Mek cables [probably what @aidancbrady intended] but on the hate side, I have to pull out a configurator if I want to break more than just a couple cables unless I want to stand there for an hour. :)

**Comment by Stuart74** [comment]
I wasn't aware of the configurator so thanks for that, I still think it be nice to have it be able to still be hard to break but be able to use a yeta wrench or similar to break them like how thermal expansions crescent hammer was compatable with pretty much all cables or conduits.

**Comment by aidancbrady** [comment]
This kind of support can't be added until more mods start supporting capabilities
