### ISSUE TITLE
portable teleporter bug

### ISSUE THREAD

**Issue by blanas** [aidancbrady/Mekanism#3666]
Hey there i need a fix fro this IMPORTANT bug . It does not happen every time but it will happen sooner or  later when i try to teleport . first i press teleport on the portable teleporter . then it teleports me , and then the screen turns blue , and then i crush and get this crush log
[crash-2016-08-17_11.21.10-client.txt](https://github.com/aidancbrady/Mekanism/files/422084/crash-2016-08-17_11.21.10-client.txt)

**Comment by aidancbrady** [comment]
Fixed in development
