### ISSUE TITLE
1.10.2 pipe removal

### ISSUE THREAD

**Issue by Frontrider** [aidancbrady/Mekanism#3668]
I could not find any tool to effectively remove pipes. No wrench seems to work (I tried ender io,extra utilities and rf tools). 

or just reduce their hardness so its not annoying to remove them with normal tools?

**Comment by moondust3** [comment]
If you change the mode on the Configurator to Wrench mode, it will act like a wrench for removing pipes and machines. I'm pretty sure you don't need power to use this mode.

Although, I would still like to see integration with other mods' wrenches, as I prefer to use the Configurator for configuring, and it can be semi-annoying to switch modes often.

**Comment by Frontrider** [comment]
I gave that multiple tries, but I can't change the modes on that. I was able to do on the disassembler, but not on the configurator.

**Comment by tipilu** [comment]
Check keyboard bindings in options. Configurator has **Wrench mode** which allows for safe cables/pipes removal.

**Comment by Frontrider** [comment]
I already rebound that. That was the exact first thing I've done after starting that world. modeswitch, shift+modeswitch, nothing happens.
On shift modeswitch, I hear my jetpack but nothing actually happens.

Its pretty strange tough, that the dissassembler reacts to shift-right click, and not the supposed mode switch.

**Comment by Utildayael** [comment]
Using 1.10.2 and it works fine. I set my mode button as N so while holding the configurator I just hit shift-N to cycle modes.

**Comment by Frontrider** [comment]
I would update the record: the function doesn't works, if its bound to
anything other than a key on the English keyboard.

2016-08-28 0:08 GMT+02:00 Aidan <notifications@github.com>:

**Comment by HellishINC** [comment]
@Utildayael Could you post a screenshot to what keybind you're talking about? I have tried using the "item mode" as well as "armor mode" but neither do anything for me.
