### ISSUE TITLE
Robit Crash upon placing on chargepad

### ISSUE THREAD

**Issue by Arcanatias** [aidancbrady/Mekanism#3669]
[crash-2016-08-18_10.34.20-client.txt](https://github.com/aidancbrady/Mekanism/files/425301/crash-2016-08-18_10.34.20-client.txt)

Not sure if you can see the crash report but I am getting this everytime I try to place a Robit on a Chargepad to Initialize it. Pretty sure the crash is caused by Entity's Vehicle: ~~ERROR~~ NullPointerException: null. I am using the latest release of Mekanism. (9.1.1.290 for 1.10.2)

**Comment by tipilu** [comment]
Seems like its crashing on setting Robbit's home:

`homeLocation.write(nbtTags);`

**Comment by TitaniumSapphire** [comment]
@tipilu Yes, and it's an NPE, so maybe its home location is null

**Comment by HeavyDeception** [comment]
Ah so this is a thing. So as long as you don't look at him you can stay in the game.
anyone know of a fix?

**Comment by BaalEvan** [comment]
It's Propably Wawla related issue (same problem with OpenComputers Drones)

**Comment by thommy101** [comment]
Already fixed in 9f4c73ee9400f8c5e89709c5b58b27f01037e416
