### ISSUE TITLE
1.7.10 object with meta unique identifiers

### ISSUE THREAD

**Issue by TitaniumSapphire** [aidancbrady/Mekanism#3670]
I can't seem to find what the unique identifiers for the Mekanism ores are. I assumed that they are `Mekanism:OreBlock.<OreName>`, for example, for Osmium Ore, it would be `Mekanism:OreBlock.OsmiumOre`. But this does not exist in the item registry (yes, my mod is loading after Mekanism). What are the names for the ore blocks so that I can reference them?

**Comment by TitaniumSapphire** [comment]
And this question also follows for dusts, ingots, clumps, etc... I can't figure out these multi-id items. I will edit the title for clarification.

**Comment by bookerthegeek** [comment]
Using mod tweaker is useful. Type /mt hand and it should give you the name and meta data you need.

**Comment by TitaniumSapphire** [comment]
@bookerthegeek Thanks for the help. I got this result from that command while holding a block of Osmium Ore: 
![output](https://cloud.githubusercontent.com/assets/7462892/17796957/867eb088-6579-11e6-86fc-0a2573b3322f.PNG)
What does this mean by "is in"?

**Comment by TehStoneMan** [comment]
<Mekanism:OreBlock> is the id of the block itself.
<ore:oreOsmium> is the ore dictionary entry that the block is in.
You would probably want to use the ore dictionary entry in case another mod also adds osmium ore.

**Comment by bookerthegeek** [comment]
Yep. The "is in" can have multitude of entries as items can have multiple ore dictionary entries
