### ISSUE TITLE
[1.10.2] Crash when pulling energy from turbine

### ISSUE THREAD

**Issue by Cyrilshark** [aidancbrady/Mekanism#3671]
I've had no problems with Mekanism before now.
I have created an industrial turbine, then I placed down a basic universal cable attached to an energy storage block (can't recall the name). When I tried to set the cable to "pull", my game crashed. I now can not load my world.

Not sure what reports you need, hopefully these will suffice.
[crashreport.txt](https://github.com/aidancbrady/Mekanism/files/425876/crashreport.txt)
[gameoutput.txt](https://github.com/aidancbrady/Mekanism/files/425877/gameoutput.txt)

**Comment by TitaniumSapphire** [comment]
It looks like the turbine doesn't implement a certain interface. What mod is an "industrial turbine" from?

**Comment by Cyrilshark** [comment]
Mekanism v9?

**Comment by TitaniumSapphire** [comment]
Heh, sorry, I'm used to older versions. From looking through the source, I can't find a problem directly besides that maybe the turbine doesn't implement a few interfaces, but that seems unlikely. Good luck :)

**Comment by aidancbrady** [comment]
Fixed in development.
