### ISSUE TITLE
Oredictionificator refuses ore dictionary registrations with colons in their name

### ISSUE THREAD

**Issue by UntouchedWagons** [aidancbrady/Mekanism#3672]
OpenComputers adds its own version of End Stone (don't know why really) and registers that and the vanilla end stone under the ore dictionary registration "oc:stoneEndstone" but the Oredictionificator refuses to let me enter the colon into the filter GUI. I can copy/paste "oc:stoneEndstone" but it still gets refused.

I don't think the Oredictionificator really should worry about whether or not a registration name is valid and leave that to Forge.

**Comment by VT-14** [comment]
End Stone in the ore dictionary is "endstone"  while oc:stoneEndstone looks like the item name call for things like the /give command.

http://www.minecraftforge.net/wiki/Common_Oredict_names

Does the wildcard * work with the Oredictionificator?  If so, "*ndstone" might give you what you want.

**Comment by UntouchedWagons** [comment]
No you can't put a * in the Oredictionificator.

**Comment by UntouchedWagons** [comment]
Yeah the oredictionificator doesn't work. I tried itemSilicon and it wouldn't accept that either.

**Comment by UntouchedWagons** [comment]
Still doesn't work in 9.2.0.292

**Comment by VT-14** [comment]
As seen in #3707, the Oredictionificator only works with certain oreDictionary flags for balance purposes.

**Comment by UntouchedWagons** [comment]
I can't even convert wood planks. What *can* I convert?

**Comment by VT-14** [comment]
Probably ores, at least the common ones.  same for ingots, and maybe dusts.

I don't think i have ever actually used the Oredictionificator.
