### ISSUE TITLE
Digital Miner Problems

### ISSUE THREAD

**Issue by WarMind666** [aidancbrady/Mekanism#3676]
I am running a 1.10.2 server, and the Digital Miner will find ores, but will not pull them up, and I cannot connect anything to the back of it, where it ejects the items it pulls up.  I tried the logistical pipes from the mod itself, and they will not interface with the digital miner.  I have it powered by two advanced solar panels, and even though it isn't pulling up any ores, it is still pulling power.  I am running version 290 of the mod, I updated from 288, where the same issues were taking place.

**Comment by Stuart74** [comment]
I am also suffering the same issue 

mekanism version 290
Forge 2056

**Comment by LuciDuki** [comment]
Hi Hi Guys.


I' ve also this Problem.

But only on my Server.
In SP it works perfect.

I've tested it on three different Servers and it never worked.
I use Mekanism 9.1.0, Minecraft 1.7.10 (Forge 1614) in Bevos TechPack.

Hope this can be fixed soon.



Best Regards

Luci

**Comment by iPencil** [comment]
1.10.2, same issue. Works on single player, doesn't work on servers. :/

**Comment by bookerthegeek** [comment]
Odd, works over on our network. This is most likely a permission missing that your server staff will need to fix as this is not an error in the mod.

**Comment by Stuart74** [comment]
Odd that we are running pure forge no plugins etc where do you get these "permissions" from ????? I think you should elaborate on thing a bit more than just blaming non existent permissions from a forge server that is running no plugins.

**Comment by LuciDuki** [comment]
Strange. I am op on this server... so i have all permissions.
Without op i can't use the mekanism  blocks/machines/items...

**Comment by Stuart74** [comment]
After going through some older issues that were the same problem you need to op the fake player for mekanism  which is /mk op 

I am assuming this is still just as valid irrespective of the version being 1.7.10 or 1.10.2 the fakeplayer side would not of changed since then 

https://github.com/aidancbrady/Mekanism/issues/2909
