### ISSUE TITLE
Crash when pumping items into a colossal chest

### ISSUE THREAD

**Issue by phit** [aidancbrady/Mekanism#3677]
**Reproduction**:
create a colossal chest, connect any logistical transporter to its core and pump items in it from any inventory, you crash as soon as the item is inserted into the chest

**Crashlog**: http://vpaste.net/SKbY0

**relevant mod versions**:
Forge 12.18.1.2065
ColossalChests-1.9.4-1.3.9.jar
MCMultiPart-1.2.1-universal.jar
Mekanism-1.10.2-9.1.1.290.jar

**Comment by aidancbrady** [comment]
Mekanism follows ISidedInventory as it's supposed to be following, ColossalChests is doing something wrong.
