### ISSUE TITLE
Crash on startup for EnergyCube (1.7.10 latest build)

### ISSUE THREAD

**Issue by DraksterAU** [aidancbrady/Mekanism#3680]
Hi Aidan,

I've got an issue where a world fails to load on restart.... IC2 is trying to load meks energy cube into the EnergyNet and it has an NPE?

If this isn't mechanism, any advice would be appreciated man..

http://pastebin.com/TzUbFbVr

**Comment by aidancbrady** [comment]
Report this to IC2, I'm doing everything right on my end.
