### ISSUE TITLE
[1.10.2-9.1.1.290] Mechanical pipe render causing to crash

### ISSUE THREAD

**Issue by tipilu** [aidancbrady/Mekanism#3681]
As in the title, it crashes in 50/50 chance when player will spawn in chunk which has mechanical pipes near.

Crashlog:

[crash-2016-08-21_16.11.39-client.txt](https://github.com/aidancbrady/Mekanism/files/428884/crash-2016-08-21_16.11.39-client.txt)

**Comment by VT-14** [comment]
Looks like a rendering crash, and you have Optifine.  Try it without Optifine.

**Comment by aidancbrady** [comment]
Fixed in dev.
