### ISSUE TITLE
universal cable crash

### ISSUE THREAD

**Issue by DnTheMn** [aidancbrady/Mekanism#3683]
Issue Description: using universal cable, connecting to Laser Relay, causes server to crash, any time this chunk loads the server crashes.

What happens: Ticking block entity

What you expected to happen: provide power.

Steps to reproduce:

1.connect universal power cable to laser relay.

Version of All the Mods:13c

Added mods (Optifine, Fastcraft, etc.): none

crash report.
http://pastebin.com/m2tH74iU

**Comment by aidancbrady** [comment]
Fixed in dev, thanks!
