### ISSUE TITLE
[Question] Naming convention for ores in 1.10.2

### ISSUE THREAD

**Issue by rockobonaparte** [aidancbrady/Mekanism#3685]
I'm trying to boost Mekanism oregen using OreSpawn, which requires providing the name of the ores in a JSON file as their block names; metadata is also available. I have been trying a lot of things. For example, for copper:

mekanism:oreCopper
mekanism:oreBlock (metadata 1)
mekanism:oreBlock#type=copper

I'll be soon trying:
mekanism:oreBlock (metadata "#type=copper" if that's even legal)

It's not detecting that regardless what I do. I don't think it's a problem with oreSpawn. Really, my problem is I can't get a straightforward answer from 1.10.2 mods what these ores are named. NEI would traditionally dump that, but it didn't look like NEI was working at all. JEI was a no-go. Minetweaker is supposed to be able to dump it, but gives a bland oreBlock name w/o metadata. Finally, WAILA hasn't implemented block names yet. I figured I'd just ask at this point.

(tweaking oregen settings would be nice. I haven't even found osmium and copper yet at all).

**Comment by TehStoneMan** [comment]
You should be able to see the block ID when looking at the block with the debug (F3) screen open. It's listed in the bottom-right of the screen.

**Comment by bookerthegeek** [comment]
"F3 + H" works very well.
