### ISSUE TITLE
[1.7.10] Easy Dupe Glitch with Infusing Factory

### ISSUE THREAD

**Issue by MJRLegends** [aidancbrady/Mekanism#3686]
see https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/493 for more details because this is the post made to me by a player of my mod pack

**Comment by MJRLegends** [comment]
Im guessing this if statement is where the issue is https://github.com/aidancbrady/Mekanism/blob/1.7.10/src/main/java/mekanism/common/inventory/container/ContainerFactory.java#L214

**Comment by MJRLegends** [comment]
@aidancbrady I know your busy, but have you been able to look at this issue

**Comment by aidancbrady** [comment]
Fixed, thanks!

**Comment by MJRLegends** [comment]
Sweet thanks

**Comment by MJRLegends** [comment]
@aidancbrady where can i find a build download for this ddc9e68f8ef81f5ae3979be0cecf4cce016a2ab2
