### ISSUE TITLE
Unable to get Mechanical Pipe to connect to Purifier

### ISSUE THREAD

**Issue by TekkifyChara** [aidancbrady/Mekanism#3687]
I have tried everything, I cannot get Oxygen into it in any way. Have tried all combinations of side configs. EIO pipes will visually connect, but are not physically connected when trying to pump gasses.  [Image](http://i.imgur.com/wUH0xfv.png)

Minecraft 1.7.10 V9.1.0.281

**Comment by aidancbrady** [comment]
Not sure what a Purifier is. Regardless, calling this a mod interaction.
