### ISSUE TITLE
Logistical Transporter pipes on extract only check last item in chest

### ISSUE THREAD

**Issue by proto-chris** [aidancbrady/Mekanism#3688]
Mekanism 9.1.1.290 for 1.10.2

Logistical Transporter pipes attached to a chest on extract ignores all items before the last one.

Example setup: Furnace - Logistical transporter pipe - chest
Put poppy (or any other item not suitable for furnace) into the second (or later) slot and put wood (or any other furnice suitable item) into the first slot and the wood won't be extracted. If the poppy is removed the wood is extracted as expected.

Expected behaviour: the wood is always extracted even if a non-furnace suitable item is in a higher numbered slot.

**Comment by aidancbrady** [comment]
This has been the case since the release of Mekanism inventory-based machines and I'm afraid there's not much I can do to fix this; the functionality exists to prevent lag from iterating over large inventories.

**Comment by proto-chris** [comment]
I'm not sure how different your way to access the inventories is from the way other mods (name EnderIO) is, but maybe it could be worth looking at it at some point. It might just give the idea that's missing to make the full inventory access performant.
