### ISSUE TITLE
Server crash via watchdog, GasNetwork issue?

### ISSUE THREAD

**Issue by utoc** [aidancbrady/Mekanism#3689]
Crash here: http://pastebin.com/7JEMWPT5 and here: http://pastebin.com/dCvsmLxW

Points to Mekanism's GasNetwork and to the best of my knowledge, no other mods are using Mek's gas.  EnderIO is around but gas conduits are not available.

Running
    FML 2068
    Mekanism 9.1.1 dev version (build 290 with Tesla mod to lowercase fix)

I do not have any specifics for what the users online were doing at the time.  I have had two crashes of the server thus far.  Please let me know what troubleshooting steps I can take to better help you.

**Comment by aidancbrady** [comment]
Fixed in dev, thanks!
