### ISSUE TITLE
NPEs in server console log, report only

### ISSUE THREAD

**Issue by utoc** [aidancbrady/Mekanism#3690]
Server's latest.log: http://pastebin.com/SCpY3zAe

Starting at line 45 you get a slew of NPEs which hints at the configurator.  I don't know what action was being performed by the users.  I'm reporting this in case it can be of any use to you.

I'm running FML 2069 and Mekanism 9.1.1-homebaked (build 290 with Telsa to lowercase modid fix)

Please let me know if there are any additional steps I can take to help clarify this issue.

**Comment by aidancbrady** [comment]
Fixed in dev, thanks
