### ISSUE TITLE
[1.10.2] [Bug] Pipes stop transporting power

### ISSUE THREAD

**Issue by Dijkstra1** [aidancbrady/Mekanism#3692]
I had elite power pipes running from one cube to another cube but the power would stop part though
![2016-08-22_22 30 55](https://cloud.githubusercontent.com/assets/11648771/17925915/632e6074-69de-11e6-9d54-5e584cdbbf92.png)

and the only way i found of fixing is it breaking and replacing all the pipes that are not lit (Which is time consuming speed they break at), it should be noted that this happens on a chunk boundaries, but when it happens i do not think i would be far enough away to unload the chunks.

Also may be something else but when place pipes quickly i got [this](https://github.com/aidancbrady/Mekanism/files/434420/crash-2016-08-23_16.16.58-client.txt)

**Comment by utoc** [comment]
We're seeing similar behavior in build 290; Users are having to break and replace universal cables after chunks are reloaded.  We cannot reproduce it on command though.

**Comment by UntouchedWagons** [comment]
Are those pipes crossing a chunk boundary? I bet my Digital Miner they are. None of Mekanism's pipes (item, fluid, gas or energy) are usable on any sort of large scale setup due to this.

**Comment by aidancbrady** [comment]
Merging with #3678
