### ISSUE TITLE
Crash on opening turbine GUI

### ISSUE THREAD

**Issue by romanian9** [aidancbrady/Mekanism#3695]
my game crashes whenever i open the gui of the turbine specially if it's generating power if it's not generating power it doesn't crash 

the crash log 
[crash-2016-08-25_19.04.23-client.txt](https://github.com/aidancbrady/Mekanism/files/438187/crash-2016-08-25_19.04.23-client.txt)

using Mekanism-1.7.10-9.1.0.281
MekanismGenerators-1.7.10-9.1.0.281
MekanismTools-1.7.10-9.1.0.281

**Comment by aidancbrady** [comment]
Fixed in dev!
