### ISSUE TITLE
Crash because wrong tesla modid in annotation

### ISSUE THREAD

**Issue by bdew** [aidancbrady/Mekanism#3696]
Crash: https://gist.github.com/bdew/04435005f14327e593362b07cfb1d206

You changed it to the lower case modid here: https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/multipart/PartUniversalCable.java#L39

But it's still uses the capitalised version here: https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/multipart/PartUniversalCable.java#L347

This leads to that method getting stripped and calling it throws an AbstractMethodError

**Comment by aidancbrady** [comment]
fixed in dev: https://github.com/aidancbrady/Mekanism/blob/1.10/src/main/java/mekanism/common/multipart/PartUniversalCable.java#L347
