### ISSUE TITLE
Cardboard box Blacklist does not work. Version 9.1.0

### ISSUE THREAD

**Issue by Imotepchief** [aidancbrady/Mekanism#3697]
What originally started as an attempt to prevent boxes picking up nodes has uncovered the fact that the 9.1.0 version of mekanism cardboard boxes completely ignore the blacklist.

I thought it was working at first when I was unable to pick up warded blocks, but it turns out it simple cannot interact with unbreakable blocks.

# Use this file to tell Mekanism which blocks should not be picked up by a cardboard box.
# Proper syntax is "ID:META". Example (for stone):
# 1:0

# Thaumcraft
Thaumcraft:blockWarded:0
Thaumcraft:blockCosmeticOpaque:2
Thaumcraft:blockArcaneDoor:32767
Thaumcraft:blockStoneDevice:32767
Thaumcraft:blockAiry:0
635:0

# Carpenter's Blocks
CarpentersBlocks:blockCarpentersSafe:32767

# Twilight Forest
TwilightForest:tile.TFBossSpawner:32767
TwilightForest:tile.TFTowerDevice:32767
TwilightForest:tile.TFTowerTranslucent:32767

I added 635:0 in an attempt to follow the "proper syntax" but even that doesn't work.

It was unable to pick up Warded blocks, glass, doors and it was also unable to pick up bedrock, but other than that all other items could be picked up, including Safes and boss spawners.

**Comment by utoc** [comment]
I can assure you that cardboard boxes definitely work in 9.1:

Also, check your log upon startup: it'll tell you if you have an invalid item which in this case you probably do.

````
randomthings:beanStalk 0
randomthings:lesserBeanStalk 0
````

Those are two working examples after a lot of trial and error.  From this point I suggest you focus on one or two items, test those and then follow the syntax to add the rest.

**Comment by DeGariless** [comment]
Blacklist is also not working for me. Don't know how much simpler my config could be. What am I doing wrong? What information can I provide to fix the problem?

[BoxBlacklist.txt](https://github.com/aidancbrady/Mekanism/files/669945/BoxBlacklist.txt)
