### ISSUE TITLE
i cant give player's blocks other than basic's

### ISSUE THREAD

**Issue by idnthvn** [aidancbrady/Mekanism#3698]
i am using mekanism version 9 for 1.7.10
I know there is an issue with selling mekansim blocks through shops, however we cant spawn items in with the /give command 
all it does is give the players basic blocks. as the basic/advanced/elite/and ultimate all use the same block id? 
is there something i can do or are we stuck this way untill there is someone who can code it with meta values?

**Comment by aidancbrady** [comment]
Some Mekanism blocks use NBT to define their type. I'm afraid shops won't be able to handle these kinds of things until they update to 1.10 with the addition of block states.

**Comment by bookerthegeek** [comment]
Easy fix on the server side though, use a kit mod/Plugin.

**Comment by idnthvn** [comment]
Bookerthegeek - Do you know of any plugins that do this?

**Comment by bookerthegeek** [comment]
Those ones we use on our server, I'll get the name tonight. We are still on. 1.7 so I don't know if they will have been updated to anything later yet.

**Comment by idnthvn** [comment]
Okay cool. Thanks Bookerthegeek im also on 1.7.10 so thatll work

**Comment by bookerthegeek** [comment]
[This](https://www.spigotmc.org/resources/guishopplus.15561/) one should work pretty good.
