### ISSUE TITLE
Crash While Leaving the Nether (Mechanical Pipe)

### ISSUE THREAD

**Issue by rannday** [aidancbrady/Mekanism#3701]
[http://pastebin.com/raw/mHNcJah9](url)

**Comment by ShaCraft** [comment]
That link is broke for me.  How did you come to the conclusion the issue is with Mechanical pipes? What steps did you take to test? Dose the crash occur with only Mekanism installed?

Might the issue be the same as #3626 ?

**Comment by aidancbrady** [comment]
Fixed in dev.
