### ISSUE TITLE
(1.10.2) Crash to Desktop when crafting paxel

### ISSUE THREAD

**Issue by psychofad** [aidancbrady/Mekanism#3704]
Mekanism-1.10.2-9.1.1.290.jar
MekanismGenerators-1.10.2-9.1.1.290.jar
MekanismTools-1.10.2-9.1.1.290.jar
forge-1.10.2-12.18.1.2073

When I try to craft an Obsidian Paxel, as soon as I put the pickaxe into the crafting grid I am crashed to desktop.  The good news, I have seen this exact crash before with Router Reborn!

crash report
[http://pastebin.com/k6qMyc1A](http://pastebin.com/k6qMyc1A)

The mentioned Router Reborn issue:
[https://bitbucket.org/zyberwax/main/issues/56/arrayindexoutofboundsexception](https://bitbucket.org/zyberwax/main/issues/56/arrayindexoutofboundsexception)

his fix:
> Tom Erik Voll [repo owner]
> problem solved, seems the registration of the itemstack to sue for repair had changed, and caused a crash since i used the old method.
> 

I hope this helps!

**Comment by aidancbrady** [comment]
Don't think it's on my end then :)

**Comment by psychofad** [comment]
Perhaps you misunderstood.  The crash is identical to the one that Router Reborn had when it first updated to 1.10.2.  He was able to fix it by using the updated itemstack method since it had changed in forge/minecraft.  I only mentioned it because the crash reports were identical, but RR had nothing to do with this crash.  

Just asking you to take a look if you can, thanks.

**Comment by psychofad** [comment]
Botania mod author believes it is on your end after all:

 

> williewillus commented 23 hours ago
> 
> this is whoever that tool's mod author not setting their ToolMaterial's repairMaterial properly.
>
