### ISSUE TITLE
[9.1.290] Can't take power from Dimensional Transceiver (EnderIO)

### ISSUE THREAD

**Issue by Lukas45** [aidancbrady/Mekanism#3705]
I have some wind generators up at y250, hooked to a Dimensional Transceiver (with Universal Cables), which works just fine.
However down on the ground, where I receive the power, the Cables can not pull the power from the Transceiver.
If I place a machine next to it, it gives power just fine.

Minecraft 1.10.2
Forge 12.18.1.2064
Mekanism 9.1.1.290
EnderIO 3.0.1.96
EnderCore 0.4.1.51

**Comment by laz2727** [comment]
Try to set the wire to pull (with the configurator, it's the mods' wrench).

**Comment by Lukas45** [comment]
Tried, no luck

**Comment by laz2727** [comment]
Okay. Try the cube.

There are some compatibility problems in minecraft mods right now, so these are basically workarounds.

**Comment by Lukas45** [comment]
That's what I'm doing at the moment, even though the Ultimate Cube has a max transfer rate of 20k RF/T (where the Transceiver/Elite Universal Cable has 25k RF/T), but it'll do for the time being

**Comment by laz2727** [comment]
There is no upper limit for the cables, they are only limited by the
cable's length and the MAX_INT.

**Comment by XSmeets** [comment]
I had a similar problem today. Usually breaking and replacing the dimensional transceiver worked for me.
