### ISSUE TITLE
Oredictionary Converter

### ISSUE THREAD

**Issue by Fortist** [aidancbrady/Mekanism#3707]
I cant seem to convert Gems of any kind, as I cant add them to the filter.
I have two different kinds of Sapphires, and "gemSapphire" isnt being inputed. Same goes for "gemRuby", Diamond, Emerald, etc. 
Anything dictionaried as a gem. 
Ingots work fine.  "ingotWhatever"
Blocks dont work either. "blockWhatever"

If it's a bug or oversight, please add it. 
This is the most powerful converter due to having almost unlimited filters in one block.

If "it's a feature" it's dumb, especially for the Gems.

**Comment by laz2727** [comment]
It's a feature, but not for gems. It blocks a lot of gamebreaking
transmutations.

**Comment by Fortist** [comment]
I just want to convert a Sapphire into a Sapphire, so it routes correctly into storage.

**Comment by aidancbrady** [comment]
The Oredictionificator works the way it does for balance reasons, certain gems are registered under the same name that may not be equal in value.

**Comment by Fortist** [comment]
But they ARE equal in value, hence they're under the same oredictionary name, and me as the Modpack maker AND user says they are in my instance.
Who are you to say they are not?
At least at some point allow it to be used unrestricted.

I really do hate this "muh vision" bullshit.

**Comment by aidancbrady** [comment]
@Fortist, I'm the developer and owner of Mekanism, and that gives me the right to decide how I manage my interaction with the Ore Dictionary.  I'm fairly confident Industrial Diamonds from IC2 are registered as "gemDiamond", and I would not call them equal to vanilla Minecraft diamonds in value.

Also, the kind of rhetoric you projected in your last comment is, to say the least, completely uncalled for.  Remember you're talking about totally free-to-use, open-source software; if you're that angry about the way it works, just make the change yourself.

**Comment by laz2727** [comment]
Iirc you can craft them back directly (but I never played a non-modpack ic2
version).

**Comment by VT-14** [comment]
You shouldn't have duplicate ores.  You as the modpack maker should disable duplicate ores by disabling ore gens mod by mod until you have 1 of each kind, and adjust the spawning levels of the one ore you keep around to maintain balance.

Minetweaker or a similar mod is another option. (shapeless) gemSapphire -> ProjectRed:Sapphire.

I'm pretty certain the major case for this oreDict conversion issue would be Lapis and Blue Dye.  Natura added a flower dye that was blue, and registered it as dyeBlue.  Lapis is already dyeBlue, and thus they technically are convertible. Obviously, a bunch of flowers on the surface don't have the same value as Lapis.  Additionally, things like ProjectE would assign lapis a higher value than a flower dye, which isn't much of a problem so long as you can't convert between the two.

**Comment by ShadowDrakken** [comment]
Industrial Diamonds haven't been legitimately in IC2 for years... the placeholder item is there for backwards compatibility, and IC2 lets you craft them into standard diamonds directly. There's no way to craft Industrial Diamonds anymore.

Also, the entire purpose of the ore dictionary is to allow multiple mods to use the same items interchangeably in recipes. If the mods can use them interchangeably to craft, what's wrong with allowing them to convert for storage purposes?

That's not to say you don't have the right to control your mod however you want, but at least use an excuse that isn't complete BS.

**Comment by HuJK** [comment]
How about make it configurable to modpackers? We can specify a white list prefix in config file?
