### ISSUE TITLE
Crash when placing mechanical pipe on EnderIO dimensional transceiver

### ISSUE THREAD

**Issue by utoc** [aidancbrady/Mekanism#3708]
Hello 

We had a server crash after placing an ultimate mechanical pipe onto a dimensional transceiver. I'll have to edit it out with MCEdit otherwise it crashes every time the chunks are reloaded. 

Log: http://pastebin.com/4L6MdV7V

We're running the current dev build 9.2 with FML 2073. Enderio 1.10.2-3.0.1.96_beta with Endercore 1.10.2-0.4.1.51-beta

Let me know if this needs to go to EnderIO instead.

**Comment by aidancbrady** [comment]
Fairly confident this is on EIO's end. Let me know if this isn't the case.
