### ISSUE TITLE
Energy Net Server Crash (1.7.10)

### ISSUE THREAD

**Issue by Jengo13** [aidancbrady/Mekanism#3709]
Hello again, I've encountered another issue and I figured I'd report it. The issue seems to stem from the use of Extra Utilities fluid transfer node -> A Mekanism mechanical pipe. Here's the pastebin: 
http://pastebin.com/V37kWQQC

**Comment by DraksterAU** [comment]
1.7 Mek not supported anymore. I had the same issue but for IC2.
