### ISSUE TITLE
1.10.2 - Several machines names are incorrectly shown

### ISSUE THREAD

**Issue by viper2g1** [aidancbrady/Mekanism#3711]
MC: 1.10.2
Forge: 12.18.1.2073
Mekanism + Generators + Tools: 9.1.1.290
JEI: 3.9.0.244

I believe its JEI that shows the information at the top center of the screen.  I have built all machines needed for tier 2 ore processing but they all show up as Enrichment Chamber when hovering over them.  When clicking on them they show the correct names on their interfaces.  Also searching in JEI (inventory page) will show the correct machine based on the query.

**Comment by Utildayael** [comment]
Not a JEI issue, it's a WAILA issue. 

WAILA for 1.10 is buggy right now and I've seen the same thing with more than just Mekanism sadly.

Well either that or I'm running a LOT of rotary condensers as that's all WAILA reports most of my machines as. :)

**Comment by viper2g1** [comment]
That makes sense, I found the issues page for WAILA so I'll just leave that here.  One of the comments does say this regarding the issue:

"This is most likely down to the Maekanism machines, being the same ID and all that makes them different, is the NBT tags this is what JEI does to fix the issue and mod authors, seem to use when they know about it let aidancbrady know about and in about day he got back to me say he had implemented, if WAILA is still an extension, of JEI like it was to NEI, this was be easy for look up, and maybe use fix things like."

Here is the issue page:
https://bitbucket.org/ProfMobius/waila/issues/273/194-showing-incorrect-block-type-mekanism

**Comment by JaSpr** [comment]
I have committed a fix to WAILA, which was definitely causing the error.

https://bitbucket.org/ProfMobius/waila/pull-requests/47

**Comment by thommy101** [comment]
WAILA isn't being updated since May last year. There are other alternatives which are maintained.
An example which is a fork of WAILA: https://minecraft.curseforge.com/projects/hwyla
An example which is a "more immersive version" of WAILA: https://minecraft.curseforge.com/projects/the-one-probe

**Comment by JaSpr** [comment]
Yes, I agree.  However, when modpacks choose to use WAILA, users will see the incorrect names.  The fix is simple, so MAYBE they'll accept the merge request, but who knows.  As I understand it, hwyla already has the fix, and I know one probe works.

(I use both oneprobe and waila (for now) because they give differing information)

**Comment by JaSpr** [comment]
Hmm.  HWYLA seems to have the same issue.  I'll submit a fix there, too.

**Comment by JaSpr** [comment]
Never mind.  They had a different implementation to fix it.
