### ISSUE TITLE
[BUG] Ultimate Tier Upgrade Card 

### ISSUE THREAD

**Issue by Utildayael** [aidancbrady/Mekanism#3712]
Hello Aidan!

I recently decided that elite was simply not enough for my factories and decided I would go to ULTIMATE because why not, MOAR POWER?

So... I made the tier upgrade card and tried to apply it to my elite factories and... it doesn't work. 

Minecraft 1.10.2
Mekanism 9.1.1
Forge 2065

Thanks!

**Comment by aidancbrady** [comment]
Sadly, Ultimate Factories are not yet a thing.  As soon as they are, it will be as simple as applying the upgrade, however :)

**Comment by Utildayael** [comment]
Oh good to hear! I figured that might be the case but wanted to report just in case not. :)

Thanks!

**Comment by BigAl607** [comment]
Playing Stone Block 2 and this is still happening. Click on the Elite with the Ultimate and nothing happens.

**Comment by pupnewfster** [comment]
Last I checked stone block 2 is for 1.12... in other words the ultimate factories don't exist.
