### ISSUE TITLE
World Crashing Bug

### ISSUE THREAD

**Issue by Pkr1345** [aidancbrady/Mekanism#3713]
Not sure If this is a Mekanism or Tinker's error but, I was upgrading a basic tank to an advanced tank, shift clicked the recipe into a TC crafting station and the world crashed. The world now crashes every time upon entry.

Here's the crash log.
http://pastebin.com/HT9dk27V

**Comment by VT-14** [comment]
1) Remove Optifine.  Most mods don't support it, and you have a rendering crash.

2) If you are still crashing, try disabling Tinker's in-world table top item render thing in its config file.

**Comment by yutang13** [comment]
Mekanism tanks and solar panels do crash in tinkers tables. A vanilla table works just fine.

**Comment by aidancbrady** [comment]
Yeah, as reported previously, I'm not able to do much about this; I've gone pretty far out of my way already to fix this crash.
