### ISSUE TITLE
[1.10.2] Crash with Universal Cable with Bigreactor

### ISSUE THREAD

**Issue by Morpheus1101** [aidancbrady/Mekanism#3714]
My World crashes everytime on load now Crash log @ http://pastebin.com/bdAGKyKr

**Comment by ZeroNoRyouki** [comment]
I think the problem is the Tesla modid change

**Comment by Morpheus1101** [comment]
Using Tesla 1.2.1.48 crash on join still crash log @ http://pastebin.com/NvcRHt6g
[fml-client-latest.txt](https://github.com/aidancbrady/Mekanism/files/441855/fml-client-latest.txt)

**Comment by ZeroNoRyouki** [comment]
PartUniversalCable.givePower() is annotanted with @Method(modid = "Tesla") so it get stripped out by FML because there is no mod with an Id of "Tesla" (since it's now "tesla")

**Comment by Morpheus1101** [comment]
Whats the status on the update on this being released? i see the code has been fixed up...
