### ISSUE TITLE
Curse/Curseforge?

### ISSUE THREAD

**Issue by MakeLord95** [aidancbrady/Mekanism#3716]
It's been a month now (#3547), and we're still waiting for Mekanism on Curse... Any updates on it?

**Comment by UntouchedWagons** [comment]
Mekanism was on Curse for a little bit, but it's not there anymore. Rather disappointing.

**Comment by VT-14** [comment]
That was some random person uploading it without permission.

Aidan mentioned that Mekanism would be officially co-hosted on CurseForge in this blog post: http://aidancbrady.com/2016/05/its-that/

Supposedly, it will come eventually.  Seems to be taking longer than Aidan predicted though.  I'm curious what the hold up is.

**Comment by aidancbrady** [comment]
The main hold up is college having started two weeks ago; while I've been adjusting I haven't had as much time to get some serious fixes done for the 1.10.2 branch, something I wanted to have done before the CurseForge release. I should have some time in the next couple weeks to polish things off, though- I promise it will happen soon :)
