### ISSUE TITLE
Server Crash on start up, INCORRECT STATE

### ISSUE THREAD

**Issue by GeneralGred** [aidancbrady/Mekanism#3717]
I have a MC 1.7.10 forge server that's been working fine for weeks, but after deciding to regenerate the world by deleting the folder it crashes. I deleted the world once and regenerated it fine, but was not happy with the seed so I did it again about 3 minutes later and now after a dozen attempts I can't get the server to start. I have determined it to be mekanism but not sure how or why. I am running Mekanism-1.7.10-9.1.0.281 with both generators and tools.

http://pastebin.com/3DGTqnHq
http://pastebin.com/g9vXVySH

**Comment by bookerthegeek** [comment]
First, edit you post and delete the log. 

Second, pastebin the complete server log and crash report

Third, put those pastebin links in the post.

Thank you.

**Comment by DraksterAU** [comment]
1.7 no longer supported...

**Comment by bookerthegeek** [comment]
Even if no longer supported I have no issue helping people out as much as I can.

@GeneralGred I'll take a look at this tonight when I get home.

**Comment by GeneralGred** [comment]
Thank you bookerthegeek, I know there is a fix because it worked fine for the past two weeks, I'd like to add that I also made the modpack for the server and that with the exception of a few client mods is completely identical and the game still works in single player. I'm not sure but my only guess could be that it has something to do with a plugin and world generation because this has happened 3 times, always when I generate a new world from scratch.

**Comment by GeneralGred** [comment]
I found the problem and while I'm still looking into it I think my suspicion was right. I found out that the cause was that a conflict with Mekanism occurs when you have the mod GalaxySpace and turn off the generation of the added solar systems. I think it may have to do with an ore generation issue, I am going to continue to tweak the settings to find the root.

**Comment by bookerthegeek** [comment]
... You completely deleted the world folder, or just the dimensions....?

**Comment by GeneralGred** [comment]
completely deleted the worlds folder

**Comment by DraksterAU** [comment]
Suggestions :
Try using thermos instead of kcauldron. 
Also, your aware that Galaxy space doesn't get updated and isn't recommended by Galacticraft devs anymore?

**Comment by bookerthegeek** [comment]
What launcher are you using?

**Comment by DraksterAU** [comment]
It's a server bud.
