### ISSUE TITLE
Digital Miner is at once away.

### ISSUE THREAD

**Issue by cyberpunkbln** [aidancbrady/Mekanism#3718]
Hello,
some strange bug. After i play a while the Digital Miner is at once away. I must cheating to became him back:).

All other around are fine, the chests and the generators. 

Minecraft: 1.10.2
Mekanism: 1.10.2-9.1.1.290

Edit: When i'm in the overworld outside from the chunk, then its happend, the digital miner is gone. When i leave the world in the nether the digital miner stand on his place, when i come back from the nether.

But i dont know if this is relevant to time or to leave the chunk in the overworld.

**Comment by cyberpunkbln** [comment]
Hello,

Update: When i leave the chunk and be in the chunk for some moments (jump nether-gate and after a few seconds back dont trigger this bug) about a few minutes the DG is away. Its the Mekanism-Chunk-Problem what the 1.10.2er Versions have, I try to use a ChunkLoader.

**Comment by koalalord9999** [comment]
Yea, I ran into the same bug a couple days ago, I was casually mining diorite outside my base, then I ran to someones base cause they wanted my to come look at something, came back 5 mins later, it was gone (we were only ones online). The miner was in an unloaded area.

**Comment by cyberpunkbln** [comment]
Glory to the Neotech-ChunkLoader :). But in the Nether i have the chunk-loader allready placed and then then digtital, and the digital miner was gone. I think this chunkloader from Neotech we must place after we have placed the Digital Miner. ChunkLoader_upgrades or capabilities was very great.

**Comment by TheSirati97** [comment]
I just hope this eventually get fixed.

**Comment by JaSpr** [comment]
I think (and could be wrong) that this could have a lot to do with placing a digital miner across the chunk border, so that part is in one chunk, and part is in another.  And when one of those chunks unloads before the other, it just breaks and the miner disappears.

Whatever the case it seems by adding the anchor upgrade, the miner will no longer disappear

**Comment by aidancbrady** [comment]
Did some testing, appears to no longer be an issue in 1.11 :)

**Comment by halvors** [comment]
@aidancbrady Maybe not 1.11, but still happening sometimes in 1.12.

**Comment by thiakil** [comment]
You owuld need to find us an exact reproduction sequence, and preferably logs too.

**Comment by Hero9909** [comment]
Hey there ive got a world where you would be abled to watch the bug get reproduced.
ive tested that 4 times and it keeps disaprearing at the same place. but i cant determinate the exacte sequence ( anchor upgrade installed)

can i help anyone by uploading the world ? with instructions?

**Comment by ProsperCraft** [comment]
This is happening in 1.12.2, will open a new issue.

**Comment by douglasg14b** [comment]
vanishes for me too.... wtf

**Comment by JaSpr** [comment]
There is a chunkloader upgrade for the digital miner
