### ISSUE TITLE
mekanism generators

### ISSUE THREAD

**Issue by playwithjane** [aidancbrady/Mekanism#3719]
WHAT I MUST DO??????????S

---- Minecraft Crash Report ----
// You're mean.

Time: 30.08.16 23:41
Description: Unexpected error

java.lang.NoSuchMethodError: mekanism.common.util.MekanismUtils.makeBoundingBlock(Lnet/minecraft/world/World;IIILmekanism/api/Coord4D;)V
	at mekanism.generators.common.tile.TileEntityWindTurbine.onPlace(TileEntityWindTurbine.java:110)
	at mekanism.generators.common.block.BlockGenerator.func_149689_a(BlockGenerator.java:123)
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:213)
	at mekanism.generators.common.item.ItemBlockGenerator.placeBlockAt(ItemBlockGenerator.java:166)
	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:353)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mekanism.generators.common.tile.TileEntityWindTurbine.onPlace(TileEntityWindTurbine.java:110)
	at mekanism.generators.common.block.BlockGenerator.func_149689_a(BlockGenerator.java:123)
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:213)
	at mekanism.generators.common.item.ItemBlockGenerator.placeBlockAt(ItemBlockGenerator.java:166)
	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:353)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['play_with_jane'/241, l='MpServer', x=-291,23, y=79,62, z=-170,65]]
	Chunk stats: MultiplayerChunkCache: 431, 431
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-256,64,-208), Chunk: (at 0,4,0 in -16,-13; contains blocks -256,0,-208 to -241,255,-193), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 17472 game time, 17472 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 46 total; [EntityPig['Pig'/64, l='MpServer', x=-283,53, y=124,00, z=-111,81], EntityPig['Pig'/65, l='MpServer', x=-286,50, y=129,00, z=-104,50], EntityBat['Bat'/68, l='MpServer', x=-263,38, y=21,10, z=-120,38], EntityBat['Bat'/457, l='MpServer', x=-335,29, y=52,51, z=-167,44], EntityBat['Bat'/459, l='MpServer', x=-336,51, y=53,00, z=-164,22], EntityBat['Bat'/77, l='MpServer', x=-241,34, y=18,10, z=-219,25], EntityBat['Bat'/78, l='MpServer', x=-261,34, y=22,00, z=-208,25], EntitySheep['Sheep'/79, l='MpServer', x=-248,81, y=71,00, z=-205,22], EntityBat['Bat'/463, l='MpServer', x=-273,44, y=41,89, z=-194,14], EntitySheep['Sheep'/80, l='MpServer', x=-249,75, y=71,00, z=-203,63], EntitySheep['Sheep'/81, l='MpServer', x=-235,09, y=67,00, z=-181,03], EntityBat['Bat'/17, l='MpServer', x=-344,15, y=35,87, z=-133,91], EntityBat['Bat'/82, l='MpServer', x=-248,54, y=14,00, z=-166,70], EntityPig['Pig'/83, l='MpServer', x=-244,50, y=79,00, z=-128,78], EntityPig['Pig'/84, l='MpServer', x=-244,22, y=79,00, z=-127,47], EntityPig['Pig'/85, l='MpServer', x=-247,09, y=78,00, z=-120,53], EntityPig['Pig'/86, l='MpServer', x=-244,16, y=79,00, z=-125,66], EntityBat['Bat'/26, l='MpServer', x=-336,50, y=48,10, z=-233,31], EntitySheep['Sheep'/92, l='MpServer', x=-234,50, y=68,00, z=-231,50], EntitySheep['Sheep'/93, l='MpServer', x=-235,50, y=68,00, z=-229,50], EntitySheep['Sheep'/94, l='MpServer', x=-238,44, y=68,00, z=-231,91], EntityBat['Bat'/95, l='MpServer', x=-239,63, y=18,10, z=-219,25], EntitySheep['Sheep'/96, l='MpServer', x=-235,09, y=68,00, z=-218,91], EntitySheep['Sheep'/97, l='MpServer', x=-235,84, y=69,00, z=-187,84], EntityPig['Pig'/98, l='MpServer', x=-225,34, y=75,00, z=-114,44], EntityCow['Cow'/99, l='MpServer', x=-231,97, y=75,00, z=-113,88], EntityPig['Pig'/100, l='MpServer', x=-236,47, y=78,00, z=-124,69], EntityCow['Cow'/101, l='MpServer', x=-229,63, y=89,00, z=-107,81], EntityCow['Cow'/102, l='MpServer', x=-235,25, y=92,00, z=-106,50], EntityCow['Cow'/103, l='MpServer', x=-235,72, y=96,00, z=-105,50], EntityBat['Bat'/43, l='MpServer', x=-305,73, y=37,91, z=-184,45], EntityBat['Bat'/109, l='MpServer', x=-230,03, y=15,00, z=-221,48], EntityBat['Bat'/110, l='MpServer', x=-213,48, y=27,84, z=-206,25], EntityPig['Pig'/111, l='MpServer', x=-222,66, y=75,00, z=-118,69], EntityPig['Pig'/112, l='MpServer', x=-213,47, y=73,00, z=-125,69], EntityBat['Bat'/53, l='MpServer', x=-294,65, y=35,32, z=-211,26], EntitySquid['Squid'/54, l='MpServer', x=-282,53, y=59,48, z=-175,53], EntityBlock['unknown'/374, l='MpServer', x=-296,75, y=75,00, z=-180,75], EntityItem['item.item.seeds'/55, l='MpServer', x=-287,56, y=79,13, z=-168,22], EntityPig['Pig'/58, l='MpServer', x=-279,03, y=99,00, z=-108,78], EntityPig['Pig'/59, l='MpServer', x=-280,50, y=104,00, z=-101,50], EntityPig['Pig'/60, l='MpServer', x=-281,50, y=107,00, z=-96,22], EntityClientPlayerMP['play_with_jane'/241, l='MpServer', x=-291,23, y=79,62, z=-170,65], EntityPig['Pig'/61, l='MpServer', x=-282,50, y=121,00, z=-104,31], EntityPig['Pig'/62, l='MpServer', x=-282,50, y=117,00, z=-102,50], EntityPig['Pig'/63, l='MpServer', x=-282,50, y=117,00, z=-102,50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 229853832 bytes (219 MB) / 575086592 bytes (548 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.17} [BuildCraft] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.17} [BC Silicon] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.17} [BC Transport] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.17} [BC Builders] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.17} [BC Energy] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.17} [BC Robotics] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.17} [BC Factory] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	EnderIO{2.0_beta} [Ender IO] (Ender-IO-Mod-1.7.10.jar) 
	UCHIJAAAA	IC2{2.2.821-experimental} [IndustrialCraft 2] (Industrial-Craft-2-Mod-Experimental-1.7.10.jar) 
	UCHIJAAAA	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAAAA	Mekanism{8.1.7} [Mekanism] (Mekanism-1.7.10-8.1.7.252.jar) 
	UCHIJAAAA	MekanismGenerators{8.1.6} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.6.249.jar) 
	UCHIJAAAA	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics 4000'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4276, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
WHAT I MUST DO??????????

**Comment by idnthvn** [comment]
Client crash? or server?
Have you tried to increase Ram since i see your using 1GB (probably should use 2GB

**Comment by aidancbrady** [comment]
Not quite sure how this could happen, possibly a corrupt download or another mod using an outdated API interfering with the class path.  Regardless, not on my end.
