### ISSUE TITLE
Digital Miner Issue/Glitch

### ISSUE THREAD

**Issue by idnthvn** [aidancbrady/Mekanism#3720]
So i know that this has been resolved in other posts, however
i am using 9.1.0 mekanism on 
minecraft 1.7.10
Thermos 1614.58
i am using Towny and PEX 
i place the digiminer
used /mk op
Worked great for a bit
then it quits
i use a maxed 32 radius,
Now i reopped mekanism 
added it to Towny
added it to Pex 
Still nothing
I then mess with the Config and go from 32 radius to 31
and POOF it starts mining, Then it stops after a while again 
go back to config and go from 31 to 30 and POOF
it works again for a little bit, 
go from 30-29 and works again and stops. 
Is this suppose to be this way>?
Am i missing something?
or is this a legit error

**Comment by aidancbrady** [comment]
I'm afraid I'm not able to do much here; just ensure that the Digital Miner is whitelisted on all platforms.  Permissions can be a real pain sometimes.

**Comment by idnthvn** [comment]
@aidancbrady  What do you mean by Whitelisted? I did /mk op and have added the fake player [Mekanism] added,
