### ISSUE TITLE
Request - Arrows on Laser Tractor/Amp Blocks

### ISSUE THREAD

**Issue by Utildayael** [aidancbrady/Mekanism#3721]
Mucking around with the fusion reactor and setting up my laser charging bits. I noticed one minor issue and tbh I can't remember if it was this way in v8 or not...

The tractors and the amplifiers have the same texture on all sides. I thought it was my texture pack at first so I swapped to default and nope, same texture. Would be SUPER handy if they had any sort of marking on the output side to help with alignment prior to possible painful laser blasts through your base.

Arrows/dots/something on the output side would be stellar. Heck even coloring the side different would work. Just need some way to visually indicate which direction the tractor or amp is going to output to without having to fire a laser through it to test.

Thanks :)

**Comment by aidancbrady** [comment]
Fixed, thanks!

**Comment by Utildayael** [comment]
I've lost track of how many things fixed today. Haha. Any swag on when next release drops with all the fixes over past couple weeks?

I know some devs go nuts and shove new releases daily but I'm guessing you actually do things like... Test your mod... :)

Thanks again!

**Comment by aidancbrady** [comment]
My goal is to fix the issue with cables/pipes/etc disconnecting on server restart before I push anything; I'm looking into it now.  Assuming I can fix that today, you'll have your release tonight :)

**Comment by Utildayael** [comment]
Awesome! Ya that one has been a plague since uh Mek 7? It's the bug that won't die! 

Good luck killing this one, hopefully permanently. :)
