### ISSUE TITLE
Logistical Transporter pipes do not attach to Extra Utilities 2's Trash Cans

### ISSUE THREAD

**Issue by UntouchedWagons** [aidancbrady/Mekanism#3722]
Using Mekanism 9.1.1.290 on 1.10.2

**Comment by Paul17041993** [comment]
They don't attach to nullifiers from UsefulNullifiers either...

**Comment by Paul17041993** [comment]
Commit?

**Comment by thommy101** [comment]
It are probably mods who only support inventory capabilities, for which support is added in the 1.11 branch.

**Comment by Paul17041993** [comment]
Anything to back that up?

**Comment by thommy101** [comment]
Only checked UsefulNullifiers (as extra utilities 2 is closed source).

https://github.com/Bartz24/UsefulNullifiers/blob/master/src/main/java/com/bartz24/usefulnullifiers/tiles/VoidNullifierTile.java
This is the tile entity, which isn't an instance of IInventory, but has an inventory capability.
The implemented class is an abstraction of IItemHandler (a requirement for the capability) as defined at https://github.com/McJty/compatlayer/blob/1.11.2/src/main/java/mcjty/lib/compat/CompatItemHandler.java

As for reference of the commits in the 1.11 branch (not sure if I got them all):
b97b7184c138000997e34194174a7d82e5ebbed4
0392f550dcef7621c8a5361f9c3aedf3afeb9a24
796c9e502a6b5f5ad60b220a004d15b84cd1bbbd
ccb342ead7aab4260245edbbdd32b2ce370ea757

**Comment by Paul17041993** [comment]
Ok those are the commits I was expecting to see here, though it seems like we're going to see a lot of segmentation as to what the mainstream-modded-mc-version is going to be...
