### ISSUE TITLE
Visual Waila/Wawla Bug

### ISSUE THREAD

**Issue by RainbowGravity** [aidancbrady/Mekanism#3723]
Not in 1.7.10 version, but in 1.10.2 version, many machines are called different machines when using waila and walwa (which also causes the robit crash) Somebody is currently doing a 'survival with mekanism' series and also has the issue.  

https://youtu.be/I3A2SfwUGZc?t=9m51s

If you notice here, all the machines are called enrichment chamber etc. Do not have an extensive list of which machines are called what.

**Comment by aidancbrady** [comment]
Known issue, sadly on WAILA's end.
