### ISSUE TITLE
Digital Miner Quality of Life Update 1.10.2

### ISSUE THREAD

**Issue by koalalord9999** [aidancbrady/Mekanism#3725]
Could it be possible to make the energy ports, and item ports be made uninteractable blocks, so we can just right click to place a chest or power source onto them? That would be awsome, thanks :D

**Comment by VT-14** [comment]
What is wrong with Shift + Right Click?  That's how vanilla handles not opening GUIs.  The quality of life improvement would be so minor, that I don't think it would be worth the effort.  It would also lead to confusion as attempting to open the GUI while accidentally looking at those pieces would do nothing.

If you are flying (creative mode), then you can stop yourself from loosing altitude by holding both shift and space at the same time, and then right click.

Unless it has changed, energy can be input from any side.  The only special sides are input (top) and output (back).

**Comment by koalalord9999** [comment]
There are two side ports that allow power into them, every other area, without a port will not accept energy ;P but oh well
