### ISSUE TITLE
crafting formula

### ISSUE THREAD

**Issue by DnTheMn** [aidancbrady/Mekanism#3726]
Issue Description:
Unable to craft Crafting Formula for mekanism

What happens: try to make dosnt do anything.

What you expected to happen: craft a crafting formula

Steps to reproduce:

1.Collect items to make
2.Place in crafting table
3.No output
...

Version of All the Mods: v1.9

**Comment by aidancbrady** [comment]
Fixed in dev.

**Comment by Dulana57** [comment]
I have the same problem too (1.9.4)
