### ISSUE TITLE
Security system bug

### ISSUE THREAD

**Issue by bbgott** [aidancbrady/Mekanism#3727]
I'm running a small 1.10.2 pack with some friends. Whenever someone else places down either a quantum entangleporter or a teleport base block, I no other player can access the UI. They are told that they do not have access. If I break the block and place it down, then I can access the UI, but no one else can. We have verified that the access it set to public. We even built a security station, but got the same behavior.

Forge 1.10.2-12.18.1.2053
Mekanism 9.1.1.290

**Comment by aidancbrady** [comment]
Intentional behavior. Teleporters and Quantum Entangloporters are still constrained by the security set by the owner's Security Desk.

**Comment by bbgott** [comment]
Well then there is an issue with the security station, because he set down a security station and tried to set it to public.  So unless other players are not supposed to see the UI under any circumstances, then there is a bug.
