### ISSUE TITLE
Request - Increase Dynamic Tank Capacity

### ISSUE THREAD

**Issue by Utildayael** [aidancbrady/Mekanism#3728]
With the addition of tiered fluid tanks and gas tanks [thanks for that btw!] the dynamic tank is feeling a bit weak. 

Given the size of it, in the same space you can hold significantly more fluids. I would suggest at least a 2x increase in storage which would put it in line with BDew's tanks in Pressure Pipes.

Trying to not compare to Extra Utils drums as they are way OP compared to most any other mods fluid storage. Besides, dynamic tanks look cooler. :)

Another idea would be to tier the dynamic tank much like everything else in Mekanism which would be similar to how Railcraft handled their multiblock tanks [iron/steel tiers].

Just a thought. :)

Cheers!

**Comment by yutang13** [comment]
I can get behind this idea. I wanted to build a dynamic tank to hold a buffer of water for my thermal evaporation plant. I was shocked at how large I had to make it to hold over 4,000 buckets of water (greater than a reinforced drum for EU2)
Even more of a shock was how ridiculously expensive it was; especially compared to a fluid tank.

**Comment by Utildayael** [comment]
It's hard to compare to the EU drums as they just kinda blow everything out of the water for resource cost vs what you get and that hasn't changed in EU2 other than the bedrock drum is MIA still, kinda like the EU dev...

Now compared to say, Pressure Pipes or Railcraft I think that is a much more fair comparison. :)

I'm sure devs cringe every time they hear multiblock tank compared to EU drums. ;)

The 18x18x18 Mek tank IS impressive tho ungodly expensive to actually build. Holds 96,000,000mb or 96k buckets IIRC but costs a tooooooooon of steel.

**Comment by Utildayael** [comment]
Side note.  Still want multiblock tanks to hold gas. Did get quite a bit better wth the tiered gas tanks so that helps. (512k vs the old 96k only)

**Comment by aidancbrady** [comment]
How about a 4x boost- 64,000 per tank block instead of 16,000?

**Comment by Utildayael** [comment]
I can live with that. :)

<3
