### ISSUE TITLE
[Issue/DUPE] Tesla API outdated

### ISSUE THREAD

**Issue by accessdenied0** [aidancbrady/Mekanism#3730]
Hello @aidancbrady ,

I recently run into issues with the current Tesla API. It cause crashes if I connecting Universal-cable to Machines which using the current API.

I link here two issues which have probably the same topic:

https://github.com/Ellpeck/ActuallyAdditions/issues/227
https://github.com/aidancbrady/Mekanism/issues/3636

access_denied

**Comment by canitzp** [comment]
I updated a older issue with the same topic #3636

**Comment by accessdenied0** [comment]
I know, I linked it. But I felt like I should bring it to a point and collect it in a order.

**Comment by aidancbrady** [comment]
Fixed in dev, thanks.
