### ISSUE TITLE
1.10.02 Universal cables don't transmit energy with Ender IO or Big Reactors

### ISSUE THREAD

**Issue by Valdee** [aidancbrady/Mekanism#3732]
As in the topic, latests mods, Ender IO and Big Reactors Legacy, tried universal cables, they do attach to different mods machinery but do not transmit power. 
Ender IO power conduit however does transmit to mekanism machinery.

**Comment by aidancbrady** [comment]
Universal Cables currently do not accept energy from non-Tesla sources.

**Comment by mgdgfbhevdyeh** [comment]
can u add full RF support?
