### ISSUE TITLE
Suggestion - Computer Interface

### ISSUE THREAD

**Issue by XredstonemodsX** [aidancbrady/Mekanism#3733]
I suggest adding a digital miner computer interface for OpenComputers and ComputerCraft that allows these mods to Start/Stop the miner and edit the configurations, this could be in the form of an upgrade that allows a computer to directly connect to the miner or a block you can put on one of the miner's ports that CC/OC can connect to

**Comment by aidancbrady** [comment]
This is already implemented, check out the implementation in TileEntityDigitalMiner :)
