### ISSUE TITLE
[9.1.0.281] NEI Spawn Overlay/Mekanism Machine log overload

### ISSUE THREAD

**Issue by Nohicom** [aidancbrady/Mekanism#3734]
While playing around using a few mods on a singleplayer world, I noticed that every so often my log would fill up with thousands and thousands of lines of errors, which would not cause the game to crash nor generate a crash report but would consume lots of storage space with excessive file sizes and stop the MultiMC log from displaying past it.
Not knowing how to read these things very well, I'm fairly certain that it's a bad interaction between the NEI mob spawning overlay and a Mekanism machine or pipe or something.

[The log fills up with itself up with these 41 lines over and over](http://pastebin.com/raw/kSJ9U5fh)

Relevant versions:
Forge: 10.13.4.1614
CodeChickenCore: 1.0.7.47
NotEnoughItems: 1.0.5.120
Mekanism: 9.1.0.281

**Comment by aidancbrady** [comment]
Yeah, I have a feeling you're right about the issue. 1.7.10 isn't technically supported anymore, and luckily this is not a critical issue.  I've added checks for the 1.10.2 branch to make sure this no longer happens.
