### ISSUE TITLE
1.10.2 Obsidian and the digital miner

### ISSUE THREAD

**Issue by LordHellscream** [aidancbrady/Mekanism#3738]
1.10.2-9.1.1.290

I setup a digital miner and look for obsidian, it found 29.

So I mined the 29 obsidian, but when it stopped and I pressed reset and started again, it found another 24 obsidian, this continues, every time I reset and restart the miner, it find more obsidian. (only obsidian, not any of the other ores of course)

My question is: is this working as intended? is the miner so smart that it turns the lava beneath the obsidian into new obsidian or its a duping bug, I can't find the spot where it mines so I cannot be sure.

**Comment by TehStoneMan** [comment]
It's the way the miner operates. It will only mine the ore (in this case, obsidian) that it finds on the initial scan. If the obsidian that it mines is a result of water interacting with lava, then, when the water flows into the empty space from the removal of the blocks, more obsidian may be created, but wont be seen by the miner until it is reset, and performs a new scan.

**Comment by LordHellscream** [comment]
ah huh! cool, glad its not a bug.

**Comment by VT-14** [comment]
Yup, Obsidian is being created.

It's worth adding that the Miner mines an entire y level, and goes from the bottom up.  It will mine far fewer than expected gravity affected blocks like Sand and Gravel because of that.
