### ISSUE TITLE
Induction Cells/Providers Changing Colors

### ISSUE THREAD

**Issue by Utildayael** [aidancbrady/Mekanism#3740]
Not sure if this is intended or not...

When I place various induction cells and providers in my induction matrix, some of the will change colors to look like different tiers.

For example, I have a 5x5x5 induction matrix that has 2 advanced cells and 1 advanced provider inside. The model for those if I place them on the ground is red using default textures. If I place them on top of eachother in my induction matrix, I get green - red - green which makes it look like I have two basic components and one advanced. This is a bit confusing and especially difficult as WAILA is a broken pile of crap right now in regards to how it handles Mekanism and many other mods so I can't even look at the block and tell what it is. I know they are adv since I placed them but... it's annoying. I also don't like the Christmas tree look.

I would expect the colors/texture to stay same in any config minus the bit of "connected texture" you do with them but that was also why I wasn't sure if this was a bug or "as intended" ... :)

Thanks!

Mekanism 9.1.1
MC 1.10.2
Forge 2065

**Comment by Utildayael** [comment]
Suppose a screenshot might help. 

http://imgur.com/a/m3pkX

As noted, all three items in the matrix are advanced level [2 cells, 1 provider] so I'd expect them to all be red.

**Comment by aidancbrady** [comment]
Indeed an issue, I fixed this a week or so back. I'll have a fix out soon :)

**Comment by Utildayael** [comment]
Thanks Aidan! I know you have a few things I've reported you have fixed so awaiting 9.1.2 :)
