### ISSUE TITLE
Universal Cables don't transfer EU

### ISSUE THREAD

**Issue by DFliyerz** [aidancbrady/Mekanism#3742]
I can't get universal cables to convert any other power system to EU or even transfer EU, and am therefore having to create an entirely separate power grid for IC2 stuff.

**Comment by Utildayael** [comment]
What version? I'm using Mekanism 9.1.1 and literally just set up a power system for my IC2 stuff using universal cables. No issues and nothing special other than run cable to machine.

I'm assuming your cables are properly pulling power from *somewhere* right? IE: They are lit up with the green stripe?

**Comment by Utildayael** [comment]
Sidenote, there is a config option to blacklist IC2 power but it is disabled by default so that could also be an issue if you [or your server admin if you play MP] changed it.

**Comment by aidancbrady** [comment]
Make sure your cables are set to extract from EU sources.

**Comment by evernife** [comment]
Same here, I can send RF to ic2 machines (It converts ok)

But, it dont pull EU from generators/MFSUs etc.

**Comment by evernife** [comment]
T.T

**Comment by evernife** [comment]
> Make sure your cables are set to extract from EU sources.

How i do this?

**Comment by Utildayael** [comment]
The same way you set any pipe in Mekanism to extract? :)
