### ISSUE TITLE
FPS Tanked w/ Logistics Pipes + Mek Bins

### ISSUE THREAD

**Issue by Utildayael** [aidancbrady/Mekanism#3745]
Suffering major FPS drops [like 90%+ drops] when using ultimate logistical transporters + Mekanism bins. 

Not sure if it is flooding rendering updates or what but it is only with the bins as the logistics pipes by themselves don't cause it even when transferring insane amounts of items to say... 10 overclocked recyclers. Ran into something like this with Pressure Pipes tanks when using the tank indicator and bdew tracked the problem to his rendering update code firing waaaay too much as the tank indicator was constantly changing as the tank filled and I believe he said something about "complex models" being within a 16x16x16 range around the tank indicator, ie models that have rendering updates often/constantly if that helps.

I don't have this issue using Storage Drawers or any other storage systems.

Mekanism 9.1.1
MC 1.10.2
Forge 2065

Thanks

**Comment by Utildayael** [comment]
Additional: Tried setting opaque transmitters and no change in fps. Definitely the bins. Once items stopped transferring to the bin, fps went back to normal immediately.

**Comment by thommy101** [comment]
Cannot reproduce with latest version
