### ISSUE TITLE
Thermodynamic conductors are not discernibly different across tiers.

### ISSUE THREAD

**Issue by 99887** [aidancbrady/Mekanism#3746]
I noticed while building an early steam system that the different tiers of conductors are not actually different when it comes to transferring heat from multiple sources. Using heat generators (with 5 lava contacts) and basic pipes to a minimum-sized boiler provides 8mb/T of steam for each generator, but **only** when the generators are connected in parallel rather than series. Upgrading conductor tier doesn't change this.

Seems to be an oversight, surely the higher tiers of conductors have increased heat conductivity across a single series circuit and so can carry the heat from more than 1 generator.

Version 290 of course on forge 2076 of course in case this is a bug with my configuration rather than mek.

**Comment by aidancbrady** [comment]
Not a bug, there's currently a very very small difference between the different conductors. This will likely change in the future.
