### ISSUE TITLE
Strange cross-mod interaction between TiCo and Mekanism

### ISSUE THREAD

**Issue by utoc** [aidancbrady/Mekanism#3747]
Running TiCo 2.4.0 w Mantle 0.10.4, FML 2076 and Mekanism Dev build

The setup: Make a smeltery. 3x3x10 seems to be consistent. Now place any non-basic energy cube block from Mekanism in the same chunk. Advanced energy Cube. Elite, Ultimate. Place a few of the MCMultiPart universal cables too if you like. Whatever, etc. Now, wait. Its a bit random but eventually (within 20-40 seconds) the advanced/elite/ultimate tiers will be stripped down and show basic in TOP (the one probe) as well as the basic textures in-game looking at the item. All the multipart cables flash in and out of existence briefly. If you right click the energy block to open the GUI, it shows its proper form again (advanced, elite etc) but during the next few seconds it'll go back to being a basic when the tiles update.

I sent this to [TiCo's repo](https://github.com/SlimeKnights/TinkersConstruct/issues/2369) first, boni said this was possibly a bulk tile update event?

Seen here: http://i.imgur.com/0IEy1ed.gifv

**Comment by Utildayael** [comment]
This kind of sounds like my issue in #3740 with the induction matrix components placing properly then updating to different colors which, in most cases, is to show the "basic" level of the item instead of advanced/elite/ultimate. Sadly with those you can't open the GUI as they don't have one. :)

**Comment by utoc** [comment]
That is very similar behavior, might be the same issue? We'll see..

**Comment by aidancbrady** [comment]
This has been fixed as of the latest 1.11 versions.
