### ISSUE TITLE
[Bug] Induction Matrix Not Showing Output

### ISSUE THREAD

**Issue by Utildayael** [aidancbrady/Mekanism#3749]
Problem: Induction matrix reports input but does not report the output even when I know there is output and can watch the power storage drain.

So I thought this was maybe an issue with using a mix of EnderIO cables and Mekanism cables so I removed everything but the Mek cables and still exists... this has been an issue since Mekanism 9.0.

Mekanism 9.1.1
MC 1.10.2
Forge 2065

Thanks :)

**Comment by Utildayael** [comment]
Screenshot...

http://imgur.com/a/9OTe4

**Comment by aidancbrady** [comment]
Yeah, this is definitely a strange issue and I'm fairly confident it has to do with structures placed between chunk boundaries.  Closing as this is mentioned in several other issues, but it's being looked into.
