### ISSUE TITLE
Latency When Placing Conduits

### ISSUE THREAD

**Issue by Utildayael** [aidancbrady/Mekanism#3751]
Possibly solved with your transmitter fixes [I hope!] ...

When I place or remove any type of conduit [power seems worst] I get latency placing/removing the block. This happens if the conduit is attached to a power source [or liquid tank, gas tank, etc] and seems to be really any type of conduit that has a buffer as I haven't seen this with logistics pipes but I could be mistaken.

I can't repro in SP but it happens on MP 100% of the time.

Short/long runs... doesn't seem to matter.

Example setup below. If I break/place any cable between those gas gens and the induction port it is super laggy.

http://imgur.com/a/FYVMT

That's an easy setup. Really any setup I have is having this same issue but the gas gens seemed a good one to pass along since it is 100% Mekanism parts and is a very small configuration.

Thanks

**Comment by Utildayael** [comment]
Oops.

Mekanism 9.1.1
MC 1.10.2
Forge 2065

FWIW I experience similar issues with EnderIO conduits and have a bug open with that developer as well. Forge issue maybe??

Thanks :)

**Comment by aidancbrady** [comment]
I'm afraid this links to MCMultipart and their placement logic; not much I can do :(

**Comment by Utildayael** [comment]
That definitely helps with where the issue goes next. Appreciate the info. :)

**Comment by Utildayael** [comment]
Side note. Opened an issue with MCMultiPart and linked to this. Hopefully they have a fix!

Thanks again.
