### ISSUE TITLE
[Bug] Multiparts not blocking pipe connections

### ISSUE THREAD

**Issue by Utildayael** [aidancbrady/Mekanism#3753]
So in 1.7.10 you could use Forge Microblocks to make the thin covers to place between say, two pressurized pipes from Mekanism and that would keep the two from connecting. In 1.10.2 we have chisel and bits and while the pipes behave *much* better with the multiparts as covers to hide them, they seem to have lost the "don't connect through a multipart!" functionality.

I can place a cable/pipe and a "cover" equivalent on its side. If I place any cable/pipe that normally would connect to it next to it, it just connects right through the cover.

Bit annoying when dealing with liquid or gas lines that you really want to keep separate without leaving a space between them. I miss being able to run lines parallel. :)

Mek 9.1.1
MC 1.10.2
Forge 2065

Cheers!

**Comment by aidancbrady** [comment]
Fixed in dev :)

**Comment by Utildayael** [comment]
Boom!
