### ISSUE TITLE
Factory Performance - Major FPS Drops

### ISSUE THREAD

**Issue by Utildayael** [aidancbrady/Mekanism#3755]
You may hate me at this point Aidan... :)

So you fixed the issue with factory performance in #3572 for 9.1.1 but I seem to have found another scenario where fps tanks when using factories. I found this as I also found IC2 to be guilty of doing the same thing so hopefully it is the same type of issue and thusly will maybe help point you in the right direction of a fix.

It seems that if you are running a machine and it turns on then off in a fast manor, such as ore processing where some parts of the chain are much faster than another.. the on/off of the factories constantly causes significant fps pain due to all the updates being sent out. [guess based on feedback from IC2 dev Aroma for IC2 machines doing the same thing]

Example:

Tier 4 ore processing [5x]:

All elite factories with max speed upgrades but bottlenecked by the crystallizer/washer/dissolution which are super slow. As the cry/wash/diss chain slowly churns out one crystal at a time to be injected/purified/crushed/enriched/smelted... those 5 factories rip through it like it is nothing as they are max speed and are on/off within a second or less. Add in a constant flow of single crystals from the slow t4 ore proc machines and you have a perpetual update loop of pain.

Again, just a theory based on IC2's issues but hopefully that makes sense. Once factories are all done, problem goes away. 

Under normal use, read: everything in the chain is at least mostly keeping up or at least backlogged; everything works fine since your fix. It's just when earlier in the chain is slower than later in the chain by a significant amount that you get pummeled. We're talking single digit fps in many cases so it's really bad and that's with a Geforce 770 and ample ram/cpu [ok it's not a 1080 but its at least not like.. a 480... ] :)

Thanks!

**Comment by aidancbrady** [comment]
This is luckily something I added a fix for a while back. Increase the value of "UpdateDelay" in your config, it will restrict how fast a machine changes states!

**Comment by Utildayael** [comment]
Is that client update delay within Forge? Does server need this too or just client? Had poked through all the client settings which is why I missed this one under general. :)

Last q. Is this number in ticks, seconds, something else? Saw default is 10 so curious how far I should kick it up as I have no idea scale. :)

Thanks!

**Comment by aidancbrady** [comment]
The value is in ticks, and it can be set for server, client or both.  Let me know how it works!

**Comment by Utildayael** [comment]
Will test and report back! 

Thanks :)

**Comment by Utildayael** [comment]
Ok did some testing and it certainly helps! I don't tank down to single digit fps anymore but I had to go  up to 120 for it to make any difference. Went to 240 from there and it was only a few fps better but not noticeable. I noticed things like the crusher got to play their entire animation instead of it stuttering like before fwiw and no more blinking lights on the factories since the delay was eating those updates.

When running instead of single digits I'm at 15-60 with average being around 30 and occasional dips down to 15. Leaps and bounds better.

That said, even sticking pretty solid around 35 I still get "stuttering" where fps isn't dipping but the game is choppy. 

So... better? Yes. Ideal? Eh. 

I'm trying to remember as there have been so many issues fixed since 9.1.1 came out if there are any in the hopper for 9.2 release that might help with this. Sounded like you are putting that out in the next day or so if you can nail down those last couple bits so I can certainly hold off and test once 9.2 is out.

Thanks!

**Comment by aidancbrady** [comment]
Glad to hear it helped, even if it's just a little!

After fixing that transmitter issue, I've found like 5 or 6 related bugs to transmitters that I'm attempting to fix.  Remember that render issue you found where the transmitter connections would sometimes behave strangely and point in the wrong directions?  Well, my caching wasn't completed properly, and that's fixed now too.  Hopefully I'll be done soon!

**Comment by Utildayael** [comment]
Mekanism 9.2 - The transmitter update :)

I feel like your personal QA guy lately. Hopefully the reports are generally helpful. ;)

Looking forward to 9.2!
