### ISSUE TITLE
Sounds causing lock ups

### ISSUE THREAD

**Issue by iKaneki-Ken** [aidancbrady/Mekanism#3756]
No logs or anything, have to turn off sounds while Mekanism is installed in order to play modded Minecraft.

Using the latest version of Mekanism, as well as Forge 2073, Java 8 update 102, I've tested this with and without other mods, results are the same either way.

If there are some sort of way to get logs that I'm unaware of, please let me know how to get them and I will provide them.

**Comment by Utildayael** [comment]
Mekanism has its own config options for sound as well so you could try turning just that off [if you haven't already] as a workaround so you get sound from everything else at least.

**Comment by iKaneki-Ken** [comment]
Thank you for the suggestion, but even with those settings turned off, I still freeze up completely.

**Comment by VT-14** [comment]
You can manually crash Minecraft by holding F3 + C for 10 seconds.  That crash log might help.


How to find logs:

There are 2 kinds of logs; generic (running) and crash.  generic logs are generated every time you start that instance, and a crash log is generated when your game crashes.

Both can be found in that Minecraft Instance's folder (the same one as your Config folder).  Most launchers have some way to open this folder, or you can find it by searching for that instance's name.

Generic logs are saved in the "logs" folder.  Crash logs are saved in the "crash-reports" folder.  If you are playing on a server, you may need to contact an admin to get the server's generic logs.

If you locked up last time you played, then the best file to upload is latest.log.  If you can get it to crash, then upload the crash report with the proper time stamp as well.  Please upload these massive walls of text on something like Pastebin or a Github Gist (You can make a Gist by going to Github's header), and posting a link on here.

**Comment by iKaneki-Ken** [comment]
Alright checked the latest.log file, no errors pop up in it when I attempt to turn on sound. The client just locks up and that's it. No errors reports in any logs or crash reports.

**Comment by aidancbrady** [comment]
I can't reproduce this. Regardless, I doubt this would happen in the latest releases.
