### ISSUE TITLE
[1.10.2] [Bug] Ghost items within smelting factories

### ISSUE THREAD

**Issue by SnowShock35** [aidancbrady/Mekanism#3758]
### Crucial Information
 
* Minecraft 1.10.2
* Minecraft Forge 12.18.1.2076
* Mekanism-1.10.2-9.1.1.290
* MekanismTools & Generators are also installed (Same as above version) 
 
### Details of Issue
 
Elite Smelting Factories take items but leave a ghost item in player inventory 
 
*****

> **DISCLAIMER:** This issue is reported on behalf of bugs found by the FTB Beta Team when testing packs please excuse the minimal information on the issue given (If a mod list of the pack is required it will be provided in confidence as the pack is not yet available to the public)

**Comment by aidancbrady** [comment]
Not on my end.
