### ISSUE TITLE
Enrichment chamber not turning dirty silver dusts into silver dust

### ISSUE THREAD

**Issue by iluvdemomanandjunkrat** [aidancbrady/Mekanism#3759]
^
 |
 |

**Comment by aidancbrady** [comment]
This is a mod interaction issue; not on my end.

**Comment by githubnemo** [comment]
It's a weird one though. I have the same problem. Mekanism does the following for each dirty dust and registered resource:

	RecipeHandler.addEnrichmentChamberRecipe(StackUtils.size(ore, 1), new ItemStack(MekanismItems.Dust, 1, resource.ordinal()));

yet, the only thing that does not work is `dustDirtySilver. All other dust types work. JEI does not list a recipe for dirty silver dust. Adding a furnace recipe via crafttweaker for dirty dust -> dust works.
