### ISSUE TITLE
Request: Be able to fuel jetpack using ethylene that burns more efficiently/faster forward movement

### ISSUE THREAD

**Issue by LordHellscream** [aidancbrady/Mekanism#3761]
Your jetpack is the best thing happened to modded minecraft (its so beautiful, its beyond comprehension), that being said, it will be even more extremely awesome (if that's even possible) if it can be added a little extra
-- a version of jetpack that powered by ethylene, the idea is that it has a much more complex and efficient (likely more expensive) engine that is powered by the potent ethylene instead of hydrogen.
The main difference is that this ethylene-powered jetpack can do forward motion much faster (let a jet) and become a effective means to travel for long distance quickly.

Thanks again for such a phenomenal mod!

**Comment by yutang13** [comment]
Yes please! The jetpack is soo bad now for moving horizontally.

Also, don't forget my idea of having an elytra upgrade too Aidan ;)

**Comment by aidancbrady** [comment]
I'd personally rather add a universal "gliding mode" to the Jetpack to allow for quick horizontal movement, as done with the glider in Open Blocks.  Expect this soon :)

**Comment by LordHellscream** [comment]
Awesome! make sure its fast :) It will be like Iron man + Thor (the atomic assembler) 
Thanks again for such as a incredible mod.
