### ISSUE TITLE
Crash on startup after 9.2 update

### ISSUE THREAD

**Issue by d0wns3t** [aidancbrady/Mekanism#3762]
no other changes than update from 9.1.0 to 9.2 but now get crash on startup
[crash-2016-09-07_13.11.40-client.txt](https://github.com/aidancbrady/Mekanism/files/458200/crash-2016-09-07_13.11.40-client.txt)
tried without optifine but it didnt change anything

**Comment by UnPure** [comment]
Same problem as in issue https://github.com/aidancbrady/Mekanism/issues/3763.

**Comment by aidancbrady** [comment]
Fixed in build 292.

**Comment by d0wns3t** [comment]
I just had a weird situation where Power seemed to be infinite due to some
strange loopinh of cables around a power cell.  Not sure if I can replicate
it again but there's no way I should have been running all the machinery I
had from the power Gen I had.

Sorry I know this is very vague, I'm playing aground a bit trying to
reproduce the problem and will report it properly if I can replicate it

**Comment by d0wns3t** [comment]
Sorry last comment is unrelated, not overly familiar with GitHub, apologies
