### ISSUE TITLE
Mekanism: Tesselating Block in World

### ISSUE THREAD

**Issue by ZeetherTX** [aidancbrady/Mekanism#3764]
Sometimes when i place a Pipe or a Conduit this will happen:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingHook (Mekanism-1.10.2-9.1.1.290.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  MalisisCorePlugin (malisiscore-1.9.4-4.1.1.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 9/5/16 8:04 PM
Description: Tesselating block in world

java.util.ConcurrentModificationException
	at com.google.common.collect.HashBiMap$Itr.checkForConcurrentModification(HashBiMap.java:339)
	at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:345)
	at mcmultipart.multipart.MultipartContainer.getExtendedStates(MultipartContainer.java:484)
	at mcmultipart.block.BlockMultipartContainer.getExtendedState(BlockMultipartContainer.java:402)
	at mcmultipart.block.BlockMultipartContainer.getExtendedState(BlockMultipartContainer.java:66)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:278)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.collect.HashBiMap$Itr.checkForConcurrentModification(HashBiMap.java:339)
	at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:345)
	at mcmultipart.multipart.MultipartContainer.getExtendedStates(MultipartContainer.java:484)
	at mcmultipart.block.BlockMultipartContainer.getExtendedState(BlockMultipartContainer.java:402)
	at mcmultipart.block.BlockMultipartContainer.getExtendedState(BlockMultipartContainer.java:66)

-- Block being tesselated --
Details:
	Block type: ID #348 (tile.null // mcmultipart.block.BlockMultipartContainer)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (1660,238,-1033), Chunk: (at 12,14,7 in 103,-65; contains blocks 1648,0,-1040 to 1663,255,-1025), Region: (3,-3; contains chunks 96,-96 to 127,-65, blocks 1536,0,-1536 to 2047,255,-1025)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['ZeetherTX'/983933, l='MpServer', x=1660.35, y=237.00, z=-1034.04]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (1670,4,-1035), Chunk: (at 6,0,5 in 104,-65; contains blocks 1664,0,-1040 to 1679,255,-1025), Region: (3,-3; contains chunks 96,-96 to 127,-65, blocks 1536,0,-1536 to 2047,255,-1025)
	Level time: 12059 game time, 12059 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 2 total; [EntityPlayerSP['ZeetherTX'/983933, l='MpServer', x=1660.35, y=237.00, z=-1034.04], EntityMinecartChest['Minecart with Chest'/983837, l='MpServer', x=1601.50, y=123.06, z=-1002.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:498)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:57)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1853971864 bytes (1768 MB) / 3200253952 bytes (3052 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.1.2076 Optifine OptiFine_1.10.2_HD_U_C3 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2076.jar) 
	UCHIJAAAAAAAAAAAAAA	Forge{12.18.1.2076} [Minecraft Forge] (forge-1.10.2-12.18.1.2076.jar) 
	UCHIJAAAAAAAAAAAAAA	BiomesOPlenty{5.0.0.2080} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2080-universal.jar) 
	UCHIJAAAAAAAAAAAAAA	Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
	UCHIJAAAAAAAAAAAAAA	mcmultipart{1.2.0_74} [MCMultiPart] (MCMultiPart-experimental-1.2.0_74-universal.jar) 
	UCHIJAAAAAAAAAAAAAA	chiselsandbits{12.1} [Chisels & Bits] (chiselsandbits-12.1.jar) 
	UCHIJAAAAAAAAAAAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAAAAAAAAAAAA	JEI{3.9.0.246} [Just Enough Items] (jei_1.10.2-3.9.0.246.jar) 
	UCHIJAAAAAAAAAAAAAA	journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
	UCHIJAAAAAAAAAAAAAA	malisiscore{1.9.4-4.1.1} [MalisisCore] (malisiscore-1.9.4-4.1.1.jar) 
	UCHIJAAAAAAAAAAAAAA	malisisdoors{1.9.4-5.0.4} [MalisisDoors] (malisisdoors-1.9.4-5.0.4.jar) 
	UCHIJAAAAAAAAAAAAAA	mantle{1.10.2-0.10.4.jenkins163} [Mantle] (Mantle-1.10.2-0.10.4.jar) 
	UCHIJAAAAAAAAAAAAAA	Mekanism{9.1.1} [Mekanism] (Mekanism-1.10.2-9.1.1.290.jar) 
	UCHIJAAAAAAAAAAAAAA	MekanismGenerators{9.1.1} [MekanismGenerators] (MekanismGenerators-1.10.2-9.1.1.290.jar) 
	UCHIJAAAAAAAAAAAAAA	MekanismTools{9.1.1} [MekanismTools] (MekanismTools-1.10.2-9.1.1.290.jar) 
	UCHIJAAAAAAAAAAAAAA	reborncore{2.6.2.27} [RebornCore] (RebornCore-1.10.2-2.6.2.27-universal.jar) 
	UCHIJAAAAAAAAAAAAAA	reborncore-mcmultipart{2.6.2.27} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.6.2.27-universal.jar) 
	UCHIJAAAAAAAAAAAAAA	rftools{5.21} [RFTools] (rftools-1.10-5.21.jar) 
	UCHIJAAAAAAAAAAAAAA	StorageDrawers{1.10.2-3.2.6} [Storage Drawers] (StorageDrawers-1.10.2-3.2.6.jar) 
	UCHIJAAAAAAAAAAAAAA	tconstruct{1.10.2-2.4.0.jenkins325} [Tinkers' Construct] (TConstruct-1.10.2-2.4.0.jar) 
	UCHIJAAAAAAAAAAAAAA	techreborn{1.4.0.45} [TechReborn] (TechReborn-1.10.2-1.4.0.45-universal.jar) 
	UCHIJAAAAAAAAAAAAAA	tesla{1.2.1.49} [TESLA] (Tesla-1.10.2-1.2.1.49.jar) 
	UCHIJAAAAAAAAAAAAAA	VeinMiner{0.34.1_1.9-73be663} [Vein Miner] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCHIJAAAAAAAAAAAAAA	VeinMinerModSupport{0.34.1_1.9-73be663} [Mod Support] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCHIJAAAAAAAAAAAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.0.203.jar) 
	UCHIJAAAAAAAAAAAAAA	wawla{2.3.0.202} [What Are We Looking At] (Wawla-1.10.2-2.3.0.203.jar) 
	Loaded coremods (and transformers): 
LoadingHook (Mekanism-1.10.2-9.1.1.290.jar)
  
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
MalisisCorePlugin (malisiscore-1.9.4-4.1.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	Launched Version: 1.10.2-forge1.10.2-12.18.1.2076
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM)2 Quad CPU Q6700 @ 2.66GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_C3
	Render Distance Chunks: 5
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 372.70
	OpenGlRenderer: GeForce GTX 750 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

Hopefully this will be fixed in a later update ;)

ZeetherTX

**Comment by aidancbrady** [comment]
Report to McMultipart.
