### ISSUE TITLE
[Suggestion] Be able to stop pipes connecting

### ISSUE THREAD

**Issue by yutang13** [aidancbrady/Mekanism#3765]
I really wish there was a way to stop similar transmitters from connecting together. Currently it is impossible to run say two fluid pipes next to each other with different purposes.
I've had to go to great lengths to stop my Hydrogen and Hydrogen Chloride supplies from mixing together :( 
Being able to tell pipes to stop connecting would be amazing!

**Comment by rdunham3** [comment]
I think the microblocks covers I've used for this were from the Extra Utilities mod. Put one between the pipes and they don't connect.

**Comment by DFliyerz** [comment]
Just use the Configurator to change the pipe colors.

**Comment by aidancbrady** [comment]
Indeed, use micro blocks for now. I'll consider adding color support in the future.

**Comment by Zixiken** [comment]
In recent versions cables/pipes/etc seem to have lost microblocks support. Is this a new bug, or is it intentional in favor of replacing it with the aforementioned color support?

**Comment by Zixiken** [comment]
Looks like I had the wrong mod installed...in case anyone is wondering, you need the MCMultiPart API installed.
