### ISSUE TITLE
1.10.2 (Mekanism 290) - Item clogging up the Entangloporter network

### ISSUE THREAD

**Issue by LordHellscream** [aidancbrady/Mekanism#3767]
The quantum entangloporter will take an item into the network even when there is no receiving end for it. This resulting all other items being stuck in the pipeline. 

For example, I have a auto-farm for wheat and seeds I use the entangloporter to output the crop into my storage, and have a crafter to create hoes and input that into the entangloporter for the machine. At one point my entangloporter stopped working completely, after much debugging I found out that there is a hoe stuck in the network, since the farming machine cannot take another hoe it ends up stucked and completely blocked the pipeline.

This mean one channel/network can only reliably transfer 1 type of item at any given time to prevent it from randomly breaking because one of the receiving end is full, it seems quite limiting. 

Is it possible to NOT put any item to the network when the receiving side is full (or cannot take anymore item).

**Comment by aidancbrady** [comment]
The best way to avoid this is to make sure Entangloporters can always stream items; have backlog chests in your sorting systems, always make sure items and blocks have a place to go.  The Logistical Sorter definitely helps with this!

**Comment by thiakil** [comment]
@LordHellscream An Entangleporter Frequency _is_ a destination, as it has a 1 slot buffer to allow you to pull from it; it's not a proxy for the other ends.
