### ISSUE TITLE
1.10.2 - After update to 9.2.0.292 users reporting teleporters links are gone

### ISSUE THREAD

**Issue by viper2g1** [aidancbrady/Mekanism#3768]
I'm not sure if this is intended or not thru the update, and I have no crash log but I have reports from my users that this is occurring.  

Just reporting it.

**Comment by dhalek** [comment]
I can confirm this. After upgrading to 9.2.0.292 my portable teleporter lost link to every teleporter block. I hat to travel to them and reestablish the links. One link survives game restart while the other farer away one does not. I have this issue in singleplayer.

**Comment by aidancbrady** [comment]
Teleporters now require 'Anchor Upgrades' to remain loaded.
