### ISSUE TITLE
[1.10.2] Server Crash with Solar Flux Reborn Infinit Cables (Induction Matrix)

### ISSUE THREAD

**Issue by UnPure** [aidancbrady/Mekanism#3770]
Hey there.
I used the Solar Flux Reborn infinit cable to transfer energy from my mekanism fusion reactor to my mekanism induction matrix. Right after the induction matrix was full, the server crashed.
Its possible to start the server but after a few minutes the server is crashing again.
I dont know if that problem is on the side of mekanism, but i reported it on both sides.

Crashlog: http://pastebin.com/pFucZ3gu
Solar Flux Reborn Issue: https://minecraft.curseforge.com/projects/solar-flux-reborn/issues/10

If you need any other informations, let me know!

**Comment by MrDimkasStudio** [comment]
It was my problem with not knowing math, oh well... :/
And I fixed it.
