### ISSUE TITLE
API not compleate and many Problems

### ISSUE THREAD

**Issue by chaos234** [aidancbrady/Mekanism#3771]
Hey @aidancbrady ,

I actually trying to get my addition out as seperate addon but it isn't easy.

The API is quite small and I could not found any maven so I used bdew thirdparty maven to implement your API for 1.10.2.

It will be glad if you can implement the Shaped/ShaplessMekansimRecipe stuff and the Multiblock stuff so that I must not implement my own one.

Also some acces to e. g. the circuit tiers will be glad too and an option to add config valus to the actually one.

Sourccode can be found here: https://github.com/chaos234/MekanismAdditions/tree/1.10.2
But I have trouble with the empty proxys: http://paste.ee/p/3qryt

I also contacted you over Skype but without any response from your side so I hope that you can help me out like you have said it in the past.

**Comment by aidancbrady** [comment]
Your proxy issue has to do with you not extending CommonProxy in your ClientProxy.

The API is small for a reason; it's meant as an application programming _interface_, not as a library that contains Mekanism's functional code.  As I said before, you can definitely reference core Mekanism classes in your module, but you should refrain from shipping Mekanism code that is not the API in your packaged mod.

**Comment by chaos234** [comment]
For 1.7.10:

I have inserted the liquid system but the images are not what htey should be.
Please refere: https://github.com/chaos234/MekanismAdditions/issues/1

For 1.10.2:

I found out, that the new ModelRender needs a specific .json file which I have added and now my
InformationTab is in.

I must only change it to that what it should be.

My Secound way for Heavy Water and Deuterium for 1.10.2 is compleatly finished. Only language is missing.

How can I distribute it?

**Comment by chaos234** [comment]
Ok, all images and system are working now, only the gui for my information tablet is missing :)
