### ISSUE TITLE
[1.7.10] Weird Issue with Mekanism Reactor

### ISSUE THREAD

**Issue by MJRLegends** [aidancbrady/Mekanism#3772]
I having issues with the mekanism reactor turning off, it seems to be at random times when i log off then come on later on like hours or days after and the reactor is off. The reactor isn't chunk-loaded while im not online. 

I dont think fuel is a issue as it seems to run fine for hours if im staying online, when i come back online and its off it seems the injection rate changes to 0??

Not really sure what the issue is here.

Im using Thermos and latest forge and Mekanism

**Comment by chaos234** [comment]
Simpley place a chunk loader. This should/can fix your problem.

Since I does it with chunk loading, I have never had any on/off problems.

**Comment by MJRLegends** [comment]
I am using a chunk loader im using a Dimensional anchor

**Comment by MJRLegends** [comment]
Think i have found the issue i will reply back here and close the issue when i confirm its the issue im having

**Comment by MJRLegends** [comment]
Fixed it was my issue

**Comment by MJRLegends** [comment]
Im still getting a issue with the injection rate changing back to 0 after server restart @aidancbrady @chaos234

**Comment by Omgalof** [comment]
i can confirm this is happening in MP as well. also chunk loaders are a bad workaround cause some will only work if the player that owns then is on.

**Comment by MJRLegends** [comment]
@omgalof what setup do you have for mp like what mod pack/server jar/plugins and that

**Comment by Omgalof** [comment]
the Ferret Business, it is the mineyourmind server, but details about the server i don't know

**Comment by MJRLegends** [comment]
@aidancbrady I know your probably busy, but any thoughts on this issue?

**Comment by Just-some-cannibal** [comment]
Happens to me too

**Comment by falizure** [comment]
In my experience this has been a persistent problem with reactor across multiple versions, chunk loaders help while you are online but in teh case of a server they always seam to break after going away for  some time, i personally suspect it has to do with others loading the chunks but not activating whatever you use for chunkloading, personally the servers i play on have always used the railcraft personal anchors.

**Comment by aidancbrady** [comment]
I made a few fixes that should hopefully solve this issue.

**Comment by MJRLegends** [comment]
@aidancbrady for the 1.7.10 version, if so will there be a download? i only ask as im going to be making a update for my mod pack so would be amazing if i could include it in the update
