### ISSUE TITLE
[1.10.2 9.2.0.292] TESLA TileEntityElectricBlock Capability NoSuchMethodException

### ISSUE THREAD

**Issue by rreeggkk** [aidancbrady/Mekanism#3778]
When calling getCapability() with a TESLA Consumer capability on a TileEntityElectricBlock a NoSuchMethodException gets thrown from [this line](https://github.com/aidancbrady/Mekanism/blob/1.10/src/main/java/mekanism/common/capabilities/CapabilityWrapperManager.java#L26). I believe this is caused by the fact that the teslaManager in the TileEntityElectricBlock is created using IEnergyWrapper as the type parameter. When the reflection is later run in the CapabilityWrapperManager, it fails to find a constructor that accepts a mekanism.common.base.IEnergyWrapper as its first parameter. [Here is the full exception.](http://pastebin.com/JJfDQTL7)

**Comment by aidancbrady** [comment]
Fixed, thanks
