### ISSUE TITLE
[1.10.2-9.2.0.292] Energy upgrade has no effect on electrolytic separator

### ISSUE THREAD

**Issue by jco2641** [aidancbrady/Mekanism#3781]
Mekanism version: 9.2.0.292
Forge 12.18.1.2077

Electrolytic separator (processing water) is using 400 J/t running without any upgrades.
Inserting any amount of energy upgrades does not change the reported energy usage in the GUI.  After inserting 8 upgrades, it still reports using 400J/t.

Not happening in any other machines or factories I've tried.  Speed upgrades work normally in the separator.

**Comment by aidancbrady** [comment]
Intended.

**Comment by jco2641** [comment]
Then the tool-tip in the upgrade window on the separator should not indicate energy upgrades are supported, and the machine should not accept them.

**Comment by aidancbrady** [comment]
The Energy Upgrade still boosts energy capacity.

**Comment by bookerthegeek** [comment]
Why not split the energy upgrade into speed and capacity upgrades? That will stop this and add an additional mechanic.  :)

**Comment by VT-14** [comment]
Does anyone really use the increased energy storage feature of Energy Upgrades?  That feature could be cut and I don't think many people would notice.

Why do mods increase power buffers anyway?  If its something about increased power usage, then why isn't that feature on the Speed Upgrades or a separate upgrade instead?

**Comment by jco2641** [comment]
I think that it makes perfect sense the way it is. Capacity and efficiency seem to both be needed numerically if you max out on speed upgrades.
My main complant is the discoverability of the separator being an exception to half the effect of the energy upgrade.  
An update on the wiki would help, and some way to discover it in the ui in game would be really nice, maybe a little more text when the energy upgrade is selected.
