### ISSUE TITLE
Dynamic tank high network usage due to logic error

### ISSUE THREAD

**Issue by tossaponk** [aidancbrady/Mekanism#3785]
Refer to my last issue about excessive rendering update packet. #2690

It seems that there's an attempt to detect fluid type change by storing them into "prevFluid". But due to logic error causing the "prevFluid" to always be null and making needRenderUpdate() to always return true thus sending rendering update packet every tick for each tank.

Refer to this line 
https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/tile/TileEntityDynamicTank.java#119

**Comment by aidancbrady** [comment]
Done, thanks!
