### ISSUE TITLE
Request - Pipe redstone sensitivity change

### ISSUE THREAD

**Issue by jco2641** [aidancbrady/Mekanism#3787]
Should pipe redstone sensitivity default to off?  

I can certainly see the utility of being able to toggle a pipe connection with a redstone signal.  But in the case of a buried pipe that you've forgotten is present, it can cause a great deal of frustrated troubleshooting.  

I think it would be reasonable for a person that wants to switch a pipe at a certain point need to toggle redstone sensitivity on at that single block, rather than a person who doesn't want it (or doesn't know about it) needing to turn it off at any place it runs past a powered block.

Alternately, If the detection could distinguish between the pipe being directly powered (adjacent to a redstone source) vs indirectly (adjacent to a powered block) that would eliminate the chance of a redstone wire run atop a block with a buried pipe below causing an unintended disconnect.

**Comment by yutang13** [comment]
I agree. May also slightly help performance if they're not checking for redstone updates.

**Comment by aidancbrady** [comment]
Done, thanks! Now off by default.
