### ISSUE TITLE
[1.10.2 9.2.0.292] Teleporter immediately ports back to original location

### ISSUE THREAD

**Issue by neomelonas** [aidancbrady/Mekanism#3790]
I made a [webm](https://a.vidga.me/mhktta.webm) of the weirdness, but what happens is when I walk through one teleporter, I appear on the other end, long enough to see several chunks load, then get sent back to my starting location.  Server logs are apparently empty of any reasoning for this, per the server admin.

We're running All The Mods 1.10.2v1.22.

**Comment by aidancbrady** [comment]
Apparently fixed in 1.11.
