### ISSUE TITLE
Compat Request (1.7.10)

### ISSUE THREAD

**Issue by bookerthegeek** [aidancbrady/Mekanism#3792]
[Magneticraft](https://github.com/Magneticraft-Team/Magneticraft) Includes its own heat mechanic which acording to its author is FMP compatable. Would it be feasible to make compatible with your heat?

**Comment by aidancbrady** [comment]
Integration with other heat systems can be tricky; I'd rather leave foreign energy transfer up to electricity.

**Comment by bookerthegeek** [comment]
Rodger. Are you open to others being compatible with yours?

**Comment by aidancbrady** [comment]
Definitely!
