### ISSUE TITLE
Add config files to add stuff to machines.

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [aidancbrady/Mekanism#3793]
Much like https://github.com/SleepyTrousers/EnderIO/tree/master/resources/assets/enderio/config does, with their .xml files, it'd be great to be able to add stuff to machines.

Like Industrial Hemp Seeds from Immersive Engineering to the crusher to get bio fuel for instance.

**Comment by aidancbrady** [comment]
I integrate with the IMC API which should allow for other mods to easily add their own materials to Mekanism's processing.  Perhaps I'll consider adding a user entry-defined way to add recipes in the future, but I'm happy with the functionality at the moment.
