### ISSUE TITLE
Request: allow bin to input-output from all side

### ISSUE THREAD

**Issue by LordHellscream** [aidancbrady/Mekanism#3795]
Bin is great and having advantage over the storage drawer since storage number is not limited due to stack size. 

However, there are two shortcomings:
1. its very difficult to position it due to restriction of input/output sides.
1. it is not possible to connect it to something like storage network like storage drawers do.

Is it possible to make input/output from any sides (and be recognized as a normal storage unit and can be connected to a storage network).

**Comment by aidancbrady** [comment]
Already suggested, definitely considering!
