### ISSUE TITLE
[1.10.2] Digital Miner Filter not working

### ISSUE THREAD

**Issue by UnPure** [aidancbrady/Mekanism#3796]
Hey there.
I'm currently trying to setup my digital miner in the nether,
It seems like the filter is not working.
I tried it with every possible setting to filter for specific ores and i tried the inverse too.
Its just mining everything it can find.

Mekanism: 9.2.0.292
Forge: 12.18.1.2076

If you need any other informations, let me know.

**Comment by aidancbrady** [comment]
Pretty sure I fixed this a few weeks ago, can't seem to reproduce.
