### ISSUE TITLE
[1.7.10] [Minetweaker] Why do Mekanism machines need NBT tags on input to match exactly?

### ISSUE THREAD

**Issue by Robijnvogel** [aidancbrady/Mekanism#3799]
Using Minetweaker and Technomancy I found that Mekanism machines are the only machines I have found so far, that need you to specify the exact item NBT tag for an input item if it has any NBT tag at all.*

All other machines, Vanilla, IC2, IE, TE, Fz, etc. just accept any NBT tag on the item, if you do not specify an NBT tag in the minetweaker recipe.

I really wonder why this is and if it could be changed.

Much appreciated!

*Technomancy semi-products have NBT Data to keep track of their previous processing steps.
I will post this on the MT Issue Tracker as well.

**Comment by aidancbrady** [comment]
NBT is necessary for many Mekanism items to not be confused in recipes.

**Comment by Robijnvogel** [comment]
Yet, no other mods seem to need this.
And why would an input item without any NBT **not** mean "this specific item with any NBT attached"?

**Comment by aidancbrady** [comment]
Energy cubes use NBT for differentiating between tiers. Factories use NBT for different recipe types. There's many other cases that require this kind of functionality.
