### ISSUE TITLE
Elite Induction cells + providers - probs in creating process / Energy Cubes change tier in crafter recipe

### ISSUE THREAD

**Issue by Tessellry** [aidancbrady/Mekanism#3800]
MC 1.10.2
Forge 12.18.1.2086
Mekanism 1.10.2-9.2.0.292
TConstruct 1.10-2.3.3a
RFTools 1.10-5.22
Principium 1.1.0

Crafting Induction cells and Providers and both of them in elite version disapears being crafted in Tcon table. Repeated the procedure a second time with both types to be sure and every time the same happend. Start with 1 Elite cell and provider in my inventory and then do another of the same sort - klick on plus (+) material is used to create it but I dont get a second one - still have only one in my inventory. And the material used is uneven in the end. Had 12 advanced to begin with - did the maneuver twice, should have had 4 but had only 2 left.  My guess is that the elite counts as an advanced still and is used as such - the next time - in making another elite.

When using RFTools Crafter the Elite Energy Cube is exchanged to an Advanced instead in the recipe after klicking on the Apply button. The cubes tiers changes also in other recipies so cant use the crafter.

**Comment by aidancbrady** [comment]
Sounds like RFTools doesn't care about crafting item NBT values.  This is not on my end.
