### ISSUE TITLE
[bug] Cardboard Box -> Bed, is buggy

### ISSUE THREAD

**Issue by rapus95** [aidancbrady/Mekanism#3801]
Using a Cardboard Box on a bed will remove the whole bed but place only half of the bed on unwrapping -> when triggering a block update the half bed is removed due to an invalid state -> you destroyed a bed

**Comment by yutang13** [comment]
Same thing happens with doors. I found the trick is to not try and pick up a bed XD 

Not sure if this is even an issue. Being able to pick up blocks like this will always cause issues with something

**Comment by rdunham3** [comment]
I agree...anything that's more than 1 block in size shouldn't be valid for the box to act upon.

**Comment by TheGuyRunningSouth** [comment]
Blacklist it in the config, and maybe if we bug Aidan about it enough he'll make that a default.

**Comment by aidancbrady** [comment]
Fixed!
