### ISSUE TITLE
[Enhancement/Bug] Cardbox doesn't remember its relative orientation

### ISSUE THREAD

**Issue by rapus95** [aidancbrady/Mekanism#3803]
In contrast to what is written in the wiki, that the cardbox will remember its orientation, it instead works like this: when i unwrap a cardbox the front will always face me, thus making it difficult to place a block frontside back. It'd be nice, if the cardbox would remember from which side i packed the box and when i place the box (or when i unwrap it) that side should face me again.

**Comment by aidancbrady** [comment]
Technically the box doesn't store any such information; the contained block runs its own logic code which may result in the orientation being changed.
