### ISSUE TITLE
[bug] Jetpack somehow resets consumed hydrogen regularly

### ISSUE THREAD

**Issue by rapus95** [aidancbrady/Mekanism#3805]
(1.10.2)
Situation: Ascending in regular mode.
2 Ways:
a) switch to hover mode while keeping space pressed. The used hydrogen since the beginning of the "flight" is being restored.
b) stop holding space and once you have some nice falling speed press and hold space again. You're slowing the fall and the used hydrogen is restored aswell

**Comment by LousyLynx** [comment]
I am getting this bug also

**Comment by yepidoodles** [comment]
I'm seeing this on my SpongeForge server.

Mekanism-1.10.2-9.2.3.97 (+ Tools and Generators)
spongeforge-1.10.2-2281-5.2.0-BETA-2597
[Modpack](https://www.technicpack.net/modpack/172-dragontech-testserver.408937)

**Comment by thiakil** [comment]
Please refrain from adding "me too" comments to issues. You can subscribe to updates in the sidebar without adding a comment.

**Comment by yepidoodles** [comment]
@thiakil The more relevant information they can get, the better. In my case, this hasn't been posted on in so long, it was unclear if anyone was still getting it for this version (1.10.2).

**Comment by thiakil** [comment]
Still open = hasn't been fixed.

And just a heads up, it likely won't be fixed in 1.10. Non crashing issues are unsupported.
