### ISSUE TITLE
[enhancement] provide a way to disable the "auto-ascend" on free runners

### ISSUE THREAD

**Issue by rapus95** [aidancbrady/Mekanism#3808]
The sense is that one often uses some sort of 1-high barrier to prevent falling into a lava lake etc. (especially when mining)

Btw. is the amount of consumption reduced when wearing an armored jetpack?

**Comment by SuperFanatic** [comment]
This. Oh *please* this!

**Comment by thommy101** [comment]
Created a pull request to add a disabled feature to free runners :)

**Comment by thommy101** [comment]
Implemented in https://github.com/aidancbrady/Mekanism/commit/6f78c19cb202b131ec729483678c1ce3e3904146
