### ISSUE TITLE
[bug] shift-clicking stacks into the machines ghost-duplicates items

### ISSUE THREAD

**Issue by rapus95** [aidancbrady/Mekanism#3809]
i guess it's somewhat self explanatory:
When opening a gui, like the mechanical infuser and shift clicking some iron ingots the stack moves into the corresponding field. But instead of visually moving, one now has a ghost stack of the same size in his inventory. That one is removed a few seconds after the gui is closed. (if opening directly after one closed it, the ghost still seems to be "alive")

**Comment by aidancbrady** [comment]
Yeah, honestly have no clue where to go with this desync. It's been occurring for years and I still haven't been able to find a fix.

**Comment by rapus95** [comment]
why you don't label it as "unclear how to fix" or similar and/or maybe let it open?
