### ISSUE TITLE
[doc] [1.10.2] the sawdust->paper recipe is outdated

### ISSUE THREAD

**Issue by rapus95** [aidancbrady/Mekanism#3810]
![image](https://cloud.githubusercontent.com/assets/5960902/18616309/c3738e8e-7db9-11e6-967e-03b6d9298cd5.png)

**Comment by yutang13** [comment]
I believe the recipe is now three sawdust in a row? Check JEI/NEI

**Comment by rapus95** [comment]
Yeah, seems so, then i let it open as marker for anyone who followed the wiki aswell
(Consider to add a doc-label)
