### ISSUE TITLE
[Suggestion] Logistical Transporter Tiers

### ISSUE THREAD

**Issue by ToadsworthLP** [aidancbrady/Mekanism#3812]
Mekanism's item transport pipes has, unlike the other pipes, no tiers, which seems strange.

My suggestion is to add a cheaper, weaker version of the Logistical Transporter:

Basic Transporter, Recipe:
SGS
(S=Steel,G=Glass)

Logistical Transporter, Recipe:
BC
(B=Basic Transporter,C=Control Circuit)

While the functionality of the Logistical Transporter should stay the same, the Basic Transporter should not have any of the options that are accessed using a Configurator.
This should be optional, using a config option.

Thanks for reading :smile:

**Comment by aidancbrady** [comment]
Mekanism does have tired Logistical Transporters, each with differing item transport speeds :)
