### ISSUE TITLE
Server crash - java.lang.Error 	at mekanism.common.util.MekanismUtils.saveChunk

### ISSUE THREAD

**Issue by ProsperCraft** [aidancbrady/Mekanism#3816]
Multiplayer server crash, unkonwn cause.

Minecraft 1.10.2
Modpack Allthemods on the curse launcher.

http://pastebin.com/SKiA7SBr

**Comment by thommy101** [comment]
Watchdog issue, seems like your server tick was way too low and it killed the server. Has probably nothing to do with Mekanism.
