### ISSUE TITLE
[1.10.2, bug/enhancement] strange security behaviour

### ISSUE THREAD

**Issue by rapus95** [aidancbrady/Mekanism#3818]
Why only the placer can enter the gui of entangloporter, teleporter & Security Desk? (for some even though they don't show an owner in their tooltip at all)
If that was intended as feature, then why everyone can break and place the block himself?

2nd Point: It'd be GREAT if the owner could transfer the ownership of a tool/machine to someone else (especially when building up something together where one is crafting and the other is building)
Similar it'd be nice if machines could be made public finally
Implementation idea: add Public as a user and once someone changed owner to public only public can change the ownership. Then set every user on Publics trusted list and security override for trusted alternatively security override with public

**Comment by aidancbrady** [comment]
You can indeed transfer ownership to someone else- simply place the machine in the 'unlock' slot of a Security Desk.

Yes, teleporters and entangloporters currently are only accessible by their owners- may change in the future.

**Comment by rapus95** [comment]
@aidancbrady if it was intended to only allow the owners to use the gui, then why everyone can break the block? :/ the way it works right now is annoying while it doesn't add security :/

(No offense intended:)
You didn't say anything about the security desk. As far as i understand it, there it makes absolutely no sense to only allow the owner to use it, that'd be similar to only allow the crafter of the ender chest to use the ender chest :/
