### ISSUE TITLE
[1.10.2, critical, client renderer] after shift-right clicking a bin in the wrench mode

### ISSUE THREAD

**Issue by rapus95** [aidancbrady/Mekanism#3820]
EDIT: The problem was a bin that contained 3 bio generators and was in my lower bar of items

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 21.09.16 19:49
Description: Rendering item

java.lang.IllegalStateException: Not building!
    at net.minecraft.client.renderer.VertexBuffer.func_178977_d(VertexBuffer.java:720)
    at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
    at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:164)
    at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:135)
    at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:198)
    at net.minecraft.client.renderer.RenderItem.func_184390_a(RenderItem.java:439)
    at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:478)
    at net.minecraft.client.gui.GuiIngame.func_184044_a(GuiIngame.java:1192)
    at net.minecraft.client.gui.GuiIngame.func_180479_a(GuiIngame.java:566)
    at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:329)
    at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:140)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1369)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at net.minecraft.client.renderer.VertexBuffer.func_178977_d(VertexBuffer.java:720)
    at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
    at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:164)
    at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:135)
    at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:198)
    at net.minecraft.client.renderer.RenderItem.func_184390_a(RenderItem.java:439)

-- Item being rendered --
Details:
    Item Type: mekanism.common.item.ItemBlockBasic@3989e022
    Item Aux: 6
    Item NBT: {tier:0,mekData:{storedItem:{id:"mekanismgenerators:Generator",Count:1b,tag:{mekData:{owner:"rapus95",security:0,fluidStored:0,energyStored:0.0d,Items:[]}},Damage:4s},itemCount:3}}
    Item Foil: false
Stacktrace:
    at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:478)
    at net.minecraft.client.gui.GuiIngame.func_184044_a(GuiIngame.java:1192)
    at net.minecraft.client.gui.GuiIngame.func_180479_a(GuiIngame.java:566)
    at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:329)
    at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:140)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['rapus95'/488929, l='MpServer', x=94,70, y=54,00, z=-159,64]]
    Chunk stats: MultiplayerChunkCache: 199, 199
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (128,64,-22), Chunk: (at 0,4,10 in 8,-2; contains blocks 128,0,-32 to 143,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 7408716 game time, 8433637 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 68 total; [EntityCreeper['Creeper'/485127, l='MpServer', x=168,50, y=16,00, z=-108,50], EntityRobit['Richi=Penis'/1, l='MpServer', x=101,50, y=55,00, z=-184,50], EntityRobit['(??_?)'/2, l='MpServer', x=100,50, y=55,00, z=-184,50], EntityZombie['Zombie'/488197, l='MpServer', x=141,50, y=46,00, z=-120,50], EntityPlayerSP['rapus95'/488929, l='MpServer', x=94,70, y=54,00, z=-159,64], EntityRobit['Bonny'/3, l='MpServer', x=102,50, y=55,00, z=-184,50], EntityZombie['Zombie'/488452, l='MpServer', x=115,50, y=43,00, z=-133,50], EntityRobit['Kasper'/4, l='MpServer', x=103,50, y=55,00, z=-184,50], EntitySpider['Spider'/488451, l='MpServer', x=116,50, y=43,00, z=-132,50], EntityEnderman['Enderman'/466178, l='MpServer', x=95,57, y=42,00, z=-141,50], EntityCreeper['Creeper'/488065, l='MpServer', x=95,50, y=18,00, z=-162,50], EntityItem['item.item.Substrate'/488855, l='MpServer', x=86,50, y=50,68, z=-162,50], EntityZombie['Zombie'/487827, l='MpServer', x=147,50, y=40,00, z=-89,50], EntityItem['item.item.Substrate'/488863, l='MpServer', x=86,50, y=50,68, z=-162,50], EntitySkeleton['Skeleton'/460959, l='MpServer', x=93,30, y=42,00, z=-142,84], EntityItem['item.item.Substrate'/488862, l='MpServer', x=86,50, y=50,68, z=-162,50], EntityItem['item.item.Substrate'/488861, l='MpServer', x=86,50, y=50,68, z=-162,50], EntityItem['item.item.Substrate'/488860, l='MpServer', x=86,50, y=50,68, z=-162,50], EntityZombie['Zombie'/483484, l='MpServer', x=159,48, y=29,00, z=-108,92], EntityZombie['Zombie'/481692, l='MpServer', x=170,50, y=16,00, z=-99,50], EntityItem['item.item.Substrate'/488859, l='MpServer', x=86,50, y=50,68, z=-162,50], EntityItem['item.item.Substrate'/488858, l='MpServer', x=86,50, y=50,68, z=-162,50], EntityItem['item.item.Substrate'/488857, l='MpServer', x=86,50, y=50,68, z=-162,50], EntityItem['item.item.Substrate'/488856, l='MpServer', x=86,50, y=50,68, z=-162,50], EntityBat['Bat'/488359, l='MpServer', x=149,61, y=17,35, z=-93,28], EntityBat['Bat'/487717, l='MpServer', x=119,72, y=44,72, z=-129,46], EntitySkeleton['Skeleton'/486702, l='MpServer', x=140,50, y=41,00, z=-102,50], EntitySkeleton['Skeleton'/486701, l='MpServer', x=145,50, y=41,00, z=-106,50], EntityZombie['Zombie'/486828, l='MpServer', x=143,50, y=19,00, z=-142,50], EntityCreeper['Creeper'/486704, l='MpServer', x=143,50, y=41,00, z=-105,50], EntityItem['item.item.Substrate'/488895, l='MpServer', x=86,50, y=50,68, z=-162,50], EntityItem['item.item.Substrate'/488894, l='MpServer', x=86,50, y=50,68, z=-162,50], EntityZombie['Zombie'/487102, l='MpServer', x=147,50, y=28,00, z=-88,50], EntitySpider['Spider'/483646, l='MpServer', x=170,50, y=16,00, z=-101,50], EntityItem['item.item.Substrate'/488893, l='MpServer', x=86,50, y=50,68, z=-162,50], EntityItem['item.item.Substrate'/488892, l='MpServer', x=86,50, y=50,68, z=-162,50], EntityItem['item.item.Substrate'/488891, l='MpServer', x=86,50, y=50,68, z=-162,50], EntityCreeper['Creeper'/487620, l='MpServer', x=152,50, y=40,00, z=-117,50], EntityItem['item.item.Substrate'/488899, l='MpServer', x=86,50, y=50,68, z=-162,50], EntityCreeper['Creeper'/487619, l='MpServer', x=152,50, y=40,00, z=-118,50], EntityItem['item.item.Substrate'/488898, l='MpServer', x=86,50, y=50,68, z=-162,50], EntityItem['item.item.Substrate'/488897, l='MpServer', x=86,50, y=50,68, z=-162,50], EntitySkeleton['Skeleton'/478529, l='MpServer', x=93,29, y=42,00, z=-143,51], EntityItem['item.item.Substrate'/488896, l='MpServer', x=86,50, y=50,68, z=-162,50], EntityRabbit['Rabbit'/72, l='MpServer', x=67,46, y=83,00, z=-87,61], EntityZombie['Zombie'/486090, l='MpServer', x=145,50, y=41,00, z=-102,50], EntitySkeleton['Skeleton'/487127, l='MpServer', x=147,50, y=45,00, z=-111,50], EntityItem['item.item.Substrate'/488927, l='MpServer', x=86,50, y=50,68, z=-162,50], EntityBat['Bat'/389468, l='MpServer', x=91,93, y=43,10, z=-143,36], EntitySkeleton['Skeleton'/487386, l='MpServer', x=153,50, y=28,00, z=-97,50], EntityZombie['Zombie'/488281, l='MpServer', x=163,40, y=28,00, z=-116,00], EntityItem['item.item.Substrate'/488804, l='MpServer', x=86,50, y=50,68, z=-162,50], EntityItem['item.item.Substrate'/488803, l='MpServer', x=86,50, y=50,68, z=-162,50], EntityBat['Bat'/486243, l='MpServer', x=89,44, y=16,11, z=-160,50], EntitySkeleton['Skeleton'/466659, l='MpServer', x=94,44, y=42,00, z=-142,90], EntityItem['item.item.Substrate'/488928, l='MpServer', x=86,50, y=50,68, z=-162,50], EntitySkeleton['Skeleton'/487787, l='MpServer', x=158,50, y=40,00, z=-124,50], EntitySkeleton['Skeleton'/487786, l='MpServer', x=153,50, y=40,00, z=-120,50], EntitySkeleton['Skeleton'/392053, l='MpServer', x=80,21, y=58,00, z=-182,54], EntityBat['Bat'/486771, l='MpServer', x=135,80, y=34,00, z=-84,63], EntityItem['item.item.Substrate'/488817, l='MpServer', x=86,50, y=50,68, z=-162,50], EntitySkeleton['Skeleton'/400126, l='MpServer', x=92,31, y=42,00, z=-143,30], EntityRabbit['Rabbit'/121, l='MpServer', x=172,89, y=62,51, z=-140,17], EntityItem['item.item.Substrate'/488827, l='MpServer', x=86,50, y=50,68, z=-162,50], EntityItem['item.item.Substrate'/488826, l='MpServer', x=86,50, y=50,68, z=-162,50], EntityItem['item.item.Substrate'/488825, l='MpServer', x=86,50, y=50,68, z=-162,50], EntityZombie['Zombie'/480505, l='MpServer', x=99,80, y=42,00, z=-143,52], EntityItem['item.item.Substrate'/488824, l='MpServer', x=86,50, y=50,68, z=-162,50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:498)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 301080368 bytes (287 MB) / 812957696 bytes (775 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.32 Powered by Forge 12.18.1.2088 Optifine OptiFine_1.10.2_HD_U_C3 9 mods loaded, 9 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2088.jar) 
    UCHIJA  Forge{12.18.1.2088} [Minecraft Forge](forge-1.10.2-12.18.1.2088.jar) 
    UCHIJA  inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks](InventoryTweaks-1.61-58.jar) 
    UCHIJA  JEI{3.9.5.257} [Just Enough Items](jei_1.10.2-3.9.5.257.jar) 
    UCHIJA  mcmultipart{1.2.0_74} [MCMultiPart](MCMultiPart-experimental-1.2.0_74-universal.jar) 
    UCHIJA  Mekanism{9.2.0} [Mekanism](Mekanism-1.10.2-9.2.0.292.jar) 
    UCHIJA  MekanismGenerators{9.2.0} [MekanismGenerators](MekanismGenerators-1.10.2-9.2.0.292.jar) 
    UCHIJA  MekanismTools{9.2.0} [MekanismTools](MekanismTools-1.10.2-9.2.0.292.jar) 
    Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)

```
GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 372.70' Renderer: 'GeForce GTX 860M/PCIe/SSE2'
Launched Version: 1.10.2-forge1.10.2-12.18.1.2088
LWJGL: 2.9.4
OpenGL: GeForce GTX 860M/PCIe/SSE2 GL version 4.5.0 NVIDIA 372.70, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 8x Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
OptiFine Version: OptiFine_1.10.2_HD_U_C3
Render Distance Chunks: 8
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 4.5.0 NVIDIA 372.70
OpenGlRenderer: GeForce GTX 860M/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 8
```

**Comment by BlueSilverXIII** [comment]
got the same problem
as soon as I picked up the bin it crashed. tried logging in again and it gives me a crash but still keeps me logged in the server.
[crash-2016-09-26_20.24.55-client.txt](https://github.com/aidancbrady/Mekanism/files/494381/crash-2016-09-26_20.24.55-client.txt)

**Comment by rapus95** [comment]
@BlueSilverXIII just in case you don't already know it, ask the server admin to edit your nbt tag and let it remove from your inventory

**Comment by aidancbrady** [comment]
Fixed in dev
