### ISSUE TITLE
[1.10.2] Universal cables do not extract RF from non-Mekanism blocks

### ISSUE THREAD

**Issue by TheGuyRunningSouth** [aidancbrady/Mekanism#3821]
I imagine it's due to the non-capability supporting RF API, but I am experiencing the title issue with every non-Mekanism generator and storage block I have tried. Energy insertion works correctly, it is only extraction.

I know that this is most likely known, but I didn't see any mention of it so better safe than sorry.

**Comment by rdunham3** [comment]
Is this with the cable being configured as Normal or Pull?

**Comment by TheGuyRunningSouth** [comment]
If memory serves I've tried both. I know normal used to work for anything
that would export RF on its own, and still works for Mek generators. Was
there an undocumented change somewhere?

**Comment by LordHellscream** [comment]
I can confirm this, using any setting (push/pull/normal) wouldn't work at all, I even configure ender io energy bank to push out power and no avail.
As far as I know the cable only can transport power into non-Mekanism blocks, but not From them.

This is major limitation, i really like mekanism cable, they are HUGE (compare to ender io), but they have high capacity and less annoying to craft.

**Comment by TheGuyRunningSouth** [comment]
I managed to get a basic universal cable to pull from a SolarFlux Reborn
solar panel when set to pull. Have not tested with any other generators.
Like I stated originally, this may be due to the RF API and not a true
Mekanism problem.

**Comment by LordHellscream** [comment]
Haven't tried solarflux, but so far it doesn't appear to work in anyway to pull power from energy sources in Ender IO and Rftools

**Comment by Utildayael** [comment]
There's a bug with it pulling from EnderIO for sure. @aidancbrady said it's an issue with how they implemented [or didn't implement] Tesla API and the EnderIO dev refuses to fix it. [I logged a bug on this quite some time ago on here and then over on EnderIO after Aidan confirmed it wasn't a Mek issue per-say]

Basically, EnderIO auth doesn't want to implement Tesla... ever.

**Comment by TheGuyRunningSouth** [comment]
Will be interesting to see how they handle the new forge system. I had
figured it was an API issue.

**Comment by Utildayael** [comment]
Always wished everyone would settle on one power system and be done with it but it's like herding cats (and egos). 

Always have loved Mek because of universal cables and Aidan's attitude of "just make it work" ... Immersive Engineering does the same with their power cables too. It's a big pain running a bunch of tech mods that each have their own power system. Granted Mek has its own, but it's also fully compatible with RF/EU out of the box. :)

**Comment by PwrThruFait** [comment]
I have also been having the same issue pulling power from non Mekanism machines. I am getting power from Solar Flux solar panels and trying to transfer into my Mekanism power system. When I go and change the configuration to pull on the Ulitimate energy cable even with the cable not hooked to the system or anything it will drain the solar panel of all its 2 million RF.

**Comment by sandalle** [comment]
This may be unrelated, but it's the same symptom going the opposite direction. I'm drawing (Pull) power from a Mekanism Elite Energy Cube with Elite Universal Cables (green light, power is pulling) into a Refined Storage [Controller](https://refinedstorage.raoulvdberge.com/wiki/controller) (tried both Push and Normal on the connecting cable), but no power goes into the Controller.

* Minecraft 1.10.2
* Forge Mod Loader 1.10.2-12.18.2.2125
* Mekanism 1.10.2-9.2.0.294
* [Refined Storage](https://minecraft.curseforge.com/projects/refined-storage) 1.2.4

Using [Immersive Engineering's](https://minecraft.curseforge.com/projects/immersive-engineering) [MV Wire Coil](http://ftb.gamepedia.com/MV_Wire_Coil) from the Mekanism Elite Energy Cube (face configured for Output) allowed the Refined Storage Controller to be powered. I have not tried other cabling between the Mekanism Elite Energy Cube and the Refined Storage Controller.

Plus other mods (see [here](https://github.com/sandalle/ModderationConfigs/tree/frostburn) for full list, no Ender IO installed :) ).
