### ISSUE TITLE
[bug, 1.7.10] Robit disappear when flying too quickly

### ISSUE THREAD

**Issue by TheTonyk** [aidancbrady/Mekanism#3824]
Hello,

When i'm using the Jetpack from Mekanism with the Hang Glider from OpenBlocks, my Robit don't teleport to me and just disappear. I'm unable to find it. Maybe teleport the Robit to player when player is on the ground in the next version ?

And to fix that now, where can i find the location of the Robit ? I've already check the level.dat and my_uuid.dat with NBT Explorer

Thanks !

**Comment by rapus95** [comment]
Though i can't help with your problem, I'd like to suggest a feature to overcome the worstcase where robits are just lost: add some "call-home-functionality" that you can somehow trigger at the robits chargepad that will make it teleport back home no matter where it is right now.
I know it's hard to move anything that's in a possibly unloaded chunk, but it'd be really useful

**Comment by aidancbrady** [comment]
Can't do much to solve this here. Perhaps I'll add the call-home functionality as mentioned above, but it won't be for a while.
