### ISSUE TITLE
Server crash - Techreborn chainshaw and a Mek windmill.

### ISSUE THREAD

**Issue by ProsperCraft** [aidancbrady/Mekanism#3825]
Every time the player logs in the server goes down.

http://pastebin.com/Y9zneGc7

http://pastebin.com/F54QJ3ee

http://pastebin.com/wrQ2nADp

http://pastebin.com/MdjbuQAA

http://pastebin.com/bMC88J5Y

**Comment by modmuss50** [comment]
We use JTraits to apply the power interfaces to our items, and you charging thing doesnt seem to like it. I think I will remove JTraits if you cannot fix it.

Fix for now is to disable forge and RF power in the reborn core config, log back in, remove items, and then enable it again.

**Comment by ProsperCraft** [comment]
I can't find that option in the config.

**Comment by modmuss50** [comment]
Its in the config folder, I dont think its in the sub folder though.

**Comment by modmuss50** [comment]
This can be closed, its an issue with JTraits and FML, it could be fixed with a core mod on our end.
