### ISSUE TITLE
[1.10.2] Machine UI broke

### ISSUE THREAD

**Issue by janekos** [aidancbrady/Mekanism#3826]
Version: Mekanism-1.10.2-9.2.0.292
Minecraft version: 1.10.2
I was making a heat generator setup when I shift+right clicked on one of the heat generators and the lava source block got placed and then instantly disappeared. I thought nothing of it and just placed another lava block, but when I wanted to check my basic energy cube for power the UI looked like [this](http://s12.postimg.org/u64ryl6zh/asi.jpg). Closing and relaunching the game didn't help and I'm not very sure what to do about this other than post an issue here.

**Comment by aidancbrady** [comment]
I don't believe this is on my end, looks like somehow the rendering stack got screwed up.
