### ISSUE TITLE
[Feature Request] Make Quantum Entangloporter follow Security Desk rules

### ISSUE THREAD

**Issue by Hazmatik** [aidancbrady/Mekanism#3827]
When a player places down a QE no other players can access it even if trusted in the Security Desk. Would be nice for players who are teaming together to be able to both access the QE's.

**Comment by bbgott** [comment]
That is what I was trying to convey with ticket #3727, but it got closed a few weeks ago. The teleports also don't follow the security desk rules.

**Comment by aidancbrady** [comment]
Interfaces are restricted on Teleporters and Quantum Entangloporters for network efficiency reasons. I'll see about changing this in the future.
