### ISSUE TITLE
[1.7.10] Can't cancel Flame burn

### ISSUE THREAD

**Issue by Eufranio** [aidancbrady/Mekanism#3828]
I have a server and i have Mekanism and MyTown2 mods installed. I created a protection to check each tick for a EntityFlame:

```
    {
      "class": "mekanism.common.entity.EntityFlame",
      "type": "entity",
      "actions": "TRACKED",
      "flags": "PVP",
      "range": 20,
      "priority": "HIGH"
    }
```
The protection works fine, except because the target starts burning, even without the flame impact it. Maybe it is setting the target in burning, instead waiting for the flame strike the target.

**Comment by aidancbrady** [comment]
Consider disabling aesthetic world damage in the config, accomplishes the same thing.

**Comment by Eufranio** [comment]
It's false and I still able to burn stuff with a Flamethrower, even cancelling right-click and the flame.
