### ISSUE TITLE
[Question] About downloading a 1.7.10 version

### ISSUE THREAD

**Issue by MJRLegends** [aidancbrady/Mekanism#3830]
Where can i find a build download for this ddc9e68 , I've looked on the website and i cant seem to see it....

**Comment by Bysokar** [comment]
Probably on the premium only build server?

**Comment by MJRLegends** [comment]
@Bysokar well @aidancbrady did say he fixed a bug i was having here #3686 with the version so i was hoping for a build of it,

**Comment by Bysokar** [comment]
@aidancbrady Sidenote, does DefenseTech have builds on your build server.... I cant compile it because of issues with Sided inventory for some reason.

**Comment by MJRLegends** [comment]
@aidancbrady bump on issue, sorry i know your probably busy but i feel like this problem wasn't intended :D and is a very easy fix for you :)

**Comment by MJRLegends** [comment]
@aidancbrady Anyone alive?

**Comment by ThatGamerBlue** [comment]
@MJRLegends no

**Comment by ThatGamerBlue** [comment]
@MJRLegends http://www.mediafire.com/file/qxnlatnw9w9n7xt/MekanismAll-1.7.10-9.1.1.homebaked.jar
