### ISSUE TITLE
Gas Pipes won't accept gas

### ISSUE THREAD

**Issue by fwolle30** [aidancbrady/Mekanism#3831]
Hi,
Your pressurized tubes won't accept gas from the electrolytic seperator, or any other machines.

I've tested it with the newest forge with only your mods installed (Mekanism, Mekanism Generators and Mekanism Tools).

**Comment by yutang13** [comment]
Use the configurator on Fluid more and shift right click on the end portion and set it to extract (pull)

**Comment by fwolle30** [comment]
I feel like a coplete idiot right now ....
Works as expected -.-
