### ISSUE TITLE
[1.10.2] Slurry Split Between Crystallizers

### ISSUE THREAD

**Issue by DFliyerz** [aidancbrady/Mekanism#3833]
With the way that ore quintupling currently works, chemical crystallizers are extremely slow compared to all of the other machines ahead of it in the ore processing chain, necessitating multiple crystallizers per chain. However, what ends up happening is that a batch of clean slurry (2000mb if I remember correctly) will get split between two or more crystallizers, preventing them from processing anything and freezing up the whole chain until you manually remove the slurry using a dropper. Perhaps there could be a way to make crystallizers not do this?

**Comment by Utildayael** [comment]
You'd really need some sort of liquid router that can move specific amounts of liquid between the machines. I'm not aware off the top of my head of anything that can do that. You would need to figure out how much clean slurry is needed to make a single crystal and use that value as a round-robin distro between all connected crystallizers. 

I've often wanted to do the same thing for those last three machines in the chain but the logistics proved problematic. Could probably do it in 1.7.10 with AE2 and Extra Cells but I'd have to test. I'm not sure you can feed slurry into liquid storage or not... which would be another issue. Refined Storage [AE2-clone] in 1.10 has fluid storage now [I think?] but that mod is buggy as hell.

TBH I just usually 4x all the general stuff and run batches of 5x stuff if I really need specific things [usually iron if we don't have digi miner enabled].
