### ISSUE TITLE
Energy network bug

### ISSUE THREAD

**Issue by bbgott** [aidancbrady/Mekanism#3835]
Each time you add a segment to an energy network it adds the throughput to the overall throughput of the network. One segment of basic universal cable can transfer 3.2kJ/t.  Two segments can transfer 6.4kJ/t, and so one.  It seems that the network throughput should be based on what tier universal cable you have, not the length of cable.

MC version: 1.10.2
Forge version: 12.18.1.2073
Mekanism version: 9.2.0.292

**Comment by aidancbrady** [comment]
Not a bug.

**Comment by bbgott** [comment]
Wow, OK. Sure seems like a bug to me. If that's intended behavior, it means you never really have upgrade your cables, just throw on a few more segments to increase your throughout. It's your mod, you can do what you want with it, but that makes no sense to me.
