### ISSUE TITLE
World crashes while trying to craft an Armored Jetpack on a TConstruct crafting station

### ISSUE THREAD

**Issue by cryptrol** [aidancbrady/Mekanism#3836]
Ways to reproduce : 
- Add a Crafting station from TConstruct
- Add items needed to craft an Armored Jetpack
- The game crashes

Using latest Forge (2093), Mekanism 292 and TConstruct-1.10.2-2.5.1

The world crashes and it's not possible to (reliably) start it again until you remove the items from the crafting station (I did it with NBTexplorer).

I don't know if this is a TConstruct or Mekanism issue and the debug messages are far from informative (to me anyway).

**Comment by cryptrol** [comment]
I am adding a crash log : http://pastebin.com/7Ea6zm1E
Also the TConstruct issue I posted has been closed saying it's a Mekanism issue, just FYI.

**Comment by yutang13** [comment]
Well known issue. Also happens with portable tanks and solar panels.

Turning off tinker's fancy in game display may help. Might let you load the world
