### ISSUE TITLE
[1.10] Chemical Oxidizer output

### ISSUE THREAD

**Issue by toarii** [aidancbrady/Mekanism#3838]
Hi, I think there is a bug with the Chemical Oxidizer. The gaz (Sulfur Dioxide) don't go out throught the Pressurized Tube even if it's in PULL mode. When you place a Gaz Tank next to, it work, but not directly in the Tube :/

![2016-09-27_22 18 04](https://cloud.githubusercontent.com/assets/3897988/18890344/fc24fd50-8500-11e6-9e54-f842d78f02dc.png)
![2016-09-27_22 18 01](https://cloud.githubusercontent.com/assets/3897988/18890345/fc518b90-8500-11e6-87db-fff2b2748ae9.png)

**Comment by rapus95** [comment]
@toarii I'm not sure if it helps, but did you try rotating the block? IIRC you can only extract the gas from particular sides

**Comment by toarii** [comment]
yes, I have try too, to put the gaz tube around the machine. There is just this face that accept the tube.

**Comment by rapus95** [comment]
stupid question (out of curiosity), is there gas inside the machine? attach it to some power network (is it already connected?) and feed it with the corresponding items.
:D

**Comment by toarii** [comment]
Yes I have tried, but no result :/

**Comment by rapus95** [comment]
last two options that i can think of (helped me a lot of times) are a) attaching a machine right next to it and b) trying a server restart

**Comment by toarii** [comment]
Yeah, attach the machine next to the Oxidizer work, but I thing it's a bug for tube. Thank you :)

**Comment by aidancbrady** [comment]
Fixed in dev.
