### ISSUE TITLE
[Bug, 1.10.2] Electrolytic Separator

### ISSUE THREAD

**Issue by Silsec** [aidancbrady/Mekanism#3839]
The Electrolytic Separator power isn't reduced after adding energy upgrade (doesn't matter how many) in it.  I've tried taking them back out and in, and update to newest version of mekanism 9.2.0.292 with a new world.

**Comment by rapus95** [comment]
why you closed it? the thumbs up should show, that you're not the only one where that bug occurs

**Comment by yutang13** [comment]
Because it's not a bug.

https://github.com/aidancbrady/Mekanism/issues/3781

https://github.com/aidancbrady/Mekanism/issues/3760

https://github.com/aidancbrady/Mekanism/issues/3731

Definitely intended
