### ISSUE TITLE
[1.10.2, bug, breaking] machine denies to let any item enter through a tube (only at a given coordinate, restart solves temporarily)

### ISSUE THREAD

**Issue by rapus95** [aidancbrady/Mekanism#3840]
all other possibilities (other tubes, machines, configurations and rotations) didn't change it. Only moving the machine into an adjacent block and doing some rewiring worked. Moving the machine back to it's original place made it stop accepting items again.

Server restart solved the problem temporarily.

Guess: Chunkloading issues

**Comment by aidancbrady** [comment]
Should be fixed.
