### ISSUE TITLE
[bug/feature] connecting energy in- and output to a quantum entangloporters makes it suck up all energy (maxing out the transfer rate of the induction matrix)

### ISSUE THREAD

**Issue by rapus95** [aidancbrady/Mekanism#3841]
Even if there are no energy consumers anywhere in the network.
Simplest setup: Induction Matrix,output -> input - quantum entangloporter - output (same porter) -> Induction Matrix, input
Result: Induction Matrix transfer rate is used up (always 100% output and 100% input)

Suggestion: If there are no consumers, don't let the cube drain energy from the matrix

**Comment by Malkierian** [comment]
CONFIRMED, though  the output of the entangloporter has to be set to auto-eject.  If the pipe is set to pull, it maxes out at 32kJ/tick.  I have SO many problems with the power mechanics right now, though...

**Comment by aidancbrady** [comment]
Due to the efficient way Entangloporters handle input and output of resources, this kind of predictive functionality is not possible.  You can avoid this behavior avoiding setups that involve power loops.
