### ISSUE TITLE
[feature] Make quantum entangloporters use energy for doing their job (same way as teleporters need energy)

### ISSUE THREAD

**Issue by rapus95** [aidancbrady/Mekanism#3842]
I guess the easiest way would be to have an additional energy input slot with it's own color. Thus if you pipe energy into it, that energy will only be used to power the connection itself.
If you want to input energy for the network, do it from another side.

Alternatively:
Just consume some of the energy that flows around in the network (even if it is a constant amount of consumption that is independent of the amount of items, gas etc that passes the network)

Right now it simply is a free global connection and feels a little bit op.

But who am I to judge what's op :D

**Comment by aidancbrady** [comment]
I'm going to leave this the way it is- so many other mods offer the same technology without any kind of cost.

**Comment by rapus95** [comment]
if i wanted it like they do it, i'd go there :/

**Comment by PJB3005** [comment]
I think a config option would be a nice middle ground.
