### ISSUE TITLE
[suggestion] superposition industion matrix

### ISSUE THREAD

**Issue by Deathlymad** [aidancbrady/Mekanism#3843]
I just had a thought concerning induction matrix energy transmission. One problem is see is that it takes a long time to equal out 2 max energy storages so what i'd like to suggest is a kind of T2 entangloporter.
it would be a part of an induction matrix similar to the provider and the storage parts. However it would be possible to entangle two of them in different induction matrixes which would allow for a much simpler and potentially faster energy transfer (it also gives me fun ideas of new base energy systems).
also i could see that the entangeoporter transfer rate would be the same as the provider amount but gains a multiplier using the mekanism upgrade system. (but since they are cheap why not require 8 at a time where 80 yield a multiplier of x3).
similary that transfer could have a loss percentage that would be reduced similary to 0% by using energy upgrades ;D

**Comment by aidancbrady** [comment]
I'd rather just stick with the Entangloporter for wireless energy transmission.  Maybe in the future!
