### ISSUE TITLE
6Gb of Server Logs - java.lang.NoSuchMethodException

### ISSUE THREAD

**Issue by utoc** [aidancbrady/Mekanism#3845]
Good morning,

There is some kind of incompatibility between CyclopsCore (Integrated Dyanmics) and Mekanism which seems to be resulting in 6gig log files.  I'm not entirely sure which interaction on the server is causing this as we have several players that use both ID for automation with Mek.

Partial can be seen here: http://pastebin.com/waewNSS6

Running Mek 292, CyclopsCore 0.7.7 with FML 292.  If you'd like the full log, let me know.. I'll try to tar/gzip it.

Thanks

**Comment by tterrag1098** [comment]
https://github.com/aidancbrady/Mekanism/blob/1.10/src/main/java/mekanism/common/capabilities/CapabilityWrapperManager.java#L26 Problem code

This entire system seems pointless and circumvents the way capabilities are meant to be used. I suggest you read http://mcforge.readthedocs.io/en/latest/datastorage/capabilities/

Even if you do not redesign the system, doing `try { ... } catch (Exception e) { e.printStackTrace(); }` is *always* bad code. 100% of the time. An exception is a FATAL error. You need to take steps to either assure the exception is not raised again, or  just crash outright.

**Comment by aidancbrady** [comment]
Should be fixed in development branch.
