### ISSUE TITLE
[feature] allow anchor upgrades in quantum entangloporters

### ISSUE THREAD

**Issue by rapus95** [aidancbrady/Mekanism#3846]
the best example would be a quantum entangloporter & a pump in the nether that shall bring lava into the overworld. Problem: the nether station usually is unloaded except i place a teleporter or a DM next to it.
Sure, a teleporter might even make sense but you don't want to be forced to use one :)

**Comment by SuperFanatic** [comment]
You could always make a basic machine, put an anchor upgrade in it, and place it next to the entangloporter. it doesn't need to be running to be anchoring.

**Comment by thiakil** [comment]
BTW: I'm fairly certain you don't need the full teleporter structure. Obviously it would only be inbound from the portable tele, but it is a solution.

**Comment by JustinHuPrime** [comment]
This has been fixed for a while - shouldn't it be taken off the feature requests project?
