### ISSUE TITLE
Crash while crafting items in mekanism on Tic crafting station

### ISSUE THREAD

**Issue by iluvdemomanandjunkrat** [aidancbrady/Mekanism#3851]
[crash-2016-09-30_09.00.55-client.txt](https://github.com/aidancbrady/Mekanism/files/502031/crash-2016-09-30_09.00.55-client.txt)
I got this crash report. I tried to turn off the rendering in Tic config already but still crashing. I trying to craft Rotary Condensentrator.

**Comment by VT-14** [comment]
Remove Optifine.
