### ISSUE TITLE
Update checker does not check that the update is for the correct MC version

### ISSUE THREAD

**Issue by DaMachinator** [aidancbrady/Mekanism#3852]
On 1.7.10, getting notices about the 9.2.x updates even though to the best of my knowledge no such version exists for 1.7.10.

**Comment by SureWhyNotMinecraft** [comment]
I'm having the same problem, I don't think there is a way to disable the update notice ether.

**Comment by SureWhyNotMinecraft** [comment]
Ok I lied in the Mekanism Config

B:UpdateNotifications=true

Just set that to false, it's still a problem yes, but hey.

**Comment by aidancbrady** [comment]
Fixed in latest 1.7.10 version.
