### ISSUE TITLE
[1.7.10] Robit doesn't fire a PlayerInteractEvent in the server

### ISSUE THREAD

**Issue by Eufranio** [aidancbrady/Mekanism#3854]
I'm making a protection file for the Robit on my modded server, because everyone can open a Robit. Please make the Robit sync with the server, and fire a PlayerInteractEvent when a player interact with it :/

**Comment by aidancbrady** [comment]
In 1.11 at least, EntityInteractSpecific is always fired when interacting with any entity by default. Shouldn't be an issue.

**Comment by Eufranio** [comment]
The problem was in 1.7.10, rip
