### ISSUE TITLE
[1.10.2][9.2.0.292] Logistical Sorter not filtering by Mod ID

### ISSUE THREAD

**Issue by Aedda** [aidancbrady/Mekanism#3856]
I tried setting up a Logistical Sorter to filter out Cyberware items from a mob grinder. However try as I might, even using wildcards I could not get it to match the mod ID. I verified the id both through Mod Options and the mcmod.info file in the jar.

I was able to sort these items by Mod ID using EnderIO without any trouble.

So I went on to test other mods; Wired, EnderIO, BloodMagic, Better With Mods, Biomes O Plenty, Chisels & Bits, and Botania.

Of those only Botania sorted, the others were sent to the default route (I also tried a restricted pipe and they continued to choose that path remaining uncolored). I verified each through the Mod Options to ensure the spelling and case of each ID.

Versions:
Minecraft 1.10.2
Forge 2093
Cyberware beta-0.2.2
EnderIO 3.0.1.112_beta
BloodMagic 2.1.0-63
Better With Mods 0.11-1.10.2-hotfix2
Biomes O Plenty 5.0.0.2085
Chisels & Bits 12.1
Mekanism 9.2.0.292

**Comment by MadEgg** [comment]
I experienced the same in 1.7.10. Setting a Mod ID of Mekanism didn't sort all the Mekanism items (such as logistical transporters, mechanical pipes, fluid tanks) there but will send them the default route.

**Comment by thommy101** [comment]
Can confirm in latest 1.11.2 version.
Filtering on oredict works, filtering on mekanism or mekanis* doesn't work.

**Comment by thommy101** [comment]
Found a couple reasons which could cause it do malfunction:
ItemRegistryUtils#53 capitalizes the modname. Not every mod has a capital at the beginning.
Finder#127 filters on instanceof ItemBlock. There are also Items that could be filtered which are currently ignored.
