### ISSUE TITLE
1.10.2 Server Crash after activating  the miner 

### ISSUE THREAD

**Issue by tymop** [aidancbrady/Mekanism#3861]
On a multiplayer server:
Juste after  having activating the [miner ](http://wiki.aidancbrady.com/wiki/Digital_Miner), the server chash and then crash when i want to restart it.

[Crash log](http://pastebin.com/6yRQdhng)

**Comment by Toudi2** [comment]
its a problem with Sponge: https://github.com/SpongePowered/SpongeForge/issues/931  its fixed now

**Comment by tymop** [comment]
It is now working with the last sponge
spongeforge-1.10.2-2092-5.0.0-BETA-1775.jar
<http://files.minecraftforge.net/maven/org/spongepowered/spongeforge/1.10.2-2092-5.0.0-BETA-1775/spongeforge-1.10.2-2092-5.0.0-BETA-1775.jar>

Thank you.

2016-10-03 11:07 GMT+02:00 Toudi2 <notifications@github.com>:
