### ISSUE TITLE
Mekanism infusion factories accept no automated imports

### ISSUE THREAD

**Issue by Tawnyman** [aidancbrady/Mekanism#3862]
I just attempted to automate my elite infusion factory the input sides were correctly set I attempted to use vanilla hoppers, Applied Energistics export buses and interfaces none managed to push any items at all into it. The redstone you see in there was manually placed

![2016-10-03_14 02 52](https://cloud.githubusercontent.com/assets/19567087/19027302/659b5020-8972-11e6-8fbf-17e41ed5f338.png)

![2016-10-03_14 02 59](https://cloud.githubusercontent.com/assets/19567087/19027301/659a5170-8972-11e6-998c-4a35c9782176.png)

![2016-10-03_14 03 02](https://cloud.githubusercontent.com/assets/19567087/19027303/659e7f8e-8972-11e6-8cff-bd61a676d395.png)

![2016-10-03_14 04 22](https://cloud.githubusercontent.com/assets/19567087/19027304/65a01358-8972-11e6-899d-64d3415cdb35.png)

sorry if this has been brought up before I am new to github and did not see this posted anywhere on your problem page

**Comment by MadEgg** [comment]
+1 - also experiencing this. Too bad, I could really use infusing factories but now I'm stuck to a set of infusers in parallel because the factories can't be automated.

**Comment by redelman** [comment]
It sucks, but I work around this by exporting from ME interfaces or export buses or whatever into a chest, and then use logistical pipes from there into the machine. Looks ugly but at least it works.

**Comment by aidancbrady** [comment]
Should be fixed in latest version
