### ISSUE TITLE
Server TPS dropping to .286 due to Mekanism

### ISSUE THREAD

**Issue by ProsperCraft** [aidancbrady/Mekanism#3863]
Warmroast profile provided here-
https://gyazo.com/32b95d89fc37289c7c54940ecf558c2a

[09:27:28] [Server thread/INFO]: Dim 0 : Mean tick time: 3494.541 ms. Mean TPS: 0.286
[09:27:28] [Server thread/INFO]: Overall : Mean tick time: 3517.201 ms. Mean TPS: 0.284

This freezes the server so badly the console does not respond for 5-10 minutes, then it recovers for a second then back to not responding.  This maintains until the server is rebooted.

This seems to be a problem with the latest update to the Allthemods modpack 1.32

Unfortunately it may appear we are running a non official version so I will cross post to the pack github as well.
MekanismAll-1102-921homebaked.jar

We have hardware selected for single core speed, so its not hardware-
CPU INTEL|CORE I7 4790K 4.0G 8M R
SSD 500G | SAMSUNG MZ-N5E500BW RTL
32 gigs of ram

**Comment by devryb** [comment]
Same issue here:

https://timings.aikar.co/v2/?id=ad6388e099fa4b2e8cc48ceafb9fc657&section=all

Version: Mekanism-1.10.2-9.2.0.292

**Comment by thiakil** [comment]
Methods listed in the screenshot were changed recently in 1.11 branch, if it persists please supply the `.nps` files so we may properly analyse.

**Comment by devryb** [comment]
Hi 😁
