### ISSUE TITLE
[Flamethrower] Fire causes server/client crash

### ISSUE THREAD

**Issue by Lukas45** [aidancbrady/Mekanism#3864]
~~The Inferno mode causes the server and client to crash, and the Flamethrower has to be removed/switched stance on directly from the database, as the server is not able to start up again while it's there.~~
After further reading, and fixing attempts on the server, it is the fire from the Flamethrower that's causing issues, however I had not used the fire for the at least past 10 seconds. The server just happened to crash the moment I switched to Inferno mode.
The server needed a rollback (which luckily happened to have a backup 20mins prior) before it was playable again
Minecraft 1.10.2
Forge 12.18.1.2092
Mekanism 9.2.0.292
Client crash log:
http://pastebin.com/C8PYmmnn

**Comment by aidancbrady** [comment]
Seems to be fixed in 1.11.
