### ISSUE TITLE
[1.7.10] Crash when used with Progressive Automation Chopper

### ISSUE THREAD

**Issue by Master-Jynx** [aidancbrady/Mekanism#3866]
Mekanism 281
Progressive Automation 1.6.34
Forge 1614
plus 181 other mods on an SMP Server

When PA's Chopper is fed from a side that it can actively plant from, the game will crash when
you first enter that region, or if you are in that area when you logon.

If you place chopper with a Basic Cable connected to the front side and leave the game,
no crash will occur if you rejoin quickly.
A crash will occur if you restart the client and rejoin.
The Server and the client will both crash.
The clients error message is about bad packets when trying to connect, I don't believe it relates.
The server error message we get is at
http://pastebin.com/fjFvM9h4
and , No, its not Thaumcraft related, the crash is on an island with 1 oak tree more then 40 blocks away
and 4 slime trees more then 30 away.

**Comment by smbarbour** [comment]
Based on the crash log and code of PA, it appears to be having an issue getting the unlocalized name of a universal cable.

**Comment by aidancbrady** [comment]
Doesn't appear to be a Mekanism-related issue
