### ISSUE TITLE
Mekanism-1.10.2-9.2.0.292 - CTD - Basic Cable set to pull against Turbine

### ISSUE THREAD

**Issue by SpikeyTheDJ** [aidancbrady/Mekanism#3867]
I encountered a crash while in survival mode, I recreated it in creative mode. 

If you have formed turbine multi-block. Placing a universal cable next to the cable valve works fine, BUT If you change the universal cable to PULL it crashes to desktop and crashes again if you re-open the world. 

If there is anymore information needed please let me know. 

Thanks for all your hard work. I love Mekanism. 

[crash-2016-10-04_05.49.36-server.txt](https://github.com/aidancbrady/Mekanism/files/508239/crash-2016-10-04_05.49.36-server.txt)
[crash-2016-10-04_05.52.37-client.txt](https://github.com/aidancbrady/Mekanism/files/508240/crash-2016-10-04_05.52.37-client.txt)

**Comment by aidancbrady** [comment]
Fixed in 1.11 :)
