### ISSUE TITLE
Speed Upgrade is a downgrade to gas efficiency

### ISSUE THREAD

**Issue by codewarrior0** [aidancbrady/Mekanism#3868]
A machine with eight speed and eight gas upgrades consumes the same amount of gas per operation as a machine with zero speed and zero gas upgrades. A machine with eight speed and zero gas upgrades will consume _ten times_ the gas per operation as a machine with no upgrades. Likewise, a machine with eight speed and eight gas upgrades will consume _ten times_ the gas per operation as a machine with zero speed and eight gas upgrades.

From [the Mekanism wiki](http://wiki.aidancbrady.com/wiki/Speed_Upgrade):

> HINT: (For machines that use gasses) Machines consume gasses based on how long they are running. that means using speed upgrades will increase the gas efficiency.
## 

Furthermore, a gas-using factory will consume gas _twice_ on the final tick of processing, due to the gas tank being depleted once in the `for process in tier.processes` loop, and again when `recipe.operate()` is called during the final tick. This adds up to a 5% increase in gas costs when eight speed upgrades are installed.

**Comment by VT-14** [comment]
I'm pretty certain that hint from the Mekanism wiki predates the addition of Gas Upgrades, so its likely just out of date and needs to be removed.

No comment on the 'consume twice' note.

**Comment by rdunham3** [comment]
The wiki is out of date on many things.  Speed upgrades cause energy and material usage to spike.

Efficiency and speed upgrades counter each other, so if you have equal numbers you get the increased speed at the original gas use.  Same goes with energy upgrades.  Ideally you'll want to do the material and energy efficiency upgrades at the same time or even before the speed upgrades.  Throw a chunk load upgrade (new, and not mentioned in wiki yet) in one machine in the chunk and who cares if it works at max speed or not? While you're out it can slowly process through everything.
