### ISSUE TITLE
[1.10.2] Doesn't use doFill variable for fluid tank draining

### ISSUE THREAD

**Issue by Da-Technomancer** [aidancbrady/Mekanism#3870]
I'm the dev of Crossroads, and someone reported a crash with the Crossroads fluid pipes and the Mekanism fluid tank. After looking into it, it seems to be because in the fluid tank code you ignore the doDrain argument in the drain method in the fluid handler, as well as the doFill in the fill methods. These arguments are part of the forge specifications, and the fact that you ignore them probably causes problems with several other mods as well. I'll just remind you what they do: if doDrain is true, have the tank act the way you currently do (drain the tank), but if it is false, do all the math and return the same thing you would return if it was true, but don't actually drain the tank. Similarly with the doFill argument. 

I'll link the report I recieved, which contains the info like steps to reproduce, mod list, etc: https://github.com/Da-Technomancer/Crossroads/issues/37

**Comment by ProsperCraft** [comment]
http://pastebin.com/LLyDRssd

I think our server crash may be related.

**Comment by Da-Technomancer** [comment]
looks like it, were you using the fluid tubes on a mekanism block?

**Comment by ProsperCraft** [comment]
Da-Technomancer's Crossroads Mod
