### ISSUE TITLE
Basic Universal Cable bug

### ISSUE THREAD

**Issue by TheDCPlaya** [aidancbrady/Mekanism#3871]
all universal cable will not pull from any machine that produces RF unless its a mekanism generator back http://i.imgur.com/Q7DB9WM.png mekanism version 9.2.0

**Comment by TheDCPlaya** [comment]
tried with immersive cabl;e and it worked seems to be a bug with the uniersal cable

**Comment by Nephatrine** [comment]
I'm seeing this as well. using 9.2.0.292

**Comment by superdave4054** [comment]
it also cannot be used to transfer RF power from non-mek storage.

**Comment by FnordMan** [comment]
Same issue here, it won't get power from or deliver power to any other RF machines. This includes both Ender IO and Environmental Tech. 

Ender IO power conduits can deliver power from other RF sources to energy cubes just fine though.

**Comment by zeldatp151** [comment]
Yea, Universal Cable, all tiers, will not pull power from the Ender IO Capacitor Bank I have. I haven't tried any other configurations. MC 1.10.2  Mekanism 9.2.0.292
