### ISSUE TITLE
[1.10.2] Rendering crash with Tinkers

### ISSUE THREAD

**Issue by YOYOK9** [aidancbrady/Mekanism#3873]
Issue description: Rendering error cause client to crash
What happens: If a player inserts the Personal Chest (Mekanism) into a Tinkers Crafting Table (Tinkers Construct) and leaves the crafting table interface, Shortly after the game the players client (And anyone within 250 blocks of that client) will also crash.

Steps to reproduce:
1. Open tinkers crafting table GUI
2. Insert Personal Chest
3. Exit GUI and wait

Version:
- Minecraft: 1.10.2
- Forge: 2092
- Mekanism: 9.2.0.292
- TConstruct: 2.5.3

Does this issue occur on a server? yes

Crash Report (Client): http://pastebin.com/NW7dtY4T

**Comment by VT-14** [comment]
Known issue.  Has been reported before.  Disable the tabletop render in Tinker's config until it is fixed, and remove Optifine (the vast majority of mods refuse to support it).
