### ISSUE TITLE
[1.10.2] No JEI Recipies

### ISSUE THREAD

**Issue by YOYOK9** [aidancbrady/Mekanism#3874]
Not sure if this is because of mekanism or JEI but all recopies for mekanism do not show up anymore.

Mc: 1.10.2
mekanism: 1.10.2-9.2.0.292
JEI: jei_1.10.2-3.12.5.303

**Comment by cjburkey01** [comment]
For me, they show up, but when you click on an item to show the recipe for it, it shows ALL the items' recipes in the mod.

**Comment by gabor6505** [comment]
I have the same issue, for me the base blocks show their recipe in JEI, but if I click on a base block's recipe, it shows the recipes for all blocks from Mekanism. If I want to see a machine's recipe, I have to look it up on the wiki, because JEI doesn't show it.

**Comment by cjburkey01** [comment]
I tried updating JEI to the latest version, and then I found that no recipes could be seen.

**Comment by Ashano** [comment]
I'm having the same issue. Most recipes are there but some are not displayed like the blocks for the dynamic tank. The ones that are displayed, when clicked, show all mekanism recipes. It's especially annoying because of the lack of up to date info on v9 on the wiki.

**Comment by PJB3005** [comment]
Update to the latest version of Mekanism please.

I know the "all recipes shown" bug got fixed.
