### ISSUE TITLE
Industrial Turbin display issue.

### ISSUE THREAD

**Issue by Hordorr** [aidancbrady/Mekanism#3875]
i can't see the production :'(
![image](https://cloud.githubusercontent.com/assets/22684571/19197389/e768aa22-8cb9-11e6-9e21-a4d7cb8acaff.png)

![image](https://cloud.githubusercontent.com/assets/22684571/19197403/f1f611be-8cb9-11e6-814d-1c5b3818e03a.png)

im using Mekanisme/generato/tools 1.7.10-9.1.0.280, and have the same issue with 9.1.0.281

**Comment by RealGrep** [comment]
Same issue in 1.10.2 and 9.2.0.292, actually. Turbine is producing, but the numbers in the GUI don't show it. I can see the steam in the steam graphical display, but the numbers say nothing. Same as your screenshot.

**Comment by aidancbrady** [comment]
Already reported. Definitely a strange issue
