### ISSUE TITLE
Bins inaccessible by Refined Storage external storage

### ISSUE THREAD

**Issue by LukeLonas** [aidancbrady/Mekanism#3877]
The images below are an attempt to show that the RS external storage can't read the items that are stored in a bin.  I have also tried to place the external storage on the bottom (I know that, currently, items are removed from bins using the bottom face).  Talking to the RS dev he said, "[Bins] are deep storage units but ONLY if MFR is installed.  That means RS interfaces with them as inventories.  And, that causes [the] buggy behavior."  He continued to say, "If I could interface with them as DSU's then the problem wouldn't be there."  I would love to see this cross-mod compatibility fixed as I love Mekanism and RS systems are fantastic.  Bins would be an obvious choice for externally storing items for your RS system.  If there is any more information I can get you I would be glad to oblige.  Thanks in advance for your time.
- Minecraft: 1.10.2 
- Forge: 2070 - 2097 (newest at the time of posting)
- Mekanism: 9.2.0.291 and 9.2.0.292 (newest at the time of posting)
- Refined Storage: 1.0 - 1.1.3 (newest at the time of posting)

![image](https://cloud.githubusercontent.com/assets/16693361/19217488/e839fe56-8d90-11e6-937a-7e4b347366ab.png)![image](https://cloud.githubusercontent.com/assets/16693361/19217492/fca35c98-8d90-11e6-9920-e826db5e891a.png)

**Comment by raoulvdberge** [comment]
This is the reason:

https://github.com/raoulvdberge/refinedstorage/issues/314#issuecomment-252490290

**Comment by Nephatrine** [comment]
Yeah would be fantastic to have DSU api enabled on these.
