### ISSUE TITLE
[1.7.10] Formulaic Assemblicator could use a stock control feature

### ISSUE THREAD

**Issue by MadEgg** [aidancbrady/Mekanism#3879]
When automating multi-ingredient recipes, it's very easy to clog the Formulaic Assemblicator. If I have two ingredients and one of them is scarce and the other abundant, the abundant one will soon fill all the stock slots in the FA, preventing the scarce ingredient to enter and making the production come to a halt. It would be awesome if there were maybe just 9 stock slots, each of the tied to one slot in the crafting grid, limiting stock to that specific item.

A different solution like #3811 would also help. Some other mods with transporters have some kind of 'stock' pipe or upgrade to control the stock kept in inventories or machines (the 'Module Stock' from 'Refined Relocation', for example), that could also work but makes the pipe system more complex, of course.

**Comment by MadEgg** [comment]
Another option: the MFR Planter has a setting 'Consume stack' that can be turned on or off. When this setting is off, it will always leave one unit of each slot there, so that its place cannot be taken by a different type of item.

**Comment by aidancbrady** [comment]
Added "stock control" mode, does exactly as you specified.

**Comment by MadEgg** [comment]
Sounds great, thanks! Which version is it in? Is it still available for MC 1.7.10?
