### ISSUE TITLE
[1.10.2] Rendering crash with bin and solar generator

### ISSUE THREAD

**Issue by 61352151511** [aidancbrady/Mekanism#3880]
So this appears to be a very specific crash. I had 212 Advanced Solar Generators in an Advanced Bin, I then used the Configurator in wrench mode in order to pick up the bin, and move it from the houses basement, to outdoors where I could more easily place the generators. As soon as the bin dropped in item form however, me, and the other player on the server, crashed. The only way to get back on was killing the item drop via command in console.

http://pastebin.com/SQvpzDU6

**Comment by Nephatrine** [comment]
Had this same issue when I tried to configurate/wrench a basic bin with 16 basic energy cubes in it. Caused anyone whose client attempted to render it to crash. Had to plop down a command block to kill the dropped item. Same error as in your pastebin.

**Comment by aidancbrady** [comment]
No longer should be an issue.
