### ISSUE TITLE
Logistical Transporters don't connect to many things

### ISSUE THREAD

**Issue by LucidCrux** [aidancbrady/Mekanism#3881]
Using the skyexchange pack on curseforge, I found that there are many objects to which the pipes simply won't connect. Other blocks like hoppers or transfer nodes push/pull from those objects just fine. Some examples are the projecte blocks, and Extra Utilities 2 blocks.

**Comment by AngelCry** [comment]
and i want to add Immersive Engineering as another example - at least Fermenter wont connect with transporters. at same time, EIO item conduit connect just fine to this machine.

**Comment by MadEgg** [comment]
The Harvester from Minefactory Reloaded will also not connect to logistical transporters.

**Comment by AngelCry** [comment]
well, i think we need to mention what version (mekanism and/or MC) we talk about. because i talk about version for MC 1.10 and i think LucidCrux too (because Extra Utilities 2) while MadEgg mean MC 1.7 i guess (because Minefactory Reloaded)

**Comment by MadEgg** [comment]
Ah, yes, sorry. I am talking about MC 1.7.10 indeed. For me, the MFR Harvester is the only issue I've experienced with transporters not connecting though. They do connect with the MFR Planter, for example.
