### ISSUE TITLE
Mekanism v9 Modtweaker 2 incompatibility 

### ISSUE THREAD

**Issue by nathan72419** [aidancbrady/Mekanism#3882]
Hi, I am trying to create a modpack. But I think mekanism just crashed with modtweaker 2.
Here's the crash report: 
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 10/11/16 7:25 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: mekanism/common/recipe/machines/SolarEvaporationRecipe
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.NoClassDefFoundError: mekanism/common/recipe/machines/SolarEvaporationRecipe
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
    at java.lang.Class.privateGetPublicMethods(Unknown Source)
    at java.lang.Class.getMethods(Unknown Source)
    at stanhebben.zenscript.type.ZenTypeNative.complete(ZenTypeNative.java:157)
    at minetweaker.runtime.GlobalRegistry.registerNativeClass(GlobalRegistry.java:95)
    at minetweaker.MineTweakerAPI.registerClass(MineTweakerAPI.java:340)
    at modtweaker2.mods.mekanism.Mekanism.<init>(Mekanism.java:48)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at modtweaker2.utils.TweakerPlugin.load(TweakerPlugin.java:18)
    at modtweaker2.utils.TweakerPlugin.register(TweakerPlugin.java:12)
    at modtweaker2.ModTweaker2.init(ModTweaker2.java:73)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
    ... 18 more
Caused by: java.lang.ClassNotFoundException: mekanism.common.recipe.machines.SolarEvaporationRecipe
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 60 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_101, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 2605166304 bytes (2484 MB) / 4065853440 bytes (3877 MB) up to 4065853440 bytes (3877 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx4096m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1566 171 mods loaded, 164 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHI    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHI    FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1566-1.7.10-universal.jar) 
    UCHI    Forge{10.13.4.1566} [Minecraft Forge](forge-1.7.10-10.13.4.1566-1.7.10-universal.jar) 
    UCHI    appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core](minecraft.jar) 
    UCHI    CodeChickenCore{1.0.7.46} [CodeChicken Core](minecraft.jar) 
    UCHI    ivtoolkit{IvToolkit} [1.2](minecraft.jar) 
    UCHI    NotEnoughItems{1.0.5.111} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
    UCHI    OpenComputers|Core{1.5.22.46} [OpenComputers (Core)](minecraft.jar) 
    UCHI    OpenEye{0.6} [OpenEye](OpenEye-0.6-1.7.10.jar) 
    UCHI    ThE-core{1.0.0.1} [Thaumic Energistics Core](minecraft.jar) 
    UCHI    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) 
    UCHI    OpenModsCore{0.9.1} [OpenModsCore](minecraft.jar) 
    UCHI    <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHI    FastCraft{1.23} [FastCraft](fastcraft-1.23.jar) 
    UCHI    AccidentallyCircumstantialEvents{1.12.10} [Accidentally Circumstantial Events](accidentallycircumstantialevents-1.12.10.jar) 
    UCHI    AgriCraft{1.7.10-1.5.0} [AgriCraft](AgriCraft-1.7.10-1.5.0.jar) 
    UCHI    aobdbb{1.0.6} [Another One Bites The Dust: Berry Bushes](AOBDBB-1.0.6.jar) 
    UCHI    AppleCore{1.3.2} [AppleCore](AppleCore-mc1.7.10-1.3.2.jar) 
    UCHI    appliedenergistics2{rv3-beta-6} [Applied Energistics 2](appliedenergistics2-rv3-beta-6.jar) 
    UCHI    CoFHCore{1.7.10R3.1.3} [CoFH Core](CoFHCore-[1.7.10]3.1.3-327.jar) 
    UCHI    MineFactoryReloaded{1.7.10R2.8.1} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHI    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHI    Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHI    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHI    Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHI    Automagy{0.28.2} [Automagy](Automagy-1.7.10-0.28.2.jar) 
    UCHI    Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x.jar) 
    UCHI    betterquesting{1.0.155} [Better Questing](BetterQuesting-1.0.155.jar) 
    UCHI    BiblioCraft{1.11.5} [BiblioCraft](BiblioCraft[v1.11.5][MC1.7.10].jar) 
    UCHI    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) 
    UCHI    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) 
    UCHI    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1826-universal.jar) 
    UCHI    BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition](BiblioWoods[BiomesOPlenty][v1.9].jar) 
    UCHI    HardcoreEnderExpansion{1.8.6} [Hardcore Ender Expansion](HardcoreEnderExpansion  MC-1.7.10  v1.8.6.jar) 
    UCHI    Forestry{4.2.15.63} [Forestry for Minecraft](forestry_1.7.10-4.2.15.63.jar) 
    UCHI    BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition](BiblioWoods[Forestry][v1.7].jar) 
    UCHI    BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition](BiblioWoods[Natura][v1.5].jar) 
    UCHI    AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.3-17.jar) 
    UCHI    Botania{r1.8-249} [Botania](Botania r1.8-249.jar) 
    UCHI    BrandonsCore{1.0.0.12} [Brandon's Core](BrandonsCore-1.0.0.12.jar) 
    UCHI    BuildCraft|Core{7.1.18} [BuildCraft](buildcraft-7.1.18.jar) 
    UCHI    BuildCraft|Transport{7.1.18} [BC Transport](buildcraft-7.1.18.jar) 
    UCHI    BuildCraft|Silicon{7.1.18} [BC Silicon](buildcraft-7.1.18.jar) 
    UCHI    BuildCraft|Energy{7.1.18} [BC Energy](buildcraft-7.1.18.jar) 
    UCHI    BuildCraft|Factory{7.1.18} [BC Factory](buildcraft-7.1.18.jar) 
    UCHI    BuildCraft|Builders{7.1.18} [BC Builders](buildcraft-7.1.18.jar) 
    UCHI    BuildCraft|Robotics{7.1.18} [BC Robotics](buildcraft-7.1.18.jar) 
    UCHI    ThermalFoundation{1.7.10R1.2.5} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.5-115.jar) 
    UCHI    ThermalExpansion{1.7.10R4.1.4} [Thermal Expansion](ThermalExpansion-[1.7.10]4.1.4-247.jar) 
    UCHI    BuildCraft|Compat{7.1.5} [BuildCraft Compat](buildcraft-compat-7.1.5.jar) 
    UCHI    Railcraft{9.12.2.0} [Railcraft](Railcraft_1.7.10-9.12.2.0.jar) 
    UCHI    ForgeMultipart{1.2.0.347} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
    UCHI    chisel{2.4.1.40} [Chisel 2](Chisel2-2.4.1.40.jar) 
    UCHI    CarpentersBlocks{3.3.8.1} [Carpenter's Blocks](Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar) 
    UCHI    ctmlib{1.0.1.5} [CTMLib](Chisel2-2.4.1.40.jar) 
    UCHI    ComputerCraft{1.75} [ComputerCraft](ComputerCraft1.75.jar) 
    UCHI    EnderStorage{1.4.7.36} [EnderStorage](EnderStorage-1.7.10-1.4.7.36-universal.jar) 
    UCHI    MrTJPCoreMod{1.1.0.33} [MrTJPCore](MrTJPCore-1.1.0.33-universal.jar) 
    UCHI    ProjRed|Core{4.7.0pre12.95} [ProjectRed Core](ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
    UCHI    ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission](ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
    UCHI    OpenComputers{1.5.22.46} [OpenComputers](OpenComputers-MC1.7.10-1.5.22.46-universal.jar) 
    UCHI    CompactMachines{1.7.10-1.21} [Compact Machines](compactmachines-1.7.10-1.21.jar) 
    UCHI    customitems{1.0.8b} [Custom Items](customitems-1.0.8_beta_1.7.10.jar) 
    UCHI    CustomMainMenu{1.9.2} [Custom Main Menu](CustomMainMenu-MC1.7.10-1.9.2.jar) 
    UCHI    customnpcs{1.7.10c} [CustomNpcs](CustomNPCs_1.7.10c.jar) 
    UCHI    DraconicEvolution{1.0.2h} [Draconic Evolution](Draconic-Evolution-1.7.10-1.0.2h.jar) 
    UCHI    Enchiridion{1.3} [Enchiridion](Enchiridion 2-1.7.10-2.0.2a.jar) 
    UCHI    Enchiridion2{2.0.2a} [Enchiridion 2](Enchiridion 2-1.7.10-2.0.2a.jar) 
    UCHI    Mekanism{9.1.0} [Mekanism](Mekanism-1.7.10-9.1.0.281.jar) 
    UCHI    EnderIO{1.7.10-2.2.8.381} [Ender IO](EnderIO-1.7.10-2.2.8.381.jar) 
    UCHI    extracells{2.3.14} [Extra Cells 2](ExtraCells-1.7.10-2.3.14b197.jar) 
    UCHI    ImmersiveEngineering{0.7.7} [Immersive Engineering](ImmersiveEngineering-0.7.7.jar) 
    UCHI    TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct](TConstruct-1.7.10-1.8.8.jar) 
    UCHI    ExtraUtilities{1.2.10} [Extra Utilities](extrautilities-1.2.10.jar) 
    UCHI    ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-164.jar) 
    UCHI    ForbiddenMagic{1.7.10-0.575} [Forbidden Magic](Forbidden Magic-1.7.10-0.575.jar) 
    UCHI    MineTweaker3{3.0.9B} [MineTweaker 3](MineTweaker3-1.7.10-3.0.9C.jar) 
    UCHI    FTBL{1.0.18.2} [FTBLib](FTBLib-1.7.10-1.0.18.3.jar) 
    UCHI    FTBT{1.0.2} [FTB Tweaks](FTBTweaks-1.0.2.jar) 
    UCHI    FTBU{1.0.18.2} [FTBUtilities](FTBUtilities-1.7.10-1.0.18.3.jar) 
    UCHI    iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) 
    UCHI    GraviGun{4.0.0-beta} [GraviGun](GravityGun-4.0.0-beta.jar) 
    UCHI    guideapi{1.7.10-1.0.1-20} [Guide-API](Guide-API-1.7.10-1.0.1-20.jar) 
    UCHI    Hats{4.0.1} [Hats](Hats-4.0.1.jar) 
    UCHI    HatStand{4.0.0} [HatStand](HatStand-4.0.0.jar) 
    UCHI    HardcoreQuesting{4.4.4} [Hardcore Questing Mode](HQM-The Journey-4.4.4.jar) 
    UCHI    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) 
    UCHI    IronChest{6.0.60.741} [Iron Chest](ironchest-1.7.10-6.0.60.741-universal.jar) 
    UCHI    JABBA{1.2.2} [JABBA](Jabba-1.2.2_1.7.10.jar) 
    UCHI    journeymap{@JMVERSION@} [JourneyMap](journeymap-1.7.10-5.1.0-unlimited.jar) 
    UCHI    LoreExp{1.0.5} [Lore Expansion](LoreExpansion-1.7.10-1.0.5.B29.jar) 
    UCHI    MekanismGenerators{9.1.0} [MekanismGenerators](MekanismGenerators-1.7.10-9.1.0.281.jar) 
    UCHI    MekanismTools{9.1.0} [MekanismTools](MekanismTools-1.7.10-9.1.0.281.jar) 
    UCHI    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHI    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHI    MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHI    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHI    ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration](ProjectRed-1.7.10-4.7.0pre12.95-World.jar) 
    UCHI    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHI    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHI    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHI    MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHI    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHE    modtweaker2{0.9.6} [Mod Tweaker 2](ModTweaker2-0.9.6.jar) 
    UCHI    Morph{0.9.2} [Morph](Morph-Beta-0.9.2.jar) 
    UCHI    NEIAddons{1.12.13.38} [NEI Addons](neiaddons-1.12.13.38-mc1.7.10.jar) 
    UCHI    NEIAddons|Developer{1.12.13.38} [NEI Addons: Developer Tools](neiaddons-1.12.13.38-mc1.7.10.jar) 
    UCHI    NEIAddons|AppEng{1.12.13.38} [NEI Addons: Applied Energistics 2](neiaddons-1.12.13.38-mc1.7.10.jar) 
    UCHI    NEIAddons|Botany{1.12.13.38} [NEI Addons: Botany](neiaddons-1.12.13.38-mc1.7.10.jar) 
    UCHI    NEIAddons|Forestry{1.12.13.38} [NEI Addons: Forestry](neiaddons-1.12.13.38-mc1.7.10.jar) 
    UCHI    NEIAddons|CraftingTables{1.12.13.38} [NEI Addons: Crafting Tables](neiaddons-1.12.13.38-mc1.7.10.jar) 
    UCHI    NEIAddons|ExNihilo{1.12.13.38} [NEI Addons: Ex Nihilo](neiaddons-1.12.13.38-mc1.7.10.jar) 
    UCHI    neiintegration{1.1.2} [NEI Integration](NEIIntegration-MC1.7.10-1.1.2.jar) 
    UCHI    NetherOres{1.7.10R2.3.1} [Nether Ores](NetherOres-[1.7.10]2.3.1-22.jar) 
    UCHI    bq_npc_integration{1.0.10} [NPC Integration](NPCIntegration-1.0.10.jar) 
    UCHI    NuclearCraft{1.9d} [NuclearCraft](NuclearCraft-1.9d--1.7.10.jar) 
    UCHI    OpenMods{0.9.1} [OpenMods](OpenModsLib-1.7.10-0.9.1.jar) 
    UCHI    OpenBlocks{1.5.1} [OpenBlocks](OpenBlocks-1.7.10-1.5.1.jar) 
    UCHI    OpenPeripheralCore{1.3} [OpenPeripheralCore](OpenPeripheral-1.7.10-AIO-7.jar) 
    UCHI    OpenPeripheral{0.5.1} [OpenPeripheralAddons](OpenPeripheral-1.7.10-AIO-7.jar) 
    UCHI    OpenPeripheralIntegration{0.5} [OpenPeripheralIntegration](OpenPeripheral-1.7.10-AIO-7.jar) 
    UCHI    harvestcraft{1.7.10j} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10Lb.jar) 
    UCHI    PortalGun{4.0.0-beta-5} [PortalGun](PortalGun-4.0.0-beta-5.jar) 
    UCHI    Progression{0.3.5} [Progression](Progression-1.7.10-0.3.5.jar) 
    UCHI    ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration](ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
    UCHI    ProjRed|Fabrication{4.7.0pre12.95} [ProjectRed Fabrication](ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar) 
    UCHI    ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination](ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
    UCHI    ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion](ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
    UCHI    ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation](ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
    UCHI    qCraft{1.7.10-1.2.2} [qCraft](qCraft-1.7.10-1.2.2.jar) 
    UCHI    RandomThings{2.2.4} [Random Things](RandomThings-2.2.4.jar) 
    UCHI    reccomplex{0.9.7.1} [Recurrent Complex](RecurrentComplex-0.9.7.1.jar) 
    UCHI    RedstoneArsenal{1.7.10R1.1.2} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.2-92.jar) 
    UCHI    bq_rf{1.0.13} [RF Expansion](RFExpansion-1.0.13.jar) 
    UCHI    Sanguimancy{1.7.10-1.1.9-35} [Sanguimancy](Sanguimancy-1.7.10-1.1.9-35.jar) 
    UCHI    SpiceOfLife{1.3.6} [The Spice of Life](SpiceOfLife-mc1.7.10-1.3.6.jar) 
    UCHI    bq_standard{1.0.99} [Standard Expansion](StandardExpansion-1.0.99.jar) 
    UCHI    StevesFactoryManager{A93} [Steve's Factory Manager](StevesFactoryManagerA93.jar) 
    UCHI    StevesAddons{0.10.16} [Steve's Addons](StevesAddons-1.7.10-0.10.16.jar) 
    UCHI    StevesCarts{2.0.0.b18} [Steve's Carts 2](StevesCarts2.0.0.b18.jar) 
    UCHI    StevesWorkshop{0.5.1} [Steve's Workshop](StevesWorkshop-0.5.1.jar) 
    UCHI    Sync{4.0.0} [Sync](Sync-4.0.0.jar) 
    UCHI    thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin](thaumcraftneiplugin-1.7.10-1.7a.jar) 
    UCHI    thaumicenergistics{1.0.0.5} [Thaumic Energistics](thaumicenergistics-1.0.0.5.jar) 
    UCHI    ThaumicHorizons{1.1.9} [Thaumic Horizons](thaumichorizons-1.7.10-1.1.9.jar) 
    UCHI    ThermalDynamics{1.7.10R1.2.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.2.0-171.jar) 
    UCHI    TiCTooltips{1.2.5} [TiC Tooltips](TiCTooltips-mc1.7.10-1.2.5.jar) 
    UCHI    TMechworks{0.2.14.100} [Tinkers' Mechworks](TMechworks-1.7.10-0.2.14.100.jar) 
    UCHI    TML{4.0.1} [TooMuchLoot](TooMuchLoot-1.7.10-4.0.1.B0.jar) 
    UCHI    WailaHarvestability{1.1.2} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.2.jar) 
    UCHI    wawla{1.3.3} [What Are We Looking At](Wawla-1.3.3-1.7.10.jar) 
    UCHI    WR-CBE|Core{1.4.1.9} [WR-CBE Core](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHI    WR-CBE|Addons{1.4.1.9} [WR-CBE Addons](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHI    WR-CBE|Logic{1.4.1.9} [WR-CBE Logic](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHI    XaeroMinimap{1.10.9} [Xaero's Minimap](Xaeros_Minimap_1.10.9_Forge_1.7.10.jar) 
    UCHI    Ztones{1.7.10} [Ztones](Ztones-1.7.10-2.2.1.jar) 
    UCHI    ForgeMicroblock{1.2.0.347} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
    UCHI    McMultipart{1.2.0.347} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
    UCHI    ForgeRelocation{0.0.1.4} [ForgeRelocation](ForgeRelocation-0.0.1.4-universal.jar) 
    UCHI    MCFrames{1.0} [MCFrames](ForgeRelocation-0.0.1.4-universal.jar) 
    UCHI    RelocationFMP{0.0.1.2} [RelocationFMP](ForgeRelocationFMP-0.0.1.2-universal.jar) 
    UCHI    aobd{2.9.2} [Another One Bites The Dust](AOBD-2.9.2.jar) 
    UCHI    denseores{1.0} [Dense Ores](denseores-1.4.2.jar) 
    UCHI    HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul](HungerOverhaul-1.7.10-1.0.0.jar) 
    UD  MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.14.4414' Renderer: 'Intel(R) HD Graphics 4600'
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: all safe
    AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
    CoFHCore: -[1.7.10]3.1.3-327
    MineFactoryReloaded: -[1.7.10]2.8.1-174
    Mantle Environment: Environment healthy.
    ThermalFoundation: -[1.7.10]1.2.5-115
    ThermalExpansion: -[1.7.10]4.1.4-247
    TConstruct Environment: Environment healthy.
    NetherOres: -[1.7.10]2.3.1-22
    RedstoneArsenal: -[1.7.10]1.1.2-92
    ThermalDynamics: -[1.7.10]1.2.0-171
    Stencil buffer state: Function set: GL30, pool: forge, bits: 8

**Comment by LosVaqueros** [comment]
I am having the same trouble.
I receive an error with Waila and Mekanism-1.7.10-9.1.0.281 when trying to start my server.
It seems to be an issue on Mekanism's side, with the Solar Evaporation Controller. (class)
Note: I also receive a similar error with "Mod Tweaker 2" as OP @nathan72419 

**Waila Error Report Below:**

22.10 04:49:38 [Server] Server thread/INFO [WAILA Plugins]: Sorting plugins. After:  [Mekanism, IFluidHandler, TE Augments, Railcraft, MFR, DSU, Forestry, Extra Utilities, Pam's Fruit]
22.10 04:49:38 [Server] Server thread/FATAL [WAILA Plugins]: Plugin Mekanism threw an error on init. Skipping...
22.10 04:49:38 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoClassDefFoundError: mekanism/common/tile/TileEntitySolarEvaporationController
22.10 04:49:38 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at tterrag.wailaplugins.plugins.PluginMekanism.load(PluginMekanism.java:36)

**Mod Tweaker Error Report Below:**

22.10 04:56:18 [Server] Server thread/INFO [modtweaker2]: Starting Initialization for modtweaker2
22.10 04:56:20 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoClassDefFoundError: mekanism/common/recipe/machines/SolarEvaporationRecipe

**Comment by aidancbrady** [comment]
Report this to ModTweaker.
