### ISSUE TITLE
Modtweaker remove recipe

### ISSUE THREAD

**Issue by Maxwelljones** [aidancbrady/Mekanism#3883]
# https://github.com/stanhebben/MineTweaker3/issues/384#event-819480245

Was this not sorted already after implementing IMC?
Is there a way around for me @aidancbrady please?

Is there a way for me to load mekanism recipes before minetweaker or simply disable all mekanism recipes so I can implement the tweak ones that rebalance my modpack?

**Comment by theshadowake** [comment]
Can confirm Mekanism shaped recipes are not being removed by Modtweaker. Works fine for all 200+ other mods in my pack (using the latest 1.7.10 version of Modtweaker & Mekanism).
