### ISSUE TITLE
server crash when connecting mekanism pipe to big reactor

### ISSUE THREAD

**Issue by Bebabo10** [aidancbrady/Mekanism#3885]
http://pastebin.com/dz9xBy2y
http://pastebin.com/iXRBYD9N
http://pastebin.com/t2S7Dhtg
let me know if u need more 
#https://github.com/ZeroNoRyouki/BigReactors/issues/28

**Comment by RogueLogic** [comment]
please close this issue as it has already been fixed by ZeroNoRyouki.
