### ISSUE TITLE
Rendering crash Universal cables 1.10.2 

### ISSUE THREAD

**Issue by gp009** [aidancbrady/Mekanism#3887]
Mekanism build 1.10.2-9.2.1.56 

Crashes when trying to beak universal cable by hand or tool.

Update 1:   also crashes when breaking logistic and mechanical pipes as well

Crash log:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  DepLoader (BrandonsCore-1.10.2-2.1.0.47-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.3.1.88-universal.jar)
  LoadingHook (Mekanism-1.10.2-9.2.1.56.jar)
  MalisisCorePlugin (malisiscore-1.9.4-4.0.1.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 10/13/16 4:04 AM
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
    at mekanism.common.multipart.ConnectionProperty.valueToString(ConnectionProperty.java:48)
    at mekanism.client.render.obj.TransmitterModel.func_188616_a(TransmitterModel.java:135)
    at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.func_188645_a(SourceFile:119)
    at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.<init>(SourceFile:102)
    at mcmultipart.client.multipart.MultipartContainerSpecialRenderer.renderBreaking(MultipartContainerSpecialRenderer.java:157)
    at mcmultipart.client.multipart.MultipartContainerSpecialRenderer.renderMultipartContainerAt(MultipartContainerSpecialRenderer.java:53)
    at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.renderTileEntityAt(MultipartContainerSpecialRenderer.java:200)
    at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.func_180535_a(MultipartContainerSpecialRenderer.java:195)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:742)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1381)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at mekanism.common.multipart.ConnectionProperty.valueToString(ConnectionProperty.java:48)
    at mekanism.client.render.obj.TransmitterModel.func_188616_a(TransmitterModel.java:135)
    at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.func_188645_a(SourceFile:119)
    at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.<init>(SourceFile:102)
    at mcmultipart.client.multipart.MultipartContainerSpecialRenderer.renderBreaking(MultipartContainerSpecialRenderer.java:157)
    at mcmultipart.client.multipart.MultipartContainerSpecialRenderer.renderMultipartContainerAt(MultipartContainerSpecialRenderer.java:53)
    at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.renderTileEntityAt(MultipartContainerSpecialRenderer.java:200)
    at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.func_180535_a(MultipartContainerSpecialRenderer.java:195)

-- Block Entity Details --
Details:
    Name: mcmultipart:multipart.ticking // mcmultipart.block.TileMultipartContainer.Ticking
    Block type: ID #501 (tile.null // mcmultipart.block.BlockMultipartContainer)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-1426,70,-652), Chunk: (at 14,4,4 in -90,-41; contains blocks -1440,0,-656 to -1425,255,-641), Region: (-3,-2; contains chunks -96,-64 to -65,-33, blocks -1536,0,-1024 to -1025,255,-513)
    Actual block type: ID #501 (tile.null // mcmultipart.block.BlockMultipartContainer)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:742)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1381)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['gp009'/152, l='MpServer', x=-1426.70, y=69.00, z=-650.00]]
    Chunk stats: MultiplayerChunkCache: 349, 349
    Level seed: 0
    Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-232,64,256), Chunk: (at 8,4,0 in -15,16; contains blocks -240,0,256 to -225,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 352981 game time, 354342 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 67 total; [EntityBat['Bat'/257, l='MpServer', x=-1362.61, y=14.70, z=-698.21], EntitySpider['Spider'/258, l='MpServer', x=-1350.50, y=78.00, z=-700.50], EntityCreeper['Creeper'/259, l='MpServer', x=-1380.50, y=31.00, z=-658.50], EntitySheep['Sheep'/263, l='MpServer', x=-1384.01, y=68.00, z=-728.81], EntitySpider['Spider'/266, l='MpServer', x=-1416.11, y=65.00, z=-673.30], EntitySpider['Spider'/267, l='MpServer', x=-1418.96, y=66.00, z=-676.00], EntitySpider['Spider'/268, l='MpServer', x=-1415.01, y=66.00, z=-681.04], EntitySheep['Sheep'/269, l='MpServer', x=-1382.42, y=63.00, z=-717.74], EntitySquid['Squid'/270, l='MpServer', x=-1381.22, y=57.00, z=-709.68], EntityBat['Bat'/271, l='MpServer', x=-1401.26, y=51.10, z=-691.64], EntityBat['Bat'/272, l='MpServer', x=-1400.23, y=50.45, z=-693.41], EntityBat['Bat'/273, l='MpServer', x=-1399.48, y=50.41, z=-695.56], EntityBat['Bat'/278, l='MpServer', x=-1373.50, y=22.90, z=-703.86], EntitySheep['Sheep'/280, l='MpServer', x=-1362.50, y=67.00, z=-711.90], EntityItem['item.tile.dirt.silty_dirt'/153, l='MpServer', x=-1420.70, y=70.00, z=-653.04], EntityCreeper['Creeper'/281, l='MpServer', x=-1412.50, y=33.00, z=-664.50], EntityItem['item.tile.dirt.silty_dirt'/154, l='MpServer', x=-1421.88, y=70.00, z=-653.85], EntityBat['Bat'/308, l='MpServer', x=-1359.47, y=26.05, z=-576.41], EntitySheep['Sheep'/319, l='MpServer', x=-1377.80, y=69.00, z=-582.73], EntityCreeper['Creeper'/320, l='MpServer', x=-1376.50, y=69.00, z=-581.50], EntitySkeleton['Skeleton'/199, l='MpServer', x=-1447.50, y=36.00, z=-617.50], EntitySkeleton['Skeleton'/200, l='MpServer', x=-1446.50, y=102.00, z=-610.50], EntitySkeleton['Skeleton'/202, l='MpServer', x=-1475.50, y=64.00, z=-572.50], EntitySpider['Spider'/330, l='MpServer', x=-1358.30, y=66.00, z=-599.86], EntityCreeper['Creeper'/203, l='MpServer', x=-1443.44, y=82.00, z=-671.79], EntityZombie['entity.Zombie.name'/204, l='MpServer', x=-1455.50, y=105.00, z=-661.50], EntitySheep['Sheep'/333, l='MpServer', x=-1401.51, y=73.00, z=-592.71], EntitySheep['Sheep'/334, l='MpServer', x=-1414.22, y=73.00, z=-602.50], EntityPig['Pig'/335, l='MpServer', x=-1406.45, y=72.00, z=-605.86], EntitySheep['Sheep'/336, l='MpServer', x=-1392.30, y=70.00, z=-601.50], EntitySheep['Sheep'/337, l='MpServer', x=-1419.43, y=78.00, z=-591.76], EntityCreeper['Creeper'/338, l='MpServer', x=-1391.50, y=27.00, z=-620.50], EntityPlayerSP['gp009'/152, l='MpServer', x=-1426.70, y=69.00, z=-650.00], EntitySheep['Sheep'/349, l='MpServer', x=-1391.74, y=71.00, z=-603.45], EntitySkeleton['Skeleton'/350, l='MpServer', x=-1379.25, y=66.00, z=-597.58], EntityCreeper['Creeper'/224, l='MpServer', x=-1388.22, y=23.00, z=-652.49], EntityCreeper['Creeper'/225, l='MpServer', x=-1381.50, y=32.00, z=-646.50], EntityCreeper['Creeper'/226, l='MpServer', x=-1380.50, y=32.00, z=-647.50], EntityMinecartChest['Minecart with Chest'/227, l='MpServer', x=-1399.50, y=21.06, z=-637.50], EntityCreeper['Creeper'/355, l='MpServer', x=-1347.50, y=32.00, z=-626.42], EntitySkeleton['Skeleton'/228, l='MpServer', x=-1397.50, y=21.00, z=-630.50], EntitySkeleton['Skeleton'/229, l='MpServer', x=-1403.50, y=31.00, z=-636.50], EntityCreeper['Creeper'/357, l='MpServer', x=-1364.57, y=77.00, z=-637.17], EntityCreeper['Creeper'/230, l='MpServer', x=-1407.50, y=31.00, z=-635.50], EntityZombie['Zombie'/358, l='MpServer', x=-1354.50, y=77.00, z=-628.50], EntityBabySkeleton['Baby Skeleton'/231, l='MpServer', x=-1397.21, y=68.00, z=-632.46], EntityPig['Pig'/359, l='MpServer', x=-1357.64, y=80.00, z=-639.25], EntityPig['Pig'/232, l='MpServer', x=-1414.75, y=75.00, z=-597.52], EntitySheep['Sheep'/233, l='MpServer', x=-1419.24, y=75.00, z=-600.50], EntityPig['Pig'/361, l='MpServer', x=-1404.77, y=68.00, z=-584.27], EntityCreeper['Creeper'/234, l='MpServer', x=-1417.50, y=72.00, z=-604.50], EntitySheep['Sheep'/362, l='MpServer', x=-1406.90, y=69.00, z=-590.52], EntityCreeper['Creeper'/238, l='MpServer', x=-1375.50, y=27.00, z=-649.50], EntityBabySkeleton['Baby Skeleton'/241, l='MpServer', x=-1365.50, y=13.00, z=-699.50], EntityZombie['Zombie'/242, l='MpServer', x=-1360.50, y=13.00, z=-695.50], EntityBat['Bat'/243, l='MpServer', x=-1362.73, y=14.02, z=-695.07], EntityBat['Bat'/244, l='MpServer', x=-1361.73, y=14.58, z=-696.45], EntityCreeper['Creeper'/245, l='MpServer', x=-1355.50, y=75.00, z=-706.50], EntityCreeper['Creeper'/246, l='MpServer', x=-1353.50, y=75.00, z=-706.50], EntityZombie['Zombie'/247, l='MpServer', x=-1439.50, y=22.00, z=-628.18], EntityZombie['Zombie'/248, l='MpServer', x=-1401.50, y=35.00, z=-659.50], EntityBat['Bat'/249, l='MpServer', x=-1405.75, y=36.10, z=-667.75], EntityCreeper['Creeper'/250, l='MpServer', x=-1402.50, y=32.00, z=-671.50], EntityZombie['Zombie'/251, l='MpServer', x=-1395.50, y=63.00, z=-668.50], EntityZombie['Zombie'/252, l='MpServer', x=-1439.19, y=80.00, z=-614.49], EntitySkeleton['Skeleton'/253, l='MpServer', x=-1452.50, y=97.00, z=-601.50], EntitySkeleton['Skeleton'/254, l='MpServer', x=-1451.50, y=97.00, z=-602.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_101, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 711534272 bytes (678 MB) / 1849663488 bytes (1763 MB) up to 17153064960 bytes (16358 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx16G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 108
    FML: MCP 9.32 Powered by Forge 12.18.2.2099 24 mods loaded, 24 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.2.2099.jar) 
    UCHIJAAAA   Forge{12.18.2.2099} [Minecraft Forge](forge-1.10.2-12.18.2.2099.jar) 
    UCHIJAAAA   BiomesOPlenty{5.0.0.2068} [Biomes O' Plenty](BiomesOPlenty-1.10.2-5.0.0.2068-universal.jar) 
    UCHIJAAAA   birdsnests{1.3} [Bird's Nests](BirdsNests1.10-1.3.jar) 
    UCHIJAAAA   brandonscore{2.1.0} [Brandon's Core](BrandonsCore-1.10.2-2.1.0.47-universal.jar) 
    UCHIJAAAA   draconicevolution{2.0.0} [Draconic Evolution](Draconic-Evolution-1.10.2-2.0.0.105-universal.jar) 
    UCHIJAAAA   endercore{1.10.2-0.4.1.56-beta} [EnderCore](EnderCore-1.10.2-0.4.1.56-beta.jar) 
    UCHIJAAAA   JEI{3.12.7.312} [Just Enough Items](jei_1.10.2-3.12.7.312.jar) 
    UCHIJAAAA   Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UCHIJAAAA   EnderIO{1.10.2-3.0.1.120_beta} [Ender IO](EnderIO-1.10.2-3.0.1.120_beta.jar) 
    UCHIJAAAA   ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.10.2-alpha-1.1.0b.jar) 
    UCHIJAAAA   fastleafdecay{v11} [Fast Leaf Decay](FastLeafDecay-v11.jar) 
    UCHIJAAAA   grapple_hooks{1.0.8} [Grapple Hooks](Grapple-Hooks-1.10.2-1.0.8.jar) 
    UCHIJAAAA   journeymap{1.10.2-5.2.4} [JourneyMap](journeymap-1.10.2-5.2.4-unlimited.jar) 
    UCHIJAAAA   levels{r4.1.3} [Levels](Levels-1.10.2-r4.1.3.jar) 
    UCHIJAAAA   malisiscore{1.9.4-4.0.1} [MalisisCore](malisiscore-1.9.4-4.0.1.jar) 
    UCHIJAAAA   malisisdoors{1.9.4-5.0.1} [MalisisDoors](malisisdoors-1.9.4-5.0.1.jar) 
    UCHIJAAAA   mcmultipart{1.3.0_83} [MCMultiPart](MCMultiPart-experimental-1.3.0_83-universal.jar) 
    UCHIJAAAA   Mekanism{9.2.1} [Mekanism](Mekanism-1.10.2-9.2.1.56.jar) 
    UCHIJAAAA   MekanismGenerators{9.2.1} [MekanismGenerators](MekanismGenerators-1.10.2-9.2.1.56.jar) 
    UCHIJAAAA   MekanismTools{9.2.1} [MekanismTools](MekanismTools-1.10.2-9.2.1.56.jar) 
    UCHIJAAAA   simplyconveyors{1.7.10-1.0.0} [Simply Conveyors](SimplyConveyors-1.0.3.jar) 
    UCHIJAAAA   WailaHarvestability{1.1.9} [Waila Harvestability](WailaHarvestability-mc1.10.2-1.1.9.jar) 
    Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
DepLoader (BrandonsCore-1.10.2-2.1.0.47-universal.jar)

CCLCorePlugin (CodeChickenLib-1.10.2-2.3.1.88-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
LoadingHook (Mekanism-1.10.2-9.2.1.56.jar)

MalisisCorePlugin (malisiscore-1.9.4-4.0.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 373.06' Renderer: 'GeForce GTX 650 Ti/PCIe/SSE2'
    EnderIO: No known problems detected.
    Detailed RF API diagnostics:
                  \* RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Tony/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.0.47-universal.jar!/cofh/api/energy/EnergyStorage.class
                  \* RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Tony/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.0.47-universal.jar!/cofh/api/energy/IEnergyConnection.class
                  \* RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Tony/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.0.47-universal.jar!/cofh/api/energy/IEnergyContainerItem.class
                  \* RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Tony/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.0.47-universal.jar!/cofh/api/energy/IEnergyHandler.class
                  \* RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Tony/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.0.47-universal.jar!/cofh/api/energy/IEnergyProvider.class
                  \* RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Tony/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.0.47-universal.jar!/cofh/api/energy/IEnergyReceiver.class
                  \* RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Tony/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.0.47-universal.jar!/cofh/api/energy/IEnergyStorage.class
                  \* RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Tony/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.0.47-universal.jar!/cofh/api/energy/ItemEnergyContainer.class
                  \* RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Tony/AppData/Roaming/.minecraft/mods/BrandonsCore-1.10.2-2.1.0.47-universal.jar!/cofh/api/energy/TileEnergyHandler.class
    Detailed Tesla API diagnostics:
                  \* Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  \* Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  \* Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  \* Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  \* Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  \* Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  \* Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  \* Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  \* Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  \* Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  \* Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

```
Launched Version: 1.10.2-forge1.10.2-12.18.2.2099
LWJGL: 2.9.4
OpenGL: GeForce GTX 650 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 373.06, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 8x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
```

**Comment by Siern** [comment]
I have run into this problem as well...

I have diagnosed this problem...and fixed it *kind of* for my version.

Here are my findings... and at this point I am actually leaning on saying it is mcmultiparts mod's fault.

The real crash problem is evident earlier than your crash report.  It is the extended state is not valid.
The get extended states here will return a null (extended.getValue(OBJProperty.INSTANCE)...
```
	@Override
	public List<BakedQuad> getQuads(IBlockState state, EnumFacing side, long rand)
	{
    	if(side != null) 
    	{
    		return ImmutableList.of();
    	}
    	
    	if(state != null && tempState == null)
    	{
			IExtendedBlockState extended = (IExtendedBlockState)state;
			BlockRenderLayer layer = MinecraftForgeClient.getRenderLayer();
			ColorProperty colorProp = extended.getValue(ColorProperty.INSTANCE);
			int color = -1;
			
			if(colorProp != null && colorProp.color != null)
			{
				color = extended.getValue(ColorProperty.INSTANCE).color.ordinal();
			}
			
			OBJState obj = extended.getValue(OBJProperty.INSTANCE);
```

based on the code shortly following in the method, I assume this should never be the case.
```
			if(obj.getVisibilityMap().containsKey(Group.ALL) || obj.getVisibilityMap().containsKey(Group.ALL_EXCEPT))
	        {
	            updateStateVisibilityMap(obj);
	        }
```

I then looked into why the state was bad... and found that in the mcmultiparts mod... there is some code logic in effect that I assume mekanism was not expecting this behavior. (note the double type check, which makes me believe this method is not well thought out.  Considering too that I think the deprecation suppression is entirely for this part in which their first type check ensures the deprecated function is never called?)

```
    @SuppressWarnings("deprecation")
    private static void renderBreaking(IMultipart part, IVertexConsumer consumer, double x, double y, double z, float partialTicks,
            int destroyStage, TileEntityRendererDispatcher rendererDispatcher) {

        MultipartSpecialRenderer<IMultipart> renderer = MultipartRegistryClient.getSpecialRenderer(part);
        if (renderer != null && renderer.canRenderBreaking(part)) {
            renderer.setRendererDispatcher(rendererDispatcher);
            renderer.renderMultipartAt(part, x, y, z, partialTicks, destroyStage);
        } else {
            if (MinecraftForgeClient.getRenderPass() == 1) {
                ResourceLocation path = part.getModelPath();
                IBlockState state = part.getActualState(MultipartRegistry.getDefaultState(part).getBaseState());
                if (part instanceof IMultipart2 && ((IMultipart2) part).shouldBreakingUseExtendedState()) {
                    state = part instanceof IMultipart2 ? ((IMultipart2) part).getExtendedState(state, part.getWorld(), part.getPos())
                            : part.getExtendedState(state);
                }
```

The effect of this is that getExtendedState is never called on the PartUniversalCable -> PartSidedPipe's getExtendedState.
```
	@Override
	public IBlockState getExtendedState(IBlockState state)
	{
		ConnectionProperty connectionProp = new ConnectionProperty(getAllCurrentConnections(), currentTransmitterConnections, connectionTypes, renderCenter());
		
		return ((IExtendedBlockState)state).withProperty(OBJProperty.INSTANCE, new OBJState(getVisibleGroups(), true)).withProperty(ConnectionProperty.INSTANCE, connectionProp);
	}
```


I fixed this in my version by simply changing the PartSidedPipe to overload shouldBreakingUseExtendedState and return true in order to assure the intended extended state is likely the intended cable's state.
Code change: Added this method to the class PartSidedPipe
```
	@Override
	public boolean shouldBreakingUseExtendedState() {

		return true;
	}
```


PS.  Hope this helps, I'm not a minecraft modder, just a programmer.  So I have made a lot of assumptions in my diagnoses.

**Comment by ProsperCraft** [comment]
Here is another crash report-
This is happening to multiple players a day, we are recommending using Enderio conduits instead for now.

Modpack- FTB InfinityLite 1.0.1
http://pastebin.com/RLUTbxK4

**Comment by Orgoth** [comment]
The Problem is MCMultipart 1.3.0, not Mekanism.
amadornes/MCMultiPart/issues/58

1.2.1 was working without any problem, after a upgrade to 1.3.0 it is crashing.
