### ISSUE TITLE
game locks up on thermal evaporation plant

### ISSUE THREAD

**Issue by jtb1313** [aidancbrady/Mekanism#3888]
When building the thermal evaporation plant at max size when you get water hooked up to it when you look in the gui it locks up the game
I had to mcedit it out
Edit: I went back a version and it still locks up and this time it even completely crashed out of the game
Edit: I went back to the newest version and made the tower just 5 blocks tall I would test taller but I do not want my game to crash again

**Comment by conor1234** [comment]
I am also having this issue, did you find a way around it?

**Comment by aidancbrady** [comment]
Should be fixed as of 1.11
