### ISSUE TITLE
[Request] Project Red Electrotine support

### ISSUE THREAD

**Issue by pwnage-pineapple** [aidancbrady/Mekanism#3892]
It seems that universal cable cannot link to and power blocks such as the auto-crafting bench from Project Red. I would like to see this feature implemented.

**Comment by Just-some-cannibal** [comment]
Mekanism cables only transfer tesla, rf and eu

**Comment by pwnage-pineapple** [comment]
While I'm not sure if it was clear, the point of this issue is a request to see it implemented. I'll update OP to reflect that.

**Comment by KamranMackey** [comment]
I don't see Project Red support being implemented for the universal cables, due to the fact of Aidan focusing on Minecraft 1.10, and Project Red has not yet been updated for 1.10 or anything past 1.7.10 for that matter.

**Comment by Ushupiuck** [comment]
Ehrm... Sorry to necro this, but ProjectRed is already 1.10.2

**Comment by VT-14** [comment]
Well, at the moment Aiden is MIA.  He's busy with school, so Mekanism hasn't been publicly updated in months.

**Comment by Ushupiuck** [comment]
explains a few things... Still, doesn't means he wouldn't come back later! ='3 he will do, or consider it, whenever he gets free enough to read this ticket.

**Comment by JaSpr** [comment]
Hmm. Wonder if he can't appoint someone to take over public updates while he's busy.

**Comment by TehStoneMan** [comment]
I would be willing to help out with that, although I am busy with another mod at the moment.
Mekanism is one of my favourite mods, and I would love to see it updated.

**Comment by JaSpr** [comment]
I'd be totally behind helping getting more frequent updates. Mekanism is definitely my favorite mod

**Comment by aidancbrady** [comment]
I'm going to pass on this; we are now supporting EU, RF, Forge Energy and Tesla which I believe is plenty to account for the majority of other mod integration.
