### ISSUE TITLE
Diversion Transporter does not react to redstone

### ISSUE THREAD

**Issue by Mahir007** [aidancbrady/Mekanism#3893]
According to the wiki, you can set a logistical transporter Redstone sensitivity with the configurator, I've tried that and it didn't work, when right clicking it just says what colour the pipe is. 
Then after reading a bug report posted on GitHub, I see that you changed it so that only diversion transporters can have a Redstone sensitivity mode.
So I tried setting the mode to active with Redstone on each face of the diversion transporter that I could access but that still does nothing when presented with a Redstone signal.

Also every time I join my server it asks me to upgrade to mekanism 9.2.0 even thought 9.1.0 is the latest version for MC1.7.10

**Comment by EmperorJon** [comment]
Identical situation on a server my friend runs. 9.1.0 on 1.7.10, diversion transporter redstone settings seem to have no impact whatsoever.

**Comment by tsutsarin** [comment]
Same thing on
Minecraft: 1.10.2
Mekanism: 9.2.1

**Comment by aidancbrady** [comment]
Appears to be fixed in 1.11.
