### ISSUE TITLE
Thermal Evaporation Plant produce high ms on Sponge Server

### ISSUE THREAD

**Issue by Lexio375** [aidancbrady/Mekanism#3894]
Hey guys, we have an issue on our server network with your mod mekanism. We actually have run a server with the new modpack "hermitpack" from the FTB-Team based on sponge. Now we have the problem with the Thermal Evaporation Plants. They produce very much laggs.

MC-Ver.: 1.10.2

**Comment by Dilnu** [comment]
It would be helpful if you could provide a screenshot and a copy of your latest log files. The screenshot would make it more clear what size Thermal Evaporation plant you're using and what's attached to it, text describing the same would be almost as helpful.

The log file would provide details on which version of each mod you have and whether there are errors or warnings being thrown by Mekanism or another mod.

As you are on Hermitpack I think it's also worth asking whether you're using Torcherino alongside the Evaporation plant. If you are I think it's unlikely that the issue can be resolved.
