### ISSUE TITLE
A few files in the package mekanism.api.gas seem to be referencing files not present in the API

### ISSUE THREAD

**Issue by DovahOfKiin** [aidancbrady/Mekanism#3896]
I downloaded the MDK for 1.9.4 from the official website, and placed the mekanism (which contains the api folder) inside src/api/java. Upon adding the java folder as a source folder, I noticed that a few files such as [Gas.java](https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/api/gas/Gas.java) and [GasNetwork.java](https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/api/gas/GasNetwork.java) seem to be importing from the packages mekanism.common and mekanism.client. These packages are not present in the API. I thought this was something that was only in 1.9, so I downloaded the 1.10 MDK just to check, but the same issue seems to persist. Am I doing something wrong, or is this an issue that needs to be fixed?

**Comment by DovahOfKiin** [comment]
After a bit of checking versions, I have noticed that the issue goes back all the way to 1.8.9. 1.7.10 does not seem to have those imports. However as early as 1.8.9: https://github.com/aidancbrady/Mekanism/blob/1.8.9/src/main/java/mekanism/api/gas/Gas.java lines 3 and 4 import from mekanism.client, and https://github.com/aidancbrady/Mekanism/blob/1.8.9/src/main/java/mekanism/api/gas/GasNetwork.java lines 13 and 14 import from mekanism.common. So this is certainly not a new issue.

**Comment by DovahOfKiin** [comment]
This issue had been brought up earlier, but no one responded: https://github.com/aidancbrady/Mekanism/issues/3645

**Comment by aidancbrady** [comment]
Fixed!
