### ISSUE TITLE
[1.10.2] Suggestion: bring back wrench-compatiblity

### ISSUE THREAD

**Issue by hron84** [aidancbrady/Mekanism#3898]
In 1.7.10 I loved how Mekanism honored EnderIO or BC wrenches, preventing me to create configurator too early. Could you please bring back this wrench-paradise for us again? Currently, EnderIO wrench cannot pick up neither machines or cables, it's same with RFTools wrench (this two mod is pretty popular). Allowing them to act as a Mek wrench would be awesome. No need for configurator properties, just for wrenching and optionally rotation.

**Comment by nolimet** [comment]
Would also be handy if that functionality could be used to pick up the cables/ pipes in the mods
