### ISSUE TITLE
[1.10.2] [9.2.0.292] JEI compatibility messed up

### ISSUE THREAD

**Issue by hron84** [aidancbrady/Mekanism#3899]
Currently, JEI has a serious problems with Mek blocks, if I click on a machine or a block in the JEI, recipe for all similar blocks pop up. E.g. if I select Enrichment Chamber from JEI I see almost all one-block machines in JEI recipe window. Same for containing blocks (block of charcoal, osmium block, etc).

Affected modpack: FTB Presents HermitCraft 1.0.1
Affected Mek version: 1.10.2-9.2.0.292

**Comment by KindarConrath** [comment]
+1 on this, while not game breaking, very frustrating!

**Comment by utoc** [comment]
https://github.com/aidancbrady/Mekanism/pull/3925
