### ISSUE TITLE
[1.10.2] Dynamic tanks will not output to Quantum Entangloporters.

### ISSUE THREAD

**Issue by cpeake9** [aidancbrady/Mekanism#3900]
As title says. Been playing with the steam reactor/ turbine and opted to use quantum entangloporters to move fluids around as there's no good way to move 150000 mb of steam/water per tick otherwise. Even ultimate cables don't support nearly enough. However the dynamic tank seems to be unable to output to an entangloporter directly. It accepts just fine.

**Comment by Malkierian** [comment]
Just tested it with 295 and it works.  If it still doesn't for you (if this is still an issue), make sure that you set the mechanical pipe to extract from the dynamic valve it is attached to, that it is plugged into an input side of the entangloporter, and that the exit entangloporter is either set to auto-eject, or the pipe attached to it is set to extract, and that the pipe is attached to an output side (in the liquid configuration of the panel).

If this isn't still an issue, please close it.
