### ISSUE TITLE
Wind generator with power (?)

### ISSUE THREAD

**Issue by Remtak** [aidancbrady/Mekanism#3901]
Hello there, 

I'm having trouble trying to make the wind generator work.

![066fba6a8f](https://cloud.githubusercontent.com/assets/22887565/19437438/bd9697ea-9475-11e6-877f-ec2a799e57c4.png)

As you can see there is no power generated and i tried to put the wind turbine in different position on Y.
I need your help thanks :).j
Btw i'm running 9.1.0.281 for 1.7.10

**Comment by VT-14** [comment]
2 things:
1) The wind turbine requires visibility to the sky.  If you place (opaque) blocks above it, it won't work.  Your picture does not make it clear if you are doing that or not.

2) Those power output numbers have clearly been altered.  This may be bad configuration, or an attempt to effectively disable the Wind Generator.
