### ISSUE TITLE
[1.7.10] Logistical Sorter 'default' route is counter-intuitive

### ISSUE THREAD

**Issue by MadEgg** [aidancbrady/Mekanism#3902]
It seems that the default route is used as a fallback for everything.

What I would like to do is define say 5 filter rules to send specific items one direction and all others a different direction. So I set up a default route. However, of the destination for one of the 5 filter rules is full (for example, a ore processing setup, which isn't fast enough to keep up), it will not hold on to the items until space is available but send them the default route instead.

I'd like this behaviour to be at least configurable, where 'default' can either mean, 'if you can't send it any other way, send it here', or 'if you there isn't a filter matching this item, send it here'.

**Comment by DrParanoia** [comment]
+1 Would be nice if we can configure the Sorter in a way that it won't sent items if the target color is full (like a strict color filter or something).

**Comment by aidancbrady** [comment]
Added an "Allow Default" option to transporter filters.
