### ISSUE TITLE
[1.7.10] Logistical Sorter should prefer larger stacks

### ISSUE THREAD

**Issue by MadEgg** [aidancbrady/Mekanism#3903]
The logistical sorter will send out items based on their position on the filter list, not based on stack size. I have ingots trickling in from a smelting factory, and because the ingot\* filter is above, for example, a filter sending gravel elsewhere, when a bunch of gravel comes up, this will directly fill the inventory and leave one spot open for the trickling ingots that are always send out first. This can easily clog a sorting system.

I think it would be nice if the sorter had a preference for larger stacks of items, or, alternatively, have a timer that prefers to send out items that have been in the inventory longer / leaves stacks for a couple of seconds to grow if there's also other items to send out.

At this moment I am able to configure a minimum stack size, but not for OreDict-filters, only for item filters, so that doesn't really help unless I want to add a huge amount of filters for each type of ingot.

**Comment by aidancbrady** [comment]
I'd rather leave this functionality the way it is for now.  Entirely prioritizing filters is the goal of the Logistical Sorter.
