### ISSUE TITLE
[1.10.2] Universal Cables Don't Output To Tesla Machines Correctly?

### ISSUE THREAD

**Issue by Nephatrine** [aidancbrady/Mekanism#3905]
When I attach a universal cable to a TESLA consumer (e.g. from EnderIO), they fail to output power to the machine. They can accept power from TESLA producers just fine but cannot output to a TESLA consumer at all afaik. Strangely enough, an adjacent Energy Cube does provide power without issue - it's just the cable that is seemingly broken.

When using a mod like [Teslafied](https://minecraft.curseforge.com/projects/teslafied) that enables TESLA support for all RF-based tile entities, it stops universal cables from outputting to those previously RF-based machines as well (e.g. from Deep Resonance or RFTools) since they're trying to take TESLA power now.

I get a lot of STDERR spam from `mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30` as well which seem TESLA-related (many of which also mention EnderIO).

Using:
Mekanism 9.2.0.292 (also tried with dev version from AllTheMods)
FML 2107 (also tried with 2094)
Tesla 1.2.1.49

**Comment by KingZero** [comment]
Only fix we have been able to find so far is EnderIO conduits and the tesla API must be installed
