### ISSUE TITLE
Shift-Clicking into smelting factory weird desync

### ISSUE THREAD

**Issue by AnZaNaMa** [aidancbrady/Mekanism#3906]
Hi, I'm playing on Mekanism 9.2.0 and whenever I shift-click a stack of items into my basic smelting factory, the items go into the slots in the factory, but visually move to the top half of my inventory. Not sure if it's a desync issue or something or what. Just thought I'd let you know

**Comment by aidancbrady** [comment]
This desync has been around for years. Definitely on my agenda but I honestly have no idea how this could be occurring.
