### ISSUE TITLE
Question about my Addon

### ISSUE THREAD

**Issue by chaos234** [aidancbrady/Mekanism#3908]
Hey Aidan,

I want to ask if you have recived my mail. If so, or even if not, pls contact my in Skype.
In addition:

1.7.10: https://github.com/chaos234/MekanismAdditions/tree/1.7.10
1.10.2: https://github.com/chaos234/MekanismAdditions/tree/1.10.2

It is still hard to contact you without writing you a "issue".

**Comment by chaos234** [comment]
Push

**Comment by chaos234** [comment]
Push

**Comment by chaos234** [comment]
Push

**Comment by aidancbrady** [comment]
Closing- 1.11 is now the only supported Mekanism release.  I hope your addon is coming well!

**Comment by chaos234** [comment]
Ok, I'll look on it soon.

⁣Gesendet mit BlueMail ​
