### ISSUE TITLE
[Suggestion] IC2 rubber wood should give Jungle planks

### ISSUE THREAD

**Issue by hron84** [aidancbrady/Mekanism#3910]
In 1.10.2 (but IIRC in 1.7 too) rubber wood log can be smelted for jungle log, also ThermalExpansion sawmill handles MFR and IC2 rubber wood same way - splits it up to jungle planks. Even IC2 Block Cutting Machine produces jungle planks from it. Currently Mek is the only mod that produces oak planks from rubber logs.

 So the question: what if we unify handling rubber wood and consider it has a jungle planks inside?

**Comment by aidancbrady** [comment]
Done!
