### ISSUE TITLE
Mechanical Pipes and Machines wont in/out liquids 

### ISSUE THREAD

**Issue by KakesRevengeCZ** [aidancbrady/Mekanism#3913]
Hello, 
So i have a problem with getting chloride from electrolytic separator to the chemical infuser  with mechanical pipes (even tried it with transfer nodes and ender io conduits and doesnt work). As you can see from the pictures, it doesnt even connect to the chemical infuser, so am i doing something wrong here or is it the code fault? Im getting kinda frustraded lol

![screenshot_18](https://cloud.githubusercontent.com/assets/23000419/19620421/520d71b8-987d-11e6-8a76-63251acf00a7.png)
![screenshot_19](https://cloud.githubusercontent.com/assets/23000419/19620423/56d15b56-987d-11e6-9100-6dacabfbfbcc.png)
![screenshot_20](https://cloud.githubusercontent.com/assets/23000419/19620424/584a1c34-987d-11e6-95b4-cee23e557f95.png)

**Comment by KakesRevengeCZ** [comment]
![screenshot_21](https://cloud.githubusercontent.com/assets/23000419/19620472/56202efc-987e-11e6-8a21-b417e3ba1b03.png)

**Comment by chaos234** [comment]
Aren't they gaseuos? Yes, they are gaseous so try with gas pipeps ans look how it flows :).

**Comment by KingZero** [comment]
Make sure you have the inputs and outputs for the machines correct the Configuator helps a ton with making sure the input and outputs are correct

**Comment by VT-14** [comment]
AS Chaos234 pointed out, the Electrolytic Separator inputs fluids (mechanical pipes) and produces 2 gasses.  Use Pressurized Tubes to extract the Chloride, which I think will come out of the right side of the block (left side on the bottom picture).

As a pre-warning before you find it, The Electrolytic Separator does not receive a power efficiency boost from Energy Upgrades (only the increased internal capacitor).  It produces Hydrogen, which can be burned in a Gas-Burning Generator to produce power (the same amount that you put in).  This upgrade abnormality is there to prevent it from breaking the laws of thermodynamics.

@KingZero I think the Electorlytic Separator is one of the handful of blocks that doesn't have side configuration.  The output and input sides can't be changed.

**Comment by KakesRevengeCZ** [comment]
Oh no's, Im a derp, sorry for the dumb question and thank you for the help.
