### ISSUE TITLE
Tesla implementation leads to infinite energy

### ISSUE THREAD

**Issue by utoc** [aidancbrady/Mekanism#3918]
This has been a difficult issue to track down due to the lack of mods in my pack using Tesla, however, now that EnderIO supports it; we've narrowed it down further.

Preliminary case before EnderIO supported Tesla: https://github.com/utoc/BBQBugs/issues/18

The setup: Two tesla capable mods; one of which is Mekanism.  The other mod needs to have energy transport, ie, ActuallyAdditions or EnderIO are what we've tested with.

Using EnderIO item conduits, you effectively multiply energy by 2.5x when going from a Mek cube -> EIO Energy Conduit -> Mek Energy Cube.  Using ActuallyAdditions, you can use their energy relays and get some squirrely results.  EnderIO and ActuallyAdditions, between themselves, behave quite well.  This leads me to believe that something is misbehaving with Mek's Tesla implementation.

If I remove the Tesla jar, the issue goes away completely and Mek plays nicely.

Can you check into this;  I've been all over EnergyAcceptorWrapper.java and can't spot the issue

**Comment by b0bst3r** [comment]
This maybe related to the issue we found:-

So made a quintuple AA battery, set to charge items in inventory/hotbar, is enabled.

Grab up an empty ultimate energy cube from Mekanism and it will fill 51.x million rf in about a second while using up very little energy from battery itself.

Tried with an EIO capacitor bank and didn't have any issues, same with draconic capacitor that was disabled to not charge anything.  It charged both of these items as expected. It's just mekanism energy cubes.

**Comment by Saereth** [comment]
This is also occuring with Telsa energy blacklisted if the Tesla mod is installed

**Comment by utoc** [comment]
This may have been addressed with https://github.com/aidancbrady/Mekanism/pull/4148

**Comment by Bluexin** [comment]
I confirm my PR fixes it.
The issue was mekanism not converting back from Tesla to Joules.
