### ISSUE TITLE
Disabled Jetpack, can't enable it

### ISSUE THREAD

**Issue by juleskickflip** [aidancbrady/Mekanism#3919]
Not sure what could be causing this. I made a Jetpack and was messing around with it, I hit the hotkey to change the modes, and it Disabled it fine, but when I hit the hotkey again to Enable it won't do it. It's just stuck on Disabled and I can't do anything about it outside of crafting an entirely new jetpack and not hitting the armor mode change button. I made sure to assign a hotkey for armor switch mode to a key that is completely free and it's still giving me this problem.

1.10.2 mc version with the latest Mekanism build.

Edit: I should mention that I also hear the sound properly when I hit the armor switch key, and continue to hear it despite the Jetpack being stuck in Disabled and not enabling.

**Comment by Brandomine** [comment]
Are you playing on hermitpack because ive had the same issue

**Comment by juleskickflip** [comment]
I am not, I'm playing on my own Forge server with mods I handpicked myself.

**Comment by BricksMcGee** [comment]
Experienced this issue on FTB Infinity Lite for 1.10 v1.0.1  Keybinding in pack was set to Shift-F. After eliminating conflicting keybinds the issue persisted.  Changing keybind from Shift-F to F without a modifier fixed the issue for me.
