### ISSUE TITLE
Mekanism Textures hog a lot of space in the Texture Atlas

### ISSUE THREAD

**Issue by mezz** [aidancbrady/Mekanism#3920]
Here's the texture atlas of a very large pack (HermitPack).
![](https://cloud.githubusercontent.com/assets/916092/19634119/0f719690-996d-11e6-80b1-1ee6747deaa2.png)

As you can see, Mekanism takes up a large amount of space in the upper left area, wasting a lot of it with blank areas.

Here's the new mod to dump textures if you want to try it out: https://github.com/mezz/TextureDump

**Comment by CyanideX** [comment]
Yeah, a lot of those were supposed to be cleaned up when I finalized the models but never got around to it. I also forgot how large some of those cable icons were... yeesh! My bad!

**Comment by KillerMapper** [comment]
The ideal would be using 16*16 textures as much as possible, especially on all those machines textures you can see at the bottom. But reducing the size of the cables and the model textures will already be a good progress.

**Comment by CyanideX** [comment]
The machines are 32x for a reason, although I do prefer to do strictly 16x textures. I'll talk to Aidan and see what I can do to fix those cables.

**Comment by Joshwoo70** [comment]
any update on this?

**Comment by aidancbrady** [comment]
I made some changes in the 1.11.2 builds that should help solve this.

**Comment by Joshwoo70** [comment]
any implementation for 1.10?
