### ISSUE TITLE
Adfly

### ISSUE THREAD

**Issue by Therion666** [aidancbrady/Mekanism#3926]
Is this mod available on a website that is not adfly?

Every time I try to download your mod from that site it tries to force me to download pretty much anything else. 

I've been redirected to movie trailer previewers, music players, graphic tweakers, and pretty much anything that isn't Mekanism when trying to download your mod. I can't say I'm impressed with Adfly. 

I go to the site, there is a countdown in the corner. When this reaches 0 it gives me a button which says skip ad. When I click this, I'm instantly taken to a non-Mekanism site. As such, I cannot use your mod. 

That's a pretty major bug, IMO.

**Comment by jburrows82** [comment]
There's a Chrome extension to skip adfly pages. Still goes to the actual adfly page, but then forwards to the link redirect automatically. I just verified the adfly links on http://aidancbrady.com/mekanism/download/ correctly forward to officially hosted files. 

Other options:
1) Strip the forward link from the URL
2) Download from the Jenkins

**Comment by VT-14** [comment]
Aiden promised to upload to CurseForge 'soon' shortly after V9 came out.  He wanted to get a few bug fix releases out before uploading there.  That was a few months ago. He's been rather busy with school. :P 

I copied the mod files over from the Hermitpack modpack, which is actually safe to download from FTB or Curse.  It has Mekanism 1.10.2-9.2.0.292, and the same versions for Generators and Tools.  At the moment, that's the most current version available.

**Comment by aidancbrady** [comment]
Curse will definitely be coming soon. Adf.ly was a great way to provide some much-needed passive income but it seems that it has grown to be too much of a nuisance to users.

**Comment by aelfwyne** [comment]
PLEASE stop using Adfly...

I just spent 20 minutes trying to download Mekanism via your adfly link. Constant hammering of sites trying to hijack my browser and NOT actually directing me to the download. Finally after multiple tries I've gotten updates for 2 out of 3 of your files.

**Comment by ktole1999** [comment]
i use chrome with adblocker. works like a champ.

**Comment by aelfwyne** [comment]
ktole1999: Adblock doesn't stop all of the adfly junk, only some of it. Issue remains that Adfly is a known malware distributor.

**Comment by thiakil** [comment]
you can URL decode the adfly link and just download it direct if you want to avoid adfly 100%

**Comment by ktole1999** [comment]
@aelfwyne  i didnt say it blocked it 100%. i just mentioned what works for me.
