### ISSUE TITLE
Reactor randomly shutting down

### ISSUE THREAD

**Issue by nosknut** [aidancbrady/Mekanism#3929]
Hi. I have a redundant reactor setup on a server. Im producing a lot more fuel of both types then i need. The reactor injection rate is set to 8 and still it keeps shutting down randomely. Why? Can this be a result of the reactor not being in only one chunk or in the same chunk as the fuel generating setup? Also are there any effects of uverheat?

**Comment by Just-some-cannibal** [comment]
The injection rate keeps on being set to 0 for me

**Comment by nosknut** [comment]
Only numbers devidable  by 2

**Comment by aidancbrady** [comment]
I've done some extensive testing and can't reproduce this, in 1.7.10 or the latest 1.11 builds.  Not sure why this would be occurring on your end.

**Comment by nosknut** [comment]
Did you try it on aserver and did you try to reboot the server while having the setup chunkloaded and running while you were not on?

**Comment by aidancbrady** [comment]
Yeah I did, many times.  The only times my reactor turned off were when the fuel was cut off externally.

**Comment by nosknut** [comment]
Well. In that case it must be sommething wrong with the chunkloading systems. Thank you for trying to fix it ...
