### ISSUE TITLE
[BUG] Cardboard box has problems with IC2 machines

### ISSUE THREAD

**Issue by hron84** [aidancbrady/Mekanism#3930]
Cardboard box does not package up IC2 machines correctly. After removing the box, an unskinned `ic2:te` will be placed, losting with the block's metadata (almost all IC2 machines are ic2:te the only difference is in metadata). I have no problems with purple and black but the resulted machine is also not working anymore and I really don't need this expensive decoration blocks. 😄 

**Steps to reproduce:**

1. Make a CESU
2. Make a cardboard box
3. Place down CESU 
4. Put cardboard box on CESU
5. Pick it up
6. Place down, remove cardboard box.

**Expected result:**

A CESU, an orange-ish colored block

**Actual result:**

A purlple-black checked block with name ic2:te

**Affected versions:**

Minecraft 1.10.2
Forge: 2099
IC2: 2.6.87-ex110
Mekanism: 1.10.2-9.2.0.292

Note: CESU is `ic2:te:73`, maybe cardboard box has a limit on metadata number like 64 or so?

**Comment by thommy101** [comment]
Can confirm on latest 1.11.2 as of this moment.

Metadata isn't limited to 64, it's saved in the cardboard as an integer.

**Comment by aidancbrady** [comment]
Merging with #4370
