### ISSUE TITLE
Heat Generators: Transferring no heat

### ISSUE THREAD

**Issue by Armitxes** [aidancbrady/Mekanism#3931]
Sorry if this is not a bug / intended but I've build some Heat Generators to gather heat. The issue is, that all the heat is being Dissipated. Transfer is always on 0.0

Steps to reproduce:
1) Place a heat generator
2) Connect any thermo conduits / cables to it
3) Surround the heat generator with lava on all remaining sides

Result:
"Transferred (heat)" always is on 0.0

Affected versions:
Minecraft 1.10.2
Forge: 12.18.1.2090

**Comment by aidancbrady** [comment]
The "Heat Generator" is kind of quirky in the way it is intended for electricity generation FROM heat, not heat generation itself.  It does absorb very little heat, hence the heat GUI tab.
