### ISSUE TITLE
Request: update your ores with tool requirement / min mining level

### ISSUE THREAD

**Issue by Kaisoul** [aidancbrady/Mekanism#3934]
I have an issue with your ores now to explain the issue in detail my pick axe is a tinkers construct pickaxe made with  paper head,paper binding/knightslime handle with 5 reinforced plates added & a obsidian sharpening kit added to the tool.

So the tool will mine Cobalt level ores and will mine ores faster if the tool is a higher minging level then the ore in question.

Your ores are not either requiring a pickaxe to mine or they don't have a min mining level set so mining each one of your ores is like mining obsidian...

was wondering if this can be corrected in a future update?

**Comment by aidancbrady** [comment]
This isn't on my end, blocks don't set "min mining levels" for themselves.  It uses the same material as any other ore.
