### ISSUE TITLE
Industrial Turbine runs on any fluid

### ISSUE THREAD

**Issue by Karmacopper** [aidancbrady/Mekanism#3938]
Forge 1.7.10 10.13.4.1614
Mekanism 9.1.0.281

Whilst testing steam/turbine setups I mistakenly pumped 2000mb/t of water directly into my turbine. It appears to create the same amount of power as the equivalent amount of steam. I would consider this quite broken behaviour.

Further testing shows lava, milk (via MRF) and liquid XP (from Open Blocks) also work!

**Comment by aidancbrady** [comment]
Fixed
