### ISSUE TITLE
Digital Miner Texture

### ISSUE THREAD

**Issue by Katapow99** [aidancbrady/Mekanism#3939]
Hi there,
A quick warning, this is in 1.7.10-9.1.0.281 and not 1.10+, so if this isn't fixed in due time because of the work on future versions that is fine with me. The bug in question is with the Digital Miner when it is active and mining blocks, there is a OpenGL error and the texture turns completely white, I am quite surprised this hasn't been fixed already.

**Comment by ThatGamerBlue** [comment]
1.7.10 isn't supported /close @aidancbrady
