### ISSUE TITLE
Logistical transporter - some items won't cross chunk boundary

### ISSUE THREAD

**Issue by DougGreenhough** [aidancbrady/Mekanism#3940]
Just ran into a very odd issue: had a vanilla chest that was getting Sulfur Ore (Railcraft) and Iron Ore inserted into it from another mod (Immersive Engineering Excavator, but that isn't relevent: I replicated it without IE stuff anywhere near). Connected the chest to an Entangloporter via a Basic Logistical Transporter and configured the chest end to pull, and found that it was pulling the Sulfur and dirt out of the chest, but would not pull Iron Ore or grassy dirt. I checked the destination, and there was plenty of room in the output inventory. If the last item in the input chest was grassy dirt or Iron Ore, it wouldn't pull anything into the Entangloporter. 

I tried removing and replacing all components several times, and made sure nothing was colour-coded with the configurator, but no joy.

I've used the same setup dozens of times with no problems, so it took me a while to spot what I'd done differently: the chest and the Entangloporter were separated by a chunk boundary. Both chunks were chunkloaded, but moving the entangloporter to the same chunk caused the pipe to start dragging out everything properly.

**Comment by aidancbrady** [comment]
Merging with #4479, this lines up exactly with the issue.
