### ISSUE TITLE
Crash when breaking a cable

### ISSUE THREAD

**Issue by QuantumSheep** [aidancbrady/Mekanism#3943]
This error happen when we try to break a Mekanism's cable. (I'm not alone with this glitch)

Minecraft version: 1.10.2
Forge version: 12.18.2.2118
MCMultiPart version: 1.3.0
Mekanism version: 9.2.0.292

Crash-Report: http://pastebin.com/rfGq1aG0

**Comment by QuantumSheep** [comment]
Reported to MCMultiParto to: https://github.com/amadornes/MCMultiPart/issues/58

**Comment by BrianEdmonds** [comment]
I ran into this as well. Tried upgrading Mekanism to 294 and Forge to 2121, but still crashes.

**Comment by P1st0lpr0** [comment]
It crashed for me , too.

**Comment by Prodiod** [comment]
One of my players has this problem as well.
