### ISSUE TITLE
Hermitpack mekanism crashing issue.

### ISSUE THREAD

**Issue by rarrapuda** [aidancbrady/Mekanism#3944]
Hello I'm running ftb hermitpack 1.1.0 on a server.
I constructed the reactor and maybe I didn't have things setup right because it wasn't creating the amount of power I was expecting but then I decided to just get steam from it well when I did that every time I tried to extract steam it would crash the server.
I still have it built on my server you can contact me if you want to see it yourself I just have the steam disconnected.
Twitter Rarrapuda
Email rarrapuda@gmail.com 
I also attached the crash reports I have a few more also if needed.

[crash-2016-11-02_08.50.02-server.txt](https://github.com/aidancbrady/Mekanism/files/573261/crash-2016-11-02_08.50.02-server.txt)
[crash-2016-11-02_08.49.01-server.txt](https://github.com/aidancbrady/Mekanism/files/573262/crash-2016-11-02_08.49.01-server.txt)

**Comment by SDUBZ** [comment]
remove the multipart that is loaded by deploader and install the latest multipart seems to be the issue here mate

**Comment by rarrapuda** [comment]
I've updated the modpack and it still crashes I'm now on ftb hermitpack 1.2.1. I'm not sure what the mcmultipart is though

**Comment by SDUBZ** [comment]
well until mekanism stops using deploader your gonna have to fix it by going into your mods folder then the 1.10 folder delete the mcmultipart and install the latest manually through the launcher,which can be done by going to profile options unlocking the pack and then you should be able to fix the problem :D 
only fix i got for you until mekanism removes deploader
