### ISSUE TITLE
[9.2.1] Liquid loss with basic fluid tank and mechanical pipes

### ISSUE THREAD

**Issue by tsutsarin** [aidancbrady/Mekanism#3949]
Part of liquid is lost during the transfer.

Steps to reproduce:
1. Place two basic fluid tanks.
2. Connect them with basic mechanical pipe.
3. Configure one end in PUSH mode, second in PULL mode/
4. Put one bucket of water in tank.
5. Only 500 mB of water appears in second tank.

Versions information.
Minecraft: 1.10.2
Forge: 12.18.1.2014
Mekanism: 9.2.1
Modpack: All the mods lite

**Comment by red-mist** [comment]
Possibly related issue: liquids disappear when taken from a basic/advanced fluid tank by a fluid conduit. Tested same setup with seared tank, this worked correctly. (ftb infinity light 1.10.2, mekanism 9.2.0)

**Comment by thommy101** [comment]
Please make sure you're using the latest version of mekanism. It's supposed to be fixed in version 9.2.1 295
