### ISSUE TITLE
"The Logistical Grid" - Resource Management System

### ISSUE THREAD

**Issue by Vaygrim** [aidancbrady/Mekanism#395]
![2013-11-13_14 42 10](https://f.cloud.github.com/assets/4295188/1535458/382d14ec-4ca4-11e3-8a4c-17dd60f04735.png)

The above screenshot is a mockup of an idea I had, and was discussing in the Mekanism IRC channel last night. The basic concept behind this proposed enhancement is the further expansion of the Logistical Transporters, Logistical Sorters.. and their overall capabilities... transforming them into an end to end inventory management system (or "Logistical Grid" if you will). Two blocks are standing in for the proposed enhancement blocks I am thinking of:

- Logistics Coordinator (Shown as the Crafting Table)
- Logistical Provider (Shown as the Osmium Block)

**** The Logistical Provider ****
   This block will act as a liaison between a chest (or other inventory block) and a grid of Logistical Transporters. The "Provider" block shares two critical pieces of information with the Logistical Grid... what items it has in its inventory currently that it can 'provide' to the rest of the Grid, and what items it 'wants' or 'fetches'. This 'Fetch System'  will communicate actively with any Sorters on the Logistical Grid, telling them exactly what items that Sorter can send to the Provider in question. A Provider could be attached to a chest and configured to 'fetch' all ores travelling on the Logistical Grid. 

The Provider should have a few different 'fetch methods':
  (-) Ore Dictionary Fetch - Just as with the sorter, this would allow me to type "ingotIron" or "*stick*", etc.
  (-) Item Specific Fetch - This would be block specific, just as the normal Item Filter in a sorter.
  (-) Mod Fetch - This would allow me to type in the name of a specific mod, for example "Thaumcraft", and have every item from that mod get 'fetched' by the Provider.

   The provider is meant to act as an alternate means for expanding the sorting capabilities of Logistical Grids, allowing for functionality WITHOUT needing to color-code another segment of pipe. Why limit yourself to only 16 colors when you could add into that Logistical Providers which actively ask for (or "Fetch") specific block/item types?

**** The Logistics Coordinator ****
   The Coordinator is designed to act as a 'Master Control Unit' for the entire Logistical Grid to which it is attached:

  (-) It checks with Logistical Sorters that it finds, allowing for reconfiguration of settings or filters on that specific Sorter.
  (-) It will communicate with Logistical Providers, 'pulling' any chosen amount of goods or materials from those Providers to a chest sitting adjacent to the Coodinator.
  (-) It can be set to automatically 'pull' specific amounts of specific resources to its adjacent chest. (Example: Telling the Coordinator to always keep 64 Cobblestone blocks on hand.)

   The Coordinator can be thought of as the master interface on an Applied Energistics network: It lets you view your current supplies and inventory (that is attached to the Grid via Provider or perhaps by Bin?), grabbing anything you want... as long as you are willing to deal with a time delay to allow for 'pulled resources' to travel through the Logistical Transporters.
   I think that the Coordinator SHOULD actually have power requirements, unlike the rest of the system's setup. The Coordinator's tasks and capabilities would be great, so it could perhaps consume a meager amount of power each time that it performs a task.

**** OVERALL CONCEPT ****
  This entire system setup and idea stems from the concept of making alternatives to the likes of Applied Energistics or Logistical Pipes, both of which can be extremely resource intensive to get setup and power hungry to maintain. The "Logistical Grid" can be cheaper in cost to get setup, but just as flexible and expandable as other alternatives.
  Simply have a Logistics Coordinator (with a chest adjacent to it) located in your regular workroom or machine room, and the rest of your inventory storage could be located in another room or building entirely. This would give you the ability to fetch any resource you needed... without the pesky walk!

If further mockup screenshots are required to better make my point, just let me know. I would really love this system to be made, especially if it could be cost efficient and low in power requirements, creating minimal lag in the mean time.

**** LONG TERM OPTIONS ****
    Further enhancements that could be added to this system could be power-requiring alternatives to BuildCraft's "AutoCrafting Bench" or XyCraft's "Fabricator"; a block that is set to craft one item whenever given supplies, and will talk to a Logistical Grid.. acting as its own 'Provider' for whatever it is capable of crafting.

**Comment by aidancbrady** [comment]
I'm going to put this on hold while I focus on the rest of the outstanding issues.  While I don't think I'll be adding anymore advanced functionality to the transporters themselves, adding blocks that allow for more advanced inventory coordination is on my to-do list.
