### ISSUE TITLE
1.10.2 MCMultiPart

### ISSUE THREAD

**Issue by SimonCursley** [aidancbrady/Mekanism#3950]
I am trying to run MCMultipart 1.3.0, which i need for some mods like Refined Storage.

 Mekinism1.10.2- 9.2.0.294 seems to load an older version MCMultiPart1.2.0

**Comment by SDUBZ** [comment]
its mostly due to them using deploader which is not meant to used anymore i told aidan on twitter and once on here but dont think anyone noticed
