### ISSUE TITLE
[1.10.2][9.2.0.292] NullPointerException when breaking any pipe

### ISSUE THREAD

**Issue by magnus97** [aidancbrady/Mekanism#3955]
I have tried and breaking every pipe in mekanism with a normal pickaxe and a tinker's pickaxe and everything leads to the same crash but it seams to be the result of having mcmp v1.3.0

http://paste.ee/p/iD8Ph

**Comment by magnus97** [comment]
#3952 #3935 and this one is mostly the same issue but with different pipes

**Comment by Drakma** [comment]
This also occurs in [1.10.2][9.2.0.294]

**Comment by todofixthis** [comment]
Note:  I can whack the pipe a few times without consequence.  The crash seems to occur right as the first damage overlay should appear on the pipe.

In the meantime, you can use a configurator in wrench mode to remove pipes and cables.
