### ISSUE TITLE
Cardboard Not Opening when Shield in Second Hand 1.10.2

### ISSUE THREAD

**Issue by desagas** [aidancbrady/Mekanism#3957]
Version 9.2.0.294 playing on All the Mods Modpack on the Curse Launcher Version 1.41b

I thought I would let you know that you can not shift right click on cardboard boxes unless both your hands are empty. Meaning, if you have a shield or something in the shield spot, and you have an empty hand and try to shift right click to unwrap, nothing happens. I thought it was broken, but through trial and error, I figured out that both hands need to be emptied. I do not know if this is intended or not, but no infomration on the mod anywhere mentions this that I have been able to find.

**Comment by thommy101** [comment]
Cannot replicate in the latest version.
Holding a shield in the offhand slot and nothing in the main slot. Shift right click unboxes the block.
