### ISSUE TITLE
[Bug] "Fell from a high place" jetpack=death from 1m(block) high

### ISSUE THREAD

**Issue by NightOps007** [aidancbrady/Mekanism#3959]
When using the jetpack in normal mode(not hover), you will die when landing from a short fall of 1m(block) if you, during any part of your flight, went high enough that the fall would kill you.  Mekanism-1.10.2-9.2.0.292

**Comment by Thranx** [comment]
I can reproduce this as well.

**Comment by VizuaaLOG** [comment]
I can also reproduce this. Was super annoyed when it first happened 😄

**Comment by aidancbrady** [comment]
Appears to be fixed in 1.11.
