### ISSUE TITLE
Flux Networks issue with Wind Generators

### ISSUE THREAD

**Issue by GreatBanoose** [aidancbrady/Mekanism#3962]
Posting here as well as at the Flux Networks github.   

Hooking up a wind generator to a Flux Networks Flux Plug with the "Ignore Limit" option set to true will transfer millions of RF/t while only producing around 200 RF/t.   

Only really seems to happen with the Wind Generator and not other power producing blocks.

http://imgur.com/a/0NBDo

That's from a 20 kRF/t deep resonance crystal and one of the wind generators on the flux network.

Mekanism 1.10.2 9.2.0.924
Flux Networks 1.9.4.107

EDIT: Video of 4 Wind generators

https://www.youtube.com/watch?v=9FkRb7USYhQ&feature=youtu.be

**Comment by aidancbrady** [comment]
Fixed in dev
