### ISSUE TITLE
Potentially adding muffling upgrade for Generators

### ISSUE THREAD

**Issue by SpellMaster20** [aidancbrady/Mekanism#3965]
I know this isn't an issue but a suggestion just not sure where to put it.

I know that the machines in 1.10 have upgrades for muffling that is so nice, since I could hear them in another chunk but the generators make sooo much noise as well. So would it be possible for the option to add muffling upgrades to the generators as well? They do not have the nicest sound to listen to when you are in your base with a bio generator going off. Or is there something like this already that I have completely missed?

Thanks Spell_Master

**Comment by aidancbrady** [comment]
I'm going to leave the Muffling Upgrades exclusively for the machines for now.

**Comment by Mochnant** [comment]
@aidancbrady Any chance we might revisit this?  The generators, especially when they cycle on and off due to the variable burn rate, can be quite annoying to hear.  Seems reasonable to allow the generators the muffle upgrade, assuming it is not too technically challenging.
