### ISSUE TITLE
Server lagging with Mekanism 9.1.0

### ISSUE THREAD

**Issue by AnorexieMentale** [aidancbrady/Mekanism#3970]
**Hi.**
I'm playing on private Feed The Beast server (Modified modpack).
We are currently four on the server, and Mekanism cables (Energy Cables, mostly advanced and ultimate) cause lags, We don't know why but when we replace cables with another mod , TPS are much better.
Is there a fix or a config files to replace ? This is pretty annoying cause we like Mekanism. 
Thank's for your time and for the mod.

**Comment by aidancbrady** [comment]
I'm going to try to make things a little more efficient over the next few releases.  Thanks for the report!
