### ISSUE TITLE
mekanism crash in Infinity lite 1.10

### ISSUE THREAD

**Issue by popps73x** [aidancbrady/Mekanism#3972]
was trying to use a logistical transport pipe to move salt from and extra utilities 2 crafter to a chemical injection chamber.  attempting to break the transport pipe with a pickaxe causes the crash.

https://www.dropbox.com/s/gsvybbha6l6gta2/crash-2016-11-12_11.44.23-client%20mekanism%20crash.txt?dl=0

**Comment by aidancbrady** [comment]
Fixed in dev

**Comment by popps73x** [comment]
ty
