### ISSUE TITLE
mekanism 1.10.2-294 crash when breaking basic energy cables

### ISSUE THREAD

**Issue by SDUBZ** [aidancbrady/Mekanism#3973]
crash report:
[crash-2016-11-13_07.31.46-client.txt](https://github.com/aidancbrady/Mekanism/files/587615/crash-2016-11-13_07.31.46-client.txt)
forge:1.10.2-2124
mekanism,generators,tools:1.10.2-294

**Comment by dominx** [comment]
I got a similar crash with version 1.10.2-292, after updating the hermitpack from 1.1.0 to 1.3.0. It seems that the mekanism version did not change. Works fine with pack version 1.2.1
Just touching the cable or transporter with disassembler triggers crash. Wrenching with the horrible configurator works fine.
[http://pastebin.com/FTSfNXMr](url)

**Comment by Tntdruid** [comment]
Glad its not only me there crash

**Comment by thommy101** [comment]
There are around 7 other issues with exact the same error message. There's a pull request ( #3967 ) fixing the issue being described here.

**Comment by ariosos** [comment]
Can confirm. I suspect it's similar to the item breaking issue that Tinkers' Construct had a few months ago after Forge changed something with the rendering of the breaking animation. It breaks at 9% (according to WAILA).

**Comment by SDUBZ** [comment]
@thommy101 can we get a pull request for deploader to be updated to latest aswell?

**Comment by thommy101** [comment]
@SDUBZ I can look into it. But I'm unfamiliair with deploader and it's intended purpose. Looks like loading of dependencies, but that could be done in other ways.
Maybe someone can explain what it is, and if there is an update/alternative for.

**Comment by SDUBZ** [comment]
its a dependancie downloader but its outdated causing the wrong mcmultipart to be added and if newer mcmultipart is already installed it overwrites it and installs the outdated mcmulitpart that other mods require to launch,if you contact covers1624 he can point you in the right direction he helped brandans core do the same because it also was causing crashes to other mods, due to it overwriting newer mcmultipart versions

**Comment by aidancbrady** [comment]
I've updated the MCMP dependency version for Mek v9.2.2, expect the fix soon.
