### ISSUE TITLE
MEKANISM 1.10 DOESNT WORK

### ISSUE THREAD

**Issue by ADITHYAMC** [aidancbrady/Mekanism#3974]
HEY AIDANCBRADY

I TRIED OPENING IT BUT I FAILED TO OPEN

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Mac OS X (x86_64) version 10.11.5
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 104086296 bytes (99 MB) / 337932288 bytes (322 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.2.2116 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2116.jar) 
	UC	Forge{12.18.2.2116} [Minecraft Forge] (forge-1.10.2-12.18.2.2116.jar) 
	UE	Mekanism{9.2.1} [Mekanism] (Mekanism-1.10.2-3.jar) 
	UE	MekanismGenerators{9.2.1} [MekanismGenerators] (Mekanism-1.10.2-3.jar) 
	UE	MekanismTools{9.2.1} [MekanismTools] (Mekanism-1.10.2-3.jar) 
	Loaded coremods (and transformers):

**Comment by ADITHYAMC** [comment]
FIX IT AIDAN

**Comment by spannerman79** [comment]
> FIX IT AIDAN

Don't make demands @ADITHYAMC

**Comment by VT-14** [comment]
Mekanism-1.10.2-3 is NOT a proper Mekanism version.  Delete whatever the heck that (likely malware) is and never use that site again.

I would bypass the "official" download links that take you to malware happy AddFly.  I personally downloaded the Hermitpack modpack and pulled the files from there, but there is also a way to skip strait to the download page by editing the download link's URL.

Aidan really needs to get around to uploading it to CurseForge (he said he would shortly after v9 came out).  AddFly is far to untrustworthy.

**Comment by SDUBZ** [comment]
can we please get a pull request for deploader to be updated so it actually installs the right mcmultipart so not everypack that has mekanism and other mods doesnt crash because you guys are using outdated deploader please :(

**Comment by ktole1999** [comment]
works fine for me
