### ISSUE TITLE
Machines rotating by themselves

### ISSUE THREAD

**Issue by jadeonking** [aidancbrady/Mekanism#3977]
the advanced solar panel and electrolytic separator just randomly rotate it doesn't seem to effect the inputs and outputs of the machines not sure if any other Mekanism machines do this and to clarify only mekanism machines are doing this its very strange

**Comment by Kzorith** [comment]
I have noted this with a bio-generator that I have placed in the world.  It will, at random turn 90 degrees right, breaking the connection with the energy cell that it's touching and stopping work.  It also appears to clear out the biofuel that is displayed in the window of it.  However if I open the UI, it rotates back to it's original position and begins working again.  This was in both 292 and 294 releases.

**Comment by Ommina** [comment]
Add Elite Enriching. Elite Crushing, and Elite Smelting factories to the list of tiles that turn around randomly.  Interestingly, while they are turned, The One Probe reports them all as "Elite Smelting Factory".  As with @Kzorith above, opening the GUI fixes both the rotation and the name reported.

In my case, all machine are supposed to be facing South.  I've not noticed a North-facing machine rotated.

292 with forge 2122.

**Comment by duragizer** [comment]
Having the same problem, for me it is contained within a chunk but if it starts in a chunk all the mekanism machines will rotate and flicker. Also in the machines GUI the item slots, power meter flicker in and out looks like it is empty but there are items there, the auto split flicker on and off.

Also when this happens the FPS is unplayable, get 3fps around the machines. Solved that by using optifine though, with that fps is unaffected.

**Comment by OldManMining** [comment]
Same rotating problems, but mine includes the bins. I come back to my storage area and every face (or almost every one) has rotated 180º. Same as above, where you access the bin and it shows correct again. In my new base building zone, it seems to be when I leave the area and come back. In my previous mining area, however, I could set down a bin or machine and watch it turn backwards almost instantly. On a side note, I thought the area of the map was glitched, because inventories would vanish as you were using them (crates, chests, machines, everything from any mod or vanilla) and show back up after clicking the sort button or waiting a few seconds. On changing areas, this seems to have stopped, but the Mekanism rotating continues.

**Comment by Hexmare** [comment]
Add the Digital Miner to the rotating list. Using version .295 and when I first put the miner down it was rotating 90 degrees. When I Saw this take place, I was not able to destroy the machine and replace. I disconnected and reconnected to my local server and was able to destroy the miner and replace it. After re-setting the miner it no longer rotated, however it did shift back and forth 1 block. The operation of the unit was normal, the power feed even though it looked disconnected still was feeding power. Very odd.

**Comment by Skar78** [comment]
Same problem. Encountered in multiple instances:

Abridged Beta 4, 5 and 6 - with factory upgrades under a Forestry farm see [here](https://github.com/elytra/Unabridged/issues/561#event-882901035) - and now also in Hermitpack 1.4 and 1.5.

However in Germitpack everyhting was fine for many many hours, until I created a space controller from rftools with a space covering the mekanism factories.

**Comment by krelios** [comment]
I am also affected by this bug but it seems to happen more often in chunks that are chunkloaded by FTB Utilities--although not *only* in those chunks.

**Comment by ab9rf** [comment]
I am having problems with a metallurgic infuser that will briefly appear in the desired orientation, then rotate to a different orientation a few seconds later. Attempts to rotate it with a configurator have no apparent effect.

An adjacent enrichment chamber more or less rotates normally, except that sometimes when I rotate the enrichment chamber, the metallurgic infuser also rotates. And then a few seconds later, both rotate to a different position.

This behavior is quite irritating.

**Comment by kurisubrooks** [comment]
Having this with my metallurgic infuser, enrichment chamber and energized smelter. Quite annoying, aesthetically. The machines still work and outputs are as expected, but they just seem to always want to face North 😞 

It should be noted that Mekanism Generators seem to be completely unaffected by this.

**Comment by Ricket** [comment]
I'm having machines randomly rotate very often. Here's an example:

![image](https://cloud.githubusercontent.com/assets/196978/21706005/a0c9b812-d391-11e6-98e8-a427b283a69d.png)

The two metallurgic infusers both rotated on their own, the back faces are supposed to be facing the middle of that cluster of machines. And the gas tank is hilariously laying on its side! It's obviously supposed to be upright (I don't think you can even normally place it sideways like that).

If I right-click each machine then it will typically fix the rotation of the machine I right-clicked, though sometimes it messes up some other machine. For example I just right-clicked the tank and it went upright, then I right-clicked one metallurgic infuser and it fixed and I right-clicked the second metallurgic infuser, and it fixed but messed up the gas tank again. And then I right-clicked the gas tank and it was fixed. Now they are all their correct rotation:

![image](https://cloud.githubusercontent.com/assets/196978/21706038/eb0f658e-d391-11e6-910d-e9e3420ee2a7.png)

But just now as my game was paused and I was typing the above, they rotated back to the broken rotations:

![image](https://cloud.githubusercontent.com/assets/196978/21706101/8ec5ed88-d392-11e6-9791-d02fc66abe06.png)

**Comment by sputim** [comment]
**Modpack: All The Mods**

Same problem here. Some machines (noticed it first with the bins) are rotating themselves to face north.

It breaks connections with cables and other machines and the bins stop accepting items.

**Comment by DietmarKrause** [comment]
latest build of All the mods(23 March 2017) the wind turbine rotate counter clockwise 90 degrees from time to time and they dont give RF any more. Opening the GUI solves it for the moment, often only for 5 sec. or so. It started after building a enderio farming staion with dark oak wood trees, but the dont obstruct the sky. Perhaps the wind mills were to close to another, they had a space of 2 blocks. I rebuild them on the roof on my building and until now everything seems to be fine.

**Comment by SteveSutton1989** [comment]
I also noticed this. With all machines so far. One of the main causes for me is when something is updated. Ex: turn on my Rf tools shield projector or turning on a compressor. Again though it doesn't effect input and output it's purely graphical.

**Comment by DietmarKrause** [comment]
I have to look for this: if it is purely graphical. I am not sure until now. But the far to laud win mills were suddenly quiet :) And update: yes can be. in my case i had a enderio farm station with oak seeds and boen meal in it. The chunc gets updates by every use of bone meal i guess?

**Comment by thommy101** [comment]
Acording to @Ricket, who had made a pull request for fixing this issue:

> Forge 1922+ introduced a new TileEntity syncing mechanism, which by
default calls readFromNBT with a compound that contains only x/y/z/id
data. It does this on chunk load, and when blocks are marked dirty or need
update. As a result, the Mekanism tile entities were having readFromNBT
called where the expected keys were not in the NBTTagCompound, so all the
state was being set default, until later Mekanism's custom networking
would overwrite it to bring it in sync with the server again, and repeat.
I just added an implementation which does not call readFromNBT.
Fixes: #3977 #4170 (maybe others too)
In the future, we should remove Mekanism's custom networking code for
sending TileEntity state, and instead use this built-in one properly. It
looks like they have similar interfaces so it should be a fairly
straightforward port.

This issue has a fix available, it's only a matter of time to have it in a released version.
