### ISSUE TITLE
Suggested redstone interaction on reactors

### ISSUE THREAD

**Issue by falizure** [aidancbrady/Mekanism#3978]
in relation to the issue i have been having along with many others, that the injection rate gets reset it seams to me the easiest fix would be to allow the reactor to react to redstone, i find it curious it can output it but not input, especially when most of the other blocks are fully configurable, it does not necissarily have to be computercraft although that would be nice addition but even just being able to input x redstone strength to get y injection rate would be nice, at least enough to turn it back on automatically, i discovered the lack of said feature today when trying to automate it to work around the issue, i can do everything else including the lasers and amplifiers so why not that.

**Comment by aidancbrady** [comment]
The injection rate issue should be fixed.
