### ISSUE TITLE
Digital Miner has stopped working

### ISSUE THREAD

**Issue by jadeonking** [aidancbrady/Mekanism#3979]
![DM](http://i.imgur.com/dBOt3hP.png) as you can see it shows that there is ore to mine but it just doesnt do anything it was working like an hour ago i picked it up moved it now it stops working its being powered by a reactor in this screenshot so it has plenty of power and is using ore* as the filter

**Comment by VT-14** [comment]
Mekanism version, and are you using a mod that provides chunk ownership/protection?

For example, FTB Utils needs to have the owner set their chunks to allow fake player interactions using commands.  /FTB chunks ...

**Comment by jadeonking** [comment]
1.10.2-9.2.0.292 Hermit Pack and yes I believe i did claim the chunks but they arent being chunkloaded from what the claim chunk window was telling me or does that not matter simply claiming messes it up?

**Comment by VT-14** [comment]
Claiming a chunk prevents other players from messing with it.  The default setting also disabled Fake Players, like the Digital Miner.

**Comment by jadeonking** [comment]
ah confirmed that unclaiming fixed it sorry to trouble you with this have a good day!

**Comment by VT-14** [comment]
You should be able to keep the chunk claimed (for chunk loading) using /FTB chunk (and I forget all the rest of the options, but one of them is fake player.  Use tab to auto-fill and see the possible entries).  That is not an op command, so any player can use it to set their own chunk settings.

**Comment by jadeonking** [comment]
the option for fake player doesnt appear to be there sadly ![nowhere](http://i.imgur.com/nnMUUKI.png)

**Comment by VT-14** [comment]
Whoops. It's under a different /ftb command.  maybe settings or something?  It will be fairly obvious once you find it.

On a different note, you should be able to close this issue.
