### ISSUE TITLE
Request a new ad provider other than ad.fly.  Ad.fly displays pornographic content now in it's ad's.

### ISSUE THREAD

**Issue by sharkck** [aidancbrady/Mekanism#3980]
I downloaded this awesome mod yesterday and Ad.fly presented me with the following ad:
http://mmofreegames.online/general/static/0018/index.html?voluumdata=BASE64dmlkLi4wMDAwMDAwMS00NmIyLTQxMmMtODAwMC0wMDAwMDAwMDAwMDBfX3ZwaWQuLmY1N2U1ODAwLWFhMzctMTFlNi04MjM2LTBmMWFiN2Y2NjEwNl9fY2FpZC4uNDE5YjMwOTAtM2YzZC00ZDczLThmOTEtN2Q1ZTc3NTk0NjRiX19ydC4uREpfX2xpZC4uYTFjNmUzYTctNzhlMi00MjkwLThjZjctNWYyYmM5OTEyNDgzX19vaWQxLi4wNDlkY2YyZi0xOTBhLTQxZTAtYjY3OS03ZGY4ODBiOWJkMDlfX3JkLi5hZGZcLlxseV9fYWlkLi5fX2FiLi5fX3NpZC4u

For those who dont' want to click on that... it's a picture with an anime woman's vagina right in your face giving head and a .gif of some anime chick getting boned.  I really hope that you guys take this into consideration and change who you go through if they're going to be presenting your downloader's (which, I'm sure, a large percentage of them are kids) with pornographic content.

**Comment by VT-14** [comment]
Uploading on CurseForge is planned according to the Mek V9 release post.

**Comment by jburrows82** [comment]
You provided the link, but not a screenshot verifying it being served by Ad.fly so it could be reported for inappropriate content. Next time, provide a screenshot. It'll help prevent children from seeing inappropriate content... unlike your easy to click link.

**Comment by sharkck** [comment]
I provided the full link because it contained referral data in the link and hoped that he would be able to report it to adfly or something.  Providing a snapshot would be posting the content forcing everyone that clicks on this to see it where saying what the link is would let people know what it is so that if they dont want to see it, they dont click on it.

**Comment by Xiaminou** [comment]
Yeah what happened to putting it on curseforge?

**Comment by ariosos** [comment]
Would agree - I keep getting spyware trying to install itself and more often than not, I have to resort to CTRL-ALT-DEL to close each chrome window )a good half dozen that sometimes don't want to close).

**Comment by laserjet25** [comment]
If you have chrome you can use this extension to "skip" the adfly: https://chrome.google.com/webstore/detail/adfly-skipper-★now-workin/obnfifcganohemahpomajbhocfkdgmjb?hl=en

**Comment by aidancbrady** [comment]
https://minecraft.curseforge.com/projects/mekanism-v9
:)

**Comment by ben-mkiv** [comment]
sorry for bumping the old thread, but the ad.fly links are still on your homepage, and they are known to spread malware.

google actually marked the optifine homepage as harmful two weeks ago, and they used ad.fly, too.

**Comment by thiakil** [comment]
Use Curseforge then.
