### ISSUE TITLE
[9.2.0] Chemical Injection Chamber does not export non-vanilla shards

### ISSUE THREAD

**Issue by BroCube** [aidancbrady/Mekanism#3981]
How to recreate:

Place a chemical injection chamber, power and gas it up.
Set a side to eject and turn auto-eject on. Or off, doesn't matter.
Add a mekanism pipe connecting to a purification chamber. Configure the pipe however you'd like,; push or pull either end, it doesn't matter.
Insert an ore. If it is a vanilla ore like iron, the shards will move to the purification chamber as expected. If it is any other ore, such as mekanism's own osmium ore, the shards will not move.

bonus: if you take just one shard and manually place it in the purification chamber, the rest will then move.

EDIT: seems it isn't as reliably reproducible as I thought, it only happens sometimes. Trying to figure out if there's a location or direction issue or a last-item-through-the-system-related thing. I'll reply with my findings.

**Comment by aidancbrady** [comment]
Can't reproduce.
