### ISSUE TITLE
Purifying Factory Not Accepting Automated Inputs

### ISSUE THREAD

**Issue by dsbookbug** [aidancbrady/Mekanism#3984]
I am having an issue with the Purifying Factory not accepting items from any form of automation. I've tested it with a Logistical Sorter/Transporters, as well as as a hopper. I am currently using version 9.2.0.294 for Minecraft 1.10.2

**Comment by jburrows82** [comment]
did you configure the sided configuration for input? And if so, can you take a couple screenshots showing your setup?

**Comment by dsbookbug** [comment]
I managed to figure out what the issue was. The purifying factory requires the gas to be input before it will allow any ores to be added in automatically. I didn't realize this, and tried to put the ores in first
