### ISSUE TITLE
[1.10.2] Rendering Block Entity

### ISSUE THREAD

**Issue by YOYOK9** [aidancbrady/Mekanism#3987]
Was building an evaporation tower with a builders wand from Better builders wands and when the tower completed I saw the redstone particals then my client crashed. Looks like a rendering error. 

MC: 1.10.2
forge: 2139
Mekanism: 1.10.2-9.2.0.294
http://pastebin.com/AgPQN2Dt

**Comment by jburrows82** [comment]
Try disabling mipmapping and reproducing without Optifine.

**Comment by YOYOK9** [comment]
Disabled mipmaping and removed Optifine and it built fine. But ones I added water to the multi-block it crashed.  I believe when I built the first one it already had water in it. 

http://pastebin.com/DpYapNq6

**Comment by HyperBlueCore** [comment]
similar issue but with rendering TiC Smeltery controller
http://pastebin.com/YJJf6Z27

**Comment by jennybrush** [comment]
another similar issue, but with rendering universal fluid tank 

MC 1.10.2
Mekanism 9.2.0.294
Forge 1.10.2-12.18.2.2151
https://gist.github.com/jennybrush/c5c5a47700dd143884ea016554f3bd6f

**Comment by aidancbrady** [comment]
Fixed in dev
