### ISSUE TITLE
Rendering Block Error when breaking glowpanels

### ISSUE THREAD

**Issue by Hachuurui** [aidancbrady/Mekanism#3988]
MC 1.10.2
Forge: 12.18.2.2124
Mekanism-1.10.2-9.2.0.292

Tried breaking them with vanilla tools, Draconic Evolution tools, and Tinker Tools. Same error. 

This may be related to https://github.com/aidancbrady/Mekanism/issues/3987  but wanted to show it may be more than just multiblocks.

[crashlog.txt](https://github.com/aidancbrady/Mekanism/files/601730/crashlog.txt)

**Comment by thommy101** [comment]
It's related to #3967 (open pull request fixing breaking of cables and glowpanels)
