### ISSUE TITLE
crash when placing mechanical pipes next to biogens

### ISSUE THREAD

**Issue by audenga** [aidancbrady/Mekanism#3989]
[crash-2016-11-20_13.57.13-server.txt](https://github.com/aidancbrady/Mekanism/files/601815/crash-2016-11-20_13.57.13-server.txt)   - client

[crash-2016-11-20_13.55.03-server.txt](https://github.com/aidancbrady/Mekanism/files/601816/crash-2016-11-20_13.55.03-server.txt)  - server

i would remove mechanism then just spawn the stuff back in, but my entire infrastructure depends on it : (

**Comment by Cuppycake** [comment]
Happening with vanilla items as well.

https://github.com/Cuppycake/Mech-and-Magic/issues/119

**Comment by thommy101** [comment]
@Cuppycake The problem with your report is an other bug. See #3967

**Comment by thommy101** [comment]
Hey @audenga, can you try the fix in #3995?

**Comment by audenga** [comment]
i honestly dont know how to try any fixes, if theres an easy way to try then im all ears

**Comment by thommy101** [comment]
I've compiled my latest version:
[MekanismAll-1.10.2-9.2.1.homebaked_161122.zip](https://github.com/aidancbrady/Mekanism/files/605898/MekanismAll-1.10.2-9.2.1.homebaked_161122.zip)

Please let me know if it fixes the problem for you.

**Comment by audenga** [comment]
i do believe its fixed, not getting any crashes related to the original issue from my testing, now i just need to wait untill some 1 over in ic2 land fixes a crash with other stuff

**Comment by thommy101** [comment]
You can leave this issue open as it's not merged into the official repository. What you've got is a compiled version by me.

**Comment by thiakil** [comment]
how to reproduce this for testing?
