### ISSUE TITLE
Need Help MEKANISM  Keeps Crashing 

### ISSUE THREAD

**Issue by ItsreficuL** [aidancbrady/Mekanism#3990]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.60-beta.jar)
  LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 11/19/16 10:26 PM
Description: Unexpected error

java.lang.IllegalStateException: Already building!
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:284)
	at net.minecraft.client.renderer.RenderGlobal.func_174976_a(RenderGlobal.java:1947)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1625)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1335)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:284)
	at net.minecraft.client.renderer.RenderGlobal.func_174976_a(RenderGlobal.java:1947)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1625)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['TheModGod'/301, l='MpServer', x=27.41, y=64.00, z=589.33]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 04 - customized, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (108,64,256), Chunk: (at 12,4,0 in 6,16; contains blocks 96,0,256 to 111,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 253983 game time, 161904 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 44 total; [EntityPig['Pig'/454, l='MpServer', x=19.45, y=65.00, z=551.87], EntitySheep['Sheep'/327, l='MpServer', x=89.80, y=78.00, z=649.54], EntityPig['Pig'/460, l='MpServer', x=-8.55, y=68.00, z=578.22], IndestructibleEntityItem['item.item.tconstruct.hammer'/461, l='MpServer', x=12.13, y=67.00, z=565.11], EntityPig['Pig'/335, l='MpServer', x=-21.28, y=70.00, z=612.54], EntityPig['Pig'/337, l='MpServer', x=-35.75, y=72.00, z=627.51], EntityPig['Pig'/401, l='MpServer', x=69.79, y=65.00, z=549.24], EntityPig['Pig'/467, l='MpServer', x=-2.78, y=70.00, z=562.88], EntityPig['Pig'/468, l='MpServer', x=-2.56, y=70.00, z=561.95], EntityPig['Pig'/340, l='MpServer', x=80.10, y=78.00, z=635.52], EntityPig['Pig'/469, l='MpServer', x=17.72, y=67.00, z=534.50], EntitySpider['Spider'/342, l='MpServer', x=-33.50, y=48.00, z=559.50], EntityBat['Bat'/344, l='MpServer', x=-34.40, y=52.51, z=552.40], EntityCreeper['Creeper'/346, l='MpServer', x=-34.50, y=63.00, z=548.50], EntityBat['Bat'/347, l='MpServer', x=-34.50, y=48.10, z=558.50], EntityBat['Bat'/476, l='MpServer', x=-34.50, y=35.10, z=603.50], EntityBat['Bat'/477, l='MpServer', x=-35.50, y=35.10, z=604.50], EntityBat['Bat'/478, l='MpServer', x=-34.50, y=35.10, z=604.50], EntityPig['Pig'/350, l='MpServer', x=9.72, y=75.00, z=636.59], EntityZombie['Zombie'/357, l='MpServer', x=-36.50, y=47.00, z=535.50], EntityBat['Bat'/358, l='MpServer', x=-32.78, y=47.29, z=537.93], EntityBat['Bat'/359, l='MpServer', x=-33.76, y=47.64, z=536.73], EntityPig['Pig'/423, l='MpServer', x=-3.50, y=71.00, z=557.75], EntityPig['Pig'/424, l='MpServer', x=10.45, y=65.16, z=543.46], EntityPig['Pig'/425, l='MpServer', x=1.52, y=66.00, z=543.70], EntityZombie['Zombie'/428, l='MpServer', x=-32.50, y=26.00, z=587.50], EntitySquid['Squid'/365, l='MpServer', x=-34.59, y=60.71, z=536.40], EntityPig['Pig'/430, l='MpServer', x=-32.49, y=68.00, z=591.81], EntityFancyItemFrame['Golden Item Frame'/302, l='MpServer', x=29.50, y=57.50, z=588.97], EntityPig['Pig'/431, l='MpServer', x=-35.93, y=67.00, z=586.52], EntityFancyItemFrame['Golden Item Frame'/303, l='MpServer', x=29.50, y=56.50, z=588.97], EntityBabySkeleton['Baby Skeleton'/432, l='MpServer', x=-36.50, y=67.00, z=578.50], EntityFancyItemFrame['Golden Item Frame'/304, l='MpServer', x=29.50, y=55.50, z=588.97], EntitySpider['Spider'/433, l='MpServer', x=-33.50, y=68.00, z=583.50], EntityFancyItemFrame['Golden Item Frame'/305, l='MpServer', x=26.50, y=57.50, z=588.97], EntityPig['Pig'/434, l='MpServer', x=-32.07, y=68.00, z=582.58], EntityFancyItemFrame['Golden Item Frame'/306, l='MpServer', x=26.50, y=56.50, z=588.97], EntityFancyItemFrame['Golden Item Frame'/307, l='MpServer', x=26.50, y=55.50, z=588.97], EntityPlayerSP['TheModGod'/301, l='MpServer', x=27.41, y=64.00, z=589.33], EntityPig['Pig'/436, l='MpServer', x=17.47, y=72.00, z=647.75], EntityPig['Pig'/437, l='MpServer', x=18.18, y=77.00, z=642.67], EntityBat['Bat'/310, l='MpServer', x=-36.50, y=45.10, z=646.50], EntityPig['Pig'/438, l='MpServer', x=30.49, y=68.00, z=648.75], EntityZombie['Zombie'/313, l='MpServer', x=-33.50, y=40.00, z=649.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:496)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1012888232 bytes (965 MB) / 2482503680 bytes (2367 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.2.2132 Optifine OptiFine_1.10.2_HD_U_C1 44 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2132.jar) 
	UCHIJAAAA	Forge{12.18.2.2132} [Minecraft Forge] (forge-1.10.2-12.18.2.2132.jar) 
	UCHIJAAAA	actuallyadditions{1.10.2-r75} [Actually Additions] (ActuallyAdditions-1.10.2-r75.jar) 
	UCHIJAAAA	BRod{1.10.2} [BRod] (BRod.jar) 
	UCHIJAAAA	JEI{3.13.3.382} [Just Enough Items] (jei_1.10.2-3.13.3.382.jar) 
	UCHIJAAAA	cyclicmagic{1.8.10} [Cyclic] (Cyclic-1.10.2-1.8.10.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.60-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.60-beta.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.0.1.127_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.127_beta.jar) 
	UCHIJAAAA	valkyrielib{1.10.2-0.10.5d} [Valkyrie Lib] (valkyrielib-1.10.2-0.10.5e.jar) 
	UCHIJAAAA	environmentaltech{1.10.2-0.10.5h} [Environmental Tech] (environmentaltech-1.10.2-0.10.5h.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.0.0.jar) 
	UCHIJAAAA	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCHIJAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.1.5.jar) 
	UCHIJAAAA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.1.4.jar) 
	UCHIJAAAA	GStone{1.10.2} [GStone] (GStone.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJAAAA	jeresources{0.5.7.87} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.7.87.jar) 
	UCHIJAAAA	LavaBucket{1.10.2} [LavaBucket] (LavaBucket.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.1.194} [Mantle] (Mantle-1.10.2-1.1.1.jar) 
	UCHIJAAAA	Mekanism{9.2.0} [Mekanism] (Mekanism-1.10.2-9.2.0.292.jar) 
	UCHIJAAAA	MekanismGenerators{9.2.0} [MekanismGenerators] (MekanismGenerators-1.10.2-9.2.0.292.jar) 
	UCHIJAAAA	MekanismTools{9.2.0} [MekanismTools] (MekanismTools-1.10.2-9.2.0.292.jar) 
	UCHIJAAAA	mousetweaks{2.6.4} [Mouse Tweaks] (MouseTweaks-2.6.4-mc1.10.2.jar) 
	UCHIJAAAA	multitools{Beta-2} [Multi Tools] (MultiToolsBeta2.jar) 
	UCHIJAAAA	notenoughwands{1.4.0} [Not Enough Wands] (notenoughwands-1.10-1.4.0.jar) 
	UCHIJAAAA	Osidian{1.10.2} [Osidian] (Osidian.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJAAAA	ProjectE{1.10.2-PE1.0.6B} [ProjectE] (ProjectE-1.10.2-PE1.0.6B.jar) 
	UCHIJAAAA	quantumflux{2.0.9} [QuantumFlux] (quantumflux-1.10.2-2.0.9.jar) 
	UCHIJAAAA	refinedstorage{1.2.4} [Refined Storage] (refinedstorage-1.2.4.jar) 
	UCHIJAAAA	simplegenerators{1.10.2-0.10.5b} [Simple Generators] (simplegenerators-1.10.2-0.10.5b.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6b.jar) 
	UCHIJAAAA	TinkersAddons{1.0.3} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.3.jar) 
	UCHIJAAAA	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCHIJAAAA	Torcherino{4.2s} [Torcherino] (Torcherino-4.2s.jar) 
	UCHIJAAAA	treechopper{1.1.1a} [Tree Chopper] (TreeChopper-1.10.2-1.1.1a.jar) 
	UCHIJAAAA	VeinMiner{0.34.1_1.9-73be663} [Vein Miner] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.34.1_1.9-73be663} [Mod Support] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCHIJAAAA	veinminermodintegration{1.7.10-0.2.0} [Veinminer Mod Integration] (veinminermodintegration-0.6.0-1.9.4r29+2f88da6.jar) 
	UCHIJAAAA	weaponcaseloot{4.0.1} [WeaponCaseLoot] (weaponcaseloot-1.10.2-4.0.1.jar) 
	UCHIJAAAA	WHead{1.10.2} [WHead] (WHead.jar) 
	UCHIJAAAA	WitherBane{1.10.2} [WitherBane] (WitherBane.jar) 
	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.10.2-0.4.1.60-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13418 Compatibility Profile Context 15.301.2301.1002' Renderer: 'AMD Radeon(TM) R2 Graphics'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Alex%20Laurel/Documents/Curse/Minecraft/Instances/Survival/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Alex%20Laurel/Documents/Curse/Minecraft/Instances/Survival/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Alex%20Laurel/Documents/Curse/Minecraft/Instances/Survival/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Alex%20Laurel/Documents/Curse/Minecraft/Instances/Survival/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Alex%20Laurel/Documents/Curse/Minecraft/Instances/Survival/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Alex%20Laurel/Documents/Curse/Minecraft/Instances/Survival/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Alex%20Laurel/Documents/Curse/Minecraft/Instances/Survival/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Alex%20Laurel/Documents/Curse/Minecraft/Instances/Survival/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Alex%20Laurel/Documents/Curse/Minecraft/Instances/Survival/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	Launched Version: forge-12.18.2.2132
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) R2 Graphics GL version 4.5.13418 Compatibility Profile Context 15.301.2301.1002, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Faithful 1.10.2-r4
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD E2-7110 APU with AMD Radeon R2 Graphics 
	OptiFine Version: OptiFine_1.10.2_HD_U_C1
	Render Distance Chunks: 5
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13418 Compatibility Profile Context 15.301.2301.1002
	OpenGlRenderer: AMD Radeon(TM) R2 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by jburrows82** [comment]
Disable mipmapping, and remove Optifine.

**Comment by ItsreficuL** [comment]
how do i disable mipmaping

**Comment by ItsreficuL** [comment]
can i install a other optifine or no

**Comment by HyperBlueCore** [comment]
Optifine is a major game crash hander for modpacks I also get the exact same issue
http://pastebin.com/YJJf6Z27

**Comment by HyperBlueCore** [comment]
to disable mipmapping go to Esc >options   > video settings > mipmaplevels > scroll down to 0
