### ISSUE TITLE
tier generators

### ISSUE THREAD

**Issue by fjgj2** [aidancbrady/Mekanism#3992]
Maybe add different tiers of generators that produce more energy, use more fuel and are more expensive to make (of resources).

**Comment by EurypteriD192** [comment]
They kinda got. Like the reactor is top tier.. heat is basic.. bio and wind get step up.. and solar.. including gas burner.

**Comment by fjgj2** [comment]
Yes, but the fusion reactor costs a lot of energy to get going so you need a lot of generators that use a lot of space. Also then you can choose what kind of fuel you want to use as main fuel.

**Comment by VT-14** [comment]
I'm mostly with Eurypteri here.  Using the Heat Generator with coal or other fuels is pretty bad but is enough to get started.  Bio, Wind, and Solar are all fairly easy to get within a few minutes once you have done some mining.  Once you reach the mid game, you can start making Ethylene and use it in a Gas-Burning Generator as an advanced form of bio-fuel.  After that you can move onto the Reactor, which is basically solar powered.

Some of Mekanism's generators are already abnormally OP compared to other mods; and most are way OP compared to where RF power is supposed to be balanced, but RF has unfortunately gone through years of Power Creep to the point where Mek's power levels are considered somewhat normal.  Just a friendly reminder that RF was created by the people who made Thermal Expansion, which had Dynamos that generated 80 RF/t and required fuel.

**Comment by fjgj2** [comment]
But I mean like I had a system for mass producing food for biofuel as main power source. But when I needed more power all the bio generators used a lot of space. So multiple tier for all the generators solve this problem.
And player can choose what they use as main power source (and then when use the fusion reactor as they have the resources and energy)

**Comment by PJB3005** [comment]
Personally I'm firmly against items that "compress" blocks to take less space for the same (or more) resource cost and output like you're suggesting. Items like the upgraded solar panels mod for IC2.

Space requirements and the logistics for such are, IMO, already a challenge in and of themselves and this feature request would easily remove that.

**Comment by VT-14** [comment]
You are supposed to move to better generators.  Ethylene is literally a better version of Bio-Fuel.
