### ISSUE TITLE
game  java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by QDKZ** [aidancbrady/Mekanism#3993]
[crash-2016-11-20_22.57.59-client.txt](https://github.com/aidancbrady/Mekanism/files/603581/crash-2016-11-20_22.57.59-client.txt)

**Comment by thommy101** [comment]
This is an issue of Chisel 2, not mekanism

**Comment by QDKZ** [comment]
and what i can do with this?

**Comment by thommy101** [comment]
Report it to them, not here.
Found your issue: Chisel-2/Chisel-2#420

**Comment by QDKZ** [comment]
thank you
