### ISSUE TITLE
mekanism or ic2 error || mek tanks + ic2 fluid pull = crash

### ISSUE THREAD

**Issue by audenga** [aidancbrady/Mekanism#3998]
ic2 works fine
mekanism works fine

put both together and i get a bad crash i cant recover from : (
https://imgur.com/a/orc84  - setup
http://pastebin.com/GR8PzfKA  - crashlog

i know the log says ic2 upgrade module but from my testing it doesnt happen with the ic2 tanks

**Comment by audenga** [comment]
update from the ic2 guys

Mekanism isn't respecting the doDrain parameter of IFluidHandler, so it is
empting the tank in the calculation drain to leave nothing for the actual drain.
They should change
https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/tile/TileEntityFluidTank.java#L554
to if(canDrain(from, null) && doDrain)

**Comment by thommy101** [comment]
I'm having a same kind of issue. Thanks for pointing in the right direction. Hopefully I can fix it. The provided "fix" from the IC2 dev's does prevent crashing, but also prevents extracting anything at all.

I'll let know if I have a fix

**Comment by Chocohead** [comment]
Changing https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/tile/TileEntityFluidTank.java#L556 to 
```Java
return fluidTank.drain(maxDrain, tier != FluidTankTier.CREATIVE && doDrain);
```
Should properly simulate draining.

**Comment by thommy101** [comment]
I should have seen that comment earlier... Created a pull request with the fix. (second one.. first one had wrong base branch)
