### ISSUE TITLE
Mekanism on Curse?

### ISSUE THREAD

**Issue by Patrick1005de** [aidancbrady/Mekanism#3999]
Hi Guy,

why do you dont upload Mekanism on the Curse Launcher? 
It were pretty nice!

**Comment by HyperionNexus** [comment]
If I recall, it is planned to be on Curse, but due to Aidan being busy and with the lack of updates, it hasn't happened yet.

**Comment by Utildayael** [comment]
Oddly, you can still use Mekanism in a Curse mudpack just fine even though it doesn't show up ON Curse. We're using it on ours.

That said, would be nice to see it formally on Curse. @aidancbrady posted some time ago [on his blog or twitter, cant remember] that he was indeed going to be putting it there "soon" as it didn't make sense to keep doing it the way he is currently doing it with hosting the files and whatnot.

**Comment by C0rn3j** [comment]
Would really welcome this as this is one of the 2 mods in my 200-mod pack that's not on Curse. Sucks for automating updates

**Comment by aidancbrady** [comment]
done :)

**Comment by Utildayael** [comment]
Woot!

**Comment by C0rn3j** [comment]
Awesome! Would you be so kind and add the 1.10.2 version to it too?
