### ISSUE TITLE
crash issue from shift-right clicking on universal pipe with config tool

### ISSUE THREAD

**Issue by badjob12** [aidancbrady/Mekanism#4001]
i was shift-right clicking on a basic universal transport pipe with the config tool
[crash-2016-11-22_16.59.05-client.txt](https://github.com/aidancbrady/Mekanism/files/607034/crash-2016-11-22_16.59.05-client.txt)

**Comment by HyperBlueCore** [comment]
Try deleting your config file and reinsalling the latest right verision of forge and the mod

I was not able to read it properly sorry that what i was able then read i have a flight to the us in a few hours

**Comment by thommy101** [comment]
Looks like a Rf tools bug to me. 
And it seems to be fixed in the latest version right now (5.62)

**Comment by HyperBlueCore** [comment]
Nop thats rf tools loading only so dont worry
