### ISSUE TITLE
digital miner keeps on despawning

### ISSUE THREAD

**Issue by rivercobber** [aidancbrady/Mekanism#4003]
hey im having a problem with the digital miner it keeps on de-spawning i have gone thought 4 of them at first it was just when i logged off but now its happening when im there please help

**Comment by VT-14** [comment]
I didn't have that issue while using a chunk loading upgrade in the DM.  Otherwise, I lost two a while ago.

**Comment by MoonCutter2B** [comment]
has happened to me too once, was logged off

**Comment by thommy101** [comment]
Duplicate of #3718
