### ISSUE TITLE
Duplicate ID: Crusher

### ISSUE THREAD

**Issue by Jake1702** [aidancbrady/Mekanism#4004]
I have a few other mods installed, but the crash reports only show Mekanism being errored. And it mentions something saying "Duplicate ID: Crusher". Crash report: https://paste.ee/r/nYVTv (If you can help me figure out which mod it is and if I can fix it, would be great, or I can ask the author of the other mod.) I just can't find which other mod has it.

**Comment by EurypteriD192** [comment]
Looking at your crash report did you try as it asks you to?
`Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
ThermalExpansion: -[1.7.10]4.1.4-247
TConstruct Environment: Environment healthy.
NetherOres: -[1.7.10]2.3.1-22
ThermalDynamics: -[1.7.10]1.2.0-171
EnderIO: Found the following problem(s) with your installation:
* Optifine is installed. This is NOT supported.
This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.`

**Comment by Jake1702** [comment]
Yes, I did, but it only happens with Mekanism anyway.

**Comment by aidancbrady** [comment]
Another mod is registering a Tile Entity with the identifier "Crusher".  Not much I can do, changing this on my end would break things pretty severely.
