### ISSUE TITLE
[help]How to keep an item in bin?

### ISSUE THREAD

**Issue by Javacym** [aidancbrady/Mekanism#4006]
I want to keep an item in bin.
if there are 64 items in a bin,right-click will get all 64 items, how to keep an item in bin,so get 63 items,then i
 can use the bin to store the same item next time,because there are more bins at my auto factory.

**Comment by VT-14** [comment]
You can shift left click to get 1.  Unfortunately, I don't know of a way to lock bins to a particular item.  That would be rather handy and I would suggest making that a feature request if it isn't already possible.

**Comment by ktole1999** [comment]
depending on the item transport being used is there an item filter available to only allow that item into bin?
