### ISSUE TITLE
Jetpack won't drain hydrogen in the Basic Gas Tank

### ISSUE THREAD

**Issue by wylderhoads1809** [aidancbrady/Mekanism#4008]
I'm using version Mekanism-1.10.2-9.2.0.294 and the gas tank will drain the gauge dropper, but won't drain the jetpack of hydrogen.

**Comment by aidancbrady** [comment]
You're not supposed to be able to drain jetpacks, scuba tanks or flamethrowers of their respective gases.

**Comment by BrianEdmonds** [comment]
Out of curiosity, any particular logic why not? I can't say it's something I'd plan to do much, but it doesn't seem unreasonable to be able to get gas out of a jetpack, since I'd imagine they probably would use some sort of universal coupling, should they actually exist. :)
