### ISSUE TITLE
multiple crashes because of turbines and ticking block entity

### ISSUE THREAD

**Issue by benstuwie** [aidancbrady/Mekanism#4010]
http://pastebin.com/bttG7Vhx
My server has crashed about 5-6 times in the past hour because of this. It only seems to happen when I teleport from my reactor/turbine set up in the overworld, to my base in a rftools world, using the charm of dislocation from DE. It only crashes when the turbine/reactor is on, and not when I travel to another spot in the overworld with my charm. 

I destroyed the turbine mentioned in the crash report, then rebuild it in the same spot, but it still crashes and I don't know why. 

This only happened when I updated to Mekanism version 9.1.0.281 for 1.7

When it crashes, and I reload the world, the reactor is turned off, the fuel injection rate is set back to 0, and the hohraum is placed back into the reactor's gui, loaded with 10 d-t

EDIT: Nevermind, it turns out it's crashing even when the turbine is off. Just to make sure, I broke one of the turbine blocks to unform the multiblock. And after a few minutes it crashed again, still saying that was the error.  After unforming the multiblock it has crashed twice, when I did certain things. Once when I powered on a bigreactor, and once when I hit a floating cobblestone. Both were in the same dimension of the turbine that crashed me, but they were nowhere near it

EDIT: 2 more crashes in a row that all happened before I got on the server, but not right when it started up

EDIT: even when I go back to the older version that used to be stable, it still crashes. 

EDIT: when I place the turbine somewhere else it doesn't crash.

**Comment by aidancbrady** [comment]
Should be fixed in the latest versions
