### ISSUE TITLE
Mekanism BUG with wind turbine...

### ISSUE THREAD

**Issue by EvilGamer** [aidancbrady/Mekanism#4012]
Hello everyone, I'm new here and I need some help...
The issue I have... is  the wind turbine, I have some pictures here to see this, I place the wind turbine on a block without blocks blocking the sky:
![2016-11-24_14 31 48](https://cloud.githubusercontent.com/assets/23725513/20605662/ba38cb26-b253-11e6-8b3c-07c555861404.png)
5 seconds later, this happen:
![2016-11-24_14 32 00](https://cloud.githubusercontent.com/assets/23725513/20605661/ba386596-b253-11e6-8304-9434849978a4.png)
The turbine just face towards back and says that is blocked by a block in the sky...BUT there's NOTHING!
![2016-11-24_14 32 18](https://cloud.githubusercontent.com/assets/23725513/20605663/ba39dfc0-b253-11e6-8c7c-cb0687ffce8c.png)

![2016-11-24_14 56 20](https://cloud.githubusercontent.com/assets/23725513/20606150/4a05d634-b256-11e6-9155-64a588228dca.png)
The wind turbine doesn't crash the game but it just don't collect energy for my machines!
If someone know what is this and what can be doing this, just tell me plz 👍 

(ps: I'm using the modpack from FTB Infinity 1.10.2 and I'm using the latest version of mekanism mod)

**Comment by thommy101** [comment]
The cable breaking crash has an open pull request ( #3967 )
I've tried to reproduce your issue with the wind generator not working, but when trying to replicate your situation it works as supposed. Can you make sure there isn't any block above it (even transparant ones) or try to place it one block further.

**Comment by EvilGamer** [comment]
> The cable breaking crash has an open pull request ( #3967 )
I've tried to reproduce your issue with the wind generator not working, but when trying to replicate your situation it works as supposed. Can you make sure there isn't any block above it (even transparant ones) or try to place it one block further.

I tryed multiples locations and there isn't any transparent block, I sure of it! Thank you anyway ;)

**Comment by HyperBlueCore** [comment]
use a mekansim cable in front of the out put place for a cable which is in front of it and that whould work normally
\

**Comment by HyperBlueCore** [comment]
and when it says the sky is blocked it means the there is something blocking the air from turbines which is the red tree

**Comment by HyperBlueCore** [comment]
and maybe it rotated because you right click it with a wrench

**Comment by EvilGamer** [comment]
> use a mekansim cable in front of the out put place for a cable which is in front of it and that whould work normally

Nop, looks the same :/

> and when it says the sky is blocked it means the there is something blocking the air from turbines which is the red tree

I tryed others locations and biomes and looks the same!

> and maybe it rotated because you right click it with a wrench

I didn't. The wind turbine just rotate for itself and now this isn't just happening with wind turbine, and yes with other machines... they just keep rotate for itselves. Thanks for the help anyway 👍

**Comment by HyperBlueCore** [comment]
i think its caused by walia so can you try to go in a flag large empty space and use only mekanism mod block and items

**Comment by HyperBlueCore** [comment]
or try in another world

**Comment by Ommina** [comment]
See also #3977 for more machine rotation oddities.  The random rotation is not confined to the wind turbine.

**Comment by McSassyK** [comment]
I'm having the same issue with the wind generators in the image shown by the OP. Sometimes when I log onto my single player world, they're all facing the opposite direction away from the cables and saying the sky is blocked. Since they're literally IN the sky, with nothing above or around them, there is definitely nothing blocking them. Sometimes, logging out and then in again will fix it, and they're all turned the right direction again. But sometimes not. I ended up just wrapping cable around both sides so that no matter what way they randomly decide to face, they stay connected.
