### ISSUE TITLE
Server Owner issue - Cant disable locking of machines

### ISSUE THREAD

**Issue by sevdeawesome** [aidancbrady/Mekanism#4013]
Hi, I dont want people on my server to be able to lock their machines with this little thing: http://imgur.com/a/qCzqM
My server is a raiding server so I would like for people to be able to raid machines and things. I cant find the config option to disable locking of machines, or enable unlocking, is there one? 

Thank you!

**Comment by HyperBlueCore** [comment]
well that's now a suggestion I have the same thing and its fine for me I guess

**Comment by sevdeawesome** [comment]
Its not a suggestion at all... Im asking if there is a config option or something I can do to disable this

**Comment by aidancbrady** [comment]
Done in development!

**Comment by sevdeawesome** [comment]
Just curious, was this fixed in the most recent update for 1.7.10?

**Comment by HyperBlueCore** [comment]
i don't know
