### ISSUE TITLE
Cant get steam out of reactor mekanism Version 1.10.2-9.2.0.29

### ISSUE THREAD

**Issue by cutter4ever** [aidancbrady/Mekanism#4014]
Built a fusion reactor. fuels go in, reactor produces and exports the power. So I water cooled it to produce steam. But steam and excess water wont pipe out. pictures show the reactor hook to turbine
![2016-11-25_17 47 04](https://cloud.githubusercontent.com/assets/10689780/20636274/f37e78b0-b337-11e6-8309-f0a15c9222d1.png)
![2016-11-25_17 47 14](https://cloud.githubusercontent.com/assets/10689780/20636278/03cf04be-b338-11e6-96ea-4f5f803d0999.png)
![2016-11-25_17 47 24](https://cloud.githubusercontent.com/assets/10689780/20636280/07503176-b338-11e6-9c9d-1862b10e464b.png)

**Comment by thommy101** [comment]
I don't recognise your version number, but it's certainly not the latest. Can you try with the latest version?

**Comment by aidancbrady** [comment]
This was indeed a bug in an earlier version, please update!
