### ISSUE TITLE
items rotating while they are traveling through pipes

### ISSUE THREAD

**Issue by Mysterizon** [aidancbrady/Mekanism#4015]
The version is Mekanism-1.10.2-9.2.1.295
Forge: 2151 (latest one) 

It doesn't matter which items i put in chest that the Logic Sorter OR Logistical Transporter pulled out and push it into the pipe to send it off to the destination.. while its traveling through the pipe, it was rotating, Clockwise (from north to south).   and one more thing to add.. when I hit "T" to bring up a chatbox so i can type anything... the weird thing is that when i bought up the chatbox, these items in the pipe has stop rotating. it may be the best clue for a solution to fix the issue. 

if you have any questions, please let me know.

**Comment by aidancbrady** [comment]
Item rotation isn't really an issue.

**Comment by Mysterizon** [comment]
actually, i am having trouble trying to find whats the cause of why its rotating while travelling through the pipes. 
I dont know why it's doing that. do you know any solution to my problem?
or know whats the cause.  at this rate, i won't able to use your mod because of the problem.

**Comment by BrianEdmonds** [comment]
Perhaps if you described the problem differently? I honestly have no idea what you mean by items rotating as they travel through pipes. Is it just a visual issue, or is there something functional going on that I'm missing?

**Comment by ktole1999** [comment]
ocd i bet.
