### ISSUE TITLE
Liquid Lithium Production with Chemical Oxidiziers

### ISSUE THREAD

**Issue by freddworld** [aidancbrady/Mekanism#4016]
Hello I have a short question. I have seen some people on youtube playing the bevo tech pack and used chemical oxidizers with lithium dust to produce lithium gas. but i have tested this in the newest version of the modpack and could not do it. in this case my question is, if this is disabled and if there is a way to make it work again ?

Thanks for your Help!

**Comment by thommy101** [comment]
Have you switched its mode by clicking on the arrow in its gui?

**Comment by freddworld** [comment]
how do i get into this gui?

**Comment by aidancbrady** [comment]
Working fine for me.  There's a chance you're using a type of lithium dust that isn't OreDict-registered.

**Comment by thommy101** [comment]
@freddworld Right click it, and click the arrow in the center of your GUI.

**Comment by freddworld** [comment]
Sorry but the only recipe in my oxidizer which is possible , is the recipe for sulfur
