### ISSUE TITLE
Latest update

### ISSUE THREAD

**Issue by richardrickard44** [aidancbrady/Mekanism#4018]
The base universal cable, if you try to remove it, to move it The game crashes 
The Enrichment chamber does not work now.
This is on FTB Infinity Lite 1.10

**Comment by thommy101** [comment]
Please make sure you're using the latest version, build 295.

**Comment by richardrickard44** [comment]
I installed 295 and the cables, now can be moved, but the Enrichment chamber still does not work. Dirty iron dust from crusher will not work in enrichment chamber.

**Comment by jburrows82** [comment]
[Works fine](https://snag.gy/9wGJv6.jpg) in latest build (295), perhaps you should consult the modpack makers to find out whats going on with THEIR pack, since default operation is working as intended. They may have made changes, etc.
