### ISSUE TITLE
[MC1.10.2][FTB Hermitpack 1.40] Crash when breaking a universal cable

### ISSUE THREAD

**Issue by Yusifcalibri** [aidancbrady/Mekanism#4021]
If you attempt to break any universal cable, you will crash when the cable is 9% broken.
[Crash Report](https://github.com/aidancbrady/Mekanism/files/615385/crash-2016-11-28_17.32.57-client.txt)

**Comment by thommy101** [comment]
Please update to the latest version of mekanism.

**Comment by Malkierian** [comment]
Wish I had the power to close issues like this one...
