### ISSUE TITLE
Digital Miner issue in The End

### ISSUE THREAD

**Issue by LordPinkerton** [aidancbrady/Mekanism#4022]
Refer to the linked image for what is occurring. Basically, the Digital Miner's base mining/scanning area is being transposed to y=0 in The End (possibly any void dimension, untested) instead of the area around it and is unable to function as intended.

https://s18.postimg.org/nm59kcerd/2016_11_28_06_07_45.png

**Comment by aidancbrady** [comment]
Not a bug, Digital Miner's scanning range is based on world coordinates and not based on relative space, other than x and z start bounds.
