### ISSUE TITLE
Mekanism Bronze not being detected by other mods

### ISSUE THREAD

**Issue by IBeCrayZ** [aidancbrady/Mekanism#4023]
On 9.2.1.295, 1.10.2

I have a weird issue with bronze where tinkers construct and other mods are not recognizing bronze in the mod however the ingots are still useable, e.g.

http://i.imgur.com/s9sisSi.png
http://i.imgur.com/1vaSxt2.png

this clearly shows the shield can be crafted, (and it can) but the mod shows there is no bronze detected,
Furthermore I can't create molten bronze in the smeltery and the bronze ingot itself won't smelt, while tin and copper from the mod can (not creating bronze). I've tested this with Ic2 bronze and everything works, so I'm posting here. Could it be another mod overwriting some things, or ore dic errors? I also have IE installed if that helps.

**Comment by aidancbrady** [comment]
Not sure why this would be, Mekanism bronze is registered in the OreDictionary just as all its other resources are.
