### ISSUE TITLE
[Request] Custom Enrichment Recipes

### ISSUE THREAD

**Issue by Malkierian** [aidancbrady/Mekanism#4028]
I know there's a need to add dirty dusts and clumps for any ores to be compatible with higher-tier ore processing (and I could request other ores be added to that list, like nickel, aluminum/alumina, chromuim, and others), but at least, for ores that have dusts in other mods, could it be possible to set up the possibility of custom Enrichment Chamber recipes from ore blocks to dusts?  Or is that just not in the cards?  Nickel and chromium each already have dusts in other mods, and other mods also have enhanced processing using those dusts.

**Comment by ThatGamerBlue** [comment]
http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Mekanism_Support

Ctrl+F -> enrichment chamber

**Comment by Malkierian** [comment]
Ahhh.  MineTweaker isn't available for 1.10, but the successor mod, CraftTweaker, is already in my modpack XD.  I don't think I know 1/5 of the mods in the pack I'm using...  I'll see how CraftTweaker works.

**Comment by Malkierian** [comment]
CraftTweaker doesn't have Mekanism support right now because they say Mekanism's not in development anymore, and has lots of issues to work through as-is.  Going to leave this closed, though, as eventually it should sort itself out.  I'll just have to use other machines...

**Comment by ktole1999** [comment]
what do you mean mekanism is not in development anymore?

**Comment by Malkierian** [comment]
I didn't say that, they did.  And that's what I told them, but apparently the latest "real" commit on this repo was 23 days ago.

**Comment by VT-14** [comment]
I would describe it as "on hold" while Aiden is busy at college/university.
