### ISSUE TITLE
injectionrate over98 with computercraft

### ISSUE THREAD

**Issue by Dispelnator** [aidancbrady/Mekanism#4030]
hio
Version:Mekanism-1.7.10-9.1.0.281

I do not know if it is normal but you can use computercraft to exceed the limit (98) from the injection rate.

In the statistic of the reactor stands inj-rate of 354 35.4 mrf
  But there are about 1.56grf
![2016-12-01_11 10 33](https://cloud.githubusercontent.com/assets/24291680/20790036/e005878c-b7b6-11e6-849a-f7ce9b060e91.png)

But with inj-rate 512  only 51.2 mrf

And also that the number can be 7 or 99 normally 6, 8, 10, ...

Sry translated with google

**Comment by aidancbrady** [comment]
Yes, this is normal :)
