### ISSUE TITLE
Quantum Entangloporter not sending fluids

### ISSUE THREAD

**Issue by DuskFalls** [aidancbrady/Mekanism#4031]
As said, when all the faces are configured correctly and it's given power (if it even needs power), the fluids just sit in the pipes and dont travel to the other one

As seen here : http://imgur.com/a/UjP2b

Using the version thats floating around here somewhere, 9.2.1 that fixed the cable breaking crash

**Comment by jburrows82** [comment]
Use the latest RELEASED version (295), it's working fine.

[PULL from Input, Auto-eject to Ouput. See here.](https://snag.gy/N5O1Wq.jpg)
