### ISSUE TITLE
Mekanism 295 | IE 52 | Forge 2171 - Unable to get CCW facing of down

### ISSUE THREAD

**Issue by Alaberti** [aidancbrady/Mekanism#4039]
http://pastebin.com/Vf5FeJ6m

¯\_(ツ)_/¯

https://github.com/BluSunrize/ImmersiveEngineering/issues/1769

**Comment by Alaberti** [comment]
Please help?

**Comment by thommy101** [comment]
This is fixed in one of the latest commits, cant find which.
