### ISSUE TITLE
[1.10.2] Make recipes use chest oredict (chestWood)

### ISSUE THREAD

**Issue by matanui159** [aidancbrady/Mekanism#4042]
I'm not sure if this has been suggested yet. (Looked through issues but couldn't find anything)

I've been playing Mekanism in 1.10.2 with some other mods including Quark which adds multiple types of chest. I've noticed that although most mods are fine with the different chests and accept any chest in their crafting recipes Mekanism only accepts the default oak wood minecraft chest.

Could you change these recipes (Personal Chest, Oredictionifcator, Formulaic Assemblicator) to use the oredict chestWood? Also possibly the sawmill so it can destroy Quark chests.

**Comment by aidancbrady** [comment]
Done!
