### ISSUE TITLE
Gas will not stay in tank when connected to purifier

### ISSUE THREAD

**Issue by DarkestDreams24** [aidancbrady/Mekanism#4043]
Oxygen is instantly emptied out of the tank and disappears into almost nowhere. (purifier is full yet keeps taking). Tested with creative infinite tank aswell and still doesnt hold oxygen
![2016-12-05_23 44 16](https://cloud.githubusercontent.com/assets/24372159/20913348/1405a54e-bb45-11e6-97d9-e488951d2628.png)

**Comment by aidancbrady** [comment]
Can't reproduce
