### ISSUE TITLE
Request: Colour coding for connectors.

### ISSUE THREAD

**Issue by duncanwebb** [aidancbrady/Mekanism#4046]
Would it be possible to colour the connectors on bin, the digital miner to match the machines? For example dark red on the top of a bin and dark blue below it and dark blue for the rear connector of the digital miner. 

I'm using Mekanism-1.10.2-9.2.1.295.

**Comment by ktole1999** [comment]
configurator will color the connecting mek pipe. are you trying to sort items?

**Comment by PJB3005** [comment]
I think he means coding it connector specific so you can have 2 connectors with different colors on a single tile.

**Comment by duncanwebb** [comment]
What I was doing is running a Logistical Transporter from a Digital Miner and put the Bins on top of the pipe, it looked like they were connecting but didn't take the items as the bottom of the bin is an output so I reckon it would be nice to have a connector socket on the bottom of the bin that is coloured dark blue and one on the top that is dark red. The same for the digital miner, back dark blue and the front or top dark red for the auto-pull. I can't get the digital miner's auto-pull to work and as the transporters are not being displayed as connected so I thought it would help to see where to connect to. Does this make it clear?

**Comment by ktole1999** [comment]
so rather than sitting the bins on top of the transporter pipe have them on bottom to coincide with the bin side configuration. I have never used bins so not sure if their sides can be configured. Also not sure if you can use transporter pipe with both input and output on miner. does the mek pipe have to be set to push mode? i am still new to v9.

**Comment by duncanwebb** [comment]
Mek pipes are for fluids so I would think that they cannot connect to the digital miner. There does not seem to be any configuration for a bin (very similar to Jabba Barrels, lots of one type of item) except shift right-clicking them which turns on some lights. I was expecting this mode to be a lock preventing the last item from being pulled out.
