### ISSUE TITLE
Mekanism 1.7.10

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [aidancbrady/Mekanism#4048]
[20:33:13] [Thread-10/ERROR] [Mekanism/Mekanism]: An error occured while connecting to URL 'https://dl.dropbox.com/u/90411166/Mod%20Versions/Mekanism.txt.'

Shows up in the logs while starting the server. I reckon you can easily replace the URL :)

**Comment by ktole1999** [comment]
what version of mek are you using?

**Comment by aidancbrady** [comment]
Dropbox has had some strange instability issues over the past few months, and I'm pretty sure they're gonna be discontinuing their public links service fairly soon. I'm gonna move to directly host the donators and news files from my website fairly soon, that should fix the issues.
