### ISSUE TITLE
Anvil shows mutually exclusive enchantments.

### ISSUE THREAD

**Issue by duncanwebb** [aidancbrady/Mekanism#4049]
I wanted to have a Obsidian Sword with smite and mending. I had two books one with mending and sharpness II and the other with smite IV. Unfortunately I did the Anvil task the wrong way around, first mending+sharpness and then smite (forgetting that they are mutually exclusive), and lost the smite enchant. The Anvil showed the resulting sword had both enchantments, I don't think this happens with other vanilla swords (haven't tested this as I try not to cheat in my survival game).

**Comment by aidancbrady** [comment]
This should be fixed in the latest version
