### ISSUE TITLE
Pipes not connected after server restart

### ISSUE THREAD

**Issue by Xiaminou** [aidancbrady/Mekanism#4051]
It seems this bug is still happening as whenever I restart my server some of mekanism's pipes are no longer connected to other mod's blocks, while some are fine:

![2016-12-07_16 00 19](https://cloud.githubusercontent.com/assets/8670392/20972840/776af498-bc96-11e6-9113-c672cfa031ec.png)

as you can see the pipes on the left are not connecting while the pipes on the right are just fine.
And it's not just pipes, at some point I had a quantum entangloporter connected to a capacitor bank from Ender IO, every time the server would restart I would have to re-tune the capacitor bank to output energy into the quantum entangloporter.

Minecraft: 1.10.2
Forge: 2183
Mods: [list.txt](https://github.com/aidancbrady/Mekanism/files/636909/list.txt)

**Comment by ktole1999** [comment]
by chance is that reactor crossing a chunk border where the missing connections are at?

**Comment by Xiaminou** [comment]
Here it is with the chunk borders, the reactor controller and pipes are indeed in a different chunk.
![2016-12-07_18 28 02](https://cloud.githubusercontent.com/assets/8670392/20978923/03ca2b20-bcab-11e6-95c3-1c3e34bd513c.png)

**Comment by ktole1999** [comment]
so unless all chunks load exactly the same time you will have a multiblock structure that has not formed. major issues. always place multi block structures within 1 chunk

**Comment by Xiaminou** [comment]
Yeah, no, that's not the problem here, other cables have no trouble staying connected and multiblock structures have no problem forming even if they're in multiple chunks.
All multiblock form just fine even if they're not in a single chunk.

**Comment by Shaltear** [comment]
I have exactly the same problem on DNS techpack

**Comment by aidancbrady** [comment]
Should be fixed in 1.11
