### ISSUE TITLE
Several issues with the power distribution mechanic

### ISSUE THREAD

**Issue by Malkierian** [aidancbrady/Mekanism#4054]
Just going to link to this to bring it to the top again.  #3841

Now, one thing aside from that that I noticed that seems to be a little ridiculous:  When inputting energy into an induction matrix or energy cube, using auto-eject (and this is the case through entangloporters, too), the amount drawn and delivered to the matrix changes based SOLELY on the number of cables leading up to it.  So, for instance, I have a matrix that has 3 providers (can't tell yet if that has any effect on input alone).  If I put one creative cube directly onto a port, it provides 98.3 MJ/tick.  If I put ONE cable between them, it drops to 320 kJ/tick.  Put TWO cables between the cube and the port, and suddenly the registered input jumps to 640 kJ/t.  As expected, three cables yields (oddly), 959.99 kJ/tick (odd because it's not exactly 960).

So that's odd enough, right?  Here's where it gets silly: if I merely ATTACH another cable to the line, so it would look like this:
[Imgur](http://i.imgur.com/sTXoMHK.png)
So the cable isn't in the direct chain, IT STILL INCREASES THE TOTAL THROUGHPUT.  By the EXACT same amount as the other three.  WHAT IS GOING ON HERE?!?!

And THEN, if I disable auto-eject and set the cable attached to the cube to extract, it drops down to 32 kJ/t, and it doesn't matter how many cables are in between or attached to the chain.  If I attach another energy cube to the chain, and set it up the same way, the second extraction then adds another 32 kJ/t to the chain.  I am thoroughly confused at this point.

AND, the induction matrix, if you happen to attach one of its output ports to one of its input ports, provides power to itself.  It doesn't seem to make much difference anymore, as it does still supply power to something else on the circuit when it requests it, but it still seems weird.

The other thing is that there's no capability to transfer power from one entangloporter to another.  If I have an induction matrix feeding power to one entangloporter (which is powering my machines), and that QE is attached to another QE (which is receiving items from my miners), the power doesn't get through that second entangloporter to the miners on the other side.  I have to have a QE attached directly to the matrix on that second channel for the miners to get power.  Is this on purpose, and if not, is it possible to fix it so that I don't have to expend another QE just to get power on a secondary channel?

**Comment by PJB3005** [comment]
Yeah there definitely is a limit on the amount of power a single connector can draw from something which seems like a very strict engineering limitation.

**Comment by ktole1999** [comment]
each power transfer cable used increases throughput but that amount. transfer rate is calculated by total nodes not by individual node. this is how Aiden intended.

**Comment by PJB3005** [comment]
Of course, though 32 kJ/t seems a little low since it basically forces you to do stuff like using a QE to get power out a reactor, which just seems weird IMO.

**Comment by ktole1999** [comment]
you just have to be creative in how retrieve power from reactor. will reactor output directly to induction matrix or other high capacity storage?

**Comment by PJB3005** [comment]
Of course, but it just seems counterintuitive.

**Comment by ktole1999** [comment]
its always been like this and always will be. accept it :)
