### ISSUE TITLE
Texture Memory

### ISSUE THREAD

**Issue by Joshwoo70** [aidancbrady/Mekanism#4055]
Congrats.. the mod takes up 20.32% of texture map provided.
[texturemap](https://app.box.com/s/sf4kjj6zuwid44gjotttb7z29dzygfk7)

Some suggestions to compression :
compress the following
> Chemical washer
electronic seperator
fluid tank
electric pump
chemical infuser/oxidiser
logical sorter
metallugic infuser.

Thanks.

**Comment by bookerthegeek** [comment]
Congrats! @Joshwoo70 you are a dick.

Next time don't be one.

**Comment by VT-14** [comment]
1)  "Congrats, you are doing something negative" is an extremely rude way of reporting this issue.

2) This is a duplicate issue of #3920, which was bought up by Mezz, the creator of that texture dump mod.

**Comment by Joshwoo70** [comment]
> "Congrats, you are doing something negative" is an extremely rude way of reporting this issue.

This is a duplicate issue of #3920, which was bought up by Mezz, the creator of that texture dump mod.

THANKS.
Really i closed the issue after i seen the mekanism issue. do you REALLY have to bump it again?!
