### ISSUE TITLE
Mekanism machines can no longer be connected to phantomfaces

### ISSUE THREAD

**Issue by DuskFalls** [aidancbrady/Mekanism#4056]
They used to work, they dont now

Something changed between mekanism 9.2.1-291 and 295 and Actually Additions r75 and r88 to break it

**Comment by thommy101** [comment]
I guess it won't take any power anymore. I personally don't use Actually Additions, but looking at there changelog (and associated commits), they've dropped support for RF energy and fully support Forge Energy (and a couple others).
Mekanism doesn't support Forge Energy at this moment.

**Comment by DuskFalls** [comment]
Still takes power from the phantom energyfaces, its just the standard ones that deposit items into the machines that dont work
