### ISSUE TITLE
Latest build not up to date

### ISSUE THREAD

**Issue by thommy101** [aidancbrady/Mekanism#4059]
The latest build on the mekanism website is based of the master branch. The master branch does not contain all changes of the 1.10 branch, in particular the change with the deploader.

I've compiled one for my modpack and server, but for the rest it's maybe nice to have it up to date from a official channel.

**Comment by wylderhoads1809** [comment]
> The latest build on the mekanism website is based of the master branch. The master branch does not contain all changes of the 1.10 branch, in particular the change with the deploader.

Where can I find this version? I'm still having major issues with this preventing me from playing my world.

**Comment by thommy101** [comment]
Depends on your issue, if it's only the deploader then you can compile from the 1.10 branch yourself, or download a compiled version at issue #4119. There is a by myself compiled version of the 1.10 branch with some fixes.

**Comment by wylderhoads1809** [comment]
Yes, I'm just having issues with the dep loader and MCMultipart where I can't load my world because deploader crashes looking for an old version of MCMultipart.

**Comment by ktole1999** [comment]
1 temp fix is to temp remove mcmultipart mod from mods folder and use the deploader version. unless you can compile as mentioned previously.

**Comment by thommy101** [comment]
Master is up to date with 1.10 since yesterday. 1.10 branch is 15 commits ahead and latest version is sadly still of the master branch. I think a lot of people would like the deploader fix which will prevent a lot of issues for modpack makers and users.

**Comment by thommy101** [comment]
Latest build (301) is up to date! Thank you @aidancbrady!

**Comment by ate0ate** [comment]
I resoundingly echo the above thank you to you, Mr Brady! 🥇
