### ISSUE TITLE
Mod conflicts with EnderIO Alloy Smelter

### ISSUE THREAD

**Issue by kostanakis** [aidancbrady/Mekanism#4060]
Exactly, server randomly crashes with such error: [Error Gist](https://gist.github.com/Bulldog83/4c8608cca5b0f1f8373a87d2555f9afd)

Server doesn't start until backup is restored.
Mekanism v 9.1
Minecraft 1.7.10
Forge 10.13.4.1614

**Comment by aidancbrady** [comment]
A mod is shipping with an outdated IC2 API.
