### ISSUE TITLE
Can't extract steam out of reactor. Mekanism Version 1.10.2-9.2.1.295

### ISSUE THREAD

**Issue by SOL3675** [aidancbrady/Mekanism#4068]
Same as closed issue #4014.
I think it still has the bug or something...
I made water-cooled reactor on my server, but can't extract steam from reactor in any way.
So I tried to build in creative for debug, but no steam extraction. It has steam in reactor's GUI.

![2016-12-17_08 26 56](https://cloud.githubusercontent.com/assets/16431933/21282074/05de2060-c435-11e6-9cc4-975c44f2adcf.png)
No steam extraction

I'm using the modpack called All the Mods V1.50

**Comment by jburrows82** [comment]
Not a bug, it's user error. Configure the port from INPUT to OUTPUT. Also, the reactor pushes steam out. No need to pull. Tested and works fine as seen with attached screenshot. 

![image](https://cloud.githubusercontent.com/assets/8468011/21284752/a1ec13f0-c3f3-11e6-8bc3-d0e7a6d049d6.png)

**Comment by SOL3675** [comment]
Thank you for the response.
I couldn't find the documentation about it. I'll try soon and close this issue.
