### ISSUE TITLE
Using Bins in a Project Bench (from the Project Red mod) can duplicate items.

### ISSUE THREAD

**Issue by dat3ngy** [aidancbrady/Mekanism#4069]
I'll also be sending this to Project Red Bug Tracker about this bug. So basically, as long as you have 2 or more items, if you combine the items and the bin in a Project Bench and shift click the output, the bin will have all of the items you used, but the Project Bench will only use up 1 item. So you can keep doing this bug until you end up with stacks of items. This was done in Minecraft 1.7.10 with Forge 10.13.4.1614. on a server using a custom modpack. You should be able to replicate this glitch by have both Mekanism and Project Red mods installed and using a bin and any 2 or more items in a project bench.

So I start off with a bin and 2 Diamond Blocks
![2016-12-16_22 17 35](https://cloud.githubusercontent.com/assets/24617149/21284312/b63e0cb6-c3dd-11e6-9ac1-8ba2f4426fdc.png)

I put the Diamond Blocks and the Bin in the Project Bench which is suppose to put 2 Diamond Blocks in the Bin, this is normal.
![2016-12-16_22 17 40](https://cloud.githubusercontent.com/assets/24617149/21284318/d42822de-c3dd-11e6-934d-c52792dba465.png)

I shift clicked the output but 1 Diamond Block is still left in the grid, I put the bin back in the crafting grid and now it says it's going to yield 3 Diamond Blocks.
![2016-12-16_22 17 47](https://cloud.githubusercontent.com/assets/24617149/21284336/084622f0-c3de-11e6-9f34-646d53ae5ae1.png)

I placed the bin down, and now I am able to get 3 Diamond Blocks. I started off with 2, then I got 3.
![2016-12-16_22 17 55](https://cloud.githubusercontent.com/assets/24617149/21284358/610dfb9c-c3de-11e6-9c8b-bf495cc3cb09.png)

If more information is required, I'll be happy to help.
P.S. - I was using the Sphax PureBDCraft Resource pack with user submitted patches.

**Comment by AsukaLangleyfag** [comment]
Can confirm, bug is in the Mekanism itself (compiled last version for 1.7.10, same forge version), used Formulaic Assembler to confirm it's not Project Red bug, same result, if you use bin and 3 blocks on the Formulaic Assembler, it puts 3 in the Bin and this leaves 2 blocks inside the machine on the grid, so you can repeat and get 3 more, each time one block less on the bench (works with any amount of blocks). Also, using Project Bench or Formulaic Assembler to pull out the blocks out destroys the Bin and you'll get maximum of 64 blocks.

**Comment by dat3ngy** [comment]
@AsukaLangleyfag Does the Machinist's Workbench from Thermal Expansion also duplicates items?

**Comment by AsukaLangleyfag** [comment]
Oddly, no. You can only put one block at the time. But it's still destroys the bin and it's not the way it should work.

**Comment by aidancbrady** [comment]
Should be fixed in 1.11.
