### ISSUE TITLE
No lasers in Space Block R2

### ISSUE THREAD

**Issue by Insyder28** [aidancbrady/Mekanism#4071]
I recently started playing this modpack called Space Block R2, which runs Mekanism, MekanismTools and MekanismGenerators all v9.1.0.281. In this modpack there aren't any lasers to start a fusion reactor. Is this because of the modpack or is it because there are no lasers in this version?

**Comment by jburrows82** [comment]
What did the modpack author(s) say when you first brought this to their attention?

**Comment by Insyder28** [comment]
I tried to contact them multiple times, but they only responded just now. They have indeed removed the items, and did not mention this in any banned or removed item lists. The problem has been solved.

**Comment by Insyder28** [comment]
I take it there isn't an other way of jumpstarting the reactor? I built it all in survival except for the lasers, and it is quite a hard task to do in a SkyBlock environment, to say the least.

**Comment by Insyder28** [comment]
I looked around on the forums of the modpack authors, they are a group called OhGaming, and I only found threads that said they were disabled in other modpacks by the same authors, and none were saying anything about them being disabled on Space block. I have started a new thread, but no response yet.

**Comment by AsukaLangleyfag** [comment]
Did you checked mekanism.cfg in your minecraft instance folder/config for `B:LaserEnabled=true`
