### ISSUE TITLE
Rendering Bug

### ISSUE THREAD

**Issue by p4di** [aidancbrady/Mekanism#4073]
the basic solar generators are invisible in my inventory, only by hovering over them you get the tooltip text and an indication that they're there. when placed in the world they are visible, however a lot of the mekanism machines have incorrect WAILA descriptions - solar generator says heat generator for example (Idk if that's a WAILA related bug though)

When placed on a TiCon Crafting table the game tries to render the solar generators and causes a crash.

it's game version 1.10.2

**Comment by PJB3005** [comment]
Are you on the very *very* latest version of the mod?

Also, you don't happen to have Optifine installed, correct?

**Comment by p4di** [comment]
optifine is installed, does it cause the problems? I'll post the modlist in a minute

**Comment by p4di** [comment]
Here are two screenshots illustrating the issues. 
Mekanism is on version 1.10.2-9.2.1.295
modlist is below

![2016-12-17_17 36 44](https://cloud.githubusercontent.com/assets/24624556/21288324/514575da-c480-11e6-994f-14da20e2f1ff.png)
![2016-12-17_17 37 22](https://cloud.githubusercontent.com/assets/24624556/21288325/5147d604-c480-11e6-822d-bbf3660d590c.png)

ActuallyAdditions-1.10.2-r84.jar
AdvancedRocketry-1.10.2-1.0.2.jar
ae2stuff-0.6.0.6-mc1.10.2.jar
appliedenergistics2-rv4-alpha-8.jar
Aquaculture-1.10.2-1.4.0.28.jar
Aroma1997Core-1.9.4-1.1.1.1.jar
AutoRegLib-1.0-1.jar
Baubles-1.10.2-1.3.6.jar
bdlib-1.12.2.17-mc1.10.2.jar
BetterAchievements-1.10.2-0.3.2.39.jar
BetterFps-1.3.2.jar
BiomesOPlenty-1.10.2-5.0.0.2109-universal.jar
Bookshelf-1.10.2-1.4.3.338.jar
BrandonsCore-1.10.2-2.1.1.61-universal.jar
Chameleon-1.10-2.2.0.jar
Chisel-MC1.10.2-0.0.7.7.jar
chiselsandbits-12.7.jar
CodeChickenLib-1.10.2-2.4.3.145-universal.jar
CookingForBlockheads_1.10.2-4.2.26.jar
covers-0.4.1.14-mc1.10.2.jar
CraftTweaker-1.10.2-3.0.15.jar
cyberware-1.9.4-1.10.2-beta-0.2.4.jar
Decocraft-2.3.5_1.10.2.jar
deepresonance-1.10-1.3.1.jar
Draconic-Evolution-1.10.2-2.0.3.137-universal.jar
DrawersBits-1.10.2-0.35.jar
EiraMoticons_1.10.2-4.2.4.jar
ElecCore-1.10.2-1.6.345.jar
EnderCore-1.10.2-0.4.1.60-beta.jar
EnderIO-1.10.2-3.0.1.138_beta.jar
endertanks-1.10.0-1.4.8.jar
enderutilities-1.10.2-0.6.5.jar
extrautils2-1.10.2-1.1.1.jar
ExtremeReactors-1.10.2-0.4.5.19.jar
Farseek-1.9.4-2.0.jar
FastLeafDecay-v11.jar
flatcoloredblocks-mc1.10-v4.4.jar
forestry_1.10.2-5.2.16.330.jar
FTBLib-1.10.2-3.1.5.jar
FTBUtilities-1.10.2-3.1.4.jar
gendustry-1.6.4.25-mc1.10.2.jar
GeographiCraft-1.9.4-0.7.6.jar
ic2
iChunUtil-1.10.2-6.1.0.jar
ImmersiveEngineering-0.10-50.jar
industrialcraft-2-2.6.105-ex110.jar
InventoryTweaks-1.61-58.jar
IronBackpacks-1.10.2-2.2.17.jar
ironchest-1.10.2-7.0.11.797.jar
jefb_1.10.2-1.0.4.jar
jei_1.10.2-3.13.6.387.jar
journeymap-1.10.2-5.3.1.jar
JustEnoughResources-1.10.2-0.5.8.98.jar
LibVulpes-1.10.2-0.1.10-universal.jar
Liste
LootBags-1.10.2-2.2.2.jar
magneticraft-1.0.2-release.jar
Mantle-1.10.2-1.1.2.jar
mcjtylib-1.10-2.2.0.jar
Mekanism-1.10.2-9.2.1.295.jar
MekanismGenerators-1.10.2-9.2.1.295.jar
MekanismTools-1.10.2-9.2.1.295.jar
ModTweaker2-2.0.6.jar
morebees-1.10.2-1.1.5.jar
Morpheus-1.10.2-3.1.12.jar
MouseTweaks-2.6.4-mc1.10.2.jar
MTLib-1.0.0.jar
multistorage-1.10.0-1.2.10.jar
netherportalfix-mc1.9.4-4.0.1.jar
omlib-1.10.2-3.0.0-28.jar
OpenComputers-MC1.10.2-1.6.0.4.jar
openmodularturrets-1.10.2-3.0.0-21.jar
OptiFine_1.10.2_HD_U_D4.jar
Pam's HarvestCraft 1.9.4-1.10.2h.jar
platforms-1.10.0-1.2.6.jar
ProjectE-1.10.2-PE1.1.0B.jar
Psi-r1.0-42.jar
PSIonicUpgrades-r1.15.jar
Railcraft_1.10.2-10.0.1.jar
refinedstorage-1.2.8.jar
rftools-1.10-5.62.jar
rftoolsctrl-1.10-1.5.2.jar
rftoolsdim-1.10-4.45.jar
RoguelikeDungeons-1.10.2-1.5.4.jar
RTG-1.10.2-4.1.1.8.jar
ShadowMC-1.10.2-3.6.0.jar
shetiphiancore-1.10.0-3.3.5.jar
simplegenerators-1.10.2-0.10.5b.jar
simpleretrogen-1.10-4.0.1+8.jar
SleepingBag-1.10.2-1.4.0.jar
SoulShards-TOW-1.10.2-2.6.6-46.jar
StorageDrawers-1.10.2-3.5.5.jar
Streams-1.9.4-0.3.jar
Substratum-1.10.2-1.8.2.1.jar
SuperCircuitMaker-1.0.4.jar
TConstruct-1.10.2-2.5.6b.jar
thutcore-3.10.1.jar
thuttech-4.0.10.jar
Tinkers' Addons-1.10.x-1.0.3.jar
tinkersdefense-1.4.0.4a.jar
TinkerToolLeveling-1.10.2-1.0.1.jar
TombManyGraves-1.10.2-2.1.13.jar
UniDict-1.10.2-2.4.jar
valkyrielib-1.10.2-0.10.5e.jar
Waila-1.7.0-B3_1.9.4.jar
WailaHarvestability-mc1.10.2-1.1.9.jar
WanionLib-1.10.2-1.2.jar
Wawla-1.10.2-2.3.1.213.jar
weaponcaseloot-1.10.2-4.0.1.jar
zerocore-1.10.2-0.0.8.2.jar

**Comment by PJB3005** [comment]
Yeah optifine has a tendency to cause issues, might want to try without to see if that changes anything.

On the WAILA thing, I just remembered that yes that wasn't fixed, I was confusing it with something else for a moment

**Comment by thommy101** [comment]
You can prevent the TiCon rendering crash by disabling rendering of items on toolstations.
It's found in config/tconstruct.cfg clientside S:renderInventoryInWorld, set that one to false to disable rendering (and the crashes).

The incorrect display is a combination of Mekanism and WAILA, there are a couple "reborn" versions of WAILA which fix displaying it.
