### ISSUE TITLE
Duplicate Bug with Energized Smelter and ExtraPlanets Ore

### ISSUE THREAD

**Issue by Markezzz** [aidancbrady/Mekanism#4076]
### ---Issue Report---

**Have you checked Closed Issues (if applicable): Yes
### Description of Issue
I found a duplication bug on our server with the Mekanism Energized Smelter and the Ores from Extra Planets. So if i let smelt the ores with the Energized Smelter i get the ingots but it wont consume the ore.

### Steps to Reproduce Issue
1. Place the Ore in the inputslot
2. The Energized Smelter smelt the ore to ingot
3. After smelting you have the ore in the inputslot and the ingot in the outputslot. The ore is not consumed. This way you can have an infinite production.

**Crash log/Log (if applicable): Their was no crash or a error in the client and server log.

**Version of Mod using: Extra Planets 3.7.6 and Mekanism 9.1.0.281

**Comment by aidancbrady** [comment]
Report this to ExtraPlanets, this is something funky on their end
