### ISSUE TITLE
[MC 1.10.2] [Mekanism 9.2.1] Digital Miner Configuration

### ISSUE THREAD

**Issue by 1146949** [aidancbrady/Mekanism#4077]
When the digital miner energy buffer isn't full, you are not able to modify/view the configuration.
Not sure if relevant but was using RF power.

EDIT : After further testing power preference are irrelevant. It affects the filters (aka Configuration button) part of the GUI. When the Digital Miner has less than 100% in it's energy storage and you click on the Configuration button the whole GUI close. As soon as the energy stored reach 100% you are once again able to open the GUI window properly.

**Comment by aidancbrady** [comment]
Fixed!
