### ISSUE TITLE
I cannot open a chest with a stair on top of it

### ISSUE THREAD

**Issue by positron** [aidancbrady/Mekanism#4078]
I just installed mekanism on my existing world.

I have a storage wall with double chests embedded in the wall lengthwise. Above each one is a stairs so I can put a sign on it. Here is [an example](http://i.imgur.com/zf5Qn7R.png) someone else did but with glass instead of stairs.

I *can* open chests if the stairs above them is backwards *and* upside down. i.e. if the it is shaped like this (`*` is stairs and `-` is chest).
```
    ****
      **
--------
--------
```

I cannot open the chest if the stairs is like this.
```
      **
    ****
--------
--------
```

This is different than vanilla minecraft.

Minecraft: 1.9.4
Mekanism: 1.9.4-9.1.0.282
Forge: 1.9.4-12.17.0.1976
MCMultiPart: 1.3.0
No other mods

**Comment by VT-14** [comment]
That is a change introduced by Forge itself.  Stairs (and slabs?) are now considered solid on the sides that they are full blocks.  The useful thing is that you can now put torches on them.

Personally, I hate the change.  It might be a Vanilla 'bug' but it is used for decoration all the time.  I don't think Forge bothered to fix Piston Translocation or Redstone Quasi-connectivity (BUD switches), so this is an annoying double standard.

**Comment by positron** [comment]
Wow, thanks for the info @VT-14
