### ISSUE TITLE
[MC 1.10.2; Mek 9.2.1] Seismic Reader only detecting air

### ISSUE THREAD

**Issue by SeamusDonohue** [aidancbrady/Mekanism#4081]
Seismic Reader only reports detecting air, despite fact that Seismic Vibrator is sitting on solid ground (dirt or grass, specifically).  See attached screenshot.

Reproduction steps:
1) Start new Singleplayer game: Mostly default options, but turn on Cheats and Bonus Chest.
2) Switch to Peaceful Mode.  (If a cave or roofed forest happens to be nearby, you don't want to be ambushed by a Creeper during testing.)
3) Cheat-spawn for yourself a Seismic Reader, Seismic Vibrator, and Creative Energy Cube.
4) Place the Creative Energy Cube and Seismic Vibrator on the ground such that the Creative Energy Cube supplies energy to the Seismic Vibrator.  Make sure the Seismic Vibrator is animating.
5) Hold the Seismic Reader in-hand and right-click to use the Seismic Reader.  Notice that only Air is reported, despite knowing that you have at least grass/dirt under the Seismic Vibrator.
6) Click the up and down buttons in the Seismic Reader interface; this presumably changes the elevation being scanned, but only Air is reported.

Singleplayer game - Survival Mode with cheats enabled.
Feed The Beast Infinity Lite 1.10
Based on Minecraft 1.10.2
forge-12.18.2.2166
Mekanism 9.2.1
Mac OS 10.10.5

I've disabled only "Soul Shards: The Old Ways" from this modpack.

![2016-12-21_15 16 28](https://cloud.githubusercontent.com/assets/24704643/21405315/682c3d4a-c793-11e6-9abb-0c18b70c8602.png)

**Comment by duncanwebb** [comment]
I found this happening too...

**Comment by aidancbrady** [comment]
Fixed in dev
