### ISSUE TITLE
Server crash trying to filter osmium ore with digital miner

### ISSUE THREAD

**Issue by positron** [aidancbrady/Mekanism#4082]
Steps to reproduce:

- Place Digital Miner in creative mode
- Right click on machine
- Hit Config button
- New Filter
- Material
- Put Osmium Ore in both left and right slot
- Hit Save
- Server crashes and client disconnects!

[Here is the stack trace](https://gist.github.com/positron/990d9ec6f59b89962329be64f9a95cce).

I realize that's probably not the correct way to use it, but crashing the entire server which takes a minute to start up again is not optimal :)

Minecraft: 1.9.4
Mekanism: 1.9.4-9.1.0.282
Forge: 1.9.4-12.17.0.1976
MCMultiPart: 1.3.0
No other mods

**Comment by TehStoneMan** [comment]
OK, first off, you are trying to replace the mined ore with itself. The left slot is what ore to mine, the right slot is the optional block to replace it with.
Looking at your log, my best guess is that the server is crashing trying to save an invalid filter config. Most likely the code is missing a check for this situation.

**Comment by ktole1999** [comment]
if you realized it was not the correct way to use the machine then why do it? If you are doing it for bug testing then fine.

**Comment by positron** [comment]
I didn't realize the first time until it crashed the server. I reproduced and reported here because I figured others might have the same experience.

**Comment by aidancbrady** [comment]
Should be fixed in latest release
