### ISSUE TITLE
Chemical Crystallizer I/O

### ISSUE THREAD

**Issue by AlexSargon** [aidancbrady/Mekanism#4085]
Hello, and Merry Christmas! I'm running Technic's 1.7.10 pack, which (according to my mods list in-game) is running 9.1.1 of Mekanism. I've got the 5x build set up and running almost flawlessly. The first time I built it, I had the leftover slurry issue that others have mentioned in other posts. Somehow, that got fixed with my second build; however, now I'm having problems with input from the washer/output to the injector.

It appears that the crystallizer thinks the input and output are on the same side. Since it has the fixed ports on the two sides, at first when I placed it, it wouldn't accept the slurry (I had it piping in from the right instead of the left. Flipping the input/output in the settings didn't help, so I rotated it 180. It accepted the gas! But... why won't it send the crystals to the injector? I flipped it around 180 again, and the crystals shot over to the injector, but it wouldn't accept more gas, until I flipped it back around again.

For the record, the entire rest of my build is using EnderIO power, gas, fluid and item conduits, which work excellently with your machines.

I'm also confused by the version number, as your site's download page lists the latest build as being 9.1.0.281 for 1.7.10 and minecraft says I'm running 9.1.1.

Otherwise, I completely love this mod! I'm just trying to figure out how to filter my ME system exporting only the ores that your processing will accept, as well as how to convert ores from other mods into ores your machines will process (i.e. Nether Ores and Galacticraft).

Thanks for all your hard work!

**Comment by rdunham3** [comment]
The three 5x processing machines have "in" on the left and "out" on the right (non-configurable) when you place them. Plan your facility layout accordingly or rotate them as needed **_before_** starting them up, or you'll need the eyedropper to suck out anything that gunks up the system.

The 2x through 4x machines have in and out configurable so they're usually easier to place and more flexible in facility layouts, but every once in a while the eyedropper will be useful for them too.  In particular I've had a PRC (not an ore processor, but a great part of Mekanism's repertoire) somehow backflow ethylene into an electrolytic separator before on multiple occasions so now I always have a short tube between them with one end of the tube configured to limit that particular flow one-way.

**Comment by AlexSargon** [comment]
Thanks! I will remember the eyedropper if I have problems in the future, though I am planning my layouts way more carefully. I'm trying to keep my 5x build within a single chunk, which can be difficult with the large evaporation plant, but it makes it easier to keep a chunk loader in place without having power issues.
