### ISSUE TITLE
Can't even Download the Mod

### ISSUE THREAD

**Issue by ProxyPlayerHD** [aidancbrady/Mekanism#4087]
The Title says it,
Because Mekanism does not have Mirror Downloads or is not on Curse in case the Normal Downloads don't work it makes it quite hard to get it in case that one Download Option falls Flat.

For some reason i can't Download them, the adf.ly link just sits there (Site is Empty as Always) until i can Skip to the Download, but when i click it a new Tab opens up and Closes again Instantly.
Nothing Happens except that.

**Comment by VT-14** [comment]
You can:
A) Download a modpack like Hermitpack, which I think has the current Mekanism version.
B) Copy the links from the download page and remove the adf.ly redirect part.

**Comment by ProxyPlayerHD** [comment]
B worked. thanks.
(still wonder why it isn't on Curse Directly tho)

**Comment by 61352151511** [comment]
Mekanism has adfly links different from most I see. When you click on the mod to download it brings you to a URL like http://adf.ly/1140958/dl.aidancbrady.com/download?u=http%3A%2F%2Faidancbrady.com%2Fwp-content%2Fuploads%2Fmekanism%2F295-recommended%2FMekanism-1.10.2-9.2.1.295.jar&wiki=http%3A%2F%2Fwiki.aidancbrady.com

All you have to do is delete the http://adf.ly/1140958/ from the URL and the remaining link will bring you to the actual download.

**Comment by ProxyPlayerHD** [comment]
uhh, yes.
maybe you missed the Part where i said that Option B worked.
i have the mod already.

**Comment by VT-14** [comment]
The mod is not on Curse yet because Aiden wanted to get a few more bug releases out before he uploaded there.

He then got busy with University/College and hasn't been able to update the mod very much.
