### ISSUE TITLE
[BUG]Managing Resistive Heater with OpenComputer

### ISSUE THREAD

**Issue by Natchesprout** [aidancbrady/Mekanism#4088]
If you manage resistive heater with opencomputer, the Energy usage will be 0 if you right click on, and the induction matrix will not output the correct amount of RF(max ~= 25000 even if i put 50000, and i have elite induction provider) and the heat produce will be higher  than if we put 50000Rf manually, and if in the thermoelectric water boiler there no more water, it will increase heat a lot( i have a boiler at 2.2MK, that's too much i think? no)
Sorry if it's a little difficult to understand, English is not my mother language

**Comment by aidancbrady** [comment]
Fixed, thank you!
