### ISSUE TITLE
[1.10.2] [9.2.1.295] Logistical transporter inserting when set to none

### ISSUE THREAD

**Issue by addrever** [aidancbrady/Mekanism#4089]
Hello,

I set a logistical transport to none as it was connected to the bottom of an iron chest.  I then proceeded to give a default color in my logistical sorter.  I also put a restrictive transporter on the top of the chest so that it goes there if nothing else is available ( I am using bins ).  It colored the items green ( the color of my default sort direction ) and watched it proceed to go into the chest from the bottom ( transport set to none on the bottom with a restrictive transporter on top ).

The intended action would have been to go up to the next row of bins and into the chest from the top.  I have attached screenshots of my setup.  Please let me know if you need anything else.

![2016-12-26_11 11 42](https://cloud.githubusercontent.com/assets/190461/21484223/21afddcc-cb5d-11e6-8293-50ed33c69c20.png)
![2016-12-26_11 18 42](https://cloud.githubusercontent.com/assets/190461/21484224/21b29c24-cb5d-11e6-839e-9366373de960.png)
![2016-12-26_11 18 48](https://cloud.githubusercontent.com/assets/190461/21484225/21b2eef4-cb5d-11e6-97e1-8f80f2b683bb.png)

**Comment by aidancbrady** [comment]
Fixed in dev.
