### ISSUE TITLE
Digital miner - "running, ready, to mine: 0", not able to mine anything. 

### ISSUE THREAD

**Issue by dragonslife** [aidancbrady/Mekanism#4091]
Hello, 

For me and the wife I created a private pack for us to play, however I've ran into an issue with the Digital Miner for Mekanism and I'm hoping someone can assist me into solving this issue. 

I'm not able to get my digital miner to mine. It always says "running, ready, to mine: 0".

See these images: http://imgur.com/a/XRxKh

So far I haven't been able to solve this problem. As a test, I made a new instance of minecraft with just forge-1.7.10-10.13.4.1558-1.7.10-universal and mekanism. No other mods are installed and it still has the same issue  I'm running Minecraft 1.7.10 and I've tried both version 8.1.9.265 and 9.1.0.281 for Mekanism. Both seem to have the same issue.

Does anyone have any idea how I can solve this problem?

**Comment by addrever** [comment]
Try changing Min: on the digital miner to 0 instead of 255.

**Comment by dragonslife** [comment]
Oh my god... I can't believe I was that stupid not to read that properly.... Mistake of not actually reading well enough I guess.. Thanks for giving me the answer and apologies for my stupidity.

**Comment by addrever** [comment]
All good.  It's not stupid if you need help.  The only dumb questions are questions not asked imho.
