### ISSUE TITLE
Unable to pipe fluids into IC2 machines

### ISSUE THREAD

**Issue by todofixthis** [aidancbrady/Mekanism#4092]
Running Mekanism 9.2.1 and IC2 2.6.138-ex110 on Minecraft 1.10.2 and Forge 12.18.3.2185.

1. Place an IC2 machine that accepts fluids (e.g., Fluid/Solid Canning Machine).
2. Place a Mechanical Pipe next to the IC2 machine.
  - There is no way (that I can determine) to connect the pipe to the IC2 machine, let alone pipe fluids into the machine.

Able to reproduce with the following IC2 machines:
- Fluid/Solid Canning Machine
- Fluid Distributor
- Fluid Regulator

<img width="1440" alt="Basic Mechanical Pipe next to Fluid/Solid Canning Machine" src="https://cloud.githubusercontent.com/assets/202040/21487260/1280ac1a-cb93-11e6-8549-7fdfe5515749.png">

**Comment by todofixthis** [comment]
There is a workaround for this issue:

1. Place a Basic Fluid Tank next to the IC2 machine:
     <img width="848" alt="Basic Fluid Tank next to Fluid/Solid Canning Machine" src="https://cloud.githubusercontent.com/assets/202040/21487334/7c36ec5e-cb94-11e6-95fe-6e670fb08f0f.png">

2. Install a Fluid Pulling Upgrade into the IC2 machine:
    <img width="679" alt="Fluid/Solid Canning Machine interface showing Fluid Pulling Upgrade installed" src="https://cloud.githubusercontent.com/assets/202040/21487345/a30c6c78-cb94-11e6-812e-dd752aa910e8.png">

**Comment by aidancbrady** [comment]
Not on my end, IC2 is doing something funky with their fluid management.
