### ISSUE TITLE
Upgrading Tank (1.10.2) No OpenGL

### ISSUE THREAD

**Issue by hasezoey** [aidancbrady/Mekanism#4095]
Error:
Description: Tesselating block in world

java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glPushMatrix(GL11.java:2592)
	at net.minecraft.client.renderer.GlStateManager.func_179094_E(GlStateManager.java:623)
	at mekanism.client.render.item.BakedCustomItemModel.func_188616_a(BakedCustomItemModel.java:434)
	at slimeknights.tconstruct.shared.client.BakedColoredItemModel.<init>(BakedColoredItemModel.java:52)
	at slimeknights.tconstruct.library.client.model.ModelHelper.getBakedModelForItem(ModelHelper.java:69)
	at slimeknights.tconstruct.shared.tileentity.TileTable.getTableItem(TileTable.java:110)
	at slimeknights.tconstruct.tools.common.tileentity.TileCraftingStation.setInventoryDisplay(TileCraftingStation.java:48)
	at slimeknights.tconstruct.shared.tileentity.TileTable.writeExtendedBlockState(TileTable.java:72)
	at slimeknights.tconstruct.shared.block.BlockTable.getExtendedState(BlockTable.java:109)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at codechicken.lib.render.block.CCExtendedBlockRendererDispatcher.func_175018_a(CCExtendedBlockRendererDispatcher.java:53)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:290)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
	at java.lang.Thread.run(Thread.java:745)

Installed Mods:
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJA	appliedenergistics2-core{rv4-alpha-9} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.0.178-universal.jar) 
	UCHIJA	IC2{2.6.128-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.128-ex110.jar) 
	UCHIJA	advanced_solar_panels{4.0.4} [Advanced Solar Panels] (Advanced Solar Panels-4.0.4.jar) 
	UCHIJA	infinitylib{1.10.2-0.3.0} [InfinityLib] (infinitylib-0.3.0.jar) 
	UCHIJA	agricraft{2.0.0-i0.3.0-a3} [AgriCraft] (agricraft-2.0.0-i0.3.0-a3.jar) 
	UCHIJA	appliedenergistics2{rv4-alpha-9} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-9.jar) 
	UCHIJA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCHIJA	JEI{3.13.6.387} [Just Enough Items] (jei_1.10.2-3.13.6.387.jar) 
	UCHIJA	BloodMagic{1.9.4-2.1.0-69} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-69.jar) 
	UCHIJA	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCHIJA	CodeChickenLib{2.5.0.178} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.0.178-universal.jar) 
	UCHIJA	CodeChickenCore{2.4.0.100} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.0.100-universal.jar) 
	UCHIJA	ChickenChunks{2.2.0.52} [ChickenChunks] (ChickenChunks-1.10.2-2.2.0.52-universal.jar) 
	UCHIJA	chisel{MC1.10.2-0.0.7.7} [Chisel] (Chisel-MC1.10.2-0.0.7.7.jar) 
	UCHIJA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.6.1_1.10.2.jar) 
	UCHIJA	props{2.3.6.1} [Decocraft] (Decocraft-2.3.6.1_1.10.2.jar) 
	UCHIJA	endercore{1.10.2-0.4.1.61-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.61-beta.jar) 
	UCHIJA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJA	EnderIO{1.10.2-3.0.1.144_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.144_beta.jar) 
	UCHIJA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.1.3a.jar) 
	UCHIJA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJA	FlatBedrockx{1.2.1} [FlatBedrock Xplosion's Edition] (FlatBedrock-1.2.1_1.9.4.jar) 
	UCHIJA	ichunutil{6.1.0} [iChunUtil] (iChunUtil-1.10.2-6.1.0.jar) 
	UCHIJA	mantle{1.10.2-1.1.3.199} [Mantle] (Mantle-1.10.2-1.1.3.jar) 
	UCHIJA	tconstruct{1.10.2-2.6.1.464} [Tinkers' Construct] (TConstruct-1.10.2-2.6.1.jar) 
	UCHIJA	immersiveengineering{0.10-53} [Immersive Engineering] (ImmersiveEngineering-0.10-53.jar) 
	UCHIJA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJA	journeymap{1.10.2-5.3.2} [JourneyMap] (journeymap-1.10.2-5.3.2.jar) 
	UCHIJA	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	UCHIJA	malisiscore{1.10.2-4.2.9} [MalisisCore] (malisiscore-1.10.2-4.2.9.jar) 
	UCHIJA	malisisdoors{1.10.2-5.1.6} [MalisisDoors] (malisisdoors-1.10.2-5.1.6.jar) 
	UCHIJA	mcmultipart{2.0.0_88} [MCMultiPart] (MCMultiPart-experimental-2.0.0_88-universal.jar) 
	UCHIJA	Mekanism{9.2.1} [Mekanism] (Mekanism-1.10.2-9.2.1.295.jar) 
	UCHIJA	MekanismGenerators{9.2.1} [MekanismGenerators] (MekanismGenerators-1.10.2-9.2.1.295.jar) 
	UCHIJA	MekanismTools{9.2.1} [MekanismTools] (MekanismTools-1.10.2-9.2.1.295.jar) 
	UCHIJA	modularforcefieldsystem{2.5.0} [Modular ForceField System] (MFFS-1.10.2-3.0.0.0_1.10_655de1f.jar) 
	UCHIJA	testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar) 
	UCHIJA	mobdismemberment{6.0.0} [MobDismemberment] (MobDismemberment-1.10.2-6.0.0.jar) 
	UCHIJA	Morpheus{1.10.2-3.1.13} [Morpheus] (Morpheus-1.10.2-3.1.13.jar) 
	UCHIJA	omlib{1.10.2-3.0.0-37} [OMLib] (omlib-1.10.2-3.0.0-37.jar) 
	UCHIJA	openmodularturrets{1.10.2-3.0.0-42} [Open Modular Turrets] (openmodularturrets-1.10.2-3.0.0-42.jar) 
	UCHIJA	ProjectE{1.10.2-PE1.1.1B} [ProjectE] (ProjectE-1.10.2-PE1.1.1B.jar) 
	UCHIJA	StorageDrawers{1.10.2-3.5.15} [Storage Drawers] (StorageDrawers-1.10.2-3.5.15.jar) 
	UCHIJA	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	UCHIJA	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	UCHIJA	WorldEditCuiFe{1.0.2} [WorldEdit CUI Forge Edition] (WorldEditCuiFe-v1.0.4-mf-1.10.2-12.18.2.2125.jar) 

PS: Im Playing on my loacal Server with a Friend and when i will try to Upgrade the Tank i get the Error (when i placed the last Item in the crafting grid...( Used a Tinkers Craftingtable)).
And the Tanks are not Displayed in JEI.

**Comment by thommy101** [comment]
You're having a conflict between Mekanism and Tinkers, currently no fix, but there is a workaround. You can disable the display of crafting table items in Tinkers. 
I'm currently not near a minecraft install to check for the exact naming, but it's quite easy to find in the config.

**Comment by hasezoey** [comment]
Thanks, i must trun the renderInventoryInWorld to false by the Client...
