### ISSUE TITLE
Turbine multiblock crash - Size

### ISSUE THREAD

**Issue by Rudolpher** [aidancbrady/Mekanism#4096]
[Crash log](http://pastebin.com/VvP2fi7Q)

Building turbine multiblock, 17x17xUnknown, 20-25ish height. Been trying to find documentation on max size but failed to find a definitive answer so decided to find out.Think I found and passed it? ;-)
If you have a definitive limit, maybe add it to the [Wiki](http://wiki.aidancbrady.com/wiki/Turbine)?

Crash happened when I closed the gap from base turbine casing up to vents filling the room around rotary complex.

**Comment by thommy101** [comment]
It's not directly stated in the wiki, but the first comment says something about maximum (useful) size is 11*11*18. I remember something about maximum for all multiblock structures of Mekanism which is 18*18*18. It's also recommended to place multiblock structures within chunk boundaries which tend to give you less hassle.

**Comment by PWTordenskiold** [comment]
Yes. I decided to ignore that comment as I seem to remember going past that limit(11x11x18) in 1.7.10. I'm guessing it was 18x18x18(How do you place 18x18 inside a 16x16 chunk?). 
Either ways it should probably not cause a crash?

**Comment by thommy101** [comment]
Theoretical limit (18x18) and practical limit (within chunks). I agree it should not crash.

**Comment by ktole1999** [comment]
as with any multiblock structure. just because you can build it that size doesnt mean you should. just because you did in previous version doesnt mean that will work in new version. just because other mod multiblocks work doesnt mean this can. regardless of documentation use common sense for game stability.

**Comment by aidancbrady** [comment]
Shouldn't be happening anymore!
