### ISSUE TITLE
Turbine multiblock crash - Universal cable Push on port

### ISSUE THREAD

**Issue by PWTordenskiold** [aidancbrady/Mekanism#4097]
Setting Universal cable to Push configuration on active turbine port with another port in Pull on same cable [causes a crash](http://pastebin.com/x5rEZn3u), same on [relog](http://pastebin.com/jYYJUvMJ). Was going to set it to None for a test with RFTools Power monitor as it was showing odd RF values with 2 active Pull connections on ports.

**Comment by ThatGamerBlue** [comment]
Fixed by #4101 - waiting for pull
