### ISSUE TITLE
[1.10.2-9.2.1.295] Digital Miner Disappearing when dimension is unloaded

### ISSUE THREAD

**Issue by Jimmacle** [aidancbrady/Mekanism#4111]
I'm seeing this issue repeatedly in my single player world. It seems to happen when the dimension the miner is in is unloaded e.g. I took a trip to the Nether and End and the miner disappeared from my overworld base both times. I can do more testing if necessary, just let me know what information you need. This has happened 2 or 3 times in the past couple days so I shouldn't have trouble reproducing it.

**Comment by oryfoxer7410** [comment]
Experiencing same behavior.

**Comment by Utildayael** [comment]
Same issue in MP. Not fun.

**Comment by ThatGamerBlue** [comment]
Logs? Reproduced in mek only environment?

**Comment by thommy101** [comment]
Duplicate of #3718
