### ISSUE TITLE
[1.10.2] Digital Miner not visible by all players

### ISSUE THREAD

**Issue by oryfoxer7410** [aidancbrady/Mekanism#4114]
Here's the steps to reproduce

2 Players in 1 area. 

Player A - place the digital miner. Player B - cannot see the digital miner
Player B - place the digital miner. Player A - cannot see the digital miner

A quit/rejoin OR place another block in the effect area (where the digital miner is) will show the digital miner for both players. 

Also, when breaking digital miner, players do not always see the ground item it produces. The 2 seem related, but if not, I can open a separate issue.

**Comment by ktole1999** [comment]
that sounds like a client sync issue but i could be wrong.

**Comment by aidancbrady** [comment]
Yeah, sounds like a client sync issue.  Did some testing and was unable to reproduce.
