### ISSUE TITLE
[Suggestion] Replace MC Multipart with Forge Multipart

### ISSUE THREAD

**Issue by Ushupiuck** [aidancbrady/Mekanism#4115]
As the title reads. you might think of me as dumb for this, but actually, ForgeMultipart for 1.10.2 is out! thus, that's what this used before... [check it out here, in the chickenbones downloads.](http://chickenbones.net/Pages/links.html)
thanks for reading and keep up the good work!

**Comment by VT-14** [comment]
I checked the link.  It's under "Latest" but is not under "Recommended" so I assume it's in alpha or beta still.

It's also looks like a separate mod and isn't actually associated with Forge, so it's on the same ground as MCMultipart.  In fact, MCMultipart was going to be merged into Forge a few months ago, but that was cancelled for some reason.

Everyone who is using multipart stuff is already using MCMultipart, so I don't see any reason to switch at this point.
