### ISSUE TITLE
[1.10.2] Universal Cables

### ISSUE THREAD

**Issue by oryfoxer7410** [aidancbrady/Mekanism#4116]
Issues with power transfer between Clockwork Engine from Forestry with universal cables. This issue shows up with other mods also.

**Comment by roboderpy** [comment]
Confirmed. Universal Cables connects to RF based machinery, but they can't receive any energy from RF storages, only transmit energy to them.
![2017-01-03_10 37 54](https://cloud.githubusercontent.com/assets/6339511/21599548/d48e21da-d1a0-11e6-94a5-7e64e7c75a63.png)
![2017-01-03_10 38 10](https://cloud.githubusercontent.com/assets/6339511/21599547/d48e0434-d1a0-11e6-98e3-fef129ac2608.png)
![2017-01-03_10 38 43](https://cloud.githubusercontent.com/assets/6339511/21599549/d48e9d54-d1a0-11e6-9487-ea86de70c756.png)

**Comment by ktole1999** [comment]
versions/pack used?

**Comment by roboderpy** [comment]
Latest Mekanism version (9.2.1.295), Not a modpack.

**Comment by roboderpy** [comment]
Additional info - Energy Cubes *can* transmit and receive RF energy directly from RF generators, capacitor banks, etc.

**Comment by roboderpy** [comment]
Installed Tesla API. Now i got this:
![2017-01-04_20 27 03](https://cloud.githubusercontent.com/assets/6339511/21643674/35b6a060-d2bc-11e6-9d55-cbcbcbd0af70.png)
![2017-01-04_20 27 31](https://cloud.githubusercontent.com/assets/6339511/21643675/35bb96f6-d2bc-11e6-86fd-869f9980e24b.png)
Universal Cables can't transmit energy to RF machinery, but they now can receive energy from them.

**Comment by thommy101** [comment]
Also took a look at this one and found the culprit. Mekanism doesn't follow the Tesla guidelines regarding to sending and receiving power.

From the standard page of the Tesla github:
Power sources are responsible for pushing power to nearby machines. Machines and wires should NOT pull power from other sources. 

Mekanism cables currently look for energy providers (TeslaProducer capability, IEnergyProvider RF, IEnergySource EU and own CableOutputter capability). It should look for energy consumers and push the energy towards them.
Current situation is that producers (like a Capacitor Bank) pushes power into a universal cable, the cable pulls power from the Capacitor Bank (thus receiving twice every tick). The cable doesn't output to a consumer (like a Power Buffer) and the consumer expects the cable to push it to it.

This requires a rewrite of how energy is handled in Mekanism. Cables should not pull, it should be pushed in and it should push not pulled out.

**Comment by ThatGamerBlue** [comment]
@thommy101 you should just steal mekanism ;p

**Comment by thommy101** [comment]
@ThatGamerBlue I'm not gonna steal it ;) Maybe help with a rewrite which I may or may not already have plans for.
First getting through the semester and then I'll take a look on if it's possible at all (time, licenses, permission of Aidan, and did I already mention time?)

Already took a look to update to 1.11, but there's a lot of stuff which is deprecated in the latest version of 1.10.2 which is removed in 1.11. Requires a total rewrite of every machine that handles fluids.

**Comment by MrPatience** [comment]
I had this issue.. did you try to actually configurate the mekanism cables ?

**Comment by roboderpy** [comment]
rip
![2017-01-04_22 29 20](https://cloud.githubusercontent.com/assets/6339511/21647549/5c99b2c4-d2cd-11e6-92db-d3706276110a.png)

**Comment by Utildayael** [comment]
FWIW, I logged this same issue quite some time ago and @aidancbrady replied it was due to EnderIO not having proper Tesla support which then one of the EnderIO devs [Henry] threw a fit about how Tesla was shit and he would never implement it. 

Glad to hear EnderIO finally implemented it. ;)

Sad to hear we still have Mek issues with it. I had taken a break from MC and came back recent to see the same bugs. You'll run into this trying to use EnderIO conduits into induction matrix, etc as well. You can put power IN to it ok but they can't take power OUT. Various other scenarios. Dimensional Matrix from EnderIO can't seem to output to Mek cables so I had to put in a hack using Immersive Engineering HV cables which worked fine [dim matrix -> hv cond -> hv wire -> hv cond -> mek energy pipes].


So are you saying you installed Tesla API and it *works* now? Just clarifying.

Cheers

**Comment by roboderpy** [comment]
@Utildayael No, Tesla didn't fixed that. 
I only said that behaviour is changed. Before install, Universal cables does Push only to EnderIO machinery, after install Pull only from EnderIO machinery. 
Mods that adds it's own port of RF works differently (broken in various ways). 
But, mods that are same at Universal Cable behaviour,

**mods that supports RF but not Tesla can pull power from Universal Cable, but can not push power into it. When mod support Tesla, it can Push power into cable, but they can't pull power from it**

**Comment by Utildayael** [comment]
Ahhh gotcha. Was hoping. :)

**Comment by ThatGamerBlue** [comment]
Gonna attempt to rewrite this... Wish me luck :P

**Comment by Utildayael** [comment]
You da man! :)

**Comment by thommy101** [comment]
@ThatGamerBlue One advice, take a look at the takePower and givePower methods of TeslaIntegration, it's totally ignoring the simulated argument. This could also mess with a lot of mods. If you're going to tackle the whole Tesla/power issue, please solve that one also.

If you need any help, let me know ;)

**Comment by ThatGamerBlue** [comment]
@thommy101 noted, if you want to help there's a repo on my github ;)
