### ISSUE TITLE
[1.10.2] Digital Miner with Anchor Upgrade does not keep dimension loaded

### ISSUE THREAD

**Issue by Ricket** [aidancbrady/Mekanism#4117]
I put an anchor upgrade into a digital miner and left it in an RFtools dimension. As soon as I teleported out of the dimension, I took a look at the ender chest it was dumping into, and I saw a few ores, then the ores stopped, then the server console showed the lines indicating the dimension had unloaded.

I expected the miner to do the necessary to keep the chunk(s) it is mining chunkloaded, and keep the dimension it is in loaded as well.

**Comment by ktole1999** [comment]
does it work if you place miner/anchor in overworld, nether, end?

**Comment by bookerthegeek** [comment]
@ktole1999 Does not matter.

@Ricket Since you said server can we assume you are running a non-purge forge environment? I.e. spigot or thermos or cauldron or sponge?

Their is a config, different for each, to unload dimensions without players in it. You will need to turn that off.

**Comment by Ricket** [comment]
I am running the server of Direwolf20-1.10 pack version 1.2.2, and then I added Mekanism myself (built from latest master as of a couple weeks ago). So it's just forge, I think. Not any of the things you listed as far as I know. I downloaded [the server files](https://www.feed-the-beast.com/projects/ftb-presents-direwolf20-1-10/files/2361694#additional-files), unzipped them and ran `ServerStart.sh`. It looks like FML is doing the unloading:

```
[17:20:54] [Server thread/INFO] [Actually Additions]: Unloading WorldData for world 4!
[17:20:55] [Server thread/INFO] [FML]: Unloading dimension 4
```

It might be ok to turn unloading off (might eventually cause memory issues), but I have not yet found how to tweak this. There is a `forgeChunkLoading.cfg` but it only sets limits on number of chunks loaded by a mod.

**Comment by roboderpy** [comment]
For some reason, it is not happening for me. Installing Anchor Upgrade keeps The Deep Dark dimension loaded.

**Comment by apdjz** [comment]
I seem to be experiencing the same problem on an infinity light 1.10 pack

**Comment by thiakil** [comment]
Of those who have encountered this, has anyone seen it happen with a *non* RFTools dimension?

**Comment by thiakil** [comment]
I cannot confirm this happening. All my tests show the dimension doesn't get unloaded until the server closes.

A quirk I *can* reproduce however is the RFTools dimensions don't appear to be loading *on server startup*, but this is not a Mekanism bug. The dimension appears to stay loaded once a player has travelled there.

Please reopen if you can show that the dimension unloads before the server closes.
