### ISSUE TITLE
Mobs can spawn inside an induction matrix

### ISSUE THREAD

**Issue by timsalt** [aidancbrady/Mekanism#4118]
I looked through the issues, and I didn't find one like it so I am filing a new one.

I have a 18 x 4 x 8 induction matrix with an elite cell and an elite provider in it. Because there is so much extra room inside mobs can spawn in it (Just had a spider spawn inside). I cannot put torches or non-induction blocks inside or it will not make a valid induction matrix multiblock. It seems like the only solution is to fill the empty space with basic cell providers, but that will be expensive to pull off. 

This is bad because opening up a multiblock to find a creeper that then destroys my very expensive induction cells/providers would be pretty frustrating.

I'm on FTB-Infinity Lite v1.4.1. I am ashamed to admit I don't know how to find the associated version of Mekanism.

**Comment by ktole1999** [comment]
fill in the gaps with induction cells. i think the matrix capacity is based on cells contained not the matrix shell.

**Comment by timsalt** [comment]
I made it so large for aesthetic reasons. It will be expensive to fill all the gaps with induction cells, though that does seem to be the workaround for now. 

Other multiblocks allow or fill with liquid which prevent this sort of thing. Perhaps the induction cells/providers could emit light or some other effect to prevent this from happening.

**Comment by ktole1999** [comment]
you cant have your cake and eat it too. its built for  functionality. not just fit to the environment.

**Comment by bookerthegeek** [comment]
@ktole1999 Mobs should NOT be spawning inside of the multi block structure.

**Comment by ThatGamerBlue** [comment]
Working as intended. @aidancbrady /close

**Comment by timsalt** [comment]
After some experimentation I have discovered that induction ports are not opaque and thus allow light in. This seems like fair behavior to me.
