### ISSUE TITLE
[Crash] Atomic Disassembler has an unchecked cast

### ISSUE THREAD

**Issue by The-Fireplace** [aidancbrady/Mekanism#4120]
Hey, someone just reported a crash to me that happens when a non-player entity attacks using your atomic disassembler.
[Here's the report.](https://github.com/The-Fireplace/Overlord/issues/67)

And [here's where you make the cast without checking](https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/item/ItemAtomicDisassembler.java#L68).

**Comment by thommy101** [comment]
Tried to replicate it, but was unable to do so. (I'm no hero with summon command to spawn a vanilla skeleton with an Atomic Disassembler).
Anyway, it's definitely an error so I've opened a pull request (#4124) with a fix for this.
