### ISSUE TITLE
mekanism and tinkers construct copper issues

### ISSUE THREAD

**Issue by dritz56** [aidancbrady/Mekanism#4121]
hello,

I'm having an issue with tinkers construct now being able to smelt mekanism copper ores. I'm not sure if its something to do with tinkers construct or with mekanism. From what i've read on the mekanism wiki the copper ore should work with other mods. I've tried melting all forms of copper ore,dust,blocks and so on. I'm using mekanism 9.1 on MC 1.10.2

**Comment by thommy101** [comment]
My guess is that there's something wrong with Tinkers Construct. As EnderIO and Mekanism both have the same issue.
Copper is all oredict in Mekanism to ore- ingot- dustCopper.

**Comment by dritz56** [comment]
thank you that works

**Comment by roboderpy** [comment]
@dritz56 You can help issue tracker be clean by closing your issues that has been solved by pressing "Close Issue" button near "Comment"
