### ISSUE TITLE
Machines forgetting in/out settings

### ISSUE THREAD

**Issue by Riyshn** [aidancbrady/Mekanism#4127]
As title, machines (Metallurgic Infusers, specifically. ...which I just realized WAILA is registering as Enrichment Chambers for some reason?) are forgetting their input/output side settings. Seems to be time- or possibly operation- based, rather than anything to do with chunkloading.

Bug in action: https://youtu.be/ScO5Ms6hMEE

If there is a log somewhere that would be helpful for this, please let me know where to find it.

EDIT: Actually, it seems that this isn't an issue of machines forgetting their settings, but rather they're cloning settings form other machines. Edit one machine, and another changes as well.

Minecraft: 1.10.2
Forge: 1.10.2-12.18.3.2185
Mekanism: 1.10.2-9.2.1.295

**Comment by ThatGamerBlue** [comment]
WAILA bug is in waila not mek, use the one probe or wawla for accurate information.

And god fucking damnnit I thought I fixed this already.

**Comment by Riyshn** [comment]
I forgot to mention it in the initial post, but I did use the Configuration Card to initially set up the machines before changing the few the needed slightly different settings, if that helps narrow it down.

**Comment by ThatGamerBlue** [comment]
Will have to research this, haven't seen this one yet.

**Comment by aidancbrady** [comment]
Should be fixed.
