### ISSUE TITLE
Voiding excess gases and fluids

### ISSUE THREAD

**Issue by KraKenG81** [aidancbrady/Mekanism#4129]
several gas processing machines lack the ability to void or refil containers of gases and fluids. they make the experience of the whole mod a bit unsettling. many would appreciate a fix to this issue beacause crafting several machines for only one purpose isn´t really fun...

i hope this message gets to the mod creator and hopefully you can fix the issue

**Comment by KraKenG81** [comment]
I don´t know if there has been any recent updates since im playing in Project Ozone 2. It is updated to the latest version but I´m not sure if it has the latest version of mekanism

**Comment by ktole1999** [comment]
which gas/fluid are you referring to? latest version is .295 i think.

**Comment by VT-14** [comment]
Gauge Dropper.  Use it to click on the tank in the GUI.

**Comment by ThatGamerBlue** [comment]
1.7.10 isn't supported. Close please.

**Comment by roboderpy** [comment]
![2017-01-07_21-00_minecraft](https://cloud.githubusercontent.com/assets/6339511/21742211/4ecf530a-d51c-11e6-9b96-c923b611bc76.jpg)

**Comment by VT-14** [comment]
Gauge dropper is an item.  click on the associated tank in the GUI while holding it.  I believe you can then dump it by (shift?) right clicking in the world.

**Comment by roboderpy** [comment]
Shift-Right Click in world does nothing, but Gauge Dropper works.
![2017-01-07_21 07 30](https://cloud.githubusercontent.com/assets/6339511/21742244/626ba17e-d51d-11e6-9cd7-59d85a831cc0.png)
But buttons are still missing.
![2017-01-07_21-09_minecraft](https://cloud.githubusercontent.com/assets/6339511/21742255/841df51a-d51d-11e6-87c7-4e54b3045329.jpg)

**Comment by VT-14** [comment]
I'm fairly certain the Electrolytic Separator is the only machine (other than gas tanks) that include those dumping buttons.  I think it's there so you can always produce one of the gasses by dumping the other without having to have an extra gas tank just for the purpose of voiding air.

For the other machines, use a Gauge Dropper.  That's what it was made for, and it works on both fluids and gasses.  I'm also reasonably certain there is a way to dump it in the world, but I don't remember what it is.  Did you try looking at a block or at the air?

**Comment by roboderpy** [comment]
??? I done Shift + RightClick on placed machine

**Comment by VT-14** [comment]
Shift right click is to empty the Gauge Dropper and void the gas/fluid so you can use it again.  If you want to save the gas/fluid, you should be able to use a tank.

The Gauge Dropper was made to empty machine tanks that do not have the dumping buttons.

**Comment by roboderpy** [comment]
Oh. I already know that you can void gauge dropper by shift+rightlick with gauge dropper in the world.

**Comment by tomasdev** [comment]
For some reason, it seems neither a gas tank nor a gauge dropper would empty wrongly placed Tritium as input on a Solar Neutron Activator (yes, I messed up the tubes below, and now they won't empty)

**Comment by tomasdev** [comment]
Nevermind. Gotta click with the Gauge on the blue thing, not place it on the [-]
