### ISSUE TITLE
Quantum Entangloporter bug/request

### ISSUE THREAD

**Issue by blackice125** [aidancbrady/Mekanism#4131]
working with build: 1.10.2-9.2.1.295

we found a limit on the Quantum Entangloporter - 400Krf/t  per channel.

Could we get the ability to set this limit in the config file?

Currently one of our power guys is using 23 or something channels to move the power from the steam turbine to the bat room.

also noticed the channel list only shows the first 4 channels in the Quantum Entangloporter.

**Comment by thommy101** [comment]
Limit confirmed, there's currently a hard limit of 1.000.000J (400.000 rf) defined in InventoryFrequency.
Would be nice to change it indeed.

**Comment by thiakil** [comment]
@blackice125 you can scroll the list by dragging the little box in the scrollbar.

**Comment by aidancbrady** [comment]
Already reported, I'll see about adding something to the config.
