### ISSUE TITLE
Dupe bug with bins

### ISSUE THREAD

**Issue by AsukaLangleyfag** [aidancbrady/Mekanism#4133]
1.7.10 have dupe bug: #4069
As I found, 1.10.2's latest release of Mekanism have dupe bug too! I'm not sure if Mekanism have Formulaic Assembler in this version, but i've tried with Ender/io's auto-crafter (forgot the name, sorry) and it dupes the bins. To reproduce, just use bin as usual in the crafting grid, but in auto-crafter.

**Comment by aidancbrady** [comment]
Thanks- I'll look into #4069
