### ISSUE TITLE
Cardboard box Blacklist not working. Version 9.1.0

### ISSUE THREAD

**Issue by DeGariless** [aidancbrady/Mekanism#4134]
MC: 1.7.10
Mek: Mekanism-1.7.10-9.1.0.281

Blacklist is not working for me. Don't know how much simpler my config could be. I was able to pickup stone with the cardboard box with the example config (attached). What am I doing wrong? What information can I provide to fix the problem? This was tested both client and server in a Mekanism only environment.

[BoxBlacklist.txt](https://github.com/aidancbrady/Mekanism/files/669945/BoxBlacklist.txt)

**Comment by ThatGamerBlue** [comment]
1.7.10 isn't supported.
