### ISSUE TITLE
Merry Christmas message on January 8th?

### ISSUE THREAD

**Issue by Ricket** [aidancbrady/Mekanism#4135]
Erm.. Why is there a "Merry Christmas" message on Jan 8 instead of Dec 25? Or Jan 7 for Orthodox Christmas? Or is it supposed to be orthodox+1?

https://github.com/aidancbrady/Mekanism/blob/81e810794581cabba8925634f93f1323400014cb/src/main/java/mekanism/client/HolidayManager.java#L99

![image](https://cloud.githubusercontent.com/assets/196978/21752416/785ff1c8-d5a5-11e6-87b5-0aaeed1003e8.png)

It is a beautiful sentiment nonetheless, thanks for the belated Christmas cheer, and same to you Aidan!

edit: Also I see in the code it's supposed to replace the sounds with nutcracker sounds, but I'm hearing the same old sounds from the crusher -- oh well!

**Comment by thommy101** [comment]
I saw the same message. 25 December is the date for the Christian Christmas, there are other religions which have it on other days. Orthodox Christians have it around 7 January for example.

**Comment by roboderpy** [comment]
This works as expected. In Russia we have Christmas at 7th January.

**Comment by thommy101** [comment]
Can be closed, is changed to 25 December on the master branch.
