### ISSUE TITLE
Bug/Compatibility Issue with Cyclic mod and Mekanism jetpack.

### ISSUE THREAD

**Issue by MadToilet** [aidancbrady/Mekanism#4138]
After experiencing a bug in the 1.10.2 Mech and Magic pack on the ATLauncher whereby I was receiving fall damage while using the mekanism jetpack even when feathering down to a soft landing I started to search for the cause. Mekanism doesn't exhibit this bug when run solo, so it seemed to be a mod conflict issue. After doing a 50/50 of mods (cutting half out, rinse repeat until I could narrow it down to 2 or more mods), I found that this bug is exhibited only with the existence of two mods: Cyclic and Mekanism.

Steps for reproduction of bug:
1) Install latest version of both mods
2) equip a Mekanism jetpack **AND** any boots (no fall damage taken unless wearing boots - bug negated if boots are damage negation boot, such as the slime boots from TiCo).
3) attempt to land safely with above configuration -- fall damage taken at normal rate. This will occur regardless of how safely you land (feathering the landing).

Replicated using any combination of the following mods(vers.):

Mekanism 1.10.2-9.2.1.295 (core mod plus generators and tools mods)
OR
Mekanism-1.10.2-9.2.1.298 (core mod plus generators and tools mods)

&

Cyclic-1.10.2-1.9.12
OR
Cyclic-1.10.2-1.9.14

I will cross-post this with the Cyclic team so they can look into it as well.

**Comment by ThatGamerBlue** [comment]
Workaround: Hop into hover mode on the jetpack and back out just before you land.

**Comment by thommy101** [comment]
For reference:
https://github.com/aidancbrady/Mekanism/blob/1.10/src/main/java/mekanism/common/CommonPlayerTickHandler.java#L104
Here does Mekanism set the falldamage to zero.

**Comment by ThatGamerBlue** [comment]
This is not on mekanism's side AFAIK.

**Comment by thommy101** [comment]
Hehehehe, I know its (95%) not Mekanism, just for reference of those who want to look how Mekanism nullifies the damage.

**Comment by MadToilet** [comment]
I was pretty sure it wasn't on Mekanism's side, but posted here just in case. I am pretty sure PrinceOfAmber is looking into it on his side:

https://github.com/PrinceOfAmber/Cyclic/issues/235

**Comment by MadToilet** [comment]
Hey Aidan and Mekanism team.  Just wanted to follow-up on this and say that PrinceOfAmber solved this issue with his last update. If you receive anymore reports or messages about this, telling them to update to the latest version of Cyclic should solve the issue.
