### ISSUE TITLE
Add RF API to Induction Matrix.

### ISSUE THREAD

**Issue by EntityReborn** [aidancbrady/Mekanism#4140]
I use RFTools' screens to display information about my base.
While these work fine with Dynamic Tanks and the Fluid Modules for RFTools, it doesn't work for the Induction Matrix and the Energy Modules. Trying to use an Energy Module on the induction port, the only mode on the module that will work is RF/t. RF and RF% both show up as completely blank.

I have spoken to the devs of RFTools, and they say that Mekanism needs to support the RF API (I assume they mean https://github.com/CoFH/RedstoneFlux-API) to have this properly supported.

**Comment by ThatGamerBlue** [comment]
tell rftools to support tesla

**Comment by EntityReborn** [comment]
I'll make a mention to them, thanks. It would be great if it could still be looked into tho.

**Comment by thommy101** [comment]
Mekanism does support rf (cofh version), tesla (although it seems to contain some bugs). Only thing that isn't supported is Forge Energy.

**Comment by EntityReborn** [comment]
Hm, then something is a little weird. I'm using HermitPack 1.5.1. I'll talk with McJty and see what he thinks. @ThatGamerBlue , I might work on it as well, schedule depending this weekend.

**Comment by EntityReborn** [comment]
@thommy101 do you happen to know what bugs there might be?

**Comment by thommy101** [comment]
I do happen to know what bugs there are:https://github.com/aidancbrady/Mekanism/issues/4116#issuecomment-270376948

**Comment by EntityReborn** [comment]
Ouch, that doesn't look trivial to fix.
