### ISSUE TITLE
[Request] Total Capacity for Induction Matrix

### ISSUE THREAD

**Issue by Utildayael** [aidancbrady/Mekanism#4141]
Maybe I'm missing this somehow... but would be nice to see total capacity in an induction matrix. The power graph showing how much it has stored works for that *if* you are at 100% otherwise I don't know any other way to see it. The statistics tab has nice fields for input/output but sadly not a text line showing how much power out of how much max power, ie: 10M RF out of 5GRF.

**Comment by aidancbrady** [comment]
Definitely will look into this. It's mentioned in another issue back, closing this one.
