### ISSUE TITLE
[1.10.2] MC multipart causing issues and terrain animation lag

### ISSUE THREAD

**Issue by shivachirr** [aidancbrady/Mekanism#4142]
so apparently strangely after alot of testing i traced alot of lag and render issues with other mods to the multipart mekanism downloads and uses which i feel needs to be looked into especially since the mod file actually says experimental. and one mod is basically destroys is the localized weather mod which is a mod that spawns a lot particle is keeps them from rendering or messes them up to the point it lags the game out completely. also it auto deletes the version other mods call for via the curses launcher which i would not be surprised is causing i even more issues

**Comment by thommy101** [comment]
There is a build available which removes the deploader. Deploader is responsible for downloading the wrong experimental version of MCMultiPart. You can find it here: https://github.com/aidancbrady/Mekanism/issues/4119

You can install MCMultiPart 1.3 yourself and try again.
