### ISSUE TITLE
Digital Miner not working on server. 

### ISSUE THREAD

**Issue by Sztacho** [aidancbrady/Mekanism#4144]
Hey. I have problem. The digital miner not working on my server.  my serwer have installed permissional Ex. I try op mekanism but this still not work.  The serwer is version 1.7.10 . 

Sorry. But i from Poland.

**Comment by Sztacho** [comment]
This not work.

**Comment by VT-14** [comment]
Which permissions mods/extensions?  You have to enable "Fake Players" to let this kind of thing work.

The only one I know of off the top of my head is FTB Utilities, which can be fixed by setting your personal chunk protection config with the command "/ftb team config ftbu.fake_players true"

**Comment by Sztacho** [comment]
I have FTB Utilites but I don't have this command :C

**Comment by VT-14** [comment]
The gui was probably working in 1.7.10.  FTBUtilities is the stuff on the left side of your inventory.  Flip through those options to find a fake player config option.
