### ISSUE TITLE
Quantum Entantangleporter Slow Fluids/Items

### ISSUE THREAD

**Issue by Kin37ix** [aidancbrady/Mekanism#4146]
On the latest version of Mekanism for 1.7.10, the Quantum Entangleporter is extremely slow at transferring fluids. I suspect it has a very small fluid buffer? It doesn't matter if you push from the device or pull with Ultimate Mechanical Pipe/Ender IO, it simply can't keep up with a maxed out Electrolytic Separator. Item transfer also seems really slow. I really want to use the Quantum Entantangleporters, but the TE Tesseract just beats it in every way barring gasses.

**Comment by ThatGamerBlue** [comment]
-insert 1.7.10 isn't supported comment here-
