### ISSUE TITLE
Is the Resisitive Heater working correctly?

### ISSUE THREAD

**Issue by duncanwebb** [aidancbrady/Mekanism#4147]
Hi,

I've attached a resistive heater to Thermoelectric Boiler and it generating far too little heat. With 5 Bio-Generators and configured to 3.5kJ/t (1.4 RF/t) it is generating about 35mB/t of steam. Comparing this to Fuelwood Heater that generates 40nB/t, it doesn't seem quite correct.

When feeding the steam into an Industrial Turbine the turbine as generating about 70 RF/t with seems a bit feeble compared to the 1400 RF/t that was being fed in.

May be there is something wrong with my build. Any ideas?

Thanks
Duncan

**Comment by ThatGamerBlue** [comment]
Screenshots? Logs?

**Comment by duncanwebb** [comment]
Not sure what you would like from the logs but pictures are easy.

![boiler resistive](https://cloud.githubusercontent.com/assets/4198031/21997156/0984a93a-dc2e-11e6-8a26-cf258e187a42.png)
![boiler resisitive heat](https://cloud.githubusercontent.com/assets/4198031/21997158/0c00b15e-dc2e-11e6-8366-993ed3210b91.png)
![boilder_fuelwood](https://cloud.githubusercontent.com/assets/4198031/21997160/0f426682-dc2e-11e6-8ec2-66d2a854e4c3.png)
![boiler fuelwood heat](https://cloud.githubusercontent.com/assets/4198031/21997162/11290f6e-dc2e-11e6-9783-8369cde2dcf8.png)

Thanks for your time hope these pictures show something useful. I want small size plants where possible. The boiler is 5x3x6

**Comment by VT-14** [comment]
If I'm understanding your setup correctly (I haven't used the thermal stuff yet) you are using heat to make steam to make power.

It also looks like you are now trying to make heat from power.  I'm sorry, this mod (mostly) respects the laws of thermodynamics.  That is intentionally not power positive.

In a similar frame of mind, the Electrolytic Separator does not get an efficiency boost from Energy Upgrades due to Hydrogen being able to be burned to get 100% of the power back, and boosting the efficiency would generate power from nothing.

**Comment by duncanwebb** [comment]
Yes, that is correct heat->steam->power with the fuelwood heaters and power->heat->steam->power with the resistive heaters. Makes sense that you would get a net loss of power from the resistive heater.

power->heat should be about 100% efficient a little less efficient for heat->steam and IIRC steam to power with a turbine is where most of the loss would occur but would be more efficient than a generator. Something I need to test how much power a stack of charcoal generates in the Boiler+Turbine compared to a Heat Generator.

I did try the Electrolytic Separator Gas Burning Generator power being fed back into the Electrolytic Separator to see if there was a net power gain, it did behave rather badly the Hydrogen levels jumped up and down like crazy rather than a smooth reduction of Hydrogen.

It seems that the resistive heater is far too inefficient and the losses should be at the Turbine.

**Comment by duncanwebb** [comment]
> I need to test how much power a stack of charcoal generates in the Boiler+Turbine compared to a Heat Generator

The result was about 75:1 - 75 times more energy from the fuelwood+boiler+turbine!

**Comment by aidancbrady** [comment]
The values can be adjusted- I'm happy with the way things work for now.
