### ISSUE TITLE
Cardboard box won't open

### ISSUE THREAD

**Issue by hornsfan01** [aidancbrady/Mekanism#4151]
I am playing the FTB Infinity Lite 1.10 modpack, version 1.5.1 through the Curse launcher. I have a Builder block being run as a quarry with a diamond chest on top accepting the quarried contents. I made a cardboard box and clicked it on the diamond chest to preserve the quarried inventory. I was then able to break the cardboard box block and take it into inventory.

But once I place it back anywhere into the world, no amount of sneak-right-clicking will open it. Shift-right click has no visible effect. It breaks and can be placed normally but I cannot open it. While in inventory, the item shows that it does have associated block data.

![image](https://cloud.githubusercontent.com/assets/25268589/22176151/35a61d48-dfc9-11e6-8352-37fdce7b2cad.png)

I have restarted the server and the client and that makes no difference.

I then made a new wood chest, placed it (without contents) into the world, made a new cardboard box, and clicked it onto the wood chest, which wrapped it in the cardboard box. That also will not open.

I also changed the keybinding for sneak to a different key to make sure it wasn't a keyboard conflict. The new key (the letter "O", chosen at random) still allows me to sneak. But the new sneak plus right click does not open any of the cardboard boxes either.

**Comment by hornsfan01** [comment]
Error traced to a shift key on my keyboard that doesn't work even though the rest of my keyboard works. No idea why just the shift key would stop working. Not a Mekanism issue.

**Comment by M0uts** [comment]
Had the same problem, removing the shield from the second hand solved it.

**Comment by ArsStarhawk** [comment]
> 
> 
> Had the same problem, removing the shield from the second hand solved it.

Was the same problem for me as well. Thanks.

**Comment by Crayder** [comment]
>>Had the same problem, removing the shield from the second hand solved it.
>
>Was the same problem for me as well. Thanks.

Thank ya fellas.

This should probably be fixed right? Can we reopen this?

**Comment by pupnewfster** [comment]
No, as it is not a bug or something we can even fix, the offhand is consuming the interaction.
