### ISSUE TITLE
Machines and Bins rotating by themselves

### ISSUE THREAD

**Issue by duncanwebb** [aidancbrady/Mekanism#4154]
I'm using **Mekanism-1.10.2-9.2.1.295** and **Progressive Automation 1.6.48** for 1.10.2. When Generators and Bins are in the same chunk the bins are either rotating of showing empty when they are not empty.

I've only seen this behaviour near the tree farm, where the Progressive Automation machines are. Where there are only Mekanism blocks everything behaves well.

![bins-1](https://cloud.githubusercontent.com/assets/4198031/22299211/9b3be680-e323-11e6-95f5-c77c3599586b.png)
![bins-2](https://cloud.githubusercontent.com/assets/4198031/22299212/9d5fc1ac-e323-11e6-9619-53baa52d351d.png)
![generators-1](https://cloud.githubusercontent.com/assets/4198031/22299215/9f37f800-e323-11e6-8300-1f4236d1e91d.png)
![generators-2](https://cloud.githubusercontent.com/assets/4198031/22299219/a1202c96-e323-11e6-855a-ceaf08ee8411.png)

I cannot say if other mods cause the same effect.

Many thanks

**Comment by thommy101** [comment]
Please use the search function, this has been reported multiple times.

**Comment by duncanwebb** [comment]
Sorry I didn't know how to search github was only getting code results, now I know how. 

I see I've duplicated https://github.com/aidancbrady/Mekanism/issues/3977.
