### ISSUE TITLE
Logistical Sorter OC/CC Support

### ISSUE THREAD

**Issue by kofteistkofte** [aidancbrady/Mekanism#4156]
If would be really useful if we could configure and reconfigure Logistical Sorter with OpenComputers or ComputerCraft. Currently it's only a configure and do what you configured before, but with computer support, we could make dynamic systems and much more smart sorting alternatives.

**Comment by aidancbrady** [comment]
Done- you can now add/remove OreDict and ItemStack filters, as well as set default color, auto-eject value, and round-robin value.
