### ISSUE TITLE
Minecraft won't launch

### ISSUE THREAD

**Issue by LordMortus** [aidancbrady/Mekanism#4157]
Running a fresh install of 1.10.2 in the newest Curse Client (no mods) and Minecraft runs fine..

I add Mekansim .298 and Minecraft won't launch:

[fml-client-3.txt](https://github.com/aidancbrady/Mekanism/files/733777/fml-client-3.txt)

I also get a "Half command" line in the Launcher Log

[Launcher Log.txt](https://github.com/aidancbrady/Mekanism/files/733790/Launcher.Log.txt)

**Comment by thommy101** [comment]
This looks like the common Nvidia problem which has been introduced in its latest driver update of January 24th. Please try forge without any mods.
If the issue persists, try installing (or rollback) of your driver.
For more information, go and take a look at the following reddit post. 
https://www.reddit.com/r/feedthebeast/comments/5pydv9/dont_install_nvidia_gpu_driver_version_37849_it/

**Comment by LordMortus** [comment]
Thanks for the response. Rolling back seems to have fixed it (as was stated in the reddit post)
