### ISSUE TITLE
Bucketless Fluids and Other Mods

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [aidancbrady/Mekanism#4159]
I'm running Mekanism and Refined Storage and I'd like to use the latter to store liquids from the former.  However, Mekanism doesn't have buckets for all their fluids, which is a BIG PROBLEM.  Because of how RS works you can only manipulate fluids that do have bucket (i.e. item) forms. No bucket means no exporting or fluid level detection, which basically means that RS is unable to do anything but store such fluids, much like a black hole. Not Very Useful.

Is there some particular (bad...I mean GOOD) reason most fluids in Mekanism don't have buckets?!?  Were they specifically left bucket-less because of some design scheme/paradigm/realism/balancing reason?!?  Regardless, could you please offer a code switch setting that enables buckets for all fluids, because design schemes/paradigms/realism/balancing reasons are all fine and dandy and whatnot, Until They Get In The Way Of Playing The Game!  I don't care if I have to enter in a console command "enableAllFluidBuckets true" or whatever, just so long as I can get them.

**Comment by aidancbrady** [comment]
The only fluids that you should be transferring via buckets in Mekanism are heavy water and brine; the rest are either internal or related to the gas API.

**Comment by SamuelYaron** [comment]
I do not know if this is still relevant for you @7OOTnegaTerces , but you can just use a mekanism fluid tank with the relevant fluid in it. Refined storage accepts that for configuring filters. I encountered the same problem today but luckily I was able to find this easy solution.
