### ISSUE TITLE
Electrolytic Separator Output Error

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [aidancbrady/Mekanism#4160]
While I can stick an RC to the right of a Seperator to turn the right hand gas into a fluid, I cannot do so on the left side, but instead MUST use a pipe to connect the Seperator to the left RC, which just wastes space.  Could you please fix it so that the Seperator will directly dump from the left side into other machines without requiring piping?

Minecraft: 1.10.2
Mekanism: 9.2.1.295

**Comment by thommy101** [comment]
The separator has a fixed input and output, if you place the rotary condensentrator 180 degrees turned it works just as fine as on the other side.
