### ISSUE TITLE
[MC 1.7.10 - latest Mek Build] Precision Sawmill won't autooutput to Logistics Basic Pipe

### ISSUE THREAD

**Issue by chaos234** [aidancbrady/Mekanism#4161]
As the tilte says, the announced machine is not compleatly interacting with the Basic Logistics Pipe from Logistics Pipe Mod even if auto eject is on and the correct side is configured for output bot still nothing happens.

However, the machine is still accepting the RF provided over the TE Power Supplier Upgrade which can be placed in the Basic Logistics Pipe.

So this seems to be a problem on Meks side because normaly it should eject the output to it.

I hope that this will get fixed soon.

**Comment by aidancbrady** [comment]
1.7.10 is no longer supported
