### ISSUE TITLE
Complete Tinker's Construct Support ~ It's kind of wierd?

### ISSUE THREAD

**Issue by zerafox** [aidancbrady/Mekanism#4163]
Mekanism is already mostly compatible with Tinkers, however it doesn't appear to support all the liquids that the Smeltery can create. Such as Molten Obsidian for example.
~~There also seems to be some small issue with sending liquids back into the Smeltery, although there appears to be 0 issues with taking liquids out.

Pulling lava from the Smeltery into a Basic Tank works, but pulling lava from the same tank into a pipeline~~

Actually, it only appears that these fluids don't fill pipes if they don't have a destination. Iron and Gold will show flowing through the pipes if there is no available tank.

**Comment by aidancbrady** [comment]
Doesn't sound like a bug on my end.  There's no specific Tinkers Construct support, which means if some things work and some things don't, it's not my fault.
