### ISSUE TITLE
Basic Fluid Tanks + Higher

### ISSUE THREAD

**Issue by zerafox** [aidancbrady/Mekanism#4165]
So being new to Mek, I found myself playing around Pipes and the Tanks (Not the dynamic).
I figured out that I could make the Basic tanks (and higher) "active" which allowed them to 'drain' to tanks below them. Unfornately they still act as seperate tanks which means if I setup a 'tube' of tanks for one liquid, lets say water. And another 'tube' for say lava, the lava can still pour into my 'water tube' because the connected Tanks still act as though they are separate, despite the liquids draining to the lower tank.

What I'm asking for, is making it so that stacked, active tanks can act as one complete tank.
The purpose for this, is to allow 'tubes' of liquids to setup in a manner of 'Water liquid tube' and 'Lava liquid tube' and 'Copper liquid tube' without having one of them wind up in some other tube they weren't meant to be in.

Sadly to achieve this right now I have 1 of 2 options:

1. complete separate pipe units
2. setup complex levers and redstone to disable pipes/tubes I don't want the liquid to enter, but allow into the one I do want to enter.

**Comment by thommy101** [comment]
I've made a pull request implementing this feature, see linked pull request (4400)
