### ISSUE TITLE
[Request] Base and Modern Metal Ore Processing

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [aidancbrady/Mekanism#4166]
Could you expand the 5x ore processing method to include all the metals from Base Metals and Modern Metals (as well as their nether and end equivalents)?!?  That would be REALLY AWESOME!!!

Oh, and why can't I at least get 3x ore processing for stuff like redstone, diamonds, and emeralds?!?

**Comment by jriwanek** [comment]
Support for mekanism is being added to BMe and MMe directly.
