### ISSUE TITLE
[Suggestion] Shift + Scrollwheel to run through Configurator/Tool settings

### ISSUE THREAD

**Issue by Dragnier** [aidancbrady/Mekanism#4167]
This would be an awesome addition to the controls for the mod. Doesn't specifically need to be Shift+ Scrolling; that was just an example. If there were also a way to specify pipe color on the configurator prior to setting it rather than having to cycle them all every single time, that would just be a bonus.

**Comment by dragonpc75** [comment]
i am wholeheartedly supporting this! 👍 it would make Life SO much better. Ender IO uses this for their wrench and its simply amazing. even better for your configurator since it has like 3 times more functions.. lol

**Comment by ThatGamerBlue** [comment]
might be added in the rewrite, added it to my notes

**Comment by aidancbrady** [comment]
Done!
