### ISSUE TITLE
Refined Storage Auto crafting and Mekanism, not so nice together.

### ISSUE THREAD

**Issue by dragonpc75** [aidancbrady/Mekanism#4169]
found out today that auto crafting bins in Refined storage is a bad idea. you can craft it but then it doesn't let you have the item out of the grid, or any other way.. i don't know what is causing this there was no crash report or anything, it just won't let me take it out. i even tried an advanced bin, it is also stuck there now.. lol can't take them out. figured you'd at least want to know. 
**Another bug i found, when in the crafting grid of Refined storage you place a Bin with lets say 2k redstone in it, and shift click it to extract all the items, you get one stack and the bin disappears/disintegrates.. **
i am unsure whether this is on your side or on Refined storage's side, but i will post in both places to be safe.

**Comment by aidancbrady** [comment]
Going to call this a Refined Storage issue; if it works with vanilla then it's not on my end.

**Comment by LogosWorks** [comment]
This same issue is currently causing a dupe issue.
when you place a bin (full or empty) and stack of an item into crafting grid area (with or without more of bin/item in grid storage area) then shift click the crafting output you get a bin with all items +64 and it leaves 64-1=63 items in crafting area or 62 if you do it again. if you do not shift click it is a client crash.

**Comment by Ant95** [comment]
Fixed (1.12) by https://github.com/aidancbrady/Mekanism/commit/9c7164c0db3877538a6c525700b64d4353d20da5 on Mekanism end
And fixed (1.12) by https://github.com/raoulvdberge/refinedstorage/commit/d1c275d35eb89519e9c537db42851352d3b60146 on Refined Storage end
