### ISSUE TITLE
After removing energy upgrades, machines retains all energy stored, even if the amount is above the new maxEnergy limit.

### ISSUE THREAD

**Issue by JaSpr** [aidancbrady/Mekanism#4172]
This is causing issues with other plug-ins that display a bar graph of stored energy -vs- max energy:

A story in pictures: http://imgur.com/a/VTd7t

Each time an efficiency upgrade is removed from the machine, the code appears to properly adjust the "total available" (max) energy that the machine can hold, but doesn't update the total actual energy that the item is holding.

The energy bar can thus extend all the way across the screen.

**Comment by thommy101** [comment]
Can confirm this issue, exactly the way described.

**Comment by JaSpr** [comment]
After cloning the code and testing, I've found that the actual issue is that adding energy upgrades temporarily increases a machine's energy capacity (maxEnergy).  So if you install upgrades, the capacity goes up, and then you can continue to charge the item to get it up to its new capacity.

Once you remove the upgrade, the machine might have a capacity above the new maxEnergy limit.  

A discussion should be have whether this is as designed (we don't want to have the user lose the energy they already spent), and, if so, whether we want to report it as the higher value, or report it as the maxEnergy capacity until it goes back below that threshold organically (i.e. we could retain the total stored energy, but report it as `Math.min(storedEnergy, maxEnergy)`).

**Comment by thommy101** [comment]
If I would design it, I would make it that removing an energy upgrade also decreases the stored energy to the max level. It's like removing a battery, the energy won't stay.

**Comment by 7OOTnegaTerces** [comment]
@thommy101 If your battery analogy is true, that would mean that the extra energy is being stored on the upgrades themselves, which means that when they get inserted into a new machine it should instantly get that extra energy, no charging needed.  If that's not how upgrades work, then the energy should stay in the machine.

**Comment by JaSpr** [comment]
As a note, TOP was updated to prevent the power bar graph from ever extending beyond the bounds of the graph itself.  That being said, this issue doesn't affect TOP anymore (for which it was originally created), but perhaps a discussion should still be had.

**Comment by aidancbrady** [comment]
I've changed the mechanic to cap a machine's energy at it's new maximum after an energy upgrade is removed.  Letting the energy sit above it's maximum felt... unclean to me.
