### ISSUE TITLE
IC2 Uranium ore can't be processed by Enrichment Chamber

### ISSUE THREAD

**Issue by JaSpr** [aidancbrady/Mekanism#4173]
IC2's Uranium Ore can't be converted to uranium dust within the enrichment chamber.  All other ores that convert to dust seem to be able to, just not this one.

**Comment by ktole1999** [comment]
that is correct. its always been like that. you either had to use sag mill from enderio or thermal expansion and since thermal expansion doesnt exist you need to use sag mill, ic2 or another mod machine.

**Comment by aidancbrady** [comment]
Done!
