### ISSUE TITLE
Industrial Turbine port - Hermitpack 1.10.2 - 1.6.1

### ISSUE THREAD

**Issue by JesterHorse** [aidancbrady/Mekanism#4177]
The port has an error when looking at it. It says Error: "theoneprobe:default" the words are red indicating a problem. I believe this is preventing me from forming the turbine.. The entire multiblock structure is 5x5x11.

![screenshot 118](https://cloud.githubusercontent.com/assets/25517008/22574729/516260ee-e976-11e6-878d-6d36cfa0bfcc.png)
![screenshot 119](https://cloud.githubusercontent.com/assets/25517008/22574735/5edd75ba-e976-11e6-9533-f2550bdf4ded.png)

**Comment by StrommKral** [comment]
FTB Lite Infinity 1.10.2 / 1.51 also has this problem. has anyone found a fix or cause  for this problem?

**Comment by laz2727** [comment]
It's not the thing that's stopping you, that's for sure. TOP.default just
means that TOP support is broken.
