### ISSUE TITLE
Universal cables need forge energy support

### ISSUE THREAD

**Issue by FnordMan** [aidancbrady/Mekanism#4179]
The "universal" cables are powering almost no devices anymore, they need an update for FE support to enable this again. Tesla support would also be good as well, not the old crusty unofficial RF api. 

See Ex Compressum issue 177: https://github.com/blay09/ExCompressum/issues/177

**Comment by jburrows82** [comment]
Mekanism supports Tesla, RF, and EU. Mods that support FE usually either support Tesla or RF, if not both. FE isn't a standard for power transfer, it's just another option at this time.

**Comment by ThatGamerBlue** [comment]
we use tesla because tesla is the sh*t

**Comment by FnordMan** [comment]
Well something needs fixed as the "universal" cables won't deliver power to Ender IO or ExCompressum.

**Comment by jburrows82** [comment]
ExCompressum dropped RF support. We'll have to see how Thermal Expansion 5 goes as far as for an energy api, but KingLemming has expressed disinterest in the capability system provided by Forge. So RF may become the defacto standard once again.

I believe upstream that Tesla energy has been fixed, so EnderIO shouldn't be an issue. Just mods that only support FE now (which is a handful at best, and other energy api bridge mods that exist resolve that issue automagically).

**Comment by ktole1999** [comment]
eio also dropped rf support in favor of FE. So until everyone can find a common ground for power and keep the systems updated this will be an issue.

**Comment by jburrows82** [comment]
Well in 1.10 this is a non-issue with the handful of energy bridging mods available. As long as the backend is functioning properly in the Tesla implementation, everything should be good to go. 

If you could provide a link to the repository commit, or source citation from one of the EIO devs explicitly saying they're dropping RF support entirely in 1.10.2, I would appreciate that since that would be interesting indeed considering their latest release was using RF just fine. No Tesla in the instance either.

**Comment by ktole1999** [comment]
i may have misinterpreted the comments from this post. https://github.com/SleepyTrousers/EnderIO/issues/3992

> MatthiasMann commented 3 days ago
@VT-14 EnderIO items no longer accept RF - only Forge Energy or Tesla.
But EnderIO conduits and machines still support RF when the RF API is available (it is no longer bundled).

@Nuinethir I have several MC 1.10.2 instances with EnderIO, AA and Tesla API - and they work just fine together - I even use the AA battery to charge my EnderIO items in my inventory.

If you have other mods which do not handle Tesla API correctly then that is not EnderIO's fault - either rise that issue with these mods or remove them.

**Comment by Nuinethir** [comment]
The post that @MatthiasMann made to me was oblivious to the fact that other mods still support RF. Ender IO just moved forward and refuses to be backwards compatible. The Tesla API did nothing to assist with the compatibility between Mekanism and Ender IO, in fact, it just made things worse (devices would not connect to each other).

The "we've moved forward, @aidancbrady has old/bad code" is not a solution and quite honestly is immature at best. I have already found a workaround for power management issues (all machines powered by Mekanism). Hell, the only reason I keep Ender IO around is for the mob spawners, automated farming, and as a prereq for Simply Jetpacks.

**Comment by VT-14** [comment]
@ThatGamerBlue I know you've been working on Mek's power API issues.  Which repo would you currently suggest using?

**Comment by ThatGamerBlue** [comment]
@VT-14 for now this repo until I get something decent up on my repo

**Comment by MatthiasMann** [comment]
@Nuinethir EnderIO supports most power APIs available (3 for machines/conduits, 2 for items) - and it works with other mods just fine. We can't provide a work around for every mod which doesn't using the APIs correctly. If you don't like that than I can't help you.

**Comment by FnordMan** [comment]
You can add Actually additions to the list of things that don't accept power from "universal" cables.

**Comment by tterrag1098** [comment]
@Nuinethir You are misunderstanding the issue. Mekanism *does* support Tesla, as does EIO, and in this case it is not working, which is on Mekanism's side. RF is not involved.

**Comment by Nuinethir** [comment]
@tterrag1098 It is confusing since the Tesla API doesn't make much sense from the end user's point of view (it is more geared towards devs from what I gathered). Both mods still to this day report all power and are configured with RF, so if we are switching to Tesla, why still show RF?

**Comment by MatthiasMann** [comment]
@Nuinethir Tesla is just another API to use for power transfer - that doesn't change the unit or value of the power transferred. Basically 1 Tesla == 1 RF == 1 Forge Eenergy.

**Comment by aidancbrady** [comment]
Done
