### ISSUE TITLE
[Suggestion/Request] Tier 4 Sulfuric Acid Ore Proccessing

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [aidancbrady/Mekanism#4180]
In Tier 4 ore processing sulfuric acid is created to turn the ore into a slurry and eventually extract crystals.  However, while this does match certain real world techniques, the sulfuric acid is used in gaseous form and the ore slurry is also a gas.  This strikes me as not just wrong, but absurd.  According to all the research I could do, in real life _liquid_ sulfuric acid is used to create a liquid ore slurry.

Now Minecraft isn't real life, but it does tend to imitate it, and furthermore, if one is going to use a real world technique, it seems only natural to replicate it accurately.  So, while it's not strictly necessary, I for one (and I hope others as well) would love it if the Chemical Dissolution Chamber used liquid Sulfuric acid (which already exists in Mekanism) to produce liquid ore slurry, which was then washed and turned into liquid clean ore slurry.

**Comment by aidancbrady** [comment]
Mekanism's "Gas API" primarily exists to provide a more flexible way to transfer and manage Mekanism's 'chemicals' that are used in many different layers of machinery.  I may restructure the API eventually to further match this definition, but in the meantime I'd rather leave the system the way it is.  Thanks for your concerns though!
