### ISSUE TITLE
Mekanism crashes on minecraft startup

### ISSUE THREAD

**Issue by Frost2779** [aidancbrady/Mekanism#4181]
Whenever I attempt to launch my game it crashes almost immediatly after I hit the Launch button.
Below is the fml-client-latest log(I had to move it into a txt file to upload it):

[fml-client-latest.txt](https://github.com/aidancbrady/Mekanism/files/752472/fml-client-latest.txt)

**Comment by TehStoneMan** [comment]
Latest NVidia video card drivers broke something. Reinstall an older driver.

**Comment by thommy101** [comment]
That, or the newly released version with a bug fix (version 378.57).

**Comment by TehStoneMan** [comment]
It's been fixed? I can update my drivers again?

**Comment by thommy101** [comment]
There is a new version yes. I do not know if it's beta or not.

**Comment by TehStoneMan** [comment]
I've looked into it. It's a hot fix version, not certified, so it's not on the official downloads.
http://nvidia.custhelp.com/app/answers/detail/a_id/4378/~/geforce-hot-fix-driver-version-378.57
