### ISSUE TITLE
LevelUp mod interferes with Atomic Disassembler's Vein mode

### ISSUE THREAD

**Issue by todofixthis** [aidancbrady/Mekanism#4183]
Running Minecraft 1.10.2, Forge 12.18.3.2185, Mekanism 9.2.1.298

1. Install [LevelUp!](https://minecraft.curseforge.com/projects/level-up) mod.
2. Acquire an Atomic Disassembler.
3. Level up and assign points to woodcutting skill.
4. Switch Atomic Disassembler to Vein mode.
5. Break a wood block in a tree.

All of the connected wood blocks should break, but only the clicked block will break.

Note that another mod, [VeinMiner](https://minecraft.curseforge.com/projects/veinminer) works as expected:

1. Install [VeinMiner](https://minecraft.curseforge.com/projects/veinminer).
2. Acquire any axe.
3. Level up and assign points to woodcutting skill.
4. Break a wood block in a tree with VeinMiner active.

This will correctly break all of the wood blocks in the tree (plus, any bonuses from woodcutting skill will be applied).

**Comment by aidancbrady** [comment]
Not totally sure why this would be occurring, but clearly LevelUp! is interfering with some low-level MC functionality. I'm going to leave things be.
