### ISSUE TITLE
[1.10.2] Universal Cables dont xfer power

### ISSUE THREAD

**Issue by Morpheus1101** [aidancbrady/Mekanism#4188]
I have the Ultime Universal Power Cable connected to a draconic creative rf power source whihc is then connected to a draconic Energy pylon feeding into a Draconic Power Storage system, but its not transmitting any power.  I also connected the cable to a Builder from RfTools an also no power is being receieved

**Comment by ThatGamerBlue** [comment]
Our tesla integrations are broken, we're working on it.

**Comment by Morpheus1101** [comment]
Im confused to what Tesla integrations have to do with it not being able to transfer any power at all form anything that produces rf

**Comment by Utildayael** [comment]
TGB, same issue with BDEW's Advanced Generators.  Reposting from:

https://github.com/bdew/generators/issues/132

Universal Cables from Mekanism don't want to attach to the RF producer in Adv Gens. EnderIO conduits work fine. The workaround is to place a Mekanism Energy Cube next to the RF producer and THAT works but they are of course output limited with even the largest cube in Mek being limited to 20k RF/t which is less than a fully built turbine setup [25k]. 

bdlib-1.12.2.21-mc1.10.2
generators-0.9.20.19-mc1.10.2

MC 1.10.2
Forge 12.18.3.2221
Mekanism 1.10.2-9.2.1.295

Thanks

**Comment by bdew** [comment]
Is RF working at all with the cables? I tried them with my mods, i tried with the machines in EnderIO and EU2... it doesn't seem to work at all.

I can use tesla to output into Mek cables, but then they still don't transfer the power to any RF based machine.

**Comment by Morpheus1101** [comment]
RF works if you place a Cube from Mekanism to gather the power then connect the Universal cable to the cube, the pic below is how i use it for EnvironmentalTech Solar power gen.

![2017-02-14_12 31 53](https://cloud.githubusercontent.com/assets/10524952/22912585/e284d7b6-f2b1-11e6-89f6-e43d7f920551.png)
