### ISSUE TITLE
Liquid Monitor Crash with Fluid Pipes

### ISSUE THREAD

**Issue by nerdnosyd** [aidancbrady/Mekanism#4189]
Crash report: http://pastebin.com/Q99GRc7J

Placing an RFTools Liquid Monitor and selecting a Mekanisms liquid pipe with it immediately crashes and corrupts the world, requiring mcedit to remove the offending blocks.

**Comment by ThatGamerBlue** [comment]
*unrelated comment about how its not a duplicate bug* thanks for the report, will investigate.

**Comment by thommy101** [comment]
It's an easy issue. Facing is nullable in any capability related thing and RF Tools uses it, Mekanism doesn't.
It results in a nullpointer at the folowing line:
https://github.com/aidancbrady/Mekanism/blob/1.10/src/main/java/mekanism/common/multipart/PartSidedPipe.java#L158

Sollution would be adding a case at:
https://github.com/aidancbrady/Mekanism/blob/1.10/src/main/java/mekanism/common/multipart/PartMechanicalPipe.java#L259
Which allowes null and returns it (Currently not able to make a pull request)

if(from == null || getConnectionType(from) != ConnectionType.NONE)

Little note: should be fixed for every kind of pipe/fluid capability usage.

**Comment by thommy101** [comment]
On the second look, someone already has a fix available.
See #4185
