### ISSUE TITLE
TileComponentChunkLoader#write assumes that tick() has already been called

### ISSUE THREAD

**Issue by Aaron1011** [aidancbrady/Mekanism#4192]
In [TileComponentChunkloader#write](https://github.com/aidancbrady/Mekanism/blob/2d04343/src/main/java/mekanism/common/tile/component/TileComponentChunkLoader.java#L172), `prevCoord.write` is called. Normally, `tick()` is always called before `write`, ensuring that `prevCoord` has been properly initialized.

However, [SpongeForge](https://github.com/SpongePowered/SpongeForge) creates a Forge `BlockSnapshot` in order to properly fire an event. Since `BlockSnapshot` calls `TileEntity#writeToNBT`, `prevCoord` ends up being used before being initialized, leading to a `NullPointerException`.

It would be a great help to Sponge if you could either add a field initializer for `prevCoord`, or ensure that it's not null before using it in `TileComponentChunkloader#write`. Thanks!

**Comment by ThatGamerBlue** [comment]
sponge is horrible

**Comment by aidancbrady** [comment]
Done!
