### ISSUE TITLE
Fixes available? 1.10.2

### ISSUE THREAD

**Issue by ktole1999** [aidancbrady/Mekanism#4193]
This is not really an issue but more of curiosity. I am glad to see that fixes and patches are being done while Aiden is absent but how are these being distributed? Is there a new download repository?

**Comment by ThatGamerBlue** [comment]
Not yet, working on setting up a CI system to build off the 1.10 branch to my download server.

**Comment by ktole1999** [comment]
excellent thanks for quick response.
