### ISSUE TITLE
Game Crashes when removing Basic Universal Cable

### ISSUE THREAD

**Issue by JackONeill12** [aidancbrady/Mekanism#4194]
The game crashes when i try to remove a Basic Universal Cable.

http://pastebin.com/JzNvaADY

**Comment by ThatGamerBlue** [comment]
Fixed in 1.10 branch #3967

**Comment by JackONeill12** [comment]
Thank you very much.

**Comment by JackONeill12** [comment]
But an additional Question. If it was fixed months ago why is it not in the most recent build on the website?

**Comment by thommy101** [comment]
That's up to Aiden to fix (Mekanism's owner).

**Comment by JackONeill12** [comment]
OK

**Comment by ThatGamerBlue** [comment]
You can build a version yourself from the 1.10 branch, download the zip here: https://github.com/aidancbrady/Mekanism/archive/1.10.zip , unzip it to any folder, open a command window there (shift+rightclick -> open command window here) and type in `gradlew build`, the output should be in `output` folder

**Comment by JackONeill12** [comment]
Thank you

**Comment by ThatGamerBlue** [comment]
a quick word of warning, it does take a while to build

**Comment by JackONeill12** [comment]
sorry to bother you again.

Tried to build:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileApiJava'.
> Could not find tools.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 23.549 secs

**Comment by ThatGamerBlue** [comment]
haven't seen that before, give me a minute and ill build a version and upload it

**Comment by JackONeill12** [comment]
Awesome. Thank you very much.

**Comment by ThatGamerBlue** [comment]
Uploaded, http://thatgamerblue.com/MekanismAll-1.10.2-Not.A.Version.homebaked.jar - This is a replacement for all three jars BTW.

**Comment by JackONeill12** [comment]
Great. Again thx for the help

**Comment by JackONeill12** [comment]
It's me again. Tried with your new version. Still crashing while trying or remove the cable.

**Comment by ThatGamerBlue** [comment]
Very weird, you can reopen I think, @thommy101 what do you think?

**Comment by thommy101** [comment]
Uh, I'm not at my pc right now. Only thing I can think of is mcmultipart. What version of mcmultipart are you using? There's something wrong with the file naming and file version of it. 
The log has another error that the original "can't break cables" bug there was.

Can you try with a fresh download of mcmultipart 1.3.x (latest from curse/curseforge) and post a new crashlog for me please?

**Comment by JackONeill12** [comment]
Was using MCMultiPart-experimental-2.0.0_88-universal.

Downgraded to MCMultiPart-1.3.0-universal.

Still crashes.

http://pastebin.com/PFjnWryR

**Comment by JackONeill12** [comment]
MCMultiPart-1.2.1-universal is working without problems.

So its seems its MCMultiPart-1.3.0 and not Mekanism

**Comment by thommy101** [comment]
I've just setup my dev workspace for 1.10 again, it's working flawless with 1.3.0. It's certainly not a mcmultipart issue.

Are you using any pre-release mods? I can't seem to find "treecapacitor" yet.

**Comment by JackONeill12** [comment]
Yeah I think treecapacitor is prerelease. But it works anyway. Thanks for the help I think this issue can be closed

**Comment by thommy101** [comment]
It's definitely an issue with treecapacitor. Found the download and tried in my test pack. Instant crash on breaking. You could try reporting it to the current maintainer and see if they can solve it. This issue can be closed. If the maintainer of Treecapacitor needs anyhelp, just reach out to me. I can try and help with debugging.

Current maintainer Treecapacitor: https://github.com/lehjr/Treecapitator

**Comment by JackONeill12** [comment]
Thx will do
