### ISSUE TITLE
Reactor - Mechanical Pipes - Etc

### ISSUE THREAD

**Issue by donalderoberts** [aidancbrady/Mekanism#4195]
For the life of me I can't get enough water into my reactor. I am not sure if this is a bug, or I am doing something wrong. I have 40+ electric pipes, fully powered up with speed and energy... The Reactor is then only able to pump 3200mb of steam to the turbine. I have tried many different designs, which include going through a Entangleoporter. All mechanical cables are upgraded. I have sent all water straight to reactor, and I have sent it all through a dynamic tank. No matter what I do it won't change. Is this a known problem? (Currently only FTB Infinity Lite).

**Comment by thommy101** [comment]
Mekanism cables/pipes work a bit different than most mods. If I hook up a turbine to a dynamic tank full of steam, it only uses 6400 mb/t, even if the tank is full with steam. Connecting multiple cables to the dynamic tank gives an higher throughput.

Pictures say more than 1000 words:
http://imgur.com/a/VkOfa (probably in the wrong order, look from bottom up)
