### ISSUE TITLE
Obsidian leggings give +12 armor

### ISSUE THREAD

**Issue by tacgnol06** [aidancbrady/Mekanism#4196]
Obsidian leggings are way out of balance with the other leggings and other obsidian pieces. Well, actually, MOST of the tools and armor are completely out of balance with both vanilla and other mods (for example, you have to go to Draconic Evolution to find other swords that beat out the default 14 damage your obsidian swords does, and that's BEFORE enchants. And Bronze does 10?). However, I'm assuming the leggings are a bug given just how out of line they are, combined with the fact that tweaking the config doesn't seem to effect them at all.

**Comment by aidancbrady** [comment]
Fixed- somehow armor balance values were reversed for armor indices.
