### ISSUE TITLE
[1.10.2] Server crash on loading mekanism chunks, stackoverflow error

### ISSUE THREAD

**Issue by SpatiumPrinceps** [aidancbrady/Mekanism#4197]
Hello everyone,

yesterday night a friend built a dynamic tank on our server. 
He said, he followed the instructions on the wiki: he built a casing with dynamic tank blocks 18 * 18 * 18 and filled the sides with structural glass. At one point he switched one glass block to a dynamic valve in order to insert some fluids. It didnt work... 
Now, as soon as he joins the server, the game crashs. I wanted to check out his base to break the tank, but the server also crashed as soon as I loaded the critical chunks. 
We are trapped and cant go on playing, no matter if the tank is broken or not. 

Minecraft: 1.10.2
Forge: 2185
Mekanism: Tank was built on 295, but I just updated the mod to 298 hoping the issue would be resolved - it wasnt. 

Crash report: [pastebin.com](http://pastebin.com/yw06uP28)

Probably someone can take a look at this issue...

Thank you in advance :)
Greetings, 
Spatium

**Comment by thommy101** [comment]
You can try and replace the blocks with an offline edit tool like mcedit (if that one still works, there are enough ones to find).
The max size is indeed 18*18*18, but I wouldn't recommend building it that large. There are some flaws in the multiblock detection. I recommend building it max 14*14, centred in a chunk. This way you'll have it always fully loaded with all pipes/conduits attached to it.

**Comment by SpatiumPrinceps** [comment]
Well, I installed WorldEdit, selected the area without entering the specific chunks and setted dynamic tank blocks to 0. 
Not a perfect solution, by far not. Atleast we are able to play again.

**Comment by thommy101** [comment]
Oh, thats also a solution. I must try and remember that one.
Luckely you've solved it! Thanks for closing the issue.
