### ISSUE TITLE
Metallurgic Infuser dosen't work (All the Mods)

### ISSUE THREAD

**Issue by Totulotu** [aidancbrady/Mekanism#4198]
I play All the Mods modpack and for some reason metallurgic infuser dosen't infuse some things. 
It infuses osmium to circuit but most of the recpies dosent work. Does the JEI (Just Enough Items) shows wrong recpies?

**Comment by JaSpr** [comment]
Different items require different things to infuse it with.  E.g. some items need redstone (like osmium to circuit board) but some need obsidian dust and some need diamond dust.  Can you list any recipes you're having problems with?

**Comment by Totulotu** [comment]
One thing that Im having problem with is Atomic alloy. I put refined obsidian dust to purple slot and reinforced alloy to the red slot and i have power on metallurgic infuser but nothing happens.

**Comment by ThatGamerBlue** [comment]
screenshots?

-- ThatGamerBlue
