### ISSUE TITLE
[1.7.10] EnderIO Gas Conduit not visually connecting to Chemical Oxidizer, but still works.

### ISSUE THREAD

**Issue by Kiefy** [aidancbrady/Mekanism#4199]
The Conduit is passing the gas :) but **visually** does not connect to the Oxidizer.

They connect with all the other machines correctly. Only the Chemical Oxidizer misbehaves.
![Ore Processing](http://image.prntscr.com/image/5c6b7efd75fb4f07b9861a3b0f22264c.png)
- Forge-10.13.4.1614
- Mekanism-9.1.0.281
- EnderIO-2.3.0.429

**Comment by aidancbrady** [comment]
The Chemical Oxidizer functions entirely as a gas outputter, it doesn't have an internal reserve.  Mekanism's implementation allows for forced connections, this incompatibility is because EnderIO's does not.

**Comment by Kiefy** [comment]
better late than never :P
