### ISSUE TITLE
Compatability with Extra Utilities 2 + Can't enrich some ores

### ISSUE THREAD

**Issue by tenten8401** [aidancbrady/Mekanism#4200]
Can we get compatibility with Mekanism pipes for Extra Utilities 2? Can't use mechanical pipes to pump into an XU2 Crusher.
![image](https://cloud.githubusercontent.com/assets/6174343/22866964/77aacaa6-f14c-11e6-8d9f-6bd7584b09be.png)
The only reason I'd like to use the XU2 crusher is because it can convert most of the ores into dust, and the enriching factory from Mekanism cannot. For instance, the XU2 Crusher can crush up IC2 uranium ore, but the Mekanism enrichment factory cannot:
![image](https://cloud.githubusercontent.com/assets/6174343/22866959/5bbab39c-f14c-11e6-82ed-653dc16aa72f.png)
vs.
![image](https://cloud.githubusercontent.com/assets/6174343/22866961/64342cc4-f14c-11e6-85ea-5c530e10e760.png)

**Comment by JaSpr** [comment]
Also, the mekanism crusher cannot crush uranium ore.

**Comment by thommy101** [comment]
Uranium ore should be working in the latest version of the 1.10 branch.
See commit: https://github.com/aidancbrady/Mekanism/commit/33aed2341a1a59284f2e1e62df674f8bdd2ce9fe

**Comment by JaSpr** [comment]
Hmm. the modpack we're running just updated last week or so. Currently running 9.2.1.298. Don't know how to check if this commit was included in that release.

**Comment by thommy101** [comment]
Just checked, latest version (298) is still made of the master branch. Sadly it doesn't include the 26 commits of the 1.10 branch.

**Comment by thiakil** [comment]
Mekanism still largely does not support the Capability item handlers, likely ExU2 only supports the Capability; therefore this is part of the larger issue of Capability support.
