### ISSUE TITLE
Miner silk touch stack creation

### ISSUE THREAD

**Issue by rubensworks** [aidancbrady/Mekanism#4202]
The miner seems to [call `Block#getMetaFromState` directly](https://github.com/aidancbrady/Mekanism/blob/81e810794581cabba8925634f93f1323400014cb/src/main/java/mekanism/common/util/MinerUtils.java#L34) instead of invoking `Block#createStackedBlock` when creating `ItemStacks` for silk touched blocks.
The vanilla silk touch logic will also invoke `Block#createStackedBlock`, as can be seen in Block#harvestBlock.
The problem is that this can set a non-zero metavalue to the `ItemStack`, even if this is not intended by the block.

This causes issues like CyclopsMC/EvilCraft#515, and possibly also for other blocks like vanilla Redstone when it is activated.

**Comment by aidancbrady** [comment]
Fixed, thanks
