### ISSUE TITLE
Universal cables don't work with actually aditions and EnderIO

### ISSUE THREAD

**Issue by NerdCraft** [aidancbrady/Mekanism#4203]
![2017-02-13_20 42 24](https://cloud.githubusercontent.com/assets/13489837/22906983/27242342-f22e-11e6-80ff-fc984b73aeff.png)

**Comment by ThatGamerBlue** [comment]
Duplicate of roughly half the issues on here. Not sure what one we're meant to be using but it's a duplicate, please close :)
