### ISSUE TITLE
Machine/item ownership restricts by username, not UUID

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [aidancbrady/Mekanism#4204]
I just changed my Minecraft account name, and logged into a server to discover that my machines were locked and now considered owned by another player.

The ownership system should be using the player persistent player UUID.

**Comment by ThatGamerBlue** [comment]
Thanks for the report, will be fixed for next Major (breaking) version

**Comment by thommy101** [comment]
Just a heads up: I'm currently working on this issue, changing all usernames to UUIDs.
Expect a WIP pull request in an hour or so.

**Comment by aidancbrady** [comment]
Done!

**Comment by MrMetric** [comment]
Any chance of getting this fixed in 1.7.10?

**Comment by Lord-i7** [comment]
Please fix the 1.7.10 mod file too

**Comment by thiakil** [comment]
1.7 is no longer supported.

**Comment by Lord-i7** [comment]
The UUID system or the mod
Cause the mod is still supported

**Comment by Tahakk** [comment]
Mod is supported, but not on 1.7, if you want new features go and play 1.12

**Comment by MrMetric** [comment]
Would it really be that hard to fix the issue and make a new build?

**Comment by thiakil** [comment]
It is not a simple change. And like has been said, we do not support 1.7

**Comment by Lion4K** [comment]
Where are the data stored on the server?
A player of mine wanted to give ALL of his stuff to another player, I did so replacing his UUID for the one of his friend on all server files, and everything went to him, except Mekanism stuff.
