### ISSUE TITLE
PSA: If minecraft doesn't launch update your nvidia drivers.

### ISSUE THREAD

**Issue by ThatGamerBlue** [aidancbrady/Mekanism#4205]
It's now safe to update through geforce, a patch has been pushed through geforce today, go update!

**Comment by leonardopsantos** [comment]
I was getting an error:

[22:57:44 ERROR]: Game ended with bad state (exit code -1073740791)

And upgrading to the latest nvidia drivers (378.66) resolved the issue! The funny things was that stock Minecraft wasn't crashing! I could play with or without mods like IC2, it was just when I installed Mekanism that the game began to crash on startup!

Thank you for your solution!

**Comment by ThatGamerBlue** [comment]
@leonardopsantos the problem was the texturemap, all the texture get stitched together into one big file in memory and the drivers didn't handle that very well, mekanism has a lot of textures compared to most mods.
