### ISSUE TITLE
Deleted Portable Teleporter destinations return every log on.

### ISSUE THREAD

**Issue by Apocryphai** [aidancbrady/Mekanism#4207]
Mekanism version 1.10.2-9.2.1.295

Teleporter destinations that no longer exist cannot be deleted from the Portable Teleporter. They always return to the portable teleporter the next time the client logs on. Even destroying the portable teleporter and crafting a new one doesn't get remove the non-existent destinations from it's memory.

Given that the mouse wheel doesn't scroll the destinations list and the scroll bar is incredibly tiny and difficult to grab and scroll it'd be really nice to be able to clean up the destinations list a bit :)

**Comment by thommy101** [comment]
The teleporter doesn't have "destinations". It has frequencies, when two teleporters have the same frequency they are linked up. You can delete a frequency by selecting it and clicking delete. Even if no teleporter is using a frequency, you still can delete it (if not, let me know how you reproduce it).

I agree, the scrolling part is quite small on a small GUI scale. Would be nice if it could scroll with your mouse wheel.

**Comment by WywySenariosa** [comment]
I also have this problem. It isn't just me. The frequency keeps on coming back and my AFK channel needs to be scrolled to
