### ISSUE TITLE
[Feature Request] Processing raw emerald ore (similar to how diamond ore works)

### ISSUE THREAD

**Issue by JaSpr** [aidancbrady/Mekanism#4211]
Currently, we can send raw diamond ore through the enrichment chamber to get 2x returns. Emerald ore, however, can't be processed this way, and there's no way to get the emeralds out without taking the blocks, placing them in the world, and manually breaking them with a pickaxe. This can be extremely tedious when you have 4 full stacks of emerald ore from a trip with the digital miner (2 stacks of nether emerald ore through the smelter returns 4 stacks of plain emerald ore).

**Comment by ktole1999** [comment]
if it wont smelt then send to block breaker.

**Comment by JaSpr** [comment]
I was able to find a temporary solution of using the Sag Mill from EnderIO (it's the ONLY thing that will convert emerald ore to emerald.)

**Comment by thiakil** [comment]
There is an API/IMC message to do this, you could see if BoP(?) would want to add it, or if Mine/CraftTweaker supports it.

**Comment by laz2727** [comment]
One slight problem. It's a vanilla ore.

**Comment by thiakil** [comment]
Somehow I got confused with Ruby or something! whoops lol

**Comment by aidancbrady** [comment]
Done!
