### ISSUE TITLE
[Long running bug] Taking damage while flying throws you down super fast

### ISSUE THREAD

**Issue by TheUnderTaker11** [aidancbrady/Mekanism#4213]
When you use the jetpack and take any damage it throws you down at an insane speed. This is a big problem considering the fact flying over lava is a death sentence. If I get hit by a ghast it can throw me into lava, catching me on fire and throwing me down each hit I take of fire damage. Same concept with when a blaze hits you. Overall it really screws you over.

**Comment by Paul17041993** [comment]
Temporary workaround; switch to hover mode when taking damage, you should remain at the same altitude.

**Comment by TheUnderTaker11** [comment]
Alright if it's known I'll go ahead and close this. Also it was funny to use with slime boots above ground, since it threw me down so fast the slime boots launched me up a crazy amount into the air.
