### ISSUE TITLE
[1.10, 9.2.1] Logistical Sorter default route non-functional

### ISSUE THREAD

**Issue by Paul17041993** [aidancbrady/Mekanism#4214]
Placing the sorter on a chest with misc items coming in, a cobble filter set as the only filter, there's absolutely no way to get the default route to work. Even when using the filter in-line and/or having the default as the same colour as the filter, it remains jammed and/or will only ever allow the filtered item through. Round-robin, auto-eject and filter settings all make no difference.

**Comment by aidancbrady** [comment]
Should be fixed in latest release
