### ISSUE TITLE
[Feature] Capacity on Dynamic Tanks

### ISSUE THREAD

**Issue by Utildayael** [aidancbrady/Mekanism#4216]
Minor GUI request. Dynamic tanks show their volume, as in, this is how many blocks they are. IE: 350. What it doesn't seem to show is the total fluid capacity of the tank as-built. 

If you fill the tank up fully you will know of course... or if you know it is 64b per block [I think?] you can do the math using the volume calc it feeds you but... would be nice if in the GUI it would show you what the max capacity is. This is similar to my request for the Induction Matrix to show you the max capacity without having to sit and do all the math [or wait for it to fill up 100%].

Thanks :)

**Comment by thiakil** [comment]
There should be a tooltip when you hover over the 'graph' of the filled amount?

**Comment by Utildayael** [comment]
Filled yes but would be nice to have x of y, aka 1000mb of 10000mb. Basically see *max* capacity without tank having to be full.

**Comment by thiakil** [comment]
It's been a while since I've used one, I thought it did have that x of y or x/y type display, my bad.

**Comment by Utildayael** [comment]
No worries. I thought it used to show it in Mek 7 or 8 tbh tho I don't know why it would have been discontinued in 9. I may be crazy too. :)

**Comment by aidancbrady** [comment]
Merging this with #3647
