### ISSUE TITLE
Tesseract/Fluxduct (from Thermal Expansion) don't work on Industrial Turbine.

### ISSUE THREAD

**Issue by MrDiabli** [aidancbrady/Mekanism#4220]
Hello,

I'm actually building an industrial turbine but when I try to join this turbine with my Induction Matrix it doesn't work. After a few test, I have come to the conclusion that the valves from the turbine don't send any energy when a Tesseract or a Cryo-Stabilised Fluxduct is connected just on it but if I put an universal cable and then a Tesseract/Fluxduct, then it works.
I couldn't find anything about that on internet. I believe that it is a bug, but I'm not sure.

Thanks in advance. And thanks to the dev of this huge and powerful mod :)

**Comment by aidancbrady** [comment]
Should be fixed
