### ISSUE TITLE
[1.10.2-9.2.1.298] - Digital Miner cannot filter by "Tinkers' Construct" because apostrophes are not allowed

### ISSUE THREAD

**Issue by JaSpr** [aidancbrady/Mekanism#4222]
While testing, I discovered that the "modid" filter type for the digital miner is actually a filter by mode NAME.  In attempting to add a filter for "Tinkers' Construct" I was unable to do so, because the apostrophe character was not getting typed.  I did try without the apostrophe ("Tinkers Construct") and by the actual modid (tconstruct) but no ores were found, even though they ARE found when filtering by oreDict "oreCobalt".

**Comment by aidancbrady** [comment]
Fixed, thanks!
