### ISSUE TITLE
[1.10.2-9.2.1.298] - No factory equipped to convert "Draconium Ore" or "Nether Draconium Ore" to dust.

### ISSUE THREAD

**Issue by JaSpr** [aidancbrady/Mekanism#4223]
By default, a pickaxe will turn draconium ore to draconium dust.  When using the digital miner with Silk Touch, you get the original ore, but the ores cannot be handled by any Mekanism factories, therefore it has to be taken out of the miner and manually mined into dust, before then being put back in the system to let the smelting factory convert that dust to ingots (which does work).

**Comment by ktole1999** [comment]
you could have it routed to a block placer/block breaker and then sucked back into the system

**Comment by JaSpr** [comment]
That's what I'm considering for now.

**Comment by JaSpr** [comment]
Resolution pending integration from #4239
