### ISSUE TITLE
[1.10.2-9.2.1.298] Plastic Fence colors inverse of itemblock colors.

### ISSUE THREAD

**Issue by mallrat208** [aidancbrady/Mekanism#4227]
Mekanism: 9.2.1.298
Forge: 12.18.3.2234

It appears that the color of the fences is reversed between the item form and the actual block form.

Black is for example meta 0 as an Item, but is 15 as a Fence. The end result is you end up with a Black item placed in world looking like a White Fence.

![Fence Color Mismatch](http://puu.sh/ucUka/47f4a49396.jpg)

**Comment by thommy101** [comment]
It's fixed in the 1.10 branch.
It's up to @aidancbrady to merge it in the master branch or finally make a build of the 1.10 branch.
