### ISSUE TITLE
[1.10.2-9.2.1.298] Issue with dependencies.info

### ISSUE THREAD

**Issue by NillerUdenDild** [aidancbrady/Mekanism#4228]
Hey!

I have an issue, where Mekanism keeps changing my MCMultiPart version "MCMultiPart-experimental-2.0.0_88-universal". I believe this is caused by the dependencies.info file in Mekanism. Because of this issue, some players aren't able to join my server. 
So I would like to ask, would it be okay if I edit the dependencies.info file, and release it via my modpack, on curse? I will ofcourse note the change in the changelog, and in no way take credit for the mod.

**Comment by thommy101** [comment]
You could also compile the 1.10 branch yourself which totally removes the need for the dependencies.info file ;) It's possible (and allowed by the license) to redistribute it. I'm also distributing a custom compiled version in my modpack through Curse (althrough it doesn't contain all the fixes of the 1.10 branch).

**Comment by NillerUdenDild** [comment]
Thanks for the quick answer :D

**Comment by SteelShot** [comment]
Or if this is still relevant to anyone? Open Mekanism-1.10.2-x.x.jar with Winrar, 7z or any other software that works with .zip files. Edit the dependancies.info ->

{
	"repo": "http://maven.amadornes.com/MCMultiPart/MCMultiPart/1.4.0/",
	"file": "MCMultiPart-1.4.0-universal.jar",
	"dev": "MCMultiPart-1.4.0-deobf.jar",
	"class": "mcmultipart.MCMultiPartMod"
}

No need to recompile
