### ISSUE TITLE
Brine behaves visibly as a gas, although requires liquid containers and pipes

### ISSUE THREAD

**Issue by JaSpr** [aidancbrady/Mekanism#4231]
Visually brine behaves as a gas.  Even in a massive dynamic tank, having even a little bit of brine in it, the tank will appear to have a slight tinge of beige.  As the tank gets more full, the beige will get more opaque, but at no time is there visually any sense that the brine is filling x-amount of the container (except in the GUI).

[Screenshot.](http://i.imgur.com/KAOrQhH.png)

**Comment by aidancbrady** [comment]
Fixed, thanks
