### ISSUE TITLE
Boiler & Industrial Turbine crash

### ISSUE THREAD

**Issue by craft90** [aidancbrady/Mekanism#4243]
So yeah as of 9.1.281 for 1.7.10 Minecraft crashes when you try to use the interface on either the Thermoelectric Boiler or the Industrial Turbine when trying to input steam or water via pipes transfering from bedrockium drums from Extra Utilities. It's quite the annoyance. I looked around and it has been reported before but as far as I can tell it was only fixed in 1.10 Yes, I understand that 1.7.10 is outdated nowadays and I guess it could be considered unsupported. It's just unfortunate that so many other mods still hasn't made the jump over. So I'm stuck in this version.
But have you absolutely no intention of back-porting a fix like that? It's a pretty critical bug and it sucks to just leave it in an old build.

I don't know if it's just broken in 9.1.281 If it's not I could downgrade and stick with an older version.

I'm also concerned that the fusion reactor may be broken in a similar way...

But anyway here's some crash reports
http://pastebin.com/JR6R0hqN - Boiler crash
http://pastebin.com/nAhffudj - Turbine crash

**Comment by craft90** [comment]
Welp, and now the world is utterly broken. I guess I'll have to stay away from the Boiler and Turbine. 
http://pastebin.com/sMmkbD3i

**Comment by LorentzNL** [comment]
Hey craft90 i had the same issue with Turbine. To solve the world crash Delete the mekanism Generator mod. start server again and it should be running again. After that you can reinstall the mod. Thi si what solved it for me

**Comment by ktole1999** [comment]
yes but how much world damage will you do by removing the generator mod from blocks already placed.

**Comment by aidancbrady** [comment]
Should be fixed in 1.11.2 versions. 1.7 is no longer supported
