### ISSUE TITLE
About the digital miner

### ISSUE THREAD

**Issue by forestbat** [aidancbrady/Mekanism#4244]
The digital miner will stop working if the player leave a long distance，even if the player is loading the chunk and there still has mine in the chunk。
And the number of mine what the digital miner counts is 0，the player must reset the miner。
So I hope you can solve the problem as soon as possible。

**Comment by forestbat** [comment]
Yes，It‘s version is 9.2.1.298。

**Comment by PJB3005** [comment]
Tried the digital miner's own chunk loading upgrade?

**Comment by forestbat** [comment]
@PJB3005 No，it is not useful。

**Comment by ktole1999** [comment]
the miner count changing to 0 or a lesser value of the actual blocks being mined is an issue since 1.7.10. stop miner, reset and then start. it will correctly count the blocks. Yes the anchor upgrade is usefull.

**Comment by forestbat** [comment]
@ktole1999 But as long as I leave the miner，it will stop and count become 0 so I must reset the machine again and again……

**Comment by ktole1999** [comment]
what chunkloader are you using? the miner anchor or another version? Is this SSP or SMP. Are there any resrictions for chunkloading.

**Comment by forestbat** [comment]
@ktole1999 I use FTB Utilities。

**Comment by ktole1999** [comment]
ftbu chunkloading may not work as intended for the miner. not all chunkloaders work the same way. if you have ic2 you can use their chunkloader. There is a mod called persistent bits that has a chunkloader. railcraft has anchors.

**Comment by VT-14** [comment]
Are you loading the entire mining area or just the Digital Miner's chunk?

**Comment by forestbat** [comment]
@VT-14 Just the digital miner‘s chunk。

**Comment by VT-14** [comment]
Well, that's your problem.  The Digital Miner doesn't chunk load anything (except for that upgrade, and I'm not sure how that works).

When you leave the area, the surrounding chunks unload.  The Digital Miner can only mine in its chunk, and quickly reaches the end of its mining area, says "Done," and shuts down.

**Comment by ate0ate** [comment]
Yeah, I used to encounter this all the time until I realised you had to keep the miner AND the chunks to be mined loaded. I use chickenchunks chunkloader, set the size it keeps loaded accordingly and it always works flawlessly for me.
