### ISSUE TITLE
Cant download old 1.7.10 versions 

### ISSUE THREAD

**Issue by 31trainman** [aidancbrady/Mekanism#4246]
I can't download the 1.7.10 versions of your mod from your website and the old download page says this
Warning: Invalid argument supplied for foreach() in /home/aidan/public_html/wp-content/plugins/jenkins-wordpress/Jenkins_Wordpress.php on line 128

**Comment by MastaC729** [comment]
Try again, I was able to download the latest 1.7.10 build posted on his website.
