### ISSUE TITLE
[1.7.10] Not removed recipes

### ISSUE THREAD

**Issue by Shurik1236** [aidancbrady/Mekanism#4249]
Изменяю рецепты через MineTweaker и столкнулся с такой проблемой...
Старые рецепты не удаляются. Если перезагрузить MT, то всё работает. Но при запуске игры старые рецепты остаются. Каждый раз при запуске нужно вводить /mt reload. Можно это исправить?
Причём это только с рецептами на верстаке из mekanism.

(Online translator)
Change the recipes via MineTweaker and faced with such problem...
Old recipes are not removed. If you restart MT, it works. But when I run a game old the recipes are. Every time you start need to type /mt reload. You can fix this?
And it is only with recipes on the workbench from mekanism.

**Comment by aidancbrady** [comment]
Not sure why this would be occurring, Mekanism's recipe registrations have always been handled the same way.  Note that 1.7.10 is no longer supported.
