### ISSUE TITLE
Refined Storage Core does not accept power from Universal Cables.

### ISSUE THREAD

**Issue by JacobMuken** [aidancbrady/Mekanism#4252]
Issue description:

Refined Storage Core does not accept power from Universal Cables.
Tried connecting it to an alloy smelter from Ender IO, same deal.
Edit number 3, I don't think they transfer power to anything thats not mekanism, thats a problem

What happens:

Nothing

What you expected to happen:

Something

Steps to reproduce:

Put down a core
Put down a power source
Connect with a Universal Cable
Pat yourself on the back for a job well done

Version (Make sure you are on the latest version before reporting):

Minecraft: 1.10.2
Forge: 12.18.3.2239
Mekanism: 9.2.1.295
Does this issue occur on a server? [no]

Extra Notes

The cable physically connects to the core and power flows into the cable, but nothing enters the core.

I just copy and pasted the Refined storage ticket and made little edits

**Comment by Bluexin** [comment]
might be linked to #4148

**Comment by SteveSutton1989** [comment]
Have you tried setting the cable to pull aswell as set to input/output on the relevant machines sides? Sometimes both have to be done. 
There is an existing issue with compatibility of drawing from an ender IO capacitor but not pushing into it and may have the same issue here. 
Usually a work around by using another power storage or cable as a pass through or buffer.

**Comment by thommy101** [comment]
Refined storage works fine for me with an energycube and any cable (from Mekanism).
Did you forget to switch the energycubes side to output?
