### ISSUE TITLE
Forge Multipart 1.6.4 Crash

### ISSUE THREAD

**Issue by leosefcik** [aidancbrady/Mekanism#4253]
I have downloaded the latest 1.6.4 legacy version of Mekanism, and when it installs forge multipart, it always crashes when opening a world. The mod forces me to download it, so is there a way to skip the multipart or another solution?

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 3.3.2017 17:10
Description: Unexpected error

java.lang.NullPointerException
	at com.slimevoid.littleblocks.world.LittleWorldClient.func_82737_E(LittleWorldClient.java:118)
	at codechicken.multipart.TickScheduler$WorldTickScheduler.loadTag(TickScheduler.scala:110)
	at codechicken.multipart.TickScheduler$WorldTickScheduler.load(TickScheduler.scala:102)
	at codechicken.lib.world.WorldExtensionManager.onWorldLoad(WorldExtensionManager.java:220)
	at codechicken.lib.world.WorldExtensionManager.access$100(WorldExtensionManager.java:25)
	at codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler.onWorldLoad(WorldExtensionManager.java:88)
	at net.minecraftforge.event.ASMEventHandler_136_WorldExtensionEventHandler_onWorldLoad_Load.invoke(.dynamic)
	at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:39)
	at net.minecraftforge.event.EventBus.post(EventBus.java:108)
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:69)
	at com.slimevoid.littleblocks.world.LittleWorldClient.<init>(LittleWorldClient.java:42)
	at com.slimevoid.littleblocks.client.events.WorldClientEvent.onWorldLoad(WorldClientEvent.java:45)
	at net.minecraftforge.event.ASMEventHandler_102_WorldClientEvent_onWorldLoad_Load.invoke(.dynamic)
	at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:39)
	at net.minecraftforge.event.EventBus.post(EventBus.java:108)
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:69)
	at net.minecraft.client.multiplayer.NetClientHandler.func_72455_a(NetClientHandler.java:354)
	at net.minecraft.network.packet.Packet1Login.func_73279_a(Packet1Login.java:119)
	at net.minecraft.network.MemoryConnection.func_74428_b(MemoryConnection.java:89)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1967)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
	at net.minecraft.client.main.Main.main(SourceFile:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.6.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_80, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 248776336 bytes (237 MB) / 771346432 bytes (735 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Suspicious classes: FML and Forge are installed
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 59 mods loaded, 58 mods active
	mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	FML{6.4.49.965} [Forge Mod Loader] (minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	Forge{9.11.1.965} [Minecraft Forge] (minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	CodeChickenCore{0.9.0.9} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	cuchaz.ships{1.0} [Ships Mod] (shipsMod-v1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	TooManyItems{1.6.4} [TooManyItems] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	grim3212core{V0.1 - 1.6.2} [Grim3212 Core] (grim3212_core_1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	GulliverForged{0.14.3} [Gulliver Forged] (gulliverforged-965-0.14.3-MC1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	Trapcraft{v2.1.0a} [Trapcraft] (14165867113_Trapcraft-Mod-1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	TeNNoX_Bacteria{2.0.5} [Bacteria] ([1.6.4] Bacteria Mod v2.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	TeNNoX_CustomSelectionBox{1.2.1} [CustomSelectionBox] ([1.6.4] Custom Selection Box v1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	TeNNoX_KeyAndCodeLock{1.3.2} [Key and Code Lock] ([1.6.4] Key and Code Lock v1.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	LaserMod{v1.0.0} [Laser Mod] ([1.6.x] LaserMod - v1.0.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	cfm{3.2.9.2} [§6MrCrayfish's Furniture Mod] ([Forge]FurnitureModv3.2.9.2(1.6.4).zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	ccm{1.0.1} [MrCrayfish's Construction Mod] ([Forge]MrCrayfishConstructionModv1.0.5 (1.6.4) (1).zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	ArchimedesShipsMod{1.6.4 v1.4.5} [Archimedes' Ships] (Archimedes-Ships-Mod-1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	BiblioCraft{1.5.5} [BiblioCraft] (BiblioCraft[v1.5.5].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	Billund{1.0} [BILLUND] (BILLUND1.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	bouncingblockmod{2.1 for 1.6.4 (FORGE 9.11.1.916)} [Bouncing Block Mod] (BouncingBlockMod-v21.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	BuildCraft|Core{4.2.2} [BuildCraft] (BuildCraft-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	BuildCraft|Builders{4.2.2} [BC Builders] (BuildCraft-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	BuildCraft|Energy{4.2.2} [BC Energy] (BuildCraft-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	BuildCraft|Factory{4.2.2} [BC Factory] (BuildCraft-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	BuildCraft|Transport{4.2.2} [BC Transport] (BuildCraft-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	BuildCraft|Silicon{4.2.2} [BC Silicon] (BuildCraft-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	CarpentersBlocks{3.2.8.6} [Carpenter's Blocks] (Carpenter's Blocks v3.2.8.6 - MC 1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	ChickenBones{1.0} [The Chicken Bones Mod: You can pick up chicks!] (ChickenBones.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	CloneCraft{1.2} [CloneCraft] (CloneCraft v2.0 MC1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	ComputerCraft{1.63} [ComputerCraft] (ComputerCraft1.63.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	craftguide{1.5.2} [CraftGuide] (CraftGuideMod1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	dimdoors{2.2.4-349} [Dimensional Doors] (DimensionalDoors-2.2.4-349.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	dualhotbar{1.5} [Dual Hotbar] (Dual-Hotbars-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	EnhancedPortals3{${version}} [EnhancedPortals] (Enhanced-Portals-3-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	iChunUtil{2.4.0} [iChunUtil] (iChun-Util-Mod-1.6.x.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	PortalGun{2.0.1} [PortalGun] (filespg^PortalGun2.0.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	ftfloocraft{0.2, for Minecraft 1.6.4} [Floocraft] (Floocraft-Mod-1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	GraviGun{2.0.0} [GraviGun] (Gravity-Gun-Mod-1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	SlimevoidLib{2.1.0.0} [Slimevoid Library] (SlimevoidLib-1.6.4-2.1.0.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	LittleBlocks{2.2.4.1} [Little Blocks] (LittleBlocks-1.6.4-2.2.3.1-Gulliver.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	MagicClover{0.3.1} [Magic Clover] (Magic-Clover-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	mca{3.6.0} [Minecraft Comes Alive] (MCA-3.6.0_MC-1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	Mekanism{6.0.5} [Mekanism] (Mekanism-6.0.5.46.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	MekanismGenerators{6.0.5} [MekanismGenerators] (MekanismGenerators-6.0.5.46.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	MekanismTools{6.0.5} [MekanismTools] (MekanismTools-6.0.5.46.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	MoarSigns{1.0.1} [MoarSigns] (MoarSigns-1.6.4-1.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	UniversalElectricity{3.0.0} [Universal Electricity] (Universal-Electricity-3.0.0.1-dev.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	OpenComputers|Core{1.0.0} [OpenComputers (Core)] (OpenComputers-MC1.6.4-1.2.0-pre3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	OpenComputers{1.2.0-pre3} [OpenComputers] (OpenComputers-MC1.6.4-1.2.0-pre3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	PaperMarioMod{v1} [PaperMarioMod] (PaperMarioMod.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	mod_ReiMinimap{v3.4_01 [1.6.2]} [mod_ReiMinimap] (Reis-Minimap-1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	secretroomsmod{4.6.2} [The SecretRoomsMod] (SecretRoomsMod-universal-1.6.4-4.6.2.324.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	Sync{2.0.0} [Sync] (Sync-Mod-1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	timecontrol{V0.1 - 1.6.2} [Time Control] (Time-Control-Remote-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	TooMuchTNT{2.6} [TooMuchTNT] (TooMuchTNT v2.6) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	trollstuff{1.4.1.32 alpha} [TrollStuff] (TrollStuff 1.4.1 alpha - MC 1.6.4 (1).zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	ForgeMultipart{1.0.1.268} [Forge Multipart] (ForgeMultipart-universal-1.6.4-1.0.1.268.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	McMultipart{1.0.1.268} [Minecraft Multipart Plugin] (ForgeMultipart-universal-1.6.4-1.0.1.268.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	ForgeMicroblock{1.0.1.268} [Forge Microblocks] (ForgeMultipart-universal-1.6.4-1.0.1.268.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	timecontrol_dummy{V0.1 - 1.6.4} [Time Control_Dummy] (minecraft.jar) Unloaded->Disabled
	Launched Version: 1.6.4-Forge9.11.1.965-GulliverForged0.14.3
	LWJGL: 2.9.0
	OpenGL: GeForce GT 630M/PCIe/SSE2 GL version 4.5.0 NVIDIA 376.19, NVIDIA Corporation
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Pack: Default
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

**Comment by ktole1999** [comment]
have you tried removing the mcmultipart mod?

**Comment by ThatGamerBlue** [comment]
Remove LittleBlocks

**Comment by leosefcik** [comment]
But when i remove mc multipart, mekanism needs it to work.

**Comment by ktole1999** [comment]
so is the issue a duplicate mod or mod compatibility?

**Comment by leosefcik** [comment]
I think so... but what is so bad about Little Blocks is incompatible?

**Comment by ktole1999** [comment]
i would post this on little blocks tracker and see what they have to say.

**Comment by leosefcik** [comment]
Yeah, but do you know how to fix it? If no, i will send the report to them.

**Comment by leosefcik** [comment]
I have found this post about a crash:
http://www.minecraftforum.net/forums/support/modded-client-support/2133220-little-blocks-1-7-2-crash
