### ISSUE TITLE
Question about adding Recipes via IMC

### ISSUE THREAD

**Issue by mallrat208** [aidancbrady/Mekanism#4254]
Mekanism: 1.10.2-2.1.298

I'm working on a small modpack and am currently trying to add some recipes to Mekanism machines, given there is no CraftTweaker or ModTweaker support, I've opted to instead make a mod myself to handle it. 

I've run into a small problem however. Recipes when added via IMC do not show up in JEI. They still work and function as expected, there's just no way to tell that the recipe was registered. If there any way to make them show up properly when using IMC, or should I ignore the warning at the top of the RecipeHelper class  in the MDK about it being depreciated?

**Comment by aidancbrady** [comment]
This may be because JEI loads recipes before IMC messages are handled.  Take a look and see if JEI has any kind of helper method to reload or add recipes.

**Comment by mallrat208** [comment]
So for the record if anyone sees this at a later point, the answer seems to be no, at least not with how Mekanism's JEI support is done.

If you want your recipes to show up in game, you may as well make a mod and manually add them ignoring IMC all together.
