### ISSUE TITLE
Hovering Advanced Tank Crash

### ISSUE THREAD

**Issue by mk0003** [aidancbrady/Mekanism#4255]
I am playing Nameless 1.10 pack.
I have a advanced tank full of Liquid Coralium(AbyssalCraft). When i hovering the item game crashes. (Crash file name is crash-2017-03-07_21.31.49-client)

Crash Log: http://pastebin.com/ukcbsKXp

**Comment by mk0003** [comment]
This crash always happening when i set item mode control to "**<**" key. After resetted this control this crash never happened.

**Comment by aidancbrady** [comment]
Fixed, thanks
