### ISSUE TITLE
Game crashes when trying to pick up robit

### ISSUE THREAD

**Issue by jonilala796** [aidancbrady/Mekanism#4256]
when I shift + right click the robit with the network tool from AE2 then my client is crashing
crash report: http://pastebin.com/SShKUjLm

Minecraft Version: 1.10.2
Mekanism Version: 9.2.1.298
Forge Version:12.18.3.2239
AE2 Version: rv4-alpha-11

**Comment by ktole1999** [comment]
are you supposed to be able to pick up robit using AE2 network tool?

**Comment by jonilala796** [comment]
I can pick it up. But I have to restart the client after the crash.

**Comment by thommy101** [comment]
Can you break it normally (without the network tool) or with the Mekanism configurator? If yes, please report it at AE2.

**Comment by jonilala796** [comment]
Yeah it works fine with the configurator

**Comment by aidancbrady** [comment]
Not a Mekanism issue
