### ISSUE TITLE
Conversion from Joules to RF is wrong

### ISSUE THREAD

**Issue by NerdCraft** [aidancbrady/Mekanism#4257]
Mekanism and Mekanism Generator 1.10.2-9.2.1.300

![2017-03-09_17 10 53](https://cloud.githubusercontent.com/assets/13489837/23768620/68a0b5c2-04eb-11e7-81fa-1c16d2644de0.png)

![2017-03-09_17 08 25](https://cloud.githubusercontent.com/assets/13489837/23768514/12cb6f52-04eb-11e7-9c9b-052921052ddf.png)
![2017-03-09_17 08 30](https://cloud.githubusercontent.com/assets/13489837/23768515/12d25510-04eb-11e7-8d9b-978a96035e93.png)

**Comment by ktole1999** [comment]
use your words.

**Comment by NerdCraft** [comment]
Windmill says it is producing 61,44 rf/t, but if you look at the capacitor it's saying 153 rf/t. I think the energy isn't being converted from joules to rf.

**Comment by ktole1999** [comment]
if you replace the eio stuff with mek cable and cube do you get same result for transfer?

**Comment by NerdCraft** [comment]
Yes

**Comment by ktole1999** [comment]
you should get a different transfer rate based on how mek cables work if i recall.

**Comment by NerdCraft** [comment]
tested in another instance, and now it works. weird
