### ISSUE TITLE
[9.2.1] Cardboard Box crashes on mouseover with certain blocks inside

### ISSUE THREAD

**Issue by Babbie** [aidancbrady/Mekanism#4258]
If you right-click the top side of a door (just an example) with the cardboard box, break it and afterwards mouse over the cardboard box, you will immediately crash to desktop.

Using Mekanism 9.2.1 for Minecraft 1.10

**Comment by Babbie** [comment]
As a side note, you can't unpack the top half of the door either, so you need to destroy the cardboard box without hovering over it in your inventory to get rid of it.

**Comment by ktole1999** [comment]
duplicate issue. please check closed issues list.

**Comment by Babbie** [comment]
My bad.
