### ISSUE TITLE
Crashing when start up the Digital Miner in 1.10.2

### ISSUE THREAD

**Issue by Pyrom4nia** [aidancbrady/Mekanism#4259]
[crash-2017-03-12_14.15.17-server.txt](https://github.com/aidancbrady/Mekanism/files/836340/crash-2017-03-12_14.15.17-server.txt)
When start up the Digital Miner or open the visual feature the game will crash the server
Tried to put the energy conduit after the miner, still crashing the server

**Comment by thommy101** [comment]
Not a Mekanism issue. Please report to the owner of NetherMetals 
https://github.com/MinecraftModDevelopmentMods/NetherMetals/
