### ISSUE TITLE
Basic Fluid Tank Error/Game crash

### ISSUE THREAD

**Issue by killory** [aidancbrady/Mekanism#4260]
Mekanism-1.10.2-9.2.1.298
On separate occasions I have experienced a problem using the Mekanisim fluid tank
1st instance, a basic fluid tank was placed in a tinkers construct smelter basin causing an Open GL error that would crash the game.
2nd instance, an attempt to upgrade a basic fluid tank to an advanced fluid tank was made on a tinkers construct crafting station this also resulted causing an Open GL error that would crash the game as well.
I thought it was important to let it be known here as well as to the tinkers construct team.

**Comment by thommy101** [comment]
Duplicate issue.

There's a known bug in Mekanism causing GL error's when used with Tinkers Construct. A workaround (not a permanent solution) is to disable fancy rendering of items in Tinkers Construct.
