### ISSUE TITLE
Energy Tablet NOT WORK and all recipes with them [1.7.10]

### ISSUE THREAD

**Issue by MCMARCELO2** [aidancbrady/Mekanism#4261]
I updated on my Server Mekanism from v8 to v9 (newest) and all recipes with a Energy Tablet not work.
I can only autocrafting the Energy Tablet but thats not a solution because recipes Nevertheless dont crafting. (vanilla crafting table too not work). 

(I am from Germany, sorry for my bad English)

**Comment by JaSpr** [comment]
1.7.10 is no longer supported.

**Comment by MCMARCELO2** [comment]
What is not supported? Only the Energy tablet in v9 ? all another stuff in v9 works.

**Comment by bookerthegeek** [comment]
Because it is 1.7.10

You can fix it yourself with minetweaker scripts. Or you know update to a supported version.

**Comment by JaSpr** [comment]
@MCMARCELO2 Any bugs that happen in 1.7.10 will not be fixed, as the Mekanism team is no longer supporting version 1.7.10

**Comment by MCMARCELO2** [comment]
Can you help me too fix it ?

**Comment by bookerthegeek** [comment]
Give me a screenshot of the recipe in nei and also of you ttui g to make it in the crafting table.

**Comment by MCMARCELO2** [comment]
![screenshot 2](https://cloud.githubusercontent.com/assets/26365998/23930894/74e3bc2e-092f-11e7-8d83-4d0610ca6724.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/26365998/23930893/74e2a276-092f-11e7-8e13-e6dbabab1802.png)

**Comment by MCMARCELO2** [comment]
![screenshot 4](https://cloud.githubusercontent.com/assets/26365998/23930920/9aa8e2fe-092f-11e7-89f7-536f23fc4640.png)

**Comment by bookerthegeek** [comment]
![proof](http://i.imgur.com/gZTu5id.png)
Interestingly enough it works for me. You said server so I can assume you are running a pack? And also running on Kauldron / Bukkit ?

1) First picture again please, without a texture pack
2) First picture again, in single player, without a texture pack
3) Server Mod Pack name and DL location.

**Comment by thommy101** [comment]
My guess is that it's a problem with the autocrafting of the tablets. When autocrafted with AE2 they won't get all the NBT tags which are set when crafted by a player.
Try crafting the tablets in a vanilla craftingtable and then try to craft an energy cube (also in a vanilla craftingtable).

**Comment by MCMARCELO2** [comment]
i cant click the energy table for the recipe
![screenshot 5](https://cloud.githubusercontent.com/assets/26365998/23980246/e47288a2-09fe-11e7-92cd-f2357a523547.png)

**Comment by MCMARCELO2** [comment]
![screenshot 7](https://cloud.githubusercontent.com/assets/26365998/23980310/47a7b690-09ff-11e7-8adc-4ecb3ab523cb.png)

**Comment by MCMARCELO2** [comment]
When i cheat my the energy tablet than i can craft the energy cube in a vanilla crafting table

**Comment by MCMARCELO2** [comment]
https://www.technicpack.net/modpack/novus-official-youtube-pack.895793

this is the modpack.
its only forge not kauldron or bukkit.

i only change the mekanism version from v8 to v9

**Comment by MCMARCELO2** [comment]
is this important ?
![screenshot 10](https://cloud.githubusercontent.com/assets/26365998/23980543/91b5331a-0a00-11e7-9abe-ef441f1efd79.png)

**Comment by MCMARCELO2** [comment]
i'm testing to craft a energy tablet in vanilla crafting table and it works. but the id ist 5828:100 and not only 5828. it not work to craft a energy cube with the 5828:100
![screenshot 11](https://cloud.githubusercontent.com/assets/26365998/23980947/67b1181a-0a03-11e7-837f-3d1130605cee.png)

**Comment by bookerthegeek** [comment]
delete that script and try it again.
