### ISSUE TITLE
Inconsistency with Factory power consumption

### ISSUE THREAD

**Issue by cosmicdan** [aidancbrady/Mekanism#4262]
Hi,

As I can see in the source code (and have verified this in a quick game test), the factory blocks all have a flat energy consumption of 50 * numberOfProcessingQueues (e,g 50 * 3 for Basic Factory). This makes sense for the basic machines like the Smelter and Crusher, but for machines like the Chemical Injection Chamber which consume much more than the basic machines, this one-for-all formula introduces balancing issues.

Consider replacing the config option of "FactoryUsage" with a consumption *multiplier* instead? Perhaps with a default value of 1.0 - meaning that each queue of a Factory consumes 1.0 * the original energy consumption. So the basic machine factories would still be the same, but the advanced ones would scale to their original energy rates appropriately.

I've noticed you haven't done any activity on 1.7.10 for a while, which is what we're using. If you like this idea but aren't interested in updating old Mekanism, can I fork it and make the change for our modpack - sending a PR back when done?

Cheers

**Comment by aidancbrady** [comment]
Fixed, thanks!

**Comment by cosmicdan** [comment]
Glad to hear it. Will this be back-ported to 1.7.10 or have you effectively finished 1.7.10 development?
