### ISSUE TITLE
Logistic transporters only pull enough for the first target

### ISSUE THREAD

**Issue by Paul17041993** [aidancbrady/Mekanism#4264]
If a line of machines are requesting stacks of items, the transporters will only ever check the first target and, as such, not pull nearly enough items to fulfil the line.

**Comment by SteveSutton1989** [comment]
You have to use the sorter if you wish for it to "round robin"  hope this helps

**Comment by Paul17041993** [comment]
It's not round-robin, but more so that the transporters will never pull to their proper specification, if the first-most destination only allows 1 item then the transporters will only ever transport 1 item at a time. Similarly if the source inventory's last-most slot only has 1 item then the transporters will only ever pull that one item until the slot moves or you use a secondary transporter on the same inventory.

And if you think this may be by design to prevent over-pulling, it definitely isn't because the transporters will over-pull regardless of the source and destination conditions (unless all the destinations are completely full), often resulting in single-item stacks bouncing back and forth in the transporters.

Also, in the current release I'm using, the sorter is basically non-functional so I cant use it anyway...

**Comment by ktole1999** [comment]
are pipes connecting destination machines colored? can you show a screenshot?

**Comment by Paul17041993** [comment]
Colours are not used, it's just single lines of transporters pulling from a chest each (1 source, 16 destinations).

Cant show screenshots currently as the transporters were stripped out once I discovered the bug.

**Comment by aidancbrady** [comment]
This is to avoid inefficiency; only one destination is considered per calculation.  As mentioned previously, use round robin mode if you want to distribute destinations.
