### ISSUE TITLE
Industrial Turbine does not work in 9.1.0.281 for 1.7.10

### ISSUE THREAD

**Issue by comus777** [aidancbrady/Mekanism#4265]
I copied the design in your video https://www.youtube.com/watch?v=kHJSEUjCsyA down to the last block, but I never get the red particles, nor do I get the GUI. Rather annoying that it's so difficult to get a simple turbine working, can you add a debug item or feature of some sort?

**Comment by aidancbrady** [comment]
1.7.10 is no longer supported, but regardless, double check to make sure your structural proportions are correct.
