### ISSUE TITLE
Quantum Entangloporter

### ISSUE THREAD

**Issue by Alfatossa** [aidancbrady/Mekanism#4266]
Is there a way to let admin to open a Quantum Entangloporter that doesn't belong to them because like for example someone is stealing power form another player without agreement so the admin could go and change that i cant seem to find a way to let opped player to open a quantum entangloporter they didn't place

**Comment by JaSpr** [comment]
Breaking and replacing will allow the admin to have ownership rights, but the original player who placed it would have to do the same to get those rights back.

**Comment by Alfatossa** [comment]
thast what i want it to be fixed because its annoying adding a tag for that in the mekanism.cfg file.

**Comment by aidancbrady** [comment]
There isn't an easy way around this due to the way the security system works.  I may make some changes in the near future to combat these kinds of issues, but in the meantime breaking and replacing doesn't seem like too much of a hassle.
