### ISSUE TITLE
Ores harvested while using LevelUp mod with default settings cannot be processed

### ISSUE THREAD

**Issue by bmwalter68** [aidancbrady/Mekanism#4267]
The LevelUp mod gives players perks for performing actions like mining and digging.  In order to prevent abusing the system, the LevelUp mod tags all harvested blocks with the NoPlacing tag, preventing some blocks from being placed and re-harvested for more experience.  Mekanism ore processing machines will not accept ores that have the NoPlacing tag applied to them.

The tag can be removed by passing the affected ores through the Oredictionificator.

This can be partially mitigated by setting the LevelUp config options:

B:"Ore blocks harvested cannot be placed"=false
B:"Prevent duplicated ores placing"=false

But all ore harvested prior to the settings change still cannot be processed and players can also duplicate experience by re-placing and breaking ore blocks.

**Comment by ktole1999** [comment]
so what are you asking or reporting? That another mod changes the block so its no longer recognized by mek? That is the other mods fault.

**Comment by bookerthegeek** [comment]
Or to ignore the tag and process the ore as normal

**Comment by bmwalter68** [comment]
The latter.  Mostly, since it is an issue I wanted to report it along with possible mitigations.  But I'm also wondering why a strict NBT match needs to happen on ores for them to be processed.  There may be a good reason, but I for one couldn't think of it.  Because of that I didn't want to recommend a change, but rather raise it as an issue so someone more in the know could decide what if anything should be done.

**Comment by thommy101** [comment]
Mekanism does check for ItemStackInput.java equality with nbt at the following place:
https://github.com/aidancbrady/Mekanism/blob/1.10/src/main/java/mekanism/common/recipe/inputs/ItemStackInput.java#L66

I do not know (yet) if there will occur any complications when changing it to ignore nbt.
