### ISSUE TITLE
Build 9.2.1.300 still has an outdated multipart dependancy.

### ISSUE THREAD

**Issue by ate0ate** [aidancbrady/Mekanism#4268]
Build 300 again forces a bogus multipart 2.0 dependency when multipart is officially at version 1.4. McMultipart 1.4.0 is actually a newer version of multipart than the the unintentionally published 2.0 release that mekanism is dependant on.

**Comment by thommy101** [comment]
There's (a long known issue) related to that. Aiden is still releasing build of the master branch, while there are 32 commits, with the above issue fixed, on the 1.10 branch.

If you want to use it now, you can compile the 1.10 branch and use it.

**Comment by ate0ate** [comment]
Thank you much for the suggestion, but for some reason compiling mekanism always fails for me. I was actually using your (quite appreciated) build for quite a while but figured I'd update since it had been a rather long time. I was surprised to still see this issue existed. In the meantime I've deleted the dependencies.info in the jar as a workaround since the constant deletion of the proper mcmultipart causes some issues with refined relocation. Do you recommend I close this issue since it is already known?

**Comment by thommy101** [comment]
There's currently an open issue (by me) for attending Aiden on the issue with the branches (#4059).
Great to hear the old build is appreciated! Maybe I can help you with compiling? What kind of errors do you get?
Deleting of the dependencies file is a good workaround, but your missing some nice bugfixes, which you can see at: https://github.com/aidancbrady/Mekanism/compare/1.10

**Comment by ate0ate** [comment]
Well, again I owe you many thanks. I dusted off my old compiling shoes, downloaded the most recent jdk, and was greeted with a "build successful" on my first attempt. Haven't tested it though yet. No idea what I was doing wrong last time either. 

Suppose I'll close this issue. I'll post here again if I have any problems with my homebaked build if you have the time to answer any questions. And I give you a giant gold star for always helping out here. I've been using mekanism and lurking about the issues for years now and Aiden is a great guy, but he needs a little help with some maintenance at times. It was great when unpairedbracket was around to do it and you seem to be picking up the slack now. I just want to say that its much appreciated and thanks for the help!

**Comment by thommy101** [comment]
Great that the build has succeeded and thank you for your appreciation! :D Means a lot
