### ISSUE TITLE
Logistical Sorter doesn't like underscores

### ISSUE THREAD

**Issue by Nuinethir** [aidancbrady/Mekanism#4269]
The Logistical Sorter (LS) OreDict Filter will not allow me to find any block/item that uses an underscore in its name.

I recently tried implementing a sorting system with the LS and it works fine, right up until a block or item has an underscore in the name, I used JEI to search for an underscore and found vanilla items suffer this issue (ex: _minecraft:golden_apple_), along with mods such as Mystical Agriculture, where it too uses underscores in the names (ex: _mysticalagriculture:osmium_essence_).

**Comment by aidancbrady** [comment]
Fixed, thanks!
