### ISSUE TITLE
Logistical transporters getting jammed up

### ISSUE THREAD

**Issue by Optimoos** [aidancbrady/Mekanism#4270]
I have LT connected to a vanilla chest feeding Elite Infusing Factories. Often, the process will stop because the factory has run out of infusing product even though there is plenty of it in the chest. When I manually pull some out of the chest and put it in the factory, everything starts going again. However, I often notice significant gaps in product being delivered when there is definitely more available in the chest, so it appears that the LT is getting hung up on something. It _appears_ that it is only the refining product (coal, redstone) getting stuck, not the incoming metal.

I've tried - 1 connection on chest set to pull to two connections on factory, as well as 2 connections on chest through individual colored pipes to 2 connections on the factory, both with strict input enabled and disabled.

This is in the All The Mods modpack v2.5.2b with Mekanism 9.2.1-300.

It appears this may be related to this issue - https://github.com/aidancbrady/Mekanism/issues/4221 - however, I'm not using sorters at all.

**Comment by ktole1999** [comment]
pipe wont skip items with no destination. the logistical sorter will. place sorter between pipe and set filters.

**Comment by Optimoos** [comment]
Thanks for pointing that out. Sadly because Logistical Sorters are horizontal only I've had to expand the size of my setup and rework pathing, but I've got it working.

**Comment by Optimoos** [comment]
Well, spoke too soon, sorters are exhibiting the same behavior. I wanted this to be a Mekanism only build but EnderIO conduits Just Work(tm) so I'll probably swap them in.
