### ISSUE TITLE
Fluidic plenisher leaves gaps when pumping lava

### ISSUE THREAD

**Issue by SteveSutton1989** [aidancbrady/Mekanism#4271]
This may happen with other liquid's (I'm guessing not water because it generates more source blocks) but I am using the latest pack. 

I have tried moving it and resetting it and get various results. 

It it fully power with speed and energy upgrades and I have tried without them as well. SameSame result but slower. 
Powered fully and constantly flow of lava at all times via elite mechanical pipe and a gargantuum barrel of lava. 
It pump's out swiftly and covers a good distance of what I want it to. But there are a lot of gaps where there is lava but it's not a source block. 
Over a 200x140 area having so much flowing lava may cause issues.

I have reset it after its "complete = yes" for it to takes it time but eventually use a bit more lava fill in a few holes then stop again. Tried 4 or 5 times couldn't observe how much was filled in so it wasn't a lot.  

Also moved it several spaces away to have it use a bit more than just resetting it. 

If it matters I have it set up to pump between glass blocks.

**Comment by thommy101** [comment]
I've made a hole (not 200*140 as you described in your first report) and it filled it perfectly, no hole to be found.

**Comment by SteveSutton1989** [comment]
I have recently been using it again for several different liquids and a very very large amount of water. It seems it misses blocks out over a large area but not small ones.

I'm really no expert but I think it does checks of certain blocks but not all like the ranged pump for example is very uniform and pumps in a pattern.

The fluid plenisher however may create long lines of a liquid and then do miss a couple of lines completely. I can't work out a pattern if there is one anyway. 

My latest endeavour was putting it against a wall that was over 100 wide 100 long and 20 deep. The results were ok it did 5 blocks wide and about 60 forward with a few holes here and there, I moved it to the edge of the side it stopped (5 blocks) and it did the same but 2 blocks wide. 
I repeated it with different results every time.

**Comment by thommy101** [comment]
I'll try and make the hole bigger. See if I get the same weird stuff.

**Comment by thommy101** [comment]
Bigger hole (100*100*20) and it filled perfectly in one try, no need to replace the fluidic plenisher or so.

**Comment by SteveSutton1989** [comment]
That's crazy I don't understand what I could be doing wrong. I've tried on different versions currently latest.  Currently on FTB beyond was on infinity lite. 
Using a mekanism fluid pipe and a drum on top.
I can recreate it whenever

**Comment by aidancbrady** [comment]
I can't reproduce this either. Perhaps another mod is interfering with the environment?
