### ISSUE TITLE
rendering errors 

### ISSUE THREAD

**Issue by ApostolosRisen** [aidancbrady/Mekanism#4272]
I actually seem to be getting a large number of crashes since adding Mekanism to the modpack my group of friends plays on, almost all of them are rendering issues, and are frequently several items or just one item, not rendering properly and causing an instant crash upon failing to render. included are two crash reports of two such instances.
[crash-2017-03-24_21.34.35-client.txt](https://github.com/aidancbrady/Mekanism/files/869583/crash-2017-03-24_21.34.35-client.txt)
[crash-2017-03-24_21.47.08-client.txt](https://github.com/aidancbrady/Mekanism/files/869584/crash-2017-03-24_21.47.08-client.txt)

And one involving Tinkers construct, though I have had many
[crash-2017-03-24_20.29.13-client.txt](https://github.com/aidancbrady/Mekanism/files/869585/crash-2017-03-24_20.29.13-client.txt)
 other people do not seem to be having nearly the issues that I do, most of them are only having mild to moderate frame drops. Any assistance that anyone could give would be much appreciated

**Comment by thommy101** [comment]
Known compatibility issue between Mekanism and Tinkers Construct.
See #4260 #4212 #4095 
Please use the search function, as it's reported quite a lot.

**Comment by jburrows82** [comment]
OptiFine Version: OptiFine_1.10.2_HD_U_D6

Render issues and using Optifine? Try not using Optifine, it causes render issues.
