### ISSUE TITLE
1.10.2 Basic Fluid Tank not craftable

### ISSUE THREAD

**Issue by penguinmayhem** [aidancbrady/Mekanism#4274]
I'm running Mekanism v9.2.1.300 and JustEnoughItems on Minecraft 1.10.2

Went to make the Rotary Condensentrator, cannot see any recipe for Basic Fluid Tank.  Tried crafting the Basic Fluid Tank manually using the recipe here http://wiki.aidancbrady.com/wiki/Basic_Fluid_Tank and with the recipe here https://ftbwiki.org/Portable_Tank_(Mekanism) and neither one works.  The fluid tanks are completely inaccessible.  What am I doing wrong?

Edit: just updated to 9.2.1.301  Problem still same.

**Comment by thommy101** [comment]
You're right, the wiki is quite outdated. The correct recipe is using 4 enriched alloys and 4 iron in the same way as the wiki states (replace redstone with enriched alloy).

**Comment by penguinmayhem** [comment]
JEI doesn't show the recipe.

Also I tried doing exactly what you said, four iron and four enriched alloy, does not work.
![2017-03-28_12 15 46](https://cloud.githubusercontent.com/assets/26691269/24402402/5097b254-13b0-11e7-9404-063ce34a4447.png)

**Comment by thommy101** [comment]
Wierd, I'm currently not able to open a game to test it myself, but the code does show that you're using the correct recipe.
What modpack are you using? There could be a mod/config that disables/prevents crafting of fluidtanks.

**Comment by ktole1999** [comment]
or has changed recipe.

**Comment by BrianEdmonds** [comment]
I'm working on a Mekanism based modpack, and this works as expected in 300 and 301. The recipe shows up in JEI, and crafts correctly.

**Comment by penguinmayhem** [comment]
Not a modpack.  Currently using:

Mekanism v9.2.2.301
BetterAchievements v0.3.2.39
Bookshelf 1.4.3.338
EnchantingPlus 4.1.0.115
Journeymap 5.4.6
OptiFine 1.10.2 HD U D6
JustEnoughItems v3.13.6.393

**Comment by BrianEdmonds** [comment]
My pack has that version of journeymap, and v416 of JEI, but I have no experience with the other mods. I've got ~60 mods in my current pack. The best way to narrow it down would be to take a copy of your world and try removing mods to see if one of them is causing the problem.

**Comment by penguinmayhem** [comment]
Tried deleting every mod but Mekanism, no change.

Am I using the correct version of Forge?  I am currently on 1.10.2 forge v1.10.2-12.18.3.2239

**Comment by BrianEdmonds** [comment]
Looking back, I'm not sure what thommy101 was talking about with the alloys. My 301 world is crafting it just fine with redstone dust in the corners, and I've not tweaked any recipes.

**Comment by thommy101** [comment]
@BrianEdmonds I didn't have a working minecraft instance at that time, I only had the code.

And the code speaks of "alloyBasic" at: https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/Mekanism.java#L599

Sorry for the inconvenience ;)

**Comment by penguinmayhem** [comment]
Excuse me, why is this issue closed?  I still don't have an answer and it's still not working.

**Comment by ThatGamerBlue** [comment]
@penguinmayhem it's because @aidancbrady closes every new issue with no apparent reason.

**Comment by penguinmayhem** [comment]
No wonder Minecraft is on the decline.
