### ISSUE TITLE
Other players beside placer can't access blocks

### ISSUE THREAD

**Issue by Salads** [aidancbrady/Mekanism#4275]
When trying to access the Teleporter block, or the Quantum Entangloporter energy thing, they get a message from [displayNoAccess(EntityPlayer player)](https://github.com/aidancbrady/Mekanism/blob/81e810794581cabba8925634f93f1323400014cb/src/main/java/mekanism/common/util/SecurityUtils.java#L122)

I have opped the player but still no luck, like [this checks seems to say](https://github.com/aidancbrady/Mekanism/blob/81e810794581cabba8925634f93f1323400014cb/src/main/java/mekanism/common/block/BlockMachine.java#L573)

I'm using the "All the Mods" modpack, version **1.10.2 v2.53**
Mekanism v **9.2.2**
MekanismGenerators v **9.2.2**
MekanismTools v  **9.2.2**

**Comment by thommy101** [comment]
First of all, thank you very much for the detailed bug report! I would love to see that every one I see looks like this. 

By default only the player can access placed blocks. If you want ops to access you'll have to change the config (default value is deny op access defined at https://github.com/aidancbrady/Mekanism/blob/2b02042f4c38aac672f9af72db155bd583b492c0/src/main/java/mekanism/common/CommonProxy.java#L249 ) 

The player who placed the block could set it to public/restricted (don't quote me on the restricted naming, could also be something like friends) to allow others. 

Last but not least, in one of the latest build there is an added feature to deny all protection server wide.

**Comment by lumpusman** [comment]
is there a way to share access for teleporter block?  we have tried the security desk etc.
