### ISSUE TITLE
Power cables don't connect to Environmental Tech Void Miners

### ISSUE THREAD

**Issue by TauzentBlitz** [aidancbrady/Mekanism#4277]
Cables won't physically connect to void miners, let alone power them.

**Comment by jburrows82** [comment]
Mekanism doesn't support Forge Energy, currently, and that is all Environmental Tech supports at the moment. [ET dropped RF support](https://minecraft.curseforge.com/projects/environmental-tech/files/2386796) a couple versions ago. You will have to use another mod that supports Forge Energy (such as EnderIO) between Mekanism and ET.
