### ISSUE TITLE
feature request: better theoneprobe integration

### ISSUE THREAD

**Issue by BrianEdmonds** [aidancbrady/Mekanism#4279]
When I look at a Quantum Entangloporter with the one probe (worn as a bauble), and shift for extra information I get "Error: theoneprobe:default" as the additional information. There are probably other blocks with similar issues, but this was the one that I hit when I was in a bug reporting mood.

Relevant versions: Minecraft 1.10.2, Mekanism 301, theoneprobe 1.4.4, Baubles 1.3.9 (if that matters).

Screenshot
![2017-03-28_14 00 12](https://cloud.githubusercontent.com/assets/18468613/24427180/e6908016-13be-11e7-82c9-1b12540a2069.png)

**Comment by BrianEdmonds** [comment]
I take back the "other blocks" comment. I took a look around all my Mekanism equipment and only the QE displayed this issue. (Could of course affect something I've not built yet, as I'm only up to 4x ore processing, so there's a bunch of the tech tree I've yet to explore.)

**Comment by thommy101** [comment]
Guess this one is solved now:

![TheOneProbe](https://cloud.githubusercontent.com/assets/1036527/26558308/f2cdface-44a7-11e7-8108-5272fe44d6bc.png)
