### ISSUE TITLE
[Request] Gasses in JEI

### ISSUE THREAD

**Issue by mezz** [aidancbrady/Mekanism#4281]
JEI now has support for custom ingredient types, in addition to ItemStack and FluidStack.
I think Mekanism's gasses are a good candidate for this feature.

Here's the wiki documentation on adding new ingredients: https://github.com/mezz/JustEnoughItems/wiki/Non-Item-Ingredients
The vanilla plugin in JEI adds ItemStack and FluidStack using the same API, so you can look there for an example.

Let me know if you have any questions.

**Comment by PJB3005** [comment]
Maybe doing it the other way and changing Mekanism gases to use the regular fluid types in Forge would be a better idea, though that might be a lot more work.

**Comment by Dilnu** [comment]
Have their been any further thoughts on doing this? It's hard to remember how to make Sulfuric Acid without consulting a wiki.

**Comment by thommy101** [comment]
I'm willing to pick this up, together with an update of the used JEI api as soon as my 1.12 update and 1.10 back port are accepted and merged.

**Comment by thiakil** [comment]
This appears to already have been added in https://github.com/aidancbrady/Mekanism/commit/89905c836bc31b3043b62d5f521ad69150dff089#diff-055b8be0fe0984f3a1efe9ff4ff5173cR162 ..

![2017-07-23_13 27 53](https://user-images.githubusercontent.com/1788847/28496946-5993f054-6fac-11e7-8ecf-5051387c6265.png)

**Comment by mezz** [comment]
Completed fully here: https://github.com/aidancbrady/Mekanism/commit/7b9bf2194257ee42d74ec328619c0d96510c6bd5
