### ISSUE TITLE
[Request] Add Forge ITEM_HANDLER_CAPABILITY support for 1.10 and 1.11

### ISSUE THREAD

**Issue by Landmaster** [aidancbrady/Mekanism#4283]
Peeking at the source code, it seems that the cables (and most other items from this mod) do not support the new Forge ITEM_HANDLER_CAPABILITY. Support for this should be added; otherwise, modders would be forced to use IInventory in order to have generic support for item pipes.

**Comment by thommy101** [comment]
Looks like it has already been added in https://github.com/aidancbrady/Mekanism/commit/c12f1c1e6f521465ba7ea81c3ef0c39289ae115b.

Nice work @aidancbrady!

**Comment by Landmaster** [comment]
Will this be backported to 1.10?

**Comment by thommy101** [comment]
Maybe a nice idea to add to this request: use the ItemCapability to interact with other mods. Currently all tileentities that interact with other blocks use IInventory (for example logistical pipes and the push of machines).
There amount of mods that only support capabilities is increasing. Would be nice to have a better cross mod interaction.

**Comment by thommy101** [comment]
First part done by @aidancbrady at b97b7184c138000997e34194174a7d82e5ebbed4

**Comment by thommy101** [comment]
Tested latest version (okey, version of 12 hours ago). Tested with Actually Additions crate as that only supports the inventory capability and not the IInventory.
Working:
- Digital miner output to crate and vanilla chests
- All processing machines automatic output to crate and vanilla chests
- Pipes extracting from crate
- Pipes inserting and extracting from chests

Not working:
- Pipes inserting into crate

To test:
- Something like RFTools inventory viewer (forgot the name) to test if Mekanism's capability is exposed correctly
- Normal operations of non capability providing blocks (vanilla exposes both capability and IInventory)

**Comment by aidancbrady** [comment]
Should be done!

**Comment by thommy101** [comment]
Working flawless!!
