### ISSUE TITLE
Strange behavior of energy.

### ISSUE THREAD

**Issue by marcin212** [aidancbrady/Mekanism#4284]
Why is there a division by 10 [here](https://github.com/aidancbrady/Mekanism/blob/1.10/src/main/java/mekanism/common/multipart/PartUniversalCable.java#L76)? Setting the cable to PULL mode causes it to transfer 10x less than it should.

Also, [here](https://github.com/aidancbrady/Mekanism/blob/1.10/src/main/java/mekanism/common/multipart/PartUniversalCable.java#L87) - taking the min of the cable throughput and battery capacity causes a PULLing cable to pull energy with its max thropughput, ignoring the battery's max output. The simplest solution would be to add a getMaxOutput method to the IStrictEnergyStorage interface.

**Comment by aidancbrady** [comment]
Fixed, thanks
