### ISSUE TITLE
work with tinkers without registerAllItems=true

### ISSUE THREAD

**Issue by BrianEdmonds** [aidancbrady/Mekanism#4288]
TL;DR: How much work would it be to have Mekanism advertise the metals it provides such that Tinkers Construct will automatically include support for them?

I'm working on a modpack that contains both Mek and TC, and I've found that without the TC config setting registerAllItems=true, TC does not recognize that Mek is providing Tin and Copper, so , for example, the tin and copper variants of the tool forge are not available to craft, among many other issues.

If it could also support Osmium as part of this integration work, that would be even better.

**Comment by aidancbrady** [comment]
If someone wanted to submit a TC support pull request I'd consider merging it, but in the meantime I have too many other issues to look at.

**Comment by BrianEdmonds** [comment]
@aidancbrady Out of curiosity, do you have something you use to track
planned work, or is all in your head?

**Comment by laz2727** [comment]
It should automatically register them (TiC catches oredict event for that). Wonder what's the bug is.

**Comment by Landmaster** [comment]
@aidancbrady @laz2727 @BrianEdmonds The reason why they are not automatically registered is that

> you are registering them in `init`, [whereas they are supposed to be registered in `preInit`.](https://mcforge.readthedocs.io/en/latest/utilities/oredictionary/) This is causing problems with other mods which depend on the oredicts, such as Tinkers Construct.
>
>The same problem occurs with your copper, tin, and bronze.
>
>(I discovered this problem early on when working on my addon mod [PlusTiC](https://github.com/Landmaster/PlusTiC) and adding Mekanism integration, and had to manually register the metals as a workaround.)

(from my comment on #4463)

**Comment by thommy101** [comment]
Created pull request #4465 to fix this issue.
