### ISSUE TITLE
Compatibility - Please name your Forge fluids "liquidoxygen" and "liquidhydrogen"

### ISSUE THREAD

**Issue by radfast** [aidancbrady/Mekanism#4290]
Hey guys.  In case you don't know me, I'm co-dev of Galacticraft, working with micdoodle8.  We like to have 100% compatibility between Galacticraft and Mekanism, as these two mods go back a long way together. 

Mekanism is currently registering **liquid oxygen** and **liquid hydrogen** as Forge fluids with the names "oxygen"  and "hydrogen".

This is causing a problem for Galacticraft, and probably for other mods as well.  The reason is that Galacticraft (and some other mods like MineChem) register **oxygen gas** as a Forge fluid with the name "oxygen", and similarly **hydrogen gas** is a Forge fluid with the name "hydrogen".  So when our Galacticraft machines should be producing oxygen **gas**, they can actually end up producing Mekanism's liquid oxygen [instead](https://github.com/micdoodle8/Galacticraft/issues/2464) if Mekanism is present.

For liquid oxygen we create another Forge fluid with the name "liquidoxygen", and the same for liquid hydrogen.  I am requesting and hoping to persuade you to do the same, for 100% compatibility!  It's just a single internal name change your side, you'd also need to update the fluid.oxygen and fluid.hydrogen keys in your .lang files to match...

Mekanism has its own system for gases, but other mods use the Forge fluid system for gases as well as for liquids (you can set the density of the Forge fluid to be very low - Minechem actually uses negative densitites for some gases).  In normal English usage both liquids and gases are "fluids".  :)

**Comment by radfast** [comment]
> One question about the "simple" change, do fluids which are currently in a save remain after a name change?

**Comment by thommy101** [comment]
Thank you for your explanation!

**Comment by aidancbrady** [comment]
Done!

**Comment by radfast** [comment]
hero, thank you :)
