### ISSUE TITLE
Issue with digital miner ore dict NPE in 1.11.2 branch.

### ISSUE THREAD

**Issue by kragnoth** [aidancbrady/Mekanism#4291]
Unfortunately I don't have a crash log, but I do have a pastebin for the latest log with the NPE thrown.
https://pastebin.com/EQd2Xu6i

It looks like mekanism/common/content/miner/MinerFilter.java is throwing a NPE (or whatever it is referencing) at about line 47.

I know this is probably being looked into already, but I figured since I was able to get it to compile and I found a bug, I'd post the bug to make someone's life a little easier.

**Comment by thommy101** [comment]
It's probably a missed null item stack. The 1.11 branch is quite new and aidancbrady is still busy with it.

**Comment by thommy101** [comment]
Quick look led me to:
https://github.com/aidancbrady/Mekanism/blob/1.11/src/main/java/mekanism/common/tile/TileEntityDigitalMiner.java#L371

There are still some null's there ;) Maybe it could be an idea to switch from public variables to private variables and getters/setters. That way it's easy to look for nullable errors with annotations.

**Comment by kragnoth** [comment]
went through fixing them on my end to see how bad it was, it is definitely an issue with needing to change == null and != null to !ItemStack.isEmpty() and ItemStack.isEmpty().  I'll let the professionals handle it though, as I was getting unbreakable ultimate cables and hooking up a hopper to a biofuel generator led to a crash due to an unhandled capability handler (was kind of ironic)  If you want any of my crash logs I can post them here, but I'd just assume that this issue might be unneeded as the 1.11.2 branch is very new.  Much appreciated that it is being worked on though.

**Comment by aidancbrady** [comment]
Should be fixed! Appreciate you testing the 1.11 branch.

**Comment by kragnoth** [comment]
Awesome, will re-download and compile and test some more.
