### ISSUE TITLE
[1.11.2] Multipart Mekanism missing

### ISSUE THREAD

**Issue by Mohron** [aidancbrady/Mekanism#4294]
Mekanism: 9.3.0.15

I have been trying to test the dev builds of Mekanism for 1.11.2 but MultipartMekanism is not included on `http://dl.indiewikis.com` with the rest of the dev builds. Where can Mekanism Premium members get this new dependency?

Crash: https://hastebin.com/vojiworagu.sql

**Comment by aidancbrady** [comment]
Fixed!

**Comment by Mohron** [comment]
Updated to the latest downloads on the site. Still no dice :(

> 	net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mekanism (mekanism) 
> 	Caused by: java.lang.NoClassDefFoundError: mekanism/common/integration/multipart/MultipartMekanism 

> 	UCE	mekanism{9.3.0} [Mekanism] (Mekanism-1.11.2-9.3.0.18.jar) 
> 	UCE	mekanismgenerators{9.3.0} [MekanismGenerators] (MekanismGenerators-1.11.2-9.3.0.18.jar) 
> 	UCE	mekanismtools{9.3.0} [MekanismTools] (MekanismTools-1.11.2-9.3.0.18.jar)

**Comment by aidancbrady** [comment]
Would you mind posting the full log?

**Comment by Mohron** [comment]
https://hastebin.com/izakegizuz.sql

**Comment by thommy101** [comment]
I didn't look that well at your log, but do you have MCMultipart2 installed? It isn't registered as a required dependency anymore (probably a mistake).

https://github.com/aidancbrady/Mekanism/blob/1.11/src/main/java/mekanism/common/Mekanism.java#L165
I recommend changing that from after to required-after. That way it gives an missing mod screen at startup is mcmultipart is missing.

**Comment by Mohron** [comment]
This is the 1.11.2 version which doesn't use MCMP. https://twitter.com/AidanBrady_/status/847096568905977856

**Comment by thommy101** [comment]
Well.. I missed that.. Then there is deffinitly a bug, because I couldn't start it without MCMP.

**Comment by Mohron** [comment]
If it works with MCMP, I may just try that but It doesn't seem to be intentionally dependent.

**Comment by thommy101** [comment]
I'm currently checking out the latest version and compile it to see if I remember what I did last time.

**Comment by aidancbrady** [comment]
There's a few more changes I overlooked that are necessary to make things totally independent. I'll get it done today.

**Comment by Mohron** [comment]
I look forward to putting Mekanism 1.11 to the test!

**Comment by thommy101** [comment]
A crash report for the record:
https://gist.github.com/thommy101/9bfd7e9bb9f596c29647ac563e8a306f

I'm also looking forward to testing. If you need any extra help (code writing/testing), just ping me on github or something else.

**Comment by thommy101** [comment]
@aidancbrady What would you rather see, an issue for each bug found or one big "All the 1.11 bugs"?

**Comment by aidancbrady** [comment]
A single issue would be most convenient. Appreciate it :)

**Comment by aidancbrady** [comment]
By the way, the latest build has the fix for this issue.

**Comment by thommy101** [comment]
Regarding your fix, the error thrown is a NoClassDefFoundError, which doesn't inherit from exception but from error (or even more general, throwable).

And my other bug report is canceld, see you just fixed it :) (related to fluids)

**Comment by Mohron** [comment]
`dl.indiewikis.com` seems to be having problem because i've been trying to get the new version with no success. I've received multiple cloudflare error pages trying to download the builds. Is there an alternative?

**Comment by thommy101** [comment]
@Mohron The latest version of 1.11 is only available on Github. To test it you can download the source and compile it yourself. My advice: only use it for testing, no production as things might crash/change.

**Comment by Mohron** [comment]
@thommy101 You obviously know nothing about Mekanism Premium... part of donating to Mekanism's development gives you access to the dev builds. If you not sure what's going on, why answer?

**Comment by thommy101** [comment]
If you can't answer normally, why answer? 

I'm just a fanatic user of Mekanism, programmer and helping in my free time for free. Please have a little respect for others. 
My advice about the dev build still stands.

**Comment by Mohron** [comment]
I have respect for others but this is now twice that you have stepped outside your area of expertise. I had to share with you that Aidan was eliminating the MCPC dependency completely and now that there is a download site specifically for  Mekanism Premium members.  I appreciate your help, I really do, but this issue is outside your realm. I'm sure only Aidan has access to the `dl.indiewikis.com` page for Mekanism.

**Comment by ThatGamerBlue** [comment]
@Mohron 
https://thatgamerblue.com/MCMultiPart-2.0.0-mc1.11.jar
https://thatgamerblue.com/MekanismAll-9.3.0-mc1.11.jar

**Comment by Mohron** [comment]
@ThatGamerBlue Thanks. I actually ended up making a build myself but It still wouldn't work without MCMP.
