### ISSUE TITLE
1.11.2 capabilities crash

### ISSUE THREAD

**Issue by kragnoth** [aidancbrady/Mekanism#4303]
Link to my crashlog: 
https://pastebin.com/jTQU4anu

This happens when trying to place an ultimate cable next to another ultimate cable, but missing the grass block they are both on and hitting the previous ultimate cable instead.

I also got this error when placing a hopper on top of a biofuel power generating machine.

edit: I will report back if this happens without the 2.0.0.17 MCMP mod installed and see if the issue lies with that.

This does not seem to happen with MCMP removed.  However, still getting the hopper issue with the following pastebin crashlog:
https://pastebin.com/FqScPCw1

edit: I'll try again with foamfix removed and report back here, forgot that was installed.  Doubt its root cause, but I see that whole "don't report errors with this installed" line. 
edit2: yup same crash with foamfix removed.  Not sure the root cause though, as it doesn't link to a mekanism line.

**Comment by thommy101** [comment]
Uhm.. You've just closed your issue?

I can confirm the crash with the hopper on top of the biofuel generator.
Root cause is a missed empty itemstack check at:
https://github.com/aidancbrady/Mekanism/blob/1.11/src/main/java/mekanism/generators/common/tile/TileEntityBioGenerator.java#L77

**Comment by thommy101** [comment]
@kragnoth I've opend a pull request fixing the hopper/biogenerator issue, see #4305.

**Comment by kragnoth** [comment]
I don't remember closing this, thanks Thommy101!
