### ISSUE TITLE
[1.11.2] Wind Generator recipe not working.

### ISSUE THREAD

**Issue by Ristovski** [aidancbrady/Mekanism#4307]
With the latest 1.11 branch, crafting a Wind Generator is not possible. This has also been tested and confirmed with Mekanism(+Generators/Tools) being the only mods installed.

Forge: 1.11.2 - 13.20.0.2279
Mekanism: [562c127](https://github.com/aidancbrady/Mekanism/commit/562c1276475e30fc1c02e3ff35830444147d7a9c)

![alt tag](https://ptpb.pw/-5_H.png)

**Comment by thommy101** [comment]
Can confirm it's not working with all handcrafted items.

**Comment by aidancbrady** [comment]
Fixed!

**Comment by Ristovski** [comment]
For reference: [b355b80cf4edc429ed5fb3782fdb93f175656592](https://github.com/aidancbrady/Mekanism/commit/b355b80cf4edc429ed5fb3782fdb93f175656592)
