### ISSUE TITLE
Download Issues

### ISSUE THREAD

**Issue by 63502** [aidancbrady/Mekanism#4308]
I cannot download the latest version for 1.10.2 (9.2.2.301) from the Mekanism website. When I try to skip the adfly page in chrome, I get taken to a broken webpage with nothing more than one pixel in the middle[page just says download (1x1)]. When I do the same thing using Microsoft Edge, the download page just doesn't load.

Is this just me, or are other people having the same problem?

**Comment by thommy101** [comment]
The download site seems to be working for me.

**Comment by 63502** [comment]
This is apparently a problem dependent on where I connect to the internet, so it isn't on an end that I or the Mek. website can fix. The download does work on the connection I regularly use, so I guess problem solved. :)
