### ISSUE TITLE
[Suggestion] Maven Repo

### ISSUE THREAD

**Issue by oa10712** [aidancbrady/Mekanism#4309]
If one doesn't already exist (which I have found no reference to one existing), possibly look into setting up a maven repo for the MDK? It makes adding sources to projects easier IMO, and means that every addon doesn't need to have the jar uploaded to their source control

**Comment by aidancbrady** [comment]
I'd rather leave things the way they are for now.  I'll look into this once we have a stable release out for 1.11.2.
