### ISSUE TITLE
[1.7] Osmium not generating

### ISSUE THREAD

**Issue by Tavern-lexicon** [aidancbrady/Mekanism#4310]
Hello. I'm searched up and down on google and have not been able to find a straight forward answer to this. My friend's and I are running a private server, with Mekanism included. Everything works fine but, Osmium is not spawning in the overworld at all. It is however spawning in the nether (using Nether ores). We looked in the Mekanism cfg file and found only one mention of Osmium ore under the following...

_I:OsmiumPerChunk=12_

Changing that number has not provided any results. We also looked in the COFH and tried adding it there as well, and did not change anything. Any help would be appreciated, we're looking forward to using this mod, and don't want to have to pull it. I also wish to understand Why the is disabled for servers, but not for SP. Thanks.

**Comment by aidancbrady** [comment]
Perhaps the world was already generated. Try using the retrogen feature.
