### ISSUE TITLE
Cubes charging in the GUI of Induction Matrix disappear after exit

### ISSUE THREAD

**Issue by canaria2014** [aidancbrady/Mekanism#4311]
Mekanism 9.2.2.301
Minecraft 1.10.2

Energy cube will disappear after exit game if I put it charging in the gui of Induction Matrix.
I tested several times and found the problem may be that a Quantum Entangloporter is next to the Matrix.
but it happend even if the QE without any setting.

**Comment by aidancbrady** [comment]
Seems to be fixed in 1.11.
