### ISSUE TITLE
[Request-Infos] How to change some recipes ?  

### ISSUE THREAD

**Issue by Slater022** [aidancbrady/Mekanism#4316]
Why ? Because I want to replace osmium by Steel in the recipe of the enriched alloy and increase the redstone used by the recipes ( same for the other alloy recipes ).
 
I'm actually building a modpack for 1.10 based around Mekanism But i want to slow the progression to have long term goal and one of the thing i'm doing is basically slow the machinary progression till you got railcraft Steel.

( oh, and 'im replacing osmium by steel plates too ^^" and maybe aluminium for high end machinary ) 

Short desc : A completely different modpack that actually exist ^^' .

Anyway : how , if possible, can i change this kind of recipes ? 

Do I need to write myself an addon mod to do that ?

**Comment by thommy101** [comment]
Currently the way of changing recipes is by using IMC (inter mod communications). You can delete and add recipes with it. You need to write yourself an addon mod to do it.

How the IMC messages should look like is explained at:
https://github.com/aidancbrady/Mekanism/wiki/IMC-based-recipe-integration

**Comment by Slater022** [comment]
Thanks for your answer @thommy101 I really appreciate that. Is there any example project i can use to simply use IMC with mekanism ? 
I'll try to do that :)

**Comment by thommy101** [comment]
Sorry, I don't know any example for this. Maybe someone else who reads this.

**Comment by Slater022** [comment]
Huuuum ... 
```
NBTTagCompound recipeTag = new NBTTagCompound();
        recipeTag.setTag("itemInput", new ItemStack(Blocks.COBBLESTONE).writeToNBT(new NBTTagCompound()));
        recipeTag.setTag("itemOutput", new ItemStack(Items.DIAMOND).writeToNBT(new NBTTagCompound()));
        FMLInterModComms.sendMessage("Mekanism", "EnrichmentChamberRecipe", recipeTag);
```

Don't add the recipe in the enrichment chamber ...

**Comment by thommy101** [comment]
Enrichmentchambers use input and output, not itemInput and itemOutput.
There should be a log output which warns you for "unrecognised" IMC messages.

**Comment by Slater022** [comment]
Nope when i run the game from my idea project it's not showing me any output errors for imc :/

**Comment by thommy101** [comment]
Try it with this: (replaced itemInput with input and itemOutput with output)

NBTTagCompound recipeTag = new NBTTagCompound();
        recipeTag.setTag("input", new ItemStack(Blocks.COBBLESTONE).writeToNBT(new NBTTagCompound()));
        recipeTag.setTag("output", new ItemStack(Items.DIAMOND).writeToNBT(new NBTTagCompound()));
        FMLInterModComms.sendMessage("Mekanism", "EnrichmentChamberRecipe", recipeTag);

**Comment by Slater022** [comment]
Already tried ^^

**Comment by thommy101** [comment]
I'll come back to this when I've got a workspace in front of me.

**Comment by Slater022** [comment]
Thanks :)

**Comment by Slater022** [comment]
I'm trying with that but not working :  ```

 String key = "MetalurgicInfuserRecipe";
//InfusionString = CARBON;TIN;DIAMOND;REDSTONE;FUNGI;BIO;OBSIDIAN
        NBTTagCompound nbt = new NBTTagCompound();
        nbt.setTag("input", input.writeToNBT(new NBTTagCompound()));
        nbt.setTag("infuseType", new NBTTagString(infusionType));
        nbt.setTag("infuseAmount", new NBTTagInt(infusionAmount));
        nbt.setTag("output", output.writeToNBT(new NBTTagCompound()));

        FMLInterModComms.sendMessage("Mekanism", key, nbt);
```

**Comment by thommy101** [comment]
See the following repository for an example of a Mekanism EnrichmentChamber recipe being added through IMC: https://github.com/thommy101/MekanismIMC

There should be a log entry with the following:
```[Mekanism] mekanismimc added recipe of type EnrichmentChamber to the recipe list.```

After adding the mod, putting a cobblestone in the enrichment chamber gives me a diamond as result.

**Comment by aidancbrady** [comment]
Consider reading this: https://github.com/aidancbrady/Mekanism/wiki/IMC-based-recipe-integration

**Comment by Slater022** [comment]
@aidancbrady Yeah Believe me I read that. 
It work now.
Someone tell me to use that way to do that : 
```
@EventHandler
    public void init(FMLInitializationEvent event) {
        RecipeHandler.Recipe.METALLURGIC_INFUSER.get().clear();
        RecipeHandler.addMetallurgicInfuserRecipe(InfuseRegistry.get("CARBON"), 50, new ItemStack(MekanismItems.EnrichedAlloy), new ItemStack(MekanismItems.ControlCircuit, 1, 0));
    }
```
Unfortunately that seem to not work when i run the client ... :/
