### ISSUE TITLE
Bug: Atomic Disassembler

### ISSUE THREAD

**Issue by maginator** [aidancbrady/Mekanism#4318]
Hi there 
after i Update to Mekanism 9.2.2 the Atomic Disassembler dosent Charge Wireless via Wireless Charger from Ender IO. I hope you Fix that.

LG Magi

**Comment by ktole1999** [comment]
nothing will charge from enderio at the moment. guessing you are talking about 1.10? they are having issues communicating when it comes to power transfer. read open and closed issues on this.
