### ISSUE TITLE
[1.11.2] All recipes with empty spaces do not work

### ISSUE THREAD

**Issue by allanf181** [aidancbrady/Mekanism#4319]
![image](https://cloud.githubusercontent.com/assets/14101716/25068970/37ee0616-2249-11e7-9ea8-d4c6d514f923.png)
![image](https://cloud.githubusercontent.com/assets/14101716/25068972/406ec2f8-2249-11e7-8fdd-d80f2699ba9a.png)
![image](https://cloud.githubusercontent.com/assets/14101716/25068973/48bbb600-2249-11e7-9979-fb29c907c8ce.png)
![image](https://cloud.githubusercontent.com/assets/14101716/25068974/500b28dc-2249-11e7-8d5f-29aebe73e8d3.png)
![image](https://cloud.githubusercontent.com/assets/14101716/25068975/56fa014a-2249-11e7-9d69-fc72ef9bf74a.png)

Mekanism: https://github.com/aidancbrady/Mekanism/commit/20cf847b64f66466d62771532d0ab7b435a0829b
Forge: 13.20.0.2282

**Comment by ThatGamerBlue** [comment]
More null itemstacks -> ItemStack.EMPTY

**Comment by cyberpunkbln** [comment]
Hello,
yes some recipes are not crafttable but viewable in JEI. I try to help me with CraftTweaker and by the Way no Recipe will shown in jei_1.11.2-4.3.2.264.

**Comment by ThatGamerBlue** [comment]
working on it

**Comment by cyberpunkbln** [comment]
Thx

**Comment by cyberpunkbln** [comment]
Some Crafttweaker-Recipes for the time to the Bugfix:):

`recipes.addShaped(<mekanism:anchorupgrade>, [[null, <minecraft:glass>, null], [<mekanism:enrichedalloy>, <ore:dustDiamond>, <ore:itemEnrichedAlloy>]]);
recipes.addShaped(<mekanism:energyupgrade>, [[null, <ore:blockGlass>, null], [<ore:itemEnrichedAlloy>, <ore:dustGold>, <mekanism:enrichedalloy>], [null, <ore:blockGlass>, null]]);
recipes.addShaped(<mekanism:speedupgrade>, [[null, <ore:blockGlass>, null], [<ore:itemEnrichedAlloy>, <ore:dustOsmium>, <mekanism:enrichedalloy>], [null, <ore:blockGlass>, null]]);
recipes.addShaped(<mekanism:transmitter:2> * 8, [[<mekanism:ingot:4>, <minecraft:glass>, <mekanism:ingot:4>]]);
recipes.addShaped(<mekanism:controlcircuit:1>, [[<mekanism:enrichedalloy>, <ore:circuitBasic>, <ore:itemEnrichedAlloy>]]);
recipes.addShaped(<mekanism:transmitter>*8, [[<ore:ingotSteel>, <ore:dustRedstone>, <mekanism:ingot:4>]]);
recipes.addShaped(<mekanism:machineblock2:11>, [[<ore:dustRedstone>, <ore:ingotIron>, <ore:dustRedstone>], [<ore:ingotIron>, null, <ore:ingotIron>], [<ore:dustRedstone>, <minecraft:iron_ingot>, <minecraft:redstone>]]);
`

The Robot must be cheated:(

**Comment by D4rknessKing** [comment]
@allanf181 managed to fix it in his fork ¯\_(ツ)_/¯

**Comment by thommy101** [comment]
Thank you @allanf181 for finding it.. I looked totally at the wrong spot. Hope you don't mind that I included it in a pull request with other null itemstack issues.

**Comment by cyberpunkbln** [comment]
Hello,

i have copied yout fixes to the last commit from adanbradys 1.11 branch and compiled. 

thx, first the Receipe-Bug are bugfixed and the Digital Miner don't cause a crash no more. I think that the digital miner don't accept Crates from ActAdditions is another issue.

Very thx the receipe-bug was hard to resolve, thanx to you and allanf181. My times where i have activ java code was to j2me times:).

I'm an old man:), but can you please merge your [https://github.com/thommy101/Mekanism/commit/704826f0fd52726636ba7b4e280ca73af5b9dfa4](https://github.com/thommy101/Mekanism/commit/704826f0fd52726636ba7b4e280ca73af5b9dfa4) Commit with the actual 1.11 Branch from adanbrady with his commits? I'm a simple Git-Cloner:).
