### ISSUE TITLE
[1.11.2] Dusts smelt into nuggets instead of ingots.

### ISSUE THREAD

**Issue by Ristovski** [aidancbrady/Mekanism#4326]
Unless I missed some undocumented change, dusts seem to be broken as they smelt into nuggets instead of ingots.

Edit: Even JEI shows this:

![alt tag](https://ptpb.pw/_M4-.png)

**Comment by thommy101** [comment]
Wierd.. As stated at https://github.com/aidancbrady/Mekanism/blob/1.11/src/main/java/mekanism/common/Mekanism.java#L827 it should be a ingot..

**Comment by Ristovski** [comment]
I tested all possible dusts and they all smelt into nuggets.
Were you able to replicate this?

**Comment by thommy101** [comment]
I'm currently not able to start a dev environment. I will let you know when I'm home and tested this.

**Comment by thommy101** [comment]
Looks like you have some additional mods who are changing the minecraft smelting. Mekanism uses the vanilla smelting. My dusts are smelting just fine to ingots.

**Comment by Ristovski** [comment]
Seems like BetterWithMods somehow managed to slip into my test instance of Minecraft. 
**Resolved: NOTABUG**

**Comment by thommy101** [comment]
(You can close your own issues ;) )

**Comment by Ristovski** [comment]
How much I hate a wonky internet connection...
