### ISSUE TITLE
[1.11.2] Digital Miner don't accept Crates from Actually Additions for input and ouput

### ISSUE THREAD

**Issue by cyberpunkbln** [aidancbrady/Mekanism#4327]
Hello,

Digital Miner don't accept Crates from Actually Additions for input and ouput. IronChest and other mods with correct ore-Dic entry as an chest will be accepted.

AA has no ore-Dic Entry and an own block <actuallyadditions:block_giant_chest>

But with all the great Fixes in the last time from the Community i have Pipes for pumping cobble out to an iron chest:).

**Comment by thommy101** [comment]
It's related to #4283.
Actually Additions only supports item capabilities and not the IInventory which is currently the only supported way in Mekanism.
