### ISSUE TITLE
Universal cables not compatible with ForgeMultipart

### ISSUE THREAD

**Issue by halvors** [aidancbrady/Mekanism#4333]
Universal cables not compatible with ForgeMultipart, MCMultipart works.

Is this supposed to be supported?

**Comment by aidancbrady** [comment]
As FMP is no longer actively being updated I decided to change support from FMP to MCMP.  Most mods are making the transition as well, at least as of 1.11.

**Comment by halvors** [comment]
@aidancbrady It actually is updated, at least for 1.11.

**Comment by aidancbrady** [comment]
Just saw that. Is it being developed by chickenbones or is it being continued by someone else? I'll definitely consider adding integration if there are plans to keep it updated beyond 1.11.

**Comment by halvors** [comment]
@aidancbrady Think it is developed by chickenbones.
