### ISSUE TITLE
[1.11.2] Dupe bug quantum entangloporter

### ISSUE THREAD

**Issue by thommy101** [aidancbrady/Mekanism#4334]
As 1.11.2 isn't publicly released I'm reporting this easy dupe bug publicly:

What happens:
Quantum entangloporters dupe items infinitely when transporting them.

Expected:
Only send the items it receives elsewhere.

How to reproduce:
Hook up a chest to some logistical transporters (I used two of them)
Connect the pipes to a quantum entangloporter
Place a second quantum entangloporter
Connect two pipes to it
Connect a chest to those pipes
Configure input/output
Set both quantum entangloporters to the same channel

Mini schematic:
```
C--QEQ--C

C = Chest
- = Logistical transporter
E = Creative energy cube
```

--Edit-- Damn markdown

**Comment by aidancbrady** [comment]
Fixed!
