### ISSUE TITLE
[1.10.2] Induction Matrix doesn't report input to OpenComputer 

### ISSUE THREAD

**Issue by MokuJinJin** [aidancbrady/Mekanism#4335]
I'm using OpenComputer to have a graphical monitoring of my induction matrix.

Induction Matrix shows in the computer component, all methods return correct values (getOutput(), getEnergy(), getMaxEnergy(), ...) except getInput() wich return always 0.

The only input is a solar panel ( Environmental Tech), with enhanced energy cable (EnderIO).
The Energy goes down when it is the night (obviously solar panel), and goes up in the day.
So everything is good, except this getInput()

Mekanism 9.2.1
Forge 12.18.3.2185
OpenComputer 1.6.1.6
MC 1.10.2

**Comment by aidancbrady** [comment]
This is related to another issue that I'm currently in the process of finding a fix for.
