### ISSUE TITLE
[1.11.2] When right clicking a tank with lava in it, it does not yield a bucket of lava.

### ISSUE THREAD

**Issue by savosdarkran** [aidancbrady/Mekanism#4337]
Hello,

When I right click a tank of lava with an empty bucket it removes the lava from the tank, but I don't get a bucket of lava.

This can be reproduced.

Mekanism: 9.3.0.44

**Comment by thommy101** [comment]
I've heard of this before. Something changed in the fluid integration of Forge. 

I'll look back for the change.

**Comment by aidancbrady** [comment]
Fixed!
