### ISSUE TITLE
Ore pick up issues

### ISSUE THREAD

**Issue by ApostolosRisen** [aidancbrady/Mekanism#4338]
So using this in a private pack, Although the ore I am looking for is in the ore dictionary and is addable to the list of searches the digiminer does not find it and mine it, the ore in question being  dark gem ore from evilcraft, 
![image](https://cloud.githubusercontent.com/assets/26664327/25318412/4405652a-285c-11e7-94ba-c8a5b5cdb07f.png)
this is the ore in the ore dictionary entry tab and I found the ore less than seven blocks away as well as testing in creative mode and no luck 
assistance on editing the blocks that are picked up by the digiminer would be nice or this could be a bug with evilcraft and I will be posting this there as well

**Comment by thommy101** [comment]
Cannot reproduce with latest version. Which versions do you use?

**Comment by ApostolosRisen** [comment]
Ok if it's a case of issue with version there isn't anything I can do about it now, I have a friend hosting the server, but if it isn't just that how would I go about adding an oredict tag to the ore

**Comment by ApostolosRisen** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } I'm using I think one or maybe two off from the newest version for 1.10.2 I'll get you the exact versions for both mods when I get home  if you know how to add oredict tags I could start with that 


Sent from Yahoo Mail for iPhone


On Monday, April 24, 2017, 2:03 PM, Tom E <notifications@github.com> wrote:


Cannot reproduce with latest version. Which versions do you use?

**Comment by rubensworks** [comment]
Glowing Dark Ore not reverting to the regular blockstate (with oredict) will be fixed in the new EvilCraft release: CyclopsMC/EvilCraft#541
So this issue should not occur anymore then.
