### ISSUE TITLE
[1.11.2] Nice little Feature-Request - Cardbox break after one use

### ISSUE THREAD

**Issue by cyberpunkbln** [aidancbrady/Mekanism#4340]
Hello,

is this easy possible to make the Cardboxes as an OneUse-Item? With Config?

At the moment i increase the price for this cardboxes. Are a few bit to cheap for me.

Thx

**Comment by aidancbrady** [comment]
I like the reusability of the boxes. Increasing the price via crafting sounds like a good alternative.

**Comment by cyberpunkbln** [comment]
Yes the reusability of the boxes are cool, but the Actually Additions part is a one use and useless in comparsion with the cardboxes.  Yes i think increasing the price seems like the better and easier option.

wear? no? Smile;)

**Comment by BrianEdmonds** [comment]
As I recall, the boxes have infinite durability.  If you're interested
in realism, it would be nice to give them some durability loss per use,
just like real world boxes wear out with use.  I think it would make
perfect sense for them to be cheap, but not especially durable.

**Comment by cyberpunkbln** [comment]
This will be great cheap and with durability loss and with an ini option for on/off;).
