### ISSUE TITLE
Digi miner cannot mine Gregtech ores as of 1.7.10 lastest

### ISSUE THREAD

**Issue by redmage17** [aidancbrady/Mekanism#4341]
It sees them with the ore dictionary entry but refuses to pull them. They are tile entities but nothing in the mode code should prevent it being mined

**Comment by aidancbrady** [comment]
1.7.10 is no longer supported

**Comment by redmage17** [comment]
And 1.10 is buggy and missing chunks of content as well as several core mods.

**Comment by aidancbrady** [comment]
Which is why development is now focused on 1.11.
