### ISSUE TITLE
[1.11.2] UUID conversion

### ISSUE THREAD

**Issue by thommy101** [aidancbrady/Mekanism#4342]
(Opening an issue for visibility) 

There is an issue with your UUID commit.
I don't know exactly what happend, but my guess is an hover over an fluidtank.
Log: https://gist.github.com/thommy101/ea43c6df2fd4bba594664057a5c8ecbc

Playing on an old 1.11 world.

--Edit--
Shift hover over an fluidtank in my inventory triggered this bug.

**Comment by aidancbrady** [comment]
Ah, looks like merely a conversion issue. Not worried as I consider 1.11 to be a hard update.

**Comment by thommy101** [comment]
In my pull request was a little part about an username to uuid conversion which only runs once. Maybe an idea to use it?

**Comment by thommy101** [comment]
I also think here are some issues with nbt tag conversions. There seems to be changes to the tag to get, but the check if those tags exists are not changed.

https://github.com/aidancbrady/Mekanism/blob/1.11/src/main/java/mekanism/common/tile/component/TileComponentSecurity.java#L156

**Comment by ruyanve** [comment]
I also am having issue with NBT tags on 1.11.2. The mod LevelUp sets a no place nbt tag on ores which makes them not process in mek machines. Didn't know if I should open a new issue since it was mentioned here...

**Comment by aidancbrady** [comment]
All done!
