### ISSUE TITLE
Transparent Jetpacks

### ISSUE THREAD

**Issue by Inquesitor** [aidancbrady/Mekanism#4343]
So I installed the mod and at first everything appeared normal, but then I noticed the chest plate thing on the armored jetpack was transparent/see through, I thought it might have something to do with my minecraft skin, but when I was certain dimensions like the Nether, the End, Mars (from the Galacticraft mod) it was fine/solid. My immediate thought was that this was a bug caused by something I did in the world I was playing in, but then I noticed it seemed to be the same issue on another world I had, which made me think that this might be how it was made, I have no clue, does anyone have an answer, explanation, or solution to this?  

Btw, I'm using it for 1.7.10

**Comment by aidancbrady** [comment]
This is an interaction with another mod.

**Comment by Inquesitor** [comment]
If I was to provide a list of the mods I'm using could you tell me *which*
mod?

**Comment by Inquesitor** [comment]
Could you?
