### ISSUE TITLE
Mekanism pipes crashing server

### ISSUE THREAD

**Issue by Curunir** [aidancbrady/Mekanism#4348]
Greetings!

I have been using the latest Mekanism 1.10.2 build (301) in my private pack, which I am still testing. It works fine mostly, but there is one reproducible crash issue relating to pipes. When I teleport back to my base area (usually coming through the Nether Portal, but the method does not matter, happens with other methods, too), the server instantly crashes with a ticking block entity error. Crash log:
https://hastebin.com/edinarimoq.pl

This happened several times now, always pointing to a block that was occupied by a Mekanism pipe (Ultimate Mechanical Pipe, Elite Logistical Transporter, at this point I think all of them are affected). The pipes in question are not in direct contact with the teleport location, but some blocks off to the side. When I remove them, the crashes stop happening. Crash happens fairly often, but not on every occasion, maybe 50% of the time I teleport back there. Base is not chunkloaded prior to teleporting.
The client gets kicked out on server crash, but remains stable itself. This is purely a server issue. Running on Forge 12.18.3.2281, using Asie's FoamFix on both client and server (coremod/anarchy version on the client, lawful version on the server). I'd be happy to provide further information, just tell me what you need.

My workaround for now is not using Mekanism pipes, at least not in the vicinity of teleporting locations.

**Comment by thommy101** [comment]
Thank you for your descriptive report! I've got 2 questions:
Can you show a picture of the surroundings of the crashing pipe? Trying to replicate the issue over here. 
And can you replicate it without foamfix?

**Comment by Curunir** [comment]
![crashing_mek_pipe](https://cloud.githubusercontent.com/assets/8467967/25484119/fbc7546c-2b58-11e7-9cbd-dfea1305e633.jpg)
Here is a picture of the pipe from the crash report (right in the middle between the Immersive Engineering Coke Ovens). It did happen with several others. Basically, as long as any Mekanism pipe was near, the crash would occur. Now that I think of it, Universal Cables are exempt from this - still have them, but no crashes. It might be important that all the pipes in question had been set to force-extract on at least one end. My (wild) guess is that the code doing the force-extract is triggering the issue.
I will make a test run without Foamfix next.

**Comment by Curunir** [comment]
Turns out I meant to include Foamfix in the server package, but never got around to it. These crashes are happening without Foamfix - while the client has it, the server is the one that is crashing.

**Comment by aidancbrady** [comment]
Shouldn't be an issue anymore in 1.11 :)
