### ISSUE TITLE
IC2 Classic Crashing Industrial Turbine

### ISSUE THREAD

**Issue by LukasGrove** [aidancbrady/Mekanism#4351]
I have a max size turbine (17x17 and 18 tall, using condensers), when I complete the multiblock structure (while steam is hooked up to it) it crashes with the attached log. I can log back in, and the turbine "works" (the animation is frozen, but the power generation works), but after awhile is crashes with the same errors again. Anytime I connect steam to it it crashes, I'm feeding it from a mekanism reactor (also when it crashes the reactors turn off and the fuel is set back to 0).
Removing IC2 Classic fixes the issue, so I know it's related to that. It seems like this was an issue in the past: [https://github.com/aidancbrady/Mekanism/issues/3255](url)

Minecraft Version: 1.7.10
KCauldron:1.7.10-1614.201
(IC2Classic Version 1.2.1.5.jar)
(Mekanism-1.7.10-9.1.0.281.jar)

[crash-2017-04-29_16.17.07-server.txt](https://github.com/aidancbrady/Mekanism/files/966453/crash-2017-04-29_16.17.07-server.txt)

**Comment by Palpiter** [comment]
Reproducable in creative and singleplayer as well, the crash happens the moment the internal energy-storage of the turbine hits 8.49 or 8.5G RF.

I used a 11x11x18 turbine so I assume it's independent of the size as long as the internal buffer can go that high.

Versions used:
Minecraft 1.7.10
Forge 10.13.4.1614
Mekanism 9.1.0.281
IC2Classic 1.2.0.3 (should probably update that)

Crashlog attached in case there's some additional usefull info.
[crash-2017-04-30_02.20.33-server.txt](https://github.com/aidancbrady/Mekanism/files/966490/crash-2017-04-30_02.20.33-server.txt)

**Comment by LukasGrove** [comment]
Glad to know it's not just me, thanks Palpiter. Just another thing IC2 fails at... If it wasn't for the mass fabricator (which is pretty much the only thing I've found that uses the kind of power these machines make) I'd ditch IC2 all together.

Think there's any way to fix this on the Mekanism side? because I imagine getting IC2 to do anything wouldn't happen.

**Comment by thommy101** [comment]
1.7.10 isn't supported anymore. Development is currently focused on 1.11.2

**Comment by aidancbrady** [comment]
Should be fixed.
