### ISSUE TITLE
Digital Miner won't eject any items

### ISSUE THREAD

**Issue by Spearkiller** [aidancbrady/Mekanism#4353]
I am using Mekanism-1.10.2-9.2.2.301

I have spent the past hour or two in my Single Player world trying to get my digital miner attached to my ore processing system, but nothing will connect.
Logistical Sorters will not extract any items no matter what side I place it on, Mekanism transport pipes will not connect to any sides, and EnderIO item conduits won't even take items out of them, even when configured to not require redstone and to only export items.
Auto Eject was enabled and nothing would happen even when a chest was placed directly next to the miner, next to any ports.

**Comment by thommy101** [comment]
I'm pretty sure that the digital miner would output items. Have you tried placing a vanilla chest on the back of the digital miner (top mid) with auto output enabled?
Mekanism transport pipes should also work (although there is a visual bug of them not connecting).

**Comment by ktole1999** [comment]
and you confirmed this with no other mod installed except mekanism and forge?

**Comment by thommy101** [comment]
Which other chests do you have (besides oak chests). I only know of the chests from the mod Quark, which do work exactly as the vanilla chests.

**Comment by BrianEdmonds** [comment]
> Which other chests do you have (besides oak chests)?

I recall a recent issue where it wouldn't eject to Actually Additions
crates, but I also seem to recall that may have been fixed.  No idea if
there is a release out with the fixes, as I'm a bit out of date on
Mekanism updates.

**Comment by thommy101** [comment]
There was an issue with all storage blocks which only supported the new inventory methods through capabilities, which has been fixed in the 1.11 branch which currently have no official release.

But if there are any storage blocks who support the old method (IInventory) and do not work, it is a bug.

**Comment by ktole1999** [comment]
@Spearkiller i am using v300 of mekanism and do not experience this issue.

**Comment by Spearkiller** [comment]
@thommy101 I tried with diamond and obsidian chests from the ironchest mod. I found it confusing as my ore setup would still deposit into an obsidian chest but I could not for the life of me get the miner to.

**Comment by thommy101** [comment]
Well.. That is wierd. The mod iron chests (https://github.com/progwml6/ironchest/) should work. I'll test this and see if I can reproduce it.

If you're using an other ironchest mod, please let me know ;)

**Comment by aidancbrady** [comment]
Just did some testing, the Digital Miner was able to output to progwml6's Iron Chests just fine.
