### ISSUE TITLE
[1.10.2] blocks showing wrong textures

### ISSUE THREAD

**Issue by YOYOK9** [aidancbrady/Mekanism#4354]
On my server players have started to comment that some of their machines are changing into other machines visually but are still the same working wise. So like an elite smelter looks like and enrichment chamber and vice versa. 
using Mekanism 301

Block is an elite enriching factory but shows as a smelting factory that has been rotated.
https://puu.sh/vEEgP/cf7df9b958.jpg

**Comment by BrianEdmonds** [comment]
This has been a longstanding issue.  My experience is that it happens in
tandem with chunk updates.  Having a tree grow in the same chunk is a
guaranteed trigger, but there are others.

**Comment by aidancbrady** [comment]
Fixed in 1.11 branch
