### ISSUE TITLE
[1.10.2] IC2 power blacklist doesn't work

### ISSUE THREAD

**Issue by WildKarrade** [aidancbrady/Mekanism#4355]
Using release 9.2.2.301 with the option B:BlacklistIC2Power=true the cables still connect to IC2 machines and feed them power. I turned the setting on because when trying to change the ratio to more evenly match the RF conversion EU things either exploded or gained power way to fast. Maybe the IC2 API being used is outdated but it's definitely not working correctly at all. I have a server with a few friends to play together since we haven't in a while and one of them informed me it still works.

![](http://i.imgur.com/LWZzzEN.png)

**Comment by thommy101** [comment]
The config change should do the trick. The boolean overrules everything, for that it doesn't even need an up to date API. Have you changed the value client and server side?

**Comment by WildKarrade** [comment]
IC2 doesn't provide any others however given that the conversion between EU and RF in the config isn't working either I'm guessing it's not just the config. The config is on both server and client side yes, although for a setting such as that it should read from the server regardless of what the client says because that could cause problems.

**Comment by thommy101** [comment]
It isn't much better in the current 1.11.2 release... The cables do not connect at all.
And apparently is my Minecraft client bugged as I cannot seem to find any logs. So sorry, no log yet from me.

**Comment by aidancbrady** [comment]
Merging with #4370
