### ISSUE TITLE
[Request] Forge Power Compatibility

### ISSUE THREAD

**Issue by devilunaworkshop** [aidancbrady/Mekanism#4356]
Would be nice if you could charge items compatibile with Forge Power API using Mekanism.

**Comment by thommy101** [comment]
It's already implemented in the 1.11 branch

**Comment by devilunaworkshop** [comment]
Ah, so no backporting to 1.10?

**Comment by aidancbrady** [comment]
I'm focusing development on 1.11- I sadly don't have the time to manage both branches at once.
