### ISSUE TITLE
Weird particle Bug

### ISSUE THREAD

**Issue by Deloyar81** [aidancbrady/Mekanism#4359]
**Issue Description:**

There is a bug with particle rendering related to mekanism. 
Nearly everytime a player re-enter a chunk by porting in (it seems, that it doesn't matter what kind of port is used; I tested it with Mekanism Portable Teleporter, RFTools Dimensional Porting System and Journey maps waypoint teleport) all particle effects like for example Botanias Natura Pylon, Mana spreader, Mekanisms Fusion Laser, Endermans teleporting Particles, mining particles, etc are disabled.

This is a multiplayer and SP bug, I could reproduce it in creative SP.

The only fix for this at the moment is to restart the whole client, only reconnecting to the server doesn't help.

But it doesn't seem to be the port itself. The problem doesn't appear, when I am porting into the chunk I am already in. Neither when I am porting into an (clientsided) unloaded area for the first time. And re-enter the chunk by flight causes no problems too.
It seems to be the second port in an area with a mekanism Multiblock like Brine Tower, industrial Turbine, fusion reactor, etc; after that, all particles are gone.
For now, only the induction matrix seems not to be the problem. At least the issue doesn't appear when it's the only multiblock in range - for now.

**I confirmed the issue with a minimal setup:**

ChickenChunks-1.10.2-2.2.0.52-universal (to chunkload the teleporter)
CodeChickenCore-1.10.2-2.4.1.102-universal
CodeChickenLib-1.10.2-2.5.8.255-universal
Mekanism-1.10.2-9.2.2.301
MekanismGenerators-1.10.2-9.2.2.301
MekanismTools-1.10.2-9.2.2.301
MCMultiPart-1.4.0-universal

**Affected Versions:**

Minecraft 1.10.2
Forge 12.18.3.2254/2281
Java 8 Update 131
Mekanism : 1.10.2-9.2.2.301
Mekanism Generators: 1.10.2-9.2.2.301
MekanismTool: 1.10.2-9.2.2.301
Dedicated Server for a few friends
215 mods (private modpack)

**Comment by aidancbrady** [comment]
I wouldn't call this a Mekanism bug, rather an issue with the Minecraft particle renderer. I'm not doing anything that would cause this.

**Comment by Deloyar81** [comment]
To Clarify:
This issue report should be no offense against mekanism; I like your mod, it has a cool design and nice playstyle.
It's something I've been noticed and which seems relative important so I reported it. ;)

I investigate a little bit deeper and tested following setups so far:

ChickenChunks-1.10.2-2.2.0.52-universal (to chunkload the teleporter)
CodeChickenCore-1.10.2-2.4.1.102-universal
CodeChickenLib-1.10.2-2.5.8.255-universal
Mekanism-1.10.2-9.2.2.301
MekanismGenerators-1.10.2-9.2.2.301
MekanismTools-1.10.2-9.2.2.301
MCMultiPart-1.4.0-universal

(I tested different multiblocks like Fusion Reactor / Industrial Turbine / Brine Tower / Induction Matrix; all on their own, means I broke one block of the multiblock and  tested the next candidate)

- Issue encountered by Brine Tower / Fusion Reactor / I-Turbine / Induction Matrix

-----

ChickenChunks-1.10.2-2.2.0.52-universal (to chunkload the teleporter)
CodeChickenCore-1.10.2-2.4.1.102-universal
CodeChickenLib-1.10.2-2.5.8.255-universal
Mekanism-1.10.2-9.2.2.301
MekanismGenerators-1.10.2-9.2.2.301
MekanismTools-1.10.2-9.2.2.301
MCMultiPart-1.4.0-universal
Botania r1.9-341
Baubles 1.102-1.3.10

Botania for his great amount of particle effects and Mekanism only for the teleporter, no other machine

- no issue

-----

Botania r1.9-341
Baubles 1.102-1.3.10
ChickenChunks-1.10.2-2.2.0.52-universal (to chunkload the area, if this cause the issue)
CodeChickenCore-1.10.2-2.4.1.102-universal
CodeChickenLib-1.10.2-2.5.8.255-universal
teleport command

- no issue

-----

Botania r1.9-341
Baubles 1.102-1.3.10
teleport command

- no issue

------

ChickenChunks-1.10.2-2.2.0.52-universal (to chunkload the teleporter)
CodeChickenCore-1.10.2-2.4.1.102-universal
CodeChickenLib-1.10.2-2.5.8.255-universal
Mekanism 1.10.2-9.2.0.292
Mekanism Generators 1.10.2-9.2.0.292
Mekanism Tools 1.10.2-9.2.0.292
MCMultiPart-1.4.0-universal
teleport command

- Issue encountered by Brine Tower / Fusion Reactor / Induction Matrix / I-Turbine

-----
I build the Multiblock and port, the issue appears. I restart the client (only relog doesn't work) and break one block of the multiblock and port, no issue appears. I repair the block and port... issue appears. (Sometimes it happened, when I finished the multiblock and the red sparkles appeared, no need for port)
I tested in my mainworld multiblocks of other mods too, but nothing happened (like Immersive Engineering, EnderIO Capacitorbanks). It seems to be something about the forming of the multi, directly after the red sparkles appears, but this is a shot in the dark.
Maybe the particle renderer of Minecraft is responsible for the issue, but Mekanism's multiblocks are definitely related to it. I'm surprised, nobody else noticed it yet.
You can do with this report what you want now, your the author - ignore it or look a little bit closer to what the relationship between the particle rendering and the multiblocks is.
I won't do anything further.
