### ISSUE TITLE
Mekanism MDK 9.2.2.301 (Latest/recommended) Unusable; Imports from files not available

### ISSUE THREAD

**Issue by TheGuyRunningSouth** [aidancbrady/Mekanism#4361]
mekanism/api/gas/GasNetwork.java Line 14, /gas/GasTransmission.java Line 10, and potentially more import from mekanism.common.capabilites.Capabilites which is inaccessable from the API.

It looks like it was brought up in issue #3896 and marked as fixed, but the changes haven't reached the code base in master or 1.10 branch.
I'd hoped to be able to try and make an addon that adds more content with gasses and possibly adds more uses for heat, but haven't had any luck since my project won't build because of the API issue.

Sorry if I've missed something that works around this.

TheGuyRunningSouth

**Comment by thommy101** [comment]
Development has switched to 1.11. There has the whole gasnetwork/transmission been taken out of the API and is now part of the mod itself.

See commit 4733420eee39f8c65a54aae98e961bf742d7fd3f

**Comment by turbodiesel4598** [comment]
Sorry, just want to ask then - is the MDK unusable for MC 1.10.2?

**Comment by thiakil** [comment]
Aidan has just merged Thommy's big PR where we backported many 1.11 changes, so when that hits release (if it hasn't already) this might be fixed. You could test it out by building your own MDK from the 1.10 tree with gradle task `MDKZip`

**Comment by thommy101** [comment]
I might have skipped one commit related to the api as I wasn't 100% sure if the changes made it to 1.10 (a lot of energy has changed and the transmitters). Let me know if it works or not
