### ISSUE TITLE
Digital miner crash 1.11.2

### ISSUE THREAD

**Issue by woodzykiler** [aidancbrady/Mekanism#4364]
When u open the config button on insode the digital miner then select any option the game crashes.
1.11.2

**Comment by ktole1999** [comment]
wont do any good to report it if there is not a crash report attached.

**Comment by woodzykiler** [comment]
Here are the requested reports:
[crash-2017-05-12_17.17.03-client.txt](https://github.com/aidancbrady/Mekanism/files/997955/crash-2017-05-12_17.17.03-client.txt)
[fml-junk-earlystartup.txt](https://github.com/aidancbrady/Mekanism/files/997959/fml-junk-earlystartup.txt)

[fml-client-latest.txt](https://github.com/aidancbrady/Mekanism/files/997957/fml-client-latest.txt)

[latest.txt](https://github.com/aidancbrady/Mekanism/files/997960/latest.txt)

**Comment by aidancbrady** [comment]
Update your Mekanism build
