### ISSUE TITLE
Machines produce Light (Yes that is bad)

### ISSUE THREAD

**Issue by ProxyPlayerHD** [aidancbrady/Mekanism#4367]
[As you can see here](https://i.gyazo.com/15aaf52e243e8bd63de6c58a11e7562b.mp4)
The Constant Ligth updates create quite some lag. during the Day it is not really there, but in the Night or in Rooms where not every single block has a light source this can butcher the FPS really down.

Why isn't there an Option in the config or some kind of Upgrade or Button to turn the Light from these things off?

**Comment by thiakil** [comment]
There is. Client settings -> Enable Ambient Light(ing?). Turn this off.

**Comment by ProxyPlayerHD** [comment]
where exactly is it? like what config file.

**Comment by thommy101** [comment]
Modpackfolder/config/mekanism.cfg
In the category client there is a "B:EnableAmbientLighting=true" setting this to false disables the light updates from the machines.

**Comment by thiakil** [comment]
You can also do it from within the client. Pause menu -> Mod Options -> Mekanism

**Comment by ProxyPlayerHD** [comment]
Thank you. i will see if i can get the Modpack Creators to make this the Default Option.
