### ISSUE TITLE
[1.10.2] Dynamic tanks not outputing liquid

### ISSUE THREAD

**Issue by WildKarrade** [aidancbrady/Mekanism#4369]
After using dynamic tanks to store lava and water using the same sizing of railcraft I realized that inputting the liquids worked fine, extracting them doesn't. I tried valves on several different sides and pipes including mekanisms own mechanical pipes and it doesn't output any liquid at all.

Edit: The mechanical pipes started working but the enderio or immersive engineering ones still won't output from any mekanism device.

**Comment by aidancbrady** [comment]
Sounds like they need to update their fluid integration.

**Comment by WildKarrade** [comment]
I will report it to them then, given the other issue I encountered and reported with IC2 power I assumed it was an out of date API that was being used for enderio that stopped working properly.
