### ISSUE TITLE
IC2 compatability

### ISSUE THREAD

**Issue by SpatiumPrinceps** [aidancbrady/Mekanism#4370]
Hi there, 

thank you for this awesome mod :) However, there is a huge logspam...

https://gist.github.com/SpatiumPrinceps/ec37b0c82bba89b3f35ef12681ee5606

This happens very often... I think it started when the IC2 API got major changes. 

IC2: 2.6.211
Mekanism: 9.2.1.298
Forge 2185 

Thank you for your efforts!

**Comment by bookerthegeek** [comment]
Can you cut that out from the post and put it up on gist.com please?

**Comment by SpatiumPrinceps** [comment]
Sorry 👍

**Comment by SpatiumPrinceps** [comment]
Yea, just discovered something. The Mekanism machines cant pull EU as they used to do

**Comment by bonnedav** [comment]
Please get this working.

**Comment by thommy101** [comment]
It's on the radar, but guessing the holidays are quite the same over the world, and so are schools, I guess there are exam periods which everyone is quite busy with.

**Comment by aidancbrady** [comment]
Funny, the primary issue with 1.11 compatibility is the fact that all mod IDs became lowercase. I'm looking into this and should have a fix out by the end of the week.

**Comment by aidancbrady** [comment]
Fixed in 1.11 development branch!
