### ISSUE TITLE
JetPack Suggestions

### ISSUE THREAD

**Issue by jubalearly** [aidancbrady/Mekanism#4371]
Running 1.11.2 previous build from current (does not appear latest version has a fix so haven't updated).

When hovering on jetpack and you come to a landing, you almost always have to hit shift at least once more to fully "land" and stop the jetpack from hovering.  This frequently creates a problem in that often when you are mining without fully being "landed" the blocks you break become ghost blocks.  

This is a very reproducible issue, the solution is to keep pressing shift until the hover mode turns off.  It seems like this could be tweaked pretty easily so you better register when player has landed and turn off hover mode.

I know you have addressed this in early submissions but I would love to see the forward/lateral speed of the jetpack increased.  Maybe via speed upgrades like the machines.  I find that I mainly make the Mek jetpack for mid-game and switch to something else that is faster.  

Loving the 1.11.2 update and appreciate your hard work.

Thanks.

**Comment by aidancbrady** [comment]
The bug you mentioned has already been reported.

The jetpack mode you mentioned is definitely high on my agenda once I finish the fixes for the 1.11.2 release.  Keep an eye out :)
