### ISSUE TITLE
Crash with Storage Drawers controller 1.11.2

### ISSUE THREAD

**Issue by jubalearly** [aidancbrady/Mekanism#4373]
Trying to dump from chest into storage drawers controller using logistical transporter cables
 
https://pastebin.com/7w6c58zN

**Comment by thiakil** [comment]
That looks like a Storage Drawers bug to me, Mek is calling a method on its ItemHandler which is crashing inside SD code.

**Comment by thommy101** [comment]
It does work here using latest Mekanism version of now, Storage Drawers 4.2.6 and forge 2282.
