### ISSUE TITLE
[1.11.2] Metallurgic Infuser Dupe

### ISSUE THREAD

**Issue by 016Nojr** [aidancbrady/Mekanism#4375]
When placing a Metallurgy Infuser next to a basic universal cable it dupes the metallurgic infuser. 

Forge: 13.20.0.2298
Mekanism: 9.3.0

Mods: https://gyazo.com/c9f248f41f8db40ecb8f13162ff4969b

**Comment by thommy101** [comment]
Cannot reproduce in 1.11.2, version of right now. Probably an other mod who does some weird things.

**Comment by 016Nojr** [comment]
I can not test right now, but try adding Inventory Tweaks

**Comment by aidancbrady** [comment]
Going to call this an interaction issue, can't reproduce with Mekanism alone.
