### ISSUE TITLE
[1.11] Logisitcal Transporter Malfunctions

### ISSUE THREAD

**Issue by RODragon** [aidancbrady/Mekanism#4376]
There are two major issues with the logistical transporters in the most up to date 1.11 branch commit. I have tested this in both single player and multiplayer, with Mekanism the only mod loaded. Forge Version 13.20.0.2298

-------------------
1. Actively pulling from Mekanism machine outputs duplicates items indefinitely. 

After some testing, it looks like the transporter is looking at the item that is in the output for a machine, and decreasing the count and type of the item in the input. As long as there is an item in the output, the transporter will continuously decrement the input slot, even converting what is in the input to the item in the output. As the transporter pulls when there is an item in the output, items will still be pulled even if no items are in the input (I assume it still tries to decrement the "item" in the input even when there is none). 

This issue doesn't exist only for Mekanism machines, but others as well. I was able to duplicate the issue using a transporter in pull mode on the bottom of a vanilla furnace.

Ex: Say there is 1 iron ingot in the output slot of an energized smelter. If 64 gold ore is inserted into the input of the smelter, the stack gets turned into an iron ingot, and then decrements as iron is pulled out of the smelter. 

---------------------
2. Auto pushing from Mekanism machine outputs to a logistical transporter makes a "ghost" item that disappears upon reaching its destination. 

I say "ghost" because even though it disappears eventually, you can still see the item being transported by the logistical transporter. Once it reaches it's destination, it simply does not go into the inventory at the end of the transporter. It does not seem to matter what kind of inventory, as both Mekanism machines and vanilla chests seem to experience the same issue. The transporter connected to the machine was set to default configuration, not in pull or push mode.

I realized my initial test for this was only 1 block long for the transporter. I extended the length of the transporter, and noticed that while the item is rendered for the first transporter, it disappears when attempting to enter the second in line. This suggests that while the item is being rendered, the actual item itself is not being inserted into the "inventory" of the transporter.

**Comment by thommy101** [comment]
Weird, thought it was fixed until I tested it.
Can confirm both of them.

Pull from a chest to another chest still works, but pulling from a Mekanism (in my case an elite smelting factory) does duplicate all. Letting the smelting factory push does show ghost entries being moved for the first block.

**Comment by aidancbrady** [comment]
Sounds like a bug with the machine's transporter integration, not as much the transporter itself.  I'll take a look tonight for sure.

**Comment by RODragon** [comment]
I'm not sure the duplication issue would be. I was able to replicate the issue with just a standard vanilla furnace pulling from the bottom of it.

**Comment by aidancbrady** [comment]
Should be fixed in the latest build, let me know!

**Comment by RODragon** [comment]
All my testing suggests that this issue has been fixed. Thanks!
