### ISSUE TITLE
Cables is not working with MCMultipart.

### ISSUE THREAD

**Issue by halvors** [aidancbrady/Mekanism#4377]
Cables is not working with MCMultipart. By this i mean the hollow covers, cables isn't transmitting energy thru hollow covers, so something has to be wrong here.

I'm using the latest 1.10.2 build (9.2.2.301)

**Comment by thommy101** [comment]
In my experience they do work with other MCMultipart capable mods (like chisel and bits).
From which mod are those hollow covers (name + version) and which MCMP version are you using?

**Comment by mallrat208** [comment]
What hollow covers? 

MCMP doesn't add covers by itself let alone hollow ones. IIRC Simple Covers by bdew should work, but if you're using something that you got access to due to Project Red being in the pack, that won't work since it's probably FMP not MCMP.

**Comment by aidancbrady** [comment]
Marking this as fixed until I know for sure otherwise.

**Comment by Cbert** [comment]
Covers not supported Mekanism-1.10.2-9.2.2.301.jar
![2017-06-07 19 26 15](https://user-images.githubusercontent.com/9320867/26890217-767630d6-4bb9-11e7-88b9-5269b5612d26.png)

**Comment by halvors** [comment]
@aidancbrady Could you please reopen this?

**Comment by thiakil** [comment]
1.10 is not supported aside from game breaking crashes.
