### ISSUE TITLE
[1.10.2] Logistical sorter not respecting no machine sounds setting

### ISSUE THREAD

**Issue by FnordMan** [aidancbrady/Mekanism#4380]
(Again I might add...)

Running version 1.10.2-9.2.2.301

I have this line in the config:
B:EnableMachineSounds=false

The problem?
Whenever it send something along (from an ender chest to a vanilla chest) I get one of those vanilla environmental cave noises.

**Comment by thommy101** [comment]
I saw a pull request/commit coming by last week which should have fixed this. Cannot find it right now.

**Comment by aidancbrady** [comment]
Yes, this is indeed fixed
