### ISSUE TITLE
Fusion Reactor Not Producing Energy

### ISSUE THREAD

**Issue by congochicken** [aidancbrady/Mekanism#4381]
Having the weirdest issue with my fusion reactor, I either messed something up or it's a bug.

For around two weeks my reactor was working perfectly, generating a ton of energy consistently, and then one day the energy just stopped outputting. I didn't take a screenshot, but I should have while I still could. The plasma temp was a ridiculously high number, the case temp was very low, and the reaction was still ongoing, but no energy was being produced. 

It's air cooled, injection rate of 2, fuel supplies are way more than necessary, I have the capacity to run at a higher injection rate, my induction setup just can't handle that much energy at once. 

I stopped the reaction and restarted it, here's what happened:

![screen shot 2017-05-21 at 3 54 10 pm](https://cloud.githubusercontent.com/assets/20884252/26288087/a1b17e14-3e3e-11e7-8f44-717e9cf1d4f0.png)

Even when a reaction isn't sustainable, it still produces some power, right? 

I ignited with over 800MRF of energy.
![screen shot 2017-05-21 at 3 53 03 pm](https://cloud.githubusercontent.com/assets/20884252/26288088/bae0b0da-3e3e-11e7-93a7-e5bfd03ceb50.png)

The reaction is self-sustaining, but still no energy being produced.
![screen shot 2017-05-21 at 4 01 54 pm](https://cloud.githubusercontent.com/assets/20884252/26288091/d4b39f22-3e3e-11e7-8831-dac95917c42b.png)

Anyone have any idea what's going on? Tried searching for other threads about this, nothing came up. Happy to supply more screenshots if needed. Thanks in advance for any help.

**Comment by aidancbrady** [comment]
Very strange; I can't reproduce in my test environment. I'd recommend breaking and replacing the controller and/or the reactor ports, it may just be some crazy corner case.
