### ISSUE TITLE
Still problems with Tesla

### ISSUE THREAD

**Issue by RedGuy54** [aidancbrady/Mekanism#4383]
It seems like most of the problems with Tesla are fixed, but there is still some problems the universal cables have with accepting power. I'm trying to get a cable to take power from a power relay from RFTools, and it won't work, but it will work with an Enderio conduit. I'm pretty sure it's not an RF tools problem since it works fine with Endeiro, but I could be wrong.

Here's a video displaying the issue: https://www.youtube.com/watch?v=z2EpOB9sPu8&feature=youtu.be

**Comment by thiakil** [comment]
RFTools Power relay does not appear to use Tesla (at least not directly in the Relay TileEntity class). So yes, technically an RFTools problem.

If you are using an up to date 1.11 Mekanism build however it should work using Forge Energy.

PS the amount of support you can receive is **severely** limited when you do not supply version numbers. This applies to every Github Issue submission.

**Comment by thommy101** [comment]
Agree with @thiakil. RFTools doesn't support Tesla, only the RF-API (do not confuse this with RF the energy) and Forge Energy.

@RedGuy54 is using 1.10, as he's using EnderIO which is only available for 1.10 and Mekanism for 1.10 only supports the RF-API and Tesla.

Mekanism 1.11 supports RF, ForgeEnergy and Tesla.

**Comment by thiakil** [comment]
@thommy101 good point about EIO, though there is a 1.11 branch (probably for ForgeCraft), so one never knows ;)

Technical note: RFTools does support the cofhRF api on this TE; but like with EIO, it does not support extraction, which is the only way MCMultipart cables can work in 1.10 with cofh.
