### ISSUE TITLE
[1.7.10] Thermodynamic conductors kill framerate when attached to reactor

### ISSUE THREAD

**Issue by system86** [aidancbrady/Mekanism#4384]
Framerate drops from 120 (set as max) to 12 when 5 ultimate thermodynamic conductors are connected to a fusion reactor, framerate steadily gets better the more the conductors reach the temperature of the reactor.
Maybe slow down operations per second for high-temp thermal transfers?

[edit] this reactor runs at 19GK, in case that is a needed piece of information

**Comment by aidancbrady** [comment]
Fixed in 1.11

**Comment by system86** [comment]
Minecraft version 1.11 or something i dont know about?

**Comment by thiakil** [comment]
@system86 yes, Aidan is focusing on MC 1.11 now.
