### ISSUE TITLE
Solar Neutron Activators Not accepting Lithium on any side

### ISSUE THREAD

**Issue by FluxAdept** [aidancbrady/Mekanism#4386]
I am playing Infinity Lite 1.10 Version 1.8 and I cannot for the life of me get my Solar Neutron Activators to accept Lithium from any side using any piping solution.  I have tried everything from the Mekanism Pipes (all tiers) to Ender IO conduits, to Extra Utilities Pipes using Transfer and Receiver nodes. Note in the Photo with the Extra Utils Piping going into the bottom they connect but the Extra Utils Pipes do not Transmit the Lithium.
![2017-05-26_23 28 56](https://cloud.githubusercontent.com/assets/28994261/26518015/1498f796-426c-11e7-9820-0a1ef73eb064.png)
![2017-05-26_23 34 18](https://cloud.githubusercontent.com/assets/28994261/26518016/1499d986-426c-11e7-9c26-0b6b58984d40.png)
![2017-05-26_23 04 18](https://cloud.githubusercontent.com/assets/28994261/26518014/1489f00c-426c-11e7-9172-2d948d35fcad.png)

**Comment by thommy101** [comment]
Are those fluid pipes you're trying to connect? The SNA works with gaseous lithium and produces gaseous Tritium. To make it work with your ender fluid tank you'll have to convert the liquid to a gas with a rotary condensentrator.

**Comment by Adam4CZ** [comment]
Lithium must be gas form. Convert it with Rotary Condensator (use Decondensating mode) and connect with pressurized pipes.

**Comment by FluxAdept** [comment]
Thanks! This was a User error >.> I'm stupid sometimes, thanks guys!

**Comment by thommy101** [comment]
You can close your own issues ;) It will save others some time to check all and close them if needed
