### ISSUE TITLE
License mismatch Curse and Github

### ISSUE THREAD

**Issue by thommy101** [aidancbrady/Mekanism#4389]
First of all, thank you for putting Mekanism on Curse, I think it would help a lot of people with updating and saves a lot of frustration with issues because they can update easier.

On the Curse page you've mentioned it as All Right Reserved, and here on Github it's MIT as described in your README.MD.
Would be nice if those two are the same. And maybe you can upload the license at github as LICENSE.MD which Github automatically will pickup and put at the top bar (alongside commits, branches, releases and contributors).

Another slightly unrelated "issue". Master is the default branch while all commits for 1.11 go in the 1.11 branch. Maybe an idea to make the 1.11 branch the default so all new pull requests (and the overview) default to 1.11.

**Comment by aidancbrady** [comment]
License fixed!
Also, what you mentioned is not an issue; '1.11' is the working branch for 1.11 development, whenever a release is ready it's merged into master.

**Comment by thommy101** [comment]
Thanks! Didn't know about the branch intentions, good to know :)
