### ISSUE TITLE
MC 1.10.2 - Mekanism + Optifine Texture Bugs

### ISSUE THREAD

**Issue by StuardBr** [aidancbrady/Mekanism#4391]
I'm posting here and in Optinfine thread justo to people to come to here see that problem. (https://github.com/sp614x/optifine/issues/457#issuecomment-304529495)

Using only Forge (12.18.3.2281) + Meknaism (9.2.2) + MCMultipart (1.4.0)+ Optifine (1.10.2_HD_U_D8) is easy to reproduce a texture bug issue. 

Log:
https://pastebin.com/nmH3NXYD

Screnshots:
http://imgur.com/a/UR8ON

**Comment by aidancbrady** [comment]
Closing as development is now entirely focused on 1.11 and Optifine has been known to not play nicely with Mekanism rendering.

**Comment by StuardBr** [comment]
No Problem. I posted here just to other players to know. :)

**Comment by sp614x** [comment]
When OptiFine's AA or AF is enabled then some item models do not render properly.

The Mekanism rendering is very strange and it goes against the basic idea of item models: https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/client/render/item/BakedCustomItemModel.java#L404

The method getQuads() should return a list of quads, nothing else.

It should not:

- manipulate OpenGL state: https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/client/render/item/BakedCustomItemModel.java#L438
- bind textures: https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/client/render/item/BakedCustomItemModel.java#L444
- manipulate the default Tessellator: https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/client/render/item/BakedCustomItemModel.java#L447, https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/client/render/MekanismRenderer.java#L254

The BakedCustomItemModel looks like one big hack and it should not be expected to be compatible with anything else.
