### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by kenijey** [aidancbrady/Mekanism#4393]
[crash-2017-05-28_23.27.45-client.txt](https://github.com/aidancbrady/Mekanism/files/1034514/crash-2017-05-28_23.27.45-client.txt)
we did nothing, it just crashed.

**Comment by thommy101** [comment]
Just copied this out of the log (saves others some time to spit through it) :
Client crash 
Foamfix present
Mekanism-1.11.2-9.3.0.302
forge{13.20.0.2309}

Nullpointer at ClientTickHandler#223

**Comment by aidancbrady** [comment]
Fixed!

**Comment by kenijey** [comment]
thanks a lot!
