### ISSUE TITLE
Incompatibility with Nutrition mod

### ISSUE THREAD

**Issue by erindalc** [aidancbrady/Mekanism#4394]
Crash report, not sure who's at fault: https://gist.github.com/erindalc/026fd6d5a9eba7bcc3afa3512d630432

**Comment by erindalc** [comment]
Issue on Nutrition github: https://github.com/WesCook/Nutrition/issues/1

**Comment by aidancbrady** [comment]
Looks like a Nutrition issue, everything is handled on my end.
