### ISSUE TITLE
[1.11.2]Crash with extra Utilities wireless RF transmitter and universal cables

### ISSUE THREAD

**Issue by Thedrummonger** [aidancbrady/Mekanism#4395]
Placing a Wireless RF transmitter from extra utilities near a universal cable causes the game to crash. Tested with only Mekanism, Extra Utilities and JEI.

https://pastebin.com/PC1NFWHR

**Comment by aidancbrady** [comment]
Fixed!

**Comment by Thedrummonger** [comment]
Just to confirm, this is not fixed in the latest release version correct? I'm still getting the crash with 931.305.

**Comment by thommy101** [comment]
It will be fixed in the next version

**Comment by thommy101** [comment]
For easy searching of fix commits:
Fixed in 26061f35f73d9783803b8d630d17d8261f5388b9
