### ISSUE TITLE
1.11.2 server crash

### ISSUE THREAD

**Issue by Wizardon777** [aidancbrady/Mekanism#4396]
started happening after adding mekanism to pack, works fine on single player, crash on server startup.

[crash-2017-05-29_00.10.03-server.txt](https://github.com/aidancbrady/Mekanism/files/1034957/crash-2017-05-29_00.10.03-server.txt)

**Comment by aidancbrady** [comment]
Seems to be related to a mod called "TinkerIO." Not me :)
