### ISSUE TITLE
your mod does not work with jei

### ISSUE THREAD

**Issue by Bossman195** [aidancbrady/Mekanism#4402]
when I have your mod with jei it does not load so fix it so jei works with is

**Comment by thommy101** [comment]
With nothing to work with, no logs, no version numbers, all I could say it works over here.

**Comment by Bossman195** [comment]
what version of jei do you use for 1.11.2 so i can use it to fix my problem

**Comment by thommy101** [comment]
Versions I'm using:
Mekanism latest as of this moment (don't know version as I'm building it myself)
JEI 4.3.6.282
Forge 2310

**Comment by thiakil** [comment]
@thommy101 assuming you're on a publicly accessible branch you can run `git rev-parse HEAD`, then Bossman can run a `git checkout` with that revision

**Comment by thommy101** [comment]
The version I'm using is probably the latest released version as well, as my test environment is based of the 1.11 branch which is up to date with the release or a bit ahead. However, in the latest changes is nothing that could mess with JEI ;)

No need for others to compile Mekanism as the 1.11 builds are publicly released on Aidans site and on Curse(Forge).

**Comment by aidancbrady** [comment]
Mekanism is developed with JEI in the second workspace so I'm fairly sure this is not the case. Make sure you're using an up to date version of JEI!
