### ISSUE TITLE
[CRASH] Crash Mekanism with Galacticraft

### ISSUE THREAD

**Issue by Dezton** [aidancbrady/Mekanism#4403]
When I fly to the planets (asteroids) I crash the cause of mekanism / api / energy / ICableOutputter.
That's all crash https://pastebin.com/H4Yq1e19

**Comment by thommy101** [comment]
Galacticraft is using an outdated version of the API. The interface ICableOutputter has been removed/changed in the process of updating to 1.11.2. Couldn't find whether it's deleted or moved.

This is a Galacticraft issue. If someone of them needs some help implementing the newest API, they can let me/someone here know. Sure someone would help with it.

**Comment by Dezton** [comment]
Ok

**Comment by radfast** [comment]
hey @thommy101 I'm one of the Galacticraft developers, thanks for this

which Mekanism versions is that updated API found in (1.8.9  /  1.10.2  /  1.11.2  /  all recent)?

**Comment by thommy101** [comment]
I've opened an issue over at your issue tracker, will post over there ;)

**Comment by thommy101** [comment]
Could be closed, @radfast updated the API over at Galacticraft. Thanks again for the quick fix!
