### ISSUE TITLE
[glitch/graphic] Weird cable / pipe behaviour with simple cover

### ISSUE THREAD

**Issue by victoroos** [aidancbrady/Mekanism#4404]
HI all

I installed simple cover, hoping it would make pipes really come out of the wall. It kinda does, however:
<a href="http://s1099.photobucket.com/user/Victor_Roos/media/2017-05-30_15.24.14.png.html" target="_blank"><img src="http://i1099.photobucket.com/albums/g393/Victor_Roos/2017-05-30_15.24.14.png" border="0" alt="Glicht mekanism simple covers photo 2017-05-30_15.24.14.png"/></a>

it looks a bit weird ;)
Any ideas?

**Comment by thommy101** [comment]
Do you have a log when this happens an a couple versions (atleast the Forge, Mekanism and SimpleCovers version)?

**Comment by victoroos** [comment]
Ehm, no log is produced if you mean that. But here is latest: https://pastebin.com/7Y76bKqf

And versions are Forge: forge-1.10.2-12.18.3.2281-universal
Mekanism: 9.2.2.301
Covers: 0.4.1.17

**Comment by thommy101** [comment]
Thank you, I indeed meant that one. Sometimes there's stuff in there that could point towards some errors/warnings.

**Comment by victoroos** [comment]
Well, keep me posted. it isn't bad but yeah, autism and looks etc ;)

**Comment by thiakil** [comment]
Have you got Optifine installed by any chance? I don't recall the cables rendering in the hand like that (but I could easily be wrong).

In the meantime you could use Chisels & Bits as I've found it works fine to create covers manually.

**Comment by victoroos** [comment]
I do indeed. why? It actually isn't about hand, but about the cable on the floor. Really, ahnd shoulcn't be like that? :o.
Chisel and bits it is :)

**Comment by thiakil** [comment]
The item in hand was just a clue. Optifine _does_ mess with rendering.

Does the issue in your initial post occur without Optifine?

**Comment by victoroos** [comment]
I never played mechanism without optifine. I shall come back to you on that good sir

**Comment by victoroos** [comment]
Actually, without optifine it does the same.

**Comment by aidancbrady** [comment]
Occlusion support has not fully been implemented yet for Mekanism transmitters, so strange functionality like this can be expected.  Should be fixed for next minor release, but I'll leave the original posted issue open (#4377)
