### ISSUE TITLE
Cannot make Lithium

### ISSUE THREAD

**Issue by jubalearly** [aidancbrady/Mekanism#4406]
Using latest 1.11.2 version.  This is my own custom pack.

Have pumped Brine into Thermal Evaporator,  Let heat get to max but Lithium is not produced.  

![2017-05-30_15 57 40](https://cloud.githubusercontent.com/assets/7937235/26606943/3d310e7c-4551-11e7-807d-82af94611e11.png)

If I click on recipes inside Thermal Evaporator, I get this:

![2017-05-30_15 58 04](https://cloud.githubusercontent.com/assets/7937235/26606969/564f4676-4551-11e7-9031-f35370944798.png)

Not sure if it is my pack or actual bug with Mekanism.

**Comment by aidancbrady** [comment]
Fixed!
