### ISSUE TITLE
[1.11.2] Storagedrawers and Mekanism crash

### ISSUE THREAD

**Issue by marcin212** [aidancbrady/Mekanism#4407]
Placing a Drawer next to a Mekanism Mechanical Pipe crashes the server.
crash log: https://hastebin.com/gijinejifa.cs

Mekanism-1.11.2-9.3.1.305
forge-1.11.2-13.20.0.2310
StorageDrawers-1.11.2-4.2.7

**Comment by aidancbrady** [comment]
Report to StorageDrawers.
