### ISSUE TITLE
Thermal Evaporator Infinite Water Bug.

### ISSUE THREAD

**Issue by xannor** [aidancbrady/Mekanism#4408]
I was building the thermal evaporator and I was testing to see which of the three biomes around me gave the best output, the three biomes are Beach, Outback and Savanna. When I built the evaporator on the beach I noticed no inidcation of the biome multiplier, so I moved it to the Outback. I still had no multiple (even tried changing my GUI scale.) I decided to put in a buck of water to see if it would update and that is when I noticed the water tank filling but the bucket never moved to the output. As long as I kept the bucket of water in there it filled the tank. even while producing brine.

Update: It did move the full bucket to the output after the tank was full.

**Comment by aidancbrady** [comment]
Confirmed.  Looking into a fix now

**Comment by aidancbrady** [comment]
Should be fixed in development.
