### ISSUE TITLE
[1.10.2]cable PULL mode only transfer one-tenth of  it's capacity per tick

### ISSUE THREAD

**Issue by canaria2014** [aidancbrady/Mekanism#4409]
Mekanism 9.2.2.301

for example, a single basic universal cable can transfer 3200J/t (two should be 6.4kJ/t, due to total capacity ) from a cube to another one , but setting the cable to PULL mode, it can only transfer 320J/t, one tenth of Normal mode.Other cables are the same.

And in 1.11.2( Mek 9.3.1.306) ,PULL mode can transfer 3200J/t as it should, I think it fixed.
Hope to fix it in 1.10.2. Thanks

**Comment by aidancbrady** [comment]
Sorry, 1.11 is the only supported Minecraft version at the moment.
