### ISSUE TITLE
Crash from nothing, than not loading any more. (Null pointer exception at mekanism.common.block.BlockTransmitte)

### ISSUE THREAD

**Issue by Swornh** [aidancbrady/Mekanism#4411]
I got this error when I was running toward an WindMill with some cables and two infuser (coal and redstone) then the game crash...  I tried to load again but it crash during the loading screen.

Guess is with mechanism, by the "mekanism.client.render.ctm.CTMModelFactory.func_188616_a" but it has journey map with the log to, so Not sure. I tried with Journey Map off so..

I was trying to read the log, and it is possible something with having Mekanism machines right next to an Tinker Construct Furnace. The problem not happens when I place the machines, but after closing and open then game again, those machines were not running, I have just placed them, I had the basic one [purification chamber, Crusher, Enrichiment Chamber], all idle, nothing in it. The furnace was a max size one 11x11 in large, but 4 or 5 in height.

LastLog_Journey.txt > JourneyMap on
LastLog.txt >JourneyMap off

The second one has las trace errors

I can upload any other stuff if it is needed.
If it has nothing to do with Mekanism, please sorry, if possible, redirect me to the right mod.
Any way. Thanks in advanced for the time. Awesome mod.

Minecraft 1.11.2
Mekanism-1.11.2-9.3.1.305.jar
MekanismGenerators-1.11.2-9.3.1.305.jar
MekanismTools-1.11.2-9.3.1.305.jar
TConstruct-1.11.2-2.7.0.26.jar
forge-1.11.2-13.20.0.2228-universal.jar
[LastLog.txt](https://github.com/aidancbrady/Mekanism/files/1043266/LastLog.txt)
[LastLog_journeymap.txt](https://github.com/aidancbrady/Mekanism/files/1043267/LastLog_journeymap.txt)

**Comment by aidancbrady** [comment]
Should be fixed, thanks!

**Comment by Swornh** [comment]
Wow, that was fast, but unfortunately that not fix :(.
Can I help with something else besides the log file?

I have this versions now from your web site

Mekanism-1.11.2-9.3.1.306.jar
MekanismGenerators-1.11.2-9.3.1.306.jar
MekanismTools-1.11.2-9.3.1.306.jar
[lastlog.txt](https://github.com/aidancbrady/Mekanism/files/1043466/lastlog.txt)

**Comment by IchigoGames** [comment]
so is this fixed or not ?

**Comment by thommy101** [comment]
Fixed in commit 26061f3

**Comment by ktole1999** [comment]
anyone know if this bug is in 1.10?

**Comment by thommy101** [comment]
This bug is also affecting 1.10, which I think won't get updated anymore.

https://github.com/aidancbrady/Mekanism/blob/1.10/src/main/java/mekanism/common/multipart/PartUniversalCable.java#L298

**Comment by ktole1999** [comment]
i hate to hijack a post but by no longer supporting 1.10 how does that adversely affect all the packs still on 1.10 due to mod compatibility? I can understand trying to keep up with latest MC/forge but you are killing your player base in the process. Mek is an awesome and very popular mod for packs.

**Comment by thiakil** [comment]
I don't think this would affect 1.10, as transmitters are Multipart blocks, which don't support the cofh interfaces as far as I know (this being the reason EIO doesn't play nice with the cables).

**Comment by Swornh** [comment]
The lasted version on the site **307** still with the same problem.

**Comment by thiakil** [comment]
Please post the log from this version so it can be determined what is causing it.

**Comment by Swornh** [comment]
ok, here is the log.
[crash-2017-06-10_23.05.12-client.txt](https://github.com/aidancbrady/Mekanism/files/1066216/crash-2017-06-10_23.05.12-client.txt)
[latest.txt](https://github.com/aidancbrady/Mekanism/files/1066217/latest.txt)

**Comment by thommy101** [comment]
Looks like #4453 is still needed as some mods directly call the method.

**Comment by thiakil** [comment]
Well my solution is just more of an extra band-aid...

My guesses to causes:
* `result.valid()` is failing
* something else is calling `setDefaultForTile` (unlikely)
* the `World` parameter is actually the null culprit (which my pull would not fix)

**Comment by Swornh** [comment]
yeh, the last update **308** not fix it as you already mention before.
[crash-2017-06-11_22.20.04-client.txt](https://github.com/aidancbrady/Mekanism/files/1066960/crash-2017-06-11_22.20.04-client.txt)

**Comment by Swornh** [comment]
Just to make a note, still happens on 309.

**Comment by Swornh** [comment]
Question. Would I open a new one for the Mekanism-1.12.1-9.4.1.326.
I was making some test and almost got on a good scenario, but before posting I would ask where do I post it? Here or in a new one?

**Comment by thiakil** [comment]
I believe this will be fixed in the next release, which should be soon

**Comment by Swornh** [comment]
OK, thanks for the quick answer.

I'll save a copy of the %appdata%\.minecraft folder for later if you guys need it.

The scenario that I have here was just after downloading two more mods [Refined Storage and Extra utilities]. As I tested it out, looks like it happens when I put the Refined Storage, the game loads for a few seconds and crash, don't know why... If I remove only this one [refined storage] it works as normal.

**Comment by thiakil** [comment]
Well that doesn't really sound like this bug, so if it's not the same crash, you can post a new issue

**Comment by Swornh** [comment]
Hmm don't know if it's another issue, looks the same.
The stack trace looks the same, just change the line numbers.
Any way, let's leave this one closed.
I'll wait the next version, if still happens then I post a new one. Thanks for the support.
