### ISSUE TITLE
Crash with Darkhax's Bookshelf

### ISSUE THREAD

**Issue by InsomniaKitten** [aidancbrady/Mekanism#4414]
Game crashes to desktop during recipe loading due to a ClassCastException on an unused variable being cast to an ArrayList in your `addLogRecipes()` method.

**Mekanism version:** [9.3.1.305](https://minecraft.curseforge.com/projects/mekanism/files/2426233)
**Bookshelf version:** [2.0.0.382](https://minecraft.curseforge.com/projects/bookshelf/files/2427942)
**Forge version:** [1.11.2-13.20.0.2304](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11.2-13.20.0.2304/forge-1.11.2-13.20.0.2304-changelog.txt)

**Crash report:** [paste.ee/xyVsH](https://paste.ee/p/xyVsH)
**Relevant code:** [OreDictManager.java#L349](https://github.com/aidancbrady/Mekanism/blob/1.11/src/main/java/mekanism/common/integration/OreDictManager.java#L349)

**Comment by thommy101** [comment]
I must say this: Thank you for such a readable and great issue report!

**Comment by aidancbrady** [comment]
Thanks!

**Comment by darkhax** [comment]
Is there a release with this fix out? I am getting this issue reported to me almost five times a day and would like to point them somewhere lol.

**Comment by thommy101** [comment]
... Looks like it's only released on his own site and not on CurseForge.

http://aidancbrady.com/mekanism/download/

**Comment by thommy101** [comment]
Adding a zip with a build from the current 1.11 branch for those who can't wait for an official release.

For those who want to use it, please do not change the filename, it will pop up in the logs and makes lives of the maintainers easier if they know which version you're running.
Also a big note: THIS IS NOT AN OFFICIAL RELEASE.

[MekanismAll-1.11.2-9.3.3.issue4414-20170706.zip](https://github.com/aidancbrady/Mekanism/files/1127197/MekanismAll-1.11.2-9.3.3.issue4414-20170706.zip)
SHA256 `db59dfabc90753b9af4335b8f8e72a2022eae92bbd77fa5ffad91fb25112e907` *./MekanismAll-1.11.2-9.3.3.issue4414-20170706.jar
