### ISSUE TITLE
BlockTransmitter NullPointerException #4411

### ISSUE THREAD

**Issue by Swornh** [aidancbrady/Mekanism#4416]
Hi, I was trying to reply on the last post, but looks like it not notify new messages after close, so I'm opening a new one

Last one:
#4411 

Unfortunately looks like the problem persist. The game still crash on load with the same error.

Can I help with something else besides the log file?

I have this versions now from your web site

Mekanism-1.11.2-9.3.1.306.jar
MekanismGenerators-1.11.2-9.3.1.306.jar
MekanismTools-1.11.2-9.3.1.306.jar

[https://github.com/aidancbrady/Mekanism/files/1043466/lastlog.txt]

**Comment by aidancbrady** [comment]
The mod is fixed in development, meaning the changes haven't been pushed yet.  I'll be releasing v9.3.2 very soon :)

**Comment by Swornh** [comment]
Ohh, sorry for that, I saw a change from the 0.5 to 0.6, my bad, probably i was using and old version... 
Well,thanks for the explanation.
