### ISSUE TITLE
Bug: Upgrades Disappearing.

### ISSUE THREAD

**Issue by kbcoder** [aidancbrady/Mekanism#4417]
Build: 1.11.2-9.3.1.306

If you open up the Electrolytic Separator and then click on an upgrade in your inventory (upgrade sticking to your pointer)  and THEN hit the 'upgrades' arrow when the upgrade component is still attached to your pointer, your upgrades will disappear.

I was using 2 energy upgrades and didn't try any other upgrades or machines.

- Just thought I would post if it might help.

**Comment by kbcoder** [comment]
Also, if you have 2 energy upgrades selected and try to put them into the upgrade slot, you lose one upgrade. It only places 1 energy upgrade into it and even trying to retrieve them back to your inventory give you only 1 back.

**Comment by thiakil** [comment]
RE: clicking buttons with stack on cursor;

Are you sure MC didn't just act as if you threw the stacks into the world? As far as I can remember that's what happens with just about any GUI...

**Comment by marcin212** [comment]
Fixed by https://github.com/aidancbrady/Mekanism/pull/4412
