### ISSUE TITLE
Fusion Reactor 1.10.2 tweak options ?

### ISSUE THREAD

**Issue by sintaxcz** [aidancbrady/Mekanism#4423]
Hello i have problem on my server (modpack) mekanism fusion reactor is cheaper than other mods fusion reactors and make 10 times more energy /t and lots of players are unhappy with that setup.
Please i need help to tweak it down i cant find it in options :(

**Comment by aidancbrady** [comment]
Values can be changed in the config.

**Comment by sintaxcz** [comment]
thank you but what values ? what i need to change ? there is not values of Fusion reactor
