### ISSUE TITLE
[Question] Code cleanup

### ISSUE THREAD

**Issue by thommy101** [aidancbrady/Mekanism#4424]
Hi @aidancbrady,

Would a pull request with code cleanup have any change of being accepted?
Asking because I would like to clean up some compiler warnings / bad practices, but not spend a lot of time if it won't be accepted.

Things like:
- Java5/6 compatible stuff what could be rewritten to Java 8 stuff, think of foreach instead of a for loop over every element.
- Inlining variables (int i = someMethod(); return i; -> return someMethod();
- Remove unnecessary returns

**Comment by aidancbrady** [comment]
Assuming you follow standard practices and don't make things less efficient, I see no way it wouldn't be accepted.

**Comment by thommy101** [comment]
Nice, will open a pull request "soon"!
