### ISSUE TITLE
Thermal Evaporation Plant causes massive lag while entering world

### ISSUE THREAD

**Issue by PlayerWithoutName** [aidancbrady/Mekanism#4425]
It is caused by instancing many display lists during recalculation of water model inside the plant.

Reproduction: Add one level to fully built and filled plant

**Comment by PlayerWithoutName** [comment]
Basically Thermal Evaporation Plant with 10 blocks height creates 51200 display lists

**Comment by ktole1999** [comment]
i get a 15sec or so lag when entering area with evap tower as well as when i open the gui. once gui opens the first time i have no other lag. but i am on v300.
