### ISSUE TITLE
[1.10.2] Industrial Turbine never displays Production or Flow Rate

### ISSUE THREAD

**Issue by JonoColwell** [aidancbrady/Mekanism#4427]
For industrial turbine, no matter how much steam is being input, the production and flow rate always stay at 0. This issue has been around for a while and is consistent across multiple installs and with multiple

http://puu.sh/w9q31/b95a277e52.png

Seems consistent across all turbine sizes

http://puu.sh/w9qk1/c5a5b2c5e4.png

Mekanism 9.2.2.301

**Comment by thommy101** [comment]
Are the turbines by any chance on the border of chunks? I know they have some "slight" issues when crossing borders of chunks.

**Comment by JonoColwell** [comment]
Issue happens regardless of chunk borders.

**Comment by thommy101** [comment]
Wierd.. It works over here (althrough i'm using an 1.11.2 build)
![Turbine image](https://cloud.githubusercontent.com/assets/1036527/26752872/d979988e-4859-11e7-8567-59db0e9c1390.png)

**Comment by aidancbrady** [comment]
Definitely a corner case, but also already reported.

**Comment by JonoColwell** [comment]
I was unable to find a previously reported issue, could you perhaps link me to that one?

**Comment by aidancbrady** [comment]
#3301

**Comment by JonoColwell** [comment]
I think this is a different issue for the following reasons

1. Issue is occurring in 1.10.2 rather than 1.7.10
2. Breaking and replacing the multiblock does not fix the issue, it remains consistent and is 100% reproducible.
3. This is consistent across multiple clients, multiple server reinstalls, and multiple client reinstalls.

**Comment by medinasgaider** [comment]
Hi, I have the same problem, but for me just is not displayed the production rate, the flow rate ok! I remember that in my first turbine setup the production rate was shown, but after that no more. It's happening in all the worlds created in my modpack. If there is anything I can do to get more information with tests about the problem to help in the solution you can ask.

Mekanism version 9.2.2.301
