### ISSUE TITLE
Fusion Reactor 1.10.2 tweak options ?

### ISSUE THREAD

**Issue by sintaxcz** [aidancbrady/Mekanism#4428]
Hello i have problem on my server (modpack) mekanism fusion reactor is cheaper than other mods fusion reactors and make 10 times more energy /t and lots of players are unhappy with that setup.
Please i need help to tweak it down i cant find it in options :(

@aidancbrady commented 16 hours ago
Values can be changed in the config.

thank you but what values ? what i need to change ? there is not values of Fusion reactor only turbines and steam but i need to change clasic fusion generation and there is no explanation what vallues are for that :(

I seek fo help not for "Values can be changed in the config."  becouse that can be translated to "Fck you blind retard find it for your self" and that is realy nice help :(

English is not my first language and thats mean i dont know all words and i cant find fusion reactor options in config ! I search for help on forums and i find some topics of how much is fusion over povered but no one knows where to change values !

I own small czech minecraft server and realy want tune this op reactor down becouse lots of players on my server consider it op and i dont want to ban it becouse i like mekanism.

Sry for my english i hope that mess can be understandable and i have big hangover from yesterday and please tell me what values i need to change and not the "Values can be changed in the config" on me again thanks

**Comment by aidancbrady** [comment]
My bad, apparently there actually were no available configurable values for the fusion reactor.  I've added configurable generation for the next version.
