### ISSUE TITLE
Thermal Evaporation Tank not producing Lithium.. 9.3.1.306

### ISSUE THREAD

**Issue by kbcoder** [aidancbrady/Mekanism#4433]
Unless some requirements have changed, the Thermal Evaporation Tank is not producing Lithium.  Brine fills up on the left, but never lithium on the right. I can take the same setup, remove the brine from it and pump water into it instead and it immediately starts to produces brine.

**Comment by thommy101** [comment]
Please use the search functionality when reporting issues.
There's an issue open for the exact same issue.

#4425 and #4426 with an open pull request to fix the issue.
