### ISSUE TITLE
Crash with Mekanism and Tinkers 

### ISSUE THREAD

**Issue by IchigoGames** [aidancbrady/Mekanism#4434]
one of my modpack players crashed from what is i see in the crash report it looks like a issue with Mekanism and TConstruct

Minecraft 1.11.2
Forge 2312
Mekanism-1.11.2-9.3.1.305
TConstruct-1.11.2-2.7.0.26
crash report https://pastebin.com/PpKrUnV6
Not sure if this is a issue with your mod or with tinkers.

**Comment by thommy101** [comment]
Do you have any clue what the user was doing at that moment? Which tool/item did he/she have in his/her hands and at which block did he/she look? (Block the player looked at is probably a pipe/tube from Mekanism)

**Comment by IchigoGames** [comment]
ill ask

**Comment by IchigoGames** [comment]
sounds like it might be more of a tinkers issue he was using a osmium tinkers Hammer to brake something.

**Comment by thommy101** [comment]
I sadly cannot reproduce it.. Tried smacking all kind of cables with a Tinkers Construct hammer, nothing weird happening.

If you can reproduce it and explain the steps to reproduce that would be great.

**Comment by IchigoGames** [comment]
ok well if it happens to any other users ill hopefully get better info from them.

**Comment by Zarkov2** [comment]
I'm experiencing what seems to be the same crash when looking at Mekanism machinery and cables while (or after) using a cobalt TiCo hammer. I was able to reproduce the crash a few times even after reloading the world, but then it stopped crashing.

Minecraft 1.11.2
Forge 13.20.1.2393
Mekanism 9.3.2.307
Tinkers Construct 2.7.0.26
(All The Mods 2 v0.72c)

Crash log: https://pastebin.com/pCvSXXtb
