### ISSUE TITLE
1.7.10 Rotary Condenser making wrong HCl

### ISSUE THREAD

**Issue by Klimosity** [aidancbrady/Mekanism#4435]
Instead of converting the gas into the blue hydrogen chloride liquid its converting it to the green hydrogen chloride from IHL tools and machines!

**Comment by aidancbrady** [comment]
Both should be cross compatible

**Comment by Klimosity** [comment]
Well, it's not doing that on your latest 1.7.10 build. The Rotary Condenser can create the green hydrogen chloride and output it into barrels but the Rotary Condenser can't convert the green hydrogen chloride back into the gas. So it's one way only. Thanks for your response anyway!
