### ISSUE TITLE
[1.11.2] Logistical Transporters try to insert items into bins from bottom (and fail)

### ISSUE THREAD

**Issue by pflonk** [aidancbrady/Mekanism#4437]
Hey there,
I have been building a room with bins as a storage room, connected with logistical transporters to an input-chest. See picture below for setup :D
The lower bins have their inputs connected from the top (as it should be), the upper bins have been disconnected from the logistical transporters that lead to the lower bins with the configurator (set to "NONE") as they are not supposed to output any items via pipe. For the upper bins there is another pipe, leading alongside the top sides of those bins (as intended).
The bug now is, that the pipe tries to fill the bins from the bottom and fail. The bins won't accept items from that side but the pipe is stubborn and tries endless. New items that are sent into the system, will also go the wrong way. For the bins in the bottom row everything works fine. Is it a bug in the pipe-system or in the bins?
Disassembling the corresponding piece of pipe results in itemloss. I've lost 1000 redstones that way because i thought it'd drop into my face when disassembling the buggy piece of pipe.
I could of course add a block in between the upper bins and the pipe for the lower bins to achieve the upper ones not beeing connected to the lower bins' pipes, but the setup I've built worked in older versions, so it should still do?
The chest you can see at the end of the setup normally is not there. Build it for debugging attempts. It does not affect the outcome, still happens without the chest attached.

Kind regards
pflonk

Mekanism-1.11.2-9.3.1.306
forge1.11.2-13.20.0.2312

![2017-06-05_15 05 51](https://cloud.githubusercontent.com/assets/29201706/26784978/89d5fce8-4a00-11e7-97fd-0b0782cb90b3.png)

**Comment by thommy101** [comment]
I can confirm your issue.

Mekanism: 1.11.2-9.3.1.305
Forge: 13.20.0.2313

My basic setup:
![Setup](https://cloud.githubusercontent.com/assets/1036527/26796359/8721c30a-4a29-11e7-871b-249bc0ff16c1.png)

After inserting a stack of stone and dirt in the chest:
![Result](https://cloud.githubusercontent.com/assets/1036527/26796429/cc9d3ea0-4a29-11e7-8974-7baeeaa9cb24.png)

Result is dirt bouncing between the pipe and the bin as it follows the wrong way to the bin. Looks like a pathfinding issue and the return way isn't available, leaving the dirt bouncing and getting lost on breaking the pipe.

**Comment by christofferson** [comment]
@thommy101 Are you actively working on this? If not I may have a fix ready

**Comment by thommy101** [comment]
Fixes are always welcome! If I'm actively working on something I try to assign myself to the issue ;) (although I might forget that sometimes)
