### ISSUE TITLE
[1.11.2] Jetpack fuel is not getting consumed

### ISSUE THREAD

**Issue by pflonk** [aidancbrady/Mekanism#4438]
Hey there,
I am using a jetpack in 1.11.2 and just found out the hydrogen is not getting consumed correctly. When using it pulsed (regular mode), sometimes the counter jumps back up. (from say 23600 to 23700)
I have been flying with my first load for a long time now.
When I am floating in hovermode it does not happen.
You can see what I mean in this short video:
[youtube](https://youtu.be/R-HY2ht_ph0)

kind regards
pflonk

forge1.11.2-13.20.0.2312
Mekanism-1.11.2-9.3.1.306

**Comment by thommy101** [comment]
Can confirm with only Mekanism installed
Mekanism(generators, tools) 1.11.2-9.3.1.305
Forge 13.20.0.2313

Looks like a client desync

**Comment by PlayerWithoutName** [comment]
Easy reproduce: charge jetpack to 24000, fly straight up till it reaches ie. 23000 and release space bar, it will return to 24000

**Comment by aidancbrady** [comment]
Already reported (#3805)
