### ISSUE TITLE
Thermoelectric Boiler wont from with boiler valves inserted

### ISSUE THREAD

**Issue by Dicara1** [aidancbrady/Mekanism#4440]
Hi,

I'm having an issue getting the thermoelectric boiler to form when i insert the boiler valves. if i create the boiler with just the structural glass or boiler casing on the outside without any valves. it forms and i can access the gui, but when i remove one of the glass/casing and replace it with one of the valves, it wont reform and i am unable to access the gui. but if i them remove the valve i added and replace it with the glass/casing it will form again and i can access the gui.

I'm currently running version 	9.3.1.132 if that helps

**Comment by thommy101** [comment]
Assuming you meant version 9.3.1.305 or something near that, It works over here.
Things to check:
Make sure you're using a boiler valve, not a turbine valve.
Valve cannot be on the border. The frame (corners and connection between the corners need to be casing)

If all those are checked and it still won't work, please post a screenshot and confirm your version number

**Comment by Dicara1** [comment]
i'm currently using the latest version i can see on the Mekanism-Dev build server. I'l give the release version 
9.3.1.306 and see if that fixes the issue.

**Comment by Dicara1** [comment]
No Luck :( 
using 9.3.1.306, I'm still getting the same issue. i must be doing something wrong but i can not work out what, I've tried building several versions on the boiler  from the 3x3x4 on the wiki to a 5x5x8. all of them form without the boiler valves but as some as i remove a block to replace one it wont reform.


The first 3x screenshots are of it formed with out any valves. the last 2x are with he valves installed but not formed/unable to access the gui.

hopefully you can see what im doing wrong as i can not work it out at the moment.

Thanks
![2017-06-05_16 43 14](https://cloud.githubusercontent.com/assets/27697222/26791423/f5a67dcc-4a0e-11e7-81c9-4311c727a3f9.png)
![2017-06-05_16 43 29](https://cloud.githubusercontent.com/assets/27697222/26791424/f5a86858-4a0e-11e7-89d4-9a837e50a0fb.png)
![2017-06-05_16 44 16](https://cloud.githubusercontent.com/assets/27697222/26791425/f5acf224-4a0e-11e7-8978-0d84cdaec438.png)



![2017-06-05_16 56 09](https://cloud.githubusercontent.com/assets/27697222/26791758/ffb67f64-4a0f-11e7-9f7d-efe3b8b998cb.png)
![2017-06-05_16 56 40](https://cloud.githubusercontent.com/assets/27697222/26791759/ffb7d36e-4a0f-11e7-8568-fadd8923683e.png)

**Comment by thommy101** [comment]
I've tried to replicate your boiler, it works just fine over here. Looks like something is intervening with the boiler. Do you have any logs available? maybe there are some warning/errors regarding this.

![Boiler](https://cloud.githubusercontent.com/assets/1036527/26795671/ccb8ec2a-4a26-11e7-9fb0-7ae7166543bd.png)

**Comment by Dicara1** [comment]
I've sort of worked it out/sorted it... it was being caused by another mod installed called Dark Roll Play. 
i noticed that it was mentioned right after the boiler tile entry in the logs.
as soon as i removed this mod, and logged in. the boiler formed as soon as i inserted the valve and i'm now able to access the gui :D

I've attached the Server Logs and the Forge Logs

`java.lang.NullPointerException
	at mekanism.common.tile.TileEntityBoilerValve.hasCapability(TileEntityBoilerValve.java:189) ~[TileEntityBoilerValve.class:?]
	at net.drpmedieval.common.events.AttachCapabilityTileEntity.AttachCapability(AttachCapabilityTileEntity.java:16) ~[AttachCapabilityTileEntity.class:?]
	at net.minecraftforge.fml.common.even
`
[Logs.zip](https://github.com/aidancbrady/Mekanism/files/1053176/Logs.zip)

**Comment by thiakil** [comment]
Yup, looks like this has come up before (#4112)

**Comment by thommy101** [comment]
Thanks @thiakil! It's kinda difficult to search on mobile :)

**Comment by thiakil** [comment]
Agreed @thommy101, have to switch to desktop mode to do it D:

**Comment by thommy101** [comment]
@Dicara1 Dark Roleplay Medieval's version you're using is 0.1.8. Version 0.1.9 should contain a fix. Try updating the mod ;)

**Comment by Dicara1** [comment]
w00t :)
I've updated Dark role play to v1.9 and drpcore to v2.0b and its working now :)
Thanks all for your help. :)

on a side note, which version on Mekanism is the "latest" is it the 9.3.1.306 which is on the main website, or is it 9.3.1.132 which is on the indiewikis/mekanism-dev site? or are they both the same?
