### ISSUE TITLE
[Request] Thermal Foundation Ore support

### ISSUE THREAD

**Issue by blupilot** [aidancbrady/Mekanism#4441]
It'd be pretty cool if there was support for the Thermal Foundation ores, or even the oredict registries for them, to work with the ore processing machines. Aluminum and Nickel work on the Enrichment Chamber, and Platinum, Iridium, and Mana Infused/Mithril don't work on any machines (except smelting of course)

**Comment by mgdgfbhevdyeh** [comment]
+1
What kind of ore does Mek ore processing support now?

**Comment by Dilnu** [comment]
Mekanism has ore processing up to 5x, aluminum and Nickel are only set up to yield up to 2x at the moment.

**Comment by Lukas45** [comment]
Mekanism only supports 7 ores for anything higher than 2.
Iron, Gold, Copper, Tin, Osmium, Silver and Lead.
It can Double every ore, as long as they have a set crusher recipe (Enrichment Chamber in this case) set up and has a dust version.

**Comment by Dilnu** [comment]
This used to be handled by AOBD but that hasn't updated to 1.10.

**Comment by mgdgfbhevdyeh** [comment]
but AOBD is dead now

**Comment by blupilot** [comment]
I've been trying to rewrite AOBD for 1.10+ but I don't really have the skills atm

**Comment by mgdgfbhevdyeh** [comment]
If eveyone can rewrite AOBD this will be a epic job.

**Comment by blupilot** [comment]
DeflatedPickle seems to be working on an AOBD clone, not sure if they are gonna add the mek machine support

**Comment by aidancbrady** [comment]
Added Platinum and Iridium- I'll leave the rest up to a continuation of AOBD.
