### ISSUE TITLE
critical failure mekanism

### ISSUE THREAD

**Issue by IchigoGames** [aidancbrady/Mekanism#4442]
A critical failure will occur if a mekanism power cable is placed within receiving range of a powered extrautilities 2 wireless transmitter.
The failure will hard crash a client if in single player mode, or will hard stop a server (without a way to recover short of editing the chunk to remove the cable or restoring a backup).
 

 
attached is a crash log: https://pastebin.com/ukitLxS4

Mekanism-1.11.2-9.3.1.305
Minecraft 1.11.2
side note it needs to have power going into it for it to crash.

**Comment by thommy101** [comment]
I probably know what's happening. The wireless transmitter tries to send energy to all blocks in range who accepts energy. Mekanism fails to check on some points for a null facing (which is a valid value for a facing). A null facing is used in wireless situations like this. 

Before this can be solved, the following question needs to be answered: for which blocks is it logical to receive wireless power. 
My opinion, all blocks (machines) could receive power wireless. The cables shouldn't receive it wireless. If someone want to use cables, they probably won't use wireless to the same machine. And if wireless and cables are desired, use an energy cube as a transfer between wireless and cables. 

There is however another side to it, some machines may want to draw power wireless, I think this shouldn't be possible for machines.

**Comment by IchigoGames** [comment]
needs to be power going into it to crash

**Comment by IchigoGames** [comment]
hopefully theres a way to fix it on your side RWTema takes forever to fix anything.

**Comment by IchigoGames** [comment]
but its also been reported to him i was not sure what mod was the main one crashing

**Comment by thommy101** [comment]
It's not something on the side of ex utils. It can only be fixed on the side of Mekanism.

**Comment by thommy101** [comment]
.... Totally missed some issues last week..

It's already fixed for the next release #4411

**Comment by IchigoGames** [comment]
cool

**Comment by thommy101** [comment]
@IchigoGames It's fixed in commit 26061f35f73d9783803b8d630d17d8261f5388b9

Somehow I totally messed up the issue reference, should be #4395

*note to self, do not link to other issues from mobile*

**Comment by IchigoGames** [comment]
i hate to use this to ask but i don't know any other way do you know when Mekanism will update on curse to fix this crash atm its the only mod i'm waiting on before i update my pack.

**Comment by thommy101** [comment]
Updating/releasing is all up to @aidancbrady. I do not know when he releases an update. It would save some duplicate issues that will be made for sure in the couple next days

**Comment by ktole1999** [comment]
if its 1.10 there wont be. hes stated hes only supporting 1.11
