### ISSUE TITLE
2 suggestions on digital miner further improvement.

### ISSUE THREAD

**Issue by Cbert** [aidancbrady/Mekanism#4443]
1 Enabled or Disabled Item Filters function.
2 Top down only function, miner won’t mine lower filters if higher filter not completely done.

![2017-06-06 16 42 23](https://cloud.githubusercontent.com/assets/9320867/26833133/43bf9e5a-4ada-11e7-8028-7a72a29199e8.png)

**Comment by aidancbrady** [comment]
Merging with #1474
