### ISSUE TITLE
[1.11.2] Bookshelf/Mekanism Crash?

### ISSUE THREAD

**Issue by MokahTGS** [aidancbrady/Mekanism#4445]
Bookshelf Version: 1.11.2-2.0.0.385
Mekanism-1.11.2.3.1.305
MekanismGenerators-1.11.2-9.3.1.305
MekanismTools-1.11.2-9.3.1.305

Forge 13.20.0.2314

Log: https://pastebin.com/0bvQyu4K

**Comment by thommy101** [comment]
Posted multiple times, fixed for the next release.
#4414 and fixed in #4415
