### ISSUE TITLE
Chest into sawmill -> NPE: Updating screen events

### ISSUE THREAD

**Issue by OrdinatorStouff** [aidancbrady/Mekanism#4447]
SMP, ATM2 official server. 1.11.2 Mek 9.3.1.305

Client-side crash https://pastebin.com/2dpQF4te

The player put an oak chest into a sawmill and crashed client (server did not crash). When the player logged back in the chest was still in his inventory and had no been "placed" into the sawmill before crash.

**Comment by thommy101** [comment]
Looks like there are still some missed null itemstacks in the recipe code.

**Comment by uwebeschde** [comment]
I can confirm that one with multiple wodden items (e.g. wodden door) which cause the error.
In my case the whole server was affected and isn't able to restart at the moment because the error is getting triggered on every restart while loading the map.

Crash log: https://pastebin.com/5YQ7inEk

**Comment by aidancbrady** [comment]
Fixed!
