### ISSUE TITLE
[1.11.2] Tesselating block in world - crash

### ISSUE THREAD

**Issue by Gladi** [aidancbrady/Mekanism#4448]
I suddenly got a client crash when looking at my base - it seems to be the Mekanism area.
I managed to get back to base walking backwards and looking at different areas of the base.
The Tinkers area loads just fine.

The Mekanism area has 4 Heat Generator connected to a Basic Energy Cube, from there two Metallurgic Infuser, one Energized Smelter and a Enrichment Chamber are connected.
these 3 machines are not connected with each other.
In one Metallurgic Infuser is Diamond.
The Heat Generator have each a Ultimate Tank inside with lava.

Mekanism version: 9.3.1.305
Forge version: 1.11.2-13.20.0.2312

Crash report: http://paste.feed-the-beast.com/view/aff205d2

**Comment by thiakil** [comment]
Turn off `renderInventoryInWorld` in **Tinkers Construct** settings, remove the mekanism object from the Crafting Station.

You then have two options:
* Leave the setting off
* Turn it back on and don't craft Mekanism blocks in the Crafting Station

**Comment by Gladi** [comment]
hey thanks for the info and insight

**Comment by ktole1999** [comment]
@thiakil "........ don't craft Mekanism blocks in the Crafting Station"

please explain

**Comment by thiakil** [comment]
When the config option I mentioned is turned on, Tinkers Construct tries to render the blocks on top of the crafting station, which does not play nice with Mekanism's rendering of some items at current.

**Comment by ktole1999** [comment]
i understand that part as i have seen reports in the past about this bug. just didnt understand why you said "dont" craft mek blocks in craft station. Are you saying just dont use the tinkers version of the table if this setting is on? I thought the render bug was fixed?

**Comment by thiakil** [comment]
`**Turn it back on** and don't craft Mekanism blocks in the Crafting Station`

Emphasis added. Yes that is correct, Don't use it if the setting is on, or you risk a crash.

**Comment by ktole1999** [comment]
ahhh i misinterpreted the way you said it. my apologies.
