### ISSUE TITLE
Crashing on Loading World

### ISSUE THREAD

**Issue by PessimisticBastard** [aidancbrady/Mekanism#4449]
Whenever I load up my save looking at various parts from Mekanism, my world immediately turns to black, with some white boxes showing up. 

However, so long as I let the world load without looking at anything from Mekanism, it loads just fine, and I continue working on Mekanism stuff with no issue. 

Crash log: https://pastebin.com/iEk4M8iw

Edit: I should add this is for 1.11.2

**Comment by thiakil** [comment]
The crash itself looks like #4434 (seems to be basically a race condition)

As for the world turning to black (I'm assuming you mean it doesn't always crash), this could be a cross mod issue (you have quite a number of CoreMods), or perhaps an issue with the resource pack in use (perhaps shaders).
