### ISSUE TITLE
Electrolytic Separator Speed Upgrade Bug [1.11.2]

### ISSUE THREAD

**Issue by PessimisticBastard** [aidancbrady/Mekanism#4450]
Every other machine seems to accept speed upgrades just fine, but the electrolytic separator seems to be adding two at a time to add one level. It also seems to not correctly show its actual level, nor accurately show how much rf/t it is using.

**Comment by thommy101** [comment]
The dubble speed upgrades are already fixed in #4412 and will be available in the next build.
