### ISSUE TITLE
[1.10.2] McMultipart/Mekansim Crash

### ISSUE THREAD

**Issue by SirKillz** [aidancbrady/Mekanism#4451]
Mekanism Version: 9.2.2.301 
McMultipart 1.4.0

I'm playing a modded server custom pack I made and it seems that whenever I transport between dimensions with the Galacticraft mod I run into a server crash.  The crash does not point in anyway towards Galacticraft (I could be wrong) but instead I see the mention of McMultipart and Mekanism Universal Cables.  
Crash Report: https://pastebin.com/Ww7GCKft 
I've already posted in the McMultipart issues section but I figured I'd try here as well.

**Comment by thommy101** [comment]
Please use the search functionality... It's reported multiple times on this issue tracker and the one of mcmultipart

**Comment by SportsFan10** [comment]
Sorry about that, is there a fix then?

**Comment by thommy101** [comment]
#4374 It's a bug in MCMultiPart and no one knows yet what's causing the fault. It's known and under investigation over at amadornes/MCMultiPart#71
