### ISSUE TITLE
Mekanism turbine valve crash

### ISSUE THREAD

**Issue by IchigoGames** [aidancbrady/Mekanism#4455]
placing down a turbine valve from mekanism into the world results in an instant crash (crash report: https://pastebin.com/4pEBRbUx)
Mekanism-1.11.2-9.3.1.305
minecraft 1.11.2
if this is fixed in 306 sorry you can remove this.

**Comment by thommy101** [comment]
This one isn't fixed as far as I see right now. 

Technical explanation:
Some methods in TileEntiyTurbineCasing have null checks for the structure and some don't. As it seems the structure could be null it would be a good idea to protect them all with a null check
