### ISSUE TITLE
Digital Miner not mining on a modded server

### ISSUE THREAD

**Issue by GuestUserNameGUN** [aidancbrady/Mekanism#4458]
Here is the modlist for the server: http://www.wtechn.com/mod-list.html 
It has enough power, i have tried changing the redstone signal, changing what ores it mines, placing an ore right next to it and setting it to mine that, tried with all the options, i can't figure out what to do.

**Comment by thommy101** [comment]
Got a couple questions:
Which minecraft version? 
Which mekanism version? 
Got a log file? (case Singel player client log, case multi player server log) 
Got any protections active? (spawn protection, towns, ftb utilities)

**Comment by GuestUserNameGUN** [comment]
no protections apart from on spawn as it is a towny server, but i am 4k blocks away from spawn. minecraft 1.7.10, and mekanism 9.1.0. No log file, it wasn't an error. The digital miner says on the machine that it is working, but just doesn't mine stuff.

**Comment by thommy101** [comment]
1.7.10 isn't supported sadly.
But I know that if you're using Towny, you're also having something to manage permissions on your server. Towny has permissions for breaking blocks outside of towns, and Mekanism does need to have permission to break blocks outside of towns.

Up to the server administrator to add the permissions to the Mekanism user.
Permission is probably: towny.wild.*
User needed is printed in the log on startup like: Fake player readout: UUID = <UUID>, name = <NAME>
