### ISSUE TITLE
[1.10.2] No Sound Ingame

### ISSUE THREAD

**Issue by Black-Photon** [aidancbrady/Mekanism#4460]
I tried adding all 3 modules to the Direwolf20 pack, but it resulted in sound working normally on the main menu, but there is no sound whatsoever once a world is loaded - even in the menu. The sound returns when exiting back to the main menu

**Comment by thommy101** [comment]
That's wierd.. A couple questions:
- What version of Mekanism are you using?
- What version of the modpack are you using?
- Do you have any logs available?
- Is this singelplayer or multiplayer?

**Comment by Black-Photon** [comment]
Wow, I just downloaded and tried it again and it works fine. I can't imagine what the problem was before. Thanks anyway

If anyone ever sees this, try redownloading and reinstalling the mods

**Comment by nalivai** [comment]
I have the same problem, I'm using FTB beyond modpack, with Minecraft 1.10.2 version, and I've added Mekanism mod to it. When I load any world, my bluetooth headphones just stop working, not just in Minecraft but anywhere. And as long as my world is loaded, it stays so, but when I exit the world, headphones start working again.

**Comment by Black-Photon** [comment]
As I said, try removing Mekanism, play, and add it again, redownloaded. If this doesn't work, try making a new profile, and, if that doesn't work, restart your computer.
If it still doesn't work, consider reinstalling Minecraft.
If it still STILL doesn't work, come back here.

**Comment by nalivai** [comment]
Of course I did this before commenting. Also I've tried different versions of modpack and different versions of mod, new clean installation of client in a different location and even different windows profile, still the issue stays.

**Comment by thiakil** [comment]
Did it work before you added Mekanism? (it's not clear from your comments)

**Comment by nalivai** [comment]
Yeah it works good without Mekanism, and the problem goes away as soon as I remove it.

**Comment by Black-Photon** [comment]
Well, I'm out of advice. If none of that works, I guess I'll reopen the issue. Good Luck!
