### ISSUE TITLE
Do u still work on bigs on 1.7.10??

### ISSUE THREAD

**Issue by killer1stt1** [aidancbrady/Mekanism#4461]
I have an issue with mekanism for 1.7.10 idk if ur still workin pn it if not then im srry for bothering u but if u are then any time i use anything with steam in it it crashes this includes the dynamic tank and turbine im useing big reactors to make steam with ult pipes pumping ot into the tank then ult pipes pumping it into thw turbine i cant access the turbine or tank and to be noted i am pumping more then 5000mb/t for sure idk if that helps givin idk how much im actually pumping in ty

**Comment by ProxyPlayerHD** [comment]
the way this is Written... my eyes hurt...

But I am wondering the same thing, I have one Specific Issue with the 1710 Version of Mekanism, it kinda makes it hard to work with.

**Comment by aidancbrady** [comment]
Development is focused on 1.11, sorry.
