### ISSUE TITLE
Redstone Sensitivy does nothing

### ISSUE THREAD

**Issue by ProxyPlayerHD** [aidancbrady/Mekanism#4462]
No matter if ON or OFF if a Redstone Signal is on a Cable it will not Conduct Power.
even worse i have to mine the cable and place it again after removing the Redstone Signal for it to correctly work again.
Mek. Version 1.7.10-9.1.0.281

EDIT: also Turbines don't show any Power Generation, same version
[PIC](https://i.gyazo.com/b5268884f4e202b20669571e0fc6a89c.png)

**Comment by thommy101** [comment]
The 1.7.10 version isn't supported any more. Development is currently focused on 1.11.2.

**Comment by ProxyPlayerHD** [comment]
well shit, what am i supposed to do now? I can't patch mods...

**Comment by aidancbrady** [comment]
1.7.10 was released three years ago. It's about time other developers start porting to the later versions.
