### ISSUE TITLE
Mekanism Steel isn't recognized by Tinker's Construct

### ISSUE THREAD

**Issue by Partonetrain** [aidancbrady/Mekanism#4463]
[I'm assuming this is a Mekanism problem because all other mods that have steel are recognized by Tinkers' as far as I can tell]

Mekanism Steel Ingots **are** registered to the ore dictionary, but oddly enough Tinkers' Construct doesn't recognize it.

Using latest (CurseForge releases, not GitHub) Tinkers' Construct and Mekanism for 1.11.2, but according to this thread it is also a problem in 1.10.2. http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/mods-discussion/2800566-no-steel-in-tinkers-construct

**Comment by aidancbrady** [comment]
Steel is definitely registered, make sure another mod isn't changing recipes.

**Comment by Landmaster** [comment]
@aidancbrady Although you are correct that steel is registered in the oredict, it is registered too late: you are registering them in `init`, [whereas they are supposed to be registered in `preInit`.](https://mcforge.readthedocs.io/en/latest/utilities/oredictionary/) This is causing problems with other mods which depend on the oredicts, such as Tinkers Construct.

**Comment by thommy101** [comment]
By the look of @Landmaster 's comment, it's also responsible for #4288

**Comment by thommy101** [comment]
Created pull request #4465 to fix this issue.
