### ISSUE TITLE
CompatLayer?

### ISSUE THREAD

**Issue by bonnedav** [aidancbrady/Mekanism#4466]
Will the MC 1.11.2 version run on MC 1.10.2 using [CompatLayer](https://minecraft.curseforge.com/projects/compatlayer)? If not would it be possible to make it work? If it would be too hard and/or CompatLayer does not have a function you need, than that's fine. I am just wondering if it would work.

**Comment by thommy101** [comment]
It could work, but requires a whole redone of all the code touching anything with ItemStacks, which is.. Well.. Quite a lot. As CompatLayer (which I think is a great solution on itself) isn't going to support 1.12 (for very understandable reasons), I don't think it's a good idea to use CompatLayer in Mekanism as the 1.11.2 version is getting one of the most stable versions of Mekanism to date.

If I've got some more time after graduation (expected in a couple weeks), I'll think about backporting some of the bug/crash fixes to 1.10.2 to let Aidan make one final 1.10.2 release with the fixes till that date.

**Comment by bonnedav** [comment]
Ok thank you. So does that mean that people should go on a big bug finding spree in the next couple of weeks to get as many bugs fixed for 1.10.2 as possible? :)

**Comment by thommy101** [comment]
I would say, go on a bug finding spree for 1.11.2. Bugs which are there are probably also in the 1.10.2 version and have an much higher priority.

**Comment by bonnedav** [comment]
Yes that is what I meant. Find all the bugs we can in 1.11.2 and fix them there, then you can backport the fixes to 1.10.2.

**Comment by thommy101** [comment]
Exactly :D

**Comment by bonnedav** [comment]
Mainly I would like to see the IC2 issues fixed for the 1.10.2.

**Comment by thiakil** [comment]
@thommy101 There's been a number of commits since I've last updated (as I've had other projects to do lol), but I've been using this tree on my server ;) 

https://github.com/thiakil/Mekanism/tree/1.10-backports

**Comment by bonnedav** [comment]
Hay look, a jump start! :)

**Comment by bonnedav** [comment]
Sorry but I do not know a lot about Minecraft mods, how do you compile this (on Windows)?

**Comment by thiakil** [comment]
I would not advise doing so at this stage unless you know what you're doing, as once you use this branch your save file will be incompatible with Aidan's builds.

**Comment by bonnedav** [comment]
i will back up my save first than.

**Comment by thommy101** [comment]
@bonnedav, take a look at #4504 ;)
