### ISSUE TITLE
Atomic Disassembler crashes server when breaking blocks that are not solid blocks

### ISSUE THREAD

**Issue by koalalord9999** [aidancbrady/Mekanism#4467]
Using: Mekanism-1.11.2-9.3.1.305
Breakin doors, and slabs crashes the server when mined on vein mode, probably all modes.

**Comment by thommy101** [comment]
Do you have a crashlog? Please upload it to [gist.github.com](https://gist.github.com/) and place a link here.
Also please update to 9.3.1.307, there've been a couple fixes to the Atomic Disassembler, but I think they're already in version 305. Nevertheless, an update would fix a lot of issues.

**Comment by aidancbrady** [comment]
Just ran some tests, can't reproduce this on any mode with any kind of non-solid block. Interaction issue perhaps.
