### ISSUE TITLE
[Suggestion] Cactus -> Bio Fuel

### ISSUE THREAD

**Issue by VT-14** [aidancbrady/Mekanism#4469]
I would suggest allowing Cactus to make a small amount of Bio Fuel.

Pros: 
It's an organic material available in Vanilla
It is an easy to automate farm in Vanilla

Con: It's a **really** easy Vanilla farm.

Currently playing Mekanism v9 on 1.11.2 (9.3.2.307)

**Comment by aidancbrady** [comment]
Done!
