### ISSUE TITLE
[1.7.10] rotary condensentrator not inputting water

### ISSUE THREAD

**Issue by vanjiali** [aidancbrady/Mekanism#4470]
it is supposedly a fixed thing but with the newest versions for 1.7.10 (via curse/twitch desktop app) the rotary condensentrator reffuses to imput water through any form of pipe (and i did try quite a few of them) but whatever i try it doesnt work, even deinstalled mekanism and reinstalled, crafted another one, placing it in different ways etc, and that just breaks the automatic part of things :(

**Comment by vanjiali** [comment]
also i just noticed that if you put a portable tank (thermal expansion) into the bucket slot, it fills the machine with water without draining it from the tank

**Comment by aidancbrady** [comment]
1.7.10 is no longer supported, but regardless, this has been fixed.
