### ISSUE TITLE
[1.11.2] Logistical Transporters Server Crash

### ISSUE THREAD

**Issue by EmosewaGamer** [aidancbrady/Mekanism#4471]
While this may have to do more with mod interaction, when the Logistical Transporters are connected with a Crucible Inserter from Sky Resources, the server crashes. By the server crash log I can tell that i has to do with the way the transporter works, rather than the inserter.

https://pastebin.com/njYRHXZM

**Comment by aidancbrady** [comment]
Not sure how this could be occurring on my end but I added a check to be safe. Should be fixed in next release.

**Comment by EmosewaGamer** [comment]
Well piping systems from other mods don't crash it.

**Comment by aidancbrady** [comment]
If you can give me an exact reproduction scenario with a picture or two I could take a look again.
