### ISSUE TITLE
Game crashes on during mod construction

### ISSUE THREAD

**Issue by LordMortus** [aidancbrady/Mekanism#4473]
#### Issue description:

Game crashes while loading

#### Steps to reproduce:

1. Launch Minecraft

#### Version (make sure you are on the latest version before reporting):

**Forge: 13.20.0.2315 ** 
**Mekanism:  1.11.2-9.3.2.309 ** (Including Generators and Tools)

**Other relevant version:** 

#### crash-log

[crash-2017-06-16_18.20.54-client.txt](https://github.com/aidancbrady/Mekanism/files/1082089/crash-2017-06-16_18.20.54-client.txt)

**Comment by cursinorock** [comment]
same here
[crash-2017-06-16_22.43.32-client.txt](https://github.com/aidancbrady/Mekanism/files/1082229/crash-2017-06-16_22.43.32-client.txt)

**Comment by NoplixDE** [comment]
Just gonna confirm that I have the exact same Issue so I won't post an Error code, hope this get fixed quickly :)

**Comment by thommy101** [comment]
I will look at this today. Should be easy to solve

**Comment by thommy101** [comment]
Fixed and opened a pull request ;)

**Comment by NoplixDE** [comment]
When do you think will u release the Updated?

**Comment by thommy101** [comment]
That's up to @aidancbrady

**Comment by NoplixDE** [comment]
*sad face* xD hope it doesn't take too long :/ really want to use/play with it.

**Comment by aidancbrady** [comment]
Likely a week or so

**Comment by NoplixDE** [comment]
wait really? why would you not updated the mod right now if it is fixed already, doesn't make sense to me.
I can't use the mod now for a week why would you do something like this?

**Comment by aidancbrady** [comment]
There's more fixes in the pipeline, I'm waiting to release them all at once so we don't have staggered releases.

**Comment by NoplixDE** [comment]
But do the other bugs prevent u from playing with the mod completely? Don't get me wrong I dont want to be annoying or something but if something is game breaking why would you not updated it immediately. I mean I can't remove the mod and add it later again all the items would be gone + the wold might break.

**Comment by Ceriwaen** [comment]
Is there any way to work around this issue while we wait?  I tried backdating both Mekanism and Bookshelf/DarkUtilities but couldn't find a solution.

**Comment by Ceriwaen** [comment]
Nevermind, found the solution on the Bookshelf comments:
Using bookshelf version 1.5.0.371 and Dark Utilities version 1.2.0.135 fixes the crash.

**Comment by NoplixDE** [comment]
Thank u so much for the info!
