### ISSUE TITLE
crash with Bookshelf

### ISSUE THREAD

**Issue by Hypsellis** [aidancbrady/Mekanism#4476]
**Issue description:** The game crash when loading when using Bookshelf 20.0.0.379 and higher verion.

**Steps to reproduce:**

1. Have Bookshelf 20.0.0.379 or higher and Mekanism
2. Launch Minecraft

**Version (make sure you are on the latest version before reporting):**

**Minecraft:** 1.11.2
**Forge:** 13.20.0.2315
**Mekanism:** 9.3.2.309

**Crash log:** https://pastebin.com/shfKZCcd

**Comment by thommy101** [comment]
Please use the search as mentioned in the default issue template. #4473

**Comment by GuntherDW** [comment]
This is on a different bit of code as the other ones though.
The other ones crash on a bit of unused text in OreDictManager.java.
This one crashes on a bit of *used* code in MekanismUtils.java.
