### ISSUE TITLE
Mekanism pipes invisible when Connected Textures Mod is installed.

### ISSUE THREAD

**Issue by Dilnu** [aidancbrady/Mekanism#4477]
#### Issue description:
Hi, on 1.10 Connected Textures Mod breaks Mekanism pipes rendering.

Specifically the mekanism pipes are all invisible.
Relevantly CTM is a required library of chisel which sees wide usage.

#### Steps to reproduce:
1. Place down a basic universal cable
2. Observe that it is invisible

#### Version (make sure you are on the latest version before reporting):
My minecraft version is 1.10.2
Forge: 12.18.3.2297
CTM-MC1.10.2-0.1.0.13
Mekanism: 9.2.2.301
MC Multipart: 1.4.0

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://gist.github.com/Dilnu/7d73ced44946c60f691176fa09ebc689

**Comment by ACGaming** [comment]
Can confirm this: http://i.imgur.com/KiIsalS.png

**Comment by Dilnu** [comment]
As a work around reverting to version 10.22 of Chisel and removing CTM fixes the issue. I don't think there are any new textures added in that interval.

**Comment by thommy101** [comment]
Linking this to Chisel-Team/Chisel#459
There's a test version of the Connected Texture Mod in that thread which should fix the issues you're describing.
