### ISSUE TITLE
Galacticraft4 fluid pipes will not connect to Mekanism Oxygen

### ISSUE THREAD

**Issue by DrTwosie** [aidancbrady/Mekanism#4482]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Galacticraft oxygen pipes used to connect to electrolytic separators and gas tanks of oxygen. Galacticraft 4 replaced oxygen pipes with fluid pipes. These do not connect.

#### Steps to reproduce:
1. In a creative map, place a full tank of oxygen, an electrolytic separator, and a pressurized tube
2. Place fluid pipe next to each of these, or a sealed fluid pipe
3. They don't connect.

#### Version (make sure you are on the latest version before reporting):
** Mekanism:9.3.2.309 for 1.11.2
** Galacticraft 4

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

No crash, just loss of functionality.

**Comment by thiakil** [comment]
> Galacticraft 4 replaced oxygen pipes with fluid pipes. These do not connect

Mekanism oxygen is a gas (using a different connector api). Try using liquid oxygen from a rotary condensentrator. 

Otherwise this is very much Galacticraft's issue

**Comment by DrTwosie** [comment]
I'll raise it with Galacticraft. They seem to have created a pipe that handles both liquids and gases:

> Fluid pipes - these replace Oxygen Pipes in earlier Galacticraft versions, and can transport oxygen gas or many other types of gas or liquid, including a simple "pull" mechanism (when right-clicked with a Standard Wrench) to pump liquids out of a tank

Found [here](https://wiki.micdoodle8.com/wiki/Galacticraft_4)

**Comment by thiakil** [comment]
It does look like they still have compat code in there specifically for Oxygen gas. But as a general rule, if another mod's object is failing to interact with a mod, it's the object's mod's issue (unless of course you're the developer of the other mod).
