### ISSUE TITLE
Entity.BabySkeleton.name in death msg?

### ISSUE THREAD

**Issue by tyler489** [aidancbrady/Mekanism#4483]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Mekanism Baby Skeletons register as entity.BabySkeleton.name

#### Steps to reproduce:
1.Get shot by a baby skeleton
2.Die
3.Look at death msg

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.11.2 13.20.0.2315
**Mekanism:** 1.11.2 9.3.2
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://gyazo.com/430cbb59b462b717917b78084497ff66

does this mean that the Eu_us file needs changed ?

**Comment by thommy101** [comment]
It is indeed a fault in the language files. There's an "entity.Mekanism.BabySkeleton.name=Baby Skeleton" mapping, but not one you're describing.

**Comment by tyler489** [comment]
i knowticed that it is now ```entity.BabySkeleton.name```

**Comment by thommy101** [comment]
Can be closed, issue is solved and will be available in the next release.
