### ISSUE TITLE
Caught exception from Mekanism crash

### ISSUE THREAD

**Issue by IchigoGames** [aidancbrady/Mekanism#4486]
#### Steps to reproduce:
1.add Mekanism 
2.add darkhax bookshelf
3.crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2315
**Mekanism:** Mekanism-1.11.2-9.3.2.307
**Other relevant version:** Bookshelf-1.11.2-2.0.0.388

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/A4dH6H6N

**Comment by thommy101** [comment]
Please use the search functionality, this has been reported before and the fix will be available on the next release

**Comment by IchigoGames** [comment]
sorry i most of missed it.
