### ISSUE TITLE
Unexpected Error 1.11.2 Rendering Block

### ISSUE THREAD

**Issue by captcookie** [aidancbrady/Mekanism#4487]
#### Issue description: **java.lang.NullPointerException: Unexpected error**
	at mekanism.common.block.BlockTransmitter.func_180640_a(BlockTransmitter.java:179)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185918_c(BlockStateContainer.java:432)
	at net.minecraft.client.renderer.RenderGlobal.func_72731_b(RenderGlobal.java:2743)
	at slimeknights.tconstruct.tools.common.client.RenderEvents.renderExtraBlockBreak(RenderEvents.java:78)

**2nd crash

Unexpected error**

java.lang.NullPointerException: Unexpected error
	at mekanism.common.block.BlockTransmitter.func_180640_a(BlockTransmitter.java:179)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185918_c(BlockStateContainer.java:432)
	at net.minecraft.client.renderer.RenderGlobal.func_72731_b(RenderGlobal.java:2743)
	at slimeknights.tconstruct.tools.common.client.RenderEvents.renderExtraBlockBreak(RenderEvents.java:78)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1015_RenderEvents_renderExtraBlockBreak_RenderWorldLastEvent.invoke(.dynamic)

#### Steps to reproduce:
1. Look at mechanical pipes while a iron tinker tool is in hand; also looks like iron trowel tool from water strainer may cause it. I relogged on and my shovel like tool was in hand looking at pipes and the crash repeated to the launcher.
2. https://minecraft.curseforge.com/projects/water-strainer 
3. Simply look at pipes with tinkers or other non vanilla tool

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2315
**Mekanism:** 309
**Other relevant version:** 

https://pastebin.com/TBe9CFrX
https://pastebin.com/LrxWDKN1

**Comment by thommy101** [comment]
Cannot replicate with only Tinkers Construct & Mekanism.
Versions tested with:
TiCon 1.11.2-2.7.1.34
Mantle 1.11.2-1.2.0.26
Mekanism current 1.11 branch

**Comment by aidancbrady** [comment]
Fixed as of latest releases.

**Comment by stefgl** [comment]
I got this error too. In which Release will this be fixed?

**Comment by thiakil** [comment]
@stefgl please try this build and post the crash report

http://maven.thiakil.com/mekanism/MekanismAll-1.12.1-9.4.1.326.jar

NB: this goes in place of Mekanism, MekanismGenerators, & MekanismTools

**Comment by stefgl** [comment]
Same Exception but different Row now :[crashreport](https://pastebin.com/U5FzT7hS)

**Comment by thiakil** [comment]
Can I have the latest.log too please? Forgot to ask sorry. I made it give us some extra info so we can find which part is failing

**Comment by stefgl** [comment]
Hi,

attached you can find the latest logs



Regards,

Stefan

**Comment by stefgl** [comment]
did you receive the attachment? I think you are looking for this row, just before the error:

`[08:42:09] [main/ERROR] [Mekanism/]: state: mekanism:transmitter[tier=basic,type=universal_cable]
world: net.minecraft.client.multiplayer.WorldClient@7535baf9
pos: BlockPos{x=482, y=80, z=-521}
getTileEntitySidedPipe: mekanism.common.tile.transmitter.TileEntityUniversalCable@6eb5b2d1
getDefault: null`

**Comment by thiakil** [comment]
Attachment didnt work, but that's the line I was after, thanks

**Comment by thiakil** [comment]
OK, this one will either work (I may have found the issue), or it will crash somewhere else lol

http://maven.thiakil.com/mekanism/MekanismAll-1.12.1-9.4.1.326-2.jar

**Comment by stefgl** [comment]
Great Job 👍 
It doesn't crash anymore. Thank You!

**Comment by thiakil** [comment]
Excellent, thanks for your troubles!

**Comment by PapiDimmi** [comment]
@thiakil 404 not found! :(
