### ISSUE TITLE
[1.11.2]  Conflict between Mekanism and Journeymap

### ISSUE THREAD

**Issue by Endmateria** [aidancbrady/Mekanism#4488]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Error in log when only Mekanism and Journeymap are installed.  Log below is from client side instance, though I believe the error also was showing up in my server log.  Does not crash server or client games.

#### Steps to reproduce:
1.  Remove all mods except for the 3 Mekanism mods and Journeymap
2.  Launch game
3.  Read the latest log file

#### Version (make sure you are on the latest version before reporting):
**Forge: 2315** 
**Mekanism: 1.11.2-9.3.2.307** 
**Journeymap 5.4.7:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://gist.github.com/Endmateria/f2924c6b0c8d471ea63054e55305e9bd#file-latest-log
[gist/pastebin/etc link here]

**Comment by techbrew-mc** [comment]
@aidancbrady - the code in question is when JM iterates through valid blockstates and uses the block model's quads to figure out the texture and derive a map color.  The code works for vanilla blocks and most mods, but clearly something's unhappy in Mekanism with this approach.  If you have any questions or spot a problem with the way JM is going about it, let me know.

**Comment by andyb2** [comment]
I have the same problem.Tried going back a couple versions but same thing happens unless JM is removed

**Comment by techbrew-mc** [comment]
I've overhauled the color generation system in JourneyMap 5.5.0, which is now in beta.  The problem seen here should be solved.

**Comment by thommy101** [comment]
The latest version of Mekanism doesn't use the code which caused the errors any more, should be solved anyway ;)
