### ISSUE TITLE
[1.11.2] Crash with Bookshelf?

### ISSUE THREAD

**Issue by MokahTGS** [aidancbrady/Mekanism#4489]
Getting a crash calling out both Mekanism and Bookshelf.

Bookshelf v1.11.2-2.0.0.388 (release)
Mekanism v1.11.2-9.3.2.307
MekanismGenerators v1.11.2-9.3.2.307
MekanismTools v1.11.2-9.3.2.307

Crash Log: https://pastebin.com/5ubzPM7G

Is there a particular version of Bookshelf needed?

**Comment by thommy101** [comment]
As stated in the text you've deleted, please use the search functionality.. 

Has been reported multiple times, is fixed and will be available in the next release

**Comment by MokahTGS** [comment]
This issue is only fixed in the versions available through adfly's virus network.  Please update the curse entry so that people can play your mod without viruses and malware.

**Comment by thommy101** [comment]
Even the version on the Mekanism site isn't the right one, only contains one of the two fixes. Mod developers are just humans, and some of them are very busy with real life stuff like school and exams. Give them some slack and it will be released soon. 

And if you look at the closed issues, this one will be closed as well (like the precious x duplicates)

**Comment by BrianEdmonds** [comment]
> And if you look at the closed issues...

Might make your lives easier to keep a canonical issue open at least
until a fix is released.  GitHub defaults to searching open issues.
Might also make your lives harder, since you'd have to track the issues
to map them to releases. :)
