### ISSUE TITLE
1.10.2 - Mekanism/IE interop - cannot get CCW of Down

### ISSUE THREAD

**Issue by robertmaxton42** [aidancbrady/Mekanism#4491]
Mekanism 301 on 1.10.2 interfacing with IE 0.10-60 pipes. I am aware of https://github.com/aidancbrady/Mekanism/issues/4039, but we are using the latest Mekanism version and the problem persists.

A full crash log (it's a clientside crash) can be found [here](https://pastebin.com/XNJqZ1RC).

**Comment by thommy101** [comment]
Found the commit that fixed it: c12f1c1e6f521465ba7ea81c3ef0c39289ae115b

Looking at the history it's one of the changes that didn't made it to the 1.10.2 version of Mekanism.

**Comment by robertmaxton42** [comment]
Mmkay. So then, will there be a 1.10.2 update to fix it?

**Comment by thiakil** [comment]
See #4504, once it's completed hopfully Aidan will accept it.
