### ISSUE TITLE
1.11.2 Cannot craft Compressed Obsidian

### ISSUE THREAD

**Issue by captcookie** [aidancbrady/Mekanism#4493]
#### Steps to reproduce:
1. https://cdn.discordapp.com/attachments/329036220422160384/329036293671616522/ScreenHunter_876_Jun._26_18.08.jpg
2. https://cdn.discordapp.com/attachments/329036220422160384/329036316782100482/ScreenHunter_877_Jun._26_18.08.jpg
3. Nothing Happens-- stuck cannot progress to make other things in the mod. D:

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2315 Multiplayer Server
**Mekanism:** 309
**Other relevant version:**

**Comment by thommy101** [comment]
That looks a lot like obsidian dust, not refined obsidian dust.
You need to put obsidian dust, together with some diamonds in the left slot in a metallurgic infuser.
You'll get refined obsidian dust out of it, which you can put in an enrichment chamber to make compressed obsidian.

**Comment by captcookie** [comment]
Yup that was it thanks
