### ISSUE TITLE
[Request} Advanced Rocketry ore support

### ISSUE THREAD

**Issue by llloyd4** [aidancbrady/Mekanism#4500]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

I noticed even though there is dust forms for all the AR ores, like Titanium, Iridium, etc, the Enrichment Chamber can't double the ore nor the Smelter can turn that dust into ingots. 

#### Steps to reproduce: 
1. Put 'rutile' ore into an enrichment chamber
2. observe it sitting there doing nothing
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.10.2-12.18.3.2316
**Mekanism:** 1.10.2-9.2.2.301
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

N/A

**Comment by aidancbrady** [comment]
I'd leave this kind of integration up to Advanced Rocketry.
