### ISSUE TITLE
Actually Additions "Crushed Black Quartz" stopped processing in Smelter

### ISSUE THREAD

**Issue by llloyd4** [aidancbrady/Mekanism#4501]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

I had setup, ages ago, an elite smelter to handle AAs Crushed Black Quarts to smelt it into Black Quartz. Just recently I noticed that the whole process came to a screaming halt. On investigation I found the Crushed Black Quartz was just sitting in the Smelter. I've had to swap over to an Electric Furnace from Thermal Expansion. 

#### Steps to reproduce:
1. Put "Crushed Black Quartz" in a Smelter
2. Observe it doing nothing
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.10.2-12.18.3.2316
**Mekanism:** 1,10.2-9.2.2.301
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

N/A

**Comment by thommy101** [comment]
I'm pretty sure Mekanism didn't change anything that could cause this. Mekanism uses the default provided smelting list of Minecraft/Forge to smelt it's items in the smelter.

If it does smelt in a furnace, but not in a smelter, then it's a Mekanism bug. Could you test if it works in a vanilla furnace and the Mekanism smelter has enough energy to process it?
