### ISSUE TITLE
[1.10.2]I keep on facing exceptions for minecraft 1.10.2 with two mods

### ISSUE THREAD

**Issue by Bakaistic** [aidancbrady/Mekanism#4502]
#### Issue description:
I keep on facing exceptions from both mekanism and Universal Coins when i put in the mod Universal Coins and Metroid Cubed. 

#### Steps to reproduce:
1.Install minecraft forge
2.Put in Mekanism, and the modules of it as well
3.Put in either Universal Coins mod 1.10.2(https://github.com/notabadminer/UniversalCoins/releases/tag/1.10.2-0.6), or put in Metroid Cubed mod 1.10.2(https://mods.curse.com/mc-mods/minecraft/241126-metroid-cubed-3). Make sure to install the block/item API for it.(https://minecraft.curseforge.com/projects/firemeralds-block-item-model-api)

#### Version:
**Forge:12.18.3.2272** 
**Mekanism:9.2.2.301** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: 

https://anotepad.com/notes/6g7rim
https://anotepad.com/notes/ftc68e

**Comment by thiakil** [comment]
The Universal Coins crash has nothing to do with Mekanism.

If the 2nd one disappears after Metroid Cubed is removed, then it is probably either incorrectly bundling the Galacticraft API, or its coremod is preventing Forge's `Optional.Interface` from working

**Comment by thiakil** [comment]
Also if you're going to put minimal reproduction steps like that, your crash logs should reflect that. The crash could be related to something else in there.

**Comment by Telemain** [comment]
I also encountered this issue and posted it on the [Metroid Cubed repository](https://github.com/FirEmerald/Metroid-Cubed-3-API/issues/3)

**Comment by thommy101** [comment]
If you're sure the downloads are not corrupted, I'm 80% sure to blame core mods. And metroid is one. I guess this is not a Mekanism issue.
