### ISSUE TITLE
Disable welcome message

### ISSUE THREAD

**Issue by fcpwiz** [aidancbrady/Mekanism#4509]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I want to disable the `[Mekanism] Using developer build 9.2.2` message on worldjoin.

#### Steps to reproduce:
1. Join a world

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2281
**Mekanism:** Mekanism-1.10.2-9.2.2.301.jar
**Other relevant version:** N/A

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by EzerArch** [comment]
Try this:
1. Open Mekanism.cfg, in .minecraft/config.
2. Search `B:UpdateNotifications`
3. Set it to `false`.

**Comment by fcpwiz** [comment]
Well, that did it- thank you! It's too bad it's in such an odd location in that config file.
