### ISSUE TITLE
[1.11.2]mekanism crash with bookshelf mod

### ISSUE THREAD

**Issue by jackytuutykcaj** [aidancbrady/Mekanism#4512]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Crashing on startup

#### Version (make sure you are on the latest version before reporting):
**Forge:*13-20.1.2393* 
**Mekanism:*1.11.2-932.307* 
**bookshelf:*1.11.2-2.0.0.388* 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/2pvi9EZ9

**Comment by MokahTGS** [comment]
Please use the search functionality before reporting an issue. Also take a look at the closed issues!

Issue description:

Crashing on startup confirmed.  Also testing with .309

Version (make sure you are on the latest version before reporting):

**Forge:13-20.1.2393
**Mekanism:1.11.2-932.307
**MekanismGenerators:1.11.2-932.307
**MekanismTools:1.11.2-932.307
**bookshelf:1.11.2-2.0.0.388

If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/tK9RjAX4

**Comment by MokahTGS** [comment]
And the crash log for v309 of Mekanism...I'm just assuming the issue wasn't fixed between 307 and 309.

https://pastebin.com/WZzUZSMg

**Comment by thommy101** [comment]
As in the default text mentioned, please use the search functionality.. This issue has been reported before and it's fixed and will be available in the next release.

**Comment by jackytuutykcaj** [comment]
Thanks for answering, Will look before reporting next time.
