### ISSUE TITLE
Advanced Solar Generator causing crash

### ISSUE THREAD

**Issue by crazyamri** [aidancbrady/Mekanism#4514]
In need of help with finding the problem.

Issue description: Everytime i'm trying to craft advanced solar generator, it crashes. no problem if i was in creative. Only when crafting.

https://pastebin.com/embed_js/mQxWM69Q

**Comment by thommy101** [comment]
There's a known issue with Mekanism items and Tinkers Construct crafting table rendering. There's a fix which is supposed to fix it, but it's not released yet.
In the mean time, disable crafting table rendering of tinkers construct in it's config (I don't know the exact name for it at this moment).

**Comment by crazyamri** [comment]
Thank you. 

I dont really know how to edit config and such, so i'll wait for the patch instead.

**Comment by thommy101** [comment]
For the patch, keep an eye out for #4504.

**Comment by thommy101** [comment]
Can be closed as #4504 has been merged and will be available in the next release for 1.10.
