### ISSUE TITLE
Machines do not output into storage drawers, pipes do not connect to storage drawers

### ISSUE THREAD

**Issue by BarsikTheCaT** [aidancbrady/Mekanism#4516]
Mekanism does not seem to recognize storage drawers as inventories - I can not make machines to output into a drawer and pipes do not connect to them

The issue occurs when playing All The Mods 3.00b for Minecraft 1.10.2

**Comment by xannor** [comment]
I have been having this issue as well 1.11.2, the machines and pipes will connect to Controllers and Slaves, just not individual drawers.

**Comment by BarsikTheCaT** [comment]
Machines do not seem to work with thermal dynamics itemducts too - I can't even pull items out with a servo.

**Comment by ktole1999** [comment]
i have a custom pack and machines WILL output to storage drawers using mek pipes using mek v301.

**Comment by thommy101** [comment]
Confirmed in latest 1.11.2.

Code analysis:
https://github.com/aidancbrady/Mekanism/blob/1.11/src/main/java/mekanism/common/util/TransporterUtils.java
Individual storage drawers return 0 as their inventory size, causing a fault in Mekanisms detection of inventories. Storage drawers are a special case as they are not realy an inventory with normal stacks, but something that was once referenced as Deep Storage Units.
The check for InventoryUtils.isItemHandler would pass correctly (and is the more recommended way in the later versions)

**Comment by aidancbrady** [comment]
Going to mark this closed, as IItemHandler compatibility would perform correctly.

**Comment by thommy101** [comment]
IItemHandler does work correctly, but is skipped as the block does have a IInventory (it is an if and elseif, not two ifs).
