### ISSUE TITLE
[Enhancement Request] Digital Miner Markers

### ISSUE THREAD

**Issue by R1ZL4** [aidancbrady/Mekanism#4517]
Instead of moving the digital miner around (it looks nicer sitting in your base) it would be nice if we could have range markers instead. They could either be used in a set of 4 which indicate the boundary to mine or singularly where each marker is placed in a chunk you wish to mine.

As the digital miner uses teleportation technology to mine (presumably) it's location shouldn't really matter other than chunk loading.

**Comment by aidancbrady** [comment]
If this was done, I'd probably do so using some kind of fancy UI rather than markers -- I don't want to infringe too much on BuildCraft.  Closing for now, but I'll consider in the future :)
