### ISSUE TITLE
Lag causing the server to crash

### ISSUE THREAD

**Issue by Zeldri** [aidancbrady/Mekanism#4518]
#### Issue description:
I noticed that after I timed out on my server, those errors appears on the console, And I dont find why it's keep doing that and what I need to do to fix it
(Btw I'm new in GitHub :D ans I'm French)
#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge: **forge-1.10.2-12.18.3.2297-universal 
**Mekanism:** Mekanism-1.10.2-9.2.2.301 
**Other relevant version:** 

[Pastebin](https://pastebin.com/2tb5GmGb)

**Comment by thommy101** [comment]
Do you have a whole log? The warnings I see aren't related to a slow server only to the broken IC2 integration of Mekanism (see #4370).
What does indicate that you're having a slow server is the first line of the provide log, but that's not Mekanism.

**Comment by thiakil** [comment]
Your Refined Storage is having errors, make sure that's on the latest version too.
