### ISSUE TITLE
Turbine Valve + RFTool's Power Monitor = Crash

### ISSUE THREAD

**Issue by Xiaminou** [aidancbrady/Mekanism#4522]
#### Issue description:
When I broke a block of my fully formed Turbine that was being monitored by an RFTools' RF Power Monitor the server got locked into a crash loop.

#### Steps to reproduce:
1. Form a Turbine
2. Use RFtool's power monitor on turbine valve
3. Break a block of the turbine

#### Version (make sure you are on the latest version before reporting):
**Minecraft:** 1.11.2
**Forge:** 2388
**Mekanism:** 9.3.2.307
**RFTools:** 6.10

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
[crash-2017-07-10_15.51.58-server.txt](https://github.com/aidancbrady/Mekanism/files/1135725/crash-2017-07-10_15.51.58-server.txt)

**Comment by thommy101** [comment]
Thank you for your detailed report, traced down the crash :)
I'll open a pull request in a moment!
