### ISSUE TITLE
Copy bug using Chemical Washer in 1.7.10

### ISSUE THREAD

**Issue by iKEVAREZ** [aidancbrady/Mekanism#4526]
#### Issue description:
Copying using ChemicalWasher

#### Steps to reproduce:
1. Open inventory
2. Place stackable item in first slot in hotbar
3.  Use letfclick with left shift on item
4. Look at slot 9 in hotbar (moved item from first slot and added one item from bug)

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.7.10-10.3.4.1614
**Mekanism: 1.7.10-9.1.0.281
**Other relevant version: I've tested with latest version from github (MekanismAll-1.7.10-9.1.1.homebaked.jar) but bug exist in this version :/

Please help ;)

**Comment by thommy101** [comment]
1.7.10 isn't supported anymore. Development is currently focused on 1.11.2 ( and probably switching to 1.12 soon). 

If I remember correctly, it is fixed in 1.10 and onwards.

**Comment by iKEVAREZ** [comment]
Ok. But how can I fix this? If 1.7.10 is not supported anymore...

**Comment by thommy101** [comment]
The fix is somewhere in 650 commits, I don't think you can find it that easy. 

I can only advice updating to a more recent version  of Minecraft.

**Comment by iKEVAREZ** [comment]
Ok. I fixed this with my friend :D
By adding "!" somewhere xD


My friend: 
ezz to fix <3
