### ISSUE TITLE
Logistical Sorters Delete Overflowing Items

### ISSUE THREAD

**Issue by SuperFanatic** [aidancbrady/Mekanism#4527]
#### Issue description:
   When using a logistical sorter to send items into a container, if the storage container being outputted into doesn't have enough space for a stack of an item that is in its input storage container, but does have space for a partial stack, it will send an entire stack through anyway, deleting what won't fit.

#### Steps to reproduce:
1. Place down two storage containers/machines with inventories, and connect them with a logistical sorter.
2. Fill the second container(the one on the sorters output) with any item, but leave one slot only partially full
3. Put enough of said item into the first container (input end) so that it would be MORE than enough to fill the second container.
4. the sorter will pull a/the stack of items out of the first container, put what it can in the second, and delete the rest of that stack

#### Current workaround:
   Make sure your logistical sorters always have enough space to output into, such as a double chest that then outputs directly into a machine using regular pipes, rather than using the sorter to go straight into the machine. This will prevent any overflow from happening and thus, prevent item deletion.

#### Version:
**Forge: 13.20.0.2228** 
**Mekanism: 9.3.2** 
**Minecraft: 1.11.2**

**Comment by thommy101** [comment]
Confirmed with latest version
