### ISSUE TITLE
[1.12] Gasses are fluids!

### ISSUE THREAD

**Issue by Skillotic0703** [aidancbrady/Mekanism#4528]
Forge supports fluids (so it supports gasses). You should stop using your own gas system as it's bad for compatibiliy with other mods. If you want gaseous brine, call it gaseous brine but allow it to be transported with the same conduits as liquids! Stop this nonsense please!!!!!!!!!!!!!!

Thank you in advance for taking a look at this.

**Comment by SteelShot** [comment]
While gases and liquids are both fluids, but they both are subsets, which have their own unique characteristics.

Now when it comes to transporting it, most known way to people is by pipelines, there not much difference. Both are big tubes that run over large amounts of length. You can transport liquids over gas pipelines, but not vice versa. 

Gasses need to be pressurized to high pressure so they can be in liquid form and be most effectively transported, while liquids are all ready as a liquid form, there is no need to have high pressure and they can only need to be pumped one way. Usually pipelines for oil are made from steel or plastic and are often buried underground, while gas pipelines which need to withstand the high pressure of the compacted gas, henceforth they are made of carbon steel.

Also for gas pipelines there is a need of more substations and valves to release overbuilt pressure and required compressors for the gas to be liquefied by pressure, while liquid pipelines only require pumping station, that provide low pressure just to upkeep the flow.

In a sense Aidan is keeping it, "realistic" and in my opinion it's up forge to provide a GAS API, as gasses and liquid are not 1 to 1 in characteristics.

[IMG]http://i.imgur.com/99SpNxe.png[/IMG]

**Comment by thiakil** [comment]
> You should stop using your own gas system as it's bad for compatibiliy with other mods.

In other words "I don't like that I have to use this mod the way the author intended it"

**Comment by Skillotic0703** [comment]
The way gasses are transported in mekanism is very similar to fluids.
Pressurized tubes are just liquid pipes that were named pressurized tubes, that can only transport "gasses" and that are crafted with steel.
I mean that it's just sth visual.
Minecraft is not a realistic game!
Do you think that every machine is made exactly with the same materials and the same processes than in reality?
I won't go further in this post because I think there isn't one solution.
Everybody can't agree with the same idea.

**Comment by HanatakeYurii** [comment]
> Everybody can't agree with the same idea
Everybody won't agree with the same idea

> Stop this nonsense please!!!!!!!!!!!!!!
Take that for yourself, since it makes sense for some (many) people you can't name that nonsense. It's just another point of view. You can have yours but you can't expect everyone to have or follow the same. Plus talking about "realistic" won't go anywhere, since any game/creation will be realistic at some point. Gas will not overkill Minecraft unrealism.

For last I would say let Aidan make the choice, it's his mod, his vision after all. Who knows if he has specific plans for this, or Forge Team will develop specific gas system in the future.

**Comment by aidancbrady** [comment]
_Maybe_ one day. Not anytime soon, though.

**Comment by thommy101** [comment]
I do like the suggestion of using the default forge api for gasses, what I do not like is the fact that every other mod would totally wreck the balance of Mekanism as they do not diffirenciate between fluids and gasses. If other mods make it so their fluid pipes only accepts fluids, then I would have no objection. 

As it stands now, I like the current feature of the seperate gas api.

**Comment by cauamachado51** [comment]
up
