### ISSUE TITLE
[Question] How would I go about porting Mekanism to Minetest

### ISSUE THREAD

**Issue by JacobSinclair** [aidancbrady/Mekanism#4532]
Sorry, but this is really the best way I could think of contacting you.

If you don't know, minetest is an open-source game engine and game made in C++ with a Lua modding API.

Now, I was wondering; how would I go about porting Mekanism to minetest? I would like to use the mechanism models and textures, although I don't know whether I am allowed to.

And also, I would like to make everything work the same way so I don't end up messing up any designs.

I have the power API already done (me and a friend are working on an API) and I know how to use it

So, how would I go about implementing this? Could I use resources from mechanism? Should I make slight changes to the way things work to better suit minetest, or should I edit some small things about minetest to better suit the mod (like some ore's generation).

Thanks in advance

**Comment by aidancbrady** [comment]
Mekanism is licensed under MIT which means you really can do whatever you want with it. If you're porting Mekanism to a different platform you definitely have my blessing, although I do ask that you provide credit. Let me know if I can do anything to help.

**Comment by zzApotheosis** [comment]
For the record, I'm pretty sure someone would have to rewrite the entire mod in Lua, since the official modding platform on Minetest is designed for Lua. Though I must say that would be pretty cool to see.

It may be noted that Lua can instantiate objects, so most Java classes should be able to almost directly translate to Lua.

**Comment by JacobSinclair** [comment]
@zzApotheosis Yes, I would have to re-write it (and ontop of that I would need to make my own class system) but, after that, allot of things should pretty much be me translating java to lua. @aidancbrady If you can (if you can't it's fine) could you get the Mekanism 3D models in .obj format? Minetest doesn't allow you to define vertices and colors in code as far as I know.

**Comment by RSL-Redstonier** [comment]
I am also working on a mekanisim clone/port for minetest
