### ISSUE TITLE
Mek Generators + BC = Crash

### ISSUE THREAD

**Issue by ProxyPlayerHD** [aidancbrady/Mekanism#4533]
newest Forge Version (13.20.1.2414)
newest Mek. Versions (9.3.2.307)
newest BC Verison (7.99.6)
[REPORT](https://pastebin.com/5eHkwqjp)

**Comment by thommy101** [comment]
Please use the search functionality. 
Duplicate of #4513

**Comment by ProxyPlayerHD** [comment]
oops, sorry.

**Comment by thiakil** [comment]
@ProxyPlayerHD you are able to close your own issue btw

**Comment by ProxyPlayerHD** [comment]
oh i didn't knew that.
