### ISSUE TITLE
[1.11.2] Placing water in a machine with a forestry tin can or capsule causes a ticking tile entity

### ISSUE THREAD

**Issue by BionicFelps** [aidancbrady/Mekanism#4539]
Using a forestry tin can or capsule instead of a bucket in Mekanism machines causes ticking block crash.

1. Place electrolytic separator
2. Put water can in water slot
3. Crash

Mekanism 307
Forge 13.20.1.2386
Minecraft 1.11.2

Log:
https://paste.ee/p/oxUq9

**Comment by thiakil** [comment]
While the crash is a Mekanism bug, are Forestry cans meant to be consumable? (the silver ones, I grabbed a water filled one from JEI)

If not, that's a Forestry bug

**Comment by BionicFelps** [comment]
I'd have to ask, I know the capsules are supposed to be consumable, they're only made of wax after all. I want to say I remember getting the cans back a long time ago, but this was 1.6.4, could've just been other mods assuming to give back empties.
