### ISSUE TITLE
Crash on startup with Mek 1.10

### ISSUE THREAD

**Issue by warplord** [aidancbrady/Mekanism#4540]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Crash on startup when I updated from Mekanism v9.2.2.301 to final

#### Steps to reproduce:
1. Start the game
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** latest for 1.10
**Mekanism:** final
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

http://paste.feed-the-beast.com/view/269205cd

**Comment by thommy101** [comment]
Note: Reportedly happening after updating Mekanism. Also reported on the reddit post about this update. 
Linking to https://github.com/SonarSonic/Flux-Networks/issues/124

**Comment by warplord** [comment]
So the final version is unusable? OR is there anything that can be done?

**Comment by thommy101** [comment]
Ik not sure what causes the crash, I'll look into it a bit more tomorrow (currently on mobile)

**Comment by bytetrip** [comment]
This should probably be closed. FluxNetworks is using the old API and crashing. It's already reported there: https://github.com/SonarSonic/Flux-Networks/issues/124

**Comment by thommy101** [comment]
I'm happy it's reported here. Gives us insight at what happened and we might be able to solve it. 

The reason it's breaking isn't their fault, we released a version without backwards compatibility.

**Comment by thommy101** [comment]
Created a pull request for Flux-Networks to fix this issue.

**Comment by thiakil** [comment]
This should be fixed in this Mekanism version (FN should load, but any specific Mek functions will require them to update)
https://minecraft.curseforge.com/projects/mekanism/files/2455227
