### ISSUE TITLE
1.11 update master branch from 1.11 branch

### ISSUE THREAD

**Issue by robjw95** [aidancbrady/Mekanism#4554]
Can we get an update on the master branch with all the fixes from 1.11 branch from the last month and a half.  The master update done last night only included one fix making the new 310 download do basically nothing.  We still have crashes with dark utilities and buildcraft which all has been fixed in the 1.11 branch.   Or is there way to download the 1.11 branch version directly instead?

**Comment by aidancbrady** [comment]
Very very soon :)
