### ISSUE TITLE
[Feature 1.11.2] Compatibility to Storage Drawers

### ISSUE THREAD

**Issue by PearlCanopus** [aidancbrady/Mekanism#4558]
It's no bug or big deal and I don't know whether this has ever worked before. I checked that out yesterday.

Mekanism: 9.3.2.307 (latest release)
Forge: 13.20.1.2386 (recommended)
StorageDrawers 4.2.10 (latest release)

Osmium seems not to be compatible with "Compacting Drawers", because it's not splitting into block, ingot, nugget within this drawer.
It works fine with metal parts from Thermal Foundation and Immersive Engineering. I have no idea whether this could have conincidence with any other of my bunch of mods possibly.
I don't use a predefined modpack.

**Comment by thommy101** [comment]
It seems to be working fine over here. Just the osmium ingots and blocks, as there are no nuggets.

![image](https://user-images.githubusercontent.com/1036527/28523439-ba4a7924-707c-11e7-98fe-68aa1adc1b9d.png)

_Sidenote: you're not using the latest Mekanism version ;)_

**Comment by thommy101** [comment]
Aaah, I see what you mean. If I insert the block first, it doesn't work. If I insert the ingot first it does work.
Sounds like a problem with StorageDrawers.

**Comment by PearlCanopus** [comment]
ok, might be a problem elsewhere in my pack of mods... :) thx

**Comment by thommy101** [comment]
No problem ;) If you've found it, would you let me know? Might come in handy

**Comment by thiakil** [comment]
@thommy101 It could be partially our fault, depending on how the ingot/block recipes are registered. IIRC SD has an API call that we can use to ensure it can read our recipes

**Comment by thommy101** [comment]
They check if the item inserted gives 9 of an other item back and the other way if 9 items of x result in 1 of another type. Think it's all automated without hardcoding.

**Comment by thiakil** [comment]
```
/**
 * Recipe handlers are used by compacting drawers to find more-compressed forms of blocks and items.  If your recipe
 * to craft compressed items is a custom IRecipe implementation, you will need to register a handler for it.
 */
```

**Comment by thommy101** [comment]
That would explain a lot, we use a custom IRecipe for almost everything (in 1.11, 1.12 has changed it a lot)
