### ISSUE TITLE
[1.11.2] Energy side configuration doesn't respect block orientation

### ISSUE THREAD

**Issue by christofferson** [aidancbrady/Mekanism#4560]
#### Issue description:
Regardless of which way a block is oriented the side configuration for energy always treats the faces as follows:
- Front is North
- Back is South
- Left is West
- Right is East
- Bottom is Down
- Top is Up

Also tested with items but this seems to be functioning as expected.

#### Steps to reproduce:
1. Face north
2. Place an energy cube / machine / quantum entangloporter
3. Configure the block to accept energy on every side
3. Surround the block with universal energy cables
4. Toggle the energy acceptance for each side on/off and make note of which cables detach
5. Repeat the process facing South, East, West, Up, Down as desired

#### Version:
**Forge:** 13.20.1.2393
**Mekanism:** 9.3.3.311-fix

**Comment by thommy101** [comment]
Fixed in 2a535733c1b5a5c38361acf5f3b267ea78efb165
