### ISSUE TITLE
(1.11) Poof! crashes.

### ISSUE THREAD

**Issue by Migmag789** [aidancbrady/Mekanism#4561]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. In the Minecraft Loading
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 10.20.1.2421
**Mekanism:** 9.3.2.307
**Other relevant version:** 
[crash-2017-07-24_22.22.30-client.txt](https://github.com/aidancbrady/Mekanism/files/1171097/crash-2017-07-24_22.22.30-client.txt)

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thommy101** [comment]
You're using an old version. Please update to the latest version (311-fix on curseforge).

**Comment by Migmag789** [comment]
Ok thank you ^^
