### ISSUE TITLE
[Request] Support for Cyclic Nether Ores in Vein Mode for Atomic Disassembler

### ISSUE THREAD

**Issue by Laruae** [aidancbrady/Mekanism#4564]
Would love to see the vein mode working for the Cyclic Nether ores. Possibly a config where which blocks are considered for vein mode could be adjusted would be really, really nice!

#### Version (make sure you are on the latest version before reporting):
**Forge:1.11.2-13.20.1.2386** 
**Mekanism:1.11.2-9.3.2.307**
**Cyclic:Cyclic-1.11.2-1.5.7**

No Crash here, just no vein compatibility for some ores.

**Comment by thommy101** [comment]
Did some testing, All Cyclic nether and end ores are oredict registrated to the corresponding values (oreRedstone, oreIron). Mekanism filters on blocks with an oredict starting with ore. All are working correctly.

**Comment by aidancbrady** [comment]
Vein mode is guaranteed to work on all blocks that have an OreDict registration starting with "ore". If an ore is not compatible, it is up to the offending mod author to add a proper registration.
