### ISSUE TITLE
Quantum Entangloporter - Can't navigate channels

### ISSUE THREAD

**Issue by scotty9090** [aidancbrady/Mekanism#4566]
Similar issue as #3328 - except I can't navigate channels at all once I add more than 4.  The scroll bar at the right is not responsive and I've tried finding a place to click that will allow me to scroll the list but can't.  I've  basically done a pixel hunt trying to find a sweet spot to click that will scroll the list but without success - tried both the top and the bottom.

Scroll wheel functionality would be great, but failing that is there any other way to navigate this?  It seems like I can just enter the name in the text box and click the check mark to set it, but I'm not clear if that's setting the channel or just adding a new one.

**Comment by thommy101** [comment]
Depending on which version you're using, there is already a scroll feature implemented.
Just hover over anywhere in the frequency list (marked red on the picture below) and it automatically scrolls. Manually scrolling is with the dark gray dot (marked blue).

![quantumentangloporter](https://user-images.githubusercontent.com/1036527/28588221-25988222-717a-11e7-9d2e-a3bc352e23d0.png)

**Comment by scotty9090** [comment]
Thank you for the reply.  I'm on 1.10.29.2.2.301 and unfortunately neither of those is working for me.  Hovering definitely doesn't do anything and I've tried clicking on that top dot - that's actually the first thing I tried.  So it sounds like I'm trying the right things, but just without success. 

I'll try this in a test world so I have a fresh list and see if I can get something to happen.

**Comment by thommy101** [comment]
Ah, that explains a lot. The scrolling feature is initially added in 1.11 and backported with the latest release of mekanism 1.10. Please try it with the latest version, should work a lot better.

**Comment by thiakil** [comment]
I have a feeling I actually added the scroll feature to 1.10 and Aidan ported it to 1.11 haha. Been a while tho so not sure.

**Comment by thommy101** [comment]
Is it already that long ago? Damn.. Than it should certainly work.

**Comment by thiakil** [comment]
It may not have made it to 301 though, as it was past when Aidan started focusing on 1.11

**Comment by thommy101** [comment]
Just checked, 301 doesn't contain support for the scroll wheel. To use it, please update to a newer version (9.2.2-final-fix on CurseForge).

**Comment by scotty9090** [comment]
Awesome - I just updated to the "final-fix" version for 1.10.2 and now I can scroll with the mouse wheel!  Thanks for the help guys.  I'll go ahead and close this.
