### ISSUE TITLE
[1.10.2] Missing language localization

### ISSUE THREAD

**Issue by MJRLegends** [aidancbrady/Mekanism#4569]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
A item has no lang localization

![](https://i.gyazo.com/d11b67fee0f73b2a463e9a95f46a668d.png)

#### Version (make sure you are on the latest version before reporting):
**Forge:** Latest
**Mekanism:** Latest

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
Seems to be due to a spelling mistake
https://github.com/aidancbrady/Mekanism/blob/1.10/src/main/resources/assets/mekanism/lang/en_US.lang#L1114

**Comment by thommy101** [comment]
Please be specific with versions.. Something like "latest" isn't always the latest :)

**Comment by MJRLegends** [comment]
Yeah i get you, i always make sure im using latest but 1.10.2-9.2.2-final-fix.jar

**Comment by MJRLegends** [comment]
Thanks for fixing this @thiakil btw there is double entry's for these items https://github.com/aidancbrady/Mekanism/blob/7efff059bb2bf8d03a7a0d32329e4365002f1553/src/main/resources/assets/mekanism/lang/en_US.lang#L1106 is the ones that need to be removed

**Comment by thiakil** [comment]
Well that would mean the change I made doesn't fix it.

**Comment by MJRLegends** [comment]
No i mean there is two sets of localization in each lang file for the lapis lazuli tools and armour

**Comment by thiakil** [comment]
Meaning the key that your screenshot is showing was *already present*

**Comment by MJRLegends** [comment]
No it had a typo in as it was lazli not lazuli see https://github.com/aidancbrady/Mekanism/blob/1.10/src/main/resources/assets/mekanism/lang/en_US.lang#L1114

**Comment by MJRLegends** [comment]
And the the double entrys look at lines 1046 and 1106

**Comment by MJRLegends** [comment]
I believe this is fixed though
