### ISSUE TITLE
[Infinity Lite 1.10] Industrial Turbine doesn't get any steam also if it's connected

### ISSUE THREAD

**Issue by realblaupilz** [aidancbrady/Mekanism#4576]
As the title says, I'm having an issue with getting steam into my Industrial Turbine. I tested it in Creative Mode to make sure to not run out of steam I would produce with an 7x7x46 Extreme Reactor in my original world. (producing 16.9b/t)

http://prntscr.com/g1nyx7

So the UI was telling me "Empty" ._.

http://prntscr.com/g1nzcg
http://prntscr.com/g1o07y

I don't really know how to continue.. I tested using Saturating Condenser above the Pressure Dispurser -> nothing happened too

EDIT: Using UMP didn't help aswell

**Comment by thiakil** [comment]
Please follow the issue template and specify your versions.

**Comment by aidancbrady** [comment]
Sounds related to #3301

**Comment by Frankeinst** [comment]
How do you put water in this reactor and extract the steam?
