### ISSUE TITLE
[Suggestion(?)] Have all machines to have their own individual Item IDs for proper mod compatibility

### ISSUE THREAD

**Issue by Gamemaster2198** [aidancbrady/Mekanism#4577]
I think the machines should have their own individual item ids because items like Builder's wands from other mods (ex. ExtraUtils2) would do something like placing a basic induction matrix instead of an ultimate induction matrix. If possible, please do this suggestion in a future update.

**Comment by thiakil** [comment]
If another mod is not placing the block correctly, that's their bug. Variants sharing a blockid is quite common.
