### ISSUE TITLE
Mekanism Generators Crash

### ISSUE THREAD

**Issue by GaterG10** [aidancbrady/Mekanism#4578]
I've looked all over and couldn't find what was wrong. Every time i add Mekanism Generators to my mod list it crashes my game when its at "6/7 Finishing Up".  I am on V9 and everything is fully updated.
 My Mod List: 
https://user-images.githubusercontent.com/30562911/28750330-763e93e0-74b5-11e7-8271-8c01a7026ca9.png

My Crash Report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.11.2-4.0.0.114.jar)
  SFRCore (SolarFluxReborn_1.11.2-2.21r.jar)
  CreativePatchingLoader (CreativeCore-1.11.2-Universal.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-3.0.0.284-universal.jar)
  BCModPlugin (Backpacks-Mod-by-Brad16840-1.11.2.jar)
  LittlePatchingLoader (LittleTiles-Mod-1.11.2.jar)
  LittleLatePatchingLoader (LittleTilesCore-v1.0.0.jar)
  CTMCorePlugin (CTM-MC1.11.2-0.2.0.8.jar)
  NEICorePlugin (NotEnoughItems-1.11.2-2.3.0.227-universal.jar)
  HammerCoreCore (HammerCore_1.11.2-1.8.9.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  CoFH Loading Plugin (CoFHCore-1.11.2-4.2.7.15-universal.jar)
  LoadingPlugin (Bloodmoon-MC1.11-1.5.1.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 7/29/17 11:05 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MekanismGenerators (mekanismgenerators)
Caused by: java.lang.NoSuchMethodError: buildcraft.api.fuels.IFuel.getFluid()Lnet/minecraftforge/fluids/FluidStack;
	at mekanism.generators.common.MekanismGenerators.postInit(MekanismGenerators.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:647)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:833)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:357)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:521)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1369719816 bytes (1306 MB) / 3005198336 bytes (2865 MB) up to 6429081600 bytes (6131 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.1.2386 Optifine OptiFine_1.11.2_HD_U_C3 73 mods loaded, 73 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2386.jar) 
	UCHIJ	forge{13.20.1.2386} [Minecraft Forge] (forge-1.11.2-13.20.1.2386.jar) 
	UCHIJ	backpacks16840{3.1.9} [Backpacks!] (Backpacks-Mod-by-Brad16840-1.11.2.jar) 
	UCHIJ	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCHIJ	littletilescore{1.0.0} [LittleTilesCore] (minecraft.jar) 
	UCHIJ	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJ	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJ	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.11.2-3.0.0.284-universal.jar) 
	UCHIJ	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJ	actuallyadditions{1.11.2-r110} [Actually Additions] (ActuallyAdditions-1.11.2-r110.jar) 
	UCHIJ	advancedcombat{1.0.1} [Advanced Combat] (Advanced-Swords-Mod-1.11.2.jar) 
	UCHIJ	bibliocraft{2.3.2} [BiblioCraft] (BiblioCraft[v2.3.2][MC1.11.2].jar) 
	UCHIJ	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon-MC1.11-1.5.1.jar) 
	UCHIJ	buildcraftlib{7.99.4} [BuildCraft Lib] (buildcraft-7.99.4.jar) 
	UCHIJ	buildcraftcore{7.99.4} [BuildCraft] (buildcraft-7.99.4.jar) 
	UCHIJ	buildcraftfactory{7.99.4} [BC Factory] (buildcraft-7.99.4.jar) 
	UCHIJ	buildcrafttransport{7.99.4} [BC Transport] (buildcraft-7.99.4.jar) 
	UCHIJ	buildcraftbuilders{7.99.4} [BC Builders] (buildcraft-7.99.4.jar) 
	UCHIJ	buildcraftenergy{7.99.4} [BC Energy] (buildcraft-7.99.4.jar) 
	UCHIJ	buildcraftrobotics{7.99.4} [BC Robotics] (buildcraft-7.99.4.jar) 
	UCHIJ	buildcraftsilicon{7.99.4} [BC Silicon] (buildcraft-7.99.4.jar) 
	UCHIJ	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.11.2.jar) 
	UCHIJ	chisel{MC1.11.2-0.0.13.22} [Chisel] (Chisel-MC1.11.2-0.0.13.22.jar) 
	UCHIJ	codechickenlib{3.0.0.284} [CodeChicken Lib] (CodeChickenLib-1.11.2-3.0.0.284-universal.jar) 
	UCHIJ	cofhcore{4.2.7} [CoFH Core] (CoFHCore-1.11.2-4.2.7.15-universal.jar) 
	UCHIJ	creativecore{1.7.4} [CreativeCore] (CreativeCore-1.11.2-Universal.jar) 
	UCHIJ	ctm{MC1.11.2-0.2.0.8} [CTM] (CTM-MC1.11.2-0.2.0.8.jar) 
	UCHIJ	customnpcs{1.11.2} [CustomNPCs] (CustomNPCs_1.11.2(25may17).jar) 
	UCHIJ	ptrmodellib{1.0.0} [ptrmodellib] (Decocraft-2.4.2_1.11.2.jar) 
	UCHIJ	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.11.2.jar) 
	UCHIJ	emvi{2.2} [Emergent Villages] (EmergentVillages-2.2.jar) 
	UCHIJ	enderstorage{1.0} [EnderStorage] (EnderStorage-1.11.2-2.3.1.116-universal.jar) 
	UCHIJ	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.5.jar) 
	UCHIJ	zerocore{1.11.2-0.1.0.6} [Zero CORE] (zerocore-1.11.2-0.1.0.6.jar) 
	UCHIJ	bigreactors{1.11.2-0.4.5.30} [Extreme Reactors] (ExtremeReactors-1.11.2-0.4.5.30.jar) 
	UCHIJ	fairylights{2.1.0} [Fairy Lights] (fairylights-2.1.0-1.11.2.jar) 
	UCHIJ	felling{1.1} [Felling] (felling-1.1.jar) 
	UCHIJ	galacticraftcore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.11.2-4.0.0.114.jar) 
	UCHIJ	galacticraftplanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.11.2-4.0.0.114.jar) 
	UCHIJ	hammercore{1.8.9} [Hammer Core] (HammerCore_1.11.2-1.8.9.jar) 
	UCHIJ	jei{4.5.0.291} [Just Enough Items] (jei_1.11.2-4.5.0.291.jar) 
	UCHIJ	immersiveengineering{0.11-63} [Immersive Engineering] (ImmersiveEngineering-0.11-63.jar) 
	UCHIJ	inventorypets{1.4.9.7} [Inventory Pets] (inventorypets-1.11.2-1.4.9.7.jar) 
	UCHIJ	inventorytweaks{1.62+release.90.40cf8fc} [Inventory Tweaks] (InventoryTweaks-1.62.jar) 
	UCHIJ	journeymap{1.11.2-5.4.1} [JourneyMap] (journeymap-1.11.2-5.4.1.jar) 
	UCHIJ	littletiles{1.4.8} [LittleTiles] (LittleTiles-Mod-1.11.2.jar) 
	UCHIJ	lunatriuscore{1.1.2.39} [LunatriusCore] (LunatriusCore-1.11-1.1.2.39-universal.jar) 
	UCHIJ	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCHIJ	mcmultipart{2.0.2} [MCMultiPart] (MCMultiPart-2.0.2.jar) 
	UCHIJ	mekanism{9.3.3} [Mekanism] (Mekanism-1.11.2-9.3.3.311-fix.jar) 
	UCHIE	mekanismgenerators{9.3.3} [MekanismGenerators] (MekanismGenerators-1.11.2-9.3.3.311.jar) 
	UCHIJ	mekanismtools{9.3.3} [MekanismTools] (MekanismTools-1.11.2-9.3.3.311.jar) 
	UCHIJ	metamorph{1.1} [Metamorph] (Metamorph-1.11.2.jar) 
	UCHIJ	mobends{0.24} [Mo'Bends] (mobends-0.24_for_MC-1.11.2.jar) 
	UCHIJ	nei{${mod_version}} [Not Enough Items] (NotEnoughItems-1.11.2-2.3.0.227-universal.jar) 
	UCHIJ	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2h.jar) 
	UCHIJ	projecte{1.11.2-PE1.0.0B} [ProjectE] (ProjectE-1.11.2-PE1.0.0B.jar) 
	UCHIJ	refinedstorage{1.4.20} [Refined Storage] (refinedstorage-1.4.20.jar) 
	UCHIJ	roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.6.jar) 
	UCHIJ	roughmobs{1.0} [Rough Mobs] (roughMobs1.0.11-1.11.2.jar) 
	UCHIJ	schematica{1.7.8.161} [Schematica] (Schematica-1.11-1.7.8.161-universal.jar) 
	UCHIJ	simplegrinder{3.122.R1112} [Simple Grinder] (SimpleGrinder-3.140.R11112.jar) 
	UCHIJ	solarfluxreborn{2.21r} [Solar Flux Reborn] (SolarFluxReborn_1.11.2-2.21r.jar) 
	UCHIJ	thermalfoundation{2.2.5} [Thermal Foundation] (ThermalFoundation-1.11.2-2.2.5.16-universal.jar) 
	UCHIJ	thermalexpansion{5.2.6} [Thermal Expansion] (ThermalExpansion-1.11.2-5.2.6.21-universal.jar) 
	UCHIJ	veinminer{0.38.1} [Vein Miner] (VeinMiner-1.11-0.38.1.635+dc28c7d.jar) 
	UCHIJ	veinminermodsupport{0.38.1} [Mod Support] (VeinMiner-1.11-0.38.1.635+dc28c7d.jar) 
	UCHIJ	vending{1.4.3.1} [Vending] (vending-1.11.2-1.4.3.1.jar) 
	UCHIJ	wailaharvestability{1.1.10} [Waila Harvestability] (Waila-Harvestability-Mod-1.11.2.jar) 
	UCHIJ	waila{1.7.1} [waila] (Waila-Mod-1.11.2.jar) 
	UCHIJ	wearablebackpacks{2.5.0} [Wearable Backpacks] (WearableBackpacks-1.11.2-2.5.0.jar) 
	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.11.2-4.0.0.114.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
SFRCore (SolarFluxReborn_1.11.2-2.21r.jar)
  com.pengu.solarfluxreborn.core.SFRSerializedTransformer
CreativePatchingLoader (CreativeCore-1.11.2-Universal.jar)
  com.creativemd.creativecore.core.CreativeCoreTransformer
CCLCorePlugin (CodeChickenLib-1.11.2-3.0.0.284-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
BCModPlugin (Backpacks-Mod-by-Brad16840-1.11.2.jar)
  brad16840.common.asm.ClassTransformer
LittlePatchingLoader (LittleTiles-Mod-1.11.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
LittleLatePatchingLoader (LittleTilesCore-v1.0.0.jar)
  com.creativemd.littletiles.LittleTilesLateTransformer
CTMCorePlugin (CTM-MC1.11.2-0.2.0.8.jar)
  team.chisel.ctm.client.asm.CTMTransformer
NEICorePlugin (NotEnoughItems-1.11.2-2.3.0.227-universal.jar)
  codechicken.nei.asm.NEITransformer
HammerCoreCore (HammerCore_1.11.2-1.8.9.jar)
  com.mrdimka.hammercore.asm.HammerCoreTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  invtweaks.forge.asm.ContainerTransformer
CoFH Loading Plugin (CoFHCore-1.11.2-4.2.7.15-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
LoadingPlugin (Bloodmoon-MC1.11-1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 384.76' Renderer: 'GeForce GTX 1050/PCIe/SSE2'
	codechickenlib Invalid Fingerprint Reports: - No invalid fingerprints.: 
	enderstorage Invalid Fingerprint Reports: - No invalid fingerprints.: 
	nei Invalid Fingerprint Reports: - No invalid fingerprints.: 
	OptiFine Version: OptiFine_1.11.2_HD_U_C3
	Render Distance Chunks: 6
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 384.76
	OpenGlRenderer: GeForce GTX 1050/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by thommy101** [comment]
Please update to the latest version of Mekanism and BuildCraft
