### ISSUE TITLE
ticking memory connection

### ISSUE THREAD

**Issue by ucaninek69** [aidancbrady/Mekanism#4580]
#### Issue description:when ı put a pipe or cable game crashing (ticking memory connection)
ı try other releases but there not initializing 
ı try to change java 

#### Version :
**Forge:** 1.7.10 - 10.13.4.1614 latest one
**Mekanism:** 1.7.10-9.1.0.281 latest one
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: 

[gist/pastebin
[crash-2017-07-30_17.28.45-server.txt](https://github.com/aidancbrady/Mekanism/files/1185741/crash-2017-07-30_17.28.45-server.txt)
[fml-client-latest.log.txt](https://github.com/aidancbrady/Mekanism/files/1185742/fml-client-latest.log.txt)

/etc link here]
/etc link here]

**Comment by thommy101** [comment]
Sorry but 1.7.10 isn't supported anymore.

**Comment by ktole1999** [comment]
Not sure what your pack requirements are for forge but i use these versions and i do not have issues. Might help, might not.

forge-1.7.10-10.13.4.1492-1.7.10
ForgeMultipart-1.7.10-1.2.0.345-universal
Mekanism-1.7.10-8.1.7.252
