### ISSUE TITLE
Fluid Tank dupe

### ISSUE THREAD

**Issue by Ar4093** [aidancbrady/Mekanism#4582]
#### Issue description:
The Mekanism fluid tanks dupe any fluid.

#### Steps to reproduce:
1. Place down a fluid tank (any tier)
2. Get any filled bucket (Tested: Water, Lava, Creosote Oil (Immersive Engineering), Molten Tin (Tinker's Construct)) and place it in the input slot of the Fluid Tank
3. The tank fills up, but the bucket is not emptied.

Note: This happens both on a server and in single-player.

#### Version (make sure you are on the latest version before reporting):
**Forge:** (1.10.2) 12.18.3.2254
**Mekanism:** (1.10.2) 9.2.2 (...9.2.2.final.jar)
**Other relevant version:** Modpack: Age of Engineering v. 1.0.4-1

**Comment by thommy101** [comment]
Please try version 9.2.2-fix3, should be fixed already.

**Comment by Ar4093** [comment]
Yeah, it's fixed there. Thanks.
