### ISSUE TITLE
[1.11.2 - version 9.3.2.307 - forge 13.20.1.2386 - modpack: Raxpack 2] Server crash

### ISSUE THREAD

**Issue by VallenFrostweaver** [aidancbrady/Mekanism#4583]
I wish I had more to go on but currently on a multiplayer server where a 5x ore production set up is located we are experiencing a crash. The server will run if this area is not loaded but once loaded it hangs and crashes. Here is the pastebin. I hope it is somewhat helpful as I have never seen results like this before in a crash report: https://pastebin.com/XGyBnqVe

**Comment by thommy101** [comment]
The crash you're having is not specific to Mekanism. Watchdog killed your server as it thought the server was locked up (`Description: Watching Server`).

Sometimes loading takes a long time for the server and the watchdogs triggers a shutdown. You can try to locate the source of the lag (can be anything) or increase the watchdog timer in the minecraft (or forge) configs.
