### ISSUE TITLE
Armored jetpack seems to have no armor

### ISSUE THREAD

**Issue by faeldray** [aidancbrady/Mekanism#4585]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Armored jetpack shows no armor in the tooltip nor does it so any armor above the toolbar. See the attached screenshot.

#### Steps to reproduce:
1. None, tooltip said no armor in JEI before I even made it.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 13.20.1.2386
**Mekanism:** 9.3.3.311-fix
**Other relevant version:** Minecraft 1.11.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

No crash logs but I can add just a regular log if that's helpful at all.

![20170731204611_1](https://user-images.githubusercontent.com/967709/28810894-beb5d082-7651-11e7-86d9-ea328776ab8f.jpg)

**Comment by aidancbrady** [comment]
Can't reproduce this on my end, there's a good chance a mod is interfering with Forge's armor handling. I bet that the armor still functions as intended.

**Comment by craft90** [comment]
Same issue exist in All the Mods 3 modpack.

**Comment by cha0s** [comment]
Yep, this exists in ATM3.

**Comment by thiakil** [comment]
![954](https://user-images.githubusercontent.com/1788847/32482773-330a3660-c3d4-11e7-8ada-799b57ef10d2.png)

Please report to your pack maker if it does not absorb damage or to whatever mod adds the info to the tooltip. The jetpack does not use the extra 2 armor values provided by forge, just the vanilla damage absorption.
