### ISSUE TITLE
Formulaic Assemblicator deletes filled buckets

### ISSUE THREAD

**Issue by SuperFanatic** [aidancbrady/Mekanism#4586]
#### Issue description:
Crafting on the formulaic assemblicator with a filled bucket deletes the bucket rather than giving the empty bucket back.

#### Steps to reproduce:
1.Take a formulaic assemblicator
2.try crafting a cake
3.Boom, no more buckets

#### Version (make sure you are on the latest version before reporting):
**Forge: 13.20.0.2253** 
**Mekanism: 9.3.3.312** 
**Minecraft: 1.11.2**

**Comment by aidancbrady** [comment]
Fixed in 1.11.2 development
