### ISSUE TITLE
Ticking Block Entity Exception with Logistical Sorter Auto-Eject

### ISSUE THREAD

**Issue by PsyberMind** [aidancbrady/Mekanism#4589]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Logistical Sorter Auto Eject with no possible routes, Causes Ticking Exception - Crashes

#### Steps to reproduce:
1. Placed down Digital Miner with Logistical Sorter - Routed to Bins, Works as Intended
2. Placed Down more Bins, Default Route - Works as intended
3. Broke connection to bins, auto-eject - Crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.10.2-12.18.3.2185
**Mekanism:** 1.10.2-9.2.2-fix3
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/gE71aykr

**Comment by PsyberMind** [comment]
Have some more information after continued testing

As long as an item has somewhere to go, it works fine. I ran a 4x setup into basic bins, worked like a charm. I then filled a bin to capacity with an ingot, and as soon as I hit the capacity, it crashed, as there was no other route for the item to go to..

**Comment by thommy101** [comment]
Just a heads up to @PsyberMind: New Mekanism version has been released (1.10-9.2.3)
