### ISSUE TITLE
[1.11.2] DigitalMiner crash server

### ISSUE THREAD

**Issue by Misiek86pl** [aidancbrady/Mekanism#4590]
**Forge:*13.20.1.2425* 
**Mekanism:*1.11.2-9.3.3.312* 

CRASH:
https://pastebin.com/bsruvsqf

**Comment by thiakil** [comment]
Please use a code block (three backticks on own line) or pastebin/similar in future.

**Comment by aidancbrady** [comment]
Fixed in dev
