### ISSUE TITLE
Logistics Pipe not always piping items

### ISSUE THREAD

**Issue by Moobien** [aidancbrady/Mekanism#4591]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

Hey guys I am currently building a nice big factory complex that has multiple levels etc.  I have run into an issue where there is a routable path from my storage area to one of my Extreme Reactors, the logistical sorter on the Mekanism bin is set to output items painted yellow and the reactor's input is painted yellow.  I am noticing that the yellorium ingots are not being piped out of the storage to go to the reactor.

#### Steps to reproduce:
Please refer to screenshots for this.

#### Version (make sure you are on the latest version before reporting):
Forge: 1.11.2-13.20.0.2296

Modlist:

bdlib-1.13.2.7-mc1.11.2.jar
BiomesOPlenty-1.11.2-6.2.0.2267-universal.jar
Bookshelf-API-1.11.2-5.0.0-B96.jar
buildcraft-7.99.6.jar
ChunkAnimator-MC1.11-1.2.jar
CodeChickenLib-1.11.2-3.0.0.284-universal.jar
compatlayer-1.11.2-0.2.5.jar
CyclopsCore-1.11.2-0.10.7.jar
Damage-Indicator-1.11.2.jar
DynamicLights-1.11.2.jar
ExtremeReactors-1.11.2-0.4.5.30.jar
FTBLib-1.1x-3.6.5.jar
Futurepack-1.11.2-25.2.124.jar
Galacticraft-Planets-1.11.2-4.0.0.114.jar
GalacticraftCore-1.11.2-4.0.0.114.jar
Hopper-Ducts-1.11.2.jar
[ic2]
industrialcraft-2-2.7.81-ex111.jar
jei_1.11.2-4.5.0.295.jar
malisiscore-1.11.2-5.0.1.jar
MalisisDoors-1.11.2.jar
malisisswitches-1.11.2-4.0.0.jar
mcjtylib-1.1x-2.3.11.jar
Mekanism-1.11.2-9.3.3.311-fix.jar
MekanismGenerators-1.11.2-9.3.3.311.jar
MekanismTools-1.11.2-9.3.3.311.jar
MicdoodleCore-1.11.2-4.0.0.114.jar
omlib-1.11.2-3.0.0-114.jar
openmodularturrets-1.10.2-3.0.0-189.jar
OverworldQuartzGen-1.0.0.jar
Pressure-Pipes-1.11.2.jar
RebornCore-1.11.2-2.11.4.2-universal.jar
[resources]
RoguelikeDungeons-1.11.2-1.6.6.jar
Ruins-1.11.2.jar
ShadowMC-1.11.2-3.7.5.jar
SpacePackExtended-1.11-2.1.22-beta.jar
StevesCarts-1.11.2-2.3.0.22.jar
Thutcore-1.11.2.jar
thuttech-5.0.0.c.jar
toroquest-1.11.2-3.4.jar
TreeChopper-1.11.2-1.1.2.jar
UniDict-1.11.2-Universal.jar
VeinMiner-1.11-0.35.3.605+dad98e1.jar
VillageInfoSSP-1.11-2.1.jar
WanionLib-1.11.2-1.0.jar
Xaeros_Minimap_1.12.9_Forge_1.11.jar
[XaeroWaypoints]
YABBA-1.11.2-0.5.1.jar
zerocore-1.11.2-0.1.0.6.jar

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
Please check the 'chat' section in the screenshots to see my commentary on what you are seeing etc
http://imgur.com/a/qiduJ

[gist/pastebin/etc link here]

**Comment by aidancbrady** [comment]
Should be fixed in v9.3.4.
