### ISSUE TITLE
[1.10.2] Dupe glitch when Refined Storage importers are connected directly to entangloporters

### ISSUE THREAD

**Issue by Scrumdiddly32** [aidancbrady/Mekanism#4592]
#### Issue description:
Transmitted items are duplicated when Refined Storage importers are connected directly to Mekanism entangloporters.

#### Steps to reproduce:
1. Set up chest and pipe/conduit/duct to transfer any item into a Mekanism entangloporter that is configured to send items.
2. Second entangloporter set to receive items.
3. RS importer attached directly to the second entangloporter.
4. Send any item through via the chest, and the grid should show massive duping of that item.
5. The item appears to remain in the entangloporter's item buffer, even though it's accepted into the RS system.

Issue occurs on a server running All the Mods 1, v3.01.
I've been told this is likely a Mekanism issue, rather than an issue with Refined Storage.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 12.18.3.2422
**Mekanism:** 9.2.2.fix3
**Other relevant version:** Refined Storage 1.2.26

**Comment by thiakil** [comment]
Have you tried this with something other than RS? His "This is most likely a Mekanism issue." is completely conjectural (though not impossible). I have seen a report of a very similar dupe with AE2 & RS on 1.10

**Comment by Scrumdiddly32** [comment]
Yes, sorry. Forgot to mention that I tried with AE2 in place of RS, but connecting an AE2 import bus directly doesn't work at all - it just doesn't take the item.

I've also tried RS with dimensional transceivers from enderio, and there was no duping there.

**Comment by thiakil** [comment]
While there appears to be a bug in Mekanism, the dupe is caused because RS is technically doing it wrong - it inserts it into the network from only the *simulate* result.

**Comment by thiakil** [comment]
This is fixed in dev. You'll need to compile from source or wait until `1.10.2-9.2.2.fix4`
