### ISSUE TITLE
Render Problem?

### ISSUE THREAD

**Issue by themechman** [aidancbrady/Mekanism#4596]
Issue description:
I am having an odd rendering problems and I am trying to nail down which mod is doing it. Currently the following behavior is exhibited.

I go into the attic of my house which contains a single, Adv Solar array. This is connected via basic Mek power cables to an Adv Energy Cube.

If I look directly at it some times the solar panel will rotate random positions. The Cable will visibly still be connected and containing power. The cube will change to from the usual red texture to the green one.
![2017-08-04_22 55 48](https://user-images.githubusercontent.com/2990361/28992424-0bcdea2a-7969-11e7-9f76-058208109783.png)
If I rightclick the cube, the UI clearly shows that it is an adv cube. I exit the UI and it show the correct textures.
![2017-08-04_22 55 58](https://user-images.githubusercontent.com/2990361/28992429-53ef341c-7969-11e7-9673-0d2388581375.png)

Even HWYLA is confused by this!

While this is merely cosmetic, I hope it is not affecting actual operation. It happens on three diff PC's with varying hardware.

MC: 1.10.2
Forge: 12.18.3.2185
Mek: 9.2.2.301

Other mod versions:
1.10.2_deadly_monsters_1.5.jar
advgenerators-0.9.20.23-mc1.10.2.jar
ae2stuff-0.6.0.9-mc1.10.2.jar
appliedenergistics2-rv4-alpha-11.jar
AutoRegLib-1.0-2.jar
Baubles-1.10.2-1.3.11.jar
bdlib-1.12.4.24-mc1.10.2.jar
Botania r1.9-341.jar
Chameleon-1.10.2-2.3.0.jar
Chisel-MC1.10.2-0.0.11.26.jar
CodeChickenLib-1.10.2-2.5.9.267-universal.jar
CoFHCore-1.10.2-4.1.9.13-universal.jar
compatlayer-1.10-0.2.9.jar
CookingForBlockheads_1.10.2-4.2.45.jar
CTM-MC1.10.2-0.1.1.16.jar
cyberware-1.9.4-1.10.2-beta-0.2.10.jar
Decocraft-2.4.2_1.10.2.jar
ElevatorMod[V.1.3.0][MC.1.10.2].jar
EnderZoo-1.10-1.2.3.44.jar
Galacticraft-Planets-1.10.2-4.0.0.111.jar
GalacticraftCore-1.10.2-4.0.0.111.jar
GraveStone-1.10.2-Graves-1.0.6.jar
GraveStone-Extended-1.0.5.jar
Hwyla-1.8.17-B31_1.10.2.jar
InventoryTweaks-1.62-dev-66.jar
jei_1.10.2-3.14.7.420.jar
journeymap-1.10.2-5.4.7.jar
malisiscore-1.10.2-4.4.0.jar
malisisdoors-1.10.2-5.2.0.jar
malisisswitches-1.10.2-3.2.0.jar
Mantle-1.10.2-1.1.5.jar
MCMultiPart-1.4.0-universal.jar
Mekanism-1.10.2-9.2.2.301.jar
MekanismGenerators-1.10.2-9.2.2.301.jar
MicdoodleCore-1.10.2-4.0.0.111.jar
NetherPortalFix_1.10.2-3.3.4.jar
omlib-1.10.2-3.0.0-110.jar
ompd-1.10.2-3.0.0-22.jar
openmodularturrets-1.10.2-3.0.0-182.jar
Pam's HarvestCraft 1.10.2j.jar
PersistentBits-1.10.2-1.0.6.jar
plustic-5.2.0.0.jar
ServerTickMonitor-1.9.4-1.1.0.jar
special_ai-1.10.2-1.1.3.jar
StorageDrawers-1.10.2-3.7.10.jar
TConstruct-1.10.2-2.6.5.jar
ThermalDynamics-1.10.2-2.0.9.12-universal.jar
ThermalExpansion-1.10.2-5.1.8.16-universal.jar
ThermalFoundation-1.10.2-2.1.4.8-universal.jar
TickDynamic-1.10.2-1.0.0.jar
Tinkers Addons-1.10.x-1.0.3.jar
TinkerToolLeveling-1.10.2-1.0.1.jar
WIRED-1.7.0.jar

**Comment by thommy101** [comment]
Please update to the latest version of Mekanism.

**Comment by themechman** [comment]
Will give that a whirl.

**Comment by aidancbrady** [comment]
Yes, this is a bug that was fixed in a later version.
