### ISSUE TITLE
Problem with Induction Matrix

### ISSUE THREAD

**Issue by MelanX** [aidancbrady/Mekanism#4597]
#### Issue description:
I have built an Induction Matrix 10x10x10 and there are 10 Ultimate Providers and 11 Ultimate Induction Cells. I have a Fusion Reactor with Injection Rate 6 in a Dessert RFTools dimension. The reactor produces ~600kRF/t. Everything is chunkloaded. With Flux Plug I send the energy to the Induction Matrix. It only stores 2.14GRF and then input rate=output rate. I breaked all Induction Cells and only one stored this energy. This one I left outside and then another cell stored the incoming energy until 2.14GRF. Then I put this cell I left outside in the Induction Matrix and the internal storage was at 4.28GRF but no input. At 2.14GRF the input rate=outout rate.
Reactor to Matrix and Matrix to every machine have their own 'channel' at Flux Networks.
Problem found in my modpack and rebuilt only with Flux Networks and Mekanism.

#### Steps to reproduce:
1. Build a 10x10x10 Induction Matrix with 10 Ultimate Providers/Induction Cells
2. Build a Fusion Reactor and start it
3. Connect Flux Point/Plug
4. Wait until 2.14GRF

#### Version (make sure you are on the latest version before reporting):
**Minecraft:** 1.10.2
**Forge:** 12.18.3.2422
**Mekanism:** 9.2.2.fix3
**Other relevant version:** Mekanism Generators and Tools 9.2.2.fix3
MCMultiPart 1.4.0
Sonar Core (required for Flux Networks) 3.2.8
Flux Networks 1.2.5

[test world.zip](https://github.com/aidancbrady/Mekanism/files/1202342/test.world.zip)
That's the world I tested in with Mods you can see above.

**Comment by thiakil** [comment]
Can you insert further power with something other than Flux Networks? If so, that's a FN bug.

We recently changed our API, and Flux Networks code which uses it needs to update.

**Comment by thommy101** [comment]
2.14G is exactly the MAX_INT value (2,147,483,647). FN probably uses Forge Energy or RF as that's the limit of those methods. Tesla uses long (9,223,372,036,854,775,807) for their energy storage values.

**Comment by MelanX** [comment]
Yes, with other mods it's fine. Then I go and report to Flux Networks :D Thank you for help!

**Comment by thommy101** [comment]
Well... It not charging beyond 2.14G isn't something they could change easily. There might be a way we could change it, but I'm not 100% certain about it.

**Comment by thiakil** [comment]
@thommy101 they were using the API we removed, so maybe they're checking its capacity, and as far as ints are concerned, its at max.

**Comment by thommy101** [comment]
Aaah, that sound plausible, was just checking if one of the RF/Forge Energy methods where limiting on MAX_INT as max storage (instead of working around the int limit as it supports more than that)
