### ISSUE TITLE
Personal Chest not working

### ISSUE THREAD

**Issue by Antilie** [aidancbrady/Mekanism#4598]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I can't move items from or to a personal chest while using it in my inventory.

#### Steps to reproduce:
1. Open a personal chest in your inventory

#### Version (make sure you are on the latest version before reporting):
**Forge: 13.20.1.2386**
**Mekanism: 9.3.3.311**
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thommy101** [comment]
Please update to the latest version of Mekanism.
