### ISSUE TITLE
OC integration problems

### ISSUE THREAD

**Issue by tacnuke** [aidancbrady/Mekanism#4603]
under open-computers 1.7.0.40  m.c. version 1.11.2 the fusion reactor, induction matrix, energy cubes, and laser amplifier all show up as energy_device when you pull a components list when they are attached by an adapter(which is required)

**Comment by thiakil** [comment]
Do you have any OpenComputers addons installed? Such as something that lets your read RF capacity?

**Comment by thommy101** [comment]
It's probably due to the fact that we haven't changed the ModID of OpenComputers, it's now lowercased to `opencomputers`. In the code we still use the old `OpenComputers`.
Used in Mekanism.java & MekanismHooks.java

_(currently not able to open a PR)_

**Comment by thiakil** [comment]
I think Aidan fixed that in a recent commit (I'd forgotten about the modid thing). Not sure if it made it to release yet.

**Comment by thommy101** [comment]
Partially solved, in MekanismHooks it's lowercased, Mekanism not:
https://github.com/aidancbrady/Mekanism/blob/1.12/src/main/java/mekanism/common/Mekanism.java#L791

**Comment by thiakil** [comment]
Right you are as usual :P

**Comment by tacnuke** [comment]
ok would that also cause getEnergyStored() and getMaxEnergyStored() methods to have the same value?
the first method should be what is currently stored and the second obviously should be the max storable. and no the induction matrix is not full but getEnergyStored() pulls the max value.

**Comment by thommy101** [comment]
It could cause them to return the same value, as the "driver" needed to communicate isn't loaded and it falls back to a default one.

Should be fixed in the next release

**Comment by thiakil** [comment]
If it has more than `2,147,483,647RF` then it's likely a limitation of the Java data type ;)
