### ISSUE TITLE
Infinite Lava Fluid Tank

### ISSUE THREAD

**Issue by salomj** [aidancbrady/Mekanism#4604]
#### Issue description:
If you use a Minecraft bucket filled with lava on a fluid tank, in my case an Advanced Fluid Tank, you can glitch it to give you infinite lava.

#### Expected Results:
Lava bucket should empty and fill tank with 1,000mB of Lava.

#### Steps to reproduce:
1. Take a Bucket filled with Lava
2. Place a Fluid Tank
3. Put the bucket in the "Input" slot of the fluid tank
4. The fluid tank fills up without emptying the bucket
5. Fluid tank becomes full
6. Filled lava bucket is then placed in "Output"

#### Version:
Minecraft: 1.10.2
Forge: 12.18.3.2281
Mekanism 1.10.2 9.2.2 FINAL
ATLauncher 3.2.3.7
Resonant Rise: 4.3.0.0-b

**Comment by thommy101** [comment]
Please update to the latest version of Mekanism, is fixed in 9.2.2FINAL-fix3
