### ISSUE TITLE
Thermodynamic conductors reverting to basic version on chunk unload

### ISSUE THREAD

**Issue by PsionicArchon** [aidancbrady/Mekanism#4605]
Forge: 2429

Mekanism: 9.3.3.311-fix

Steps to reproduce:

Place any higher tier thermodynamic conductor into the world. 

Unload the chunk.

Reload the chunk/restart the server.

They will have swapped back to their basic version.

Has anyone else encountered this bug? Does it happen with other mekanism pipes?

I'll have to put upgrading my steam boiler on hold for the time being.

**Comment by PsionicArchon** [comment]
Fired up your new release, still broken. Honestly, not sure how this one's flying under the radar.

**Comment by aidancbrady** [comment]
Haha you're right, this is pretty major. Somehow I forgot to save the tier on chunk load/unload back when I first ported to 1.11. The fix is just two lines of code and I'll get it done right in the morning for 1.11 and 1.12.

**Comment by PsionicArchon** [comment]
Cool beans, no worries man it happens :)

**Comment by thommy101** [comment]
Fixed in a4958ae8c96905bf9151b1898b35a3cad024731c for 1.11 and 1.12(.1). Will be available in the next release :)
