### ISSUE TITLE
Quantum Entangloporter transfer rate reduced from infinite to 20,000 rf/t

### ISSUE THREAD

**Issue by PsionicArchon** [aidancbrady/Mekanism#4606]
Versions:
Forge: 2429
Mekanism: 9.3.4.313

I updated to the newest version of Mekanism and my entire power grid went down.

Entangloporters are maxing out at 20,000 rf/t, roughly what the ultimate energy cube outputs.

Was this a nerf or an unintended side effect of this commit: https://github.com/aidancbrady/Mekanism/commit/7b3f4e8e2aa88820920bd7e697966a6309618a36

**Comment by thommy101** [comment]
That's indeed quite a nerf of the max output.. I don't think that was supposed..

The old value was: 1.000.000, the current value is 51.200.
The old value will return ;)

**Comment by PsionicArchon** [comment]
Two fixes in one night, thanks guys.

**Comment by thommy101** [comment]
Well.. I wouldn't call it one night ;) For some it's already morning

**Comment by thiakil** [comment]
or afternoon ;)

**Comment by PsionicArchon** [comment]
Damn, it is already three in the morning. Fusion reactor > sleep > life, I guess.

**Comment by thommy101** [comment]
Long live timezones!

**Comment by thommy101** [comment]
Fixed in a4958ae8c96905bf9151b1898b35a3cad024731c for 1.11 and 1.12(.1). Will be available in the next release :)
