### ISSUE TITLE
Fusion reactor sets fuel to 0 after a restart

### ISSUE THREAD

**Issue by Galadriel1640** [aidancbrady/Mekanism#4609]
This issue has popped up a few times in the issues but i couldn't find any resolved ones...

After every restart, whether I use a chunkloader or not, my fusion reactor sets its fuel usage to 0 without fail.  This is 1.7.10 and I cannot find a config option for this anywhere either.  I know I am not running out of fuel because my towers and electrolytic separator are always full, along with the respective pipes.  It is just the reactor itself resets fuel to 0.  I also noticed that it resets my power type (rf, j, etc.) but i assume it is just going back to the default.

#### Steps to reproduce:
1. Install the latest stable mekanism version for 1.7.10 
2. Turn on the server (we use thermos 1.7.10)
3. Set up a reactor and its fuel supplies.
4. Restart the server; do not just turn it off then back on, do an actual restart.

#### Version (make sure you are on the latest version before reporting):
**1.7.10, version 1614** 
**Latest mekanism for 1.7.10:**

**Comment by thiakil** [comment]
We don't generally support 1.7.10 any longer
