### ISSUE TITLE
Cant load into singleplayer world

### ISSUE THREAD

**Issue by Breadabix** [aidancbrady/Mekanism#4611]
I am unable to load into a singleplayer world, and I dont know if its the same for multiplayer or not. I have deleted all minetweaker scripts, reinstalled Mekanism, and I am out of ideas. I dont know what logs/files would be needed, so could someone please comment what is needed to help determine the cause of the issue.

As for reproducing it I have no idea, I have this issue on a modpack I hope to release, and I have done alot of fiddling over the last couple of days. I can only say that the issue no longer exists without Mekanism.

Forge: 10.13.4.1614
Mekanism: 1.7.10-9.1.0.281
Other relevant version: ? (someone please comment if anything is needed here)

**Comment by thiakil** [comment]
If it actually crashed, there should be a crash log in `<instance folder>/crash-reports`, otherwise `logs/latest.log`

Aside from that, support/updates for 1.7 have long since ceased.
