### ISSUE TITLE
Fusion reactor does output power not as it should

### ISSUE THREAD

**Issue by Nico8400** [aidancbrady/Mekanism#4612]
Issue description:

In my survival world my fusion reactor won't output the amount of energy it should(I'm using redstone flux) the rector tell me that it produce 9.8 M rf/t but it outputs only 2 or 3 M. It use D-T fuel + tritium and deuterium combo with good buffers and good production (all buffers are always full).
I use draconic evolution to transfer the energy (20M rf/t is the maxiumum transfer rate) it has a separated channel from the reactor to the energy storage (again using draconic evolution).
This issue does not happen is my creative test world with almost the same config.

#### Steps to reproduce:
1. Create a fusion reactor
2. Provide all 3 fuel possible with a double D-T fuel input
3. Use top tier draconic evolution energy setup to transfer the enerygy to the energy storage

#### Version (make sure you are on the latest version before reporting):
**Forge: 12.18.3.2254
**Mekanism: Mekanism-1.10.2-9.2.3.97
**Other relevant version: Draconic-Evolution-1.10.2-2.1.3.256-universal
                                        BrandonsCore-1.10.2-2.1.10.122-universal

No crash log

Video: https://www.youtube.com/watch?v=h6xkKT3WJC0

**Comment by thiakil** [comment]
at [0:41](https://youtu.be/h6xkKT3WJC0?t=41) TOP is showing the Energy Pylon at full capacity. Are you sure that's not the bottleneck? (I don't know DE well)

**Comment by Nico8400** [comment]
The energy pylon is aslo full in my test world.
I tired to connect the reactor to an induction matrice (still using DE crystals) and the output was correct.
Now I will report this issue to the DE dev and I think that for now I will use the induction matrice to store the energy of the reactor.
