### ISSUE TITLE
CTM is broken

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [aidancbrady/Mekanism#4615]
![2017-08-11_20 40 04](https://user-images.githubusercontent.com/20567492/29213461-ecd825c8-7ed5-11e7-8898-72427bc130ed.png)
I just update my mekanism to new versions.
**Forge:1.11.2-13.20.1.2429
**Mekanism:9.3.4.313

**Comment by thommy101** [comment]
That would be correct, it's not documented (yet), but we've added an optional dependency on CTM (https://minecraft.curseforge.com/projects/ctm) which would handle the new connected textures as the old code was quite hacky and needed an update as it caused some errors (visible and invisible).

**Comment by mgdgfbhevdyeh** [comment]
ok cool thanks!
