### ISSUE TITLE
[1.12] [9.4.0.318] Jetpack fall damage adding up

### ISSUE THREAD

**Issue by Kris1432** [aidancbrady/Mekanism#4616]
Issue description:

Jetpack adding up all the air time as fall damage.

Steps to reproduce:
1. Get A Jetpack
2. Fly in the air for a bit
3. Drop nearly all the way and then drop a tiny bit and the damage all mounts up.

Forge: 2443
Mekanism: 9.4.0.318

**Comment by Kris1432** [comment]
what logfile would you like?

**Comment by thommy101** [comment]
Fml-client-latest.log would do, it contains all the information to help us :)

**Comment by Kris1432** [comment]
alright, i'll reproduce it asap and get you the log!

**Comment by thommy101** [comment]
Thanks

**Comment by Kris1432** [comment]
https://www.dropbox.com/s/11zb2toeeqw9ge9/fml-client-latest.log?dl=0

**Comment by thommy101** [comment]
Thanks for providing the log!

**Comment by thommy101** [comment]
Can confirm there's a "slight" desync issue :) Client does know about the new falldistance, server sadly doesn't know about it... So it might be related to #3805 after all

**Comment by aidancbrady** [comment]
Merging with #3805
