### ISSUE TITLE
[1.12]Item pipe  config"TransporterPullAmount" is broken

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [aidancbrady/Mekanism#4617]
Because of the individual needs, I try to change the configuration file for the item pipe
![2017-08-12_11 03 24](https://user-images.githubusercontent.com/20567492/29237332-e2f5afd4-7f4e-11e7-8037-fc1ef109cedf.png)
`I:UltimateTransporterPullAmount=320
I:UltimateTransporterSpeed=50`
![2017-08-12_11 05 43](https://user-images.githubusercontent.com/20567492/29237333-e303c894-7f4e-11e7-9b76-925e00d4647b.png)
But the pump rate still is  the default
#### Version (make sure you are on the latest version before reporting):
**Forge:1.12 latest
**Mekanism:latest
**Other relevant version:some isseus in 1.11

**Comment by thommy101** [comment]
Can confirm this is affecting 1.12 (haven't tested other versions)

Analysis:
`Tier#loadConfig` isn't called on first load, only on world left.
This causes the config sync `Tier#readConfig` and `Tier#writeConfig` syncing the default values.

(SingelPlayer) Try and join a world, old default values. Rejoin world, new values apply.
Also setting an value of >64 for pullamount has no result, as it looks like it only looks for 1 full stack to transport.
