### ISSUE TITLE
[1.10.2]Energy Cube can't receive EU from IC2 generator

### ISSUE THREAD

**Issue by Ariados-Z** [aidancbrady/Mekanism#4618]
#### Issue description:
Energy Cube cannot get the power generated by IC2 generator

I've tried:
- Config the input/output sides. Not work.
- Put energy cube next to the IC2 generator. Not work.
- Connect them with different tier of IC2 cable. Not work.
- Put an IC2 transformer between them. Not work.
- Put the energy cube INTO the generator, charge it as an item. This works. (?????)
- Put IC2 battery INTO energy cube to discharge it. This works.

However the energy cube can output EU without problem

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge1.10.2-12.18.3.2281
**Mekanism:** Mekanism-1.10.2-9.2.3.97
**Other relevant version:** industrialcraft-2-2.6.252-ex110

In an old version with Mekanism-1.10.2-9.2.2.83 and industrialcraft-2-2.6.188-ex110, energy cube can receive EU from IC2.
Something changed?

**Comment by thiakil** [comment]
Do the IC2 cables *look* connected to the cube?

**Comment by Ariados-Z** [comment]
Yes, they do connect

**Comment by aidancbrady** [comment]
IC2 support has been tested to work in 1.11 and 1.12. I'm happy to port back major fixes to 1.10, but as this is a compatibility issue for a 2-year-old Minecraft version, I'm going to mark this closed.
