### ISSUE TITLE
[1.10.2] Power use = Null after in-place factory upgrade

### ISSUE THREAD

**Issue by themechman** [aidancbrady/Mekanism#4622]
![2017-08-12_20 25 10](https://user-images.githubusercontent.com/2990361/29245097-5e19d90e-7f9c-11e7-9221-63be6a3b03dc.png)
I am able to stop machines such as enrichment chamber and energized smelter from using energy by simply upgrading them while they are operating. The internal power buffer indicates no charge and power tab on lower left shows no consumption. Cube does not drain despite work being performed.

Removed cable and was still able to process items

Breaking and replacing machine corrects this action.

Mek 9.2.2 [Fix3]

**Comment by thiakil** [comment]
> despite work being performed.

So to confirm, the processing is being done, but no power is being used?

**Comment by themechman** [comment]
Correct. That screenshot is it, doing work with no power consumption.

I was going to double confirm that in a separate environment.

**Comment by themechman** [comment]
Confirmed this is happening on fix3. I have taken them in sequence.

![2017-08-13_09 37 20](https://user-images.githubusercontent.com/2990361/29250149-5ac29d08-800b-11e7-98b4-5f45bb4113c0.png)
![2017-08-13_09 37 27](https://user-images.githubusercontent.com/2990361/29250148-5ac29952-800b-11e7-9a08-406c7a3ce618.png)
![2017-08-13_09 37 36](https://user-images.githubusercontent.com/2990361/29250146-5abce4bc-800b-11e7-9f6f-ba691e31e779.png)
![2017-08-13_09 37 51](https://user-images.githubusercontent.com/2990361/29250144-5abc88dc-800b-11e7-9419-87af9e63989a.png)
![2017-08-13_09 37 55](https://user-images.githubusercontent.com/2990361/29250145-5abca038-800b-11e7-8dae-2ce3c8a4a4cc.png)
![2017-08-13_09 38 21](https://user-images.githubusercontent.com/2990361/29250147-5abd3458-800b-11e7-999e-b228ad425917.png)
![2017-08-13_09 38 24](https://user-images.githubusercontent.com/2990361/29250151-5ac5bd9e-800b-11e7-893d-569e2e0eaca9.png)
![2017-08-13_09 38 28](https://user-images.githubusercontent.com/2990361/29250150-5ac5a368-800b-11e7-8626-08cc35509c6a.png)

Sorry, I ment to show the lack of cable on the last three images.
If you apply the next tier upgrade (Basic to Advanced) while it is in this condition, it will fix itself.

**Comment by themechman** [comment]
Confirmed this is still happening with latest release.

![2017-08-13_09 47 04](https://user-images.githubusercontent.com/2990361/29250226-a8c72a36-800c-11e7-94a8-3825baf14e32.png)
![2017-08-13_09 47 07](https://user-images.githubusercontent.com/2990361/29250224-a8c2919c-800c-11e7-9ec5-6037798aa80a.png)
![2017-08-13_09 47 10](https://user-images.githubusercontent.com/2990361/29250228-a8cb9710-800c-11e7-80e6-861464bf360b.png)

You can see power being consumed from cube pre-upgrade.
I perform basic tier upgrade and break cable at this point.

![2017-08-13_09 48 20](https://user-images.githubusercontent.com/2990361/29250223-a8c2aede-800c-11e7-9661-da91385f3305.png)
![2017-08-13_09 48 23](https://user-images.githubusercontent.com/2990361/29250222-a8c278b0-800c-11e7-852f-fbd6e5744f61.png)
![2017-08-13_09 48 30](https://user-images.githubusercontent.com/2990361/29250225-a8c353c0-800c-11e7-93d1-d1a180ad1695.png)
![2017-08-13_09 48 34](https://user-images.githubusercontent.com/2990361/29250227-a8ca9202-800c-11e7-833b-3ac6565e0bb3.png)

**Comment by thommy101** [comment]
Cannot confirm in latest 1.12 (so it might be a 1.10 only issue).
I remember some fixes to factories and their energy usages.. */me is looking through commit history*

**Comment by aidancbrady** [comment]
Now that 1.12 is supported I'm going to phase out 1.10 for minor fixes.

**Comment by icyevilfantasy** [comment]
Any News/Fix on that issue? Or any workaround?

i've play atm in SMP and it seems that the order is important.

if i take the energy-upgrades (8x) first and the speed-upgrades (8x) second > the energy usage is extremly high

if i take the speed-upgrades (8x) first and the energy-upgrades (8x) second > the energy usage is extremly low

**Comment by thiakil** [comment]
Please read the above comment; this will not be fixed for 1.10
