### ISSUE TITLE
[1.12] Aluminum/Iridum/NoMansLib-Mithril/AA-Black-Quartz compatibility

### ISSUE THREAD

**Issue by llloyd4** [aidancbrady/Mekanism#4625]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

I setup two Elite Factories, a Enrichment Chamber and a Smelter, the one feeds into the other for basic ore doubling. So the Enrichment Chamber has no issues turning TD Aluminum and Iridum ore into two dust but it chokes at smelting it, the Elite Smelter refuses to accept it to turn them into ingots. The Elite Enrichment Chamber, on the other hand, refuses to take NoManLib's Mithril and Actually Additions Black Quartz Ore. I had to build a Pulverizer / Redstone Furnace setup *just* for those 4. 

#### Steps to reproduce:
1. Build an Enrichment Chamber and Smelter
2. Set them up so the Chamber auto ejects into the Smelter
3. Put TD Aluminum Ore or Iridum Ore into the Chamber
4. Watch the Chamber turn them into Pulverized Aluminum or Iridium but then choke as it can't empty into the Smelter.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12-14.21.1.2443
**Mekanism:** 1.12.1-9.4.318
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
Aluminium & Iridium is a COFH issue. They removed the smelting recipe. https://github.com/CoFH/ThermalFoundation/commit/fadde125a175c72e46bbb1ae1ec677f87537d538

Mithril & BQuarts we can probably add to the minor compat list.

**Comment by llloyd4** [comment]
Really. How odd. I have TE installed and have been processing TE aluminum and iridium with the pulverizer / redstone furnace for a while now. I upgraded to the Factories as they're faster once I put in all the speed an energy upgrades into them and bump up energy production. Well, nothing you can do about it, I'll go over to their Github and make a posting.

**Comment by thommy101** [comment]
Smelting is apparently Work As Intended (https://github.com/CoFH/Feedback/issues/474).

Mithril and BlackQuarts could be added as @thiakil mentioned.

**Comment by llloyd4** [comment]
Yeap, so I posted that to the FTB team, hopefully in a future update of
Unstable 1.12 they will either disable them in favor of other mod aluminum
and iridium or Craft Tweak in smelting recipes. I'd do it myself but I've
never used Craft Tweaker before.

**Comment by thommy101** [comment]
Mini crafttweaker tutorial adding smelting recipes:
furnace.addRecipe(output, input, xp); 
Example:
furnace.addRecipe(<minecraft:speckled_melon>, <minecraft:melon>, 1500);

More info at https://crafttweaker.readthedocs.io/en/latest/Vanilla/Recipes/Recipes_Furnace/

**Comment by llloyd4** [comment]
Cool! When I get home I will poke at it. Thanks. :D

**Comment by llloyd4** [comment]
@thommy101 Do I want to use the Meta's Unlocalized Name? So...

furnace.addRecipe{item.thermalfoundation.material.ingotaluminum, item.thermalfoundation.material.dustAluminum,0.3);

?

**Comment by thommy101** [comment]
You can define the meta data, I know it's defined somewhere on the linked read the docs above ;)

**Comment by llloyd4** [comment]
@thommy101 I could, in theory, even add the enrichment chamber recipes, hmm... *peers* 

mods.mekanism:machineblock:0.addrecipe 

by the looks of it?

**Comment by thommy101** [comment]
You could, if you're using 1.7 ;) Any version higher than that doesn't support craft/modtweaker yet

**Comment by llloyd4** [comment]
Minecraft 1.7? O.o

**Comment by thommy101** [comment]
Yea, that old version which isn't supported by us anymore ;) newer versions do not have that support yet..

**Comment by llloyd4** [comment]
Oy. Beginning to see why no one includes this in their mod packs. :(

**Comment by thiakil** [comment]
Includes what in their packs? External mod support for Craft/MineTweaker has always been done by *Mod*Tweaker. 

Your best bet for adding smelting recipes would be to use the oredict entries. I think it would be `<ore:dustAluminum>` for example.

**Comment by llloyd4** [comment]
Well, that would not break existing dust to aluminum recipes?

**Comment by thiakil** [comment]
Wasn't your problem that you didnt have any to begin with?

**Comment by llloyd4** [comment]
For TE aluminum since that is what spawned in world. If the FTB team fixes
the spawn settings then it will be some other mod's aluminum.

On Aug 15, 2017 6:08 PM, "Xander" <notifications@github.com> wrote:

Wasn't your problem that you didnt have any to begin with?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/aidancbrady/Mekanism/issues/4625#issuecomment-322632393>,
or mute the thread

**Comment by thiakil** [comment]
and using oredict in CT will mean it won't matter whose blocks you have

**Comment by llloyd4** [comment]
Ok, so

Furnace.addrecipe:(ore:aluminum, ore:dust,.0.3)

?

On Aug 15, 2017 6:13 PM, "Xander" <notifications@github.com> wrote:

and using oredict in CT will mean it won't matter whose blocks you have

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/aidancbrady/Mekanism/issues/4625#issuecomment-322633452>,
or mute the thread

**Comment by thiakil** [comment]
I would suggest reading the wiki, and using the `/ct hand` command

**Comment by llloyd4** [comment]
CT hand? Ok...
