### ISSUE TITLE
Digital miner won't silk touch ores!

### ISSUE THREAD

**Issue by Fireworkpyro47** [aidancbrady/Mekanism#4629]
Whenever I set my digital miner to silk touch with redstone and diamonds as a filter, it has 8 speed upgrades, and when I try to start it, all the screens remain black, it tells me the remaining amount to mine, and then doesn't do anything.

Steps to reproduce:
1. Got digital miner
2. Added filters of diamond and redstone.
3. Put silk touch on, and then nothing happened.

I am on all the newest versions of Mekanism on 1.7.10 (I just downloaded it from the website) so it shouldn't be a version problem.

**Comment by ktole1999** [comment]
with that many speed upgrades you cant feed it energy fast enough. start with 1 upgrade and increase till it  stops. this will tell you how many you can safely add.

**Comment by Fireworkpyro47** [comment]
Just removed ALL of my speed upgrades, and it is working now. I thought an Ultimate would work for this kind of immense energy, but I guess not. My issue is solved, thank you.

**Comment by thommy101** [comment]
You could also try to add some energy upgrades to it, it does help a lot with large energy demands
