### ISSUE TITLE
Energy Conduit Client Crash 1.10.2

### ISSUE THREAD

**Issue by SparkyBearBomb** [aidancbrady/Mekanism#4631]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
1.10.2 Client crashes when mining up basic energy conduit

#### Steps to reproduce:
1. place basic universal conduit
2. mine it up
3. crash

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.10.2 
**Mekanism: Latest 9.2.3.97
**Running this pack https://www.technicpack.net/modpack/the-1102-modpack-pack.1070627

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://openeye.openmods.info/crashes/ec10b14166d0db658533222e4de505ce

**Comment by aidancbrady** [comment]
Report to MCMP
