### ISSUE TITLE
Energy consumption is being calculated incorrectly

### ISSUE THREAD

**Issue by roboderpy** [aidancbrady/Mekanism#4632]
#### Issue description:
Energy usage is calculated like there is no speed upgrades installed at all

Can be fixed by removing one of speed upgrades and installing it back

This issue exists on >=1.10.2

#### Steps to reproduce:
1. Place Down any factory
2. Install all 8 speed upgrades
3. Install 8 energy upgrades

#### Version (make sure you are on the latest version before reporting):
**Forge:** Build 2443
**Mekanism:** Build 318

**Comment by aidancbrady** [comment]
Fixed in dev, appreciate it.
