### ISSUE TITLE
[1.11.2] Crash with mekanism 9.4.3

### ISSUE THREAD

**Issue by PapyLols** [aidancbrady/Mekanism#4633]
#### Issue description:
I can't load the game when i have Mekanism in my mod list
#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.11.2-13.20.1.2454
**Mekanism:** 9.4.3
#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/VXHHv9i1

**Comment by aidancbrady** [comment]
Crash relates to some kind of multipart mod in your installation.

**Comment by PapyLols** [comment]
Thanks for replying this quickly!
What "multipart mod" means pls?

**Comment by aidancbrady** [comment]
“Hammer Microblocks” is the name of the mod

**Comment by PapyLols** [comment]
thank you!
