### ISSUE TITLE
[1.12] Personal Chest, Saw Mill, Creative Energy Cube Issues

### ISSUE THREAD

**Issue by IBeCrayZ** [aidancbrady/Mekanism#4634]
Issue description:

1. Unsure if this has always been like this, but seems odd: Personal Chest only allows right-clicking
2. Precision Saw Mill does not contain recipes for any wood log variants (planks seem to work) and will not process normal wood logs, including any wood (planks are fine; does not touch fences/doors/other wooden items from other mods but idk if that's always been the case) from mods like BOP & Forestry.
3. Again unsure if this was chosen to be like this, but the Creative Energy Cube when (for example) spawned in does not contain power, which makes it hard to test machinery without creating power first/using an energy tablet.

Steps to reproduce:

1.  When the Personal Chest is open, you can't move any blocks both in your inventory and the chest via left click like you normally would, only right click,
2. http://imgur.com/a/YixIy > shows sawmill not working.
3. http://imgur.com/a/zPlx2 > no energy in cube.

Version (make sure you are on the latest version before reporting):
Forge: latest 1.12.1
Mekanism: Latest from Curseforge
Other relevant version: All other mods are latest versions, tested with and without them.

**Comment by thiakil** [comment]
regarding point 3: there has always been a full one and an empty one present, make sure you select the correct one. If only one is present then that would be a bug, though I don't see how that would have changed between 12.0 and 12.1, I recall it being fine in 12.0 since that's how I test machines.

**Comment by thommy101** [comment]
And regarding point 2, that is fixed and will be available in the next release of Mekanism :)

**Comment by thommy101** [comment]
@IBeCrayZ Regarding point 1, did you have by any chance a personal chest in your first inventory slot when you wanted to access anything from a personal chest?

**Comment by BaneOfSerenity** [comment]
I'm running mekanism 9.4.0.318 on MC 1.12.0 and i only see the empty creative cube in the JEI selection.

**Comment by IBeCrayZ** [comment]
@thommy101 hmm interesting, yes I did, and it only seems to affect the rest of the inventory when this is the case. I assume there is some kind of implementation to avoid inputting personal chests inside of other ones. 

- When in the first slot of the hotbar it prevents all items in the inventory from being left-clicked, although you can right-click everything bar the personal chest.
- When put in my inventory and not in the hot-bar, everything works as usual expect you cannot left/right click on the personal chest in the inventory.
-  When put in any other section of the hotbar, it does exactly as it would when not placed in the hotbar.

I assume there's a weird problem when placed in the first slot I guess.

@BaneOfSerenity, @thommy101, I also only see one empty creative cube in JEI.

**Comment by thommy101** [comment]
@IBeCrayZ thanks for confirming it and the analysis, I found the bug :D 
You're right with the conclusion about preventing personal chests in personal chests. Will iron out the bug tomorrow. 

Aah, JEI doesn't show the full one.. Creative tab works, sounds like a bug yes :)

**Comment by IBeCrayZ** [comment]
@thommy101 Happy to help!

**Comment by BaneOfSerenity** [comment]
@thommy101  Ah yes, i see it under the creative tab, it seems there are a good handful that show up there that do not show up in JEI.

**Comment by thommy101** [comment]
Personal chest issue is fixed (atleast, there's a PR for it).

JEI is confirmed to be missing in minimal environment. Items missing are the filled energy cubes and filled gas tanks.

**Comment by thommy101** [comment]
Aaaand the last one is also fixed :)
