### ISSUE TITLE
java.lang.NullPointerException: Tesselating block model     at mekanism.common.tile.TileEntityGlowPanel

### ISSUE THREAD

**Issue by ProsperCraft** [aidancbrady/Mekanism#4636]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Player logs in, they crash, another play logs in same base, they crash.

#### Steps to reproduce:
1. Asking players if they can make it happen in single player.

#### Version (make sure you are on the latest version before reporting):
In the crashlog.

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

Player 1- https://pastebin.com/SBwjzEZ2  
Player 2- https://pastebin.com/cCV01H8T

**Comment by thommy101** [comment]
Could you let the players try without foamfix?

There's somehow an issue that there is either no blockstate for the block, or the blockstate doesn't have a color property set.

**Comment by thiakil** [comment]
We should still be checking for nulls in `IExtendedBlockState`. I have a very similar issue open on Applied Llamagistics.

Unlike a normal state, it is completely valid for `IExtendedBlockState` to be missing a value for an unlisted property, `getValue` will just return null. In the glow panel's case it can happen if the TE is null for whatever reason.

I've found BlockState related crashes can happen with using "builder's wands" to place things (No idea which one the user on my server had used when the similar crash happened with ProjectRed stuff)

**Comment by ProsperCraft** [comment]
Reply from a player in that base...

tried without foamfix, with optifine, all settings off and render fast, nothing.

A buioders wand was not used to place them

**Comment by ProsperCraft** [comment]
After using cofh to clear them- 
/cofh clearblocks -1654 10 -4236 -1854 120 -4436 Mekanism:glowpanel

I now get this client crash when going there.
https://gist.github.com/ProsperCraft/041cd4302b39193ca7783357d0184ae5

**Comment by ProsperCraft** [comment]
After rebooting the server- 
https://gist.github.com/ProsperCraft/0e981b44731d6f00277a3f2f9aeedea6

Here is a clean one without foamfix or blur-

https://gist.github.com/ProsperCraft/c21171d41769549796664208e85fe888

**Comment by ProsperCraft** [comment]
This stack trace was in console, this might help.

https://gist.github.com/ProsperCraft/e27c08a566abcff1993152176f81ca0d

**Comment by thiakil** [comment]
your last 3 crashlogs are failing in exactly the same spot. Furthermore from what I can find it is actually crashing *inside the rendering error handler* so you either have a corrupt world or something is seriously messing with your rendering that is not Mekanism. Either the blockstate is null, or the block referenced by it is null.

I'm leaving this open only because there is a potential NPE in Mekanism as I mentioned before, however impossible it should be under normal circumstances.

I suggest you start removing mods one by one until the error stops, starting with the listed coremods.

**Comment by thiakil** [comment]
this should be fixed for next release

**Comment by thommy101** [comment]
Fixed in 3cc755f33dc8b4ac78fbaca6753361ee401bbd26
