### ISSUE TITLE
[Feature] redstone control of universal conduits

### ISSUE THREAD

**Issue by SparkyBearBomb** [aidancbrady/Mekanism#4639]
1.7.10 had the ability to disconnect energy conduits when Redstone was applied,

Can this be re-added to 1.10.2 and later?

**Comment by thommy101** [comment]
All versions should have this feature. Have you turned on redstone sensitivity mode with the configurator? (right clicking the energy conduit with it in the middle)

**Comment by SparkyBearBomb** [comment]
I can't find that in the config, I am using defaults for both client and server.

**Comment by thommy101** [comment]
It's not in the config, there's an ingame item called configurator which allowes you to configure transmitters and mekanism machines.

**Comment by SparkyBearBomb** [comment]
ah, thanks =)
