### ISSUE TITLE
Digital Miner in Silktouch mode produces unusable non-textured blocks when harvesting logWood

### ISSUE THREAD

**Issue by nekoexmachina** [aidancbrady/Mekanism#4640]
#### Issue description:
I wanted to clear a forest using Digital miner, and it was left in silktouch mode because I've forgot to change that. 

Its filter was "logWood". It produced a series of unusable unstackable non-textured blocks named "Oak Wood", etc. This blocks, when placed, reverted themselves to regular Oak Woods (every single one of them, including Acacia logs and Pine logs). 

#### Steps to reproduce:
1. Place SilkTouch Digital Miner
2. Configure it to harvest Logs
3. Behold!

#### Version (make sure you are on the latest version before reporting):
**Forge:** 12.18.3.2422
**Mekanism:** Mekanism-1.10.2-9.2.3.97.jar 
**Other relevant version:** n/a

**Comment by thommy101** [comment]
Merging with #4637 as they have the same cause.
