### ISSUE TITLE
flamethrower not aiming correctly

### ISSUE THREAD

**Issue by gerb82** [aidancbrady/Mekanism#4647]
#### Issue description:
i've been playing on a pack called modern skyblock 2. it's a fun skyblock pack that has mekanism. i made a flamethrower for fun, and tried using it a little. charged it up, and, tried to smelt something below me. and then it didn't work. tried a few times, and then realised that it's not firing where i'm aiming. used f5, and noticed something weird. when i look forward in a 90 degree angle, it fires right. if i move it x degrees up/down, it will fire x degrees up. then i tried firing around me, and noticed it always fires in relatively the same direction. i was able to spin it a bit to the left or right, but it always fired there, even when i looked the other way. so i checked which direction it is. apparently, i couldn't fire anywhere that isn't in the arc between south to east. when the flames hit something they do act correctly, so this is only an issue with how it aims.

#### Steps to reproduce:
1. make flamethrower
2. charge it
3. fire it

#### Version:
**Forge: 14.22.0.2459** 
**Mekanism: 1.12.1-9.4.0.318** 
**Other relevant version: minecraft 1.11.2, modern skyblock 2 version 2.3.5**

**Comment by gerb82** [comment]
my guess is that when summoning the "flame" it doesn't calculate the angle correctly. when i looked towards positive z, it worked. lets say that is the 90 point. if directly left is 0 and directly right is 180, then it should just use the angle i am looking at. but instead, when it's for example 140, instead of aiming towards 140, it reduces 50 out of 90, resulting in it firing towards 40 degrees. is seems that way in x y and z. sorry if it's a weird explenation, but i hope it's clear enough.

**Comment by thommy101** [comment]
@gerb82 Just confirming, you're using MC version 1.12.1 right? As your last line of the initial report says 1.11.2, but the line above it 1.12.1?

I don't know yet which code causes this, but I'm almost certain that the line resulting in this bug has a git blame pointing to me :D 
Sounds a lot like a wrong x/xCoord conversion in 1.12

**Comment by gerb82** [comment]
i am in fact using mc 1.11.2, but the pack uses mekanism 1.12.1 on the 1.11.2 mc

**Comment by thommy101** [comment]
You're sure with those version numbers? Something isn't adding up.
1.11.2 isn't compatible with 1.12.

**Comment by gerb82** [comment]
¯\_(ツ)_/¯
somehow it works. those are the version numbers according to the twitch launcher

**Comment by thiakil** [comment]
I think you'll find v2.3.5 is MC 1.12.1... https://minecraft.curseforge.com/projects/modern-skyblock-2/files/2467535

**Comment by gerb82** [comment]
Makes sense. It wouldn't surprise me if twitch displayed a wrong number. After the mass of bugs on twitch I've seen in the last few days, i wouldnt even be surprised at this point if it displayed the wrong modpack name :D

**Comment by thiakil** [comment]
Fixed in dev. Yes the main issue was a `Vec3D` variable change ;)

**Comment by thommy101** [comment]
Definitely a git blame for me! Somehow I looked at this issue and that method a couple times and still have I missed it :/ Thanks for finding!

**Comment by thiakil** [comment]
Veeeerrrryyyy easy to miss, don't worry

**Comment by thommy101** [comment]
Fixed in 31a3482e40612bb621a34602c14c56925ac57303
