### ISSUE TITLE
Missing assets when compiling dev branch

### ISSUE THREAD

**Issue by roboderpy** [aidancbrady/Mekanism#4649]
![9ab013da82_javaw_2017-08-25_13-38-52](https://user-images.githubusercontent.com/6339511/29702284-c71b2360-899a-11e7-8f61-ee5d4219969b.png)
```
[13:28:06] [main/WARN]: Failed to load texture: mekanism:render/personalchest.png
java.io.FileNotFoundException: mekanism:render/personalchest.png
```
Happens because assets are not lower-cased:
![081bd57bae_7zfm_2017-08-25_13-39-26](https://user-images.githubusercontent.com/6339511/29702296-d61d2a2a-899a-11e7-9360-cc994ee2aca8.png)

**Comment by roboderpy** [comment]
`git clear` solved the issue

**Comment by thommy101** [comment]
The wonderful thing called Windows' case insensitivity :)

Happy you've solved it.

**Comment by thiakil** [comment]
If i have to switch between the 1.10 branch and 1.11/12 I find myself deleting the resources dir, checking out, then discarding changes xD

**Comment by thommy101** [comment]
I've solved it in another way, 3 workspaces :) One for each version
