### ISSUE TITLE
Bounding blocks after breaking Wind Generator. 

### ISSUE THREAD

**Issue by gefailter71** [aidancbrady/Mekanism#4651]
Server: Yes
Forge version: 2459
Mekanism version: 1.12.1-9.4.0.318
Mekanism Generators version: 9.4.0.318

After Breaking the Wind Generator invisible bounding blocks were still there.

![](http://i.imgur.com/BFSm9fP.png)

**Comment by thommy101** [comment]
Thanks for reporting the issue! I've got a couple questions to be able to help you as much as possible:
- Do you have a client & server log of when this happens?
- Did you break it with the pickaxe in your hotbar?

I've tested it locally with a slightly more up to date version (which shouldn't contain anything what could have fixed something like this), and it doens't happen when I break it with a pickaxe.

**Comment by thiakil** [comment]
I can't reproduce it either, so I have a couple extra questions

* Is the server using Sponge?
* Are there any chunk claiming mods installed and active?

**Comment by NerdCraft** [comment]
It happened in my server too:
![2017-09-07_17 50 26](https://user-images.githubusercontent.com/13489837/30184726-5ab1bd00-93f5-11e7-8e27-a4feacf3156e.png)
I used mcedit to remove it:
![sem titulo](https://user-images.githubusercontent.com/13489837/30184776-83800eda-93f5-11e7-8929-294143403321.png)

1.12.1
Mekanism 9.4.1.326

**Comment by thiakil** [comment]
@NerdCraft please attempt to answer the questions we posed. We need to know how to reproduce it, not just that it happens

**Comment by NerdCraft** [comment]
Do you have a client & server log of when this happens?
no, it happened when my friend enter the server, sometime ago.

Did you break it with the pickaxe in your hotbar?
yes, it not work

Is the server using Sponge?
no, it's using forge

Are there any chunk claiming mods installed and active?
yes, chicken chunks

**Comment by thiakil** [comment]
> no, it happened when my friend enter the server, sometime ago

So there wasn't a Mekanism wind generator there previously? Because that sounds like a Forge or corruption  issue.

**Comment by NerdCraft** [comment]
No, it hadn't any blocks there

**Comment by thiakil** [comment]
Thats probably not related to this issue then

**Comment by NerdCraft** [comment]
My friend told me now that this block appeard after someone tried to use shift+ right click with CarryOn mod on a block from mekanism with security. I don't know if this is causing the issue.

**Comment by NerdCraft** [comment]
https://minecraft.curseforge.com/projects/carry-on

**Comment by thommy101** [comment]
That would definitely cause stuff like this. Multiblocks generally do not like being moved. It's not something Mekanism could solve either.
