### ISSUE TITLE
[1.10] CraftTweaker Recipe Removal Being Overwritten

### ISSUE THREAD

**Issue by quixQuery** [aidancbrady/Mekanism#4655]
#### Issue description:
Currently Mekanism is overwriting the removal of recipes by CraftTweaker, this has not been an issue in past versions of Mekanism in 1.10. Additionally, every time recipes are reloaded, another identical recipe is added (this is understandable as reloading recipes isn't the best practice, but it might help someone understand where the issue lies).

#### Version:
All versions are current for MC(1.10) as of posting.
Forge - 12.18.3.2422
Mekanism - 9.2.3.97
CraftTweaker - 3.0.26

![example](https://user-images.githubusercontent.com/26725961/29798095-7efe9372-8c20-11e7-892d-c070cee9a8b2.png)

**Comment by thiakil** [comment]
Please post your latest.log and crafttweaker log. Note though that we're mostly only fixing crashes in 1.10.

AFAIK Mekanism doesn't do anything strange in recipe registration, so it's likely that CT is not removing the recipe in the first place - whether it is failing or your script is incorrect.

**Comment by thommy101** [comment]
And on top of what @thiakil asked, also please provide the zenscripts you're using so we could try and reproduce it.

It could be that Mekanism is registering recipes too early/late for CT to pick it up, but it's definitely solved in the latest version for 1.12 :)

**Comment by quixQuery** [comment]
The scripts I am using worked previously, and upon updating Mekanism to the latest version, they stopped working and this happened. I will do a full-blown analysis though and provide the logs and scripts and other data.

**Comment by quixQuery** [comment]
The following is the .log and the .zs:
[2017-08-29-4.log.gz](https://github.com/aidancbrady/Mekanism/files/1260111/2017-08-29-4.log.gz)
[test.txt](https://github.com/aidancbrady/Mekanism/files/1260114/test.txt)

NOTES: 
-I had to rename test.zs to test.txt because .zs is an unsupported format for uploading files.
-There are no errors running or reloading the CraftTweaker script.
-The only mods I had installed for this specific test were: Forge, CraftTweaker, JEI, Mekanism, and MCMultiPart.

Steps to reproduce:
1. Remove a Mekanism recipe using a CraftTweaker Script.
2. Upon reloading scripts, the original recipe is present again.
3. This is not an issue with vanilla recipes or the recipes from other mods.

Upon further investigation it turns out the issue only occurs after using `/mt reload`, which makes this mostly a non-issue, but I figured I'd give the data anyway since this seems to be the only mod that does this. Thanks for the patience and the active development!

**Comment by thiakil** [comment]
Sounds like an issue with CT not handling tracking/reverting its changes properly then. Did you happen to update CT at the same time as Mekanism?

**Comment by quixQuery** [comment]
Again this is not an issue with other mods so I would assume this has something to do with Mek code and not CT.

**Comment by thommy101** [comment]
Sadly going to close this as wont fix, Mekanism 1.10 registeres it recipes a bit too late for CraftTweaker to work, this requires a bunch of work to make it work properly.

In 1.12 and up the recipes are registered on time for CraftTweaker to work.
