### ISSUE TITLE
1.12.1 Texture Errors

### ISSUE THREAD

**Issue by mcfilmmakers** [aidancbrady/Mekanism#4657]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When I try to run mekanism, I notice the following texture errors 

#### Steps to reproduce:
1. Install latest Mekanism on Forge 2463
2. Look at minecraft log

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.12.1 2463
**Mekanism: 9.4.0

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[https://pastebin.com/uWS2GFYh](https://pastebin.com/uWS2GFYh)

**Comment by thiakil** [comment]
I see only texture errors in the `minecraft` domain. Unsure how this is related to mekanism.

**Comment by mcfilmmakers** [comment]
It is related to
Melanoma because melanoma is the one causing the issue. Removing melanoma stops the error from happening.

**Comment by mcfilmmakers** [comment]
Damn auto corrected. Above should read as melanoma = mekanism.

**Comment by mcfilmmakers** [comment]
I've tested with every mod available on curse for 1.12.1 yours is one of 6 that cause texture issues. When I test with other mods that do not cause texture issues, mekanism creates more missing textures from those mods.

**Comment by mcfilmmakers** [comment]
Why is the issue closed? Mekanism is legitimately causing this texture issue, log provided and can be reproduced.

**Comment by thiakil** [comment]
- The log mentions missing textures in the `minecraft` domain, not `mekanism`
- You have more than just Forge & Mekanism loaded
- Two of your mods appear under the locations for `minecraft` domain - either they are incorrectly packaging their textures or overwriting vanilla, either of which could be the issue

Combined, I do not find it to be sufficient evidence that Mekanism is the cause. When I have time I will test and see if I can reproduce it with just Mekanism and Forge. I am more than happy to reopen if I can reproduce it or you can show (with logs) that it a) doesnt happen with just forge and no mods and b) does happen with just Forge and Mekanism

**Comment by mcfilmmakers** [comment]
Sounds good. I currently can't test this until tomorrow evening but will present my log at that time.

**Comment by thommy101** [comment]
Looking at the logs (don't have a workspace in front of me), it looks a lot like Mekanism is causing this as the 4 mentioned textures are all being "used" by the transmitters.
https://github.com/aidancbrady/Mekanism/blob/1.12/src/main/resources/assets/mekanism/blockstates/diversion_transporter.json#L6

It's not a bug causing missing textures, but it would be nice if we can "fix" it so it doesn't show a warning on startup.

**Comment by thiakil** [comment]
Those names are used in the mtl file https://github.com/aidancbrady/Mekanism/blob/1.12/src/main/resources/assets/mekanism/models/block/transmitter_large.mtl

**Comment by thiakil** [comment]
They're used in the mtl file exactly as written (`map_Kd`)

https://github.com/aidancbrady/Mekanism/blob/1.12/src/main/resources/assets/mekanism/models/block/transmitter_large.mtl

**Comment by thiakil** [comment]
probably a forge bug if anything

**Comment by aidancbrady** [comment]
This has been an issue with a while, and has to do with Forge's model handling. I fixed it back in the early days of 1.10 but I think it came up again after I refactored transmitters for 1.11. A bit of digging should fix the issue- usually it's an unhandled ModelResourceLocation case.

**Comment by thommy101** [comment]
I'm no hero with blender and .mtl files, but the issue is probably exactly what @thiakil pointed out. Other .mtl files (like glow_panel) reference to textures like `mekanism:blocks/models/multipart/GlowPanel`.
