### ISSUE TITLE
Bug with universal cables

### ISSUE THREAD

**Issue by pcking99** [aidancbrady/Mekanism#4658]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Game crashes when trying to mine universal cable.

#### Steps to reproduce:
1. Place 1x2 with universal cable.
2. Mine with a pick axe or paxel.
3. crash after 1 hit.

#### Version (make sure you are on the latest version before reporting):
**Forge: forge-1.10.2-12.18.3.2185-universal** 
**Mekanism: Mekanism-1.10.2-9.2.3.97** 
**Other relevant version:
MekanismGenerators-1.10.2-9.2.3.97
MekanismTools-1.10.2-9.2.3.97
** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://www.dropbox.com/s/4mlvesvc24enn60/crash-2017-08-30_11.47.03-client.txt?dl=0
[gist/pastebin/etc link here]

**Comment by thommy101** [comment]
That would be an issue with treecapitator. See #4329 for more information.
