### ISSUE TITLE
AE2 system can't hold elite+ objects

### ISSUE THREAD

**Issue by TheGoldenProof** [aidancbrady/Mekanism#4664]
I have an AE2 system and i was trying to autocraft an elite energy cube but it was getting stuck and i couldn't do anything about it. i tried normally crafting one in the crafting terminal and it worked just fine but as soon as I tried to put it into the system nothing would happen, as in it wouldn't go in. i tried putting other elite items in but they wouldn't go in either. I know that they all have the same item id (which i discovered while trying to give them EMC and soon was very annoyed) if it has anything to do with that.

### Versions:
**Forge: forge-10.14.4.1614** 
**Mekanism: 9.1.0.281** 
**AE2: rv3-beta-6** 
**Minecraft: 1.7.10**

#### [similar issue](https://github.com/aidancbrady/Mekanism/issues/397)

**FIXED**
I ran out of storage :P

**Comment by thiakil** [comment]
you are able to close your own issues btw
