### ISSUE TITLE
[1.12] MCMultipart issues

### ISSUE THREAD

**Issue by thiakil** [aidancbrady/Mekanism#4668]
```
MCMP: 2.2.2
Mekanism: 334fe1cd59285cf735fa58523f9f896a060c12fc
Forge: 14.22.0.2446
```

- [x] Glow panel bounding box incorrect when placed on transmitter
- [x] Cable & Glow panel invisible after world reload

**Comment by thiakil** [comment]
![2017-09-02_13 16 28](https://user-images.githubusercontent.com/1788847/29993167-56ceb0ca-8fe1-11e7-9fcc-a90aaee87457.png)

**Comment by thommy101** [comment]
Just making sure:
It only displays nothing when a glow panel is placed on top (of at) a pipe? All other cases are still rendering as expected?
Does it work correctly with the previous MCMP version we've used (exp 2.2.1_36)?

**Comment by thiakil** [comment]
> All other cases are still rendering as expected?

Unsure

> Does it work correctly with the previous MCMP version we've used

Didn't test, but unlikely. Didn't see any changes that should affect it.

**Comment by BrisingrAerowing** [comment]
I think this may be related to MCMP failing to provide the world object for a multipart block / TE. This seems to affect versions 2.0.1+

Ref: amadornes/MCMultiPart#91
Ref: raoulvdberge/refinedstorage#1427

**Comment by thiakil** [comment]
It's likely a model issue due to how the Mekanism models work. The blocks are there just fine, but the obj models need properties from the block state that may not be there.

**Comment by thiakil** [comment]
models does appear to have been a mcmultipart issue, bounding box is fixed with an event
