### ISSUE TITLE
Chemical injection chamber not accepting hydrogen chloride

### ISSUE THREAD

**Issue by Mceonith** [aidancbrady/Mekanism#4669]
couldn't find anything on the web about this nor any other threads here but trying to get injection chamber to accept the input but its not happening. any suggestions? 
![input output selected](https://user-images.githubusercontent.com/3062613/30002858-84bd133c-9081-11e7-937a-27b658e14e3c.png)
![making hcl](https://user-images.githubusercontent.com/3062613/30002860-84bd90f0-9081-11e7-88b4-c0b8684e4f78.png)
![my setup](https://user-images.githubusercontent.com/3062613/30002861-84bdb0e4-9081-11e7-810f-571e39ecd1c9.png)
![no hcl coming in](https://user-images.githubusercontent.com/3062613/30002859-84bdacac-9081-11e7-9eb0-624a1225c959.png)
![piping it out](https://user-images.githubusercontent.com/3062613/30002862-84be459a-9081-11e7-80e6-a786d287b292.png)

**Comment by thiakil** [comment]
Your first screenshot shows the item tab, not the gas tab. Please check that the Chemical injection chamber is set to input gas from the top.

**Comment by Mceonith** [comment]
okay will do when i get back to my system in a few days, currently not available

**Comment by Mceonith** [comment]
Gas tab
![untitled](https://user-images.githubusercontent.com/3062613/30102784-a6979344-92be-11e7-888e-3cbfec21fb24.jpg)

**Comment by thommy101** [comment]
By the look of your pipes there's already a gas in it, hydrogen chloride is light blue (as seen in the C.Infuser). Please break all the pipes & try again.

**Comment by Frantasad** [comment]
Hello, i had the same problem, injection chamber did not accepted hydrogen chloride from any side, but only from pipes, when i put a gas tank next to it, and set it to output on the side facing the injection chanber, it started working... maybe some problems with the pipes ? hope this helps
