### ISSUE TITLE
Dynamic Tank Crash the Server

### ISSUE THREAD

**Issue by Lyror** [aidancbrady/Mekanism#4670]
Hello,

i use the mekanism version "MekanismAll-1.12-9.4.0.homebaked-3.jar". I build a 18x18x18 Dynamic Tank filled with brine and i build a second 18x18x18 Tank for Lithium. All works fine.

I have some issues with draconic evolution wireless RF network. So i restart the server over /restart command and now the server crashes on startup. I attached the crash log

Can anyone help me.

Lyror

[crash-2017-09-03_14.37.13-server.txt](https://github.com/aidancbrady/Mekanism/files/1272918/crash-2017-09-03_14.37.13-server.txt)

**Comment by thommy101** [comment]
Did you have build them right next to each other by any chance, like no space apart?

**Comment by Lyror** [comment]
i attached a screenshot from the tanks. 

i fixed the problem with updating to the latest version for 1.12.1

![image](https://user-images.githubusercontent.com/10835078/30036338-ab6c423c-91b2-11e7-82eb-60f44da6b86a.png)

**Comment by Lyror** [comment]
now i get this exception again :( .

Mekanism-1.12.1-9.4.0.318
MekanismGenerators-1.12.1-9.4.0.318
MekanismTools-1.12.1-9.4.0.318

Crashlog: https://pastebin.com/0sYtjjH6
