### ISSUE TITLE
[1.12.1] Crash on launch

### ISSUE THREAD

**Issue by ProxyPlayerHD** [aidancbrady/Mekanism#4671]
Log: https://pastebin.com/WLL4AFg4
Forge: 14.22.0.2467
Mek: all v9.4.0.318

it says something about a texture not fitting? and Resourcepacks... it was the first time i launched the pack, there is no possible way i could have had a Resourcepack active.

**Comment by thommy101** [comment]
You can have texturepacks active by default. The error you're getting is about the texture atlas (all textures of all active mods combined) isn't large enough to fit all textures. Either there are mods with huge textures (I know Mekanism does use a bit), or there is a texturepack/resourcepack active with something like HD textures.

**Comment by ProxyPlayerHD** [comment]
well as said it was the first time i launched the pack, i didn't have any resourcepacks, even if my self made pack is 16x16...

removing Mekanism fixed it.

**Comment by thiakil** [comment]
Have you tried without optifine? 2048x2048 is rather small for a texture atlas...

**Comment by ProxyPlayerHD** [comment]
well shit, without Optifine it works...

welp, guess no Mekanism until both work.
