### ISSUE TITLE
[code] increasing the D-T capacity of fusion reactors.

### ISSUE THREAD

**Issue by Buggy123** [aidancbrady/Mekanism#4672]
#### Issue description:

I'm attempting to increase the internal capacity of a fusion reactor above 1,000 mB of D-T fuel, so that I can burn more than 1,000mB fuel per tick, and thus make more than 100MRF/T per reactor. After a bit of searching, I found (what appears to be) the relevant bit of code and changed it. The mod works normally, and the volume increases accordingly, [however it's not actually possible to put more than 1,000 mB into the reactor.](https://imgur.com/iXImVFb.jpg) I've tried several different methods of injecting fuel, and all of them are incapable of putting more than 1,000mB of deuterium, tritium, or d-t into the internal tank over any period of time, regardless of the state of the reactor. This includes the pressure pipes mod, which has infinite I/O and natively supports Mekanism's gas system, as well as Mekanism pressurized pipes.

I've probably missed some bit of code somewhere which is limiting it, but I've yet to find anything after a hour of searching.

#### Steps to reproduce:

In TileEntityReactorController.java, edit
`	public static final int MAX_FUEL = 1 * Fluid.BUCKET_VOLUME;`
change to
`	public static final int MAX_FUEL = 10000000 * Fluid.BUCKET_VOLUME;`
compiled, install, and run normally.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 12.18.3.2422 
**Mekanism:** 9.2.3 (latest version for 1.10.2)
**Other relevant version:** Running 1.10.2 Minecraft, specifically the FTB Beyond pack with some modifications and additions.

**Comment by thiakil** [comment]
First thing I notice is that you're setting `MAX_FUEL` to something that will overflow an integer.

**Comment by thommy101** [comment]
And after changing the value to something that would fit into an integer, did you replace the controller (more preferably created a new one). It saves the current max gas and current gas in it. Changing that value only affects new ones.

**Comment by Buggy123** [comment]
Ah, yep that did the trick. Thank you, issue resolved.
