### ISSUE TITLE
[1.12.1] Dupe bug using Chemical Washer.

### ISSUE THREAD

**Issue by DEv0on** [aidancbrady/Mekanism#4673]
#### Issue description:
Dupe bug using Chemical Washer

#### Steps to reproduce:
1.Open chemical washer gui
2. Put stackable item in left down corner [ScreenShot](https://gyazo.com/c4b6bff40b52d0a14e6d703ce207fe3c)
3.Hold shift and click on this item

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.22.0.2469
**Mekanism:** 9.4.1.325

**Comment by thommy101** [comment]
Fixed in c1e0cf828838d44807565be9f5d90a29e63a5805
