### ISSUE TITLE
[1.10.2] Cant extract from crusher

### ISSUE THREAD

**Issue by pcking99** [aidancbrady/Mekanism#4680]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I can't extract items out from crusher via mekanism's item pipes.
I have configured it so it will eject items automatically but it wont.

#### Steps to reproduce:
1. Put cobblestone (or anything that can be used in crusher) in a configurated crusher (factorry or not) for automation.
2. place mekanism basic item pipes
3. Configurate the pipe with pull and push to chest

#### Version (make sure you are on the latest version before reporting):
**Forge: 12.18.3.2185** 
**Mekanism: 9.2.4.103** 
**MekanismGenerators: 9.2.4.103**
**MekanismTools: 9.2.4.103**
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thommy101** [comment]
Have you configured the crusher to output on the side the pipe is on?

**Comment by pcking99** [comment]
yes. I have found out i can get items out of the top but not anywhere else. I am trying to make it work with AE2. Also 1 input and 1 output sides.

**Comment by thommy101** [comment]
You can configure which sides are input and output in one of the tabs on the side of the GUI.

http://wiki.aidancbrady.com/wiki/Tutorials/Machine_Configuration
Heading "The Configuration User Interface"

**Comment by pcking99** [comment]
I have done that.
For testing i did all the sides to output.

**Comment by pcking99** [comment]
https://www.dropbox.com/sh/3u6v7c8h23zxrj4/AABbQx5dYIKpO80-Y8IY7wfqa?dl=0
Pictures of what i have tryed.

**Comment by pcking99** [comment]
Looks like i was at fault. Since it got into the Bin at the top. but not on any other sides.

**Comment by thiakil** [comment]
That's correct, bins will only accept items from the top, and output from the bottom using pipes.

Any side probably works with other mods' pipes. We should also probably stop Mek pipes from appearing connected to the sides.
