### ISSUE TITLE
[1.7.10] v8 to v9 change?

### ISSUE THREAD

**Issue by becauseitsnecessary** [aidancbrady/Mekanism#4681]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
From v8 > v9 solar evap. towers became thermal, seems to have made modtweaker unable to interface.

Also the version checker mentions updating to versions that do not exist on 1.7.10.

#### Steps to reproduce:
1. Install Mekanism
2. Install Modtweaker
3. Try to add a tower recipe

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1614
**Mekanism:** Mekanism-1.7.10-9.1.0.281
**Other relevant version:** --

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
> seems to have made modtweaker unable to interface.

That's a modtweaker issue.

> Also the version checker mentions updating to versions that do not exist on 1.7.10.

Unfortunate, but as 1.7 is no longer supported I recommend turning off the update checker.
