### ISSUE TITLE
Power loss through infrastructure.

### ISSUE THREAD

**Issue by InfiniteMaximum** [aidancbrady/Mekanism#4686]
Relevant info: https://onedrive.live.com/view.aspx?resid=BCAA72FF672DB3E3!17524&ithint=onenote%2c&app=OneNote&authkey=!AA2pwONbJp_7AMA. 

Formatted to instructions minus any required  logs that I may need to present.

**Comment by thiakil** [comment]
A) Don't post information like that. Put it in the text of the GH issue and attach the images on github.
B) Did you search at all? Duplicate of #4676

**Comment by InfiniteMaximum** [comment]
That was the result of an out of date version. I am using an up to date version of mek. I will repost according your guidelines.
