### ISSUE TITLE
Mekanism Power Distribution Bug

### ISSUE THREAD

**Issue by InfiniteMaximum** [aidancbrady/Mekanism#4687]
Hi,

I am having an issue using mekanism cables for my power infrastructure in Minecraft. It seems when you go away from your house a bit, teleport, go to sleep… power generation seems to stop and the cables do not transfer power properly.

I do not have an accurate cause for this, but it has affected players on my Minecraft Server. 

In the pictures attached you will see: 
1. The Windmills are charged and are not drained. Very high elevation, not prone to loss of wind speed. There is sufficient power in the grid to power my items at ~414.55 J/t or ~165.82RF/T per windmill. (2 Windmills running)
2. The cables indicate they have a charge and yet visually as you will notice there is no indication of that with the green glow. 
3. The items that are powered in my house do not get replenished with power as the cables should indicate. 

I do not know if this is a bug with the modpack I am using in combination with other mods or the mod itself. Would it be possible for someone on the dev team to help me debug it?

### **Minecraft Info:**
Version: 1.12.1 
Modpack: Beyond the New Frontier V4.8 
### **Mekanism Mods:**
Mekanism-1.12.1-9.4.1.326 
MekanismGenerators-1.12.1-9.4.1.326 
MekanismTools-1.12.1-9.4.1.326 

1. I apologize if my first post did not satisfy posting requirements for easy reading #4686 . That was indeed my fault. 

2. In reply to whether I searched for similar issues... I did but the answer given was unclear. There was no indication of a resolution, rather a vague hint in #4676. Last Reply: "Your version is far too out of date and probably doesn't even include the initial half of the fix to this type of problem. The latest is 9.4.1.326 for 1.12". That does not stipulate that is is being looked into or resolved. Rather it leaves an impression that it is resolved via upgrading mekanism, which is not my issue. Now I am not trying to be an assh***. I realize people have lives away from virtual wonderland and I am not looking for a quick fix. I would appreciate it when you have the time to help me look into this. Please and Thank You. 

![powergenwind](https://user-images.githubusercontent.com/25554587/30356425-f66087c6-9806-11e7-85c9-252d88273e4f.JPG)
![cable](https://user-images.githubusercontent.com/25554587/30356428-fcd5aafa-9806-11e7-8ff3-1f9ead76b840.JPG)
![infuser](https://user-images.githubusercontent.com/25554587/30356429-0019f31a-9807-11e7-9f4f-f5865c5c3dcd.JPG)
![mattertransmitter](https://user-images.githubusercontent.com/25554587/30356433-034757ee-9807-11e7-9819-d7ea992bdc13.JPG)

**Comment by thiakil** [comment]
You could have edited your issue rather than starting a new one.

My comment about a version update was not in  response to the op, which is why it is still open. 

The original issue post is exactly the issue you are having. Earlier in the thread Tom stated "apparently it's not fixed completely..." which he has since tested and confirmed.

Please subscribe to that thread using the button in the sidebar.
