### ISSUE TITLE
Debug spamming console log about caps for Colossal Chests

### ISSUE THREAD

**Issue by dmodoomsirius** [aidancbrady/Mekanism#4691]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Mekanism spamming debug about Colossal Chests caps for its chests

#### Steps to reproduce:
1. any pipe that is logistical sorter or any inventory/item pipe
2.any pipe of mek's that does isided capabilities
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2478
**Mekanism:**  9.4.1.326
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://gist.github.com/dmodoomsirius/f08b00d79e00053ddf157a8e9f18615a

**Comment by thiakil** [comment]
That's an issue on their side. Slots are supposed to be 0 based, meaning that the highest slot number is 1 less than the number of total slots they report.

Without that check things have crashed with other mods.

**Comment by dmodoomsirius** [comment]
I just made a issue on ColossalChests issue tracker about it.

**Comment by thommy101** [comment]
Fixed by Collossal Chests
