### ISSUE TITLE
[1.7.10] Array out of bounds when switching gas input

### ISSUE THREAD

**Issue by Michal-MK** [aidancbrady/Mekanism#4692]
#### Issue description:
On changing gas input on chemical crystallizer I get kicked out of the world, MC does't crash but it puts you back to the menu. log says:
https://gist.github.com/Michal-MK/b224ca74074c67262bae58f0a4af22de

I know that 1.7.10 is no longer supported, I would just like to know whether this is caused by mekanism or by a combination of mods.

Ty.

#### Steps to reproduce:
1. Place Chemical Crystallizer
2. Open gui and switch to "gas" tab
3. Click on any side of the block to change input/output

#### Version (make sure you are on the latest version before reporting):
**Forge:** Latest 1.7.10
**Mekanism:** Latest 1.7.10
**Other relevant version:**

**Comment by thiakil** [comment]
looks to be a mekanism thing, but you don't appear to actually be on the latest 1.7
