### ISSUE TITLE
[Feature request] 1 way pipe

### ISSUE THREAD

**Issue by Moobien** [aidancbrady/Mekanism#4693]
For larger/more complicated networks a 1 way logistics pipe could be beneficial for flow control, similar to how a redstone repeater acts to control redstone flow.

I am suggesting this as my foundry is set up in a different building to my storage area and i have an Oredictionificator running parallel to a part of this between the digital miner output and the storage area. I have the foundry input set to dark red and the logistics sorter keeps sending ores to the oredictionificator instead of the red pipe (where they are supposed to go). My only workaround to this is to set the logistics sorter to round robin that way only 50% go to the oredictionificator instead of 100%

*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by Moobien** [comment]
Also another possible item is a pipe upgrade item similar to the machine installers so you can upgrade pipes in situ

**Comment by zashra00** [comment]
couldn't you just move the oredictionificator or is it detrimental to the entire process?

**Comment by Moobien** [comment]
I wish i could remove it but i have a lot of mods that add similar or same ores. Because the mek bins arent lockable i have to use yabba barrels on top of them to lock the bins input, yabba doesnt accept by ore dict like jabba barrels did so i need the oredictionificator to unify ores fore storage.

**Comment by Moobien** [comment]
If the mek bins were lockable and accepted ores via ore dict then it wouldnt be an issue.

**Comment by zashra00** [comment]
is this a mod pack?

**Comment by Moobien** [comment]
No. Just my own selection of mods

**Comment by thiakil** [comment]
sounds like your setup is not quite right.

**Comment by aidancbrady** [comment]
Easy alternative would be a chest buffer with pipes set to rigid push/pull states.
