### ISSUE TITLE
[1.11.2] Logistical Sorter item filtering issue

### ISSUE THREAD

**Issue by DoomsDoorWay** [aidancbrady/Mekanism#4694]
#### Issue description:
Using the logistical sorter to sort the drops from a mob farm and I've run into an issue when trying to send items like bows ect which are damaged to a different location it will only filter the exact bow that was used to create the filter because it's using the metadata from that item. 
With a bow filter in place it will send the bow or those with identical metadata to the correct storage but at the same time it also wont send the other bows to the other storage which is currently set to take everything not filtered so the bows will just sit in the original storage. 
I found a <a href="https://github.com/aidancbrady/Mekanism/issues/992">similar issue from 2014</a> where a subtype check was added but this doesn't seem to be an option in the logistical sorter anymore.

#### Steps to reproduce:
1. Place storage.
2. Place logistical sorter pulling from the storage.
3. Place logistical transporters connecting the sorter to two more storage and paint the transporters different colours.
4. Set the sorters default filter to 1 of the colours then create a filter for bows set to the 2nd colour.
5. Add some random items and bows with different metadata to the first storage.
6. The random items will now be in the 2nd storage and any bows with the same metadata as the original will be in the 3rd storage all the remaining bows will still be in the first storage.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 13.20.1.2454
**Mekanism:** 9.3.4
**Other relevant version:**

**Comment by thommy101** [comment]
Confirmed for latest Mekanism version.

Easier reproduction:
- Place a bunch of random bows (different damage) and some junk (bones/arrows or anything other than bows) in a chest
- Logistical sorter next to it, with a pipe leading to another chest
- Try to filter all bows out

There isn't a way to ignore nbt/damage/whatever.
