### ISSUE TITLE
Joapca recipe problem

### ISSUE THREAD

**Issue by Trinsdar** [aidancbrady/Mekanism#4695]
#### Issue description:
When Joapca, mekinism, jei, and a mod that adds other ores such as thermal foundation are installed together, joapca adds the crystals and stuff but the recipes for them do not exist. I posted this on 
joapca's github, but they said it was a mekinism and jei issue and not their problem.
#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
forge-1.10.2-12.18.3.2422
Mekanism-1.10.2-9.2.3.97
ThermalExpansion-1.10.2-5.1.10.25-universal
ThermalFoundation-1.10.2-2.1.5.12-universal
JAOPCA-1.10.2-2.0.2.42
jei_1.10.2-3.14.7.416

**Comment by thommy101** [comment]
Do you have a link to the issue from Joapca?

**Comment by Trinsdar** [comment]
Here it is: https://github.com/TheLMiffy1111/JAOPCA/issues/32

**Comment by thiakil** [comment]
Do the recipes work in the machines (but not show in JEI)?

**Comment by Trinsdar** [comment]
They do not work in machines. I tested it with even the ores.

**Comment by thiakil** [comment]
Please post your server log if on server, client log otherwise. There should be messages in there about a mod attempting to add Mekanism recipes

**Comment by Trinsdar** [comment]
here is the log: https://pastebin.com/9cNS52Lm

**Comment by thiakil** [comment]
what about `fml-client-latest.log`?

**Comment by Trinsdar** [comment]
Here is the latest log: https://justpaste.it/1beu6
I had to use a different site because it was too big for pastebin.
Also, I included base metals just to make sure it wasn't a specific mod's ore.

**Comment by thiakil** [comment]
Yeah this is their issue. the ModID in the IMC message is wrong.
