### ISSUE TITLE
dup with gas tanks

### ISSUE THREAD

**Issue by codydbgt** [aidancbrady/Mekanism#4696]
Minecraft: 1.11.2
    SpongeAPI: 6.1.0-SNAPSHOT-c4a7afd
    SpongeForge: 1.11.2-2393-6.1.0-BETA-2549
    Minecraft Forge: 13.20.1.2386

Mekanism-1.11.2-9.3.4-fix.jar

place a stack of empty tanks and put it in a full tank on the ground in the plus slot to fill the hole stack at once

**Comment by thommy101** [comment]
Thanks for reporting!
Will take a look soon. 

Sidenote, probably a regression of 
b24cbb797aea9572a439043538f7393ada0b785d

**Comment by thommy101** [comment]
Temporary disabled stacking, a lot of code assumes they aren't stackable, resulting in this kind of behaviour. Leaving the issue open for a more permanent sollution.

**Comment by thommy101** [comment]
The duplication bug is solved by disabling stacking, re-enabling the stacking is opened in a new feature (there are more similar duplication bugs) in #4765.
