### ISSUE TITLE
[1.7.10] Heat Generator not producing no where near the same amount of power as before.

### ISSUE THREAD

**Issue by llloyd4** [aidancbrady/Mekanism#4697]
Right, let me throw this out there, this is for an older, probably unsupported, version of Mekanism, but, I can at least ask and hope for the best. >.< I seem to remember, in 1.7.10, that a tower of 8 Mekanism Heat Generators producing 80 RF a tick if all 8 were surrounded by lava on 5 sides. I've been playing an old 1.7.10 pack (made up a pack though the Twitch Client) and I am finding the old trick isn't working any more. O.o Each generator is only putting out 1.5 ish RF a tick with 5 sides of lava. I double checked and, yeah, lava source blocks on 5 sides of each one. Under, three sides, and top. Did you nerf it or am I being a derp and my memory is full of swiss cheese? >.< 

#### Version (make sure you are on the latest version before reporting):
**Forge:** 10.13.4.1614
**Mekanism:** 1.7.10-9.1.1.1031
**Other relevant version:**

**Comment by thiakil** [comment]
It appears to be a config option. `heatGenerationLava` should be it.

**Comment by llloyd4** [comment]
Hmm... 5, presumably 5 J , and the wiki says '1 *RF* = 0,1 *MJ* = 2,5 *J* =
0,25 *EU ' *'

So, in theory, it should be making 2 rf a tick, if I want it 10 like the
old days, that would be 25 J I'll have to give that a poke. As I checked,
even Vaygrim said a tower of 8 should produce 80, or 10 per -
https://www.youtube.com/watch?v=6tLXSEasnfY&t=5m5s ...

**Comment by thiakil** [comment]
That's from a much much older version of Mekanism. Lots of things have changed.

See https://github.com/aidancbrady/Mekanism/commit/020d347ee3cc4ec4ce184d409a95e2dfa55ba139

As a summary:
**old**
5 per side of lava
**new**
(1 per side of lava) x heatGenerationLava

The value is indeed in Mekanism J, which also may have changed, and you'd need to look at your config to determine the correct value, as any wiki may or may not be accurate.

**Comment by llloyd4** [comment]
So 1 per side of lava is 5 if it's 5 sides x 5 that is default is 25 J, so
assuming 2.5J per RF is true, 25 J / 2.5 is 10, unless something is going
whistling over my head. O.o At 5 it's producing 1.5 ish RF/t with 5 lava
blocks on 5 of the sides.

**Comment by thiakil** [comment]
> assuming 2.5J per RF is true

Is that what your config says?

**Comment by llloyd4** [comment]
D:JoulesToEU=10.0
    D:JoulesToRF=2.5

Looks like it?

**Comment by thiakil** [comment]
IIRC the calculations are always multiplications. That's why there are both from and to values in the config (at least in modern MC versions)

Did you restart after changing the config?

**Comment by llloyd4** [comment]
Yeap, I closed out Minecraft then once the new config was saved I restarted
Minecraft.

**Comment by thiakil** [comment]
¯\_(ツ)_/¯

**Comment by thommy101** [comment]
Looks like you've dropped your arm, here it is ¯\\_(ツ)_/¯ \ 😄

**Comment by thiakil** [comment]
hahaha don't know why that one never copy pastes properly

**Comment by thommy101** [comment]
Escape characters ;) \ is a special character and escapes stuff

**Comment by llloyd4** [comment]
Guess it is a bug but one that'll never get fixed? Or is 5J per side wrong?
O.o

On Sep 18, 2017 7:20 AM, "Tom E" <notifications@github.com> wrote:

Escape characters ;) \ is a special character and escapes stuff

—
You are receiving this because you authored the thread.
Reply to this email directly, view it o
<https://github.com/aidancbrady/Mekanism/issues/4697#issuecomment-330238118>


n GitHub
<https://github.com/aidancbrady/Mekanism/issues/4697#issuecomment-330238118>,
or mute the

**Comment by thiakil** [comment]
As I said before, the code says `1 x sides with lava x heatGenerationLava` in Mekanism J. I don't particularly care about how much RF that translates to, as that's a separate issue.

If the formula does not hold true we will check it on current versions, but quite unlikely to get fixed on 1.7

**Comment by llloyd4** [comment]
Doesn't seem to be. 5 x 15 should be 75 j and I am not getting that.  So...
And, yeah, I kinda figured it was not gonna get fixed.

On Sep 18, 2017 5:51 PM, "Xander" <notifications@github.com> wrote:

As I said before, the code says 1 x sides with lava x heatGenerationLava in
Mekanism J. I don't particularly care about how much RF that translates to,
as that's a separate issue.

If the formula does not hold true we will check it on current versions, but
quite unlikely to get fixed on 1.7

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/aidancbrady/Mekanism/issues/4697#issuecomment-330396286>,
or mute the thread
