### ISSUE TITLE
crash with pipes StackOverflowError

### ISSUE THREAD

**Issue by codydbgt** [aidancbrady/Mekanism#4699]
don't know the cause ... 

 Minecraft: 1.11.2
    SpongeAPI: 6.1.0-SNAPSHOT-c4a7afd
    SpongeForge: 1.11.2-2393-6.1.0-BETA-2549
    Minecraft Forge: 13.20.1.2386

Mekanism-1.11.2-9.3.4-fix.jar

[crash-2017-09-18_16.47.02-server.txt](https://github.com/aidancbrady/Mekanism/files/1312185/crash-2017-09-18_16.47.02-server.txt)

**Comment by thiakil** [comment]
Yikes, how big is your cable/pipe/tube network? lol
