### ISSUE TITLE
[1.10.2] Weird Container Crash

### ISSUE THREAD

**Issue by MJRLegends** [aidancbrady/Mekanism#4701]
#### Issue description:
Hello so i got this bug reported to me via my mod pack issue tracker, im really not sure to think of it. 

Issue report that was posted to me: https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/issues/126

#### Version (make sure you are on the latest version before reporting):
**Forge:** 12.18.3.2422
**Mekanism:** 9.2.4.103
**Other relevant version:**

**Comment by thiakil** [comment]
Looks like an oversight from the backporting

**Comment by onehappyballoon** [comment]
Is there anything I can do or... ?

**Comment by thiakil** [comment]
You could try using NBTExplorer (or another world editor) to clear the inventory slot in the meantime

**Comment by onehappyballoon** [comment]
I changed my location using NBTExplorer and now everything works. Thanks guys :)

**Comment by MJRLegends** [comment]
@thiakil Dont mean to be a pin but is there any news on the issue to this issue :P

**Comment by thiakil** [comment]
I've been working on a models refactor, so no news :P

**Comment by thiakil** [comment]
@onehappyballoon @MJRLegends are you sure the crash log posted is the one that happens on world load? It points to GUI code which shouldn't be running unless you actually click the GUI...

**Comment by onehappyballoon** [comment]
As I remember it, I logged out perfectly fine and then I couldn't log in anymore. But my memory is not the best, maybe the world crashed and then I couldn't open the world.. quite sure it's the first one though.
The crash log is 100% the right one.

**Comment by thiakil** [comment]
Please try this build http://maven.thiakil.com/mekanism/MekanismAll-1.10.2-9.2.4.103+6f129e14.jar

**Comment by MJRLegends** [comment]
@onehappyballoon Sorry to bother you but are you able to still make it crash or have a copy of the crashing world?

**Comment by onehappyballoon** [comment]
Umm wait, I might have, but if I have it's on the other computer. (I'll reply again as soon as possible, which probably means tomorrow in European time).

**Comment by MJRLegends** [comment]
@onehappyballoon Ok Thank you, please do let me know :P

**Comment by onehappyballoon** [comment]
I do have, can I PM in this forums? (didn't find PMs)

**Comment by MJRLegends** [comment]
@onehappyballoon Please delete the Mekanism, Mekanism tools, and Mekanism generators in the mods folder and put this one in the mods folder http://maven.thiakil.com/mekanism/MekanismAll-1.10.2-9.2.4.103+6f129e14.jar

And then load up the crashing world and see if it crashes with this file

**Comment by MJRLegends** [comment]
@onehappyballoon If you want i can offer voice chat for getting this tested if you prefer, feel free to join my discord: https://discordapp.com/invite/h6VjkKP
