### ISSUE TITLE
[1.10.2] Major Power issue with Mekanism and Modular Powersuits Power Suit

### ISSUE THREAD

**Issue by MJRLegends** [aidancbrady/Mekanism#4702]
So im pretty sure a fix needs to come from Modular Powersuits mod but i will post this here anyways :D 

Modular Powersuits Version: 1.2.124
Forge Version: 12.18.3.2422
Mekiansm Version: 9.2.4.103

See https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/issues/127 for detals since everything is posted in that issue :D

**Comment by thiakil** [comment]
More than likely their issue, but please let us know if that turns out not to be the case

**Comment by MJRLegends** [comment]
Modular Powersuits Power Suit devs have confirmed and said it was there bug :D @thiakil
