### ISSUE TITLE
Dynamic Tank crash server again

### ISSUE THREAD

**Issue by Lyror** [aidancbrady/Mekanism#4703]
I had this issue before. Here the old Issue: https://github.com/aidancbrady/Mekanism/issues/4670

Now i get this exception again.

Mekanism versions:
Mekanism-1.12.1-9.4.1.326
MekanismGenerators-1.12.1-9.4.1.326
MekanismTools-1.12.1-9.4.1.326

The new Crashlog: https://pastebin.com/0sYtjjH6

**Comment by thiakil** [comment]
Yay, recursion \o/
