### ISSUE TITLE
FrequencyManager.removeAll doesn't work as intended

### ISSUE THREAD

**Issue by josephcsible** [aidancbrady/Mekanism#4710]
https://github.com/aidancbrady/Mekanism/blob/89e10b1d9d0399ca821c30db3f416638522ee723/src/main/java/mekanism/common/frequency/FrequencyManager.java#L121

This is seeing if a `UUID` equals a `String`, which will always be false, since they're different types. That leads to this whole method effectively becoming a no-op. (I'm not sure whether `user` is supposed to be a UUID, or if it should be checking `iterFreq.name` instead of `iterFreq.ownerUUID`, and I can't find the code that calls this method to check there.)

**Comment by thiakil** [comment]
Yeah looks like an oversight. IDEA agrees that it's unused.

**Comment by thommy101** [comment]
That method could probably be removed. Some parts of the code are in need of "some" cleanup
