### ISSUE TITLE
[Possibly a feature] Jetpack goes down really fast when HP changes

### ISSUE THREAD

**Issue by kraft2004** [aidancbrady/Mekanism#4720]
This is a problem specially in the Nether, where sometimes you get hit by Blazes shooting fire at you. I've died two times to that and nearly died many other times in my newest world.

I hope this is not a feature.

Edit: That just killed me again. Very awesome, such cool, much nice.

**Comment by thiakil** [comment]
What exactly do you mean by "goes down"? The vanilla thing where it adds downwards motion to the player, or the fuel level?

**Comment by kraft2004** [comment]
It adds downwards motion, basically throwing the player to the ground.
Hadn't noticed that it was Vanilla. Welp.

**Comment by thommy101** [comment]
If you turn on hovering mode you don't get that downwards motion, makes it a lot easier in the nether.

**Comment by aidancbrady** [comment]
Would be tough to fix something like this. I still would like to add some kind of "glide mode" in the future that would allow easy horizontal movement.
