### ISSUE TITLE
Server crashes while joining

### ISSUE THREAD

**Issue by Destroyer4LP** [aidancbrady/Mekanism#4722]
#### Issue description:
Server crashes while joining. I am not  what happend.
I hope the Crash log helps you

#### Steps to reproduce:
I am not sure since it happened on my Server while I was ofline.

#### Version (make sure you are on the latest version before reporting):
**Forge: forge-1.10.2-12.18.3.2488
**Mekanism: 1.10.2-9.2.4.103
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
[crash-2017-09-26_19.18.07-server.txt](https://github.com/aidancbrady/Mekanism/files/1337887/crash-2017-09-26_19.18.07-server.txt)

https://pastebin.com/U4GUHW4B

**Comment by thiakil** [comment]
#4374
