### ISSUE TITLE
[1.12.1] An error occured while connecting to URL

### ISSUE THREAD

**Issue by UnPure** [aidancbrady/Mekanism#4723]
#### Issue description:
While starting the server/client Mekanism is producing an error while trying to connect to URL's.
Seems like the URL's have changed to something else or are removed completly while Mekanism is still searching for them.

    [10:43:13] [Thread-5/ERROR] [Mekanism]: An error occured while connecting to URL 'http://aidancbrady.com/data/versions/Mekanism.txt.'
    [10:43:13] [Thread-5/ERROR] [Mekanism]: An error occured while connecting to URL 'http://aidancbrady.com/data/capes/Mekanism.txt.'

#### Steps to reproduce:
1. Start Mekanism
2. Look at the logs.
3. ???
4. Profit!

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.22.0.2475
**Mekanism:** 9.4.1.326

**Comment by thommy101** [comment]
They have been changed recently, but those are the good values. Could you try and open the pages?
http://aidancbrady.com/data/capes/Mekanism.txt
http://aidancbrady.com/data/versions/Mekanism.txt

Can you also provide a fml-client-latest.log file? This should contain a detailed description of what went wrong.

**Comment by thiakil** [comment]
@thommy101 I've been noticing it myself even in dev, note that the url inside the quotes has a full stop at the end.

**Comment by thommy101** [comment]
The dot on the end is an error with the logging ;) Sadly it doesn't print the actual error.
