### ISSUE TITLE
Fusion Reactor Tick error

### ISSUE THREAD

**Issue by Redthebuilder** [aidancbrady/Mekanism#4725]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description: Fusion Reactor activation causes game crash with a BLOCK ENTITY TICK ERROR (reactorport tick). I've tried in creative, crashes every time as soon as I turn on the lasers. I've used several tutorial videos that you link to on the wiki page to check my set up. I can't find the problem.

I'm submitting on a Mac, but I have the same problem on my pc, don't know if that could be relevant.

I can't find any reasoning for this, I'd really appreciate your help.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 13.20.1.2386
**Mekanism:** 9.3.4 fix
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[crash-2017-09-29_09.50.12-server.txt](https://github.com/aidancbrady/Mekanism/files/1344859/crash-2017-09-29_09.50.12-server.txt)

**Comment by josephcsible** [comment]
Hmm, this reminds me of #4645 (though it's not the exact same thing). See if installing [CoFH Core](https://minecraft.curseforge.com/projects/cofhcore) does anything.

**Comment by thiakil** [comment]
Ummm, that should never happen in 1.11 as we bundle the api :/

I'd advise removing mods one by one until it doesn't happen

**Comment by thommy101** [comment]
Looks like some other mod packages an other version of the rf api... Either we are outdated (don't think they make such a breaking change), or someone had added a corrupt api..

**Comment by thommy101** [comment]
Small addition, do you have a normal startup log (fml-client-latest.txt or the server equivalent). That should contain which api gets loaded from where

**Comment by Redthebuilder** [comment]
I'm removing all other mods and running the test with exclusively your mods, (Mekanism, generators & tools) I'm going to run a test like that right now and I'll let you know how it goes, I do have that log for you, just in case/maybe you can tell me which one is actually causing me issues and I can remove it. I love your mod it's great fun, and I apologize about taking so long to get back to you. RL getting in the way of the important things in my life.


[fml-client-latest.log](https://github.com/aidancbrady/Mekanism/files/1346879/fml-client-latest.log)

**Comment by thiakil** [comment]
That latest.log appears to be from 1.10?

**Comment by thiakil** [comment]
Mekanism and Immersive Engineering appear to be the only ones in your list that bundle the erroring API

**Comment by Redthebuilder** [comment]
Ok, I took out all other mods, and it works great. I then put Immersive engineering back in and couldn't recreate the error, It may be on that same line I have several of those Immersive's, but I'll put them back in one by one, It does fix my problem though. I appreciate your guys help. As soon as I find the offending mod I'll respond in this thread to let future Mekanism players know there is an issue. I'm prepared to call that solved. Thanks again!
