### ISSUE TITLE
Chisel&Bits/ForgeMultipart not functioning properly with Mekanism

### ISSUE THREAD

**Issue by Xopharios** [aidancbrady/Mekanism#4728]
Issue description:
When trying to use Chisel&Bits (v13.14) or ForgeMultipart (v2.2.0.41) in conjunction with Mekanism (v9.3.4-fix) for Minecraft 1.11.2, Forge version 13.20.1.2476, I get improper functionality with cables, and pipes.

![ForgeMultipart](https://i.imgur.com/HpccdYc.png)
![Chisel&Bits](https://i.imgur.com/9eB1vKz.png)

When attempting to apply a 'cover' or 'bit' it simply does not work as it should/used to

Steps to reproduce:
1. Place Pipe/Cable
2. Attempt to apply ForgeMultipart or Chisel&Bits parts
3. Failure

#### Version (make sure you are on the latest version before reporting):
**Forge: 13.20.1.2476
**Mekanism: v9.3.4-fix 
**Chisel&Bits: v13.14
**ForgeMultipart 2.2.0.41

**Comment by thiakil** [comment]
What exactly does not work?

**Comment by Xopharios** [comment]
The ''Multipart'' in ForgeMultipart for example. The covers would normally snap onto the cable, but as you can see in the top picture above, I can only get the cover to snap just outside of the cable. This is the same issue with Chisel&Bits, where I can't place the bits on or around the cable

**Comment by thommy101** [comment]
The multipart of FMP isn't supported, we only support MCMP (Mcmultipart) . The C&B is a bit weird, as that's supposed to work as it's MCMP.

**Comment by Xopharios** [comment]
I updated my Mekanism to 9.3.5.206 and reinstalled my McMultipart. But now stuff like this happens on our server
![Cable Break](https://i.imgur.com/tA21B37.png)
![Cable Break](https://i.imgur.com/nfoYyAZ.png)

**Comment by thiakil** [comment]
Is the rendering failing to look connected *only* when C&B is on the part?

**Comment by Xopharios** [comment]
Unfortunately, no. I recorded this [Video Demonstration](https://youtu.be/cmZ3dPL2BcI) of the effect, to allow you to better understand the effect it is having when I try linking universal cables together. 
The same effect can be seen when connecting to machinery as well, and stretches across all types of cable. WIth the logistical cables however, it actually stops the item from progressing through the pipe

**Comment by thiakil** [comment]
Any chance you've tried this with just Mek/MCMultipart/C&B installed? I've not played any of Mek in 1.11 so can't say I've seen it.

**Comment by thommy101** [comment]
Well.. That's a first.. I've played almost every version (singelplayer and multiplayer) an this is something I haven't seen before. It looks like a mod or something is messing with the blockstates causing it not to render the connection correctly.

Is the power being transferred or is it only a render glitch?

**Comment by Xopharios** [comment]
No, power has not 'apparently' been affected by this glitch. Logistic Pipes, however, as you can see in the video above, actually stops the pipe from transferring items, until said pipe is fixed. I should also remind that this is only an issue on multiplayer, and though I forgot to add before since I didn't think it was important, I am running SpongeForge 6.1.0-BETA with Nucleus 1.1.3, PEx 2.0, VoxelSniper Sponge 8.4.1, FastAsyncWorldEdit 17.09.24 and Worldedit Forge 6.1.6

**Comment by Xopharios** [comment]
UPDATE: This is definitely an issue caused directly by sponge. After temporarily removing it, the cables and pipes worked properly, as they should. I'm not sure, however, what to do now that I've figured this out

**Comment by thiakil** [comment]
Oh good, I don't have to suggest trying without Sponge  xD

I would suggest reporting to them, as Sponge is a very invasive core mod that does things forge mods don't anticipate. That's why it gets a lot of hate.
