### ISSUE TITLE
Issue with Refined Storage mod, 

### ISSUE THREAD

**Issue by Diamond45123** [aidancbrady/Mekanism#4731]
#### Steps to reproduce:
1. IDK
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 13.20.1.2425
**Mekanism:** 9.3.4
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here:  https://pastebin.com/uAigUfg9

[gist/pastebin/etc link here]

**Comment by thommy101** [comment]
What do you mean with "it just keeps on crashing". Does it crash when loading a world, does it crash when opening the wireless grid?

Also, you're one version behind ;)

**Comment by Diamond45123** [comment]
It keeps crashing when i open the wireless grid, And my version is 1.9.4-fix
i cant find a version more then that.

**Comment by Diamond45123** [comment]
According to the issue : https://github.com/raoulvdberge/refinedstorage/issues/1477
This is a problem with item name implementation

**Comment by thommy101** [comment]
It is indeed an issue with the naming, but this should never happen... There seems to be an invalid item in the RS system.

Latest version is 9.3.5, available on curseforge

**Comment by Diamond45123** [comment]
I updated to 9.3.5 and still the same problem, I tried to access the RS System using a Pattern Grid, but same crash happened again. https://pastebin.com/Hs0LjT9z

**Comment by Diamond45123** [comment]
just something to mention, this happened after i finished my tier 2 ore proccessor, which is the only thing thats putting items into the RS system automatically, although im using a thermal expansion furnace, cause i want all of the ingots to be in thermal expansion oredict

**Comment by thiakil** [comment]
+1 to `you have an invalid item in your system`

Best we can do is safely return `invalid` for the name, but whatever item(s) are there will need to be trashed

**Comment by thiakil** [comment]
Fixed in 589346011dd307061bb8c9c2ec540e45d83fdaf5

**Comment by Diamond45123** [comment]
So, what should I exactly do? I don't want to literally trash a whole drive so I can remove the Mekanism invalid item.

**Comment by thommy101** [comment]
The next release will contain a fix so it won't crash, that way you can look and identify the "corrupt" Mekanism block and trash it.

**Comment by Diamond45123** [comment]
Thanks, last thing. Estimated release time? Sorry in advance.

**Comment by thommy101** [comment]
All I can say is soon, there are multiple fixes which should be released on short terms.

**Comment by thiakil** [comment]
@Diamond45123 since it looks like you're on Single Player, you can use http://maven.thiakil.com/Mekanism/1.11.2-9.3.5.206+2f7bf80/Mekanism-1.11.2-9.3.5.206+2f7bf80.jar

**Comment by Diamond45123** [comment]
@thiakil I tried the mod and now got this crash : https://pastebin.com/kgUUvwam
make an issue on galactic craft github?

**Comment by thiakil** [comment]
Yeah seems same  issue but with a GC item :/
