### ISSUE TITLE
UBifyOres not fully supported for Digital Miner

### ISSUE THREAD

**Issue by DEX47** [aidancbrady/Mekanism#4732]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Digital Miner appears to be unable to input the identity of UBifyOres ores from UndergroundBiomes Example: 'UndergroundBiomes:Metamorphic_oreCoal'. Use of a wildcard prefix does not work. Unable to enter in block names due to character limitations. Unable to enter Block IDs.

Had limited success with ItemStack filter however fuzzy logic did not work and thus it was limited to the specific block only. Having over 20 variants of each type of ore makes this option not an option.

#### Steps to reproduce:
Install Mekanism: 1.7.10-9.1.1.1031 and UndgergroundBiomesConstructs 1.7.2-0.7. Use digital minter with UBifyOres 'Metamorphic ores'

#### Version (make sure you are on the latest version before reporting):
Forge- 10.13.4.1614
Mekanism: 1.7.10-9.1.1.1031
UndgergroundBiomesConstructs 1.7.2-0.7

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
Try using oredict. Otherwise it's probably their issue and we no longer support 1.7

**Comment by DEX47** [comment]
Am I using the oredict wrong? because 'oreCoal' and '*oreCoal' did not work.

**Comment by thiakil** [comment]
`oreCoal` should be correct, *if* they're registered

**Comment by DEX47** [comment]
When did you terminate 1.7 support? I was surprised to hear that since an update came out a few weeks ago.

**Comment by thommy101** [comment]
The version released a couple weeks ago was a needed fix due to some external changes. Beside that 1.7 only had 3 other commits in the past 10 months.
