### ISSUE TITLE
[1.10] Tinkers Crafting station With Mekanism solar panel causes a crash

### ISSUE THREAD

**Issue by MJRLegends** [aidancbrady/Mekanism#4734]
See https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/issues/139

When trying to craft with the Basic solar panel in a crafting grid it crashes
Crash log for this issue https://pastebin.com/DALANh9h

#### Version (make sure you are on the latest version before reporting):
**Forge:** 12.18.3.2422
**Mekanism:** 9.2.4.103
**Other relevant version:** Mod pack: https://minecraft.curseforge.com/projects/space-astronomy-2

**Comment by thommy101** [comment]
I thought this issue was fixed... Apparently not.
Altough, it could be that it's only fixed in 1.11 and above. Try turning off the item rendering option of Tinkers Construct, should be a workaround to this issue.

**Comment by MJRLegends** [comment]
No problem

**Comment by thommy101** [comment]
Slightly more info:
In the file `tconstruct.cfg` set `S:renderInventoryInWorld` to `false`.

Please let me know if that solves it ;)

**Comment by MJRLegends** [comment]
will test in the next 30 mins :D

**Comment by MJRLegends** [comment]
@thommy101 Yeah this fixes the issue

**Comment by thommy101** [comment]
Glad to hear! :D

**Comment by MJRLegends** [comment]
Is there any chance this could be fixed so this option can be true again?

**Comment by thommy101** [comment]
We kinda dropping support for 1.10 (atleast for the non-crashing bugs), but as this is a crashing one, maybe we will backport the fix from 1.11 (or 1.12, don't remember where it's fixed)

**Comment by MJRLegends** [comment]
Yeah i understand, and i understood and remembered the knowledge that it was just crash fixes mekansim were only doing for mc 1.10.2. thanks for your time

**Comment by thiakil** [comment]
That stack trace is different from the old tinkers crash, which was fixed in 5243ac56b7b7b5d74338812d64dd539766219812

The crashlog doesn't actually mention Mekanism in the stack trace, so I'm not sure it's us this time.

**Comment by MJRLegends** [comment]
@thiakil Maybe but all i know is its only crashing with the Mekanism basic solar panel

**Comment by thiakil** [comment]
[This thing?](http://wiki.aidancbrady.com/wiki/Solar_Generator) That has no custom rendering stuff (nor its ingredients), so definitely not us.

Furthermore, its crashing when drawing the tab at the top of the window.
```
-- Item being rendered --
Details:
    Item Type: slimeknights.tconstruct.tools.common.item.ItemBlockTable@119f3959
```

Bookshelf & CClib are both touching the render pipeline before it hits MC code, so it's likely their fault.

**Comment by MJRLegends** [comment]
@thiakil Yeah but if thats the case why only that solar generator that is having the issue with it? The problem i got is tinkers isnt updated MC 1.10.2....

**Comment by thiakil** [comment]
How do you expect us to know what's causing it, when it's not crashing in our code?

**Comment by MJRLegends** [comment]
Im trying to work it out now to what mod is causing the issue :D

**Comment by MJRLegends** [comment]
It doesnt seem to be either codechicken lib or bookshelf mod so i will do some testing and find out what mod it is

**Comment by MJRLegends** [comment]
Ok so it doesnt seem to be mekanism @thommy101 @thiakil Thanks for your time with this issue :D
