### ISSUE TITLE
Mekanism generators dont output energy to buildcraft pipes.

### ISSUE THREAD

**Issue by Diamond45123** [aidancbrady/Mekanism#4735]
#### Steps to reproduce:
1. place any type of generator
2. connect it to a buildcraft pipe
3. and itll not output energy

#### Version (make sure you are on the latest version before reporting):
**Forge:** 10.13.4.1614
**Mekanism:** 9.11
**Other relevant version:** buildcraft 7.1.22

picture : https://i.imgur.com/RJdaozq.png

**Comment by thiakil** [comment]
1.7 is not supported. No idea if that ever worked.
