### ISSUE TITLE
1.12.1 Formulaic Assemblicator does not work (version 9.4.0 Mekanism)

### ISSUE THREAD

**Issue by EliogabalusPL** [aidancbrady/Mekanism#4736]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
The device does not activate the production capability after inserting any items of production. It is connected to the power supply. For a better understanding of how a YouTube movie is running, https://www.youtube.com/watch?v=3GhHcNagJ84
Unfortunately nothing helped.

#### Steps to reproduce:
1. Set the Formulaic Assemblicator
2. I connect the Formulaic Assemblicator to the power supply
3. I lay in the window crafting the raw materials in the right pattern
4. I'm trying to change the way the power is
5. Buttons: - Craft Single Itemand Craft Items Items are inactive all the time although the device has electricity and is fully charged.

#### Version 
Minecraft 1.12.1
forge-1.12.1-14.22.1.2479-universal
Mekanism:  9.4.0
**Other relevant version:** 
additional modules Mekanism:
Mekanism-Mod-Generators-1.12.1
Mekanism-Mod-Tools-1.12.1

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

P.S. I used the next device of this module to create a translation into Polish, because the translation file you have put in the module is very outdated and is smaller than the original by 60% and variables by 30%

**Comment by thommy101** [comment]
Could you please try the newest release for 1.12.1? An older version contained a bug causing the behaviour you've described.

**Comment by EliogabalusPL** [comment]
Hello

Thank you for the information. I'm already checking.
I am in the process of translating Mekanism into Polish. The translation that is added to the module is completely incompatible. It has only 534 lines when the original has 1118. In addition, some of the variables have been changed by the makers of Mekanism, and in the Polish version still appear old.

The file pl_pl.lang (currently in Beta2) has already been fully translated, but requires polishing, hence my detailed testing of the module.
If you are interested in a file that translates modules into Polish please contact me.
Regards
Eliogabalus (aka PC_Maniac)

BTW Here I describe my progress with the translation: http://forum.minecraft.pl/topic/30223-t%C5%82-the-popular-mod%C3%B3w-na-pl/
  Sorry, the site is in Polish.


Wysłane z aplikacji Poczta<https://go.microsoft.com/fwlink/?LinkId=550986> dla Windows 10

Od: Tom E<mailto:notifications@github.com>
Wysłano: czwartek, 5 października 2017 08:48
Do: aidancbrady/Mekanism<mailto:Mekanism@noreply.github.com>
DW: EliogabalusPL<mailto:pc_maniac@hotmail.com>; Author<mailto:author@noreply.github.com>
Temat: Re: [aidancbrady/Mekanism] 1.12.1 Formulaic Assemblicator does not work (version 9.4.0 Mekanism) (#4736)


Could you please try the newest release for 1.12.1? An older version contained a bug causing the behaviour you've described.

**Comment by thommy101** [comment]
Updated translations are always welcome, you can create a pull request with the updated Polish translations. We can't check them all, but we will ofcourse throw a couple through google translate to make sure you didn't write crap.

Please let me know if the original issue has been solved :)

**Comment by EliogabalusPL** [comment]
I downloaded the latest 4 files of Mekanism module:
- Mekanism-1.12.1-9.4.1.326.jar
- MekanismGenerators-1.12.1-9.4.1.326.jar
- MekanismTools-1.12.1-9.4.1.326.jar
- Mekanism-1.12.1-9.4.1.326-api.jar
When you start the game with all 4 files, the game will crash.
After deleting the file Mekanism-1.12.1-9.4.1.326-api.jar, the remaining games start correctly.

As for my reports with GitHub: Formulaic Assemblicator works fine.
Flamethrower is aiming correctly, M mode change does not work either on bow or Flamethrower. If I have any errors in testing, I'll let you know.

Regards
Eliogabalus (aka PC_Maniac)

Wysłane z aplikacji Poczta<https://go.microsoft.com/fwlink/?LinkId=550986> dla Windows 10

Od: Tom E<mailto:notifications@github.com>
Wysłano: czwartek, 5 października 2017 10:39
Do: aidancbrady/Mekanism<mailto:Mekanism@noreply.github.com>
DW: EliogabalusPL<mailto:pc_maniac@hotmail.com>; Author<mailto:author@noreply.github.com>
Temat: Re: [aidancbrady/Mekanism] 1.12.1 Formulaic Assemblicator does not work (version 9.4.0 Mekanism) (#4736)


Updated translations are always welcome, you can create a pull request with the updated Polish translations. We can't check them all, but we will ofcourse throw a couple through google translate to make sure you didn't write crap.

Please let me know if the original issue has been solved :)

**Comment by thommy101** [comment]
You've downloaded one file too much, as you've found out. The API is only needed when you compile mods against Mekanism. I've described the mode switching issue at the other two issues.

I'll close this issue as it's solved, but if you've got any questions, you can ask them here.

**Comment by EliogabalusPL** [comment]
I used to work on creating visual elements for games, servers, and modules (though it was in the very early days of Neverwinternights).

By browsing your website http://wiki.aidancbrady.com/wiki/Main_Page I noticed that you are focusing too much on the question of what the device is creating, completely bypassing or simply mentioning how to configure it.
I understand that it is very laborious to describe such elements, but it is quite easy - just use the instructional videos on Youtube and attach them to your device description.

As far as the older version of your module did not have a complicated device, unfortunately these devices now have so many options that no description of their configuration can discourage players.
The best example is Formulaic Assemblicator, where information is very modest.
Many players do not notice that even pipe tips can be configured using the Configurator. These videos would help to understand aspects of the module without even knowing the language.
Such a small cosmetic change would spread your work around the world

Regards
Eliogabalus (aka PC_Maniac)

Wysłane z aplikacji Poczta<https://go.microsoft.com/fwlink/?LinkId=550986> dla Windows 10

Od: Tom E<mailto:notifications@github.com>
Wysłano: czwartek, 5 października 2017 11:03
Do: aidancbrady/Mekanism<mailto:Mekanism@noreply.github.com>
DW: EliogabalusPL<mailto:pc_maniac@hotmail.com>; Author<mailto:author@noreply.github.com>
Temat: Re: [aidancbrady/Mekanism] 1.12.1 Formulaic Assemblicator does not work (version 9.4.0 Mekanism) (#4736)


You've downloaded one file too much, as you've found out. The API is only needed when you compile mods against Mekanism. I've described the mode switching issue at the other two issues.

I'll close this issue as it's solved, but if you've got any questions, you can ask them here.

**Comment by EliogabalusPL** [comment]
As for the translation to pl_pl.lang, I think Beta tests will take me about 7 days. I do not want to supply you with a product that I would later be ashamed of.

As for the Mekanism module itself, I would have a few questions, but I do not want to bother you. I will find answers on Youtube.

It is not a good idea to use Bin with the left mouse button, because in Creative mode, the player always clicking the left or left button with SHIFT destroys the Bin.

Regards
Eliogabalus (aka PC_Maniac)



Wysłane z aplikacji Poczta<https://go.microsoft.com/fwlink/?LinkId=550986> dla Windows 10

Od: Tom E<mailto:notifications@github.com>
Wysłano: czwartek, 5 października 2017 10:39
Do: aidancbrady/Mekanism<mailto:Mekanism@noreply.github.com>
DW: EliogabalusPL<mailto:pc_maniac@hotmail.com>; Author<mailto:author@noreply.github.com>
Temat: Re: [aidancbrady/Mekanism] 1.12.1 Formulaic Assemblicator does not work (version 9.4.0 Mekanism) (#4736)


Updated translations are always welcome, you can create a pull request with the updated Polish translations. We can't check them all, but we will ofcourse throw a couple through google translate to make sure you didn't write crap.

Please let me know if the original issue has been solved :)

**Comment by EliogabalusPL** [comment]
Hello

I have a problem with the meaningful translation into Polish of the term "Thermal Evaporation Plant".

Has the device you placed in the module called Thermal Evaporation Plant is not a Desalination Plant?



Regard

Eliogabalus (aka PC_Maniac)

**Comment by thommy101** [comment]
The old name of the thermal evaporation plant was salination plant, but it's more than just that. So it's deffinitly a thermal evaporation plant, not a desalination plant. I don't know if you know some German, but that translation is pretty spot on.

**Comment by EliogabalusPL** [comment]
I know German because I was learning it at school (I am English myself) so most of the descriptions I did from German. Thank you for the quick reply.


Regards
Eliogabalus (aka PC_Maniac)

Wysłane z aplikacji Poczta<https://go.microsoft.com/fwlink/?LinkId=550986> dla Windows 10

Od: Tom E<mailto:notifications@github.com>
Wysłano: piątek, 6 października 2017 19:37
Do: aidancbrady/Mekanism<mailto:Mekanism@noreply.github.com>
DW: EliogabalusPL<mailto:pc_maniac@hotmail.com>; Author<mailto:author@noreply.github.com>
Temat: Re: [aidancbrady/Mekanism] 1.12.1 Formulaic Assemblicator does not work (version 9.4.0 Mekanism) (#4736)


The old name of the thermal evaporation plant was salination plant, but it's more than just that. So it's deffinitly a thermal evaporation plant, not a desalination plant. I don't know if you know some German, but that translation is pretty spot on.

**Comment by EliogabalusPL** [comment]
Sorry to interrupt again, but unfortunately I can not find a place where 2 sentences with variables change. What makes the lack of context impossible for me to translate these sentences logically.
It is about the sentence:
1- tooltip.configurator.toggleMode =  % s behavior bumped to
2- tooltip.configurator.viewMode =   Current% s behavior
Would you be able to send complete sentences that occur with sample variables (changing the color of a fragment that is just that variable)?
This would allow me to translate these sentences in a proper way with the variable.

I hope you have disturb last time.

Greeting
Eliogabalus (aka PC_Maniac)

**Comment by thommy101** [comment]
Those two sentences are being used by the configurator when you right click on a block which can be configured.
Right click for `tooltip.configurator.viewMode`
Shift + right click for `tooltip.configurator.toggleMode`

**Comment by EliogabalusPL** [comment]
I do not know if you read replies in closed topics on GitHub, so I decided to reply also via Mail.


After all, in Just Enough Items this sort is used and even on JeI Mod servers are working properly, so how come the objection?

1. I do not understand why words in local languages ​​can not be used in search? After all, Just Enough Items Mod. We type the word in the local language, and the script translates the word into the variable used in the xx_xx.lang file. All variables used in xx_xx.lang files are identical.
Even on the server the item variable names are identical, otherwise the names could not be translated. This solution is used in Just Enough Items Mod

2. The current system used to sort the "Create New Filter" items is not enough if the player is not playing in Creative mode. Why? Let's try to sort the Coal, Redstone, Egg, Bone or Flint without having them in the backpack.
a) Item function - requires using the item to program the device (not suitable)
b) The Dictionary - item dictionary does not even detect items such as Coal, Redstone, or Flint, as in the rest of Vanilla in the Miscellaneous tab (not suitable).
c) Function Material - too broad sorting concept, with the rest of what raw is Coal or Egg? (unsuitable)
d) Mod ID - This is the ID of the module itself, because typing ID Coal or 263 Coal does not exist.

The current system simply does not search for a very large number of items, which in the case of a game in a different mode than Creative (where we can manually add items) it 's impossible to program at least 100-150 items only from Vanilla.

Regards
PEliogabalus (aka  PC_Maniac

**Comment by thommy101** [comment]
please only respond on the corresponding github issues.. Replying by mail wil only add an extra comment on issues ;)

**Comment by EliogabalusPL** [comment]
If I have a serious problem with translating a good way to check the translation is to write to google the original text and translate it back into English. The difference after this operation will show if a meaningful translation is used.
Unfortunately for these 2 sentences the variables I sent you are based on all logic because I do not know what the author meant by writing "Fluids/Gasses/Items behavior bumped to".

After using rotational translation, "Fluids/Gasses/Items retention after impact in ..."
In the Polish language the word "bumped" means "after the crash, after the collision, after impact ".
I do not think that was the point in this sentence?

Can you describe me in my own words (without thinking short) what does this sentence mean?
The German version did not help me this time. The sentence is simply too short to understand its meaning.

Regards
Eliogabalus (aka PC_Maniac)
Wysłane z aplikacji Poczta<https://go.microsoft.com/fwlink/?LinkId=550986> dla Windows 10

Od: Tom E<mailto:notifications@github.com>
Wysłano: sobota, 7 października 2017 15:36
Do: aidancbrady/Mekanism<mailto:Mekanism@noreply.github.com>
DW: EliogabalusPL<mailto:pc_maniac@hotmail.com>; Comment<mailto:comment@noreply.github.com>
Temat: Re: [aidancbrady/Mekanism] 1.12.1 Formulaic Assemblicator does not work (version 9.4.0 Mekanism) (#4736)


Those two sentences are being used by the configurator when you right click on a block which can be configured.
Right click for tooltip.configurator.viewMode
Shift + right click for tooltip.configurator.toggleMode

**Comment by thommy101** [comment]
> "Fluids/Gasses/Items behavior bumped to"

Fluid/Gasses/Items behaviour changed to. It's displayed after you've changed the behaviour to another mode (it cycles through all available modes). Smack a machine with a configurator and it should display ;)

**Comment by EliogabalusPL** [comment]
THX


You had some fun with inventing non-existent names..
For example Paxel: D
I changed it to Polish associated Lopasiekilof (Polish names - Lopata-Siekiera-Kilof - trans.eng - Shovel-Axe-Pickaxe).

I think you used the same associations in Paxel.

**Comment by thommy101** [comment]
It's not me who wrote that ;) I'm "just" an active contributor.

**Comment by EliogabalusPL** [comment]
Phew, (wipes sweat from forehead). This was my most difficult job with the translation of the Mekanism module.
What I did not manage to translate myself properly also helped me as an administrator on the Polish Minecraft forum ( http://forum.minecraft.pl/topic/30223-t%C5%82umaczenia-popularnych-mod%C3%B3w-na-pl/ ) and my wife.
I tried to make the translation not 100% literal but logical for the module and in terms of device descriptions - understandable for the players.


Did my work make sense and I have done it well enough to judge the players in Poland.

Now I'm getting a translation of another module (what my daughter asked me).


Regards
Eliogabalus (aka PC_Maniac)

**Comment by thommy101** [comment]
Feel free to open a pull request to add the Polish translation, that way everyone could benefit from it without a manual download. If you're unable to, you could share the file so I can add it.

**Comment by EliogabalusPL** [comment]
On Github?


Wysłane z aplikacji Poczta<https://go.microsoft.com/fwlink/?LinkId=550986> dla Windows 10

Od: Tom E<mailto:notifications@github.com>
Wysłano: poniedziałek, 9 października 2017 21:37
Do: aidancbrady/Mekanism<mailto:Mekanism@noreply.github.com>
DW: EliogabalusPL<mailto:pc_maniac@hotmail.com>; Comment<mailto:comment@noreply.github.com>
Temat: Re: [aidancbrady/Mekanism] 1.12.1 Formulaic Assemblicator does not work (version 9.4.0 Mekanism) (#4736)


Feel free to open a pull request to add the Polish translation, that way everyone could benefit from it without a manual download. If you're unable to, you could share the file so I can add it.

**Comment by thommy101** [comment]
Yea, a pull request or as file. Looks like your pull request is a bit messed up btw
