### ISSUE TITLE
1.12.1 Flamethrower (version 9.4.0 Mekanism) 

### ISSUE THREAD

**Issue by EliogabalusPL** [aidancbrady/Mekanism#4737]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Flamethrower - button M does not change mode.
Targeting, in contrast to bow, is completely accidental.

#### Steps to reproduce:
1. I set the Flamethrower as a hand weapon
2. Click on M (all mode Combat mode is on)
3. I try to aim at cows even from close range. The flame does not fly towards the target.

#### Version (make sure you are on the latest version before reporting):

Minecraft 1.12.1
forge-1.12.1-14.22.1.2479-universal
Mekanism: 9.4.0
Other relevant version:
additional modules Mekanism:
Mekanism-Mod-Generators-1.12.1
Mekanism-Mod-Tools-1.12.1

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thommy101** [comment]
Changing mode is sneak key + item switch key (default shift + M).
The flamethrower completely missing it's target is fixed in the latest release, please update ;)
