### ISSUE TITLE
1.12.1 Electric Bow (version 9.4.0 Mekanism) 

### ISSUE THREAD

**Issue by EliogabalusPL** [aidancbrady/Mekanism#4738]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
You can not change weapon mode with any key

#### Steps to reproduce:
1. I set a charged energy bow as a hand weapon
2. Click the M button (fire mode is off all the time)
3. Mode of the item does not change

#### Version (make sure you are on the latest version before reporting):
Minecraft 1.12.1
forge-1.12.1-14.22.1.2479-universal
Mekanism: 9.4.0
Other relevant version:
additional modules Mekanism:
Mekanism-Mod-Generators-1.12.1
Mekanism-Mod-Tools-1.12.1

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thommy101** [comment]
Same as your issue with the flamethrower, you need to sneak and press the button. The default for this is shift + M
