### ISSUE TITLE
Steam Turbine Lag

### ISSUE THREAD

**Issue by dataxel** [aidancbrady/Mekanism#4739]
#### Issue description:
I have an enormous NuclearCraft steam fusion reactor attached to a maximum size MekGen steam turbine, and when the steam enters the turbine in large quantities, I experience massive server wide tick lag and extreme user end lag.

#### Steps to reproduce:
1. Start fusion process in steam reactor and gain a notable amount of steam generation (upwards of 100000mb/t).

![mekerror2](https://user-images.githubusercontent.com/4468725/31263116-8f302bb6-aa0c-11e7-9998-406e20f9a5ba.png)
![mekerror3](https://user-images.githubusercontent.com/4468725/31263117-90e7c2ca-aa0c-11e7-8c02-401554f834b8.png)
![mekerror1](https://user-images.githubusercontent.com/4468725/31263110-88102c78-aa0c-11e7-869e-79c49bbf5488.png)

2. Change steam turbine from dump mode, allowing it to gain steam and begin to function.
3. Dense steam travels through a field of steam decompressors to enter the turbine. Epic lag ensues.
4. If I turn the Turbine back to dump mode (which takes forever because it's lagging pretty badly) the tick loss immediately stops and things return to normal.

#### Version (make sure you are on the latest version before reporting):
**Forge: 7.10.99.99
**Mekanism: 9.1.0.281
**Other relevant version: MC 1.7.10

**Comment by thiakil** [comment]
Sorry, we no longer support 1.7

The steam turbine is designed around the Mekanism Reactor

**Comment by dataxel** [comment]
Wow.
