### ISSUE TITLE
Localisation key conflicts

### ISSUE THREAD

**Issue by D3nnis3n** [aidancbrady/Mekanism#4740]
Should be self-explanatory, so i just post an Image:
https://ibb.co/mR3B5b

--Edit by Thommy101--
Mekanism doesn't use "Mekanism-specific" localisation keys, causing issues with other mods using the same localisation keys.
Happens mainly with guis and liquids.

**Comment by D3nnis3n** [comment]
Same for portable teleporters.

**Comment by thommy101** [comment]
Are you using any custom language packs? As that value ("Are you sure you want to delete this?") isn't part of our default localisation.

**Comment by D3nnis3n** [comment]
No, i'm not. I use PureBDCraft as Resource Pack for Skins, other than that, nothing.

**Comment by D3nnis3n** [comment]
What can i do to find out which mod is fucking up something there?

**Comment by thommy101** [comment]
Aah... I could see what's happening.. There seems to be a localisation key conflict. We (sadly) do not use a Mekanism specific localisation key.
It seems another mod is also using `gui.delete`, with the value you're seeing. You could try to add a en_us.lang file in a resourcepack with the following in it (just a plain text file) as a temporary solution:

`gui.delete=Delete`

**Comment by D3nnis3n** [comment]
Thank you! :)

**Comment by thiakil** [comment]
Essentially the same as #4698 but worse

**Comment by thommy101** [comment]
Somehow i couldn't find that issue...
