### ISSUE TITLE
Mekanism isn't compatible with Forge multipart CBE?

### ISSUE THREAD

**Issue by Diamond45123** [aidancbrady/Mekanism#4741]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. install Forge multipart CBE from chickenbones.net
2. place a mekanism cable
3. and try to place a cover on it

#### Version (make sure you are on the latest version before reporting):
**Forge:** latest version
**Mekanism:** 9.3.5
**Other relevant version:**  forge multipart 2.2.0.39
https://imgur.com/a/YJSDp

**Comment by thommy101** [comment]
Sorry, but Mekanism currently only supports MCMultiPart. ForgeMultiPart isn't supported.

**Comment by thommy101** [comment]
MCMultiPart is only a library, other mods could use it to add covers. One of the most well known for MCMP is [Chisels & Bits](https://minecraft.curseforge.com/projects/chisels-bits).

**Comment by Diamond45123** [comment]
sorry to bother you again, but how do i place covers on the side of cables? there isn't any wiki around here

**Comment by 18iteration** [comment]
Anyone encountering this in the future: Uodating Forge Multipart in the mods->1.7.10 folders fixed the issue.
Don't assume you have the latest version, verify yourself.
