### ISSUE TITLE
Logistical Sorter 1.12.1 - different look

### ISSUE THREAD

**Issue by EliogabalusPL** [aidancbrady/Mekanism#4742]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
The Logistical Sorter has a completely different look. (The Logistical Sorter is quite different in appearance (http://wiki.aidancbrady.com/w/images/aidancbrady/b/bd/Logistical_Sorter.png).
In the drawings, the mounting flanges are clearly different in the 1.12 version. The difference in size is imperceptible, so that players often install the Logistical Sorter in reverse and are frustrated that the device is not working at all. I suggest either restoring the look of the instruction images or (which would be a much more intuitive solution) using the directional arrows on the sides of the device. (information from many users of the module)

#### Steps to reproduce:
1. Change the look of the mounting flanges 
2. or add directional arrows on the device walls
3.

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.12.1-14.22.1.2479-universal
**Mekanism: Mekanism-1.12.1-9.4.1.326
**Other relevant version: MekanismTools-1.12.1-9.4.1.326 and MekanismGenerators-1.12.1-9.4.1.326

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
Wiki is well out of date - most pages contain pre texture update screenshots

**Comment by EliogabalusPL** [comment]
This does not change the fact that the appearance at present makes it much harder to understand the operation of the element.

**Comment by thiakil** [comment]
I don't see how the old look makes it any easier to understand input/output sides
