### ISSUE TITLE
Seismic Reader - add a description (SHIFT + M)

### ISSUE THREAD

**Issue by EliogabalusPL** [aidancbrady/Mekanism#4743]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
The Seismic Vibrator is based on the SHIFT + M keypad, but unfortunately most users try to use Seismic Reader first, and they have no idea how this device works. It's easy for English-speaking gamers to use the module's Web site. It would be sufficient to add a description of the Seismic Reader when you press SHIFT + M

#### Steps to reproduce:
1. Add a description of Seismic Reader by pressing SHIFT + M on it
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.12.1
**Mekanism:* 1.12.1
**Other relevant version: additional modules Mekanism

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thommy101** [comment]
Created a PR to add some information to the tooltip ;)
