### ISSUE TITLE
Static Teleporter - no "Teleport" button (1.12.1)

### ISSUE THREAD

**Issue by EliogabalusPL** [aidancbrady/Mekanism#4746]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
In static telepathy (built on the ground), it is possible to adjust one teleport with the other static, as shown by the "V" stamp in the upper left corner. The intention of the creator was probably to include static teleports also can be combined into pairs. Unfortunately there is a button that activates the teleportation, same as the Portable version. And the entrance to the teleport frame does not have any effect.

#### Steps to reproduce:
1. Make a static teleport button "Teleport" or "Use"
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.1
**Mekanism:** 1.12.1
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thommy101** [comment]
Sorry, but I do not understand the issue here. You cannot link two teleporters to each other?

**Comment by EliogabalusPL** [comment]
Can you just pair them up if there is no button to teleport between them?

**Comment by thiakil** [comment]
The in-world version works like a nether portal; you step into it. Please ensure you build a frame to do so as the block by itself can only receive.
