### ISSUE TITLE
Chargepad does not work in all situations. (1.12.1)

### ISSUE THREAD

**Issue by EliogabalusPL** [aidancbrady/Mekanism#4747]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Chargepad does not load static devices, although it has a connection, even if the Chargepad itself is connected to the power supply and should work as a relay/transmitter.
In the http://wiki.aidancbrady.com/wiki/Chargepad statement, "Any rechargeable item you have in your inventory will be charged while standing on it."
Unfortunately, when standing on a charger with a discharged Configurator, it is not charged.

#### Steps to reproduce:
1. Check why the rear Chargepad connector does not have power.
2.  Check if the Configurator is in the inventory or in the hand is not charging while standing on Chargepad.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.1
**Mekanism:** 1.12.1
**Other relevant version:  

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thommy101** [comment]
I cannot replicate this in the latest version. The code also hasn't changed for the whole release of 1.12.1.

My steps to reproduce:
1. Place a chargepad & a full energy cell on the back
2. Have a bunch of empty configurators in my inventory (hotbar, and some at random places in my inventory)
3. Stand on the chargepad
4. Look at inventory and see them charged one by one, starting at the hotbar on the left, to the right, main inventory from top left to bottom right.

Are you having an (empty) chargepad in your inventory? That also stores energy, you only don't see the damage indicator indicating it's storing energy.
Try standing on a charge pad for atleast one minute. It should atleast give some particles indicating it's active when you stand on it.
