### ISSUE TITLE
No mention of MTLib being required for CraftTweaker support

### ISSUE THREAD

**Issue by josephcsible** [aidancbrady/Mekanism#4750]
If MTLib isn't installed, CraftTweaker support doesn't work. However, this isn't indicated in any way. It's not mentioned in any documentation, it's not listed as an optional library on CurseForge's dependencies page, and it doesn't give you an error or warning that it's missing if you try to use our CraftTweaker features without it (instead just inexplicably failing). The only way you could possibly know about MTLib is if you actually looked at #4641.

**Comment by thommy101** [comment]
We'll add some documentation about it soon :)

**Comment by thommy101** [comment]
Added a page to the wiki with some basic explanation. Link on the main page will come, I currently do not have permission to add it there.

http://wiki.aidancbrady.com/wiki/Tutorials/CraftTweaker
