### ISSUE TITLE
Extend the "Create New Filter" with a new search function by the variable name from the translate file (to be used in the future version of the module)

### ISSUE THREAD

**Issue by EliogabalusPL** [aidancbrady/Mekanism#4754]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Selecting a function in the "Create New Filter" window would be worthwhile in the future to develop one more, more useful function.
We now have a choice:
1. Use the item we have in the window
2. Use the window name acquired from the Dictionary
3. Material
4. Mod ID

Would there be a chance in the future edition (n.1.13) to add a window named after its own name to the player so that the player could use the names from the translate files?
It would be very user friendly, especially from countries whose languages do not resemble English at all (Cyrillic, Chinese, Korean, Japanese).

#### Steps to reproduce:
1. Use the variable from the translate file to find the item
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by josephcsible** [comment]
So what happens on a multiplayer server, when two players have their games set to different languages, and they both try to add filters to the same sorter? I think this (and anything else that would make gameplay depend on localization) is a bad idea.

**Comment by thiakil** [comment]
This is not really feasible as localisation is not possible server side (other than english)

**Comment by EliogabalusPL** [comment]
After all, in Just Enough Items this sort is used and even on JeI Mod servers are working properly, so how come the objection?

1. I do not understand why words in local languages ​​can not be used in search? After all, Just Enough Items Mod. We type the word in the local language, and the script translates the word into the variable used in the xx_xx.lang file. All variables used in xx_xx.lang files are identical.
Even on the server the item variable names are identical, otherwise the names could not be translated. This solution is used in Just Enough Items Mod

2. The current system used to sort the "Create New Filter" items is not enough if the player is not playing in Creative mode. Why? Let's try to sort the Coal, Redstone, Egg, Bone or Flint without having them in the backpack.
a) Item function - requires using the item to program the device (not suitable)
b) The Dictionary - item dictionary does not even detect items such as Coal, Redstone, or Flint, as in the rest of Vanilla in the Miscellaneous tab (not suitable).
c) Function Material - too broad sorting concept, with the rest of what raw is Coal or Egg? (unsuitable)
d) Mod ID - This is the ID of the module itself, because typing ID Coal or 263 Coal does not exist.

The current system simply does not search for a very large number of items, which in the case of a game in a different mode than Creative (where we can manually add items) it 's impossible to program at least 100-150 items only from Vanilla.

**Comment by josephcsible** [comment]
1. Because JEI runs entirely on the client, but the item sorter runs on the server.
2. Why exactly is option A not suitable?

**Comment by EliogabalusPL** [comment]
josephcsible:
ad 1. Are there other variables on the server in the lang files than on the client? I doubt it.
ad 2. And how do you throw in an item item you do not own?
Do not know how to enter a name or ID in A (version 1.12.1) if no text entry window?

**Comment by josephcsible** [comment]
1. Minecraft's architecture is such that the server is never supposed to use the translation files. Those are meant to be a client-only resource, just like textures and sounds.
2. Does the + button in JEI let you do this? It's generally the standard way to add virtual items that you don't have a real one of.

**Comment by EliogabalusPL** [comment]
So, according to you, how to add Coal Redstone, Flint, Bone etc. to the sort without having these items?
Probably a solution that eliminates 100-150 items only from Vanilla alone is a serious problem?

Elon Musk says that if something can not be done, it means that whoever says it can not do it, not that it can not be done at all.

**Comment by thommy101** [comment]
I agree with @josephcsible on this one.. It's not feasable to implement something like you want.
Regarding your quote of Elon Musk, it's true what he said, only if you are in control of it all. We aren't in control of Minecraft & Forge. We can't change it so that the server knows every language, which is by the way client side adjustable without the server knowing.

**Comment by josephcsible** [comment]
> So, according to you, how to add Coal Redstone, Flint, Bone etc. to the sort without having these items?

Again, the plus sign button in JEI.

**Comment by EliogabalusPL** [comment]
The "+" button in JEI 1.12.1 does not cause any reaction. In Controls, the keys for JEI are only CTRL + F and CTRL + O, the same "+" is not programmed.

**Comment by josephcsible** [comment]
Not the + key on your keyboard. There's a + on-screen button in the recipe GUI.

**Comment by thiakil** [comment]
The current filters are all you should need. The ore dictionary filter can do most of the 'I want this ore but don't have it' uses, and the ItemStack can do the rest. 

I don't like the idea of just being able to type in an item name, and I seem to recall talk of that being denied previously.

**Comment by EliogabalusPL** [comment]
josephcsible:
Hm, we have different versions of JEI. In my recipe GUI only icon with the letter "i" (Information?) Is displayed.

In the picture http://www.img4.9minecraft.net/img2/Just-Enough-Items-Mod-5.jpg there is such an icon - I do not have it.

**Comment by josephcsible** [comment]
@thiakil Personally, I wouldn't mind being able to filter items by registry name.

@EliogabalusPL It's right under the "1" in "Steps: 1" in that screenshot. (Also, eww 9minecraft).

**Comment by EliogabalusPL** [comment]
@josephcsible In the picture I see those damn + but the problem is that in my Minecraft with JEI on the same prescription they are not there. Maybe version 1.12.1 has been removed?

**Comment by josephcsible** [comment]
It has not been removed. Is there any button there?

**Comment by thommy101** [comment]
AFAIK mods need to add support for the + button (or something else) to allow JEI to fill in stuff like item filters. I don't know if any other mod has added support like this, I can only think of things that are similair that could have support, but I don't know for sure. ItemFilter from EnderIO, RefinedStorage/AE2/AL2 with their filters.

**Comment by EliogabalusPL** [comment]
@josephcsible 
I am sending you a link from my recipe window (there is + in it):
https://1drv.ms/i/s!At_Q76MtyFIHhwtavxlDRL8BgEHV

**Comment by josephcsible** [comment]
@thommy101 Good point. Other mods with item filters all support that button, so I assumed we would too. We really should add support for that ourselves.

**Comment by thommy101** [comment]
We currently do support the + for crafting recipes in the formulatic assembler & robit crafting grid.

@josephcsible If you know (for sure) a mod which supports it for item filters (or something like it), I would love to know about it. Adding support (if possible) should be doable.

**Comment by josephcsible** [comment]
Integrated Dynamics supports making item variable cards that way.

**Comment by EliogabalusPL** [comment]
Hm, but it's good that I was interested in this topic. Because it can solve this problem in a different way.

**Comment by thommy101** [comment]
I'll create a separate issue about the + integration for the filters ;) (it's not something which is done in 5 min)
