### ISSUE TITLE
quantum tank and item pipe crash

### ISSUE THREAD

**Issue by mortinho** [aidancbrady/Mekanism#4755]
#### Issue description:
quantumstorage's quantum tank and a logistical transporter pipe with a pull connection crashes the server on every atempt to load

#### Steps to reproduce:
1.place quantum tank down
2.place any type of logistical transporter attached to it
3.change connection with the configurator until pull mode

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.22.1.2485
**Mekanism:** 9.4.1.326
**Other relevant version:** minecraft 1.12.1 - QuantumStorage 4.4.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
[crash-2017-10-09_12.39.59-server.txt](https://github.com/aidancbrady/Mekanism/files/1369069/crash-2017-10-09_12.39.59-server.txt)

**Comment by thommy101** [comment]
There's only one way that line would crash, and that is when another mod screws things up badly.

Technical stuff:
We check if there's an IItemHandler capability, that check passes (the other block indicates: we've got this capability)
We get the capability and use it -> Crash.. This would indicate there isn't a capability although we explicitly checked for it.
