### ISSUE TITLE
Game crash sporadically (1.12.2)

### ISSUE THREAD

**Issue by LordHellscream** [aidancbrady/Mekanism#4758]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Game randomly crashed

#### Steps to reproduce:
1. Happens randomly

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2501
**Mekanism:** 9.4.1.326

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/HTRnw4fS

**Comment by thommy101** [comment]
Duplicate of #4700, which is fixed and will be available in the next release.
