### ISSUE TITLE
(1.12.2) poof! crashes.

### ISSUE THREAD

**Issue by Migmag789** [aidancbrady/Mekanism#4761]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
So many glitches...

#### Steps to reproduce:
1. Got Beyond the Minecraft
2. Start a new world
3. Go in the nether

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.0.2512
**Mekanism:** 9.4.1.326
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/Vwxbbh11

[gist/pastebin/etc link here]

**Comment by thommy101** [comment]
Please use the search functionality, there's exactly the same issue 3 issues below yours.
