### ISSUE TITLE
Fluid Glitch With Stacked Tanks

### ISSUE THREAD

**Issue by Zedrimar** [aidancbrady/Mekanism#4762]
#### Issue description:
If tanks are crafted (shift click) and they stack, when collecting a fluid in bucket mod, ALL tanks in the stack get that amount of fluid. So a stack of 16 tanks would automatically get 1 bucket in each rather than splitting off a tank and filling that tank only

#### Steps to reproduce:
1. mass craft 16 fluid tanks at once so MC makes them stack (when they have no "owner)
2. collect a fluid in bucket mode with the whole stack

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12 (*.2512)
**Mekanism:** 9.4.1.326

**Comment by thommy101** [comment]
Oh, crap, yet another one... Tested everything with this kind of duplication and missed this one... Will fix soon ;) (at least a workaround till I've time to good fix it)

**Comment by Zedrimar** [comment]
wow XD

**Comment by thommy101** [comment]
The duplication bug is solved by disabling stacking, re-enabling the stacking is opened in a new feature (there are more similar duplication bugs) in #4765.

**Comment by Zedrimar** [comment]
ah, that works for now
