### ISSUE TITLE
Digital Miner does nothing when Silk Touch is activated

### ISSUE THREAD

**Issue by D3nnis3n** [aidancbrady/Mekanism#4764]
#### Issue description:
When activating the silk touch Feature in the digital miner, the digital miner just stops working, even though "All well" is shown. The ore Counts no longer down and no ore is delivered.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2513
**Mekanism:** 9.4.1.326

I don't know if this is a bug, or has any other reason, as i never used Silk Touch in the miner before.
There is enough electricity, as the digital miner is fed by a creative engine, as i'm atm using it to check if my worldgen is as i want it.

**Comment by thiakil** [comment]
From discussions on discord seems like a two parter:

* some blocks are failing to silk touch and process does not continue
* enabling silk while running might not correctly activate

**Comment by Leonyx1175** [comment]
I can confirm this, even after silk touch is turned off, miner continues to stall. I tried replacing it with another and using a creative energy cube and the new one stalls as well, without silk touch turned on.
