### ISSUE TITLE
You can not use the transporters on the back in the Bins

### ISSUE THREAD

**Issue by EliogabalusPL** [aidancbrady/Mekanism#4769]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Basic Bin / Advanced Bin / Elite Bin / Ultimate Bin can not be turned so that it can be connected to the back of Logistical Transporter. Connecting from the top will cause a big loss of space, and most players are trying to hide behind the crates.

#### Steps to reproduce:
1. Enable the selection of the box/Bin side to attach the transporter
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thommy101** [comment]
Duplicate feature request of #3735
