### ISSUE TITLE
mekanism generators crash when placed

### ISSUE THREAD

**Issue by snergle69** [aidancbrady/Mekanism#4770]
#### Issue description:
Crafting any kind of generator and placing it down crashes the game with the error java.lang.NoSuchFieldError : allowProtection.  If I creative the generator in and place it there is no crash, I'm just wondering if there is a solution for placing the crafted one.  Also, after restarting minecraft the generator is placed and it works fine.

Thanks

#### Version:
**Forge: 1.7.10 - 10.13.4.1614** 
**Mekanism: 1.7.10 - 9.1.0.281** 
**Other relevant version: Mekanism Generators: 1.7.10 - 9.1.1.1031** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/xvyZWhFP

**Comment by thiakil** [comment]
```
Mekanism{9.1.0} [Mekanism] (Mekanism-1.7.10-9.1.0.281.jar)
MekanismGenerators{9.1.1} [MekanismGenerators] (MekanismGenerators-1.7.10-9.1.1.1031.jar)
```

Your Mekanism & MekanismGenerators, MekanismTools versions **must** match

**Comment by snergle69** [comment]
oh damn, didn't realize, thank you
