### ISSUE TITLE
[1.12.2] Chisels & Bits covers cause an instant crash

### ISSUE THREAD

**Issue by Buggy123** [aidancbrady/Mekanism#4771]
#### Issue description:

Attempting to place a Chisels & Bits (MCMultiPart) cover onto a Mekanism gas pipe instantly crashes the game. Mousing over the pipe while holding a cover will also crash.

Interestingly, it does still place the cover; once you load up the game the cover will be in place and working normally.

In some cases, a crash while looking at a pipe will lock you out of a world, as when you load in you'll still be looking at the pipe and you will instantly crash again.

#### Steps to reproduce:
Tested only in singleplayer.
1. Place Mekanism gas pipe (untested with other pipes)
2. Craft a Chisel & Bits cover using a Diamond Saw (tested only with thinnest panel made of obsidian)
3. Place onto or look at gas pipe while holding the cover.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.0.2512
**Mekanism:** 9.4.1.326
**Other relevant version:** Chisel & Bits 0.0.14.18, MCMultiPart 2.3.3

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
Placement crash log: https://pastebin.com/gaJh8eQa
Mouseover crash log: https://pastebin.com/ThbcuvZC

**Comment by thiakil** [comment]
both are C&B issues. Please report to them

**Comment by Alphanos** [comment]
It's possible this is entirely coincidental and unrelated, but part of your described crash sounds kind of similar to the crash I was running into with Tinkers.  No effect on the server, crash occurs when moving/placing the problematic item, and game works okay with item in place after restarting.  [https://github.com/aidancbrady/Mekanism/issues/4798](https://github.com/aidancbrady/Mekanism/issues/4798).  From your mod versions and crashlogs, it sounds like there it a good chance that you may also have been running All the Mods 3.

Buggy123, is there any chance you could test to see if editing config/forge.cfg and setting B:alwaysSetupTerrainOffThread=false fixes your crash?  Sorry if this is unrelated, but if this is a broader issue affecting a few sorts of things, then that would be nice to confirm.

**Comment by thiakil** [comment]
No, it is a very different cause.
