### ISSUE TITLE
Hell biome greater than 2.0 temperature multiplier?

### ISSUE THREAD

**Issue by ouroborus** [aidancbrady/Mekanism#4772]
Any chance the Hell biome can get a greater than 2.0 temperature multiplier?

**Comment by thiakil** [comment]
What machine is this for?

**Comment by thommy101** [comment]
That would be either the Thermal Evaporation tower or the Heat Generator if I'm correct?

**Comment by thiakil** [comment]
That was my thought, but I can't find it referenced in the 1.12 branch any longer xD

**Comment by thommy101** [comment]
Heat generator still has it, haven't found the T.Evap yet:
https://github.com/aidancbrady/Mekanism/blob/1.12/src/main/java/mekanism/generators/common/tile/TileEntityHeatGenerator.java#L204
