### ISSUE TITLE
Cable/Pipe Malfunction

### ISSUE THREAD

**Issue by Satrman** [aidancbrady/Mekanism#4773]
Issue description:
So, I've already looked through closed issues and found a similar group of people having the issue, but on an older version of mekanism here: https://github.com/aidancbrady/Mekanism/issues/2733

This is occuring with all pipes/wires, the server is running Mekanism, Generators, and Tools 9.4.1 for all.

Steps to reproduce:
The way to reproduce this never seems to be consistent, we've only been able to narrow down that is has to do with chunk loading and de-loading, as it never occurs 100% of the time, and the example picture i've pasted into this is at my location.

Having teleporter blocks with anchor upgrades littered around the place seems to be the only way we have to stop this from occuring, and even it doesn't always work.

Version (make sure you are on the latest version before reporting):
**Forge: Mod Loader 8.0.99.99, and Minecraft Forge 14.22.0.2475** 
**Mekanism: As stated above, 9.4.1** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]
![image](https://user-images.githubusercontent.com/32682998/31675935-0f1c54fa-b334-11e7-9d2b-41806318988e.png)

![image](https://user-images.githubusercontent.com/32682998/31676053-6851e58a-b334-11e7-9130-a29cf15303c6.png)

My apologies if i'm placing this in the wrong place or not including enough information, as I haven't really done this sort of thing much but this problem is coming up too often for us to ignore.

I can offer more information upon request.

**Comment by thommy101** [comment]
It does sound a lot like issue #4676. Can you confirm with a network reader (or something) that the cable which malfunctions has no network?

**Comment by Satrman** [comment]
I'm not too sure what that is.  Do you mean any kind of machine that takes a power input?

**Comment by Satrman** [comment]
The problem does sound very similar after rwading it, however the problem can crop up as soon as i connect to the server.

**Comment by Satrman** [comment]
Something else of note I just noticed when setting up another anchored teleporter block: Trying to connect a cable to a group of cables that was already running power through it(and was supplying it to machines fine) would not draw energy from the old cables to the new, despite the old ones working fine.

Also, placiing energy cubes seems to help sometimes? Some of the cables that run out of cubes work fine, while the only one that breaks consistenty is in the supplied pictures above.
For the old cables to the new working fine cables: 
![image](https://user-images.githubusercontent.com/32682998/31693899-17957158-b36f-11e7-84db-0b4e2c640854.png)

Also, picture of logistical sorters not working as to the right there is a mob spawner room where the relocators are operating fine but the items are not being removed via pipe: 
![image](https://user-images.githubusercontent.com/32682998/31693923-3dcf31a6-b36f-11e7-8bb5-a95a18550672.png)

![image](https://user-images.githubusercontent.com/32682998/31693926-447bb9de-b36f-11e7-88ab-245906cc5b85.png)

**Comment by thiakil** [comment]
Yeah this is the same as the other cable issues. @thommy101 did we backport the 1 fix we did make so far?

**Comment by thommy101** [comment]
@thiakil Looks like 9801b12b62d93a21b8ed5774fcb6f38fd847980a isn't in 1.10.

> Can you confirm with a network reader (or something) that the cable which malfunctions has no network?

@Satrman Could you please confirm the thing I asked earlier? The network reader is an item from Mekanism which you could craft.

**Comment by Satrman** [comment]
Just checked the network reader, two readings came up on the cable
 

![image](https://user-images.githubusercontent.com/32682998/31718285-54977a2e-b3dd-11e7-920e-356e875b93a0.png)  

![image](https://user-images.githubusercontent.com/32682998/31718301-66b122d2-b3dd-11e7-8f4a-072197d55fe0.png)

**Comment by Satrman** [comment]
The reading on the 2nd picture continues to the energy cube down the line, which is 15 pieces of cable away from where I took the readings, from which the cable going in and another cable going out are working fine.

**Comment by thommy101** [comment]
Looking at the two picture (and the coordinates from your minimap) it is indeed the same as #4676.

The breakage point is exactly on a chunk border, and some transmitters do not have a network. Two of the indicators it's the same issue.
It's an issue which is still on our radar, but we haven't found the fix for it yet.

**Comment by KittenKoder** [comment]
This MUST be fixed. I am going to have to reset my world completely because of this.

**Comment by Satrman** [comment]
A temporary fix for this that i've been using to some success is placing Teleporter Blocks with Anchor Upgrades every chunk, and using Quantum Entangeloporters to shorten then number of both pipes/cables/sorters and teleporters.

It's an expensive way, but it works until this gets fixed.
