### ISSUE TITLE
The unfortunate thing is that the device does not require power supply as "Disabled"

### ISSUE THREAD

**Issue by EliogabalusPL** [aidancbrady/Mekanism#4774]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Specifies in the en_us.lang translation file that the device is not required for power operation is "Disabled". I believe that this term may mislead the user and should be "Not required", which makes it clear that no power supply is required for operation.

#### Steps to reproduce:
1. Change in the English variable (file en_us.lang) the term "control.disabled=Disabled" to "control.disabled=Not Required".
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
The terminology is correct. `Disabled` refers to the Redstone control.
