### ISSUE TITLE
Extension of the function of the Digital Miner for harvesting / harvesting (for future use)

### ISSUE THREAD

**Issue by EliogabalusPL** [aidancbrady/Mekanism#4775]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Can the Digital Miner's functions be extended in the future for the ability to collect fruits / yields?
Unfortunately, this is not possible because Digital Miner can collect blocks, not apple or beet.
You can not program it to collect items from the fields. And it would be worthwhile to allow players to use Digital Miner for such work, because the device can work as a harvester of trees, unfortunately not their fruits / vegetables
#### Steps to reproduce:
1. Extend the functions of the Digital Miner to collect fruits / vegetables / crops from fields.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
It's a miner, not a harvester. As for Leaves, when mining leaves that would normally drop apples for example it should acquire apples.

**Comment by EliogabalusPL** [comment]
Well, it is worth thinking about adding in the future version of Mekanism some sort of harvester for harvesting agricultural crops. When it comes to vegetables, hand harvesting is quite a hassle. Unfortunately, when the "Pam's HarvestCraft" module is installed, the fruit does not fall off the tree, even when the tree no longer exists. The object in the form of fruit is hanging in the air and only clicking on it causes the fruit to fall to the ground. In theory, it would be possible to add to the Digital Miner the name of the object that is in the air to get it, and thus the fruit fell to the ground. And the fruit of the earth would gather Robit. Unfortunately, clicking on the Dictionary gives the answer "No key.", So the object is unrecognizable for the module.
