### ISSUE TITLE
Solve the problem of lagging the game through pipes.

### ISSUE THREAD

**Issue by EliogabalusPL** [aidancbrady/Mekanism#4776]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I noticed that the tubes transporting the forearms cause a lot of lag in the game. I suspect that the cause is transport animation through these pipes or a complicated way of configuring the junction, which anyway does not work because it can not block the pipe branch in any other way than by color, although in theory you can use the configurator to select (unfortunately not working in the case of pipe intersections) Push / Pull / None functions.

When the tube is not in sight (eg the player is facing backwards) the lag disappears. Unfortunately, when it is visible on the elpie the lag is intensified. If you use a lot of pipes (eg to transport items into boxes), the lag becomes a nightmare in the game.

#### Steps to reproduce:
1. Minimize tube animation, for example, only to display moving lights when the item is being transported, instead of visualizing the item in the tube.
2. Check if unnecessary, because the inoperative configuration of pipe ends at tube intersections does not cause lag.
3. The problem of lag does not apply to power cables.

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.12.1
**Mekanism: 1.12.1
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thommy101** [comment]
There's already an option to disable the animation. 
Change the following to true:
B:OpaqueTransmitterRender=false
