### ISSUE TITLE
Unable to configure module settings in Minecraft Modules Config

### ISSUE THREAD

**Issue by EliogabalusPL** [aidancbrady/Mekanism#4777]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
It would be wise to transfer the mod configuration to the Modules List/Config in game instead of the unmanageable and uncomfortable manual configuration in the mekanism.cfg file.

The creators of the Biomes O'Plenty module have done aesthetically. You should see how they did it.
#### Steps to reproduce:
1.Transfer the mod configuration to the Modules List in the game, instead of the unequal and inconvenient manual configuration in the mekanism.cfg file.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
in game config does exist and will be fixed in the next release
