### ISSUE TITLE
Mechanical Pipe halves fluid throughput to turbine

### ISSUE THREAD

**Issue by ghost** [aidancbrady/Mekanism#4778]
#### Issue description:
I'm using one of TE's magmatic dynamos to produce steam, it says it's producing 600mB/t of steam, turbine says it's receiving 300mB/t. I replaced it with a super-laminar fluiduct and it receives 600mB/t as it should.

#### Steps to reproduce:
1. Build turbine and magmatic dynamo, connect water/lava as needed
2. Connect dynamo to turbine with mechanical pipe
3. Compare dynamo output to turbine

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.0.2512
**Mekanism: 9.4.1.326

https://imgur.com/gallery/KloXS

Edit: Network reader is showing 2 acceptors: https://imgur.com/gallery/Rm7wK

**Comment by ouroborus** [comment]
@Leonyx1175 Is the power output consistent with a 300mB/t input or a 600 mB/t input when using the mechanical pipe?

**Comment by Leonyx1175** [comment]
It's consistent with what it should be at 300mB/t with the pipe, it seems, around half what it is with the fluiduct. One moment and I'll grab some numbers for ya.

**Comment by Leonyx1175** [comment]
It's also being halved from a 3x3x4 boiler setup, boiler shows 120mB/t out, turbine shows 60 mB/t in.

**Comment by thiakil** [comment]
I cannot see via your images or your text what tier of Mechanical Pipe you are referring to?

Please also ensure you are setting the mechanical pipe to pull mode, as auto eject is generally slow, by design.

**Comment by Leonyx1175** [comment]
I tested all tiers with the same result, but it appears to be the turbine being set to dump excess, not the pipes specifically. I'm currently unable to test it any farther, I'll give you an update in the morning if it can't be reproduced.

**Comment by Leonyx1175** [comment]
Tried setting the pipe to push into the turbine, and it still halves steam input when set to dumping/dumping excess. Setting it to pull from the dynamo stops it completely. I removed all mods except the TE suite and Mekanism +Generators, and it still shows 300 mB/t when set to dumping or dumping excess, and 600 on idle.
