### ISSUE TITLE
An absurd (unnecessary) recipe for the Purification Chamber (Mekanism-1.12.1) 

### ISSUE THREAD

**Issue by EliogabalusPL** [aidancbrady/Mekanism#4779]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
In the Purification Chamber we can create Flint using gravel and flint. It does not make sense. Why waste a lot of flint to create ... flint?
For this I completely lack the recipe as from the gravel itself to create a flint.

#### Steps to reproduce:
1. Remove in the recipe required as a flint raw material to create from the gravel as the final flint product.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:1.12.1-9.4.1.326
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by EliogabalusPL** [comment]
The problem is more complicated because by combining 2 devices into a chain, one of them always sends no products. I will try to create this test chain in a smaller structure and I will only describe the problem (or I will find the cause).

**Comment by josephcsible** [comment]
The purification chamber needs oxygen for everything, and that's available from gas tanks or from flint. It also happens to be able to create flint. I don't see an actual bug here.

**Comment by thiakil** [comment]
the only flint recipe i can see in the code is `gravel + oxygen -> flint`, so I'm not sure where you're getting a flint from flint recipe.

Please show a screenshot illustrating.

**Comment by EliogabalusPL** [comment]
Proszę, tutaj zrzut ekranu pokazujący recepturę. Nie pamiętam ile krzemienia potrzeba do stworzenia krzemienia, ale chyba muszę użyć 10 itemów aby uzyskać 1 szt krzemienia, co jest bzdurą.
https://1drv.ms/i/s!At_Q76MtyFIHhw5bgSAW-TETe1Jy

**Comment by thiakil** [comment]
I believe the purple slot is for the gas input, so that looks like a bug with the JEI integration only. No idea where the 10 items thing is coming from.

**Comment by EliogabalusPL** [comment]
A better option would be to add a recipe to the crusher eg 2 blocks of gravel for 1 flint.

**Comment by thiakil** [comment]
Why though?

**Comment by EliogabalusPL** [comment]
When Gravel and Flint are dropped, the unit consumes 10 flints before producing 1 flint. Check out these ingredients from the photo. So, rather, it's not just the JEI wine, because the device actually uses these ingredients.

**Comment by thiakil** [comment]
Then show me the machine doing this; your image only shows JEI

**Comment by EliogabalusPL** [comment]
If the cause was in JEI then Gravel + 10 Flint = 1 Flint would work and one unit would actually work after inserting these components. So, in the scripts, it allows for the selection of components.

Why though?
Because I did not find the recipe for obtaining Flint from the gravel outside the hand picking a gravel block.

**Comment by EliogabalusPL** [comment]
Please, here I give 3 screenshots from the next stages of production.
Ops, to produce 2 flints need about 40 flints!
1. https://1drv.ms/i/s!At_Q76MtyFIHhxBwt4ocmpGbjy_t
2. https://1drv.ms/i/s!At_Q76MtyFIHhxH8KhdsQENdmspj
3. https://1drv.ms/i/s!At_Q76MtyFIHhw9BMM2YNZCH63af

**Comment by EliogabalusPL** [comment]
I also have serious problems creating a chain of production boxes - Smelting Factory - Formulaic Assemblicator. I repeatedly checked all connections. And if something works properly it would seem that everything is fine. Unfortunately, when I move away from this chain of machines and after some time I return to the factory, it turns out that once again the Chest of Smelting Factory does not work and the tubes do not take the raw material. The only way to fix it is to destroy the pipes and reposition them, even without changing the configuration of the equipment. Only if you move away from the device again will cause you to stop working and not resume it. I do not know if I should report this problem separately because it is quite complicated and frustrating.

I add that the described production chain I run in the game as a client on the server.

**Comment by thiakil** [comment]
I've looked into this further, and there is no issue regarding flint in the Purification Chamber - Flint is a source of oxygen.

The pipes issue is a known issue. See #4676

**Comment by EliogabalusPL** [comment]
If Flint is the source of oxygen, it makes no sense to create Flint on this device. I would suggest moving Flint from Gravel to Crusher.

**Comment by josephcsible** [comment]
Flint is **a** source of oxygen, not **the** source. Most people get their oxygen by separating water. And a change like that would break a lot of existing setups for no real gain.

**Comment by EliogabalusPL** [comment]
Sand is quite easy to get raw. Flint does not. I still think it would be logical to use a sandstone crusher to get sand. Although, as I wrote, it is easier to sand directly from the biomes than the flint. All the more so since there is no way to obtain flint than to split the gravel manually, which is a very laborious task.

**Comment by josephcsible** [comment]
The purifier is the way to get flint. Just feed it oxygen from separating water.

**Comment by thiakil** [comment]
Flint is a form of quartz, which contains oxygen. It makes sense to be able to make it and to use it as a source in the same machine. The end.
