### ISSUE TITLE
[1.10.2] OpenComputers support not working

### ISSUE THREAD

**Issue by MJRLegends** [aidancbrady/Mekanism#4780]
#### Issue description:
When trying to connect OC cable to any Mekanism Multi Block it doesnt connect or give any information out

#### Version (make sure you are on the latest version before reporting):
**Forge:** 12.18.3.2511
**Mekanism:** 9.2.4.103
**OpenComputers:** 1.6.2.7

**Comment by thiakil** [comment]
I'm fairly certain you need an Adapter interface thingy

**Comment by MJRLegends** [comment]
Oh is that a thing.. is it from open computers?

**Comment by thiakil** [comment]
It sure is

**Comment by MJRLegends** [comment]
Ok thanks for your help. Sorry to bother you :)

**Comment by thiakil** [comment]
Please do let us know if that doesn't work

**Comment by MJRLegends** [comment]
No problem will do, probably will test in a few hours from now
