### ISSUE TITLE
Structural Glass does not block the growth of trees (1.12.1)

### ISSUE THREAD

**Issue by EliogabalusPL** [aidancbrady/Mekanism#4783]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
By creating a barrier / wall  with structural glass the trees should not create leaves on the other side of this barrier / wall. Unfortunately, this is not the case and if you create a tree wall next to this glass, you will find that the tree bough is growing on the other side as well.

#### Steps to reproduce:
1. Use vanilla block barrier configuration.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
How exactly do you expect us to stop something growing that is not our block? It would seem whatever tree you're talking about is not stopping when it cannot replace a block.

You also don't specify what Mekansim/Minecraft/Forge version you're talking about.
