### ISSUE TITLE
Mod not marked as supporting 1.12.2

### ISSUE THREAD

**Issue by C0rn3j** [aidancbrady/Mekanism#4784]
Hi, this mod is not marked as 1.12.2. I assume it works on that version since there's a 1.12 marked version.

https://minecraft.curseforge.com/projects/mekanism/files
please mark the 1.12 file as 1.12.2 too.

This "broke" my updater script.

```
  Mod unavailable: mekanism
  Mod unavailable: mekanism-generators
  Mod unavailable: mekanism-tools
```

Same goes for generators and tools.

**Comment by bookerthegeek** [comment]
Slightly off topic, can I see you update script?

**Comment by thiakil** [comment]
The file uploaded should work on 1.12.2. For now though you'll need to fix your updater script to not choke on files not specifically marked for 1.12.2

**Comment by C0rn3j** [comment]
@thiakil Well, it's not exactly choking, it's just not downloading the mod, hence quotes around "broken".

If I set it to update from 1.12 and 1.12.1 too, that'd might pull mods that are actually incompatible.

@bookerthegeek https://gitlab.com/C0rn3j/MCModUpdater

**Comment by thiakil** [comment]
My choice of word was a bit crass, apologies. By "choke" I meant, chooses to fail based on the data available on Curse.

The best way to tell would be to pull the file and check the annotation, though I don't know if that's even possible in Python

**Comment by C0rn3j** [comment]
I found the best way to do this so far is to open_issues/use_approp_channel for the project instead of working around it in the code ^^

Incorrect version marking also confuses the hell out of noobs, you can see that in the comments section on CF - "pls 1.12.2 release".

And no offense taken, my issue wasn't too explaining about my script since it's not really the point of this issue.

**Comment by thiakil** [comment]
Yeah it does need to be updated, I'd do it myself if I could

**Comment by TheTrueForce** [comment]
I would like to second(or is it third) this. If it works on 1.12.2, please mark it as such(Generators and Tools too) so that those of us using the Twitch App can get it easily.
