### ISSUE TITLE
[1.7.10] [Crash] NoClassDefFoundError: ic2/api/item/ISpecialElectricItem

### ISSUE THREAD

**Issue by anar4732** [aidancbrady/Mekanism#4785]
#### Issue description:
Crash while server start

IC2 not instaled and blacklist IC2 power option true in config

#### Steps to reproduce:
1. Place a Ender IO's D. Transceiver near mekanisim factory
2. See the crash

#### Version (make sure you are on the latest version before reporting):
All version info available in the crash log

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://paste.ubuntu.com/25800389/

**Comment by thiakil** [comment]
Sorry, we no longer support 1.7.

It appears the code doesn't check that IC2 is loaded before it does that check. You might be able to fix the crash by putting the IC2 *api* jar in your mods folder. Failing that you will need to add IC2

**Comment by anar4732** [comment]
I solved the problem already, thanks anyway.
