### ISSUE TITLE
Industrial Turbine Not Working 1.12.1

### ISSUE THREAD

**Issue by jcv01** [aidancbrady/Mekanism#4786]
Issue description:
Industrial Turbine Not working
or not accepting steam

Configuration Use:
1. Created Smallest Config < Not working
2. Created dev. tut. Config < Not working

Version:
Forge: forge-1.12.2-14.23.0.2515
Mekanism: Mekanism-1.12.1-9.4.1.326

https://imgur.com/nSnnXfA
https://imgur.com/QoICulT
https://imgur.com/GaLoSDv

**Comment by thiakil** [comment]
I don't believe you've built that correctly.

This design with total height of 6 (which I built based on the wiki info http://wiki.aidancbrady.com/wiki/Industrial_Turbine)

![2017-11-07_21 05 19](https://user-images.githubusercontent.com/1788847/32495209-af8dfa34-c3ff-11e7-9ef9-27efc2ff76c3.png)
![2017-11-07_21 05 22](https://user-images.githubusercontent.com/1788847/32495213-b15f6a78-c3ff-11e7-88ab-d22a1725975b.png)

Do you have a vent at the top? A rotational complex? Electromagnetic coil(s) above the rotational complex?
