### ISSUE TITLE
Server console littered (removal without registration see pastebin); causes TPS drops 

### ISSUE THREAD

**Issue by kulflame** [aidancbrady/Mekanism#4789]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*  Didn't see one

#### Issue description: Server console littered with spam from ic2 with mekanism machines.  https://pastebin.com/2UKuSYTn  
https://pastebin.com/z7V7nzsP
When the spam happens the TPS on the server drops to single digit numbers.  I have no ic2 machines nor ic2 power wiring at my base.  Just Mekanism machines connected to mekanism generators and a refined storage system.  Do I need to report this to ic2 as well?

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2512
**Mekanism:** 326
**Other relevant version:** ATM3 v.4.3

https://pastebin.com/2UKuSYTn
https://pastebin.com/z7V7nzsP

**Comment by zashra00** [comment]
Is it chunkloaded?

**Comment by kulflame** [comment]
Yes I confirmed it was chunkloaded

**Comment by zashra00** [comment]
What is the method of chunk loading

**Comment by Aphenon** [comment]
I have the same problem on my server, the chunkloader being the IC2 chunkloader.

**Comment by zashra00** [comment]
To be honest I've always found chicken chunks to be the most reliable chunk loader. The problem completely disappeared when we started using it on ats

**Comment by kulflame** [comment]
I made sure all my players had their bases chunkloaded via FTBU and it seems to be ok now.


Sent from Yahoo Mail for iPhone


On Tuesday, October 31, 2017, 10:03 AM, zashra00 <notifications@github.com> wrote:


To be honest I've always found chicken chunks to be the most reliable chunk loader. The problem completely disappeared when we started using it on ats

**Comment by zashra00** [comment]
That's good
