### ISSUE TITLE
Dynamic tanks loses fluid on world load

### ISSUE THREAD

**Issue by Dannerick** [aidancbrady/Mekanism#4791]
#### Issue description:
One of my dynamic tanks would lose its contents every time I would load the world (SP). I could break one of the blocks and replace it, the multi-block would reform and the fluid would be back.

I have tried to track down what was happening internal. There was an error message in the log "Error while encoding packet data", so I started looking at that. I figured out that the inventoryId in the SynchronizedTankData was starting as null as the world loaded; the null in the data array was causing the packet handler to give an error. I couldn't track down why the inventoryId would not get loaded correctly.

The only thing different with this tank compared to others in the world was in this one I added a valve after the tank was in use. I was able to fix the tank by completely breaking all the blocks in the multi-block structure and remaking it in the same configuration. Now it works correctly.

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 12.18.3.2477
**Mekanism:** 1.10.2-9.2.4
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
See #4706

**Comment by desagas** [comment]
This seems to be a separate issue. Every time the world is reloaded, every single dynamic tank loads empty. It can be reset by breaking one block and replacing it. However, when you have a world where gases and certain liquids are being auto produced, a lot of waste happens. And, in the 1.9.1 vanilla FTB Interactions server, many resources are rare.

This is still happening in Mekanism 1.12.2-9.7.8.379.

Is there a plan to fix this? It would seem as though every issue reported has been closed.

**Comment by thiakil** [comment]
#5395 is still open, and is 1.12 

As yet I've never been able to reproduce it

**Comment by aurumvorax** [comment]
I'm getting the same problem, on Enigmatica 2: Expert versions 1.48 and 1.67.  Every dynamic tank I have ever tried to build resets it's contents on world load.  Additional testing:  Dynamic tanks lose their contents when ANY pipe connection is removed from one of the tank's valve's.  Tested with TE fluiducts and EIO fluid conduits.

**Comment by stryker103** [comment]
Ditto for Enigmatica 2 expert. Filling a large dynamic tank with lava from magma crucibles. Empties itself periodically (im using about 12B/second but providing about 36 but constantly ends up empy)

As im watching it, it gets to 500B pretty much exactly from what I can see then empties itself....
Ill see if i can get a video
