### ISSUE TITLE
fusion and opencomputers

### ISSUE THREAD

**Issue by K1ltu** [aidancbrady/Mekanism#4792]
#### Issue description:
well now so one day i was dicking around with functions exposed by the logic port on the fusion reactor and decided to figure out how write a program to convert excess fuel into uu matter so after messing with setInjectionRate() i discovered that you can pass values over 98 into the reactor so i went balls to the wall and set it to 300 and at that point the reactor stopped consuming fuel and started making 2.58Grf/t

also at 300 it doesn't even need ignited it will make the 2.58Grf and does not play the animation and still wont consume fuel

#### Steps to reproduce:
1. send setInjectionRate(300) to fusion reactor
2.get 2.58Grf for free
3.Profit

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2477
**Mekanism:** versions tested for 1.10.2(Mekanism-1.10.2-9.2.4.103) and 1.7.10(Mekanism-1.7.10-9.1.1.1031)
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
Nop no crash just craptons of free power

i propose just adding a check to the value being passed into the logic adapter to check if "x > 98"

**Comment by thommy101** [comment]
It's an intended feature as Aidan explained at https://github.com/aidancbrady/Mekanism/issues/4030#issuecomment-285212353

**Comment by thiakil** [comment]
Seems very odd... at least the part about it not consuming fuel is a bug

**Comment by thommy101** [comment]
It does seem a bit odd indeed. The not consuming fuel is certainly a bug... That sounds like an integer overflow, which is solved by the limit you've applied.
