### ISSUE TITLE
Why does the universal cable not connect in the industrialcraft 2 1.11.2 batbox?

### ISSUE THREAD

**Issue by Chrishunk** [aidancbrady/Mekanism#4793]
Why does the universal cable not connect in the industrialcraft 2 1.11.2 batbox? 

see this https://imgur.com/CvfCplH

**Comment by zashra00** [comment]
Is the bat box set to input

**Comment by zashra00** [comment]
Oh I feel so stupid.... is eu blacklisted in the config

**Comment by zashra00** [comment]
I know a couple packs blacklist eu cause they feel it's to cheaty

**Comment by Chrishunk** [comment]
connects nothing of industrial craft, no solar panel, no box '-', please help me. see this https://i.imgur.com/GTPfjBa.png & https://i.imgur.com/AamQRaA.png

**Comment by zashra00** [comment]
I've already explained why... But just for shiggles what modpack are you running

**Comment by Chrishunk** [comment]
This modpack was the one I created.

**Comment by zashra00** [comment]
Okay now go into the config and make sure that eu is "NOT" blacklisted

**Comment by Chrishunk** [comment]
but this is already done, when you spoke in the settings, I went to check, if you know some mod q converts energy? 1.11.2 "

**Comment by thiakil** [comment]
Please post your versions of Mekanism, IC2, and Forge. Also post your server log, preferably from a time period where you placed the cable.

**In future**, please follow the issue template. It is not there simply for decoration.
