### ISSUE TITLE
[1.12.1] Crafttweaker PRC issue (Link to CT github post)

### ISSUE THREAD

**Issue by Quarris** [aidancbrady/Mekanism#4794]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
PRC recipe is added in JEI but doesn't work in machine.
CT Github Post: https://github.com/jaredlll08/CraftTweaker/issues/360

#### Version (make sure you are on the latest version before reporting):
**Forge:...** 
**Mekanism: 9.4.1** 

This links to the pictures, script and the ct log.
https://gist.github.com/Quarris/8fa8a521397a8eaac6e000d5854eb419

**Comment by thommy101** [comment]
We've got a soft dependency on MTLib for adding crafttweaker support. Do you have that installed? (it's on our TODO list to make it more visible to the end users).

**Comment by Quarris** [comment]
Yes, MTLib is installed.

**Comment by thiakil** [comment]
Can you post your server log too please

**Comment by Quarris** [comment]
https://gist.github.com/Quarris/a30c699506df0b975f52b0bb3df0fa25
I hope thats what you mean. Its the latest log that it generated

**Comment by thiakil** [comment]
That's the one. Doesn't appear to be any errors, so that's a good start lol

**Comment by thiakil** [comment]
Hmm actually, in your CT log... `[POSTINITIALIZATION][CLIENT][INFO] Adding 0 Mekanism Reaction Recipe(s) for Unknown item`

**Comment by Quarris** [comment]
Thats weird, I mean the ct log was fine, it also works in JEI which is double weird :/

**Comment by thiakil** [comment]
What's the energy capacity of your PRC? (in Mek J)

**Comment by Quarris** [comment]
I hope that this is what you mean. Im not a mekanism guy :P

![image](https://user-images.githubusercontent.com/6171764/32386209-55d873ec-c0b8-11e7-83e4-bb6e76ba6e89.png)

![image](https://user-images.githubusercontent.com/6171764/32386231-65c78072-c0b8-11e7-8051-656a243dd20a.png)

**Comment by Quarris** [comment]
omg @thiakil you are a genius! Thanks!!

**Comment by thiakil** [comment]
I take it that means it was that the power required by your addition was too high?

The power figure in the ct function appears to be extra power per tick

**Comment by thommy101** [comment]
The number of 5k could work perfectly, if you upgrade the machine (either to a factory version or with energy / efficiency upgrades)

**Comment by Quarris** [comment]
Yeah I realised this but its good that its been figured out. Thank everyone! <3
