### ISSUE TITLE
Turbine Port Crash Upon Placing In Structural Glass

### ISSUE THREAD

**Issue by Ryahn** [aidancbrady/Mekanism#4795]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
After creating a 9x9x9 turbine using structural glass for windows. I would place the port in the glass. If I try to place a new one or break the old one, the game crashes and I can no longer log in.

#### Steps to reproduce:
1. Create 9x9x9 turbine
2. Use structural glass for windows
3. Place port in glass

#### Version (make sure you are on the latest version before reporting):
**Forge:** 12.18.3.2281
**Mekanism:** 1.10.2-9.2.3.97
**Other relevant version:** Resonant Rise 4.3.0.1-b

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://gist.github.com/Ryahn/1e08f4b19b101d905cc2cce29cec5417

**Comment by thiakil** [comment]
I'm pretty sure LimeLib should be checking `canConnectEnergy(EnumSide)` before asking how much energy can be stored, but shouldn't crash in next version

**Comment by Ryahn** [comment]
@thiakil Is it possible to test this dev version :P

**Comment by thiakil** [comment]
You can always build it from source.

**Comment by thommy101** [comment]
Whoops.. this is a 1.10 issue, not 1.12...
