### ISSUE TITLE
1.10.2 enrichment chamber wont work

### ISSUE THREAD

**Issue by rdc122999** [aidancbrady/Mekanism#4796]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
the enrichment chamber wont work

#### Steps to reproduce:
1.no clue
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 12.18.3.2511
**Mekanism:** 9.2.3.97 i also used the latest version it wouldnt work so i tried the one before it
**Other relevant version:** i also have the same version of generator and tool

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by zashra00** [comment]
Hmm something not working is a big deal.... but it's very hard to fix if you don't tell them how it's not working... Like things its not making and such..

**Comment by thiakil** [comment]
*What* won't work about it?

**Comment by rdc122999** [comment]
Sorry just seen this like you can’t shift click no items into it and even when you just place them in it it won’t work. And it doesn’t seem to be working with anything

**Comment by thiakil** [comment]
:man_shrugging: 

Either not enough power or something has screwed with recipes is my only guess

**Comment by rdc122999** [comment]
Hmm ok who knows it’s my personal pack I just threw a bunch of mods in it so I’m sue something broke thanks for replying
