### ISSUE TITLE
fall damage bug when using jetpack 1.12

### ISSUE THREAD

**Issue by TandJ21** [aidancbrady/Mekanism#4797]
Hello  There,
When using the jetpack from v1.12.1-9.4.1.326 it appears that no matter how high up in there you are or how low to the ground you are that u take fall damage no matter what, is this something thats meant to be or is this a bug that you need to fix?

**Comment by TandJ21** [comment]
seems to also drag you down with the fall damage too

**Comment by thiakil** [comment]
Normal mode on the jetpack does not counter fall damage. Hover mode will.
