### ISSUE TITLE
Crash to desktop upon placing a Mekanism Solar Generator into a Tinker's Construct Crafting Station

### ISSUE THREAD

**Issue by Alphanos** [aidancbrady/Mekanism#4798]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*
#### Issue description: 

Good evening, 

I'm running into a repeated crash to desktop when placing a Mekanism Solar Generator into a Tinker's Construct Crafting Station while attempting to craft the Advanced Solar Generator.  From my searching, this looks like a possible repeat/regression on a previously reported and patched issue, found here: [https://github.com/aidancbrady/Mekanism/issues/4514](https://github.com/aidancbrady/Mekanism/issues/4514.)

I have already removed Optifine, so the crash log I have included was from a crash with only the base modlist from pack All the Mods 3 v4.3.

The crash occurs most of the time, but not every time, when placing the Solar Generator into the Crafting Station.  This happens whether I place it in using JEI's help, or shift click it in, or manually place it in.  A small number of times I experience the crash just from trying to open the Crafting Station GUI, but usually it is only the action of placing a Solar Generator into the grid which triggers the crash.  The Solar Generator stays in the Crafting Station after I reload my game (playing on a server).  I can successfully craft the Advanced Solar Generator once all Solar Generators have been placed in and I have reloaded post-crash.  I notice that when I observe the rendered miniature items upon the crafting station in the world, the solar generators do not show, in case this is relevant.

Thank you for your advice in the previous report of this issue of the known workaround, which I can confirm prevents the crash.  When I edit config/tconstruct.cfg and set B:renderInventoryInWorld=false, the crash does not occur.  However, this is non-ideal for a permanent fix since it has side effects such as hiding the casts currently placed in Tinker's Construct casting tables.

Thanks very much for your work on such great mods.  I really enjoy Mekanism =).

#### Steps to reproduce:
1. Place a Mekanism Solar Generator into the crafting grid of a Tinker's Construct Crafting Station.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.0.2512
**Mekanism:** 1.12.1-9.4.1.326 (At time of writing, this is the latest version released to Curseforge for Minecraft 1.12)
**Other relevant version:** All the Mods 3 v4.3

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/Pg53z1ae

**Comment by thiakil** [comment]
Looks like some interaction between The One Probe and CodeChickenLib, not something on our end.

**Comment by thiakil** [comment]
The issue with Mekanism blocks crashing in the Tinkers table has long since been fixed btw.

**Comment by Alphanos** [comment]
I apologize if the crash report I included did not illustrate the problem well.  To clarify, I am regretfully reporting that the bug with Mekanism blocks crashing in the Tinkers table has not remained fixed.

Below I will link to 7 other crashlogs, all triggered when placing the Solar Generator into the Crafting Station.  Now that I look at the stacktrace of each one, I notice that various random things rendering in the vicinity appear in the stack trace.  The One Probe, Psi (using some Psi lights nearby), Actually Additions (nearby laser power link), and Tinker's (I will highlight that stacktrace).

Although I don't have any experience developing mods for Minecraft, it appears that the interaction between the Solar Generator and the attempted mini-render from the Tinker's Crafting Station is causing some kind of corruption in the rendering objects which is resulting in other nearby things crashing when they attempt to render.  This does seem at least closely related to the bug as I previously referenced, since it occurs specifically when the Mekanism Solar Generator is placed into the Crafting Station, and it stops occurring when I use the workaround suggested in that report to prevent the Tinker's Crafting Station from attempting to render the mini version of the Solar Generator.

https://pastebin.com/ndpu2Q9t
https://pastebin.com/hpLNkd9Z
https://pastebin.com/Q4ycCAQ8
https://pastebin.com/vbweqCTM
https://pastebin.com/ztRgCGuG
https://pastebin.com/PjbNu2L1  <-- This stacktrace shows Tinker's
https://pastebin.com/1YpSH8Ba

I hope this helps!  Thank you.

**Comment by Alphanos** [comment]
I tried some further tests to try to help isolate the problem.

I created a fresh Minecraft 1.12.2 profile with forge 2512.  I added only Tinker's Construct and the 3 Mekanism mods; nothing else.  I created a new single player creative world and tested.  The crash did not occur.

I loaded All the Mods 3 v4.3.  I created a new single player creative world and tested.  The crash did occur.

So you are definitely correct in saying that some other kind of mod interaction is happening here which is contributing to the crash.

Can you provide any advice or insight as to how I can assist in resolving this bug?  Should I report this as a bug to the All the Mods 3 pack maintainer?  Or is there any other mod you can clearly see is likely the cause based on the 8 crashlogs?  So far, I had not noticed any similar crashes when placing various other things in the crafting station as I had been playing All the Mods 3.

Thank you again.  I hope that I have not inadvertently reported this issue incorrectly.

**Comment by Alphanos** [comment]
Although it did not contain any updates for Tinker's Construct or Mekanism, just to be safe I updated my client and server from All the Mods 3 v4.3 to All the Mods 3 v4.4.  The crash still occurs on the latest pack version.

**Comment by thiakil** [comment]
The only real way to diagnose it is to either a) remove mods until you cant reproduce, or b) take the bare instance and add mods until it happens

It looks like something is seriously messing with the rendering pipeline.

**Comment by Alphanos** [comment]
With some additional testing, I have isolated the cause of the crash to a Forge config file setting that All the Mods 3 edits from the default value.  I will list the steps to reproduce below, and then report the issue to All the Mods 3.  I do not have sufficient understanding of the implications of this setting to be able to tell whether this should be reported to Forge.  If this should be reported as a bug to Forge, hopefully either you or the All the Mods 3 pack maintainer will know how this should be done.

Steps to replicate the crash:
1) Using the Twitch launcher, create a new custom profile with Minecraft 1.12.2 and Forge 2529 (latest at the time of writing).
2) Add Tinker's Construct, which will add Mantle as a dependency.
3) Since the most recent Mekanism release has not yet been marked for 1.12.2, manually copy in Mekanism-1.12.1-9.4.1.326.jar, MekanismGenerators-1.12.1-9.4.1.326.jar, and MekanismTools-1.12.1-9.4.1.326.jar into the mods folder of your new profile.
4) Launch the game and create a new single player creative world.
5) Get a Tinker's Construct Crafting Station and some Mekanism Solar Generators.
6) Repeatedly place the Solar Generators into the Tinker's Construct Crafting Station and remove them again.  You will observe no crash.  Exit the game.
7) Edit config/forge.cfg.  Set value B:alwaysSetupTerrainOffThread to true instead of the default, which is false.
8) Restart the game and repeat step 6 in your test world.  Within a few attempts of placing and removing the Solar Generators into and out of the crafting grid in the Crafting Station, the game should crash to desktop.

Workaround: In config/forge.cfg, set value B:alwaysSetupTerrainOffThread to the default setting, which is false.

The description of the setting involved reads as follows:

# Enable forge to queue all chunk updates to the Chunk Update thread. May increase FPS significantly, but may also cause weird rendering lag. Not recommended for computers without a significant number of cores available.

Thank you!

**Comment by Alphanos** [comment]
In case it is useful, I will cross-link here to the ATM3 issue report: [https://github.com/AllTheMods/ATM-3/issues/253](https://github.com/AllTheMods/ATM-3/issues/253)
