### ISSUE TITLE
Quantum Entangloporter Issues

### ISSUE THREAD

**Issue by joselardizabal** [aidancbrady/Mekanism#4800]
So i wanted to start feeding my miners wirelessly in the nether to automate the process because i was using energy cubes, but the process of recharging the cube took me a  while and im too lazy and inpatient to wait for that ( reason i wanted to automate my miners in the nether) So as a solutiion i started researching a bit about the entanglo's which are similar to the tesseracts and enderIos transcievers (but i have issues with those too) so my entagloporters work well on the overworld they send and recieve energy very well and also on the item transport part, but the problem was once i moved to the nether they stoped feeding each other, i have 3 entanglos 2 for each the rf transfer and 1 for the item process, the entangloporter I was using for the RF transfer on the nether stoped recieving energy but the item entaglo worked really well and it still sends the items over to the overworld

Forge:12.18.3.2511
mekanism 9.2.4 & mekanism generators 9.2.3

**Comment by thiakil** [comment]
Sounds like a chunkloading issue to me
