### ISSUE TITLE
pipe render bug

### ISSUE THREAD

**Issue by ouroborus** [aidancbrady/Mekanism#4805]
#### Issue description:
Cables attached to another mod's cables do not connect visually on server (chunk?) load. The pipes are connected and power is transferring, they just don't look like they're connected.

![2017-11-08_02 06 48](https://user-images.githubusercontent.com/392047/32543268-fd512d0c-c429-11e7-8c2e-70e5fb114763.png)

#### Steps to reproduce:
1. Place pipes connected to another mod's pipes.
2. Restart server.
3. Note graphical issue.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.0.2517
**Mekanism:** 9.4.1
**Other relevant version:** ATM3 4.4

**Comment by thiakil** [comment]
I couldn't reproduce in dev with just Mek & TE/TD etc. Can you reproduce it with just those?

**Comment by ouroborus** [comment]
If you can recommend a Curse modpack with a server pack, I can test it.

**Comment by thiakil** [comment]
Doesnt ATM have a server pack? just use that and remove everything but the COFH mods, Mek, and MCMultipart if present.

**Comment by ouroborus** [comment]
Ah, okay. I wasn't aware that was a thing you could do. I'll see about trying to reproduce this that way then.

**Comment by thiakil** [comment]
Did you manage to reproduce this?

**Comment by ouroborus** [comment]
Not reliably. I suspect it might be one of the underlying libraries. I just updated to ATM3 v5.1. we'll see if it still happens.

**Comment by ouroborus** [comment]
I've generated a single player world using the mods listed below. The render issue shows up reliably but only on world load, not chunk load.

![2017-11-19_04 00 13](https://user-images.githubusercontent.com/392047/32990438-34004b8c-ccde-11e7-8f12-d5d387af3daa.png)
![2017-11-19_04 00 18](https://user-images.githubusercontent.com/392047/32990439-3415b512-ccde-11e7-880f-48e6a869b697.png)

CodeChickenLib-1.12-3.1.3.313-universal.jar
CoFHCore-1.12-4.3.6.14-universal.jar
CoFHWorld-1.12-1.0.1.8-universal.jar
jei_1.12.2-4.8.0.114.jar
MCMultiPart-2.3.3.jar
Mekanism-1.12.1-9.4.1.326.jar
MekanismGenerators-1.12.1-9.4.1.326.jar
MekanismTools-1.12.1-9.4.1.326.jar
RedstoneFlux-1.12-2.0.1.2-universal.jar
ThermalCultivation-1.12-0.1.1.6-universal.jar
ThermalDynamics-1.12-2.3.6.13-universal.jar
ThermalExpansion-1.12-5.3.6.20-universal.jar
ThermalFoundation-1.12-2.3.6.16-universal.jar

**Comment by thiakil** [comment]
Thanks, managed to reproduce it in dev. Seems having RF in the pipes is the key, my setup that had just the pipes loads fine

**Comment by ouroborus** [comment]
The connections of the mekanism conduits need to be on two opposite sides of a specific block; having adjacent sides connected prevents this issue. It seems that there needs to be power connected during world load for this to most reliably happen. It happens more reliably if that power is supplied to the fluxduct. Once it loads that way, it can become electrically disconnected (rather that just visually) if you try to move the power around without fixing it.  Once the pipes become broken, they'll generally stay broken regardless of power.

EDIT: Yeah, just discovered the RF requirement myself.

**Comment by thiakil** [comment]
I'm thinking it *might* be race condition, or a TD issue, as the Mek cable is not finding a valid acceptor.

I have no idea if the TD cable triggers a neighbour update when it establishes its network. If it did this probably wouldn't happen.

**Comment by thiakil** [comment]
Have you seen it with any other mod's power cables?

**Comment by ouroborus** [comment]
It seems weird that valid acceptors aren't found only when the connections are arranged in certain ways.

Doesn't seem to happen with the other types of fluxducts. The cryo-stabilized fluxducts are odd in that they don't appear to have internal storage and claim "infinite" transfer rate. They act more like a proxy rather than a conductor.

**Comment by thiakil** [comment]
Yeah if it only happens with one type of cable, I'm gonna lean towards it being a TD issue, nothing really that we can do there if it's not sending out a neighbour changed message.

**Comment by ouroborus** [comment]
I'll report it on their repository tomorrow and see if they have any ideas.

**Comment by ouroborus** [comment]
Welp, CoFH says the fluxduct is sending out neighbor changed messages correctly.

**Comment by thiakil** [comment]
I figured he'd say that, I once traced through his code and found him clamping stack sizes to 1 (should have been 0 in this case) and he denied that his code did such a thing.

I will double check later if it's an issue with the transmitters joining networks, but on such a small scale I doubt it.

**Comment by thiakil** [comment]
![2017-11-21_19 43 46](https://user-images.githubusercontent.com/1788847/33070974-b9781084-cef4-11e7-8011-3cfba7859bdc.png)
It appears it is not just cryo stabilised ducts that have the problem.

Nothing we can really do on our end, aside from special case it, which I really don't want to do. You'll just have to wait until Lemming actually takes a look, or trigger a block update next to the mek cable after load. Sorry.
