### ISSUE TITLE
[1.7.10] Crash on exploide near dynamic tank

### ISSUE THREAD

**Issue by anar4732** [aidancbrady/Mekanism#4806]
Forge and mekanisim last version.

https://paste.ubuntu.com/25925819/

**Comment by thiakil** [comment]
1.7.10 is not supported sorry.

**Comment by anar4732** [comment]
1.7.10 is still a very current version of modded minecraft.
we public server running on 1.7.10.
please fix this.

**Comment by thiakil** [comment]
1.7.10 is over 3 years old and 5 major releases behind.

**Comment by anar4732** [comment]
60% of presently working servers 1.7.10

**Comment by anar4732** [comment]
Also, 80% of the current mods are not available for new versions.

**Comment by thiakil** [comment]
No.
