### ISSUE TITLE
Wind Gen Missing?

### ISSUE THREAD

**Issue by TheGreatNaj** [aidancbrady/Mekanism#4808]
#### Issue description:
I have Mekanism on 2 different modpacks both in 1.10.2. One has the wind generator in it but the other doesn't and theres probably an easy explanation but I cant figure it out lol One mod pack I downloaded (the one that does have the wind gen) and the other is a smaller one I put together for myself (does not have wind gen)

When I compared the two configs the one missing the wind gen didn't have the generators section at all. I tried downloading a newer version of mekanism and even copying over the same file from the other modpack and removing the config but neither worked. The config did have a generators section after trying this but despite wind gens being enabled they still don't show up in game.

#### Steps to reproduce:
_unsure ?_

#### Version (make sure you are on the latest version before reporting):
**Forge:** 12.18.3.2185
**Mekanism:** 1.10.2-9.2.4.103
**Other relevant version:** Before was using Mekanism 1.10.2-9.2.2

Sorry this is more of a personal problem than a bug, just not sure where else to ask for help x.x

**Comment by thommy101** [comment]
Have you installed Mekanism Generators? Mekanism has 2 sub mods (tools and generators) which both depend on Mekanism.

**Comment by TheGreatNaj** [comment]
Ah, I did not lol thank you, I am blind :P

**Comment by thommy101** [comment]
No problem
