### ISSUE TITLE
Cardboxes doesn't work in 1.12 witht the newest build.

### ISSUE THREAD

**Issue by halvors** [aidancbrady/Mekanism#4809]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When using cardboxes to move TE's your unable tom shift rightclick it.

I know there was some changes to the onRightclick() functions from 1.10 so maybe a porting issue?

#### Steps to reproduce:
1. Place furnace
2. Place cardbox and wrap furnace.
3. Shift right click cardbox to unwrap the furnace (This doesn't work).

#### Version (make sure you are on the latest version before reporting):
Forge: 14.23.0.2491
Mekanism: 9.4.1.326

**Comment by thiakil** [comment]
There was a Forge change in recent 1.12 builds that changed hand handling, so for now you'll need to unbox with BOTH hands empty.

**Comment by thiakil** [comment]
Should be fixed in latest release
