### ISSUE TITLE
Digital Miner does not mine Chorus Flowers in 1.10.2, even with Item Stack filter

### ISSUE THREAD

**Issue by araevingaming** [aidancbrady/Mekanism#4811]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
Fixed for 1.12; 1.10 is crash fixes only.
