### ISSUE TITLE
Cables, pipes, and logistical transporters are always placed upon right-clicking

### ISSUE THREAD

**Issue by PapiDimmi** [aidancbrady/Mekanism#4812]
If you are holding a cable, pipe, or logistical transporter while opening a door, chest, etc., it is placed in front of the door or chest, rather than allowing you to open said door or chest.

The same goes for any block.

**Minecraft version:** 1.12.2
**Mekanism version:** 9.4.1.326

**Comment by thiakil** [comment]
#BlameAma https://github.com/amadornes/MCMultiPart/issues/73
