### ISSUE TITLE
How to change recipe for Enrichment Chamber in 1.10.2 by using Crafttweaker

### ISSUE THREAD

**Issue by prototype-saber** [aidancbrady/Mekanism#4815]
As title,i`m using modtweaker and crafttweaker to change the recipes.
But the log report as this:

[SERVER_STARTED][SERVER][ERROR] Mekanism.zs:4 > No such member: Mekanism
[SERVER_STARTED][SERVER][ERROR] Error executing Mekanism.zs: 2
java.lang.ArrayIndexOutOfBoundsException: 2
	at stanhebben.zenscript.type.natives.JavaMethod.rematch(JavaMethod.java:168)
	at stanhebben.zenscript.expression.ExpressionCallVirtual.<init>(ExpressionCallVirtual.java:24)
	at stanhebben.zenscript.type.ZenTypeAny.call(ZenTypeAny.java:175)
	at stanhebben.zenscript.expression.Expression.call(Expression.java:79)
	at stanhebben.zenscript.parser.expression.ParsedExpressionCall.compile(ParsedExpressionCall.java:37)
	at stanhebben.zenscript.statements.StatementExpression.compile(StatementExpression.java:20)
	at stanhebben.zenscript.ZenModule.compileScripts(ZenModule.java:113)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:149)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:508)
	at minetweaker.MineTweakerImplementationAPI.lambda$static$0(MineTweakerImplementationAPI.java:70)
	at minetweaker.MineTweakerImplementationAPI$$Lambda$4/501306018.execute(Unknown Source)
	at minetweaker.MineTweakerImplementationAPI$3.execute(MineTweakerImplementationAPI.java:493)
	at minetweaker.mc1102.server.MCServer$MCCommand.func_184881_a(MCServer.java:110)
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:83)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892)
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.util.Util.func_181617_a(SourceFile:45)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

Plz tell me what should i do

**Comment by prototype-saber** [comment]
Code like this:
import mods.botania.Apothecary;
import minetweaker.item.IIngredient ;


mods.mekanism.Infuser.removeRecipe(<mekanism:ControlCircuit>,<mekanism:Ingot:1>, "REDSTONE");

**Comment by thommy101** [comment]
Do you have MTLib installed? it's one of the requirements for our CraftTweaker implementation.

**Comment by prototype-saber** [comment]
yes

**Comment by prototype-saber** [comment]
[SERVER_STARTED][SERVER]Mod: mcp - Minecraft Coder Pack - 9.19
[SERVER_STARTED][SERVER]Mod: FML - Forge Mod Loader - 8.0.99.99
[SERVER_STARTED][SERVER]Mod: Forge - Minecraft Forge - 12.18.3.2511
[SERVER_STARTED][SERVER]Mod: AdvancedRocketryCore - Advanced Rocketry - 1
[SERVER_STARTED][SERVER]Mod: Aroma1997Core - Aroma1997Core - ${version}
[SERVER_STARTED][SERVER]Mod: ivtoolkit - IvToolkit - 1.3.3-1.10
[SERVER_STARTED][SERVER]Mod: OpenComputers|Core - OpenComputers (Core) - 1.7.0.124
[SERVER_STARTED][SERVER]Mod: <CoFH ASM> - CoFH ASM - 000
[SERVER_STARTED][SERVER]Mod: ccl-entityhook - ccl-entityhook - 1.0
[SERVER_STARTED][SERVER]Mod: libVulpes - libVulpes - 0.2.6.
[SERVER_STARTED][SERVER]Mod: advancedRocketry - Advanced Rocketry - 1.2.5a
[SERVER_STARTED][SERVER]Mod: JEI - Just Enough Items - 3.14.7.420
[SERVER_STARTED][SERVER]Mod: AppleCore - AppleCore - 2.2.2
[SERVER_STARTED][SERVER]Mod: appleskin - AppleSkin - 1.0.9
[SERVER_STARTED][SERVER]Mod: Aroma1997CoreHelper - Aroma1997Core|Helper - 1.1.1.2
[SERVER_STARTED][SERVER]Mod: Aroma1997sDimension - Aroma1997's Dimensional World - 1.0
[SERVER_STARTED][SERVER]Mod: AromaBackup - AromaBackup - 1.0.1.1
[SERVER_STARTED][SERVER]Mod: AromaBackupRecovery - AromaBackup Recovery - 1.0
[SERVER_STARTED][SERVER]Mod: Psi - Psi - r1.0-42
[SERVER_STARTED][SERVER]Mod: AutoRegLib - AutoRegLib - 1.0-2
[SERVER_STARTED][SERVER]Mod: Baubles - Baubles - 1.3.11
[SERVER_STARTED][SERVER]Mod: bdlib - BD Lib - 1.12.4.25
[SERVER_STARTED][SERVER]Mod: BetterAchievements - Better Achievements - 0.3.3.10
[SERVER_STARTED][SERVER]Mod: Botania - Botania - r1.9-341
[SERVER_STARTED][SERVER]Mod: CodeChickenLib - CodeChicken Lib - 2.5.9.283
[SERVER_STARTED][SERVER]Mod: cofhcore - CoFH Core - 4.1.12
[SERVER_STARTED][SERVER]Mod: brandonscore - Brandon's Core - 2.1.13
[SERVER_STARTED][SERVER]Mod: cfm - MrCrayfish's Furniture Mod - 4.1.2
[SERVER_STARTED][SERVER]Mod: ctm - CTM - MC1.10.2-0.2.3.26
[SERVER_STARTED][SERVER]Mod: chisel - Chisel - MC1.10.2-0.0.14.33
[SERVER_STARTED][SERVER]Mod: CodeChickenCore - CodeChicken Core - 2.4.1.102
[SERVER_STARTED][SERVER]Mod: controlling - Controlling - 1.0.5
[SERVER_STARTED][SERVER]Mod: cosmeticarmorreworked - CosmeticArmorReworked - 1.10.2-v2a
[SERVER_STARTED][SERVER]Mod: crafttweakerjei - CraftTweaker JEI Support - 1.0.1
[SERVER_STARTED][SERVER]Mod: MineTweaker3 - MineTweaker 3 - 3.0.26
[SERVER_STARTED][SERVER]Mod: ctgui - CT-GUI - 1.0.0
[SERVER_STARTED][SERVER]Mod: thermalfoundation - Thermal Foundation - 2.1.5
[SERVER_STARTED][SERVER]Mod: draconicevolution - Draconic Evolution - 2.1.7
[SERVER_STARTED][SERVER]Mod: EnderStorage - EnderStorage - 2.2.1.106
[SERVER_STARTED][SERVER]Mod: valkyrielib - Valkyrie Lib - 1.10.2-0.10.6
[SERVER_STARTED][SERVER]Mod: environmentaltech - Environmental Tech - 1.10.2-0.10.6b
[SERVER_STARTED][SERVER]Mod: Waila - Waila - 1.8.17-B31_1.10.2
[SERVER_STARTED][SERVER]Mod: sonarcore - SonarCore - 3.3.0
[SERVER_STARTED][SERVER]Mod: fluxnetworks - FluxNetworks - 1.2.8
[SERVER_STARTED][SERVER]Mod: forgelin - Shadowfacts' Forgelin - 1.5.1
[SERVER_STARTED][SERVER]Mod: advgenerators - Advanced Generators - 0.9.20.23
[SERVER_STARTED][SERVER]Mod: harvestfestival - Harvest Festival - 0.5.27
[SERVER_STARTED][SERVER]Mod: ichunutil - iChunUtil - 6.5.0
[SERVER_STARTED][SERVER]Mod: inventorytweaks - Inventory Tweaks - 1.61-58-a1fd884
[SERVER_STARTED][SERVER]Mod: jaopca - JAOPCA - 1.10.2-2.0.5.55
[SERVER_STARTED][SERVER]Mod: oredictinit - OreDictInit - 1.10.2-2.0.1.59
[SERVER_STARTED][SERVER]Mod: journeymap - JourneyMap - 1.10.2-5.5.2
[SERVER_STARTED][SERVER]Mod: jeresources - Just Enough Resources - 0.5.8.98
[SERVER_STARTED][SERVER]Mod: llor - Light Level Overlay Reloaded - 1.1.1-mc[1.9-1.11]
[SERVER_STARTED][SERVER]Mod: malisiscore - MalisisCore - 1.10.2-4.4.0
[SERVER_STARTED][SERVER]Mod: malisisdoors - MalisisDoors - 1.10.2-5.2.0
[SERVER_STARTED][SERVER]Mod: mantle - Mantle - 1.10.2-1.1.5.205
[SERVER_STARTED][SERVER]Mod: mcmultipart - MCMultiPart - 1.4.0
[SERVER_STARTED][SERVER]Mod: Mekanism - Mekanism - 9.2.4
[SERVER_STARTED][SERVER]Mod: MekanismGenerators - MekanismGenerators - 9.2.4
[SERVER_STARTED][SERVER]Mod: MekanismTools - MekanismTools - 9.2.4
[SERVER_STARTED][SERVER]Mod: minefactoryreloaded - MineFactory Reloaded - 2.9.0B1
[SERVER_STARTED][SERVER]Mod: MineFactoryReloaded|CompatVanilla - MFR Compat: Vanilla - 2.9.0B1
[SERVER_STARTED][SERVER]Mod: mtrm - MineTweakerRecipeMaker - 1.2.1.26
[SERVER_STARTED][SERVER]Mod: testdummy - MmmMmmMmmMmm - 1.11
[SERVER_STARTED][SERVER]Mod: mobdismemberment - MobDismemberment - 6.0.0
[SERVER_STARTED][SERVER]Mod: mtlib - MTLib - @VERSION@
[SERVER_STARTED][SERVER]Mod: modtweaker - Mod Tweaker - 2.0.13
[SERVER_STARTED][SERVER]Mod: Morpheus - Morpheus - 1.10.2-3.1.13
[SERVER_STARTED][SERVER]Mod: mousetweaks - Mouse Tweaks - 2.8
[SERVER_STARTED][SERVER]Mod: natura - Natura - 1.10.2-4.1.0.82
[SERVER_STARTED][SERVER]Mod: Neat - Neat - 1.3-12
[SERVER_STARTED][SERVER]Mod: recipehandler - NoMoreRecipeConflict - 0.6
[SERVER_STARTED][SERVER]Mod: notenoughwands - Not Enough Wands - 1.5.5
[SERVER_STARTED][SERVER]Mod: OpenComputers - OpenComputers - 1.7.0.124
[SERVER_STARTED][SERVER]Mod: refinedstorage - Refined Storage - 1.2.26
[SERVER_STARTED][SERVER]Mod: ocrsdriver - OC RS Driver - 1.0
[SERVER_STARTED][SERVER]Mod: omlib - OMLib - 3.0.0-129
[SERVER_STARTED][SERVER]Mod: openmodularturrets - Open Modular Turrets - 3.0.0-220
[SERVER_STARTED][SERVER]Mod: oreexcavation - OreExcavation - 1.2.107
[SERVER_STARTED][SERVER]Mod: ProjectE - ProjectE - 1.10.2-PE1.3.1
[SERVER_STARTED][SERVER]Mod: tconstruct - Tinkers' Construct - 1.10.2-2.6.5.10
[SERVER_STARTED][SERVER]Mod: p455w0rdslib - p455w0rd's Library - 1.0.30
[SERVER_STARTED][SERVER]Mod: portalgun - PortalGun - 6.0.1
[SERVER_STARTED][SERVER]Mod: psionup - PSIonic Upgrades - 15.1
[SERVER_STARTED][SERVER]Mod: reccomplex - Recurrent Complex - 1.4.5-1.10
[SERVER_STARTED][SERVER]Mod: refinedexchange - Refined Exchange - 1.1.1
[SERVER_STARTED][SERVER]Mod: rftools - RFTools - 7.13
[SERVER_STARTED][SERVER]Mod: shadowmc - ShadowMC - 3.6.1
[SERVER_STARTED][SERVER]Mod: simpleoregen - Simple Ore Generation - 2.2.2
[SERVER_STARTED][SERVER]Mod: flammpfeil.slashblade - SlashBlade - mc1.10.2-r38
[SERVER_STARTED][SERVER]Mod: SleepingBag - Sleeping Bag - 1.4.0
[SERVER_STARTED][SERVER]Mod: stacksonstacks - stacksonstacks - 1.1.4
[SERVER_STARTED][SERVER]Mod: theoneprobe - The One Probe - 1.4.19
[SERVER_STARTED][SERVER]Mod: thermaldynamics - Thermal Dynamics - 2.0.11
[SERVER_STARTED][SERVER]Mod: WailaHarvestability - Waila Harvestability - 1.1.10
[SERVER_STARTED][SERVER]Mod: wanionlib - WanionLib - 1.10.2-1.3
[SERVER_STARTED][SERVER]Mod: wcg - Wireless Crafting Grid - 1.0.0
[SERVER_STARTED][SERVER]Mod: Woot - Woot - 1.10.2-1.4.1
[SERVER_STARTED][SERVER]Mod: yarrmateys_cutemobmodels - Yarr Cute Mob Models - Remake - 1.0.14
[SERVER_STARTED][SERVER]Mod: unidict - UniDict - 1.10.2-2.9b
[SERVER_STARTED][SERVER]Mod: wrapup - WrapUp - 1.10.2-1.0.2

**Comment by prototype-saber** [comment]
mod list given by crafttweaker

**Comment by thiakil** [comment]
@thommy101 didn't you only implement this for 1.12 (or 1.11+)?

**Comment by thommy101** [comment]
.... You're right
@prototype-saber sorry, mekanism doesn't support crafttweaker in 1.10.2.
