### ISSUE TITLE
[1.12.2] The metallurgic infuser loses its items, and the purification chamber loses its gas, upon breaking the block

### ISSUE THREAD

**Issue by ghost** [aidancbrady/Mekanism#4819]
It keeps everything except the bar on the left (diamond dust, redstone, coal, etc.).

**Mekanism version**: 9.4.1.326

**Comment by PapiDimmi** [comment]
Also, blocks like the purification chamber don’t retain their gas.

**Comment by thommy101** [comment]
Confirmed:
- Metallurgic infuser loses the infusing item
- Purifying loses stored oxygen
- Factories loses power till basic level
