### ISSUE TITLE
All the Mods 3 keeps crashing

### ISSUE THREAD

**Issue by Krazon** [aidancbrady/Mekanism#4822]
#### Issue description:
I can't connect to my server anymore because my game instantly crashes.
Not entirely sure what causes the crash but I was told to report the issue here.

**Forge:** 14.23.0.2531
**Mekanism:** 9.4.1.326

https://pastebin.com/mFa6YgVV

**Comment by thiakil** [comment]
already been fixed in dev. Until Aidan releases the update you will need to edit your player data file to not have the tinkers tool in your active hotbar slot - you can't look at cables/tubes/pipes with a Tinkers tool in hand with that version
