### ISSUE TITLE
Xnet - Mekanism Compatibility

### ISSUE THREAD

**Issue by gedefims** [aidancbrady/Mekanism#4824]
Any chance of adding Xnet compatibility to this great mod?
Seems that the liquids and gasses doesn't work well together with Xnet!

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.0.2531
**Mekanism:** 1.12.1-9.4.1.326
**Other relevant version:** ATM3 v5.1

**Comment by thiakil** [comment]
There should be no compatibility required on our side, Xnet uses the standard interfaces as far as I know, which we do supply.

Check that your sidedness is set correctly.
