### ISSUE TITLE
Bees secondary output // Species unreachable

### ISSUE THREAD

**Issue by MrFootman** [aidancbrady/Mekanism#4826]
Hi, 

Not sure if it's a bug, or a choice. So i prefer to report it

#### Issue description:
1. Few bees i tried can't produce their secondary output : Gelid bee don't produce cryotheum dust, Yellorium bee don't produce yellorium comb... ...
2. Some species can't be breed. There is no oblivion hive, and no infernal hive in the nether (tried a lot of spot with a digiminer). So all species from this two are unobtainable.

#### Steps to reproduce:
1. Works with several bees i tried. Gelid / Yellorium / Nuclear / Unstable
2. 

#### Version :
Lastest version of the modpack 

Thank you for any answer, and keep doing your great job on this amazing modpack !

**Comment by thommy101** [comment]
Uhm... I think you've reported this to the wrong project. Mekanism doesn't do anything with bees.

Also, "latest" is always a wrong thing to report ;) (and Mekanism is a mod, not a modpack)

**Comment by MrFootman** [comment]
Just saw that. Sorry. Have nothing to do with mekanism. I just followed a link which was supposed to take me on a modpack github.
