### ISSUE TITLE
CraftTweaker smelting recipes not working 

### ISSUE THREAD

**Issue by ixanza** [aidancbrady/Mekanism#4830]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Added  a recipe to the smelter to process thermal expansion dust but it isn't working nor giving an error
here's the script
//Add Thermal Recipes to Smelter
`mods.mekanism.smelter.addRecipe(<thermalfoundation:material:68>, <thermalfoundation:material:132>);`

#### Steps to reproduce:
1. Open recipes.zs
2. Add recipe in
3. Launch game and see that recipe isn't added

#### Version (make sure you are on the latest version before reporting): 
**Minecraft:** 1.12.2
**Forge:** 14.23.0.2544
**Mekanism:** 9.4.1.326
**Other relevant version: ** 
**CraftTweaker:** 1.12-4.0.10
**MTLIB:** 3.0.1
**ModTweaker:** 4.0.5

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
crafttweaker log
[POSTINITIALIZATION][CLIENT][INFO] Adding 0 Mekanism Smelter Recipe(s) for Unknown item

**Comment by thommy101** [comment]
Uhm.. That thing should have been removed I guess.. We make use of the vanilla smelting list. I don't think the smelter uses the stuff registered in that way. (im not 100% sure though)

**Comment by CJBok** [comment]
Indeed, make sure you add the recipe to the vanilla furnace. the smeltery will then pickup the recipe. Took me 2 days to figure this one out.

**Comment by thommy101** [comment]
Closing, functionality will be restored.

New ticket at #5010
