### ISSUE TITLE
Old Issue, New Version. Removal without registraction of items

### ISSUE THREAD

**Issue by drunkripper** [aidancbrady/Mekanism#4831]
#### Issue description:
Spams console and from former issues with the same error and believe it may be the issue and was wondering if at some point it got unfixed.

#### Steps to reproduce:
1. Start server

#### Version (make sure you are on the latest version before reporting):
**Forge:
 SpongeForge: 1.10.2-2477-5.2.0-BETA-2637
Minecraft Forge: 12.18.3.2477
*Included the Server Sponge Version incase it may matter
** 
**Mekanism: Mekanism-1.10.2-9.2.1.298 ** 
**Other relevant version: IndustrialBox ATLanucher Modpack 0.6.5** 

#### Error's/Problems

Spams console with > [11:12:07] [ic2-poolthread-5/WARN] [IC2.EnergyNet]: Tile mekanism.common.tile.TileEntityChargepad@3e42427b (dim 0: 7887/60/-5284) removal without registration
> [11:12:07] [ic2-poolthread-5/WARN] [IC2.EnergyNet]: Tile mekanism.common.tile.TileEntityChargepad@3e42427b (dim 0: 7887/60/-5284) removal without registration
> [11:12:07] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3238ms behind, skipping 64 tick(s)
> [11:12:13] [ic2-poolthread-1/WARN] [IC2.EnergyNet]: Tile mekanism.common.tile.TileEntityChargepad@3dacec48 (dim 0: 7887/60/-5284) removal without registration
> [11:12:13] [ic2-poolthread-1/WARN] [IC2.EnergyNet]: Tile mekanism.common.tile.TileEntityChargepad@3dacec48 (dim 0: 7887/60/-5284) removal without registration
> [11:12:38] [ic2-poolthread-5/WARN] [IC2.EnergyNet]: Tile mekanism.common.tile.TileEntityChargepad@6d43b925 (dim 0: 7887/60/-5284) removal without registration
> [11:12:38] [ic2-poolthread-5/WARN] [IC2.EnergyNet]: Tile mekanism.common.tile.TileEntityChargepad@6d43b925 (dim 0: 7887/60/-5284) removal without registration

And after removing mekanism CPU usage drops and lag exists no longer.

**Comment by thommy101** [comment]
Related: #4789
Issue has been fixed in the 1.12 version of Mekanism

**Comment by tenten8401** [comment]
Is there any way we can get this backported to the 1.10 branch?  94428be looks like a pretty simple change.

**Comment by thiakil** [comment]
It is possible, though our general policy is crash fixes only for < 1.12

**Comment by drunkripper** [comment]
#4833 should fix this right @thiakil ?

**Comment by tenten8401** [comment]
I'd sort of consider this a crash level issue as it really punishes and lags servers on lower end hardware.

**Comment by thiakil** [comment]
> I'd sort of consider this a crash level issue

Except it doesnt crash.

**Comment by tenten8401** [comment]
Yes, however, what I'm saying is that it makes some lower end servers just
as unusable as a crash would make them.
I'll see if the IC2 guys think it's their mod causing the issues, because
it very well could be.

**Comment by thiakil** [comment]
It's likely your chunk loading is bad.

**Comment by tenten8401** [comment]
Removing ChickenChunks, the only chunk loader that isn't banned in the server, results in no change whatsoever, with the same error in console correlating with the CPU usage spikes.

**Comment by thiakil** [comment]
You have *some* kind of chunkloading issue, it could be another mod is not checking a block is loaded before asking for its TE, etc. 

I doubt (tho it is not impossible, I've only looked at the 1.12 code) that IC2 would be loading chunks - when the Mekanism block gets unloaded it deregisters itself, which will remove the pending add if it had not been processed by the enet yet.

**Comment by tenten8401** [comment]
I'll see if I can get a recording of what I'm seeing and why I don't think it's chunkloading related.

**Comment by thiakil** [comment]
What part of 'all that we do for registration is send an event to IC2' or 'this wouldnt even be happening if the chunk was not loaded and then unloaded' do you not understand?

CPU usage is *completely irrelevant here*

**Comment by TomTheHero** [comment]
@aidancbrady This issue is still present in the latest 1.12.2 release

**Comment by thiakil** [comment]
@TomTheHero which is why there is a current open issue about it #4974
