### ISSUE TITLE
Crash on launching the game with Mekanism, Gens, Tools ver 327 and Buildcraft

### ISSUE THREAD

**Issue by Vyraal1** [aidancbrady/Mekanism#4832]
#### Version (make sure you are on the latest version before reporting):
**Forge:**  2556
**Mekanism:**  327
**Other relevant version:** Mek Tools and Generators 327
Other relevant mods  were Buildcraft 7.99.12

#### If a (crash)log is relevant for this issue, link it here:
https://hastebin.com/ijatowowit.php

**Comment by Vyraal1** [comment]
Nevermind, I think this fixes it? https://github.com/aidancbrady/Mekanism/commit/17ce49434fc1ed8eb245a596568e2d2af1e8d556

**Comment by thommy101** [comment]
Yep, that fixed the issue ;) 
Duplicate of #4827
