### ISSUE TITLE
Adjacent evaporation tower interference

### ISSUE THREAD

**Issue by ouroborus** [aidancbrady/Mekanism#4839]
#### Issue description:
Placing evaporation towers of equal height (±1 block) adjacent to each other causes some of them to stop functioning.

In the first screenshot, both towers function. In the second screenshot, the shorter tower had a layer added causing the taller tower to stop functioning.

![2017-11-30_23 37 42](https://user-images.githubusercontent.com/392047/33472808-b1709a42-d628-11e7-8427-c136a3cce729.png)

![2017-11-30_23 38 24](https://user-images.githubusercontent.com/392047/33472809-b182f9d0-d628-11e7-8f24-041c00f2517b.png)

#### Steps to reproduce:
1. Build two 4x16x4 towers such that they are touching along one entire side.
2. Add two layers to the top of one of the towers. Note that they both now function.
3. Add two layers to the other tower. Note that at least one stops working.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.0.2531
**Mekanism:** 9.4.1
**Minecraft:** 1.12.2

**Comment by thiakil** [comment]
Don't build them touching.

**Comment by ouroborus** [comment]
@thiakil If the behavior isn't consistent, it's a bug. They either should both work or neither work due to adjacency and the relative height shouldn't matter.

**Comment by thiakil** [comment]
The behaviour is likely not consistent because it might not be recalculated from the same point each time. And we shouldn't need to specifically add code to stop it from working at all because you cant accept "you're doing it wrong" as an answer.

**Comment by ouroborus** [comment]
If anything is "doing it wrong", it would be the code since it is unable to correctly detect whether the towers are shaped and positioned correctly in all scenarios. I could accept that it was me doing it wrong if the mod was able to indicate that. As it stands, it half-asses it, telling me that one tower is correct and the other isn't despite there not being a clear difference between them.
