### ISSUE TITLE
Wind Generator Crash

### ISSUE THREAD

**Issue by CommandMC** [aidancbrady/Mekanism#4842]
#### Issue description:
I placed a Wind Generator in my 1.12 World, the game crashed and the world is unplayable now

#### Steps to reproduce:
1. Well, just place a Wind Generator

#### Version (make sure you are on the latest version before reporting):
Forge: Newest (14.23.1.25557)
Mekanism: Newest (9.4.2)
Other relevant version: 

#### If a (crash)log is relevant for this issue, link it here:
This is the one I got when I tried to load the world now
https://hastebin.com/lobetebeli.sm

**Comment by CommandMC** [comment]
Just tested it again with only Mekanism and MekanismGenerators, and it worked.
Now finding out what other mod isn't working with it

**Comment by thommy101** [comment]
In the crashlog you've provided there are two different versions of Mekanism installed. Mekanism 9.4.1 and Mekanism Generators 9.4.2. They need to be in sync with each other to work properly.

**Comment by CommandMC** [comment]
So, I updated the Versions (they are the same (and newest) now, my bad, sorry), the wind generator works fine and all, but when I try to pick it up after I break it, my game crashes. However, it is picked up, so if I restart the game, the generator is in my inv and I can place it and it works fine. Just, the crashing when picking up is really annoying. Not happening on just Mekanism and MekanismGenerators tho...
https://hastebin.com/abenudemek.sm

**Comment by thommy101** [comment]
Latest crashlog still gives two different versions.. 9.4.1-326 and 9.4.2-327

**Comment by CommandMC** [comment]
Well, I downloaded the newest versions from
https://minecraft.curseforge.com/projects/mekanism-generators/files
and
https://minecraft.curseforge.com/projects/mekanism/files
(9.4.2.327)
and removed the old ones completly
MultiMC too says, that they are the same version
![unbenannt](https://user-images.githubusercontent.com/34034631/33497801-73e8d688-d6cf-11e7-9a4e-422c15ecd942.PNG)

**Comment by thiakil** [comment]
Latest one is not us

`at mod.chiselsandbits.items.ItemBitBag.pickupItems(ItemBitBag.java:222)`

That'd be C&B
