### ISSUE TITLE
[1.12.2] Induction matrix doesn't show any input/output characteristics.

### ISSUE THREAD

**Issue by SpaceBeeGaming** [aidancbrady/Mekanism#4843]
Didn't find any issues regarding this, so here it is.

#### Issue description:
Induction matrix doesn't show the input/output rates in any of the three places it is supposed to be showing it, main page, statistics page and the hover over energy symbol on the lower left.
It just reads "0" all the time, even though the energy buffer is rising.

#### Steps to reproduce:
1. Create an induction matrix of any tier (in creative mode) <= not sure whether there is any difference, blocks got through JEI.
2. Connect an energy input/output device into it.
3. Observe the energy levels rising/lowering and the matrix saying that it isn't inputting/outputting anything

#### Version (make sure you are on the latest version before reporting):
**Forge:14.23.0.2546** 
**Mekanism:9.4.2-327**

**Comment by soupmeister** [comment]
Also seeing this issue with an induction matrix that worked before updating.  GUI showing no input / output data.  OpenComputers is also reading 0 on input and output.

Forge:  14.23.1.2556
Mekanism:  9.4.2-327

**Comment by thommy101** [comment]
Is the InductionMatrix by any chance on a chunk border? There is a known issue somewhere that our multiblock structures do not play nicely when they cross chunk borders.

**Comment by SpaceBeeGaming** [comment]
Seems to be fixed.
Mekanism 9.4.3-330
Forge:14.23.1.2559
Closing issue.
