### ISSUE TITLE
EU Energy doesn't work with mekanism 1.10.2

### ISSUE THREAD

**Issue by Mirahine** [aidancbrady/Mekanism#4845]
#### Issue description:
The EU energy doesn't work with the machine of mekanism in the latest 1.10.2 version.
I have tested with MFSU/MFE to Elite/Ultimate Energy cube (in solo, creative mode), Geothermal Generator to metallurgic infuser (on server, survival mode).

#### Steps to reproduce:
Testing cable of IC2 or mekanism with IC2 energy and mekanism machines.

#### Version (make sure you are on the latest version before reporting):
**Forge: 12.18.3.2422
**Mekanism: 9.2.3
**Other relevant version: IC² 2.6.252-ex110
FTB Beyond 1.10.2
Only mekanism added

**Comment by thiakil** [comment]
I've never had any issues with EU, make sure you're using the correct output side on the MFSU/MFE

**Comment by Mirahine** [comment]
After some test, i can eject energy from an energy cube (or a wind turbine for example) to an MFSU.

But the issue is the same, i can't use IC2 energy for mekanism machine or energy cube.

**Comment by Mirahine** [comment]
No news?

**Comment by Kohtachan** [comment]
You can use the forestry electrical engine to convert eu to rf. That works for my mekanism machines.

**Comment by aidancbrady** [comment]
1.10.2 is definitely not supported anymore.
