### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Moobien** [aidancbrady/Mekanism#4846]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Hey guys, decided to update my mek version. was running Mekanism-1.12.1-9.4.1.326, MekanismGenerators-1.12.1-9.4.1.326 & MekanismTools-1.12.1-9.4.1.326 for MC 1.12.2 and updated to Mekanism-1.12.2-9.4.2.328, MekanismGenerators-1.12.2-9.4.2.328 & MekanismTools-1.12.2-9.4.2.328. according to my logs the Mekanism Generators is erroring and crashing Minecraft. I also tried MekanismAll-1.12.2-9.4.2.353eecc3 which @thiakil gave me and it crashes for the generators module.

https://gist.github.com/Moobien/a80ca24eeafa02808784fd460a505418

**Comment by Moobien** [comment]
Also with the previous version I was running the energized smelter wouldn't smelt "Steel Blend"

**Comment by thiakil** [comment]
Does nobody search? This has been duplicated 7 times already. #4827

**Comment by Moobien** [comment]
Has the steel blend issue been duped also?

**Comment by thiakil** [comment]
Does the steel blend work in a normal furnace? (I want you to actually test that, not just to say it normally does)

**Comment by Moobien** [comment]
Tested just then.

Energized Smelter: Can't shift click the TE Steel Blend in, but can manually place - does not smelt
Vanilla Furnace: same as Energized smelter
TE Induction Smelter: shift clicks in, smelts when sand also in the machine.

I don't know why but the TE Steel Blend is overriding the Mekanism Steel Dust.  I talked to KingLemming about this last night and he said that the output is ore dictionarying on your end but not inputting. 

https://imgur.com/a/aTZYZ

I run iron ingot through to Metallurgic infusers but the output of the 2nd one outputs steel blend instead of steel dust.

**Comment by Moobien** [comment]
From memory the steel blend isnt supposed to work in a standard furnace but i could be wtong

**Comment by thiakil** [comment]
>  I talked to KingLemming about this last night and he said that the output is ore dictionarying on your end but not inputting.

He's right about what is happening, but not *where*. The Infuser recipes are `ItemStack` based; there is no oredict on our end. Something else is attempting to unify.

**Comment by Moobien** [comment]
only possibilities then would be UniDict-1.12.2-1.2 or LibVulpes-1.12.2-0.2.6-12-universal  would these need to go?

**Comment by Moobien** [comment]
Testing now with UniDict removed, seems Advanced rocketry needs libvulpes

**Comment by Moobien** [comment]
tried with all 3 removed and no change.

**Comment by Moobien** [comment]
this is my modlist

ActuallyAdditions-1.12.2-r124.jar
AdvancedRocketry-1.12.2-1.2.5a-23.jar
animania-1.12.2-1.4.2.jar
ArmorStandGUI-1.12-1.0.4.jar
autoplant-1.12-1.0.0.jar
backpacks 1.12.2 - 3.4.2.jar
base-1.12-3.4.2.jar
BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar
BetterFoliage-MC1.12-2.1.10.jar
BiblioCraft[v2.4.3][MC1.12.0].jar
BowInfinityFix-1.11.x-1.12.x-rv5.jar
buildcraft-7.99.12.jar
Chameleon-1.12-4.1.3.jar
ChickenChunks-1.12-2.4.0.70-universal.jar
Chisel-MC1.12-0.0.14.18.jar
chiselsandbits-14.9.jar
Chunk Pregenerator V1.12-1.5.jar
Clumps-3.0.0.jar
CodeChickenLib-1.12-3.1.3.313-universal.jar
CoFHCore-1.12-4.3.6.14-universal.jar
CoFHWorld-1.12-1.0.1.8-universal.jar
CoralReef-2.2-1.12.2.jar
CraftStudio-1.0.0.93-mc1.12-alpha.jar
CraftTweaker2-1.12-4.0.10.jar
CTM-MC1.12-0.2.3.9.jar
davincisvessels-1.12-6.340-full.jar
Decocraft-2.5.2_1.12.2.jar
EnchantingTable-1.12-1.1.2.jar
extrautils2-1.12-1.6.7.jar
ExtremeReactors-1.12-0.4.5.44.jar
FastLeafDecay-v14.jar
FTBLib-4.2.3.jar
Futurepack-1.12.1-26.2.27.jar
HoloInventory-1.12.2-2.0.2.148.jar
InventoryTweaks-1.63.jar
IronBackpacks-1.12.2-3.0.1-2.jar
ironchest-1.12.2-7.0.34.820.jar
IronMan-Beta-1.12-1.0.1.jar
jei_1.12.2-4.8.0.114.jar
journeymap-1.12.2-5.5.2.jar
LC 0.0.1.jar
LibVulpes-1.12.2-0.2.6-12-universal.jar
list.txt
lostcities-1.12-1.0.2.jar
LucraftCore-1.12-1.2.3.jar
Mantle-1.12-1.3.1.21.jar
MCA-1.12.x-5.3.1-universal.jar
mcjtylib-1.12-2.4.5.jar
MCMultiPart-2.3.3.jar
Mekanism-1.12.1-9.4.1.326.jar
MekanismGenerators-1.12.1-9.4.1.326.jar
MekanismTools-1.12.1-9.4.1.326.jar
minecolonies-universal-1.12.2-0.8.5743.jar
modeltrains-1.2.2.jar
mods.txt
movingworld-1.12-6.342-full.jar
natura-1.12-4.3.0.23.jar
NotEnoughItems-1.12-2.4.0.231-universal.jar
omlib-1.12.2-3.0.0-131.jar
openmodularturrets-1.12.2-3.0.0-227.jar
OptiFine_1.12.2_HD_U_C6.jar
platforms-1.12.0-1.4.1.jar
RadixCore-1.12.x-2.2.1-universal.jar
railsplus-1.0.1.jar
realms_persistence.json
RebornCore-1.12.2-3.4.12.155-universal.jar
RebornStorage-1.12.2-2.1.1.16.jar
RedstoneFlux-1.12-2.0.1.2-universal.jar
refinedstorage-1.5.23.jar
rflux-1.12-0.1.2.jar
rftools-1.12-7.13.jar
Roads-1.12.2-1.0.1.jar
shetiphiancore-1.12.0-3.5.4.jar
Signals-1.12.2-1.0.0-universal.jar
SpacePackExtended-1.12-2.2.4-alpha.jar
SpawnTemple-v.2.1-mc1.12.jar
StevesCarts-1.12.2-2.4.12.62.jar
StorageDrawers-1.12.1-5.3.3.jar
switchbow-1.5-1.12.2.jar
TConstruct-1.12-2.7.4.34.jar
ThermalCultivation-1.12-0.1.1.6-universal.jar
ThermalDynamics-1.12-2.3.6.13-universal.jar
ThermalExpansion-1.12-5.3.6.20-universal.jar
ThermalFoundation-1.12-2.3.6.16-universal.jar
tombstone-1.6.0-1.12.jar
torohealth-1.12.2-11.jar
TreeChopper-1.12.2-1.2.4.jar
VeinMiner-1.12-0.38.1.639+134fb1e.jar
VillageNames-1.12.2-2.0.jar
WanionLib-1.12.2-1.2.jar
wolfarmor-1.12.2-2.1.0.24-RELEASE.jar
YABBA-1.0.10.jar
zerocore-1.12-0.1.1.0.jar

**Comment by thiakil** [comment]
This is a pack level issue. Take it up with your pack maker if it is a pre-made one, or solve it yourself if it is something you put together.

**Comment by Moobien** [comment]
its one I did myself. Thanks for your help though Thiakil, go enjoy the rest of your sunday afternoon :)
