### ISSUE TITLE
[1.12.2] Teleporter requires almost no energy to use.

### ISSUE THREAD

**Issue by AcidKat** [aidancbrady/Mekanism#4847]
#### Issue description:

The Teleport Block has a power capacity of ~5 Million RF however it only seems to require a negligible amount of Power to actually activate and send players / entities through... I'm guessing this is a bug, and there doesn't seem to be anywhere in the config to edit the values.

If the energy requirement isn't a bug, then I'd like to request a config option so it can fit better into my mod pack.

Love the mod btw!!!

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.1.2559
**Mekanism:** 9.4.2.327

**Comment by thommy101** [comment]
Currently the costs is calculated as follows:
baseCost (1000) + (distance*10) + crossDimensionPenalty (10.000)

It makes sense to configure these values in the settings.

**Comment by thommy101** [comment]
Added some config values for all the three constants.

TeleporterBaseUsage=1000
TeleporterDimensionPenalty=10000
TeleporterDistanceUsage=10

**Comment by thommy101** [comment]
Now commited the fix to the right repository..
