### ISSUE TITLE
Universal cables not transferring energy

### ISSUE THREAD

**Issue by Aphenon** [aidancbrady/Mekanism#4853]
#### Issue description:
Universal cables keep "disconnecting" from eachother, they look connected, but do not transfer energy. This appears to happen randomly, when i am in the area or logged out/away from the area.

#### Steps to reproduce:
1. unsure how to reproduce reliably.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge: forge-1.12.2-14.23.1.2555-universal
**Mekanism: Mekanism-1.12.2-9.4.2.327
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
If there is a relevant log anywhere, let me know.
[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
Longstanding bug, only part of which we've been able to figure out. #4676
