### ISSUE TITLE
[1.12.2] MekanismGenerators error?

### ISSUE THREAD

**Issue by BlueAvian** [aidancbrady/Mekanism#4855]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I've been mostly using 9.4.1.326 for mostly all my messing about, as the latest version seems to have conflicted with my mod setup. Updating to the latest version seems to have a glaring issue, of things not properly loading in the correct order. The pack of mods is rather large, because I'm always open for testing new things, seeing how they interact and so on.

I mostly updated to try and fix pipes and such not properly supplying water to the Rotary Condensentrator, for some reason things kept not wanting to place and such. So I figured what the heck, and given an error of things not properly registering in the correct order. I wondered what could possibly be causing that? Since I don't recall anyone posting about it, and it's honestly had me scratching my head. My mod list is well over 100, so obviously there's a lot of places I could look. Just figured I'd start where things seem to be pointing.

Forge: 14.23.1.2555
Mekanism: 9.4.2.327

Crash log:
https://pastebin.com/2hr6hVdx

**Comment by aldra2012** [comment]
already reported and fixed #4827
