### ISSUE TITLE
[1.12.2] Crash whenever I place energy storage or transfer blocks

### ISSUE THREAD

**Issue by razage** [aidancbrady/Mekanism#4857]
#### Issue description:
Whenever I place a storage block (energy, fluid, gas), connect a pipe to anything, or place a pipe in general the game crashes. Most of the the time I can restart the game and the pipe/storage block will be working correctly, but crashing every time you place a pipe makes things pretty annoying. Other mods that have transfer or storage blocks connect to Mekanism machines fine and don't cause a crash.

#### Steps to reproduce:
1. Place any energy cube, gas tank, or the related transfer pipes.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.1.2562
**Mekanism:** 9.4.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/h9ZbDe9U

**Comment by josephcsible** [comment]
For the sake of testing, see if removing MCMultipart makes it stop.

**Comment by razage** [comment]
I removed MCMultipart, made a new world, and placing an empty gas tank causes the same crash. 

Here's the log for that crash: https://pastebin.com/iJjtn3vw

**Comment by thiakil** [comment]
There is absolutely nothing on those lines that I can see that should ever be null. Something in your mods is being screwy.

**Comment by razage** [comment]
It wasn't any of the coremods, but I found the issue. Since posting this issue, I had to remove Fancy Block Particles because it was causing problems with Botania flowers. It turns out that also was causing this crash in Mekanism. It has some kind of issue with blocks that have tags, so in Botania's case, the flowers didn't render or function. In this case, it causes a crash I guess.
