### ISSUE TITLE
[Feature Request] Atomic Disassembler Configuration

### ISSUE THREAD

**Issue by AcidKat** [aidancbrady/Mekanism#4860]
Any chance we could get an option to change how much energy the Atomic Disassembler uses?
I found this in the Config under "General":

> I:DisassemblerEnergyUsage="x"

Changing this doesn't seem to have any effect on the Atomic Disassembler... so I'm guessing either this setting is meant for something else or simply isn't working as intended. Either way, I'd like to have a way to either scale all the amounts (eg. increase or decrease overall Disassembler power usage), or assign individual usage amounts to each mode on the assembler.

**Comment by thommy101** [comment]
The DisassemblerEnergyUsage seems working for me. Changing its value from 10 to 1000 definitely increased the energy usage.
Breaking a block costs 10 energy by default, 1000 after my change.

Could you provide a scenario where it isn't increasing as you think it should?

**Comment by AcidKat** [comment]
Changing the value for me has no effect, screenshot below after the change from default to 1000:

![2017-12-16_15 43 39](https://user-images.githubusercontent.com/15000462/34072022-03eac79c-e278-11e7-8f1a-470e0bdd9a57.png)

Note: I used the assembler on some dirt to make sure that the problem wasn't simply with the "Efficiency" stat on the tool-tip (which I understand is supposed to display the energy usage), the result was that 20 J were used for each dirt mined, which is the same as if I had not changed the config at all.

pastebin of my config file:
https://pastebin.com/NX38ifWj

Seems like for some reason the setting simply isn't working for me.

**Comment by AcidKat** [comment]
Tested on a fresh install:
Forge: **14.23.1.2566**
Mekanism: **9.4.2.327**
(+ some thermal expansion mods.)
Same results.

**Comment by thommy101** [comment]
@AcidKat, looked though some stuff, I can't find an explanation to the stuff your seeing.

Is it still happening?

**Comment by AcidKat** [comment]
Problem persists, unchanged from the behaviour I stated before, (even after update to forge 14.23.1.2582 & mekanism 9.4.3.330)
