### ISSUE TITLE
Turbine drops my FPS

### ISSUE THREAD

**Issue by Xiaminou** [aidancbrady/Mekanism#4861]
#### Issue description:
Built a 11x11x18 turbine and my FPS dropped from 200 to 20.
Here is a video example with Mekanism only: https://youtu.be/_mpVu5Ke0D0

Note: I had a smallest sized turbine before that and my FPS weren't nearly as bad.

#### Steps to reproduce:
1. Build a large Turbine

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2562
**Mekanism:** 9.4.3.329-thiakil
**Mods:** [list.txt](https://github.com/aidancbrady/Mekanism/files/1553809/list.txt)

**Comment by Xiaminou** [comment]
Also what happened to the connected textures?

**Comment by josephcsible** [comment]
Hmm, seems like #4829 again.

**Comment by Xiaminou** [comment]
Is it thought? Thiakill said it's fixed and my turbine is not opaque.

**Comment by jonabrv1965** [comment]
Same here! tested in a creative world with just mekanism mod installed (and its required ones) and MC simply die (I got kicked to the main menu with an error about server not responding...not crash... but render the game unplayable)
MekanismGenerators-1.12.2-9.4.2.328
Mekanism-1.12.2-9.4.2.328
forge-1.12.2-14.23.1.2562

It does not matter the size of the turbine (at least in my creative test) and yes, the turbine does not show the animation just opaque blocks inside.

**Comment by thommy101** [comment]
@jonabrv1965 328 should contain a fix to address this issue, but, sadly, @Xiaminou reported the bug with version 329 which indicates it isn't fixed yet..

I'll take a look if I can reproduce it with the latest version.

**Comment by thommy101** [comment]
Tried to reproduce it.. I sadly cannot reproduce it. There might be two reasons, @thiakil made a wrong version, not containing the fix, or you've got another setup than I have..

My setup:
![afbeelding](https://user-images.githubusercontent.com/1036527/34070611-2db66cb6-e269-11e7-892f-50f0328f53c0.png)

**Comment by Xiaminou** [comment]
Well then can someone host the files for the latest version please?

**Comment by thommy101** [comment]
Compiled from development commit 7c14b3d520232c379dce3855d0403c6f8c40b5b8
This is exactly the version I'm currently using

[Mekanism-1.12.2-9.4.3.7c14b3d520232c379dce3855d0403c6f8c40b5b8.jar.zip](https://github.com/aidancbrady/Mekanism/files/1564801/Mekanism-1.12.2-9.4.3.7c14b3d520232c379dce3855d0403c6f8c40b5b8.jar.zip)

**Comment by jonabrv1965** [comment]
Hi Thommy, when I tried to run the version you linked above, I got a message about wrong mekanism generators and tools versions... can you send those links also? thanks in advance!

**Comment by thommy101** [comment]
My version is an all in one if I made the correct one.

**Comment by thommy101** [comment]
@jonabrv1965 My bad, the compilation has changed a bit since I last build a version..
Here's a good upload, with 3 jar files.

[Mekanism-1.12.2-9.4.3.7c14b3d520232c379dce3855d0403c6f8c40b5b8.zip](https://github.com/aidancbrady/Mekanism/files/1565613/Mekanism-1.12.2-9.4.3.7c14b3d520232c379dce3855d0403c6f8c40b5b8.zip)

**Comment by Xiaminou** [comment]
Fixed in 230.
