### ISSUE TITLE
Digital Miner can't mine Lapis

### ISSUE THREAD

**Issue by CustodianKin** [aidancbrady/Mekanism#4862]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When using the Digital miner and I tell it to mine Lapis it tells me that there is Lapis but just skips it

#### Steps to reproduce:
1. Set down the Digital Miner
2. Set it to mine oreLapis in the Ore Dict. with silk touch checked
3. Start it and watch as it nothing is mined

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.1.2566
**Mekanism: 1.12.2-9.4.2.327
**Other relevant version: Minecraft v 1.12.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
If the count starts high and then goes to zero as it is running you have some kind of chunk protection active that prevents fake players from breaking blocks.

**Comment by chardo440** [comment]
I had this same issue. It mines every other block just fine though I just can't get it to mine lapis myself. I'm using the ATM 3 pack maybe a config option or something like your saying?

**Comment by thiakil** [comment]
same issue as #4841 then, which is fixed for 329
