### ISSUE TITLE
Energy pipes not transferring energy until broken and replaced

### ISSUE THREAD

**Issue by chardo440** [aidancbrady/Mekanism#4863]
I searched and found a few posts of the older versions but no one offered a fix so I'm asking again for 1.12.2

If I wander away from base then teleport home the energy conduits will not transfer any power at all until I update every single pipe by breaking them and replacing them then the system works again just fine. Is there a fix for this or do I just need to break the pipes every time I come back to base? I'm using atm 3 5.3 pack.

To repoduce...

1. Have something that generates power.
2. Run the energy cables from said generator to something that is using the power like a 3x ore processing system that is currently working on dusting them down.
3. Leave the base travel 500 or so
4. Teleport home 

That will make all of the conduits need an update to start powering the machines again to finish the job.

EDIT: This is even true for pressurized tubes as well with gasses. Wasn't getting hydrogen out of the seperator until I broke the pipes and replaced them.

**Comment by thiakil** [comment]
Same as #4676. There is still at least one edge case we have not been able to solve.
