### ISSUE TITLE
[1.12.2] Gas tanks seem to not implement drawGas despite allowing output sides to be set

### ISSUE THREAD

**Issue by asiekierka** [aidancbrady/Mekanism#4867]
Is this an intentional design decision or an omission?

**Comment by thommy101** [comment]
My guess (no guarantees it would be correct) is that the gas tank pushes the gas when set to output. Allowing pipes (and other stuff) pull would be a bit double..

**Comment by asiekierka** [comment]
This might cause trouble with potential other mods which cannot support a push-based setup, however. Especially as other machines can be extracted from...

**Comment by thommy101** [comment]
Aaah.. I now see why you reported it.. YNot!
Nice, it was somewhere on my todo list to look into to make, nice to see it already has happened.

I'll see what I can do to make it work :)

**Comment by thommy101** [comment]
@asiekierka I made some changes. Will test tomorrow if it works with YNot & XNET and it doesn't have any side effects (see PR #4870).

**Comment by thommy101** [comment]
![afbeelding](https://user-images.githubusercontent.com/1036527/34079384-00efd202-e32d-11e7-949d-303668fe360e.png)

This is looking good. No weird side-effects.
Feel free to test :)
