### ISSUE TITLE
Recipe Issues

### ISSUE THREAD

**Issue by TheSpicePhantom** [aidancbrady/Mekanism#4873]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*
- Done.
#### Issue description:
I got Thermal Foundation (for ores), UniDict (simple ore-dict conversion to only 1 type of Ingot and so on) and Mekanism installed, now my issue is that whenever I want to craft nuggets, i'm getting Mekanism nuggets from any type of copper ingot, which, when I craft it back, gets a Mekanism ingot and no thermal foundation one.

Relevant Mods are:
1. UniDict version 1.12.2-1.6 (neds to have a config option set to only "thermalfoundation" to work properly)
2. ThermalFoundation version 2.3.7.18
3. Mekanism version 9.4.2

#### Steps to reproduce:
1. Take 1 copper ingot (any kind, preferably TE).
2. Place it in a crafting grid, craft nuggets.
3. Craft nuggets to ingot and see what happens.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.1.2560
**Mekanism:** 9.4.2
**Other relevant version:** -

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
-
[gist/pastebin/etc link here]

**Comment by thommy101** [comment]
This does sound like an unidict issue. Have you also reporting it to them?

**Comment by thiakil** [comment]
Definitely not our issue that Unidict is not doing what it says it will do.

**Comment by SHIuSH** [comment]
can you disable recipes for crafting blocks/ingots/nuggets of metals when Unidict mod is present in the modpack? there is no option to disable it in the config. [Submitted to Unidict.](https://github.com/WanionCane/UniDict/issues/62) but please don't close the issue if it is not resolved.

**Comment by thiakil** [comment]
Currently I do not believe there is an option. They can however be removed by crafttweaker

**Comment by thommy101** [comment]
Tried to convert recipes (where possible) to the default forge recipes in #4906. Will test that tomorrow to make sure everything works as before. Should fix this issue :)
