### ISSUE TITLE
Ore Gen option missing

### ISSUE THREAD

**Issue by TheSpicePhantom** [aidancbrady/Mekanism#4875]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
There is no option in the config files to disable ore-gen.

#### Steps to reproduce:
1. Read above.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.1.2570
**Mekanism:** 1.12.2-9.4.3.330
**Other relevant version:** -

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
-
[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
```
I:CopperPerChunk=16
I:OsmiumPerChunk=12
I:SaltPerChunk=2
I:TinPerChunk=14
```

**Comment by thommy101** [comment]
You've just beat me to it... I had exactly the same in my clipboard.

**Comment by TheSpicePhantom** [comment]
Well... not very obvious to be honest
