### ISSUE TITLE
Mekanism Versioning

### ISSUE THREAD

**Issue by jkroepke** [aidancbrady/Mekanism#4877]
#### Issue description:
Mekanism versioning isn't good if somebody want to use it for dependencies because prefixing the Minecraft version is bad.

Forge allows to be define a minium version of a mod as requiring, for example:

```
@Mod(modid = SodiumCraft.MODID, version = SodiumCraft.VERSION, dependencies="required-after:mekanism@[9.4,);required-after:thermalexpansion@[5.3,)")
```

On Mekanism, we should now require defining something like 

```
dependencies="required-after:mekanism@[1.12.2-9.4,)")
```

But If I support multiple Minecraft version like 1.11 and 1.12 or some minor versions, e.g. its nearly impossible to use a constant minimum-version.

Other Mods like ThermalExpansion do not use mc verson as prefix, too.

```
$ unzip -q -c Mekanism-1.12.2-9.4.3.330.jar mcmod.info | grep '"version"'
  "version": "1.12.2-9.4.3.330",

$ unzip -q -c ThermalExpansion-1.12.2-5.3.7.31-universal.jar mcmod.info | grep '"version"'
                "version": "5.3.7.31",
```

**Comment by thommy101** [comment]
Well... I first thought it was a mistake in the mcmod.info file. It seems that since our last release the way the version is replaced has been changed and somehow incluses the mc version, which is certainly not the way it's supposed to work.

If you look at our previous version (build 327), that's the way it's supposed to be.

**Comment by jkroepke** [comment]
Fine. Okay thanks. 

327 doesn't have the compability fixes for buildcraft so i'm locked on this version for now.

**Comment by thiakil** [comment]
I can see how the change would have affected your dependency string, sorry that it slipped through.

Though it should not be a problem going forward *if* we leave it as is - the version numbers are different between the MC releases anyway so you'd still need to change it. 

I also don't see how prefixing the mc version is "bad"

**Comment by jkroepke** [comment]
>  the version numbers are different between the MC releases anyway so you'd still need to change it.

Do you bump your version, if you move from 1.12.2 to 1.12.3?

I cant define a dependency like 1.12.*-9.4, can I?

**Comment by thiakil** [comment]
Why would you need to? `1.12.2 < 1.12.3`. If that does not hold true, that's a Forge bug

**Comment by jkroepke** [comment]
Fine.

Then its just my personal opinion. 

At least it breaks the compability with other mods like SodoumCraft and shoud be only happen on major version changes.

Anyway, I want the new version schema, feel free to close this issue.
