### ISSUE TITLE
Cardboard Box breaking ExtraUtils2 machiens

### ISSUE THREAD

**Issue by xenoflot** [aidancbrady/Mekanism#4878]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Some data is being lost when the Cardboard Box does its thing on ExtraUtils2 machines. Getting back a Machine Block instead of the machine.

#### Steps to reproduce:
1. Place an ExtraUtils2 machine (I tested with Furnace and Crusher
2. Drop a box over it
3. Remove the box
4. Presto! You have a Machine Block

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.1.2560
**Mekanism:** 9.4.2
**Other relevant version:** EU2 1.2-1.6.8

Found a similar issue for IC2 machines but none for EU2 machines

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
Unfortunately ExU2 machines need extra info from the itemblock, which is incompatible with the way the cardboard boxes work.

I have blacklisted them.

**Comment by xenoflot** [comment]
Thanks!

**Comment by thommy101** [comment]
Released in in version 9.4.4
