### ISSUE TITLE
Jetpack drains fuel while being in spectator mode.

### ISSUE THREAD

**Issue by SirWindfield** [aidancbrady/Mekanism#4880]
#### Steps to reproduce:
1. Equip jetpack and load with fuel.
2. Enable hover mode.
3. Switch to spectator mode. The jetpack sound is still active as are particles and the jetpack HUD. You can see the drain there too.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.1.2566
**Mekanism:** 9.4.3.330 

**Edit:** Might fix this. Never contributed to Mekanism but a simple `isSpectator` check should be fairly easy.

**Comment by thiakil** [comment]
While I'd love to blame this on user error (shouldnt really be using anything in spectator mode, no?) it is indeed an oversight

**Comment by SirWindfield** [comment]
Was more by accident than anyting else. I wanted to take a look at how my setup looks under the earth and thought that spectator might be the easiest ^_^ 
But you are right, normally you aren't using any items in spectator though.

**Comment by SirWindfield** [comment]
@thommy101 Ah, that explains why it didn't work on my fork. I didn't override the ClientTickHandler :smile:. TIL I guess ^^

**Comment by thommy101** [comment]
No problem ;)

The magic of client and server side code.... Both need to be changed :)

**Comment by SirWindfield** [comment]
I wonder why there needs to be two classes that basically contain the same things tbh. Wouldn't one source of truth (server) be more efficient in general? And just put the render specific code into the client and sync the rest. But they probably had their reasons to write it that way :smile:
