### ISSUE TITLE
AE2 dust recipes missing from Mekanism Crusher

### ISSUE THREAD

**Issue by Atolm4** [aidancbrady/Mekanism#4881]
#### Issue description:
Nether quartz dust from Applied Energistics 2 can be produced in the crusher, but certus, charged certus and fluix dust cannot. It appears these recipes were added some time in 2014, but are now missing.

#### Steps to reproduce:
1.Place certus quartz or fluix into crusher.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.2-14.23.1.2555-universal
**Mekanism:** 1.12.2-9.4.3.330
**Other relevant version:** appliedenergistics2-rv5-stable-3

**Comment by thiakil** [comment]
Yup, they need to re-add their integration.

**Comment by mrAndersen** [comment]
Any news on this one ?

**Comment by zygimantas** [comment]
As a workaround you can add a custom recipe using crafttweaker, if I remember the name correctly

**Comment by mrAndersen** [comment]
As i found, MineTweaker3 supports only minecraft 1.8, but my server uses 1.12.2 ..

**Comment by zygimantas** [comment]
There is a replacement for minetweaker for 1.12, I use it and added quartz recipes to crusher.

-------- Original Message --------
Subject: Re: [aidancbrady/Mekanism] AE2 dust recipes missing from Mekanism Crusher (#4881)
From: Armen Alaverdyan
To: aidancbrady/Mekanism
CC: Zygimantas Berziunas ,Manual


As i found, MineTweaker3 supports only minecraft 1.8, but my server uses 1.12.2 ..
