### ISSUE TITLE
Factories flicker when right clicking to open GUI

### ISSUE THREAD

**Issue by SirWindfield** [aidancbrady/Mekanism#4886]
I have basic 3x ore setup that uses elite factories. Each time I input iores into the purification chamber using emvber item pipes, the machine block itself changes its texture and the texture starts flickering (the blue illumination effect turns on and off repeatedly).
If I try to open the GUI, the same strange behaviour occurs here. The GUI is flickering, item stacks are disappearing and apperaing again aswell as the output too. The gas indication isn't effected by this behaviour iirc. 

It's just a visual bug, the machine behaves as usual. It outputs the clumbs into the next machine wuthout any issues. 

Forge: 14.23.1.2555 
Minecraft: 1.12
Mekanism: 9.4.3.330

Happened on the earlier version that I had installed (329...?) too.

**Comment by thommy101** [comment]
Couldn't reproduce this locally. Sounds like another mod messing with rendering. Do you have any other mod which might cause this, think of optifine/betterfps?

**Comment by SirWindfield** [comment]
ye, both, i will disable them and report back!

**Comment by SirWindfield** [comment]
I deinstalled OptiFine and BetterFPS but the glitch still appeared once out of 20 times I tested it. It doesn't occur everytime now but I am still kind of able to reproduce it.

**Comment by SirWindfield** [comment]
Ok so I tried this again (after upgrading my graphics card drivers) and the problem is gone. It was probably just my setup I guess .Sorry for the inconvenience.

**Comment by thommy101** [comment]
No problem. Thanks for reporting back :)
