### ISSUE TITLE
[Suggestion] Salt oredict

### ISSUE THREAD

**Issue by Lukas45** [aidancbrady/Mekanism#4888]
Mekanism salt doesn't work with quite a few food recipes, because they look for the oredict "foodSalt", which the Mekanism salt doesn't have.

**Comment by thommy101** [comment]
Mekanism salt does have "itemSalt" and "dustSalt", which already covers a lot. Which mod is explicitly looking for foodSalt?

**Comment by thiakil** [comment]
Food based mods such as Pam's IIRC ;)

**Comment by thommy101** [comment]
Pams supports all 3 :) item, dust & food.

**Comment by thommy101** [comment]
Well.. Why not, what could go wrong.

**Comment by Lukas45** [comment]
Nice, thanks :D 
Around 1/3rd of Pam's salt recipes (maybe a bit less) only supports foodSalt. Not sure why, and may even be changed in the latest update which we haven't moved to yet.

**Comment by thommy101** [comment]
Please leave it open, so the issue is closed when a release is made :)
