### ISSUE TITLE
[Crash] Using CraftTweaker to remove compressed ingredients' recipes from Enrichment Chamber gives an NPE

### ISSUE THREAD

**Issue by Fogrits** [aidancbrady/Mekanism#4890]
Trying to use
```
mods.mekanism.enrichment.removeRecipe(<mekanism:compressedCarbon>);
mods.mekanism.enrichment.removeRecipe(<mekanism:compressedRedstone>);
mods.mekanism.enrichment.removeRecipe(<mekanism:compressedDiamond>);
mods.mekanism.enrichment.removeRecipe(<mekanism:compressedObsidian>);
```
crashes the game with a NPE pointing at **RemoveMekanismRecipe** and **Enrichment$Remove**

• Versions used:
*Forge*: **14.23.1.2555**
*Mekanism*: **9.4.3.330**
*CraftTweaker*: **4.0.12**
*ModTweaker*: **4.0.6**
*MTLib*: **3.0.1**

[Crash Report](https://pastebin.com/36R1yzC9)

**Comment by thommy101** [comment]
Thank you for the report. There is indeed a bug.
I didn't think of the optional arguments with logging. Will fix this soon.

The line's you're using aren't going to work. In 1.12.2 is everything lowercased, so please check your item names. I guess (don't have a dev environment/game in front of me) that they should be as follows:

```
mods.mekanism.enrichment.removeRecipe(<mekanism:compressedcarbon>);
mods.mekanism.enrichment.removeRecipe(<mekanism:compressedredstone>);
mods.mekanism.enrichment.removeRecipe(<mekanism:compresseddiamond>);
mods.mekanism.enrichment.removeRecipe(<mekanism:compressedobsidian>);
```

**Comment by Fogrits** [comment]
turning it lowercase gives out a
```No Mekanism Enrichment Chamber recipe found for <mekanism:compressedcarbon> and <*>. Command ignored!
```

**Comment by thommy101** [comment]
Hmm.. That's the exception I was expecting with the first command. Will take a look tonight.

**Comment by thommy101** [comment]
... Well.. That explains a lot. Enrichment chambers have a required input argument and an optional output argument. ( http://wiki.aidancbrady.com/wiki/Tutorials/CraftTweaker )
You need to remove them by the input value.

compressedcarbon -> minecraft:coal:*
compressedredstone -> minecraft:redstone
compresseddiamond -> minecraft:diamond
compressedobsidian -> mekanism:otherdust:5
