### ISSUE TITLE
Anchor upgrades not properly working.

### ISSUE THREAD

**Issue by SirWindfield** [aidancbrady/Mekanism#4897]
I have two teleporters, each getting powered using one of those quantum devices. All four machines have the anchor upgrade and still, after joining the server, the teleportation frames aren't connected anymore. If I step into the chunk that the second teleporter has been placed in, the connection will get restored. 
I made sure that my power plant is also chunk loaded. Both teleporters are build in one single chunk each, same goes for the power plant.

**Edit:** Chunkloading is enabled within the config file.

**Comment by thiakil** [comment]
Are they in vanilla dimensions?

**Comment by SirWindfield** [comment]
Yep, all of those machines are within the overworld.

**Comment by thiakil** [comment]
Can you test your setup with an alternative power source, like a creative energy cube?

Need to rule out it being a power issue I guess

**Comment by SirWindfield** [comment]
Will do so later on, I currently have not access to the server. How exactly do those anchor updates work? Do they just load the chunk that the machine is placed in? Or do they also load anything that is connected to that machine too (like elite cables, heat generators etc.).

**Comment by SirWindfield** [comment]
So I replaced my quantum energy thingies with creative energy cubes and restarted the server. Same behaviour. I still need to get the chunks loaded once before the frame works. Which is quite the pain because my second teleporter is about 7000 blocks away >.>

**Comment by Florek81** [comment]
Hi,
same happened with my teleporter. I have two with an anchor upgrade and the chunk isn't loaded. I didn't noticed it, because the chunk was allways loaded while my friend was in his base. Now we built an DE Reactor and the reactor has dropped is energy output and the teleporter worked a little bit weird. My server console gave me this warn:  **_[ic2-poolthread-4/WARN] [ic2.EnergyNet]: Tile mekanism.common.tile.TileEntityQuantumEntangloporter@7ac2af9b (dim 0: 260/53/141) removal without registration_**

I found out that this is an problem with no chunkloading. Added chunkloading from Forge and now it works properly. So it seems that the anchor didn't work well.

**Comment by SirWindfield** [comment]
I think the issue is actually that anchor updates to not load on server startup. They keep the chunk loaded **if** it has already been loaded from either visiting the area or some other chunk loader. I know that chickenchunks loads up chunks at server startup. And since our server restarts every 24 hours, I had to tp to the location to load it once before having a working teleportation device. I think it's just how the anchor update works. Not sure if it is by design and the maker just does not want to have chunks loaded on startup, maybe it's hard to implement. I don't know :smile:

**Comment by thiakil** [comment]
> I think the issue is actually that anchor updates to not load on server startup. They keep the chunk loaded if it has already been loaded from either visiting the area or some other chunk loader.

They use the forge system that *does* load on startup

**Comment by SirWindfield** [comment]
I actually do have them installed just in the overworld. No cross-dimension stuff is going on. I could replicate the problem 100% of the time after a server restart. It is kind of strange. Maybe the data saved is incorrect, as you stated.

**Comment by thiakil** [comment]
All I can say is that I know it *does* work. However you have not provided any necessary details. Don't ignore the issue template.

**Comment by SirWindfield** [comment]
Well, I can't tell you more than what has already been told. My setup is described in my very first comment. The log does not contain any error besides the one posted by @Florek81. I missed that one while creating the issue. I can see if I can still dig up some log files if you want them though. 
**Edit:** We rented the server and it seems that I can no longer access the old log files since they got removed automatically.
It only occured after server restart before the chunk got loaded by any players. If I visited the area once by myself, the teleporters and quantum devices worked without any problem before the next server restart. I even used create energy cells to make sure that it is not a power bottleneck, but that did not prevent the error from happening. 
I can surely tell you that it does not work in my world as expected. As I can't travel through the teleporter frame before I did not visit my destination chunk.

**Comment by thiakil** [comment]
**There are no version number posted and no mod list. Literally anything could be stopping it from working.**

**Comment by SirWindfield** [comment]
Minecraft: 1.12.2
Forge: 14.23.1.2577
Mekanism: 9.4.3-330

[list.txt](https://github.com/aidancbrady/Mekanism/files/1692744/list.txt)

**Comment by Tresmollo** [comment]
Tested with forge 14.23.2.2611 same issue

procedure to replicate : 
- place a creative energy cube with a teleporter on top, set the frequence and add the anchor upgrade
- go away far enough to unload the chunk
- restart server or client if in single player
- try to teleport on set frequence with a portable teleporter, doesn't work, there is no link

Minecraft: 1.12.2
Forge: 14.23.2.2611
Mekanism: 9.4.3-330

[latest.log](https://github.com/aidancbrady/Mekanism/files/1725133/latest.log)
[fml-junk-earlystartup.log](https://github.com/aidancbrady/Mekanism/files/1725134/fml-junk-earlystartup.log)
[fml-client-latest.log](https://github.com/aidancbrady/Mekanism/files/1725135/fml-client-latest.log)

**Comment by thiakil** [comment]
Works fine for me, at least in my dev environment tests

**Comment by thiakil** [comment]
Apologies, there were indeed some lingering issues with anchor upgrades which should be fixed now

**Comment by SirWindfield** [comment]
What was the problem?

**Comment by thiakil** [comment]
One was saving some data with one key and trying to read a different one, and another issue regarding the internals of bringing the chunk ticket back up on world load

**Comment by Fatmice** [comment]
We're experiencing the same issue when chunkloading in an RFtools Dimension.  The dimension had two chunks that were loaded with entangolopers that had an anchor upgrade.  Those chunk will only stay loaded after a server restart if we venture into that dimension. 

Mekanism-1.12.2-9.4.13.349

**Comment by thiakil** [comment]
Please update to the latest version of Mekanism. The version you mentioned does not contain the fix.
