### ISSUE TITLE
[Suggestion] Oredict sawdust recipes

### ISSUE THREAD

**Issue by SHIuSH** [aidancbrady/Mekanism#4901]
mekanism sawdust is incompatible with thermalfoundation's sawdust in some recipes like making paper, cardboard

**Comment by SHIuSH** [comment]
Yeah apparently mekanism's recipes don't use oredict sawdust yet mekanism's sawdust is present in oredict

**Comment by ProsperCraft** [comment]
Yes please, I ran into the same issue.

**Comment by thiakil** [comment]
fixed in d8a4972

**Comment by thommy101** [comment]
Released in in version 9.4.4
