### ISSUE TITLE
Crash on Start

### ISSUE THREAD

**Issue by Chungusfungus** [aidancbrady/Mekanism#4902]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Custom modpack on 1.10.2, crashes on startup, mekanism, techreborn, and thermal expansion seem to be the cause of the crash. The game automatically quits when fml is on stage 6/7. Couldn't find anything similar to my crash log so that's why I'm submitting this as an issue.

#### Steps to reproduce:
1.Launch game

#### Version (make sure you are on the latest version before reporting):
**Forge:12.18.3.2422** 
**Mekanism:9.2.3.97** 
**ThermalExpansion:5.1.10.28-universal**
**TechReborn:2.1.18.235-universal**

[https://pastebin.com/SXpfUCFW]

**Comment by thommy101** [comment]
Please update wireless crafting terminal and try again :)

**Comment by Chungusfungus** [comment]
Yup that fixed it. I dont know how that caused mekanism and some other mods to error but thanks for thr fix.
