### ISSUE TITLE
Logistic pipes cause lag.

### ISSUE THREAD

**Issue by binary-dragon** [aidancbrady/Mekanism#4908]
I've searched but found nothing. Logistic pipes on my server cause lag when items are passing through them and are rendered. Is there a way to turn item rendering off in those pipes?

**Comment by thommy101** [comment]
There's a config option for it: OpaqueTransmitterRender

**Comment by aidancbrady** [comment]
^^

**Comment by binary-dragon** [comment]
That option turns off ALL the pipes, I just want Logistic Pipes item rendering off.

If I turn this on, I can't see if power pipes are working. :/
