### ISSUE TITLE
DigitalMiner crash, still hapening?

### ISSUE THREAD

**Issue by Janrupf** [aidancbrady/Mekanism#4910]
### Issue description:
IllegalStateException with TileDigitalMiner
I already saw this closed, but I'm going to open a new issue because this happens with the latest Mekanism version.

### Steps to reproduce:
1. Well, ist randomly crashing, so just place a digitalminer and wait

### Version:
**Forge:** 13.20.1.2510 
**Minecraft:** 1.11.2
**Mekanism (-Tools/-Generators):** 9.3.3

### Crash log
[Pastebin](https://pastebin.com/3mh5hfen)

**Comment by thommy101** [comment]
The version you're using isn't receiving updates anymore. Main support is targeted on 1.12.

The issue you're describing is fixed for 1.12. Please consider updating to that version.
