### ISSUE TITLE
[1.12.2] Fluid voiding and items being lost

### ISSUE THREAD

**Issue by themechman** [aidancbrady/Mekanism#4912]
Good morning! Hope all are warm today. Just updated mekanism in my personal modpack (non-public) and running into a problem where cables, pipes, and transporters are visually connecting to places they're not supposed to.

#### Issue description:
![2018-01-17_12 08 55](https://user-images.githubusercontent.com/2990361/35056229-3ac963f2-fb7f-11e7-8f64-2e1ebee373f4.png)

This logistical transporter is set to PULL on those two faces, into the chest, but visually, it is not.

Next I have had several instances of fluids being "lost" when extracted from a tank or machine.

If i use the configurator on it, it will cycle through the settings. As soon as I turn around and come back (chunk unload?) it goes back to looking like a pipe hooked to everything.

#### Steps to reproduce:
1. It just happens
2. Look away and look back

#### Version (make sure you are on the latest version before reporting):
Forge 14.23.1.2555
Mekanism+Generators 9.4.3.330

**Comment by themechman** [comment]
Additional Note: This did not occur on build 9.4.1.325 of Mekanism.

**Comment by thiakil** [comment]
> It just happens
> Look away and look back

Sorry, but that's not enough to go on. It could be any of your mods or server software.

**Comment by themechman** [comment]
I'm aware of that. I will be rolling back version to see if it goes away again.

**Comment by themechman** [comment]
Okay, try this out for size:
![2018-01-17_20 59 17](https://user-images.githubusercontent.com/2990361/35077100-6c064ae4-fbc9-11e7-9b00-db5083db8a17.png)
![2018-01-17_20 55 02](https://user-images.githubusercontent.com/2990361/35077104-7035f038-fbc9-11e7-9940-e54734f91c39.png)

Unloading a bin into ME storage:
Using a basic bin preloaded with any material, place on logistical transporter.
Put an ME interface (Not storage bus!) next to logistical transporter.
Set configurator to Item/Gas/Fluid/Heat.
Hold shift and Right-click bin with configurator.
Watch as bin unloads, but nothing added to storage.

Scenario 2:
![2018-01-17_21 07 51](https://user-images.githubusercontent.com/2990361/35077304-85dfccaa-fbca-11e7-9a0e-396593ea52b2.png)
![2018-01-17_21 05 31](https://user-images.githubusercontent.com/2990361/35077263-48070dbc-fbca-11e7-843e-5aafe4edc4db.png)
![2018-01-17_21 05 33](https://user-images.githubusercontent.com/2990361/35077265-4a84ed02-fbca-11e7-931f-24b6c1251224.png)

Unloading to Vanilla Minecraft Chest:
Using a basic bin preloaded with any material, place on logistical transporter.
Put a chest next to logistical transporter.
Set configurator to Item/Gas/Fluid/Heat.
Hold shift and Right-click bin with configurator.
Watch as bin unloads, but nothing added to chest.

**Comment by themechman** [comment]
Continuing to have this problem with 9.4.3.330, however now I am loosing fluids between reactor and turbine. The more water I put in, the faster it disappears. A closed loop system is no longer possible.

It happens with all tiers of mechanical pipe.
