### ISSUE TITLE
Industrial Turbine Power Output Limit

### ISSUE THREAD

**Issue by webmilio** [aidancbrady/Mekanism#4914]
#### Issue description:
(I read https://github.com/aidancbrady/Mekanism/issues/4220 before posting)
My 17 x 17 x 18 Industrial Turbine has a set power output (which I believe is 128kRF/tick), and yet it was about to output 38MRF/tick just earlier. 

It has a production capacity of 224MRF/tick and has enough steam. Removing the steam pipe from the turbine and dumping the steam shows that the energy is not going down.

![image](https://user-images.githubusercontent.com/836345/35203325-a95855fc-fef5-11e7-88c6-41bb9e35c556.png)

#### Steps to reproduce:
1. Build the turbine
2. Let it build up power
3. Connect to tesseract in any way

#### Version:
**Forge:** 10.13.1614 (latest for 1.7.10)
**Mekanism:** 9.1.1.1031

**Comment by webmilio** [comment]
Which I could delete this issue, it was simply because it generated so much damn energy so fast it filled my storage practically instantly, I just didn't think it was possible.

**Comment by webmilio** [comment]
My bad, didn't see https://github.com/aidancbrady/Mekanism/issues/3301. I assume whatever fix comes up won't come out for 1.7.10 so I'll have to do without.

**Comment by thiakil** [comment]
Indeed, 1.7 is no longer supported

**Comment by thiago-solfo** [comment]
I don't believe I made a gigantic turbine for nothing 😭😭

**Comment by webmilio** [comment]
Over 5 year Necro 💀
