### ISSUE TITLE
Suggestion:  AE2 Integration - No Input+Output for connecting to ME Interface

### ISSUE THREAD

**Issue by pauljorr** [aidancbrady/Mekanism#4921]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

When connecting an AE2 ME Interface to any Mekanism machine you have to work around the system because Mekanism machines' side config can't be set to both input and output, it would make the whole process a lot easier if each side could be configured as either input/output or both. This would make connecting an ME interface and any Mekanism machine seamless and far less cluttered.

#### Steps to reproduce:
1. Connect ME Interface to Mekanism Machine
2. Side config can only be set to input or output
3. Items, therefore, cannot be placed into the machine and pulled out without a chest and cable system.

#### Version (make sure you are on the latest version before reporting):
**Forge:2587 (but is the same on any forge version)** 
**Mekanism:9.4.3.330** 
**Other relevant version: AE2: rv5- stable-5 ** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
That's just how Mekanism has always worked.
