### ISSUE TITLE
Mekanism pipes quit working.

### ISSUE THREAD

**Issue by ProsperCraft** [aidancbrady/Mekanism#4922]
#### Issue description:
Basic mechanical pipe stops working on server reboot.

#### Steps to reproduce:
1. Place and configure a mechanical pipe
2. chunkunload/reboot server
3. Pipe is visibly empty, but Oneprobe shows fluid in it, no transfer is happening.

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.12.2-14.23.1.2601-universal
**Mekanism:** Mekanism-1.12.2-9.4.3.330
**Other relevant version:** MekanismTools-1.12.2-9.4.3.330
No generators.
Modpack  - https://minecraft.curseforge.com/projects/towncraft

![2018-01-26_11 14 00](https://user-images.githubusercontent.com/4427684/35455017-a350cdd8-028d-11e8-8bd7-901e41616dc7.png)
![2018-01-26_11 33 51](https://user-images.githubusercontent.com/4427684/35455018-a37d7374-028d-11e8-9448-42f6723e797a.png)

**Comment by thiakil** [comment]
#4676
