### ISSUE TITLE
9.1.0.281 1.7.10 Universal cable crash.

### ISSUE THREAD

**Issue by KnightForEyes** [aidancbrady/Mekanism#4924]
Hello. Something wrong in mekanism. I will putted universal cable and 💥... Crashed.... I dont know why. I putted only Universal cable.
I need cables.
 I need powerful cables... Why to my game is crashed after putting universal cable? Help.

#### Version
**Forge: 1.7.10-Forge10.13.4.1481-1.7.10
**Mekanism:  9.1.0.281

[crash-2018-01-28_22.19.30-server.txt](https://github.com/aidancbrady/Mekanism/files/1671557/crash-2018-01-28_22.19.30-server.txt)

**Comment by KnightForEyes** [comment]
Sorry about my english. I will tryed to tell what happened.

**Comment by thiakil** [comment]
Something to do with `codechicken.multipart`, also 1.7.10 is no longer supported by us, sorry.
