### ISSUE TITLE
[crash] Already reported) IC2 and logistic sorter

### ISSUE THREAD

**Issue by victoroos** [aidancbrady/Mekanism#4926]
hi all
So, let's start with the error log, jic I forget:
https://pastebin.com/J705UtKC

I seem to have hit a bug or something, when combining the logistic sorter and with an IC2 machine (macerator )
It doesn't have to do anything, but as long as it is in the sorter system, it seems to have a problem, completely crashing the server.
Am I doing something wrong?

vkr
victor

**Comment by victoroos** [comment]
I see it already has been reported (people should give better titles..)

**Comment by thiakil** [comment]
you are able to close your own issues btw

**Comment by Aroma1997** [comment]
This is caused by Mekanism calling IInventory.isItemValid() with an empty ItemStack. I'll fix it on our side, but there's still most likely something wrong in Mekanism, when it tries to insert an empty stack into an inventory.

**Comment by thiakil** [comment]
yup was already noted in #4923

**Comment by victoroos** [comment]
Thanks! Also for the 1.10 IC2 version then I hope? ^^
Hmm, lets see what mechanism peeps think of it :).
