### ISSUE TITLE
Crash with solar evaporation tower blocks

### ISSUE THREAD

**Issue by teamMK** [aidancbrady/Mekanism#4930]
#### Issue description:
Everytime I place more then one block of the solar evaporation tower, the game crash without any crashlog.

#### Steps to reproduce:
1. get the blocks
2. place them in the world

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.1.2610**
**Mekanism: 9.4.3.330** 

Sry that I cant get a crashlog, it displays always accidentil error, when I use the blocks :-/

**Comment by thiakil** [comment]
The game always crashes with a crashlog.

**Comment by teamMK** [comment]
nope not this time

**Comment by teamMK** [comment]
OK, Problem found... Java Version was too old and crashed with mekanism :-P
