### ISSUE TITLE
Game crash on load.

### ISSUE THREAD

**Issue by bonnedav** [aidancbrady/Mekanism#4931]
Description:
`The game crashed whilst there was a severe problem during mod loading that has caused the game to fail.
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mekanism (Mekanism)`

Version:
MC:1.10.2
Forge:12.18.3.2511
Mekanism:9.2.4.103

[Crash Log](https://pastebin.com/scZNHBqz)

**Comment by bonnedav** [comment]
it's already the latest version(2.1.41).

**Comment by thiakil** [comment]
Not our issue. Please report to Extracells. (and update first if not already up to date)

**Comment by bonnedav** [comment]
Will do. Thank you.
