### ISSUE TITLE
CC incompatiblility

### ISSUE THREAD

**Issue by Gamer95875** [aidancbrady/Mekanism#4934]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. install cubic chunks (1.12) (http://forkie.me/job/Cubic%20Chunks%20Related%20Jobs/job/Cubic%20Chunks%201.12-1.12.2/)
2. Create a world
3. Set world type to Custom Cubic (or flat cubic)
5. Select create

#### Version (make sure you are on the latest version before reporting):
**Forge:** should work on all versions since it's a mekanism problem
**Mekanism:** i used the latest version, should happen on all 1.12 version
**Other relevant version:** probably happens on all cc versions

#### If a (crash)log is relevant for this issue, link it here: https://cdn.discordapp.com/attachments/322363883698520065/405271648040779776/crash-2018-01-19_18.55.45-server.txt

[gist/pastebin/etc link here]

**Comment by Gamer95875** [comment]
Its 20 days, nobody has noticed?

**Comment by thommy101** [comment]
Hi @Gamer95875 ,

This has certainly been noticed, @thiakil added a label 19 days ago. We (the devs) all are currently quite busy with our real lives.

**Comment by Gamer95875** [comment]
Ok then, just be sure to prioritise irl things and give me an eta (if you can), this mod is definently one of my favourites.
