### ISSUE TITLE
Destabilized Redstone digital miner filter

### ISSUE THREAD

**Issue by TheHuntrod** [aidancbrady/Mekanism#4940]
#### Issue description:
I am trying to use the digital miner to silk touch blocks of Destabilized Redstone. I tried with the oreDict filter and the block picture shows in the filter however it does not seem to mine the blocks. I had also tried with the actual material in the filter and it just mines every block, I started getting a ton of stone.
Is this intended?

#### Steps to reproduce:
1. Digital miner
2. oreDict with the filter *Redstone*
3. material filter with Destabilized Redstone

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.1.2587
**Mekanism:** 1.12.2-9.4.3.330
**Other relevant version:** All the mods 3

**Comment by thiakil** [comment]
The material filter is not designed to get the specific block, getting everything stoney is correct.

As for the oredict one, does it show a count of the blocks when you click start? If it does, but does not mine anything there is some kind of chunk protection preventing it.

**Comment by thiakil** [comment]
no?

**Comment by Too-DAMN-Much** [comment]
well what you typed indicated that you either failed to read or understand it is all, if silk touch is enabled the ore block itself should always be the result.

**Comment by thiakil** [comment]
You have misunderstood my reply.

Material filter does not mine specific blocks. Silk touch or no.

The 2nd part of my reply is asking them if the filter actually matched something or not.

**Comment by Too-DAMN-Much** [comment]
ah, i see what you mean in that case.

at any rate is the proper way to enter these into the digital miner to cheat one and then use itemstack? or which?
i'm really being annoyed by our digital miners missing them because i don't want the destabilized redstone to just spill all over the ground at random as no one will bother to go and find or collect it.

**Comment by thiakil** [comment]
If they have an oredict entry you can use that, or yes the ItemStack filter *should* do the trick.

How you get that item to put into the itemstack filter is up to you, a silk touch pickaxe is another option.
