### ISSUE TITLE
Digital Miner won't mine!

### ISSUE THREAD

**Issue by KnottyCord** [aidancbrady/Mekanism#4941]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Simple the Digital Miner does not mine what so ever in Solo or Multiplier. Everything is setup properly. Filters, power, replacement block etc .... I thought it was because of the Fake player thing. So I did /mk op and nothing help. Then I though it migh be the claimed chunk so I tried in solo, same thing, then I tried removing the FTBUtils mod. Same thing the Digita Miner is stuck at Mining 0.

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-10.13.4.1614
**Mekanism:** Mekanism-1.7.10-9.1.0.281
**Other relevant version:** MekanismGenerators-1.7.10-9.1.0.281, MekanismTools-1.7.10-9.1.0.281, MDK-1.7.10-9.1.0.281

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
1.7.10 is no longer supported. Though it is likely some kind of chunk protection that doesnt like fake players at all. Make sure if FTBU has the option to allow fake players that you enable it.
