### ISSUE TITLE
Lasers do not turn on consistently.

### ISSUE THREAD

**Issue by MalcolmAnderson** [aidancbrady/Mekanism#4943]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Lasers, after being set up, do not appear to fire when power is applied.

I'm setting up a reactor, and depending on the day, my lasers do not fire.  
If I give them power, I can hear them spin up, but the Laser Amplifier show no sign that they are getting power.

Here's the thing, I don't really know what power levels the lasers are at.
If I click on a laser, there is no interface, so maybe I don't have enough power running through my system to fire them.
The thing is that I'm using an ultimate energy cell, and it seems to be draining fast, so it seems like this is a bug.

#### Steps to reproduce: (warning - not consistent)
1.  Put up lasers pointed at a laser amplifier
2. wire in power to the back of the lasers
3. apply power to the wire
4. see no beams of light.

#### Version (make sure you are on the latest version before reporting):
**Forge: 
**Mekanism: 1.12.2-9.4.3.homebaked
**Other relevant version:** If it matters, I'm in Survival - Hard

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
> homebaked

please use a released version to report bugs

**Comment by MalcolmAnderson** [comment]
Looks like I did not have enough power in my network.
The network reader allowed me to troubleshoot it.
(and I will use a released version in the future)
