### ISSUE TITLE
[Suggestion/Question] Mekanism Crafttweaker machine recipe output

### ISSUE THREAD

**Issue by Entayan** [aidancbrady/Mekanism#4944]
I don't know if this is already a feature but I can't seem to find hide nor tail of it. Does integration exist to allow a Crafttweaker command to dump Mekanism machine recipes as zenscript? I've already asked the Crafttweaker devs about this and they told me that this was a question for Mekanism developers.

I've been trying to add recipes to various machines but always seem to run into issues because I don't know what the recipes require as input (and I'm not familiar with how to deal with mekanism gas in crafttweaker) so I thought that looking at zenscript versions of the recipes would help me to figure out what's going on.

What I've been trying to do is add compatibility for certain ores but I can't seem to specify the amount of gas produced for my dissolution chamber recipe. I've tried both multiplying the gas directly  as in "gas * 1000" or using "gas.withAmount(1000)" and neither seem to work. It works fine when I don't specify the amount but then I only get 1mb from an ore.

Any information or help would be greatly appreciated!

**Comment by thommy101** [comment]
I've written some stuff about our crafttweaker integration over at http://wiki.aidancbrady.com/wiki/Tutorials/CraftTweaker

**Comment by ElvenChaos** [comment]
@thommy101 The dissolution chamber _add recipe_ zen method is actually bugged, though.

1. `mods.mekanism.chemical.dissolution.addRecipe(denseGold, gasGold);` Functions, but only creates an output of 1mb of Gold Slurry. The output should be size configurable anyways.

2. `mods.mekanism.chemical.dissolution.addRecipe(denseGold, gasGold * 3000);` Produces [this](https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/integration/crafttweaker/handlers/ChemicalDissolution.java#L41) error, so the output is not properly configurable.

**Comment by thiakil** [comment]
`<gasstack>.withAmount(int amount)` should do it

**Comment by ElvenChaos** [comment]
`mods.mekanism.chemical.dissolution.addRecipe(denseGold, gasGold.withAmount(3000));` gives the same error.

[CraftTweaker Log](https://gist.github.com/ElvenChaos/f998286e2ce7b51e217b94ad0fd8a3b2)
[Main Script in Question](https://gist.github.com/ElvenChaos/4365b78e427d1ae56b83452e8d825c92) _(You will need to remove the rest of the script if you try to directly run it -- it has global variables from many other files.)_
[Mek Globals for Script in Question](https://gist.github.com/ElvenChaos/a57517d8028c7553a3ca2d0984d371d4)
[Dense Ores Globals for Script in Question](https://gist.github.com/ElvenChaos/79367a619486f15d862173d75bfde6bc)
_Sorry for all the script files, this is how I've been organizing my work._

**Comment by StarkRG** [comment]
I don't know how to do a pull request, but I think I've fixed it with this:

`    public IGasStack withAmount(int amount)
    {
        return new CraftTweakerGasStack(stack.withAmount(amount));
    }`

This code definitely does work, whether it causes other problems, though, I can't say for sure.
