### ISSUE TITLE
[Request] Something like that from Immersive E. (Preferred Ores)

### ISSUE THREAD

**Issue by TheSnowyChickens** [aidancbrady/Mekanism#4945]
I searched in open issues and in closed issues already.

#### Question description:
I looked in the configs for a "preferredOre" option (Like from Immersive Engineering, cutout below the "version" section), because I want all materials in my modpack from a single mod. (I know that the "Oredictionificator" is in your Mod)
It would be the fastest and easiest way, without convertion.

#### Version:
**Minecraft: 1.12.2**
**Forge: 14.23.2.2617** 
**Mekanism-1.12.2-9.4.3.330** 
**Immersive Engineering, Thermal Expansion** 

**Immersive Config**
# A list of preferred Mod IDs that results of IE processes should stem from, aka which mod you want the copper to come from.
    # This affects the ores dug by the excavator, as well as those crushing recipes that don't have associated IE items. This list is in oreder of priority.
    S:preferredOres <
        minecraft
        thermalfoundation
        immersiveengineering
     >

**Comment by thiakil** [comment]
preferred ores for what? the Oredictionificator? It's setup in the GUI.
