### ISSUE TITLE
CraftTweaker can't remove Mekanism Ore Dictionary entries

### ISSUE THREAD

**Issue by Ithronyar** [aidancbrady/Mekanism#4946]
#### Issue description:
Using CraftTweaker's Ore Dictionary removal doesn't work on Mekanism blocks/items. I can't find any info on how to use Mekanism's CraftTweaker support to do the same thing, I'm going to assume it isn't implemented.

Removing Ore Dictionary entries from other mods in the same installation works fine, so I'm guessing Mekanism does something unusual with its Ore Dictionary entries that prevents disabling them.

#### Version:
**Forge:** 1.12.2-14.23.2.2611
**Mekanism:** 9.4.3.330
**Other relevant version:** CraftTweaker2-1.12-4.1.0

**Comment by IcedReaper** [comment]
I've the same issue. I would guess that mekanism set's their ore dict entries after crafttweaker modifies them.

Removing an ore dict entry for all other (tested) mods works, but sadly not for mekanism.

**Comment by thommy101** [comment]
Released in in version 9.4.4 
fca84074893f291736e3fc2de787c4f934674192
