### ISSUE TITLE
Mekanism Crash Issue

### ISSUE THREAD

**Issue by RoboJackPlays** [aidancbrady/Mekanism#4947]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Game is crashing on load up

#### Steps to reproduce:
1. Running in a modpack

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.10.2 - 12.18.3.2185
**Mekanism:** 9.2.3.97 for 1.10.2
**Other relevant version:** Minecraft 1.10.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mekanism (Mekanism)

https://pastebin.com/Yu0TMmrk
[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
`Caused by: java.lang.NoSuchMethodError: p455w0rd.wct.api.IWCTItems.wirelessCraftingTerminal()Lp455w0rd/wct/api/IWCTItem;`

Need to search harder, this has been reported multiple times.
