### ISSUE TITLE
Routing a mechanical pipe next to a shield block results in a crash.

### ISSUE THREAD

**Issue by itstwoam** [aidancbrady/Mekanism#4951]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
As stated in the title it's pretty straight forward.  Shield blocks and at the least mechanical pipes cannot touch each other.

#### Steps to reproduce:
1.  Place shield block.
2.  Place pipe down next to shield block.
3.  Server crashes.

#### Version (make sure you are on the latest version before reporting):
Forge: 14.23.2.2611
Mekanism: 9.4.3.330
Other relevant version:
Mekanism tools version is the same version.

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

I can get the crash log from the admin if needed.

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
> I can get the crash log from the admin if needed.

You shouldn't have even reported it without it.
