### ISSUE TITLE
Crafttweaker additions don't seem to function for some machines

### ISSUE THREAD

**Issue by superfluke** [aidancbrady/Mekanism#4953]
#### Issue description:
The craft tweaker add recipes for some machines show in JEI but don't actually function when the ingredients are placed in the machine. 

#### Steps to reproduce:
Some of the additions that do not work (examples taken from the mek craft tweaker wiki page)
mods.mekanism.purification.addRecipe(<minecraft:wool:1>, <gas:hydrogenchloride>, <minecraft:wool>);
Can't seem to insert hydrogen chloride into the purification chamber

mods.mekanism.reaction.addRecipe(<mekanism:polyethene>, <liquid:liquidethene>, <gas:oxygen>, <mekanism:polyethene> * 8, <gas:oxygen>, 50000, 2000);
Everything seems to input, but does not actually process

mods.mekanism.separator.addRecipe(<liquid:liquidfusionfuel>, 5000, <gas:deuterium>, <gas:tritium>);
Liquid D-T fuel does not seem to input into the separator

#### Version (make sure you are on the latest version before reporting):
Forge 14.23.1.2604
Mekanism-1.12.2-9.4.3.330
CraftTweaker2-1.12-4.1.2

**Comment by thiakil** [comment]
logs please

**Comment by superfluke** [comment]
Sure, there's no crash or anything, but here's the normal log from when I was testing the example mek scripts. 
https://paste.ubuntu.com/p/KCQvmVJgSy/

**Comment by dshadowwolf** [comment]
With:
```
mods.mekanism.reaction.addRecipe(<minecraft:iron_ingot>, <liquid:coal> *250, <gas:water> * 250, <pneumaticcraft:ingot_iron_compressed> * 3, <gas:ethene> * 125, 50000, 4000 );
```
I get an error about wrong types. Removing the quantity specifier from the gas removes the error and the recipe shows up, but the machine does not work.

**Comment by thiakil** [comment]
should be covered by #4944
