### ISSUE TITLE
Mek And Ic2 removal without registration?

### ISSUE THREAD

**Issue by XnF0** [aidancbrady/Mekanism#4955]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
The problems of Mek and IC2
like: [21:16:25] [ic2-poolthread-1/WARN] [IC2.EnergyNet]: Tile mekanism.common.tile.TileEntityLaser@47c6c89f (dim 4: 13119/74/-20619) removal without registration

#### Steps to reproduce:
1.Sponge with Mek and IC2
2.When the block is unloaded, the error will be reported
3.If a block loading machine is used, this will not be the case

#### Version (make sure you are on the latest version before reporting):
**Forge:12.18.3.2511
**Mekanism:9.2.4.103
**Other relevant version: IC2: 2-2.6.254-ex110

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
merge with #4974
