### ISSUE TITLE
[1.12.2] Fluid tank doesn't render texture for Creosote Oil from Immersive Engineering

### ISSUE THREAD

**Issue by ixanza** [aidancbrady/Mekanism#4956]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

The Fluid tank from Mekanism doesn't render the texture of Creosote Oil from Immersive Engineering.
![image](https://user-images.githubusercontent.com/5535758/36540207-751b29c6-1814-11e8-93a9-0004629b5b22.png)
On the left shows the Creosote Oil without textures in the Mekanism Fluid Tank. Middle shows Resonant Ender Rendering Fine. Right shows Creosote Oil rendering fine in an OpenBlocks Tank

#### Steps to reproduce:
1. Make Fluid Tank
2. Put a bucket of Creosote Oil in
3. See Purple and Black Fluid

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.2.2619
**Mekanism:**  1.12.2-9.4.3.330
**Other relevant version:** Immersive Engineering 0-12-77

**Comment by Tahakk** [comment]
If I remember correctly, this was issue in 1.10.2 too. In fact it was problem wit fluid and not the tank, as it was registering fluid from wrong mod. Read this, try to apply this fix and then let us know. 

[IE#1969](https://github.com/BluSunrize/ImmersiveEngineering/issues/1969)

**Comment by thiakil** [comment]
Can't reproduce with either Immersive Engineering or Thermal Expansion. Please ensure the mods are updated or otherwise figure out what mod's creosote it is.

**Comment by thiakil** [comment]
I stand corrected, it happens when both are installed and TE was installed alone previously.

**Comment by ixanza** [comment]
My bad I'm still at work so I couldn't replicate it in time to respond to your initial query.

**Comment by thiakil** [comment]
It's all good, I had time to look at it, couldnt find it, but then loaded back up my usual world with both installed and found it haha
