### ISSUE TITLE
[1.10.2] Caused by: java.lang.IllegalArgumentException: Block: class mekanism.common.block.BlockBasic$1 has property: type with invalidly named value: osmıum_block

### ISSUE THREAD

**Issue by asederf** [aidancbrady/Mekanism#4957]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When I try to launch game, I get this crash. 

#### Steps to reproduce:
1.Launch game
2.Creates a crash report.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.10.2-12.18.3.2185
**Mekanism:** 1.10.2-9.2.4.103
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[https://pastebin.com/SNqZuzZH]

**Comment by asederf** [comment]
yes

**Comment by asederf** [comment]
I know that problem is connected with my computer's language (Turkish) because I had same issue with textures in mekanism 1.7.10. Game could not find textures because they have written with "ı" instead of "i" and I have changed them to "i" myself and it worked but with this issue I dont know how to fix it myself.

**Comment by thiakil** [comment]
Will have to do some digging to find where it's happening, but somewhere there's a toLowerCase() which uses the system default locale, it should be giving locale.root as a parameter

**Comment by asederf** [comment]
Is there a way to fix this without editing mods ? Because im having same issue with some other mods too

**Comment by thiakil** [comment]
You'd need to override the java locale.

Google leads to these JVM options (set in your launcher) might do the trick `-Duser.country=US -Duser.language=en`

With that set you can change the language in Minecraft back to Turkish if that's what you use (if it should decide to change itself)

**Comment by asederf** [comment]
These JVM options have worked. I have been looking for this for 2 years. Thank you very much

**Comment by thehaplo** [comment]
> These JVM options have worked. I have been looking for this for 2 years. Thank you very much

Hi. I have the same problem and can't open a server. Can you explain how and where we use `-Duser.country=US -Duser.language=en` settings?

Thank you.
