### ISSUE TITLE
Things missing from latest 1.7.10 "release"

### ISSUE THREAD

**Issue by Anyone700** [aidancbrady/Mekanism#4959]
No fusion reactor or solar panels of any kind

I would understand this from an alpha or beta release but this was listed as an offical release. I was able to follow the fusion tech tree all the way up to D-T fuel but was puzzled when I could not craft a Hohraum. Not being able to craft panels for the e-vaps was also puzzling, however I paid it no mind.

Forge: 10.13.4.1614
Mekanism-1.7.10-9.1.1.1031
Minecraft 1.7.10

**Comment by thiakil** [comment]
Make sure they're not disabled in config and that you have all the modules at the same version.

Other than that 1.7 is no longer supported and I highly doubt there was an error in the build with what little changed..

**Comment by Anyone700** [comment]
Nope, I downloaded from curseforge. The problem was that the other components of Mekanism weren't listed on the page.
