### ISSUE TITLE
ITEms and ENergy

### ISSUE THREAD

**Issue by RazeSoldier12** [aidancbrady/Mekanism#4960]
Mods in bug: 
Mekanism(Full pack) latest 1.11.2 versions
Refind Storage (with core/s) latest 1.11.2 versions (olso refereed as RS)

1st bug) mekanism energy cables are bugging out and are not sending energy through. How does it happens I have no idea. To fix it usually you need to break the  last cable that are connected to powergen. If that doesn't left you either have to log off log in into your world or break and replace all cabling

2 bug) RS+Mekanism. Mekanism gas and fluid tanks are "unavailable", if gas/fluid( often happens to Ultimate tanks) tank are in the RS network you can click it but you actually can't get it out. To fix it you need to empty the whole RS storage disk. And even then the tank are still "unavailable", you can't get it out.

**Comment by RazeSoldier12** [comment]
Oh olso third bug. I red morning stared (Project E) a farm (aka broke a good chunk of it) with a logistics sorter and I didn't get it back

**Comment by thiakil** [comment]
First of all, **don't write latest, you are being lazy**

1) #4676, did you even search?

2) that sounds like an RS issue

3) I have no idea what you are saying there

**Comment by thiakil** [comment]
Closing due to no response
