### ISSUE TITLE
[1.12.2] Digital Miner Sort Hierarchy broken

### ISSUE THREAD

**Issue by Xopharios** [aidancbrady/Mekanism#4961]
#### Issue description:
Digital Miner sorting config seems to have no affect on what gets mined first anymore. With ore dictionary ore* BELOW ore diction oreDiamond, it still randomly mines any ore

#### Steps to reproduce:
1. Go into digital miner and open config
2. Add any ore into hiearchy
3. Failure, ores added to the list are mined, but not in the specifically specified order

#### Version:
**Forge:** 1.12.2-forge1.12.2-14.23.2.2613
**Mekanism:** Mekanism-1.12.2-9.4.3.330.jar

P.S. This is likely already known but, "Are you sure you want to delete this?" also overlaps any of the delete buttons

**Comment by thiakil** [comment]
> anymore

In what version did it?

**Comment by Xopharios** [comment]
Version 9.4.3.330

**Comment by thiakil** [comment]
no, what version did the sorting function how you describe?

**Comment by thiakil** [comment]
Closing due to no response.
