### ISSUE TITLE
[1.12.2] Tanks won't fill past 14000mb

### ISSUE THREAD

**Issue by Xopharios** [aidancbrady/Mekanism#4962]
#### Issue description:
Whenever server restarts, the tanks will not fill past 14000mb, even stacked on top of each other. When the tank below fills to 14000, the tank above starts filling to 14000. This can be temporarily fixed by replacing the tanks, but once the server restarts, they are stuck again and need to be broken and replaced once more

#### Steps to reproduce:
1. Place Tanks
2. Restart Server
3. Failure

#### Version:
Forge: 1.12.2-forge1.12.2-14.23.2.2613
Mekanism: Mekanism-1.12.2-9.4.3.330.jar

**Comment by thiakil** [comment]
Which tanks?

**Comment by Xopharios** [comment]
Every tanks has this issue

**Comment by Xopharios** [comment]
If you cannot reproduce it could be a mod conflict, if that's the case I'll fetch you a mod list

**Comment by thiakil** [comment]
![2018-03-24_16 58 00](https://user-images.githubusercontent.com/1788847/37862251-d0abf3a6-2f84-11e8-96e2-60ab81e27eff.png)
Cannot reproduce

**Comment by aidancbrady** [comment]
@thiakil for the future, feel free to close issues without responses for over (or close to) a month
