### ISSUE TITLE
Option to write warnings to Crafttweaker log only

### ISSUE THREAD

**Issue by justinrusso** [aidancbrady/Mekanism#4964]
Hello,

Would it be possible to add a way to not output warnings for Crafttweaker to the chat? I'd assume you'd have to change from logging as a warning to logging as info for the Crafttweaker integration.

![image](https://user-images.githubusercontent.com/25138621/36936958-1946dab0-1eda-11e8-8123-00445b806111.png)

#### Version:
**Forge:** 14.23.2.2623
**Mekanism:** 1.12.2-9.4.3.330

**Comment by thiakil** [comment]
pretty sure that's CT, not us

**Comment by justinrusso** [comment]
Crafttweaker outputs to player when a warning is logged. An info is only logged to the log. The request was to log as `info` instead of `warn` which would prevent this. Could be on toggle or not. But since, Crafttweaker added a global toggle to just stop all player output. Not perfect but its fine.
