### ISSUE TITLE
[1.12.2] Broken EU (IC2) compatability

### ISSUE THREAD

**Issue by MasterEnderman** [aidancbrady/Mekanism#4965]
#### Issue description:

As stated in this issue (https://github.com/aidancbrady/Mekanism/issues/4370) before. Mekanism Cables won't work well together with IC2. Mekanism Machines can't be powered by EU neither they are able to power IC2 Machines with the Universal Cable.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.2.2623
**Mekanism:** 9.4.3.330
**IndustrialCraft2:** 2.8.61

**Comment by thiakil** [comment]
Mek cables drawing from IC2 energy storage need to be set to pull mode.
