### ISSUE TITLE
Digital Miner mines NuclearCraft byproducts in Silk Touch mode.

### ISSUE THREAD

**Issue by ftog-thorgal** [aidancbrady/Mekanism#4967]
The Digital Miner mines NuclearCraft byproducts in Silk Touch mode.
So when it mines Coal Ore it can also "mine" Beryllium Dust and Sulfur. Lapis Ore it also gets Fluorite, and with Redstone Ore it mines Rhodochrosite.

When mining with any tool (not Silk touched) you are supposed to have a chance to get these byproducts, but not with Silk Touch.

#### Steps to reproduce:
1. Place Digital Miner, set to Ore Dictinary *ore*, set Silk Touch mode
2.
3.

#### Version (make sure you are on the latest version before reporting):
Forge: 14.23.2.2611
Mekanism: 1.12.2-9.4.3.330
NuclearCraft: 2.9d--1.12.2

**Comment by thiakil** [comment]
They're not checking silk touch correctly in their event handler.
