### ISSUE TITLE
[1.12.2] No dust processing for AE2

### ISSUE THREAD

**Issue by mrAndersen** [aidancbrady/Mekanism#4968]
Hi, i have mekanism 9.4.3 on minecraft 1.12.2 and along with this AE2, and i can't see any recipes to crush quartz crystals using mekanism factory infuser oк crusher, is this all right ?

I guess at least crusher can and should be compatible with AE2

**Comment by thiakil** [comment]
did you even *read* the other issue?

***Don't create a new issue when one exists and especially not when you've already commented on it***
