### ISSUE TITLE
[1.12.2] **Induction Casing Causes Fatal Server Crash**

### ISSUE THREAD

**Issue by hazzar21** [aidancbrady/Mekanism#4972]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Mekanism induction matrix storage multi-block doesn't like enderio conduit. Test can be replicated and and energy conduit connected to the induction matrix will crash a server.

#### Steps to reproduce:
1. Built the smallest induction matrix
2. Connected enderio conduit to input and output sides with a input and output of power
3. Close the server, when the server is started it will crash the log will show a tile entity issue

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.2.2624
**Mekanism:** 330
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

https://hastebin.com/zabojegujo.pl

**Comment by thiakil** [comment]
you need to link the hastebin of your crash, not the homepage

**Comment by hazzar21** [comment]
haha my bad it was late. i have provided the full url.
