### ISSUE TITLE
Dupe with GUI's not closing when player leaves area.

### ISSUE THREAD

**Issue by Kevin67632342** [aidancbrady/Mekanism#4976]
#### Issue description:
When players open a GUI for any Mekanism machine and then leave sthe area so that the chunk the machine unloads, they can remove the items and the machine will still have the item when reloaded.

#### Steps to reproduce:
1. Open any Mekanism machine GUI and put in any item.
2. Leave area either with Minecart or something else.
3. Remove item, and reload the machines.

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.2.2627**
**Mekanism: 1.12.2-9.4.3.330** (Also tested on 1.7.10)
**Other relevant version:** 

Video demonstration: https://youtu.be/WuYvBchsImk

**Comment by thiakil** [comment]
That's some stupid editing.
