### ISSUE TITLE
Performance of factories/logistic transporters when idling

### ISSUE THREAD

**Issue by roboderpy** [aidancbrady/Mekanism#4978]
#### Issue description:
Mekanism create significant TPS lags on server even when machines are idling.

Under *idling* i mean:
* Have items in slots, but have no energy
* Input slots are full but output are also full
* Input slots are (semi)full -> any interaction from other mods which attempt to insert big amount of items at once create lag because of mekanism's check for recipes, even if factory already contains that item in it's processing slots
* Logistical transporters/pipes are creating lags because of constant attempts to extract/insert items even if on previous tick all machines connected weren't accepting all type of items or were full, or connected extract inventory is empty
* Mekanism **do** checks for recipe for items in already full slots even if machine is disabled by redstone signal and therefore it forces itself to be disassembled to reduce lag

**Forge:** 2617 build
**Mekanism:** 9.4.4 (git, you all really should push an update to curse)

![javaw_2018-03-16_19-13-17](https://user-images.githubusercontent.com/6339511/37520287-01c2d9fa-294f-11e8-813a-1f1fade1f0c9.png)
![javaw_2018-03-14_17-14-00](https://user-images.githubusercontent.com/6339511/37520330-2538e6ea-294f-11e8-9463-1139db2f2d1b.png)
This is when factories were idling, but had loot in them. Output slots were full too.
![lags](https://feen.us/04h3kxcg.png)

this create more lags in idle
![javaw_2018-03-16_19-28-45](https://user-images.githubusercontent.com/6339511/37520598-45d623f8-2950-11e8-92f3-62aa62372271.png)
than this in full-work (wall of pulverizers)
![javaw_2018-03-03_18-57-07](https://user-images.githubusercontent.com/6339511/37520638-6920de34-2950-11e8-9c0d-b15db4c2cac8.png)

**Comment by thiakil** [comment]
4ms is hardly significant.

But also, did you bother searching? #4899

**Comment by roboderpy** [comment]
4ms for 6 factories? This is basically what make server owners refuse from using mekanism on servers. And on "lags" github didn't gave me anything related
