### ISSUE TITLE
Mekanism + opencomputers, energy cables stop transferring energy after reboot

### ISSUE THREAD

**Issue by pdglobal** [aidancbrady/Mekanism#4980]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
mekanism universal energy cables stop transferring power to opencomputers energy converter after reboot.

#### Steps to reproduce:
1. Install opencomputers 1.7.2.67 & mekanism 9.4.3.330
2. Set up any type computer with open computers
3. power opencomputer power converter with universal cable
4.reboot
(cable will not transmit power until the cable touching the energy converter is broken then re-created)

#### Version (make sure you are on the latest version before reporting):
**Forge:14.23.2.2625** 
**Mekanism: 9.4.3.330** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
#4676
