### ISSUE TITLE
[Suggestion] Remove the Boiler, or make it by default slightly better.

### ISSUE THREAD

**Issue by JonoColwell** [aidancbrady/Mekanism#4983]
At the moment the thermoelectric boiler doesn't really have a purpose, it's just kind of a waste of resources at this point, you could basically replace it wholesale by adding an additional crafting step on top of a fuelwood heater to make it a boiler.

The 40mb/t default rate is kind of useless for anything, it's much, MUCH cheaper to build solar or wind farms even with the wind nerf.

Especially considering the amount of infrastructure that goes into producing a boiler at all and the turbine to power it.

I'd say at this point either the Steam/Heat Unit default value should be raised or the boiler removed, as it stands it's basically a really cool multiblock that would be wonderful to use but has no use case.

**Comment by thiakil** [comment]
I managed to make a 3x3x4 (minimum size) thermoelectric boiler produce 274mb/t of steam, so not sure where you're getting 40 from, perhaps not heating it to full capacity.

In the Turbine i have setup in my test environment that generates 1.5kRF/t.
