### ISSUE TITLE
Taking off Free Runners sets player.stepHeight to wrong value

### ISSUE THREAD

**Issue by winauer** [aidancbrady/Mekanism#4985]
Issue description:

Taking off Free Runners sets player.stepHeight to 0.5 but it should be 0.6. This creates issues with chisel&bits stairs.
See  AlgorithmX2/Chisels-and-Bits#85

Steps to reproduce:

1. Create stairs with chisels & bits. You can walk up those stairs normally.
2. Equip Free Runners and unequip them again
3. You now can't walk up stairs and slabs made with chisels & bits

Version:

Minecraft: 1.12.2
Forge: 14.23.2.2611
Mekanism: 1.12.2-9.4.3.330
Chisels & Bits: 14.16

**Comment by thommy101** [comment]
Fixed in version 9.4.4
1197dc3c3951e95942bc0a1a26b3b509bd74ad20
