### ISSUE TITLE
Mekanism hide recipe IC2 in JEI

### ISSUE THREAD

**Issue by DarkEvangels** [aidancbrady/Mekanism#4989]
#### Issue description:
I play FTB Revelation modpack 1.12.2, and i add mekanism mod for more machine and better energy production and after the installation i see in JEI most recipe from IC2 just disappear ( every fluid cell, steel ingot from other mod and other recipe). And the recipe come back if I uninstall mekanism from the modpack.

![2018-03-27_21 22 44](https://user-images.githubusercontent.com/37847785/37990487-bd406d18-3206-11e8-817c-2f8821f13f18.png)

#### Steps to reproduce:
1. Play FTB Revelation
2. Add mekanism mod
3. See recipe disappear

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.2 - _14.23.2.2638_
**Mekanism:** 1.12.2 - _9.4.3.330_
**IC2:** 1.12.2 - _2.8.16-ex112_

**Comment by thiakil** [comment]
That's a JEI thing that happens when an item has too many subtypes. Nothing directly to do with us.
