### ISSUE TITLE
My N00B problems (No such member: mekanism) (Truncated class file)

### ISSUE THREAD

**Issue by Sibith** [aidancbrady/Mekanism#4990]
Intro:

I'm gonna be honest: I'm a complete n00b to crafttweaker and have no freaking idea what i'm doing. I tried to follow the tutorial on the wiki because i wanted to change a couple crafting recipes in my mod pack, but the tutorial on the wiki isn't all that straight forward :/ So I'm using the portal gun mod, the mekanism mod, and the techgun mod. I wanted to make it so ender pearl dust for the portalguns could be made in the crusher from the mekanism mod instead of the furnace. I successfully got rid of the original furnace recipe. (I was pumped to see I got a script to work). The problem came when I attempted to make a script that would let me make ender pearl dust from ender pearls in the crusher. I tried to add a crusher recipe script but ended up with some weird errors that probably make me look like a n00b.

Issue Description:

I get the "No such member: mekanism" ERROR
and the "Truncated class file" ERROR

What happens: I run my world and get the aforementioned errors.

What you expected to happen: I can put enderpearls in a crusher and get enderpearl dust

The script giving me issues:

https://pastebin.com/MWRzmP38

The other script I'm using in case it's causing problems(Don't think it is, just thought I'd include it):
https://pastebin.com/5qFD1PUd

Minetweaker.log file: https://pastebin.com/uTAJkAkB

Affected Versions:

Minecraft:1.12.2
Forge:14.23.2.2611
Crafttweaker: 1.12-4.1.6
Your most recent log file where the issue was present:

https://pastebin.com/eeWyHrng

**Comment by thommy101** [comment]
Hi,
It looks like you don't have MTLib installed, it's a helper thingy for crafttweaker which we use to make it ourself a bit easier.
Could you try with MTLib installed?

**Comment by Sibith** [comment]
Thought I had tried that but apparently not! It worked perfectly! Thank u so much!

**Comment by Sibith** [comment]
I thought it worked prefect but when I checked the recipe on jei it showed the recipe but with missing textures and when I place the Ender pearls in the crusher it doesn't work

**Comment by thiakil** [comment]
I don't think the ender pearl has meta, and it would seem the dust does not either, so you dont need the `:1` in your script

**Comment by Sibith** [comment]
I didn't really know what the :1 did, I was just copying the tutorial script. Thank you soooo much that fixed it!
