### ISSUE TITLE
Mekanism API Crashes Server

### ISSUE THREAD

**Issue by AMinecraftLover** [aidancbrady/Mekanism#4991]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1.install all mods in crash log
2.run server
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.12.2-14.23.2.2611
**Mekanism:** 1.12.2-9.4.3.330
**SpongeForge**1.12.2-2611-7.1.0-BETA-2990

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

crash log
https://pastebin.com/raw/shBSwwxG

**Comment by thiakil** [comment]
Either someone is packaging an un-reobfed api (which they shouldn't be packaging in any form), or Sponge is doing some stupid things...

Please try removing mods (including Sponge) until the error stops.

**Comment by AMinecraftLover** [comment]
Everything worked when I removed Mekanism API, so maybe Sponge doesn’t like Mek API
Haven’t  tried on a plain forge server yet.
As far as I know, this causes a crash on client as well.
