### ISSUE TITLE
Ticking Crash

### ISSUE THREAD

**Issue by D3nnis3n** [aidancbrady/Mekanism#4994]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Get the following crash after a server restart.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2654
**Mekanism:**  330
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://gist.github.com/D3nnis3n/7b16c986fa597f5f06fc66d611c5748d

**Comment by thiakil** [comment]
#4972
