### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Chasejr1** [aidancbrady/Mekanism#4995]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:14.23.2.2627** 
**Mekanism:9.4.3.330** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
[crash-2018-04-11_17.24.02-client.txt](https://github.com/aidancbrady/Mekanism/files/1900718/crash-2018-04-11_17.24.02-client.txt)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
#4991
