### ISSUE TITLE
Mekanisms crashes after adding redstone flux from cofh core

### ISSUE THREAD

**Issue by Dashna99** [aidancbrady/Mekanism#4996]
forge 14.23.2.2627
have already tried mekanisms .30, .28, and .27 no change same issue occurs after adding redstone flux
..................................................................................................................................................................................................................

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  llibrary (llibrary-1.7.9-1.12.2.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.169.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.18.jar)
  BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 4/13/18 4:18 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mekanism (mekanism)
Caused by: java.lang.NoSuchMethodError: net.minecraft.block.Block.getUnlocalizedName()Ljava/lang/String;
	at mekanism.api.util.BlockInfo.hashCode(BlockInfo.java:35)
	at java.util.HashMap.hash(Unknown Source)
	at java.util.HashMap.remove(Unknown Source)
	at java.util.HashSet.remove(Unknown Source)
	at mekanism.api.MekanismAPI.removeBoxBlacklist(MekanismAPI.java:42)
	at mekanism.common.CommonProxy.onConfigSync(CommonProxy.java:610)
	at mekanism.client.ClientProxy.onConfigSync(ClientProxy.java:1109)
	at mekanism.common.Mekanism.preInit(Mekanism.java:706)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at info.mineshafter.GameStarter.main(GameStarter.java:33)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 361041232 bytes (344 MB) / 900771840 bytes (859 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2627 Optifine OptiFine_1.12.2_HD_U_D1 75 mods loaded, 75 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version                      | Source                                          | Signature                                |
	|:----- |:-------------------------- |:---------------------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft                  | 1.12.2                       | minecraft.jar                                   | None                                     |
	| UCH   | mcp                        | 9.42                         | minecraft.jar                                   | None                                     |
	| UCH   | FML                        | 8.0.99.99                    | forge-1.12.2-14.23.2.2627.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                      | 14.23.2.2627                 | forge-1.12.2-14.23.2.2627.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | micdoodlecore              |                              | minecraft.jar                                   | None                                     |
	| UCH   | bowinfinityfix             | rv5                          | minecraft.jar                                   | e250ba31147feb059b86cfd74ee61a8aeb88fb9b |
	| UCH   | mercurius_updater          | 1.0                          | MercuriusUpdater-1.12.2.jar                     | None                                     |
	| UCH   | movillages                 | 1.5.4                        | [1.12]MoVillages-1.5.4 .jar                     | None                                     |
	| UCH   | appliedenergistics2        | rv5-stable-11                | appliedenergistics2-rv5-stable-11.jar           | None                                     |
	| UCH   | bdlib                      | 1.14.3.12                    | bdlib-1.14.3.12-mc1.12.2.jar                    | None                                     |
	| UCH   | ae2stuff                   | 0.7.0.4                      | ae2stuff-0.7.0.4-mc1.12.2.jar                   | None                                     |
	| UCH   | applecore                  | 3.1.1                        | AppleCore-mc1.12.2-3.1.1.jar                    | None                                     |
	| UCH   | bibliocraft                | 2.4.3                        | BiblioCraft[v2.4.3][MC1.12.0].jar               | None                                     |
	| UCH   | biomesoplenty              | 7.0.1.2348                   | BiomesOPlenty-1.12.2-7.0.1.2348-universal.jar   | None                                     |
	| UCH   | codechickenlib             | 3.1.6.339                    | CodeChickenLib-1.12.2-3.1.6.339-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | chickenchunks              | 2.4.1.71                     | ChickenChunks-1.12.2-2.4.1.71-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | chisel                     | MC1.12.2-0.2.0.31            | Chisel-MC1.12.2-0.2.0.31.jar                    | None                                     |
	| UCH   | redstoneflux               | 2.0.1                        | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCH   | cofhcore                   | 4.3.11                       | CoFHCore-1.12.2-4.3.11.6-universal.jar          | None                                     |
	| UCH   | cofhworld                  | 1.1.1                        | CoFHWorld-1.12.2-1.1.1.12-universal.jar         | None                                     |
	| UCH   | cookingforblockheads       | 6.3.26                       | CookingForBlockheads_1.12.2-6.3.26.jar          | None                                     |
	| UCH   | customnpcs                 | 1.12                         | CustomNPCs_1.12.2(20jan18).jar                  | None                                     |
	| UCH   | lootablebodies             | 2.4.0                        | DrCyanosLootableBodies_1.12-2.4.0.jar           | None                                     |
	| UCH   | endercore                  | 1.12.2-0.5.18                | EnderCore-1.12.2-0.5.18.jar                     | None                                     |
	| UCH   | jei                        | 4.8.5.159                    | jei_1.12.2-4.8.5.159.jar                        | None                                     |
	| UCH   | thermalfoundation          | 2.3.11                       | ThermalFoundation-1.12.2-2.3.11.8-universal.jar | None                                     |
	| UCH   | enderio                    | 5.0.20                       | EnderIO-1.12.2-5.0.20.jar                       | None                                     |
	| UCH   | enderiointegrationtic      | 5.0.20                       | EnderIO-1.12.2-5.0.20.jar                       | None                                     |
	| UCH   | enderiobase                | 5.0.20                       | EnderIO-1.12.2-5.0.20.jar                       | None                                     |
	| UCH   | enderioconduits            | 5.0.20                       | EnderIO-1.12.2-5.0.20.jar                       | None                                     |
	| UCH   | enderiointegrationforestry | 5.0.20                       | EnderIO-1.12.2-5.0.20.jar                       | None                                     |
	| UCH   | mantle                     | 1.12-1.3.2.24                | Mantle-1.12-1.3.2.24.jar                        | None                                     |
	| UCH   | tconstruct                 | 1.12.2-2.9.1.65              | TConstruct-1.12.2-2.9.1.65.jar                  | None                                     |
	| UCH   | enderiointegrationticlate  | 5.0.20                       | EnderIO-1.12.2-5.0.20.jar                       | None                                     |
	| UCH   | enderiomachines            | 5.0.20                       | EnderIO-1.12.2-5.0.20.jar                       | None                                     |
	| UCH   | enderiopowertools          | 5.0.20                       | EnderIO-1.12.2-5.0.20.jar                       | None                                     |
	| UCH   | extrautils2                | 1.0                          | extrautils2-1.12-1.7.6.jar                      | None                                     |
	| UCH   | zerocore                   | 1.12-0.1.2.1                 | zerocore-1.12-0.1.2.1.jar                       | None                                     |
	| UCH   | bigreactors                | 1.12.2-0.4.5.48              | ExtremeReactors-1.12.2-0.4.5.48.jar             | None                                     |
	| UCH   | fairylights                | 2.1.2                        | fairylights-2.1.2-1.12.x.jar                    | None                                     |
	| UCH   | fastleafdecay              | v14                          | FastLeafDecay-v14.jar                           | None                                     |
	| UCH   | galacticraftcore           | 4.0.1.169                    | GalacticraftCore-1.12.2-4.0.1.169.jar           | None                                     |
	| UCH   | galacticraftplanets        | 4.0.1.169                    | Galacticraft-Planets-1.12.2-4.0.1.169.jar       | None                                     |
	| UCH   | ichunutil                  | 7.1.4                        | iChunUtil-1.12.2-7.1.4.jar                      | None                                     |
	| UCH   | hats                       | 7.0.0                        | Hats-1.12.2-7.0.2.jar                           | None                                     |
	| UCH   | waila                      | 1.8.25                       | Hwyla-1.8.25-B40_1.12.jar                       | None                                     |
	| UCH   | inventorypets              | 1.4.9.9b                     | inventorypets-1.12-1.4.9.9b.jar                 | None                                     |
	| UCH   | inventorytweaks            | 1.64-dev+release.110.b4fac73 | InventoryTweaks-1.64-dev.jar                    | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | jeresources                | 0.8.7.41                     | JustEnoughResources-1.12.2-0.8.7.41.jar         | None                                     |
	| UCH   | llibrary                   | 1.7.9                        | llibrary-1.7.9-1.12.2.jar                       | None                                     |
	| UCH   | lootbags                   | 2.5.4b                       | LootBags-1.12.2-2.5.4b.jar                      | None                                     |
	| UCH   | lunatriuscore              | 1.2.0.42                     | LunatriusCore-1.12.2-1.2.0.42-universal.jar     | None                                     |
	| UCH   | malisiscore                | 1.12.2-6.4.0                 | malisiscore-1.12.2-6.4.0.jar                    | None                                     |
	| UCH   | malisisdoors               | 1.12.2-7.3.0                 | malisisdoors-1.12.2-7.3.0.jar                   | None                                     |
	| UCH   | radixcore                  | 1.12.x-2.2.1                 | RadixCore-1.12.x-2.2.1-universal.jar            | None                                     |
	| UCH   | mca                        | 1.12.2-5.3.1                 | MCA-1.12.x-5.3.1-universal.jar                  | None                                     |
	| UCE   | mekanism                   | 9.4.2                        | Mekanism-1.12.2-9.4.2.327.jar                   | None                                     |
	| UCE   | mekanismgenerators         | 9.4.2                        | MekanismGenerators-1.12.2-9.4.2.327.jar         | None                                     |
	| UCE   | mekanismtools              | 9.4.2                        | MekanismTools-1.12.2-9.4.2.327.jar              | None                                     |
	| UCH   | morph                      | 7.1.2                        | Morph-1.12.2-7.1.2.jar                          | None                                     |
	| UCH   | nei                        | 2.4.1                        | NotEnoughItems-1.12.2-2.4.1.233-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | harvestcraft               | 1.12.2t                      | Pam's+HarvestCraft+1.12.2t.jar                  | None                                     |
	| UCH   | schematica                 | 1.8.0.168                    | Schematica-1.12.2-1.8.0.168-universal.jar       | None                                     |
	| UCH   | spiceoflife                | 1.3.11                       | SpiceOfLife-mc1.12-1.3.11.jar                   | None                                     |
	| UCH   | tails                      | 1.12-1.10.0                  | Tails-1.12-1.10.0.jar                           | None                                     |
	| UCH   | theoneprobe                | 1.4.22                       | theoneprobe-1.12-1.4.22.jar                     | None                                     |
	| UCH   | thermalcultivation         | 0.1.5                        | ThermalCultivation-1.12.2-0.1.5.3-universal.jar | None                                     |
	| UCH   | thermaldynamics            | 2.3.11                       | ThermalDynamics-1.12.2-2.3.11.7-universal.jar   | None                                     |
	| UCH   | thermalexpansion           | 5.3.11                       | ThermalExpansion-1.12.2-5.3.11.14-universal.jar | None                                     |
	| UCH   | thermalinnovation          | 0.1.0                        | ThermalInnovation-1.12.2-0.1.0.3-universal.jar  | None                                     |
	| UCH   | torcherino                 | 7.1                          | torcherino-7.1.jar                              | None                                     |
	| UCH   | wailaharvestability        | 1.1.12                       | WailaHarvestability-mc1.12-1.1.12.jar           | None                                     |
	| UCH   | wanionlib                  | 1.12.2-1.5                   | WanionLib-1.12.2-1.5.jar                        | None                                     |
	| UCH   | wawla                      | 2.5.253                      | Wawla-1.12.2-2.5.253.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | unidict                    | 1.12.2-2.4c                  | UniDict-1.12.2-2.4c.jar                         | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  invtweaks.forge.asm.ContainerTransformer
llibrary (llibrary-1.7.9-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.169.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.18.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
  com.github.parker8283.bif.Transformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics 4000'
	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* AppleCoreAPI (3.1.0) from AppleCore-mc1.12.2-3.1.1.jar
		* appliedenergistics2|API (rv5) from appliedenergistics2-rv5-stable-11.jar
		* Baubles|API (1.1.1.0) from inventorypets-1.12-1.4.9.9b.jar
		* bigreactors|API (4.0.1) from ExtremeReactors-1.12.2-0.4.5.48.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.0.31.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-0.2.0.31.jar
		* cofhapi (2.2.0) from CoFHCore-1.12.2-4.3.11.6-universal.jar
		* cofhapi|block (2.2.0) from CoFHCore-1.12.2-4.3.11.6-universal.jar
		* cofhapi|core (2.2.0) from CoFHCore-1.12.2-4.3.11.6-universal.jar
		* cofhapi|item (2.2.0) from CoFHCore-1.12.2-4.3.11.6-universal.jar
		* cofhapi|tileentity (2.2.0) from CoFHCore-1.12.2-4.3.11.6-universal.jar
		* cofhapi|util (2.2.0) from CoFHCore-1.12.2-4.3.11.6-universal.jar
		* Core (0.1) from CustomNPCs_1.12.2(20jan18).jar
		* Core|Blocks (0.1) from CustomNPCs_1.12.2(20jan18).jar
		* Core|Constants (0.1) from CustomNPCs_1.12.2(20jan18).jar
		* Core|Entities (0.1) from CustomNPCs_1.12.2(20jan18).jar
		* Core|Entities|Data (0.1) from CustomNPCs_1.12.2(20jan18).jar
		* Core|Entities|Data|Role (0.1) from CustomNPCs_1.12.2(20jan18).jar
		* Core|Events (0.1) from CustomNPCs_1.12.2(20jan18).jar
		* Core|Handlers (0.1) from CustomNPCs_1.12.2(20jan18).jar
		* Core|Handlers|Data (0.1) from CustomNPCs_1.12.2(20jan18).jar
		* enderioapi (4.0.0) from EnderIO-1.12.2-5.0.20.jar
		* enderioapi|addon (4.0.0) from EnderIO-1.12.2-5.0.20.jar
		* enderioapi|capacitor (4.0.0) from EnderIO-1.12.2-5.0.20.jar
		* enderioapi|conduits (4.0.0) from EnderIO-1.12.2-5.0.20.jar
		* enderioapi|farm (4.0.0) from EnderIO-1.12.2-5.0.20.jar
		* enderioapi|redstone (4.0.0) from EnderIO-1.12.2-5.0.20.jar
		* enderioapi|teleport (4.0.0) from EnderIO-1.12.2-5.0.20.jar
		* enderioapi|tools (4.0.0) from EnderIO-1.12.2-5.0.20.jar
		* enderioapi|upgrades (4.0.0) from EnderIO-1.12.2-5.0.20.jar
		* Galacticraft API (1.1) from GalacticraftCore-1.12.2-4.0.1.169.jar
		* iChunUtil API (1.2.0) from iChunUtil-1.12.2-7.1.4.jar
		* jeresources|API (0.8.7.41) from JustEnoughResources-1.12.2-0.8.7.41.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.8.5.159.jar
		* MekanismAPI|core (9.0.0) from Mekanism-1.12.2-9.4.2.327.jar
		* MekanismAPI|energy (9.0.0) from Mekanism-1.12.2-9.4.2.327.jar
		* MekanismAPI|gas (9.0.0) from Mekanism-1.12.2-9.4.2.327-api.jar
		* MekanismAPI|infuse (9.0.0) from Mekanism-1.12.2-9.4.2.327.jar
		* MekanismAPI|laser (9.0.0) from Mekanism-1.12.2-9.4.2.327-api.jar
		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.12.2-9.4.2.327.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.12.2-9.4.2.327.jar
		* SchematicaAPI (1.1) from Schematica-1.12.2-1.8.0.168-universal.jar
		* SchematicaAPI|Events (1.1) from Schematica-1.12.2-1.8.0.168-universal.jar
		* theoneprobe_api (1.4.4) from theoneprobe-1.12-1.4.22.jar
		* WailaAPI (1.3) from Hwyla-1.8.25-B40_1.12.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.12-0.1.2.1.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.12-0.1.2.1.jar
		* zerocore|API|multiblock|tier (1.10.2-0.0.2) from zerocore-1.12-0.1.2.1.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.12-0.1.2.1.jar
	OptiFine Version: OptiFine_1.12.2_HD_U_D1
	OptiFine Build: 20180323-135452
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.4358
	OpenGlRenderer: Intel(R) HD Graphics 4000
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by thommy101** [comment]
Hi,

You've got a file called Mekanism-1.12.2-9.4.2.327-api.jar in your mod folder. This is an source file needed for developing mods, not for running Mekanism on a client/server. Deleting that file should resolve your issue.

**Comment by Dashna99** [comment]
Thanks for the help
