### ISSUE TITLE
Mekanism Steam conflict with Thermal's Steam

### ISSUE THREAD

**Issue by Xiaminou** [aidancbrady/Mekanism#4997]
When both Mekanism and Thermal-suite mods are installed Mekanism's steam conflict with Thermal's Steam and throw a lot of error, in addition after restarting your server you can't pump steam into Thermal Expansion's Steam Dynamos anymore.

https://youtu.be/XUhPb827HW4

Server Log: [latest.log](https://github.com/TheLMiffy1111/JAOPCA/files/1908767/latest.log)

Minecraft: 1.12.2
Forge: 2659
Mods: [list.txt](https://github.com/TheLMiffy1111/JAOPCA/files/1908777/list.txt)

**Comment by Xiaminou** [comment]
Talk to KingLemming, I don't know enough to comment on what's happening.

**Comment by thiakil** [comment]
I'm telling you it can't be Mek's fault.

**Comment by nematrec** [comment]
Can confirm this is happening. Removing Mekanism makes them work again. 
Other mods producing steam are installed and don't conflict with Thermal expansion.

**Comment by thiakil** [comment]
That sounds more and more like thermal isn't using the fluid registry properly. Multiple mods register fluids and the registry decides which one should be used.

Mekanism uses it properly as it does not cache a fluid reference.

**Comment by KingLemming** [comment]
It is indeed something I re-introduced in TE. I had solved this before, was told to move it to FluidStacks for delegate reasons and apparently that was incorrect.
