### ISSUE TITLE
digital miner creates huge amounts of lighting errors when in silk touch mode

### ISSUE THREAD

**Issue by Too-DAMN-Much** [aidancbrady/Mekanism#4998]
self explanatory really, place a digital miner, enable silk touch, be annoyed by the dark holes left by ores it mines.

**Comment by thiakil** [comment]
Screenshot please.

Though it sounds like something we can't change.

**Comment by Too-DAMN-Much** [comment]
yeah doing so now, we run with a lot of mods and have been used to this for the past few minecraft versions so always assumed it was a mekanism issue.

**Comment by Too-DAMN-Much** [comment]
https://imgur.com/a/457Kd

let me know if you need more information, sorry it took so long.

**Comment by thiakil** [comment]
Is the miner set to replace the mined block with anything? or is it an air hole?

**Comment by Too-DAMN-Much** [comment]
sorry for the late response, but no i don't really find replacing the blocks with anything to be useful.

**Comment by thiakil** [comment]
Unlit air blocks are not caused by us, it is likely another mod or server software causing it.

If you can reproduce it with just Forge and Mekanism though I'll take another look.
