### ISSUE TITLE
suggestion: add old AOBD functionality into mekanism as there is no useful successor

### ISSUE THREAD

**Issue by Too-DAMN-Much** [aidancbrady/Mekanism#4999]
the closest we currently have for 1.12 is JAOPCA which is manual addition through integration only which from my experience misses a totally unacceptable and ridiculously large amount of ores.

**Comment by thiakil** [comment]
You might want to look into Base Metals from MMD. Other than that many things can be done with CraftTweaker.

We're not going to add 5x processing for every single modded ore out there.
