### ISSUE TITLE
Jobs Plugin & Digi Miner Not Working

### ISSUE THREAD

**Issue by GlutenfFreeAIDS** [aidancbrady/Mekanism#5001]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Digital miner doesn't pull any resources due to jobs reborn plugin. Power drains from the machine, but nothing gets pulled.

If this isn't a fix you can do, how can I mend this problem/incompatibility?
#### Steps to reproduce:
1. Install jobs reborn plugin
2. Digital miner some stuff
3. Notice it doesn't work

#### Version (make sure you are on the latest version before reporting):
**Forge:** 7.10.99
**Mekanism:** 9.1.1
**Other relevant version:** 1.7.10 minecraft (augmented triad pack)

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
no crashes
[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
> 1.7.10 minecraft

We don't update 1.7
