### ISSUE TITLE
World crash on startup ( cannot use backups )

### ISSUE THREAD

**Issue by Mystrik** [aidancbrady/Mekanism#5005]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Opened up a chance cube, then world crashed and every time I open it it crashes, a modding community told me to send this to you

#### Steps to reproduce:
1. have a giant energy battery
2. open a gay chance cube
3. watch the world burn ????

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[https://pastebin.com/wPcZndLB]

**Comment by thiakil** [comment]
already been reported
