### ISSUE TITLE
Digital Miner Auto-Eject not functioning

### ISSUE THREAD

**Issue by SolSavvy** [aidancbrady/Mekanism#5007]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce: I dont even know what led up to it bugging out
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.2.2611** 
**Mekanism: 1.12.2-9.4.3.330**
As well as
**-MekanismGenerators 1.12.2-9.2.3.330**
**-MeknismTools 1.12.2-9.4.3.330**
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
Show your configurations and the destinations

**Comment by MarshTheBacca** [comment]
It works just fine for me
