### ISSUE TITLE
Fluix Crystal to Fluix Dust - does not work

### ISSUE THREAD

**Issue by Cbert** [aidancbrady/Mekanism#5008]
Crusher does not work with Fluix Crystals.
![2018-04-20 17 48 05](https://user-images.githubusercontent.com/9320867/39058071-84e00f26-44c3-11e8-8f95-37599867e6ae.png)

forge/1.12.2-14.23.3.2669
Mekanism-1.12.2-9.4.3.330
appliedenergistics2-rv5-stable-11

**Comment by Cbert** [comment]
Peanut to bio fuel does not work
![2018-04-20 18 56 41](https://user-images.githubusercontent.com/9320867/39061327-9b0fcf58-44cc-11e8-935c-7224696e314b.png)

**Comment by thommy101** [comment]
For pams integration, take a look at the this crafttweaker script:
https://github.com/DarethZ33/pams-harvestcraft-mekanism-crusher/blob/master/03_pams_harvestcraft_mekanism_crusher.zs

**Comment by Cbert** [comment]
**thommy101**, thanks, but to work it (CraftTweaker2-1.12-4.1.6.jar) also needs MTLib-3.0.4.jar, modtweaker-4.0.10.jar.

Fixed with CraftTweaker, MTLib, modtweaker, DarethZ33 03_pams_harvestcraft_mekanism_crusher.zs, and few scripts from Enigmatica 2 Modpack.

**Comment by Cbert** [comment]
**thommy101**, thanks, but to work it (CraftTweaker2-1.12-4.1.6.jar) also needs MTLib-3.0.4.jar, modtweaker-4.0.10.jar.

Fixed with CraftTweaker, MTLib, modtweaker, DarethZ33 03_pams_harvestcraft_mekanism_crusher.zs, and few scripts from Enigmatica 2 Modpack.
