### ISSUE TITLE
[Request] Foundation mod/version

### ISSUE THREAD

**Issue by Skillotic0703** [aidancbrady/Mekanism#5009]
Mekanism is a great mod but sometimes it doesn't really fit in your pack because there are a lot of overlapping features between Mekanism and other tech mods but you actually want some crafting items from mekanism to use them in crafts.
That's why I suggest two solutions to this problem:
- Create a foundation mod that will contain all base items from Mekanism (alloys, circuits, ingots, ores, crafting items like teleportation cores and eventually the wrench) and the other Mekanism modules will depend on it.
- Or you can just create a mod that only registers Mekanism items without adding machines etc...

I'm actually going to tell the same thing to other tech mod devs except for Thermal Expansion because it already has Thermal Foundation as a dependency.

**Comment by thiakil** [comment]
Many things can be disabled via config. Splitting the mod up is suboptimal
