### ISSUE TITLE
Cannot add recipe via CraftTweaker to Energized Smelter

### ISSUE THREAD

**Issue by justinrusso** [aidancbrady/Mekanism#5010]
#### Issue description:
I am trying to add a recipe to the Energized Smelter via CraftTweaker and it appears to not work. There is no error in the crafttweaker.log file

#### Steps to reproduce:
```
//Ensure furnace removals dont affect smelter recipe adding
furnace.remove(<minecraft:iron_ingot>, <mekanism:dust>);
mods.mekanism.smelter.addRecipe(<mekanism:dust>, <minecraft:iron_ingot>);

//Attempt to just add any random recipe to test if recipe addition works at all
mods.mekanism.smelter.addRecipe(<minecraft:stick>, <minecraft:sticky_piston>);
```

#### Version (make sure you are on the latest version before reporting):
**Minecraft:** 1.12.2
**Forge:** 14.23.3.2669
**Mekanism:** 1.12.2-9.4.3.330
**CraftTweaker:** 1.12-4.1.6
**MTLib:** 3.0.4

#### Logs:

[crafttweaker, debug, and latest](https://gist.github.com/justinrusso/cf462e905960b3818b3fff904b90697a)

**Comment by thommy101** [comment]
Hi @justinrusso,
You're right that the current crafttweaker implementation for the energizer smelter is broken.
I don't know if adding the recipes to the default smelting list (which Mekanism also uses) is an option for you/Sevtech?

**Comment by justinrusso** [comment]
I do understand that the smelter does also use the furnace recipes.

But the intention of these recipes is to make it so normal furnaces cant do this recipe, and only the smelter can.

**Comment by thommy101** [comment]
That's what I already thought with my current sevtech experience (loving it by the way).
I might have some time this weekend to take a look at fixing it.

It might take some time to get it released.. Currently Aidan is the only one capable of releasing to curse.

**Comment by justinrusso** [comment]
Glad youre enjoying it! Appreciate the help. Is there any known idea of when a release is to be made? I noticed the last release was in December. With the amount of changes that appear to have happened, this would probably have to be slated for a further release of the pack.

**Comment by thommy101** [comment]
I've messaged Aidan. I hope to get a release out soon.
Since December are almost only bugfixes and no new features (that I know off)

**Comment by thiakil** [comment]
@thommy101 does the Mek Smelter have its own smelting list?

**Comment by thommy101** [comment]
It does, but doesn't use it if I remember correctly.
Somewhere on startup it copies everything from the vanilla smelting list to the energized smelter list.

**Comment by thommy101** [comment]
Found the bug causing it.. It's gonna take a bit more time to fix properly, as I want the JEI integration to be working as well.
[Who thought it would be a good idea to clear all the recipes on server start?](https://github.com/aidancbrady/Mekanism/blob/1.12/src/main/java/mekanism/common/Mekanism.java#L661)

Btw, releases will be a lot quicker, so when it's fixed, it should be out short after it.

**Comment by thommy101** [comment]
![Energized smelter](https://user-images.githubusercontent.com/1036527/39360058-df5eeb9e-4a1c-11e8-9688-092251cf40e8.png)

I think this looks good :)

**Comment by thommy101** [comment]
I will create a release later today, should be out and available about half an hour after this issue will be closed (depending curse approval time)

**Comment by thommy101** [comment]
Build has started, it will automatically upload to curse. Version will be 9.4.7
