### ISSUE TITLE
Mekanism API - Can't add recipe

### ISSUE THREAD

**Issue by trabpukcip** [aidancbrady/Mekanism#5013]
#### Issue description:
Can't add Mekanism recipes using Mekanism API. Crashes at startup complaining that the recipes are not being added in init (despite them actually being added in init).

#### Steps to reproduce:
1. Make a very basic single class mod.
2. Add Mekanism and Mekanism API to you mods libs folder and import them to your build path.
3. Add a recipe such as ```MekanismAPI.recipeHelper().addEnrichmentChamberRecipe(new ItemStack(Blocks.END_STONE, 1), new ItemStack(Items.BEEF, 4));``` to your mods init.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.2.2611
**Mekanism:** 9.4.3.330 + API

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[crash-2018-04-22_14.27.20-client.txt](https://gist.github.com/trabpukcip/47b90a5c9fbf7ac7b9319fdaec8336be)

#### Notes:
Test Mod Repo: https://github.com/trabpukcip/Trab-Test-Mod
Works fine using the RecipeHandler class from Mekanism itself. That of course defeats the purpose of using the API though :smiley: 
Also I could just be doing something derpy...

**Comment by thiakil** [comment]
Message is incorrect, register recipes *before* init. The Recipe registry event is your last chance.

**Comment by trabpukcip** [comment]
I have tried previously to put the statement into preInit (crashes because too early). I have now has a crack at doing the same thing with the recipe registry event and it still crashes: https://github.com/trabpukcip/Trab-Test-Mod/blob/master/src/main/java/org/icannt/trabtestmod/RecipeRegistry.java

**Comment by thommy101** [comment]
d093d4b5035d8de659d931ad30619434d0a19f50
5ad333102584b219938ca12388bd133b2960f8f1

**Comment by thiakil** [comment]
Should work in `9.4.5.340`

**Comment by trabpukcip** [comment]
Well it does work if you load your recipe at the VillagerProfession event.
```
    	@SubscribeEvent
        public static void registerVillagerProfession(final RegistryEvent.Register<VillagerProfession> event)
        {
    		logIt("VillagerProfession", Loader.instance().getLoaderState());
    		MekanismAPI.recipeHelper().addEnrichmentChamberRecipe(new ItemStack(Blocks.END_STONE, 1), new ItemStack(Items.BEEF, 4));
        }
```

This is kinda hacky obviously, the logic check needs to be more granular.
