### ISSUE TITLE
[1.12.2] Client Crash: java.lang.NullPointerException: Rendering screen

### ISSUE THREAD

**Issue by Morpheus1101** [aidancbrady/Mekanism#5016]
Forge *.3.2670
Mekanism 1.12.2-9.4.4.0ab57d0

Crash Log @ https://gist.github.com/Morpheus1101/7c270c9cabb919d875c65d26cc993625

At the time of crash i was trying to move a configurator from 1 inv slot to another

**Comment by thiakil** [comment]
Fixed in dev, thanks

**Comment by thommy101** [comment]
108f4ddbe8d960c9f566af3330fee388c74dd400
