### ISSUE TITLE
Game Crash: Survival Mode While Placing Generators (1.7.10)

### ISSUE THREAD

**Issue by SwagamiteJohnson** [aidancbrady/Mekanism#5018]
#### Issue description:
When playing Minecraft on survival mode (difficulty normal, cheats off), and attempting to place generators of any discription (heat and bio generators in particular), the game will crash, and give an error.  In addition, upon logging back into the world, not just will the generator have been placed, but it is duplicated in my inventory (therefore having at least two total generators).  Do note that if I play a creative world, it does not seem to have this issue at all.

#### Steps to reproduce:
1.  Setup a normal Minecraft survival world (difficulty normal, cheats off, cheat chest on).
2.  Build a generator.
3.  Place generator on any surface.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.7.10-Forge10.13.4.1614-1.7.10
**Mekanism:** 
1.7.10-9.1.0.281
Generators & Generators: 1.7.10-9.1.1.1031
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
The game crashed whilst unexpected error
Error: java.lang.NoSuchFieldError: allowProtection

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 4/24/18 7:38 PM
Description: Unexpected error

java.lang.NoSuchFieldError: allowProtection
	at mekanism.generators.common.item.ItemBlockGenerator.getSecurity(ItemBlockGenerator.java:523)
	at mekanism.generators.common.item.ItemBlockGenerator.placeBlockAt(ItemBlockGenerator.java:223)
	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:360)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mekanism.generators.common.item.ItemBlockGenerator.getSecurity(ItemBlockGenerator.java:523)
	at mekanism.generators.common.item.ItemBlockGenerator.placeBlockAt(ItemBlockGenerator.java:223)
	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:360)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['noobyhypster'/260, l='MpServer', x=-501.88, y=64.62, z=23.30]]
	Chunk stats: MultiplayerChunkCache: 441, 450
	Level seed: 0
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-252,64,248), Chunk: (at 4,4,8 in -16,15; contains blocks -256,0,240 to -241,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 237268 game time, 275466 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 56 total; [EntitySpider['Spider'/384, l='MpServer', x=-437.16, y=31.00, z=-24.38], EntityZombie['Zombie'/385, l='MpServer', x=-435.94, y=18.00, z=19.53], EntitySkeleton['Skeleton'/386, l='MpServer', x=-437.50, y=18.00, z=20.50], EntityClientPlayerMP['noobyhypster'/260, l='MpServer', x=-501.88, y=64.62, z=23.30], EntityCow['Cow'/392, l='MpServer', x=-430.31, y=63.00, z=-48.56], EntityCow['Cow'/393, l='MpServer', x=-429.91, y=64.00, z=-46.34], EntityChicken['Chicken'/9, l='MpServer', x=-441.09, y=67.00, z=96.47], EntityCow['Cow'/394, l='MpServer', x=-431.63, y=64.00, z=-46.84], EntityChicken['Chicken'/10, l='MpServer', x=-441.06, y=67.00, z=97.88], EntityCreeper['Creeper'/395, l='MpServer', x=-426.97, y=12.00, z=-9.56], EntityChicken['Chicken'/11, l='MpServer', x=-441.75, y=67.00, z=97.41], EntityCow['Cow'/396, l='MpServer', x=-431.06, y=64.00, z=-28.09], EntityChicken['Chicken'/12, l='MpServer', x=-440.72, y=67.00, z=95.94], EntitySkeleton['Skeleton'/397, l='MpServer', x=-428.22, y=11.00, z=-9.16], EntityZombie['Zombie'/398, l='MpServer', x=-426.50, y=12.00, z=-8.50], EntitySpider['Spider'/399, l='MpServer', x=-431.06, y=40.00, z=-3.13], EntitySkeleton['Skeleton'/402, l='MpServer', x=-426.53, y=33.00, z=13.13], EntityCow['Cow'/403, l='MpServer', x=-423.81, y=63.00, z=6.13], EntitySkeleton['Skeleton'/304, l='MpServer', x=-578.50, y=45.00, z=80.50], EntitySpider['Spider'/312, l='MpServer', x=-564.66, y=19.00, z=-51.75], EntitySpider['Spider'/313, l='MpServer', x=-572.50, y=37.00, z=99.50], EntityChicken['Chicken'/324, l='MpServer', x=-546.59, y=63.00, z=-36.53], EntitySkeleton['Skeleton'/325, l='MpServer', x=-543.84, y=20.00, z=17.53], EntityZombie['Zombie'/337, l='MpServer', x=-541.50, y=38.00, z=-45.50], EntitySkeleton['Skeleton'/338, l='MpServer', x=-539.50, y=15.00, z=-6.25], EntitySkeleton['Skeleton'/339, l='MpServer', x=-539.50, y=15.00, z=-5.31], EntityCreeper['Creeper'/340, l='MpServer', x=-539.50, y=15.00, z=-9.50], EntityCreeper['Creeper'/341, l='MpServer', x=-539.50, y=15.00, z=-8.50], EntityCreeper['Creeper'/342, l='MpServer', x=-533.50, y=26.00, z=3.50], EntitySkeleton['Skeleton'/343, l='MpServer', x=-535.50, y=26.00, z=6.50], EntitySquid['Squid'/344, l='MpServer', x=-532.34, y=60.00, z=48.47], EntityCreeper['Creeper'/349, l='MpServer', x=-516.50, y=43.00, z=-40.50], EntityCow['Cow'/350, l='MpServer', x=-518.47, y=63.00, z=-37.47], EntityCow['Cow'/351, l='MpServer', x=-514.25, y=63.00, z=-39.47], EntitySkeleton['Skeleton'/352, l='MpServer', x=-526.94, y=20.00, z=-26.41], EntityCreeper['Creeper'/353, l='MpServer', x=-513.75, y=61.00, z=3.38], EntitySquid['Squid'/354, l='MpServer', x=-513.02, y=59.00, z=48.97], EntitySquid['Squid'/355, l='MpServer', x=-513.88, y=60.00, z=57.50], EntitySkeleton['Skeleton'/359, l='MpServer', x=-505.50, y=30.00, z=-10.50], EntitySkeleton['Skeleton'/360, l='MpServer', x=-509.06, y=31.00, z=-6.53], EntityItem['item.tile.Generator.BioGenerator'/361, l='MpServer', x=-496.63, y=60.13, z=41.41], EntityCow['Cow'/362, l='MpServer', x=-485.28, y=63.00, z=-52.41], EntityZombie['Zombie'/363, l='MpServer', x=-498.66, y=16.00, z=-46.95], EntityBat['Bat'/364, l='MpServer', x=-495.59, y=17.00, z=-44.09], EntityCow['Cow'/365, l='MpServer', x=-494.28, y=63.00, z=-30.47], EntityCreeper['Creeper'/366, l='MpServer', x=-482.53, y=24.00, z=2.97], EntityBat['Bat'/367, l='MpServer', x=-475.25, y=23.10, z=4.75], EntitySkeleton['Skeleton'/369, l='MpServer', x=-464.50, y=20.00, z=-32.50], EntityCreeper['Creeper'/370, l='MpServer', x=-479.00, y=25.00, z=25.56], EntitySquid['Squid'/371, l='MpServer', x=-473.25, y=57.22, z=60.50], EntityCow['Cow'/373, l='MpServer', x=-462.47, y=63.00, z=-40.81], EntityEnderman['Enderman'/374, l='MpServer', x=-459.50, y=17.00, z=-10.78], EntitySkeleton['Skeleton'/375, l='MpServer', x=-452.94, y=19.00, z=-10.50], EntityZombie['Zombie'/376, l='MpServer', x=-452.50, y=15.00, z=0.50], EntitySkeleton['Skeleton'/382, l='MpServer', x=-430.00, y=11.00, z=-17.30], EntityBat['Bat'/383, l='MpServer', x=-447.47, y=18.00, z=-21.25]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 983681864 bytes (938 MB) / 1778384896 bytes (1696 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 104
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E3 30 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	voltzenginepreloader{0.0.1} [Voltz Engine Preloader] (minecraft.jar) 
	UCHIJAAAA	lucky{5.1.0} [Lucky Block] ([1-7-10]_Lucky_Block_v5-1-0.jar) 
	UCHIJAAAA	lightsabers{1.1.1} [Advanced Lightsabers Mod] (AdvancedLightsabers-1.7.10-1.1.1.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.22} [BuildCraft] (buildcraft-7.1.22.jar) 
	UCHIJAAAA	voltzengine{1.9.14.302} [Voltz Engine] (VoltzEngine-1.7.10-1.9.14b302.jar) 
	UCHIJAAAA	armory{0.7.4.132} [Armory] (Armory-1.7.10-0.7.4b132.jar) 
	UCHIJAAAA	assemblyline{0.5.3.154} [Assembly Line] (Assembly-Line-1.7.10-0.5.3b154.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.22} [BC Transport] (buildcraft-7.1.22.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.22} [BC Factory] (buildcraft-7.1.22.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.22} [BC Silicon] (buildcraft-7.1.22.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.22} [BC Robotics] (buildcraft-7.1.22.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.22} [BC Energy] (buildcraft-7.1.22.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.22} [BC Builders] (buildcraft-7.1.22.jar) 
	UCHIJAAAA	ctb{2.4} [Call To Battle] (Call to Battle 2.jar) 
	UCHIJAAAA	icbm{2.15.4.497} [ICBM] (ICBM-1.7.10-2.15.4b497.jar) 
	UCHIJAAAA	icbmsentry{0.1.0.58} [ICBM Sentries] (ICBM-Classic-Sentry-1.7.10-0.1.0b58.jar) 
	UCHIJAAAA	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAAAA	Mekanism{9.1.0} [Mekanism] (Mekanism-1.7.10-9.1.0.281.jar) 
	UCHIJAAAA	MekanismGenerators{9.1.1} [MekanismGenerators] (MekanismGenerators-1.7.10-9.1.1.1031.jar) 
	UCHIJAAAA	MekanismTools{9.1.1} [MekanismTools] (MekanismTools-1.7.10-9.1.1.1031.jar) 
	UCHIJAAAA	militarybasedecor{0.1.0.197} [Military Base Decor] (MilitaryBaseDecor-1.7.10-0.1.0b197.jar) 
	UCHIJAAAA	voltzenginemodcompat{1.9.14.302} [Voltz Engine Mod Compatibility Loader] (VoltzEngine-1.7.10-1.9.14b302.jar) 
	UCHIJAAAA	voltzenginemodflag{1.9.14.302} [VoltzEngine mod protection, flag, and region system] (VoltzEngine-1.7.10-1.9.14b302.jar) 
	UCHIJAAAA	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 22.20.16.4836' Renderer: 'Intel(R) HD Graphics 630'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 630 GL version 4.5.0 - Build 22.20.16.4836, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_E3
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 22.20.16.4836
	OpenGlRenderer: Intel(R) HD Graphics 630
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by thiakil** [comment]
Like all of the other issues that you didnt search for. Don't mix Mekanism version numbers.
