### ISSUE TITLE
Fuelwood heater problems

### ISSUE THREAD

**Issue by Frunblumglin** [aidancbrady/Mekanism#5019]
#### Issue description:
When placing heat sources such as lava buckets (and in my case the lava crystal from bloodmagic) inside the fuelwood heater, the bucket is consumed.

#### Steps to reproduce:
1. place a fuelwood heater in the world
2. place a lava bucket or other item that should have non-consumables inside
3. cry from seeing the item vanish

#### Version (make sure you are on the latest version before reporting):
![image](https://user-images.githubusercontent.com/13581892/39225896-e4a63f8c-4803-11e8-803b-744b33999934.png)

**Forge:** 14.23.2.2651
**Mekanism:** 9.4.3.330
**Other relevant version:** sevtech 3.0.6

**Comment by thommy101** [comment]
I do remember a ticket like this, can't find it right now.
We released a new version yesterday which contains a lot of bugfixes, it might solve this bug too.
