### ISSUE TITLE
Unable to place machinery with bound blocks above 255 height with Cubic Chunks installed

### ISSUE THREAD

**Issue by roboderpy** [aidancbrady/Mekanism#5023]
Im not sure where to report it, but you can place regular Mekanism machinery outside of vanilla's 0 -> 255 height range and it would work.

Some of affected machinery:
Wind Generator
Neutron Activator
Advanced Solar Panel (you *can* place regular solar panel however)
others...
_____
### Version
**Forge:** 2655
**Mekanism:** https://github.com/aidancbrady/Mekanism/commit/2657f7b9571f576716ab2244c0cfa5416d312163

**Comment by thiakil** [comment]
Apologies, I posted the previous comment from mobile.

I've changed the checks to use `World` methods, so assuming CC is a sane mod, it should work
