### ISSUE TITLE
Server Log spam from Dynamic Tanks

### ISSUE THREAD

**Issue by Bigevildog666** [aidancbrady/Mekanism#5025]
Hello,
our Dynamic Tanks from Mekanism are buggy.Sometimes the fluids are disappear,only after breaking and build again the machine work again.And the Dynamic Tanks spam our Log.We are playing on the server.

Energized Glowstone didnt show correctly.

Mekansim Version: 1.12.2-9.4.3.330

Server Log:
https://gist.github.com/Bigevildog666/c7c7b4f6e1839b8ce3503742354d59a5

**Comment by thiakil** [comment]
Please do what the template asks. https://github.com/aidancbrady/Mekanism/issues?q=is%3Aissue+The+validated+object+is+null+is%3Aclosed

Update your version.
