### ISSUE TITLE
Mekanism 9.4.5 says it is 9.4.4

### ISSUE THREAD

**Issue by coldReactive** [aidancbrady/Mekanism#5026]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Mekanism 9.4.5 thinks it's 9.4.4, and will constantly say that it should be updated in chat when loading a world.

#### Steps to reproduce:
1. Not applicable (Or upgrade from 9.4.4 and start a new world.)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.3.2673
**Mekanism:** 1.12.2-9.4.5.340 (via twitch app)
**Other relevant version:** 

Video: https://www.youtube.com/watch?v=haVneMU6Tvk

**Comment by thiakil** [comment]
Yeah i noticed it today, my bad!
