### ISSUE TITLE
[Suggestion] Unbalanced Crusher recipe for AE2 Silicon

### ISSUE THREAD

**Issue by raspopov** [aidancbrady/Mekanism#5029]
Currently Crusher processing any Sand to Silicon (ore:itemSilicon):

![Sand to Silicon](https://i.imgur.com/FGfGoy0.jpg)

But it's very unbalanced since AE2 uses smelting from Quartz Dust (ore:dustNetherQuartz and ore:dustCertusQuartz) only:

![Quartz to Silicon](https://i.imgur.com/sFxGRUO.jpg)

I suggest to remove a Crusher recipe and left Energized Smelter ones only.

**Comment by thiakil** [comment]
Use crafttweaker. That recipe has always been there.

**Comment by raspopov** [comment]
I used it, Thank you for suggestion!

NOTE: To remove a recipe we need:

1. Install [CraftTweaker](https://www.curseforge.com/minecraft/mc-mods/crafttweaker)
2. Install [ModTweaker](https://www.curseforge.com/minecraft/mc-mods/modtweaker) for CraftTweaker
3. Install [MTLib](https://minecraft.curseforge.com/projects/mtlib) for ModTweaker
4. Create a new .zs-file in Notepad with single line: `mods.mekanism.crusher.removeRecipe(<appliedenergistics2:material:5>);` and place it to minecraft\scripts folder.
