### ISSUE TITLE
JEI is not showing an Energized Smelter recipes at all

### ISSUE THREAD

**Issue by raspopov** [aidancbrady/Mekanism#5030]
It's happened several days ago (one or two Mekanism updates ago). All other recipes are OK.

JEI: 4.9.1.168
Mekanism: 1.12.2-9.4.6.341
Forge: 14.23.3.2676

P.S. Can it be depend with #5010?

**Comment by thommy101** [comment]
As far as I know it hasn't shown the recipes ever. It's fixed in the same commit at the issue you've linked.

**Comment by thommy101** [comment]
Fixed in c713b3acb340f70aef965b13688cbee1ae215e10

**Comment by thiakil** [comment]
There's a tab at the top there.

**Comment by trabpukcip** [comment]
@thiakil There is Chemical Dissolution Chamber, Purification Chamber, Chemical Injection Chamber & Enrichment Chamber. No Energized Smelter is showing up.

**Comment by thiakil** [comment]
One does not process ores in the energized smelter.

If you have a CT script that changes that then you'd need to show it

**Comment by trabpukcip** [comment]
Is it advisable? In a lot of cases no. JEI should still represent what you can do with a given object even if it is suboptimal, that is the user's choice during gameplay to utilise it.

The wiki also states that it is a thing that can be done: http://wiki.aidancbrady.com/wiki/Ore_Processing#Tier_0
Other mods always show their basic electric furnace in JEI regardless.

![Screenshot](https://i.imgur.com/9Tq2P96.png)

**Comment by thiakil** [comment]
- If you have any scripts that remove a standard furnace recipe from Mekanism it *won't* display as a furnace catalyst
- It never did show as a catalyst until recently

So again, *give details of your setup instead of just saying it doesnt work*

**Comment by trabpukcip** [comment]
No scripts at all I am talking about the mod by itself with JEI loaded.

The only thing being tested is the example with gold.

Other mods show a basic smelt with an ore and an ingot in their electric furnace in JEI, I don't get how this mod would be an exception?

Is it assumed that a user would know they could do a basic smelt with the energized smelter? Maybe they don't have the power or resources for the enrichment chamber for some reason. Perhaps the ore that is being processed does not have a dust/pulverized version to process to?

**Comment by thiakil** [comment]
What you are arguing (that Mekanism does add an entry to the vanilla smelting category catalysts) is *not* related to this issue.

As I said it has *never* added it. So it cannot be "broken again"

**Comment by trabpukcip** [comment]
Ok I agree on that point of it not being "broken again". The issue title had no mention of crafttweaker, it was more assumed once that P.S. bit was read. Should I open a feature request then?

**Comment by thiakil** [comment]
Please
