### ISSUE TITLE
Crash when Applied Energistics 2 API is not in build path

### ISSUE THREAD

**Issue by trabpukcip** [aidancbrady/Mekanism#5031]
#### Issue description:
Crash from missing Applied Energistics 2 API, which as far as I am aware should not be required in a dev environment when developing against the Mekanism API. Has no effect on running the normal game client.

#### Steps to reproduce:
1. Make a basic mod
2. Add Mekanism and Mekanism API to your workspaces build path
3. Run from dev environment and crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.2.2611
**Mekanism:** 9.4.6.341
**Other relevant version:**

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://gist.github.com/trabpukcip/971f2bce00bd4ad3c9ee0b96b2b3e272

#### Notes
Does not happen with builds made before commit b2df586 something on that commit is causing the issue. Operates fine in a dev environment with commit 37b8e15. Current build and builds made with commit b2df586 operate fine if appliedenergistics2-rv5-stable-11-api.jar is added to the build path. Crash with commit b2df586 is here: https://gist.github.com/trabpukcip/5d975f204f25b91a6a9cbe791c892d05

**Comment by thiakil** [comment]
Looks like a forge issue. 92914f6b07424866b8b86655e8182d698b8b6a19 *might* fix it
