### ISSUE TITLE
The game crashes when you try to break wires/pipes. ( I apologize for the mistakes, I do not know English well.)

### ISSUE THREAD

**Issue by Hurfy** [aidancbrady/Mekanism#5035]
The game crashes when you try to break wires/pipes. 
However, in the creative mode, these blocks break without problems.

1. Put the pipe / wire.
2. Try to break it in survival mode.
3. Re-enter the game. 

Forge 12.18.3.2185
Mekanism-1.10.2-9.2.4.103 

Crash-Report: pastebin.com/i6GePj7q

**Comment by thiakil** [comment]
looks like a `treecapitator` issue

**Comment by Hurfy** [comment]
This is indeed so. Thank you.
