### ISSUE TITLE
Smelting Factories Not Working?

### ISSUE THREAD

**Issue by simplykarma** [aidancbrady/Mekanism#5036]
#### Issue description:
The Energized Smelter still smelts dusts and items, however it seems that the smelting factories will not smelt at all. I suspect https://github.com/aidancbrady/Mekanism/commit/c713b3acb340f70aef965b13688cbee1ae215e10 might have something to do with this.

![image](https://user-images.githubusercontent.com/38862001/39435774-797b23b2-4c59-11e8-844a-8514649584b2.png)

#### Steps to reproduce:
1. Place any tier of Smelting Factory and provide power.
2. Place a dust such as tin dust inside.
3. Nothing happens.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.3.2655
**Mekanism:** 1.12.2-9.4.7-342
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thommy101** [comment]
Thanks for the report.
The commit you guessed is 99.9% the cause of it.. I'll take a look.

**Comment by ProsperCraft** [comment]
Can confirm we are having this issue after updating as well.

**Comment by simplykarma** [comment]
Is there any way I could grab this build from the CI or do I need to wait for the CF release?

**Comment by thiakil** [comment]
http://aidancbrady.com/mekanism/download/ or CF

**Comment by simplykarma** [comment]
Thank you so much!
