### ISSUE TITLE
(BUG?) Energy Upgrades no longer reduce operating power costs for Electrolytic Separators

### ISSUE THREAD

**Issue by Vaygrim** [aidancbrady/Mekanism#5040]
#### Issue description:
_The Energy Upgrade no longer reduces the operating power costs for the Electrolytic Separator, it only increases the internal power reserves that the machine has available._

#### Steps to reproduce:
1. _Place down Electrolytic Separator, wire it with power and pipe water into it._
2. _Watch and note operating power cost._
3. _Put a full stack of 8 Energy Upgrades into it, then go back to power panel on the machine and watch as the operating power cost for the machine does NOT decrease._

#### Version (make sure you are on the latest version before reporting):
**Forge:** _14.23.3.2673_
**Mekanism:** _1.12.2-9.4.4.339_
**Other relevant version:** _Mekanism Generators 1.12.2-9.4.4.339_

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by Karmacopper** [comment]
Not so much a bug as a balancing thing. Making hydrogen then burning hydrogen used to be a net gain from what I understand.

**Comment by thiakil** [comment]
They've never been meant to reduce usage in the separator, as ding so would allow for a net energy gain, thus violating thermodynamics.
