### ISSUE TITLE
1.12.2 Issue with JEI

### ISSUE THREAD

**Issue by MrSnakiesFR** [aidancbrady/Mekanism#5042]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
JEI won't show up the recipes of Mekanism metallurgic infuser and other machines

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.3.2678
**Mekanism:** 1.12.2-9.4.9.344 of Mekanism , Generator and Tools
**Other relevant version:** JEI 4.9.1.168 Just Enough Resources 0.8.5.27

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
Fixed in c18501a09958cc30d8e8cf8e2af9c3af38797c81
