### ISSUE TITLE
solar panel don't exist in my minecraft

### ISSUE THREAD

**Issue by gabriel234** [aidancbrady/Mekanism#5049]
#### Issue description:
the crafting and iten don't exist

versions
**Forge:** 13.20.1.1588
**Mekanism:** 9.3.1.305
**minecraft version:** 1.11.2

**Comment by thommy101** [comment]
Do you have Mekanism Generators installed?

**Comment by gabriel234** [comment]
I'm going to download

**Comment by gabriel234** [comment]
thank you
