### ISSUE TITLE
Can't open own Heat Generator

### ISSUE THREAD

**Issue by DanielGRamos** [aidancbrady/Mekanism#5051]
Hey,
So I can´t access my Heat Generator. I am playing on Survival mode (alone) and I can't open or take out my Heat Generator, every time I try to it appears: "[Mekanism] You don't have access.". The other machines from Mekanism are good and I have access to all of them but I can't open Heat Generator.

Forge:  1.12.2-forge1.12.2-14.23.3.2678
Mekanism-1.12.2-9.4.8.343
MekanismGenerators-1.12.2-9.4.8.343
MekanismTools-1.12.2-9.4.8.343
Thanks ^^

**Comment by thiakil** [comment]
How was it placed? Did someone else give you the item? If you had placed it your UUID would be attached.

**Comment by DanielGRamos** [comment]
I placed it myself. I am playing Singleplayer no one else is playing. I just noticed that I couldn't open when I tried to change it from place.
Still cant open it :(

**Comment by thiakil** [comment]
Hmm, you might have to try breaking it in creative or using an NBT editor or World editor

it's possible something caused an error when placing

**Comment by Gskartwii** [comment]
I'm having the same issue. I suspect it's related to changing my in-game name.
