### ISSUE TITLE
Can't build a Heat Generator

### ISSUE THREAD

**Issue by soundasleep** [aidancbrady/Mekanism#5053]
#### Issue description:

According to [the Getting Started tutorial](http://wiki.aidancbrady.com/wiki/Tutorials/Getting_Started), the first thing I should be able to create is the [Heat Generator](http://wiki.aidancbrady.com/wiki/Heat_Generator).

I have all the parts, but I can't create it.

![2018-05-16_17 49 59](https://user-images.githubusercontent.com/3889656/40098854-ac8449de-5931-11e8-86f4-f3d7416613a7.png)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.3.2689
**Mekanism:**  1.12.2-9.4.10.345
**Other relevant version:** Absolutely zero other mods installed. Installed with the Twitch client.

**Comment by soundasleep** [comment]
Here's the latest log if that helps.
[latest.log](https://github.com/aidancbrady/Mekanism/files/2007669/latest.log)

**Comment by soundasleep** [comment]
I installed JEI and Heat Generator isn't even listed as one of the possible items. (?!?)

**Comment by thommy101** [comment]
Do you have Mekanism Generators installed?

**Comment by soundasleep** [comment]
That worked. I didn't know I had to install that :>

**Comment by OwenJF** [comment]
Oh god, are there more extra mods that I need to know?
