### ISSUE TITLE
Sliver and lead dust smelting recipes register after Crafttweaker scripts

### ISSUE THREAD

**Issue by Cyther1** [aidancbrady/Mekanism#5057]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
The recipes for smelting lead and silver dust to ingots are assigned after Crafttweaker scripts are loaded. This is problematic for packs that want to gate or change certain ore processing.

#### Steps to reproduce:
1. Have Mekanism+Crafttweaker
2. Remove Lead or Silver ingot recipes from furnace in script
3. Witness failure for specific Mekanism recipes

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.3.2698
**Mekanism:** 9.4.10.345
**Other relevant version:** Crafttweaker 4.1.8

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

not relevant

**Comment by thiakil** [comment]
Please post minimal script that illustrates the problem, and explain what "failure for specific Mekanism recipes" means *exactly*

**Comment by Cyther1** [comment]
furnace.remove(<ore:dustLead>);
furnace.remove(<dustSilver>);

The furnace recipe for Lead and Silver Dust to ingots will still be there. The results are the same if you use the specific item instead of their oredicts.
