### ISSUE TITLE
[1.12.2] Strange behavior of digital miner

### ISSUE THREAD

**Issue by Sanofus** [aidancbrady/Mekanism#5062]
Forge. 2701
Mekanism 1.12.2-9.4.10.345

The digital miner changed to bounding blocks and can't be mined after that. I have to replace it in creative mode.   

![2018-05-24_18 58 32](https://user-images.githubusercontent.com/26455012/40530214-2a9fab70-5ff8-11e8-9bbb-35116e7abc74.png)

**Comment by Sanofus** [comment]
Hand and pickaxe did not work. The digital miner converted before I had tried to mine it. And this happens at the same postion again every time I place it there.

**Comment by thiakil** [comment]
It does not "convert" to anything. A digital miner is a 3x3x3 multi block. 1 digital miner block, 8 bounding boxes.

If a pickaxe breaking it does not work then it is likely a server or other mod issue. Breaking a bounding box will break the main structure.

**Comment by Sanofus** [comment]
But normally it is shown as digital miner and not bounding block in WAILA. How can I find out which mod causes this behavior?

**Comment by thiakil** [comment]
Remove mods until it no longer happens if you're sure that was the original behaviour.

Also be sure you're not actually using TOP, as it may do things differently.

**Comment by Sanofus** [comment]
That was HWYLA.

It always happens if a place it on blocks of Underground Biomes.
