### ISSUE TITLE
Generator Crash

### ISSUE THREAD

**Issue by ARoom555** [aidancbrady/Mekanism#5064]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Everytime I place a generator, the game crashes. But it used to not do that. It seems it is happening because minecraft can't find this dropbox file - https://dl.dropbox.com/u/90411166/Mod%20Versions/Mekanism.txt.

(reading other issues didn't help me, there are no information how to fix it)
#### Steps to reproduce:
1. start minecraft
2. load any world
3. place a generator

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.7.10-10.13.4.1558 (universal)
**Mekanism:** 1.7.10-9.1.0.281 (+mekanism-mod-generators-1.7.10)
**Other relevant version:** 
(I'm not on the latest version, because other mods I have aren't compatible with higher minecraft versions)
#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
[crash.txt](https://github.com/aidancbrady/Mekanism/files/2042544/crash.txt)
#

**Comment by thiakil** [comment]
Update Mekanism.

**Comment by ARoom555** [comment]
I already have latest version for 1.7.10

**Comment by thiakil** [comment]
281 latest is not

**Comment by ARoom555** [comment]
which then

**Comment by ARoom555** [comment]
because i cant find higher for 1.7.10

**Comment by ARoom555** [comment]
could you please send me a link for it?

**Comment by thiakil** [comment]
https://minecraft.curseforge.com/projects/mekanism/files/2475797

it appears it didnt make it to aidan's website
