### ISSUE TITLE
BC cable not work with Mekanism and mekanisme cable not work with bc

### ISSUE THREAD

**Issue by croziors** [aidancbrady/Mekanism#5068]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
BC cable not work with Mekanism and mekanisme cable not work with bc

#### Version (make sure you are on the latest version before reporting):
**Forge:**  1.12.2 - 14.23.4.2705
**Mekanism:* last version 
 Mekanism-1.12.2-9.4.10.345.jar

**Other relevant version:** 
BuildCraft 7.99.17

**Comment by thiakil** [comment]
what is "buildcraft cable"?

If you refer to the BC joule energy type, support is not planned at this stage and as far as I can find never has been (MC1.7 and newer used RF with mj being display only)

**Comment by croziors** [comment]
how connect quarry with wind turbine ? it s not possible

**Comment by thiakil** [comment]
Buildcraft is mechanical power, Mekanism is electrical power. Use Buildcraft engines
