### ISSUE TITLE
Crash when clicking on the item in JEI looking for the recipe.

### ISSUE THREAD

**Issue by F34RxPredator** [aidancbrady/Mekanism#5069]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When I clicked on the induction cell in JEI it crashed the pack to the launcher, I don't know if this is a crash due to another mod interfering or not, but seems to always happen when I click on the block in JEI. 

#### Steps to reproduce:
1.Search Induction Cell In JEI
2.Click To View The Recipe
3.Then Crash

#### Version (make sure you are on the latest version before reporting):
**Forge:*14.23.4.2705* 
**Mekanism:*1.12-9.4.10.345* 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/DsWdq6ww

**Comment by MinecraftArchive** [comment]
Also note it not just that its the entire Mekanism Mod, and click on the Mekanism creative tab crashes it too

**Comment by F34RxPredator** [comment]
this could be the same issue as masterbuilder was having also as project red is in the pack

**Comment by F34RxPredator** [comment]
I have also posted the issue to project red found here https://github.com/MrTJP/ProjectRed/issues/1311

**Comment by TheCyberKing** [comment]
Mechanism is not compatible with Project Red - Mechanical. I had the same issue and fixed it by removing that mod.

**Comment by thiakil** [comment]
duplicate of #5067 technically
