### ISSUE TITLE
Solar Generators Not Showing Up

### ISSUE THREAD

**Issue by captincreeper1** [aidancbrady/Mekanism#5074]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I have a modpack with Mekanism in it and i cannot seem to find the advanced solar generators to create a thermal distillery. 

#### Steps to reproduce:
1. Download this: https://www.dropbox.com/s/4cirl82f64w9dhu/Ben%27s%20Server%20Pack-2.2.zip?dl=0
2.Import in Twitch Mod Packs
3. Run and NEI Search "Advanced Solar Generator" or any Solar Panel / Generator from Mekanism

#### Version (make sure you are on the latest version before reporting):
**Forge:** .1614
**Mekanism:** 9.1.1.1031
**Other relevant version:** 1.7.10 MC

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
- list your mods, not a download
- ensure you have Mekanism Generators
