### ISSUE TITLE
Heat Generator Missing

### ISSUE THREAD

**Issue by SicNasty** [aidancbrady/Mekanism#5080]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Heat generator and recipe missing from build

#### Steps to reproduce:
1. searched in creative
2. searched in NEI
3. tried building via old recipe config to see if it would show in crafting

#### Version (make sure you are on the latest version before reporting):
**Forge:14.23.4.2707** 
**Mekanism:9.4.10** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thommy101** [comment]
Do you have Mekanism Generators installed?

**Comment by SicNasty** [comment]
I didn't see it on the mekanism page, I only saw the core mekanism .jar, and assumed that everything was included, where is the generator download?

**Comment by thommy101** [comment]
Mekanism Generators is a separate mod on curse

https://minecraft.curseforge.com/projects/mekanism-generators
