### ISSUE TITLE
Quantum Entangloporter into Thermal Tower Crash

### ISSUE THREAD

**Issue by MarshTheBacca** [aidancbrady/Mekanism#5089]
#### Issue description:
I'm not sure if this is Mekanism's fault, but I thought I'd just report it just in case.
I shift clicked a Quantum Entangloporter by accident when I had the Thermal Tower Controller UI open, and then my game crashed. I've tried it 3 more times and it consistently crashes.

#### Steps to reproduce:
1. Open an 18 block tall Thermal Evaporation Tower
2. Have a Quantum Entangloporter in your inventory
3. Shift + Click the Quantum Entangloporter

#### Version (make sure you are on the latest version before reporting):
**Forge:**                            forge-1.12.2-14.23.4.2705-universal
**Mekanism:**                     Mekanism-1.12.2-9.4.11.346, MekanismGenerators-1.12.2-9.4.11.346, 
                                             MekanismTools-1.12.2-9.4.11.346
**Other relevant version:**  Minecraft 1.12.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
Crash Report: https://pastebin.com/gTYaEWdy

**Comment by MarshTheBacca** [comment]
I just tried it again with the latest version as of 16/06/2018: Mekanism-1.12.2-9.4.13.349
                                                                                               MekanismGenerators-1.12.2-9.4.13.349
                                                                                               MekanismTools-1.12.2-9.4.13.349

**Comment by thiakil** [comment]
Yup that's 100% us
