### ISSUE TITLE
Mechanical pipe uncraftable

### ISSUE THREAD

**Issue by mundik** [aidancbrady/Mekanism#5094]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Mechanical pipes (all tiers) don´t have crafting recipe. They are shown in JEI, but you cannot craft them. 

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:**  1.12.2 14.23.2.2611
**Mekanism:** 1.12.2 9.4.13.349
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
That's something to do with your modpack, I'd bet. Otherwise gonna need more info about your setup.
