### ISSUE TITLE
Heat generation

### ISSUE THREAD

**Issue by Treep3r** [aidancbrady/Mekanism#5097]
So, I've been playing with Mekanism for a bit now, and I really think the boiler is pretty much useless. Well, not the boiler itself, but rather the ways of generating heat to power it. 
The boiler UI tells you that it's able to generate a very large amount of steam (even the smallest possible boiler). However in order to do so you would need a ridiculous amount of fuelwood heaters (resistive heaters would be inefficient) and some way to fuel them. 
The amount of resources you need is tremendous and it's really not worth it, considering that you could easily just build a gas burning generator setup with ethylene. You would need about 73 fuelwood heaters to produce enough steam to have the same generation rate as a gas burning generator. (gas burning ~8kRf/t (minus <500Rf/t for the setup) vs. fuelwood heater ~110Rf/t).
I think in order to make the boiler valuable, the gas burning generator should be switched from generating energy directly to generating heat only. <del>This would not only make it more realistic</del> **Well ok no actually there are gas turbines that work like that, my mistake** ...but also balance the gas burning generator a bit better (it's kinda op right now if you can automate wheat).

**Comment by thiakil** [comment]
#5021 #4983 #4147
