### ISSUE TITLE
CraftTweaker cannot fined a mekanism recipe 

### ISSUE THREAD

**Issue by OpticalDust** [aidancbrady/Mekanism#5098]
When I used mods.mekanism.crusher.removeRecipe(<thermalfoundation:material:128>, <mekanism:dust:3>); to remove thermal copper ingot from making mekaism copper dust in the crusher. Craft tweaker said that there is no recipe to remove when JEI shows that there is. I tested this recipe to make sure that it was not a JEI bug and the recipe dose work. 

Forge 14.23.4.2709  
Mekanism 1.12.2-9.4.13.349
CraftTweaker2-1.12-4.1.8

**Comment by OpticalDust** [comment]
re-open

**Comment by thiakil** [comment]
All Mekanism added recipes are added at roughly the same time, so are you sure the meta values are correct?

**Comment by OpticalDust** [comment]
I think so because I have used thermalfoundation:material:128 to remove copper ingot from JEI and mekanism:dust:3 should be mekanism copper dust if I'm right.

**Comment by thiakil** [comment]
Swap the parameters. Now that I think about it the output usually comes first as per craft tweaker convention

**Comment by OpticalDust** [comment]
So is it something on my side or is it a mod issues?

**Comment by OpticalDust** [comment]
I changed it so that the output is first and the input is last. It now works thanks for your help, hope I did not waste much of your time.
