### ISSUE TITLE
Crushed Mekanism-1.12.2-9.4.13.349

### ISSUE THREAD

**Issue by sirohigan** [aidancbrady/Mekanism#5101]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When accessing the boiler, it crashed after a little freezing.

#### Steps to reproduce:
1.I connected a boiler to the immersivetech turbine.
2.Logged out
3.Into the world.
4.Accessed the boiler.
5.Crushed.

#### Version (make sure you are on the latest version before reporting):
**Forge:1.12.2-forge1.12.2-14.23.4.2708
**Mekanism:Mekanism-1.12.2-9.4.13.349
**Other relevant version:MekanismGenerators-1.12.2-9.4.13.349
　　ImmersiveEngineering-0.12-82
　　immersivetech-1.12-1.3.10
　　Aroma1997Core-1.12.2-2.0.0.0.b155
　　Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b77
　　OptiFine_1.12.2_HD_U_D3

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://gist.github.com/sirohigan/ed8f1b9914e615aa4207699772b8f557

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
- This exception is not possible in the current version
- Your filename says `9.4.13.349` but the crash report says `9.4.11`

Please download a clean version and try again, as your install is highly suspicious.
