### ISSUE TITLE
TileEntityBasicBlock causes incompatibility

### ISSUE THREAD

**Issue by dav20011** [aidancbrady/Mekanism#5104]
TileEntityBasicBlock updates neighbouring blocks during the chunk loading process by calling markDirty(). This may happen before the server is running and therefore may cause errors in other mods.

For example this results in XNet networks to not load correctly as described [here](https://github.com/McJtyMods/XNet/issues/283).

**Comment by StellarPatois** [comment]
Just wanted to +1 this. Causing issues using Xnet in the Enigmatica 2 modpack.

**Comment by DanagaMoose** [comment]
Any chance on getting the call removed and a new release moved out. This has disabled a large server with some complicated Xnet that I am a part of and we would love to get back to using both Mekanism as well as Xnet
