### ISSUE TITLE
Mekanism/AE2/Astral Cardboard box interaction. 

### ISSUE THREAD

**Issue by thundR** [aidancbrady/Mekanism#5106]
#### Issue description:
Given a cardboard box placed into an AE system, unusual behavior occurs. To see an example of this behavior and some discussion related to the issue, refer to the issue on[ AE2's tracker](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3589). Also going to link in [AS 1.9 megathread](https://github.com/HellFirePvP/AstralSorcery/issues/762).

#### Steps to reproduce:
1. Place a cardboard box with a vanilla blaze spawner into an AE2 system, with Astral Sorcery installed. 
2. Try to remove the box

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2705
**Mekanism:** 9.4.13.349
**Other relevant version:** MC: 1.12.2, AS 1.9.2 (fscan confirmed on AS 1.9.3), AE2 rv6-alpha-1
No log relevant

**Comment by thiakil** [comment]
Based on fscan's analysis that's something for AS to fix. A capability should not depend solely on `getMaxStacksize`

It's perfectly valid behaviour as far as I'm aware for `getMaxStackSize` to change based on nbt as far as I know.

**Comment by fscan** [comment]
I'm not sure its valid to change a Item property after the creation of the ItemStack. An easy fix on your side would be just to use the exiting meta for it.

**Comment by thiakil** [comment]
The javadoc states `This is a ItemStack (and thus NBT) sensitive version of Item.getItemStackLimit()`

Nbt changes == you *cannot* make any prior assumptions

**Comment by ihastunes** [comment]
a temporary fix i found is to extract the cardboard boxes is use an export bus a fuzzy card with a cardboard box (box has to have a block in it)

**Comment by Merrit** [comment]
> 
> 
> a temporary fix i found is to extract the cardboard boxes is use an export bus a fuzzy card with a cardboard box (box has to have a block in it)

I had this same issue, and your workaround helped. Thank you :)
