### ISSUE TITLE
Coal Ore Duplication

### ISSUE THREAD

**Issue by FallenEagle1** [aidancbrady/Mekanism#5107]
#### Issue description:

Noticed that this was brought up before, but it is still a Mekanism issue. There are mods that allow reliably 6.5 coal from an ore (Integrated Dynamics) up to 8 (Industrial Wires) and a number of others that give 4.
This is an issue, as a number of people are using this dupe to make a continuous cycle and using the extras to make diamonds. Every modpack shouldn't have to change this recipe when it could be changed once and in one spot.

A solution to this would be to simply change the amount of coal needed to make the ore, such as 8 coal per ore.

**Comment by thiakil** [comment]
That just leads to things like the RF inflation. We'd need to up the base amount our machines give from coal ore 'just because mod X does it'

**Comment by FallenEagle1** [comment]
I'm not saying up the amount that the machines give from coal, I'm saying up the amount it takes. Although looking through the code, I can see why that came up, it looks like the combiner looks at the ingredient list to determine how much of the ingredient to have it use. Not sure how feasible it would be, but have the code look for the recipe that gives the max coal, or goes that more run into issues of what recipes are currently loaded at that point? 
 At the very least, would it be something to have an override where it looks at a config file to determine if an override is necessary? Although that's getting back to modpacks having to change it with scripts. This machine is an interesting case since it's basically the only way that you can turn materials back into ores.

**Comment by thiakil** [comment]
It would mean upping it because all the other recipes are based on being juuuuuust below what we give from the opposite conversion.

Inter-mod balance is 100% on pack authors.

**Comment by themechman** [comment]
@thiakil I think FallenEagle1 is refering to is using the Combiner machine to make the ore from 3 coal and 1 cob.
Since some mods like Thermal, make 6 coal per ore, and easily you could automate this process with just three machines. Your only expense to run is cob (unless you have Thermal installed and then its 50% profit).

I also noticed that to make a unit of gold ore, you need 8 pieces of dust and 1 cob. Simply increasing the requirement of 8 coal + 1 cob would null this infinite power scenario.

**Comment by thiakil** [comment]
I know exactly what they mean. Like I said, if you have *another* mod which gives you more coal from the ore than we do, *it is on you to fix that with CraftTweaker*

**Comment by FallenEagle1** [comment]
Since this was from so long ago, I decided it wasn't worth the hassle and the recipes were just straight up removed from the combiner. Not worth sifting through ore recipes when players are just setting up these loops and they just lag things out. Combiner recipes removed and it fixes the issue.
