### ISSUE TITLE
java.lang.ClassCastException with Forestry

### ISSUE THREAD

**Issue by fcpwiz** [aidancbrady/Mekanism#5108]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
On occasion, the following is produced in the console thousands of times in a row:

https://gist.github.com/fcpwiz/c451f106d5f7c993ffb1a066e2d0174b

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2705 (1.12.2)
**Mekanism:** 1.12.2-9.4.13.349
**Other relevant version:** SpongeForge: 2705-7.1.0-BETA-3235

**Comment by thiakil** [comment]
One of the positions in the multiblock's list is either invalid, or sponge is somehow giving the wrong TE.

When blocks are broken the list would be recalculated, so something's wonky with your setup.
