### ISSUE TITLE
Game crashing on placing Solar Generator (Modded Tekkit Legends Client) 1.7.10

### ISSUE THREAD

**Issue by TGzProud** [aidancbrady/Mekanism#5109]
#### Issue description:
Hi, I've modded my Tekkit Legends client to my likings and that's why I've put in Mekanism as well as Mekanism Generators. Only I've found quite an annoying early game problem; upon placing a solar generator in the world my entire game crashes and closes. I've tried looking into the crash report but couldn't really find out what's wrong. 
NOTE: I didn't have any problems with placing the Metallurgic Infurser
Also, side question; at the bottom of the crash log it always says that Ender IO found some issues that had nothing to do with this crash, is this even relevant or do you just skip this bit because it's not relevant? Or something else? 

#### Steps to reproduce:
1. Make solar generator (basic one)
2. Place in world
3. Crash.

#### Version (make sure you are on the latest version before reporting):
**Forge: Recommended for 1.7.10 (10.13.4.1558)** 
**Mekanism: Mekanism-1.7.10-9.1.0.281** 
**Mekanism Generators: MekanismGenerators-1.7.10-9.1.1.1031**

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/F3dje2AB

If anything else is relevant, please let me know and I'll provide the missing information as soon as I am able to!

**Comment by thommy101** [comment]
Please use the same versions for mekanism and mekanism generators

**Comment by TGzProud** [comment]
... Silly me, that worked! Thanks!
