### ISSUE TITLE
when Mekanism running on the SpongeForge Server cause Error

### ISSUE THREAD

**Issue by MoeShimaKaze** [aidancbrady/Mekanism#5112]
Error logs:https://pastebin.com/rVKY4XxB
Forge Version:1.12.2-14.23.4.2705
SpongeForge Version:1.12.2-2705-7.1.0-BETA-3291
Mod list:https://pastebin.com/Zsf5A1wL
Plugins List:https://pastebin.com/bfLvYCpr
Mekanism Version:9.4.13.349 for 1.12.2

**Comment by thiakil** [comment]
The function mentioned in the stack loops the player list provided by the server. If it's null by the time it tries to send it there's nothing we can do. If there's a null entry in the list, that's a sponge problem. Not enough info to tell.

Either the player managed to disconnect at just the wrong moment or some internal Forge/Sponge stuff is going wonky.
