### ISSUE TITLE
mekanism1.10

### ISSUE THREAD

**Issue by Rafik2000** [aidancbrady/Mekanism#5115]
i got this issue because of the core mods of dark utilities and minefacori reloaded
[crash-2018-07-16_22.39.51-client.txt](https://github.com/aidancbrady/Mekanism/files/2199215/crash-2018-07-16_22.39.51-client.txt)

**Comment by thiakil** [comment]
No that has nothing to do with those other mods. Same issue as #4957

Set your JVM flags to `-Duser.country=US -Duser.language=en` and then readjust MC language in settings if necessary.
