### ISSUE TITLE
mekanism 1.10.2 with MCmultipart crash

### ISSUE THREAD

**Issue by Rafik2000** [aidancbrady/Mekanism#5116]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
mekanism 1.10.2 with MCmultipart crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[crash-2018-07-17_14.27.32-client.txt](https://github.com/aidancbrady/Mekanism/files/2201445/crash-2018-07-17_14.27.32-client.txt)

**Comment by thiakil** [comment]
Do you even read your crash reports? this is literally the same as the previous one.
