### ISSUE TITLE
Please update the 1.7.10 version

### ISSUE THREAD

**Issue by AtomicWaffle14** [aidancbrady/Mekanism#5118]
The latest 1.7.10 version of Mekanism has some really annoying issues still, and a few bug fixes is all I ask.

1. The evaporation chamber sound is way too loud, and sounds horrible. It has clicking sounds and should just be removed.
2. Machine sounds don't turn off when a player teleports away before it can fade out, resulting in the sound being permanently on until relogging.
3. Thermal cables and heating don't seem to affect the evaporation chamber. This needs to be either implemented properly or removed.

Please release one more final version for 1.7.10 Mekanism implementing these fixes, than you can forget 1.7.10 forever. Leaving the version with obvious bugs is just careless.

**Comment by thiakil** [comment]
Then don't play it on an unsupported version.
