### ISSUE TITLE
[1.7.10] [Mekanism 9.1.0] WorldEdit Issue

### ISSUE THREAD

**Issue by jbdman** [aidancbrady/Mekanism#5119]
#### Steps to reproduce:
1. Make a WE selection including Mekanism conduits.
2. Copy the selection.
3. Paste the selection, and watch it reappear without conduits.

#### Version (make sure you are on the latest version before reporting):
**Forge: 1614 (Thermos)
**Mekanism: 9.1.0 (1.7.10 Unabridged R.14)
**WorldEdit: 6.1

When placing a block where the conduit(s) should have been placed, the following error is logged: https://hastebin.com/juyifezeja.pl

Below is a sample schematic file.  

https://drive.google.com/file/d/1SMUdZcJiLE9bqhMNq0s5mMFhTyVkwiFE/view?usp=sharing

This issue has also been recreated with schematica.

I have also recreated the issue using just Mekanism 9.1.1 and Schematica. I am in the process of installing the absolute latest version, and retesting.

The mod(s) in question function properly using the development version on 1.12.2. I sincerely hope there is a way to fix this functionality. Like the previous poster, I am a proponent for one last update to 1.7.10, but I completely understand if this isn't possible due to API changes or other reasons.

**Comment by thiakil** [comment]
> When using world edit to do any sort of editing in a chunk, or copying and pasting or use schematics

This is not a Mekanism issue as I do not see how we would have control over this.

> When placing a block where the conduit(s) should have been placed, the following error is logged: https://hastebin.com/juyifezeja.pl

That's to do with the multipart lib, not us.

> The mod(s) in question function properly using the development version on 1.12.2. I sincerely hope there is a way to fix this functionality. Like the previous poster, I am a proponent for one last update to 1.7.10, but I completely understand if this isn't possible due to API changes or other reasons.

Nope, its just 100% EOL.
