### ISSUE TITLE
Mekanism Teleporter Crashes Server and Players

### ISSUE THREAD

**Issue by Reliphyte** [aidancbrady/Mekanism#5120]
#### Issue description:
Teleporter crashes entire game in singleplayer and multiplayer. It also crashes anyone who enters the chunk in multiplayer along with the server.

#### Steps to reproduce:
1. Place teleporter block
2. Witness the crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1614 (Server running Thermos)
**Mekanism:** 9.1.1 (1.7.10)
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/MdHPZhkJ

**Comment by thiakil** [comment]
1.7.10 is unsupported, expecially with Thermos
