### ISSUE TITLE
Electrolyzer acts as a fluid and power void when both outputs are set to dump excess

### ISSUE THREAD

**Issue by kkjdroid** [aidancbrady/Mekanism#5125]
**Expected behavior:** When both outputs are set to dump excess, the electrolyzer will produce both until it can no longer output either gas, at which point it will stop running.

**Observed behavior:** When both outputs are set to dump excess and cannot be ejected, the electrolyzer will continually both produce and dump both gases, using thousands of RF/t for no discernible benefit.

**Comment by thiakil** [comment]
No, that's precisely what it is designed to do.
