### ISSUE TITLE
Dimension Teleporter Problem

### ISSUE THREAD

**Issue by Daron122** [aidancbrady/Mekanism#5130]
Whenever I set up a teleportation frequency in another dimension, it works until I quit and rejoin my world. Does anyone know how to fix this, or why this is happening? 
Thanks

**Comment by thiakil** [comment]
Chunkload.

**Comment by thiakil** [comment]
My apologies on this one. Turns out there were still a few gremlins in the chunkload upgrade code, which *should* be resolved now \*crosses fingers\*
