### ISSUE TITLE
Industrial turbine multiblock not registering to form 5x5x8

### ISSUE THREAD

**Issue by SolSavvy** [aidancbrady/Mekanism#5131]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce: *This was built on a Superflat*
1. build a standard 5x5x8 industrial turbine multiblock
2. try to have it form as a multiblock
3. fail

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.2.2611
**Mekanism: 1.12.2-9.4.13.349
**Other relevant version:
                                 Mekanism Tools 1.12.2-9.4.13.349
                                  Mekanism Generators 1.12.2-9.4.13.349

![2018-08-05_11 03 43](https://user-images.githubusercontent.com/27328200/43687211-601ce332-989f-11e8-9487-7df5f9fa2cdd.png)

![2018-08-05_11 04 04](https://user-images.githubusercontent.com/27328200/43687217-6e4f5e58-989f-11e8-83b0-2a43a1d8217c.png)

![2018-08-05_11 04 34](https://user-images.githubusercontent.com/27328200/43687222-73e11b68-989f-11e8-973f-7e896818846c.png)

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thommy101** [comment]
It might just work as a multi block. It doesn't show the connected textures if you don't have CTM installed.

**Comment by thiakil** [comment]
yeah looking at the Thermal towers (that appear to be working?) in the background, you're just missing CTM. Otherwise please post a full mod list.
