### ISSUE TITLE
multi functional sides

### ISSUE THREAD

**Issue by Chupp4-Jo3** [aidancbrady/Mekanism#5134]
Sorry if this was already suggested but I did look and didn't see it anywhere

So EnderIO had this cool feature where there their machines could do Push/Pull as well as the standard array of connection modes which the Thermal Expansion machines now also sport.

I was wondering if it would be possible to add this kind of feature to the Mekanism machines? I imagine the fact that there is more than just in and out on most machines as they have fluid, gas, items, power etc. all supported might make it difficult but at least with things like the metallurgic infuser it would be nice to be able to have one side do both material and the infused items. Especially as there doesn't seem to be any overlap with what you can put in the infusing side and what it can infuse that into.

Just an idea though

**Comment by thiakil** [comment]
Possible, yes. However it was a conscious decision by the main developer.
