### ISSUE TITLE
[SpongeForge 1.10.2.] Destroyed blocks won't fell off

### ISSUE THREAD

**Issue by Jason505** [aidancbrady/Mekanism#5140]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
On our server running latest version of SpongeForge is bug with destroying some blocks from Mekanism (and Forestry), mined blocks won't fell off.

#### Steps to reproduce:
1. Place e.g. Induction Casing
2. Mine it with Pickaxe
3. Sometimes, block won't instantly destroy, for few moments it just stays on its place, and then disappear.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 12.18.3.2511
**Mekanism:** 9.2.4
**Other relevant version:** SpongeForge 2477-5.2.0-BETA-2793

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]
Just one last thing, server is not always running at 20TPS (as it's a modded server with 20+ players) and I think it causes this issue.

EDIT: Blocks are even disappearing when I want to place a block and there is a server lag.

**Comment by thiakil** [comment]
> Just one last thing, server is not always running at 20TPS (as it's a modded server with 20+ players) and I think it causes this issue.

It is.

**Comment by Jason505** [comment]
Wow... So you've basically saying it's our problem? What a support...
Why aren't this machines dropped like other blocks, which dropping is just fine?

**Comment by thiakil** [comment]
You described exactly the desync caused by a server not running at full speed, so yes it is your problem. Plenty of resources just a google search away for diagnosing why the lag exists.

Machine blocks save their data to the item and thus may break only server side.
