### ISSUE TITLE
[Suggestion/issue] Allow Mekanism sounds to interact with other mods' mufflers normally

### ISSUE THREAD

**Issue by dsmall3303** [aidancbrady/Mekanism#5144]
#### Issue description:
Mekanism's machine and generator sounds do not seem to be able to be silenced/muffled by other mods such as Quark's Soundproofing blocks, or by Super Sound Muffler's Super Sound Muffler. Especially after messing with the latter, I noticed that most of the sounds from Mekanism don't seem to be listed, unlike almost every other sound in the game. I realize there is a config option for default sounds, but it would be nice to be able to quiet sounds where you don't want them (for example wind turbines around your base). If that is not possible, then is there a chance for upgrade slots (for Mek's muffling upgrade) to be added to all the machines?

#### Steps to reproduce:
1. Place down wind turbine
2. Place down Soundproofing/Super Sound Muffler
3. Sounds from wind turbine will remain unchanged. Repeat as needed for other machines such as crusher, metallurgic infuser, etc.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.4.2750 
**Mekanism:** 1.12.2-9.4.13.349
**Other relevant version:** 
Behavior happens in both SMP and SSP.
#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
No crash is generated for this issue.

**Comment by thiakil** [comment]
Mekanism has its own sound system for historical reasons I don't quite understand. To use other mods' mufflers they will need to add special support.

**Comment by ParadoxBomb** [comment]
Yeah that's what I'm saying; is there any way to change it on Mek's end so that it doesn't? If that isn't possible, can we get a Mek-internal method to muffle all machines as desired?

**Comment by thiakil** [comment]
> Yeah that's what I'm saying; is there any way to change it on Mek's end so that it doesn't

That being why I said I don't understand it, I don't know. There *are* already sound settings in Mek's settings screen.

**Comment by ParadoxBomb** [comment]
I'm not sure how to explain what I'm asking any clearer. If there is no way to make Mekanism's sound system work with other mods (as appears to be the case), then can you add an upgrade slot restricted to mufflers to all machines that don't have upgrade slots right now? The overall volume adjuster is good, but some sounds get annoying when hearing them in a constant loop (like the wind turbines I mentioned previously)

**Comment by GreatestFool** [comment]
Didn't know that Quark had soundproofing blocks, but I still agree with this. If support could be added for Super Sound Muffler and the like, it'd be grand. Or just sound muffling upgrade slots in everything, that's fine too.
