### ISSUE TITLE
Flamethrowers don't work on Ghasts

### ISSUE THREAD

**Issue by sfxworks** [aidancbrady/Mekanism#5145]
#### Issue description:

D: A player of mine was given a flamethrower and nearly died! Are they fire resitant?

#### Steps to reproduce:
1. Git flamethrower
2. Am for the nose!
3. Oh noes

#### Version (make sure you are on the latest version before reporting):
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-SNAPSHOT-d453c3e
    SpongeForge: 1.12.2-2705-7.1.0-BETA-3206
    Minecraft Forge: 14.23.4.2705
-rwxrwxr--  1 lapitos minecraft  16M Jul 28 00:03 Mekanism-1.12.2-9.4.13.349.jar
-rwxrwxr--  1 lapitos minecraft 332K Jul 28 00:03 MekanismGenerators-1.12.2-9.4.13.349.jar
-rwxrwxr--  1 lapitos minecraft 158K Jul 28 00:03 MekanismTools-1.12.2-9.4.13.349.jar

**Other relevant version:** 
![2018-08-22_22 52 36](https://user-images.githubusercontent.com/5921035/44502145-1688c980-a65e-11e8-9129-540fbe37c275.png)
![2018-08-22_22 52 33](https://user-images.githubusercontent.com/5921035/44502146-1688c980-a65e-11e8-86ca-265ed6ab2445.png)

**Comment by thiakil** [comment]
Probably a vanilla thing where, ya know, nether mobs aren't affected by fire damage...

**Comment by Redd56** [comment]
...
You do realize ghasts dont burn right?

**Comment by sfxworks** [comment]
Nope lol oof sorry

**Comment by Redd56** [comment]
They love to swim in lava as well

**Comment by sfxworks** [comment]
kinky
