### ISSUE TITLE
Re Connection Issue Soon After Removing Water Beside Universal Cable to Get Down from installing Wind Generator

### ISSUE THREAD

**Issue by FriendlySurvival** [aidancbrady/Mekanism#5153]
#### Steps to reproduce:
1.Stack up cables up to 250 meters 
2.Place Cobble Stone for the generator and place in front  
3.Dump water beside a bare cable (not by the cobble or anything) and start going down 
4. Remove the water with the empty bucket 
5. Get all of the way down and stay put for a few minutes 
6. Disconnect and re connect to produce the attached error 
#### Version (make sure you are on the latest version before reporting):
**Forge:1.12.2 ending in 2759
**Mekanism:Latest at the time of writing for this Minecraft version 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: Connection Based Error
See attachment
![screenshot from 2018-09-05 18-05-28](https://user-images.githubusercontent.com/38051855/45174869-eb63b580-b1d9-11e8-9672-ead86223f0fe.png)

**Comment by thiakil** [comment]
That's a server issue, either it dies or there should be an error message in its log.

**Comment by FriendlySurvival** [comment]
All I found was this on my client... 
`net.minecraft.client.multiplayer.GuiConnecting]: Connecting to trinity2.serverblend.com., 25583
[20:14:29] [Server Connector #1/ERROR] [net.minecraft.client.multiplayer.GuiConnecting]: Couldn't connect to server
io.netty.channel.AbstractChannel$AnnotatedConnectException: syscall:getsockopt(..) failed: Connection refused: trinity2.serverblend.com./63.251.42.60:25583
	at io.netty.channel.unix.Socket.finishConnect(..)(Unknown Source) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
Caused by: io.netty.channel.unix.Errors$NativeConnectException: syscall:getsockopt(..) failed: Connection refused
	... 1 more` 
Was it really trying to connect to my very old server "out of no where" after hours of game play on the new one??

**Comment by thiakil** [comment]
> Was it really trying to connect to my very old server "out of no where" after hours of game play on the new one??

That's what the log says. If the timestamp matches.
