### ISSUE TITLE
Ore Excavating Turbine Blade Crash

### ISSUE THREAD

**Issue by NillerMedDild** [aidancbrady/Mekanism#5157]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Original issue: https://github.com/NillerMedDild/Enigmatica2Expert/issues/248
I broke a rotor with 2 turbine blades on it using OreExcavation (it was the bottom rotor of 7 that used to be part of a mekanism turbine if it matters), and my server crashed.

#### Steps to reproduce:
1. Place Rotor
2. Attach turbine blades
3. Break Rotor while holding the Ore Excavation key

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.2-14.23.2751
**Mekanism:** 1.12.2-9.4.13.349
**Other relevant version:** OreExcavation-1.4.129

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/UJg1ez1y

**Comment by Algester** [comment]
same NPE Issue with veinmining the turbine rotors from Stoneblock

https://pastebin.com/Ns3xwBiz

here's my log

**Comment by thiakil** [comment]
Line 161 mentioned in the crashlog is `if(!world.isRemote)`; something that should never be null.

Please report to Ore Excavation
