### ISSUE TITLE
Extreme FPS Issues with Universal Cable

### ISSUE THREAD

**Issue by douglasg14b** [aidancbrady/Mekanism#5160]
#### Issue description:
When using Universal cable in a base, FPS drops for everyone that comes nearby.

Upon removal of all universal cables, FPS is back to normal for anyone that comes near. This seems have been an ongoing issue for a few years::

- https://github.com/aidancbrady/Mekanism/issues/161 (6 Comments. Closed)
- https://github.com/aidancbrady/Mekanism/issues/1762 (71 Comments. Closed)
- https://github.com/aidancbrady/Mekanism/issues/5127 (9 comments. Open)
- https://github.com/aidancbrady/Mekanism/issues/164 (4 Comments. Closed)
- https://www.reddit.com/r/feedthebeast/comments/6485vd/will_unlimited_input_into_mekanism_cables_cause/
- https://www.reddit.com/r/feedthebeast/comments/28mess/mekanism_machines_and_fps_lag/
- 

#### Steps to reproduce:
1. Place a few hundred universal cable in an active base
2. Wach FPS Drop
3. Remove cable and replace with almost any other mods cables
4. Watch FPS drastically improve

Alternatively

1. Load empty world
2. Place 8x8x8 cube of cable and power it
3. Watch FPS suffer
4. Remove cable and replace with other mods cables
5. Notice FPS improve

#### Version:
**Forge:** 14.23.4.2715 
**Mekanism:** 1.12.2-9.4.13.249

**Comment by thiakil** [comment]
> (9 comments. Open)

So why open a new one?

**Comment by douglasg14b** [comment]
@thiakil 

To bring up the information presented in a closed one, and to aggregate the threads in one place.

And to try and bring up a thread where you might not be involved, as you seem to disregard this and many issues out of hand, and you're attitude aroudn this repo is unprofessional, hostile, and non-conducive to a community. 

You're very toxic, and all it breeds it's disdain for the mod and it's maintainers.

**Comment by Jatoxo** [comment]
Investigated the FPS issues which have been getting worse and worse, tuns out it was because we were placing more and more universal cables! They should really be optimized or disabled by default, so many players must be suffering from terrible FPS with no idea that these cables are causing it

**Comment by ErythroCraft** [comment]
https://github.com/juliand665/Dynamic-FPS or https://www.curseforge.com/minecraft/mc-mods/fps-reducer
