### ISSUE TITLE
Server Crash [Mekanism Server Tickloop]

### ISSUE THREAD

**Issue by AgentHani** [aidancbrady/Mekanism#5161]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Mekanism Server tickloop crash?

Server randomly got crashed and it says something about mekanism, 

#### Steps to reproduce:
1. (x)
2. (x)
3. Check the logs

#### Version (make sure you are on the latest version before reporting):
**Forge: 2749 - 1.12.2** 
**Mekanism: 1.12.2-9.4.13.349.jar** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/xVKSdYPU

**Comment by thiakil** [comment]
I dont think that should be possible, you'll want to try without coremods

**Comment by AgentHani** [comment]
> I dont think that should be possible, you'll want to try without coremods

Core mods like? My server keeps crashing everytime with the same error idk why and what could be the reason.. i dont think it really is the core mods? not sure

**Comment by thiakil** [comment]
The core mods are listed in the crash log. I'm not blaming anything at this stage; nothing should be iterating that list while modifying it during a tick loop.

I will have a more detailed look at the error point when back at my normal workstation

**Comment by thiakil** [comment]
Yeah I can't see any place in the erroring code which would be modifying the list while its being looped, so it appears you have something that's doing normal tick things while the tick event is being run, or someone is messing with stuff

**Comment by AgentHani** [comment]
> Yeah I can't see any place in the erroring code which would be modifying the list while its being looped, so it appears you have something that's doing normal tick things while the tick event is being run, or someone is messing with stuff

Yep you're right, i already figured it out.. It was a mod called Sleeping Overhaul and it had a mod dependency called Tickrate changer and that caused the problem with mekanism.. i removed it and its now fixed.. no more crashes :)
