### ISSUE TITLE
[1.12.2] Digital Miner Inventory locked?

### ISSUE THREAD

**Issue by NickelHub** [aidancbrady/Mekanism#5164]
I tried to extract items form the digital miner the way I'm acostumed, but the items were still in. I tried Itemducts, Ender Conduits and the Logistical Transporter. Did I configured something wrong?

Forge: 2755
Mekanism: 1.12.2-9.4.13.349.jar 

![2018-09-22_02 21 03](https://user-images.githubusercontent.com/26455012/45911038-ab721480-be0e-11e8-9825-7003ca9b30f2.png)
![2018-09-22_02 21 51_2](https://user-images.githubusercontent.com/26455012/45911039-ad3bd800-be0e-11e8-874a-bb61dda0a2f6.png)

**Comment by NickelHub** [comment]
Found out, that the port on the back has to be used.

**Comment by thiakil** [comment]
Any of the gold/yellow ports should work afaik
