### ISSUE TITLE
Lack of connected textures

### ISSUE THREAD

**Issue by themechman** [aidancbrady/Mekanism#5165]
#### Issue description:
As of late, I am seeing no connected textures on multiblock structures. This seems to have started in the past few major releases. I dont know if this is an option in config or not.

#### Steps to reproduce:
1. N/A
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.4.2705
**Mekanism:** 1.12.2-9.4.13.349

![2018-09-25_22 06 54](https://user-images.githubusercontent.com/2990361/46053211-d9f23700-c10f-11e8-8c13-d82b0b4ee1f1.png)
![2018-09-25_22 08 02](https://user-images.githubusercontent.com/2990361/46053218-dbbbfa80-c10f-11e8-9545-07fa48e9baff.png)

**Comment by thommy101** [comment]
Do you have the mod CTM? It's a required library for our new connected textures feature

**Comment by themechman** [comment]
Nope! Should be suggested on download site though. Thanks. I'll stuff that in.
