### ISSUE TITLE
Thaumcraft adds  Silver, and Lead Nuggets, but not Ingots. Causes various issues

### ISSUE THREAD

**Issue by PokeMaserJ** [aidancbrady/Mekanism#5167]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Mekanism adds the Ore multiplication for Lead and Silver, but no way to get them / they don't produce 			Ingots. Minor issue. But I thought I'd let you know. 

#### Steps to reproduce:
1. Install Mekanism and Thaumcraft
2. See that there is the Ore multiplication for Lead and Silver, even though there is no way to get them, and they produce nothing
3. Profit?  

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.4.2718
**Mekanism:** Mekanism-1.12.2-9.4.13.349
**Other relevant version:** Thaumcraft-1.12.2-6.1.BETA24

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
"Causes various issues" such as?

**Comment by PokeMaserJ** [comment]
Just that it adds the Ore Multiplication system for Lead and Silver, even though you can't get them, and they produce nothing. Small bug, nothing game breaking

**Comment by thiakil** [comment]
like, it shows a recipe and takes your input and does nothing? (screenshots of the JEI view would help)

**Comment by PokeMaserJ** [comment]
There is no way to get any of the Ore Multiplication steps for Lead and Silver with just Thaumcraft and Mekansim, but they appear in JEI. Also hope these pictures help https://imgur.com/a/yJe44Bn

**Comment by Robijnvogel** [comment]
So what you are saying is that Thaumcraft does add Lead and Silver Clusters, but no way to craft them (and obviously no way to craft them into ingots, because it would depend on other mods' Lead and Silver Ingots for that)?

Wouldn't that just mean they show up in JEI? What exactly is the problem with that?

**Comment by PokeMaserJ** [comment]
Just a minor issue, nothing really game breaking. Probably an extreme edge case, but I thought I'd report it.

**Comment by Robijnvogel** [comment]
If anything could be done about this, it would probably have to be done in Thaumcraft by @Azanor as it is not Mekanism that does this.
The only thing that Mekanism could do is actually adding Lead and Silver ores and ingots.

**Comment by PokeMaserJ** [comment]
I've reported this to Azanor, he said he can't do anything, or it'll break everyone's saves

**Comment by PokeMaserJ** [comment]
Going off on one of the comments on the report I did on Thaumcrafts end, mods in general need to check if there are nugget registered , but not ingots.
