### ISSUE TITLE
Mekanism crash while loading.

### ISSUE THREAD

**Issue by RiptideC27** [aidancbrady/Mekanism#5170]
#### Issue description:
The mod crash while going though the loading phase.
No other mods installed! 

#### Version (make sure you are on the latest version before reporting):
**Forge:14.23.4.2764** 
**Mekanism:1.12.2-9.4.13.349** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/UzjRMgKt

**Comment by schweezey** [comment]
I was able to duplicate the issue. No problems launching with Forge 14.23.4.2763.

**Comment by schweezey** [comment]
Yeah, crash report is similar to yours.

https://pastebin.com/ffPi6mTZ

**Comment by tgstyle** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/5170

**Comment by thommy101** [comment]
Thanks for pointing to the Forge issue @tgstyles!
Should be fixed as of last forge version
