### ISSUE TITLE
mekanism boiler casing: 20ms per tick

### ISSUE THREAD

**Issue by PhanaticD** [aidancbrady/Mekanism#5181]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
boiler casing is way too laggy

warmroast profile: https://gyazo.com/701015b14e33992be4f2fd4af65bea9d
tickprofiler output: https://gyazo.com/350886e068278c20fb0d56db4c74fdd6

#### Steps to reproduce:
1. make a big boiler
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.2-14.23.4.2760
**Mekanism:** 1.12.2-9.4.13.349
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
Not enough info. Post an nps file and reopen
