### ISSUE TITLE
Minecolonies guards can't use Mekanism weapons

### ISSUE THREAD

**Issue by lebanni** [aidancbrady/Mekanism#5188]
Hi, according to Minecolonies developpers, Mekanism weapons would be missing the minecraft "weapon class" that would allow the guards use the Mekanism swords.
They already use some tools like axes, pickaxes and shovels, but not the hoe.

https://github.com/ldtteam/minecolonies/issues/2270

**Comment by thiakil** [comment]
https://github.com/aidancbrady/Mekanism/blob/3e469fb40a2a086527cf14dbe9ba709f708a9bca/src/main/java/mekanism/tools/item/ItemMekanismSword.java#L15

The Swords extend vanilla's `ItemSword`, so they're talking bulldust
