### ISSUE TITLE
Some Machines will be stuck on 1 or 0 of what fluid/gas they have

### ISSUE THREAD

**Issue by TheRealDadbeard** [aidancbrady/Mekanism#5192]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Some machines do not deplete completely

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2772
**Mekanism:** Mekanism-1.12.2-9.4.13.349

**Comment by thiakil** [comment]
Stuck on 1 is not an issue, if the recipe needs > 1 of course its gonna get stuck.

Need a reproduction scenario for getting stuck on 0.

**Comment by TheRealDadbeard** [comment]
Well stuck on one is a big issue when I try to empty a machine to use with another gas, that's where I'm having the most issues. I can't deplete it, it's just stuck somehow. Sometimes on 0.

Bug happened longer than the issue creating so I'll have to look which machines gave me the issue and report back.
