### ISSUE TITLE
Change Factory Descriptions so they don't show up with Tier Installers

### ISSUE THREAD

**Issue by Xevion** [aidancbrady/Mekanism#5198]
When you search `tier installer @mekanism` in JEI, you get all of the Basic through Ultimate Tier Installers **PLUS** the Factories of every type, since they include a description regarding how they work.

Dunno, just a small suggestion; Please make it so that this isn't so. You should get all of the factories when you search `factories` and tier installers when you search `tier installers`.
It's so minor and OCD but it bugs me, personally. Maybe someone else will agree.

---

Modpack: Enigmatica 2: Expert
Mekanism Version: Mekanism 9.4.5
Minecraft Versionn: Minecraft 1.12.2

**Comment by thiakil** [comment]
You can turn off the default search description option in JEI
