### ISSUE TITLE
Quantum Entangloporter Exploding

### ISSUE THREAD

**Issue by NillerMedDild** [aidancbrady/Mekanism#5199]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Quantum Entangloporters explode at random times.
Original issue: https://github.com/NillerMedDild/Enigmatica2Expert/issues/389#issuecomment-439715853

I realize this bug could be impossible to fix because of it's inability to be reproduced, but I thought I'd report it either way.

#### Steps to reproduce:
Cannot be reliably reproduced. 

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.2-14.23.5.2768
**Mekanism:** 1.12.2-9.4.13.349

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
Exploding is an IC2 thing. You're probably putting too much power through it as far as IC2 is concerned

**Comment by NillerMedDild** [comment]
Oh, I didn't know IC2 could affect the machines of other mods like that. Thanks :)
