### ISSUE TITLE
Atomic Disassembler ignores quick leaf decay

### ISSUE THREAD

**Issue by jgeekw** [aidancbrady/Mekanism#5200]
#### Steps to reproduce: include quick leaf decay (by lumien)
1. Set atomic disassembler to vein mine
2. Punch any tree
3. Leaves decay as if no mod is installed

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.5.2770
**Mekanism: 1.12.2-9.4.13.349
**Other relevant version: quick leaf decay v1.2.4

**Comment by thiakil** [comment]
Unless you can tell us what we're missing, that's an issue for QLD. I don't have time to figure out how someone else's mod works.
