### ISSUE TITLE
[1.12.2] invisible items

### ISSUE THREAD

**Issue by TheSnowyChickens** [aidancbrady/Mekanism#5205]
### Issue description:
Items (digital miner as example) are invisible. (only the icon)

#### Steps to reproduce:
1. start the game, I think it is one of the newest Forge versions, because with 2774, all was okay.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2784
**Mekanism:** 9.4.13.349
**Other relevant version:** no Optifine, but betterfps & foamfix 

![grafik](https://user-images.githubusercontent.com/29357962/49032753-b00bce00-f1ad-11e8-8c2e-e149e1406222.png)

**Comment by Dulana57** [comment]
I have this issue aswell

**Comment by RiptideC27** [comment]
Same here with that version of forge

**Comment by RiptideC27** [comment]
![image](https://user-images.githubusercontent.com/28847909/49057863-68ab2f00-f1f9-11e8-9f0f-e2927cd1c3b4.png)

**Comment by RiptideC27** [comment]
![image](https://user-images.githubusercontent.com/28847909/49058061-3a7a1f00-f1fa-11e8-9649-49c84eb00cf1.png)

**Comment by thiakil** [comment]
Yes, Mekanism's rendering isn't the safest. Rewrite is planned but is not a simple task.

Try without BetterFPS. I don't think Foamfix would interfere, but always possible.

**Comment by RiptideC27** [comment]
Hmm I don't have BetterFPS, Foamfix or Optifine in my pack. Just a quick question is the rewrite going to happen for the 1.13 versions of the mod? I know that forge and a lot of mod devs are rewriting their mods.

**Comment by Ciflire** [comment]
I had the same issue then a moved to forge 1.12.2-2768 and my textures items got back

**Comment by thiakil** [comment]
Looking at the changelogs there were some recent rendering changes in Forge, which probably breaks the hacky rendering.

The rendering rewrite will happen when it happens. *shrug*

**Comment by pupnewfster** [comment]
Setting `allowEmissiveItems` in forge.cfg to false works as a workaround to make the items visible again.

**Comment by Fearion** [comment]
> 
> 
> Setting `allowEmissiveItems` in forge.cfg to false works as a workaround to make the items visible again.

This does not seem to work for me, still no textures. Is there an other solution ?

**Comment by thiakil** [comment]
This should be fixed in the latest build. Still a flimsy hack though

**Comment by wldr8** [comment]
![2019-12-28_14 38 23](https://user-images.githubusercontent.com/59304041/71540182-21561b80-2982-11ea-9b07-bd4ca836a050.png)

**Comment by nddragoon** [comment]
Sorry for the necro but this seems to be happening in 1.16 and the forge config system changed and `allowEmissiveItems` doesn't exist anymore

**Comment by thiakil** [comment]
Sorry means nothing if you just barrel ahead and do it anyway.

Your issue is not related. Remove/update optifine and if it still occurs open a new issue.
