### ISSUE TITLE
Mekanism corrupting world

### ISSUE THREAD

**Issue by EuFuchs** [aidancbrady/Mekanism#5207]
#### Issue description: 
After adding Mekanism into my modpack and loading an existing world the whole world gets corrupted; totaly unstable and laggy, most blocks have been changed into other blocks

note: newly generated worlds work fine

EDIT: https://gyazo.com/de3a82d01525b1612db7727b823e67d2 this is what happens to my world once i install mekanism

#### Version 
**Forge:** 14.23.5.2772
**Mekanism:** 9.4.13.349
can provide complete modlist if necessary

would appreciate any help, im out of ideas

**Comment by thiakil** [comment]
yeah, the log that message mentions? gonna need to see it.

**Comment by EuFuchs** [comment]
[latest.log](https://github.com/aidancbrady/Mekanism/files/2634814/latest.log)
wasnt able the answer, sry ^^ took some time but finaly managed to find that damn log i guess

**Comment by thiakil** [comment]
```
20:57:27] [Chunk Batcher 14/ERROR] [CodeChickenLib]: 
 CCL has caught an exception whilst rendering a block
  BlockPos:      x:-6351, y:14, z:1749
  Block Class:   class com.carpentersblocks.block.BlockCarpentersPressurePlate
  Registry Name: carpentersblocks:carpenters_pressure_plate
  Metadata:      0
  State:         carpentersblocks:carpenters_pressure_plate[facing=down]
 Tile at position
  Tile Class:    null
  Tile Id:       null
  Tile NBT:      null
```

Seems Carpenter's Block are your problem
