### ISSUE TITLE
Logistical Sorter By "name like"

### ISSUE THREAD

**Issue by AnibalDuarte** [aidancbrady/Mekanism#5210]
#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2768
**Mekanism:** 1.12.2-9.4.12.349
**Other relevant version:** Minecraft 1.12.2

The scenario: I'm and some friends are been playing for a while on a private server, in a "communist-like society" where every man had their specific job. My job is to build the easiest auto-classification chest system to people who farm can just throw everything on a single chest and things should go to their specific spaces (saving those who need to be used/transformed on our factory, they will be sent to there).

I'm trying for a while to use Logistical Sorters to redirect things using their names, but I have no success on the task. 

I've see another closed issues saying that you can use the block name on OreDict, but seems isn't working everytime.

I've tryed to use the Mod ID filter as well, and it's only filtering by the mod name (the word before the **:** in the Item ID), not by the Item ID on the MOD (as I presume it should work), and it's not fully working. For instance, I have Thinkers Construct installed, and if I try to filter by the Mod ID ( tconstruct ) itsn't filtering nothing, even if I use only a part of the word with asteriscs ( like **\*construc\*** ).

With this "limitation" I'm actually need to create an ItemStack filter to each item, wich is kind of hard since many times I haven't the item itself on hands and need to use one "Lost and Found" chest to get those unclassified items on my system.

I believe that's a new filter using "name like" system would be very usefull, since we'll no need to have the items on hand to create filters anymore. Then I can just program to send "\*stuff\*" to thier correct chest.

**Comment by thiakil** [comment]
For filters that don't seem to work like they should, please show setup (screenshots would help) along with the item that's not working in a minimal test case.

Filtering by name is problematic. I think its been requested before and rejected.
