### ISSUE TITLE
Mekanism Blocks/items invisible

### ISSUE THREAD

**Issue by Xetapro12** [aidancbrady/Mekanism#5216]
#### Issue description:
Mekanism Blocks/items invisible
like this :/ I dont understand why!
https://i.imgur.com/r8mbHdl.png

#### Version (make sure you are on the latest version before reporting):
Forge:14.23.5.2784
Mekanism:1.12.2-9.4.13.349

**Comment by Xetapro12** [comment]
Found out need to set Allow Emmisive Item Rendering from true to false 
-Closed

**Comment by thiakil** [comment]
Oops, sorry for spam. Dupe of / tracking on #5205
