### ISSUE TITLE
Mekanism Teleporter

### ISSUE THREAD

**Issue by Cratios** [aidancbrady/Mekanism#5224]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

Minecraft 1.12.2: When i teleport from Nether to  Overworld ok in an other Dimension i am sometimes inviseble for other Players in Game and on JourneyMap. 
Also the FTBUtilities bar for changing Weather or changing Gamemode desappears. I have to made an relogg to solce the Problem 

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by jammehcow** [comment]
Consider updating that bug report with the appropriate details (FML version, Mekanism version, steps etc..). Makes it easier for developers :)
