### ISSUE TITLE
[1.12.2] Some models are missing

### ISSUE THREAD

**Issue by Cazadorsniper** [aidancbrady/Mekanism#5225]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Some item/block models are gone, they are invisible so no missing texture error in JEI and the creative tab.
Example: Digital Miner, Flamethrower, and jetpack.

#### Steps to reproduce:
1. Install Mekanism and JEI

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2795
**Mekanism:** 1.12.2-9.4.13.349
**Other relevant version:** JEI_1.12.2-4.14.3.238

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by scotty9090** [comment]
Getting the same thing with both the Atomic Deconstructor and the Digital Miner.  The Digital Miner is fine if placed in world, but invisible in an inventory slot.

**Comment by pupnewfster** [comment]
duplicate of #5205

**Comment by Cazadorsniper** [comment]
Alright closing this duplicate.
