### ISSUE TITLE
EnergyNetwork performance issue

### ISSUE THREAD

**Issue by Sir-Will** [aidancbrady/Mekanism#5226]
![](https://i.imgur.com/EDm3H6U.jpg)

Mekanism-1.12.2-9.4.13.349
forge-1.12.2-14.23.5.2768-universal

**Comment by Sir-Will** [comment]
Looking at the code here: https://github.com/aidancbrady/Mekanism/blob/1.12/src/main/java/mekanism/common/transmitters/grid/EnergyNetwork.java#L224
the max amount of entries seems to be 6 where the average is probably 2-3, so List should be faster here but there might be a different issue here.

**Comment by Sir-Will** [comment]
![](https://i.imgur.com/JPIOyRx.jpg)

**Comment by thiakil** [comment]
your highlighted line there is `0.111340206185567ms`  per call. No way to optimise that.
