### ISSUE TITLE
Mechanical pipes not transparent

### ISSUE THREAD

**Issue by BCI1999** [aidancbrady/Mekanism#5228]
Hi all,
Recently played a bit with Mekanism and I noticed that the mechanical pipes are not transparent, so they are not showing the fluid that they're transporting. I looked it up but I can't find why this is happening.
I'm playing mekanism in the Modern Skyblock 3 modpack, but other people playing an earlier version of this modpack don't have this issue.
I'm using Mekansim 9.4.13 and Forge version 8.0.99.99

Here's a screenshot of the machanical pipes
![image](https://user-images.githubusercontent.com/40671831/50539235-24ef7080-0b7d-11e9-880d-80486a423661.png)

**Comment by thiakil** [comment]
There's a setting for opaque rendering.
