### ISSUE TITLE
Wind generator is a tps demon

### ISSUE THREAD

**Issue by 2slow4gaming** [aidancbrady/Mekanism#5240]
I am playing the modpack enigmatic 2 on a server. But here comes the problem and I don't really know anything about this so I don't know how to fix it. Every time I place down a wind generator the server starts lagging as hell, but when I destroy it again the server immediately stops lagging and I don't know what i could do to do to fix it.

~2slow

**Comment by thiakil** [comment]
A tick profiler of some sort would help

**Comment by thiakil** [comment]
Can't reproduce by just placing a wind generator, so going to need a tick profiler file to fix.
