### ISSUE TITLE
Enrichment Chamber won't accept certus/fluix crystal seeds

### ISSUE THREAD

**Issue by AlexPoulsen** [aidancbrady/Mekanism#5241]
I'm trying to use Mekanism's Enrichment Chamber to grow Certus/Fluix in a processing chain. First I tried having the Thermal Expansion Sequential Fabricator auto-export directly into it without anything in between. That didn't work so I tried with itemducts. Still nope. Tried with Logistical Transporters, and still nope. Tried with a vanilla hopper, and nope. I tried reconfiguring the input to a different side because maybe it needed to be updated or something, and then I tried all those again with different side inputs. Again, didn't work. I ended up changing it out with the standard way of growing pure Certus/Fluix, which causes more lag and takes more time, maybe takes more energy idk. It very well might be an issue with one of the other mods in my custom modpack but I haven't tested to see what it could be yet.

**Forge:** 14.23.5.2768 (current recommended version)
**Mekanism:** Mekanism-1.12.2-9.4.13.349.jar
**Mod List:** https://hastebin.com/yubefomuca.md

**Comment by AlexPoulsen** [comment]
tested with other machines and with mekanism logistical transporters again. seems to only be the enrichment chamber that is having issues.

**Comment by AlexPoulsen** [comment]
actually, it only seems to be with the crystal seeds

**Comment by thiakil** [comment]
Are they partially grown seeds? Could you please let me know the AE2 version, seems your hastebin expired

**Comment by AlexPoulsen** [comment]
appliedenergistics2-rv6-stable-3
