### ISSUE TITLE
Mekanism Charging pad won't recognize Ic2 jetpack with chestplate

### ISSUE THREAD

**Issue by GlitchOG** [aidancbrady/Mekanism#5242]
Forge 2795
Ic2 Ex112
Mekanism 349

So basically mekanism will recognize and charge the electric jetpack from ic2 , but if i use the jetpack attachment plate from Ic2 and combine any chestplate then the charge pad won't recognize it as a chargeable item.

**Comment by Fireztonez** [comment]
This is possibly because IC2 use custom EU and not RF, like most mods does... The IC2 EU energy doesn't work with RF, unless you convert or use something who it made to work with both energy systems...

**Comment by GlitchOG** [comment]
you are wrong , i connect mekanism cables to any ic2 machines and they work fine , same if i connect any other rf mod to them. the electric jetpack charges fine with the charge pad just not when i combine it with a chestplate , probably because of an nbt tag.

**Comment by thiakil** [comment]
Though I'm not familiar with IC2, I would assume this is because the item itself does not implement `IElectricItem`, which the charge pad currently checks for.
