### ISSUE TITLE
Can't make the personal chest for the robit

### ISSUE THREAD

**Issue by Bartjuhh83** [aidancbrady/Mekanism#5243]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
i try to make the digital miner which requires the robit as a component but when i try to build the personal chest which is used for the robit then it takes the items but i dont get the personal chest

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
Forge: 14.23.5.2796 
Mekanism: 1.12.2-9.4.13.349
Other relevant version: modpack stoneblock2 1.0.1

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by rockbanddude** [comment]
I'm pretty sure it's just a texture error. The energy cubes, digital miner, and a few other blocks and items are invisible in the inventory.
