### ISSUE TITLE
[Issue4974] Mekanism generator's mod log spam in a similar way to previous issues

### ISSUE THREAD

**Issue by alxcool** [aidancbrady/Mekanism#5245]
https://github.com/aidancbrady/Mekanism/issues/4974

#### Issue description:
I'm not experiencing lagg at all, and I really enjoy your mods! I just want to share this log file in hope the spam line could help to solve problems.

I've connected a set up of many mekanism machines in order to obtain the 5x ore bonus, while only using mekanism's pipes. Note there is no chunk loading upgrade or system in proximity to my base.

As example, my thermal evaporator tower is offline since both of its tanks are full and I could say the same about every others machines using gas or else. I've used some factory upgrades, some energy upgrade along with speed upgrade and muffling, but no chunk loader at all. Note : the whole system is connected to a induction multiblock who is connected to a reactor, to a boiler, and to a "steam generation tower". But I'm not using any of them, the reactor is offline and the heat is at 300 kelvin. 

#### Steps to reproduce:
I have no idea, sorry!

#### Version (make sure you are on the latest version before reporting):
Single player 1.12.2 forge 2768
MekanismGenerators-1.12.2-9.4.13.349
Mekanism-1.12.2-9.4.13.349
sodiumcraft-1.3.4
MCsokiCraftUtil-1.3.6
MekanismTools-1.12.2-9.4.13.349
GasConduits-1.12.2-1.0.0 (unused so far)
Darkhax+Hwyla-1.8.26-B41_1.12.2
VanillaFix-1.0.10-99
foamfix-0.10.2-1.12.2
5-The 5zig Mod v3.12.5 for Minecraft 1.12.2
#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
[latest.log](https://github.com/aidancbrady/Mekanism/files/2739050/latest.log)

-----
edit : I've forgot about
JAOPCA-1.12.2-2.2.8.100

**Comment by alxcool** [comment]
1 month later, I have not check if this is still an issue, or happening again. Let me know if someone what me to run some test or to close this topic.

**Comment by thiakil** [comment]
It looks like you have a yo-yo chunk loading problem. please ensure that the chunk is not loading/unloading in a tight loop, and (to be safest) that the reactor is not crossing a chunk border.

If you can cause it to happen in a small test world, feel free to upload it
