### ISSUE TITLE
Digital miner, is anything really going to be fixed?

### ISSUE THREAD

**Issue by Andresian** [aidancbrady/Mekanism#5247]
#### Issue description:
Digital miner keeps disappearing even when being in center of a chunk and that chunk being loaded.
THE most simple fix would be making it one block machine and thats literally it.

#### Steps to reproduce:
1. Install clean forge with only mekanism
2. Place digital miner
3. Fly far away and back and see dig and see absence of digital miner.

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.5.2796
**Mekanism: 9.4.13.349
**Other relevant version: None

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
Its not (nothing appears there)

**Comment by Skar78** [comment]
Playing Enigmatica 2 and noticed the Digital Miner is not shown as icon in JEI or on the belt - blames ressource pack first but thats also with vanilla. When placed its rendered however.

However makes me wonder if in your case the Miner is really gone or just not rendered?

**Comment by brachy84** [comment]
Same problem but atomic dissassembler, jetpack and some other stuff disapears to

**Comment by thiakil** [comment]
Both of these issues have pre-existing github issues.

And no, we're not going to just make it a single block magic machine.

**Comment by ate0ate** [comment]
Please never make it a single block lol. I think the model is one of my favorites. The old model used to look like an imposing silver-backed gorilla. The new model toned that down a little, but its still great.
