### ISSUE TITLE
Atomic disassembler / Energy cubes are invisible

### ISSUE THREAD

**Issue by Noahboy007** [aidancbrady/Mekanism#5248]
Issue description:
The atomic disassembler and all tiers of energy cubes are invisible.

Steps to reproduce:
1. As soon as the game starts these items don't render while being held and can't be seen in the world.
Durability bars are the only way to know where the items are in my inventory. The items are still functional.

Version:
Forge: 14.23.5.2807
Mekanism: 9.4.13.349

**Comment by Mikotochan** [comment]
You sure are the only one who ever encountered this bug! You are a genius for discovering it!
Please do ignore these however
https://github.com/aidancbrady/Mekanism/issues/5205
https://github.com/aidancbrady/Mekanism/issues/5215
https://github.com/aidancbrady/Mekanism/issues/5216
https://github.com/aidancbrady/Mekanism/issues/5225
https://github.com/aidancbrady/Mekanism/issues/5237
