### ISSUE TITLE
server crash mekanism 1.12.2

### ISSUE THREAD

**Issue by Nbgreen** [aidancbrady/Mekanism#5252]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

server crash caused by mekanism

#### Steps to reproduce:

N/A

#### Version (make sure you are on the latest version before reporting):

**Forge:** 14.23.5.2768
**Mekanism:** 1.12.2-9.4.13.349
**Other relevant version:** 
 **Sponge** 1.12.2-2768-7.15-rc3513

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://paste.dimdev.org/orilefeqoh.sql

**Comment by MonstahGames** [comment]
Having this issue on Lapito's aswell
