### ISSUE TITLE
[1.12.2] when i'm standing on charging pad minecraft is crashing.

### ISSUE THREAD

**Issue by EskimsOOn** [aidancbrady/Mekanism#5255]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When I'm standing on chraging pad for Robit, minecraft is crashing. I'm playing on my prive server.

#### Version:
**Forge:14.23.5.2768** 
**Mekanism:9.4.13.349** 
[crash-2019-01-16_19.20.16-client.txt](https://github.com/aidancbrady/Mekanism/files/2765597/crash-2019-01-16_19.20.16-client.txt)
[latest.log](https://github.com/aidancbrady/Mekanism/files/2765599/latest.log)

**Comment by thiakil** [comment]
Some mod is not registering data manager properties properly, or you have a difference of mods between server/client. You'll need to remove mods one my one until it stops.
