### ISSUE TITLE
[Crash] At landing with jetpack in hover mode the game crashed, can't load again.

### ISSUE THREAD

**Issue by Bellwar** [aidancbrady/Mekanism#5259]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. Go into hole 1x1x2 (in a wall), with jetpack on using space
2. After getting in press shift to land.
3. Game crashes.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2796
**Mekanism:** 9.4.13.349
**Other relevant version:** atm3 Lite 3.0.3

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[pastebin](https://pastebin.com/TVPDydd5)

**Comment by thiakil** [comment]
Can you please test with the latest release to see if it was resolved?

**Comment by Bellwar** [comment]
I really don't think, I can. I resolved it buy removing it from inventory. And never came across it again even after testing again I think. So, it is not easily replicatable.

**Comment by thiakil** [comment]
Alrighty. Give us a ping if it does happen again, then :)
