### ISSUE TITLE
Gas shown in JEI recipes does not show its amount

### ISSUE THREAD

**Issue by Snownee** [aidancbrady/Mekanism#5267]
#### Issue description:

Gas shown in JEI recipes does not show its amount. It should help people calculating cost and profit.

I wonder if there is any reason to add [this](https://github.com/aidancbrady/Mekanism/blob/3e469fb40a2a086527cf14dbe9ba709f708a9bca/src/main/java/mekanism/client/jei/BaseRecipeCategory.java#L163)?

**Comment by Darkosto** [comment]
This would be an awesome addition. I've had trouble knowing exactly how much I'm going to need ahead of time.

**Comment by thiakil** [comment]
I honesly don't know why that was added. Perhaps because some of the infos aren't correct when supplied to JEI. I've done some changes locally to show them, but I'll eat my hat if I _don't_ miss an incorrect display somewhere haha
