### ISSUE TITLE
Machines aren't being dropped after broken

### ISSUE THREAD

**Issue by Diamond45123** [aidancbrady/Mekanism#5272]
#### Issue description:
Well, the title says it. I try breaking any machine like metallargic infuser in my modpack, and it doesn't drop. The Configurator works but i want it work using my pickaxe.

#### Steps to reproduce:
1. idk
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2808
**Mekanism:** 9.4.13.349
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
More info needed. Reproduce with just Mekanism & Forge

**Comment by Diamond45123** [comment]
It turned out it was some kind of weird conflict with Extreme Energy Mod
