### ISSUE TITLE
Opaque pipe rendering still rendering items inside of the pipes

### ISSUE THREAD

**Issue by CraftalotReloaded** [aidancbrady/Mekanism#5274]
In the screenshot you can see bits of charcoal clip through the opaque logistical pipe which means that things are still rendered within opaque pipes which is a huge waste of performance: https://cdn.discordapp.com/attachments/369154823049969664/542792210849202197/unknown.png
Forge: 1.12.2forge-14.23.5.2808
Mekanism: 1.12.2-9.4.13.349

**Comment by thiakil** [comment]
Are you able to reproduce this with just forge and Mekanism? Based on how the rendering works, I'm not sure how this could happen (the method that does the rendering nopes out right at the beginning if its set to opaque transmitters)

**Comment by CraftalotReloaded** [comment]
Seems like this is being caused by some other mod, but there are a few other issues imma report which do stay around with only mekanism
