### ISSUE TITLE
Teleporter Not Working Right

### ISSUE THREAD

**Issue by Drac0logist** [aidancbrady/Mekanism#5285]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When I first login to my single player world my teleporter says it has no link but when i run over to my other teleporter the link becomes active and will stay active the rest of the time i play the game until I exit game then it does it all over again. I have anchor upgrade in both teleporters so it should be chuck loaded. They both also have full power,

#### Steps to reproduce:
1.Login to singleplayer world
2.Go to teleporter
3.Go to second teleporter

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2781
**Mekanism:** 1.12.2-9.4.13.349
**Other relevant version:** Enigmatica 2 Expert 1.56

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by dizzyd** [comment]
Hi @Drac0logist - I tracked down this bug and fixed it in my maint. fork: https://minecraft.curseforge.com/projects/mekanism-dz-edition You can find it in 9.4.16 of that fork. I'll be submitting a PR to the main project and hopefully they can start cutting releases again. :)

**Comment by Drac0logist** [comment]
Sweet Thank you very much
