### ISSUE TITLE
Client Crash with Evaporation Plant and Resistive Heater

### ISSUE THREAD

**Issue by Fladorius** [aidancbrady/Mekanism#5286]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Attempting to shift click a Resistive Heater into a valid Thermal Evaporation Plant multiblock crashes the game. I tested in both single player, and multiplayer while hosting a separate server locally. Both methods my client would hard crash, though on MP the server would stay running.

#### Steps to reproduce:
1. Build a valid Thermal Evaporation Plant multiblock (No valves, or liquid inside the block is required)
2. Try to shift+click a Resistive Heater in the UI screen.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2815
**Mekanism:** 9.4.13.349

**Other relevant version:** 
These mods are in the test profile crash report, but are not necessary to reproduce the issue. With only the Mekanism and Forge versions above I can reproduce the issue.
MekanismGenerators 9.4.13.349.
MekanismTools 9.4.13.349
Better Builder's Wands 0.11.1 rev 245
jei 4.13.1.225

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]
Single Player Crash log https://pastebin.com/amLdf3Ak

**Comment by dizzyd** [comment]
Hi @Fladorius - I believe this has been fixed in 4b084e3a37cccb9296854b53b22305c102d1b8a7, back in June of last year. Obviously, it hasn't been released yet. :) 

As an interim fix, you might try my fork here: https://minecraft.curseforge.com/projects/mekanism-dz-edition which will incorporate that fix in 9.4.16 later today.

**Comment by Fladorius** [comment]
Just got around to testing your build dizzyd. The crash was fixed in 9.4.16, thanks.
