### ISSUE TITLE
Some textures are larger than they need to be

### ISSUE THREAD

**Issue by GreatestFool** [aidancbrady/Mekanism#5289]
Some [textures are way to large](http://i.imgur.com/KhSch6I.png) ([alternate version with gray background](http://i.imgur.com/jthUSY0.png)), 128x128 without using even half of that size. With only vanilla it covers ~88% of the texture atlas, even with over 150 mods it covers ~35%. That in and of itself would not be an issue had it not been for the fact that some textures, generators or blocks with multiple faces are the normal contender, but I can't remember the names of every block.

Cables are 48x48, and while much to big for my liking are fine because they don't waste space in the texture atlas.

I'm pretty sure you should be able to cut down the sizes of the generators or blocks by a bit, though I don't know if there _is_ some strange reason for them being this way. I still thought I should make an issue report on it.

**Comment by thiakil** [comment]
Indeed, this is known and reported in other issues. Not a simple task though I'm afraid
