### ISSUE TITLE
Infinite Obsidian Tnt explosion

### ISSUE THREAD

**Issue by Malzum** [aidancbrady/Mekanism#5297]
#### Issue description: When placing two blocks of obsidian tnt near enough where one will detonate the 2nd, but then trigger one 1 block... it will explode infinitely. One begins the count down of the 2nd block and then the 2nd block will re-trigger the first block. It then explodes infinitely.

Tested this in creative world after it destroyed my SMP world in the Enigmatica 2.

#### Steps to reproduce:
1. Place 2 or more blocks of obsidian tnt next to each other
2.Trigger only 1 block to explode
3. Run away because infinity loop of tnt explosion begins.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2781
**Mekanism:** MekanismDz-1.12.2-9.4.18
**Other relevant version:** Modpack Engimatica 2 version 1.61

**Comment by thiakil** [comment]
`MekanismDz-` thats not this project. Not even gonna touch it.
