### ISSUE TITLE
Where is Icon and Tools ???

### ISSUE THREAD

**Issue by Apollon-Theos** [aidancbrady/Mekanism#5299]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
In game not show FlameThrower, and icons in toolbar, wear and JEI
![mekanosm-9 6 0](https://user-images.githubusercontent.com/46534073/54085888-0fa07a80-4354-11e9-92d3-a84a65098021.jpg)

#### Steps to reproduce:
1. play a saved game from previous version
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2814
**Mekanism:**  9.6.0 (today downloaded)
**Other relevant version:**  JEI .268

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
Use the search. #5205

**Comment by Apollon-Theos** [comment]
"Search" is big power, but I test fork of Mekanism, and this fork don't have any problem with render without any changes in forge configuration.
Your team make big changes (9.**4**.xx -> 9.**6**.0) and I hope this problem are solved.
Fork have their bugs ....

**Comment by ate0ate** [comment]
#5282 actually does fix this issue and builds with it work well.

**Comment by thiakil** [comment]
Except it actually causes #5293 to happen again, so no that PR is not really a solution.

> Your team make big changes (9.4.xx -> 9.6.0)

This is largely because of said fork using the same version numbers. I know how to fix it properly, but that requires a fair amount of work on each and every one of those 'missing' item models
