### ISSUE TITLE
Crash on Loading

### ISSUE THREAD

**Issue by bobrob2004** [aidancbrady/Mekanism#5310]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Minecraft crashes upon loading.  I have no other mods installed, only Mekanism.  I've tried downgrading Forge, but it crashes on all versions that I've tried (forge-14.23.5.2815 - forge-14.23.5.2821).

#### Steps to reproduce:
1. Create new profile.  
2. Install only Mekanism.
3. Load game.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2821
**Mekanism:** 1.12.2-9.6.3.355
**Other relevant version:** Minecraft 1.12.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/CfEbrRJm

**Comment by TheSnowyChickens** [comment]
Same:

https://paste.dimdev.org/betejaqewi.mccrash

**Comment by thiakil** [comment]
Doh! sorry about that

**Comment by thiakil** [comment]
https://minecraft.curseforge.com/projects/mekanism/files/2688272 should work
