### ISSUE TITLE
Ore Dictionary Standardizer machine

### ISSUE THREAD

**Issue by Greylocke** [aidancbrady/Mekanism#796]
I'd like to see a new "Dictionary Standarizer" machine that would take similar items as defined in the ore dictionary and "standardize" them to a chosen item.

Piping items through this machine would have the effect of synchronizing all the similar ores that are created by the various mods, saving a lot of storage space and confusion.

For example, I could build a Standardizer and set it so that all the copper ingots from Tinker's Construct, Thermal Expansion and Basic Components are standarzied to Mekanism copper ingots. As I piped ingots through the Standardizer, they would enter as the copper from the various mods, but exit as Mekanism copper.

**Comment by aidancbrady** [comment]
I am now starting work on this.

**Comment by aidancbrady** [comment]
Okay, so the plan is to have a filter-based system like the Digital Miner.  Operations will be instantaneous - put an ore in the left slot, it will be converted right then to whatever result is configured by the filters.  Within the filter you will be able to choose which version of the ore you want to be standardized by the machine.

**Comment by aidancbrady** [comment]
This is now complete.
